### ISSUE TITLE
Assets module's AssetId cannot be used as constant

### ISSUE THREAD

**Issue by GopherJ** [paritytech/substrate#10030]
after integrating scale-info, it seems that `AssetIdOf` cannot be used as `pallet::constant` anymore because of missing `TypeInfo` trait bound

https://github.com/paritytech/substrate/blob/master/frame/assets/src/lib.rs#L194-L201

**Comment by bkchr** [comment]
> Shall we add `TypeInfo` trait bound to line

Yes that would be the correct way.
