### ISSUE TITLE
realisd.service: Failed with result 'exit-code'

### ISSUE THREAD

**Issue by rigger774** [paritytech/substrate#10041]
Hi guys,
Just installed Realis Node and faced such issues.
Can you please advice how to fix it? 
===============================================
окт 17 17:45:40 visual-System-node realis[871367]: Version: 3.0.0-dev-9556bfe-x86_64-linux-gnu
окт 17 17:45:40 visual-System-node realis[871367]:    0: sp_panic_handler::set::{{closure}}
окт 17 17:45:40 visual-System-node realis[871367]:    1: std::panicking::rust_panic_with_hook
окт 17 17:45:40 visual-System-node realis[871367]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
окт 17 17:45:40 visual-System-node realis[871367]:    2: std::panicking::begin_panic::{{closure}}
окт 17 17:45:40 visual-System-node realis[871367]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
окт 17 17:45:40 visual-System-node realis[871367]:    4: std::panicking::begin_panic
окт 17 17:45:40 visual-System-node realis[871367]:    5: tokio::runtime::blocking::shutdown::Receiver::wait
окт 17 17:45:40 visual-System-node realis[871367]:    6: tokio::runtime::blocking::pool::BlockingPool::shutdown
окт 17 17:45:40 visual-System-node realis[871367]:    7: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
окт 17 17:45:40 visual-System-node realis[871367]:    8: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
окт 17 17:45:40 visual-System-node realis[871367]:    9: jsonrpc_ws_server::server::Server::start
окт 17 17:45:40 visual-System-node realis[871367]:   10: sc_rpc_server::inner::start_ws
окт 17 17:45:40 visual-System-node realis[871367]:   11: sc_service::start_rpc_servers::{{closure}}
окт 17 17:45:40 visual-System-node realis[871367]:   12: sc_service::start_rpc_servers
окт 17 17:45:40 visual-System-node realis[871367]:   13: sc_service::builder::spawn_tasks
окт 17 17:45:40 visual-System-node realis[871367]:   14: node_cli::service::new_full
окт 17 17:45:40 visual-System-node realis[871367]:   15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
окт 17 17:45:40 visual-System-node realis[871367]:   16: tokio::park::thread::CachedParkThread::block_on
окт 17 17:45:40 visual-System-node realis[871367]:   17: tokio::runtime::thread_pool::ThreadPool::block_on
окт 17 17:45:40 visual-System-node realis[871367]:   18: tokio::runtime::Runtime::block_on
окт 17 17:45:40 visual-System-node realis[871367]:   19: sc_cli::runner::Runner<C>::run_node_until_exit
окт 17 17:45:40 visual-System-node realis[871367]:   20: node_cli::command::run
окт 17 17:45:40 visual-System-node realis[871367]:   21: realis::main
окт 17 17:45:40 visual-System-node realis[871367]:   22: std::sys_common::backtrace::__rust_begin_short_backtrace
окт 17 17:45:40 visual-System-node realis[871367]:   23: std::rt::lang_start::{{closure}}
окт 17 17:45:40 visual-System-node realis[871367]:   24: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
окт 17 17:45:40 visual-System-node realis[871367]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
окт 17 17:45:40 visual-System-node realis[871367]:       std::panicking::try::do_call
окт 17 17:45:40 visual-System-node realis[871367]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
окт 17 17:45:40 visual-System-node realis[871367]:       std::panicking::try
окт 17 17:45:40 visual-System-node realis[871367]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
окт 17 17:45:40 visual-System-node realis[871367]:       std::panic::catch_unwind
окт 17 17:45:40 visual-System-node realis[871367]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
окт 17 17:45:40 visual-System-node realis[871367]:       std::rt::lang_start_internal::{{closure}}
окт 17 17:45:40 visual-System-node realis[871367]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
окт 17 17:45:40 visual-System-node realis[871367]:       std::panicking::try::do_call
окт 17 17:45:40 visual-System-node realis[871367]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
окт 17 17:45:40 visual-System-node realis[871367]:       std::panicking::try
окт 17 17:45:40 visual-System-node realis[871367]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
окт 17 17:45:40 visual-System-node realis[871367]:       std::panic::catch_unwind
окт 17 17:45:40 visual-System-node systemd[1]: realisd.service: Main process exited, code=exited, status=1/FAILURE
окт 17 17:45:40 visual-System-node systemd[**1]: realisd.service: Failed with result 'exit-code'.
окт 17 17:45:43 visual-System-node systemd[1]: realisd.service: Scheduled restart job, restart counter is at 196.
окт 17 17:45:43 visual-System-node systemd[1]: Stopped Realis Node.
окт 17 17:45:43 visual-System-node systemd[1]: Started Realis Node.

**Comment by bkchr** [comment]
Wrong repo, please report to the repo of the chain you are using.
