### ISSUE TITLE
Depricate and remove GitHub Wiki

### ISSUE THREAD

**Issue by nuke-web3** [paritytech/substrate#10052]
The DevHub [now contains](https://github.com/substrate-developer-hub/substrate-docs/issues/105) all the content that is on the Substrate GitHub Wiki - can I go ahead and ***delete everything*** but the [top level page](https://github.com/paritytech/substrate/wiki) that redirects to our Docs?

Alternatively we can remove the Wiki feature for this repo completely

Note: I can go ahead and remove the pages and close the issue, no PR or other approval flow is required. If we want to turn off the wiki, an admin must do this. 
Please voice any objections/opinions here.

**Comment by bkchr** [comment]
Yeah let's do it.
