### ISSUE TITLE
Fix docker related problems

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate#10051]
Originally by @koslib [here](https://github.com/substrate-developer-hub/substrate-node-template/issues/236#issuecomment-945587897)  :

> Most of the links posted above also contain non functional manifests. 
> 
> Example 1: this link https://github.com/paritytech/substrate/blob/master/bin/node-template/docker-compose.yml results in a path error.
> 
> Example 2: this link https://github.com/paritytech/substrate/tree/master/docker indicates this as an option
> ```
> docker run --rm -it parity/substrate node-template --version
> ```
> however this spits back 
> ```
> ❯ docker run --rm -it parity/substrate node-template --version
> error: Found argument 'node-template' which wasn't expected, or isn't valid in this context
> ```
> 
> That's why I think a general revamp and cleanup of all docker-related examples is needed. It's confusing for a starter.

**Comment by koslib** [comment]
@chevdor thanks for the proposed solution, but it doesn't seem to work at least out of the box either. 

When building the `node-template` image from scratch (to be specific, this: https://github.com/paritytech/substrate/tree/master/bin/node-template)

I still get errors
```
ERROR: for dev  Cannot create container for service dev: invalid mount config for type "bind": bind source path does not exist: <redacted path>/substrate/bin/node-template/.local
```

I'm suspecting that the `.local/` path it's trying to find has something to do with rust's compilation, but I don't want to do anything outside of Docker. Am I wrong? Or generally, all ideas welcome.

**Comment by chevdor** [comment]
It sounds like you'd need to creater this folder that does not exist.
For this kind of issue I suggest testing first without binding any path (so no `-v` flag).
It help knowing if that works at that point or not.
You may also need to get inspired from https://github.com/paritytech/substrate/blob/master/docker/substrate_builder.Dockerfile#L24-L26

**Comment by bkchr** [comment]
Any update on this? Can this be closed?

**Comment by TriplEight** [comment]
Just realized that the problem was on the surface:

`docker run --rm -it parity/substrate node-template --version` errors out with an unexpected argument `node-template`.
It expects the flags right away as if you'd run a binary.

To specify which binary are you calling, you should override the entrypoint script i.e. adding `--entrypoint [new_command]` to `docker call.
