### ISSUE TITLE
Assets Genesis Config

### ISSUE THREAD

**Issue by apopiak** [paritytech/substrate#10067]
It would be useful to be able to create assets and set endowed accounts at genesis for the assets pallet (similar to what the balances pallet allows), e.g. for setting up testnets (like statemint-dev).

**Comment by dharjeezy** [comment]
Picking this up

**Comment by dharjeezy** [comment]
<img width="1440" alt="Screenshot 2021-11-10 at 21 54 28" src="https://user-images.githubusercontent.com/11888724/141192004-5acdab55-e0f6-424a-9aa8-3a38669787e2.png">
Seems to me, this has already been done according to the screenshot here @apopiak

**Comment by apopiak** [comment]
Huh, you're right, my bad.
