### ISSUE TITLE
substrate: will snapshot be supported?

### ISSUE THREAD

**Issue by AmadeusGB** [paritytech/substrate#10098]
I noticed that substrate4.0.0-dev has 3s out of blocks by default, which will increase the storage requirements. 

Therefore, is it possible to provide snapshot feature to traverse MPT to save previous blocks safely and then delete some data, thus reducing the storage pressure on the server?

**Comment by AmadeusGB** [comment]
@bkchr 
How should I run non-archive nodes, is there some tutorials or links I can refer to?

Thanks

**Comment by AmadeusGB** [comment]
If there is a problem of not being able to get out of the block (error: unexpected epoch change), will the full node not work properly?

**Comment by bkchr** [comment]
Not sure what you mean. If you have problems, please go to https://github.com/paritytech/subport

**Comment by AmadeusGB** [comment]
Ok, thanks a lot!

I'm looking for ways to preserve data on the substrate chain so that I can recover from a disaster state. For example: https://polkashots.io/getting-started
