### ISSUE TITLE
Runtime_update using compact version does not work

### ISSUE THREAD

**Issue by Yithis** [paritytech/substrate#10120]
I tried to perform a runtime update following [this tutorial](https://docs.substrate.io/tutorials/v3/forkless-upgrades/) from branch "polkadot-v0.9.9" to "polkadot-v0.9.12", but due to changes between branches it is not simply possible. Every attempt ends up with a chain crash with the following error: 
![Screenshot from 2021-10-29 14-41-30](https://user-images.githubusercontent.com/22166107/139436217-1c4c8921-4e7c-4238-a61b-93202737482f.png)
It is connected to changes introduced here [9391](https://github.com/paritytech/substrate/pull/9391), where the function `secp256k1_ecdsa_recover_compressed` got a newer version.

I managed to overcome this problem by using "node_runtime.wasm" instead of "node_runtime.compact.wasm". Should I understand it is a bug or the tutorial is inaccurate? Why does "wasm-gc" remove this function as unused?

**Comment by bkchr** [comment]
If there are host functions being added, you can not upgrade without updating the client before.

**Comment by Yithis** [comment]
How to check if there were any changes in host functions? Is there any documentations about current list of all host functions?
