### ISSUE TITLE
On the Feasibility and Viability of Sharding and Side-Chains on Substrate

### ISSUE THREAD

**Issue by gokulsan** [paritytech/substrate#10147]
Hello Team, 

I am new to polkadot protocol and substrate framework. Is it possible to implement sharding and shaded side chains similar to Ethereum 2.0. architecture on a new chain built on substrate framework. Would it be an unnecessary overhead in context of para-chains and para-threads?

**Comment by burdges** [comment]
Parachains/parathreads already are "cut & choose roll ups".  They provide shared security under byzantine assumptions, as opposed to zk rollups which provide shared security under cryptographic assumptions.  They require far less total CPU time than zk rollups, and execute in a more conventional computational model, but cost more bandwidth, although not necessarily that much more bandwidth if you ask the zk rollup to be live and decentralized. 

We've discussed chain that demand even less CPU time, but provide less security, but realistically some bespoke single hop L2 designs work better.

**Comment by gokulsan** [comment]
Thank you so much @burdges for the detailed response. It is quite interesting to know that parachains and parathreads are essentially similar to rollups. In this context, are these parachains and parathreads talking directly to the runtimes or do we need specific pallets to verify and aggregate the rollups into the relay chain. Sorry if my question is confusing or out of context.

**Comment by burdges** [comment]
We block finality upon approvals, meaning we inherently rollup anything our relay chain finalizes, so regular parachains do not do anything special.  We do have some parachains that implement strange consensus rules like bridges, and thus do not capture their whole state of course.  

As for checking finality from other consensus protocols, we'll implement finality proofs eventually under beefy, but polkadot itself would use the aggregated public key system in development, not the merkle proof sampling system designed to do proof to ethereum.

**Comment by gokulsan** [comment]
Thank you so much for the guidance on parachain types. It is also exciting to see the roadmap for finality proofs on beefy. I will work further on this structure.
