### ISSUE TITLE
Cannot override static Pays::No with PostInfo

### ISSUE THREAD

**Issue by shelbyd** [paritytech/substrate#10143]
We want users to be able to bootstrap their accounts on our chain. To do that, they need to submit an extrinsic with no balance. We need to have a static `Pays::No` on that extrinsic definition to allow Substrate to accept the extrinsic.

We'd like to include a transaction fee once the user has a balance. We already have code that returns `Pays::Yes` in the right cases. But the PostInfo Pays::Yes does not override the static Pays::No (as in the user doesn't pay a transaction fee).

Can this be changed? Is there another way to accomplish this same behavior without reimplementing the TXN fee logic?

**Comment by thiolliere** [comment]
Note that if you have an extrinsic which is written as `Pays::No` upfront, then the extrinsic is free, then it must have some code to prevent the extrinsic to go into the block in case the extrinsic is not legit. you can use [SignedExtension::validate](https://paritytech.github.io/substrate/master/sp_runtime/traits/trait.SignedExtension.html#method.validate) to implement this constraint.

If you accept any extrinsic in the block. Then people can spam the chain for free and make all blocks full.

But IMO you should use the ValidateUnsigned mecanism, similar to what people do with `claim` on polkadot: https://github.com/paritytech/polkadot/blob/bbe8b114f0ccd7bc83b95dd17c1a4c87a2a68667/runtime/common/src/claims.rs#L466-L514

**Comment by thiolliere** [comment]
In general I don't think we need something else than a refund mecanism here, the usual process is charge upfront for the worst case then refund for the actual case.

Personally I don't think we should support a pay afterward mecanism.

**Comment by shawntabrizi** [comment]
Pays::No -> Pays::Yes is not a supported scenario, just like having the fees of a tx increase after the tx has already started to process.

Of course within the dispatch logic, you can manipulate balances to take more fees or reserve a balance, but the point of the fee check is to check before we even process the tx that the user would have enough to pay the fee.

For any kind of free tx which targets a user with no balance, you will need to do a SignedExtension verification or a `validate_unsigned` verification, to ensure that this tx cannot be abused by malicious parties.

Once you populate a user with some balance, you can of course take it from them within the same dispatch logic or have them pay fees in subsequent extrinsics, but you should not be mixing up the concept of pre-dispatch fee checking with other stuff.

**Comment by bernardoaraujor** [comment]
@shelbyd can't you implement a separate `Pays::No` extrinsic (with proper spam-prevention mechanisms) with the sole purpose of allowing the user to bootstrap their account?

The downside is the extra step that you'd introduce to the UX (although it could potentially be abstracted away by the Front-end implementation).

The upside is that the other extrinsics would go on being `Pays::Yes` without overlapping with the bootstrap procedure, and without unnecessarily exposing the chain to spam and DoS attacks.

**Comment by thiolliere** [comment]
I'm not sure it makes sense to support `Pays::No -> Pays::Yes`, I don't see real a usecase, we should always charge upfront the worst case, so implementing this goes against our principles AFAICT.

For this reason I think we should close it. But we can reopen if there is disagreement and further discussion.
