### ISSUE TITLE
pallet-balances: should slash be able to kill an account.

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#10175]
Inside the slashing there is this code which confused me: https://github.com/paritytech/substrate/blob/e40710abffde7dffcd30eb51756a7a1e9eb0e249/frame/balances/src/lib.rs#L1567-L1572

When we slash from the free balances of an account we don't care about the ED and allow to kill the account, but on the second attempt when we slash from both free and reserved balance, then now we care about the ED and don't allow to kill the account.

I think there is something inconsistent here.

**Comment by burdges** [comment]
We'd maybe want the account to exist to simplify reverting slashes.  If so, we'd exclude the ED from staking operations though, so not sure which turns out simpler.

**Comment by gavofyork** [comment]
slash cannot kill an account without breaking the references system. so no.

**Comment by thiolliere** [comment]
if slash happen in a context where it isn't required to live then it can kill an account.
I finally understood the code, no issue there
