### ISSUE TITLE
Can't install subkey

### ISSUE THREAD

**Issue by sashman-jaspin** [paritytech/substrate#10185]
As per the documentation to install standalone subkey with cargo : 

> curl https://getsubstrate.io -sSf | bash -s -- --fast
> cargo install --force subkey --git https://github.com/paritytech/substrate --version 2.0.1 --locked

Updating git repository `https://github.com/paritytech/substrate`
error: could not find `subkey` in https://github.com/paritytech/substrate with version `=2.0.1`

What am I missing here?

**Comment by bkchr** [comment]
Works for me. No problem

**Comment by Benzales** [comment]
Yeah. It's not working for me either.

**Comment by bkchr** [comment]
@Benzales do you get the same error? What rustc are you using?

**Comment by dutterbutter** [comment]
@Benzales this worked for me for future reference:
```
cargo install --force subkey --git https://github.com/paritytech/substrate --tag=v3.0.0 --locked
```

**Comment by Ethereumx** [comment]
@dutterbutter would you please explain why the tag is set,,?
