### ISSUE TITLE
Move pallet-staking's counters to `CountedMap`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#10180]
Similar to https://github.com/paritytech/substrate/pull/10179, no migration should be needed since we used a backward compatible name,

**Comment by ayevbeosa** [comment]
Good day, I am interested in picking this up but I have been unable to find the counters in pallet-staking. Could you please help?

**Comment by ayevbeosa** [comment]
Nvm found them.

**Comment by KiChjang** [comment]
Fixed in #10233.
