### ISSUE TITLE
Building substrate on your Apple M1 machine

### ISSUE THREAD

**Issue by aliXsed** [paritytech/substrate#10203]
I know Apple M1 as a native host is not yet supported by substrate. However I am creating this issue for those like me who happen to have an apple silicon host and just need to be able to compile and run substrate on their machine. A similar issue was created [here](https://github.com/substrate-developer-hub/substrate-node-template/issues/179) but it was about one of the earlier issues with wasmtime in specific which seems to have been resolved by recent wasmtime packages. My own issue was presenting itself as follows: 
> libp2p-core failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): Bad CPU type in executable

The workaround that worked for me is an outside the box solution! Why building for the `aarch64-apple-darwin` target when you can build for the `x86_64-apple-darwin` target. When Apple Rosetta 2 is installed, you can directly execute the binaries for the previous intel based architectures on your apple machine. You may not get the highest performance but it works smoothly. So What I did was:

`softwareupdate —install-rosetta`

`rustup target add x86_64-apple-darwin`
`rustup set default-host x86_64-apple-darwin`
`rustup toolchain add stable-x86_64-apple-darwin` (possibly with --force-non-host)
`rustup toolchain add nightly-x86_64-apple-darwin` (possibly with --force-non-host)
`rustup default stable-x86_64-apple-darwin`
`rustup target add wasm32-unknown-unknown --toolchain nightly`

Has anyone got a better solution or workaround?

**Comment by xlc** [comment]
No idea what do you you mean. I've been compiling with Apple M1 natively for almost a year.

**Comment by bkchr** [comment]
As @xlc said it works + this is an upstream "bug" https://github.com/stepancheg/rust-protobuf/pull/556

You can just install protoc.

**Comment by aliXsed** [comment]
@xlc @bkchr Thank you for your comments. Looks like either installing Rosetta 2 itself was the key or I had observed a temporary issue. Today I updated my rust and did a native build and it worked. @xlc you may have had Rosetta 2 installed and that's why you never noticed it, so people with a fresh machine might be more prone to bump into this. By the way, if it's been stable for a while would you @bkchr consider updating the warning information about Apple M1 builds here: https://docs.substrate.io/v3/getting-started/installation/?

**Comment by gavofyork** [comment]
I also just ran into this fwiw. @bkchr @xlc

**Comment by gavofyork** [comment]
```
error: failed to run custom build command for `libp2p-core v0.29.0`

Caused by:
  process didn't exit successfully: `/Users/gav/Core/polkadot/target/release/build/libp2p-core-c882693ae1cc05a4/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): Bad CPU type in executable (os error 86)" }', /Users/gav/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.29.0/build.rs:22:64
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by xlc** [comment]
Try make sure everything is native including terminal and homebrew. Use `arch` to ensure the terminal is not running under Rosetta

**Comment by gavofyork** [comment]
This is on a completely clean 14" MBP - haven't knowingly touched Rosetta.

**Comment by gavofyork** [comment]
(`arch` returns `arm64` fwiw)

**Comment by arkpar** [comment]
Also ran into this. Just install rosetta2 with `softwareupdate —install-rosetta`. It is only needed to run the `protoc` tool during the build. The build itself and the target binaries should be `arm64`

**Comment by bkchr** [comment]
> @xlc @bkchr Thank you for your comments. Looks like either installing Rosetta 2 itself was the key or I had observed a temporary issue. Today I updated my rust and did a native build and it worked. @xlc you may have had Rosetta 2 installed and that's why you never noticed it, so people with a fresh machine might be more prone to bump into this. By the way, if it's been stable for a while would you @bkchr consider updating the warning information about Apple M1 builds here: https://docs.substrate.io/v3/getting-started/installation/?

Would be nice if you do this. You can just open a pr from the wiki page :)

**Comment by aliXsed** [comment]
@bkchr Can you please point me to the github repository which keeps the content for doc.substrate.io? The substrate wiki has not got only links to that website.

**Comment by shawntabrizi** [comment]
@aliXsed there should be an edit button on that page which takes you here:

https://github.com/substrate-developer-hub/substrate-docs/edit/main/v3/docs/01-getting-started/c-installation/index.mdx

Repo: https://github.com/substrate-developer-hub/substrate-docs/
