### ISSUE TITLE
Thread 'http.worker00' panicked at 'Expected always-serializable type; qed: Error("u128 is not supported", line: 0, column: 0)', /home/bun/substrate-node-template/pallets/kitties/rpc/src/lib.rs:47

### ISSUE THREAD

**Issue by VegeBun-csj** [paritytech/substrate#10210]
Version: 3.0.0-afdc867-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/4e282795d7d1d28a4c6c1c6521045ae2b59f3519/library/std/src/panicking.rs:627:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/4e282795d7d1d28a4c6c1c6521045ae2b59f3519/library/std/src/panicking.rs:520:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/4e282795d7d1d28a4c6c1c6521045ae2b59f3519/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/4e282795d7d1d28a4c6c1c6521045ae2b59f3519/library/std/src/panicking.rs:516:5
   5: core::panicking::panic_fmt
             at /rustc/4e282795d7d1d28a4c6c1c6521045ae2b59f3519/library/core/src/panicking.rs:93:14
   6: core::result::unwrap_failed
             at /rustc/4e282795d7d1d28a4c6c1c6521045ae2b59f3519/library/core/src/result.rs:1599:5
   7: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   8: <futures::future::either::Either<A,B> as futures::future::Future>::poll
   9: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  10: futures::future::chain::Chain<A,B,C>::poll
  11: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  12: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  13: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  14: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  15: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  16: <jsonrpc_http_server::handler::RpcHandler<M,S> as futures::future::Future>::poll
  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  18: <hyper::server::conn::Connection<I,S,E> as futures::future::Future>::poll
  19: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  20: futures::future::chain::Chain<A,B,C>::poll
  21: futures::task_impl::std::set
  22: futures::task_impl::Spawn<T>::poll_future_notify
  23: tokio_threadpool::task::Task::run
  24: tokio_threadpool::worker::Worker::run_task
  25: tokio_threadpool::worker::Worker::run
  26: tokio_timer::clock::clock::with_default
  27: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  28: std::thread::local::LocalKey<T>::with
  29: std::thread::local::LocalKey<T>::with
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4e282795d7d1d28a4c6c1c6521045ae2b59f3519/library/alloc/src/boxed.rs:1572:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4e282795d7d1d28a4c6c1c6521045ae2b59f3519/library/alloc/src/boxed.rs:1572:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/4e282795d7d1d28a4c6c1c6521045ae2b59f3519/library/std/src/sys/unix/thread.rs:91:17
  33: start_thread
  34: __GI___clone

Thread 'http.worker00' panicked at 'Expected always-serializable type; qed: Error("u128 is not supported", line: 0, column: 0)', /home/bun/substrate-node-template/pallets/kitties/rpc/src/lib.rs:47

This is a bug. Please report it at:

        support.anonymous.an

**Comment by bkchr** [comment]
3.0 is not supported anymore. Please use master.

**Comment by VegeBun-csj** [comment]
OK,fine. I use NumberOrHex solve this problem. Thanks
