### ISSUE TITLE
Unify `InherentData`

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#1022]
Currently `InherentData` is defined in `sr-primitives` and will be generated by the `construct_runtime` macro. 
This is required, because `InherentData` needs to be accessible by core. We need to find a way to unify both implementations into one.

Related: #1228

**Comment by gavofyork** [comment]
@bkchr are you ok to take this on?

**Comment by bkchr** [comment]
Yeah, that is my next task on the list.

**Comment by bkchr** [comment]
Done with https://github.com/paritytech/substrate/pull/1488
