### ISSUE TITLE
client/service: refactor group param of spawn into an Enum

### ISSUE THREAD

**Issue by ordian** [paritytech/substrate#10241]
Something like:

```
enum GroupName {
    Default,
    Specific(&'static str),
}

impl From<Option<&'static str>> for GroupName {
    fn from(name: Option<&'static str>) -> Self {
        match name { Some(name) => Self::Specific(name), None => Self::Default }
    }
}

impl From<&'static str> for GroupName {
    fn from(name: &'static str) -> Self {
        Self::Specific(name)
    }
}
```

would have been super cool :P 

Because then you could write:

`pub fn spawn(.., group: impl Into<GroupName>, ..)`

And stuff like `spawn(.., "name", ..)` or `spawn(.., None, ..)` should work :P 

This would maybe be the icing on the top, but no requirement.

_Originally posted by @bkchr in https://github.com/paritytech/substrate/pull/10196#discussion_r747370788_

**Comment by dharjeezy** [comment]
Picking this up. @ordian

**Comment by ordian** [comment]
Note that this would be a breaking change and you'd have to create a companion for polkadot and cumulus.
The process is described [here](https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc#updating-polkadot-as-well) and you can take a look at #10196 as an example.

**Comment by bkchr** [comment]
This will should not break any code at all, because we will provide an implementation of `From<Option<&'static str>>` and the current code uses `Some(_)`. So, it should work out of the box.

**Comment by ordian** [comment]
Ah, right. But isn't the purpose of `group: impl Into<GroupName>` that we won't use `Some(_)` explicitly? 
That can be implemented later (not as a companion).

**Comment by bkchr** [comment]
> `group: impl Into<GroupName>` that we won't use `Some(_)` explicitly?

Yes for sure, but this is mainly something to make the code look nicer. So, as you said, it can be done later :)

**Comment by dharjeezy** [comment]
@ordian can you take a look at this PR
