### ISSUE TITLE
nodes 'tokio-runtime-worker' panicked when uploaded a contract bundle 

### ISSUE THREAD

**Issue by garrettmaring** [paritytech/substrate#10260]
I have a 3-node private network with finalization that supports the contracts pallet

![Screen Shot 2021-11-13 at 12 10 21 PM](https://user-images.githubusercontent.com/8270120/141657682-2af51f1c-781c-4cc9-b4ed-931c3ab1e9be.png)

I'm building my ink! contract with the latest builder (v.15) and dependencies (3.0.0-rc6). When I upload the bundle, a signed transaction is successfully sent.

![Screen Shot 2021-11-13 at 12 11 57 PM](https://user-images.githubusercontent.com/8270120/141657731-b0e6a0a8-92d9-4912-9279-b64dd3d103dc.png)
![Screen Shot 2021-11-13 at 12 12 07 PM](https://user-images.githubusercontent.com/8270120/141657730-dcacd707-ef2f-4ece-a18c-a68d9203b218.png)

However after the first consensus begins (after uploading/instantiating my contract), my nodes panic.

![Screen Shot 2021-11-13 at 12 12 37 PM](https://user-images.githubusercontent.com/8270120/141657744-aa4f4024-5afa-4bcf-8750-d867bdce2f3f.png)

"this is a bug"

![Screen Shot 2021-11-13 at 12 14 08 PM](https://user-images.githubusercontent.com/8270120/141657757-bb24e03c-244c-4f2e-bd37-9a51530ff13b.png)

And shortly after a failure message 'Invalid' appears back in the UI.

![Screen Shot 2021-11-13 at 12 15 37 PM](https://user-images.githubusercontent.com/8270120/141657797-e740b5cc-37dc-46d5-b5f4-ae7a235f8f7c.png)

**Comment by bkchr** [comment]
Please use latest master!

**Comment by garrettmaring** [comment]
Updating my [contracts](https://github.com/paritytech/substrate-contracts-node/blob/main/runtime/src/lib.rs) node...
