### ISSUE TITLE
Update ink! test fixtures in `pallet-contracts`

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate#10274]
The `contracts` pallet test fixtures contain one of the older ink! release candidates. Recently we got a question in our public channel because someone tried to reuse code from a `contracts` pallet test, which relied on such a fixture. The code didn't work with newer ink! rc's. I'm creating this issue so that we don't forget updating the fixtures with the next stable ink! 3.0.0.

For example, in newer rc's the code [here](https://github.com/paritytech/substrate/blob/a9465729e2c5d2ef8d87ac404da27e5e10adde8a/frame/contracts/src/benchmarking/mod.rs#L2264-L2268) requires encoding only the `arg`, but not the `selector`. So instead of `let data = (selector, arg).encode();` it should be something along the lines of:
```rust
let mut arg_enc: Vec<u8> = arg.encode();
let mut data = Vec::new();
data.append(&mut selector);
data.append(&mut arg_enc);
```

**Comment by athei** [comment]
But this should yield exactly the same output and the current code is nicer to read IMHO. The encoding of an array is the array itself. Please note that a slice would prepend its length which would be a different encoding.

**Comment by cmichi** [comment]
`let data = (selector, arg).encode();` doesn't work with the latest ink! rc, I know the code above is ugly, can surely be prettyfied.

**Comment by athei** [comment]
I think the error must be somewhere else. Clone and run this repository as proof that this change cannot be the solution: https://github.com/athei/scale-test

My hunch is that whoever struggled with this error did pass in an slice or vector instead of an array @justinFrevert 

Closing this for now. Please reopen with minimal reproducer if this error persists.

**Comment by cmichi** [comment]
cc @justinFrevert
