### ISSUE TITLE
error: Could not compile `srml-support`

### ISSUE THREAD

**Issue by pkrasam** [paritytech/substrate#1028]
Tried to run through Gav demo from #Web3Summit -- curl getsubstrate.io -ssf | sh -- I am getting this error: Could not compile srml-support -- any tips on how to fix these errors?

[https://gist.github.com/pkrasam/5f5985d215bf1525c9d906457106088a](url)

**Comment by bkchr** [comment]
You need at least rust 1.30.0 that was released in Thursday.
