### ISSUE TITLE
Improve sp_io::storage::clear_prefix API to return the number of key deleted

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#10288]
Currently the api is:
https://github.com/paritytech/substrate/blob/9a00c43a1a81217548b3b7853271f07de6a6b858/primitives/io/src/lib.rs#L143-L175

So the return type KillStorageResult only return the number of keys deleted from the backend.
But sometime we also want to know the number of key deleted from the overlay. Like in https://github.com/paritytech/substrate/pull/10231 to implement CountedStorageMap::remove_all with some limit on the number of key to remove in backend.

To implement this we need to create the version 3 of clear_prefix. returning all the key removed to overlay.
Then we can implement the ability to have a limit in CountedStorageMap::remove_all similarly to StorageMap::remove_all.

**Comment by dharjeezy** [comment]
Picking this up @thiolliere

**Comment by dharjeezy** [comment]
Hello @thiolliere is version 3 of clear_prefix just going to return all the key removed from overlay or return both that of backend and overlay?

**Comment by thiolliere** [comment]
ideally I think we should return:
The number of key removed from overlay, the number of key removed from backend, and if all the keys at the prefix were removed or if there is some remaining ones. So the only information to add from current type is the number of key removed from overlay

**Comment by dharjeezy** [comment]
I just made a PR for this issue. Can you help check to see what i did @thiolliere

**Comment by thiolliere** [comment]
ah sorry I have mistaken, even if we return the number of key deleted from the overlay, the method `CountedStorageMap::remove_all` still cannot support any limit. Because some keys can be deleted from both overlay and backend and thuswe cannot update the counter correctly :-/

For example if both backend and overlay contains some key "abc", doing a clear prefix with a limit of one will delete the key from and overlay and the key from backend, and thus we would decrease the counter by 2. but actually it should be decreased only by one because the key deleted from overlay and the key deleted from backend correspond to the same key in the storage counted map.

Considering this I'm not sure implementing the new API is very useful. At least I don't have any usecase for the new API suggested in the issue.
And solving the issue about allowing `CountedStorageMap::remove_all` to have some limit similarly to `StorageMap::remove_all` would require more work.

I don't know if it worth pursuing the implementation, srroy @dharjeezy

**Comment by dharjeezy** [comment]
uhmmm... So are you saying we should scrap the implementation that i am doing currently and you'd close this issue? @thiolliere

**Comment by dharjeezy** [comment]
Should i go ahead and close my PR while you close this issue? @thiolliere

**Comment by thiolliere** [comment]
Yes I think I can close the issue, if people feel like the propose API have usecases then we can reopen.

Sorry for having mistaken.
