### ISSUE TITLE
construct_runtime to allow for cfg macro for pallets

### ISSUE THREAD

**Issue by dzmitry-lahoda** [paritytech/substrate#10286]
```rust
// Create the runtime by composing the FRAME pallets that were previously configured.
construct_runtime!(
	pub enum Runtime where
		Block = Block,
		NodeBlock = opaque::Block,
		UncheckedExtrinsic = UncheckedExtrinsic
	{
		#[cfg(feature = "develop")]
		AssetsRegistry : assets_registry::{Pallet, Call, Storage, Event<T>} = 55,
	}
);
```

why would i want it ?

- I want have single runtime, but able to make it different depending of feature gates.
- I do not want to copy paste list of other 50+ pallets in runtime

**Comment by thiolliere** [comment]
To support this we need something recursive, we first would parse the input, look to see if there is some feature gated on some items, in case there is some we would generate some code which call construct_runtime again:

So this input:
```rust
construct_runtime!(
	pub enum Runtime where Block = Block, NodeBlock = opaque::Block,	UncheckedExtrinsic = UncheckedExtrinsic
	{
		#[cfg(feature = "develop")]
		AssetsRegistry : assets_registry::{Pallet, Call, Storage, Event<T>} = 55,
		System: frame_system,
	}
);
```

Would generate:
```rust
#[cfg(feature = "develop")]
construct_runtime!(
	pub enum Runtime where Block = Block, NodeBlock = opaque::Block,	UncheckedExtrinsic = UncheckedExtrinsic
	{
		AssetsRegistry : assets_registry::{Pallet, Call, Storage, Event<T>} = 55,
		System: frame_system,
	}
);

#[cfg(not(feature = "develop"))]
construct_runtime!(
	pub enum Runtime where Block = Block, NodeBlock = opaque::Block,	UncheckedExtrinsic = UncheckedExtrinsic
	{
		AssetsRegistry : assets_registry::{Pallet, Call, Storage, Event<T>} = 55,
		System: frame_system,
	}
);
```

Which will then expand as currently because there is no longer feature gated items.

**Comment by xlc** [comment]
what happen if there are multiple feature gates?

**Comment by dzmitry-lahoda** [comment]
> Would generate:

yes, that is what i have done by hands now

> what happen if there are multiple feature gates?

I hope there will be few. initially can compile error and say that only one gate is supported

Overall, how it is possible to assemble `construct_runtime!` from several parts? Example, if one team is already parachain. And that team wants to allow other teams to put its pallets into its para chain.  May be something like this could also help teams within initial collaboration.

**Comment by gilescope** [comment]
I'd like to see this too. Then we can add the `sudo` pallet when `fast-runtime` feature of polkadot is enabled. At the moment this is the only manual code editing we have to do when testing parachains and ideally I'd like there to be no code editing at all for that.
