### ISSUE TITLE
OCW http response report IoError

### ISSUE THREAD

**Issue by kinosang** [paritytech/substrate#10299]
current on polkadot-v0.9.12 (d76f39995315ec36980908e4b99709bd14927044)

sample codes from https://github.com/jimmychu0807/substrate-offchain-worker-demo

```rust
let url = "https://api.github.com/orgs/substrate-developer-hub";

let deadline = sp_io::offchain::timestamp().add(Duration::from_millis(5_000));

let request = http::Request::get(url);

let pending = request
    .add_header("User-Agent", "SampleWorker/1.0")
    .deadline(deadline)
    .send()?;

let response = pending.try_wait(deadline)??;
```

with `https://min-api.cryptocompare.com/data/price?fsym=BTC&tsyms=USD` it works. with `https://api.github.com/orgs/substrate-developer-hub` nor `https://min-api.cryptocompare.com/data/v2/histohour?fsym=BTC&tsym=USD&limit=50` nor `https://www.google.com` nor `https://t.me/parity_technologies` it doesn't.

similar issue: https://stackoverflow.com/questions/69309980/substrate-offchain-worker-http-fetch-error

maybe the real world of http response has the same mistake as the testing one?

**Comment by kinosang** [comment]
it seems does not work with larger response. but I didn't find where's the codes.

**Comment by kinosang** [comment]
seems `HttpApi::request_start` not called, so stucked at `impl Future for HttpWorker`.

**Comment by kinosang** [comment]
seems always got Pending here

https://github.com/paritytech/substrate/blob/05a6abb9369426e862fc09fa51c544f1d03d5b71/client/offchain/src/api/http.rs#L607-L617

**Comment by kinosang** [comment]
tried with codes from #4647, still not work

**Comment by bkchr** [comment]
Did you tried to increase the timeout?

**Comment by kinosang** [comment]
@bkchr increase to 60_000 cause the request hang for 60 seconds and then deadline reached.

**Comment by kinosang** [comment]
move to 05a6abb9369426e862fc09fa51c544f1d03d5b71 still have the same issue.

**Comment by kinosang** [comment]
"solved" by creating my own HTTP runtime interface.

**Comment by bkchr** [comment]
FYI, the problem is http2. This pr https://github.com/paritytech/substrate/pull/10305 will solve your problem.

**Comment by kinosang** [comment]
@bkchr works well with #10305, but I don't think `https://min-api.cryptocompare.com/data/v2/histohour?fsym=BTC&tsym=USD&limit=50` is over http2, so seems there might be some other problem (that had already be fixed by the pr).

![image](https://user-images.githubusercontent.com/4987102/142589497-20ab4aec-d940-4432-b699-5e4f1016d44d.png)

**Comment by bkchr** [comment]
> https://min-api.cryptocompare.com/data/v2/histohour?fsym=BTC&tsym=USD&limit=50

Yes that is right, but that was working from me from the beginning. Only google and telegram failed.
