### ISSUE TITLE
Error importing block 0x9424295f8479fdf6e2d85ac5f073179777ea9d7837e2d1ba1cd37f34e17625de: Err(UnknownParent)  

### ISSUE THREAD

**Issue by Irish-bee** [paritytech/substrate#10319]
Could you please help me check this problem: half of the verification nodes on my side stopped due to network reasons, and when they were connected again, the final block did not produce a block, and reported this error. How should this situation be resolved

**Comment by bkchr** [comment]
Please open this issue in the appropriate repo that is associated to the validator you are running.
