### ISSUE TITLE
Remove weight annotation.

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#10327]
When defining calls we usually have some weight annotation:
https://github.com/paritytech/substrate/blob/541a72f9eb41678e4601593735655a5cf794bd4a/frame/system/src/lib.rs#L354-L360

I think those information are not useful:
* The base weight depend on the benchmark machine so they should be removed.
* The number of storage read and write can be useful but I believe almost nobody read them and check them, I think we should remove them.
* The complexity is infered by the weight formula: if a weight formula is `call_name(some_args.len(), foo)` then the weight is `O(some_args.len()) + O(foo)` so the notation isn't very useful.

So as some propose https://github.com/paritytech/substrate/pull/10293#issuecomment-971369191 we should remove them.
And instead when running the benchmark for a runtime we should check that the result is consistent with the implementation of the dispatchable. but only at this stage.

Any other opinion ?

**Comment by dharjeezy** [comment]
I want to pick this up. @thiolliere

**Comment by dharjeezy** [comment]
Kindly look at the PR i opened for this @thiolliere
