### ISSUE TITLE
The 'import block' command shows a large gap between the optimal block and the final block

### ISSUE THREAD

**Issue by Irish-bee** [paritytech/substrate#10354]
```
./substrate export-blocks --chain main --to 318450 shuju --base-path db1/ --pruning=archive
```
```
./substarte import-blocks --chain main shuju --base-path db-cp --pruning=archive
```
when i run my local node with `./substratre --chain main --base-path db-cp --pruning=archive`,
and there are my log:
```
 〽️ Prometheus server started at 127.0.0.1:9615    
Nov 24 01:26:22.339  INFO Listening for new connections on 127.0.0.1:9944.    
Nov 24 01:26:27.184  INFO Accepted a new tcp connection from 127.0.0.1:51642.    
Nov 24 01:26:27.340  INFO 💤 Idle (0 peers), best: #318450 (0x4fc6…b8d8), finalized #317952 (0x162d…eb7d), ⬇ 0.3kiB/s ⬆ 0.2kiB/s    
Nov 24 01:26:32.340  INFO 💤 Idle (0 peers), best: #318450 (0x4fc6…b8d8), finalized #317952 (0x162d…eb7d), ⬇ 0.2kiB/s ⬆ 0.2kiB/s    
Nov 24 01:26:37.340  INFO 💤 Idle (0 peers), best: #318450 (0x4fc6…b8d8), finalized #317952 (0x162d…eb7d), ⬇ 0 ⬆ 0    
Nov 24 01:26:42.340  INFO 💤 Idle (0 peers), best: #318450 (0x4fc6…b8d8), finalized #317952 (0x162d…eb7d), ⬇ 0.2kiB/s ⬆ 0.3kiB/s  
```

**Comment by bkchr** [comment]
What is the problem here? Were the blocks finalized before?

**Comment by Irish-bee** [comment]
> What is the problem here? Were the blocks finalized before?

I mean, using the './ substrate import block 'command, why would the height of the latest block and the final block normally be different

**Comment by Irish-bee** [comment]
> > What is the problem here? Were the blocks finalized before?
> 
> I mean, using the './ substrate import block 'command, why would the height of the best block and the final block normally be different

And, the data is exported in a normal database using the command './substrate export-blocks --chain main --to 318450 shuju --base-path db1/ --pruning=archive
'

**Comment by bkchr** [comment]
> Were the blocks finalized before?

Can you please answer this.

**Comment by transxask** [comment]
> > Were the blocks finalized before?
> 
> Can you please answer this.

Yes, the final block of the chain is higher than the best block above, I just want to export the data that already has the final block in front

**Comment by transxask** [comment]
The final block of the chain was 318,467 when I exported the data. So the expectation is that the final block here is going to be 318450 as is the best block

**Comment by bkchr** [comment]
I think there was probably just no justifications for these blocks. I think grandpa only outputs justifications on authority set changes. @andresilva should be able to answer this concretely.

However, I don't see this as such a big problem, the node would finalize when it connects to other nodes.

**Comment by Irish-bee** [comment]
> I think there was probably just no justifications for these blocks. I think grandpa only outputs justifications on authority set changes. @andresilva should be able to answer this concretely.
> 
> However, I don't see this as such a big problem, the node would finalize when it connects to other nodes.

Yes, it's not a big problem. We just want to completely derive the equal final block and the best block. This is sufficient if the data is exported for a node. Thank you！

**Comment by bkchr** [comment]
Then you need to share the db.
