### ISSUE TITLE
Unable to distinguish between identical transfers done via proxy announce.

### ISSUE THREAD

**Issue by sicco-moonbeam** [paritytech/substrate#10375]
I've encountered a bit of an interesting wrinkle. I've been working with the proxy functionality; and in my unit testing, I'm creating a serious of identical transfers.

It seems that there's no real way to "target" a specific transfer with the proxy/announced functions because what you're announcing is the call hash of the transfer, and if all the details of the transfer are identical (same target account, same amount) the hashes for these end up being identical; i.e.:

```
const transferAmount=100
const tx1=api.tx.balances.transfer(targetAddress, transferAmount);
const tx2=api.tx.balances.transfer(targetAddress, transferAmount);
api.tx.proxy.announce(sourceAddress, tx1.method.hash).signAndSend(delegate);
api.tx.proxy.announce(sourceAddress, tx2.method.hash).signAndSend(delegate);
```

results in two announcements with identical call hashes on chain.

When you then do a proxyAnnounced call, as long as enough blocks have passed, a single call dispatches ALL transfers- there's no real way to select a specific one; even if tx1 and tx2 end up in different blocks:

```
api.tx.proxy.proxyAnnounced(delegate, sourceAddress,'Any', tx1.method.toHex());
api.tx.proxy.proxyAnnounced(delegate, sourceAddress,'Any', tx2.method.toHex());
```

In this example, the proxyAnnounced of tx1 will execute the announcement made in both tx1 and tx2 because the hashes are identical. The proxyAnnounced of tx2 will fail because by that point, no unexecuted announcements are left on chain.

I find that a bit counter intuitive- imagine a scenario where I want to set up a series of regular payments of identical amounts (say daily) and I want a 7 day delay for a chance to review. I realize you could play around with the proxy block delay and make sure you execute tx1 before enough blocks for tx2 pass. But if that review is by a human, I don't think you'd want to count on human discipline and punctuality :)

Is there some way to ensure tx1 and tx2 end up with distinct hashes even when the details are the same?

**Comment by gavofyork** [comment]
> Is there some way to ensure tx1 and tx2 end up with distinct hashes even when the details are the same?

Yes. Batch them with a remark.

**Comment by gavofyork** [comment]
By the way, this would be a great question for our new Substrate StackExchange site - consider re-asking there :)
