### ISSUE TITLE
NetworkBehaviour trait is not fully implemented

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#10370]
See the review comment https://github.com/paritytech/substrate/pull/10035#discussion_r750396469 (and the other comment right below)

The `NetworkBehaviour` trait implementations presently don't always redirect the method calls to their underlying `NetworkBehaviour`s because rust-libp2p doesn't give the possibility to deconstruct a `MultiHandler`.

This means that a `cargo update` that updates libp2p could potentially break our code.

This should be solved in a short time frame.

**Comment by kpp** [comment]
That's what I came up with:

```diff
diff --git a/client/network/src/discovery.rs b/client/network/src/discovery.rs
index dc08ab57ed..93ea14ef56 100644
--- a/client/network/src/discovery.rs
+++ b/client/network/src/discovery.rs
@@ -589,13 +589,16 @@ impl NetworkBehaviour for DiscoveryBehaviour {
 
 	fn inject_connection_closed(
 		&mut self,
-		_peer_id: &PeerId,
-		_conn: &ConnectionId,
-		_endpoint: &ConnectedPoint,
+		peer_id: &PeerId,
+		conn: &ConnectionId,
+		endpoint: &ConnectedPoint,
 		_handler: <Self::ProtocolsHandler as IntoProtocolsHandler>::Handler,
 	) {
 		self.num_connections -= 1;
-		// NetworkBehaviour::inject_connection_closed on Kademlia<MemoryStore> does nothing.
+		for k in self.kademlias.values_mut() {
+			let handler = k.new_handler().into_handler(peer_id, endpoint);
+			NetworkBehaviour::inject_connection_closed(k, peer_id, conn, endpoint, handler);
+		}
 	}
 
 	fn inject_disconnected(&mut self, peer_id: &PeerId) {
@@ -689,8 +692,11 @@ impl NetworkBehaviour for DiscoveryBehaviour {
 		}
 	}
 
-	fn inject_listen_failure(&mut self, _: &Multiaddr, _: &Multiaddr, _: Self::ProtocolsHandler) {
-		// NetworkBehaviour::inject_listen_failure on Kademlia<MemoryStore> does nothing.
+	fn inject_listen_failure(&mut self, local_addr: &Multiaddr, send_back_addr: &Multiaddr, _: Self::ProtocolsHandler) {
+		for k in self.kademlias.values_mut() {
+			let handler = k.new_handler();
+			NetworkBehaviour::inject_listen_failure(k, local_addr, send_back_addr, handler);
+		}
 	}
 
 	fn inject_listener_error(&mut self, id: ListenerId, err: &(dyn std::error::Error + 'static)) {
```

@mxinden Max, is it enough or do I need to deconstruct `MultiHandler` to get `(key, KademliaHandler)` and pass in into associated inject_connection_closed by key?

**Comment by mxinden** [comment]
> @mxinden Max, is it enough or do I need to deconstruct MultiHandler to get (key, KademliaHandler) and pass in into associated inject_connection_closed by key?

Yes, that is the way to go @kpp. Can you prepare a patch for https://github.com/libp2p/rust-libp2p/?

**Comment by kpp** [comment]
Sorry, would you please elaborate?

**Comment by mxinden** [comment]
@kpp you would need to add a method to [`Multihandler`](https://github.com/libp2p/rust-libp2p/blob/master/swarm/src/protocols_handler/multi.rs) that takes `self` and returns a set of `(key, CUSTOM_HANDLER_TYPE)` pairs. For each pair in the set you can then call `NetworkBehaviour::inject_connection_closed` on the corresponding `Kademlia` behaviours in Substrate's `discovery.rs`.

**Comment by kpp** [comment]
Why should it differ from inject_listen_failure?

**Comment by tomaka** [comment]
I don't understand your questions. If you try to compile the code of your diff you will get compilation errors because of a type mismatch. When the behavior starts dialing, it turns the `KademliaHandler` into a `MultiHandler`. If the dialing fails, libp2p gives you back that `MultiHandler` and you need to turn it back into the `KademliaHandler`.

The content of `KademliaHandler` and `Kademlia::inject_*` are implementation details of `Kademlia`. This implementation of `NetworkBehaviour` is a wrapper around the `Kademlia`, and it is extremely bad if the wrapper modifies these implementation details.

**Comment by kpp** [comment]
> you will get compilation errors because of a type mismatch. 

It compiles.

> I don't understand your questions.

Do we have to split `handler` as Max said for each `inject_*` method that accepts handler as the last argument?

**Comment by tomaka** [comment]
> It compiles.

Ahh, I misread your diff. Yeah, you definitely shouldn't be calling `new_handler` in that situation.

> Do we have to split handler as Max said for each inject_* method that accepts handler as the last argument or in inject_connection_closed only?

All of them. It's part of the API contract of the `NetworkBehaviour` trait that the handler you get back is the same as the one you passed. It's actually the entire reason why the handler is passed back.

**Comment by kpp** [comment]
Thanks for clarification! Will do
