### ISSUE TITLE
Refactor `HashFor` and `HashingFor`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#10386]
This code comment explains it: 

```
// NOTE: this is a horrible choice of name, `Header` has both `type Hash` and `type Hashing`, and
// this is exactly what you would NOT expect. Should be called `HashingFor` and have a separate one
// called `HashFor`.
pub type HashFor<B> = <<B as Block>::Header as Header>::Hashing;
```

**Comment by kziemianek** [comment]
Hi, is this ready to take? Can I try ?

**Comment by bkchr** [comment]
@kziemianek yes

**Comment by kziemianek** [comment]
Great, I'll refactor it.

**Comment by kziemianek** [comment]
@kianenigma, @bkchr could You confirm that the scope of this task is to just rename mentioned type. If something more needs to be done please share more details.

**Comment by kianenigma** [comment]
rename the current one to HashingFor + make a new HashFor and add use where possible.

**Comment by kziemianek** [comment]
I'm quite busy with other stuff so unfortunately i need to give up on this for a while. If somebody else wants to take care of this task feel free to go.

**Comment by ECJ222** [comment]
Hi @kianenigma,

If you don't mind can I take this issue?

**Comment by kianenigma** [comment]
please, be my guest! 😅

**Comment by ECJ222** [comment]
> rename the current one to HashingFor + make a new HashFor and add use where possible.

Hi @kianenigma,

please could you shade more light when you mentioned: "add use where possible"

Do you mean replacing occurrences for HashFor in the codebase with the HashingFor type?
