### ISSUE TITLE
is_sufficient = true questions

### ISSUE THREAD

**Issue by girazoki** [paritytech/substrate#10417]
Hi, wanted to have some question regarding the is_sufficient = true field in pallet-assets. We are using pallet-assets for XCM-received assets, and we are creating these with is_sufficient = true because we want to avoid a failure in the usecase where someone sends a XCM message in which it deposits the asset in an account that does not have a provider. 

We would like to understand if this is the usecase thought for is_sufficient = true, or if we should change our approach.

**Comment by bkchr** [comment]
CC @apopiak

**Comment by apopiak** [comment]
Assets marked as `is_sufficient` are assets that are valuable enough that holding their minimum balance merits account existence on its own.
Just marking all assets as sufficient means that you consider any asset to merit storing which is very unlikely (and unsafe) if you allow permissionless asset creation. If you tightly control your assets and only create sufficient ones, then this can be a valid strategy AFAICT.
The question to ask yourself is: do all the assets marked `is_sufficient` really hold enough value (with their minimum balance) to store them?
If the answer is no, you will want to change your approach.

**Comment by girazoki** [comment]
We dont allow permissionless asset creation, so from that side we are good.

Thanks for the answer, indeed we will evaluate based on the question. Thanks!
