### ISSUE TITLE
On Ubuntu 18.04 (Bionic) running cargo build fails.

### ISSUE THREAD

**Issue by bruciebruce** [paritytech/substrate#1042]
I cloned the substrate master on 10/30/18 and tried the following to get past the 'old' openssl dependency:

`[patch.crates-io]
openssl = { git = 'https://github.com/kryptco/rust-openssl.git' }`

but got this:

`error: failed to run custom build command for `openssl v0.9.24`                                         
process didn't exit successfully: `/devel/substrate/target/debug/build/openssl-d6940fa3998f9474/build-script-build` (exit code: 101) --- stderr thread 'main' panicked at 'Unable to detect OpenSSL version', /home/bruce/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

then I tried this:

`[replace]
"openssl:0.9.23" = {git = 'https://github.com/kryptco/rust-openssl.git'}`

but got this:

`error: failed to run custom build command for `openssl v0.9.24`                                         
process didn't exit successfully: `/devel/substrate/target/debug/build/openssl-d6940fa3998f9474/build-script-build` (exit code: 101) --- stderr thread 'main' panicked at 'Unable to detect OpenSSL version', /home/bruce/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

and then this:

`[replace] 
"openssl:0.9.24" = {git = 'https://github.com/kryptco/rust-openssl.git'}`

but got this:

`$ cargo build
    Updating git repository `https://github.com/kryptco/rust-openssl.git`
error: no matching package for override `https://github.com/rust-lang/crates.io-index#openssl:0.9.24` found location searched: https://github.com/kryptco/rust-openssl.git
version required: = 0.9.24`

Here is my config:

`$ uname -a
Linux bruce-pc 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

` $ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic`

I see people solving the above issue so I am at a loss.
Thank you.

**Comment by bkchr** [comment]
Hey, can you tell us which version of `libssl-dev` do you have installed?

**Comment by bruciebruce** [comment]
`$ dpkg -l | grep libssl-dev`

`ii  libssl-dev:amd64   1.1.0g-2ubuntu4.1    amd64        Secure Sockets Layer toolkit - development files`

**Comment by bkchr** [comment]
@tomaka could you please update `websocket` in `libp2p` to use the version from `crates.io` that already contains your fix. This would remove the last usage of `openssl 0.9.24` in our dependencies and would also fix this issue.

**Comment by tomaka** [comment]
This should be fixed by #427
