### ISSUE TITLE
Cross-chain anonymous proxy

### ISSUE THREAD

**Issue by olanod** [paritytech/substrate#10426]
It's not uncommon for users to use the same account across different chains to for example keep track of assets in different networks in a central place or for projects to give crowdloan rewards to the same account that made the contribution in the relay-chain. 

When the user's main account is an anonymous proxy there's no way(that I'm aware of) for the user to recreate the same proxied account in the new chain potentially leading to unrecoverable funds.

A low-cost solution might be to allow the [`anonymous`](https://github.com/paritytech/substrate/blob/master/frame/proxy/src/lib.rs#L310) call to accept the a `when`(`Option<(T::BlockNumber, u32)>`) parameter that is used to derive the AccountId but it requires the user to identify and remember the block number and extrinsic index at the moment of creation of their account besides the user would need to recreate the anonymous with the same original account that might already be lost/trashed on purpose. 
A fancier solution could be with XCM, imagine something like an `export_proxied` call that sends a message to the target chain which is expected to re-create the same proxy set-up, if the account is anonymous it is created and assigned all the same proxy accounts from the origin chain.

**Comment by bkchr** [comment]
Cc @shawntabrizi

**Comment by xlc** [comment]
I don't think we need to do anything. You can just control the the anon account on relay chain to send Transact XCM to Parachain to access assets there.

**Comment by olanod** [comment]
@xlc could you elaborate more on the Transact approach and how you imagine it working? Doesn't seem to address one of the mentioned issues of re-using the same public key across chains, something that Acala encourages for example for receiving rewards to the account that participated in the relay-chain.

**Comment by xlc** [comment]
It does. Say `A` is anon proxy, controlled by `B` on Polkadot and `A'` is `A` on Acala. It is possible to access assets under `A'` by having B sending a transaction on behalf of `A` on Polkadot. The transaction will dispatch a XCM message from Polkadot to Acala, and on Acala it will be dispatched with origin of `A'` and able to access under `A'`

**Comment by shawntabrizi** [comment]
Yeah, I also think the story described above isn't fully worked out here.

An anonymous proxy itself can have ownership changes and even multiple users to control that proxy. It would be impossible to transfer all of that logic and ownership data across all chain each time something changes.

As @xlc mentions, the ultimate proof that you have ownership of some address on polkadot is to dispatch a message from that account.

**Comment by olanod** [comment]
Thanks @xlc the explanation helped, I was assuming `A'` would need to be recreated first with the same initial conditions as `A`, With an example of how the XCM would look like with all the fees part and everything it will be perfect for the future stackexchange site 😉
