### ISSUE TITLE
Allow root to make a call on behalf of a "signatory"

### ISSUE THREAD

**Issue by librelois** [paritytech/substrate#10459]
Sudo pallet already allows to make a call on behalf of a signatory with the extrinsic `sudo_as`. But most of the production networks don't have the sudo pallet, and in some cases the call has to be made with the root origin without using sudo.

Example with the democracy pallet: if we want to submit a referundum to run a batch of calls, all the calls will necessarily be executed with the root origin, but some calls can't be done with the root origin because they require a signatory.

I see 2 possible solutions:

1. Replace everywhere `ensure_signed` by `ensure_signed_or_root`
2. Create an extrinsic `root_as`, which requires root as the origin, and which executes the call given as a parameter to the name of the signatory given as a parameter. It remains to be decided in which pallet to place this extrinsic `root_as`, I think it would have its place in the `utility` pallet.

**Comment by xlc** [comment]
I already implemented it https://github.com/paritytech/substrate/pull/9934

**Comment by librelois** [comment]
Awesome, thanks @xlc
