### ISSUE TITLE
Introduce `FromEntropy` trait to replace dummy values

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#10465]
Introduce a new trait available in std only:

```
#[cfg(feature = "std")]
pub trait FromEntropy {
  fn from_entropy(entropy: impl Encode) -> Self;
}
```

And implement it for `AccountId`s, `Address`s, `Signature`s and everything for which it is useful to be able to generate dummy values deterministically.

This can replace `dummy_` functions, `Default`s and helpers such as `fn account()` used in tests and benchmarking.

**Comment by burdges** [comment]
How is this meant to be used?

**Comment by gavofyork** [comment]
```
/// Create random values of `Self` given a stream of entropy.
pub trait FromEntropy: Sized {
	/// Create a random value of `Self` given a stream of random bytes on `input`. May only fail if
	/// `input` has an error.
	fn from_entropy(input: &mut impl codec::Input) -> Result<Self, codec::Error>;
}
```

Basically if you supply an `input` of entropy, then for any type which implements this trait you'll be able to get an arbitrary but valid value.

This is different to just using `Decode::decode` since not that many types can be validly decoded from a random stream of bytes. E.g. for 254 of 256 possible byte values `bool` would fail to decode. So our impl for `FromEntropy` for `bool` is:

```
impl FromEntropy for bool {
	fn from_entropy(input: &mut impl codec::Input) -> Result<Self, codec::Error> {
		Ok(input.read_byte()? % 2 == 1)
	}
}
```
