### ISSUE TITLE
Generate root dispatchable setters for storage items

### ISSUE THREAD

**Issue by gregdhill** [paritytech/substrate#10507]
Manipulating storage is error-prone so explicit setters are often preferred ([for example](https://github.com/paritytech/substrate/blob/7f68a8be62433949f04abc3ab9d98a10dab95c7d/frame/staking/src/pallet/mod.rs#L1147)). These are mostly always constant-time operations that `ensure_root` and insert a value into storage. Since there are already getter annotations for storage items would it also be possible to add a setter annotation that constructs a root dispatchable function on the pallet?

**Comment by shawntabrizi** [comment]
I would not recommend this kind of thing to happen automatically because extrinsics are sensitive in their ordering and encoding.

For example, at this point, deleting this `setter` function would actually adjust the number of extrinsics in the pallet, the ordering, etc...

**Comment by bkchr** [comment]
For that exists `frame_system::set_storage`.

No need to have a dispatchable for each storage item + the things @shawntabrizi said.
