### ISSUE TITLE
Ubuntu 16.04 cargo build does not compile

### ISSUE THREAD

**Issue by bruciebruce** [paritytech/substrate#1051]
Here is my config:

`# uname -a`
`Linux bruce-VirtualBox 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

`# dpkg -l | grep libssl-dev`
`ii  libssl-dev:amd64  1.0.2g-1ubuntu4.13  amd64        Secure Sockets Layer toolkit - development files`

Here is the compile output....

`  Compiling srml-support v0.1.0 (file:///devel/substrate/srml/support)`
`error[E0658]: :vis fragment specifier is experimental and subject to change (see issue #41022)`
`   --> srml/support/src/dispatch.rs:111:3`
`    |`
`111 |         $vis:vis fn deposit_event() = default;`
`    |         ^^^^^^^^`
``
`error[E0658]: :vis fragment specifier is experimental and subject to change (see issue #41022)`
`   --> srml/support/src/dispatch.rs:132:3`
`    |`
`132 |         $vis:vis fn deposit_event($($param_name:ident : $param:ty),* ) { $( $impl:tt )* }`
`    |         ^^^^^^^^`
``
`error[E0658]: :vis fragment specifier is experimental and subject to change (see issue #41022)`
`   --> srml/support/src/dispatch.rs:174:3`

Thank you...in advance.

<img width="551" alt="bug-2" src="https://user-images.githubusercontent.com/493847/47872848-eb90c380-ddcc-11e8-8bfa-e36432390a81.png">

**Comment by bkchr** [comment]
Hey, you need at least rust 1.30.0 that was released last Thursday.

**Comment by bruciebruce** [comment]
Okay,

`$ rustc -V`
`rustc 1.30.0 (da5f414c2 2018-10-24)`

Gets to this:

<img width="843" alt="one" src="https://user-images.githubusercontent.com/493847/47885590-0d04a600-ddf3-11e8-9ea6-bfb149fd810f.png">

...and fast forwarding to the end...

<img width="837" alt="two" src="https://user-images.githubusercontent.com/493847/47885606-2148a300-ddf3-11e8-8b15-237165f284c3.png">

**Comment by bkchr** [comment]
Yeah, you probably need for RAM in your virtual machine. The linker is killed because its get out of memory.

**Comment by bruciebruce** [comment]
Good catch.  I wanted to see if this would work on a default settings.  Bumped it to 2048 MB.  Works now.
