### ISSUE TITLE
benchmarking prompt pallet-collective missing `successful_origin` in implementation

### ISSUE THREAD

**Issue by herryho** [paritytech/substrate#10548]
When I run the following command to try to generate the weight file for pallet-democracy,  the compiler prompted that some part of the collective pallet are "missing `successful_origin` in implementation", as it is shown below. In fact, as I clicked into the error link(xxx/.cargo/git/checkouts/substrate-7e08433d4c370a21/fcc54a7/frame/collective/src/lib.rs:1035:1), it actually has implemented the successful function with the feature "runtime benchmarks". 

What might cause this problem?

command:
cargo run --release --features="with-asgard-runtime,runtime-benchmarks" -- benchmark --chain="asgard-local" --steps=50 --repeat=1 --pallet="pallet-democracy" --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --header=./HEADER-GPL3 --output="./runtime/asgard/src/weights/pallet_democracy.rs"

Error:
![image](https://user-images.githubusercontent.com/45537372/147230575-10a5e83e-1fef-405b-833a-b7251c8d2f30.png)

![image](https://user-images.githubusercontent.com/45537372/147230723-f2f383da-457c-484f-bd07-7b6dd60c4172.png)

**Comment by bkchr** [comment]
This means you have forgot to forward the enabling of the `runtime-benchmarks` feature.

**Comment by herryho** [comment]
Yes, you are right. Thanks a lot for the help :)

**Comment by ltfschoen** [comment]
> This means you have forgot to forward the enabling of the `runtime-benchmarks` feature.

what do you mean when you say "forward the enabling of the runtime-benchmarks feature"?

i am trying to run benchmarks on the latest commit in this PR https://github.com/DataHighway-DHX/DataHighway-Parachain/pull/17, which is based upon the substrate-parachain-template.
i am able to compile without errors with `cargo build --release`
but when i run `cargo build --release --features runtime-benchmarks`, it outputs error
```
error[E0046]: not all trait items implemented, missing: `successful_origin`
    --> /Users/ls/.cargo/git/checkouts/substrate-7e08433d4c370a21/22d40c7/frame/society/src/lib.rs:1268:1
     |
1268 | impl<T: Config> EnsureOrigin<T::Origin> for EnsureFounder<T> {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `successful_origin` in implementation
     |
     = help: implement the missing item: `fn successful_origin() -> OuterOrigin { todo!() }`
```

so it's saying that in Substrate commit 22d40c761a985482f93bbbea5ba4199bdba74f8e ('polkadot-v0.9.17') is missing `fn successful_origin`,
but it appears to already be implemented in that commit here https://github.com/paritytech/substrate/blob/22d40c7/frame/society/src/lib.rs#L1278

i'm also not even using the dependency frame society, but it appears in Cargo.lock

it appears to be similar to this Substrate issue that was previously closed https://github.com/paritytech/substrate/issues/10548, where Basti said "This means you have forgot to forward the enabling of the runtime-benchmarks feature"

how do you "forward the enabling of the runtime-benchmarks feature"?

**Comment by salman01zp** [comment]
I am facing the same problem as  @ltfschoen . Adding them to the runtime-benchmark feature in runtime/cargo.toml does shut compiler error and build the node. But I don't have any other use of those deps.

**Comment by salman01zp** [comment]
@ltfschoen . I found this [issue_link](https://substrate.stackexchange.com/questions/240/missing-successful-origin-in-implementation-when-running-runtime-benchmarks) which can be helpful.
