### ISSUE TITLE
from_{integer} for FixedPointNumbers

### ISSUE THREAD

**Issue by benluelo** [paritytech/substrate#10572]
The only way to create a `Fixed*` number from an integer type is to cast it to `Self::Inner` and use `checked_from_integer`. This doesn't feel ideal, as if you have a `u64` and want to create a `FixedU128` out of it, which you *know* will fit in the 110 bit integer portion of the number, you must first cast it to `u128` (losing the type information) and then unwrap `checked_from_integer`... even though it will never fail. However, if the type is later changed to be a `u128` instead of a `u64`, it introduces a possibility for a runtime panic as the cast will be silently accepted but the invariant that safely allowed the `unwrap` previously is no longer upheld.

**Comment by apopiak** [comment]
Why doesn't `saturating_from_integer` https://github.com/paritytech/substrate/blob/62fcc8abb7679221814fd3a76d36ad5eafb65657/primitives/arithmetic/src/fixed_point.rs#L113-L120

do what you want?
Is the problem that you would want to disallow a saturating conversion of `u128` to `FixedU128`?

**Comment by kianenigma** [comment]
> you must first cast it to u128 (losing the type information) and then unwrap checked_from_integer... even though it will never fail

No information is lost if you convert. 

Nonetheless, we can improve this with: https://github.com/paritytech/substrate/pull/11159
