### ISSUE TITLE
The network key should periodically change

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#1059]
If you run a client on a laptop and use the same network key all the time, people can build a mapping between the network key and the IP address being used over time. This is quite bad for privacy.

**Comment by tomaka** [comment]
The problem with this issue is that bootstrap nodes must obviously keep the same key all the time, as this key is hard-coded in the client. Similarly, if a validator changes key it will then lose reputation.

My approach would be to add an option in the `NetworkConfiguration`, and let people enable it if they want. For example Polkadot could enable it for light clients only.

**Comment by melekes** [comment]
Is this still something we want to do here? I mean "the light client" is now a separate project https://github.com/paritytech/smoldot, implemented from scratch. It can choose to rotate keys if it wants to (I can move the issue there if desired).

**Comment by altonen** [comment]
I think we can close this and reopen/create new issue if we realize this is needed for Substrate-based clients as well

**Comment by burdges** [comment]
At some point we'll implement my slashing reform proposals, which requires nodes post back-certs on-chain, and shut down when their back-cert gets replaced.  These back-certs should involve machine specific randomness for this detection to happen.

In this, it's also reasonable for back-certs to contain certificates for nodes network keys, so then network keys end up authenticated from the chain.  We could also discuss creating network keys on node startup for most nodes, even mot validators perhaps, so not the same as rotating keys, but every time a node goes down its keys gets rotated.

This is a different topic from this issue, but I wanted to point out that some rotation should be imposed eventually.

**Comment by altonen** [comment]
@burdges Is there a paper or blog post or something available on your slashing reform?

**Comment by burdges** [comment]
A flavor appeared as https://github.com/paritytech/substrate/issues/7398#issuecomment-728875053 but also some internal issues, to which I can send links over matrix.
