### ISSUE TITLE
Investigate performance impact of compiler flags

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#10608]
Try out different compiler flags and check with the benchmarks for any substantial performance increase.  
The LTO flag seems promising after being discussed and later on used in Polkadot: https://github.com/paritytech/polkadot/issues/4311.  

If you specifically know more flags that could help: please post them here.

**Comment by koute** [comment]
There's also the `-C target-cpu` flag (mentioned in https://github.com/paritytech/polkadot/issues/4311); by default AFAIK it's set to `x86-64` (run `rustc -C target-cpu=help` for a full list), and I *think* we could use the `x86-64-v2` by default as CPUs which are a decade old should support it at this point.

The feature levels themselves are described here:

https://gitlab.com/x86-psABIs/x86-64-ABI/-/blob/master/x86-64-ABI/low-level-sys-info.tex

**Comment by ggwpez** [comment]
> There's also the `-C target-cpu` flag (mentioned in [paritytech/polkadot#4311](https://github.com/paritytech/polkadot/issues/4311)); by default AFAIK it's set to `x86-64` (run `rustc -C target-cpu=help` for a full list), and I _think_ we could use the `x86-64-v2` by default as CPUs which are a decade old should support it at this point.

Thanks for the idea!  
This was investigated as well for `wasmi` https://github.com/paritytech/wasmi/issues/339#issuecomment-1015761543  
I also tested it in Substrate on reference hardware, with no performance increase.  

I'm not sure if it makes sense to specify a concrete value (besides `native`) for it, since we are only concerned about the performance on reference hardware.

**Comment by koute** [comment]
That's good to know, thanks for checking!

I was wondering about the actual performance difference since the Moonbeam guys wrote that it gave them "good results"; it's a bummer you've found no increase. (Although maybe it just makes a difference when a significantly newer target is specified, instead of just slightly bumping the baseline?)

**Comment by ggwpez** [comment]
> Although maybe it just makes a difference when a significantly newer target is specified, instead of just slightly bumping the baseline?

The reference hardware is a `i7-7700K` from 2017, so compiling on newer CPU should already make it faster than the weights that we have specified.  
I will still put this in my backlog to take another look, just to ensure that we get maximum performance.  
PS: We are looking to upgrading the ref hardware soon anyway, so everything here would change again :see_no_evil:

**Comment by ggwpez** [comment]
#10777 Talks about `target-cpu` again.  
As it turns out: we currently do not have the tooling in place to actually test this.  
I just ran the benchmarks and compared the weights, but these are only the computational complexity *minus* the DB operations.  
So if the `target-cpu` thing turns out to improve DB performance, I will test it.  
Better tooling for this is on the way.

**Comment by koute** [comment]
Could we perhaps use the `export-blocks` subcommand and then do an `import-blocks` to indirectly also test the DB performance? (Not sure whether you've already tried it nor if it'd actually be useful; just throwing the idea out.)

**Comment by ggwpez** [comment]
> Could we perhaps use the `export-blocks` subcommand and then do an `import-blocks` to indirectly also test the DB performance? (Not sure whether you've already tried it nor if it'd actually be useful; just throwing the idea out.)

Yea I actually tried that [here](https://github.com/ggwpez/substrate-bench/tree/master/reports/02-sync-time) :smile:  
Currently I am trying to reproduce the setup that came up with [these](https://github.com/paritytech/substrate/blob/ded44948e2d5a398abcb4e342b0513cb690961bb/frame/support/src/weights.rs#L170) hardcoded weights.  
Then I can re-run it and get proper values for DB-Read/Write, BlockBase- and ExtrinsicBaseFees.

**Comment by ggwpez** [comment]
Does not seem to make a difference as shown here: https://github.com/paritytech/substrate/issues/10777#issuecomment-1080662752  
Closing until we find new compiler flags that we want to test.

**Comment by MathCryptoDoc** [comment]
I wanted to reopen this issue since it seems that the production profile that uses ``opt-level=3, lto=fat, codegen-units=1`` is not always that good when compiling for the native arch. See the [summary](https://www.math-crypto.com/optimized/summary-0-9-27/) and more details are in these [Python notebooks](https://github.com/MathCryptoDoc/polkadot-optimized/tree/main/notebook) where I benchmarked basically all possible options. Quite surprisingly, ``opt-level=2`` seems to be better.

The scores uses the benchmarks for BLAKE2 and SR25519, and the timing of the remark extrinsic. Are there other good extrinsics that can be benchmarked via the polkadot binary?

**Comment by nazar-pc** [comment]
If you're compiling for native then you can tweak other flags too. Default builds are not tuned for native.

**Comment by MathCryptoDoc** [comment]
Ah, didn't know this was meant for only default build. Which flags would you use for tuning native then?

**Comment by nazar-pc** [comment]
I meant I believe flags in this repo don't impact compilation flags in project that use it as dependency. It is up to you to have whatever flags you want in your workspace's `Cargo.toml` or whatnot.

**Comment by ggwpez** [comment]
> I wanted to comment on this issue since it seems that the production profile that uses opt-level=3, lto=fat, codegen-units=1 is not always that good when compiling for the native arch.

Yes possibly. But there have to be *some* settings for a production build and we cant optimize for every CPU.  
I think the default options are reasonable? We tried to pick options to let the compiler do all optimizations it can.

> Throwing away builds that do not improve upon the official binary, we have 15, 21, 38, 40, 45 as the good builds. They all build with `target-cpu=native``.

So the default release binary should be good enough for most cases. High performance users have to themselves anyway.

> Are there other good extrinsics that can be benchmarked via the polkadot binary?

It prints all available ones if you call it with the `--list` flag, but currently there is only one other: `transfer_pee_alive`.  
You can also take a look at the other benchmark commands: [README](https://github.com/paritytech/substrate/tree/master/utils/frame/benchmarking-cli#the-benchmarking-cli).

**Comment by MathCryptoDoc** [comment]
> Yes possibly. But there have to be _some_ settings for a production build and we cant optimize for every CPU. I think the default options are reasonable? We tried to pick options to let the compiler do all optimizations it can.

Sure, I agree for a generic production profile, the current settings make a lot of sense of course. I thought this issue was meant to investigate performance of compiler flags in general, including specialised builds. My mistake... 

> It prints all available ones if you call it with the `--list` flag, but currently there is only one other: `transfer_keep_alive`. You can also take a look at the other benchmark commands: [README](https://github.com/paritytech/substrate/tree/master/utils/frame/benchmarking-cli#the-benchmarking-cli).

Thanks, that convenient. Testing all that will take a long time, but might be interesting.

**Comment by ggwpez** [comment]
> Sure, I agree for a generic production profile, the current settings make a lot of sense of course. I thought this issue was meant to investigate performance of compiler flags in general, including specialised builds. My mistake...

We investigated the impact of the flags in order to find good default settings.  
Writing some kind of blog article (like you are doing :heart:) is better for more advanced insight.
