### ISSUE TITLE
Unable to build for release

### ISSUE THREAD

**Issue by ebalo55** [paritytech/substrate#10609]
Good afternoon everyone, i'm experiencing the inability to build for release `cargo build --release` any version of the substrate framework after the tagged v3.0.0.
This error is caused by the chain_spec code
```
error[E0783]: trait objects without an explicit `dyn` are deprecated
  --> bin/node/cli/src/chain_spec.rs:54:50
   |
54 | #[derive(Default, Clone, Serialize, Deserialize, ChainSpecExtension)]
   |                                                  ^^^^^^^^^^^^^^^^^^ help: use `dyn`: `<dyn ChainSpecExtension>`
   |
   = note: this error originates in the derive macro `ChainSpecExtension` (in Nightly builds, run with -Z macro-backtrace for more info)
```
It seems not to throw until you first try building for release. After the first building for release, the compilation in debug mode will throw the same error too.

I'm trying to build the code using the latest stable release at the time of writing, moving to a previous release (1.56.1) does not seem to solve the issue.

**Comment by bkchr** [comment]
EIther use master or downgrade to a rustc version that isn't failing because of this. (Try some stable of when 3.0 was released)
