### ISSUE TITLE
Probability of BABE stalling?

### ISSUE THREAD

**Issue by c-geek** [paritytech/substrate#10610]
I've found in the docs + checked code that BABE has only 2 fallbacks in case no primary blocks: SecondaryPlain + SecondaryVRF.

While I'm happy to have discovered this extra SecondaryVRF I was not aware of, yet two secondary authors seems a bit low to me because it's quite easy to have a faulty node in a epoch, even more with sleeping attackers.

Is there another fallback I'm not aware of? Don't you think there is a security issue here? Am I missing something?

**Comment by bkchr** [comment]
You only need one block per epoch/session to prevent BABE from stalling.

**Comment by c-geek** [comment]
I don't get it. The problem is the same to me whether the block is the first of an epoch, the second or the last.

Don't we have a stalling if no next block is proposed?

**Comment by bkchr** [comment]
What you mean? When no block is produced anymore? Why should there be no  block be produced anymore?

**Comment by c-geek** [comment]
Because of VRF leading to no primary block (no validator matching), same for secondary VRF, and same for secondary plain because, as I understand it, only one validator is selected per slot and he might be faulty.

**Comment by bkchr** [comment]
There is no problem if one slot is skipped.

**Comment by c-geek** [comment]
That was my blind spot. Thanks.
