### ISSUE TITLE
stop generating keys from seeds in service and keystore

### ISSUE THREAD

**Issue by azban** [paritytech/substrate#1063]
as per this [comment](https://github.com/paritytech/substrate/blob/d7bb960c9d2a240a17ea18d45be57434b5ba02ba/core/keystore/src/lib.rs#L156), we should find some way to prefill the keystore with keys that are generated from seed that is not in the standard execution path, because it is meant to be used for testing only.

**Comment by chevdor** [comment]
FYI: There is a very similar piece of code outside the keystore:
https://github.com/paritytech/substrate/blob/master/subkey/src/main.rs#L44

**Comment by webmaster128** [comment]
> that is not in the standard execution path

what do you mean by "standard execution path"?

There seems to be a lot of naming confution here. `generate_from_seed` generates an Ed25519 seed from a 0-32 character string.

**Comment by azban** [comment]
> what do you mean by "standard execution path"?
 it's just for testing

> There seems to be a lot of naming confution here
the name seems fine with some amount of context.. do you have a suggestion?

**Comment by webmaster128** [comment]
> do you have a suggestion?

What about this derication chain: passphrase -> seed -> keypair

The good thing about the term "passphrase" is that it implies to be choosen by user and it has the potential of being low entropy.

**Comment by webmaster128** [comment]
There are two types of seeds here in as input of `generate_from_seed`:

1. an arbitrary string
2. a 256bit Ed25519 seed

Do you want to get rid of both? Or only get rid of the 1. -> 2. derivation?

**Comment by dvc94ch** [comment]
Is it ok to remove this code? After updating the keystore to handle lru, this is inconvenient since we'd have to store testing and session_keys separately to avoid the testing key being auto removed.

**Comment by gavofyork** [comment]
This is sorted with the new RPCs.
