### ISSUE TITLE
Require `MaxEncodedLen` per default

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#10652]
Many pallets are currently missing `MaxEncodedLen` implementations. All future pallets should have it.   
To make it easier not to miss it, we could either:
- Add an optional `bool` argument to `generate_storage_info` which default to `true`
- Remove `generate_storage_info` and add a `without_storage_info` attribute

What do you favor?  

I personally like the second approach more, since we could then in the future remove both after all pallets have been migrated.

Related https://github.com/paritytech/substrate/issues/8629

**Comment by shawntabrizi** [comment]
I strongly prefer the second option. By default, we should make sure all pallets follow this storage definition requirement.
