### ISSUE TITLE
Odd bug when updating to master

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#10667]
Getting build errors that default isn't implemented for `AccountId` causing a myriad of other errors. Any idea why this occurs when updating to the `master` branch?
```
161 |     #[pallet::storage]
    |               ^^^^^^^ the trait `std::default::Default` is not implemented for `<T as frame_system::Config>::AccountId`
```

**Comment by apopiak** [comment]
This PR is the reason: https://github.com/paritytech/substrate/pull/10403
TLDR: `AccountId` should not have a default value, so it was removed.

**Comment by drewstone** [comment]
So the recommendation is convert all instantiations to `Option<T::AccountId>` in the pallet's storage?

**Comment by nazar-pc** [comment]
Many things were updated in that PR, just follow those examples. In some cases `Option<T::AccountId>` might make sense, in other cases something different, all depends on the use case.
