### ISSUE TITLE
state_traceBlock for large rpc-max-payload not working?

### ISSUE THREAD

**Issue by sourabhniyogi** [paritytech/substrate#10676]
We are instantiating acala nodes [with onFinality Dedicated Nodes and our own archive node] with --rpc-max-payload=32 to get large "state_traceBlock" results (along with `--rpc-methods=Unsafe`) but are receiving the following error still (in both cases):

```
curl   -H "Content-Type: application/json"   -d '{"id":1, "jsonrpc":"2.0", "method": "state_traceBlock", "params": ["0x7a50f573efb05b55a845e036e2bd086774873433730041d52e24fb2bc9f5afcb", "state", "", "Put"]}'  [endpoint]
{"jsonrpc":"2.0","result":{"traceError":{"error":"Payload likely exceeds max payload size of RPC server."}},"id":1}
```
[The above corresponds to https://acala.subscan.io/block/31754]

There are a few dozen blocks with this on acala, and the acala team lead believes this is likely a substrate issue ( https://github.com/AcalaNetwork/Acala/issues/1784 cc @kianenigma )

Here is a Kusama equivalent:

```
curl   -H "Content-Type: application/json"   -d '{"id":1, "jsonrpc":"2.0", "method": "state_traceBlock", "params": ["0xa31a6970ef016bd9d9f0e6a98b53118fec96563aa06f7cf81ebaea129efb663c", "", "Put"]}'
curl: (52) Empty reply from server
```
[The above corresponds to https://kusama.subscan.io/block/339742]

Our use case is for archival indexing -- Can you advise?

**Comment by bkchr** [comment]
Try again with this: https://github.com/paritytech/cumulus/pull/907/

**Comment by kianenigma** [comment]
Yeah, the above PR in cumulus will fix this. Please reopen if otherwise.
