### ISSUE TITLE
Add a link for AfG consensus in the readme

### ISSUE THREAD

**Issue by jamesray1** [paritytech/substrate#1067]
DDG is not helpful: https://duckduckgo.com/?q=%22AfG+Consensus%22&t=ffcm&ia=software.

**Comment by rphmeier** [comment]
The downside of new research is that it's not well indexed by the internet :P 
Feel free to add links.

Best docs are in
https://github.com/w3f/consensus/blob/master/pdf/grandpa.pdf
and
https://github.com/paritytech/finality-grandpa

**Comment by ltfschoen** [comment]
@rphmeier perhaps it'd be good to include those links at https://wiki.parity.io/Consensus, which would require updating https://github.com/paritytech/wiki/blob/master/Consensus.md

**Comment by jamesray1** [comment]
https://github.com/w3f/consensus/blob/master/pdf/grandpa.pdf should be added to https://github.com/paritytech/finality-grandpa.

**Comment by jamesray1** [comment]
Note also that those links don't seem to explain what AfG stands for.

**Comment by rphmeier** [comment]
AfG is an internal codename "Al's Finality Gadget" due to @AlistairStewart who invented it

**Comment by ltfschoen** [comment]
@rphmeier might be worth sneaking the AfG definition into Part 1 of your awesome GRANDPA blogpost somehow https://medium.com/polkadot-network/grandpa-block-finality-in-polkadot-an-introduction-part-1-d08a24a021b5.

**Comment by jamesray1** [comment]
> AfG is an internal codename "Al's Finality Gadget" due to @AlistairStewart who invented it

Haha, OK, although if you are going to refer to it in public documents then it's probably best to state what it stands for when it is first introduced in a document.

**Comment by ltfschoen** [comment]
AfG's been added to the glossary https://hackmd.io/Jd0byWX0RiqFiXUVC78Bdw#Origin

**Comment by jamesray1** [comment]
I made some edits to https://hackmd.io/Jd0byWX0RiqFiXUVC78Bdw and made a PR: https://github.com/paritytech/substrate/pull/1661.
