### ISSUE TITLE
export-genesis-wasm and build-spec taking code blob from genesis file instead of actual wasm build

### ISSUE THREAD

**Issue by chrisdcosta** [paritytech/substrate#10675]
I've noticed an unexpected behaviour when using `export-genesis-wasm` and `build-spec` with a custom genesis file if it is included in the runtime build rather than executed as an option at startup of the node (which should already contain the wasm blob anyway).

The behaviour I would expect is that the wasm blob should be generated from the compiled wasm for the runtime because generally you are only using these `export-genesis-wasm` and `build-spec` options when creating your genesis chainspec file. It is not necessarily needed once a substrate-based network is running.

However, the behaviour I observe is that when a genesis file is referenced in the node itself executing `export-genesis-wasm` or `build-spec` extracts the (potentially out-of-date) wasm blob from the Chainspec file and not the (potentially new) blob from the compiled wasm itself. 

In contrast this behaviour would be expected in a scenario where you might be executing these commands on a file that was not included in the runtime (i.e. by referencing using `--chain some-other-genesis-file.json`)

The impact of this issue is that developers must use a workaround to extract the correct wasm blob or else if they are not aware of this issue causing them to use the generic blob by accident.

The current workaround is to use the `--chain local or dev` option with either of the commands to obtain the current wasm blob. This can then be copy-pasted into your own custom genesis file to be included in your node.

To observe the issue you can replicate using the following steps:

### Step 1 Change the `code` section in the Chainspec to be `0x` and save it to the `res` directory of your node.

```json
 "genesis": {
     "runtime": {
       "system": {
        "code": "0x"
       },
       ...
       }
   }
```

### Step 2 Convert the chainspec file to raw:

```shell
./target/release/substrate build-spec --chain your-chainspec.json > your-chainspec-raw.json
```

### Step 3 In the `chain_spec.rs` file of your node you can force the node to include this genesis file by creating an entry:

```rust
pub fn your_config() -> Result<ChainSpec, String> {
	ChainSpec::from_json_bytes(&include_bytes!("path/to/res/your-chainspec-raw.json")[..])
}
```

### Step 4 For convenience adjust the `command.rs` file to allow you to call this config:

```rust
fn load_spec(
	id: &str,
) -> std::result::Result<Box<dyn sc_service::ChainSpec>, String> {
	Ok(match id {
		"dev" => Box::new(chain_spec::development_config()),
		""| "local" => Box::new(chain_spec::local_testnet_config()),
		"command-to-start-your-chain" => Box::new(chain_spec::your_config()?),
		path => Box::new(chain_spec::ChainSpec::from_json_file(std::path::PathBuf::from(path))?),
	})
}
```

### Step 5 Compile your node and perform extract genesis wasm or build the spec from your node:

```rust
./target/release/substrate build-spec --chain your-chain-name > your-chainspec.json

// or

./target/release/substrate export-genesis-wasm --chain your-chain-name > your-wasm-blob.wasm
```
* The output for `build-spec` will contain `0x` in the code section (unexpected).

* The output contained in your-wasm-blob.wasm is `0x`(unexpected)

## Proposed solution

There should be three options to these commands

**default**

No chain name, it always extracts the from latest wasm build, for dev, local and main runtime

    ./target/release/substrate export-genesis-wasm > your-wasm-blob.wasm

**existing**

Will use the existing code blob from a genesis file. Does not need to be explicitly stated but is the default behaviour when a file is passed in the chain option. 

    ./target/release/substrate export-genesis-wasm --existing --chain your-chain-name > your-wasm-blob.wasm

### Justification

Teams planning to build a Mainnet or Parachain based on Substrate, will be (should be?) building their chains specs correctly especially if they have already implemented custom pallets and are expecting third-parties to download, compile and run their code directly without having to search for or use a separate Chainspec file.

This also avoids confusion over where to obtain the correct wasm blob, and why it might be needed.

**Comment by bkchr** [comment]
1. This is done by intention, because people should first build the chain spec they will gonna use and then export the relevant data from this file. Everything else doesn't make any sense and is just more confusing.
2. You control the entire code that s being used for exporting the wasm.  https://github.com/paritytech/cumulus/blob/master/parachain-template/node/src/command.rs#L213-L233 This means, you can modify this as you like.

**Comment by chrisdcosta** [comment]
1) This only works if you use `dev` or `local` to extract your wasm blob. It does not work for any other chainspec that _is included in your runtime_ .

2) The link only shows that you are allowed to pass in parameters which I dealt with that case in the issue text.

By not addressing the issue, it makes the barrier to entry for developers that much harder because _there is no specific way to extract the current wasm blob_.

**Comment by bkchr** [comment]
> 2\. The link only shows that you are allowed to pass in parameters which I dealt with that case in the issue text.

If you speak about the `extract_genesis_wasm` function. This function is defined in the very same file: https://github.com/paritytech/cumulus/blob/master/parachain-template/node/src/command.rs#L110-L117 Aka this is your code and you can still whatever you like.



> 1. This only works if you use `dev` or `local` to extract your wasm blob. It does not work for any other chainspec that _is included in your runtime_ .

I don't understand this, as chain specs are not part of the runtime.



> _there is no specific way to extract the current wasm blob_ that does not result in copy paste and multiple steps.

You already copy and pasted the code, so I don't see any big difference.

**Comment by bkchr** [comment]
In your repo the function is defined here: https://github.com/totem-tech/totem/blob/experimental-ledger/parachain-totem-kapex/node/src/command.rs#L116-L123

**Comment by bkchr** [comment]
When you want to launch a parachain, you should do the following:

1. Create a chain spec. (This is also what you do for solo blockchains).
2. Run `export-genesis-wasm --chain my-just-created-chain-spec.json` & `export-genesis-state --chain my-just-created-chain-spec.json`. By doing this, you ensure that the chain-spec and the data  that is being registered on the relay chain match.

We have already seen multiple times that step 2 failed, because people registered the wrong genesis state. To prevent this, we recommend the way as described above.

If you don't like this way, you are free to change your code in whatever way you like. This is one of the reason why the "user" code decides on what to do when a particular cli flag is given.

**Comment by chrisdcosta** [comment]
The issue is in "Create a chain spec." step one.

To "create a chainspec" you require a file that contains the wasm blob. To obtain wasm blob you use "export-genesis-wasm" to extract it. However it extracts from the chain spec not from the actual `.wasm` that you just compiled. Do you see the issue?

It does not surprise me that other teams are having issues, because they are unaware that the wasm blob isn't in fact coming from their current `.wasm` file. It's my opinion that it should.

**Comment by bkchr** [comment]
> To "create a chainspec" you require a file that contains the wasm blob. To obtain wasm blob you use "export-genesis-wasm" to extract it. However it extracts from the chain spec not from the actual `.wasm` that you just compiled. Do you see the issue?

No that is not true. https://docs.substrate.io/how-to-guides/v3/basics/custom-chain-spec/
Here you can read how you build your chain spec.
