### ISSUE TITLE
Trait PerThing missing MaxEncodedLen

### ISSUE THREAD

**Issue by zzm-Zhong** [paritytech/substrate#10712]
PerThing: [./primitives/arithmetic/src/per_things.rs#L428](https://github.com/paritytech/substrate/blob/master/primitives/arithmetic/src/per_things.rs#L428) missing **MaxEncodedLen**

**Comment by ggwpez** [comment]
Thanks for reporting! Looks like we do not test this.  
I will fix it together with another problem.
