### ISSUE TITLE
Delete (DataProvider = Pallet<Self>) at pallet-staking

### ISSUE THREAD

**Issue by zzm-Zhong** [paritytech/substrate#10724]
Cloud delete **DataProvider = Pallet\<Self\>**  at  [frame/staking/src/pallet/mod.rs#L86](https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L86) and  [.frame/staking/src/pallet/mod.rs#L93](https://github.com/paritytech/substrate/blob/master/frame/staking/src/pallet/mod.rs#L93), that i can impl my cutom **ElectionProvider**

**Comment by bkchr** [comment]
CC @kianenigma @emostov

**Comment by kianenigma** [comment]
Can you explain why you need this? There is a reason that we added that constraint, which is explained right above the line: 

```
// we only accept an election provider that has staking as data provider.
```

All in all, removing the bound might allow for more misconfiguration and footguns to happen.

**Comment by zzm-Zhong** [comment]
Sorry, i know how to do this.
