### ISSUE TITLE
Return the error value from contract transactions when `ContractReverted`

### ISSUE THREAD

**Issue by forgetso** [paritytech/substrate#10730]
When a contract function is run via a `dry run`, any errors are visible in the contracts debug and also in the polkadotjs interface.

When a transaction is actually submitted, these errors are not returned. Despite the error index being available in the `retval`: https://github.com/paritytech/substrate/blob/31d90c202d6df9ce3837ee55587b604619a912ba/frame/contracts/src/lib.rs#L378

Logging this value gives, for example:
`Retval: ExecReturnValue { flags: REVERT, data: Bytes([1, 0]) }`

This is the first error in the error `enum` in the contract.

It would be helpful if this error could be propagated inside the `ContractReverted` error so that transactions returned meaningful errors.

**Comment by bkchr** [comment]
CC @athei

**Comment by athei** [comment]
This isn't possible because from a dispatchable we can only return a `DispatchError` which does not allow to include arbitrary data. So we couldn't include the `bytes`. If you need your contract to communicate something to the off chain world the way of doing that would be to emit an event.

**Comment by forgetso** [comment]
The idea that you're going to emit an event for every error seems like contract bloat to me. It forces me to write code like this:

```
    // Event emitted when a provider does not exist
    #[ink(event)]
    #[derive(Debug)]
    pub struct ProviderDoesNotExist {
        #[ink(topic)]
        account: AccountId,
    }


    if self.providers.get(&provider_account).is_none() {
       self.env().emit_event(ProviderDoesNotExist {
           account: provider_account,
       });
       return Err(Error::ProviderDoesNotExist);
    }
```

instead of

```
            if self.providers.get(&provider_account).is_none() {
                return Err(Error::ProviderDoesNotExist);
            }
```

I have 17 different errors in my contract so far. That's a lot of boilerplate.

Your `DispatchErrorWithPostInfo` error allows for post info. Why not expand it to include the error message as well as the gas used? This would make it a lot easier for newbies to understand why their transactions were failing.

After using ink! for a while, I now understand that you can dry run contract functions to receive the actual error message. However, I've spent many many hours misunderstanding `ContractReverted` errors and I'm sure it's the same for other people.

**Comment by athei** [comment]
> Your DispatchErrorWithPostInfo error allows for post info. Why not expand it to include the error message as well as the gas used? This would make it a lot easier for newbies to understand why their transactions were failing.

Cause this type is shared for all of FRAME. Adding pallet specific data there would bloat that type up for everyone. Also, this would incur cost for everyone transaction even if this information isn't needed. Instead, the contract needs to pay for emitting the event in gas if it determines that it needs the event. This disincentivizes bloating the chain history.

> After using ink! for a while, I now understand that you can dry run contract functions to receive the actual error message. However, I've spent many many hours misunderstanding ContractReverted errors and I'm sure it's the same for other people.

So you already arrived at the right conclusion: On chain execution isn't for debugging. You should use the dry run RPC and probably some `debug_println!` in your contract. Events should only be added when the particular event is of interest to some off chain entity and not to debug the contract.

> I have 17 different errors in my contract so far. That's a lot of boilerplate.

Automatically deriving events from errors and emitting them on return is something that might be interesting for ink!.  However, it should never be the default behavior as it adds additional costs. @cmichi what do you think?

**Comment by forgetso** [comment]
Thanks, this makes it much clearer for me why you wouldn't extend the error.

Automatic event derivation from errors would be useful. Perhaps switched on with the `--debug` log flag. However, it is also acceptable for me to dry run and also place debug in the code for now. Maybe it's just a documentation issue. Something along the lines of "Why does my transation return `ContractReverted` instead of my contract error codes?" may need added to the ink [FAQ](https://paritytech.github.io/ink-docs/faq#why-am-i-getting-a-contracttrapped-error-when-interacting-with-a-contract).
