### ISSUE TITLE
`construct_runtime` should allow declaring log type without extending `DigestItem` trait or generic struct

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1074]
Note that any such variants of `DigestItem` will *not* be visible from the `core`, so this is just for `DigestItem` variants that only ever are accessed by the runtime. If you need `core` to be able to access them at all, then they must be "hard coded" as at present.

**Comment by svyatonik** [comment]
Seems like example from #1086 works fine in this case => I'm closing the issue
