### ISSUE TITLE
construct_runtime should bail if pallet have config but not declared

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#10756]
For many pallets the config is required to make it working properly but it is easy to miss it in `construct_runtime` and therefore end up in unexpected state.

It really need to be a compile error to prevent inconsistent state.

**Comment by xlc** [comment]
Fixed by the new construct_runtime syntax.

**Comment by bkchr** [comment]
For posterity: https://github.com/paritytech/substrate/pull/9681
