### ISSUE TITLE
`MaxEncodedLen` for FixedPoint primitives

### ISSUE THREAD

**Issue by sander2** [paritytech/substrate#10766]
Now that `MaxEncodedLen` is required by default (https://github.com/paritytech/polkadot/pull/4746), the fixedpoint types in `primitives/arithmetic/src/fixed_point.rs` should derive `MaxEncodedLen`.

**Comment by ggwpez** [comment]
Which types do you need to continue your work?  
Just the `FixedI64`, `FixedI128` and `FixedU128`?

**Comment by gregdhill** [comment]
We only require `FixedI128` and `FixedU128` but I assume it can't hurt to derive `MaxEncodedLen` for all fixed point types.
