### ISSUE TITLE
why chain prefix not accept the PR

### ISSUE THREAD

**Issue by cj1afs** [paritytech/substrate#10763]
From 29 Nov 2021 to now, I don't know why it is not merged.

https://github.com/paritytech/ss58-registry/pull/57

At the same time, we are also bidding on KSM  parachain, and the parachain ID is 2107.

I very much hope that the official technical team can explain the reason，thank you very mush.

**Comment by bkchr** [comment]
Please get in contact with @BenWhiteJam and not create issues in Substrate.
