### ISSUE TITLE
Performance issues related with RocksDB

### ISSUE THREAD

**Issue by fixxxedpoint** [paritytech/substrate#10777]
In our benchmarks/stress tests we discovered several issues related with RocksDB used within substrate. I couldn't find any info describing them so I figured that writing an issue would be a good idea. I will just number them so it will be easier to relate later in potential discussion:
1. crc32 from rocksdb is not using its SSE4.2 ("fast") version. By default, cargo uses a generic target-cpu, which limits number of available cpu features available for rustc and others significantly. Few of the libraries within substrate dependencies are using for example SSE4.2. Some of them even attempts to discover if they are supported at runtime. This doesn't apply to rocksdb. Its rust crate conditionally compiles with SSE4.2 support - default set of features misses it. This forces rocksdb to use its "slow" version of crc32. This function was occupying a significant amount of time in our tests. It would be a good idea to document it somewhere. It seems it also applies to build guide provided for polkadot here https://github.com/paritytech/polkadot/blob/4ac95dcbfff341e7d13a76b34623ad5040b49efb/README.md?plain=1#L111.
2. Is it ok to disable Snappy (or any other compression) for rocksdb or something might get "broken" by doing it? The way substrate dependencies are declared (their Cargo.toml files) prevents us from changing rocksdb's compression algorithm - by default it uses Snappy. It would be nice to allow to configure it somehow.
3. Internal issue within rocksdb itself: one can configure ReadOptions for rocksdb in a way that avoids verification of checksums every time a block-content is loaded. By default it verifies it every time it is called. Disabling it gave us a huge performance gain.

**Comment by ggwpez** [comment]
In the future we want to replace RocksDB with [ParityDB](https://github.com/paritytech/parity-db), this should improve performance.  
Regarding your 1. point: Does it make a large difference if you compile it with `target-cpu=native`?  
We recently updated our `production` profile, but as I remember just now, our benchmarks do not take the DB weight into account.

**Comment by fixxxedpoint** [comment]
> 1. point: Does it make a large difference if you compile it with target-cpu=native?
I preferred to be more verbose about my target cpu and used `cascadelake` (c5.xlarge instances on aws seems to fit this description), since `native` can mean something different than I am expecting. Performance gain was huge, more than 50%. After applying all points mentioned, our chain was bottlenecked by cryptography and io (as we were kind of expecting before those tests). Before, crc32 was occupying more than 68% of cpu time. After switching on only the crc32_fast version, Snappy became main problem. I haven't tested it yet, but perhaps forcing `verify_checksums = false`  in rocksdb might also remove calls to crc32 without that cpu-target thing.

**Comment by fixxxedpoint** [comment]
One more thing: I only focused on RocksDB. I have no knowledge how many other dependencies might be influenced by not providing a `taget-cpu` for building your binaries.

**Comment by ggwpez** [comment]
I conducted a Storage benchmark for `RUSTFLAGS='-C target-cpu=native'` on a recent Polkadot snapshot.  
The performance is actually worse;  
- with the native flag: 23.85µs read, 91.48µs write
- normal release: 20.66µs read, 86.12µs write

Executed like this:
```sh
# With native flag
RUSTFLAGS='-C target-cpu=native' cargo build --profile=release --bin polkadot --target-dir native
./native/release/polkadot benchmark-storage --state-version=0 --weight-path=runtime/polkadot/constants/src/weights/

# Normal release
./target/release/polkadot benchmark-storage --state-version=0 --weight-path=runtime/polkadot/constants/src/weights/
cargo build --profile=release --bin polkadot
```
I did not use the production profile since this would take an hour to build again, but the relativity should still hold.

**Comment by ggwpez** [comment]
`ParityDB` can be used since its not experimental anymore. Its much faster anyway.
