### ISSUE TITLE
Add an event to Staking when a validator updates their commission

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#10802]
Right now, there is no such notification, and it may be specifically relevant to track which validators are increasing their commission on existing nominators.

**Comment by ECJ222** [comment]
Hi @shawntabrizi, Can I take on this issue?

**Comment by shawntabrizi** [comment]
@ECJ222 sorry, this is for @rossbulat

This is a good issue that I think you could take @ECJ222 !
https://github.com/paritytech/substrate/issues/10820

**Comment by ECJ222** [comment]
Okay @shawntabrizi

**Comment by sudipghimire533** [comment]
We can close this?
