### ISSUE TITLE
[BUG] PalletIds not uniquely determined by 8 symbol input

### ISSUE THREAD

**Issue by saiakilesh** [paritytech/substrate#10812]
I don’t exactly know why but setting `TokenWrapperPalletId` like this: https://github.com/webb-tools/protocol-substrate/blob/main/pallets/token-wrapper/src/mock.rs#L157 and setting `TreasuryPalletId` like this: https://github.com/webb-tools/protocol-substrate/blob/main/pallets/token-wrapper/src/mock.rs#L131 leads to them both being equal for some reason (specifically they are both equal to `8372043756066860909`).

After some experimenting it seems that the PalletId is determined only by the first 4 out of 8 symbols. Since the first four symbols of both are `py/t` I think this is why they ended up as equal. Not sure how to confirm this though.

**Comment by bkchr** [comment]
You are using `u64` as `AccountId` in your mocked environment. 

So, that makes sense that only the first 4 bytes of the `PalletId` are used.

https://github.com/paritytech/substrate/blob/master/primitives/runtime/src/traits.rs#L1283-L1287 see the implementation here.

**Comment by shawntabrizi** [comment]
see: https://github.com/paritytech/substrate/pull/10719

**Comment by ggwpez** [comment]
Closed by #10719

**Comment by bkchr** [comment]
Not yet closed.
