### ISSUE TITLE
[Need Support] | nodle mainnet | corrupted block issue

### ISSUE THREAD

**Issue by rajesh-nodle** [paritytech/substrate#10817]
It's related to block corruption in the nodle mainnet & wondering how the block got corrupted.

And we caught it while indexing the chain.

Right now bit blocked with this issue. & Looking for some support either to fix or remove this corrupted block.

* [nodle isse #472](https://github.com/NodleCode/chain/issues/472)

Issue Overview, Unable to decode the block # `3071198`, Hit with below event decode error ...

![](https://i.imgur.com/4UYvECo.png)

Initial Analysis outcomes ...

> With raw block data, confirmed it has metadata for two extrinsics events ...

* [dump-block-3071198.txt](https://gist.github.com/rajesh-nodle/500773d2bec50c527f76e0c7ab3d31c2)

> And with help of `@polkadot/api | packages/types/src/generic/Event.ts` traces, confirmed, 

![](https://i.imgur.com/f720k3B.png)

Getting some Invalid length & index data ...

![](https://i.imgur.com/bzDYbgJ.png)

**Setup Details**

| Package | Version |
| --- | --- |
| nodle chain | Substrate version branch = "polkadot-v0.9.13" |
| polkadot js app | "0.102.2-7" |
| polkadot js api | "7.4.1" |

**Comment by bkchr** [comment]
That is a polkadot-js issue, not a Substrate issue.

**Comment by rajesh-nodle** [comment]
Occurs, like block (source data), is corrupted. polkadot-js is firing the decode error due to source corruption.

**Comment by bkchr** [comment]
Are you 100% sure? Run the node with `--execution wasm` and check again please.

**Comment by rajesh-nodle** [comment]
Having same error response even with option `--execution wasm` ...

![](https://i.imgur.com/bxUPiVo.png)

**Comment by bkchr** [comment]
CC @jacogr what do you think?

**Comment by jacogr** [comment]
This is an incorrect type definition, not Substrate related at all.

**Comment by bkchr** [comment]
Ty @jacogr as I assumed :) Going to close this issue.

**Comment by rajesh-nodle** [comment]
Thanks @bkchr @jacogr
