### ISSUE TITLE
Add "rebalance account" function to conviction voting pallet

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#10820]
A user can participate in votes and also participate in staking.

While staking, a user can be slashed, and thus their balance can decrease.

However, the conviction voting pallet will not know that a users balance has decreased, and will still give them voting representation of their old balance.

There should be a simple, permissionless call which allows anyone to be able to ping a user account, and the system will check their latest balance, and rebalance the users votes appropriately.

**Comment by ECJ222** [comment]
I will be working on this issue @shawntabrizi

**Comment by stanly-johnson** [comment]
Possible duplicate of #10761

**Comment by shawntabrizi** [comment]
haha yes, a duplicate indeed
