### ISSUE TITLE
Is there any place to see the list of all rpc methods for substrate

### ISSUE THREAD

**Issue by FitzLu** [paritytech/substrate#10833]
Hello, I want to find all substrate rpc methods, is there any docs like [Ethereum json rpc](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/eth1.0-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=true&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false) ?

thanks

**Comment by AsceticBear** [comment]
Try this way(I usually used):
```sh
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}' https://127.0.0.1:9933 | jq
```

BTW, you can ask such questions here [Substrate Stakexchange](https://substrate.stackexchange.com/)
