### ISSUE TITLE
error: could not compile `libsecp256k1

### ISSUE THREAD

**Issue by raojianli** [paritytech/substrate#10857]
Caused by:
  process didn't exit successfully: `rustc --crate-name libsecp256k1 --edition=2018 /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libsecp256k1-0.6.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="hmac"' --cfg 'feature="hmac-drbg"' --cfg 'feature="sha2"' --cfg 'feature="static-context"' --cfg 'feature="std"' --cfg 'feature="typenum"' -C metadata=639c26cb60feb26b -C extra-filename=-639c26cb60feb26b --out-dir /opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps -L dependency=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps --extern arrayref=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps/libarrayref-71ac32bf9fa2cdb8.rmeta --extern base64=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps/libbase64-1fd5acc4d659918c.rmeta --extern digest=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps/libdigest-e344e173c70066ac.rmeta --extern hmac_drbg=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps/libhmac_drbg-7dac4ec5afd4bc1e.rmeta --extern libsecp256k1_core=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps/liblibsecp256k1_core-802ffa2e72b19639.rmeta --extern rand=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps/librand-c5c961294999487c.rmeta --extern serde=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps/libserde-7e7c6bb841810c47.rmeta --extern sha2=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps/libsha2-b32c83c65aa7abef.rmeta --extern typenum=/opt/chainmanagersv2/polkadex/subclient/lib/pdexapi/target/release/deps/libtypenum-fb4df0eb1296967c.rmeta --cap-lints allow` (signal: 9, SIGKILL: kill)

centos7.  rustc 1.58.1 (db9d1b20b 2022-01-20)

**Comment by bkchr** [comment]
You are running out of memory. Add some swap or get more ram ;)
