### ISSUE TITLE
nomination-pools: Add metadata for pools

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate#10862]
Currently, there is no good way for a pool to have some identity or general metadata associated with it for UIs to display. One could set a sub identity for the pools account, but there is nothing preventing a random user from sniping the pool account as its sub identity.

The delegator <=> pool relationship is similar to the nominator <=> validator relationship in that the delegator needs to gauge the quality and goals of the pool admin. Metadata would likely include things like emails, riot handles, and links to web pages  where the delegator can learn more about the pool admin. 

The metadata can be stored as a byte vec that represents UTF8 encoded characters and can be set by pool admin. The pool creation bond should take into account the cost of storing such metadata, even if the metadata is intended to be added after calling the pool create extrinsic; this will keep the pool creation bond logic simpler when destroying a pool.

Should wait until #10694 is merged to start working on this.

**Comment by kianenigma** [comment]
This seem to already exist.
