### ISSUE TITLE
RPC method to verify if a block hash is finalized

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#10870]
Currently in order to verify a block hash is finalized, multiple calls required:

1. chain_getFinalizedHead to get the finalized block hash
2. chain_getHeader to get the header and block number of the finalized block hash
3. chain_getHeader to get the header and block number of the verifying block hash
4. chain_getBlockHash to get the canonical block hash of the verifying block number

The block is finalized if the hash if step 4 matches and the number from step 3 is less or equal to the number from step 2.

If will be helpful if we can have a single RPC call that does all those work.

**Comment by rphmeier** [comment]
@xlc 

There is a new JSON-RPC spec under development which outlines some objectives that I think provide a good explanation of why this is not really useful long-term (https://paritytech.github.io/json-rpc-interface-spec/objectives.html). We want to discourage using trusted RPC servers and that is the only use-case where doing 4 RPC requests is actually more overhead. The new interface is designed with light clients in mind and will, as a rule, only allow merging of JSON-RPC requests that result in fewer underlying network requests.
