### ISSUE TITLE
Integrate `try-runtime` into `substrate-node-template`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#10892]
Add `TryRuntime` subcommand here: 

https://github.com/paritytech/substrate/blob/917fe4919c70cb022a9c90eb6415cf85cbc67f7b/bin/node-template/node/src/cli.rs#L13

in a similar fashion to: 

https://github.com/paritytech/substrate/blob/917fe4919c70cb022a9c90eb6415cf85cbc67f7b/bin/node/cli/src/cli.rs#L46

**Comment by omadoyeabraham** [comment]
@kianenigma I'm willing to take this up
