### ISSUE TITLE
nomination-pools: Add bond extra and bond rewards extrinsics

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate#10903]
Currently a delegator cannot bond more funds after they join. To remedy this we should add a 
- `bond_extra` extrinsic that allows the delegator increase their bond with non-locked funds,
- and a `bond_rewards` extrinsic that allows a user to take their rewards and directly use them to increase their bonded funds. The `bond_rewards` extrinsic isn't strictly necessary since a delegator could `claim_rewards` and then call `bond_extra`.

Should wait until https://github.com/paritytech/substrate/pull/10694 is merged to start working on this.

**Comment by kianenigma** [comment]
closed by https://github.com/paritytech/substrate/pull/11100
