### ISSUE TITLE
RPC subscriptions send back subscription message before sending back the subscription ID

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#10910]
To reproduce:

> websocat --jsonrpc wss://rpc.polkadot.io
> state_subscribeRuntimeVersion []

The node responds with:

> {"jsonrpc":"2.0","method":"state_runtimeVersion","params":{"result":{"apis":[["0xdf6acb689907609b",3],["0x37e397fc7c91f5e4",1],["0x40fe3ad401f8959a",5],["0xd2bc9897eed08f15",3],["0xf78b278be53f454c",2],["0xaf2c0297a23e6d3d",1],["0x49eaaf1b548a0cb0",1],["0x91d5df18b0d2cf58",1],["0xed99c5acb25eedf5",3],["0xcbca25e39f142387",2],["0x687ad44ad37f03c2",1],["0xab3c0572291feb8b",1],["0xbc9d89904f5b923f",1],["0x37c8bb1350a9a2a8",1]],"authoringVersion":0,"implName":"parity-polkadot","implVersion":0,"specName":"polkadot","specVersion":9151,"stateVersion":0,"transactionVersion":9},"subscription":"rcCL9jxosJlIDZ2C"}}
> {"jsonrpc":"2.0","result":"rcCL9jxosJlIDZ2C","id":1}

As you can see, we receive a notification for the subscription `rCL9jxosJlIDZ2C` before the `state_subscribeRuntimeVersion` is actually answered.

Doing this doesn't make. You can't know which subscription the first message is associated to before receiving the second. It forces the JSON-RPC client to buffer messages of unknown subscriptions in order to associate them later.

Happens on Polkadot version 0.9.16

cc @dvdplm @niklasad1

**Comment by niklasad1** [comment]
hrm, I think I have bumped to this too when I tried in subxt for a while ago.

I'm no expert on the `jsonrpc crate` but [this](https://github.com/paritytech/jsonrpc/blob/master/pubsub/src/subscription.rs#L295) looks not be coupled the actual `add_subscription` so it possible that the subscription response might be sent before the actual subscription ID....

**Comment by harrysolovay** [comment]
> It forces the JSON-RPC client to buffer messages of unknown subscriptions in order to associate them later.

I'm also running into this situation. With each subscription, one must buffer incoming messages, await the subscription call result, then iterate over the message buffer, match message subscription ids and then trigger the initial callback with the matched messages. To simply trust the response order would be preferable (to say the least). Any updates?

**Comment by niklasad1** [comment]
it should go away once https://github.com/paritytech/substrate/pull/8783 is merged.

**Comment by harrysolovay** [comment]
Excellent! Thank you for the update.

**Comment by niklasad1** [comment]
Should be fixed by #8783, would be good if you try it out in JS/smoldot too.
