### ISSUE TITLE
Proxy Pallet is not working on Version 4.0.0

### ISSUE THREAD

**Issue by PankajChaudhary5** [paritytech/substrate#10919]
I am trying to add the proxy pallet to the latest version of substrate 4.0.0-dev. It is giving an Error. 
Is not compatible with the latest version?

Error: 
pankajchaudhary@pankajs-MacBook-Pro testnet-beta-development % cargo build --release
    Updating crates.io index
error: failed to select a version for `parity-util-mem`.
    ... required by package `sp-core v3.0.0`
    ... which satisfies dependency `sp-core = "^3.0.0"` of package `frame-support v3.0.0`
    ... which satisfies dependency `frame-support = "^3.0.0"` of package `frame-system v3.0.0`
    ... which satisfies dependency `frame-system = "^3.0.0"` of package `pallet-proxy v3.0.0`
    ... which satisfies dependency `pallet-proxy = "^3.0.0"` of package `node-template-runtime v4.0.0-dev (/Users/pankajchaudhary/Downloads/testnet-beta-development/runtime)`
    ... which satisfies path dependency `node-template-runtime` (locked to 4.0.0-dev) of package `node-template v4.0.0-dev (/Users/pankajchaudhary/Downloads/testnet-beta-development/node)`
versions that meet the requirements `^0.9.0` are: 0.9.0

the package `parity-util-mem` links to the native library `parity-util-mem-ban-duplicates`, but it conflicts with a previous package which links to `parity-util-mem-ban-duplicates` as well:
package `parity-util-mem v0.10.2`
    ... which satisfies dependency `parity-util-mem = "^0.10.2"` of package `sc-informant v0.10.0-dev (https://github.com/paritytech/substrate.git?tag=devhub/latest#e6fbbd5c)`
    ... which satisfies git dependency `sc-informant` (locked to 0.10.0-dev) of package `sc-service v0.10.0-dev (https://github.com/paritytech/substrate.git?tag=devhub/latest#e6fbbd5c)`
    ... which satisfies git dependency `sc-service` (locked to 0.10.0-dev) of package `frame-benchmarking-cli v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=devhub/latest#e6fbbd5c)`
    ... which satisfies git dependency `frame-benchmarking-cli` (locked to 4.0.0-dev) of package `node-template v4.0.0-dev (/Users/pankajchaudhary/Downloads/testnet-beta-development/node)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='parity-util-mem' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

**Comment by bkchr** [comment]
Looks like you are trying to mix some crates.io released Substrate crates with some from git. This will not work.
