### ISSUE TITLE
pallet_assets : event emitted for noop

### ISSUE THREAD

**Issue by stanly-johnson** [paritytech/substrate#10927]
pallet-assets emits an event for [zero transfer](https://github.com/paritytech/substrate/blob/dfe52f7de12a7e308c0bc3a25e211b9cc4d61871/frame/assets/src/functions.rs#L534) while pallet-balances [does not.](https://github.com/paritytech/substrate/blob/dfe52f7de12a7e308c0bc3a25e211b9cc4d61871/frame/balances/src/lib.rs#L1495) Is this correct? If not, can make a PR to make the behaviour consistent.

**Comment by bkchr** [comment]
I mean the code is called explicitly in this branch. 

Maybe @gavofyork or @shawntabrizi can shed some light on it.

**Comment by shawntabrizi** [comment]
What is the standard within the blockchain ecosystem? We should just follow the pattern expected by others.

Otherwise, I think emitting an even when no transfer happened is a waste of resources in general, so I would actually remove the noop event.

**Comment by ggwpez** [comment]
Would also opt to remove it.
