### ISSUE TITLE
Revised how staking configurations are set

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#10938]
Currently, whenever we want to set staking parameters via [`set_staking_config`](https://paritytech.github.io/substrate/master/pallet_staking/pallet/struct.Pallet.html#method.set_staking_configs), we need to name all of the previous values as well, and double check that we are not altering them. This is a bit of a hassle. Preferably, this transaction would wrap all of its arguments in a 

```rust
enum ConfigOp<T: Default + Codec> {
    /// Don't change.
    Noop,
    /// Set to the given value.
    Set(T),
    /// remove from storage.
    Remove, 
}
```

No storage migration should be needed.

NOTE: I am open to alternative ways of doing this as well. Using an enum adds a few bytes to the transactions, which is totally fine since this is not user-dispatchable. 

I considered wrapping all arguments in another option, and if set to `None` it would not set it, but that is too ambiguous in my opinion.

**Comment by hirschenberger** [comment]
How about a `struct StakingConfig` as only parameter in combination with a builder pattern:

```rust
set_staking_config(
    origin, 
    StakingConfig::build().max_nominator_count(100).chill_threshold(None).build()
);
```

**Comment by kianenigma** [comment]
Can you expand the full example? If used for actually constructing the transaction, the builder patter won't be frequently used, as transactions are mostly built from the UI or JS.

**Comment by kianenigma** [comment]
So you are suggesting that we use an outer `Option<_>` to indicate if we want to set a value or not? I considered that, and I think a custom enum is better. 

Using a struct or not is actually not an important detail, since both a struct and named arguments convey the same logic. I prefer not using a struct since then you won't need to introduce a new type.

**Comment by hirschenberger** [comment]
My suggestion is to pass only one parameter that aggregates all values instead of an enum for each parameter.

 The outer option of the values is an implementation detail hidden to the user of the builder. When I understand it correctly that the UI is always setting all values, this inconvenience doesn't matter.

In an ideal case, the whole struct should be hidden to the user and only the builder should be able to create it.

**Comment by kianenigma** [comment]
@hirschenberger you are still thinking too much in terms of Rust API, while I am mainly aiming at making this easier when you submit a proposal from the Polkadot JS apps 😅

Say I want to keep 4 parameters the same, and change just 1. Sure, in rust code you can do `StakingConfigs::default().set(...)` and leave the rest, but Polkadot JS apps does not know what the `Default` implementaion of `StakingConfigs` is.

This is why we need something like `ConfigOp`, and then in the apps you can set 4 of the parameters to `ConfigOp::Noop`, and only one to `ConfigOp::set`.

**Comment by kianenigma** [comment]
> So the ConfigOp approach makes sense. What about the Remove case you initially mentioned? It's not possible with the current API.

Correct, but with `ConfigOps` we can support this as well.

**Comment by hirschenberger** [comment]
Ok, should I take over? Maybe I find an alternative approach while working on it?
