### ISSUE TITLE
Force Remove Approved Extrinsic in Treasury

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#10952]
We should have a function that is callable by Root or the `RejectOrigin` in the Treasury Pallet which allows us to remove a previously approved treasury item that is waiting in the approval queue.

A nice function to have in the case anything changes after the approval happens where it would make sense to not actually fund the proposal.

**Comment by guzzit** [comment]
Hi @shawntabrizi, I am attempting this issue.
