### ISSUE TITLE
Remove `CanAuthorWith`

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#10966]
We have this `CanAuthorWIth` trait that is being used by the authorship implementations to find out if the node can author with the current on chain runtime. Currently we are using the native runtime version for this. With the removal of the native runtime, we will not have the native runtime version anymore. So, we can not use this one to check if the current node can build with the on chain runtime. As this feature was not really used that much and it was only about a nice way of telling "your node is outdated". If the authoring interface is broken, it would fail anyway to produce new blocks etc.

**Comment by AurevoirXavier** [comment]
Just remove all the related code simply?
Would like to know more detail.

**Comment by bkchr** [comment]
What details are you interested in?
