### ISSUE TITLE
`try_append` for StorageValue

### ISSUE THREAD

**Issue by stanly-johnson** [paritytech/substrate#10961]
It would be nice to have a `try_append` function for [StorageValue](https://docs.substrate.io/rustdocs/latest/frame_support/storage/trait.StorageValue.html) allowing to directly work with [BoundedVec](https://crates.parity.io/frame_support/storage/trait.StorageTryAppend.html) inside.

**Comment by KiChjang** [comment]
https://github.com/paritytech/substrate/blob/f4fb93fdccc2edc38a394fc42a93ab73974fc4f1/frame/support/src/storage/mod.rs#L1307-L1326
