### ISSUE TITLE
Revert consensus related data on CLI "revert" command

### ISSUE THREAD

**Issue by davxy** [paritytech/substrate#10962]
The CLI has a command to revert the node state at most down to the last finalized block.

Example to [revert](https://github.com/paritytech/substrate/blob/f4fb93fdccc2edc38a394fc42a93ab73974fc4f1/client/cli/src/commands/revert_cmd.rs#L46) 3 blocks:

    $ node-template revert --dev --base-path mydata --pruning archive -- 3

Currently, the "revert" procedure is limited to the state and leaves by just forwarding the call to the backend [revert](https://github.com/paritytech/substrate/blob/f4fb93fdccc2edc38a394fc42a93ab73974fc4f1/client/db/src/lib.rs#L2031) routine.

The backend [revert](https://github.com/paritytech/substrate/blob/f4fb93fdccc2edc38a394fc42a93ab73974fc4f1/client/db/src/lib.rs#L2031) procedure has the following constraints:
- rollback is started from the local chain "best" block
- the state for the given block should exist. In other words, the state has not been wiped because of the pruning policy previously adopted to run the node).

The current limited scope may leave some of the node's auxiliary structures in an inconsistent state, e.g. because some aux data is referencing something that has been removed.

The focus of this issue is to properly revert the node state by also reverting all the auxiliary structures that somehow may be influenced by the state revert procedure.

Examples of such structures are:
- [x] BABE's [EpochChanges](https://github.com/paritytech/substrate/blob/f4fb93fdccc2edc38a394fc42a93ab73974fc4f1/client/consensus/epochs/src/lib.rs#L442) written on block import via the [write_epoch_changes](https://github.com/paritytech/substrate/blob/f4fb93fdccc2edc38a394fc42a93ab73974fc4f1/client/consensus/babe/src/aux_schema.rs#L101).
- [x] GRANDPA's [AuthoritySet](https://github.com/paritytech/substrate/blob/f4fb93fdccc2edc38a394fc42a93ab73974fc4f1/client/finality-grandpa/src/authorities.rs#L149) written on block import via the [update_authority_set](https://github.com/paritytech/substrate/blob/f4fb93fdccc2edc38a394fc42a93ab73974fc4f1/client/finality-grandpa/src/aux_schema.rs#L416).
- [x] States related to parachains management (to investigate).

**Comment by davxy** [comment]
@andresilva @bkchr

**Comment by rphmeier** [comment]
> States related to parachains management (to investigate).

Doable, but this is going to get very, very involved.

**Comment by davxy** [comment]
Follow up for Polkadot specific tasks https://github.com/paritytech/substrate/issues/11178
