### ISSUE TITLE
Investigate ways to improve querying the bags list over RPC

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate#10976]
This issue is meant to track efforts to improve the performance of queries to the bags list from the both the client (e.g. UI) and the node side.

From the node side we can look into creating a specialized RPC that does tasks like group a bag and its nodes into one query or provides some metadata about a bag, like its length and how many nodes are displaced.

From the client side we can look into exactly what the various needs are and benchmark different querying approaches in meeting them.

cc @rossbulat @kianenigma

**Comment by kianenigma** [comment]
A bit too opaque, closing to open something more tangible when needed.
