### ISSUE TITLE
How does `#[runtime_interface]` convert trait methods into HostFunctions?

### ISSUE THREAD

**Issue by YHM404** [paritytech/substrate#10985]
I'm researching substrate runtime, I found out that [`#[runtime_interface]`](https://github.com/paritytech/substrate/blob/master/primitives/runtime-interface/proc-macro/src/lib.rs#L77) is used to implement [`HostFunctions`](https://github.com/paritytech/substrate/blob/master/primitives/wasm-interface/src/lib.rs#L419), but its implementation is too complicated.
Could you describe `#[runtime_interface]` implementation details？

**Comment by bkchr** [comment]
Have you read the docs of the `sp-runtime-interface` crate? There is everything documented, with examples.
