### ISSUE TITLE
Remove unneeded Deserialize code once JSONRPC crate is fixed

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1098]
JSONRPC crate currently is broken in that it requires `Serialize` and `Deserialize` regardless of whether a type features only as an argument or a return.

**Comment by gavofyork** [comment]
@tomusdrw is there any progress on this in JSONRPC crate?

**Comment by tomusdrw** [comment]
@gavofyork yup, it's backward compatible. Example how to set up `Deserialize` only bound here: https://github.com/paritytech/jsonrpc/pull/336/files#diff-d41fba166fb0f3c701b3199592549237R13
Requires implementation in substrate now.
