### ISSUE TITLE
Make pallet-bags-list `VoteWeight` type be generic. 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#10990]
Because in some cases, we might want to use the actual Balance (u128), or other numeric types as the vote weight. The best way to start is: 

First, fix [`SortedListProvider`](https://github.com/paritytech/substrate/blob/da534d7f945c72b373f157826a95786543a6ec9c/frame/election-provider-support/src/lib.rs#L365): replace the hardcoded `VoteWeight` with `type Value` (avoiding the term `Weight` since it has other meanings in frame), which probably only needs to be bound by `Codec + Ord` or a few other traits (`sp-arithmetic` has useful traits for this). 

Also, rename `VoteWeightProvider` to `NodeValueProvider`. 

This should force the compiler to show you the rest of the way.

**Comment by guzzit** [comment]
Hi @kianenigma, I'd like to attempt this

**Comment by kianenigma** [comment]
> Hi @kianenigma, I'd like to attempt this

sure, although I need this relatively soon, so I might beat you to it if you don't have a PR within a week or so ;)

**Comment by kianenigma** [comment]
closed in https://github.com/paritytech/substrate/pull/10997
