### ISSUE TITLE
sp-core's `full_crypto` feature flag breaks `no_std` builds.

### ISSUE THREAD

**Issue by clangenb** [paritytech/substrate#11005]
Since commit: https://github.com/paritytech/substrate/commit/bfc6fb4a95adccf96dadbe5e5e6bb8605d5a2c01

This is because, the secp256k1 `global-context` feature implies `std`:

https://github.com/paritytech/substrate/blob/b36030a6e8c21af9f18bb0d6a667188fac0dbc47/primitives/core/Cargo.toml#L59

I currently lack the overview if disabling `global-context` in `full_crypto` would be a reasonable choice. My intuition would say it is enough for SGX-enclave because we are already  in an enhanced security environment.

**Comment by bkchr** [comment]
Ty for the report. It will be fixed with: https://github.com/paritytech/substrate/pull/11006

**Comment by clangenb** [comment]
Wow, thanks for the immediate fix!
