### ISSUE TITLE
The command `cargo build --release --features with-tracing` fails and does not compile the runtime

### ISSUE THREAD

**Issue by Imod7** [paritytech/substrate#11000]
### Description
I am trying to compile the runtime with `cargo build --release --features with-tracing` but I get an error message and nothing is being compiled. I was trying to compile with this command so I can have the `tracing` options enabled in my WASM as mentioned here [Creating-WASM-runtimes-with-Tracing-Enabled](https://github.com/paritytech/substrate-archive/wiki/5.%29-Creating-WASM-runtimes-with-Tracing-Enabled) in the `substrate-archive` repo.

### Steps to Reproduce
1. I git cloned the polkadot repo from here https://github.com/paritytech/polkadot (version 0.9.17)
2. I open the `cargo.toml `file in the folder runtime > `polkadot` and I add the following line : 
   `with-tracing = ["frame-executive/with-tracing", "sp-io/with-tracing"]`
   under `[features] `
3. I do the same (so step 2) also for the `cargo.toml `file in the folder runtime > `kusama`
4. I run the command `cargo build --release --features with-tracing` to compile the runtime with tracing 
5. I get the following error in my terminal 

> error: none of the selected packages contains these features: with-tracing

 3.1 If after step 3 I edit the `cargo.toml `file also from the folder runtime > `common` and then execute the `cargo build` command again, I get a different error which is the following : 

```
error: failed to load manifest for workspace member `/Users/imod7/Documents/polkadot-full-node/cli`

Caused by:
  failed to load manifest for dependency `polkadot-node-core-pvf`

Caused by:
  failed to load manifest for dependency `polkadot-node-subsystem-util`

Caused by:
  failed to load manifest for dependency `polkadot-node-metrics`

Caused by:
  failed to load manifest for dependency `polkadot-test-service`

Caused by:
  failed to load manifest for dependency `polkadot-runtime-common`

Caused by:
  failed to parse manifest at `/Users/tiny_imod/Documents/Parity/polkadot-full-node/runtime/common/Cargo.toml`

Caused by:
  feature `with-tracing` includes `frame-executive/with-tracing`, but `frame-executive` is not a dependency
```

- After the error messages, the program exits.

**Comment by emostov** [comment]
Looks like `frame-executive` is no longer used:

> Caused by:
  feature `with-tracing` includes `frame-executive/with-tracing`, but `frame-executive` is not a dependency
  
  I don't know the details, but the first thing I would try is changing `with-tracing = ["frame-executive/with-tracing", "sp-io/with-tracing"]` to `with-tracing = ["frame-executive/with-tracing", "sp-io/with-tracing"]`.

**Comment by emostov** [comment]
The other thing you could do is look through all the deps for polkadot and check which ones have the `with-tracing` feature, then add those deps with the tracing feature enabled.

**Comment by emostov** [comment]
This would help give some context to how features work in cargo: https://doc.rust-lang.org/cargo/reference/features.html

**Comment by bkchr** [comment]
No update here for quite some time. Closing this issue.
