### ISSUE TITLE
the trait `WrapperTypeDecode` is not implemented for `NativeOrEncoded<NeverNativeValue>`

### ISSUE THREAD

**Issue by liuchengxu** [paritytech/substrate#11046]
```
   Compiling sp-core v6.0.0 (/home/xlc/src/github.com/paritytech/substrate/primitives/core)
error[E0277]: the trait bound `NativeOrEncoded<NeverNativeValue>: WrapperTypeDecode` is not satisfied
   --> primitives/core/src/lib.rs:477:4
    |
477 |             Decode::decode(&mut b"dummy_encoded".to_vec().as_slice()).unwrap();
    |             ^^^^^^^^^^^^^^ the trait `WrapperTypeDecode` is not implemented for `NativeOrEncoded<NeverNativeValue>`
    |
    = note: required because of the requirements on the impl of `parity_scale_codec::Decode` for `NativeOrEncoded<NeverNativeValue>`

For more information about this error, try `rustc --explain E0277`.
```

```diff
diff --git a/primitives/core/src/lib.rs b/primitives/core/src/lib.rs
index b7c8b69e8..0aaeb8623 100644
--- a/primitives/core/src/lib.rs
+++ b/primitives/core/src/lib.rs
@@ -466,3 +466,14 @@ macro_rules! impl_maybe_marker {
 // The maximum possible allocation size was chosen rather arbitrary, 32 MiB should be enough for
 // everybody.
 pub const MAX_POSSIBLE_ALLOCATION: u32 = 33554432; // 2^25 bytes, 32 MiB
+
+#[cfg(test)]
+mod tests {
+       use super::*;
+
+       #[test]
+       fn test_NativeOrEncoded_decode() {
+               let decoded: NativeOrEncoded<NeverNativeValue> =
+                       Decode::decode(&mut b"dummy_encoded".to_vec().as_slice()).unwrap();
+       }
+}
```

Required for the initial feature request #10922 as I want to extract the inner actual return value of the execution https://github.com/paritytech/substrate/blob/f6679ddd31f68e9f1578064d58a246130c27026b/primitives/state-machine/src/lib.rs#L627

**Comment by bkchr** [comment]
`NativeOrEncoded` is a type holding either the native representation of a type or the same type encoded. However, you can not encode/decode the `NativeOrEncoded` type. It makes no sense.

**Comment by liuchengxu** [comment]
Hmm, I just realized that my original problem could be caused by something else. As mentioned in the first comment, I want to extract the execution result and then decode the return value of the execution. I tried directly decoding the return value of [execution_proof_check](https://github.com/paritytech/substrate/blob/142eeeb5545a03edd69d99cae0d39fc0e8a64973/primitives/state-machine/src/lib.rs#L632), but the decoded value is not what I expected. Until I somehow skip the first element of the execution result while decoding: https://github.com/subspace/subspace/commit/6b62b48ce577b90402c8f5bb026ed02f5abb65fa#diff-e9ff0c878f7a20ef320806abd54a33a355c01eb7aa4442dcb3e57f0acec4aa63R219, I got what I want(`post_execution_root` is the storage root after applying the extrinsic). Any explanation for this? @bkchr

**Comment by liuchengxu** [comment]
Hmm, I just realized that my original problem could be caused by something else. As mentioned in the first comment, I want to extract the execution result and then decode the return value of the execution. I tried directly decoding the return value of [execution_proof_check](https://github.com/paritytech/substrate/blob/142eeeb5545a03edd69d99cae0d39fc0e8a64973/primitives/state-machine/src/lib.rs#L632), but the decoded value is not what I expected. Until I somehow skip the first element of the execution result while decoding: https://github.com/subspace/subspace/commit/6b62b48ce577b90402c8f5bb026ed02f5abb65fa#diff-e9ff0c878f7a20ef320806abd54a33a355c01eb7aa4442dcb3e57f0acec4aa63R219, I got what I want(`post_execution_root` is the storage root after applying the extrinsic). Any explanation for this? @bkchr

**Comment by bkchr** [comment]
The problem is that your function returns a `Vec<u8>`. So, you need to:

```
let data = Vec::<u8>::decode(res);
let intermediate_hash = Hash::decode(&mut data[..]);
```

This will fix your problem. The leading byte is the `Compact<u32>` containing the length of the vector.

**Comment by liuchengxu** [comment]
@bkchr Thank you for the answer! Didn't realize that :see_no_evil:
