### ISSUE TITLE
Address some clippy remarks

### ISSUE THREAD

**Issue by hirschenberger** [paritytech/substrate#11054]
Clippy shows a lot of remarks all over the codebase. Some are minor or just style considerations but some make sense. E.g. "unnecessary mut", "unnecessary clones", ""unnecessary lifetime annotations", "double referenced fn params", "condition logic simplifications" or "merging nested if clauses".

I'd like to work through the code to fix some of these. 

How should I proceed to make it easier to review?

* One big commit in one PR.
* One commit for each lint type in one PR.
* Multiple PRs per lint type

**Comment by shawntabrizi** [comment]
I think one big PR is okay, see: https://github.com/paritytech/substrate/pull/10570

cc @gilescope

**Comment by bkchr** [comment]
But please ensure that you provide a pr that it not just doing what the computer is saying, because computer is not always right.

**Comment by hirschenberger** [comment]
> But please ensure that you provide a pr that it not just doing what the computer is saying, because computer is not always right.

I read your remarks in https://github.com/paritytech/substrate/pull/10570
I try to keep it sane

**Comment by gilescope** [comment]
Full disclosure: I'd like to see clippy added to polkadot repo in a gently way this year also. I've not seen any push back on the clippy rules we currently have (for polkadot I would start just with the correctness category).

**Comment by hirschenberger** [comment]
@bkchr Question on lint: [Clone-on-copy](https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy)

As I read from the former issue's context and comments: these extra clones should be left-as-is in functions where this cloned type is a generic parameter, bc. of future type changes or uses with non-copy types, right?

**Comment by bkchr** [comment]
> @bkchr Question on lint: [Clone-on-copy](https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy)
> 
> As I read from the former issue's context and comments: these extra clones should be left-as-is in functions where this cloned type is a generic parameter, bc. of future type changes or uses with non-copy types, right?

If the generic type implements `Copy`, you can for sure remove `.clone()`.



> Another Question on lint: [redundant-closure](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure)
> 
> This may also be controversial. It may save some code-size or compilation cycles but harms readability bc. it's not directly clear that the parameter is a function and not a variable:
> 
> ```diff
> -               cmd.output_analysis.clone().try_into().map_err(|e| io_error(e))?;
> +               cmd.output_analysis.clone().try_into().map_err(io_error)?;
> ```

Looks good.
