### ISSUE TITLE
Make referenda pallet and conviction-voting instantiable

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#11056]
We would like to setup multiple tracks where each of them are voted by different tokens.
One simple solution is make referenda pallet and conviction-voting instanceable so that we can have a pair of them for each token type.

**Comment by Doordashcon** [comment]
This will require writing tests?

**Comment by bkchr** [comment]
Not really.

**Comment by Doordashcon** [comment]
Noted, would like to attempt this issue

**Comment by bkchr** [comment]
Okay

**Comment by xlc** [comment]
@Doordashcon just so you know we already have PR for this.

**Comment by dzmitry-lahoda** [comment]
btw if to make a map from track/origin to asset id and use fungibles trait  referenda can be made multi asset in several lines
