### ISSUE TITLE
How to build a fully decentralized poker platform - Hiring developers $$

### ISSUE THREAD

**Issue by ERC20s** [paritytech/substrate#11070]
Hey!
I'm trying to build a fully decentralized non-profit WSOP style texas holdem poker sidechain.

It would need private random numbers that can then be provable..
It would need to process a bunch of information like raise, check, fold, players, pot size, etc..
The obviously have the game logic built in...

Where do i start?
PS I'm hiring if anyone wants to shoot me a message and hack this out

**Comment by bkchr** [comment]
This isn't a job board. 


And you could also use the search to find these kind of information: https://docs.substrate.io/how-to-guides/v3/pallet-design/randomness/
