### ISSUE TITLE
`import-blocks` high mem usage

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#11071]
Importing the whole polkadot snapshot in archive mode with the `import-blocks` command uses about 74 Gb atm.    
![Screenshot from 2022-03-17 22-52-37](https://user-images.githubusercontent.com/10380170/159135491-81e8280e-2e1a-4ad9-865a-fce17c6d2281.png)

Command used:  
```sh
cat dot-9.5M-blocks.bin | ./target/release/polkadot import-blocks --binary --pruning archive --db paritydb
```
I will try it again with Valgrind memcheck after [bytehound](https://github.com/koute/bytehound) slowed it down too much.  Maybe I also used it incorrectly :man_shrugging:. 
Instead of upload the whole 41 Gb snapshot, maybe it is already reproducible with the first [100k Polkadot blocks](https://drive.google.com/file/d/16gXcg1VqFfzzYss3aqk5IwChiGF1O1u4/view?usp=sharing).

**Comment by bkchr** [comment]
Wait. You are piping the entire file. That is currently implementing of reading everything into memory. 

The simplest solution is to just run with `--input`

**Comment by ggwpez** [comment]
> Wait. You are piping the entire file. That is currently implementing of reading everything into memory.
> 
> The simplest solution is to just run with `--input`

Oh, I did not know that flag :laughing:. Thanks for the MR!
