### ISSUE TITLE
Allow `BoundedVec` and `BoundedBTreeMap` etc. use `u8` and `u16` as bounds.

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11076]
Currently, we only allow `u32`, which is reasonable, but with some generic gymnastics, you can allow `<B: Into<u32>, T: Get<B>>` instead of `<T: Get<u32>>`.

**Comment by bkchr** [comment]
What would be the benefit of this?

**Comment by kianenigma** [comment]
https://github.com/paritytech/substrate/blob/kiz-multi-block-election/frame/election-provider-support/src/lib.rs#L264

**Comment by KiChjang** [comment]
I honestly find this to be really ugly as it adds another type parameter to `BoundedVec`, and it isn't obvious at first glance what the extra `u16` parameter is about in `BoundedVec<u8, u16, MaxLen>`, and it'll be even worse if the `B` parameter happens to be the same type as the value type. If const eval is evolved to the point where we could drop the `Get`, then we should really use const generics, instead of trying to wrestle with an additional type parameter.

**Comment by bkchr** [comment]
Yeah looking at the current draft pr, this just looks like some huge overhead on code.

**Comment by jorgeantonio21** [comment]
@KiChjang I understand your point and I agree with it. I thought slightly in a way to deal with this fact and I think it should go along with the following lines

```
pub trait Get {
    type T;
    const val: Self::Type;
}
// implementations of Get
pub struct GetUsize<const val: usize>;
impl<const val: usize> Get for GetUsize<val> {
    type Type = usize;
    const val = val;
}
// etc

pub struct BoundedVec<T, S>(Vec<T>, PhantomData<S>);
impl<T, S: Get> Trait for BoundedVec<T, S>
where
    S::Type: Unsigned,
{ /* ... */ }
```

However, this approach might lead with backward/forward compatibility issues, when using `BoundedVec` down the road with other specific bound types (that do not implement the `Get` trait as in the above). Let me know your thoughts.

**Comment by KiChjang** [comment]
I don't think you need to modify the `Get` trait to implement this:

```rust
pub struct GetUsize<const N: usize>;
impl<const N: usize> Get<usize> for GetUsize<N> {
    fn get() -> usize { N }
}
```

If the type `T` needs to be a `u32`, then we can just modify it as follows:

```rust
impl<const N: usize> Get<u32> for GetUsize<N> {
    fn get() -> u32 { N as u32 }
}
```

**Comment by shabanovd** [comment]
Maybe this was
```
pub trait IntoBound {
	fn bound() -> usize;
}

impl<T> IntoBound for T
	where T: Get<u32>
{
	fn bound() -> usize {
		usize::try_from(T::get()).unwrap_or(0)
	}
}
```
it do cover u8, u18 and u32 (if I do not miss something)

Here the [commit](https://github.com/shabanovd/substrate/commit/27871b9a56e0a140cf3ae2acf9c6493bf5e0dce0) with [tests](https://github.com/shabanovd/substrate/blob/into_bound/frame/support/src/storage/bounded_vec.rs#L871-L893)

**Comment by KiChjang** [comment]
I'd really rather not create new traits for this, as we can make it work as intended simply by creating more structs instead.

Moreover, the point I raised initially still stands -- we really should just be using const generics when it is mature enough, and I mean the following:

```rust
pub struct BoundedVec<T, const N: u32>(Vec<T>, N);
```

**Comment by shabanovd** [comment]
I wish it to be possible. Missing part is 
```rust
#![feature(generic_const_exprs)]

pub struct BoundedVec<T, const S: u32>(Vec<T>);

trait Foo {
    const N: u32;
    fn foo() -> BoundedVec<u8, Self::N>;
}
```
and it do compile ever at nightly.

**Comment by shabanovd** [comment]
Turns out it works a little differently
```rust
#![feature(generic_const_exprs)]

pub struct BoundedVec<T, const S: u32>(Vec<T>);

trait Foo {
    const N: u32;
    fn foo() -> BoundedVec<u8, { Self::N }>;
}
```

**Comment by kianenigma** [comment]
After trying this out once, it proved to not be worth the extra hassle.
