### ISSUE TITLE
`seal_is_reentrant` for `contract-pallet`

### ISSUE THREAD

**Issue by xgreenx** [paritytech/substrate#11082]
`seal_is_reentrant` returns true if the contract presents in the call stack more than one time. More information about usage of that method in the [comment](https://github.com/paritytech/substrate/issues/11018#issuecomment-1072607951).

How that method should work for the `delegate_call` case? I will expect that the delegate call doesn't change the reentry state.

**Comment by athei** [comment]
I think we should implement it in a more general way: `seal_reentrant_count`. It returns how often the currently executing contract exists on the call stack in addition to the calling instance: So a value of `0` means no reentrancy.

> How that method should work for the delegate_call case? I will expect that the delegate call doesn't change the reentry state.

I suppose so. Delegated calls should be counted as the same instance.

**Comment by athei** [comment]
Resolved by https://github.com/paritytech/substrate/pull/12695
