### ISSUE TITLE
Copy weight files into `node-template`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#11090]
Analogous to https://github.com/paritytech/polkadot/pull/5064  
Instead of using the default weights from `frame_support`, copy the files over to encourage developers to benchmark their own weights.  
Concretely `block_weight.rs`, `extrinsic_weight.rs`, `rocksdb_weight.rs` and `paritydb_weight.rs`.  

The parachain template needs this as well.

**Comment by tifecool** [comment]
@ggwpez  On this. Should the copied weights replace the frame_support weights anywhere?

**Comment by bkchr** [comment]
@shawntabrizi so we can also close this issue?

**Comment by shawntabrizi** [comment]
Yes. My opinion at this moment is that the node template should be minimal, and just point to the "default substrate weights" for now.
