### ISSUE TITLE
Benchmark different implementations of `Solver`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11111]
All structs that implement `NposSolver` are currently returning a naive `max_block` weight, just because they don't have any better way to estimate them. 

The weight of these implementations are not really runtime dependent, we can and should still leverage benchmarking pipeline. So, I propose the follwoing: 

2. Create a sub-create in `election-provider-support` called `onchain-config`. This will have a `trait WeightInfo`, similar to all other pallets, with 2 functions

```
trait WeightInfo {
  fn phragmen(<input>) -> Weight;
  fn phragmms(<input>) -> Weight;
}
```

4. This is a raw pallet, with nothing in it other than a:

```
trait Config: frame_system::Config { 
  type WeightInfo: WeightInfo;
  // ++ everything else that's in `trait Config` in `onchain.rs` now.
  /// The accuracy used to compute the election:
  type Accuracy: PerThing128;
  /// Something that provides the data for election.
  type DataProvider: ElectionDataProvider<
    AccountId = Self::AccountId,
    BlockNumber = Self::BlockNumber,
  >;
}
```

6. Then you write benchmarks for this pallet, just as you would do for any other pallet, trying to fulfill the aforementioned `trait WeightInfo`. If any further information is needed to conduct the benchmarks accurately, you can pass in more types to `trait Config`.
7. As you can probably guess now, the existing `trait Config` in `onchain.rs` can be removed. Any struct wanting to be a `OnchainExecution` needs to implement to new `onchain_config::Config` pallet config. 

The main thing that I didn't cover is what is `<input>` in the above snippet. These should be the components that dictate the complexity of phragmen, or similar algorithms. I have tried to do this once in the past, and my conclusion was that this is a function of 3 things: 

1. number of voters
2. number of candidates
3. number of edges (votes per voter)

A similar benchmark was done here: https://github.com/paritytech/substrate/blob/master/frame/elections-phragmen/src/benchmarking.rs#L454

For more general info about benchmarking, see: https://docs.substrate.io/v3/runtime/benchmarking/, https://www.shawntabrizi.com/substrate-graph-benchmarks/docs/#/

**Comment by georgesdib** [comment]
I am working on this.
