### ISSUE TITLE
GRANDPA: Proper equivocation handling and misbehavior reporting.

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1112]
On the runtime side: Alter the `srml-grandpa` module to check signatures on grandpa messages and integrate with consensus/slashing on this misbehavior.

Depends on https://github.com/paritytech/finality-grandpa/issues/26

On the node side, craft, sign, and queue equivocation-report transactions when the `finality_grandpa::Environment` methods for `prevote_equivocation` and `precommit_equivocation` are called.

related: #1065

**Comment by rphmeier** [comment]
(srml-grandpa is currently not implemented except in the `rh-grandpa-chain` branch)

**Comment by philipstanislaus** [comment]
@gavofyork is this still an issue? Trying to determine if there are any red flags to launching Centrifuge's mainnet shortly. Thanks!

**Comment by HCastano** [comment]
@philipstanislaus Equivocation handling is being worked on in #3868.

**Comment by andresilva** [comment]
Fixed in #3868.
