### ISSUE TITLE
Support custom externality extension

### ISSUE THREAD

**Issue by liuchengxu** [paritytech/substrate#11122]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Not a bug, but a feature request.

We'd like to call the execution proof API within the runtime hence an externality extension is need. Currently, I don't see there isn't a way exposed to add a custom externality extension.

https://github.com/paritytech/substrate/blob/69079b58579ea36812c4a375a118f27aac0fb281/client/service/src/builder.rs#L271-L275

But thanks to the API `set_extensions_factory`, it can be easily done by adding an optional argument to `new_full_parts` where the custom extension can be injected.

```Rust
impl ExtensionsFactory for CustomExtensions {
    fn extensions_for(&self, _: sp_core::offchain::Capabilities) -> Extensions {
        let mut exts = Extensions::new();
        exts.register(CustomExt);
        exts
    }
}
```

```diff
diff --git a/client/service/src/builder.rs b/client/service/src/builder.rs
index f4ff93243..287182b73 100644
--- a/client/service/src/builder.rs
+++ b/client/service/src/builder.rs
@@ -236,6 +236,7 @@ pub fn new_full_parts<TBl, TRtApi, TExec>(
        config: &Configuration,
        telemetry: Option<TelemetryHandle>,
        executor: TExec,
+       extensions_factory: Option<Box<dyn sc_client_api::execution_extensions::ExtensionsFactory>>,
 ) -> Result<TFullParts<TBl, TRtApi, TExec>, Error>
 where
        TBl: BlockT,
@@ -274,6 +275,10 @@ where
                        sc_offchain::OffchainDb::factory_from_backend(&*backend),
                );

+               if let Some(factory) = extensions_factory {
+                       extensions.set_extensions_factory(factory);
+               }
+
                let wasm_runtime_substitutes = config
                        .chain_spec
                        .code_substitutes()
```

Not sure if it's good to you from a bigger picture, I can prepare a PR if you think it's acceptable.

**Comment by bkchr** [comment]
You can use [this](https://github.com/paritytech/substrate/blob/7a09b82772b0597cdae224f4b124d660dda9e82b/client/service/src/client/client.rs#L1405-L1407) to get access to the `ExecutionExtensions` to then call `set_extensions_factory` :)
