### ISSUE TITLE
AsEnsureOriginWithArg no longer available on frame_support

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#11139]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

```
pub use frame_support::traits::AsEnsureOriginWithArg
``` 

No longer available 
Error
^^^^^^^^^^^^^^^^^^^^^ no `AsEnsureOriginWithArg` in `traits`

### Steps to reproduce

Clone Substrate Node Template 
Make Sure to use frame_spport 4.0.0 dev version 
Try to use frame_support::traits::AsEnsureOriginWithArgs

**Comment by bkchr** [comment]
It is exported here: https://github.com/paritytech/substrate/blob/41567c30da77a2546a90c1049042ebd7b0b09bc4/frame/support/src/traits.rs#L97

I assume you are maybe using an older commit of Substrate?

**Comment by Kalanamith** [comment]
use Substrate version 4.0.0-dev

**Comment by ggwpez** [comment]
I think the substrate node template is using an older version, looking into the [Cargo.toml](https://github.com/substrate-developer-hub/substrate-node-template/blob/7c342164629e7871b4ee3f09de3d4e130bef6543/Cargo.lock#L1556) shows that it uses `32a4fe01` which does not have thing exposed:  
https://github.com/paritytech/substrate/blob/32a4fe01f110a755bf22eb8f803cdfd7052d4f8b/frame/support/src/traits.rs#L92  
as it was just recently exposed [here](https://github.com/paritytech/substrate/commit/f6679ddd31f68e9f1578064d58a246130c27026b#diff-fdd2311fe6234ac84af9af387c1e209f64ad5783ba5256661f5d424a4caba59dR94).  
So the Node template probably needs to be updated to use the newer Substrate version

**Comment by Kalanamith** [comment]
@ggwpez  it uses the Substrate version 4.0.0-dev if um not mistaken.

**Comment by bkchr** [comment]
But you don't use the correct commit. The version `4.0.0-dev` can be found for multiple different git commits.

**Comment by Kalanamith** [comment]
would like to know the solution to get this work with the node template? to go with the specified git commit hash?

**Comment by bkchr** [comment]
You need to get a newer version of the node template. That basically uses a more recent commit.

**Comment by Kalanamith** [comment]
Please upload the tutorial as well ,Cheers!

**Comment by bkchr** [comment]
Can you please open an issue in the relevant tutorial repo to update this? Ty!
