### ISSUE TITLE
Better error message when `Benchmark_benchmark_metadata` it not found

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#11153]
I think we can improve here so that questions like [these](https://substrate.stackexchange.com/questions/868/error-running-benchmarks-on-substrate-node) do not happen.  

Could become part of #11140

**Comment by yourarj** [comment]
@ggwpez I would like to take this up. Can we discuss?

**Comment by ggwpez** [comment]
@yourarj I appreciate your motivation, but for this issue it is probably not worth since it is so small.  
Maybe https://github.com/paritytech/substrate/issues/11141 is better for you?  
In general you can look for issues with the "Z1-mentor" tag.

**Comment by yourarj** [comment]
@ggwpez Thanks will have a look. This would be my very first contribution to open source project. I hope you'll assist me through this. If yes I'll be glad to take it up.
