### ISSUE TITLE
What is the relationship between `sandbox`, `executor` and `runtime`?

### ISSUE THREAD

**Issue by EmisonLu** [paritytech/substrate#11177]
I was recently reading the code for substrate wasmtime, but I ran into some problems. I don't really understand the difference between `runtime` and `sandbox`.

For example, in the file `substrate/client/executor/wasmtime/src/runtime.rs`, we can call the method `call()` of `WasmtimeInstance` to execute the functions in the wasm instance. Also, in the `substrate/client/executor/wasmtime/src/host.rs` file, is the `invoke()` function implemented for `HostContext` also executing functions in the wasm instance? 

What is the difference between the runtime instance and the sandbox instance?

Thanks!

**Comment by ggwpez** [comment]
I think this is a great question for our Stackexchange :point_right: https://substrate.stackexchange.com/  
Would you mind asking it over there again?

**Comment by EmisonLu** [comment]
No problem!
