### ISSUE TITLE
How to use pyo3 Library in substrate

### ISSUE THREAD

**Issue by SoyEstrella** [paritytech/substrate#11172]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I imported the pyo3 library into the substrate code, however the code cannot be compiled, the error reports under Windows system are as follows:
```
error: failed to run custom build command for `pyo3-ffi v0.16.2`

  Caused by:
    process didn't exit successfully: `C:\Users\19735\Desktop\offchain_worker_2\target\debug\wbuild\node-template-runtime\target\release\build\pyo3-ffi-ee5b2633fd18a1d7\build-script-build` (exit code: 101)
    --- stdout
    cargo:rerun-if-env-changed=PYO3_CROSS
    cargo:rerun-if-env-changed=PYO3_CROSS_LIB_DIR

    --- stderr
    thread 'main' panicked at 'Path does not exist: Os { code: 267, kind: NotADirectory, message: "目录名称无效。
" }', C:\Users\19735\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\pyo3-build-config-0.16.2\src\" }', C:\Users\19impl_.rs:992:33
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  warning: build failed, waiting for other jobs to finish...
  error: build failed
```
So I searched for the solution and I found this issue: [https://github.com/PyO3/pyo3/issues/1221](url)
I switched the operating system to Linux, and followed the instructions of this issue, however I met another error:
`error: your Rust architecture (32-bit) does not match your python interpreter (64-bit)`

I guess the answer is as @davidhewitt said in issue: I should disable check_target_architecture when cross-compiling. But I do not know how to achieve it.

### Steps to reproduce

1. Compiled Python 3.10.4 with
```
./configure --enable-shared
make
```
2. Setup PYO3_CROSS flags
```
export PYO3_CROSS_PYTHON_VERSION=3.10
export PYO3_CROSS_INCLUDE_DIR=/home/Python-3.10.4/Include
export PYO3_CROSS_LIB_DIR=/home/Python-3.10.4/build/lib.linux-x86_64-3.10
```
3. Part of lib.rs of the pallet
```
#![cfg_attr(not(feature = "std"), no_std)]

use pyo3::prelude::*;
use pyo3::types::IntoPyDict;

impl<T: Config> Pallet<T> {
	fn hello() -> PyResult<()> {
		Python::with_gil(|py| {
			let sys = py.import("sys")?;
			let version: &str = sys.getattr("version")?.extract()?;
			let locals = [("os", py.import("os")?)].into_py_dict(py);
			let code = "os.getenv('USER') or os.getenv('USERNAME') or 'Unknown'";
			let user: &str = py.eval(code, None, Some(&locals))?.extract()?;
			// println!("Hello {}, I'm Python {}", user, version);
			log::info!("Hello {}, I'm Python {}", user, version);
			Ok(())
		})
	}
}
```

4. Part of Cargo.toml
```
[dependencies]
pyo3 = { version = "0.16.2", default-features = false, features = ["auto-initialize"] }
```

**Comment by bkchr** [comment]
Why do you want to execute python inside your runtime? That doesn't sound right :D

**Comment by SoyEstrella** [comment]
> Why do you want to execute python inside your runtime? That doesn't sound right :D

Because I want to call a library in Python, there is no corresponding implementation in rust.

**Comment by bkchr** [comment]
That is not really something we support nor want to support. I mean, if you want to build it that way, no one will stop you. However, we will not provide support for this. Sorry.

**Comment by SoyEstrella** [comment]
> That is not really something we support nor want to support. I mean, if you want to build it that way, no one will stop you. However, we will not provide support for this. Sorry.

Ok, thanks.

**Comment by ggwpez** [comment]
@SoyEstrella Compiling a Python interpreter to WASM and then incorporating that into your runtime could work.  
But just trying to call a binary from a pallet is not possible.

**Comment by SoyEstrella** [comment]
> @SoyEstrella Compiling a Python interpreter to WASM and then incorporating that into your runtime could work. But just trying to call a binary from a pallet is not possible.

Thank you, I will try it.

**Comment by burdges** [comment]
<img alt="Rust Evangelism Strike Force - Rewrite it in Rust" src="https://ih1.redbubble.net/image.1597487820.9472/st,small,507x507-pad,600x600,f8f8f8.jpg">
