### ISSUE TITLE
Split `SolutionImprovementThresholds` into two types.

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11204]
Currently, this type reads: 

https://github.com/paritytech/substrate/blob/07d8c9d50cf5b8f92d04e134b8504167313b8d44/frame/election-provider-multi-phase/src/lib.rs#L587-L590

and the problem is in that *any phase*. For technical reasons beyond the scope of this issue, we want to be able to define `SolutionImprovementThresholds`, with the exact same semantic, for the different `Signed` and `Unsigned` phases. So, we would break this type into two types. 

I think the logic change will be trivial. Some tests should be altered or added to demonstrate what the two configs do. 

Companion should set the `Signed` variant to `Default::default`, and keep the old `SolutionImprovementThresholds` for unsigned.

**Comment by georgesdib** [comment]
> @georgesdib interested?

Yes I am, please assign it to me, I will take a look.
