### ISSUE TITLE
Use weight `constants::` in the weight template

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#11215]
The weight template currently outputs something like `(x as Weight)` which is semantically not very clear.  
Changing this to `(x * constants::WEIGHT_PER_NANOS)` with the correct units would be much better.  

One possible approach:  
- Write a function that correctly formats the weight, eg. `38_000_000` becomes `38_000 * WEIGHT_PER_NANOS`
- PS: Better call this function directly from the template

`WEIGHT_PER_NANOS` is probably the only one that we can use, as it would otherwise use float point multiplication.

**Comment by hzy1919** [comment]
@ggwpez   hi , I am attempting this issue.

**Comment by ggwpez** [comment]
Ok great @hzy1919 !  

I added some possible was of implementation. Should be rather easy.

**Comment by hzy1919** [comment]
@ggwpez  Thanks for your help!  I commit a PR #11233 .

**Comment by ggwpez** [comment]
Will be drastically changed after https://github.com/paritytech/substrate/pull/10918 anyway. We can think of a better format in there.
