### ISSUE TITLE
Cannot upgrade the runtime

### ISSUE THREAD

**Issue by vovacha** [paritytech/substrate#11225]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Initially, I've raised [a support question on Substrate StackExchange](https://substrate.stackexchange.com/q/1862/1803) and @bkchr suggested opening an issue here.

Our goal is to migrate pallet code to the newer Substrate version and keep the block history (since ~ august 2020).
For such purpose, we've created a brand new repo with the new structure and newer Substrate version. Recently the code migration was finished. [Old Substrate ver. (10.02.2021)](https://github.com/paritytech/substrate/commit/49a4103f4bfef55be20a5c6d26e18ff3003c3353) -> [New Substrate ver. (14.01.2022)](https://github.com/paritytech/substrate/commit/afb74de23dfe2994e7ce38c0870efb9734e966f7)

We are trying to **upgrade the runtime** of our testnet nodes and getting the `FailedToExtractRuntimeVersion` error while calling `setCode` extrinsic. Attributes `spec_name`, `spec_version`, and `authoring_version` are the same between Wasm and native.

Since upgrading runtime didn't work, the next assumption will be to **upgrade the node** in the first place. 
We tried to do so and run the new node with the original `chain_spec`, but JSON structure was different and the error was next: `Error: Input("Error parsing spec file: unknown field `forkBlocks` at line 166 column 1")`.
I think trying to edit the `chain_spec` by removing extra keys like `forkBlocks`, `lightSyncState`, etc. leads to the new chain and losing blocks.

Is it possible to keep the blocks history in this case?

### Steps to reproduce

1. Start a new chain from [this commit (10.02.2021)](https://github.com/paritytech/substrate/commit/49a4103f4bfef55be20a5c6d26e18ff3003c3353)
2. Create a separate repo [from this commit (14.01.2022)](https://github.com/paritytech/substrate/commit/afb74de23dfe2994e7ce38c0870efb9734e966f7)
3. Generate a Wasm blob from the newer Substrate version.
4. Upgrade runtime (upgrade node).

**Comment by bkchr** [comment]
You can remove `forkBlocks` and `lightSyncState`. The genesis hash will not change as long as you not touch anything under `genesis`. Can you try this?

**Comment by vovacha** [comment]
@bkchr This is the Error after keys have been removed (dev chain). Probably the reason is that `chain_spec` contains old Wasm which is under `genesis`.
```
2022-04-14 22:47:40 Substrate Node    
2022-04-14 22:47:40 ✌️  version 3.0.0-5cd44fbb6-x86_64-linux-gnu    
2022-04-14 22:47:40 ❤️  by Substrate DevHub <https://github.com/substrate-developer-hub>, 2017-2022    
2022-04-14 22:47:40 📋 Chain specification: Development    
2022-04-14 22:47:40 🏷 Node name: Alice    
2022-04-14 22:47:40 👤 Role: AUTHORITY    
2022-04-14 22:47:40 💾 Database: RocksDb at /home/jenya/.local/share/subzero/chains/dev/db/full    
2022-04-14 22:47:40 ⛓  Native runtime: node-dev-100 (node-dev-1.tx1.au1)    
2022-04-14 22:47:41 Migrating database to a database-type-based subdirectory: '"/home/jenya/.local/share/subzero/chains/dev/db"' -> '"/home/jenya/.local/share/subzero/chains/dev/db/full"'    
Error: Service(Client(RuntimeApiError(Application(Execution(Other("Exported method AuraApi_slot_duration is not found"))))))
```

**Comment by bkchr** [comment]
I just checked and this method exists since 2018. From when is your genesis?

**Comment by vovacha** [comment]
We are testing it locally with the `chain_spec` and genesis created from the [initial Substrate version (10.02.2021)](https://github.com/paritytech/substrate/commit/49a4103f4bfef55be20a5c6d26e18ff3003c3353).
And node was upgraded from the [newer Substrate version (14.01.2022)](https://github.com/paritytech/substrate/commit/afb74de23dfe2994e7ce38c0870efb9734e966f7).

**Comment by DylanVerstraete** [comment]
I'm experiencing the same issue as @vovacha 

We are trying to migration from the initially released v3 substrate version to polkadot 0.9.18. While trying to upgrade the runtime following error was returned: 

```
 Failed to extract the runtime version from the new runtime., ,  Either calling `Core_version` or decoding `RuntimeVersion` failed.
```

**Comment by 2075** [comment]
> ts si



> 



> I just checked and this method exists since 2018. From when is your genesis?

The `chain_spec` was generated like @DylanVerstraete for the initial release of v3. our scenario is the same with an attempt to upgrade to 0.9.18. maybe we could try an "intermediate" upgrade, but I do not see any advantage (yet), as the chain_spec genesis blob and therefore its contents will stay the same.

**Comment by vovacha** [comment]
I'm going to close the issue. We've managed to upgrade the runtime and save the block history.
It's still not clear what was the exact root cause, but we've created a runtime from scratch and added all of the FRAME pallets. After upgrading the node, the runtime was upgraded successfully.

**Comment by bkchr** [comment]
Sounds good that you managed to fix it, sorry for not being very helpful here.

**Comment by mmyyrroonn** [comment]
@DylanVerstraete @vovacha @2075 @bkchr Hi, we meet the same issue here. We're trying to upgrade the substrate from released 3.0.0 to monthly-release-2021-06. How did you fix the issue?

**Comment by fruscitti-cf** [comment]
Same thing here. From tag v3.0.0 to branch polkadot-v0.97.26. The issue seems to be that the new RuntimeVersion has a new field: state_version: 0, and the old version is not able to parse it. Anyone knows any workaround? Thanks!

**Comment by bkchr** [comment]
> Same thing here. From tag v3.0.0 to branch polkadot-v0.97.26. The issue seems to be that the new RuntimeVersion has a new field: state_version: 0, and the old version is not able to parse it. Anyone knows any workaround? Thanks!

Which error exactly are you getting?

**Comment by fruscitti-cf** [comment]
> 

Dispatch Error:
{
  Module: {
    index: 0,
    error: 2
  }
}

Type:
system.FailedToExtractRuntimeVersion

Details:
 Failed to extract the runtime version from the new runtime., ,  Either calling `Core_version` or decoding `RuntimeVersion` failed.
 
 Thanks!

**Comment by DylanVerstraete** [comment]
We had the same issue, there are a lot of runtime migrations you need to apply if you want to go from v3 to latest. See https://github.com/threefoldtech/tfchain/blob/cfd5e6c39855fb6d6227746454c0d1b7bf8deb10/substrate-node/runtime/src/migrations.rs 

Also, your node needs to run the new binary before you can apply the runtime upgrade.

**Comment by bkchr** [comment]
@fruscitti-cf can you please use `SetCodeWithoutCheck` instead of `SetCode`?
