### ISSUE TITLE
Manual seal: support aura

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#11240]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The aura block authoring engine uses a pre-runtime digest, like many other consensus engines.

In order to use an aura-compatible runtime with manual seal, we need to tell manual seal how to prepare the pre-runtime digest that would typically be prepared by the aura worker. Concretely, we need an aura-specific implementation of the `ConsensusDataProvider` trait.

An analogous implementation already exists for babe: https://crates.parity.io/sc_consensus_manual_seal/consensus/babe/struct.BabeConsensusDataProvider.html

**Comment by bkchr** [comment]
Already exists: https://github.com/paritytech/substrate/blob/9461b2de04210c6c193726a745c3ec6552b4ce9f/client/consensus/manual-seal/src/consensus/aura.rs#L38

**Comment by JoshOrndorff** [comment]
Oh nice! Now I see https://github.com/paritytech/substrate/pull/10503
