### ISSUE TITLE
pallet_assets cannot be compiled into no_std

### ISSUE THREAD

**Issue by GopherJ** [paritytech/substrate#11255]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

error: cannot find macro `vec` in this scope
   --> /home/cheng/.cargo/git/checkouts/substrate-7e08433d4c370a21/174735e/frame/assets/src/functions.rs:672:46
    |
672 |         let mut dead_accounts: Vec<T::AccountId> = vec![];
    |                                                    ^^^
    |
    = note: consider importing one of these items:
            codec::alloc::vec
            scale_info::prelude::vec
            sp_std::vec

error: could not compile `pallet-assets` due to previous error

### Steps to reproduce

Just need to compile runtime with pallet_assets

**Comment by bkchr** [comment]
False alarm.
