### ISSUE TITLE
Tweak substrate-consensus-aura to be "aura_family"

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1127]
The pattern in forkful consensus algorithms of "divide time into discrete slots, somehow select a proposer for each slot, and have them author a block" is very common.

By introducing a trait for choosing the proposer-selection algorithm, we can easily convert our current Aura implementation into Ouroboros (instantiated with a VRF, maybe BLS or hash-chain) or other similar consensus algorithms.

**Comment by tomaka** [comment]
I guess this has been done in #1632 with the introduction of `substrate-consensus-slots`.
