### ISSUE TITLE
Can offchain worker create inherent data ?

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/substrate#11273]
I cannot find a way or example to create inherent data.

But in example pallet:
```
		fn offchain_worker(_n: T::BlockNumber) {
			// We don't do anything here.
			// but we could dispatch extrinsic (transaction/unsigned/inherent) using
			// sp_io::submit_extrinsic.
			// To see example on offchain worker, please refer to example-offchain-worker pallet
			// accompanied in this repository.
		}
```
Is the doc old ?  In my impression，There are different process flow for tx and inherent data. The tx is pushed to tx pool, but inherent data is not. 
So is offchain currently unable to create inherent data?

**Comment by bkchr** [comment]
As inherent data is also just a tx, you can push it to the tx pool as well. However, your runtime logic should prevent that any inherent is applied twice.

**Comment by bkchr** [comment]
Can this be closed?

**Comment by yjhmelody** [comment]
Okay, I will try
