### ISSUE TITLE
decl_storage! complaining about AccountId not having a default.

### ISSUE THREAD

**Issue by ruseinov** [paritytech/substrate#11300]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

While upgrading to substrate latest, where `Default` trait is no longer implemented for AccountId I'm facing problems with `!decl_storage` complaining about that. 

### Steps to reproduce

Try building that: https://github.com/SyntropyNet/substrate-nft-pallet

**Comment by ruseinov** [comment]
@ggwpez Thank you for the answer! Yep, I was not sure how exactly that macro works, it makes total sense that it expects a Default in case of returning the non-existent AccountId!

**Comment by ggwpez** [comment]
Great, hope this fixes it. Otherwise feel free to reopen the issue :smile:

**Comment by ruseinov** [comment]
Yep, that fixed it!
