### ISSUE TITLE
Rename `Epoch` to `Session` in BABE and throughout any parts in Substrate

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#11317]
Everywhere we use the term `Session`, except in BABE where we use the term `epoch`.

Lets bring consistency to the terms, and leave a note that if you are reading the BABE technical paper, the word `epoch` in that paper means `session` in Substrate.

**Comment by MC-Terrence** [comment]
Hello Shawn, can I take this on please?

**Comment by bkchr** [comment]
There was no consensus on this rename, so let's close this.
