### ISSUE TITLE
state_getMetadata doesn't return any runtime module

### ISSUE THREAD

**Issue by LeapM** [paritytech/substrate#1132]
1. cargo run -- --dev

2.  curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "state_getMetadata"}' -X POST http://localhost:9933  

3. return {"jsonrpc":"2.0","result":"0x4576656e74","id":1}

**Comment by bkchr** [comment]
I fixed that yesterday, did you update to the latest master?

**Comment by bkchr** [comment]
Did you rebuild the wasm files and purged your database? (rm -rf ~/.local/share/Substrate)

**Comment by LeapM** [comment]
there is no ~/.local folder on my computer. it is on macbook.

I did all the  below steps, no luck. 

1. ```git pull```
2. ```./scripts/build.sh```
3. ``` cargo update```
4. ``` cargo build```
5. ``` rm -rf ~/Library/Application\ Support/Substrate/chains/development/```
6. ```cargo run -- --dev```

**Comment by samzhuwj** [comment]
I reproduced this issue. Any solutions? @bkchr

**Comment by bkchr** [comment]
Hey, you are right. There was accidentally removed stuff in a recent pr that should not be removed. The following commit will fix this: https://github.com/paritytech/substrate/pull/1133
