### ISSUE TITLE
Rewrite `define_env!` as a procedural macro

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#11344]
Currently, the contracts pallet uses the [`define_env!`](https://github.com/paritytech/substrate/blob/c2fc4b3ca0d7a15cc3f9cb1e5f441d99ec8d6e0b/frame/contracts/src/wasm/env_def/macros.rs#L212) macro by example in order to [define which host functions are available for contracts](https://github.com/paritytech/substrate/blob/c2fc4b3ca0d7a15cc3f9cb1e5f441d99ec8d6e0b/frame/contracts/src/wasm/runtime.rs#L856-L2093).

This macro should be rewritten as a procedural attribute macro in order to achieve the following benefits:
- Easier to maintain macro code
- Better syntax for defining metadata of host functions (the module name for example) as attributes
- rustfmt support
- Make the host functions visible in rustdoc by emitting some public mock type

There is already a `pallet-contracts-proc-macro` crate where this macro could live.

**Comment by agryaznov** [comment]
So the new way we define the env (in `wasm/runtime.rs`) would be as follows:
```rust
#[define_env]
pub mod env {
	#[host("seal0")]
	fn gas(ctx: Runtime<E: Ext>, amount: u32) {
		ctx.charge_gas(RuntimeCosts::MeteringBlock(amount))?;
		Ok(sp_sandbox::ReturnValue::Unit)
	}

	#[host("seal1")]
	fn seal_set_storage(ctx: Runtime<E: Ext>, key_ptr: u32, value_ptr: u32, value_len: u32) -> u32 {
		ctx.set_storage(KeyType::Fix, key_ptr, value_ptr, value_len).map(|_| ())
	}
...
}
```
@athei wdyt?

**Comment by athei** [comment]
Looks good in general. I have the following suggestions

1. Don't require a special attribute to flag something as host function. Everything in this module is a host function implicitly. So it won't get polluted with other stuff.
2. Let's don't allow setting the module manually. Add a numeric version so we can do some arithmetic on it when necessary.
3. Added `#[prefixed_alias]` just as an example for a new attribute. Should be a follow up PR.

```rust
#[define_env]
pub mod env {
        // implicit version 0, no prefixing required as this function is only called "gas"
	fn gas(ctx: Runtime<E: Ext>, amount: u32);

       // implicit version 0, add alias "seal_set_storage"
       #[prefixed_alias]
	fn set_storage(ctx: Runtime<E: Ext>, key_ptr: u32, value_ptr: u32, value_len: u32);

        // new version of function. also need alias
	#[version(1)]
        #[prefixed_alias]
	fn set_storage(ctx: Runtime<E: Ext>, key_ptr: u32, value_ptr: u32, value_len: u32) -> u32 ;
       
       // implicit version 0, no prefix required as newly added function
       fn crazy_new_function();
...
}
```

**Comment by agryaznov** [comment]
> 3. Added #[prefixed_alias] just as an example for a new attribute. Should be a follow up PR.

This one delayed for now for a follow-up PR.  

Applying all other suggestions, here is how environment definition will look like (in `wasm/runtime.rs`):
```rust
#[define_env]
pub mod env {
        // will be expanded to the "seal0" module 
	fn gas(ctx: Runtime<E: Ext>, amount: u32) {
		ctx.charge_gas(RuntimeCosts::MeteringBlock(amount))?;
		Ok(())
	}

        // will be expanded to the "seal0" module 
	fn seal_set_storage(ctx: Runtime<E: Ext>, key_ptr: u32, value_ptr: u32, value_len: u32) {
		ctx.set_storage(KeyType::Fix, key_ptr, value_ptr, value_len).map(|_| ())
	}

        // will be expanded to the "seal1" module 
	#[v(1)]
	fn seal_set_storage(ctx: Runtime<E: Ext>, key_ptr: u32, value_ptr: u32, value_len: u32) -> u32 {
		ctx.set_storage(KeyType::Fix, key_ptr, value_ptr, value_len)
	}

        // will be expanded to the "__unstable__" module 
	#[unstable]
	fn seal_set_storage(
		ctx: Runtime<E: Ext>,
		key_ptr: u32,
		key_len: u32,
		value_ptr: u32,
		value_len: u32,
	) -> u32 {
		ctx.set_storage(KeyType::Variable(key_len), key_ptr, value_ptr, value_len)
	}
}
...
```

**Comment by athei** [comment]
Cool but let's not make one letter attributes :) : `v -> version`.

**Comment by agryaznov** [comment]
Ok. Also added attribute for the environment identifier, like `#[define_env(Env)]` or `#[define_env(Test)]`
