### ISSUE TITLE
Add intermediate node setup state

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1134]
In #1128,

we've introduced an intermediate setup state that is required for all components - Grandpa specifically - to wire up properly. This is necessary as the current components infrastructure decouples all parts of the system and the node macro puts together many layers of indirection in between, which are hard to penetrate. In the case of Grandpa, however, for the active consensus engine to run, we need access to the `LinkHalf` that was created during `import_queue` setup.

For now we are misusing the `CustomConfig` to provide that intermediate state to us, however this is neither elegant, efficient (we have to copy it out) nor intended. Instead we should provide a custom intermediate state struct that different setup systems have direct access to and can rely on to communicate state to one another. This can probably be discarded after startup.

**Comment by LeapM** [comment]
can I please work on this one? not sure how the issue with mentor label works, but keen to give it a crack.

**Comment by bkchr** [comment]
Yeah, you can work on this if you want. You can post any question directly to this issue :)

**Comment by LeapM** [comment]
thanks, please be patient with me :)

**Comment by LeapM** [comment]
I found the code where link half is initialized, and have a few questions:
1. what is the linkhalf for?  it has client and authority set field. is there any document? or I have to dig into the code to find its purpose?
2. the code seems like only called once, is the copy of client major concern?
3. I am very new to the substrate codebase, can you please give me some guidance of what the new code structure may look like?

**Comment by gnunicorn** [comment]
> thanks, please be patient with me :)

No worries, this isn't urgent.

> what is the linkhalf for? it has client and authority set field. is there any document? or I have to dig into the code to find its purpose?

`LinkHalf` is provided when we create the `ImportQueue`, the object that receives blocks from the network and checks them. In the specific consensus algorithm (`GRANDPA`) this piece needs to inform the consensus making engine about blocks it imported - `LinkHalf` is this communication channel and the main object we need to hold onto during setup as bot the `ImportQueue` and `AuthoritySetup` are otherwise totally disconnected from one-another.

> the code seems like only called once, is the copy of client major concern? 

I am not sure what you mean. Could you link to the line of code you are referring to? If you mean the copy of `LinkHalf` - it is not a big concern but for sure not a good design and we'd like to remove the `Copy` on `LinkHalf` to ensure it is only being connected once ever.

> I am very new to the substrate codebase, can you please give me some guidance of what the new code structure may look like?

Sure. So, I am thinking that aside from the `config` object we are passing around, we might want to pass around a `&mut setup_state` to all setup functions called from `core-service`, that the specific factory could mutate to provide state. It would be configured using the macro in a similar fashion as `CustomConfig` is provided at the moment. In this particular case, said `State` would have an `Option<LinkHalf>` that might be filled by the ImportQueue and then `,take()`n by `AuthoritySetup`.

**Comment by LeapM** [comment]
1.  all setup functions called from ```core-service```, do you means the impl Components for FullComponents? can you please give more details?
```
	fn build_client(
		config: &FactoryFullConfiguration<Factory>,
		executor: CodeExecutor<Self::Factory>,
	)
		-> Result<(
			Arc<ComponentClient<Self>>,
			Option<Arc<OnDemand<FactoryBlock<Self::Factory>, NetworkService<Self::Factory>>>>
		), error::Error>
	{
		
	}

	fn build_transaction_pool(config: TransactionPoolOptions, client: Arc<ComponentClient<Self>>)
		-> Result<TransactionPool<Self::TransactionPoolApi>, error::Error>
	{
		
	}

	fn build_import_queue(
		config: &mut FactoryFullConfiguration<Self::Factory>,
		client: Arc<ComponentClient<Self>>
	) -> Result<Self::ImportQueue, error::Error> {
		
	}
}
```
2.  I assume LinkHalf object will be updated whenever validators set change? I cannot find where it is updated in the code?

3. for pass around a ```&mut setup_state```, I don't think safe rust allow borrow object as mutable more than once at a time. do you think about using unsafe rust here?

thanks

**Comment by gavofyork** [comment]
@gnunicorn ^^^

**Comment by gnunicorn** [comment]
Sorry, I thought, I had answered this, but it appears my memory tricked me here. Sorry about dropping the ball here, @LeapM . If you are still on it, let me try to answer your Questions:

@LeapM if you take a look at the [node-cli service setup, you'll find the definition for `Configuration`](https://github.com/paritytech/substrate/blob/b57c458587e5e41b785b0197daa00723cccca488/node/cli/src/service.rs#L69), which every [specific implementation can supply](https://github.com/paritytech/substrate/blob/b57c458587e5e41b785b0197daa00723cccca488/node/cli/src/service.rs#L43-L56) and is then [passed to the setup functions](https://github.com/paritytech/substrate/blob/b57c458587e5e41b785b0197daa00723cccca488/node/cli/src/service.rs#L122). This is all [defined in the macro for `construct_service_factory`](https://github.com/paritytech/substrate/blob/ae7567b71db2206b3d9d39f7714e17291f5d3fdd/core/service/src/lib.rs#L472). Now what we want is to be able to define a second type `SetupState` (can be empty `()` by default) when creating the setup that is passed around in a similar way (but is probably mutable) so we can store things like the `LinkHalf` on and retrieve it from it during the ramp up process.

Re 2: don't worry too much about `LinkHalf` in this case, it is a specific feature the `aura` consensus mechanism needs to pass from one setup stage to another so they can be "linked up" properly. At the moment, we do that through a clone (which we don't want) but we'd much rather do this through a generic setup state type.

Does that clarify the questions?
