### ISSUE TITLE
Pallet assets refactoring for PSP22 + chain extension.

### ISSUE THREAD

**Issue by cr4pt0** [paritytech/substrate#11359]
Would be very helpful extract main logic of callable function in `pallet assets` to internal function.

Why we need it:
We are developing chain extension and use pallet assets for smart contact `PSP22`
We want reuse main logic of callable function without creating origin and dublicating instance of Lookup and etc..

In pallet assets exists some perfect example 
`mint` function has main logic with incapsulated in internfal function

![726708E8-16FB-45A5-BE7C-8506D42601AB_4_5005_c](https://user-images.githubusercontent.com/102041955/166881194-984c90e4-d4a2-4507-b72c-8329ca26aab3.jpeg)
In this case we can use internal function `do_mint`

We want to change other public callable functions which still does not have main logic in internal functions.
Good example is `create`

![35C559B7-BE64-4810-9802-E4827F3ADE03_1_201_a](https://user-images.githubusercontent.com/102041955/166882479-6cdb2d44-bc79-4830-8aff-54ea689af71b.jpeg)
We want to move code(red square) in separate internal function.
After we done it we will have posibility to use internal function in our custom chain extension without doing some kind of authorisation or authentication validation.

We would like to change those function 
```
create
destroy
freeze
thaw
freeze_asset
thaw_asset
transfer_ownership
set_team
clear_metadata
cancel_approval

```

We are not using force function so we are not going to change  that type of function.
```
force_cancel_approval
force_asset_status
force_clear_metadata
force_set_metadata
freeze_asset
```

**Comment by MrishoLukamba** [comment]
The function destroy has already being refactored
