### ISSUE TITLE
Allow submitting offences from root

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11352]
Would be very helpful for testing if there was a way for `root` e.g. sudo in a dev-chain to create an `offence`. This would help you test all sorts of things around the slashing and offence code. 

Ideally, this transaction would only accept one parameters: `offenders: Vec<(T::AccountId, Perbill)>`, and slash each of them with that fraction. 

One way to do this would be to add this transaction to the offences pallet. But it won't be able to work with the api above (offences pallet needs `FullIdentification`), and it would also pollute all runtime with this pallet.

An alternative is to build a custom, minimal pallet that only does this. 

This new pallet should strictly depend on `pallet-session`, `pallet-staking`, and `pallet-offences` in its `trait Config`.

Having all 3 of the above, realizing the interface `offenders: Vec<(T::AccountId, Perbill)>` should also be possible.

**Comment by bkchr** [comment]
> An alternative is to build a custom, minimal pallet that only does this.

I vote for this.

**Comment by burdges** [comment]
Can we do this from governance on non-sudo chains?

**Comment by MC-Terrence** [comment]
Hello @kianenigma is this agreed to be worked on now? 
I'd love to work on this.

**Comment by Szegoo** [comment]
@omadoyeabraham @gitwithterrence Are you working on this, or is the issue free to work on?

**Comment by Szegoo** [comment]
@kianenigma Could you assign this to me? I am currently working on this.

**Comment by KiChjang** [comment]
@Szegoo You might want to consider getting your outstanding PRs to the finish line. As of my typing, you have 4.

**Comment by Szegoo** [comment]
> @Szegoo You might want to consider getting your outstanding PRs to the finish line. As of my typing, you have 4.

Thanks for reminding me, out of the 4 PRs two of them need to be closed(I closed them now) and for the other two, I am awaiting reviews.

**Comment by Szegoo** [comment]
@kianenigma @bkchr Could you please take a look at my PR?
