### ISSUE TITLE
combine `iteratons` and `tolerance` in `sp-npos-elections` API

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11388]
> Note: reading this, I really feel like this `iterations: usize, tolerance: ExtendedBalance` can be made into its own `struct BalancingConfig`, don't you think? This can be a separate PR, although if you open it now, it might cause some conflicts.

taken from https://github.com/paritytech/substrate/pull/11180

cc @georgesdib feel free to assign yourself.

**Comment by georgesdib** [comment]
I had actually started working on this in the branch:

[mms-election-followup](https://github.com/georgesdib/substrate/tree/mms-election-followup)

It needs the other PR to be merged first though.

**Comment by kianenigma** [comment]
If you can rebase it on master, I am sure we can fix this one faster.

**Comment by georgesdib** [comment]
> If you can rebase it on master, I am sure we can fix this one faster.

Done in #11498
