### ISSUE TITLE
In Aura, the block hash when logging a proposed block is wrong

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1138]
because the consensus engine adds a new digest item for the seal, the hash changes after the log item is issued.

**Comment by gavofyork** [comment]
@gnunicorn @andresilva @rphmeier could one of you please volunteer to sort this?

**Comment by gnunicorn** [comment]
We are talking about specifically [this log statement](https://github.com/paritytech/substrate/blob/4a576930fbef60fb3ef9899283dbf254a4aed6d7/core/basic-authorship/src/basic_authorship.rs#L235) which states a wrong hash as Aura modifies the data after and thus is quite the annoyance in debugging. We should move this log statement to the point where the hash doesn't change anymore.

**Comment by gterzian** [comment]
I'll look into this...
