### ISSUE TITLE
The node-template doesn't compile : error: failed to select a version for the requirement `libgit2-sys = "^0.13.2"

### ISSUE THREAD

**Issue by echevrier** [paritytech/substrate#11402]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I am trying to compile the node-template from master with `cargo build --release -p node-template`. I get : 
error: failed to select a version for the requirement `libgit2-sys = "^0.13.2"`
candidate versions found which didn't match: 0.13.2+1.4.2, 0.13.1+1.4.2, 0.13.0+1.4.1, ...
location searched: crates.io index
required by package `git2 v0.14.2`
    ... which satisfies dependency `git2 = "^0.14.2"` (locked to 0.14.2) of package `generate-bags v4.0.0-dev (/home/runner/work/substrate-api-client/substrate-api-client/substrate/utils/frame/generate-bags)`

### Steps to reproduce

1. ~/substrate : git pull
2. cargo build --release -p node-template

**Comment by bkchr** [comment]
I can not reproduce this on latest master. Is your checkout clean? Without any changes?

**Comment by echevrier** [comment]
You're right. Sorry. Substrate checkout was clean, but I had to make a cargo update. So I close it?

**Comment by echevrier** [comment]
> You're right. Sorry. Substrate checkout was clean, but I had to make a cargo update. So I close it?

Can you commit the right cargo.lock so that no cargo update is required?

**Comment by ggwpez** [comment]
I think i saw the same thing, was fixed by `rustup update`.
