### ISSUE TITLE
Make Pallet Bounties and Pallet Tips Instantible

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#11421]
The Treasury Pallet is currently instantiable, but second instances of the pallet cannot have bounties or tips because these sub-pallets are not instantible.

We should make these other pallets instantible, and then create some tests which ensures that multiple instances of treasury with these extensions work.

**Comment by Doordashcon** [comment]
Hi @shawntabrizi i'd like to be assigned to this :)

**Comment by shawntabrizi** [comment]
@Doordashcon its yours

**Comment by shawntabrizi** [comment]
@koushiro this is being worked on by @Doordashcon 

I will merge from @Doordashcon assuming he finishes

**Comment by shawntabrizi** [comment]
should be completed
