### ISSUE TITLE
Council Voting: Difference between `voting` functions

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate#1144]
Assuming the `vote` function in [srml/council/src/motions.rs](https://github.com/paritytech/substrate/blob/master/srml/council/src/motions.rs#L96) is for processing a vote from a councillor (other than the councillor that proposed the motion), which involves adding it to the tally of votes for a motion only if the vote doesn't cause the motion to be either: disapproved, or approved and elevated to the table of referenda then why would you use the `vote` function in [srml/council/src/voting.rs](https://github.com/paritytech/substrate/blob/master/srml/council/src/voting.rs#L61)

**Comment by gavofyork** [comment]
they are completely different voting systems. one is for the council voting as a body regarding tabling referenda. the other is for council motions that allow for an arbitrary number of councillors to vote and initiate a call. crucially for the latter, the origin is Council, not Root, a much lower priority classification.
