### ISSUE TITLE
nomination-pools: fix usage of `stash` and `controller` around `StakingInterface`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11440]
currently it is a bit of a mess. It should be aligned with the dispatch origin of the corresponding call. For example, the controller can call `bond_extra`, so it should be called `controller`.

**Comment by kris524** [comment]
Hello again, can I pick this task instead? Is there any additional information I might need?

**Comment by shawntabrizi** [comment]
We should instead try and drop the controller account logic imo, and just rely on proxies. Seems better than continually iterating on an obsolete api

**Comment by kianenigma** [comment]
cc @ruseinov
