### ISSUE TITLE
Council Voting: Missing option for councillors to 'postpone' a council proposal

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate#1145]
Is there a function we can use for a councillor to postpone a council proposal? Is this still to be added to [srml/council/src/voting.rs](https://github.com/paritytech/substrate/blob/master/srml/council/src/voting.rs)?

**Comment by gavofyork** [comment]
postponing is equivalent to vetoing. the veto only lasts for the cooldown period.
