### ISSUE TITLE
jsonrpsee: Server is busy, try again later

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/substrate#11460]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I was testing node with upgraded Substrate (with jsonrpsee) and hit this on (also `jsonrpsee`) client:
```
RPC call failed: ErrorObject { code: ServerError(-32604), message: "Server is busy, try again later", data: None }
```

It was just a subscription and some messages sent back as a reaction to subscription.

I see it is related to resource limiting: https://github.com/paritytech/jsonrpsee/blob/e159c449551ebcfc99f05510fbac0c74e4443322/core/src/server/resource_limiting.rs#L44-L46

But which resource specifically? There is nothing in regular logs of the node about this.

Server is a local node that produces blocks in isolation and serves this single RPC client over WebSocket.

This is not something I expect to happen by default :thinking:

**Comment by nazar-pc** [comment]
It was failing at 1024 subscriptions, turned out subscriptions were leaking on the client.

Nice to see it is finally handled by the node, but error message could have been better.

**Comment by niklasad1** [comment]
Right, feel to open an issue in jsonrpsee :)
