### ISSUE TITLE
Council Voting: Potential refactoring opportunity when Vetoing a Council Proposal

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate#1146]
If a council proposal is valid, the councillor that created the proposal is added to a tuple (proposal's hash, councillor's account id) that's mapped to that councillor's vote (which is recorded as a vote of yay for the proposal's creator) for that proposal in storage using  `CouncilVoteOf` from [srml/council/src/voting.rs#L128](https://github.com/paritytech/substrate/blob/master/srml/council/src/voting.rs#L128) .

If a valid veto is submitted using the `veto` function of [srml/council/src/voting.rs#L73](https://github.com/paritytech/substrate/blob/master/srml/council/src/voting.rs#L73), it removes all entries from the  `CouncilVoteOf` mapping where the tuple has the vetoed proposal's hash and an 'active' councillor's account id as follows from [srml/council/src/voting.rs#L96](https://github.com/paritytech/substrate/blob/master/srml/council/src/voting.rs#L96):

```
for (c, _) in <Council<T>>::active_council() {
  <CouncilVoteOf<T>>::remove((proposal_hash, c));
}
```

Why does it only remove entries from 'active' council members? Is it not removing non-'active' council members for a reason?

Could we just removal all entries that contain the proposal_hash as the first element of the tuple, without having to use a loop through all the ~24 'active' council members?

**Comment by gavofyork** [comment]
"active" here is just a synonym for "current". there isn't a group who could be demonstrably enumerated as "inactive", since they would include councillors from the future.
