### ISSUE TITLE
Remove `multiply_by_rational`

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#11477]
Everything that uses it should instead be moved to use `multiply_by_rational_with_rounding`. `SignedRounding` should be used whenever inputs/outputs may be negative.

**Comment by tifecool** [comment]
I would like to attempt this issue if @Szegoo is dropping it.

Is `SignedRounding` a struct or function or will I just add my own logic to round the inputs/outputs?

**Comment by tifecool** [comment]
From my understanding, we want to work with integers for input, decimals within the function then, at output, round either up or down to the nearest integer.

Is this correct?

**Comment by Szegoo** [comment]
@tifecool You can have the issue :)

**Comment by tifecool** [comment]
Just finding out revision #11124 from yesterday adds SignedRounding. Is this issue now closed @gavofyork ?
