### ISSUE TITLE
--validator doesn't imply --pruning archive anymore

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/substrate#11475]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I suspect after https://github.com/paritytech/substrate/pull/10995 this description is no longer correct:
```
        --pruning <PRUNING_MODE>
            Specify the state pruning mode, a number of blocks to keep or 'archive'.
            
            Default is to keep all block states if the node is running as a validator (i.e.
            'archive'), otherwise state is only kept for the last 256 blocks.
```

Node is no longer storing state for old blocks. It is either expected, but documentation wasn't updated or documentation is correct and there is a regression.

cc @RGafiyatullin

### Steps to reproduce

Run any chain with `--validator` and without `--pruning archive`

**Comment by bkchr** [comment]
The docs are just not correct anymore. The new behavior is correct.

**Comment by bkchr** [comment]
@Szegoo go ahead.

**Comment by Szegoo** [comment]
Just to check before committing, AFAIU currently, the default is to keep only the last 256 blocks. Is this correct? @bkchr @nazar-pc
