### ISSUE TITLE
nomination pools: allow governance owned pools

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11479]
Currently, pools have explicit "**account Ids**" that are roles. These roles can either be set, or not set. So, a pool can now express (as of #11411) for example that they no longer keep control of their nominations. 

We now want to extend this logic to allow a pool to hand over its control over itself to e.g. governance. 

One way to go about this would be to duplicate the logic here: 

https://github.com/paritytech/substrate/blob/2823dc4de5030aada6032e2ac58f4781f8dbfaf3/frame/nomination-pools/src/lib.rs#L1915-L1924

Basically, make all calls either controllable by the pool role (if it exists), or root. 

This is okay-ish, but it will 

1. pollute the code a bit. 
2. it does not allow for any fine-grained control. For example, a pool cannot express that they want a majority council origin to control them.

Is there a better way to do this? We could let a custom type that implements `EnsureOrigin` be used as pool roles instead of raw account id, but I am not sure if this is much cleaner. 

NOTE: this issue is easy to do if we go the root approach. Before tackling, make sure the approach is final.

**Comment by kris524** [comment]
Hello, can I pick this issue? Is there anything else I would need to know? 
Thank you!

**Comment by kianenigma** [comment]
> Hello, can I pick this issue? Is there anything else I would need to know? 
> 
> Thank you!

I've already given this a try, so let's wait and see how that goes! See the linked PR
