### ISSUE TITLE
Add an integration test for warp sync

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#11471]
Warp sync is not fully covered by tests, requiring manual testing on each release. There are unit tests in `sc-network-test` that test the warp sync protocol, but they don't cover ineractions with BABE and GRANDPA after the sync is complete. So a more real-life test is required, probably on the `sc-service` level, where we already have integration tests for sync and basic block authoring/consensus.

The challenge here is that to properly test warp sync we need at least some changes to the GRANPA authority set and BABE epochs and current testing framework does not allow to simulate that.

**Comment by bkchr** [comment]
We should probably write a zombienet based test for this. We probably need some kind of chain restore. For that we need to be able to skip Babe epochs to not fail with the famous "unexpected epoch change error". I think @andresilva has some ideas for that?
