### ISSUE TITLE
election-provider: easier recovery from `Phase::Emergency`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11472]
currently, if we go to `Phase::Emergency`, the only way out is governance:

1. `governance_fallback`
2. `submit_emergency_solution`

Both of which need complicated governance process. 

It might be reasonable to relax this. Basically, if the signed phase fails, it should simply just continue, and miners should still be allowed to submit signed submissions that meet all criteria. The difference however should be that in this case we process the signed submission on the fly. A correct submission should be fairly cheap, and a bad submission should be highly punished.

**Comment by Szegoo** [comment]
@kianenigma I was reading the code of the election provider, and I am not sure I understand what the term 'target' means in the code. I am pretty new to this codebase, so I hope you can help me.

**Comment by Szegoo** [comment]
I will give this a try.

**Comment by kianenigma** [comment]
Won't be solved as explained in the linked PR.
