### ISSUE TITLE
Rename `--wasm-execution=compiled` to `--wasm-execution=wasmtime`

### ISSUE THREAD

**Issue by koute** [paritytech/substrate#11485]
In the future we might add other compiled WASM executors besides `wasmtime` (`wasmer`?); rename the value of the CLI argument `--wasm-execution=compiled` to `--wasm-execution=wasmtime` so that we explicitly specify which one we're using.

**Comment by bkchr** [comment]
Then it should directly be renamed to `wasm-execution-engine` or something. And `interpreted-i-know-what-i-do` should be renamed to `wasmi`.

However, I'm not really sure we need this in general.

**Comment by pepyakin** [comment]
Yeah, definitely not necessary. Works the way it is just fine. That said, compiled/interpreted is really unfortunate naming.

**Comment by the-right-joyce** [comment]
based on comments before closed
