### ISSUE TITLE
#[pallet::storage] can not use independently

### ISSUE THREAD

**Issue by yanganto** [paritytech/substrate#11481]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Base on the documentation to migration list as following,
- [storage-migrations](https://docs.substrate.io/how-to-guides/v3/storage-migrations/basics/)
- [Upgrades](https://docs.substrate.io/v3/runtime/upgrades/#storage-migrations)
  - the [example](https://github.com/hicommonwealth/substrate/blob/5f3933f5735a75d2d438341ec6842f269b886aaa/frame/indices/src/migration.rs#L5-L22) in Upgrades page
  
A legacy data structure should be stored in another module as following, such that the migration can be performed.

```rust
mod migration {
    use super::*;
    #[frame_support::pallet] 
    pub mod v1 {
       #[pallet::storage]
       pub type Number<T> = StorageValue<_, u64>;
    }
}
```

However, the `#[pallet::config]` or possible more things are asked while compiling. 
This is a bug to keep both version of data structure at the same time.  Also this will be an issue for data migration with the storage described with`#[pallet::storage]`.

**Comment by kianenigma** [comment]
This is the macro that you are supposed to use to maintain the old storage formats around for migration: 

https://github.com/paritytech/substrate/pull/11387
