### ISSUE TITLE
Can Polkadot use the RPCAPI parameter to control the RPC method like ETH?

### ISSUE THREAD

**Issue by duktig666** [paritytech/substrate#11508]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Can Polkadot use the RPCAPI parameter to control the RPC method like ETH?

### Steps to reproduce

1. `--rpc-methods` only have `auto` `safe` `unsafe` model
2. Can Polkadot use the RPCAPI parameter to control the RPC method like ETH?

**Comment by niklasad1** [comment]
Polkadot doesn't provide the ETH RPC API

You can use https://github.com/paritytech/frontier or https://github.com/PureStake/moonbeam which provides the ETH RPC API.
