### ISSUE TITLE
Make master branch stable by having Continuous integration

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#1152]
Proposing an enhancement and a must have feature from the get go 😺 
Witnessed instability in master branch due to major feature integration and I believe its the right time to have an automatic test integration pipeline before merging in to master branch. 

Either integrate Circle CI or Travis CI with automatic tests.

**Comment by bkchr** [comment]
Hey, we already have a CI that tests all our pull requests.

**Comment by Kalanamith** [comment]
@bkchr  the latest master branch cannot be compiled in MacOS with substrate node template project today. I have seen the CI integration

**Comment by bkchr** [comment]
Yeah sorry for that, master is currently evolving really fast. We should pin the template project to a specific commit.

**Comment by bkchr** [comment]
@Kalanamith https://github.com/paritytech/substrate-node-template/pull/8 should fix your problems :) This will also pin the example to a specific substrate version, so it should work, even when we break something in master.

**Comment by Kalanamith** [comment]
@bkchr  Great, Thanks a  lot!
