### ISSUE TITLE
Fork ID does almost nothing

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/substrate#11561]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

There is a `fork_id` field in the chain spec with the following description:
https://github.com/paritytech/substrate/blob/4544e6d2ce398cadc03b56863f57c1ed6f53d046/client/chain-spec/src/chain_spec.rs#L167-L171

However this description is misleading because the only two components aware of this `fork_id` are `beefy-gadget` and `sc-finality-grandpa`. Nothing else in the whole Substrate cares about it even though as a feature it might be helpful at times.

**Comment by bkchr** [comment]
This will be fixed by this issue: https://github.com/paritytech/substrate/issues/7746
