### ISSUE TITLE
Scheduler pallet bloats `Agenda` too easily when there's lots of insertions/removals

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#11565]
Right now, deleting a previously scheduled item results in a `None` "hole" in its `Agenda` for that block, which is not used since Scheduler just appends on `Agenda` when adding a new item. If items are continuously inserted and deleted then this can bloat storage and become a problem.

Instead, `None` items in the `Agenda` should be inserted into or the entire mechanism replaced with `remove` or `swap_remove`.

**Comment by ggwpez** [comment]
I will tackle this in https://github.com/paritytech/substrate/pull/11589 together with bound storage

**Comment by ggwpez** [comment]
I think there is still a case where through preemption or re-scheduling an agenda can be all `None`.   
But we could add a simple perpetual migration that clears out the all-`None` empty agendas on every runtime upgrade. @gavofyork
