### ISSUE TITLE
Execution Instantiation Error When Making New Substrate Node Chain Specification File

### ISSUE THREAD

**Issue by eparch** [paritytech/substrate#1159]
When I attempt to make a new Substrate Node chain specification file in terminal with:
 `substrate build-spec --chain=staging > ~/chainspec.json` 

I get receive the following message: 
`Error: Execution: Instantiation: Export ext_storage_changes_root has different signature Signature { params: [I64, I32], return_type: Some(I32) }`

The target `chainspec.json` file is empty.

The following is a printout of my terminal session:

`Eps-MBP:emsdk eparch$ substrate build-spec --chain=staging > ~/chainspec.json`
`2018-11-23 12:03:49 Substrate Node`
`2018-11-23 12:03:49   version 0.1.0-f1960129-x86_64-macos`
`2018-11-23 12:03:49   by Parity Technologies, 2017, 2018`
`2018-11-23 12:03:49 Chain specification: BBQ Birch`
`2018-11-23 12:03:49 Node name: melted-sticks-2304`
`2018-11-23 12:03:49 Roles: FULL`
`2018-11-23 12:03:49 Loading GRANDPA authorities from genesis on what appears to be first startup.
Error: Execution: Instantiation: Export ext_storage_changes_root has different signature Signature { params: [I64, I32], return_type: Some(I32) }`
`Eps-MBP:emsdk eparch$ `

For clarification, this is the script I used `curl https://getsubstrate.io -sSf | bash` to install substrate.

**Comment by cam-cen** [comment]
Also getting this on the nightly build in docker as well
```
$ docker run parity/substrate:nightly-20181126

2018-11-27 02:29:25 Substrate Node
2018-11-27 02:29:25   version 0.1.0-f196012-x86_64-linux-gnu
2018-11-27 02:29:25   by Parity Technologies, 2017, 2018
2018-11-27 02:29:25 Chain specification: BBQ Birch
2018-11-27 02:29:25 Node name: magical-news-8202
2018-11-27 02:29:25 Roles: FULL
2018-11-27 02:29:25 Generated a new keypair: 5d1d85073f315f42802e9981f0c7e55d8f367e0d5c0849ce90c06582e1371842 (5EAo5a3C...)
2018-11-27 02:29:25 Initialising Genesis block/state (state: 0xbfea…4d1c, header-hash: 0x55a7…30e1)
2018-11-27 02:29:25 Loading GRANDPA authorities from genesis on what appears to be first startup.
Error: Execution: Instantiation: Export ext_storage_changes_root has different signature Signature { params: [I64, I32], return_type: Some(I32) }```

**Comment by tarrencev** [comment]
I'm seeing this issue too

**Comment by bkchr** [comment]
Hey, could you all please try `rm -rf ~/.local/share/Substrate/`?

**Comment by gavofyork** [comment]
i had this too; the chain data needs removing. try running:

```
substrate --dev purge-chain
```

**Comment by bkchr** [comment]
I think we can close this issue.
