### ISSUE TITLE
Add `TransactionPayment` event to Pallet Tranascation Payment

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#11595]
There have been many issues from various people, all asking how to get the transaction fee of a Substrate transaction.

Currently, the only events that are emitted are those from the Balances pallet, which are not specific enough to determine the actual transaction fee in all cases.

We should add a simple event to the Transaction Payment Pallet which emits exactly the final transaction fee, tip, and user to clarify all of this.

Something like:

```rust
#[pallet::event]
#[pallet::generate_deposit(pub(super) fn deposit_event)]
pub enum Event<T: Config> {
	TransactionPayment { account: T::AccountId, fee: BalanceOf<T>, tip: BalanceOf<T> },
}
```

**Comment by shawntabrizi** [comment]
@hzy1919 great!

**Comment by shawntabrizi** [comment]
@Doordashcon I think someone else is already doing it, so lets wait until then.

**Comment by shawntabrizi** [comment]
Let's also use this issue to add an event to pallet assets tx payment

**Comment by hzy1919** [comment]
> Let's also use this issue to add an event to pallet assets tx payment.
> 
> @hzy1919 are you interested to do that too?

@shawntabrizi  Yeah, I would like to continue that .

**Comment by shawntabrizi** [comment]
test https://forum.polkadot.network/t/github-integration/134
