### ISSUE TITLE
parity_wasm are different versions

### ISSUE THREAD

**Issue by zjb0807** [paritytech/substrate#11608]
https://github.com/open-web3-stack/open-runtime-module-library/runs/6765223030?check_suite_focus=true
```
error[E0308]: mismatched types
   --> /home/acala/.cargo/git/checkouts/substrate-f4423eebfa0046a3/616d33e/client/executor/wasmi/src/lib.rs:718:35
    |
718 |         Module::from_parity_wasm_module(blob.into_inner()).map_err(|_| WasmError::InvalidModule)?;
    |                                         ^^^^^^^^^^^^^^^^^ expected struct `parity_wasm::elements::module::Module`, found a different struct `parity_wasm::elements::module::Module`
    |
    = note: perhaps two different versions of crate `parity_wasm` are being used?

```

https://github.com/alexcrichton/wasm-gc/blob/deb1c6dc3aec39a3f2bdc5595266212ead448490/wasm-gc-api/Cargo.toml#L17

https://github.com/paritytech/substrate/blob/a0a40adbf57b47b445012c6cbca940c991c94197/utils/wasm-builder/Cargo.toml#L23
the `parity-wasm = "0.32"` is old

**Comment by xlc** [comment]
related https://github.com/paritytech/substrate/issues/1262

**Comment by bkchr** [comment]
> related #1262

Not related at all.

**Comment by bkchr** [comment]
I yanked the `wasm-instrument` crate, so this is solved for now: https://github.com/paritytech/wasm-instrument/issues/20
