### ISSUE TITLE
Encountered an error: WebSocket at Capacity: Exceeded max fragments.

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/substrate#1160]
**Dev local testnet:**
**version:** substrate branch master, f1960129-x86_64-linux-gnu (now it's the last)
When running the substrate **dev** node,  then put a about >700KB file, to UI (data.bytes) by  <https://polkadot.js.org/apps/next/#/extrinsics> (local node).
Substrate node client will echo:  (And the UI is disconnect to substrate node about 1 second)
```
Encountered an error: WebSocket at Capacity: Exceeded max fragments.
Enable a logger to see more information.
```
![_ _20181126094649](https://user-images.githubusercontent.com/34789555/48988378-38638200-f160-11e8-9a56-5113af99c4f9.png)

**Tested some data.bytes, such as:** contract.call/create, grandpa.reportMisbehavior, consensus.remark.

**Comment by jiangfuyao** [comment]
**BBQ testnet:**
When use the bbq-publice-testnet, put a > 100KB file, have error. But put a file about 7KB  is ok.
 
![_ _20181126115717](https://user-images.githubusercontent.com/34789555/48992488-ebd57200-f172-11e8-8596-c57c2bfe3223.png)

**Comment by gavofyork** [comment]
@tomusdrw any ideas?

**Comment by jiangfuyao** [comment]
No need wasm file to confirm. any type is ok.

**Comment by jiangfuyao** [comment]
Reference: <https://github.com/gorilla/websocket/issues/245>
& <https://github.com/ChromeDevTools/devtools-protocol/issues/24>

**Comment by gavofyork** [comment]
should be fixed now.
