### ISSUE TITLE
Ctrl-C didn't work

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/substrate#1161]
When the substrate node running long time, Ctrl-C didn't work.
version: the last master.

**Comment by jiangfuyao** [comment]
is work, but dis delay

**Comment by bkchr** [comment]
I observed the same behavior. The delay is mostly just for validator nodes. 
As this is annoying, I reopen this bug that it gets fixed.

Could be related to: https://github.com/paritytech/substrate/issues/1206
