### ISSUE TITLE
Looking for some support on - Remove `without_storage_info` on pallets & migration to BoundedVec ...

### ISSUE THREAD

**Issue by rajesh-nodle** [paritytech/substrate#11615]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

> Issue closely related to ...

* [Remove `without_storage_info` on pallets · Issue #8629 · paritytech/substrate](https://github.com/paritytech/substrate/issues/8629)

* [BoundedVec + Shims for Append/DecodeLength by kianenigma · Pull Request #8556 · paritytech/substrate](https://github.com/paritytech/substrate/pull/8556)

Trying to migrate instances of `Vec` to `BoundedVec` & removal of `without_storage_info` annotations for nodle pallets. 

Hit With some `MaxEncodedLen` & `Clone` trait bound errors.

**Shared some demo pallet to simplify & reproduce the issue.**

https://github.com/rajesh-nodle/tst-demo

Here in this context, integrated `BoundedVec` as part of `struct Validator`

https://github.com/rajesh-nodle/tst-demo/blob/d36d477ab1872798c25972acf23c09ecf1fea12a/pallets/tst-demo/src/types.rs#L118

![](https://i.imgur.com/8JvDNsd.png)

> Issue-1 :: Removal of `without_storage_info` is causing error "the trait `MaxEncodedLen` is not implemented"

![](https://i.imgur.com/Ohg7HL9.png)

![](https://i.imgur.com/apkzPWo.png)

> Issue-2 :: Looks like Clone is not derived for const type `ConstU32`, unable to use it as part of the struct `struct Validator`

https://github.com/rajesh-nodle/tst-demo/blob/d36d477ab1872798c25972acf23c09ecf1fea12a/pallets/tst-demo/src/mock.rs#L205

![](https://i.imgur.com/encDiAG.png)

![](https://i.imgur.com/FSs0oEr.png)

Can I have some suggestions on rightway in migrating it?

### Steps to reproduce

- Demo pallet to reproduce the issue | https://github.com/rajesh-nodle/tst-demo

**Comment by shawntabrizi** [comment]
I think you need to just add the derive macro to the `UnlockChunk` type. Here is an example from a random struct in Substrate:

```
/// Store named reserved balance.
#[derive(Encode, Decode, Clone, PartialEq, Eq, RuntimeDebug, MaxEncodedLen, TypeInfo)]
pub struct ReserveData<ReserveIdentifier, Balance> {
	/// The identifier for the named reserve.
	pub id: ReserveIdentifier,
	/// The amount of the named reserve.
	pub amount: Balance,
}
```
