### ISSUE TITLE
nomination-pools: allow pool operators to manage claimable funds

### ISSUE THREAD

**Issue by tugytur** [paritytech/substrate#11638]
Currently when someone joins a nomination pool they have to actively manage it by claiming rewards or increasing their bond.
From our experience delegators want to stake and forget. Depending on the complexity of the custody this would be a rather big burden.
 
It would be great if the pool operator could take over this task for their members.
A member could set a default action for claimable funds when joining a pool, `increase_bond` or `withdraw_claimables` and then anyone could trigger the event and pay the transaction fees. This would allow the pool operator to take over this task.

@kianenigma mentioned that this should generally be possible to add but for simplicity reasons it was kept the way it is.
This feature would make the staking experience more seamless.

**Comment by kianenigma** [comment]
This sounds like a good improvement to explore! we will look into it.

**Comment by Doordashcon** [comment]
Hello @kianenigma, from the issue description I gathered the following.

1.  Anyone that joins includes the initial depositor?
2.  Members who are already part of a pool need an extrinsic to set a claimable action.
3.  New members can set a claimable action upon joining a pool.
4. This change won't be backward compatible.

**Comment by kianenigma** [comment]
cc @rossbulat please look into this.

**Comment by kianenigma** [comment]
Okay, my thoughts on this are: 

The only reasonable action for you is that you will allow the pool operator to call `bond_extra(BondExtra::Rewards)` on your behalf, at any point in time. Seems safe to me, but there might be edge cases where the operator can abuse this. 

This must be entirely optional. Existing pool members should not be affected by this. 

We can explore doing this with a lazy migration, or else you need to be very careful in how you write the migration for this.

**Comment by rossbulat** [comment]
This is a nice addition, but for many users it will be a fun experience to go back to the dashboard on a daily basis and discover how much reward they've received. This also encourages more time on the dashboard & engage more with the network. So adding a feature, although nice, potentially prohibits this positive user pattern & they will forget about checking Polkadot in the future.

**Comment by Doordashcon** [comment]
Hopefully making this feature optional should mitigate this risk, I also think nominators would want to check the actions of their pool operators from time to time.

**Comment by kianenigma** [comment]
indeed this should be option, and default is current behavior.
