### ISSUE TITLE
Include runtime API defs into metadata

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#11648]
Context: https://github.com/polkadot-js/api/issues/4930

This will help client to query the available runtime APIs and able to invoke them with correct data.

**Comment by athei** [comment]
cc @ascjones 

This should be added to the `sp_api::decl_runtime_apis!` proc macro. It is essentially the same that ink! does for its messages minus selector generation.

**Comment by gilescope** [comment]
Given that we're pushing more people to use state Call on the grounds that runtime api calls are on-chain upgradable (unlike rpc calls), we really do need to include them in the metadata. It's currently not a great dev experience that people code them up and then don't see them in the polkadot-js when they run it against their new chain.

**Comment by athei** [comment]
I agree. However, the same is true for RPC's. So it doesn't make it worse at least.

**Comment by bkchr** [comment]
Yeah, you also only see available rpc calls, but that is all. You don't see parameters that you need to pass and that you get back.

**Comment by gilescope** [comment]
No but RPCs were never on chain upgradable  so this is very much an
awesomeness unlock.

**Comment by agryaznov** [comment]
addressed in https://github.com/paritytech/substrate/pull/13302

**Comment by lexnv** [comment]
The PR which added RuntimeAPI support for the metadata
- https://github.com/paritytech/substrate/pull/13302

Stabilization PR for the Metadata V15 (features added to the V15 included in the PR description for more details):
- https://github.com/paritytech/substrate/pull/14481
