### ISSUE TITLE
Make `get_dispatch_info` and `weight_to_fee` Available via state_call

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#11665]
When constructing XCM Transact calls, it's useful to have an idea of how much weight some call will consume and how much that weight will cost in order to `BuyExecution`. `query_info` only takes a fully encoded extrinsic and returns the weight and fee, but requires some hacks, namely:

- Users must add some bytes to represent an extrinsic (signature/signed extensions), but an XCM Transact will just have the call.
- The return includes the length fee and the `ExtrinsicBaseWeight`, which are not relevant in Transact.

The [addition of these two endpoints](https://github.com/paritytech/substrate/blob/ef66142/frame/transaction-payment/rpc/runtime-api/src/lib.rs) would allow submission of a `Call` and obtaining its weight and a fee estimate (with the user knowing that the weight to fee rate can be variable so they'll want to supply a little extra):

- [`fn get_dispatch_info(call) -> DispatchInfo { weight, ... };`](https://github.com/paritytech/substrate/blob/ef66142/frame/support/src/weights.rs#L303) (useful for specifying required weight)
- [`fn weight_to_fee(weight) -> Balance;`](https://github.com/paritytech/substrate/blob/ef66142/frame/support/src/weights.rs#L656) (useful for buying execution)

Related: https://github.com/polkadot-js/apps/issues/7688

**Comment by bkchr** [comment]
> * [`fn get_dispatch_info(call) -> DispatchInfo { weight, ... };`](https://github.com/paritytech/substrate/blob/ef66142/frame/support/src/weights.rs#L303) (useful for specifying required weight)

This is already returned by [`payment_querInfo`](https://github.com/paritytech/substrate/blob/bc7a1e6c19aec92bfa247d8ca68ec63e07061032/frame/transaction-payment/rpc/src/lib.rs#L94-L119).



> * [`fn weight_to_fee(weight) -> Balance;`](https://github.com/paritytech/substrate/blob/ef66142/frame/support/src/weights.rs#L656) (useful for buying execution)

And should that not be doable with `payment_queryFeeDetails`?

**Comment by joepetrowski** [comment]
> This is already returned by [payment_querInfo](https://github.com/paritytech/substrate/blob/bc7a1e6c19aec92bfa247d8ca68ec63e07061032/frame/transaction-payment/rpc/src/lib.rs#L94-L119)

Ah, I didn't see that. OK :+1: 

> And should that not be doable with `payment_queryFeeDetails`?

AFAIK, no, because it expects an extrinsic, not just a call.

**Comment by athei** [comment]
But is there any reason why you couldn't turn your call into an extrinsic and then submit it? It shouldn't matter with which key the extrinsic is signed.

**Comment by joepetrowski** [comment]
It's _possible_ but it's also kind of a hack IMO. @TarikGul wrote [this script](https://github.com/TarikGul/yarn-pjs-template/blob/master/main.ts) to do that and that's what I use now.

It also doesn't give you the weight and execution cost of the call, because it includes `ExtrinsicBaseWeight` and the length fee. Calls made over XCM don't have this overhead. Again, it's OK-ish as it's an overestimate, but IMO we expect an increase in para-to-para interaction with instructions that are not signed by users, so we should expose weight and fee info related to executing the instructions and not on verifying signatures.

**Comment by xlc** [comment]
One thing I would like to add is that as we want to start using light client more, which doesn't supports custom RPC, we should avoid adding more custom RPC instead. The alternative solution is add new runtime API and use `state_call` to call the runtime API.

**Comment by joepetrowski** [comment]
Yes, that's why I linked to the runtime API source in the main body.
https://github.com/paritytech/substrate/blob/ef66142/frame/transaction-payment/rpc/runtime-api/src/lib.rs

**Comment by muharem** [comment]
Had a chat with @bkontur 
Picking up the issue

**Comment by athei** [comment]
Please keep in mind what @xlc said: Don't add a new RPC. Having a new runtime API should be enough in order to call it through `state_call`.
