### ISSUE TITLE
pallet benchmarking: Incorrect step-size rounding

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#11667]
Just writing this down so i dont forget it...

## Current Situation

Suppose you have a step size of 50 for a parameter `c` in range `[0, 999]`.  
The step size will be calculated as integer division: `⌊999 / 50⌋ = ⌊19.98⌋ = 19`.  
When the multiplied with up to 50, the final value is 950 instead of 998.  

## Fix

Calculate the step size as float and then round the result of the following multiplication.    
Then re-benchmark the pallets.

**Comment by bernardoaraujor** [comment]
yo @ggwpez can I give this a try?

**Comment by shawntabrizi** [comment]
@bernardoaraujor yes go for it. There is more than this to though, sometimes we allocate too many steps for a function.

For example:

assume a range between 0 and 99.

We want 50 steps.

The math is:

(99 - 0) / 50 = 1 with integer division.

Now we calculate the actual number of steps:

(99 - 0) / 1 = 99 steps

Ideally, we should only really take 50 steps, but make sure to always take at least 50 steps.

So the distribution of steps should be non linear in cases like this

**Comment by bernardoaraujor** [comment]
I have a working solution here: https://github.com/bernardoaraujor/substrate/commit/541a28dd096f5c689d04040f8bdd08e258006a8c

please note that when doing the case in the original issue description (`self.steps=50`, `range=[0-999]`) the last value is `979`, not `998`.
```
$ cargo run --features runtime-benchmarks -- benchmark pallet --pallet pallet_utility --extrinsic batch --steps 50 --low 0 --high 999
...
Data points distribution:
    c   mean µs  sigma µs       %
    0     411.2         0    0.0%
   19      1515         0    0.0%
   39      3098         0    0.0%
   59      3522         0    0.0%
   79      5155         0    0.0%
   99      6110         0    0.0%
  119      7271         0    0.0%
  139      7790         0    0.0%
  159      9336         0    0.0%
  179     10190         0    0.0%
  199     10880         0    0.0%
  219     13910         0    0.0%
  239     12710         0    0.0%
  259     13580         0    0.0%
  279     13470         0    0.0%
  299     13900         0    0.0%
  319     16930         0    0.0%
  339     15110         0    0.0%
  359     18820         0    0.0%
  379     19250         0    0.0%
  399     20940         0    0.0%
  419     19980         0    0.0%
  439     19960         0    0.0%
  459     20120         0    0.0%
  479     22340         0    0.0%
  499     23180         0    0.0%
  519     23290         0    0.0%
  539     24470         0    0.0%
  559     25390         0    0.0%
  579     31220         0    0.0%
  599     39290         0    0.0%
  619     42440         0    0.0%
  639     54540         0    0.0%
  659     36650         0    0.0%
  679     38390         0    0.0%
  699     43850         0    0.0%
  719     46230         0    0.0%
  739     47070         0    0.0%
  759     47050         0    0.0%
  779     45980         0    0.0%
  799     48040         0    0.0%
  819     59320         0    0.0%
  839     60510         0    0.0%
  859     55050         0    0.0%
  879     50540         0    0.0%
  899     51450         0    0.0%
  919     50870         0    0.0%
  939     49910         0    0.0%
  959     46260         0    0.0%
  979     45550         0    0.0%
...
```

the main point of the solution is that it sticks to the provided number of steps during the `for` loop, and rounding from `f32` to `u32` only happens for the calculation of each `component_value`.

**Comment by bernardoaraujor** [comment]
should I also re-benchmark the FRAME pallets and include it in the PR?

**Comment by ggwpez** [comment]
Thanks @bernardoaraujor. Please open a Merge Request.  
Regarding the 998 vs 979, we should probably divide by `self.steps-1` instead of `self.steps`, since it starts at 0 and `self.steps-1` will be the highest value that the step size will be multiplied with. Then the values should be very close.
