### ISSUE TITLE
nomination-pools: optimize re-bonding unclaimed rewards. 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11671]
There is an option in pools to directly bond your unclaimed rewards. This is currently coded, as of https://github.com/paritytech/substrate/pull/11669, such that is basically like a transfer. The funds are literally transferred to your account, and taken out again. 

We can and should optimize this such that the account of the pool member is not touched in this process. Although, since they pay the fee anyways, their account data is already in overlay. Some code cleanup can also be done via doing this. 

https://github.com/paritytech/substrate/blob/82287b0705ebeee563507cb9fb81f2e9d3611d1d/frame/nomination-pools/src/lib.rs#L1496-L1502

**Comment by Szegoo** [comment]
I am going to give this a try.

**Comment by kianenigma** [comment]
We tried this with @Szegoo in the linked PR and it proved to complicate the code quite a lot. Not something that we want to do for now. If we want to re-visit, this is the best we've got so far: https://github.com/paritytech/substrate/pull/11767#issuecomment-1216302362
