### ISSUE TITLE
nomination-pools: add optional commission 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11672]
Currently, we don't have commission, and we prefer to keep the code simple and ship without this. Nonetheless, it is reasonable to add an optional commission for pool operators.

**Comment by Szegoo** [comment]
I have a couple of questions about this issue.

If I understand this correctly by pool operators you mean all the pool roles inside the ```PoolRoles``` struct?

- Do all of the administrative roles get the commission? Maybe we could make choosing who receives a commission configurable(e.g setting that only the nominator gets the commission). Also, do all of them get the same share of the commission, and that should probably also be configurable.
- I assume that the commission is taken from the earned rewards.

**Comment by kianenigma** [comment]
Some notes, I propose we re-think the commission and not make it be a "free forever commission" system like staking. Each pool member can set two commission values: 

```rust 
struct Commission {
  current: Percent
  max_ever: OptionPercent,
} 

impl Default for Commission {
  fn default() -> Self {
    current: Percent::zero(),
    max_ever: Percent::one(),
  }
}
```

with the following rules: 

1. `current` can NEVER be set to a value more than `max_ever`.
2. `max_ever` can never be increased.

**Comment by kianenigma** [comment]
A rate limit on the maximum change is also a good idea.

**Comment by Szegoo** [comment]
Ok, so if I understand this correctly the `root` of the pool should be able to set the commission rate, but we also want each pool member to define what is the maximum commission that they are willing to pay, this is what the `Commission` struct from the above example should be used for, right?

**Comment by Szegoo** [comment]
Ok, so if I understand this correctly the `root` of the pool should be able to set the commission rate, and also define some maximum for it so that we don't have the problem mentioned in #6920 right?

**Comment by kianenigma** [comment]
> > Instead, each pool member can set two commission values:
> 
> Shouldn't these two values be set by the pool operators?

indeed, I meant to say that.

**Comment by kianenigma** [comment]
Having a rate change as well, this is the commission struct that has to be stored/updated per-pool (new field of `BondedPools`): 

```
struct Commission {
  // current commission percentage. 
  current: Perbill,
  // If set, the commission can never go above this. If set, this value can never be updated to a lower amount. The only way to change this is to fully dismantle the pool. 
  max_ever: Option<Perbill>,
  // If set, 
  max_change: Option<()>
 
} 

struct CommissionChange {
  prev:
  prev_set: 
```
