### ISSUE TITLE
Missing logs after `cargo update` in the node template

### ISSUE THREAD

**Issue by gdethier** [paritytech/substrate#11684]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When cloning the [substrate node template](https://github.com/substrate-developer-hub/substrate-node-template), upgrading all dependencies (i.e. running `cargo update`) and running the node, some log messages are missing (the name of the node, system information, benchmark scores, etc.).

The problem has already been described on [StackExchange](https://substrate.stackexchange.com/questions/3147/node-startup-message-missing-after-upgrade-to-polkadot-v0-9-23) and a workaround submitted in the form of [an answer](https://substrate.stackexchange.com/a/3278/2738).

I will shortly submit a PR implementing the workaround.

### Steps to reproduce

- Clone the [node template](https://github.com/substrate-developer-hub/substrate-node-template)
- Run `cargo update`
- Run `cargo build --release` 
- Run the node: `./target/release/node-template --dev`

**Comment by bkchr** [comment]
Superseded by: https://github.com/paritytech/substrate/issues/11691
