### ISSUE TITLE
Extract ImportQueue code from the network crate into consensus_common

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1168]
re: https://github.com/paritytech/substrate/issues/784

Currently a lot of the `ImportQueue` pluggable consensus trait lives in the `substrate-network` crate. All general parts of this (including the `BasicQueue`) should be extracted as possible.

**Comment by gterzian** [comment]
I'd like to take this one on, if it's still unassigned. Looks like a good way to get to know a few parts of the system...

**Comment by gterzian** [comment]
@rphmeier Looking at the `ImportQueue` trait, it appears this one is perhaps quite network specific(using for example `BlockData`). Should we leave that in "network", and rather try to move things like `Verifier` into "consensus"?

There is currently a circular dependency when using "network" from "consensus/common", which is another reason we might want to leave some things, like `ImportQueue`, in "network"...

**Comment by rphmeier** [comment]
We want to have the dependency on `consensus-common` in `network`.
Things that should be in `consensus-common`:
  - `ImportQueue` trait: probably not using `network::BlockData` but another type that accomplishes similar goals
  - `BasicImportQueue` implementation and `Verifier` trait. (we may extract this further to another crate as well)

Things that should be in `network`:
  - adapter code for taking fetched `BlockData` and turning it into whatever `ImportQueue` needs
  - calling `ImportQueue` with said data.

**Comment by gterzian** [comment]
Ok, here are a few observations:

1. With regards to Network -> ImportQueue communication, it appears to be mostly the call to `import_blocks` inside `ChainSync.on_block_data`, as well as `import_queue.stop`. 
2. With regards to ImportQueue -> Network, it seems to be all via the `NetworkLink`, which essentially allows to methods on both `Protocol` and `ChainSync` to be called from with the import queue thread.

So my conclusion is that the only way to extract import queue from network, without moving a lot of other types along with(who really do belong in network I think), is to remove the `ChainSync` and `Context` dependencies that are used to implement `Link` in `NetworkLink`. 

One solution would be to replace the `with_sync` method calls with either sending messages back to `Service`, or do something with futures. Those messages, or futures, would then be handled as part of `Service.run_thread`. 

So `NetworkLink` would become basicallly a sender of messages(or something with futures) to the network service. 

I would personally take it a step further and also have a channel to send message from `ChainSync.on_block_data` to the import_queue, which would replace what is currently done with the `self.data.signal.notify_one();` with basically waiting for a message to come in. I think it would allow `AsyncImportQueueData<B>` to be local to the import thread, which might allow us to remove the mutexes and rwlocks inside of it. 

I guess the only reason to have the method calls on `ChainSync` and `Context` inside `NetworkLink` would be if the import queue actually really needs to block while those method calls happen. 

What do you think? @rphmeier

**Comment by rphmeier** [comment]
@gterzian Isn't `NetworkLink` a trait? An implementation can live in the sync crate, same as now, but it should be defined in `consensus-common`.

The interface changes for `on_block_data` seem reasonable, and having the link work via a `Sender` whose messages are processed asynchronously by the network worker (if it's done using Futures, it should be possible to somehow access the underlying libp2p executor)

**Comment by gterzian** [comment]
Ok, I will give the `Sender` approach a try, if anything it should be an interesting experiment to see how that  approach fits in the system. It could help make things more independent, I think.

`NetworkLink` is an implementation of `Link`, and I think you're right that we could keep the implementation inside `network` and only move the trait to `consensus-common`(it's the implementation that uses other stuff from `network`). I'll try that first, and then move to the `Sender` stuff, so that we can always drop the later commits if it's somehow undesirable.
