### ISSUE TITLE
Allow Aura's forced delay to be configured

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1170]
It is currently hard-coded in node but should be possible to configure on-chain.

**Comment by rphmeier** [comment]
This speaks to the general point that we sometimes will want to have certain APIs be present in block authoring logic (timestamp, parachains in Polkadot, GRANDPA) even if the underlying runtime doesn't support them at all times (taking into account upgrades). Calls to those APIs should just fail with `NotAvailable` or similar when the runtime doesn't support them anymore.

cc @bkchr

**Comment by bkchr** [comment]
Hmm, it is only required for the `native` runtime to have all APIs implemented as you compile. So, you could easily work with your node version that uses an API, that the `wasm` runtime does not support. 
It is on my my agenda to make `has_api` be more usable and easier to implement. So you could make sure that an API is present in a given `wasm` runtime.

**Comment by rphmeier** [comment]
(Aura now draws block time from a custom API)
