### ISSUE TITLE
Exported method `TryRuntime_on_runtime_upgrade` is not found

### ISSUE THREAD

**Issue by wetalice** [paritytech/substrate#11718]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I according to this [document](https://docs.substrate.io/v3/tools/try-runtime/), the try-Runtime code written does not run.
my project [https://github.com/listenofficial/listen-parachain/blob/main/runtime/tisten/src/lib.rs#L1449](https://github.com/listenofficial/listen-parachain/blob/main/runtime/tisten/src/lib.rs#L1449)
and my node cargo toml is [https://github.com/listenofficial/listen-parachain/blob/main/node/tisten/Cargo.toml](https://github.com/listenofficial/listen-parachain/blob/main/node/tisten/Cargo.toml)
********************************************************
command 
```
cargo run --features try-runtime try-runtime \ --execution native-else-wasm \ --chain test \ on-runtime-upgrade \ live \ --uri ws://47.108.199.133:9947
```
Error info 
```
Error: Input("failed to execute TryRuntime_on_runtime_upgrade: Other: Exported method TryRuntime_on_runtime_upgrade is not found")
```

### Steps to reproduce

```
git clone https://github.com/listenofficial/listen-parachain.git
cargo run --features try-runtime try-runtime \ --execution native-else-wasm \ --chain test \ on-runtime-upgrade \ live \ --uri ws://xxxxxxx:9947
```

**Comment by bkchr** [comment]
Run with `--chain dev`. Your `test` chain spec is loaded from a file and this chain spec doesn't contain the wasm with the required runtime api.
