### ISSUE TITLE
assert_ne ,macro should be available

### ISSUE THREAD

**Issue by MrishoLukamba** [paritytech/substrate#11723]
I think this is missing in testing in substrate runtime

**Comment by MrishoLukamba** [comment]
@shawntabrizi @bkchr

**Comment by sudipghimire533** [comment]
It's already available isn't it? `assert_eq` and `assert_ne` is not to be defines by substrate but should already be there from rust

**Comment by KiChjang** [comment]
Yes indeed: https://doc.rust-lang.org/stable/std/macro.assert_ne.html.
