### ISSUE TITLE
SRML Democracy: Should we also only allow voting after checking that the data mapped to referendum index is valid

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate#1173]
Please refer to the `TODO` in the following PR https://github.com/paritytech/substrate/pull/1172#discussion_r236973477

Currently we allow voting for a referendum index only if:
* its referendum index `ref_index` is a key in `ReferendumInfoOf`.

Should we add an additional check to allow voting for a referendum index only if:
* its referendum index `ref_index` is a key in `ReferendumInfoOf`, AND additionally;
* **the data that the `ref_index` is mapped to in `ReferendumInfoOf` is valid**

For example, at the moment a voter can vote if they are voting for a referendum index `ref_index` that is a key in `ReferendumInfoOf`, even if the data that the `ref_index` maps to returns either:
* `None`, OR
* `Some(...)`, **where the block number, proposal, or vote threshold may somehow not have been defined or may be invalid** 

Perhaps a solution (if necessary) would be to add assertions in `inject_referendum` https://github.com/paritytech/substrate/blob/master/srml/democracy/src/lib.rs#L238 to validate that the provided arguments are valid?

Note that `ReferendumInfoOf`  is defined here https://github.com/paritytech/substrate/blob/master/srml/democracy/src/lib.rs#L159, as the following:

```
/// Information concerning any given referendum.
pub ReferendumInfoOf get(referendum_info): map ReferendumIndex => Option<(T::BlockNumber, T::Proposal, VoteThreshold)>;
```

**Comment by gavofyork** [comment]
if `ref_index` maps to `None`, then it is by definition not a key in `ReferendumInfoOf`. If it maps to `Some`, then we assert that it is valid, since a) it is already convention to assume storage items are valid and b) there's no way of identifying all possible invalid items.
