### ISSUE TITLE
Rename outer enums to `RuntimeCall`, `RuntimeEvent`, etc

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11736]
we should really just rename the `Call` generated by the construct_runtime! to `RuntimeCall`.

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/pull/8458#discussion_r602125898_

- [x] Call
- [x] Event
- [x] Origin

--- 

See confusions such as https://substrate.stackexchange.com/questions/3360/using-scheduler-pallet-to-schedule-contract-pallet-call

**Comment by tifecool** [comment]
I'd like to pick up this issue. Would I have to work in-depth with macros?

**Comment by KiChjang** [comment]
I could if it's urgent, otherwise other people can pick this up if they're interested.

**Comment by kianenigma** [comment]
yeah was just wondering since we talked about it in person. Nah, I don't think it is urgent and it is a good first-issue for other contributors to FRAME.

**Comment by tifecool** [comment]
Couldn't figure out where to change the Calls. I don't mind someone else picking the issue up. Would be nice to see the solution

**Comment by Szegoo** [comment]
> Couldn't figure out where to change the Calls. I don't mind someone else picking the issue up. Would be nice to see the solution
> 
> Edit: Still attempting, but if someone else takes it it's fine.

Have you managed to get it working? If not I may make a PR. I believe that the files that need to be modified are: `frame/support/procedural/src/construct_runtime/expand/call.rs` and `frame/support/procedural/src/construct_runtime/expand/event.rs`

**Comment by tifecool** [comment]
> I believe that the files that need to be modified are: frame/support/procedural/src/construct_runtime/expand/call.rs and frame/support/procedural/src/construct_runtime/expand/event.rs

Hey @Szegoo. Funny enough just figured that out yesterday hence the "Still attempting" edit. Now I'm getting the error:
`error[E0433]: failed to resolve: use of undeclared type "Call" `

Dropping the issue now. Please go ahead 😇️

**Comment by Szegoo** [comment]
@tifecool Sorry, I didn't notice the "Still attempting" edit. Feel free to continue working on this if you want to, I didn't want to make any pressure on you. If you really want to drop this issue, I would be happy to work on this.

**Comment by tifecool** [comment]
@Szegoo It's no pressure. You're welcome to work on it. I'll learn from your solution.

**Comment by kianenigma** [comment]
We could probably use a small PR for origin at some point too?

**Comment by Szegoo** [comment]
> We could probably use a small PR for origin at some point too? 

I will open a new PR for that.

**Comment by Szegoo** [comment]
Shouldn't this issue be closed?

**Comment by KiChjang** [comment]
Yes.

**Comment by shredding** [comment]
Please update the documentation as well. It'll save the next dev after me hours of frustration.
