### ISSUE TITLE
Metadata Api should be optional

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#11743]
Currently the Substrate client requires that every runtime implement the Metadata runtime Api. But not all runtimes will need this Api. When writing a simple runtime, probably without frame, you have to stub this runtime api with something like this

```rust
impl sp_api::Metadata<Block> for Runtime {
	fn metadata() -> OpaqueMetadata {
		OpaqueMetadata::new(vec![0])
	}
}
```

Is metadata intended for use in FRAME only? If so, I don't think it should be required.

cc @kianenigma 
```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/substrate/issues/13331
```

**Comment by kianenigma** [comment]
cc @bkchr @koute

**Comment by kianenigma** [comment]
As far as I understood, similar to #14198, all such bounds would go away after https://github.com/paritytech/substrate/issues/13331. If confirmed, let's close this one as well in favor of it.
