### ISSUE TITLE
Offchain Worker Api should be optional

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#11742]
Currently the Substrate client requires that every runtime implement the Offchain worker runtime Api. Many (maybe even most?) runtimes do not use offchain workers and have to stub this Api like

```rust
impl sp_offchain::OffchainWorkerApi<Block> for Runtime {
	fn offchain_worker(_: &Header) {}
}
```

While it isn't the hardest thing to paste that code into your runtime, it adds an entire dependency on `sp_offchain` for runtimes that don't otherwise need it.

I suggest the offchain worker api not be required.

cc @kianenigma

**Comment by kianenigma** [comment]
Probably has the same answer as https://github.com/paritytech/substrate/issues/11743, so will close to keep our enormous issue backlog at least one less :D
