### ISSUE TITLE
nomination-pools: Add era to `Unbonded` event 

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate#11749]
In nomination-pools tests that test cases that has Era as part of the case, it is a good idea to add in the `assert_eq!` of `pool_events_since_last_call` the era as part of the `eq`.
E.g. in the [partial_unbond_max_chunks](https://github.com/paritytech/substrate/blob/master/frame/nomination-pools/src/tests.rs#L2099) and [this assert_eq!](https://github.com/paritytech/substrate/blob/master/frame/nomination-pools/src/tests.rs#L2132-L2141) could have something like:
```
	Event::Unbonded { member: 20, pool_id: 1, balance: 3, points: 3, era: 1 },
	Event::Unbonded { member: 20, pool_id: 1, balance: 1, points: 1, era: 2 }
```

**Comment by hirschenberger** [comment]
So a `EraIndex` has to be added to `Event::Unbonded`. Does it make sense to add it to other events as well?

**Comment by kianenigma** [comment]
Which other events you have in mind @hirschenberger? It should be events that are era-related. Unbonding has a clear link to eras, because you will be unbnded 28 eras after. For, bonding for example doesn't have any significant semantical relation.

**Comment by kianenigma** [comment]
Updated the title to clarify what is meant :)
