### ISSUE TITLE
Docker image used in `node-template`'s docker-compose.yml is outdated

### ISSUE THREAD

**Issue by lucasvanmol** [paritytech/substrate#11750]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The docker image in the node template's `docker-compose.yml`  seems to be using an outdated version of Cargo (see steps to reproduce below). [This line](https://github.com/substrate-developer-hub/substrate-node-template/blob/9c89be106cb98f4a0ede20d8880ec63779232870/docker-compose.yml#L6) in the [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template) repo was causing the issue, and it seems to work if updated to use a newer tag e.g. [paritytech/ci-linux:eb1f6a26-20220518](https://hub.docker.com/layers/ci-linux/paritytech/ci-linux/eb1f6a26-20220518/images/sha256-cb96cc30c0ca864633a3c1de53bffdb3d9d5a66fd94443b2a80d9ffae248dd69?context=explore)

The same line in this repository is in [bin/node-template/docker-compose.yml](https://github.com/paritytech/substrate/blob/c28702f3f2af48b3f04374d41d3f91add33e4e45/bin/node-template/docker-compose.yml#L6)

### Steps to reproduce

```
lucasvanmol@C02HF7J3Q6L4-w3f dev % git clone https://github.com/substrate-developer-hub/substrate-node-template && cd substrate-node-template
Cloning into 'substrate-node-template'...
remote: Enumerating objects: 1951, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 1951 (delta 2), reused 6 (delta 1), pack-reused 1941
Receiving objects: 100% (1951/1951), 47.59 MiB | 15.04 MiB/s, done.
Resolving deltas: 100% (936/936), done.
lucasvanmol@C02HF7J3Q6L4-w3f substrate-node-template % chmod +x ./scripts/docker_run.sh            
lucasvanmol@C02HF7J3Q6L4-w3f substrate-node-template % touch .local
lucasvanmol@C02HF7J3Q6L4-w3f substrate-node-template % ./scripts/docker_run.sh cargo check
*** Start Substrate node template ***
[+] Running 1/0
 ⠿ Network substrate-node-template_default  Removed                                                                                                                                                    0.1s
[+] Running 1/0
 ⠿ Network substrate-node-template_default  Created                                                                                                                                                    0.0s
error: failed to parse manifest at `/var/www/node-template/node/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

**Comment by bkchr** [comment]
CC @NukeManDan

**Comment by NukeManDan** [comment]
@alvicsam thanks for the downstream update - it's fix here now too?

**Comment by alvicsam** [comment]
@NukeManDan it can be fixed in https://github.com/paritytech/substrate/pull/11802 but I think the `docker-compose.yml` can be removed since it doesn't work (there is no Cargo.toml file)
