### ISSUE TITLE
[try-runtime] Missing logs from try-runtime CLI

### ISSUE THREAD

**Issue by Marcin-Radecki** [paritytech/substrate#11772]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Hello, we're working on integrating `try-runtime` feature into our chain, and we faced issue in which nothing is being logged to std out, despite setting correct (as per docs) `RUST_LOG` and the whole feature in general working correctly (process exit with 0 code). The command should at least print line `TryRuntime_on_runtime_upgrade executed without errors. Consumed weight [...]`. (as per https://www.crowdcast.io/e/substrate-seminar/41) .

### Steps to reproduce

On Ubuntu 20.04:
1.  git clone branch https://github.com/Cardinal-Cryptography/aleph-node/tree/try-runtime-on-official-upstream
2.  run `cargo run --release --features=try-runtime bootstrap-chain --base-path /tmp --account-ids 5D34dL5prEUaGNQtPPZ3yN5Y6BnkfXun
KXXz6fo7ZJbLwRRH,5GBNeWRhZc2jXu7D55rBimKYDk8PGk8itRYFTPfC8RJLKG5o,5Dfis6XL8J2P6JHUnUtArnFWndn62SydeP8ee8sG2ky9nfm9,5F4H97f7nQovyrbiq4ZetaaviNwThSVcFobcA5aGab6167dK,5DiDShBWa1fQx6gLzpf3SFBhMinCoyvHM1BWjPNsmXS8hkrW > chainspec.json` (authorities does not matter here)
3. Run below command - note it does not provide any logging, but it exists successfully. We made sure it did run the `TryRuntime_on_runtime_upgrade` call by changing runtime locally to `panic!`s in some `pre_upgrade` hook.
```bash
marcin@marcin-Latitude-3520 ~/g/aleph-node-3 (try-runtime-on-official-upstream)> RUST_LOG=runtime=trace,try-runtime::cli=trace,executor=trace cargo run --release --features=try-runtime -- try-runtime  --
chain chainspec.json on-runtime-upgrade live --uri wss://ws.test.azero.dev:443
    Finished release [optimized] target(s) in 0.81s
     Running `target/release/aleph-node try-runtime --chain chainspec.json on-runtime-upgrade live --uri 'wss://ws.test.azero.dev:443'`
marcin@marcin-Latitude-3520 ~/g/aleph-node-3 (try-runtime-on-official-upstream)>                                                          
```

**Comment by bkchr** [comment]
Try downgrading `tracing-core`: https://github.com/paritytech/substrate/issues/11691

**Comment by Marcin-Radecki** [comment]
Indeed, this was the issue. Thanks!
