### ISSUE TITLE
[Frame-Feature] queryActualFee for when the weight from an extrinsic success event in known. 

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate#11780]
## Summary

Currently, we can find the estimated fee for an extrinsic that had yet to be submitted using `payment_queryInfo`, but there is no easy way to find the precise fee information about an extrinsic that is already a part of a block. I would love to add an RPC method to address this. From my understanding and testing, for chains such as Polkadot, Kusama, and Westend `rpc::payment::queryInfo` is sufficient for fee calculations, but for other given parachains such as Acala, and Shiden for example, this does not hold true as there are marginal differences between the fees. Subscan is able to calculate the fees correctly for all the chains they support, so I reached out to see their method and wanted to see if we could apply it to an RPC method.

## Example

Subscan uses the following algorithm to determine the actual fee of an extrinsic.
`(base_fee + len_fee)+(( adjusted_weight_fee/estimated_weight) * actual_weight)`

`actual_weight` -> via Known System::ExtrinsicSuccess event
`estimated_weight` -> via [GetDispatchInfo::get_dispatch_info](https://github.com/paritytech/substrate/blob/master/frame/support/src/weights.rs#L306-L310)
`base_fee` -> via [compute_fee_raw](https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/src/lib.rs#L503)
`len_fee` -> via [compute_fee_raw](https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/src/lib.rs#L503)
`adjusted_weight_fee` -> via [compute_fee_raw](https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/src/lib.rs#L503)

## Notes

I wanted to first see if something like this hold merit, and if so I am happy to tackle it. 

rel: https://github.com/paritytech/substrate-api-sidecar/issues/969

**Comment by bkchr** [comment]
Shouldn't this be fixed by https://github.com/paritytech/substrate/issues/11595?
Aka there is no need for a rpc?

**Comment by TarikGul** [comment]
Yea so that would work for all future blocks, but in our case we would need something like the calculation above for historic blocks to maintain that integrity for all fees in the past. 

I can see from substrate's perspective how this could just cloud the runtime with more rpcs when there is a current solution already in place. Happy to have this closed if that makes sense, currently writing a solution locally for us using `sp_arithmetic` [here](https://github.com/paritytech/substrate-api-sidecar/pull/974/files). I am not super familiar with the crate, so its going to take some playing around to get the precision correct.

**Comment by bkchr** [comment]
> Yea so that would work for all future blocks, but in our case we would need something like the calculation above for historic blocks to maintain that integrity for all fees in the past. 

As the rpc would require a runtime api, it would also not be backwards compatible. So, for the past you probably can only use a custom solution.
