### ISSUE TITLE
MMR Leaf Data: off-by-one error in beefy_next_authority_set

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#11797]
A given Leaf with MMR 0-based leaf index `N-1` is constructed and added to MMR during construction of block `N` [here](https://github.com/paritytech/substrate/blob/6a946fc36d68b89599d7ca1ab03803d10c78468c/frame/merkle-mountain-range/src/lib.rs#L205).

The Leaf data/contents can be seen populated [here](https://github.com/paritytech/substrate/blob/6a946fc36d68b89599d7ca1ab03803d10c78468c/frame/beefy-mmr/src/lib.rs#L157-L162) and it consists of:

```rust
// contents for leaf index <N-1> added by block <N>
MmrLeaf {
    version: <leaf-data-format-version>,
    (
        parent_num: <N-1>,
        parent_hash: <hash_of_<N-1>>,
    ),
    extra_data: <para_heads_of_<N-1>>,
    next_auth_set: <next_auth_set_of<N>>,
}
```

While this is not a show-stopper - (light)clients can simply handle this in their code - it introduces cognitive complexity and code logic corner cases.

We could avoid this and make it easier for users by changing `Leaf<N-1>` contents to:
```diff
// contents for leaf index <N-1> added by block <N>
MmrLeaf {
    version: <leaf-data-format-version>,
    (
        parent_num: <N-1>,
        parent_hash: <hash_of_<N-1>>,
    ),
    extra_data: <para_heads_of_<N-1>>,
-   next_auth_set: <next_auth_set_of<N>>,
+   next_auth_set: <next_auth_set_of<N-1>>,
}
```

**Comment by acatangiu** [comment]
AFAICT an easy fix is to move [Mmr: pallet_mmr](https://github.com/paritytech/polkadot/blob/5a09bf62ec7be0e90dfae335a80459728a896d95/runtime/rococo/src/lib.rs#L222) before `pallet_session` so that it builds its leaf before session is rotated.

But I would prefer a fix contained in `pallet_mmr` itself since above is prone to developer error when adding `pallet_mmr` to their runtime.

**Comment by Lederstrumpf** [comment]
> AFAICT an easy fix is to move [Mmr: pallet_mmr](https://github.com/paritytech/polkadot/blob/5a09bf62ec7be0e90dfae335a80459728a896d95/runtime/rococo/src/lib.rs#L222) before pallet_session so that it builds its leaf before session is rotated.

So since session is rotated prior to leaf construction currently, `next_auth_set: <next_auth_set_of<N>>,` can be distinct for forks of depth 1?

**Comment by vgeddes** [comment]
We haven't really been affected by this off-by-one issue while developing our light client (or we just worked around it).

The proposed change may affect how our light client detects authority handovers. But I have a feeling there shouldn't be any impact. If there is we can update our code.

Some background on our light client: It receives updates like the following at the start of every beefy session (Assume a session length of 10 blocks). Each update contains the beefy commitment for block N (first block of session) and the MMR leaf for block N-1 (last block of the previous session).
```
Update:
  BeefyCommitment(block=11) { validatorSetId: 1, ... }
  MmrLeaf(block=10) { nextValidatorSetId: 2, ...}

Update:
  BeefyCommitment(block=21) { validatorSetId: 2 }
  MmrLeaf(block=20) { nextvalidatorSetId: 3, ... }

Update:
  BeefyCommitment(block=31) { validatorSetId: 3, ... }
  MmrLeaf(block=30) { nextvalidatorSetId: 4, ... }
```

The light client knows it can perform an authority handover when the latest update contains a `leaf.nextValidatorSetId` that is greater than that of the previously observed value (See [code here](https://github.com/Snowfork/snowbridge/blob/dd161467d53ddfdc6290f5e50bbcb034babe1441/ethereum/contracts/BeefyClient.sol#L272)).

**Comment by seunlanlege** [comment]
actually have encountered this issue and i created this pr as a fix: https://github.com/paritytech/substrate/pull/10907

**Comment by acatangiu** [comment]
> actually have encountered this issue and i created this pr as a fix: #10907

this is actually something different - by building leaf `on_finalize()` you actually get:

```diff
// contents for leaf index <N-1> added by block <N>
MmrLeaf {
    version: <leaf-data-format-version>,
    (
        parent_num: <N-1>,
        parent_hash: <hash_of_<N-1>>,
    ),
-   extra_data: <para_heads_of_<N-1>>,
+   extra_data: <para_heads_of_<N>>,
    next_auth_set: <next_auth_set_of<N>>,
}
```

and at this point you also run into trouble with 1-block deep forks writing **different** leaf contents to offchain db for same `(parent, pos)` key.

The offchain-db thing can be fixed by also doing https://github.com/paritytech/substrate/issues/11799.

-------------------

@seunlanlege Is the mixed layout of `MmrLeaf` above really better?

Isn't light-client code simpler if it simply references leaf index `N` when interested in `extra_data` of block `N`?
(i.e. for `N=5`: leaf index 5 is the leaf added by block 6 containing `extra_data` of block 5)

**Comment by seunlanlege** [comment]
> Isn't light-client code simpler if it simply references leaf index N when interested in extra_data of block N?

So you're correct that this makes sense, but only from a leaf index perspective. 

But light clients won't be tracking leaf indexes, they'll be tracking block heights. 

And it's a bit wonky from that perspective that a leaf emitted a block `N` contains data about `N-1` especially when there's no clear advantage to having it this way.

Whereas it's easier to reason that a leaf emitted at block `N` contains information about block `N`

**Comment by acatangiu** [comment]
Aha, that makes sense. So to summarize, you're saying for a light client, the best experience to interact with `pallet-mmr` is if it exposed leafs with following format:

```rust
// contents for leaf added by block <N>
MmrLeaf {
    version: <leaf-data-format-version>,
    (
        parent_num: <N-1>,
        parent_hash: <hash_of_block<N-1>>,
    ),
    extra_data: <para_heads_at_block<N>>,
    next_auth_set: <next_auth_set_at_block<N>>,
}
```

right?

**Comment by seunlanlege** [comment]
> Aha, that makes sense. So to summarize, you're saying for a light client, the best experience to interact with pallet-mmr is if it exposed leafs with following format:

yes correct.

**Comment by vgeddes** [comment]
I'm happy with this change too. It makes sense for me and would allow us to improve some of the code in our off-chain relayers. As the relationship between block-height, leaf-index, and the desired leaf-paras-root was a bit confusing.

+1

**Comment by acatangiu** [comment]
> Aha, that makes sense. So to summarize, you're saying for a light client, the best experience to interact with `pallet-mmr` is if it exposed leafs with following format:
> 
> ```rust
> // contents for leaf added by block <N>
> MmrLeaf {
>     version: <leaf-data-format-version>,
>     (
>         parent_num: <N-1>,
>         parent_hash: <hash_of_block<N-1>>,
>     ),
>     extra_data: <para_heads_at_block<N>>,
>     next_auth_set: <next_auth_set_at_block<N>>,
> }
> ```

I'm sorry @vgeddes @seunlanlege but this doesn't seem to be possible :cry: see https://github.com/paritytech/substrate/pull/12446#issuecomment-1279011413

Closing for now, please reopen if you have any other ideas.

**Comment by acatangiu** [comment]
We decided we want to do at least this (since https://github.com/paritytech/substrate/pull/12446 isn't possible):

```rust
// contents for leaf index <N-1> added by block <N>
MmrLeaf {
    version: <leaf-data-format-version>,
    (
        parent_num: <N-1>,
        parent_hash: <hash_of_<N-1>>,
    ),
    extra_data: <para_heads_of_<N-1>>,
-   next_auth_set: <next_auth_set_of<N>>,
+   next_auth_set: <next_auth_set_of<N-1>>,
}
```

which could be as easy as:
https://github.com/paritytech/substrate/issues/11797#issuecomment-1177485479

**Comment by acatangiu** [comment]
> but since https://github.com/paritytech/substrate/pull/12753 moved the offchain storage handling to client-side gadget, there's nothing blocking doing next_auth_set_of<N> as implemented in https://github.com/paritytech/substrate/pull/12446, if I'm not mistaken?

it _could_ be done at the expense of extra runtime storage - keep non-canon full data in runtime storage instead of offchain storage and "back it up" to offchain on client-side finality, but then you still have problems when finality lags and aggressive pruning is configured; and obviously increased storage costs for the chain.

I think the wise path is to take the slightly increased code complexity on light-client side and use `<N-1>`, and thus avoid all the extra runtime storage required to work directly on `<N>`.

> Otherwise, I'll open up PR for `next_auth_set_of<N-1>`.

I think this is the right call.

@vgeddes @seunlanlege just to confirm there is no difference in light-client "runtime costs" between:

```rust
MmrLeaf @ block N {
    version: <leaf-data-format-version>,
    (
        parent_num: <N-1>,
        parent_hash: <hash_of_<N-1>>,
    ),
    extra_data: <para_heads_of_<N-1>>,
    next_auth_set: <next_auth_set_of<N-1>>,
}
```
and

```rust
MmrLeaf @ block N {
    version: <leaf-data-format-version>,
    (
        parent_num: <N-1>,
        parent_hash: <hash_of_<N-1>>,
    ),
    extra_data: <para_heads_of_<N>>,        <---- diff here
    next_auth_set: <next_auth_set_of<N>>,   <---- diff here
}
```

**Comment by seunlanlege** [comment]
> 
> 
> @vgeddes @seunlanlege just to confirm there is no difference in light-client "runtime costs" between:
> 

Yes correct.

**Comment by vgeddes** [comment]
Should not be a problem for our light client, I think.

**Comment by acatangiu** [comment]
Fixed in https://github.com/paritytech/polkadot/pull/6577
