### ISSUE TITLE
pallet-mmr: improve offchain storage, relax LeafData requirements

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#11799]
### Issue

PR https://github.com/paritytech/substrate/pull/11594 introduced fork-resistant offchain storage for MMR leaves.

Leaves are now saved offchain using `(parent_hash, pos)`-based key to be fork-resistant and later canonicalized to `pos`-based key.

Relying on `(parent_hash, pos)`-based keys means that conflicts could now only happen on 1-block deep forks, where two forks with identical line of ancestors compete to write at the same offchain key. This introduced a requirement on the `LeafData` to _only reference data coming from ancestor blocks_, so in the corner case above, the conflicting writes end up writing same values anyway.

While the current behavior works for `polkadot/kusama` BEEFY+MMR deployment, I think we can improve and eliminate the `LeafData` requirement shown above.

### Proposed solution

Leaves are added to the MMR offchain storage by runtime during `pallet_mmr::<Pallet as Hooks>::on_initialize(BlockNumber)` [here](https://github.com/paritytech/substrate/blob/6a946fc36d68b89599d7ca1ab03803d10c78468c/frame/merkle-mountain-range/src/lib.rs#L205) using indexing API. At that time `block_hash` is unavailable (block is still under construction) so we're using `parent_hash`-based key instead to _uniquely_ identify this leaf in offchain db (only it's not unique for 1-block deep forks, ergo the `LeafData` limitation).

Idea is to drop using the indexing API and instead store the new leaf in a placeholder `Pallet::NewLeaf` runtime storage item, and have the offchain worker function move/copy the leaf to offchain db _after_ the block is built and truly unique `(block_hash, pos)` is available to be used as offchain key.

The same `Pallet::NewLeaf` storage is reused for temporarily holding the new leaf at every block.

**Comment by seunlanlege** [comment]
Will pick this up on monday

**Comment by acatangiu** [comment]
Doing this will normally require an offchain database migration for any runtime deploying https://github.com/paritytech/substrate/pull/11594 (Rococo runtime >= 9260).

Right now though, `pallet-mmr` is only deployed on Rococo which is still running runtime version `9250`; if we get this change in soon, then we might get away upgrading directly from `9250` without needing database migration.

**Comment by iTranscend** [comment]
Hi, I've gone ahead to make the changes suggested in the Issue spec. 

I haven't updated the tests yet, but I'll do that over the next few days. 

I've opened a draft PR [here](https://github.com/paritytech/substrate/pull/12384).

**Comment by acatangiu** [comment]
> Hi, I've gone ahead to make the changes suggested in the Issue spec.
> 
> I haven't updated the tests yet, but I'll do that over the next few days.
> 
> I've opened a draft PR [here](https://github.com/paritytech/substrate/pull/12384).

Do you need any help here?

**Comment by iTranscend** [comment]
Hi @acatangiu. 
I've started working on the changes you suggested but I don't think I'll be able to finish them up as quick as they are needed.
I'd love it if someone else can pick up from where I stopped so we can get away with upgrading directly from `9250` without needing a database migration.

**Comment by acatangiu** [comment]
Unfortunately `offchain_worker` is not reliable enough to allow for this.. see https://github.com/paritytech/substrate/pull/12446#issuecomment-1279011413

Closing the issue as "Not possible".
