### ISSUE TITLE
Rename `node-runtime` to something containing `kitchen-sink`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11814]
the point of this is to further emphasize that `node-runtime` is NOTHING production-like, and should not be used, nor inspired from. It is, by all means, a kitchen sink:

https://stackoverflow.com/questions/33779296/what-is-exact-meaning-of-kitchen-sink-in-programming

**Comment by kianenigma** [comment]
A reasonable candidate in my opinion is `node-kitchensink-runtime` instead of `frame-kitchensink-runtime`.

**Comment by KiChjang** [comment]
I would probably call it a `playground` or a `sandbox` rather than a `kitchen-sink`, as it better communicates the intent behind what it is.

**Comment by kianenigma** [comment]
I think playground is actually more resemblance of a _minimal_ example that you build upon, more like `node-template`, but a kitchen sink (in programming context) is "galley of everything that has existed", which is almost exactly how we use node-runtime as it stands now.

**Comment by memorycancel** [comment]
Hi @kianenigma Can I pick this issue up? I'd like to have a try.

**Comment by sudipghimire533** [comment]
What if we name it `node-the-most-powerful-blockchain-in-galaxy-runtime` :rofl:
