### ISSUE TITLE
decl_module should allow no return type

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1182]
Currently all dispatchable functions declared in the `decl_module` macro require a `-> Result` snippet for the return type. They should also work without that snippet (i.e. no return type), with the body transformed such that:

```
fn foo() {
$body
}
```

becomes:

```
fn foo() -> Result {
let null: () = { $body };
Ok(())
}
```

**Comment by rphmeier** [comment]
I'm not convinced by this -- we should be adding less "magic", not more. There is no precedent in Rust for eliding return types
