### ISSUE TITLE
beefy: SignedCommitment/Justification channels should use versioned struct

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#11838]
There are multiple component sending [BEEFY SignedCommitments](https://github.com/paritytech/substrate/blob/ded44948e2d5a398abcb4e342b0513cb690961bb/primitives/beefy/src/commitment.rs#L142) between them:

- block-import <-> voter channel
- voter <-> RPC-worker channel
- **RPC public API**

All of the above (and possibly others) should instead be using [VersionedFinalityProof](https://github.com/paritytech/substrate/blob/ded44948e2d5a398abcb4e342b0513cb690961bb/primitives/beefy/src/commitment.rs#L290) instead of `SignedCommitment`.

(Changing the definitions of the [notification channels](https://github.com/paritytech/substrate/blob/7409589ab78e7cb508db873dd6384634d667b8f5/client/beefy/src/notification.rs#L37-L42) to use `VersionedFinalityProof` as their payload should surface all the places where this change is required)

**Comment by acatangiu** [comment]
hi @hzy1919, please wait for https://github.com/paritytech/substrate/pull/11821 to be merged before doing this issue,
or at least build your changes on top of https://github.com/paritytech/substrate/pull/11821.

**Comment by acatangiu** [comment]
> > 
> 
> ok, I will wait for #11821 .

#11821 has been merged, feel free to take this on whenever you like

**Comment by hzy1919** [comment]
> > > 
> > 
> > 
> > ok, I will wait for #11821 .
> 
> #11821 has been merged, feel free to take this on whenever you like

Ok , I'm working on this .
