### ISSUE TITLE
nomination-pools: RPC for pending reward

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11830]
I started this in the past, but decided to close it. Now, we need it again. Continue down the same path of my original PR.

Let's start with something a lot simpler for now: just one rpc endpoint, `nominationPools_pending_rewards` that returns just the bending rewards. The rest of the data is pretty trivial to read from the chain state.

**Comment by kianenigma** [comment]
@Szegoo

**Comment by Szegoo** [comment]
@kianenigma I will look into this.

**Comment by Szegoo** [comment]
@kianenigma I will look into this.
