### ISSUE TITLE
Fix `purge-chain` cli parameter in conjuction with `--dev`

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#1184]
When doing `cargo run -- --dev --purge-chain`, the `--dev` is ignored. This is a bug and should be fixed.

**Comment by ltfschoen** [comment]
i think it should be `cargo run -- --dev --purge-chain --dev`
i.e. when you run cargo run -- --help` it shows usage instructions: `substrate [FLAGS] [OPTIONS] [SUBCOMMAND]`
