### ISSUE TITLE
map/try_map for BoundedBTreeMap

### ISSUE THREAD

**Issue by benluelo** [paritytech/substrate#11866]
It would be useful if there was a way to iterate over an `&mut BoundedBTreeMap` and mutate each key in place. This wouldn't affect the length of the map at all, so it would be safe. Perhaps a `try_map` or something similar would be good as well, to allow for short circuiting.

I would be happy to take this on if it's deemed useful.

(BoundedBTreeMap link for the lazy: https://github.com/paritytech/substrate/blob/9a140a6190ae1527b89fe77bd426a38489526e44/primitives/runtime/src/bounded/bounded_btree_map.rs#L33)

EDIT:

After some experimentation, I think this is a better API:

```rust
pub fn map<T>(self, mut f: impl FnMut((&K, V)) -> T) -> BoundedBTreeMap<K, T, S> {
    self.0
        .into_iter()
        .map(|(k, v)| {
            let t = f((&k, v));
            (k, t)
        })
        .try_collect()
        // SAFETY: No entries were added or removed.
        .unwrap()
}

pub fn try_map<T, E>(
    self,
    mut f: impl FnMut((&K, V)) -> Result<T, E>,
) -> Result<BoundedBTreeMap<K, T, S>, E> {
    Ok(self
        .0
        .into_iter()
        .map(|(k, v)| (f((&k, v)).map(|t| (k, t))))
        .collect::<Result<BTreeMap<_, _>, _>>()?
        .try_into()
        // SAFETY: No entries were added or removed.
        .unwrap())
}
```

**Comment by shawntabrizi** [comment]
Sounds reasonable. Would you like to work on this?

**Comment by benluelo** [comment]
Absolutely! I will open a PR shortly :+1:

**Comment by benluelo** [comment]
#11869 implemented similar behaviour to this (adding an `iter_mut()` method to the Bounded* collections), but as per my comment (https://github.com/paritytech/substrate/pull/11869#issuecomment-1219815985) I still think that this would be useful functionality to have. I often create one bounded collection from another with the same length, which results in unsightly `.expect(...)`s throughout the code.

**Comment by ggwpez** [comment]
> One issue with iter_mut is that it doesn't allow you to transform the item's type in the collection […]

Yea… I guess that is a valid concern. Do you want to implement `map/try_map` as well?

**Comment by benluelo** [comment]
Yeah I can definitely do that! (#11869 actually started out as that :sweat_smile:) I'll open a new PR for it :+1:

**Comment by ggwpez** [comment]
> I often create one bounded collection from another with the same length, which results in unsightly `.expect(...)`s throughout the code.

FYI there is [`defensive_truncate_from`](https://github.com/paritytech/substrate/pull/12515) which can at-least get rid of these expects.
