### ISSUE TITLE
Build issue in MacOS while installing substrate-node-project

### ISSUE THREAD

**Issue by muddlebee** [paritytech/substrate#11860]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

https://github.com/substrate-developer-hub/substrate-front-end-template
in sync with https://github.com/paritytech/substrate/commits/master/bin/node-template

cargo build --release
error trace :

  Building [=======================> ] 954/964: librocksdb-sys(build)                                                                                                         

The following warnings were emitted during compilation:

warning: snappy/snappy.cc:1033:36: error: invalid output constraint '=@ccz' in asm
warning:       : [tag_type] "+r"(tag_type), "=@ccz"(is_literal));
warning:                                    ^
warning: 1 error generated.

error: failed to run custom build command for `librocksdb-sys v0.6.1+6.28.2`

Caused by:

  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,llvm14-builtins-abi,sse,sse2,sse3,ssse3")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "snappy/" "-I" "." "-Wall" "-std=c++11" "-DNDEBUG=1" "-o" "/Users/anweshnayak/Documents/projects/polkadot/parity/substrate-dev-hub/substrate-node-template/target/release/build/librocksdb-sys-0e318981b983f350/out/snappy/snappy-sinksource.o" "-c" "snappy/snappy-sinksource.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "snappy/" "-I" "." "-Wall" "-std=c++11" "-DNDEBUG=1" "-o" "/Users/anweshnayak/Documents/projects/polkadot/parity/substrate-dev-hub/substrate-node-template/target/release/build/librocksdb-sys-0e318981b983f350/out/snappy/snappy.o" "-c" "snappy/snappy.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "snappy/" "-I" "." "-Wall" "-std=c++11" "-DNDEBUG=1" "-o" "/Users/anweshnayak/Documents/projects/polkadot/parity/substrate-dev-hub/substrate-node-template/target/release/build/librocksdb-sys-0e318981b983f350/out/snappy/snappy-c.o" "-c" "snappy/snappy-c.cc"
  exit status: 0
  exit status: 0
  cargo:warning=snappy/snappy.cc:1033:36: error: invalid output constraint '=@ccz' in asm
  cargo:warning=      : [tag_type] "+r"(tag_type), "=@ccz"(is_literal));
  cargo:warning=                                   ^
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr

  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "snappy/" "-I" "." "-Wall" "-std=c++11" "-DNDEBUG=1" "-o" "/Users/anweshnayak/Documents/projects/polkadot/parity/substrate-dev-hub/substrate-node-template/target/release/build/librocksdb-sys-0e318981b983f350/out/snappy/snappy.o" "-c" "snappy/snappy.cc" with args "c++" did not execute successfully (status code exit status: 1).

### Steps to reproduce

found some discussion and fix for the issue here https://groups.google.com/g/snappy-compression/c/-AVUHVOf_OQ

**Comment by ggwpez** [comment]
This looks like a build error from rocksdb, nothing that we can change (besides updating) in Substrate.  
You could try to update your compiler, like its advised in your provided link or install GCC.

**Comment by timmyjose** [comment]
I ran into the same issue, and pointing `Cargo` to use a newer C++ toolchain worked just fine. In my case, I had LLVM 12 installed, and the command used to build was:

    CXX=/usr/local/opt/llvm@12/bin/clang cargo build --release

**Comment by ggwpez** [comment]
Going to close since there is no actionable from our side.
