### ISSUE TITLE
Prometheus metrics for successful/erroneous RPC calls are misplaced

### ISSUE THREAD

**Issue by bakhtin** [paritytech/substrate#11887]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Substrate exposes a metric called `substrate_rpc_calls_finished`. Among others it returns a flag whether a request was successful or not in `is_error` label.
![image](https://user-images.githubusercontent.com/8650477/180249777-f7309b18-df09-4b49-bab8-aa376d16c31e.png)

But it seems that values for `true` and `false` are misplaced and should be swapped out. The error seemingly comes from https://github.com/paritytech/substrate/blob/b28bf15e5160f33e257e2cc6066bdd6c55a3eb42/client/rpc-servers/src/middleware.rs#L179

### Steps to reproduce

Run the node and query `substrate_rpc_calls_finished` metric. While most of the requests are successful they are shown as errors in the output

**Comment by bkchr** [comment]
What you mean by they are shown as error in the output? In what way?

**Comment by bakhtin** [comment]
`is_error=false` selector actually shows requests that completed with an error rather that showing successful requests.

**Comment by niklasad1** [comment]
Yes, you are correct.

The actual label is `"is_error"` so if `success == true` it should be `is_error="false"` and not `is_error="true"`

**Comment by niklasad1** [comment]
Closed by #11951
