### ISSUE TITLE
make `MAX_VOTERS` and `MAX_CANDIDATES` in `elections-phragmen` configurable

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11902]
Make these two magic constants added in https://github.com/paritytech/substrate/pull/11790 be `type X: Get<_>`, set them to the same value as now in the polkadot companion. Document that parachain teams should chose these values carefully, ensuring that both the weight and PoV is within reason.

**Comment by kianenigma** [comment]
@Szegoo interested?

**Comment by Szegoo** [comment]
> @Szegoo interested? 

Yes.
