### ISSUE TITLE
Rename `--pruning` and `--keep-blocks` to be more similar to one another. 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#11907]
I actually very recently learned that we have a flag called `--keep-blocks`. We where also teaching students about Polkadot recently in Polkadot academy and they are somewhat confused about the concept of "block state" and "blocks" themselves, and how keeping one is optional, and the name of these two flags being totally unrelated does not help.

I think these two flags are very similar, and should be named accordingly: 

- `--keep-blocks` and `--keep-state`
- `--state-pruning` and `--blocks-pruning`

**Comment by bkchr** [comment]
`--keep-blocks` is about pruning block bodies. This is currently disabled by default, aka we keep all block bodies. So, you rename would be wrong. `--state-pruning` is actually about the state and how much state we keep before we prune it.

**Comment by arkpar** [comment]
`--keep-blocks` only accepts a number. `--pruning` also accepts "archive" and potentially other values for pruning modes.

**Comment by kianenigma** [comment]
the fact that pruning has different possible values doesn't justify its confusing name to. I think at the minimum, we should rename `--pruning` to `--state-pruning`, with the exact same semantics, to distinguish it with keeping block bodies.

**Comment by bkchr** [comment]
Okay fuck, sorry. I did read your first comment wrongly.

Reading it again, I like:
```
--state-pruning and --blocks-pruning
```

**Comment by wirednkod** [comment]
@kianenigma I will take this issue if you are ok with that.
