### ISSUE TITLE
[Questions] How to extract transactions and events from a specific block?

### ISSUE THREAD

**Issue by ianhe8x** [paritytech/substrate#1192]
Hi, It seems polkadot.js recommends people to use their ws-provider with substrate. But websocket is not that trustworthy in my opinion. If I want to implement a http provider simulate the subscriptions as ws provider does, I will need a way to  extract transactions and events from a block, which I haven't found in substrate yet. 
Can anyone enlighten me the approach? or if there's no such way at this moment, are there any plans?

**Comment by jacogr** [comment]
Sure. It is quite possible to use HTTP to poll - The events are available on the `system` module system under the `events` key.  (Basically using either provider in that library would expose it under `api.query.system.events`). 

Under the hood it uses the `state_storage` RPC subscription (only available over WS) to stream results, over HTTP you can get it via the `state_getStorage` RPC call. (Which takes an optional block hash param)

For transactions if you want to poll, you cannot rely on the `chain_newHead` subscription, so you can use `chain_getHead` to check for block changes in a polling fashion.
