### ISSUE TITLE
Alliance: Replace `init_members` with `force_set_members`

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#11928]
The Alliance pallet's `init_members` function is a root call with a check that only allows it to be called if there are no members yet. This makes the logic simpler, but Root should always have the ability to change the membership of the Alliance.

The function signature should be the same, but `force_set_members` would remove all current members and set each role according to the supplied parameters. If the call contains no members at all, it should clean up all storage items in the pallet, effectively disbanding the Alliance and removing their `Rule` and `UnscrupulousList`.

**Comment by joepetrowski** [comment]
Yeah, that is what I had in mind.

> can be simplified if we don't allow empty founders && fellows

I agree, and we could add another Root call, `force_disband_alliance` that takes no args and just clears everything, slashing any remaining members. (Or it could take one arg, `slash: bool`.) This would be the ultimate expression of the network's dissatisfaction with the Alliance.

So then we could require that `force_set_members` actually includes some founders or fellows, and it just replaces the current membership with the new set. Then yeah, it'd be up to the new Alliance to clean up/modify any old storage items that the old one left behind.

**Comment by muharem** [comment]
Then we need one more method to remove proposal, currently there is only close (which executes it if its voted).
