### ISSUE TITLE
add BEEFY support to `chain-spec-builder`

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#11937]
`chain-spec-builder` should [generate authority keys and store](https://github.com/paritytech/substrate/blob/969a344684d9b79b6bb6bab591ac73df4017fea9/bin/utils/chain-spec-builder/src/main.rs#L165) for BEEFY as well

**Comment by bkchr** [comment]
The chain-spec-builder is not really used anywhere, it is mainly some unmaintained piece of software. TLDR: We don't need this.

**Comment by acatangiu** [comment]
Closing as not needed.
