### ISSUE TITLE
Explore the usage of Episub for distributing PoV chunks

### ISSUE THREAD

**Issue by rymnc** [paritytech/substrate#11944]
The [Episub](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/episub.md#introduction) gossip protocol is a successor to the FloodSub protocol, which allows two types of peers to exist, `eager`, and `lazy` peers. The lazy peers are just used to transmit metadata about the message, whereas eager peers receive the whole message. 

In the context of [distributing PoV's](https://w3f.github.io/parachain-implementers-guide/types/network.html#pov-distribution-v1), it is possible for the backing set for the given parachain to be eager peers, and the other validators could be lazy peers, to facilitate gossiping. As an added functionality, the lazy peers who wish to validate the block can request the chunks as well.

There is an [existing implementation](https://github.com/solcial/libp2p-episub) of the Episub protocol, in Rust. 

As per my understanding of this use-case, using Episub for PoV distribution, would result in -
1. Reduced network overhead for validators that are not part of the backing set
2. Reduced latency in transmitting data to the backing set

**Comment by bkchr** [comment]
@rymnc could you please add your comment to the relevant issue 😁

https://github.com/paritytech/polkadot/issues/3307

Thank you :)

**Comment by burdges** [comment]
I'm think pub-sub would never be useful for parachains:  https://github.com/paritytech/polkadot/issues/3307#issuecomment-1200516641

We de facto have the eager vs lazy abstraction discussed here now, but it's proved way too slow.  We're therefore replacing it with something more direct: https://github.com/paritytech/polkadot/issues/5055#issuecomment-1180914398 

In other words, if you think you want eager and lazy then maybe what you really want is direct connections for participating and not participating, but applied to that small part.
