### ISSUE TITLE
Is it possible to create a batch transaction or transaction with multiple calls?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1196]
It is possible to create and send a batch transaction that includes multiple sub transactions and the batch transaction only successes if all its sub transactions successes? i.e. Multiple transactions performed atomically.

Use cases I would like to see if can be supported:
- User creates a signed transaction, send it to service provider, service provider broadcast transaction and somehow pay the transaction fee. So that user do not need to pay for transaction fee. Another way to see this is a batch transaction contains two sub transaction 1) service provider transfer transaction fee to user, 2) user perform the tx and pay the fee using the value that just received from service provider
- User purchase utility token with main currency, and consume the utility token immediately with a transaction. If the consuming transaction failed, the token should be refund and only pay for gas fee.

I feel the answer is no at moment, if that's the case then what are the works required to make it possible? I am keen to work on this if it is achievable (with in reasonable amount of work).

I have been looking the code and I think one way to achieve this feature is to implement a new batch transaction module, that takes signed transactions as input, and process them similar to the `executive` module. And it needs to somehow monitor to the execution status and bail out if any failed.

Am I on the right track?

**Comment by gavofyork** [comment]
Current `Extrinsic` datatype and `srml-executive` module do not support this. But yes, it would be fairly easy to add. There are already two `Extrinsic` types and it should be fairly easy to see how to add a third.
