### ISSUE TITLE
ChainExtensions' caller should be contract AccountId

### ISSUE THREAD

**Issue by shunsukew** [paritytech/substrate#11987]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Using pallet contracts polkadot-v0.9.26

According to the [Substrate Stack Exchange](https://substrate.stackexchange.com/questions/1681/how-to-access-environmental-information-about-a-contract-from-within-a-chain-ext), ChainExtensions caller `env.ext().caller()` is expected to be calling smart contract AccountId instead of original contract caller AccountId.

However, In [our implementation](https://github.com/AstarNetwork/swanky-node/blob/dadecd4e9dd05cffcb17ac3da6363f89a96df8ab/chainextensions/rmrk/impl/src/lib.rs#L287), it will receive the original caller of the smart contract.
(For example, If you call RMRK pallet `CreateCollection` with alice account via ink! smart contract [message](https://github.com/AstarNetwork/swanky-node/blob/dadecd4e9dd05cffcb17ac3da6363f89a96df8ab/contracts/rmrk_example/lib.rs#L412), `env.ext().caller()` will get Alice account.)

```
let mut env = env.buf_in_buf_out();
let (metadata, max, symbol): (Vec<u8>, Option<u32>, Vec<u8>) =
env.read_as_unbounded(env.in_len())?;

let caller = env.ext().caller().clone();
sp_std::if_std! {println!(
	"[RmrkExtension] create_collection metadata{:?}, symbol{:?}, caller{:?}, weight {:?}",
	metadata, symbol, caller, weight
);}
```
```
[RmrkExtension] create_collection metadata[0], symbol[17], callerd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), weight 100000000000
```
`5GrwvaEF...` is the AccountId of Alice. 

_No response_

**Comment by athei** [comment]
`caller()` means the caller of your smart contract (which is Alice if you call the message directly with that account). **Not** the caller of the chain extension. You are looking for your own accountid: `env.ext().address()`.
