### ISSUE TITLE
Rename `spec_name` to `runtime_name` or `name`

### ISSUE THREAD

**Issue by memorycancel** [paritytech/substrate#11999]
https://github.com/paritytech/substrate/blob/fece0657f20e15df94be5833b164dfacd44823eb/primitives/version/proc-macro/src/decl_runtime_version.rs#L71-L74

The point of this is more straight-forward, the `spec_name` here should not be confused with `spec_version`, this make people think it's specification name as opposed to runtime name. As same as the definition in document make people confusing.

![image](https://user-images.githubusercontent.com/10057052/183825680-af5c7a15-1410-4ab4-8d8f-4b2d5aa13c28.png)

closes https://github.com/substrate-developer-hub/substrate-docs/issues/1388

**Comment by xlc** [comment]
It is also specification name? I mean what exactly is the difference between specification name and runtime name? The spec_version is the specification version and you are not suggesting to rename it as well.

**Comment by memorycancel** [comment]
> It is also specification name? I mean what exactly is the difference between specification name and runtime name? 

Yes, I have the same confusion as you, about the definition of the parameter literally, I am not sure what name to rename.

So, Could we handle this as a expressive issue. Like, we can change the definition
```text
The identifier for the different Substrate runtimes
```
to
```text
The identifier for the different specification
```
From my view, the runtime is just a part of specification, right?

**Comment by bkchr** [comment]
I would then vote for:
```
The identifier of the specification implemented by the runtime.
```

**Comment by memorycancel** [comment]
@bkchr Thanks for comment, actually I am not confused with the description of the parameter but the name `spec_name` according to `spec_version`, anyway this maybe a little nitpicky, just a parameter name.

**Comment by bkchr** [comment]
Sorry, but I don't understand what you mean ?

**Comment by memorycancel** [comment]
I think this is Naming Habits issue, closing.

**Comment by Dairston** [comment]
IMPORTANT:

Metamask wallet 12 word seed phrase password: Asd

cross about grape horror village dad drill short husband soccer author merry

0xc28668af51eB08b8b2b45c438238652a11e65103

start your own distr88ibuted dao

110393Dm1V PASSCODE MAYBE* 4 ADDRESS BEG. W.

0X27 For Meta Proposal

+

+ DAO CULTDAO.IO

twitter backup:
6p2zh6ae9n9n

view-source:https://www.luden.com/

0xc28668af51eB08b8b2b45c438238652a11e65103

Very Respectfully,

D.A. Elliott
AMEIR ENTERPRISES, LLC
Owner/Founder
Cell: (304)-460-5296

Sent with [Proton Mail](https://proton.me/) secure email.
