### ISSUE TITLE
nomination-pools: allow pool-ids to be reused

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12001]
Currently, pool ids only ever increase. While generally we suggest using a `MaxPools` limits, this allows one to spam the pool ids and consume a lot of them by creating a pool and immediately destroying it. 

This is not a cheap or fast process, so it is not a huge risk either. Nonetheless, it would be nice to have a simple id-reuse system.

A simple way to do it is that `create` can have an `Option<PoolId>`. If `None`, the sender wants to use `LastPoolId + 1` . If `Some(claim)`, the sender is claiming that they know `claim` is free. `claim` must always be less then `LastPoolId`.

**Comment by Doordashcon** [comment]
Hello @kianenigma would like to get a clear understanding of what this will accomplish.

**Comment by kianenigma** [comment]
I think my description is pretty exact, don't have much to add to it after reading it again. 

What I would consider is just keeping this fully backwards compatible and creating a new transaction `create_with_pool_id` instead of breaking the old one.

**Comment by Doordashcon** [comment]
can I be assigned to this?

**Comment by ggwpez** [comment]
We would then need an `ClaimedId` event or something, otherwise UI could get confused to why a PoolId is now pointing to a different pool.

**Comment by Ank4n** [comment]
Thinking out loud, I believe it wouldn't be too hard to to keep track of all the pools that are destroyed and ready to be claimed. In that case we would not really need another fn `create_with_pool_id`. The existing fn `create` would first try to get the `last_reclaimable_pool_id` and if not available, increment `pool_id`.

**Comment by kianenigma** [comment]
تست
