### ISSUE TITLE
Remove session key of reaped accounts

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate#1201]
Currently [`set_key`](https://github.com/paritytech/substrate/blob/master/srml/session/src/lib.rs#L96) is a **public call** that checks that the origin is a signed account using `ensure_signed` https://github.com/paritytech/substrate/blob/master/srml/session/src/lib.rs#L97, and then stores in `NextKeyFor` a mapping of their account id to the session key that they provided, which will be used as their validator session key in the next session.

But since we're using `ensure_signed`, the account id of the origin that we're storing in `NextKeyFor` may not necessarily be associated with a block author or a validator.

Shouldn't `set_key` instead be an **inherent call** that checks that the origin is a block author or a validator using `ensure_inherent` instead?

**Comment by gavofyork** [comment]
You may want to set your key prior to becoming a validator. It should, however, be removed once the account has been deleted.

**Comment by gavofyork** [comment]
Session module does indeed remove the key once the account balance is zero.
