### ISSUE TITLE
Vision: Review `can_*` extrinsics/methods

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#12012]
We should review all `can_*` extrinsics that got created under the old paradigm since we now have storage layers per default.  
A lot of code can be simplified and maybe some extrinsics can be removed or deprecated. This should also reduce the weights.  

@KiChjang could you please add your related issues?

**Comment by KiChjang** [comment]
This would imply that all of the `can_*` trait methods under the `frame_support::{fungible, fungibles}` path need to be updated as well. Not sure if this also includes the trait methods under `Currency` and `ReservableCurrency`, since the aim is to migrate away from them.
