### ISSUE TITLE
Warn validators with slow hardware

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#12017]
Upon starting a node we currently print some brief hardware metrics.  
This could be extended to include a warning in case the node has bad performance and was started with `--validator`.  

The logic for comparing results and having a baseline is currently in `utils/frame/benchmarking-cli`, some of this would probably move to `sc-sysinfo`. `sc-sysinfo` would profit from this since it can use `Throughput` types (and other) instead of just `u64` in some places.

**Comment by dvdplm** [comment]
@ordian Maybe this can be helpful in view of the disputes slashing roll-out as well?

**Comment by bkchr** [comment]
We already got the host performance check in Polkadot for this: https://github.com/paritytech/polkadot/blob/master/cli/src/host_perf_check.rs

**Comment by ggwpez** [comment]
> We already got the host performance check in Polkadot for this …

Do you mean that we should not add it to Polkadot then, but still to Substrate? Or not at all?  
I keep seeing people in the Kusama 1KV channel actually using the `benchmark machine` command, so they seem to like it.

**Comment by bkchr** [comment]
We can add it to Substrate, if it is done in a generic way. Aka chain implementors like Polkadot provide their own expected numbers that are treated as "good".

My comment was more an answer to @dvdplm. 

But if we have your stuff, we can deprecate the host perf check.

**Comment by Szegoo** [comment]
@ggwpez I am gonna pick this up :)

**Comment by Szegoo** [comment]
@ggwpez You mentioned in https://github.com/paritytech/substrate/pull/12368 that we could move `Metric` to `sc-sysinfo` also, I will open a small PR for that if you didn't change your mind.

**Comment by ggwpez** [comment]
Please try to do it in one. I dont want to increase the review overhead for such a rather simple issue @Szegoo

**Comment by Szegoo** [comment]
@ggwpez Ok, I will close this issue and move Metric in the same PR.

**Comment by Szegoo** [comment]
@ggwpez Should we deprecate the host perf check in polkadot then and have it in substrate implemented in a generic way?

**Comment by ggwpez** [comment]
I have to look into the PVF check command again and chat with who created it. For now it is still fine to have both IMO.
