### ISSUE TITLE
sp-keystore does not compile

### ISSUE THREAD

**Issue by MrishoLukamba** [paritytech/substrate#12019]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

in doc.rs sp-keystore points to version 0.10.0-dev while inside substrate repo is 0.12.0, When attempting to include it does not compile

### Steps to reproduce

Including it in cargo.toml,
cargo check -- produces error cannot compile sp-keystore and indicating some crates from sp-core inside keystore/testing file cannot be imported

**Comment by MrishoLukamba** [comment]
@bkchr @shawntabrizi

**Comment by bkchr** [comment]
How do you include the crate?

**Comment by MrishoLukamba** [comment]
Inside cargo.toml. The name. The version of it git and the branch
