### ISSUE TITLE
SRML Example: Missing "internal calls" group

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate#1202]
In https://github.com/paritytech/substrate/blob/master/srml/example/src/lib.rs#L74 it mentions that there are three groups of calls: **public calls, root calls, and inherent calls**

However in https://github.com/paritytech/substrate/blob/master/srml/session/src/lib.rs#L164, the `apply_force_new_session` function appears to be a fourth group of call: **internal calls (available to other runtime modules, and has no origin)**. Or would it just be categorised as a **root call**?

**Comment by bkchr** [comment]
That is no `Call`, it is just a normal function. You will not be able to call this from the outside.
