### ISSUE TITLE
Use `parameter_types` instead of `thread_local` for test-setup 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12020]
```
parameter_types! {
    pub static Members: BoundedVec<u64,ConstU32<10_u32>> = bounded_vec![0,10]
}
```

and then you get `Members::get()` and `Members::set()` with the same functionality.

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/pull/11996#discussion_r944701672_

---

As per explained in the above PR.

**Comment by ggwpez** [comment]
That should also fix this https://github.com/paritytech/substrate/issues/10479, if used everywhere.

**Comment by bkchr** [comment]
You can not use `parameter_types!` in all tests. The problem is that some tests require that you change the values between different tests.

**Comment by kianenigma** [comment]
I don't see any function difference between the two. It is merely for the nicer syntax. Can you provide an example?

**Comment by bkchr** [comment]
Okay, I mixed stuff up. There is some usage of `thread_local` in the frame tests, but none of them is used directly as alternative for parameter_types. More like some way to introspect operations.

**Comment by tifecool** [comment]
Would like to attempt this.
