### ISSUE TITLE
`system_syncState` RPC returns highestBlock null

### ISSUE THREAD

**Issue by shunsukew** [paritytech/substrate#12038]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

`system_syncState` RPC returns null for highestBlock.
Confirmed with several chains using Substrate.

<img width="1494" alt="Screen Shot 2022-08-16 at 13 20 53" src="https://user-images.githubusercontent.com/28953860/184797428-076ec13b-0820-4756-bcff-5a0739f8d6ee.png">

(Posted here because I don't know whether it is expected or a bug, and no description I could find about this field in internet)

### Steps to reproduce

Option 1
- Go to Substrate portal https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/rpc
- Call system syncState()

Option 2
- launch node by oneselve
- expose rpc with `--rpc-port` flag
- `curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "system_syncState", "params":[]}' http://localhost:9933`

**Comment by bkchr** [comment]
This was fixed by: https://github.com/paritytech/substrate/pull/11979
