### ISSUE TITLE
Bound `RewardPoints`in pallet-staking

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12039]
... and add a log every time a validators is rewarded. 

This is a very low hanging fruit in the direction of bounding the staking pallet i.e. https://github.com/paritytech/substrate/issues/8629

**Comment by Doordashcon** [comment]
@kianenigma attempting this as well

**Comment by kianenigma** [comment]
Replaced with https://github.com/paritytech/substrate/issues/12039
