### ISSUE TITLE
nomination-pools: clear pool metadata after a pool is deleted.

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12077]
In `fn dissolve_pool`, the corresponding pool metadata has to be removed as well. 

Currently, we forget to do this. 

Also requires a small migration: iterate over all metadatas, if one does not have a corresponding bonded_pool, delete it. The migration could also be executed manually with providing the right `system::kill_storage`.

**Comment by tifecool** [comment]
Would like to attempt this

**Comment by tifecool** [comment]
What do you mean by migration?
