### ISSUE TITLE
benchmarking: Handle pallet instances

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#12080]
Currently the benchmarking does not like instances. This definition in the runtime:  
```rust
[pallet_referenda, Referenda]
[pallet_referenda, FellowshipReferenda]
```
results in the pallet being listed **twice** when listed with `--list`.  

The cleanest solution IMO would be to additionally add an `--instance` arg. Such that this could be specified with:  
`--pallet pallet-referenda --instance FellowshipReferenda …`.  

This could possibly break existing tooling like the bench bot, since it now also needs to learn about instances.  
A hackier way could be to append the instance name to the pallet name, if there are two pallets with the same name.  
Or create a short-cut syntax like `pallet-referenda<FellowshipReferenda>` to specify the instance.  

Better ideas? @shawntabrizi

**Comment by bkchr** [comment]
Why is `--list` returning the pallet name and not the name of the pallet instance in construct runtime? You are already passing both there any way, why not just choose the pallet instance name?

**Comment by ggwpez** [comment]
> Why is `--list` returning the pallet name and not the name of the pallet instance in construct runtime? You are already passing both there any way, why not just choose the pallet instance name?

Not quite sure, its legacy code after all :laughing:  
I think it makes for easier scripting if the printed name correlates to the folder name, but that is a *very* weak argument.  
Ideally the benchmarking CLI would be able to create multiple weight files itself so that we can get rid of the ugly shell scripts.

**Comment by ggwpez** [comment]
It is now benchmarking all instances.
