### ISSUE TITLE
BEEFY - justifications sync protocol

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#12093]
This issue replaces https://github.com/paritytech/grandpa-bridge-gadget/issues/20 and tracks implementing `#3` below:

A node running BEEFY worker/gadget, generates/imports and stores BEEFY justifications as follows:
1. when synced, it participates in voting gossip and builds BEEFY justifications itself from gossiped votes,
2. when behind, it imports BEEFY justifications alongside imported blocks (as part of block import - added in #11821 and #11959),
3. runs dedicated _BEEFY justifications sync protocol_ as a libp2p `RequestResponse` protocol - where node can request BEEFY justifications for certain blocks from connected peers, and also answer any requests it gets.

`#3` above is required when syncing from a peer that might be missing some/all BEEFY justifications.

**Comment by acatangiu** [comment]
I'm seeing all [current RequestResponse protocols](https://github.com/paritytech/substrate/blob/master/client/service/src/builder.rs#L861-L864) in Substrate network are [built around sync](https://github.com/paritytech/substrate/blob/master/client/network/src/protocol.rs#L1516-L1538) and are also kind of hardcoded, not really "pluggable".

Should we also "hardcode" BEEFY support (at most wrap it around an Option<>, just like warp sync)?

Should we add it to [(Protocol as NetworkBehavior)::poll()](https://github.com/paritytech/substrate/blob/7266eb7d794d74a7860fe193d7a3074200765ea1/client/network/src/protocol.rs#L1383) just like the others, maybe even through the [ChainSync](https://github.com/paritytech/substrate/blob/7266eb7d794d74a7860fe193d7a3074200765ea1/client/network/src/protocol.rs#L174) trait member?

Since this would be a _separate_ sync, we'll end up with mixed state (some block-sync-specific and some BEEFY-sync-specific) in [struct ChainSync](https://github.com/paritytech/substrate/blob/master/client/network/sync/src/lib.rs#L211), [struct PeerSync](https://github.com/paritytech/substrate/blob/master/client/network/sync/src/lib.rs#L259) and [struct PeerSyncState](https://github.com/paritytech/substrate/blob/7266eb7d794d74a7860fe193d7a3074200765ea1/client/network/sync/src/lib.rs#L301). Any concerns here?

In case we get justifs from other sources is there any way to cancel any pending request?

What kind of peer selection strategy should we use?

@andresilva @bkchr @tomaka ^

**Comment by bkchr** [comment]
> I'm seeing all [current RequestResponse protocols](https://github.com/paritytech/substrate/blob/master/client/service/src/builder.rs#L861-L864) in Substrate network are [built around sync](https://github.com/paritytech/substrate/blob/master/client/network/src/protocol.rs#L1516-L1538) and are also kind of hardcoded, not really "pluggable".

If you take a look at Polkadot you see pluggable protocols and this is the way forward. We will not accept anymore hardcoded protocols if there is not any special reason for this.

> Should we also "hardcode" BEEFY support (at most wrap it around an Option<>, just like warp sync)?

No please don't do this. It should be its own protocol, living in its own crate.

Also just no to the other stuff above :see_no_evil: 

> In case we get justifs from other sources is there any way to cancel any pending request?

I don't think there is a way currently. What would be other sources to receive a justification?

> What kind of peer selection strategy should we use?

I think for now we should be able to just follow the `Event::SyncConnected`/`Event::SyncDisconnected`: https://github.com/paritytech/substrate/blob/40703f41167c718e13b491228efeafb4a6194448/client/network/common/src/protocol/event.rs#L50-L60

You can get these by getting an `event_stream`: https://github.com/paritytech/substrate/blob/40703f41167c718e13b491228efeafb4a6194448/client/network/src/service.rs#L1042

One problem is probably to know what blocks/justification a peer has. Maybe we should have our completely own protocol on top of `sc-network` that at least gossips to all peers when it has a certain justification imported?

**Comment by acatangiu** [comment]
> I don't think there is a way currently. What would be other sources to receive a justification?

- Block import with attached justifications
- Gossiped votes -> enough of them trigger a locally generated justification

I guess it's fine even without canceling a pending request, we'll just drop the obsolete response.

> One problem is probably to know what blocks/justification a peer has. Maybe we should have our completely own protocol on top of `sc-network` that at least gossips to all peers when it has a certain justification imported?

We could use the votes gossiping to determine which peers have what (mandatory) justifications: any peer voting on block `N` will have all mandatory BEEFY justifications < N.
I'll also think about justification gossiping, see if we need that for any corner case.

> If you take a look at Polkadot you see pluggable protocols and this is the way forward. We will not accept anymore hardcoded protocols if there is not any special reason for this.

Ok, got it. Will develop this as its own protocol, living in its own crate, "pluggable" into `sc-network`.

**Comment by bkchr** [comment]
> We could use the votes gossiping to determine which peers have what (mandatory) justifications: any peer voting on block `N` will have all mandatory BEEFY justifications < N.
> I'll also think about justification gossiping, see if we need that for any corner case.

So all validators will have the justifications and only normal nodes will need to request them from validators? While doing major sync we send the BEEFY justification directly alongside the block? (Just trying to understand when we will need to request a justification)

**Comment by acatangiu** [comment]
> While doing major sync we send the BEEFY justification directly alongside the block?

yup, and the worker/voter gets them through `BlockImport/JustificationImport`.

> Just trying to understand when we will need to request a justification

A validator was offline for a while and when coming back up syncs blocks from a node that also doesn't have (latest) BEEFY justifications => no justifs through block import, no justifs through voting because those rounds ended a while ago.
Worker/voter can then fallback to on-demand request missing mandatory justifications from peers.

**Comment by bkchr** [comment]
> A validator was offline for a while and when coming back up syncs blocks

Okay, so the validator comes back online. Syncs blocks without justfication. While doing this its already running the BEEFY protocol and listens for votes. Any node that votes on stuff with a higher block number than we are missing the justification for should have all justifications of all blocks before including the one we are searching for?

**Comment by acatangiu** [comment]
> Any node that votes on stuff with a higher block number than we are missing the justification for should have all justifications of all blocks before including the one we are searching for?

Yes, that’s right, any node voting for higher blocks _should_ (if behaving correctly) have all *mandatory* block justifications leading to block number they’re currently voting on. And we’re only on-demand syncing mandatory ones so this approach should work.
