### ISSUE TITLE
Use custom type for ProtocolName

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#12115]
Currently the protocol name in the networking is passed as `Cow<'static, str>` which made sense when it was introduced. Now with the switch to using the genesis hash as part of the protocol name, we need to create a `String` for this. This means that every time we want to send a notification or similar we will need to clone this `String`. Remember before it was most of the time a `&'static str` that could be cloned for free. So, I would change `ProtocolName` to an enum:

```
enum ProtocolName {
    Static(&'static str),
    // Allocated is a really bad name and just being used to convey the idea here.
    Allocated(Arc<str>),
}

impl From<&'static str> for ProtocolName {}
impl From<String> for ProtocolName {}
impl From<Arc<str>> for ProtocolName {}
impl Deref<Target = str> for ProtocolName {}
```

**Comment by dmitry-markin** [comment]
`Allocated` -> `OnHeap`?

**Comment by bkchr** [comment]
Fine by me, still doesn't sound "perfect" :D
