### ISSUE TITLE
uniques / nfts: paged rpc call returning ones for sale

### ISSUE THREAD

**Issue by gilescope** [paritytech/substrate#12113]
We can now buy / sell uniques on statemine. But it's not that easy to tell what is for sale as at the moment you have to query each unique class at a time to see if any NFTs are for sale in that class:

```js
const [classes] = await Promise.all([
  api.query.uniques.class.keys()
]);

const result = classes.map(({ args: [id] }) => id).sort((a, b) => a.cmp(b));
console.log(result)
for (i in result) {
    const [itemPriceOf] = await Promise.all([
       api.query.uniques.itemPriceOf(i, null)
    ]);
    console.log('Item for sale: ' + itemPriceOf);
}
```

It would be great if the first argument of itemPriceOf could take null too and the results were paged so we did not try and bring everything back.

**Comment by ruseinov** [comment]
It might also be interesting to have some sort if named search if at all possible. I need to familiarize myself more with the uniques pallet storage

**Comment by bkchr** [comment]
This is not the polkadot-js issue tracker. Substrate supports paged storage reads.

**Comment by gilescope** [comment]
Good point. This is built in functionality.
