### ISSUE TITLE
WeightInfo for traits `MembershipChanged` and `MembershipChanged`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#12120]
Some functions of these traits are used in `Alliance::force_set_members` but do not expose weight info.  
Adding some additional WeightInfo would allow to correctly express the weight of `force_set_members`.

**Comment by a-moreira** [comment]
hey @ggwpez, can I work on this task?
if so, can you give more information? thanks!

**Comment by ggwpez** [comment]
I originally thought that it should be done like that, but we just re-benchmark when the hooks change.  
So actually not needed.
