### ISSUE TITLE
Rounding behaviour in `implement_fixed!`

### ISSUE THREAD

**Issue by mustermeiszer** [paritytech/substrate#12127]
Just ran into some issues with the rounding behavior of the primitive substrates fixed points and was wondering if it is intended that there exist different rounding preferences depending on which function I use.

### Examples:
* rounding on `fn checked_div_int`, `fn checked_dig`, `fn checked_mul_int`, `fn checked_mul`:  `Rounding::from_signed(SignedRounding::Minor, negative)` -> `Rounding::Down`
* `const fn into_perbill`, `const fn from_rational`, `const fn const_checked_mul`, `const fn const_checked_div` : `Rounding::NearestPrefDown`

It seems odd to me that the `const` functions round differently compared to the non-`const` functions. Is there a reason for this behavior?

**Comment by bkchr** [comment]
CC @kianenigma

**Comment by kianenigma** [comment]
I don't think this is by intention. It was seemingly the more convenient option at the time. If you have specific recommendation, we look into it.

**Comment by mustermeiszer** [comment]
@kianenigma I have no preference, just the same everwhere would be great. I would tend to `Rounding::from_signed(SignedRounding::NearestPrefLow, negative)`, so rounding always closest but choose to round to zero in case of equidistant. 

But this is a subjective choice.

**Comment by kianenigma** [comment]
I would be happy to see a PR that makes them consistent, if not, let's close the issue to keep the backlog small :)

**Comment by mustermeiszer** [comment]
We overwrote the impl on our side. Just wanted to raise this, as I thought primitives should be consistent. Will close this then.
