### ISSUE TITLE
Trie LRU cache test fails

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#12134]
`cache_lru_works` has a 2% chance of failing when run in a `for` loop. It fails at the last `assert_ne` where it assumes to have changed the LRU keys:
https://github.com/paritytech/substrate/blob/915f3c10f22777a1dc49c1ed894525280ce12244/primitives/trie/src/cache/mod.rs#L640

```pre
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `[0x3ffb5a0dbe680941d33afbd7e73c782e3591f21485fcaee31581fbc68f26a725, 0xf3cbdac4e7db24b598effe94639478856d6f4b34e0de76ee0bc9b38fb56b3036, 0x92f90f8c473928fe949f6951757664e4b4be1651d0ef779e3e4c8d16bd5cc2cf, 0xe43ac9c1b796ea17a1ed5aa526788d6c8294361b40c04b3039c6e25e96aa8d91, 0xbfed46301bf63819ba4dae77ae6077d7a9b3950210f30768acd2d110797f4adb]`,
 right: `[0x3ffb5a0dbe680941d33afbd7e73c782e3591f21485fcaee31581fbc68f26a725, 0xf3cbdac4e7db24b598effe94639478856d6f4b34e0de76ee0bc9b38fb56b3036, 0x92f90f8c473928fe949f6951757664e4b4be1651d0ef779e3e4c8d16bd5cc2cf, 0xe43ac9c1b796ea17a1ed5aa526788d6c8294361b40c04b3039c6e25e96aa8d91, 0xbfed46301bf63819ba4dae77ae6077d7a9b3950210f30768acd2d110797f4adb]`', primitives/trie/src/cache/mod.rs:640:9
```

cc @bkchr

**Comment by bkchr** [comment]
Which pr? Does this pr includes the following pr: https://github.com/paritytech/substrate/pull/12075/commits/bb17b9f77f3e719e2ce4b25b9ea1630c8b6ca138?

**Comment by ggwpez** [comment]
> Which pr? Does this pr includes the following pr: [bb17b9f](https://github.com/paritytech/substrate/commit/bb17b9f77f3e719e2ce4b25b9ea1630c8b6ca138)?

Master branch. Yea it includes that change.
