### ISSUE TITLE
Move bitswap and transactions protocol out of `sc-network`

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#12133]
Alongside https://github.com/paritytech/substrate/issues/8686 we should also move out `transactions` and `bitswap` protocol out of `sc-network`. These protocols should go on their own crates. While doing this we should also clear up [`Behaviour::new`](https://github.com/paritytech/substrate/blob/57e3486d9c7bb4deaef33cf9ba2da083b4e40314/client/network/src/behaviour.rs#L220-L233) to take all `ProtocolConfig`s in the `request_response_protocols` vector. There should be no need that we list all the other protocols on individually.

- [x] Move out transactions protocol: https://github.com/paritytech/substrate/tree/57e3486d9c7bb4deaef33cf9ba2da083b4e40314/client/network/src/transactions.rs
- [x] Move out bitswap protocol: https://github.com/paritytech/substrate/tree/57e3486d9c7bb4deaef33cf9ba2da083b4e40314/client/network/src/bitswap.rs
- [ ] Refactor `Behaviour::new`.

**Comment by bkchr** [comment]
When moving out the bitswap protocol, we need to revert the changes done in this pr: https://github.com/paritytech/substrate/pull/12082

**Comment by altonen** [comment]
The last bullet will be fixed as part of one of the upcoming pull requests that move syncing out of `sc-network`. Right now the protocols (even their names) are too deeply integrated into the code.
