### ISSUE TITLE
subkey.Dockerfile missing ability to pass in external key file for inspect-node-key

### ISSUE THREAD

**Issue by chrisdcosta** [paritytech/substrate#12137]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Whilst attempting to execute the `inspect-node-key` functionality using the docker image you are unable to pass in an external (to the container) file in order to inspect the identity generated by that key. 

A command such as this:

    docker run -i --rm parity/subkey:latest inspect-node-key --file 61757261your-node-public-key-hex < /path/to/you/node-key-file/61757261your-node-public-key-hex

...will result in the following error:

    Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })

### Usage
This is useful for activities involving the identity of your node on the p2p network for example ensuring that your bootnode is in fact using the correct key by comparison amongst others which require arguments or data to be passed to subkey.

### Proposed solution
One solution to this problem would be to add the `VOLUME` command into the dockerfile. This allows the use of the volume mapping option whilst running docker and allowing users to dynamically reference files outside the container.

There are other options although this one seems to be the most flexible.

### Steps to reproduce

As described above.

**Comment by davxy** [comment]
1. Key generation using docker
```bash
$ docker run -i --rm -w/data -v$(pwd):/data parity/subkey:latest generate-node-key --file keyfile`
```

Now in your host and within the dir from where you started docker you should have a new file `keyfile`

2. Inspect key using docker 
```bash
$ docker run -i --rm -w/data -v$(pwd):/data parity/subkey:latest inspect-node-key --file keyfile
12D3KooWJwE3zdkCvPASfQi4hj9Tyk9yCdBqpEJrnq73qoisQfHc
``` 

The trick here is to use:
- `-v $(pwd):/data` : to map your current host dir to the `/data` folder within docker
- `-w data`: to run your docker commands within docker `/data`  folder (docker working dir)
