### ISSUE TITLE
Make new Weight struct `#[codec(compact)]`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#12149]
The fields in the new weight struct should be `#[codec(compact)]`, which will involve a storage migration for any places where weight is stored.

Makes sense to do this the same time we need to do a storage migration for the second field of Weight.

**Comment by bkchr** [comment]
You should be able to implement `scale_codec::CompactAs` and then you should not need any migration.

**Comment by shawntabrizi** [comment]
So the implementation will try compact decode, and if it fails, try u64 decode?

**Comment by bkchr** [comment]
No, then you can write `#[compact]` as before. So, nothing would change in the declaration of dispatchables. However, weight would still be stored by default without compaction.

**Comment by shawntabrizi** [comment]
okay, but actually i would like to also make the values compact by default in the future

**Comment by shawntabrizi** [comment]
@bkchr here is me using compact as for now, but should make it actually compact in the future as mentioned in this issue:

https://github.com/paritytech/substrate/pull/12138/commits/b6eb595b9c926ae1fb158d52c4284d8e90528b2b

**Comment by bkchr** [comment]
> @bkchr here is me using compact as for now, but should make it actually compact in the future as mentioned in this issue:
> 
> [b6eb595](https://github.com/paritytech/substrate/commit/b6eb595b9c926ae1fb158d52c4284d8e90528b2b)

Okay :P Yeah, when we switch to the two dimensional we will need some migrations anyway.

**Comment by KiChjang** [comment]
After #12277, the new `Weight` struct has its fields all `#[codec(compact)]` by default, and so the struct itself does not need to be `#[pallet::compact]` anymore.
