### ISSUE TITLE
Why does `pallet_democracy` use a `Vec` instead of `BoundedVec` as votes?

### ISSUE THREAD

**Issue by Chralt98** [paritytech/substrate#12160]
https://github.com/paritytech/substrate/blob/435218f5c4d0045d92d094641c915c31513cf2bf/frame/democracy/src/vote.rs#L140

Couldn't we use a `BoundedVec` here? Why do we need a `Vec` here? The bound would be the maximum number of votes.

From here:

https://github.com/paritytech/substrate/blob/435218f5c4d0045d92d094641c915c31513cf2bf/frame/democracy/src/lib.rs#L1389-L1392

**Comment by shawntabrizi** [comment]
@Chralt98 yes it should. There is a tracking issue to make all of these pallets use all bounded storage, and democracy is still in progress: https://github.com/paritytech/substrate/issues/8629
