### ISSUE TITLE
construct_runtime issue with instance parsing & formatting

### ISSUE THREAD

**Issue by Dinonard** [paritytech/substrate#12161]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Hello,

I've noticed an issue while building one of our runtimes after uplifting to `polkadot-v0.9.28` and to Rust `nightly-2022-07-24`.

Running `cargo fmt` will remove `::` in front of instance declaration, causing the macro to break. To illustrate:

```Rust
construct_runtime!(
    pub struct Runtime
    where
        Block = Block,
        NodeBlock = generic::Block<Header, sp_runtime::OpaqueExtrinsic>,
        UncheckedExtrinsic = UncheckedExtrinsic,
    {
        ...
        Council: pallet_collective::<Instance1>,
        TechnicalCommittee: pallet_collective::<Instance2>,
    }
);
```

After running `cargo fmt`:

```Rust
construct_runtime!(
    pub struct Runtime
    where
        Block = Block,
        NodeBlock = generic::Block<Header, sp_runtime::OpaqueExtrinsic>,
        UncheckedExtrinsic = UncheckedExtrinsic,
    {
        ...
        Council: pallet_collective<Instance1>,   <<== '::' is gone
        TechnicalCommittee: pallet_collective<Instance2>,
    }
);
```

The compilation will fail afterwards.

I did a bit of digging and assume this part of the code is the culprit: [parse.rs](https://github.com/paritytech/substrate/blob/master/frame/support/procedural/src/construct_runtime/parse.rs#L224)

Should that code be changed to allow omitting the '::'?

**Comment by bkchr** [comment]
This is a bug in rustfmt. It should not remove some tokens in a macro.

**Comment by Dinonard** [comment]
In that case, I will post this to `rustfmt` repo.
