### ISSUE TITLE
wasm build failure for primitives crate

### ISSUE THREAD

**Issue by jnaviask** [paritytech/substrate#1218]
We're building a module for a custom substrate node that uses elements from `core/primitives`. When we add our new module to the runtime, as specified in the custom Substrate chain tutorial, we get a failure from the `build.sh` script. This failure originates with the `ring` dependency, which is used by the `ed25519` API inside `core/primitives`.

Steps to reproduce:
1. Make sure you have substrate checked out and build dependencies installed.
1. Navigate to `core/primitives`.
2. Run `cargo +nightly build --target=wasm32-unknown-unknown --release`.

What should our next steps be?

**Comment by rphmeier** [comment]
Are you adding the `core/primitives` with `default-features = false`?

**Comment by jnaviask** [comment]
Adding `default-features = false` to our module fixed the WASM build, thanks.
