### ISSUE TITLE
try-runtime: fix proof size

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12195]
as spoken with Alan from moonbeam, the current proof size that's reported in the `on-runtime-upgrade` is not correct. IIRC, it had something to do with reading/writing the code, which is not on-par with reality. 

All in all, make sure that the proof size reported by try-runtime is 100% accurate.

**Comment by crystalin** [comment]
Yes, the difference is because during the runtime upgrade of a parachain you have 2 parts.
1. Sending the runtime wasm
2. Getting it enacted and running the runtime upgrade.

In the try-runtime both are done at the same block it seems so the PoV is the sum of both action, while in reality those 2 happen in a different block

**Comment by kianenigma** [comment]
> Yes, the difference is because during the runtime upgrade of a parachain you have 2 parts.
> 
> 1. Sending the runtime wasm
> 2. Getting it enacted and running the runtime upgrade.
> 
> In the try-runtime both are done at the same block it seems so the PoV is the sum of both action, while in reality those 2 happen in a different block

Thinking about this again, I am not sure if the `:CODE:` is the cause of the issue actually. Any discrepancy must have been due to `pre_upgrade` and `post_upgrade` being executed in the call as well, which I will address in #12537. 

`:CODE:` is actually never read from within the runtime in a try-runtime call, so it should on-par.

All in all, after `#12537`, the PoV that try-runtime reports for `on-runtime-upgrade` is exactly the PoV of the entire `OnRuntimeUpgrade` calls within the runtime. This is probably slightly less than a real block being produced, because the real block will have other stuff in it as well, but nothing more than a few `on_initialize` if the weight is tracked correctly.

**Comment by crystalin** [comment]
@kianenigma now that I think about it, It is porbably another case of the `state_version: 1`  
@bkchr told me that the current behavior with state_version 0 is to include the blob in all the blocks until it is applied (which is what we observe) but this behavior is fixed with state_version 1.

**Comment by bkchr** [comment]
> behavior with state_version 0 is to include the blob in all the blocks until it is applied

You mean the code? This should currently also not happening. At least for your Parachain in production. With `try-runtime` it could happen.

**Comment by bkchr** [comment]
I remember the discussion, but not why I said this xD I mean, for the PoV containing the wasm blob twice should probably be solved by `state_version=1`, because the deletion still pulls the data into the PoV. For the other case of always including the `code` in every PoV, it mays happens because `PendingValidationCode` for whatever reason is somehow a branch node. To find this out we would need to look into the trie/proof. 

Now after looking again at your output, it is weird that already at block 6 the `code` appears in the PoV? For the block after registering the upgrade on the relay chain we call [this code](https://github.com/paritytech/cumulus/blob/3d257b770d06e94dfe223b0ba8f1252740814ea4/pallets/parachain-system/src/lib.rs#L278), which could also pull the code again into the PoV.

**Comment by kianenigma** [comment]
@crystalin have you had the chance to try any try-runtime with the correct state version and see if that gives a value that is aligned? Or even better, if you have the resources, you can try the new branch in #12537.

**Comment by crystalin** [comment]
I've been redoing the test and it seems to be fixed in current version of substrate

try-runtime =>
```
// storage-version = 0
main try-runtime::cli: proof size: 1.39 MB (1420.474609375 KB) (1454566 bytes)    
main try-runtime::cli: compact proof size: 1.41 MB (1447.4248046875 KB) (1482163 bytes)    
main try-runtime::cli: zstd-compressed compact proof 390.11 KB (399477 bytes)    
main try-runtime::cli: TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 17750000000, total weight = 500000000000 (0.0355)

// storage-version = 1
main try-runtime::cli: proof size: 1.36 MB (1392.947265625 KB) (1426378 bytes)    
main try-runtime::cli: compact proof size: 1.39 MB (1420.1552734375 KB) (1454239 bytes)    
main try-runtime::cli: zstd-compressed compact proof 389.56 KB (398906 bytes)    
main try-runtime::cli: TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 17750000000, total weight = 500000000000 (0.0355) 
```

Real runtime upgrade:
```
proposing at 65 ( 5 ms), Compressed PoV size: 15.29kb { header: 0.3427734375kb, extrinsics: 3.015625kb, storage_proof: 15.4638671875kb }
proposing at 66 ( 6 ms), Compressed PoV size: 15.31kb { header: 0.3427734375kb, extrinsics: 3.015625kb, storage_proof: 15.501953125kb }
proposing at 67 (27 ms), Compressed PoV size: 1380.kb { header: 0.3427734375kb, extrinsics: 1364.5458984375kb, storage_proof: 18.6103515625kb }
proposing at 68 ( 6 ms), Compressed PoV size: 1377.kb { header: 0.3427734375kb, extrinsics: 3.0673828125kb, storage_proof: 2738.76953125kb }
proposing at 69 ( 6 ms), Compressed PoV size: 1377.kb { header: 0.3427734375kb, extrinsics: 3.0673828125kb, storage_proof: 1377.181640625kb }
proposing at 70 ( 5 ms), Compressed PoV size: 1377.kb { header: 0.3427734375kb, extrinsics: 3.0673828125kb, storage_proof: 1377.0908203125kb }
proposing at 71 ( 9 ms), Compressed PoV size: 2690.kb { header: 0.3427734375kb, extrinsics: 3.125kb, storage_proof: 2687.310546875kb }
proposing at 72 (11 ms), Compressed PoV size: 408.3kb { header: 0.3427734375kb, extrinsics: 3.111328125kb, storage_proof: 1466.287109375kb }
proposing at 72 (11 ms), Compressed PoV size: 408.3kb { header: 0.3427734375kb, extrinsics: 3.111328125kb, storage_proof: 1466.287109375kb }
proposing at 73 ( 6 ms), Compressed PoV size: 15.80kb { header: 0.3427734375kb, extrinsics: 3.111328125kb, storage_proof: 16.056640625kb }
proposing at 73 ( 5 ms), Compressed PoV size: 16.16kb { header: 0.3427734375kb, extrinsics: 3.111328125kb, storage_proof: 16.056640625kb }
proposing at 74 ( 6 ms), Compressed PoV size: 15.58kb { header: 0.3427734375kb, extrinsics: 3.111328125kb, storage_proof: 15.7041015625kb }
```

(Block 72 is the one doing the migration)

**Comment by kianenigma** [comment]
The small difference is also because try-runtime only executes `OnRutnimeUpgrade`, while in reality, even if the migration block is empty, it called into `OnInitialize` as well.
