### ISSUE TITLE
`full_crypto` feature breaks `no_std` build

### ISSUE THREAD

**Issue by clangenb** [paritytech/substrate#12225]
The reason is that the ed25519-zebra version on crates.io is not yet `no_std` compatible. The master branch in that repository is however: https://github.com/ZcashFoundation/ed25519-zebra. substrate doesn't detect this because the `full_crypto` feature is not used in `no_std` in its codebase.

* Issue opened there: https://github.com/ZcashFoundation/ed25519-zebra/issues/60

**Comment by burdges** [comment]
We should send them a PR for no_std of course.  If they're reluctant to merge it then please send a no_std PR to https://github.com/penumbra-zone/ed25519-consensus too.

**Comment by clangenb** [comment]
The thing is, they have already implemented `no_std` compatibility on their master branch since last may. They only need to publish a release on crates.io, which I have requested now.

I kind of assumed that you do not want to add arbitrary git repositories as third-party dependencies without referencing a specific tag, as downstream implementors get simply the newest commit on master branch, which might be breaking changes.

**Comment by burdges** [comment]
cool, yeah they can simply do a release I'd think.

**Comment by clangenb** [comment]
@burdges I have not heard anything from them. Do you mind talking to them?

**Comment by clangenb** [comment]
@burdges This is now in the polkadot-v0.9.29, and now we need to patch this on our end. May I ask you again to talk to them directly to publish a release? Thank you very much!

**Comment by burdges** [comment]
We need this fast then?  We'll likely need to republish their crate ourselves, but I'll ask again right quick..

**Comment by clangenb** [comment]
Well, it seems we are the only people using this feature combination so far, and patching it with the git repository works, fortunately. But the sooner, the better!

Thank you very much!

**Comment by burdges** [comment]
Did we ever try https://github.com/penumbra-zone/ed25519-consensus ?

I voted zebra way back because zcash foundation maintains it but.. at least penumbra is not just one person now.
