### ISSUE TITLE
Associated iterator types for `InspectEnumerable`

### ISSUE THREAD

**Issue by benluelo** [paritytech/substrate#12231]
The current definition of the InspectEnumerable traits forces you to use `Box<dyn Iterator>` for the method return types. Given that the iterator types can usually be named ([and that `impl Trait` in traits is a long ways away](https://rust-lang.github.io/impl-trait-initiative/)) I think it would be beneficial to define associated types for each method:

```rust
pub trait InspectEnumerable<AccountId>: Inspect<AccountId> {
    type CollectionsIter: Iterator<Item = Self::CollectionId>;
    type ItemsIter: Iterator<Item = Self::ItemId>;
    type OwnedIter: Iterator<Item = (Self::CollectionId, Self::ItemId)>;
    type OwnedInCollectionIter: Iterator<Item = Self::ItemId>;

	/// Returns an iterator of the collections in existence.
	fn collections() -> Self::CollectionsIter;

	/// Returns an iterator of the items of a `collection` in existence.
	fn items(collection: &Self::CollectionId) -> Self::ItemsIter;

	/// Returns an iterator of the items of all collections owned by `who`.
	fn owned(who: &AccountId) -> Self::OwnedIter;

	/// Returns an iterator of the items of `collection` owned by `who`.
	fn owned_in_collection(
		collection: &Self::CollectionId,
		who: &AccountId,
	) -> Self::OwnedInCollectionIter;
}
```

These associated types could always be defined as boxed iterators if the implementer can't/ doesn't feel like explicitly naming the types.

I would be happy to take this on myself if it's accepted :+1:

**Comment by bkchr** [comment]
Sounds reasonable.
