### ISSUE TITLE
[Deprecation] Deprecate `decl_*` macros

### ISSUE THREAD

**Issue by KiChjang** [paritytech/substrate#12248]
We've now basically migrated from the previous function-like `decl_*` macros into the `#[pallet]` attribute macros, and it's time that we start deprecating/removing the old `decl_` macros.

**Comment by yourarj** [comment]
@KiChjang I would like to take it up.

**Comment by ggwpez** [comment]
There are two merge requests leading up to this https://github.com/paritytech/substrate/pull/12401 and https://github.com/paritytech/substrate/pull/12445 which are both stale&closed.  
Maybe someone can give this another nudge? The old macros still pollute the code base.

**Comment by juangirini** [comment]
The deprecated `Module` type alias for `Pallet` should also be removed

**Comment by ggwpez** [comment]
> The deprecated `Module` type alias for `Pallet` should also be removed

I am not familiar with this, but looks like it already is deprecated?! Since two years actually…  
https://github.com/paritytech/substrate/blob/9ffd3d70bfc44ab306323e33bf7d234743268b03/frame/support/procedural/src/pallet/expand/pallet_struct.rs#L197

**Comment by juangirini** [comment]
> I am not familiar with this, but looks like it already is deprecated?! Since two years actually…

Yes, it's already time to remove it :)

**Comment by ggwpez** [comment]
Okay so closign his and creating another one for removal.
