### ISSUE TITLE
warp sync stuck at downloading block #1 with `Verification failed` messages

### ISSUE THREAD

**Issue by dmitry-markin** [paritytech/substrate#12268]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Warp sync fails to download blocks with the following error messages:
```
💔 Error importing block 0x93d7405b5c449089a6a44c757074e9f614e4a2ef8155e4599bd46bef9f7b9f38: block has an unknown parent
💔 Verification failed for block 0x409d0bfe677594d7558101d574633d5808a6fc373cbd964ef236f00941f290ee received from peer: 12D3KooWRsGxnhpn3WtUAgbrQSyCQQ43FQ6rsrtJUastDvGnofEc, "UnknownBlock: State already discarded for BlockId::Hash(0xc0096358534ec8d21d01d34b836eed476a1c343f8724fa2153dc0725ad797a90)"
```

The complete logs are [here](https://gist.github.com/dmitry-markin/7230ebf833e179091811288342ce4513).

### Steps to reproduce

Run warp-sync on current polkadot+substrate master.

Polkadot commit ID: `e0441494999c689665d11d4c2981bdce074ed05f`.

Substrate commit ID: `23bb5a6255bbcd7ce2999044710428bc4a7a924f`.

**Comment by arkpar** [comment]
Looks like this is caused by #12213
`check_inherents` is now called for old blocks.

**Comment by dmitry-markin** [comment]
Yesterday version as of Sep 12 18:10:32 UTC works fine (polkadot `6b141d2de2700c1d517b52011e6d161e80bc7540`, substrate `dd1f1b5f291aa2325eddf5f26037b84cfbbe0957`).
