### ISSUE TITLE
Error when compiling `sc-network-bitswap`

### ISSUE THREAD

**Issue by Szegoo** [paritytech/substrate#12278]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Error when trying to compile `sc-network-bitswap`.

**The error message**:

error: failed to run custom build command for `sc-network-bitswap v0.10.0-dev (/Users/sergejsakac/substrate-rename-origin/client/network/bitswap)`

Caused by:
  process didn't exit successfully: `/Users/sergejsakac/substrate-rename-origin/target/debug/build/sc-network-bitswap-7f9e8857414bdb65/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '
  Could not find `protoc` installation and this build crate cannot proceed without
  this knowledge. If `protoc` is installed and this crate had trouble finding
  it, you can set the `PROTOC` environment variable with the specific path to your
  installed `protoc` binary.

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', /Users/sergejsakac/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.11.1/src/lib.rs:1227:10

### Steps to reproduce

`cargo test -p sc-network-bitswap`

**Comment by bkchr** [comment]
The failing build script directly tells you what you should do:
```
Could not find protoc installation and this build crate cannot proceed without
this knowledge. If protoc is installed and this crate had trouble finding
it, you can set the PROTOC environment variable with the specific path to your
installed protoc binary.
```

If you do this, it should work.
