### ISSUE TITLE
[Feature Request] Add Lock and Unlock events to pallet balances

### ISSUE THREAD

**Issue by sea212** [paritytech/substrate#12276]
**What is requested?**
Whenever some balance is locked or unlocked, a corresponding event `Locked` or `Unlocked` should be emitted.

**What problem would it solve?**
The events in the balances pallet already map any state change to an account very well, but they are not complete yet. Software that relies on the completeness of events (besides information in transactions), such as blockchain indexers and processors, cannot retrieve this information (lock changes) in an elegant way currently. Workarounds have to be applied in those environments to completely capture state changes to an account in the balance pallet.

**Additional notes**
Since every public function in the balances pallet that modifies locks ultimately calls [`update_locks`](https://github.com/paritytech/substrate/blob/3bef1baae8c428524152e6c5fbb1c35285a128b3/frame/balances/src/lib.rs#L947-L997) to apply the update, we only have to check in [`update_locks`](https://github.com/paritytech/substrate/blob/3bef1baae8c428524152e6c5fbb1c35285a128b3/frame/balances/src/lib.rs#L947-L997)  whether the new lock is smaller or greater to determine if it is a `Locked` or `Unlocked` event and to be able to determine how big the change is.

**Comment by shawntabrizi** [comment]
@sea212 do you want to make the PR that solves this?

**Comment by sea212** [comment]
Sure, I'll prepare a PR soon.
