### ISSUE TITLE
[pallet_assets] How to destroy an asset with potentially `u32::MAX` accounts?

### ISSUE THREAD

**Issue by Chralt98** [paritytech/substrate#12275]
Hey valuable Substrate maintainers,

I found out, that the witness limits the number of deletions [here](https://github.com/paritytech/substrate/blob/23bb5a6255bbcd7ce2999044710428bc4a7a924f/frame/assets/src/functions.rs#L682), but when there are too many accounts for one asset, then a sufficiently high number for the accounts in the witness param would lead to a weight which exceeds the maximum block limit. What could be done, if there are `u32::MAX` accounts with non-zero balances? Then, we couldn't destroy the asset right? Or is the consumed weight with `u32::MAX` below the maximum block limit? I don't think so.

What can I do to destroy a portion of all accounts? For example one could call an extrinsic multiple times with a small witness to destroy all `u32::MAX` accounts.

`u32::MAX` should only be an example to get a better understanding of this problem

**Comment by jsidorenko** [comment]
cc @tonyalaribe

**Comment by jsidorenko** [comment]
What if we change the assets deletion process a bit:
1) we mark an asset as soft-deleted and thus prevent any transfers
2) we create a method to wipe user balances for such a token by passing either the addresses or the number of accounts to wipe. This would allow calling the same method multiple times
3) and finally, completely delete the token

**Comment by joepetrowski** [comment]
It's a bit of an edge case, but `freeze_asset` should really be used in advance of deleting an asset anyway in order to provide the correct witness data. Otherwise, a simple transfer getting between your transaction construction and inclusion will invalidate the `destroy` call.

**Comment by tonyalaribe** [comment]
So an alternate solution would be to destroy the maximum number of accounts, and then emit a PartiallyDestroyed event to encourage reexecuting the action to complete destroying the asset. Like the [refund and dissolve pattern in cloud loans](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/crowdloan/mod.rs#L501L572)

**Comment by jsidorenko** [comment]
yeah, that could work as well

**Comment by tonyalaribe** [comment]
I'll create a PR for this.
