### ISSUE TITLE
Callbacks for pallet-assets

### ISSUE THREAD

**Issue by Dinonard** [paritytech/substrate#12279]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Hi there,

it would be very useful if we could register callback methods for when new assets in `pallet-assets` are created, destroyed or manipulated in some other way.
The motivation behind is making assets cross-chain compatible for EVM contracts - in order to do this automatically, we need to do some actions after a new asset has been created. Being able to do this just using what `pallet-assets` provides would be great.

E.g. introduce a trait like:
```Rust
/// Callbacks for various asset manipulation functions
pub trait AssetsCallback<AssetId, AccountId> {

	/// Indicates that asset with `id` was successfully created by the `owner`
	fn created(id: &AssetId, owner: &AccountId);

	/// Indicates that asset with `id` has just been destroyed
    fn destroyed(id: &AssetId);
}
```

and have it as part of `pallet-assets` `Config`:
```Rust
	pub trait Config<I: 'static = ()>: frame_system::Config {
                ....
		/// Callback methods for asset state change (e.g. asset created or destroyed)
		type Callback: AssetsCallback<Self::AssetId, Self::AccountId>;
	}
```
Then it's just a matter of calling it once `create` or `destroy` have been successfully executed.
This would be a lightweight change, no benchmarks would really need to be changed if user doesn't introduce any custom hooks.

Is this a feasible change for `pallet-assets`?
Or should it just be handled by another pallet in chains that require it?

Related to [this](https://github.com/paritytech/substrate/discussions/12235) discussion basically.

**Comment by joepetrowski** [comment]
Seems reasonable to me at first glance. @tonyalaribe - can you look into it more?

**Comment by kianenigma** [comment]
Should be an easy addition -- and a `() impl` does nothing.

**Comment by Dinonard** [comment]
Thanks for the feedback!

I'll prepare a PR during tomorrow and reference this issue.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-37/1736/1
