### ISSUE TITLE
Make cross-module verification of inherentdata easier 

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1228]
For instance, in #1216, we have two inherents we want to cross-check:
  - The timestamp set in the inherent
  - The expected time-slot of the header: this is extracted from a post-runtime digest called `Seal`.

We want to make sure that `expected_slot == derive_slot_from(timestamp)`. However, there is no easy way to do this exactly.

**Comment by rphmeier** [comment]
cc @bkchr

**Comment by gavofyork** [comment]
Is this solved now? If not can we push it to 1.x series?

**Comment by gavofyork** [comment]
@rphmeier ^^^

**Comment by rphmeier** [comment]
Appears to be fine
