### ISSUE TITLE
BEEFY: integrate request-response protocol peer selection strategy with all of sync

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#12296]
PR https://github.com/paritytech/substrate/pull/12124 added a custom Request-Response protocol to BEEFY, including a simple peer selection strategy based on connected peers' gossiped votes.

In the long run we want to integrate with the smarter `sync` [peer selection strategy](https://github.com/paritytech/substrate/blob/master/client/network/sync/src/lib.rs#L257-L272), once that is decoupled from the generic networking code.

Timeline is to tackle this at the same time we do it for Grandpa/Warp-sync. 

CC @andresilva

**Comment by bkchr** [comment]
> In the long run we want to integrate with the smarter `sync` [peer selection strategy](https://github.com/paritytech/substrate/blob/master/client/network/sync/src/lib.rs#L257-L272), once that is decoupled from the generic networking code.

What you mean by smarter `sync` peer selection? You just link a struct there.

You should already be able to follow the sync peers by listening on the `event_stream` from the networking service.
