### ISSUE TITLE
[pallet_lottery] Is the random number generation safe?

### ISSUE THREAD

**Issue by Chralt98** [paritytech/substrate#12292]
Hey Substrate Team!

I read this post of Shawn https://substrate.stackexchange.com/a/128/2484 and found out, that random numbers for lotteries are not reliable, even with VRF on GRANDPA since the validators could earn more money through the lottery than for the block production. So I would derive, that the usage of random numbers for lotteries is not safe in production, when the stake is high enough. So therefore the question: Is `pallet_lottery` safe in production? If yes or no, please post why?

I am not regarding the problem of the [modulus bias for `pallet_lottery` ](https://github.com/paritytech/substrate/issues/8311) .

**Comment by bkchr** [comment]
This sounds like a perfect question for stackexchange. Please post it there.

**Comment by Chralt98** [comment]
https://substrate.stackexchange.com/questions/4889/is-the-random-number-generation-safe-for-pallet-lottery
