### ISSUE TITLE
Utility.batch_all wrapped in Proxy is not transactional

### ISSUE THREAD

**Issue by MrPai** [paritytech/substrate#12306]
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Description of bug

In this PR: https://github.com/paritytech/substrate/pull/11431, 
the macro ```#[transactional]``` has been removed from 'utility.batch_all', it works good normally, however if it's wrapped in `Proxy.proxy`, there is an issue:

suppose a transaction like this:
`Proxy.proxy<Utility.batch_all<call1,call2,call3>>`
- call1: system. remarkWithEvent
- call2: balance.transfer(1 trillion)
- call3: system. remarkWithEvent

if send this transaction to on-chain, call2 failed but call1 success.

### on-chain proxy transaction:
https://polkadot.js.org/apps/?rpc=wss://rpc.polkadot.io#/explorer/query/0xfe8aded7fc1380da895e90d046acf55c6e51fe0939c0b8b93d9c477156a97931

https://polkadot.polkaholic.io/tx/0xb437c0237cba48e4eec12dffbe19bdec9305c5df7a4365f861f8c1303b664436

**Comment by shawntabrizi** [comment]
Assuming you are on the latest master, these kinds of issues should be resolved starting here: https://github.com/paritytech/substrate/pull/11927

**Comment by MrPai** [comment]
Got it, thanks.
