### ISSUE TITLE
pallet-mmr: Change runtime API and RPC API to work with block numbers instead of leaf indices

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#12339]
### Issue

This issue was triggered by a good observation made by @serban300 in https://github.com/paritytech/substrate/pull/12324#issuecomment-1255984160:

Current `pallet-mmr` APIs work with leaf indices, leaving the burden of translating block numbers to leaf indices to the users of the pallet.

Light clients might have an easier experience dealing only with block numbers, and avoiding managing leaf indices and the conversion from block numbers => leaf indices.

### Suggested solution

`pallet-mmr` could expose APIs based on block numbers and internally map those to leaf indices.

### Implications

- Breaking API change, both for Runtime API and RPC API.
- Pallet currently only deployed on Rococo so breaking change only for that. Kusama and Polkadot will directly deploy new API.

### Feedback requests

cc @vgeddes and @seunlanlege as current (light-client) users of this pallet

**Comment by Szegoo** [comment]
I will give this a try.

**Comment by acatangiu** [comment]
As shown in https://github.com/paritytech/substrate/pull/12345 there is also the option to change only RPC API to use block numbers, while leaving existing Runtime API unchanged.

**Comment by seunlanlege** [comment]
And while this change is harmless, it's actually unneccessary. As light clients need to be aware of the `leaf_index` which they can use to derive the `leaf_postion` which is needed when verifying mmr proofs with the [ckb-merkle-mountain-range lib ](https://crates.io/crates/ckb-merkle-mountain-range)

**Comment by acatangiu** [comment]
Seeing how `pallet-mmr` has only been deployed on `Rococo` so far, I'm leaning heavily to just break the API without backwards compatibility if that's acceptable to you.

**Comment by vgeddes** [comment]
sounds fine with us 👍

**Comment by acatangiu** [comment]
Yes, decision is to implement full breaking change. Let's change Runtime API too in #12345
