### ISSUE TITLE
Corruption: Bad block content

### ISSUE THREAD

**Issue by jasl** [paritytech/substrate#12346]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Sorry I can give furthur more detail, because it's a user forward me but I can't contact him again

The node's version are based on polkadot-v0.9.29 branch

![IMAGE 2022-09-25 15:38:55](https://user-images.githubusercontent.com/1024162/192133365-fa4dff89-f41d-4478-bdff-a57ff602cdae.jpg)

**Comment by bkchr** [comment]
Looks like a broken db. Maybe some file system corruption. If this happens again and isn't a faulty file system, please reopen
