### ISSUE TITLE
More tests for utility.batch / batchAll / forceBatch 

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#12374]
https://github.com/paritytech/substrate/pull/12321 introduced a regression that only allow root and signed to use batch call. Batch call is also commonly used for non root governance actions as well.

We need more tests to cover this area to ensure we won't have this kind of regression in future.

**Comment by jak-pan** [comment]
+ if this fails it doesn't throw any traceable event. (At least not on Kusama as we learned hard way)
