### ISSUE TITLE
Remove `*_old_weight` extrinsic after migration to extrinsics with new `Weight` struct is complete

### ISSUE THREAD

**Issue by KiChjang** [paritytech/substrate#12377]
In #12277, we created new extrinsics that utilizes the new 2D `Weight` struct as part of its parameters, and deprecated those that still uses the old `Weight` struct. The deprecated extrinsics are renamed and they all end with `_old_weight`. We have chosen this method of migration because we want to allow downstream dependencies to still be able to decode into the deprecated calls, but warn upon calling them.

The migration strategy we have for now is to allow downstream dependencies to call the deprecated extrinsics, and allow them to migrate to the new ones. After a certain length of time, we should however work towards:

- [ ] Removing the `OldWeight` struct
- [ ] Completely remove the deprecated extrinsics while ensuring that we keep the extrinsic indices unchanged (can be done using the `#[pallet::call_index]` attribute).

**Comment by ggwpez** [comment]
Both tasks completed for all FRAME pallets in https://github.com/paritytech/substrate/pull/13699.  
Contracts need to support V1 indefinitely - issue does therenot apply there.
