### ISSUE TITLE
Align - `codec` versions 

### ISSUE THREAD

**Issue by mustermeiszer** [paritytech/substrate#12380]
Currently, there are two dependencies in substrate that have differing codec versions from the otherwise used `version = 3.0.0`

* https://github.com/paritytech/substrate/blob/1b1a5e12c0e391c7ed4e3ffa332eb2fe928d257f/frame/conviction-voting/Cargo.toml#L17-L20
* https://github.com/paritytech/substrate/blob/1b1a5e12c0e391c7ed4e3ffa332eb2fe928d257f/primitives/io/Cargo.toml#L19

Would it be possible to align those? 

We are currently running on `version = 3.0.0` so that we are compatible with substrate.
* But on our side cargo resolves the `codec` depdency to: `version = 3.1.5`
* On the Substrate side cargo resolves the `codec` dependency to `version = 3.1.3`
which crashes our trait compatablilty.

Is there a reason these two versions need to differ from the "default" version? Would it be possible to align the versions?

**Comment by MrishoLukamba** [comment]
@kianenigma @shawntabrizi

**Comment by bkchr** [comment]
> * which crashes our trait compatablilty.

What you mean by this? 

These are all compatible versions to each other, so you can use 3.1.5 downstream.

**Comment by mustermeiszer** [comment]
But are distinct traits from a compiler perspective. 

## Example
```rust
use frame_support::traits::fungibles::Inspect;

type CurrencyOf<T> =
		<<T as Config>::Tokens as Inspect<<T as frame_system::Config>::AccountId>>::AssetId;

pub Config: frame_system::Config
{
    type Tokens: Inspect<Self::AccountId>;
}

#[pallet::Storage]
pub type Dummy<T: Config> =
      StorageMap<_, Blake2_128Concat, u32, CurrencyOf<T>>;
```

will not compile as my `MaxEncodedLen` is not equal to Substrates `MaxEncodedLen`. I can of course bound the `AssetId` to my local `MaxEncodedLen`. 

I think my main interest was, why different codec versions across Substrate and if we should adapt to that.

**Comment by mustermeiszer** [comment]
Maybe it's also just a local setup thing, why my machine does not agree on a common compatible version between Susbtrate and Centrifuge. TBH it is not important enough to waste our times here, so I will close this.

**Comment by bkchr** [comment]
> I think my main interest was, why different codec versions across Substrate and if we should adapt to that.

As I said above, the versions should all be represented by one in your downstream project. That is how semver works.
