### ISSUE TITLE
doc-only module to group all storage items of a pallet

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12398]
A simple one: create a 

```
#[cfg(doc)]
pub mod storage_types {
   pub use crate::pallet::every_public_storage_item;
}
```

for nicer discoverability in rustdocs. 

Essentially, similar to this page, but better: 

https://polkadot.js.org/docs/substrate/storage/#staking

**Comment by kianenigma** [comment]
cc @sam0x17

**Comment by sam0x17** [comment]
This would be a good add-on or follow-up to https://github.com/paritytech/substrate/pull/12334

**Comment by bkchr** [comment]
We should not only list all the public storage types. We should probably support having all of them shown in the docs, not just the public ones.

**Comment by kianenigma** [comment]
> We should probably support having all of them shown in the docs, not just the public ones.

Yeah, let's do that. Might be a little confusing though because some of them might not be public in the Rust code. 

This `pub mod storage_types {}` should have a clear documentation saying that what's named here might not be publicly available in the API and is only listed as reference.

**Comment by kianenigma** [comment]
> This would be a good add-on or follow-up to #12334

I think they are rather unrelated in terms of what needs to be done for it, but yeah perhaps a follow-up for you once you are finished there, feel free to assign to yourself :)

**Comment by kianenigma** [comment]
@olliecorbisiero this is the fix for what we spoke of today.

**Comment by kianenigma** [comment]
This is currently blocked by the fact that some storage types can be made `pub(crate)`.

Option 1: All storage items must be public and visible in the rust-docs. 
Option 2: All storage items are artificially `#[cfg(doc)] pub #[cfg(not(doc))] $vis`. A bit confusing eh? 
Option 3: non-public storage items will not go into rust-docs. 


I would go with either option 1 or 3 for now.

**Comment by kianenigma** [comment]
@ggwpez @KiChjang @shawntabrizi if you are more or less on the same page, let's consider option 1.

**Comment by KiChjang** [comment]
Well, in that case, why don't we just remove the ability to set visibility on storages? Sounds like we can just modify the macro to do so.

**Comment by bkchr** [comment]
We could, but a warning is probably better from the usability.

**Comment by sam0x17** [comment]
Bear in mind custom warnings aren't stabilized in rust yet (unless this happened very recently without me knowing) so this is often harder than it sounds

**Comment by bkchr** [comment]
Yeah I know, but yeah, we could also make it a compile_error. However, we should ensure that we generate the correct code plus the compile error. Otherwise people would get tons of unrelated compile errors.

**Comment by kianenigma** [comment]
@sam0x17 if you want to pickup https://github.com/paritytech/substrate/pull/13341 and related tasks, please feel free to do so.

**Comment by sam0x17** [comment]
Yeah I'll pick that up. It's well timed because I'm wrapping up #13224 today
