### ISSUE TITLE
Runtime api not available just after client creation? Exported method is not found

### ISSUE THREAD

**Issue by mateuszaaa** [paritytech/substrate#12392]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The runtime api is not available on client instance, just after it is created 

https://substrate.stackexchange.com/questions/5103/runtime-api-not-available-just-after-client-creation-exported-method-is-not-fou

### Steps to reproduce

provided in stackexchange thread

**Comment by kianenigma** [comment]
No need to create an issue, this will hopefully be answered in SE.
