### ISSUE TITLE
Installation fail "Unable to find libclang" on Ubuntu

### ISSUE THREAD

**Issue by webmaster128** [paritytech/substrate#1240]
Installation via `curl https://getsubstrate.io -sSf | bash` on Ubuntu 18.04 currently fails with

```
   Compiling error-chain v0.12.0
   Compiling ws v0.7.9
   Compiling libp2p-dns v0.1.0 (https://github.com/libp2p/rust-libp2p?rev=d961e656a74d1bab5366d371a06f9e10d5f4a6c5#d961e656)
   Compiling libp2p-tcp-transport v0.1.0 (https://github.com/libp2p/rust-libp2p?rev=d961e656a74d1bab5366d371a06f9e10d5f4a6c5#d961e656)
   Compiling jsonrpc-http-server v9.0.0 (https://github.com/paritytech/jsonrpc.git#4beea5c0)
   Compiling libp2p-kad v0.1.0 (https://github.com/libp2p/rust-libp2p?rev=d961e656a74d1bab5366d371a06f9e10d5f4a6c5#d961e656)
error: failed to run custom build command for `librocksdb-sys v5.11.3`
process didn't exit successfully: `/tmp/cargo-installOvlArW/release/build/librocksdb-sys-00359fe1bebca1e0/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\', \'libclang-*.so\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `substrate v0.1.0 (https://github.com/paritytech/substrate#2ad85dab)`, intermediate artifacts can be found at `/tmp/cargo-installOvlArW`

Caused by:
  build failed
```

What package are we missing here?

**Comment by bkchr** [comment]
Libclang and clang. I will update the getsubstrate script. Sorry!

**Comment by webmaster128** [comment]
Thanks @bkchr. Could you ping me when the script is updated? Then I can verify if it works. But no rush.

**Comment by bkchr** [comment]
@webmaster128 https://github.com/paritytech/scripts/pull/51 will fix this isse :)

**Comment by ltfschoen** [comment]
@bkchr I actually just encountered this same issue when running getsubstrate on Ubuntu Gnome Xenial 64-bit 16.04.2.
I've pushed this commit that avoids the user encountering the error https://github.com/paritytech/scripts/pull/56/commits/a75185fd91a04bdfebabd007456e7aa5a647839d

Below are the screenshots of the errors that I had encountered.

<img width="569" alt="screen shot 2019-01-28 at 1 02 24 am" src="https://user-images.githubusercontent.com/6226175/51801997-3bcad500-2299-11e9-8f83-c9505e33fac5.png">

<img width="608" alt="screen shot 2019-01-27 at 11 22 15 pm" src="https://user-images.githubusercontent.com/6226175/51801998-3e2d2f00-2299-11e9-83c2-6623df9de3b2.png">

**Comment by bkchr** [comment]
@lftschoen your commit is not correct, doing `install -f` is something the script should not be doing. If the user messes up its apt database, it is not the job of the script to fix it.
