### ISSUE TITLE
Contracts: Return emitted events for dry-runs

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate#12412]
Contract dry-runs should return the events that would be emitted.

This will e.g. enable user interfaces to indicate better what the consequence of signing and submitting a particular transaction is.

A current UX movement for blockchains is to counter the "blind sign and submit" behavior ("yolo sign and submit"). We should provide better means to assess the effect of a transaction before submitting; returning the events that would be emitted would be a major step towards that.

**Comment by kianenigma** [comment]
Would be good if the `system_dryRun` does the same.

**Comment by xlc** [comment]
Yeah we should just improve `system_dryRun` https://github.com/paritytech/substrate/issues/7555

**Comment by athei** [comment]
Please note we can't just use `system_dryRun` for dry running contracts. We need to return dispatchable specific data from the dry run. As long as dispatchables can't return data we need out custom dry run runtime API.
