### ISSUE TITLE
In block in memory storage

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#12415]
We don't really have a block scoped temporary variable solution currently. We are currently just use storage for that and kill them at on_finalize hook to ensure they are never persisted. However this is just a workaround and could be improved to reduce overhead of enocde/decode/hash/overlay work.

This isn't as simple as an unsafe static global variable as we are exiting wasm context during block production phase and hence in wasm memory global variable can't be persisted. A quick solution is add new host function to store the in memory data on the host side with a stack so it is possible to pop the data if block producer decided to discard a bad tx. A later optimization could make this purely in wasm memory call during block evaluation / import phase to completely eliminate the overhead of host call and potentially encode/decode work.

This makes it possible to build an in memory trie builder to build a more efficient event system https://github.com/paritytech/substrate/issues/11216

**Comment by bkchr** [comment]
Probably the same as: https://github.com/paritytech/substrate/issues/5396 ?

**Comment by xlc** [comment]
Right. I knew it exists but wasn't use the right keyword when searching. Now we just need to actually have it implemented.
