### ISSUE TITLE
Contracts: return `proof_size` with `ContractResult` from dry-runs

### ISSUE THREAD

**Issue by ascjones** [paritytech/substrate#12410]
Currently, in order to choose a value for `gas_limit` a UI would first dry-run the extrinsic via `state_call` and use the resulting [`ContractResult::gas_required`](https://github.com/paritytech/substrate/blob/37664fe5b3513eb996225f016eceaf74963b8133/frame/contracts/primitives/src/lib.rs#L36) as a parameter to the actual extrinsic.

Now that weights are two dimensional and also include `proof_size`, we should add that to the `ContractResult` in order for UIs to correctly populate that value, without having to manually supply a value.

Rel https://github.com/paritytech/subxt/pull/679

**Comment by burdges** [comment]
As an aside, actual runtimes could change since other transactions could impact Merkle proof CPU time, but not sure this impacts weight.  It won't change much usually though..

**Comment by athei** [comment]
Yes state can always change in-between and make the gas estimation stale. In practice it works well.
