### ISSUE TITLE
[pallet-assets] add asset_exists(id: AssetId) function

### ISSUE THREAD

**Issue by bernardoaraujor** [paritytech/substrate#12444]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

While working on an implementation of an Asset Registry for https://github.com/paritytech/trappist/issues/51, we needed to check whether an Asset exists.

We are currently doing the following, which feels a bit like a hack:
```
fn asset_exists(asset_id: AssetIdOf<T>) -> bool {
			!T::Assets::minimum_balance(asset_id).is_zero()
}
```

Ideally, `pallet-assets` should provide a function that does this, because it is basic functionality that is missing from the pallet.

**Comment by Doordashcon** [comment]
@bernardoaraujor who should ideally have the privilege of calling this function/extrinsic?

**Comment by joepetrowski** [comment]
Can you explain the context in which you are unable to do this?

For example, within FRAME, you can just use `Asset::<T, I>::contains_key(id)` ([example](https://github.com/paritytech/substrate/blob/a47f200/frame/assets/src/lib.rs#L513)).

`Asset` is also a [`pub` storage item](https://github.com/paritytech/substrate/blob/a47f200/frame/assets/src/lib.rs#L252), so any UI or tool using a library like Polkadot JS API should be able to read this and check if some key exists.

**Comment by bernardoaraujor** [comment]
This is coming from a [pallet](https://github.com/paritytech/trappist/tree/master/pallets/asset-registry) that has a loose-coupling with `pallet-assets`.

Correct me if I'm wrong, but as far as I could tell, I could only read `Asset` if I used tight coupling.

**Comment by joepetrowski** [comment]
I see, so you are looking for either a `pub fn asset_class_exists(id) -> bool;` function within [Inspect](https://github.com/paritytech/substrate/blob/0ba251c/frame/support/src/traits/tokens/fungible.rs#L36), or 

```rust
impl<T: Config<I>, I: 'static> Pallet<T, I> {
    pub fn asset_class_exists(id: T::AssetId) -> bool { }
}
```

within the Assets pallet? Seems like a good issue for @vieira-giulia to figure out. Also posting https://substrate.stackexchange.com/questions/922/pallet-loose-couplingtight-coupling-and-missing-traits for reference.

**Comment by bernardoaraujor** [comment]
yes... as long as it's accessible via loose coupling, it should be enough.

**Comment by dharjeezy** [comment]
I have gone ahead to open a PR for this  @joepetrowski  @bernardoaraujor since it has not been worked on for over a month

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-36/1529/1
