### ISSUE TITLE
registrar: Avoid freebies in `provide_judgement`

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#12460]
In `provide_judgement`, evaluate the return value of `repatriate_reserved` and do not store the judgement if it fails. The registrar will still have to pay the fees without getting any compensation but at least the user won't get a confirmed identity for free.

**Comment by dharjeezy** [comment]
I want to pick this up. @gavofyork @bkchr 
Meanwhile, should any specific error be thrown if the result coming from `repatriate_reserved` is an error?

**Comment by bkchr** [comment]
You probably want to introduce a new error variant, but nothing fancy.

**Comment by dharjeezy** [comment]
> You probably want to introduce a new error variant, but nothing fancy.

Alright. done
