### ISSUE TITLE
client/beefy: add some bounds on enqueued votes

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#12484]
When BEEFY voter runs behind rest of voters it will [enqueue gossiped votes](https://github.com/paritytech/substrate/blob/b324e511771b4e2d809d8319b98f3e36083c9ee2/client/beefy/src/worker.rs#L412) and process them as it catches up.

We should introduce some bounds on this queue to not grow forever if voter is stuck - we should instead drop votes once bounds are hit.

**Comment by dharjeezy** [comment]
@acatangiu I will like to work on this

**Comment by MrishoLukamba** [comment]
am working on it

**Comment by dharjeezy** [comment]
> am working on it

Oh... I already started @MrishoLukamba

**Comment by MrishoLukamba** [comment]
Okey continue

**Comment by acatangiu** [comment]
Yes, the approach is good and you should put bounds on both `pending_votes` and `pending_justifications`.

**Comment by acatangiu** [comment]
You should also bound inner vec in `pending_votes`, use `BoundedVec` or some simple custom vec wrapper for `BoundedBTreeMap<NumberFor<B>, BoundedVec<_, _>>`.

Bounds sizes should be smth in the order of a few MBs for each map - just define some constants, document them and we can fine tune the value as a final detail.

For the inner votes `Vec` it would be great to have some way to configure bound based on authority_set size (basically make it runtime configurable instead of hardcoded const).

When bounds are reached:
- votes can be dropped with a `warn!` log,
- justifications can be dropped with a `error!` log (in the future we might even decide to stop the voter with "fatal" error for dropping justifications, but for now let's start with logging errors).

**Comment by dharjeezy** [comment]
> You should also bound inner vec in `pending_votes`, use `BoundedVec` or some simple custom vec wrapper for `BoundedBTreeMap<NumberFor<B>, BoundedVec<_, _>>`.
> 
> Bounds sizes should be smth in the order of a few MBs for each map - just define some constants, document them and we can fine tune the value as a final detail.
> 
> For the inner votes `Vec` it would be great to have some way to configure bound based on authority_set size (basically make it runtime configurable instead of hardcoded const).
> 
> When bounds are reached:
> 
> * votes can be dropped with a `warn!` log,
> * justifications can be dropped with a `error!` log (in the future we might even decide to stop the voter with "fatal" error for dropping justifications, but for now let's start with logging errors).

Alright @acatangiu 
Will open a PR soon enough
