### ISSUE TITLE
Add max supply to Assets pallet.

### ISSUE THREAD

**Issue by Szegoo** [paritytech/substrate#12500]
Having a max supply could be useful when creating an asset. It should be something optional.
I thought of something like this: 

```rs
pub fn create(
	origin: OriginFor<T>,
	#[pallet::compact] id: T::AssetId,
	admin: AccountIdLookupOf<T>,
	min_balance: T::Balance,
        max_supply: Option<T::Balance>,
) -> DispatchResult {
```

The same would go for the `force_create`.

**Comment by Szegoo** [comment]
If this is confirmed I will open a PR for this.

**Comment by KiChjang** [comment]
How is max supply different from the concept of total supply?

**Comment by Szegoo** [comment]
> How is max supply different from the concept of total supply?

Total supply is something that changes when we call the mint function. Max supply is a constant that is set during the creation of the asset(it is specified by the caller). Max supply is always equal to or greater than the total supply. This could limit how many tokens could someone mint.

**Comment by KiChjang** [comment]
In practice, if max supply needs to be respected, we'd just disable the mint functionality, and total supply would just be equivalent to max supply. I don't see the reason to add another storage item just for this.

**Comment by Szegoo** [comment]
That could be an approach to this, but I believe that in some situations we don't want all of the max supply to be created. By setting a max supply we would limit how much can be minted, but the total supply may never actually reach max supply.

**Comment by KiChjang** [comment]
It is very crucially important for you to understand that storing data on blockchain isn't free. If you can't articulate what "some situations" are concretely, then we will not add such a field to bloat the size of the DB unnecessarily. I suggest that you actually go and investigate around parachains to see whether there's such a need, under what circumstances do they need it, and how this new field can alleviate their issue (or enable more functionality).

**Comment by Szegoo** [comment]
@KiChjang In the previous comment I was just trying to note that there might be a situation where we might have a max supply without ever reaching it. I am very well aware that storing information on blockchain isn't cheap. In this issue I was just giving off an idea to see whether it would be worth implementing to the assets pallet. If you believe that there wouldn't be any scenario where this would be useful I will close this issue.

**Comment by KiChjang** [comment]
Sorry, but you are presenting this idea to us. You are supposed to elaborate on your use case, not the other way around.

I have already told you what the best path for you to proceed. We are simply not going to implement something that does not add value until it is demonstrated.
