### ISSUE TITLE
pallet-mmr: gate MMR offchain canonicalization behind `--enable-offchain-indexing=true`

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#12531]
`pallet-mmr`
1. uses `sp_io::offchain_index` API to save full MMR leaves content to offchain db,
2. it also defines an `offchain_worker()` fn that does canonicalization of data in offchain db.

**Issue**
When `--enable-offchain-indexing=true` is not set, (1) doesn't write anything to offchain db, while (2) keeps on spamming error logs on failures to do canonicalization.

**Proposed solution**
Also move (2) under the `--enable-offchain-indexing=true` flag so it only runs when actually useful.

**Comment by GuruKathryn** [comment]
Thank you for posting this! We have been suffering under this issue for a while. Would love to see it fixed.

**Comment by acatangiu** [comment]
Thanks for reporting the issue!

**Comment by acatangiu** [comment]
This will be fixed by implementing https://github.com/paritytech/substrate/issues/12508

**Comment by GuruKathryn** [comment]
Awesome! 🎉

**Comment by acatangiu** [comment]
temporary workarounds (while waiting for the fix) here: https://substrate.stackexchange.com/a/5432

**Comment by acatangiu** [comment]
fixed by https://github.com/paritytech/substrate/pull/12753
