### ISSUE TITLE
Introduce `DefensiveMin` and `DefensiveMax`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#12550]
Add traits to run min/max operations defensively. In some cases we use min/max but do not expect the else case to trigger. These traits would help with finding if these cases actually ever trigger.

>Was discussing it with Ank4n: can you add a `defensive_min()` and `defensive_max` as well? I think there are a LOT of use cases where we do these operations defensively.

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/issues/12515#issuecomment-1283925928_

trait `DefensiveMin`:
- fn `defensive_min` by using `<=`
- fn `defensive_strict_min` by using `<`

trait `DefensiveMax`:
- fn `defensive_max` by using `>=`
- fn `defensive_strict_max` by using `>`

**Comment by dharjeezy** [comment]
I want to pick this up @ggwpez 
Can you give me an example of how this can be used like this example [here](https://github.com/paritytech/substrate/pull/12515/files#diff-a66e1f9bb70b6a5516c58534be76d45cf3339c5a56df4534ebfda632afb63bccR384)

**Comment by ggwpez** [comment]
Example being something like:  
```rust
assert_eq!(10, 10_u32.defensive_min(11_u32)); // works
assert_eq!(10, 11_u32.defensive_min(10_u32)); // panics in tests
```
That is at-least how I imaging it. Should be possible in Rust hopefully.
