### ISSUE TITLE
Mismatch between the specification and the implementation (Substrate)

### ISSUE THREAD

**Issue by radkomih** [paritytech/substrate#12564]
Hi there,
While I was trying to implement the `Core_version` conforming to the specification (I don't use Substrate), I noticed that it was producing a bit different SCALE encoded result compared to the one compiled from Substrate. According to the [spec](https://spec.polkadot.network/#defn-rt-core-version), the `state_version` should be a 32-bit unsigned integer, but I see that the implementation (Substrate) uses an 8-bit unsigned integer. Maybe, this is due to the fact there is only one implementation of the specification (Substrate), but which one should be the correct type to use?
Thanks!

**Comment by bkchr** [comment]
Please open an issue in the spec repo. The `state_version` should be an `u8` and not `u32`. Going to close this as the spec is wrong ;)
