### ISSUE TITLE
[pallet_collective] Usage of `Vec` instead of `BoundedVec`

### ISSUE THREAD

**Issue by Chralt98** [paritytech/substrate#12574]
I found an instance, where other pallets are using a `BoundedVec`, but `pallet_collective` does not.

https://github.com/paritytech/substrate/blob/6195ef41946017ec860d2d8ad58f9bc18b5797bf/frame/collective/src/lib.rs#L221

**Comment by dharjeezy** [comment]
I will like to take this issue up and fix. @Chralt98

**Comment by ggwpez** [comment]
The pallet bounding is ongoing here https://github.com/paritytech/substrate/issues/8629  
In this case it is in the genesis config and therefore not a problem anyway.
