### ISSUE TITLE
rename `#[runtime_interface]` to `#[host_function]`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12592]
I think it is really self-explanatory. It is a macro that is defining a host function. period.

**Comment by bkchr** [comment]
I'm against this. I choose the name as counterpart of `runtime-api`. The macro provides you the interface to program your runtime against. As part of this process it also generates the host functions.

**Comment by kianenigma** [comment]
How is "api" and "interface" counterpart of one another? 

This has been a point of confusion for students and those wanting to learn substrate. 

I agree that perhaps we can leave the macro. But we need some docs that explain host functions, externalities, and these macros from a FRAME developer PoV. the current naming and lack of explanation is a bit confusing.

This can be done in the docs, but I suggest revamping the sp-io crate docs and cater for this.

**Comment by bkchr** [comment]
I see it the following way:

- "runtime api": This is the api the runtime provides to the outside. When you want to call something in the runtime, you need to provide an api. This api can then be called from the host side.
- "runtime interface": When writing your runtime, you need to develop it against some kind of interface. This interface is provided by `runtime-interface` macro. With this interface you get access to the host side. 

So, the main difference is that "api == host -> runtime" and "interface == runtime -> host". 



> I agree that perhaps we can leave the macro. But we need some docs that explain host functions, externalities, and these macros from a FRAME developer PoV. the current naming and lack of explanation is a bit confusing.

https://docs.rs/sp-runtime-interface/latest/sp_runtime_interface/ have you read the docs here and especially of the macro. If yes, please tell me exactly what is missing and I extend the documentation.

**Comment by kianenigma** [comment]
You win basti :D.
