### ISSUE TITLE
`sync::syncs_header_only_forks` test is flaky

### ISSUE THREAD

**Issue by altonen** [paritytech/substrate#12607]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

There is a bug somewhere in the code which causes this test to freeze randomly. Bisecting doesn't help beyond a certain point because some of the history doesn't build (e.g., the commit that introduced this test) but this has been an issue since at least commit `66ff3a566e6ee7d85f30fc11d45047bd41854b9e`. The code really seems to be stuck as opposed to just polling and waiting for, e.g., a missing block.

### Steps to reproduce

I found this most reproducible when running in a virtual terminal and with debug logging enabled for `sync` target, happens maybe every 5th run.

`for i in {1..100}; do RUST_LOG=sync=debug cargo test --release sync::syncs_header_only_forks; done`

**Comment by ggwpez** [comment]
Huh cannot reproduce. Even with `taskset -c 0` to just run it on one CPU. Maybe my PC is too fast :stuck_out_tongue: ?  
Anyway, added it to the ever-growing list of flaky tests https://github.com/paritytech/substrate/issues/11321 …
