### ISSUE TITLE
Feature Request: Local multicast reserved peer discovery

### ISSUE THREAD

**Issue by senseless** [paritytech/substrate#12601]
**Context:**
We're working on deploying public RPC services for all relay networks and common goods parachains. In an attempt to reduce our overall bandwidth consumption we've begun deploying --reserved-nodes flag with a reduction for in/out peers per node. We were able to successfully reduce our average bandwidth utilization from 10Mbit/s to 3Mbit/s per node a 70% decrease in bandwidth utilization. 

**Problem:**
Attempting to maintain these reserved nodes list on a per-node basis does not scale well even with ansible or similar automation taking care of some of the tasks. If we add a new node to the network **we have to restart every node on the network** for them to start communicating with the new peer.

**Solution:**
What would be ideal is to make use of multicast in a many-to-many configuration for local peer discovery. We vision a system where you would start the node with a --multicast-reserved flag. This would enable multicast and make multicast discovered peers considered as 'reserved peers' (meaning, these nodes are added in addition to any other peers from normal peer discovery methods and do not count against in/out peers). When a node is discovered, the node's type kusama, polkadot, etc is determined (ideally sent in the multicast datagram) and connections with appropriate / similar systems are maintained. Each node should send regular interval (10-60 seconds) multicast discovery packets. The nodes would still use existing unicast systems to communicate and transfer data, this is purely for node discovery not for any sort of data transmission. 

The result is that we can reduce the number of --in-peers and --out-peers per node and rely on the multicast system for our local nodes to find and begin communicating with each other without massive unmaintainable reserved-nodes lists. We would have a local network that is in aggregate better connected than a single node with a higher in/out peers count and just as easy to maintain. The reduction in bandwidth will allow us to have lower costs and charges associated with our public rpc services. 

You can see the following RFCs for information about multicast and software inclusion:
https://datatracker.ietf.org/doc/html/rfc1112
https://datatracker.ietf.org/doc/html/rfc3170

The existing mdns system would probably work with appropriate igmp implementation to span multiple subnets as long as it was bi-directional and all peers consider each other reserved. 

**Note:**
This will make it much easier for operators to launch sentinel protected nodes by enabling this feature and setting their in/out peers to 0. A backend "protected" node would then only communicate with local nodes and it would be up to those other local nodes to provide connectivity to the protected node.

**Comment by dcolley** [comment]
For some context - this network will host public RPC servers.

The api call is documented here: https://polkadot.js.org/docs/substrate/rpc#addreservedpeerpeer-text-text
addReservedPeer is not authenticated. If the RPC external is enabled, it can be spammed.

I was able to add a peer to my own server with polkadot.js
![image](https://user-images.githubusercontent.com/1845970/199471117-6ecd14da-128d-428d-8056-3fdb5c0f1ea6.png)

For this node I have enable unsafe as it's an internal network
```
  --unsafe-rpc-external \
  --rpc-methods=Unsafe \
```

For parity `rpc=wss://kusama-rpc.polkadot.io`, it failed
![image](https://user-images.githubusercontent.com/1845970/199471797-24a05f4c-ea33-45b4-91d2-c06cb9b838c4.png)

So, we could script the `addReservedPeer` from localhost on the node

**Comment by senseless** [comment]
It should be doable with ansible and some simple scripting on the host. I didn't realize that RPC call was there. If it's too complex of a change, don't worry about it, we can proceed with the ansible + rpc solution. 

Thanks @rphmeier @dcolley

**Comment by rphmeier** [comment]
@senseless @dcolley - great to hear that the RPC approach works well enough. I will close this issue now as 'wontfix', simply because the code changes are so involved & introduce a large maintenance burden. Please don't hesitate to open a new issue if there are improvements to the RPC layer that can be introduced to make peer-set management easier from external processes.

**Comment by ehsanhajian** [comment]
I think you're talking about one datacenter. because for multicast support, igmp protocol needs to be enabled on all network devices. in addition to that, the security concerns for igmp is very high. if someone spoof your multicast IP or if someone send igmp flooding, that would be terrible to manage. igmp protocol maybe good for a managed network but it's very risky.
