### ISSUE TITLE
facility to fetch fastUnstake.reseve 

### ISSUE THREAD

**Issue by Nick-1979** [paritytech/substrate#12618]
If an account wants to do a successful registration for **fastUnstake**, the following conditions needs to be meet:

1- the account has some fund staked and not being exposed in the last "erasToCheckPerBlock"
2- the account needs to have enough funds to be **reserved**, that will be slashed if the first condition was not met.

The erasToCheckPerBlock can be fetched via _api.query.fastUnstake.erasToCheckPerBlock_, but there is no way to fetch the reserved amount before submitting the transaction and the account may face the following error: https://westend.subscan.io/extrinsic/13147898-2

**Comment by kianenigma** [comment]
@ruseinov cc

**Comment by kianenigma** [comment]
The fix is simply to put a `#[pallet::constant]` on top of `type Deposit: Get<_>`.
