### ISSUE TITLE
Allow vested funds to be staked via nomination pools

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12617]
Currently, vested funds cannot be staked. 

Since we have vested transfer, it should be possible to move the vested fund to the pool, and stake it.

Ideally, we want vested funds to be stake-able similar to direct staking. 

Although, this is not super critical as vesting funds were mainly used for initial sales of DOT and are mostly done by now.

I am not 100% sure if this possible, ergo unconfirmed.

**Comment by kianenigma** [comment]
Okay, some thoughts on this: 

vesting works off the basis of locks. locks prevent us from transferring funds from the user account to the pool account, which we absolutely have to do.

One option would to to keep the funds in the user account, and mint fake tokens in the pool side. but this is tricky because we have to make sure that the funds that are locked in pools cannot be reused in the native staking system. Perhaps we could reserve the funds (using named-reserves) and then mint some fake tokens on the pool side, but this is still hacky. With all such approaches, slashing would be quite difficult to get right. 

Alternatively, we can `force_transfer` the funds out of the user account into the pool, and keep their vesting schedule. There nothing wrong with having a vesting lock on your account that is decreasing e.g. from 50 DOTs, while you have 0 DOTs. once you get e.g. 80 DOTs back sometime in the future, 50 of them would still be subject to vesting.

**Comment by kianenigma** [comment]
Here's a draft of a stupid, but possibly viable approach: 

```diff
diff --git a/frame/nomination-pools/src/lib.rs b/frame/nomination-pools/src/lib.rs
index 3661a7f70b..e3b3c65058 100644
--- a/frame/nomination-pools/src/lib.rs
+++ b/frame/nomination-pools/src/lib.rs
@@ -875,7 +875,7 @@ impl<T: Config> BondedPool<T> {
 	) -> Result<BalanceOf<T>, DispatchError> {
 		// Cache the value
 		let bonded_account = self.bonded_account();
-		T::Currency::transfer(
+		Pallet::<T>::transfer_ignore_vesting(
 			&who,
 			&bonded_account,
 			amount,
@@ -1131,7 +1131,7 @@ impl<T: Config> Get<u32> for TotalUnbondingPools<T> {
 #[frame_support::pallet]
 pub mod pallet {
 	use super::*;
-	use frame_support::traits::StorageVersion;
+	use frame_support::{traits::{StorageVersion, LockableCurrency}, PalletId};
 	use frame_system::{ensure_signed, pallet_prelude::*};
 
 	/// The current storage version.
@@ -1153,6 +1153,8 @@ pub mod pallet {
 		/// The nominating balance.
 		type Currency: Currency<Self::AccountId>;
 
+		type VestingSchedule: frame_support::traits::VestingSchedule<Self::AccountId>;
+
 		/// The type that is used for reward counter.
 		///
 		/// The arithmetic of the reward counter might saturate based on the size of the
@@ -2104,6 +2106,25 @@ pub mod pallet {
 }
 
 impl<T: Config> Pallet<T> {
+	/// Transfer funds from a member wishing th join an account (upon [`Call::join`] or
+	/// [`Call::create`]) to the bonded account of the given pool.
+	///
+	/// This is just like a normal transfer, but will temporarily disable the lock associated with
+	/// vesting, and set it back in.
+	fn transfer_ignore_vesting(
+		from: &T::AccountId,
+		to: &T::AccountId,
+		amount: BalanceOf<T>,
+		req: ExistenceRequirement,
+	) -> DispatchResult {
+		use frame_support::traits::VestingSchedule;
+		let s = T::VestingSchedule::get_schedules(&from);
+		let res = T::Currency::transfer(&from, &to, amount, req);
+		// NOTE: event if the transfer fails, revert the schedule. Perhaps we can actually open a new transaction layer here.
+		T::VestingSchedule::set_schedules(&from, s);
+		res
+	}
+
 	/// Returns the pending rewards for the specified `member_account`.
 	///
 	/// In the case of error, `None` is returned.
diff --git a/frame/support/src/traits/tokens/currency/lockable.rs b/frame/support/src/traits/tokens/currency/lockable.rs
index a10edd6e3e..e16558d32c 100644
--- a/frame/support/src/traits/tokens/currency/lockable.rs
+++ b/frame/support/src/traits/tokens/currency/lockable.rs
@@ -73,6 +73,8 @@ pub trait VestingSchedule<AccountId> {
 	/// The currency that this schedule applies to.
 	type Currency: Currency<AccountId>;
 
+	type BlockNumber;
+
 	/// Get the amount that is currently being vested and cannot be transferred out of this account.
 	/// Returns `None` if the account has no vesting schedule.
 	fn vesting_balance(who: &AccountId)
@@ -105,4 +107,21 @@ pub trait VestingSchedule<AccountId> {
 	///
 	/// NOTE: This doesn't alter the free balance of the account.
 	fn remove_vesting_schedule(who: &AccountId, schedule_index: u32) -> DispatchResult;
+
+	fn get_schedules(
+		who: &AccountId,
+	) -> Vec<(
+		<Self::Currency as Currency<AccountId>>::Balance,
+		<Self::Currency as Currency<AccountId>>::Balance,
+		Self::BlockNumber,
+	)>;
+
+	fn set_schedules(
+		who: &AccountId,
+		schedules: Vec<(
+			<Self::Currency as Currency<AccountId>>::Balance,
+			<Self::Currency as Currency<AccountId>>::Balance,
+			Self::BlockNumber,
+		)>,
+	);
 }
```

**Comment by Szegoo** [comment]
This looks like an interesting issue to work on. @kianenigma are you working on this? If not I would like to give this a try.

**Comment by kianenigma** [comment]
I am discussing it with Polkadot auditors if this is reasonable, let me come back to you :)

**Comment by kianenigma** [comment]
A total of 800 accounts in Polkadot have vesting schedule, not so significant.

**Comment by Szegoo** [comment]
@kianenigma Do you think this feature would be used then? Or do you think this shouldn't be implemented?

**Comment by kianenigma** [comment]
This cannot work as I suggested. If multiple vested transfers are made into your account, and you already move parts of your vested funds to a nomination pool, then you are essentially delaying the release of the second vested schedule.
