### ISSUE TITLE
Substrate always attempts to finalize the parent of a finalized block, even if it's already finalized

### ISSUE THREAD

**Issue by kayabaNerve** [paritytech/substrate#12614]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

https://github.com/paritytech/substrate/blob/564cdeb9026a556133cab6ff20a6f7426e24b38e/client/service/src/client/client.rs#L657-L667 is run regardless of the parent's status.

This is in-consequential as the finalization function will simply return in this case, yet it does so printing a warning: https://github.com/paritytech/substrate/blob/564cdeb9026a556133cab6ff20a6f7426e24b38e/client/service/src/client/client.rs#L847-L853

As someone who is only importing finalized blocks, and finalizing every block, I'm forced to endure such errors regardless of not having any safety violation as I'm not the one attempting to finalize the same block multiple times.

### Steps to reproduce

- Have block A be imported and finalized
- Import block B with justifications

Alternatively, the cluster-sm profile of https://github.com/serai-dex/serai/tree/tendermint/deploy can be run to see this happen in real time. While I was worried this was my fault, as I'm working on a Tendermint implementation, a patch to my Substrate tree confirmed this corrected the behavior.

**Comment by davxy** [comment]
Fixed by https://github.com/paritytech/substrate/pull/12653
