### ISSUE TITLE
bug in the process of upgrading parathreads

### ISSUE THREAD

**Issue by decentration** [paritytech/substrate#12650]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Blockage alert!!

It seems the subport issues are not being checked currently. Please upgrade 2113 (to a permanent slot) as soon as possible. 

We are waiting for the parathread to be upgraded back into a parachain (7 days waiting).

We are working with other chains (Karura and OAK) through collaboration over xcm but have been blocked since the slot lease expired. 

https://github.com/paritytech/subport/issues/488

**Comment by bkchr** [comment]
No need to open an issue here, because that doesn't help. I messaged @al3mart on element.

**Comment by al3mart** [comment]
Taken care of it just now
