### ISSUE TITLE
FEPS weights not updated by script

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#12660]
No idea why #12325 did not update the weights for the [election-provider-support](https://github.com/paritytech/substrate/blob/82b538e3ae6e035b39a3ac8f069c9fb06757b6ac/frame/election-provider-support/src/weights.rs#L29) but should be fixed.

**Comment by bkchr** [comment]
Duplicate of https://github.com/paritytech/substrate/issues/12652

**Comment by ggwpez** [comment]
> Duplicate of #12652

That issue is for `pallet-election-provider-multi-phase` but this issue is for `frame-election-provider-support`.

**Comment by ggwpez** [comment]
I guess we can use the linked issue for both, will edit it.
