### ISSUE TITLE
Crate `array-bytes` adds GPL 3.0 license dependency to `sp-core`

### ISSUE THREAD

**Issue by haerdib** [paritytech/substrate#12689]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

[sp-core](https://github.com/paritytech/substrate/blob/2badd7203b915ae80499544056b3dc5496ccd80e/primitives/core/Cargo.toml), licensed under [Apache 2.0](https://github.com/paritytech/substrate/blob/master/LICENSE-APACHE2), adds a GPL 3.0 license by depending on [array-bytes](https://github.com/hack-ink/array-bytes).

To the best of my knowledge (not a lawyer) this violates the GLP 3.0 license.

### Steps to reproduce

Noticed this while trying to add a license check to our Apache 2.0 licensed project (https://github.com/scs/substrate-api-client/actions/runs/3443791729/jobs/5745700596)

**Comment by AurevoirXavier** [comment]
I'll consider changing array-bytes's license to Apache 2.0.

**Comment by bkchr** [comment]
@AurevoirXavier would be nice if you could do this! Maybe dual licensing also works, but I'm no lawyer :P

**Comment by AurevoirXavier** [comment]
- https://github.com/hack-ink/array-bytes/pull/22

Maybe a dual license for Apache x GPL is meaningless.

But I did release the restriction.

Anyway, you could use it under Apache-2.0 now.

**Comment by haerdib** [comment]
Awesome. Thank you very much for the quick reaction !

**Comment by AurevoirXavier** [comment]
So, I think this could be closed now.

**Comment by haerdib** [comment]
It's not closed on my end yet, because substrate still depends on the GPL version of array-bytes. A dependency bump will solve it.

**Comment by AurevoirXavier** [comment]
> It's not closed on my end yet, because substrate still depends on the GPL version of array-bytes. A dependency bump will solve it.

It looks like that I need to release a new version.

**Comment by haerdib** [comment]
Closing this, as `array-bytes` has been bumped to [v4.2.0](https://github.com/hack-ink/array-bytes/tree/v4.2.0) which includes the Apache 2.0 licence.

https://github.com/paritytech/substrate/blob/ad58606c403e13cb1819174ec311d82a02e40028/Cargo.lock#L194-L198
