### ISSUE TITLE
pallet-mmr: could not prune: no entry in pruning map for block

### ISSUE THREAD

**Issue by sandreim** [paritytech/substrate#12726]
```
Could not canonicalize elem at pos 73901 using key [12, 109, 109, 114, 173, 32, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 
```

I'm see a lot of these errors on Versi nodes after upgrading to a PR in which I merged recent master. 

CC @acatangiu

**Comment by acatangiu** [comment]
thanks for the report! this is being already tracked in https://github.com/paritytech/substrate/issues/12531 (and will come in with https://github.com/paritytech/substrate/issues/12508)
