### ISSUE TITLE
store `min-active-bond` onchain

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#12746]
two options: 

1. when snapshot is being created, store the minimum voter. Either in EPM or in Staking side.
2. when `collect_exposure`, track a map of all nominators, their stake, at the end, take the min.

Option 1 makes a whole lot more sense, so this should be in `impl ElectionDataProvider for Staking`, in the `fn get_npos_voters()`.

**Comment by kianenigma** [comment]
This will be almost zero cost for the chain, and it will be great for UIs.

**Comment by gpestana** [comment]
I took over this issue since no one did it, hopefully it's an easy and quick one.
