### ISSUE TITLE
Add ensure_ops methods (as checked_ops but returning ArithmeticError instead)

### ISSUE THREAD

**Issue by lemunozm** [paritytech/substrate#12754]
Hi! Because of the high safety standards needed in these contexts, mathematical operations tend to be made using the checked version. The checked version follows the same pattern in most cases:

```rust
a.checked_<operation>(b).ok_or(ArithmeticError::<Variant>)?
```

This has two issues:
- Your algorithm becomes more difficult to read. When the code tends to be mathematical, readability is even more important. If it's difficult to read, it's very easy to have human errors and it makes auditories more difficult to do.
- The concrete `ArithmeticError` returned is not easy to know. Depending on the value, it can differ. For example, `a - b`, could give `Underflow`, but also `Overflow` if `b` is a huge negative value.

In our parachain we've resolved both issues by creating an `ensure_<operation>` method family that reduces the code boilerplate and returns the correct `ArithmeticError` instead of an `Option`. The previous line could be rewritten in a more readable way:

```rust
a.ensure_<operation>(b)?
```

I think this can be useful for many other projects, so my intention is to move our [`ensure`](https://github.com/centrifuge/centrifuge-chain/blob/main/libs/traits/src/ops.rs#L47) module (docs [here](https://reference.centrifuge.io/cfg_traits/ops/ensure/index.html)) to `sp_runtime::traits::ensure` or any better place you recommend if you agree on this addition.

Thanks!

**Comment by bkchr** [comment]
Sounds reasonable to me.

WDYT @kianenigma?

**Comment by lemunozm** [comment]
Hi @bkchr, @kianenigma, any updates about it?

**Comment by ggwpez** [comment]
Idea looks good, but no update until someone wants to work on it :stuck_out_tongue:

**Comment by bkchr** [comment]
Yes! @lemunozm can you provide some pr?

**Comment by lemunozm** [comment]
Sure! I'll do it soon

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-37/1736/1
