### ISSUE TITLE
PoV Limit Pallet

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#12772]
As discussed in https://forum.polkadot.network/t/push-kusama-limits-with-pov-weight-limit-system-parachains/1068, we could write a pallet whose `on_initialize` would consume up to the weight limit of the block (or some percentage as a config parameter). For parachains with PoV and execution time limits, this could roughly look like:

1. Call(s) to `system.set_storage` that will consume the PoV size,
2. Some `for` loop performing arbitrary computation like hashing values to consume any remaining time limit.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/push-kusama-limits-with-pov-weight-limit-system-parachains/1068/7

**Comment by burdges** [comment]
Argon2 is good if you need to hit ram lots, but you may need to hit storage really.

**Comment by kianenigma** [comment]
cc @Szegoo ;) ?

**Comment by Szegoo** [comment]
@kianenigma I would like to tackle this issue if it is not something urgent since I am a bit sick at the moment :/

**Comment by sandreim** [comment]
I think the pallet approach is better than what we have already built as a test parachain for ZombieNet tests: https://github.com/paritytech/polkadot/blob/master/parachain/test-parachains/undying/collator/src/cli.rs#L67

We're planning to deploy it soon on Versi to test the limits when parachains actually do something.

**Comment by Szegoo** [comment]
@burdges If we were to use Argon2 we would need a new dependency(e.g. https://docs.rs/rust-argon2/latest/argon2/), would that be ok?

**Comment by burdges** [comment]
Yeah why not?  You can use any memory hard hash function, but they'd all bring an external dependency, and this is all testing so who cares about the dependencies anyways?  You're not adding a host call, just building it in WASM.

We'll need to do something else when you want to hit storage lots.

**Comment by ggwpez** [comment]
We need to benchmark two things: Runtime Storage access to inflate the PoV and Computation time.  
There is no need for special case hash functions. We can just use blake2 or whatever for the Compute time and use `storage::unhashed::get` to inflate the PoV.

**Comment by joepetrowski** [comment]
> @joepetrowski Now that the Glutton pallet has been merged what are the further plans? I assume the work on the Glutton parachains will continue on the Cumulus repository, but I couldn't find any PRs over there so I was wondering if there is some work being done regarding this at the moment.

Yes, the future plans are to make a new parachain runtime and deploy to Kusama. I am planning to open a PR (although you are welcome to :)), but am currently waiting for the dust to settle on (a) upgrading current system para XCM configs/tests to XCM v3 and (b) move of runtimes to the Polkadot Fellowship control.

Once we release a runtime then I will make a referendum on Kusama to register the first glutton parachain.

**Comment by Szegoo** [comment]
> although you are welcome to :)

Sure, I would like to write the Glutton parachain runtime :)

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-39/2277/1
