### ISSUE TITLE
[Feature request] support mock or generate private key on bechmarking and testing environment

### ISSUE THREAD

**Issue by jasl** [paritytech/substrate#12779]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

This is not bug report.

I have searched StackExchange, I see there're people also ask the similar question, e.g. https://substrate.stackexchange.com/questions/5061/access-to-ecdsa-sign-inside-runtime

I also found [NFTs 2.0 Roadmap](https://github.com/paritytech/substrate/pull/12765) that planning "offchain signatures support for nfts distribution or attributes change" should be the same scenario.

I'm working on a feature that using "offchain signatures" tech, user will submit a struct and a signiture signed by its private key, the extrinsic will use public key to verify it.

The struct contains timestamp, and extrinsic will validate it, so on benchmark or test, it's good to generate instead of mock.

So the problem is there's no way to use private key on benchmark or test, my current workaround is disable timestamp validation on those environments and mock the payload and signature.

**Comment by bkchr** [comment]
You can already generate private keys for benchmarking:
https://github.com/paritytech/substrate/blob/d1221692968b8bc62d6eab9d10cb6b5bf38c5dc2/frame/im-online/src/benchmarking.rs#L46-L48

The same also works from an offchain context.

They are using [`RuntimePublic`](https://github.com/paritytech/substrate/blob/d1221692968b8bc62d6eab9d10cb6b5bf38c5dc2/primitives/application-crypto/src/traits.rs#L94-L123) trait.

**Comment by bkchr** [comment]
I basically have given the same answer on stackexchange :P

**Comment by jasl** [comment]
hmmm... I'll try
Thank you
