### ISSUE TITLE
Cannot handle genesis json file created with different runtime

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1277]
I have created a custom substrate node with a test module, and use `build-spec` command to generate genesis json file, which contains a `test` section for the test module config. This genesis json file works fine with my custom substrate node however doesn't work with the official substrate node with error

> Error: Error parsing spec file: unknown field `test`, expected one of `system`, `timestamp`, `consensus`, `balances`, `session`, `staking`, `democracy`, `councilVoting`, `councilSeats`, `grandpa`, `treasury`, `contract`, `upgradeKey` at line 162 column 10

I would like to have the ability for people to join my chain using the official substrate client, but with this constraint, it means I cannot have configs for my modules.

**Comment by bkchr** [comment]
Okay, I looked into the code and I'm not 100% sure if this is a bug. @arkpar you implemented this in https://github.com/paritytech/substrate/pull/229/files#diff-f93e665ccf536c4085d60ccbabbd225aR235.
`#[serde(deny_unknown_fields)]` is probably the attribute that is responsible for make the de-serialization fail.
Should we change this or is this done by intention?

**Comment by arkpar** [comment]
@xlc use `build-spec --raw`. This way the spec will contain raw storage values instead of the runtime config and can be used by the substrate node.
