### ISSUE TITLE
Add `MaxEncodedLen` to `trait Parameter`

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#12773]
https://github.com/paritytech/substrate/blob/bac8e731ddf8d39a443741ff064fe7a6ad7b6602/frame/support/src/dispatch.rs#L93-L94

So we can avoid specify `MaxEncodedLen` in all the assosicated types.

**Comment by ggwpez** [comment]
We discussed this over here https://github.com/paritytech/substrate/issues/11549#issuecomment-1271662596
