### ISSUE TITLE
Reserved Nodes are no longer inclusive of in/out peer restrictions

### ISSUE THREAD

**Issue by notlesh** [paritytech/substrate#12799]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

A recent client change introduced a change in behavior where the set of `--reserved-nodes` is not counted against `--in-peers` or `--out-peers`. Previously this was counted against `--out-peers` in most (all?) cases.

Example:
```
in: 1
out: 5
num reserved: 4

behavior before: node will make up to 6 peer connections.
behavior after: node will make up to 10 peer connections.
```

This graph depicts the behavior before and after:

![image](https://user-images.githubusercontent.com/2967426/204349368-7aa37af1-f34f-4a08-919a-2743a7e2a979.png)

This may relate to the GRANDPA protocol; this graph shows a similar before-and-after with number of GRANDPA messages:

![image](https://user-images.githubusercontent.com/2967426/204349771-8d5f825a-7bb3-497d-b295-0d341ca5599b.png)

Note that this may be the desired behavior. If so, it should probably apply to all p2p and be documented.

Perhaps related: #12797

### Steps to reproduce

Compare moonbeam client `<= v0.26.1` vs `>= v0.27.0` with a configuration of both reserved and in/out peers and observe the difference in the total number of peer connections the client will maintain.

**Comment by altonen** [comment]
Probably related to this: https://github.com/paritytech/substrate/pull/11909 so it's desired behavior. I'll close this as resolved.

cc @dmitry-markin
