### ISSUE TITLE
BlockBuilder's "inherent_extrinsics" should tell you when a delay is required before authoring

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1281]
Then we could alter the `timestamp` API to do something like this:

```rust
let minimum = Self::now() + Self::block_period();
let timestamp = if provided_timestamp < minimum  {
    (Call::set(minimum), Some(Notification::ShouldWait(minimum - provided_timestamp)))
} else {
    (Call::set(provided_timestamp), None)
}
```

A `Proposer` calling `inherent_extrinsics` knows that the extrinsics received back are valid and that the returned delay should be waited before broadcasting.

**Comment by rphmeier** [comment]
After investigating further: the timestamp extrinsic is always set forward to the next valid maximum. This will probably be "good enough" assuming the slot durations are long enough for Aura.

**Comment by bkchr** [comment]
I think this can be closed.
