### ISSUE TITLE
Confusing blocks-pruning description

### ISSUE THREAD

**Issue by crystalin** [paritytech/substrate#12811]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

>  Default is to keep all finalized blocks. otherwise, all blocks can be kept (i.e 'archive'), or for all canonical blocks (i.e 'archive-canonical'), or for the last N blocks (i.e a number).
> 
> NOTE: only finalized blocks are subject for removal!

If only the finalized blocks are subject to removal, and all finalized blocks are canonical (maybe I'm wrong here?), what is the difference between parameter default (all finalized blocks) and `archive-canonical` ?

**Comment by lexnv** [comment]
Hi,

>  all finalized blocks are canonical (maybe I'm wrong here?)

The consensus engine may not revert a finalized block,
while the canonical block (theoretically) can be reverted.
Therefore, a finalized block also implies that the block is canonical
(but not necessarily the other way around).

> what is the difference between parameter default (all finalized blocks) and archive-canonical ?

The default option is `BlocksPruning::KeepFinalized` (see appendix section) which
is equivalent to the `archive-canonical` CLI flag.

The `BlocksPruning::KeepAll` is equivalent to the `archive` CLI flag.

The `archive-canonical` option implies that *ONLY* the finalized blocks are kept around
and displaced branches (blocks from forks) are eventually pruned (ie removed).

```
[block 0] -- [block 1 ] -- [block 2 ] -- [block 3]
         |
          -- [block 1'] -- [block 2']
```

In this example, when `block 3` is finalized, the displaced branch (the fork containing 1' and 2')
is pruned (presuming the node is started with `archive-canonical`).

> NOTE: only finalized blocks are subject for removal!

I'm not quite sure if this is right. I supposed that was true at some point and
we should update the documentation for this.

// CC @arkpar @cheme @bkchr 

As opposed to `archive` option that implies that *ALL* the blocks are kept around in the DB.





### Appendix

The `BlocksPruning` that you mention is defined in the `client/db` code:

https://github.com/paritytech/substrate/blob/54b7395a532df9b2fc79916b9f830d7300f0e216/client/db/src/lib.rs#L322-L331

The CLI exposes this option to end-users here:

https://github.com/paritytech/substrate/blob/54b7395a532df9b2fc79916b9f830d7300f0e216/client/cli/src/params/pruning_params.rs#L33-L42

While the user input flag is parsed here:
 
https://github.com/paritytech/substrate/blob/54b7395a532df9b2fc79916b9f830d7300f0e216/client/cli/src/params/pruning_params.rs#L66-L76

Then, here is where the pruning actually happens:

https://github.com/paritytech/substrate/blob/54b7395a532df9b2fc79916b9f830d7300f0e216/client/db/src/lib.rs#L1738-L1750

**Comment by crystalin** [comment]
Thank you for the clear explanation. I think the confusion came from the "NOTE: only finalized blocks are subject for removal!" which as you are suggesting might not be true anymore.

**Comment by cheme** [comment]
As I understand it, the note is here to underline that the pruning (when a pruning range is defined) is done against finalized the blocks in db, with range applying over the latest finalized block number.
But it should maybe say "within the finalized block number range" or something similar. 
But when using range pruning only canonical blocks are stored in state so it is not fundamentally false (only in archive mode we do prune forks in state).
