### ISSUE TITLE
Update Preimages API of pallet Whitelist

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#12821]
Instead of using 

```
type PreimageProvider: PreimageProvider<Self::Hash> + PreimageRecipient<Self::Hash>;
```

it should be

```
type PreimageProvider: QueryPreimage + StorePreimage;
```

When using `QueryPreimage::fetch(hash: &Hash, len: Option<u32>)`, make sure that `len` is `Some`! This will basically mean that `dispatch_whitelisted_call` will need to take an extra `len: u32` argument.

**Comment by muharem** [comment]
Solved in the PR https://github.com/paritytech/substrate/pull/12834
