### ISSUE TITLE
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

### ISSUE THREAD

**Issue by wetalice** [paritytech/substrate#12836]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

```
"flags": [
			  "--ws-external",
            "--rpc-external",
            "--rpc-methods=Unsafe",
            "--rpc-cors=all",
            "--",
            "--execution=wasm"
          ]
```
err:
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by nazar-pc** [comment]
There is nothing wrong with Substrate here, this is how Web works. And this indeed looks like a question to search/as question on StackOverflow.

**Comment by bkchr** [comment]
Yes, that is no Substrate issue. That is coming from your browser, nothing we can do about this.
