### ISSUE TITLE
Make wasm build script check for installed dependencies

### ISSUE THREAD

**Issue by gterzian** [paritytech/substrate#1285]
Currently, it seems that running `./scripts/build.sh` without having `wasm-gc` installed doesn't raise a warning, instead it appears as if the script ran succesfully. We should instead make it fail hard in case required dependencies haven't been installed.

**Comment by tomaka** [comment]
Seems to be fixed: https://github.com/paritytech/substrate/blob/33609c707a3bf7b1a520d639b7b1199dc77c0cff/core/utils/wasm-builder/src/prerequisites.rs#L30-L37
