### ISSUE TITLE
Scheduler cleanup

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#12851]
Scheduler should remove any trailing `None` items in agendas as items get removed.

A migration should do this for preexisting items.

**Comment by dharjeezy** [comment]
@gavofyork i will like to pick this up, So, are you saying the Agenda storage map should not store `BoundedVec<Option<ScheduledOf<T>>, T::MaxScheduledPerBlock>` anymore but store this instead
`BoundedVec<ScheduledOf<T>, T::MaxScheduledPerBlock>`?

**Comment by ggwpez** [comment]
Done in https://github.com/paritytech/substrate/pull/12989

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-37/1736/1
