### ISSUE TITLE
Enabling more flexibility on AccountData data-structure inside pallet balances

### ISSUE THREAD

**Issue by MrishoLukamba** [paritytech/substrate#12879]
`type AccountStore: StoredMap<Self::AccountId, AccountData<Self::Balance>>;`
At the moment if you want to extend or use different data structure is kinda painful. 
So what can we do to make it more flexible and not requiring for people to fork and maintain pallet-balances 
@Ank4n @kianenigma

**Comment by kianenigma** [comment]
This seems reasonable to me, but the downside is that it will be a slightly anooying change to downstream projects as they all have to add the new type config. 

End of the day though, it should be done, just need to make sure it is well documented.

**Comment by xlc** [comment]
I don't get it. Just store it in a different pallet? Like how system pallet does.

**Comment by kianenigma** [comment]
Thinking about this again, I am with @xlc that: 

1. If you want to change anything other than `frame_system::AccountInfo`, you need to use a new fork of the system pallet anyhow (I thought this was the intention and got more confused initially).
2. If you want to change the inner `AccountData` of `AccountInfo`, as noted, you can overwrite this in `frame_system::Config`, or use a new pallet that implements `StoredMap`.
