### ISSUE TITLE
Write solid docs on `decl_module`, `decl_storage` and `construct_runtime`

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1288]
Current docs are basic or non-existent. Docs should go on substrate.readme.io.

**Comment by shawntabrizi** [comment]
Construct runtime progress here: https://hackmd.io/s/HyvpYNAbN#

**Comment by gavofyork** [comment]
The definition of `Inherent` is muddled.

> The Inherent type is needed when your module defines an implementation of the ProvideInherent trait.
> 
> This custom implementation is needed whenever your runtime accepts inherent extrinsics to call your module’s functions. Because inherents are generated by the external world, you should verify that the extrinsics satisfies some fundamental conditions.
> 
> For example, in the Timestamp module, an inherent call is used to set the timestamp for a given block. However, before the set() function executes, we confirm that the proposed time is within an acceptable range of the previous block.

`InherentData` is ferried from the external world by the client. It gets transformed into zero or more `Inherent` extrinsics by the module. These extrinsics are executed similarly to all other extrinsics.

I updated the text to be correct.

**Comment by shawntabrizi** [comment]
Progress on `decl_macro!`:
https://hackmd.io/5DwOW4qLScicUkBYtnO5uQ

**Comment by shawntabrizi** [comment]
These docs now exist, but not quite consistently:
- `decl_module!` - https://docs.substrate.dev/docs/decl_module
- `construct_runtime!` - https://docs.substrate.dev/docs/construct_runtime
- `decl_storage!` - https://crates.parity.io/srml_support_procedural/macro.decl_storage.html

We need to:
* Move information from Readme into the code as reference level documentation
* Decide if we want high level documentation about the Macros on Readme at all

These items can be tracked here:
https://github.com/paritytech/substrate-developer-hub/issues/61
