### ISSUE TITLE
client/beefy: add more metrics for production visibility

### ISSUE THREAD

**Issue by acatangiu** [paritytech/substrate#12893]
We should have metrics for the BEEFY voter for most "error" cases where we currently only log `debug!` - logging debug is correct as these are not actual errors but more like "abnormal events" - which we definitely want to see somewhere -> metrics!

Non-exhaustive list:

- [ ] [voting - trying to vote with no session initialized](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/worker.rs#L230)
- [ ] [voting - no authority public key found in store](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/worker.rs#L408)
- [ ] [voting - buffered votes](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/worker.rs#L493)
- [ ] [voting - votes buffer full](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/worker.rs#L501)
- [ ] [voting - buffered justifications](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/worker.rs#L526)
- [ ] [voting - justifications buffer full](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/worker.rs#L531)
- [ ] [voting - trying to set best beefy to old block ](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/worker.rs#L638)
- [ ] [voting - successfully handled votes](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/worker.rs#L589)
- [ ] [voting - successfully voted](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/worker.rs#L796)
- [ ] [import - bad justif import](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/import.rs#L149)
- [ ] [import - good justif import](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/import.rs#L143)
- [ ] [respond to justification request - success](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/communication/request_response/incoming_requests_handler.rs#L182)
- [ ] [respond to justification request - failure/error](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/communication/request_response/incoming_requests_handler.rs#L188)
- [ ] [on demand justification - no peers to request from](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/communication/request_response/outgoing_requests_engine.rs#L135)
- [ ] [on demand justification - peer hang-up](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/communication/request_response/outgoing_requests_engine.rs#L163)
- [ ] [on demand justification - peer error](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/communication/request_response/outgoing_requests_engine.rs#L171)
- [ ] [on demand justification - invalid proof](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/communication/request_response/outgoing_requests_engine.rs#L185)
- [ ] [on demand justification - good proof - success](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/communication/request_response/outgoing_requests_engine.rs#L222)

**Comment by dharjeezy** [comment]
I will like to work on this @acatangiu 
What metric system should be used? Prometheus?

**Comment by acatangiu** [comment]
Yes, just add more metrics to [existing prometheus](https://github.com/paritytech/substrate/blob/f0b6e79a8d21856743acc5370b5d5c3271048cb9/client/beefy/src/lib.rs#L252).
