### ISSUE TITLE
Transaction pool wastes CPU

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#12903]
I've noticed that when doing full sync, all transaction from all imported blocks are re-validated by the transaction pool after the block has been imported. This happens here: 
https://github.com/paritytech/substrate/blob/9772209ee962fe36c3502afb638e1bd835c23d9e/client/transaction-pool/src/graph/pool.rs#L277

This wastes a lot of resources and hurts sync performance. Transaction pool should only re-validate transactions that are actually in the pool, shouldn't it?. Or at least skip the whole thing when the pool is empty.

**Comment by bkchr** [comment]
Transaction pool should not be called while doing a full/major sync as we don't send block import notifications?

**Comment by arkpar** [comment]
It looks like finality events are still being sent when GRANDPA imports a justification during major sync. Transaction pool then computes a tree route to the block from the previous notification and processes all blocks.

**Comment by bkchr** [comment]
Ahh! Ty for the report. 

@michalkucharczyk could you please fix this? :D

**Comment by arkpar** [comment]
> @arkpar looking at your https://github.com/paritytech/substrate/pull/12973#issuecomment-1357859847, does the above proposal (https://github.com/paritytech/substrate/issues/12903#issuecomment-1357594101) make sense to you?

Without fixing the tree route issue, it will only make things worse. Now, at least, you get at most few hundred blocks between notifications because of how grandpa sends them when finalizing. If you stop processing them at all when syncing, as I've said in the mentioned comment, you can potentially receive notification for block that's a million blocks later than the the previous notification.

**Comment by michalkucharczyk** [comment]
The first notification after `major_syncing` completion would need to be `force_update` which sets the finalized block w/o computing tree_route:
https://github.com/paritytech/substrate/blob/master/client/transaction-pool/src/enactment_state.rs#L140

**Comment by arkpar** [comment]
> The first notification after major_syncing completion would need to be force_update which sets the finalized block w/o computing tree_route:

This could work.

@bkchr what do you think?

**Comment by bkchr** [comment]
> If you stop processing them at all when syncing, as I've said in the mentioned comment, you can potentially receive notification for block that's a million blocks later than the the previous notification.

I think it would be much better for now to not build a tree route or completely ignore the update when the difference between the last updated block and the current event block is greater than some constant. I think we could pick something like `20` for this constant.

I would really not like to introduce some new kind of event. I'm looking forward to the future where the tx pool is just not running while we are not in "keep up sync mode".

**Comment by michalkucharczyk** [comment]
Why did you suggest 20? Is it based on some stats?

**Comment by bkchr** [comment]
"Educated guess" :laughing: 

Currently we are switching to major sync mode when we are 5 blocks behind the tip of the chain. So, 20 sounds reasonable. We could maybe lower it.
