### ISSUE TITLE
V14 metadata doesn't provide enough information to decode extrinsic

### ISSUE THREAD

**Issue by eldargab** [paritytech/substrate#12929]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

To properly decode extrinsic one needs to know

1. The type of `Address`
2. The type of `Signature`
3. The type of `Call`.

While all the above types are included in the `.lookup.types`, there is no way to know which one is which.

At Subsquid we look [at paths and type parameters ](https://github.com/subsquid/squid-sdk/blob/ab1cae1eb6c9c4a34760f4fea09dff45c2f4065b/substrate/substrate-metadata/src/chainDescription.ts#L170).

Polkadot.js uses its own set of hardcoded assumptions none of which is guaranteed to hold.

This is practical issue which hardens the maintenance of our stack.

**Comment by bkchr** [comment]
> 3\. The type of `Call`.

Yeah the call was always there, but more implicit by giving you all pallets and all their calls. We should probably revisit now as we have scale-info.

**Comment by jsdw** [comment]
We actually use the metadata already to decode extrinsics:

https://github.com/paritytech/subxt/blob/3f16bb8d521031c7e13749d41711f54f490bb84c/subxt/src/blocks/extrinsic_types.rs#L205

To get the address, call, signature and extra details needed, we do this:

https://github.com/paritytech/subxt/blob/3f16bb8d521031c7e13749d41711f54f490bb84c/subxt/src/blocks/extrinsic_types.rs#L483

Currently this means that we do rely on the `metadata.extrinsic.ty` containing specific generics (in other words, that it's an `UncheckedExtrinsic` type).

Perhaps we should expose those type IDs directly under `metadata.extrinsic` though, which would ensure that they exist (and make it easier to get at them). ie have:

```rust
pub struct ExtrinsicMetadata<T: Form = MetaForm> {
	/// The type of the extrinsic.
	pub ty: T::Type,
	/// Extrinsic version.
	pub version: u8,
        /// Type of the outermost Call enum.
        pub call_ty: T::Type,
        /// Type of the address.
        pub address_ty: T::Type,
        /// Type of the extrinsic signature.
        pub signature_ty: T::Type,
	/// The signed extensions in the order they appear in the extrinsic.
	pub signed_extensions: Vec<SignedExtensionMetadata<T>>,
}
```

Does that sound good?

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/stablising-v15-metadata/2819/1
