### ISSUE TITLE
Ensure substrate-node-template keeps up with API changes in substrate

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1293]
Currently, substrate-node-template can easily get out of date. We probably want to amalgamate it into the substrate repo but without compromising the its raison d'etre which is to be an isolated piece of code that can be used to jumpstart a new Substrate chain, as used by `substrate-up`.

**Comment by bkchr** [comment]
Fixed by: https://github.com/paritytech/substrate/pull/1637
