### ISSUE TITLE
Transaction Payment doesn't implement Deserialize for FeeDetails

### ISSUE THREAD

**Issue by kylezs** [paritytech/substrate#12956]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The balances don't deserialize.

It always returns inclusionFee: None

And looking at the code here: https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/src/types.rs

It looks like a custom deserializer isn't specified.

Also would be easier if the RPC returned the values as ints and not hex.

### Steps to reproduce

Something like below with subxt:
```rust
let online_client = OnlineClient::<PolkadotConfig>::from_url(
				"ws://some-substrate-chain",
			)
			.await
			.unwrap();

let details = online_client
			.rpc()
			.request::<FeeDetails>("payment_queryFeeDetails", rpc_params![<some extrinsic_hash>])
			.await
			.unwrap();

println!("Details: {details:?}");
```

**Comment by bkchr** [comment]
> [](https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/src/types.rs)
> 
> It looks like a custom deserializer isn't specified.

I don't get what you mean by this? The struct is implementing `Deserialize`?

**Comment by kylezs** [comment]
Maybe I'm missing something else here, but when I query for fee_details via RPC (on Polkadot), I get the the balances in hex. The Balances pallet uses `u128` on Polkadot, so I'm not sure why that would serialize as hex, unless specified somewhere, but I cannot see it specified anywhere. The desrialization expects it as just a number string. 

What suggested to me that there was a custom desrialization missing was the fact that for `RuntimeDispatchInfo` there is an extra bound specified ```#[cfg_attr(
	feature = "std",
	serde(bound(deserialize = "Balance: std::str::FromStr, Weight: Deserialize<'de>"))
)]```

**Comment by kylezs** [comment]
Ik what I missed... the RPC is doing it's own serialization into NumberOrHex...
