### ISSUE TITLE
Changes in the metadata format break the Bonds UI Codec

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#1295]
Currently, the Bonds UI is unable to parse `T::Balance` and `T::Index` due to breaking changes in the metadata format.

When following the ["create a custom substrate chain" tutorial](https://substrate.readme.io/v1.0.0/docs/creating-a-custom-substrate-chain), users are running into an issue where they are unable to successfully see the balance of Alice.

When using the Bonds UI to view Alice, you get the following errors in the browser console:

```
codec.js:268 Uncaught Unknown type to decode: T :: Balance
decode @ codec.js:268
StorageBond.r @ storageBond.js:14
callback @ subscriptionBond.js:20
ws.onmessage @ nodeService.js:72

codec.js:268 Uncaught Unknown type to decode: T :: Index
```

**Comment by gavofyork** [comment]
Fixed,
