### ISSUE TITLE
Exported method ParachainHost_availability_cores is not found

### ISSUE THREAD

**Issue by LukeWheeldon** [paritytech/substrate#12964]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I am getting the following error at very regular intervals in my node logs:

```
2022-12-18 15:03:24 failed to assemble or send inherent data err=Runtime(Execution { runtime_api_name: "availability_cores", source: Application(Execution(Other("Exported method ParachainHost_availability_cores is not found"))) })
```

It is a new server so I am not sure whether it is normal and to ignore, or if it is something I should be reporting. I am opening this ticket in case it would be relevant to the dev team.

### Steps to reproduce

```
polkadot \
        --sync warp \
        --validator \
        --pruning 1000 \
        -d /srv/polkadot \
        --listen-addr /ip4/1.2.3.4/tcp/30333 \
        --prometheus-external \
        --no-mdns \
        --no-telemetry
```

**Comment by bkchr** [comment]
Somewhat duplicate of: https://github.com/paritytech/polkadot/issues/5885

**Comment by bkchr** [comment]
But, this is no issue. Just an incorrect error. You can ignore these log lines!
