### ISSUE TITLE
Cleanup empty scheduler agendas

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#12977]
The number of empty agendas of the Kusama scheduler is currently growing with about 137/day since its inception ~3 weeks ago. This is a byproduct of the current scheduler design, since it keeps `None`-only agendas like `[None, None, …]` around.  
Counting them with a [script](https://gist.github.com/ggwpez/25af3e6ab69b8b11dd7da2354a62096f):  
```pre
Block height 15500000 has 604 empty agendas
Block height 15550000 has 1008 empty agendas
Block height 15600000 has 1397 empty agendas
Block height 15650000 has 2180 empty agendas
Block height 15700000 has 2723 empty agendas
Block height 15750000 has 2989 empty agendas
Block height 15800000 has 3554 empty agendas
Block height 15818682 has 3652 empty agendas
Average growth rate: 5.74 / h, 137.73 / d
```
I guess we can create a permissionless cleanup Call and then schedule that periodically.  
Any better ideas? Doing in a runtime migration is probably too rare. 

Note that Polkadot is unaffected since it is still on the V3 scheduler.

**Comment by ruseinov** [comment]
Seems like something that should probably be fixed within scheduler eventually?
Could be done on_idle too I guess, but then some monitoring won't hurt to make sure this does not 
grow too much.

**Comment by ggwpez** [comment]
> Seems like something that should probably be fixed within scheduler eventually? Could be done on_idle too I guess, but then some monitoring won't hurt to make sure this does not grow too much.

Yes we should fix it long-term and have some cleanup short-term.  
I think this could help for monitoring https://github.com/paritytech/substrate/pull/12439, but I will probably do something hacky as short-term monitoring.

**Comment by muharem** [comment]
All agendas with only None items, exist only for the future blocks

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-37/1736/1

**Comment by ggwpez** [comment]
Just double-checking on Kusama:  
```pre
Block height 15950000 has 1546 empty agendas
Block height 16000000 has 1042 empty agendas
Block height 16050000 has 226 empty agendas
Block height 16100000 has 335 empty agendas
Block height 16150000 has 579 empty agendas
Block height 16200000 has 1186 empty agendas
Block height 16250000 has 1506 empty agendas
Block height 16300000 has 1624 empty agendas
Block height 16350000 has 1564 empty agendas
Block height 16400000 has 0 empty agendas
Block height 16450000 has 0 empty agendas
Block height 16500000 has 0 empty agendas
```

Polkadot was deployed with the fix in place, so should be fine.
