### ISSUE TITLE
`AssetTxFeePaid` event should return fee and tip amounts in the asset ID

### ISSUE THREAD

**Issue by IkerAlus** [paritytech/substrate#12987]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

When an [`AssetTxFeePaid`](https://github.com/paritytech/substrate/blob/696bdc67af5fd83aca318263dbd405593b043ba3/frame/transaction-payment/asset-tx-payment/src/lib.rs#L132) event of the asset-tx-payment pallet is emitted, the fees and tip are subtracted from the asset ID balance of the sending account. However this event currently returns the `tip` and `actualFee` fields in  balances of the chain native token. This is confusing for users and external tools, since they assume the values displayed in those fields are given in units of the asset ID. 

### Steps to reproduce

Example screenshot of a transaction on Statemint paying the fees in the asset ID `1984` but emitting the AssetTxFeePaid event in DOT balances: 
<img width="469" alt="Screenshot 2022-12-21 at 09 23 38" src="https://user-images.githubusercontent.com/34474035/208856527-f6cc3010-636b-4b99-9e44-4274c429cbbf.png">

**Comment by Szegoo** [comment]
I think this is a reasonable change(I am not the one to make decisions here though). If this gets confirmed I will open a simple PR for this.

**Comment by bkchr** [comment]
Sounds reasonable as well to me! Please open a pr @Szegoo

**Comment by Szegoo** [comment]
I realised that this is not as easy and simple to implement as I thought :P
This would require us to make the `BalanceOf<T>` generic inside the `transaction-payment` pallet.
We could do something like this: 
```rust
pub fn compute_actual_fee<Balance: FixedPointOperand + AtLeast32BitUnsigned>(
```
So when we make a call to this from the `asset-tx-payment` pallet we would call this like this:
```rust
let actual_fee = pallet_transaction_payment::Pallet::<T>::compute_actual_fee::<AssetBalanceOf<T>>(
	len as u32, info, post_info, tip,
);
```
This way we could make the `Balance` type generic but this does complicate the code a bit and also results in less readable code.

I am curious if you think this is worth it for this "feature" @bkchr.

**Comment by bkchr** [comment]
Not sure I can follow you, don't we just need to add a `BalanceToAsset: BalanceConversion<BalanceOf<Self>, AssetIdOf<Self>, AssetBalanceOf<Self>>` to the `Config` trait of `asset-tx-payment` and then call this code: 
https://github.com/paritytech/substrate/blob/ea387c634715793f806286abf1e64cabf9b7026f/frame/transaction-payment/asset-tx-payment/src/payment.rs#L153-L155 to convert the balance to the asset balance?

**Comment by Szegoo** [comment]
Correct, I overlooked that and started complicating 😅
