### ISSUE TITLE
Member and rank management of ranked_collective pallet.

### ISSUE THREAD

**Issue by muharem** [paritytech/substrate#12983]
### Problem 
Member and rank management of ranked_collective pallet can not be decorated.

### Details 
The pallet's API contains the end user [call]s to add/remove and promote/demote members. But there is no high level abstraction (trait) and implementation to manage members and ranks.

Use case:
The ambassador program uses ranked_collective and referenda pallets to setup its own governance. 
On every members and rank change there are additional operations to happen (e.g. additional info stored; senior ambassador badge minted) and they needs to be a single call.

### Proposal 1, introduce trait/s for a rank management.
The implementations of the next two traits should be enough to manage the ranked collective from outside:

````
/// Trait for type that can manage a racked set of account IDs.
pub trait ChangeRank<AccountId, Rank> {
	/// Promote or demote a member of a set to the `rank`. Removes a member if given `rank` is `None`.
	/// If `who` is not a member of a set, it is included and promoted.
        fn change(who: AccountId, rank: Option<Rank>) -> DispatchResultWithPostInfo;
}

/// Trait for type that can return a member record of some set by an account id.
pub trait MemberRecord<AccountId, Record> {
	/// Return a member record of `who`. `None` if `who` does not belong to the set.
	fn member(who: AccountId) -> Option<Record>;
}
````

### Proposal 2, do_* implementations for a rank management.

Provide public associated functions of the pallet type to manage members and ranks.

This is enough for my use case, but the only disadvantage I see, if we later introduce the trait, we will have to respect both APIs.

### Proposal 3, trigger an outer function from the pallet on members/rank change.

Similar to [OnNewAccount](https://github.com/paritytech/substrate/blob/85f660fded10af9ee80d5acb6efcc16dc59fffd2/frame/support/src/traits/misc.rs#L665) trait.

Less preferable option for me. Semantically should be other way around (like in previous options). 

_Any suggestions?_

**Comment by muharem** [comment]
I personally prefer option one, a proper abstraction and no outer function call from the pallet.

**Comment by bkchr** [comment]
So there will be a special pallet for the ambassador program that will manage all these things? Does this pallet need to be generic over the collective pallet? If not, I don't see any reason to not just direcfly import the ranked collective pallet and use the functions without hiding it behind a trait.

**Comment by ggwpez** [comment]
> So there will be a special pallet for the ambassador program that will manage all these things? Does this pallet need to be generic over the collective pallet? If not, I don't see any reason to not just direcfly import the ranked collective pallet and use the functions without hiding it behind a trait.

Does this also work for instantiatable pallets?  
The `demote_member` and `remove_member` functions would still need to be factored out into `do_*` functions.

**Comment by bkchr** [comment]
> Does this also work for instantiatable pallets?

If you pass the instance, yes.

**Comment by muharem** [comment]
@bkchr yes, for my use case it's enough, pallet type with required public associated functions (proposal 2 from above).
I start with it.

**Comment by muharem** [comment]
> So there will be a special pallet for the ambassador program that will manage all these things? Does this pallet need to be generic over the collective pallet?

@bkchr it will be a set of pallet instances, few from FRAME, and one custom defined on the runtime crate level (at the beginning I do not try to generalize it, only in the future when we see how collectives evolves, for now prefer simplicity)
