### ISSUE TITLE
Upgrade `wasmtime` to at least `2.0.1`

### ISSUE THREAD

**Issue by ozgunozerk** [paritytech/substrate#12986]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

There is a known bug in `wasmtime`:
https://github.com/bytecodealliance/wasmtime/issues/5133

 that is fixed with release `2.0.1`.
https://github.com/bytecodealliance/wasmtime/pull/5134

The bug comes into existence under some weird circumstances that I'm unsure about the fully deterministic reasons, but it happens.

Upgrading `wasmtime` to `2.0.1` will get rid of this inconvenience.

### Steps to reproduce

Not quite the steps to reproduce, but here is an example:
https://github.com/subspace/subspace-cli/actions/runs/3734314112/jobs/6336216387#step:6:1215

**Comment by bkchr** [comment]
We only use `wasmtime 1.0.0` and this issue is only for `wasmtime 2.0.0`? 

I mean we can upgrade at some point, but you should not be affected by this?

**Comment by ozgunozerk** [comment]
Nope, this issue is present for `1.0.0` and `1.0.1` and `1.0.2`, all of these do not include `Win32_Foundation` and try to use them.

**Comment by bkchr** [comment]
Okay :)

**Comment by kayabaNerve** [comment]
Now 2.0.2 per https://rustsec.org/advisories/RUSTSEC-2022-0076.html.

**Comment by koushiro** [comment]
upgrade PR: https://github.com/paritytech/substrate/pull/13126

**Comment by bkchr** [comment]
Was done
