### ISSUE TITLE
Implement serde derivations also in no_std

### ISSUE THREAD

**Issue by haerdib** [paritytech/substrate#12994]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Many core primitives of substrate only implement serde in std mode. The reason being the efficiency, so I was told. However, in a no_std environment, this forces a lot of workarounds if serde is needed. Is there any chance that you would accept a PR introducing an additional compiler feature that allows to derive serialization also in no_std mode?
(such as here: https://github.com/paritytech/parity-common/blob/master/primitive-types/Cargo.toml#L26)

**Comment by bkchr** [comment]
Yes that would be okay.

**Comment by nazar-pc** [comment]
Replacing `feature = "std"` with `feature = "serde"` should be sufficient, so users can decide whether to enable it or not separately from `std`.

**Comment by haerdib** [comment]
`"serde"` or `"serde_full"`, as it's called in [frame-metadata](https://github.com/paritytech/frame-metadata/blob/main/frame-metadata/Cargo.toml#L33) ?

**Comment by bkchr** [comment]
Please call it `serde`. For this you only need to make `serde` an optional dependency. An optional dependency is directly exposed as feature in cargo.
