### ISSUE TITLE
consensus-aura: test features won't be activated due to cargo limitation

### ISSUE THREAD

**Issue by sorpaas** [paritytech/substrate#1301]
It's an old issue in Cargo (https://github.com/rust-lang/cargo/issues/2911) that test features won't be activated by itself. So unfortunately lines like below won't work alone. (You can try to `cd core/consensus/aura` and run `cargo test` there.)

https://github.com/paritytech/substrate/blob/bacc1df92abd0b412d7947c68dafe95a3692ab42/core/consensus/aura/Cargo.toml#L33

The reason why it didn't break is because other test crates already requires `test-helpers` feature, so it gets merged.

**Comment by rphmeier** [comment]
We should write a separate crate for the test helpers. This will be a lot easier after #1168, because then `aura` won't need to depend on `substrate-network` in general.

**Comment by tomaka** [comment]
Triage.
I don't see any `[target.'cfg(test)'.dependencies]` anymore, so I guess that this is fixed.
