### ISSUE TITLE
EPM and staking events improvement

### ISSUE THREAD

**Issue by gpestana** [paritytech/substrate#13026]
A few suggestions to make it easier to trace runtime events related to the election provider and staking pallets:

**EPM pallet**
- `SolutionStored { compute, prev_ejected, origin, Option<T::AccountId> }` (modified).
- `PhaseTransitioned { from: Phase, to: Phase, round: u32}`: All the phase transition events (`Event::SignedPhaseStarted`, `Event::UnsighedPhaseStarted`) are replaced by a state transition event that keep the previous and next phase. This will also allow us to easily start emitting when the emergency and phase off start and all new future phases that we may need.

**Staking pallet**:
- `ForceEra { mode: Forcing }`: signals that a new `Forcing` mode was set.

In addition to refactoring and adding new events, this PR also adds helper functions to transition EPM phases and set a new force era mode.

**Comment by Ank4n** [comment]
> * `SolutionStored { compute, prev_ejected, account_id, score }`: should also have the `AccountId` of the miner that stored the solution and its score.

- FYI: this event is also emitted for unsigned solutions. We can keep it as optional which is then will also be useful to indicate whether it was a signed or an unsigned solution. 

> * `EmergencyPhaseStarted`: indicates when the emergency phase has started.

👍 . I think we should have an event for the start of each phase including even `Off Phase`?

> * `FallbackSolution`: indicates that a solution has been provided by `T::Fallback`
> * `GovernanceSolution`: indicates that a solution has been provided by `T::GovernanceFallback`

Might be better to indicate this in the existing `SolutionSotred` event?
