### ISSUE TITLE
[frame] change StorageNMap::insert (remove) to return a previous value

### ISSUE THREAD

**Issue by melekes** [paritytech/substrate#13041]
by analogy with [HashMap::insert](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.insert).

This removes the need to check if key is present beforehand in certain cases. See https://github.com/paritytech/substrate/pull/10621#discussion_r1057166905 for example.

**Comment by ggwpez** [comment]
If you want to return the previous value, then you have to read it from storage first, or?  
That will incur a PoV to each overwriting insert call.

**Comment by melekes** [comment]
Hmm... what about the boolean flag? Or it will also require "a read from the storage"?

**Comment by ggwpez** [comment]
Currently it just does `unhashed::put` to write the value to the transactional layer [here](https://github.com/paritytech/substrate/blob/a47f200eebeb88a5bde6f1ed2be9728b82536dde/frame/support/src/storage/generator/map.rs#L256). This does not return any information whether or not the value was present.  
I dont see a different way than first reading from DB to know whether it existed.  

Maybe someone else has an idea. cc @cheme

**Comment by bkchr** [comment]
You would need to read the value and this would be wasting a read for every write and writes are very cheap. Simply checking if the value exists when it is required for some niche use cases is the proper solution. 

In the runtime it is really crucial that we optimize the number of read and writes as these are the main dominant factors in benchmarking. Going to close this issue as this is already possible if wanted.
