### ISSUE TITLE
Prevent pallet version inconsistency

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13062]
Currently we have the soft assumption that `on_chain_storage_version() == current_storage_version()` for all pallets.  
There are indications that this does not hold for all pallets on Rococo. It would be nice to have a post-migration check which asserts this so that no migrations can be forgotten.

**Comment by bkchr** [comment]
Yeah, I have already started working on this. I need to finish it :P

**Comment by ggwpez** [comment]
I wrote a draft to check Rococo here https://github.com/paritytech/substrate/compare/master...oty-check-pallet-versions  
Seems like there are issues with it. Does your code look much different @bkchr ?
