### ISSUE TITLE
Staking and nomination pools runtime API improvements

### ISSUE THREAD

**Issue by gpestana** [paritytech/substrate#13069]
As discussed in this [Polkadot forum thread](https://forum.polkadot.network/t/wasm-view-functions/1045/3) and elsewhere, it would be useful for the staking pallet to expose a few runtime APIs that can be called through the `state_call` RPC to help UIs and clients to query dynamic onchain data that is required for showing stats in UIs and help building extrinsic parameters.

Examples of RPC methods:

- `StakingApi_nominationsQuota`: Returns the number of nominations quota per bonded balance, to help UIs calculating the max nominations for the account (implemented [in this PR](https://github.com/paritytech/substrate/pull/12970));
- `NominationPoolsApi_balance_to_point`
- `NominationPoolsApi_points_to_balance`

**Comment by ECJ222** [comment]
This looks interesting.

I would be happy to work on it.
