### ISSUE TITLE
Make beefy-merkle-tree as Pure algorithms crate

### ISSUE THREAD

**Issue by DaviRain-Su** [paritytech/substrate#13075]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Move `BeefyMmrApi` to `pallet-beefy-mmr` make `beefy-merkle-tree` as pure algorithms don't impor any substrate crate.

**Comment by acatangiu** [comment]
Can you please add more details on what you need here and why?
