### ISSUE TITLE
Fast-unstake benchmarks are too slow

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13077]
Benchsuite running since 14 hrs on ref hardware. Fast-unstake taking up the majority of that.  
Looking at the `quick-benchmarks` Substrate CI shows that it is the `on_idle_check` which even with `--steps 2 --repeat 1` takes 10 minutes:  
```pre
09:18:00 Starting benchmark: pallet_fast_unstake::on_idle_check
09:18:06 Running Benchmark: pallet_fast_unstake.on_idle_check(1 args) 1/2 1/1
09:28:41 Running Benchmark: pallet_fast_unstake.on_idle_check(1 args) 2/2 1/1
```
Kusama does not suffer from this, so probably just parameters?

cc @kianenigma

**Comment by kianenigma** [comment]
cc @ruseinov can you take care of this? I hope with your familiarity with the pallet it should be simple enough.

**Comment by kianenigma** [comment]
will take a look soon.
