### ISSUE TITLE
Cannot-produce-and-finalize-blocks-with-2-node-peer

### ISSUE THREAD

**Issue by PazDia** [paritytech/substrate#13102]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Hi Guys,
this issue happens again.
I'm using ver 9.35 and cannot get finalization
Please see Oscar's response in the end. (it was solved on v 9.24)
BTW: i tried it with three nodes as well - same issue.

https://substrate.stackexchange.com/questions/3414/cannot-produce-and-finalize-blocks-with-2-node-peer

thanks

### Steps to reproduce

Installed the node on an AWS server. 
Build the server and run it.  -- all is good.
Installed second server and defined the first server as the bootnode --> the server connected and data started to exchange.
The peers connected and synced and blocks are being produced.
No finalization.

**Comment by bkchr** [comment]
@PazDia I transferred this issue out of reason, not because I was bored. Please use the old issue.
