### ISSUE TITLE
Versioned `OnRuntimeUpgrade`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13107]
We currently have the pattern of first manually checking whether a migration should run or can be deleted.  
Then setting the version and in the `post_upgrade` we check that it was set. This is error prone and redundant.  

We could improve here by using either associated types/consts or const generics to track the required version directly in the trait.  
Both being options for the case that there is (and should) be no version.  
```rust
pub trait OnRuntimeUpgrade {
    const From: Option<u32>,
    const To: Option<u32>,
```

To keep it backwards compatible we should probably create a new or wrapper trait.

**Comment by ECJ222** [comment]
This looks interesting @ggwpez.

Can you provide an example of how the associated types or const generics would be used in practice to determine whether a migration should run or be deleted?

**Comment by kianenigma** [comment]
Yeah, this is very much like what I had in mind. a `VersionedOnRuntimeUpgrade` has a blanket impl of `OnRuntimeUpgrade` and does all of this stuff automatically.

**Comment by ECJ222** [comment]
Interesting, this was the solution I had in mind based on what @kianenigma proposed.

```
pub trait VersionedOnRuntimeUpgrade {
	/// Version before upgrade.
	/// It will be used to check whether the migration is required or not.
	const FROM: Option<u32>;
	/// Version after upgrade.
	/// It will be used to check whether the migration is required or not
	/// and to set the new version after the upgrade.
	const TO: Option<u32>;
	/// Checks if the two constants are different and
	/// returns a boolean indicating whether the migration should be run or deleted.
	fn is_required() -> bool;
}
```

migration implementation.

```
impl<T: OnRuntimeUpgrade> VersionedOnRuntimeUpgrade for T {
	const FROM: Option<u32> = Some(StorageVersion::<T>::get()); // 12
	const TO: Option<u32> = Some(Pallet::<T>::current_storage_version()); // 13

	fn is_required() -> bool {
		Self::FROM != Self::TO
	}
}
```

if `is_required()` returns true we upgrade to the migration latest version of the runtime otherwise just delete or skip the migration.

**Comment by ggwpez** [comment]
@ECJ222 I am not sure if i correctly understood your example code.  
The `FROM` and `TO` would be hard-coded, not dynamic. The we can compare `FROM` with the current on-chain version and if that maches; do the upgrade and overwrite the on-chain version with `TO`.  
Otherwise if it not matches; do nothing / log error and possibly fail in `pre_upgrade`.

**Comment by kianenigma** [comment]
```rust
pub struct AutoMigrate<From, To, Inner, Pallet>(
	sp_std::marker::PhantomData<(From, To, Inner, Pallet)>,
);
impl<
		From: Get<StorageVersion>,
		To: Get<StorageVersion>,
		Inner: OnRuntimeUpgrade,
		Pallet: GetStorageVersion + PalletInfoAccess,
	> OnRuntimeUpgrade for AutoMigrate<From, To, Inner, Pallet>
{
	fn on_runtime_upgrade() -> Weight {
		let current = Pallet::current_storage_version();
		let on_chain = Pallet::on_chain_storage_version();

		if current == To::get() && on_chain == From::get() {
			let weight = Inner::on_runtime_upgrade();
			current.put::<Pallet>();

			log!(info, "{:?} applied successfully.", To::get());
			weight
		} else {
			log!(warn, "{:?} not applied.", To::get());
			todo!("need to get DbWeight somehow as well..");
		}
	}
}
```

Here's how I would do this.

**Comment by bkchr** [comment]
> ```rust
> 		if current == To::get() && on_chain == From::get() {
> 			let weight = Inner::on_runtime_upgrade();
> 			current.put::<Pallet>();
> ```

This logic is wrong. Especially if you may need to put multiple migrations in one runtime upgrade. 

```
		if on_chain == From::get() {
			let weight = Inner::on_runtime_upgrade();
			To::get().put::<Pallet>();
```

That is correct.

**Comment by liamaharon** [comment]
I'm planning to start on this soon, after I finish with my current main work effort (lazy-download).

**Comment by juangirini** [comment]
Let's look at this [issue](https://github.com/paritytech/substrate/issues/14098) when working on this

**Comment by liamaharon** [comment]
> simpler understanding. `#[pallet::storage_version]` is too much magic.

The only issue I can think of with removing this is that we would not know what initial on-chain version to set for a pallet when it's introduced to the runtime. You're correct though that we shouldn't need it in any migrations.

> If this is None, then the executive would execute the migration script in any case. migrations defined in the pallet should initially be like this, and we should strive to deprecate them.

Cool. I like the idea of the executive pallet managing this, so we don't need to think about versions at all inside the `on_runtime_upgrade` function itself.

**Comment by bkchr** [comment]
> First, I would remove `#[pallet::storage_version]` aka `current`.

To what version are you then setting the storage version in the genesis state? I'm with you that we should probably remove the `current_storage_version` function, but I don't see how you want to remove the attribute.

**Comment by liamaharon** [comment]
> > First, I would remove `#[pallet::storage_version]` aka `current`.
> 
> To what version are you then setting the storage version in the genesis state? I'm with you that we should probably remove the `current_storage_version` function, but I don't see how you want to remove the attribute.

That was also my initial thought. 

However, if we tightly couple at least the most recent migration to the pallet, we could initialise the on-chain version based on the latest migrations `To`. See this comment https://github.com/paritytech/substrate/pull/14311#issuecomment-1586977125
