### ISSUE TITLE
Add `TryState` hook for `MessageQueue`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13115]
The `MessageQueue` pallet has quite a few storage assumptions which could be checked in a `try_state` hook.   

:point_right: *Mentor* issues are meant for new-comers. Please ask before picking them up.

**Comment by mahmudsudo** [comment]
i am a newcomer, can i pick this up?

**Comment by ggwpez** [comment]
Yes @mahmudsudo !  
Please familiarize yourself with the `try_state` hook implementations that we have in other pallets and how to write them.  
For example in the [bags-list](https://github.com/paritytech/substrate/blob/89498c0d756c649d71e82340bee44fcc7cfe8037/frame/bags-list/src/lib.rs#L271) pallet or in [nomination-pools](https://github.com/paritytech/substrate/blob/911f65be7949342e12601cc3015d5c47e9339de4/frame/nomination-pools/src/lib.rs#L2126).  
Then take a look at the [message-queue](https://github.com/paritytech/substrate/blob/b3d9f3c57e7f799d49442e3456614431f2d0e51a/frame/message-queue/src/lib.rs#L827) and especially all the `debug_assert!`+`defensive!` in it. Ideally we check all these invariants in the `try_state` function.  
So for example check that every page can be decoded into `peek_*` functions etc.

**Comment by gitofdeepanshu** [comment]
Hey @mahmudsudo , are you still working on this? 
If not, I would like to take this over.

**Comment by ggwpez** [comment]
Looks stake, please go ahead @gitofdeepanshu

**Comment by gitofdeepanshu** [comment]
Hey @ggwpez 
I have written the function taking following assumptions:
 
If `serviceHead` points to a ready Queue (i.e. has some value), then BookState of that Queue has:
	 * `message_count` > 0
	* `size` > 0
	* `end` > begin
	* Some(ready_neighbours)
	* If `ready_neighbours.next` == self.origin, then `ready_neighbours.prev` == self.origin (only queue in ring)
	
  For a particular BookState of Queue present in ReadyRing, all pages from `begin` to `end`-1 should have:
	 * `remaining` > 0
	* `remaining_size` > 0
	* `first` <= `last`
	* Every page can be decoded into peek_* functions
	
If all these assumptions are correct then all Queue present in ReadyRing must have atleast 1 message. (Is this correct?) 
But there are some tests which add Queue with empty book into ReadyRing which causes try_state function to panic. Should I leave those tests or is there something wrong with my assumptions?

**Comment by ggwpez** [comment]
> If all these assumptions are correct then all Queue present in ReadyRing must have atleast 1 message. (Is this correct?)
> But there are some tests which add Queue with empty book into ReadyRing which causes try_state function to panic. Should I leave those tests or is there something wrong with my assumptions?

Looks good so far. Please open a Merge request with your changes. I will then go over them in more details.  
But AFAIK yes; there should be no empty books in the ready ring.

**Comment by gitofdeepanshu** [comment]
@ggwpez 
I have opened the merge request, kindly let me know if you want me to change anything.
