### ISSUE TITLE
mutate_exists for StorageValue with ValueQuery

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#13133]
I use ValueQuery so it creates a default value for empty key, which is handy. But I still want to delete it with `mutate_exists`.

**Comment by bkchr** [comment]
`mutate_exists` doesn't exist for `StorageValue`? Do you mean `StorageMap`? And what is the issue? The value is not deleted when you set the mutated value to `None`?

**Comment by xlc** [comment]
Sorry for not be clear. I am requesting add mutate_exists for StorageValue
