### ISSUE TITLE
cargo build fs-swap failed

### ISSUE THREAD

**Issue by weitianyuan** [paritytech/substrate#13145]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

error[E0308]: mismatched types
  --> /home/wty/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/fs-swap-0.2.5/src/platform/linux.rs:19:85
   |
19 |         match renameat2(libc::AT_FDCWD, a_path.as_ptr(), libc::AT_FDCWD, b_path.as_ptr(), libc::RENAME_EXCHANGE) {
   |               --------- arguments to this function are incorrect                          ^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u32`
   |
note: function defined here
  --> /home/wty/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/fs-swap-0.2.5/src/platform/linux.rs:7:11
   |
7  | unsafe fn renameat2(
   |           ^^^^^^^^^
8  |     olddirfd: libc::c_int, oldpath: *const libc::c_char, 
9  |     newdirfd: libc::c_int, newpath: *const libc::c_char, flags: libc::c_int
   |                                                          ------------------
help: you can convert a `u32` to an `i32` and panic if the converted value doesn't fit
   |
19 |         match renameat2(libc::AT_FDCWD, a_path.as_ptr(), libc::AT_FDCWD, b_path.as_ptr(), libc::RENAME_EXCHANGE.try_into().unwrap()) {
   |                                                                                                                ++++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `fs-swap` due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by bkchr** [comment]
`cargo update -p fs-swap` should fix it.
