### ISSUE TITLE
Enumerate only first key of StorageDoubleMap

### ISSUE THREAD

**Issue by gregdhill** [paritytech/substrate#13162]
Currently it is only possible to enumerate all keys of a `StorageDoubleMap` using [`iter_keys`](https://paritytech.github.io/substrate/master/frame_support/pallet_prelude/struct.StorageDoubleMap.html#method.iter_keys) or so. It would be very helpful to have a method that only returns the unique first keys to prevent having to collect and de-duplicate `Vec<(Key1, Key2)>` to get `Vec<Key1>`.

**Comment by xlc** [comment]
Duplicate to https://github.com/paritytech/substrate/issues/5319
