### ISSUE TITLE
signal: 10, SIGBUS: access to undefined memory

### ISSUE THREAD

**Issue by Chralt98** [paritytech/substrate#13170]
After upgrading from `polkadot-v0.9.29` to `polkadot-v0.9.36` and running `cargo test` I get the below error.

```bash
    Finished test [unoptimized + debuginfo] target(s) in 57.04s
     Running unittests src/lib.rs (target/debug/deps/template_runtime-fee138c7a810874f)
error: test failed, to rerun pass `-p template-runtime --lib`

Caused by:
  process didn't exit successfully: `/Users/testname/development/template-node/target/debug/deps/template_runtime-fee138c7a810874f` (signal: 10, SIGBUS: access to undefined memory)
```

I used the debugger and found the following:

Inside `target/debug/build/tikv-jemalloc-sys-399dd6d45c3726ce/out/build/include/jemalloc/internal/atomic.h`
```text
JEMALLOC_GENERATE_ATOMICS(void *, p, LG_SIZEOF_PTR)

Stop reason: EXC_BAD_ACCESS (code=2, address=0x1017ddcb0)
```

Could it be related to circular dependencies? How could I solve this?

**Comment by bkchr** [comment]
What OS are you using? And which hardware?

**Comment by Chralt98** [comment]
I am on a MacOS. I noticed that I updated rust to the newest version and deleted the top level project rust-toolchain file. I think the problem lies there.

**Comment by bkchr** [comment]
https://github.com/jemalloc/jemalloc/issues/2014

I'm going to close this, as this is no Substrate issue.
