### ISSUE TITLE
Create a migration that fixes CountedMap counts.

### ISSUE THREAD

**Issue by ruseinov** [paritytech/substrate#13218]
A continuation of https://github.com/paritytech/substrate/pull/13214.

Basically anybody who's been using `set` on a `CountedMap` before the aforementioned PR was merged needs to call `initialize_counter` on that map.

**Comment by kianenigma** [comment]
None of our runtimes had an issue regarding this. So while I agree that we need to communicate this to the outer world in case they did use the wrong function, I don't think having an issue here is the right way. 

This issue should be closed by someone writing a `recalculate` method for counted maps that re-generates the counter.

**Comment by ruseinov** [comment]
@kianenigma afaik recalculate already exists, will confirm and close

**Comment by ruseinov** [comment]
Yep, here it is: initialize_counter. I think we can close this.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-38/2122/1
