### ISSUE TITLE
CountedMap isn't updating the count on `set`.

### ISSUE THREAD

**Issue by ruseinov** [paritytech/substrate#13212]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Currently, when doing `CountedMap::set` it does not update the count, either on value removal or insertion. It should be consistent with `StorageMap::set` that simply delegates to either `StorageMap::insert` or `StorageMap::remove`.

We should make sure `CountedMap::set` delegates to `CountedMap::insert` or `CountedMap::remove`. 

### Steps to reproduce

Create a `CountedMap`, try to `set` a value and then check `CountedMap::count()` to verify that it returns 0.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-38/2122/1
