### ISSUE TITLE
Warp sync with Aura: Incomplete block import pipeline.

### ISSUE THREAD

**Issue by dandanlen** [paritytech/substrate#13220]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I had some issues using warp sync with the chainflip public testnet. (See [here](https://substrate.stackexchange.com/questions/6822/have-we-broken-warp-sync/))

Following @bkchr's advice in the above stackexchange question, I cherry-picked the commits from #13058 and #13074. This allowed the warp sync to progress further but I ran into a new issue: 

```
2023-01-23 13:31:24.175  WARN tokio-runtime-worker sync: 💔 Error importing block 0xd826b720a99165998df41aaf67f9590b53a874611b150aad890a3d52397dc062: consensus error: Import failed: Import failed: Incomplete block import pipeline.
```

The error originates [here](https://github.com/paritytech/substrate/blob/419b840fa1f170a1c2027b63310549d1bf6d2ed0/client/service/src/client/client.rs#L534).

As far as I can tell this is because, during a warp sync, the Aura verifier returns early, before the fork_choice is set:

https://github.com/paritytech/substrate/blob/419b840fa1f170a1c2027b63310549d1bf6d2ed0/client/consensus/aura/src/import_queue.rs#L185-L200

I tried moving this line to the start of the verify method and this allowed the warp sync to complete:

```
block.fork_choice = Some(ForkChoiceStrategy::LongestChain);
```

Not sure whether this is correct approach, but it at least demonstrates the source of the problem...

**Comment by bkchr** [comment]
Ty for the report: https://github.com/paritytech/substrate/pull/13221
