### ISSUE TITLE
Pool reward payout Issue

### ISSUE THREAD

**Issue by plasmajack** [paritytech/substrate#13228]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Pool ID 20 EK-STAKE-POOL adres: 12U578pj5dhD4PZxNCr4X3pR6kDMd5JnibTdU5qPMhf2RQ27

ID Ernst Kints adres: 12U578pj5dhD4PZxNCr4X3pR6kDMd5JnibTdU5qPMhf2RQ27

Hi i am the Creator of Pool 20,

I have noticed the following, 

When a new pool member joins the pool in epoch 5 this account shares in the total reward earned over the era it has bonded in the pool.

I think this is a bug in the pool reward payout system.

This account joint the pool at 2023-01-22 12:49:24 (+UTC)

Hash: 0x63fe635bf3ee2cb1fa9e14930bd87b487f58866b0a5340ce7e99dc91abce3ddd

Adres bonded to pool 

12j6783aSMwb2bVci1CH5iz6fJPLWzXM9NWQbyoCLzkzGmKk

On staking.polkadot.network and polkadot.js.org 

You can see the account has claimable rewards ( photo attached)

Greetings Ernst Kints 
![71292671-2DAE-4DFB-ADC7-7460ED5533F0](https://user-images.githubusercontent.com/72785533/214290973-a0c16989-a907-492e-9901-08bbb041e51e.jpg)

### Steps to reproduce

adres bonded to pool , in the fifth epoch

adres rewarded at start of new era

i have noticed this for the secound time now

**Comment by bkchr** [comment]
CC @kianenigma @rossbulat

**Comment by rossbulat** [comment]
Thanks for raising. This is known behaviour of pools and hasn't been perceived as a bug, more of a limitation of the current setup of nomination pools.
