### ISSUE TITLE
Get rid of all the `<weight>` docs in FRAME

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#13261]
as they are all super stale, and don't serve any purpose now that we have benchmarking. 

a dispatchable could still expose its complexity as:

```
/// Docs.
///
/// More docs.
///
/// ## Complexity
/// stuff
fn dispatch(origin: _, ..) -> {
```

But the current `<weight>` stuff is really garbage. 

Note that this should reduce the size of the metadata and ergo the wasm blob as the consequence, the PR closing this can and should benchmark the difference.

**Comment by bkchr** [comment]
> Note that this should reduce the size of the metadata and ergo the wasm blob as the consequence, the PR closing this can and should benchmark the difference.

Benchmark what difference?

**Comment by kianenigma** [comment]
> > Note that this should reduce the size of the metadata and ergo the wasm blob as the consequence, the PR closing this can and should benchmark the difference.
> 
> Benchmark what difference?

Size of the metadata and the wasm blob.

**Comment by bkchr** [comment]
This should be really neglectable. If we add one new pallet to a runtime we probably add more stuff than what this weight stuff changes :P

**Comment by kianenigma** [comment]
Sure sure, reducing the size is not the main purpose either. The main purpose is the clear up the noise.
