### ISSUE TITLE
export-state not work

### ISSUE THREAD

**Issue by jasl** [paritytech/substrate#13274]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

```
2023-01-30 12:39:06 [Relaychain] ✨ Imported #16416470 (0xa409…2dff)
...
~/bin/polkadot export-state --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot/chains/ksmcc3 16416470 > kusama.json
2023-01-30 12:42:15 👶 Creating empty BABE epoch changes on what appears to be first startup.
2023-01-30 12:42:15 Essential task `transaction-pool-task-1` failed. Shutting down service.
2023-01-30 12:42:15 Essential task `transaction-pool-task-0` failed. Shutting down service.
2023-01-30 12:42:15 Essential task `txpool-background` failed. Shutting down service.
2023-01-30 12:42:15 Essential task `basic-block-import-worker` failed. Shutting down service.
2023-01-30 12:42:15 Exporting raw state...
Error:
   0: UnknownBlock: Expect block hash from id: BlockId::Number(16416470)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

As the timestamp show `16416470` this block definitely a freash block

### Steps to reproduce

`~/bin/polkadot export-state 16416470` given a fresh enough block number or hash, can be reproduced on all Substrate-based node including parachains.

here I'm using polkadot v0.9.37

**Comment by ggwpez** [comment]
Could you please still try the `chain-info` command to verify that the block exists?

**Comment by jasl** [comment]
> Could you please still try the `chain-info` command to verify that the block exists? Is that block already finalized?

It's weird, the output like this

```
phala@prb:~/tmp$ ~/bin/polkadot chain-info --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot/chains/ksmcc3
{
  "best_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "best_number": 0,
  "genesis_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_number": 0
}
```

I expose the node to public, you can access the blcok via https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcomputing-node.phala.network%2Fkusama%2Fws#/explorer/query/16416470

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/1024162/215575548-7a5d388d-6ca3-4474-9a40-6d93506935d3.png">

**Comment by jasl** [comment]
Here's the node info from polkadot.js
<img width="897" alt="image" src="https://user-images.githubusercontent.com/1024162/215575973-76c05788-2314-4a57-b3fd-0b122a0f5759.png">

**Comment by jasl** [comment]
The node is a fresh syncing from our parachain node (based on Polkadot v0.9.36) and upgraded to v0.9.37 before its fully synced

**Comment by koute** [comment]
cc @michalkucharczyk Based on the error message perhaps this is related to your block ID -> block hash refactoring?

**Comment by jasl** [comment]
I'm guessing https://github.com/paritytech/substrate/issues/13269 the root cause is the same

**Comment by bkchr** [comment]
> phala@prb:~/tmp$ ~/bin/polkadot chain-info --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot/chains/ksmcc3
> {
>   "best_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
>   "best_number": 0,
>   "genesis_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
>   "finalized_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
>   "finalized_number": 0
> }

How did you sync the node? Can you provide the exact CLI params?

**Comment by jasl** [comment]
> > phala@prb:~/tmp$ ~/bin/polkadot chain-info --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot/chains/ksmcc3
> > {
> > "best_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
> > "best_number": 0,
> > "genesis_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
> > "finalized_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
> > "finalized_number": 0
> > }
> 
> How did you sync the node? Can you provide the exact CLI params?

I sync the node use our `khala-node` based on v0.9.36 branch (then changed to 0.9.37)

minimum CLI (removed assign port, node name, etc.) is

```
khala-node \
  --chain khala \
  --base-path $DATA_PATH \
  --pruning archive \
  --database paritydb \
  -- \
  --chain kusama \
  --pruning archive \
  --database paritydb
```

I haven't try
 
```
polkadot \
  --chain kusama \
  --pruning archive \
  --database paritydb
```

but maybe can reproduce the issue

**Comment by jasl** [comment]
I do more dig... here's some interesting,

First, `export-state` works, I shouldn't specify to `ksmcc3` folder,
instead, I should
`~/bin/polkadot export-state --chain kusama --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot 16566800` point to the "root path" then specify `--chain kusama`

`chain-info` should do the same way,
```
~/bin/polkadot chain-info --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot --chain kusama
{
  "best_hash": "0x61c952dc7bbae52ebc658d728f9601e619972226b36ad591234e9daf60e93243",
  "best_number": 16566810,
  "genesis_hash": "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe",
  "finalized_hash": "0x989ee1495c3b5de52755688abb00239509f6969b72f14ba80b56b30832042548",
  "finalized_number": 16566808
}%
```
I can got correct info now.

The interesting things is, my previous reply 

```
~/bin/polkadot chain-info --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot/chains/ksmcc3
{
  "best_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "best_number": 0,
  "genesis_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_number": 0
}%
```

It has returns, but totally wrong compares to correct one.
and

```
phala@prb:~$ ~/bin/polkadot chain-info --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot/
{
  "best_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "best_number": 0,
  "genesis_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_number": 0
}%
phala@prb:~$ ~/bin/polkadot chain-info --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot/chains
{
  "best_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "best_number": 0,
  "genesis_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_number": 0
}%
phala@prb:~$ ~/bin/polkadot chain-info --database paritydb --base-path /data/172.21.88.5/khala-node/polkadot/chains/ksmcc3
{
  "best_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "best_number": 0,
  "genesis_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
  "finalized_number": 0
}%
```

In Polkadot (actually it's Kusama) folder, it alwys returns the same info.

when outside Polkadot foldat,

```
~/bin/polkadot chain-info --database paritydb --base-path /data/172.21.88.5/khala-node/
{
  "best_hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "best_number": 0,
  "genesis_hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "finalized_hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "finalized_number": 0
}%
```

it returns all zero.

So, the `export-state` works, but I believe there must has something not right,
do you guys have idea?

**Comment by bkchr** [comment]
Your problem being that one base path can host multiple databases. In the `chains` folder in the base path there will be one directory per chain. The directory depends on the name in the chain spec. When you point the base path to a "Kusama base path" and don't specify `--chain kusama` it will load Polkadot. As you there isn't any Polkadot db created yet in the `chains` folder it will create a new one that correctly only contains genesis. So, everything works as expected. Going to close the issue.
