### ISSUE TITLE
:open_umbrella: Formalize `Pallet` and `Call` docs

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13299]
The FRAME team realized that `Pallet` and pallet `Call` documentation should be more formalized and probably have some templates to them.  
Ultimately this can be CI checked by parsing the docs with a macro and comparing against the templates.  
This should help to have a unified basis to build higher-level docs upon

First step would be to agree on a structure for the pallet level docs and `README` requirements for them.  

(cc @lisa-parity in case you have some ideas)

**Comment by lisa-parity** [comment]
@ggwpez, this is really cool. I do have some ideas about this. I'll try. to sketch out a sample template next week.

**Comment by bkchr** [comment]
CC https://github.com/paritytech/frame-metadata/issues/47

**Comment by kianenigma** [comment]
A step toward this is https://github.com/paritytech/substrate/pull/13341

Right now, we have a section in the docs of some pallet that repeats the dispatchables. This should be just replaced with these modules.

**Comment by lisa-parity** [comment]
At a high level, it would be nice for every pallet to cover the following, where applicable:

- Purpose (what it's for, why it's important, the use case or problem it addresses)
- Specialized terminology (though it would be great if it wasn't required)
- Public functions
- Private functions
- How it work diagram/description
- Dependencies
- Storage items
- Events
- Errors
- Examples

I gather PR #13341 is about automating the collection of information.

**Comment by bkchr** [comment]
> * Public functions
> 
> * Private functions
>
> * Dependencies
> 
> * Storage items
> 
> * Events
> 
> * Errors

All of these don't need to be in the "high level" docs. The high level docs, as the name indicate should be a on a high level. How does the pallet work, what is it doing etc. Basically all the other things you mentioned there!

**Comment by ggwpez** [comment]
I tried out some scheme for the [MQ pallet](https://docs.rs/pallet-message-queue/24.0.0/pallet_message_queue/), and it basically turned into these sections:

- Abstract: One to three sentences about what the pallet does. Not how or why, just what.
- Design goals: Outline all specific goals of this pallet. This helps with understanding why stuff was designed in a specific way.
- Design: Explain how it is designed and why it was chosen to do so. Should reference the design goals and how they are achieved.
- Scenarios: Code examples together with explanations on how the pallet will internally process the example code. (note: examples are missing from the MQ pallet docs)
- Terminology

Diagrams would be nice, but so far i did not find a good way for ASCII diagrams or something suitable for rust doc.

**Comment by kianenigma** [comment]
> Diagrams would be nice, but so far i did not find a good way for ASCII diagrams or something suitable for rust doc.
Another thing missing would be the Purpose probably…

Have you seen [`mermaide`](https://mermaid.live/edit#pako:eNplU22vmjAU_itdE-MXYYDAVT7chHG3hEWmoRJvBn6oUCe50JLaZnOG_74Kd1fUJk045zzPeXk4PcOcFQR6MKOj0bmkpfDAeSwOpCZjb0yJFBxX47YdjTKa0X3FfucHzAVYxBkF6hzl7hfHzQEsqQqUtPdeDlqnX5LwZbEFmvYMUJCi-kIMGFUpc7G9IgecoAOH9O3TgxOxqixKccoGNT6qR_goCAdrKRgvcXVF9J10CeJ046MIxJKKsiZAA99iP_q6ve3gcuIOvvJjP90ApMYlBUAkl1xVV7RA1rKSx8EAhBbDrno-Wi6W6ebz8j7DO09x3sveC7nfd0oOZekHSPw08ZtGtYBqVhVsqGHid5DAX4UPztV3lKoLVOyRgeTudT0odTXvOwx_rNOQKplZQzjelVUvx2sQbT8Amq5rzyi4teNbM_EzCiewJrzGZaFW73yJZ7Bbugx66rPA_C1TK9kqHFb_FJ1oDj3BJZlA2RRYkJcSK7nq_84G05-MDU3oneEf6JmObli2O3Ptmes8TV3LnMAT9KwnW587lmHMTMuZmrbVTuDfLoGhu5ZrO7Zp2nNzOrcNewKJ2jvGo_6hdO-l_QeaquaK) It will probably have a rendered for rust-docs.

**Comment by kianenigma** [comment]
This is my suggestion. The main alteration I have is to make the docs read from "high level" to "low level". So something like design and design goals should be all the way at the end, as this is a very low level implementation note. 

```
//! # Pallet Name
//!
//! <single-liner about the pallet>.
//! 
//! ## High Level
//! 
//! ### Terminology
//! 
//! <Optionally, contain any custom terminology before going furhter>
//! 
//! ### Details 
//! 
//! <a few paragrphs, focus on what external folks should know about the pallet>
//! 
//! ### Example
//! 
//! <If there is one or two major user journeys in this palelt, export the test code here as example>. 
//! 
//! ## Code Details 
//! 
//! See [`pallet`] module. 
//! 
//! ## Implementation Details 
//! 
//! ### Design Goals
//! 
//! Describe your goals with with the pallet design.
//! 
//! ### Design 
//! 
//! Describe how you reach those goals. This should namely describe how your storage is laid out. 
```
