### ISSUE TITLE
[Fix] try_state in BagsList needs to be feature-gated and the signature has to adhere to that in Hooks.

### ISSUE THREAD

**Issue by ruseinov** [paritytech/substrate#13293]
The current BagsList implementation does not feature-gate try_state and nor does it have an argument for block number.

As a consequence a bunch of other pallets/tests are calling a variety of `try_state` methods outside of `try-runtime` context. What this means is we need to feature gate all the instances of `try_state` related to BagsList pallet and make sure we have a decent substitute to call within tests/benchmarks, similar to `do_try_state` in staking pallet.

**Comment by kianenigma** [comment]
Please chose the right "domain" part in the project as well :)

**Comment by ruseinov** [comment]
> Please chose the right "domain" part in the project as well :)

Yep, the github UI was hiding this under a grey link `+ 1 more` so I was always missing it. Lesson learned :)
