### ISSUE TITLE
ext_ed25519_verify weird return convention

### ISSUE THREAD

**Issue by kyegupov** [paritytech/substrate#1331]
`ext_ed25519_verify` function provided to the Wasm module has an extremely weird return convention: it returns 0 for true and 5 for false. This is confusing and undocumented. Ideally, it should be converted to more conventional 0 for false, 1 for true. Or, at the very least, documented in places like https://github.com/paritytech/substrate/blob/e54390219631fd81438aff7d60a153b362a001c1/core/sr-io/without_std.rs#L81

**Comment by gavofyork** [comment]
it's an internal API and not meant for public consumption. if you want to verify a signature, use `sr_io::ed25519_verify`, which is well-documented.

**Comment by kyegupov** [comment]
I'm working on a non-Rust implementation of the WASM modules, so I cannot use `sr_io::ed25519_verify` and "ext" functions are therefore a public API for me.

**Comment by bkchr** [comment]
@kyegupov the behavior is indeed a little bit weird. But in C you also often have `0` for no error and I think that is the case for this function. 
If you prepare a pr with some documentation, I would be willing to merge it.
