### ISSUE TITLE
Block import notification for literally every imported block even when the chain is not synced to the tip

### ISSUE THREAD

**Issue by liuchengxu** [paritytech/substrate#13315]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I'm looking for a block import notification that is fired on every imported block, the existing `client.import_notification_stream()` is fired only when on the tip or there is a re-org.

https://github.com/paritytech/substrate/blob/dfc9223f5d28b258c7762012ae7ef48a7a7f1359/client/service/src/client/client.rs#L774-L775

In subspace, we have the consensus chain and execution chain, the execution chain is entirely driven by the consensus chain. Each domain block is derived from a consensus block in a deterministic way, we need a block notification of every single consensus block to build the execution chain accordingly even if the consensus chain is not fully synced.

Currently, we're using a custom block notification sent during the stage of consensus-level block import, but it has an issue (https://github.com/subspace/subspace/issues/1143) that some states might be unusable when the notification is received by the handler because the block import pipeline is not yet completed.

**Comment by bkchr** [comment]
I would accept a pr adding a second method `import_notification_stream_good_name` that gives you the opportunity to get such a stream. Internally we should then have two vecs of notification receivers based on what kind of condition they are receiving block notifications.

**Comment by liuchengxu** [comment]
Any chance we can change the semantic of `import_notification_stream`, concretely speaking,

- `partial_import_notification_stream`: Fired when the chain is synced to the tip or there is a re-org.
- `import_notification_stream`: Fired on every single block no matter what the sync state is.

This clearly requires larger changes, but I do think `partial_import_notification_stream` (or `recent_import_notification_stream`?) describes better the current behavior, the bigger reason is that I honestly don't a good concise name for `import_notification_stream_good_name`, naming is hard :P
