### ISSUE TITLE
Simple way to verify bootnodes

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13318]
Currently it requires manually running a command for each bootnode and understanding the CLI output to check if it is valid. 
It would be nice to have a simple way to validate that a list boot nodes is valid. This is great to have for CI uses.

Maybe this could be done with a sub-command or free-standing CLI @paritytech/sdk-node.

**Comment by bkchr** [comment]
No, this is clearly nothing we should integrate. This can be a standalone utility using libp2p. Nevertheless, nothing that should be integrated into Substrate.
