### ISSUE TITLE
Runtime: rename `pub type UncheckedExtrinsic` to `pub type RuntimeExtrinsic`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#13329]
Because this is what it really is. The fact that it is called `UncheckedExtrinsic` under the hood is totally irrelevant. 

This is the final extrinsic type of the runtime. It could be *unchecked* or not. It could have a signature or not. 

It should just be called `RuntimeExtrinsic` :D

**Comment by cardotrejos** [comment]
I would like to take this also :D

**Comment by kianenigma** [comment]
This should only update types used in the runtime. It should not be a breaking change in the metadata et.

**Comment by kianenigma** [comment]
Probably not worth it.

**Comment by kianenigma** [comment]
Also being addressed in https://github.com/paritytech/substrate/issues/14126
