### ISSUE TITLE
Support `storage_alias` for `CountedStorageMap`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13353]
`storage_alias` should support `CountedStorageMap` but does not.

**Comment by ruseinov** [comment]
There was a ticket somewhere that was discussing getting rid of storage_alias altogether. I'm suspecting that it will render this one irrelevant then.

**Comment by bkchr** [comment]
Which ticket? Why should we remove this?

**Comment by ruseinov** [comment]
> Which ticket? Why should we remove this?

Disregard, it stuck in my mind, but it had to do with storage getters.

**Comment by ruseinov** [comment]
Will take this on, might be needing this soon.
