### ISSUE TITLE
Pallet-NFTs protected public types

### ISSUE THREAD

**Issue by DanHenton** [paritytech/substrate#13368]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The NFTs pallet protects types exposed in its extrinsic function arguments, resulting in its inability to be extended. 

Specifically the `create` extrinsic exposes the types `AccountIdLookupOf<T>` and `CollectionConfigFor<T, I>`. However, these types are protected (not explicitly public) so a custom pallet that is extending the NFTs pallet (tightly coupled) is unable to use these types.

I'm proposing to change the type [AccountIdLookupOf<T> ](https://github.com/paritytech/substrate/blob/master/frame/nfts/src/lib.rs#L63) to be declared as `pub type AccountIdLookupOf<T> ...` 

as well as removing the `(super)` protection for the declaration of the [CollectionConfigFor](https://github.com/paritytech/substrate/blob/master/frame/nfts/src/types.rs#L59) to be `pub CollectionConfigFor<T, I = ()> ....` fixes extendablity issues.

Example: 
Let's say I would like to add some additional logic around the creation of an NFT collection within a custom pallet that is tightly coupled to the pallet_nfts::Config. This extrinsic is called `custom_nft_create` which takes the same arguments as the pallet_nfts `create` with some additional logic that would be added around the creation of a collection. In this example, let's ignore the fact that the NFTs pallet could be called directly, by-passing this custom logic :wink: 

```rust
// ... pallet imports & declaration...

#[pallet::call]
impl<T: Config<I>, I: 'static> Pallet<T, I> {
	#[pallet::call_index(0)]
	#[pallet::weight(0)]
	pub fn custom_nft_create(
		origin: OriginFor<T>,
		admin: pallet_nfts::AccountIdLookupOf<T>,
		config: pallet_nfts::CollectionConfigFor<T, I>,
	) -> DispatchResult {
		let _signer = ensure_signed(origin.clone())?;

                // Custom logic ...

		let res = pallet_nfts::Pallet::<T, I>::create(origin, admin, config);
		
                // Additional Custom logic ...
			
		Ok(())
		}
	}
```

I've forked substrate and tested these changes against my custom pallet similar to the example, and publicly exposing these two types fixed my issue. Please let me know if the team agrees to these changes and I can create a PR.

**Comment by bkchr** [comment]
These are just type declarations. Nothing special. We have these in multiple pallets, I would just copy them. 

@jsidorenko

**Comment by jsidorenko** [comment]
I don't think you can call the `CollectionConfigFor` from your pallet since it takes the config and instance of the nfts pallet as params and not yours.
You should either put `CollectionConfig<Price, BlockNumber, CollectionId>` substituting the `Price, BlockNumber, CollectionId` or simply copy&paste the same `CollectionConfigFor` wrapper into your pallet. The same applies for `AccountIdLookupOf`

**Comment by bkchr** [comment]
> I don't think you can call the `CollectionConfigFor<T, I>` from your pallet since it takes the config and instance of the nfts pallet as params and not yours.

If the `pallet_nft::Config` trait is a super trait of the other pallet `Config` trait, this will still work.

**Comment by DanHenton** [comment]
Thanks for the feedback, I've gotten the following implementation to work without exposing the protected types of the pallet_nfts following your suggestions. 

First off I define a duplicate of `AccountIdLookupOf` then we need to define `BalanceOf` which refers to the balance of the currency defined in `pallet_nfts`.

Thirdly I define the extrinsic argument `config` ensuring that It gets the types it requires: 
```rust
config: pallet_nfts::CollectionConfig<
        BalanceOf<T, I>,
	<T as SystemConfig>::BlockNumber,
	<T as pallet_nfts::Config<I>>::CollectionId,
>,
```

The full pallet implementation of this example pallet: 
```rust
#![cfg_attr(not(feature = "std"), no_std)]

use frame_support::traits::{Currency, ReservableCurrency};

pub use pallet::*;
use sp_runtime::traits::StaticLookup;

use frame_system::Config as SystemConfig;
type AccountIdLookupOf<T> = <<T as SystemConfig>::Lookup as StaticLookup>::Source;

type BalanceOf<T, I = ()> =
	<<T as pallet_nfts::Config<I>>::Currency as Currency<<T as SystemConfig>::AccountId>>::Balance;

#[frame_support::pallet]
pub mod pallet {
	use super::*;
	use frame_support::pallet_prelude::*;
	use frame_system::pallet_prelude::*;

	#[pallet::pallet]
	#[pallet::generate_store(pub(super) trait Store)]
	pub struct Pallet<T, I = ()>(_);

	/// Configure the pallet by specifying the parameters and types on which it depends.
	#[pallet::config]
	pub trait Config<I: 'static = ()>: frame_system::Config + pallet_nfts::Config<I> {
		type RuntimeEvent: From<Event<Self, I>>
			+ IsType<<Self as frame_system::Config>::RuntimeEvent>;
	}

	#[pallet::event]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config<I>, I: 'static = ()> {}

	// Errors inform users that something went wrong.
	#[pallet::error]
	pub enum Error<T, I = ()> {}

	#[pallet::call]
	impl<T: Config<I>, I: 'static> Pallet<T, I> {
		#[pallet::call_index(0)]
		#[pallet::weight(0)]
		pub fn custom_nft_create(
			origin: OriginFor<T>,
			admin: AccountIdLookupOf<T>,
			config: pallet_nfts::CollectionConfig<
				BalanceOf<T, I>,
				<T as SystemConfig>::BlockNumber,
				<T as pallet_nfts::Config<I>>::CollectionId,
			>,
		) -> DispatchResult {
			let _signer = ensure_signed(origin.clone())?;

			pallet_nfts::Pallet::<T, I>::create(origin, admin, config)
		}
	}
}

```
