### ISSUE TITLE
Kusama/Polkadot (v0.9.37) is having memory-leak-like pattern on GCP VMs

### ISSUE THREAD

**Issue by yujun-onf** [paritytech/substrate#13371]
We are using polkadot-v0.9.37 and we are experiencing some memory-leak-like issue on the polkadot/kusama nodes.
![Screenshot 2023-02-07 at 11 39 03 AM](https://user-images.githubusercontent.com/125226489/218347724-958dd6f2-4fbb-4563-a704-040fe8cda5c1.png)

<img width="1080" alt="Screenshot 2023-02-10 at 4 48 13 PM" src="https://user-images.githubusercontent.com/125226489/218347730-2b46dcea-e774-4d72-8ec6-2fd5204923ae.png">
![Screenshot 2023-02-07 at 11 39 54 AM](https://user-images.githubusercontent.com/125226489/218347753-e666cab4-95d0-4704-b18a-800f7a27d274.png)

We also host polkadot/kusama nodes on other providers (for example AWS), but it did not seems to have the same pattern.
![Screenshot 2023-02-07 at 11 39 54 AM](https://user-images.githubusercontent.com/125226489/218347792-082a433d-8e6d-42da-ba26-66335663050f.png)

On GCP we used n1-standard-16 (16 vCPU 60GB Mem) for hosting.

Here's our launch parameters

```
--base-path=/chain-data

--rpc-cors=all

--port=30333

--rpc-port=9933

--ws-port=9944

--ws-external

--rpc-external

--node-key=key_here

--pruning=archive

--rpc-methods=Safe

--name=name_here

--chain=kusama

--db-cache=3500

--in-peers=10000

--out-peers=50
```
Please kindly advise if there's any fix for this issue. Thank you!

**Comment by bkchr** [comment]
CC @koute

**Comment by koute** [comment]
Since you're running in archive mode, is this an RPC node you're running? And is it a *public* RPC node, or a private one?

**Comment by jamesbayly** [comment]
This particular node is a test one, but yes we commonly run public and private RPC nodes in this configuration

**Comment by koute** [comment]
So can I assume people you don't know are connecting to this node? (Which is important because we have seen similar patterns on our public RPC nodes.)

There are some known issues on 0.9.37 which were fixed in 0.9.38 (not all them though); you might want to consider grabbing the 0.9.38 prerelease (since it's not released *yet*) and give that a test and see if it fixes your problem/makes things better.

**Comment by AlexZhenWang** [comment]
> Since you're running in archive mode, is this an RPC node you're running? And is it a _public_ RPC node, or a private one?

Yes, this is a public RPC node.

**Comment by AlexZhenWang** [comment]
> So can I assume people you don't know are connecting to this node? (Which is important because we have seen similar patterns on our public RPC nodes.)
> 
> There are some known issues on 0.9.37 which were fixed in 0.9.38 (not all them though); you might want to consider grabbing the 0.9.38 prerelease (since it's not released _yet_) and give that a test and see if it fixes your problem/makes things better.

Yes, we don't know who is connecting to this node. Thank you, we would like to try and test the new 0.9.39 version. Is the prereleased version available on dockerhub?

**Comment by jamesbayly** [comment]
Not yet https://hub.docker.com/r/parity/polkadot/tags

@koute  would you be able to let us know when the new version is published?

**Comment by koute** [comment]
@jamesbayly Sure.

**Comment by koute** [comment]
@jamesbayly New version was just released [available here](https://github.com/paritytech/polkadot/releases/tag/v0.9.38) and [here](https://hub.docker.com/layers/parity/polkadot/v0.9.38/images/sha256-766d84cded1ec536732407a0317a8ec668933f411cb1e17f907ec047c3be2a82?context=explore).

**Comment by jamesbayly** [comment]
Memory usage is looking a lot better since upgrading, thanks
