### ISSUE TITLE
Sufficient account still needs native token to receive non-sufficient assets

### ISSUE THREAD

**Issue by olanod** [paritytech/substrate#13420]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Users having an account with a sufficient asset like USDT on Statemine are required to have an existential amount of KSM to be able to receive other tokens that are not sufficient, this takes users by surprise as they expect USDT in this case to be enough and be able to use it to pay fees for other token transfers.

### Steps to reproduce

Example in Statemine:
- Send USDT to a new account
- Send a different asset to the newly created account that holds no KSM
- The transaction fails

**Comment by juangirini** [comment]
That behaviour is expected as USDT does not contribute to the ED, which in this case should be KSM. The reason why you can send USDT is because it is sufficient, meaning that it does not require any ED.
If you want other tokens to behave as USDT, they'll need to be created as 'sufficient'.
