### ISSUE TITLE
[REPO] Consider adding an "Issue Priority"

### ISSUE THREAD

**Issue by abebeos** [paritytech/substrate#13442]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The bug issues are not prioritized. This makes it difficult to focus on relevant issues - especially (but not only) for newcomers:

https://github.com/paritytech/substrate/issues?q=is%3Aopen+is%3Aissue+label%3AI3-bug+sort%3Aupdated-asc

Consider adding some kind of priority to the issues

*  the `U2-some_time_soon` and similar U-labels.

### Steps to reproduce

Go through the bug issues, and try to identify the most important ones:

https://github.com/paritytech/substrate/issues?q=is%3Aopen+is%3Aissue+label%3AI3-bug+sort%3Aupdated-asc

**Comment by ggwpez** [comment]
Putting priorities on issues and having tasks for newcomers are two independent problems.  
Newcomers can search for https://github.com/paritytech/substrate/labels/Z6-mentor issues.

**Comment by abebeos** [comment]
?

- not all newcomers need mentors
- some newcomers can mentor the regulars (e.g in issue-tracking standard-procedures, refactoring, code-elegance etc. etc.)

As an example, I entered the go-algorand project, fixed bugs and reduced duplicated code - naturally without a mentor.

but! What is very difficult for a (High xp or not ) newcomer is to identify issue priorities.

In any way, if you (or this project) think that issue/bug priorities are not necessary, then stick to it and close this.

(though its really a must have)

**Comment by abebeos** [comment]
Just noticed that it exists already, the `U2-some_time_soon` and similar U-labels. Updated text.

**Comment by ggwpez** [comment]
Yea there are priority labels. But they are not enforced and every team / dev uses them differently.  
I am not in a position nor want to tell how other people should use labels.

We normally use the "mentor" label on free-standing issues that can be worked on asynchronously. Not necessarily that you need supervision.

**Comment by abebeos** [comment]
> Yea there are priority labels. But they are not enforced and every team / dev uses them differently.

This is standard-procedure, really not much space for things like "individuality" etc.

> I am not in a position

Who is? (usually project lead or CTO)

-

>We normally use the "mentor" label on free-standing issues that can be worked on asynchronously. Not necessarily that you need supervision.

You sure? This sounds very(!) confusing.

In any way, I start to get exhausted here, asking to get what should be already there.

To speed things up: Is there any chance to get priorities on the bug issues?

**Comment by abebeos** [comment]
> If bugs in general are high priority they are taken on directly,

Thus all open bugs have a low priority. Ok.

> start requesting these things because you know them from other projects

I know them because they are standard-procedure. 

IT pros usually do not discuss those "things".

> issues with the mentor label for external people that don't require that much help from someone working on the project full time.

Mentor issues are for juniors and dummies.

Me neither of those.

Closing, as I'll loose my cool if I see one more time the word "mentor"...
