### ISSUE TITLE
[REPO] Update Milestones

### ISSUE THREAD

**Issue by abebeos** [paritytech/substrate#13455]
(Enhancement)

## Status

https://github.com/paritytech/substrate/milestones

### Should be closed

* ~https://github.com/paritytech/substrate/milestone/14~
* ~https://github.com/paritytech/substrate/milestone/35~
* ~https://github.com/paritytech/substrate/milestone/34~

### Should be moved to a "Project"

* https://github.com/paritytech/substrate/milestone/8
* https://github.com/paritytech/substrate/milestone/5

**Comment by ggwpez** [comment]
Yea we can probably close all of them?! Looks stale since two years.  
At least: Polakdot v0.9.30, v0.9.31 and 2.x series.

**Comment by abebeos** [comment]
3 are gone. The remaining 2:

## Polkadot

20 Issues

https://github.com/paritytech/substrate/milestone/8

Suggestion here is:

- either add a label `Polkadot`
- or move to a Project dedicated to Polkadot
  -  https://github.com/paritytech/substrate/projects

## Ideas

104 Issues

https://github.com/paritytech/substrate/milestone/5

- move to a Project, like "Low Priority"

(using "Milestones" to collect random issues was necessary in the past, but not anymore, now that github has the projects).

(if this stays as-is, just close the issue please, the obsolete milestones are gone, so its fine now for me)
