### ISSUE TITLE
Issues with query_storage* RPC calls

### ISSUE THREAD

**Issue by DamianStraszak** [paritytech/substrate#13469]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

**ISSUE1:**

I'm not sure this is well known but the `state_queryStorageAt` RPC call does not really do what the documentation (and the function signature) suggests. So according to this
![image](https://user-images.githubusercontent.com/23038619/221256023-eeedba64-ae87-4ac6-9772-646b6498594c.png)
the call `query_storage_at([k], at)` should return a vector `v = [changes]` consisting of one element (corresponding to key `k`), and `changes` should be the list of all changes to the value under `k` starting from block `at` till the current `best`. Instead, the list `changes` contains always EXACTLY ONE ELEMENT -- the value under `k` at block `at`. This is also consistent with what the code does:
![image](https://user-images.githubusercontent.com/23038619/221256803-08176ad6-c854-4713-b785-1cf6eeec0cde.png)
so this calls `query_storage` with `from` equal to `to`, and hence the problem.

I can perfectly understand that this RPC query couldn't stay `safe` if it did what the doc says (because of pretty much unbounded output size), but currently the behavior of this method is highly unintuitive, given it's signature and documentation.

**ISSUE2:**

There is also a related RPC method `query_storage`, which is unsafe, and does pretty much the same as `query_storage_at` promises to do (but with arbitrary pair of blocks `from` -- `to`). However, the implementation of this method seems to be unnecessarily naive and thus inefficient, see below
![image](https://user-images.githubusercontent.com/23038619/221258320-b9dbd0b9-49ec-4675-905e-aa53b6f18887.png)
So, it iterates over all blocks in the range and queries the key at every block from the range. 
I'm not an expert on the storage backend in substrate, but I would expect that asking for all changes of a key `k` in a range of blocks `[from, to]` should be doable in complexity `O(RESULT_SIZE)` (with perhaps a large constant hidden in the big-oh notation) rather than `O(to-from)` like it is now. From what I know, there is no query, or combination of RPC queries that allows to achieve this goal efficiently, so having such a query implemented optimally would actually be great.

**Comment by bkchr** [comment]
> I'm not an expert on the storage backend in substrate, but I would expect that asking for all changes of a key `k` in a range of blocks `[from, to]` should be doable in complexity `O(RESULT_SIZE)` (with perhaps a large constant hidden in the big-oh notation) rather than `O(to-from)` like it is now.

What makes you think this? If I understand you correctly, you assume there should be a much more efficient way to find out in which blocks a value changed?

**Comment by DamianStraszak** [comment]
I was thinking that given a node in the persistent merkle tree that holds some value (i.e. corresponding to a key in the state) there is a way to relatively quickly fetch its "previous, historical" version. But if that's not the case, then I guess issue 2 is not possible to resolve -- in that case my suggestion would be to actually warn in the docs, that you can OOM your node by issuing this RPC query with a large segment of blocks :P

**Comment by bkchr** [comment]
Goes a little bit into the direction of: https://github.com/paritytech/substrate/issues/13434

In general yes, we are working on revamping the jsonrpc interface to make it robust against these kind of issues.

CC @koute

**Comment by DamianStraszak** [comment]
Ok, so conclusion:

ISSUE1: the problem here is that the docs and the function signature are just super confusing -- by no means one could guess what this ACTUALLY outputs without testing it beforehand. But on the other hand we cannot really change the output type, because it would break all libraries.
ISSUE2: this is slow, and eats a lot of memory, and probably cannot be made faster. I think the best we can do is warn the user about this being slow and memory-heavy in the docs.

I will just make a PR with some minor changes to the docs/comments. Is that alright?

**Comment by bkchr** [comment]
> I will just make a PR with some minor changes to the docs/comments. Is that alright?

Yes please!

RPC is slowly being reworked to have a better and more understandable api: https://github.com/paritytech/json-rpc-interface-spec

**Comment by DamianStraszak** [comment]
Sorry for the delay, but the PR is finally here https://github.com/paritytech/substrate/pull/13698 

The issue can be closed -- whatever happens with the PR, should address it, I guess.
