### ISSUE TITLE
How to start a GRANDPA blockchain without any initial voters? 

### ISSUE THREAD

**Issue by Kofituo** [paritytech/substrate#13464]
I've tried modifying the repository so initial voters for the grandpa pallet. In doing so, I noticed there are many checks to prevent that modification. 
The reason why we do not want any initial voters is to prevent hardcoding of some node properties in the chain_spec file. Hardcoded validators in the chain_spec file could be a target for Ddos attacks among others.
So I'd like to know why the initial voters are required with the grandpa pallet and how to do without them.
Are there any security reasons or advantages to having initial voters specified in the chain_spec file?

**Comment by abebeos** [comment]
Hi there!

My understanding of the processes of the substrate project are that support questions should be asked on:

https://substrate.stackexchange.com/

You'll probably get an answer there faster.

**Comment by abebeos** [comment]
Follow-up: https://substrate.stackexchange.com/questions/7352/how-to-start-a-grandpa-blockchain-without-any-initial-voters

**Comment by bkchr** [comment]
Answered on stackexchange.
