### ISSUE TITLE
Verification failed: Could not fetch authorities 

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1346]
I have an internal testnet running with 3 validators and 3 full client nodes.
I tried a small testing script that submit 100 transfer transactions and cause the client nodes stop importing blocks. I didn't realize it happened and few hours later submitted another 100 transfer transactions and this time cause the 3 validators stuck in some inconsistent state and brick the chain.

I have another node running a (bricked) fork attempting connecting to the validators that stuck at block 62138.

Now the client nodes stuck at block 87349 and the validators stuck at block 91252
Some relevant logs:
https://gist.github.com/xlc/8bc42d33f439b5628c66fe8e813c80ec
validator 1 have RUST_LOG=debug

I tried restart the validators but they will not connect to each other anymore

**Comment by rphmeier** [comment]
I have seen similar very occasionally. Might be a DB write issue.

**Comment by gavofyork** [comment]
@xlc have you seen this issue recently?

**Comment by xlc** [comment]
Not this one anymore. Will reopen if happens again.
