### ISSUE TITLE
[COREDEV] introduce a PR test-process

### ISSUE THREAD

**Issue by abebeos** [paritytech/substrate#13470]
Next time we should ad some zombienet test for syncing to ensure we don't break it again :D

_Originally posted by @bkchr in https://github.com/paritytech/substrate/pull/13409#pullrequestreview-1303575686_
            
Process should be mandatory

(example)

### Mandatory "zombienet" Test

* if your change affects xyz
  * use zombienet-n for testing (pre Merge)
    * via cli 'docker ...'

### Mandatory Regression Test

* if you revert a merge (commit, PR), either
  * provide a new **automated regression test** that catches the error 
    * or (in the case an automation is not possible or high effort)
      * provide a **manual regression test** step in the Core Developer Manual

**Comment by bkchr** [comment]
We have a test process and always extending our tests. You will not find that much prs that go in without any new tests.

**Comment by abebeos** [comment]
@bkchr , two things:

- clearly, you've not understood the essence of this issue.

This is not about your test-process(es), but mostly about a process that ensures that test-processes are always extended when an new incident occurs.

- I believe that your tendency to close issues that fast introduces risk to the substrate project and all its consumers.

**Comment by bkchr** [comment]
> but mostly about a process that ensures that test-processes are always extended when an new incident occurs.

As I said, this is already things we are doing. We have added dozens of tests to ensure that incidents are not gonna happen again.

**Comment by abebeos** [comment]
> > but mostly about a process that ensures that test-processes are always extended when an new incident occurs.
> 
> As I said, this is already things we are doing. We have added dozens of tests to ensure that incidents are not gonna happen again.

Again: You ignore (or do not see ) the essence.

Anyways, issue is closed.

**Comment by bkchr** [comment]
Then please inform me, what is the essence? Maybe I'm missing it. Sorry

**Comment by abebeos** [comment]
>> ### Mandatory
