### ISSUE TITLE
The paging file is too small for this operation to complete

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/substrate#13487]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Just upgraded Substrate to latest `master` in our chain and got Window CI failure: https://github.com/subspace/subspace/actions/runs/4289871755/jobs/7473325743

This test that didn't fail before started failing: https://github.com/subspace/subspace/blob/4e660669fa32560aa658b255fddc9b4b7d38ac73/domains/client/block-builder/src/lib.rs#L356-L387
> thread 'tests::block_building_storage_proof_does_not_include_runtime_by_default' panicked at 'Due to validation `initial` and `maximum` should be valid: Memory("encountered failure while operating with virtual memory: System call failed: The paging file is too small for this operation to complete. (os error 1455)")', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmi-0.13.2\src\module.rs:358:18

The only PR we imported that I think might be somehow related is https://github.com/paritytech/substrate/pull/12520, but as far as I understand it was supposed to not change behavior unless opt-in into growable memory.

### Steps to reproduce

Clone branch from https://github.com/subspace/subspace/pull/1198, `cd domains/client/block-builder`, `cargo test`

**Comment by bkchr** [comment]
Does the mentioned test works with `wasmtime`? I'm sorry that this breaks on Windows, but we also not officially support Windows. I would advise that you stop using `wasmi`: https://github.com/paritytech/substrate/issues/13496

**Comment by liuchengxu** [comment]
Yes, using `wasmtime` is fine.

**Comment by bkchr** [comment]
Going to close this then!
