### ISSUE TITLE
Remove `wasmi` as `sc-executor` backend

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#13496]
`wasmi` should be removed as `sc-executor` backend. It was quite useful in the early days, but it will never be as fast as `wasmtime` which is currently the de-facto standard in Substrate. For the beginning it should probably be enough to just remove the crate and keep the current structure with `sc-executor`/`sc-executor-wasmtime`. In the future we may could merge these both crates as well to remove unneeded code and to simplify the entire structure.

**Comment by bkchr** [comment]
`wasmtime` is already the default since quite some time.

**Comment by liuchengxu** [comment]
I notice Interpreted is still used as the default in some places though, probably nicer to update them to use Compiled and deprecate Interpreted.

https://github.com/paritytech/substrate/blob/e374a33fe1d99d59eb24a08981090bdb4503e81b/test-utils/client/src/lib.rs#L289

https://github.com/paritytech/substrate/blob/024bfcedb15c8421a90f0834f73a7b529c502c0b/client/executor/src/wasm_runtime.rs#L55-L58

**Comment by koute** [comment]
> As substrate is a framework, shouldn't this removal be done via a deprecation process?

For any practical use-case  the `wasmi`-based executor is useless as it's too slow, and it's mostly still here for historical reasons. No one should really be using it, but people do end up still accidentally using it since it's there, and then they encounter weird issues (either because it's too slow, or because almost no one uses it so it receives very little testing).

It makes sense to just remove it.

**Comment by abebeos** [comment]
> useless
> No one should really be using it
> but people do end up still accidentally using it

### core dev manual

No functionality should be removed without a deprecation warning period. In rust code, Use construct xyz...

**Comment by bkchr** [comment]
Just because we remove the backend, doesn't mean that we can not put out these warnings. Especially for users (which hopefully don't use it) we can print warnings.

**Comment by abebeos** [comment]
> Just because we remove the backend, doesn't mean that we can not put out these warnings.

I talk about functionality-deprecation.

You talk about functionality-slaughter.

All good, just go on.

**Comment by abebeos** [comment]
> Not sure why we should keep something around that is not maintained anymore.

Not "keep"...

>>As substrate is a framework, shouldn't this removal be done via a deprecation process?

=> remove via a deprecation-process (= standard practice)

**Comment by yjhmelody** [comment]
I could cleanup wasmi-executor, It's not hard for me to remove it.

**Comment by bkchr** [comment]
@yjhmelody feel free to remove it!!
