### ISSUE TITLE
storage_alias with StorageDoubleMap clear_prefix does not respect limit

### ISSUE THREAD

**Issue by wilwade** [paritytech/substrate#13506]
### Is there an existing issue?

- [X] I have searched the existing issues
- Potentially related, but appears to be fixed? https://github.com/paritytech/substrate/issues/426

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Assumptions:

- `[StorageDoubleMap Struct]::prefix_hash()` will generate a key that can be used as the prefix for all values in the Double Map.
- `frame_support::storage::unhashed::clear_prefix` can be used with the ^ prefix to remove all values (up to a limit) in the Double Map

Situation:
- I have `StorageDoubleMap` Struct `Data`
- I fill up `Data` with 10 unique values for both keys
- A `key` from `Data::prefix_hash()`
- I then call `frame_support::storage::unhashed::clear_prefix(&key, Some(5), None);`

Expected:
- If I then retrieve the count using `Data::iter().count()` I should retrieve the entire count of all values stored in the `StorageDoubleMap`.
    - Called *before* `clear_prefix`: Expected Value = 10
    - Called *after* `clear_prefix`: Expected Value = 5

Actual:
- Called *before* `clear_prefix`: Actual Value = 10 Correct!
- Called *after* `clear_prefix`: Actual Value = 0 WRONG!

### Steps to reproduce

Test is in this fork: https://github.com/paritytech/substrate/compare/master...wilwade:substrate:master

```rust
#[test]
fn storage_alias_with_clear_prefix_works() {
  new_test_ext().execute_with(|| {
      use crate::storage::generator::StorageDoubleMap;
      #[crate::storage_alias]
      type GenericData<T> = StorageDoubleMap<
        Test,
        Blake2_128Concat,
        <T as Config>::BlockNumber,
        Blake2_128Concat,
        <T as Config>::BlockNumber,
        <T as Config>::BlockNumber,
      >;
      
      for i in 0..10 {
        GenericData::<Test>::insert(i, i, i);
      }
      
      // Has stuff!
      assert_eq!(GenericData::<Test>::iter().count(), 10);
      
      let key = GenericData::<Test>::prefix_hash();
      let result =
      frame_support::storage::unhashed::clear_prefix(&key, Some(5), None);
      
      // Fails. It is 0 now, but it should still have 5
      assert_eq!(GenericData::<Test>::iter().count(), 5);
      // Fails. It returns that it cleared 5, but it actually clears 10 and should only be 5.
      assert_eq!(result.unique, 5);
  });
}
```

**Comment by bkchr** [comment]
```
#[test]
fn storage_alias_with_clear_prefix_works() {
  use crate::storage::generator::StorageDoubleMap;
      #[crate::storage_alias]
      type GenericData<T> = StorageDoubleMap<
        Test,
        Blake2_128Concat,
        <T as Config>::BlockNumber,
        Blake2_128Concat,
        <T as Config>::BlockNumber,
        <T as Config>::BlockNumber,
      >;

  let mut ext = new_test_ext();
  ext.execute_with(|| {
      for i in 0..10 {
        GenericData::<Test>::insert(i, i, i);
      }
});

// This is being important to ensure we don't have all values in the backend!
ext.commit_all().unwrap();
      
ext.execute_with(|| {
      // Has stuff!
      assert_eq!(GenericData::<Test>::iter().count(), 10);
      
      let key = GenericData::<Test>::prefix_hash();
      let result =
      frame_support::storage::unhashed::clear_prefix(&key, Some(5), None);
      
      // Fails. It is 0 now, but it should still have 5
      assert_eq!(GenericData::<Test>::iter().count(), 5);
      // Fails. It returns that it cleared 5, but it actually clears 10 and should only be 5.
      assert_eq!(result.unique, 5);
  });
}
```

This should do it. If you check the docs of `clear_prefix`, you will see that it mentions "remove all values under the first key `k1` in the overlay". In your case you only worked with the overlay, so you need to ensure to commit your changes to the backend. When building/importing a block this would mean all the values written in the block before calling `clear_prefix` will be deleted as all of them are in the overlay. From the backend it will then delete `limit` keys matching the given `prefix`. I hope that makes sense!

**Comment by wilwade** [comment]
That was it! Thanks. Updated the test in my example to now work and placed below as well if others want the final working version:

```rust
#[test]
fn storage_alias_with_clear_prefix_works() {
  use crate::storage::generator::StorageDoubleMap;
  #[crate::storage_alias]
  type GenericData<T> = StorageDoubleMap<
    Test,
    Blake2_128Concat,
    <T as Config>::BlockNumber,
    Blake2_128Concat,
    <T as Config>::BlockNumber,
    <T as Config>::BlockNumber,
  >;
  
  let mut ext = new_test_ext();
  ext.execute_with(|| {
    // Setup
    for i in 0..10 {
      GenericData::<Test>::insert(i, i, i);
    }
  });
  
  // Commit the changes so we aren't just working with the overlay storage
  ext.commit_all().unwrap();
  
  ext.execute_with(|| {
    // Has stuff!
    assert_eq!(GenericData::<Test>::iter().count(), 10);
    
    let key = GenericData::<Test>::prefix_hash();
    let result =
    frame_support::storage::unhashed::clear_prefix(&key, Some(5), None);
    
    assert_eq!(GenericData::<Test>::iter().count(), 5);
    assert_eq!(result.unique, 5);
  });
}
```
