### ISSUE TITLE
Improperly formatted upgrades stop the chain from progressing.

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#1352]
We're experimenting with doing upgrade using a CLI that we're currently developing. I am reading in the `compact.wasm` blob as a string and then converting it to the respective polkadot type (array of U8). I am then sending a transaction with this array to upgrade our runtime with the upgrade key, however, whenever I do so it crashes/halts the progress of the chain.

I get the following errors upon sending such a transaction:
```
{ next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })))                                                                                     
2019-01-04 23:37:19 Aura authorship task terminated unexpectedly. Restarting
2019-01-04 23:37:19 Idle (0 peers), best: #10151 (0xdc09…6b4d)
2019-01-04 23:37:19 Idle (0 peers), best: #10151 (0xdc09…6b4d)
2019-01-04 23:37:19 Random Kademlia request has yielded empty results
2019-01-04 23:37:20 Idle (0 peers), best: #10151 (0xdc09…6b4d)
2019-01-04 23:37:25 Idle (0 peers), 
...
...
(infinite stalling, no block proposing)
```

How should upgrades be formatted in pureJS? I want to use functionality that exists in the UI but it seems generalised to the extent that I cannot figure out.

**Comment by rphmeier** [comment]
> Improperly formatted upgrades stop the chain from progressing

There are a lot of ways to brick the chain -- providing bad runtime code is unfortunately one of them. There isn't a way to fix that specifically.

@jacogr @amaurymartiny What are you using to encode the runtime upgrades in the UI?

**Comment by jacogr** [comment]
Ok, so there are 2 approaches, depending on what you have available on your chain -

- substrate-ui used upgradeKey - so basically encode the tx, submit
- polkadot-js/apps uses proposals - so basically encode proposal submit, needs a vote (Sure way to brick your chain found here - https://github.com/polkadot-js/api/blob/master/packages/api/test/e2e/promise-tx.spec.js#L37)

I'm guess what is hapenning here is that the extrinsic is not properly encoded, i.e. maybe the length is missing (although that would throw it out earlier).

**Comment by drewstone** [comment]
I am using the `upgradeKey` approach. Reading in the WASM blob as a string, and converting it to Bytes as it expects.

**Comment by jacogr** [comment]
And the Bytes is properly encoded with the length prefix? (Anything `Vec<u8>` needs the length prefix to be usable by the runtime)

**Comment by drewstone** [comment]
Looking at our code we seem to have already been using the `compactAddLength(stringToU8a(s));` but I will test out with reading to a buffer and get back to you. Thanks!

**Comment by jacogr** [comment]
Ok, with the hex, you don't need to add the length it will be done automatically (yes, confusing, I know).

```
const hex = '0x' + fs.readFileSync(args[0]).toString('hex');

api.tx.upgradeKey.upgrade(hex).sign(...).send();
```
