### ISSUE TITLE
unexpected argument 'prepare-worker' found

### ISSUE THREAD

**Issue by jasl** [paritytech/substrate#13553]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Background:
I bullt a parachain test-net using polkadot-launch (it doesn't matter here, just a context).
Then I run another collator and validator on another VM.

I'm lazy so I just configure the parachain node (based on polkadot v0.9.37), both running as collator and validator, the cli looks like
```
khala-node \
--collator
--
--validator
```

few days later, I check its log, and found interesting output

```
2023-03-07 09:08:12 [Parachain] ✨ Imported #128336 (0xfebc…2287)
error: unexpected argument 'prepare-worker' found
Usage: khala-node [OPTIONS] [-- <RELAYCHAIN_ARGS>...]
       khala-node <COMMAND>
For more information, try '--help'.
2023-03-07 09:08:15 [Relaychain] failed to spawn a prepare worker: AcceptTimeout
2023-03-07 09:08:15 [Parachain] 💤 Idle (5 peers), best: #128335 (0x6086…832c), finalized #128334 (0xa446…e1ca), ⬇ 3.3kiB/s ⬆ 1.0kiB/s
2023-03-07 09:08:15 [Relaychain] 💤 Idle (9 peers), best: #274406 (0xf853…9f63), finalized #274404 (0xc3d2…e47b), ⬇ 7.8kiB/s ⬆ 4.6kiB/s
2023-03-07 09:08:18 [Relaychain] ✨ Imported #274407 (0xead2…4768)
error: unexpected argument 'prepare-worker' found
Usage: khala-node [OPTIONS] [-- <RELAYCHAIN_ARGS>...]
       khala-node <COMMAND>
For more information, try '--help'
```

it seems doesn't affect the node working, I can see it producing new blocks as normal validator and collator, and for a substrate node it definitley don't have `prepare-worker` option.

Restart the node will made the error disappear for minutes, then it comes again

### Steps to reproduce

I can't sure this can 100% reproduce

Run a parachain node as collator and validator, also need to configure on parachain and relaychain

**Comment by bkchr** [comment]
`prepare-worker` is a `Polkadot` sub-command. This is being used by validators to fork themselves to create a worker that is then being used to validate Parachain wasm blobs. This means in your case that this relay chain validator will not support validating parachain PoVs. However, we currently don't support running a validator alongside a collator. If you really need this feature, please open a new issue in Cumulus for this. Thank you, otherwise I'm going to close this now.
