### ISSUE TITLE
contracts: Add host function tracing

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#13593]
For contract (language) authors it can be a helpful debugging tool to see which host functions (functions exposed by pallet-contracts)  are called with which arguments and what was the result. It is of similar use as the popular `strace` tool on linux.

This can be implemented within the `define_env` macro. We should use the `log` create to emit a log line **after** each host function was called. We do it after because then we can also display the result on the same line. All code is panic free and can't divert. So there is no way that we miss a host function call on error.

Example of how it might look in the macro:

```rust
log::trace!(target: "runtime::contracts::strace", "#func_name(#arg_name0: {arg_val0}, #arg_name1: {arg_val1})={result}")
```

We use the `trace` log level and a sub target of contracts. In general, all log levels are compiled into a node (substrate as a library does not supply any features to `log`). At runtime `trace` is disabled by default. Having it disabled/enabled at runtime is fine for our use case. It just adds some code and data to the runtime binary but the expensive string formatting isn't performed.

Size conscious runtimes can always supply a feature to `log` in their build to remove those logs.

- [ ] Implement feature
- [ ] Add section to README about host function tracing
- [ ] Rebench to make sure this actually doesn't affect performance
- [ ] Compare sizes of the kitchensink runtime before and after the change

Assign to @pgherveou as soon as he is added to paritytech.

cc @xermicus @cmichi

**Comment by xermicus** [comment]
In solang we implemented [this feature](https://github.com/hyperledger/solang/blob/main/integration/substrate/debug_buffer_format.spec.ts#L29) in the contract directly (opt-in). What are the benefits of doing this on the host node?

**Comment by pgherveou** [comment]
Nice will look into this, after I wrap up #13600 
is there a special encoding / message format to use for interpreting the raw bytes from the debug_buffer  on the frontend?

**Comment by athei** [comment]
There is no structure to the debug buffer except that it is UTF-8 encoded. So just adding lines to it is the way to go.

**Comment by pgherveou** [comment]
@athei @xermicus 
added a PR for the implementation of the host function tracing calls here #13648 , I have a few more TODOs to complete on the PR but let me know if that match what you had in mind for the feature before I wrap up the PR.

I added a few screenshots with the trace output.
