### ISSUE TITLE
[Multi-Asset Treasury] Make the Pay trait in salary pallet generic over assets and central

### ISSUE THREAD

**Issue by tonyalaribe** [paritytech/substrate#13603]
### Motivation

The Pay trait is a very useful trait, as the multi-asset treasury could be implemented based off said trait, instead of forcing the treasury pallet to be implmented based off either fungible or fungibles. This brings for great flexibility.

### Request

Move the Pay trait out of the salary pallet (eg into frame_support), and make it generic over assets. This could be by adding an AssetId associated type or similar. The AssetId type could then be unit in the case of implementations that do not need to support multiple asset classes.

This is a step towards https://github.com/paritytech/polkadot/issues/5293

**Comment by franciscoaguirre** [comment]
I can grab this

**Comment by wischli** [comment]
Can this be closed as #13609 has been merged?
