### ISSUE TITLE
Build fails for nomination-pools pallet

### ISSUE THREAD

**Issue by vivekvpandya** [paritytech/substrate#13627]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

building nomination-pools test fails with attached error. 
[failed.txt](https://github.com/paritytech/substrate/files/11000871/failed.txt)

**Comment by vivekvpandya** [comment]
@kianenigma is this just rust version issue?

**Comment by ggwpez** [comment]
> ### Steps to reproduce
> _No response_

Pleas provide information about how to reproduce an issue. 

Looking at your log output:
>error: internal compiler error: unexpected panic
>note: the compiler unexpectedly panicked. this is a bug.

It is an ICE and not Substrates fault. Maybe try with stable instead of nightly.
