### ISSUE TITLE
Allow `Dispatchable` to return data

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#13642]
We want to improve the user experience of calling into the runtime from a contract (#13641). While a contract can [already call a `Dispatchable`](https://github.com/paritytech/substrate/blob/f8a1dd4c836d7d29382ba66fc2fce40fc1364546/frame/contracts/src/wasm/runtime.rs#L2371-L2424) only a subset of interactions can be crafted because a `Dispatchable` cannot return any data on success.

This is because a dispatchable  is required to return a `DispatchResult` which is defined as `Result<(), DispatchError>`. In order to allow for a proper interaction which includes querying data from the runtime we need to allow a `Dispatchable` to return any type that implements `Encode + TypeInfo`.

I think it is viable to support this in  backwards compatible matter without causing disruption: Whenever the `Dispatchable` is called by an extrinsic or from another place that doesn't need or want the output it is just discarded. This is not only useful for contracts but could also reduce the amount of runtime APIs that are basically getters: Instead of adding a new API to query data we could call a `Dispatchable` that returns data using `system_dryRun`. This potentially also allows RPC nodes to argue about the weight of operations they are performing for users.

Of course this change should be non breaking: Existing `Dispatchables` returning `()` should work as-is.

- [ ] Implement change that allows to return `Result<T, DispatchError> where T: Encode + TypeInfo` from a dispatchable.
- [ ] Check impact on emitted metadata.

**Comment by bkchr** [comment]
The problem is that people will expect that this also works for dispatchables included in a block. Then we expect people to send events and return values? Or we just add a lot of dummy runtime calls for returning values to contracts? I'm not convinced that this is a good way forward.

Your only problem with chain extensions is the benchmarking?

**Comment by xlc** [comment]
> This is not only useful for contracts but could also reduce the amount of runtime APIs that are basically getters

This makes no sense to me. Runtime APIs are getters. Dispatchables are setters. Why do I want my setters to be able to replace getters?

**Comment by xlc** [comment]
or we can weight annotate runtime API, which is actually a requirement because they are all public by default on RPC nodes and could be a DoS vector

**Comment by bkchr** [comment]
> So we probably want to design it more like a `Call`. We construct a type we might call `Getter` which is basically like `Call`. We then implement a new trait `Query` (like `Dispatchable`) on it. All the getters are then called via a single Wasm exported function which accepts `Getter`. From within the runtime we can call it directly by using `Query::query()`. This will allow a contract to pass an encoded `Query` to the runtime.

This sounds like a reasonable and good idea!

**Comment by athei** [comment]
Good :). Reposted into #13358. So we can probably close here then.
