### ISSUE TITLE
try-runtime pre-post hooks not executed if defined within the pallet

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#13681]
we have been increasingly using external migrations and have seemingly introduced a regression in how we define migrations, namely `pre-post` migration hooks within a pallet. Here's the most simple way to reproduce this: 

Apply this: 

```
diff --git a/Cargo.lock b/Cargo.lock
index 29ddf38328..d3200668fd 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -6506,6 +6506,7 @@ dependencies = [
  "sp-core",
  "sp-io",
  "sp-runtime",
+ "sp-std",
 ]
 
 [[package]]
diff --git a/bin/node-template/pallets/template/Cargo.toml b/bin/node-template/pallets/template/Cargo.toml
index f6607b25c4..6db219734d 100644
--- a/bin/node-template/pallets/template/Cargo.toml
+++ b/bin/node-template/pallets/template/Cargo.toml
@@ -20,6 +20,7 @@ scale-info = { version = "2.1.1", default-features = false, features = ["derive"
 frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../../../../frame/benchmarking" }
 frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/support" }
 frame-system = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/system" }
+sp-std = { path = "../../../../primitives/std", default-features = false }
 
 [dev-dependencies]
 sp-core = { version = "7.0.0", path = "../../../../primitives/core" }
diff --git a/bin/node-template/pallets/template/src/lib.rs b/bin/node-template/pallets/template/src/lib.rs
index 4630e344ad..3b760e06d6 100644
--- a/bin/node-template/pallets/template/src/lib.rs
+++ b/bin/node-template/pallets/template/src/lib.rs
@@ -30,6 +30,25 @@ pub mod pallet {
 		type RuntimeEvent: From<Event<Self>> + IsType<<Self as frame_system::Config>::RuntimeEvent>;
 	}
 
+	#[pallet::hooks]
+	impl<T: Config> Hooks<T::BlockNumber> for Pallet<T> {
+		fn on_runtime_upgrade() -> Weight {
+			Default::default()
+		}
+
+		#[cfg(feature = "try-runtime")]
+		fn pre_upgrade() -> Result<sp_std::prelude::Vec<u8>, &'static str> {
+			frame_support::log::info!(target: "pallet-template", "pre_upgrade");
+			Err("BOOOO")
+		}
+
+		#[cfg(feature = "try-runtime")]
+		fn post_upgrade(_state: sp_std::prelude::Vec<u8>) -> Result<(), &'static str> {
+			frame_support::log::info!(target: "pallet-template", "post_upgrade");
+			Ok(())
+		}
+	}
+
 	// The pallet's runtime storage items.
 	// https://docs.substrate.io/main-docs/build/runtime-storage/
 	#[pallet::storage]

```

Then:

```
# Run a base node: 
cargo remote run --  --release -p node-template -- --dev

# Build a try-runtime CLI and runtime 
cargo remote build --  --release --features try-runtime -p node-template
cargo remote build --  --release --features try-runtime -p node-template-runtime 

# Execute
RUST_LOG=pallet-template=trace,info ./target/release/node-template try-runtime --runtime ./target/release/wbuild/node-template-runtime/node_template_runtime.wasm on-runtime-upgrade live -u ws://localhost:9944
```

Logs won't be emitted, the error that I return in `pre_upgrade` is also not caught. Seems like the code is not really executed. 

Initially tested against `polkadot-9.38` branch. Probably present in master as well.

**Comment by ggwpez** [comment]
Did you try with `--checks`?  I think they are not run per default.

**Comment by ruseinov** [comment]
> Did you try with `--checks`? I think they are not run per default.

Going to try that right now, but according to [this](https://github.com/paritytech/substrate/pull/13045/files#diff-af56022c7cac51f6fb3bb9735da553e856d88e4cb366e213af7d800ea8e65433R43)  PR the only thing we need to add is —checks without value.

**Comment by ruseinov** [comment]
Confirmed, this works on `polkadot-v0.9.38` branch:

```
RUST_LOG=pallet-template=trace,info ./target/release/node-template try-runtime  --runtime ./target/release/wbuild/node-template-runtime/node_template_runtime.wasm on-runtime-upgrade --checks live -u ws://localhost:9944
```

**Comment by ggwpez** [comment]
Could you give us a commit hash to try this please @crystalin ?

**Comment by crystalin** [comment]
Here is the branch https://github.com/PureStake/moonbeam/tree/crystalin-broken-try-runtime
```
cargo build --release
```
```
./target/release/moonbeam try-runtime --wasm-execution compiled  --detailed-log-output --runtime target/release/wbuild/moonbase-runtime/moonbase_runtime.wasm -lXcmV2ToV3=trace,runtime=trace on-runtime-upgrade --checks=all live --uri wss://wss.api.moonbase.moonbeam.network:443 --at 0x9039446d397077d081ca1e6b9a2e0cc78cd78002ff39bbb3a76b5ee2b21c0106 --pallet AssetManager
```

**Comment by librelois** [comment]
I think that was break by #12537, this PR removed the pre/post_upgrade impl for tuples: https://github.com/paritytech/substrate/pull/12537/files#diff-1c449417be9803cb427eed15d51557931141d47d0047561407f1651d319f7103L205

And frame executive using a tuple:

```rust
<(COnRuntimeUpgrade, AllPalletsWithSystem) as OnRuntimeUpgrade>::try_on_runtime_upgrade(...)
```

**Comment by ggwpez** [comment]
I dont quite get it. Is this the problem? https://github.com/PureStake/moonbeam/blob/177c91eaa52348b68a5697327df94d464c943be8/runtime/moonbeam/src/lib.rs#L1184  
Since it is not calling `try_runtime_upgrade` like https://github.com/paritytech/substrate/blob/8f0b0f69e79c0dcf1487b9858792439c35a1d4cd/bin/node/runtime/src/lib.rs#L2350 does

**Comment by crystalin** [comment]
I don't know what `diener` is. Maybe @librelois can help here

**Comment by ggwpez** [comment]
How do you build moonbeam with a patched Substrate version? [Diener](https://github.com/paritytech/diener) can be used to patch Polkadot and Cumulus to local clones.

**Comment by crystalin** [comment]
edit the `.cargo/config.toml` and add
`paths=["../substrate"]`

In our case we use a fork of substrate `https://github.com/purestake/substrate/tree/moonbeam-polkadot-v0.9.38`

**Comment by kianenigma** [comment]
I am a bit confused by the current implementation that I have put there, it is a bit hard to argue about it -- looking further, but for now not easy to replicate a failing test: 

```diff
diff --git a/frame/support/src/lib.rs b/frame/support/src/lib.rs
index 4e9bc32b00..5e8cb9b4d4 100644
--- a/frame/support/src/lib.rs
+++ b/frame/support/src/lib.rs
@@ -371,16 +371,14 @@ macro_rules! parameter_types {
 
 			/// Set the value of this parameter type in the storage.
 			///
-			/// This needs to be executed in an externalities provided
-			/// environment.
+			/// This needs to be executed in an externalities provided environment.
 			pub fn set(value: &$type) {
 				$crate::storage::unhashed::put(&Self::key(), value);
 			}
 
 			/// Returns the value of this parameter type.
 			///
-			/// This needs to be executed in an externalities provided
-			/// environment.
+			/// This needs to be executed in an externalities provided environment.
 			#[allow(unused)]
 			pub fn get() -> $type {
 				$crate::storage::unhashed::get(&Self::key()).unwrap_or_else(|| $value)
diff --git a/frame/support/src/traits/hooks.rs b/frame/support/src/traits/hooks.rs
index a3374d0bf5..592d9733aa 100644
--- a/frame/support/src/traits/hooks.rs
+++ b/frame/support/src/traits/hooks.rs
@@ -197,10 +197,10 @@ impl OnRuntimeUpgrade for Tuple {
 		weight
 	}
 
-	#[cfg(feature = "try-runtime")]
 	/// We are executing pre- and post-checks sequentially in order to be able to test several
 	/// consecutive migrations for the same pallet without errors. Therefore pre and post upgrade
 	/// hooks for tuples are a noop.
+	#[cfg(feature = "try-runtime")]
 	fn try_on_runtime_upgrade(checks: bool) -> Result<Weight, &'static str> {
 		let mut weight = Weight::zero();
 		for_tuples!( #( weight = weight.saturating_add(Tuple::try_on_runtime_upgrade(checks)?); )* );
@@ -359,10 +359,64 @@ pub trait OnTimestampSet<Moment> {
 #[cfg(test)]
 mod tests {
 	use super::*;
+	use sp_io::TestExternalities;
+
+	#[test]
+	fn on_runtime_upgrade_pre_post_exeucted_tuple() {
+		crate::parameter_types! {
+			pub static Pre: Vec<&'static str> = Default::default();
+			pub static Post: Vec<&'static str> = Default::default();
+		}
+
+		macro_rules! impl_test_type {
+			($name:ident) => {
+				struct $name;
+				impl OnRuntimeUpgrade for $name {
+					fn on_runtime_upgrade() -> Weight {
+						Default::default()
+					}
+
+					#[cfg(feature = "try-runtime")]
+					fn pre_upgrade() -> Result<Vec<u8>, &'static str> {
+						Pre::mutate(|s| s.push(stringify!($name)));
+						Ok(Vec::new())
+					}
+
+					#[cfg(feature = "try-runtime")]
+					fn post_upgrade(_: Vec<u8>) -> Result<(), &'static str> {
+						Post::mutate(|s| s.push(stringify!($name)));
+						Ok(())
+					}
+				}
+			};
+		}
+
+		impl_test_type!(Foo);
+		impl_test_type!(Bar);
+		impl_test_type!(Baz);
+
+		TestExternalities::default().execute_with(|| {
+			Foo::try_on_runtime_upgrade(true).unwrap();
+			// todo unify the API for storage parameter_types! output.
+			assert_eq!(Pre::take(), vec!["Foo"]);
+			assert_eq!(Post::take(), vec!["Foo"]);
+
+			<(Foo, Bar, Baz)>::try_on_runtime_upgrade(true).unwrap();
+			assert_eq!(Pre::take(), vec!["Foo", "Bar", "Baz"]);
+			assert_eq!(Post::take(), vec!["Foo", "Bar", "Baz"]);
+
+			<((Foo, Bar), Baz)>::try_on_runtime_upgrade(true).unwrap();
+			assert_eq!(Pre::take(), vec!["Foo", "Bar", "Baz"]);
+			assert_eq!(Post::take(), vec!["Foo", "Bar", "Baz"]);
+
+			<(Foo, (Bar, Baz))>::try_on_runtime_upgrade(true).unwrap();
+			assert_eq!(Pre::take(), vec!["Foo", "Bar", "Baz"]);
+			assert_eq!(Post::take(), vec!["Foo", "Bar", "Baz"]);
+		});
+	}
 
 	#[test]
 	fn on_initialize_and_on_runtime_upgrade_weight_merge_works() {
-		use sp_io::TestExternalities;
 		struct Test;
 
 		impl OnInitialize<u8> for Test {

```

**Comment by crystalin** [comment]
@kianenigma is there something else we can do to help ? @librelois identified the part (the for_tuples) that is failing for us, but I don't know actually how it works and why it fixes it. Elois can help if you need

**Comment by tgmichel** [comment]
To follow up a bit on a temporary solution, I managed to run both pre and post upgrade tests by expanding what @crystalin suggested:

Add the following to https://github.com/paritytech/substrate/blob/6e81199eac74ce9a7bf3b1c720989031dd9b18a1/frame/support/src/traits/hooks.rs#L193

```
#[cfg(feature = "try-runtime")]
fn pre_upgrade() -> Result<Vec<u8>, &'static str> {
	let mut state: Vec<Vec<u8>> = Vec::default();
	for_tuples!( #( state.push(Tuple::pre_upgrade()?); )* );
	Ok(state.encode())
}

#[cfg(feature = "try-runtime")]
fn post_upgrade(state: Vec<u8>) -> Result<(), &'static str> {
	let state: Vec<Vec<u8>> = Decode::decode(&mut state.as_slice())
		.expect("the state parameter should be the same as pre_upgrade generated");
	let mut state_iter = state.into_iter();
	for_tuples!( #( Tuple::post_upgrade(
		state_iter.next().expect("the state parameter should be the same as pre_upgrade generated")
	)?; )* );
	Ok(())
} 
```

Which is essentially adding back what was removed in https://github.com/paritytech/substrate/pull/12319

**Comment by kianenigma** [comment]
I wonder if this actually got solved or not? perhaps this is still some bug in how `try_runtime_upgrade` is applied to pallets? 

This is all to some extent a consequence of the fact that we use `OnRuntimeUpgrade` directly in executive, and in pallets. 

In Parity Ops, we 99% use the former, so we rarely test the latter. Ideally, some integration tests should mimic a combination of the two.

**Comment by crystalin** [comment]
I confirm it is still NOT working in v0.9.43

**Comment by liamaharon** [comment]
> I confirm it is still NOT working in v0.9.43

Hey @crystalin this is on my list of things to look into. Do you have a branch I can reproduce that uses v0.9.43?

**Comment by liamaharon** [comment]
I see the issue, it seems due to Moonbeem using an old version of the `Executive` pallet.

The `Executive` `try_runtime_upgrade` method here needs to be updated: https://github.com/moonbeam-foundation/substrate/blob/95067ccc3a7683768f8a10036785cde8d5f8a098/frame/executive/src/lib.rs#L261-L272

to call `try_on_runtime_upgrade` instead of `pre_upgarde` and `post_upgrade` directly, like this:

https://github.com/paritytech/substrate/blob/48d4313151873e3ce8be877efb9e485649264f5e/frame/executive/src/lib.rs#L350-L384

To prevent this silent failure again, I'm going to implement Tuples for `pre_upgrade` and `post_upgrade` but just make it log an error prompting users to call `try_on_runtime_upgrade` instead.

**Comment by crystalin** [comment]
@liamaharon you are looking at a commit that is from April 2022 (more than a year late).
We are using 0.9.43 at the moment (and were using 0.9.40 at the time of the bug being reported IIRC), which included the change to `try_on_runtime_upgrade` :
https://github.com/moonbeam-foundation/substrate/blob/moonbeam-polkadot-v0.9.40/frame/executive/src/lib.rs#L348

**Comment by liamaharon** [comment]
I suspect your runtime is still trying to call the Tuples impl of `pre_upgrade` and `post_upgrade` because @tgmichel mentioned restoring their functionality fixed the issue https://github.com/paritytech/substrate/issues/13681#issuecomment-1486786058.

Can you add some logging into your Executive and `try_on_runtime_upgrade` tuples implementation to verify?
