### ISSUE TITLE
try-runtime can panic when RPC requests fail

### ISSUE THREAD

**Issue by liamaharon** [paritytech/substrate#13695]
If a node doesn't answer RPC requests correctly (for example if `--rpc-max-response-size` or `--rpc-max-request-size` are not configured correctly) then it panics and logs a [nasty output](https://gist.githubusercontent.com/liamaharon/3b695417290fe16880d229862b971358/raw/31ee15d0e9e0257ade3a09c40156481cbc8211be/gistfile1.txt). 

Rather than panicing, the cli should exit gracefully and suggest to the user that they check their node config.

**Comment by ggwpez** [comment]
The batch error in particular can be fixed by https://github.com/paritytech/substrate/issues/13562.

**Comment by liamaharon** [comment]
Closing in favor of https://github.com/paritytech/substrate/issues/13246
