### ISSUE TITLE
RPC calls -> Author -> rotateKeys generates 64 bytes key 

### ISSUE THREAD

**Issue by tapiocaboy** [paritytech/substrate#13719]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Im trying out session pallet and validador set pallet , for a selected dev account (charlie) I am executing an RPC call for rotateKey and it returns this 

<img width="1218" alt="Screenshot 2023-03-27 at 11 01 40 PM" src="https://user-images.githubusercontent.com/4618861/227910537-375dc773-219b-45db-a30a-67fea70b753a.png">

How ever when I try to add this key on `session` setkeys extrinsic it gives the following errror

<img width="1227" alt="Screenshot 2023-03-27 at 11 05 58 PM" src="https://user-images.githubusercontent.com/4618861/227911124-ca347b31-09e9-4d50-85a3-075a3dcc3571.png">

Should this be returning a 3 bit key ?

### Steps to reproduce

Try to do a key rotation for a dev account
Try to submit the key(s) as an extrinsic using  session -> setKeys

**Comment by bkchr** [comment]
> But looks like you have two separate input fields instead... probably a different polkadot js version or something you customized ? (I'm not the expert for this).

Yeah that is the "problem" here. @jacogr any idea why it is split for him?

**Comment by tapiocaboy** [comment]
@davxy Im not using a different POlkadotJS app , I am following this https://github.com/gautamdhameja/substrate-validator-set

**Comment by tapiocaboy** [comment]
@davxy Im not using a different POlkadotJS app , I am following this https://github.com/gautamdhameja/substrate-validator-set

**Comment by jacogr** [comment]
The way in which people rotate their keys (including me) -

- run `curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "author_rotateKeys", "params":[]}' http://localhost:9933` on your server (not via RPC pane - servers are not exposed to the internet, and should never be)
- go to staking -> accounts -> set session, paste output
- submit

When you go into extrinsics - you need to know what you are working with.

**Comment by tapiocaboy** [comment]
@jacogr how to prevent expose these to the internet ?

**Comment by jacogr** [comment]
Off the top of my head -

- Ensure that your firewall only allows the p2p connections/ports in/out. (No RPC ports, ever - tie it down)
- You probably want to run your RPC on a non-default port anyway (via `--rpc-port` just in case you muck something up in the first point)
- Don't run RPC + validating at the same time - you only need RPC when you rotate/insert

I'm sure there are guides out there somewhere with best-practices.

**Comment by bkchr** [comment]
Going to close this now as all the questions should be answered!

**Comment by tapiocaboy** [comment]
Well, whats the solution for the original issue? not sure its been handled

**Comment by bkchr** [comment]
> * go to staking -> accounts -> set session, paste output (all staking interactions are managed here, not via extrinsics - unless advanced usage)

This
