### ISSUE TITLE
add _(force_origin) support to benchmarking v2

### ISSUE THREAD

**Issue by sam0x17** [paritytech/substrate#13721]
In benchmarking v1 we used to be able to do:

```rust
let force_origin =
	T::ForceEnterOrigin::try_successful_origin().map_err(|_| BenchmarkError::Weightless)?;
#[extrinsic_call]
_<T::RuntimeOrigin>(force_origin)

```

In v2, this doesn't seem to work, and we have to instead do:
```rust
let force_origin =
	T::ForceEnterOrigin::try_successful_origin().map_err(|_| BenchmarkError::Weightless)?;
let call = Call::<T>::force_enter {};
#[block]
{
	call.dispatch_bypass_filter(force_origin)?;
}

```

We should be able to upgrade v2 syntax to do something like this:

```rust
let force_origin =
	T::ForceEnterOrigin::try_successful_origin().map_err(|_| BenchmarkError::Weightless)?;
#[extrinsic_call]
_(force_origin);

```

Should be an easy fix but will have to be careful about what compiler errors get emitted in the event that `force_origin` or whatever variable we put there isn't a valid origin

**Comment by sam0x17** [comment]
btw if it wasn't clear in my description, the main syntax change here is making this a legal syntax in benchmarking v2:
```rust
#[extrinsic_call]
_(some_variable_name);
```

We may need some additional assertions to ensure that the provided variable is an origin, but won't know that until we see the compiler error when you provide something random like a u32 or a String and see what it does

**Comment by sam0x17** [comment]
edit: if _possible_, would be cool to have `_(some_special_origin)` but otherwise the custom origin type syntax from v1 where it was like `_<T::RuntimeOrigin>(force_origin)` would be perfectly fine

**Comment by ggwpez** [comment]
>otherwise the custom origin type syntax from v1 where it was like _<T::RuntimeOrigin>(force_origin) would be perfectly fine. I think we probably have to do it that way

Yes IMHO this is the most extensible way, in case that there are other origin types. Maybe we can have a more compact syntax as follow-up.
