### ISSUE TITLE
Add GitHub handle to pallet-identity

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13728]
(I cant find an issue in case this was already proposed)

Would be nice to have GitHub handles in the identity data. Especially with the Polkadot fellowship being so reliant on it.  
They are automatically verifiable by registrates via edited profile text, so no problem.

**Comment by bkchr** [comment]
We can just add the github handle the to the additional fields? https://github.com/paritytech/substrate/blob/6ef33adec7123f7d61757cad010993322099bbe7/frame/identity/src/types.rs#L293

**Comment by ggwpez** [comment]
For example one person writes "Github handle", the next "github" and so on. Its probably easier to extend the enum since we have `Twitter` and `Riot` it is already opinionated.

**Comment by bkchr** [comment]
> For example one person writes "Github handle", the next "github" and so on.

Yes, but then you need to specify what kind of key is the correct one.

> Its probably easier to extend the enum since we have `Twitter` and `Riot` it is already opinionated.

I would argue that this should not have been done and it should have been generic from the beginning.

**Comment by ggwpez** [comment]
> I would argue that this should not have been done and it should have been generic from the beginning.

Yea probably better to start with this. Then we can inject the "custom" type via the config trait.

**Comment by bkchr** [comment]
Closing in favor of: https://github.com/paritytech/substrate/issues/14026
