### ISSUE TITLE
Run `integrity_test` in externalities

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#13726]
We should probably run *all* of then inside externalities. In the past I was concerned about unintended consequences, but it just annoyed us again in: https://github.com/paritytech/polkadot/pull/6957

Since there a parameter type was configured to be `storage` instead of `const`, so it would fail outside externalities.

**Comment by ggwpez** [comment]
Note: There are cases were we explicitly want to run something outside of externalities.  
For example complicated weight annotations in [pallet alliance](https://github.com/paritytech/substrate/blob/73b1bb43a451654017e7eec7cf2d50efcacc3e26/frame/alliance/src/lib.rs#L890) use config constants. These could be factored out into helper functions and ran outside of externalities as a test to ensure that they dont access state.

**Comment by bkchr** [comment]
I don't see any problem in using `storage` `parameter_type!` if there is a justification. Before we started to make all of them "const' all of these parameters where stored in the storage. However, it doesn't make any sense to read something from the storage that isn't ever changing. But some implementations may have a reason to have some value dynamic.

**Comment by ggwpez** [comment]
So you mean that reading storage in weight annotations is fine? Or how does your comment relate to mine?  
Someone on [SE](https://github.com/paritytech/polkadot/blob/dbae30efe080a1d41fe54ef4da8af47614c9ca93/runtime/parachains/src/initializer.rs#L215) pointed out that Polkadot does this.

**Comment by bkchr** [comment]
I mean reading storage for the weight needs to be done with a lot of caution to not open a DDOS door.

The linked weight looks wrong as the weight should not depend on the number of digests.

**Comment by ggwpez** [comment]
You can always create externalities in the `integrity_test`, like here https://github.com/paritytech/substrate/pull/13092/files so this should not block you.  
Although we can also run the test in externalities per default, the only catch would be that the genesis state is not configurable, which could be weird.

**Comment by atenjin** [comment]
@ggwpez oh thanks, but in fact our panic appears from transaction-payment pallet 🤣🤣🤣
