### ISSUE TITLE
Upgrades breaking progress/liveness using Polkadot utils.

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#1376]
For background, there was an issue doing a chain upgrade with formatted strings here: https://github.com/paritytech/substrate/issues/1352. The approach could be summed up as
```
const str = fs.readFileSync(args[0]).toString();
convertedArgs = [compactAddLength(stringToU8a(str))];
```

I am now using the hex encoded approach now and getting new errors. After the upgrade is proposed and included and some time has passed it seems the node fails to build blocks:
```
2019-01-09 17:25:02 Idle (0 peers), best: #36 (0x32d2…8bee)
Hash not equal
4a78c498b2e353da5b9002a39b710c7f6dcb3376773ab317ae305da167fbfced
0f3314b575c754a378fead372431706e0f46e8822c7a0eb4deab62abadc12dc7
/Users/drewstone/.cargo/git/checkouts/substrate-7e08433d4c370a21/c695efe/srml/executive/src/lib.rs
218
3
2019-01-09 17:25:06 Error with block built on 0x32d20630ccd323b2766536c929f24950a40c4ad8012c837551e939be89858bee: Error(Execution(Error(Wasmi(Trap(Trap { kind: Unreachable })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

Here is a snippet of how I'm constructing it using the api.
```
const hex = '0x' + fs.readFileSync(args[0]).toString('hex');
convertedArgs = [compactAddLength(hexToU8a(hex))];
```

**Comment by jacogr** [comment]
(Re-posted comment)

Ok, with the hex, you don't need to add the length it will be done automatically (yes, confusing, I know).

```
const hex = '0x' + fs.readFileSync(args[0]).toString('hex');

api.tx.upgradeKey.upgrade(hex).sign(...).send();
```

**Comment by drewstone** [comment]
Ok, without the length encoding I get the original error:
```
2019-01-09 17:37:50 Failed to construct block: Error(Inner(Error(Execution(Error(InvalidCode([]), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })))
```

**Comment by jacogr** [comment]
Ok, that is weird. Running an exact test locally now.

**Comment by drewstone** [comment]
Does it matter that I'm using the `compact` WASM blog and not the regular non-compact one?

**Comment by jacogr** [comment]
Ok, I have updated the sample I have to load a WASM file 

https://github.com/polkadot-js/api/blob/1ebeac059aec293853bd93d2d24e670344814028/docs/examples/promise/10_upgrade_chain/index.js

And I get this exact output, i.e. the chain has been upgraded -

```
➜  10_upgrade_chain git:(jg-derive-dep) ✗ yarn start
yarn run v1.12.3
$ node index.js
Upgrading from 5GoKvZWG5ZPYL1WUovuHW3zJBWBP5eT8CbqjdRY4Q6iMaDtZ with nonce 4 , 771301 bytes
Transaction status: Finalised
You have just upgraded your chain
Completed at block hash 0xf4cbd3cdae912115514b1166a829bdf55d324a6721f722593e4dccc9bca63439
Events:
	 ApplyExtrinsic : upgradeKey.Upgraded []
	 ApplyExtrinsic : system.ExtrinsicSuccess []
✨  Done in 9.23s.
```

**Comment by drewstone** [comment]
Ok, this should be enough to get it working for us even though the stars are not aligned for me right now haha.

**Comment by jacogr** [comment]
There is some funky stuff happening when you do supply weird runtimes - i.e. trying to upload the test runtime, could get into an Aura loop. (Same with trying to upload a polkadot runtime to a substrate one)

So you need to make sure these match. (It has improved already, previously it didn't have the `InvalidCode` checks, so it has gotten more robust)
