### ISSUE TITLE
Allow custom origin to provide_judgement for identity pallet

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#13777]
This will allow custom origin such as some OpenGov track to provide judgement without registrar

**Comment by bkchr** [comment]
This can then be used for example for the fellowship to provide judgment for identities of fellowship members.

**Comment by xlc** [comment]
We might not need this because governance body can transact with signed account over XCM.

**Comment by xlc** [comment]
I will say it is cleaner to reuse an existing mechanism. But anyway, if we do want to support custom origins, there are two possible approaches:

1. Update the `ForceOrigin` so that it can actually provide judgement and modify Polkadot/Kusama config to include the Fellow origin to `ForceOrigin`
2. Modify registrar so that it is no longer `AccountId` but `RuntimeOrigin` and then we can do governance call to add the Fellow origin as a registrar. This requires migration. No change of Polkadot/Kusama config required.
3. Or does nothing 

I personally prefer 3 but happy to do 1 or 2 as well. Let me know what do you think.

**Comment by bkchr** [comment]
> 3\. Or do nothing and use the signed account from XCM. This requires a governance call to add the account into registrar.

Yeah probably the best to go with this for now. Everything else would require some bigger refactorings as you said. I also looked over the code and would say that the entire pallet should get some bigger refactoring.

**Comment by xlc** [comment]
We will allow the Fellows to have a sovereign account instead.
