### ISSUE TITLE
parameter_types! helper functions should be uniform across modes

### ISSUE THREAD

**Issue by liamaharon** [paritytech/substrate#13795]
The `parameter_types` works in 3 modes. 

1. static (generates thread_local stuff)
2. storage 
3. const 

All of which generate a `Get` implementation, backed by something, along some other helper functions like `get`, `set`, `mutate` and `take` (kinda similar to storage items..). 

It seemed to me that the set of helper functions that is generated by `parameter_types!` is not uniform across different modes. 

If interested, you can convert this comment into an issue and self-assign.

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/pull/13794#discussion_r1154819729_

**Comment by ggwpez** [comment]
We and dowstream projects use those in many spots. Just having a breaking change here for beauty is not that of a good idea IMHO.  
Unless we can stay backwards compatible. Maybe we can give all of them storage traits?

**Comment by bkchr** [comment]
> It seemed to me that the set of helper functions that is generated by `parameter_types!` is not uniform across different modes.

You can not give all of them uniform functions. `const` for example can not be set/mutated/taken. The `static` implementation for example also can not be "taken".

**Comment by kianenigma** [comment]
What I originally suggested is entirely backwards compatible. It seemed that some functions are missing, and adding them would make the API more uniform.

**Comment by bkchr** [comment]
And which are missing?

**Comment by liamaharon** [comment]
From what I could gather, these are the differences in mode:

- const: Generates a const getter function named get.

- No prefix (non-const): Generates a non-const getter function named get.

- storage: Generates getter and setter functions. It also generates a key function to get the storage key.

- static: Generates getter and setter functions. It also generates thread_local code.

The differences in API between seem irreconcilable at first glance, e.g. it doesn't make sense for `const` to have a setter, or for the `static` mode to have a `key`.

**Comment by bkchr** [comment]
> The differences in API between seem irreconcilable at first glance, e.g. it doesn't make sense for `const` to have a setter, or for the `static` mode to have a `key`.

As I tried to explain above.

**Comment by kianenigma** [comment]
Got it, I have jumped too fast at making it an issue them. Thanks for the explanation(s), closing.
