### ISSUE TITLE
block pruning wrong

### ISSUE THREAD

**Issue by zjb0807** [paritytech/substrate#13790]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

It seems that only 255 blocks can be found. When the query range exceeds 255, the block is pruned and cannot be found.

When the block height is 259, querying block 0 fails
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16496415/229119533-3e800483-315e-4a20-8d1b-a870fe891fa3.png">

### Steps to reproduce

```
docker run -it -p 9944:9944 parity/polkadot:v0.9.40 --dev --ws-external
```

I tried `--keep-blocks=archive`, and the result was the same
```
docker run -it -p 9945:9944 parity/polkadot:v0.9.40 --dev --ws-external --keep-blocks=archive
```

**Comment by bkchr** [comment]
Same answer as here: https://github.com/paritytech/substrate/issues/9194#issuecomment-872044916
