### ISSUE TITLE
try-runtime-cli docs and tests

### ISSUE THREAD

**Issue by liamaharon** [paritytech/substrate#13796]
At least one try-runtime-cli command passes parameters in the incorrect order (https://substrate.stackexchange.com/q/7902/3991).

Need to audit all the examples in the docs and fix any issues, and write some CLI tests to make sure they don't break in the future.

We should also write some CLI tests. See `subtrate` CLI and I believe this repo is using similar testing patterns https://github.com/paritytech/staking-miner-v2/tree/main/tests for an examples on how to write the tests.

### Docs
- [ ] Audit doc examples (https://github.com/paritytech/substrate/pull/13967 credit @Szegoo)

### Tests
- [x] `follow-chain` https://github.com/paritytech/substrate/pull/13794
- [ ] `on-runtime-upgrade`
- [ ] `offchain-worker`
- [x] `execute-block` https://github.com/paritytech/substrate/pull/14343
- [x] `create-snapshot` https://github.com/paritytech/substrate/pull/14343

**Comment by ggwpez** [comment]
There are more example node tests here, just as an idea of how to do it in Substrate https://github.com/paritytech/substrate/blob/8a9f48bcf0c9f92949082535d77c12166522bb2f/bin/node/cli/tests/

**Comment by liamaharon** [comment]
> There are more example node tests here, just as an idea of how to do it in Substrate https://github.com/paritytech/substrate/blob/8a9f48bcf0c9f92949082535d77c12166522bb2f/bin/node/cli/tests/

Thanks!

**Comment by Szegoo** [comment]
@liamaharon Just to let you know I am looking to rewrite the example part of the `try-runtime-cli` docs, specifically for the `try-state` feature. I believe that some of the examples and explanations could be better.

**Comment by Szegoo** [comment]
@liamaharon If you haven't already, I would like to create a PR that covers `execute-block` and `create-snapshot with tests.

**Comment by liamaharon** [comment]
I'm not currently working on these, go ahead @Szegoo

**Comment by liamaharon** [comment]
Moved to https://github.com/paritytech/try-runtime-cli/issues/10
