### ISSUE TITLE
Replace lru with schnellru

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/substrate#13802]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Version of `lru` used right now is old (0.8 instead of current 0.10), also `schnellru` was introduced as supposedly faster and more featureful replacement.

### Request

Replace all usages of `lru` with `schnellru` to de-duplicate dependencies

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by bkchr** [comment]
@koute WDYT?

**Comment by koute** [comment]
Yeah, sounds good to me. `schnellru` should be pretty much a drop-in replacement for `lru` from a practical point of view.

For performance it probably won't make a difference since I don't think `lru` is used in any significant hot loops, but it's always nice to get rid of some extra dependencies.
