### ISSUE TITLE
Taking into account the block size limit in inherents

### ISSUE THREAD

**Issue by eskimor** [paritytech/substrate#13805]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

We track weight during block creation/block import, but weight only cares about execution time and with 2D weights also about storage proof size.

We do keep track of size in propose [here](https://github.com/paritytech/substrate/blob/657c808eb3d22284359a802d67fdfdbe823fbd17/client/basic-authorship/src/basic_authorship.rs#L452) but only for extrinsics. As far as I understand the code, we don't care about the size limits for inherents - we just assume they fit.

Now at least for parachain inherent data this is not necessarily the case. Candidates can be quite heavy, if there are lots of disputes those can also be quite some amount of data.

If it is indeed the case that all other inherents have negligible size, then some size limiting within the parachains inherent could work. Still a bit fuzzy: What is the size limit, how much of it can we actually use (as other stuff will still have some size) ...

In any case this feels a bit unsatisfying, if we for example assume we can use 70% of the block size for parachain consensus and then another inherent assumes the same, we are already at 140%.

Ideally we would have something like this:

1. Inherents are ordered by priority
2. When [asked for the inherent data](https://github.com/paritytech/substrate/blob/e374a33fe1d99d59eb24a08981090bdb4503e81b/primitives/inherents/src/client_side.rs#L86), we get passed how much size is left to use.
3. We can use that size to determine what data to include and what to leave out.

Should we introduce a mechanism like this? Other thoughts or have I overlooked something?

**Comment by eskimor** [comment]
One downside is, that this is on the node side already. Things like passing in more data than needed and let it be filtered by the runtime would no longer work with this approach. We used to do this for disputes - not a great pattern, but necessary if you are lacking data on the node side. Yet probably a non-issue, in such cases you should probably just add a runtime API to get the necessary information on the node side, as we did for disputes as well.

**Comment by bkchr** [comment]
I'm not sure if you are mixing here weight with the block size. With weights V2 the block size is actually part of the weight, hidden inside the storage proof (not sure if that is really the case, but I would do it that way). The block size is the size of all extrinsics + the block header. 

So, do you mean the block size or the weight?

**Comment by bkchr** [comment]
> Anyhow, in the benchmarks I indeed got a quite large second [component](https://github.com/paritytech/polkadot/pull/6929/files#diff-a9336f21e4ca395e2b58ba00b416805155ea1dbcee459d7f1a4faaddadcffec6R274) ... large assuming this is bytes. So this would account for ~1.4MB, which would be in the right ballpark, but has the same issue as the time component: It is static, while it should be dependent on the input parameters.

But this should be the amount of data that is read from the state? Which isn't important at all for the relay chain, as we don't record any storage proof. 

https://github.com/paritytech/substrate/blob/2bf16d831b777d3c44445d869689a66f0c0e64c6/frame/system/src/extensions/check_weight.rs#L73-L86 we are also already ensuring that the block length stays in its boundaries in the runtime.


> Given that the proof size weight is meant to prevent oversized PoVs, it should at also account for block size ... but the very least, the naming is very misleading.

Yeah the name is misleading, but we currently also don't include the block size. This is the reason for [this issue](https://github.com/paritytech/substrate/issues/13810), which you already have seen :D

**Comment by eskimor** [comment]
Actually no - #13810 would not resolve this issue at least not by itself. We would need to adjust benchmarks to ignore the storage proof part for standalone chains like the relay chain, so it only tracks actual block size. Otherwise we would heavily underutilize the available size.
