### ISSUE TITLE
BABE DB incompatible with older v0.9.37 client 

### ISSUE THREAD

**Issue by nbaztec** [paritytech/substrate#13839]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

While performing a test with the client `0.9.40`, we were unable to revert back to an older client `0.9.37` with the error:

```rust
Error: Service(Other("Polkadot service error: Backend error: BABE DB is corrupted. Decode error: Could not decode `EpochChanges::gap`:\n\tCould not decode variant byte for `Option`:\n\t\tNot enough data to fill buffer\n"))
```

Looking at the changes this [PR](https://github.com/paritytech/substrate/pull/13272/files#diff-96d4068079adf61187f42e2ed685efa46a1a55fe00aa36cfd2f6d5b50799fcf6L155) stands out, which added `scale_info::TypeInfo` to the `Epoch` struct. Could this be the reason the old client is unable to read the data? 

If yes, is it mentioned somewhere in the release notes as a breaking change? Alternatively, if not, what other possible reasons could lead to this error?

Thanks.

**Comment by arkpar** [comment]
> While performing a test with the client 0.9.40, we were unable to revert back to an older client 

Reverting to an old version is not something we generally support. The new version performs migrations on the database that make it incopatible with older code. We only support backwards compatibility, not forwards.

@bkchr From what I understand, the gap field was removed in #13127. Decoding should be compatible with the struct that has the field, so I don't see a major issue here. We still should have bumped the data format version and do proper migration though.

**Comment by crystalin** [comment]
@bkchr Thank you, do you think the PR should have been non silent ? Cause I feel this is a breaking change (as it is not retro compatible) and should probably be mentioned in the release or at least be visible in upgrading scripts (which usually rely on "silent" flags to filter information)
