### ISSUE TITLE
Potential blocking issue when use `tracing_unbounded` channel to send `Sender<T>`

### ISSUE THREAD

**Issue by NingLin-P** [paritytech/substrate#13849]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

In https://github.com/paritytech/substrate/pull/13504, the underlying channel of `tracing_unbounded` channel switched from `futures-channel` to `async-channel`. 

In `async-channel`, the unconsumed messages of the channel will not drop even though all the receivers have been dropped and these messages can never be accessed https://github.com/smol-rs/async-channel/issues/23, this behavior may be an issue when using `tracing_unbounded` channel to send `Sender<T>` to another worker and wait for receiving from this `Sender<T>` (like the usage mentioned at https://github.com/smol-rs/async-channel/issues/23).

In https://github.com/subspace/subspace/issues/1352#issuecomment-1499292448, we have encountered an issue with the abovementioned usage which causes our test block forever. I'm not quite familiar with the `tracing_unbounded` usage in substrate, but I do observe some use cases that use `tracing_unbounded` channel to send `Sender<T>` and they may be potential issues: 

https://github.com/paritytech/substrate/blob/851a8264909acb14d77a0f25a281147f4e689152/client/utils/src/status_sinks.rs#L61
https://github.com/paritytech/substrate/blob/851a8264909acb14d77a0f25a281147f4e689152/client/peerset/src/lib.rs#L278
https://github.com/paritytech/substrate/blob/851a8264909acb14d77a0f25a281147f4e689152/client/network/sync/src/service/network.rs#L124
https://github.com/paritytech/substrate/blob/851a8264909acb14d77a0f25a281147f4e689152/client/network/sync/src/engine.rs#L331

### Steps to reproduce

See https://github.com/smol-rs/async-channel/issues/23

**Comment by bkchr** [comment]
I mean a proper solution would be to fix upstream, otherwise we could just switch the internal implementation to something different that doesn't has this issue.

**Comment by NingLin-P** [comment]
> I mean a proper solution would be to fix upstream

Agree, another option is to switch back to `futures-channel` which seems does not have this behavior and there is actually a unit test to cover this case: https://github.com/rust-lang/futures-rs/blob/5ac72c751c406a525416ad56ead4009a5994b613/futures-channel/tests/mpsc-close.rs#L107

**Comment by bkchr** [comment]
Would you be open to provide a pr switching the internal implementation @NingLin-P?

**Comment by bkchr** [comment]
Ahh, we can not switch to `futures-channel`. We just recently switched to `async-channel` to support checking the length of the channel. I mean you also linked the pr :D

**Comment by NingLin-P** [comment]
Right... Or how about we manually implement that in `tracing_unbounded`, to drain all the pending messages in the `async-channel` channel when `TracingUnboundedReceiver` is dropped? I'm happy to contribute if you think this approach is feasible.

**Comment by bkchr** [comment]
If we first close the receiver and then drain all the messages, it should work. Sounds like something to try out. I'm happy if you could do this @NingLin-P :)
