### ISSUE TITLE
large size difference between variants

### ISSUE THREAD

**Issue by deepink-mas** [paritytech/substrate#13855]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Running cargo clippy on a copy of the node-template I found this issue which is still relevant. Can this warning be allowed or should the Box trick that clippy suggests be applied?

```
warning: large size difference between variants
  --> node/src/cli.rs:13:1
   |
13 | / pub enum Subcommand {
14 | |     /// Key management cli utilities
15 | |     #[command(subcommand)]
16 | |     Key(sc_cli::KeySubcommand),
   | |     -------------------------- the second-largest variant contains at least 272 bytes
...  |
41 | |     Benchmark(frame_benchmarking_cli::BenchmarkCmd),
   | |     ----------------------------------------------- the largest variant contains at least 488 bytes
...  |
52 | |     ChainInfo(sc_cli::ChainInfoCmd),
53 | | }
   | |_^ the entire enum is at least 488 bytes
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
   = note: `#[warn(clippy::large_enum_variant)]` on by default
help: consider boxing the large fields to reduce the total size of the enum
   |
41 |     Benchmark(Box<frame_benchmarking_cli::BenchmarkCmd>),
   |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by ggwpez** [comment]
That is not a problem. We dont store this in the runtime - it is entirely node side.

**Comment by ggwpez** [comment]
It would be more interesting to apply this to the `RuntimeEvent` enum, not sure if that is possible since it is macro output.

**Comment by deepink-mas** [comment]
Perhaps you'd accept a PR: https://github.com/paritytech/substrate/pull/13856 ?
