### ISSUE TITLE
Crate `proc-macro-warning` adds GPL 3.0 license dependency

### ISSUE THREAD

**Issue by haerdib** [paritytech/substrate#13872]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The newly added [proc-macro-warning](https://github.com/ggwpez/proc-macro-warning) crate adds a GPL 3.0 dependency to substrate (added in this [PR](https://github.com/paritytech/substrate/pull/13798))
To the best of my knowledge (not a lawyer) this violates the GPL v3.0 license.

### Steps to reproduce

Noticed after a cargo update via license check in our CI. Check out https://github.com/scs/substrate-api-client/actions/runs/4664840889/jobs/8259110692

**Comment by bkchr** [comment]
CC @ggwpez
