### ISSUE TITLE
Document the steps to introduce a validator node to a running network .

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#1392]
What are the correct steps to introduce a validator node to a running network?

Create a node (as non-validator)
Create an account for the node.
Transfer enough funds
Click on stake. 
Tried this approach and did not work

**Comment by gavofyork** [comment]
- Once synced, restart node with additional params `--validator --key SEED_FOR_YOUR_STAKING_KEY`.
- Wait until you have been added to the staking set (if your stake is sufficiently high, this will happen at the end of the next "era", polkadot-js will tell you how long to go until then and whether you have been selected.

**Comment by Kalanamith** [comment]
@gavofyork Thanks!
