### ISSUE TITLE
Bug- Block production halts after stacking  a newly created account .

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#1393]
**Scenario**

- Created 3 node network locally (worked fine)
- Created an account
- Did enough fund tranfer
- Clicked on `stake` in account section for the created account.

**Observation**
- Took more than 90 seconds and less than 140 seconds to produce the block.
- Block production halts.

**Error**
```
Error with block built on 0xc41694040bd48f314e023231c06194fc8e756527afcd235367ebfe86491b2bae: Error(ClientImport("Incorrect base hash"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```
Created account got hanged in •next up section.

**Comment by gavofyork** [comment]
Is this still current?

**Comment by drewstone** [comment]
@Kalanamith why did you close this? I can confirm this happened to me with similar intentions.

**Comment by xlc** [comment]
@drewstone  `Incorrect base hash` should be fixed in a recent version (I also reported it at #1525).
