### ISSUE TITLE
Ensure consistent formatting across project 

### ISSUE THREAD

**Issue by gterzian** [paritytech/substrate#1394]
Currently if one runs `cargo fmt`, with `hard_tabs = true`, you get a ton of changes across files, which means it's hard to use `cargo fmt` without introducing changes unrelated to the work at hand. 

I propose that we do the following:

1. When someone makes a "big" change to a file, run `cargo fmt` on it(even at the cost of introducing unrelated changes). 
2. After a while, when it looks like formatting is fairly consistent across the project, do one big `cargo fmt` PR for all remaining changes, and from then on add a `cargo fmt` check as part of CI. 

Note that to support tabs, one need to add a `rustfmt.toml` file with `hard_tabs = true`. 

This could also be an opportunity to reconsider the choice of tabs for indent. I'm personally in favor of spaces, since that requires no further configuration(and it makes for less indented diffs in pull requests).

**Comment by bkchr** [comment]
We will not enable rustfmt for substrate, because it does not support our coding style guide lines.

**Comment by xlc** [comment]
It will be good to be able perform automatically formatting somehow. Follow a non-standard style guide is an additional barrier of entry for new contributors especially for new Rust developers.
