### ISSUE TITLE
Improve wasm/native execution heuristics

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1395]
Currently there are three execution modes:

- WASM_ONLY Just Wasm
- TRY_NATIVE Native if possible, otherwise Wasm
- CHECK_NATIVE If native is possible, both native and Wasm; Wasm result is taken; any failure of native is logged. Otherwise just Wasm.

A fourth execution mode should be added:

- NATIVE_ELSE_WASM First native, then if that fails or is not possible, wasm.

Defaults should be:

- Syncing: NATIVE_ELSE_WASM
- General importing (including importing own blocks): NATIVE_ELSE_WASM
- Block construction (`initialize_block`, `apply_extrinsic`, `finalize_block`: WASM_ONLY
- Other runtime calls: NATIVE_ELSE_WASM

CLI options should be introduced so each of the three contexts can be changed.

**Comment by marcio-diaz** [comment]
I don't have clear the contexts @gavofyork. 

By three contexts do you mean `Syncing`, `General importing` and `Block construction`? 
Are they somehow related to `config.block_execution_strategy` and `config.api_execution_strategy`?

**Comment by gavofyork** [comment]
i don't know the codebase myself well enough to direct you to specific lines/functions where these contexts lie. in general though there are three reasons you will want to call into the runtime: when you're evaluating a block while syncing the chain, when you're importing a block to stay in sync and when you are constructing a block as a block author. if you can't discover how to identify these contexts yourself, @arkpar can probably offer some pointers.

**Comment by arkpar** [comment]
Entry point for "Syncing/General importing" is `Client::execute_and_import_block`. `origin` parameter can be used to identify block origin
"Block construction" - calls made from `client::block_builder` 
"Other runtime calls" - usually made with `Client::call_api_at`

**Comment by rphmeier** [comment]
> "Block construction" - calls made from client::block_builder

I wonder to what degree we would include e.g. API calls made during block building that are not directly to the block builder itself?
