### ISSUE TITLE
Snappy disabled with librocksdb 5.14.3, unable to create genesis file

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#1396]
When using rocksdb 5.14.3 along with the substrate-node-template, starting a new chain fails with the following error:

```
2019-01-11 11:12:03 Substrate Node
2019-01-11 11:12:03   version 0.9.0-d5ffa1f-x86_64-macos
2019-01-11 11:12:03   by Parity Technologies, 2017, 2018
2019-01-11 11:12:03 Chain specification: Development
2019-01-11 11:12:03 Node name: imminent-purpose-0856
2019-01-11 11:12:03 Roles: AUTHORITY
Error: Backend error: Invalid argument: Compression type Snappy is not linked with the binary.
```

To solve this issue, we need to downgrade to librocksdb 5.14.2.

Proposed solution:

> https://github.com/rust-rocksdb/rust-rocksdb/commit/16a49d97060ca346de95d32037079d4429bc788a#diff-90e9c5f430a85c021bdd079b3839c573
> 
> They started to enable the feature in rocksdb. but rocksdb-sys does not have the feature enabled by default...
> 
> So by updating rocksdb-sys, snappy gets disabled with the "old" rocksdb
> 
> So we either update rocksdb in my branch of parity-common (I would not want to do that). Or we start upstreaming our changes of rocksdb and switch to that ( I would recommend that!).

**Comment by gnunicorn** [comment]
@shawntabrizi could you try out the PR and confirm if that fixes it (for now)?

**Comment by attente** [comment]
Hi, I've tried your branch and it fixes the problem for me, thanks!
