### ISSUE TITLE
Avoid going to storage for runtime statics

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1399]
Long ago, we had a create which IIRC was called `environment`. It essentially allowed for a sort of  safe `lazy_static`-style mutable global variables. Given the very static nature of the runtime, this was rather useful for storing stuff that lots of logic needed to be able to access like `block_number` and `events`.

It was removed instead favouring using storage i/o for all such needs. This is less than optimal, particularly for `events`, which can get quite large and which magnifies every `.push` operation into three large allocations and `memcpy`s.

There are two ways around this problem:

Option 1: Bringing it back would avoid that. But we removed it because it was a bit clumsy and, though not unsafe, a little dirty and unidiomatic.

Option 2: A global cache could be introduced, allowing storage items to be tagged as cacheable and thus to persist in wasm memory between storage accesses.

Option 3: The cleaner way would be to allow `Module`s to have fields. All module functions would need to become non-static and accept `self`, including dispatchable functions. A `&a::Module<T>` should be `AsRef` convertible to `&b::Module<T>` iff `a::Trait` implied `b::Trait`, allow modules to easily call into their dependent modules. Modules could perhaps even include a `fn new` function, that could be automatically called when the runtime is constructed.

Option 1 is probably easier to do, Option 2 shouldn't be too difficult either, but might be rather dangerous, Option 3 is probably best, but hardest.

**Comment by pepyakin** [comment]
(writing from mobile) Doesn’t we use it already? Afair we didnt remove it but extracted on crates io?

I think it should be used now in sr-io for std for with_externalities?

**Comment by gavofyork** [comment]
yeah, that's actually a different crate that addresses a (slightly) different problem.
