### ISSUE TITLE
Should be note complier version rust

### ISSUE THREAD

**Issue by trinhvanvinh** [paritytech/substrate#13998]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I cloned substrate-node-template branch main, within version polkadot-v0.9.40. I am using rustc 1.69.0 (84c898d65 2023-04-16). when build cargo --release has an error:  feature has been removed... 

 --- stderr
     Compiling sp-io v7.0.0 (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.40#ba87188c)
  error[E0557]: feature has been removed
    --> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/ba87188/primitives/io/src/lib.rs:22:43
     |
  22 | #![cfg_attr(not(feature = "std"), feature(alloc_error_handler))]
     |                                           ^^^^^^^^^^^^^^^^^^^ feature has been removed
     |
     = note: now handled by panic handler

  error: cannot find attribute `alloc_error_handler` in this scope
      --> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/ba87188/primitives/io/src/lib.rs:1657:3
       |
  1657 | #[alloc_error_handler]
       |   ^^^^^^^^^^^^^^^^^^^

  For more information about this error, try `rustc --explain E0557`.
  error: could not compile `sp-io` (lib) due to 2 previous errors

Pls help me

### Steps to reproduce

I have been update stable rustc: 1.69.0 (84c898d65 2023-04-16) 
1. clone project: https://github.com/substrate-developer-hub/substrate-node-template,  branch main
2.  cargo build --release  
3.  will see errors

plese help me build project, or show with me that version rustc you using for camplier at this time. thanks you

**Comment by bkchr** [comment]
Please downgrade to 1.68.0 nightly or use latest master from Substrate.

**Comment by trinhvanvinh** [comment]
error: failed to run custom build command for `parachain-template-runtime v0.1.0 (/Users/Desktop/substrate-parachain-template/runtime)`

Caused by:
  process didn't exit successfully: `/Users/Desktop/substrate-parachain-template/target/release/build/parachain-template-runtime-8215f80abd5c6183/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: RUSTFLAGS="-C link-arg=--export-table -Clink-arg=--export=__heap_base -C link-arg=--import-memory  " SKIP_WASM_BUILD="" "rustup" "run" "nightly" "cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/Desktop/substrate-parachain-template/target/release/wbuild/parachain-template-runtime/Cargo.toml" "--color=always" "--profile" "release"
  Using rustc version: rustc 1.71.0-nightly (f5559e338 2023-04-24)


  --- stderr
      Blocking waiting for file lock on package cache
      Blocking waiting for file lock on package cache
      Blocking waiting for file lock on package cache
     Compiling sp-io v7.0.0 (https://github.com/paritytech/substrate?branch=polkadot-v0.9.40#98f2e345)
  error[E0557]: feature has been removed
    --> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/98f2e34/primitives/io/src/lib.rs:22:43
     |
  22 | #![cfg_attr(not(feature = "std"), feature(alloc_error_handler))]
     |                                           ^^^^^^^^^^^^^^^^^^^ feature has been removed
     |
     = note: now handled by panic handler

  error: cannot find attribute `alloc_error_handler` in this scope
      --> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/98f2e34/primitives/io/src/lib.rs:1657:3
       |
  1657 | #[alloc_error_handler]
       |   ^^^^^^^^^^^^^^^^^^^

  For more information about this error, try `rustc --explain E0557`.
  error: could not compile `sp-io` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `polkadot-runtime v0.9.40 (https://github.com/paritytech/polkadot?branch=release-v0.9.40#95fe4c88)`

i am using version rustc 1.68.0 (2c8cc3432 2023-03-06)

Please help me!

**Comment by trinhvanvinh** [comment]
> Please downgrade to 1.68.0 nightly or use latest master from Substrate.

error: failed to run custom build command for parachain-template-runtime v0.1.0 (/Users/Desktop/substrate-parachain-template/runtime)

Caused by:
process didn't exit successfully: /Users/Desktop/substrate-parachain-template/target/release/build/parachain-template-runtime-8215f80abd5c6183/build-script-build (exit status: 1)
--- stdout
Information that should be included in a bug report.
Executing build command: RUSTFLAGS="-C link-arg=--export-table -Clink-arg=--export=__heap_base -C link-arg=--import-memory " SKIP_WASM_BUILD="" "rustup" "run" "nightly" "cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/Desktop/substrate-parachain-template/target/release/wbuild/parachain-template-runtime/Cargo.toml" "--color=always" "--profile" "release"
Using rustc version: rustc 1.71.0-nightly (f5559e338 2023-04-24)

--- stderr
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Blocking waiting for file lock on package cache
Compiling sp-io v7.0.0 (https://github.com/paritytech/substrate?branch=polkadot-v0.9.40#98f2e345)
error[E0557]: feature has been removed
--> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/98f2e34/primitives/io/src/lib.rs:22:43
|
22 | #![cfg_attr(not(feature = "std"), feature(alloc_error_handler))]
| ^^^^^^^^^^^^^^^^^^^ feature has been removed
|
= note: now handled by panic handler

error: cannot find attribute alloc_error_handler in this scope
--> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/98f2e34/primitives/io/src/lib.rs:1657:3
|
1657 | #[alloc_error_handler]
| ^^^^^^^^^^^^^^^^^^^

For more information about this error, try rustc --explain E0557.
error: could not compile sp-io (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for polkadot-runtime v0.9.40 (https://github.com/paritytech/polkadot?branch=release-v0.9.40#95fe4c88)

i am using version rustc 1.68.0 (2c8cc3432 2023-03-06)

Please help me!

**Comment by bkchr** [comment]
> > Please downgrade to 1.68.0 nightly or use latest master from Substrate.
> 
> error: failed to run custom build command for parachain-template-runtime v0.1.0 (/Users/Desktop/substrate-parachain-template/runtime)
> 
> Caused by: process didn't exit successfully: /Users/Desktop/substrate-parachain-template/target/release/build/parachain-template-runtime-8215f80abd5c6183/build-script-build (exit status: 1) --- stdout Information that should be included in a bug report. Executing build command: RUSTFLAGS="-C link-arg=--export-table -Clink-arg=--export=__heap_base -C link-arg=--import-memory " SKIP_WASM_BUILD="" "rustup" "run" "nightly" "cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/Desktop/substrate-parachain-template/target/release/wbuild/parachain-template-runtime/Cargo.toml" "--color=always" "--profile" "release" Using rustc version: rustc 1.71.0-nightly (f5559e338 2023-04-24)
> 
> --- stderr Blocking waiting for file lock on package cache Blocking waiting for file lock on package cache Blocking waiting for file lock on package cache Compiling sp-io v7.0.0 (https://github.com/paritytech/substrate?branch=polkadot-v0.9.40#98f2e345) error[E0557]: feature has been removed --> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/98f2e34/primitives/io/src/lib.rs:22:43 | 22 | #![cfg_attr(not(feature = "std"), feature(alloc_error_handler))] | ^^^^^^^^^^^^^^^^^^^ feature has been removed | = note: now handled by panic handler
> 
> error: cannot find attribute alloc_error_handler in this scope --> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/98f2e34/primitives/io/src/lib.rs:1657:3 | 1657 | #[alloc_error_handler] | ^^^^^^^^^^^^^^^^^^^
> 
> For more information about this error, try rustc --explain E0557. error: could not compile sp-io (lib) due to 2 previous errors warning: build failed, waiting for other jobs to finish... error: failed to run custom build command for polkadot-runtime v0.9.40 (https://github.com/paritytech/polkadot?branch=release-v0.9.40#95fe4c88)
> 
> i am using version: 1.68.0-aarch64-apple-darwin (default) rustc 1.68.0 (2c8cc3432 2023-03-06)
> 
> Please help me!

You are not using it: 
```
Using rustc version: rustc 1.71.0-nightly (f5559e338 2023-04-24)
```

Also downgrade your nightly.
