### ISSUE TITLE
Could not compile sp-io

### ISSUE THREAD

**Issue by trinhvanvinh** [paritytech/substrate#14016]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

error[E0557]: feature has been removed
--> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/98f2e34/primitives/io/src/lib.rs:22:43
|
22 | #![cfg_attr(not(feature = "std"), feature(alloc_error_handler))]
| ^^^^^^^^^^^^^^^^^^^ feature has been removed
|
= note: now handled by panic handler

 Compiling trie-root v0.18.0
 Compiling cc v1.0.79
 Compiling memory-db v0.32.0
error: cannot find attribute alloc_error_handler in this scope
--> /Users/.cargo/git/checkouts/substrate-7e08433d4c370a21/98f2e34/primitives/io/src/lib.rs:1657:3
|
1657 | #[alloc_error_handler]
| ^^^^^^^^^^^^^^^^^^^

For more information about this error, try rustc --explain E0557.
Compiling xcm-procedural v0.9.40 (https://github.com/paritytech/polkadot?branch=release-v0.9.40#95fe4c88)
error: could not compile sp-io (lib) due to 2 previous errors

I am using: 1.68.0-aarch64-apple-darwin (default)
rustc 1.68.0 (2c8cc3432 2023-03-06)

Please help me!

### Steps to reproduce

1. clone https://github.com/substrate-developer-hub/substrate-parachain-template
2. Cargo build --release 
( 1.68.0-aarch64-apple-darwin (default)
rustc 1.68.0 (2c8cc3432 2023-03-06) )

**Comment by bkchr** [comment]
Duplicate.
