### ISSUE TITLE
Permill & Perbill should implement HasCompact

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1405]
There should be a `Compact<Permill>` and `HasCompact<Permill>::Type` in the same way it works for `Compact<u32>` and `HasCompact<u32>::Type` which it wraps.

Once done, any params of type Permill and Perbill in runtime dispatched functions should be switched to the compact variants.

**Comment by xlc** [comment]
It will be good if https://github.com/paritytech/substrate/issues/1378 can be addressed before another breaking change been introduced.

**Comment by gavofyork** [comment]
pre-1.0 I'm afraid things are going to be fairly bumpy. Post-1.0 we'll actually put some effort in to keep things stable.
