### ISSUE TITLE
try-runtime-cli: remove DB operations in async code

### ISSUE THREAD

**Issue by liamaharon** [paritytech/substrate#14066]
you don't have to do it in this PR but worth investing whether it makes things faster or not.

Ideally, we shouldn't do any DB operations in async code it might fuckup the async scheduler in tokio

_Originally posted by @niklasad1 in https://github.com/paritytech/substrate/pull/14057#discussion_r1181570805_

**Comment by ggwpez** [comment]
Just as note: optimizing in this case is much lower prio than stability and good testing.  
Formerly the try-runtime CLI would take 2hrs, so having it run in 2-5 minutes is already a huge improvement.  
I would leave any further optimization for after the stabilizing phase.

**Comment by liamaharon** [comment]
Moved to https://github.com/paritytech/try-runtime-cli/issues/14
