### ISSUE TITLE
wasm trap: out of bounds memory access

### ISSUE THREAD

**Issue by yrong** [paritytech/substrate#14075]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

https://substrate.stackexchange.com/questions/8347/is-it-safe-to-use-const-generic-structure-in-runtime-storage

```
rustc --version
rustc 1.67.0-nightly (96ddd32c4 2022-11-14)

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

### Steps to reproduce

- The branch with [BoundedVec](https://github.com/Snowfork/snowbridge/tree/ron/cache-milagro-g1-pubkeys) which works 
- The branch with [const-generic-array](https://github.com/Snowfork/snowbridge/tree/ron/cache-milagro-g1-pubkeys-const-generic-array) which does not work

For test we embed our bridge pallet into forked cumulus and link it as submodule, so after clone the repo above just update submodule and benchmark the pallet with command as following:

```
git submodule update --init --recursive && cd cumulus && RUST_LOG=debug cargo run --release --bin polkadot-parachain --features runtime-benchmarks -- benchmark pallet --chain=bridge-hub-rococo-dev --pallet=snowbridge_ethereum_beacon_client --extrinsic="*" --execution=wasm --wasm-execution=compiled --steps 50 --repeat 20
``` 

or I can just provide an ubuntu EC2 instance setup ready if nessessary.

**Comment by bkchr** [comment]
@yrong why did you close it? What was the issue?

**Comment by vgeddes** [comment]
Hey @bkchr I'm going to cut a new ticket shortly with more details.

**Comment by bkchr** [comment]
> * The branch with [const-generic-array](https://github.com/Snowfork/snowbridge/tree/ron/cache-milagro-g1-pubkeys-const-generic-array) which does not work

BTW, this branch works for me.

**Comment by bkchr** [comment]
```
rustc 1.71.0-nightly (b628260df 2023-04-22)
binary: rustc
commit-hash: b628260df0587ae559253d8640ecb8738d3de613
commit-date: 2023-04-22
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

**Comment by yrong** [comment]
Exactly, resolved when upgrade rust to `1.71.0-nightly` :thumbsup: 

Btw, Is the rust version here safely to use for cumulus?  Check the CI script [here](https://github.com/paritytech/scripts/blob/41abf440c6a02e546b271e1fbd6155d5fe832d8e/dockerfiles/ci-linux/Dockerfile#L7)  seems still `2022-11-16`

**Comment by bkchr** [comment]
With recent master you can now also use stable to compile the wasm binary. And yes, safe to upgrade.

Please also close your stackexchange question.

**Comment by yrong** [comment]
There is still a `invalid memory reference` issue left when I run unit test for pallet `snowbridge-ethereum-beacon-client`, can be reproduced on main branch as following:

```
git clone https://github.com/Snowfork/snowbridge
cd snowbridge/parachain && git checkout main
cargo test --verbose --package snowbridge-ethereum-beacon-client
...
error: test failed, to rerun pass `-p snowbridge-ethereum-beacon-client --lib`

Caused by:
  process didn't exit successfully: `/Users/yangrong/Projects/snowbridge/parachain/target/debug/deps/snowbridge_ethereum_beacon_client-213702e7f5af905e` (signal: 11, SIGSEGV: invalid memory reference)
```

More details found when debug with lldb and seems something to do with `scale_codec`

```
lldb /Users/yangrong/Projects/snowbridge/parachain/target/debug/deps/snowbridge_ethereum_beacon_client-213702e7f5af905e
(lldb) run
* thread #5, name = 'tests_mainnet::it_updates_a_committee_period_sync_update', stop reason = EXC_BAD_ACCESS (code=1, address=0x170d001b8)
    frame #0: 0x00000001000aa160 snowbridge_ethereum_beacon_client-213702e7f5af905e`parity_scale_codec::codec::decode_array::h76ab4c45e78933e3(input=0x6931c020daf94fa3) at codec.rs:739
   736 	///
   737 	/// This is equivalent to decoding all the element one by one, but it is optimized for some types.
   738 	#[inline]
-> 739 	pub(crate) fn decode_array<I: Input, T: Decode, const N: usize>(input: &mut I) -> Result<[T; N], Error> {
   740 		#[inline]
   741 		fn general_array_decode<I: Input, T: Decode, const N: usize>(input: &mut I) -> Result<[T; N], Error> {
   742 			let mut uninit = <MaybeUninit<[T; N]>>::uninit();
Target 0: (snowbridge_ethereum_beacon_client-213702e7f5af905e) stopped.
```

Again resolved when switch to `BoundedVec` with code diff as following
https://github.com/Snowfork/snowbridge/commit/22274fad4e604152a347fc03cfb9eefea28fbc6b#diff-31f52e5ac5de46b6d210572dc86bc92a789d1aeea16b48f0b3f8a8826201f795

**Comment by bkchr** [comment]
@yrong this should be: https://github.com/paritytech/parity-scale-codec/issues/425
