### ISSUE TITLE
Transaction-execution & block-import benchmarks

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1408]
Currently we don't have any real benchmarks on transaction execution and only basic benchmarking for block execution/import. There should be a consolidated suite for all benchmarking, allowing for:

- Unit benchmarking of specific extrinsics (transfer, timestamp-set, stake, ...). Should be with and without trie & changes-trie commit.
- Comprehensive benchmarking of entire blocks, with specific sets of extrinsics (empty, 10 transfers, 100 transfers, ...).

In all cases, should include results for both wasm and native.

**Comment by mattrutherford** [comment]
hey @marcio-diaz would you like to work on this now that you've taken over benchmarking from me? If not, we should find someone.

**Comment by marcio-diaz** [comment]
Well, I'm working in a `suite for benchmarking`, hopefully it will cover the`consolidated` and  `all` parts as well. If you are assigning me, probably you should un-assign yourself to avoid misunderstandings.

**Comment by mattrutherford** [comment]
OK, cool - so perhaps we should create a new issue to track the unit benchmarks if that's not possible with the new tool?

**Comment by marcio-diaz** [comment]
> OK, cool - so perhaps we should create a new issue to track the unit benchmarks if that's not possible with the new tool?

No, it will probably lead to duplicated work.

**Comment by shawntabrizi** [comment]
this has been completed by the `node-bench` cli
