### ISSUE TITLE
deprecate `#[pallet::generate_storage_info]`

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#14089]
As it seems to be the default now. 

we have both `pallet#generate_storage_info` and `pallet::without_storage_info.
one must to be redundant.

Will assign to Oliver to make the final call about what should be the default, but can be done by anyone.

**Comment by ggwpez** [comment]
It looks like this is not valid pallet syntax, so just the docs are wrong. It only works for V1 `decl_module` syntax.  
```rust
#[pallet::pallet]
#[pallet::generate_storage_info]
pub struct Pallet<T>(_);
```
Does not compile with `expected one of: generate_store, without_storage_info, storage_version`.  
So i guess we dont need to deprecate anything, just clean the docs.
