### ISSUE TITLE
`try-runtime-cli` retry for `get_keys`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#14129]
CI failed [here](https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2825521) on the `get_keys` call. It is the first time that i see it, but maybe we can make it more robust with a bit of retry.

```pre
DEBUG main remote-ext: new total = 730000, full page received: 5f3e4907f716ac89b6347d15ececedca9220e172bed316605f73f1ff7b4ade98a012cfa19460140342043a3d9f00a18861bc550480483f292fd5bf9069beb6e94ef6a1704b01ff04    
DEBUG main remote-ext: new total = 731000, full page received: 5f3e4907f716ac89b6347d15ececedca9220e172bed316605f73f1ff7b4ade98a3716ac47670e65cba624b72562b6865b76de0ae67950a7d627ac3d895868d83a0e26c4b3dbc0709    
ERROR main remote-ext: Error = Transport(HTTP error: error reading a body from connection: end of file before message length reached)    
⠹    12.956 s	Scraping keys...Error: 
    0: Invalid input: rpc get_keys failed
```
cc @liamaharon

**Comment by kianenigma** [comment]
cc @liamaharon

**Comment by liamaharon** [comment]
Can do this with `tower` middleware 
- https://docs.rs/tower/latest/tower/retry/index.html#
- https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/http.rs#L48-L61

**Comment by liamaharon** [comment]
I've created a simple RetryPolicy middleware and applied it to the HttpClient here: https://github.com/paritytech/substrate/compare/liam-remote-ext-tower-retry

Part of this required changing `HttpClient` to `HttpClient<Retry<RetryPolicy, HttpBackend>>`, however this creates an issue with trait bounds:

<img width="1157" alt="Screenshot 2023-05-15 at 12 00 22" src="https://github.com/paritytech/substrate/assets/16665596/7fb297ab-a62c-4363-819a-ba4b428dac55">

@niklasad1 any ideas here? I can continue looking into this but thought you may be able to spot the solution faster than me.

**Comment by niklasad1** [comment]
damn, perhaps the tower stuff broke the generated trait bounds...

lemme have a look

**Comment by niklasad1** [comment]
@liamaharon you must bump the `rpc-api crate` to use the same version as the remote externalities.

You try adding your changes to my pending branch https://github.com/paritytech/substrate/pull/13992

**Comment by niklasad1** [comment]
That sucks, sorry for hinting you down this rabbit hole. https://github.com/hyperium/hyper/discussions/2726.

Ideally, we don't want that stuff in jsonrpsee to keep it as simple as possible but and we already got something that @skunert wrote in cumulus for WebSocket client.

You could perhaps re-use it or write something similar for the HTTP client (the code should be simpler) depending what you need.... 

It should be to just clone "JSON-RPC params and method name"

**Comment by liamaharon** [comment]
Grr, it broke again https://gitlab.parity.io/parity/mirrors/polkadot/-/jobs/2851477, seems not just a one-off occurrence.

Prioritising this so CI doesn't break.

**Comment by ggwpez** [comment]
Hm so this is maybe a regression :sweat_smile:?  
I hope we can build some nice integration test once we have the mono-repo to spot these things earlier.

**Comment by liamaharon** [comment]
I think a regression when we switched to an HttpClient, I've seen this when making very rapid http requests to a substrate node before.

**Comment by niklasad1** [comment]
hmm, can't you do something like:

```rust
if Err(e) = client.request(foo) {
   log::warn!("got error: {:?} restarting JSON-RPC client"), e);
   client = new_client();
}
```

to work around that?

**Comment by liamaharon** [comment]
> hmm, can't you do something like:
> 
> ```rust
> if Err(e) = client.request(foo) {
>    log::warn!("got error: {:?} restarting JSON-RPC client", e);
>    client = new_client();
> }
> ```
> 
> to work around that?

We could.. Though it would be non-trivial given the way the WsClient/HttpClient is set currently in remote-externalities.

I suggest for now that we continue with a retry for `get_keys` to resolve this CI issue.

Maybe a better future solution (if it proves high enough priority to look at) could be to use a WsClient for fetching keys and an HttpClient for downloading storage 🤷

**Comment by niklasad1** [comment]
Fine, it just that `hyper client` has its background task if something goes wrong there this won't make any progress with your fix. 

Would be quite interesting to get a way to re-produce this issue when "EOF is received before that content length", have been able to re-produce locally?

**Comment by liamaharon** [comment]
> Fine, it just that `hyper client` has its background task if something goes wrong there this won't make any progress with your fix.

I see, thanks for the heads up. Hopefully `hyper` is stable enough that that won't be an issue, but if it is then we'll do a larger refactor to allow recreating the WsClient if its connection gets dropped.

> Would be quite interesting to get a way to re-produce this issue when "EOF is received before that content length", have been able to re-produce locally?

I've not been able to re-produce it locally.
