### ISSUE TITLE
Client should expose a function for accessing a block's children

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#14135]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

The specific motivation is https://github.com/paritytech/cumulus/pull/2573 , where consensus logic needs to recursively iterate children of a specific block in a fork-choice rule. Implementing other functionality for fork-choice rules, like the `SelectChain` trait would typically need this, unless a separate database is maintained.

### Request

Expose a function for accessing the children of a block from `sc_service::Client` through a trait implementation.

The client has this functionality via `sc_client_api::backend::Backend`/`sp_blockchain::Backend`, it's just simply not exposed.

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by bkchr** [comment]
If possible, I would stay away of adding more logic to our god object client. Especially as you can already get this kind of functionality through the backend, why don't you keep using the backend? I don't see any problem in this.

**Comment by rphmeier** [comment]
Sure, as long as the backend is meant to be generally available to code built on top of Substrate

**Comment by rphmeier** [comment]
Closing for now, will reopen if needed
