### ISSUE TITLE
Validator nodes are getting flooded with "Queue of packets to send over substream is pretty large"

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#1414]
According to @ddorgan, several gigabytes of logs of warnings are generated.

This happens when the number of messages waiting to be sent on the network goes over 2048.

We need to investigate whether this is normal, or if this indicates some underlying issue in the `sync` layer. If it is normal, then there should probably some mechanism in place to indicate that the remote is not ready and avoid filling a huge buffer of messages.

**Comment by arkpar** [comment]
This is resolved with fixes to gossip protocol
