### ISSUE TITLE
`impl_runtime_apis` does not work if `sp-api` is not in scope

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#14145]
Somewhat similar to https://github.com/paritytech/substrate/issues/14127, it seems like this macro also does not work if `sp-api` is not directly in scope as a dependency. The error message is very cryptic: 

```
error: proc macro panicked
   --> staging-runtime/src/lib.rs:114:1
    |
114 | / impl_runtime_apis! {
115 | |     impl frame_runtime::runtime_apis::Core<Block> for Runtime {
116 | |         fn version() -> RuntimeVersion {
117 | |             VERSION
...   |
177 | |     }
178 | | }
    | |_^
    |
    = help: message: unexpected token
```

This prevents eg. #14137 to re-export `sp_api::Core` and `impl_runtime_apis` in a way that is meaningfully usable. 

Note that for rest of the APIs, like `sp_block_builder` you can import it from a 3rd party re-export them from somewhere else and it works. Although, you need make sure to re-export them like `pub use sp_block_builder::*` to re-export some magic generated by `decl_runtime_apis!` as well.

**Comment by kianenigma** [comment]
Moreover, if `sp-api` is imported without any notion of disabling default features, like: 

```
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "kiz-frame-api" }
```


we get the following error: 

```
error[E0425]: cannot find function `to_substrate_wasm_fn_return_value` in crate `sp_api`
   --> staging-runtime-native/src/lib.rs:114:1
    |
114 | / impl_runtime_apis! {
115 | |     impl frame_runtime::runtime_apis::Core<Block> for Runtime {
116 | |         fn version() -> RuntimeVersion {
117 | |             VERSION
...   |
177 | |     }
178 | | }
    | |_^ not found in `sp_api`
    |
    = note: this error originates in the macro `impl_runtime_apis` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by kianenigma** [comment]
Can this be fixed in a timely fashion? if we can fix it sooner, I won't need to go and refactor infinite number of branches in the tutorial late 🙈

**Comment by bkchr** [comment]
> we get the following error:

Did you read what I have written in element? The same applies for all FRAME macros as well...

**Comment by kianenigma** [comment]
@bkchr do you have any plans to address this? I initially thought the #14267 is going to fix this, but I was wrong.

**Comment by kianenigma** [comment]
closed in https://github.com/paritytech/substrate/pull/14137/commits/7d912d0a23944da5cd9e0d068750b01ef77769b7
