### ISSUE TITLE
Child trie not included when exporting a snapshot

### ISSUE THREAD

**Issue by cheme** [paritytech/substrate#14151]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

This line https://github.com/paritytech/substrate/blob/e4b08db824c42f45e14e1b0a29f133b9c9903267/utils/frame/remote-externalities/src/lib.rs#L532 remove roots of child trie from the data injected in the backend state.
(presumably so child trie import would not expect content existing (I did hack around and if I put them it create trie error when injecting child trie data).

This result in https://github.com/paritytech/substrate/blob/e4b08db824c42f45e14e1b0a29f133b9c9903267/utils/frame/remote-externalities/src/lib.rs#L712 returning no child trie. And child trie not being in the snapshot.

### Steps to reproduce

Export snap from a chain with child trie (I did observe that with kusama and did a hacky fix to force the child trie in the snapshot).

**Comment by kianenigma** [comment]
cc @liamaharon
