### ISSUE TITLE
Move codebase over to 2018 edition

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1415]
- Remove all `extern crate` lines.
- For `#[macro_use]` lines, ensure any macros are imported with `use`.
- Place `edition = "2018"` into all `Cargo.toml` files
- Update `polkadot` and `substrate-node-template` projects.

`cargo fix --edition "edition = 2018"` might help.

**Comment by DarkEld3r** [comment]
List of substrate crates:
- [x] substrate-basic-authorship
- [ ] substrate-cli
- [ ] substrate-client-db
- [ ] 
- [ ] 
- [ ]

**Comment by DarkEld3r** [comment]
List of substrate crates with migration status:
- core
  - [ ] substrate-basic-authorship
  - [ ] substrate-cli
  - [ ] substrate-client-db
  - [x] substrate-client
  - [ ] substrate-consensus-aura-primitives
  - [ ] substrate-consensus-aura
  - [ ] substrate-consensus-common
  - [ ] substrate-consensus-rhd
  - [ ] runtime-test
  - [ ] substrate-executor
  - [ ] substrate-finality-grandpa-primitives
  - [ ] substrate-finality-grandpa
  - [x] substrate-inherents
  - [ ] substrate-keyring
  - [ ] substrate-keystore
  - [ ] substrate-network
  - [x] substrate-network-libp2p
  - [ ] substrate-primitives
  - [ ] substrate-rpc
  - [ ] substrate-rpc-servers
  - [ ] substrate-serializer
  - [ ] substrate-service-test
  - [ ] substrate-service
  - [ ] sr-api-macros
  - [ ] sr-io
  - [ ] sr-primitives
  - [ ] sr-sandbox
  - [ ] sr-std
  - [ ] sr-version
  - [ ] substrate-state-db
  - [ ] substrate-state-machine
  - [ ] substrate-telemetry
  - [ ] substrate-test-client
  - [ ] substrate-test-runtime-wasm
  - [ ] substrate-test-runtime
  - [ ] substrate-transaction-graph
  - [ ] substrate-transaction-pool
  - [ ] substrate-trie
- node
  - [ ] node-cli
  - [ ] node-executor
  - [ ] node-primitives
  - [ ] node-runtime-wasm
  - [ ] node-runtime
- srml
  - [ ] srml-assets
  - [ ] srml-aura
  - [ ] srml-balances
  - [ ] srml-consensus
  - [ ] srml-contract
  - [ ] srml-council
  - [ ] srml-democracy
  - [ ] srml-example
  - [ ] srml-executive
  - [ ] srml-grandpa
  - [ ] srml-indices
  - [ ] srml-metadata
  - [ ] srml-session
  - [ ] srml-staking
  - [ ] srml-sudo
  - [ ] srml-support-procedural
  - [ ] srml-support
  - [ ] srml-system
  - [ ] srml-timestamp
  - [ ] srml-treasury
  - [ ] srml-upgrade-key
- [ ] subkey
- [ ] chain-spec-builder
