### ISSUE TITLE
Extremely high benchmarked pov_size

### ISSUE THREAD

**Issue by nbaztec** [paritytech/substrate#14156]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

**What**
While regenerating the weights for one of our benchmarks [here](https://github.com/PureStake/moonbeam/blob/b3049e79a264e43bdb5447aed9080c06c0db8c61/pallets/parachain-staking/src/benchmarks.rs#L1167) on the following machine

```
Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
31GiB System memory
INTEL SSDPE2MX450G7
```

We get extremely [high pov](https://github.com/PureStake/moonbeam/blob/b3049e79a264e43bdb5447aed9080c06c0db8c61/pallets/parachain-staking/src/weights.rs#L742) for the benchmarked extrinsic - `873144491150315`. The number of steps have some form of influence at lower values (10-40) where the pov_size is low but that could be a sampling issue. However, on higher step values (100+) the high pov_size is consistent and moves to the `y` parameter instead of the `z` (which is correct).

Code analysis and debugging did not yield any specific reason for the high pov size. The generated raw json file also contains all the pov_sizes under `25kB` for all combination of components so it's quite odd why the generated pov_size is so huge.

Any ideas?

/cc @crystalin 

### Steps to reproduce

```
cargo bulid --release --features runtime-benchmarks

./target/release/moonbeam benchmark pallet --execution=wasm --wasm-execution=compiled --pallet "parachain-staking" --extrinsic "delegate_with_auto_compound" --steps "200" --repeat "5" --template=./benchmarking/frame-weight-template.hbs --json-file raw.json --output "weights2.rs"
```

**Comment by crystalin** [comment]
changed code:
```
		println!("xs: {:?}, ys: {:?} r[0].components.len(): {}", xs, ys, r[0].components.len());
		let (intercept, slopes, errors) = linear_regression(xs, ys, r[0].components.len())?;
		slopes.iter().for_each(|x| println!(" - min_squares_iqr slope: {}", x));
```

=> 
```
xs: [0.0, 350.0, 100.0, 7.0, 350.0, 100.0, 14.0, 350.0, 100.0, 21.0, 350.0, 100.0, 28.0, 350.0, 100.0, 35.0, 350.0, 100.0, 42.0, 350.0, 100.0, 50.0, 350.0, 100.0, 57.0, 350.0, 100.0, 64.0, 350.0, 100.0, 71.0, 350.0, 100.0, 78.0, 350.0, 100.0, 85.0, 350.0, 100.0, 92.0, 350.0, 100.0, 100.0, 350.0, 100.0, 107.0, 350.0, 100.0, 114.0, 350.0, 100.0, 121.0, 350.0, 100.0, 128.0, 350.0, 100.0, 135.0, 350.0, 100.0, 142.0, 350.0, 100.0, 150.0, 350.0, 100.0, 157.0, 350.0, 100.0, 164.0, 350.0, 100.0, 171.0, 350.0, 100.0, 178.0, 350.0, 100.0, 185.0, 350.0, 100.0, 192.0, 350.0, 100.0, 200.0, 350.0, 100.0, 207.0, 350.0, 100.0, 214.0, 350.0, 100.0, 221.0, 350.0, 100.0, 228.0, 350.0, 100.0, 235.0, 350.0, 100.0, 242.0, 350.0, 100.0, 250.0, 350.0, 100.0, 257.0, 350.0, 100.0, 264.0, 350.0, 100.0, 271.0, 350.0, 100.0, 278.0, 350.0, 100.0, 285.0, 350.0, 100.0, 292.0, 350.0, 100.0, 300.0, 350.0, 100.0], ys: [14053.0, 14153.0, 14575.0, 15073.0, 15472.0, 16080.0, 16578.0, 16869.0, 17400.0, 17837.0, 18238.0, 18637.0, 19036.0, 19567.0, 20023.0, 20498.0, 20864.0, 21263.0, 21662.0, 21952.0, 22351.0, 22807.0, 23008.0, 23506.0, 24047.0, 24644.0, 25043.0, 25310.0, 25766.0, 26254.0, 26719.0, 27118.0, 27517.0, 27949.0, 28348.0, 28936.0, 29335.0, 29602.0, 30035.0, 30434.0, 30866.0, 31298.0, 31787.0] r[0].components.len(): 3
 - min_squares_iqr slope: 59.493314253700596
 - min_squares_iqr slope: 2380047954198464
 - min_squares_iqr slope: -8330167839694512
```

**Comment by ggwpez** [comment]
Yea can reproduce, thanks.

**Comment by ggwpez** [comment]
Interestingly enough, it dissapears for me when running with 300 steps.  
Will have to look at the concrete values if there are just so many outliers and the 3D formular in this case is just very imprecise.

**Comment by nbaztec** [comment]
One thing that stands out in the benchmark (not sure if it's relevant) is that one of the parameters depends on another.

Ideally the benchmark components should be like:

```rust
let x 0..=T::MaxDelegations();   
let y 0..=x;                            // y is always <= x
```

but since it wasn't posssible, we went with

```rust
let x 0..=T::MaxDelegations();   
let y 0..=T::MaxDelegations();          // y will be capped to min(x, y)
```

Not sure if this can throw off the benchmarking code in any way when it tries to find the values for what it believes are independent variables x & y.

**Comment by ggwpez** [comment]
Yea looking at the data it is not ideal with the `x` component. It increases for `x` until it hits a wall. Definitely not what the benchmarking expects. 
![image](https://github.com/paritytech/substrate/assets/10380170/4f819672-3e19-4713-b426-d5b992be187f)

When i hack `x` to end at 300, then the data is clean and the result is:  
`86543 + x * (258 ±0) + y * (12 ±0) + z * (125 ±1)` you see that there is nearly no standard deviation - as it should be.  
![image](https://github.com/paritytech/substrate/assets/10380170/8a11de57-43b2-40ea-825c-b029223b0c83)

**Comment by nbaztec** [comment]
Thanks @ggwpez the issue turned out to be a PEBKAC, but the python visualizer was certainly helpful in observing the anomalies. Bookmarking.
