### ISSUE TITLE
try-runtime snapshot do not use reference count on nodes

### ISSUE THREAD

**Issue by cheme** [paritytech/substrate#14150]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

`into_raw_snapshot` is taking all memory nodes of the memorydb use by the triebackend use in remote externality.
Memory-db internally store "hash of trie node" -> ("encoded_trie_node", "reference count").
But the snapshot do not keep the reference count info.
This can result in issue when playing something from snapshot over multiple block (if reference count is > 1 and one of the instance is removed, then the state get broken).

**Comment by kianenigma** [comment]
cc @liamaharon
