### ISSUE TITLE
srml-contract: Integration tests that ensure that tx is finalized correctly

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#1417]
We need to ensure that every transaction is finalized correctly, e.g.:

- Origin gets a refund for unused gas, even if tx is failed
- Origin can't buy more gas than is available in a current block
- Gas is consumed in any case even if tx itself has failed
- etc

**Comment by athei** [comment]
That does not make sense any longer as we removed the signed extensions (and hence all the "gas buying" logic).
