### ISSUE TITLE
Unsafe revert in `sc_client_api::backend::Backend` doesn't revert finalized blocks

### ISSUE THREAD

**Issue by shunsukew** [paritytech/substrate#14194]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug
Unsafe revert in `sc_client_api::backend::Backend` doesn't work as expected.

It is described in the [doc](https://github.com/paritytech/substrate/blob/e0de1010b5664f11ac0fcab41d167107649d4d00/client/api/src/backend.rs#L579) that "If `revert_finalized` is set it will attempt to revert past any finalized block".

However, providing `true` as its second arg doesn't revert finalized blocks.

### Background
For local contract development node, we'd like to have revert RPC feature (not cli subcommand) for convenience.
However, it doesn't revert finalized blocks. https://github.com/AstarNetwork/swanky-node/pull/68/files#r1200247675

In below image case, finalized block # 100, and attempted to revert to block # 50 via RPC.
The diff number is 50 but they aren't reverted.
<img width="776" alt="Screen Shot 2023-05-23 at 14 48 05" src="https://github.com/paritytech/substrate/assets/28953860/9598f4df-197f-4941-9716-139dcb4656bb">

**Comment by shunsukew** [comment]
@andresilva 
I see, thank you so much! and actually with `--pruning archive` reverting finalized blocks worked expected.

I have an additional concern now. 
I use `--state-pruning archive` (without `--block-pruning`) and reverting finalized block succeeded.
If I read Substrate command doc, it says `node keeps state of last 256 blocks by default`.
```
--state-pruning <PRUNING_MODE>
          Specify the state pruning mode.
          This mode specifies when the block's state (ie, storage) should be pruned (ie, removed) from the database.
          This setting can only be set on the first creation of the database. Every subsequent run will load the pruning mode from the database and will error if the stored mode doesn't match this CLI value. It is fine to drop this CLI flag for subsequent runs.
          
          Possible values:
          - archive:
          Keep the state of all blocks.
          - 'archive-canonical'
          Keep only the state of finalized blocks.
          - number
          Keep the state of the last number of finalized blocks.
          [default: 256]
```
So, if I understand correctly, without `--state-pruning archive`, it should be able to revert 256 finalized block at maximum, but the reality is not.

**Comment by juangirini** [comment]
This could continue as a [Stack Exchange](https://substrate.stackexchange.com/) question
