### ISSUE TITLE
speed up debug builds by skipping the wasm build

### ISSUE THREAD

**Issue by dvc94ch** [paritytech/substrate#14206]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

faster dev cycle

### Request

only build the native runtime in debug builds

### Are you willing to help with this request?

No.

**Comment by bkchr** [comment]
You can run with `SKIP_WASM_BUILD=1 cargo whatever` or set the variable.

In general we will remove support for the native runtime, so this will not help that much. Given that you can already skip the wasm build, I will close this pr.
