### ISSUE TITLE
Wasm runtime contains a `runtime_apis` custom section but no `runtime_version` section

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#14223]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

The Rococo v2.2 genesis runtime contains a `runtime_apis` custom section but no `runtime_version` section.
I've also noticed the problem with the Nodle genesis runtime.

This problem does **not** exist with the Westend, Kusama or Polkadot runtimes.

I've uploaded the decompressed Rococo v2.2 genesis runtime converted to ASCII here: https://gist.github.com/tomaka/52dfe5fd4588eecdf57b4418dce48483

According to the Wasm spec, a custom section contains: a 0 byte (indicating a custom section), then the length of the section, then the length of the name of the section, then the name, then the rest of the section.
See https://www.w3.org/TR/2022/WD-wasm-core-2-20220419/binary/modules.html#custom-section

If I grep `12, 114, 117, 110, 116, 105, 109, 101, 95, 97, 112, 105, 115` (12 bytes followed with `runtime_apis`) in the Rococo runtime uploaded above, there's one result.
But if I grep `15, 114, 117, 110, 116, 105, 109, 101, 95, 118, 101, 114, 115, 105, 111, 110` (15 bytes followed with `runtime_version`), there's no result.

**Comment by bkchr** [comment]
The rococo v2_2 chain spec was probably generated without this commit: https://github.com/paritytech/polkadot/commit/2da9a7e6bb185b5268afe24ba63b7506953bf4f3

The commit adding the v2_2 chain spec was added one day later, probably not including the commit above: https://github.com/paritytech/polkadot/commit/cc080f052b558db37c560b7a0367e37e46418601
