### ISSUE TITLE
Limit size of know messages hash in consensus gossip

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1424]
Currently the hashes of all known messagse are kept in memory (per channel) continuously growing in case the topic isn't cleared.  Allow peers to bombard the node with messages until it runs out of memory and even makes it forward all these messages (and therefore the upcoming bomb) to all newly connecting peers as neither is limited.

We should [limit the messages we forward to newly connecting peers](https://github.com/paritytech/substrate/blob/a2dfec4d3c467a481da70efb34f105e141a289fa/core/network/src/consensus_gossip.rs#L79-L87) (to the last X messages?) as well as [the messages we keep in memory in general](https://github.com/paritytech/substrate/blob/a2dfec4d3c467a481da70efb34f105e141a289fa/core/network/src/consensus_gossip.rs#L48-L54).

**Comment by rphmeier** [comment]
We have to be very careful not to drop messages on certain topics we are listening on for consensus, or at least to make it somehow possible to recover those messages if we start listening after they are dropped.

**Comment by abebeos** [comment]
> to bombard the node with messages until it runs out of memory and even makes it forward all these messages (and therefore the upcoming bomb) to all newly connecting peers as neither is limited.

This sounds like an attack-vector. Should have been fixed.

@bkchr

**Comment by bkchr** [comment]
This specific code doesn't exist anymore and the new code doesn't has this unbounded hashset anymore.
