### ISSUE TITLE
`consensus error: Chain lookup failed` in KSM node

### ISSUE THREAD

**Issue by Imod7** [paritytech/substrate#14249]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

In Integrations Team (Parity) we are supporting different teams that our running nodes. 

One of the teams who is running : 
- a KSM node (that has been running normally before)
- in k8s environment
- version :  v0.9.42
- with the command : 
   
     ![photo_2023-05-26_13-18-13](https://github.com/paritytech/substrate/assets/12569221/06643b88-aef5-4798-9a48-fdf149efbdae)
     _Note : I deleted the `in` and `out` peers flag since they removed now._
 
- p2p port is open

has reported the following error :

![photo_2023-05-26_10-10-52](https://github.com/paritytech/substrate/assets/12569221/3e6bcd31-46ff-4463-949e-89a07384d409)

```
2023-05-27 00:37:12 💔 Error importing block 0x7346229bf6197fb16c725e6367cfef142dd929294a0983f50af71a7c8fc0c2ce: consensus error: Chain lookup failed: No block weight for parent header.
```
and the node is not syncing.

### Logs
They provided logs with the `-lsync,sub-libp2p=trace` and `-lgrandpa=trace` flags which I uploaded here : [3.20230526-ksm-logs-btr.log](https://drive.google.com/file/d/1W5S-1HFYE0aCUE6Tfjh2VdrM4DrWRTgz/view?usp=share_link)

### Steps to reproduce

- Upgrade a KSM node to v.0.9.42

**Comment by bkchr** [comment]
Looks like the db got corrupted. Not that much you can do about this.

**Comment by Imod7** [comment]
@bkchr Thank you for the feedback! 
The team purged their database and is resyncing from scratch so closing this issue.
