### ISSUE TITLE
add `where` support for impl_function_executor macro

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1426]
Adding `where` support for `impl_function_executor` macro - which turns out to be non-trivial.

https://github.com/paritytech/substrate/blob/a2dfec4d3c467a481da70efb34f105e141a289fa/core/executor/src/wasm_executor.rs#L142

**Comment by pepyakin** [comment]
Do we actually still need this? My git archeology shows that @dvdplm might know!

**Comment by bkchr** [comment]
I think someone need to clarify this todo, why do we need a where bound?

**Comment by expenses** [comment]
This macro no longer exists so this issue can be closed.
