### ISSUE TITLE
try-runtime: pre/post hooks are not available in tests

### ISSUE THREAD

**Issue by liamaharon** [paritytech/substrate#14264]
`OnRuntimeUpgrade` `pre_upgrade` and `post_upgrade` hooks are feature gated like this: https://github.com/paritytech/substrate/blob/06d8934fe3a10f5f02b930dd14e4e3bf4baf21b0/frame/support/src/traits/hooks.rs#L172

This makes the hooks are unavailable in test environments, so if you want to use the hooks in tests you need to implement an annoying pattern of creating two new functions with looser restrictions (usually `do_pre_upgrade`/`do_post_upgrade` is chosen), like suggested here: https://github.com/paritytech/substrate/pull/14218#discussion_r1209546736.

I suggest loosening the pre/post hook feature gates to `#[cfg(any(feature = "try-runtime", test))]` so they can be used in the tests directly, and we don't need to do anymore `do_pre_upgrade`/`do_post_upgrade` business just to get tests working.

Each hook has a noop default implementation, so I don't think it would break anything or require any broader refactors.

**Comment by kianenigma** [comment]
If you want to use these functions in the tests of any other crate other than `frame-support` where they are defined, `#[cfg(any(feature = "try-runtime", test))]` will not work, which is quite annoying.

AFAIK, a rule of thumb is: `cfg(test)` is always only local to the crate. You can't use it to share code between `#[cfg(test)]` of two crates. I don't exactly know the reasoning and the underlying mechanism, would be curious to know more.

Or am I wrong? will your issue be solved if `#[cfg(any(feature = "try-runtime", test))]` is used?

**Comment by liamaharon** [comment]
Ah I was not aware of that, you're right. Here is the reasoning:

> The #[cfg(test)] attribute is local to the crate, meaning that it is not exported to other crates. This is because when your library is compiled as a dependency, it's not compiled in test mode. The primary reason for this is to avoid having test dependencies affecting the dependency tree of a crate that depends on your crate.

I guess this won't work, closing the issue.

**Comment by ggwpez** [comment]
Why not just add `frame-support` as dev-dependency and enable the `try-runtime` feature @liamaharon ?
