### ISSUE TITLE
`sp-api` should not depend on `frame-metadata`

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#14296]
Not all Substrate blockchains use frame. However, all Substrate blockchains will use `sp-api` for the core and blockbuilder apis among others.

Currently `sp-api` has a hard dependency on `metadata-ir` which has a hard dependency on `frame-metadata`. Both `metadata-ir` and `frame-metadata` are very frame-specific, and are not used by non-frame chains. They should also not have to be compiled.

**Comment by bkchr** [comment]
The entire requirement of needing to pass some kind of `Runtime` type into `impl_runtimes_apis!` comes from being written with FRAME in mind. However, we can probably improve the situation (while technically it will not change anything for you besides not compiling the packages).

We should make the `metadata-ir` stuff optional behind a feature and then change `frame-support` to always activate this feature. Thus, you should not be required to pull in any FRAME deps when not building a FRAME based runtime.
