### ISSUE TITLE
try-runtime-cli: support testing new multi-block migrations

### ISSUE THREAD

**Issue by liamaharon** [paritytech/substrate#14291]
@kianenigma am I right to assume we'll want to make it easy to test these with try-runtime-cli? Ideally should be as easy as `on-runtime-upgrade`, maybe make it auto-mine blocks until all multi-block migrations are complete & provide a hook that runs afterwards?

_Originally posted by @liamaharon in https://github.com/paritytech/substrate/issues/14275#issuecomment-1570824518_
            

Kian response:
> Good to think about it early, and yes I think it is possible with little effort. I believe follow-chain will already do everything needed to test an MBM?

---

I don't think `follow-chain` is necessarily a good solution. 
1. We need to call each upgrade's `post_upgrade` hook once its migration has finished executing.
2. We can't use snapshots with `follow-chain`, making development iterations much slower and requiring a live node running. Some of the plumbing in `fast-forward` is might be a better solution here?

Ideally, I think we'd be able to run `on-runtime-upgrade` like usual and it'll fast-forward until all migrations have completed, and then run a post_migration hook. Unfortunately fast-forward is not production ready due to the [inherents issue](https://github.com/paritytech/substrate/issues/13887), it seems this feature makes fixing the inherents issue much higher priority now?

**Comment by ggwpez** [comment]
I think `fast-forward` is good, since `follow-chain` applies extrinsics; those get rejected while MBMs are active anyway.  
Just calling `on_runtime_upgrade` and then `on_initialize` repeatedly until event `UpgradeCompleted | UpgradeFailed` is received is enough AFAIK.

**Comment by liamaharon** [comment]
Yeah, repeatedly calling `on_initialize` is a better @ggwpez 👌 

What do you think about adding a `try-runtime` feature gated method to the migrations pallet called something like `run_to_completion` that does that? That way, the cli tool needs not be concerned about the mechanism that migrations progress.

**Comment by liamaharon** [comment]
Moved to https://github.com/paritytech/try-runtime-cli/issues/17
