### ISSUE TITLE
Add formatting support to the `ensure` macro

### ISSUE THREAD

**Issue by liamaharon** [paritytech/substrate#14301]
Not sure if `ensure!` can do formatting.

_Originally posted by @ggwpez in https://github.com/paritytech/substrate/pull/14241#discussion_r1211423472_
            
--- 

Unlike `assert`, `ensure` does not support string formatting.

**Comment by ggwpez** [comment]
I am not sure if it ever could - since we use it in no-std and there is no `format!`.  
Other thing is that we normally use it with `DispatchError` and that requires `&'static str`, so not even `format!` would help.

**Comment by bkchr** [comment]
Yeah, this makes no sense. In contrast to `assert`, `ensure` doesn't take any string and thus should not support any kind of formatting. The second argument can be anything and is just the return if the check fails.
