### ISSUE TITLE
Restarting a node results an IO Error

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#1430]
Whenever we are restarting a substrate node we need to kill the `ws-port`. If we don't do this we are getting an `io-error` for that particular node. 
Seems the ws-port keeps communicating with the node's DB 
 It will be a nice to have a feature to wrap this in a simpler substrate command since many will find it hard to restart a node and they will kill the whole process and even delete the node's database.

**Comment by bkchr** [comment]
By restart you mean, restarting the program? How do you kill the ws-port?

**Comment by Kalanamith** [comment]
@bkchr by getting the process id and killing it using kill -9 . I can safely restart the node after doing it

**Comment by bkchr** [comment]
@andresilva any idea?
@Kalanamith you close the node by pressing ctl + c?

**Comment by Kalanamith** [comment]
Hi @bkchr  Yes I did. But um not running nodes from a release build. Will this has an effect?

**Comment by bkchr** [comment]
Are you running it on Linux?

**Comment by Kalanamith** [comment]
Im running it on MacoS

**Comment by bkchr** [comment]
@Kalanamith https://github.com/paritytech/substrate/pull/1367 this pr should solve your problem. Can you test with latest master?

**Comment by Kalanamith** [comment]
@bkchr  It works now, 
Closing the issue
