### ISSUE TITLE
Bug :- Restarting a node results an error thread 'ImportQueue' panicked at 'attempt to subtract with overflow

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#1431]
I am trying to restart a substrate full node as a validator node and I am getting the following error.

`thread 'ImportQueue' panicked at 'attempt to subtract with overflow'`

This is thrown by the code 

```rust
let next_slash = slash << 1;
let _ = Self::slash_validator(&v, slash);
```
How to fix this issue in Substrate whenn restarting a node?

**Comment by bkchr** [comment]
Did you tried latest master? Based on a quick search, this was changed recently and it looks like your error was fixed.

**Comment by Kalanamith** [comment]
This was tested on yesterdays codebase (14/01/2019). Will check on latest master and update. Thanks

**Comment by Kalanamith** [comment]
Closing the issue since it's cannot be reproduced for the latest code base today
