### ISSUE TITLE
[Umbrella issue] Revisit constants and config storage params of pallets related to staking 

### ISSUE THREAD

**Issue by gpestana** [paritytech/substrate#14321]
It's probably a good time to revisit some of the configurations of staking, EPM and nomination pools pallets. This [spreadsheet](https://docs.google.com/spreadsheets/d/1obNJAYJZLbdUe6ZAasZaDhk77MSM8EMVgjpID8VCYGU) lists all the constants and configuration parameters and their current values in Polkadot and Kusama.

### Configs to revisit/update

- [x] **Increase nomination pools limits**
[Polkadot forum thread](https://forum.polkadot.network/t/next-revision-of-increasing-nomination-pool-limits/2498)
Increase `maxPools`, `maxMembers` and `maxPoolMembersPerPool` in Polkadot, Kusama and Westend. The current values and suggested new values are:

| Runtime::*  |  Current Values | Current state | Suggested new values |
| ------------- | ------------- | ------------- | ------------- |
| `Polkadot::maxPools`  | 256 | 128 | 512 |
| `Polkadot::maxPoolMembers`  | 16,384  | 11,250 | 49,152 |
| `Polkadot::maxPoolMembersPerPool` | None | max at 3307 | None (unchanged) |
| `Kusama::maxPools`  | 256 | 141 | None |
| `Kusama::maxPoolMembers` | 65,536  | 915 |  None |
| `Kusama::maxPoolMembersPerPool`  | 1,024 | max at 24 | None |
| `Westend::maxPools`  | 512  | 192 | None |
| `Westend::maxPoolMembers`  |  524,288 | 11,960 | None |
| `Westend::maxPoolMembersPerPool`  |  None | max at 16 | None |

The `maxPoolMembers` in Polkadot is very close to be exhausted, we should increase the bound asap. As for Kusama and Westend, we can remove all the limits and eventually propagate that to Polkadot.

- [x] **Revisit nomination pool commission parameters** 
[Polkadot forum thread](https://forum.polkadot.network/t/next-revision-of-increasing-nomination-pool-limits/2498)

Raise the global max commission from 0% on Polkadot to 10% (needs v9420 deployed before this parameter can be amended)

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/next-revision-of-increasing-nomination-pool-limits/2498/6

**Comment by rossbulat** [comment]
Updated nomination pool configs & global max commission is now on OpenGov for vote:
- Polkadot: https://polkadot.polkassembly.io/referenda/39
- Kusama: https://kusama.polkassembly.io/referenda/227
