### ISSUE TITLE
Use default config trait in mock runtimes

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#14336]
Would be good if we start using the default config trait from https://github.com/paritytech/substrate/pull/13454 to ensure that we covered most use-cases. For example in all `mock.rs` files on `frame_system` and maybe also `pallet-balances`.  
Now we can still make some adjustments before more downstream projects start using it.  
cc @juangirini 

(This brings me to the idea that we could have a `nightly` or `unstable` module in `frame-support`, where we throw stuff in that has not been battle tested.)

**Comment by kianenigma** [comment]
Isn't this one item in https://github.com/paritytech/substrate/issues/14234?

**Comment by juangirini** [comment]
It looks like a good candidate for a sub issue of the tracking one

**Comment by kianenigma** [comment]
Still seems like the list of pallets I have in https://github.com/paritytech/substrate/pull/14453 :D

**Comment by ggwpez** [comment]
yea, duplicate.
