### ISSUE TITLE
[FRAME/Meta/PM] "experimental" `FRAME` features

### ISSUE THREAD

**Issue by ggwpez** [paritytech/substrate#14345]
Analogous to the deprecation process it would be nice to have an on-ramp for new features in FRAME.
This could be used to introduce new feature in a non-semver way, so that we can start integrating them before stabilizing the design.  
I think it could increase our development velocity since we can iterate quicker on features without having to worry too much of breaking downstream. Currently I often try to keep breaking changes to a minimum - even when a feature is not used outside of Parity yet…

## Possible implementations

There were some internal discussions about how to achieve this. Some ideas:
- **A**) Some attribute macro like `frame_unstable(id)` or similar and a matching `allow_unstable(id)` where `ID` is the identifier of the issue, similar to rust nightly features. This would be the more fine-grained and elegant solution - although not sure how achievable without something like https://github.com/rust-lang/rust/issues/62398
- **B**) Rust compiler features where we have one feature that guards all unstable features. This would need to be propagated to all dependencies… we already have enough problems just from `try-runtime` and `runtime-benchmarks` though.
- **C**) Simplest would be to have a `frame_support::unstable` module, that export all unstable types. Or in the future just `frame::unstable`. The unstable features should not be accessible through another path. We can do this in `frame_support` since the modules can be made `pub(super)`, such that the `unstable` module can export them.

Inside of pallets we have more control and could opt for a better DevEx. For example with the upcoming Task API we could mark that as *unstable* and emit a warning that can be silenced through `pallet(unstable)` or something.

## Process

Without making this too cooperate-style bureaucratic I think we should still have *some* kind of process. For example:  
1. Put new non-trivial traits and types, where future changes are expected, into the `unstable` module. For example we could use that for the [VersionedRuntimeUpgrade](https://github.com/paritytech/substrate/pull/14311) or the [`Multi Block Migrations`](https://github.com/paritytech/substrate/issues/13690).
2. Start integrating the feature to discover sharp edges and improvements.
3. Set a deadline for further changes and move it out to the normal FRAME crates afterwards.
4. Maybe announce the feature somehow.

cc @kianenigma @sam0x17 @juangirini

**Comment by xlc** [comment]
unstable doesn’t means insecure right? if that’s the case, why do we need warnings? you need to implicitly import from unstable module to use it and I think that’s enough

**Comment by sam0x17** [comment]
I think it's more like "could change at any time"

Maybe the word "experimental" would be better

**Comment by bkchr** [comment]
> * something like an `unstable` module seems like the most reasonable path forward for now.

How should this work for things that require changes to any `Config` trait? 

IMO, as annoying as features can be, they are probably the best way forward.

**Comment by xlc** [comment]
Please don't abuse deprecation message. Only mark deprecated features deprecated.

**Comment by juangirini** [comment]
> unstable doesn’t means insecure right? if that’s the case, why do we need warnings? you need to implicitly import from unstable module to use it and I think that’s enough

Independently of whether we go for the **features** or the **modules** solution, this is a very good point and it would simplify things. I guess it was meant read _explicitly import_, in this or in the features case the developer is already aware of the `experimental` feature.



> Maybe the word "experimental" would be better

+1 on this one, it sounds less scary

**Comment by kianenigma** [comment]
Having thought about this a bit, I am leaning toward backing using a feature flag for this.

**Comment by sam0x17** [comment]
And consensus seems to be we call it "experimental" instead of "unstable"

**Comment by ggwpez** [comment]
So its settled then; we use an `experimental` feature that is never enabled per default.  
We can even apply this to pallets and non-FRAME crates :tada:  

-----------

We could use https://github.com/paritytech/substrate/pull/14311 as an example to try it out.

**Comment by liamaharon** [comment]
I believe we need to update the Substrate CI to run experimental tests? It seems that the test CI is configured outside of this repo, what's the way to go about tweaking that?

**Comment by bkchr** [comment]
No, the CI is configured in here: https://github.com/paritytech/substrate/blob/master/scripts/ci/gitlab/pipeline/test.yml

There you will need to change/add a new job.

**Comment by kianenigma** [comment]
@juangirini @ggwpez @paritytech/frame-coders any reason to not close this?

**Comment by juangirini** [comment]
@ggwpez https://github.com/paritytech/substrate/pull/14311 should have close this issue, right? or is there anything else that you want to do?

**Comment by ggwpez** [comment]
Yea it should be good. There were some follow up discussions on how to separate feature-gates and modules, but we can reopen it then.
