### ISSUE TITLE
Deploy contract memory limits error. 

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1434]
https://github.com/paritytech/substrate/blob/a66a044b24288a82e0cc5ebbb67ed7b4420f15ea/srml/contract/src/vm/prepare.rs#L188

use https://github.com/pepyakin/substrate-contracts-adder contract to deploy
follow error: 
intial = 17,  maximum = 16.

**Comment by holygits** [comment]
Fix for this it to compile contract with latest nightly
