### ISSUE TITLE
To get the validators&nominators history record of reward, is trouble

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/substrate#1435]
Polkawallet project to need query the record of validators&nominators history reward. is very trouble. Requires underlying support. Or there have any easier way to get this information.

**Comment by rphmeier** [comment]
You should be able to watch for storage updates to the event storage, and look for reward events.
To look into history, the storage-changes-tree should be possible to inspect.

If your use case is to query for all rewards that have ever happened in the history, then this is an antipattern. What if the chain was 10 million blocks? This query would take ages regardless.
