### ISSUE TITLE
The published crate `substrate-build-script-utils` is two version ahead of the code here.

### ISSUE THREAD

**Issue by Neopallium** [paritytech/substrate#14366]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

crates.io has two version `5.0.0` and `4.0.0`, but the code here is only at version `3.0.0`
Published versions here: https://crates.io/crates/substrate-build-script-utils/versions

The source in the repo shows only version `3.0.0`:
https://github.com/paritytech/substrate/blob/master/utils/build-script-utils/Cargo.toml

**Comment by bkchr** [comment]
Yeah we never merged this pr: https://github.com/paritytech/substrate/pull/12946

The code is the same as in master, just the version bumped. We are working on doing proper releases to crates.io.
