### ISSUE TITLE
cleaner way to prevent double block initialization

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1438]
Our check to ensure a block isn't initialized twice isn't very elegant at the moment:

https://github.com/paritytech/substrate/blob/a2dfec4d3c467a481da70efb34f105e141a289fa/core/client/src/call_executor.rs#L188

Replace it with a better and more explicit solution.

**Comment by expenses** [comment]
I believe this was closed by bb07c76ebd979154d3efc67f55ec3fd6fee575da: https://github.com/paritytech/substrate/commit/bb07c76ebd979154d3efc67f55ec3fd6fee575da#diff-e1db240b5937ee7558375dc760bc09f4L1052-R1045.

**Comment by bkchr** [comment]
Yeah this is fixed.
