### ISSUE TITLE
Split QueueInfo from ClientInfo and amalgate into single struct

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1440]
Should be possible to amalgate ChainInfo into ClientInfo:

https://github.com/paritytech/substrate/blob/a2dfec4d3c467a481da70efb34f105e141a289fa/core/client/src/client.rs#L107-L114

**Comment by tomusdrw** [comment]
What does it help with exactly? I actually like the fact that we have a nice separation between `Client` and `Blockchain` state. And the `info` call is just proxied (I'd say it would be even better to just use blockchain directly).

**Comment by gnunicorn** [comment]
this was opened when removing inline todos and fixmes. has been fixed meanwhile. closing.
