### ISSUE TITLE
Block import notifications are not fired for blocks that are imported manually

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/substrate#14448]
`ImportQueueService::import_blocks` calls do not result in either `import_notification_stream` or `every_import_notification_stream` notifications.

This seems like a bug that should be fixed, my assumption was that `every_import_notification_stream` is fired for literally every imported block, no matter the source and whether it is on canonical chain or not.

_Originally posted by @nazar-pc in https://github.com/paritytech/substrate/issues/14442#issuecomment-1604233068_

**Comment by bkchr** [comment]
Hmm, I checked the code and not sure why there is no notification send. You are sure that the blocks are really imported?

https://github.com/paritytech/substrate/blob/8dc42cf7b27bfa0290d5db847fbeac74ce8d810e/client/service/src/client/client.rs#L822-L830 could you add here some logs verifying that this is really not called when you have registered a listener?

**Comment by nazar-pc** [comment]
Double checked and you're right, it works as expected.
