### ISSUE TITLE
Sync doesn't update blocks it needs to sync over time

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/substrate#14442]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I have a sidecar sync protocol added that pulls blocks from an alternative source and imports them directly into the node using `ImportQueueService::import_blocks`.

The reason for that is that consensus in our protocol is based on storing the blockchain history, so we can pull deeper blocks from distributed storage network (DSN), while consensus nodes are pruning their older history.

So I do expect though Substrate's sync to finish off the recent blocks after I have uploaded deeper history.

The issue is that Substrate seems to be confused as to what blocks it should download and gets stuck.

Source node:
```
2023-06-22 16:49:07.191  INFO tokio-runtime-worker substrate: [PrimaryChain] ⏳ Pending (1 peers), best: #182 (0x47d3…51fe), finalized #128 (0x4fb5…6db5), ⬇ 0.6kiB/s ⬆ 0.6kiB/s    
2023-06-22 16:49:11.303 DEBUG tokio-runtime-worker sync: [PrimaryChain] Handling block request from 12D3KooWRXRBeSsV4zsQXLHQ2LTNisTWcu5gwGQjHumFkrcZ2MTe: Starting at `BlockId::Number(28)` with maximum blocks of `28`, reputation_change: `None`, small_request `false`, direction `Descending` and attributes `HEADER | BODY | JUSTIFICATION`.    
2023-06-22 16:49:11.303 DEBUG tokio-runtime-worker sync: [PrimaryChain] Sending result of block request from 12D3KooWRXRBeSsV4zsQXLHQ2LTNisTWcu5gwGQjHumFkrcZ2MTe starting at `BlockId::Number(28)`: blocks: Some(0), data: Some(0)    
```

Node that tries to sync:
```
2023-06-22 16:49:07.293  INFO tokio-runtime-worker substrate: [PrimaryChain] 💤 Idle (0 peers), best: #163 (0x0f12…9ec0), finalized #90 (0x724d…c46c), ⬇ 0.6kiB/s ⬆ 0.6kiB/s    
2023-06-22 16:49:11.301 DEBUG tokio-runtime-worker sync: [PrimaryChain] New peer with best hash 0x47d3…51fe (182).    
2023-06-22 16:49:11.301 DEBUG tokio-runtime-worker sync: [PrimaryChain] Connected 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp    
2023-06-22 16:49:11.303 DEBUG tokio-runtime-worker sync: [PrimaryChain] Received block that was not requested. Requested Number(28), got None.    
2023-06-22 16:49:11.304 DEBUG tokio-runtime-worker sync: [PrimaryChain] 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp disconnected    
```

As you can see, there is no point in requesting block 28, it was already imported from DSN and pruned from the source node.

I can get it un-stuck if I stop and start again both nodes, but it seems like a bug and should detect that local block height has changed without restart.

**Comment by altonen** [comment]
IIUC you have two syncing implementations running in parallel that import blocks and the one Substrate provides should listen to import events and update its book keeping accordingly?

I don't think `sc-network-sync` is expecting blocks to be imported from any source other than itself while the sync is progress and AFAIR there is no expectation in the implementation that a block could just appear without it having been downloaded. If would complicate our design if we have to assume that someone could be importing blocks at the same time while syncing is running and I think it would be preferable if you'd let your custom sync to download the deep history first and only then start Substrate's syncing with the information that was downloaded & imported from your DSN. Any thoughts @bkchr?

**Comment by nazar-pc** [comment]
You understanding is correct.

> I think it would be preferable if you'd let your custom sync to download the deep history first and only then start Substrate's syncing with the information that was downloaded & imported from your DSN

That is exactly what we did first, but there are cases where node loses Internet and then needs to sync to the new tip, which with only pruned nodes on the network is not possible without our DSN.

**Comment by nazar-pc** [comment]
I'm also looking for workarounds in the meantime. It doesn't seem like it should be very difficult to poll `client.info()` to see if something was imported in the meantime.

**Comment by nazar-pc** [comment]
I think changing `import_notification_stream` to `every_import_notification_stream` here might do the trick:
https://github.com/paritytech/substrate/blob/074dc1dfee4132b597db6eb147a86c72b751f03c/client/service/src/lib.rs#L165-L197

**Comment by altonen** [comment]
> That is exactly what we did first, but there are cases where node loses Internet and then needs to sync to the new tip, which with only pruned nodes on the network is not possible without our DSN.

Could you elaborate on this? Why is losing the internet connection related to this problem and how does having the syncing implementations running in parallel fix it whereas running them one after the other doesnt?

I don't think detecting that a block was imported in `sc-network-sync` is the difficult part but having additional code in the syncing state machine to invalidate/update the peer records/active requests. To me this doesn't sound like a bug but a feature request of adding support for multiple parallel "block sources" and having these sources be tolerant of work stealing. We have started refactoring `sc-network-sync` so if this is considered something Substrate should support (which I don't necessarily agree with), it would have to come only after we've finished the refactoring work.

**Comment by nazar-pc** [comment]
> Could you elaborate on this? Why is losing the internet connection related to this problem and how does having the syncing implementations running in parallel fix it whereas running them one after the other doesnt?

Imagine most (all) nodes on the network are pruned, meaning they are persisting, let's say, last 1000 blocks only. Then one node looses Internet connection for such amount of time that more than 1000 blocks were produced in the meantime. Now node is back online, but there is no node on the network that would be able to serve blocks that are more than 1000 blocks deep from current tip.

What we want to do is to pull and import most of the blocks from DSN (let's say up to 100th block from the tip) and then sync the rest from Substrate nodes using built-in sync since those newer blocks are not archived on DSN yet.

> having additional code in the syncing state machine to invalidate/update the peer records/active requests

This is actually I'm a bit confused about. According to above logs connection is dropped, so upon reconnection state of the sync progress with that peer should be reset, but looks like it is not.

**Comment by altonen** [comment]
>What we want to do is to pull and import most of the blocks from DSN (let's say up to 100th block from the tip) and then sync the rest from Substrate nodes using built-in sync since those newer blocks are not archived on DSN yet. And all of this should happen without application restart.

I still don't fully understand how this works. If most (all) of the nodes on the network have pruned all but the most recent 1000 blocks but these pruned blocks haven't reached the DSN yet, who are they being downloaded from?

>This is actually I'm a bit confused about. According to above logs connection is dropped, so upon reconnection state of the sync progress with that peer should be reset, but looks like it is not.

Can you post `-lsync=trace` logs over a longer period of time that would show the issue?

**Comment by nazar-pc** [comment]
> I still don't fully understand how this works. If most (all) of the nodes on the network have pruned all but the most recent 1000 blocks but these pruned blocks haven't reached the DSN yet, who are they being downloaded from?

To the best of our knowledge Subspace is the first protocol that resolved blockchain trilemma. Without asking you to read the technical documentation it is sufficient to know that we have two pieces of software on the network: nodes and farmers. Farmers are like miners in PoW protocols, but they use disk space for solving a puzzle and that space is occupied by the encoding of the history of the blockchain itself.

Since farmers store useful data and not random stuff (like Chia), they cumulatively form a distributed storage network, so that they can be used not just for consensus purposes, but also as a source of data from archived blockchain history, in particular, nodes can use it to reconstruct original blocks that can later be imported.

None of the farmers can (or will be able to at full scale) store the whole blockchain history individually, and nodes should be pruned to not cause farmers dilemma since they are not incentivized to store node's data, they want to dedicate as much space as possible to consensus on the farmer.

As the result node needs to be pruned as much as possible, yet there should still be a way to sync from genesis.

> Can you post -lsync=trace logs over a longer period of time that would show the issue?

Sure, here is the setup: node "From" is started first and filled with history such that it ends up with this state (`--blocks-pruning 100`):
```
best: #226 (0xc724…c960), finalized #187 (0xa443…1bba)
```
I stop "From".

Then I start node "To", it doesn't have any peers and is waiting for "From" to start again, its logs:
[node-to.log](https://github.com/paritytech/substrate/files/11847776/node-to.log)

After this I start node "From" again and "To" will try to sync (both using DSN to the height 186 and further to height 226 using "From"):
[node-from.log](https://github.com/paritytech/substrate/files/11847781/node-from.log)

As you can see, "To" keeps requesting first 64 blocks even though it is already on block 186.

**Comment by nazar-pc** [comment]
Hm... I think none of those import calls actually result in block import notification (neither `import_notification_stream` nor `every_import_notification_stream`), which is odd and would explain at least part of the issues I'm seeing.

**Comment by nazar-pc** [comment]
For those who read this in the future, adding this after sync from DSN did the job:
```rust
let info = client.info();
sync_service.new_best_block_imported(info.best_hash, info.best_number);
```
