### ISSUE TITLE
Default Config is not able to provide defaults for types that access other associated types

### ISSUE THREAD

**Issue by gupnik** [paritytech/substrate#14473]
Seems like this is an issue with `derive_impl`. I see this error when I try to remove `pallet::no_default`:
```the trait bound `Self: pallet::Config` is not satisfied```. 
CC: @sam0x17

_Originally posted by @gupnik in https://github.com/paritytech/substrate/pull/14437#discussion_r1244667598_

**Comment by gupnik** [comment]
As an example, `BlockHashCount` when retrieved from `Block` leads to this error.

**Comment by bkchr** [comment]
Already tracked in this issue: https://github.com/paritytech/substrate/issues/14234

**Comment by sam0x17** [comment]
potential solution here: https://github.com/paritytech/substrate/pull/14437#discussion_r1251861668
