### ISSUE TITLE
Client should be able to provide uncles

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1448]
The user should specify how many generations back uncles will be accepted from. Uncles of a block B are the children of an ancestor of B, which are not ancestors of B themselves.

This is useful for consensus and rewards schemes. In Aura, including can prevent us from slashing validators who issued a block on a small fork.

**Comment by marcio-diaz** [comment]
I have a question, is this function going to be always executed on a target node that is head of the chain (without children)? Otherwise, I think that implementing it using the function `leaves` may end up being inefficient (I don't see a way to get the children of a block).

**Comment by rphmeier** [comment]
The way we do it in `parity-ethereum` is to add a list of children to each block in the DB. When importing a block with hash H, we add H to `parent(H)`'s list of children. Once this metadata exists it's fairly easy to compute uncles.
