### ISSUE TITLE
contracts: Store the code size in `CodeInfo`

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#14507]
When loading contract code from storage we don't know its size before loading. This results in the side effect that we need to [pre-charge assuming a maximum sized contract and adjust](https://github.com/paritytech/substrate/blob/dfd82860feb5da6f74ca2aa04414d9cebe310204/frame/contracts/src/wasm/mod.rs#L379-L383) after loading. This can get quite costly for nested call stacks or just for contracts that call many other contracts and do nothing else.

To fix this issue we should store the code size into the `CodeInfo` storage item which we have to load from storage anyways.

**Comment by pgherveou** [comment]
We are mainly interested in this [QueryPreimage](https://paritytech.github.io/substrate/master/frame_support/traits/trait.QueryPreimage.html)  that exposes a len and fetch method and [PreImageRecipient](https://paritytech.github.io/substrate/master/frame_support/traits/trait.PreimageRecipient.html) to note (aka store a preimage)

**Comment by athei** [comment]
> There are no concerns that doing an extra io to fetch the len of the preimage reduce the overall benefits of the pallet?

Having to do another storage item access to get the length vs. overcharging is the trade off we have to decide here.

> Also, What about simply storing the len in the CodeInfo struct?

I was just thinking: Why re-implement something that already exist. But since we have to load the `CodeInfo` anyways we can just put the value there and get the info basically for free.

**Comment by pgherveou** [comment]
that's what  I did here -> 
https://github.com/paritytech/substrate/pull/14523https://github.com/paritytech/substrate/pull/14523

if we merge it fast I think we can just re-use @agryaznov 's v12 migration and add the extra field in there
