### ISSUE TITLE
Link to llvm on Mac OSX in README

### ISSUE THREAD

**Issue by jaybutera** [paritytech/substrate#1454]
The "Hacking on Substrate" section of the readme file instructs Mac users to 
`brew install llvm`

but this won't necessarily override the llvm path if a user is using Xcode build tools. I recommend adding an instruction to temporarily set the new path
`export PATH="/usr/local/opt/llvm/bin:$PATH"`

or whatever their path is from `brew --prefix llvm`. That got substrate to build for me.

**Comment by pepyakin** [comment]
Hm, that's interesting, I wonder why would you install llvm from brew and not using Xcode build tools in the first place

**Comment by jaybutera** [comment]
I don't know exactly, but Xcode uses an older version of llvm for build safety. And brew is just a way to get the latest version. When building substrate with xcode llvm I got compilation errors on rocksdb so it's definitely necessary. But I wouldn't permanently link to the brew llvm because that may mess up some apple build process.

**Comment by pepyakin** [comment]
I'm curious because I've been using Xcode build tools without any problems for building substrate on daily basis : ) 

May be it is caused by an outdated version of xcode build tools? Mine is `Apple LLVM version 10.0.0 (clang-1000.10.44.4)`

> But I wouldn't permanently link to the brew llvm because that may mess up some apple build process.

yeah true

**Comment by jaybutera** [comment]
Strange I have `Apple LLVM version 10.0.0 (clang-1000.11.45.2)`

Have you built from a new clone recently?

**Comment by pepyakin** [comment]
Yeah : ) But what I haven't done for some time is clean rebuild. Although I certainly did a clean build since my last update of macOS/Xcode.

**Comment by bkchr** [comment]
We are no longer mentioning the installation steps in the README. So, I think this issue is obsolete and can be closed.
