### ISSUE TITLE
Avoid sending finality notifications unconditionally

### ISSUE THREAD

**Issue by andresilva** [paritytech/substrate#1461]
During synchronization we might finalize a large number of blocks and we want to avoid spamming listeners with finality notifications.

https://github.com/paritytech/substrate/blob/b57c458587e5e41b785b0197daa00723cccca488/core/finality-grandpa/src/lib.rs#L891-L893

**Comment by gavofyork** [comment]
Is this still relevant @andresilva ? I'm assuming not, but if so please reopen.
