### ISSUE TITLE
[RPC-Spec-V2] Cancel ongoing operations

### ISSUE THREAD

**Issue by lexnv** [paritytech/substrate#14639]
Cancel any ongoing operation identified by the unique operation ID:
- `chainHead_stopBody`, `chainHead_stopCall` and `chainHead_stopStorage` are removed
- the `chainHead_stopOperation` will terminate any operation that is pending a result
- it is possible that an ongoing operation has already produced the result before the user calls this method 

// @paritytech/subxt-team

**Comment by tomaka** [comment]
For what it's worth I don't think you need to implement this properly in a full node, given that you send back the results immediately. The only exception is when a `chainHead_storage` is in a `waiting-for-continue` state.
