### ISSUE TITLE
Retire `storage_items!`

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#1466]
The `storage_items!` macro should be removed in favor of `decl_storage_items!`.

[Here](https://github.com/paritytech/substrate/blob/8ef14908ad9d46840db58808a72516ba9fb6602f/srml/support/src/storage/generator.rs#L197) the macro can be found.

While that is done, `StorageList` trait should be removed as well.

**Comment by sorpaas** [comment]
I still think this macro can be useful in some situations where we cannot use SRML. For example, currently in Shasper, I’m using this to declare all storage items.

https://github.com/paritytech/shasper/blob/master/runtime/src/storage.rs

**Comment by bkchr** [comment]
Depends on: https://github.com/paritytech/substrate/issues/1467

**Comment by kianenigma** [comment]
@bkchr how about I do this during #3071 ? 

StorageList also seems to be already gone?

**Comment by thiolliere** [comment]
> how about I do this during #3071 ?

does it helps you implementing it ?
Otherwise I would argue agains't as Wei says it has some needs so it might require some discussion in 1467

**Comment by bkchr** [comment]
> > how about I do this during #3071 ?
> 
> does it helps you implementing it ?
> Otherwise I would argue agains't as Wei says it has some needs so it might require some discussion in 1467

:+1:

**Comment by expenses** [comment]
`storage_items!` is no longer used in shasper, and is only used in `test-runtime/system`. I'm unsure how we properly get rid of it though. Do we declare a module there?

**Comment by bkchr** [comment]
@sorpaas you don't need it anymore?

Changing `test-runtime` will probably be relative easy :)
