### ISSUE TITLE
Move `srml_support::storage` to core or off-tree

### ISSUE THREAD

**Issue by sorpaas** [paritytech/substrate#1467]
While it is not much needed in any SRML runtime or in current Substrate codebase, macros like `storage_items!` provided by `srml_support::storage` still serve purposes for those non-srml runtimes, because what they need is a really thin wrapper on runtime's storage. So we may consider to move this module to core or off-tree.

**Comment by gavofyork** [comment]
Unless there's a way to refactor things to avoid a dependency from the `storage_items` macro into SRML, then no. It might *possibly* be rearchitected into some non-core substrate runtime help crate that could perhaps depend only on `sr-io` (which is core), I guess.

**Comment by shawntabrizi** [comment]
stale
