### ISSUE TITLE
> > Add new Treasurenet blockchain network

### ISSUE THREAD

**Issue by sennhann29** [paritytech/substrate#14681]
> > Add new Treasurenet blockchain network
> 
> Hello, I will be happy if we can cooperate and help each other
> 
> _data/chains/eip155-5005.json
> 
> _data/chains/eip155-5002.json
> 
> _data/icons/treasurenet.json
> 
> For example, these are the new wrong codes and projects in our area

oh 
I'm sorry if I submitted incorrectly
My English is not very good,
I can't understand the problem of these three files, how should I improve them?

_Originally posted by @chriszhao1988 in https://github.com/ethereum-lists/chains/pull/3191#issuecomment-1641474123_

**Comment by liamaharon** [comment]
Please open a new issue detailing how your problem is specific to substrate
