### ISSUE TITLE
Feature: Add remark_call extrinsic to pallet-utilities

### ISSUE THREAD

**Issue by lemunozm** [paritytech/substrate#14727]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

We are in a situation where we want to tie some calls to some specific value/hash. There is a `pallet-remark`, but this only allows storing marks, without any relation to a call. 

Using a batch, we could get that association. Supposing we want to tie `ExtrinsicA` to `MarkA`, we could do something like `batch(ExtrinsicA, pallet_remark::store(MarkA))`. Nevertheless, a possible indexer (i.e. Subscan) would need to inspect all extrinsic nested in batches in order to get the associations between the mark and the calls. We would want a fast solution to identify such relations.

### Request

We need a more powerful extrinsic that allows us to remark a call. Something like:
```rust
fn remark_call(origin, call: RuntimeCall, remark: Remark) {
    call.dispatch()
    dispatch_event(remark)
}
```

This call should not be nested by batches to avoid an indexer going through all calls of a batch. An indexer would only need to identify those `remark_call` extrinsic at the top level.

### Solution

We think we can add that `remark_call` to `pallet-utilities`, ensuring the batching method does not contain such extrinsic.

### Are you willing to help with this request?

Yes!

**Comment by ggwpez** [comment]
> Nevertheless, a possible indexer (i.e. Subscan) would need to inspect all extrinsic nested in batches in order to get the associations between the mark and the calls. We would want a fast solution to identify such relations.

What is the problem of this? You only need to inspect the batches that emitted a `remark(Mark*)` event and can ignore the other ones. It wont get faster than this (maybe write it in Rust 😆).

>This call should not be nested by batches to avoid an indexer going through all calls of a batch. An indexer would only need to identify those remark_call extrinsic at the top level.

I dont think it makes sense to change the runtime to optimize for such nieche off-chain use-cases. You could already look only at top-level remarks.

**Comment by lemunozm** [comment]
Make sense, probably too niche a use case. Thanks for the suggestions
