### ISSUE TITLE
the pruning mode "ArchiveCanonical" not enable?

### ISSUE THREAD

**Issue by AtenJin** [paritytech/substrate#1474]
the `config.pruning` has the enum `PruningMode`
the `PruningMode` has three mode:
```rust
/// Pruning mode.
#[derive(Debug, Clone)]
pub enum PruningMode {
	/// Maintain a pruning window.
	Constrained(Constraints),
	/// No pruning. Canonicalization is a no-op.
	ArchiveAll,
	/// Canonicalization discards non-canonical nodes. All the canonical nodes are kept in the DB.
	ArchiveCanonical,
}
```
but I only find the config.pruning could be `ArchiveAll` in
```rust
	config.pruning = match matches.value_of("pruning") {
		Some("archive") => PruningMode::ArchiveAll,
		None => PruningMode::default(),
		Some(s) => PruningMode::keep_blocks(s.parse()
			.map_err(|_| create_input_err("Invalid pruning mode specified"))?),
	};
```
and `Constrained` in default value
```rust
impl Default for PruningMode {
	fn default() -> Self {
		PruningMode::keep_blocks(256)
	}
}
```
but can't find the `ArchiveCanonical`
![image](https://user-images.githubusercontent.com/5023721/51363497-40fa8800-1b13-11e9-8c63-75a39bb32126.png)

this is important for revert block, due to `ArchiveAll` do nothing in revert:
```rust
	pub fn revert_one(&mut self) -> Option<CommitSet<Key>> {
		match self.mode {
			PruningMode::ArchiveAll => {
				Some(CommitSet::default())
			},
			PruningMode::ArchiveCanonical | PruningMode::Constrained(_) => {
				self.non_canonical.revert_one()
			},
		}
	}
```
and `Constrained` would not revert when the blocks have been pruned.
So we need a `ArchiveCanonical` mode to provide the sync node.

Is the `ArchiveCanonical` not enable now?

**Comment by arkpar** [comment]
`ArchiveCanonical` would only archive finalized chain. This mode is not enabled in CLI indeed, as it is not clear yet if end users would need it.
