### ISSUE TITLE
Bug Substrate tutorial --rpc-port <X>

### ISSUE THREAD

**Issue by Tidus91** [paritytech/substrate#14741]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Bug for the parameter --rpc-port <X>
at the first time that we are invited to do it here :

![bugTutoSubstrate](https://github.com/paritytech/substrate/assets/65631603/7dbebab7-de68-4ed9-9828-a06725fa04aa)

i have this error message after trying this : 

![bugSubstrate2](https://github.com/paritytech/substrate/assets/65631603/658e6eaf-dc7a-4695-81dd-cb89a20c9f74)

So we need to use this parameter 2 times but we have an error message by doing so.

And i guess that this bug is blocking us for the rest of the tutorial right ?

### Steps to reproduce

Just doing this tutorial part

**Comment by Tidus91** [comment]
I think there is also a bug at the following of the tutorial with the command --SURI <X> , it's not taking a string

**Comment by Tidus91** [comment]
Also an other bug here : 
![bugSubstrate3](https://github.com/paritytech/substrate/assets/65631603/f549a29b-08a1-484b-b55d-f510babafa9f)

got this error message : `error[E0220]: associated type `BlockNumber` not found for `T``

**Comment by danisvice** [comment]
Run the command without command --rpc-port 9945, & the same with bob/second node, leave out --rpc-port 9946 and it should start to work.

**Comment by liamaharon** [comment]
Thanks @Tidus91 for bringing this up!

The substrate.io docs are open source. I've added a mentor label to this issue, it would be great if someone was to open a PR to fix it :)

https://github.com/substrate-developer-hub/substrate-docs/blob/main/content/md/en/docs/tutorials/build-a-blockchain/simulate-network.md

**Comment by Tidus91** [comment]
> Also an other bug here : ![bugSubstrate3](https://user-images.githubusercontent.com/65631603/259997306-f549a29b-08a1-484b-b55d-f510babafa9f.png)
> 
> got this error message : `error[E0220]: associated type `BlockNumber`not found for`T``


By any chances, do you have a fix for this bug ?
because it is blocking the following of the tutorial

**Comment by ggwpez** [comment]
You can replace `<T as Config>::BlockNumber` with `frame_system::pallet_prelude::BlockNumberFor<T>`. It was changed here https://github.com/paritytech/substrate/pull/14437
