### ISSUE TITLE
error: could not compile `sp-runtime` (lib) Cargo build error

### ISSUE THREAD

**Issue by istommao** [paritytech/substrate#14764]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

<img width="1637" alt="image" src="https://github.com/paritytech/substrate/assets/5070879/8723c88c-3b03-4e3b-82ca-05ecd7daba83">

**Comment by ggwpez** [comment]
>Steps to reproduce
No response

?  

Looks like a compiler panic to me, not a Substrate problem.

**Comment by istommao** [comment]
> > Steps to reproduce
> > No response
> 
> ?
> 
> Looks like a compiler panic to me - not a Substrate problem.

It's a rust issue?
