### ISSUE TITLE
error[E0583]: file not found for module `sys`

### ISSUE THREAD

**Issue by istommao** [paritytech/substrate#14770]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

error[E0583]: file not found for module `sys`
<img width="1549" alt="image" src="https://github.com/paritytech/substrate/assets/5070879/9750415e-224f-4354-adab-9a7b69498662">

**Comment by bkchr** [comment]
Try to delete your folder `~/.cargo/registry`. 

This isn't any Substrate issue, more a general Rust/Cargo issue.

**Comment by istommao** [comment]
The following warnings were emitted during compilation:

  warning: src/helpers.c:1:10: fatal error: 'setjmp.h' file not found
  warning: #include <setjmp.h>
  warning:          ^~~~~~~~~~
  warning: 1 error generated.

  error: failed to run custom build command for `wasmtime-runtime v8.0.1`

  Caused by:
    process didn't exit successfully: `/home/mao/WorkSpace/Substrate-HotStuff/target/debug/wbuild/node-template-runtime/target/release/build/wasmtime-runtime-b6ea060f875367a3/build-script-build` (exit status: 1)
    --- stdout
    cargo:rerun-if-changed=src/helpers.c
    TARGET = Some("wasm32-unknown-unknown")
    OPT_LEVEL = Some("3")
    HOST = Some("x86_64-unknown-linux-gnu")
    cargo:rerun-if-env-changed=CC_wasm32-unknown-unknown
    CC_wasm32-unknown-unknown = None
    cargo:rerun-if-env-changed=CC_wasm32_unknown_unknown
    CC_wasm32_unknown_unknown = None
    cargo:rerun-if-env-changed=TARGET_CC
    TARGET_CC = None
    cargo:rerun-if-env-changed=CC
    CC = None
    cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
    CRATE_CC_NO_DEFAULTS = None
    DEBUG = Some("false")
    cargo:rerun-if-env-changed=CFLAGS_wasm32-unknown-unknown
    CFLAGS_wasm32-unknown-unknown = None
    cargo:rerun-if-env-changed=CFLAGS_wasm32_unknown_unknown
    CFLAGS_wasm32_unknown_unknown = None
    cargo:rerun-if-env-changed=TARGET_CFLAGS
    TARGET_CFLAGS = None
    cargo:rerun-if-env-changed=CFLAGS
    CFLAGS = None
    running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-DCFG_TARGET_OS_unknown" "-DCFG_TARGET_ARCH_wasm32" "-o" "/home/mao/WorkSpace/Substrate-HotStuff/target/debug/wbuild/node-template-runtime/target/wasm32-unknown-unknown/release/build/wasmtime-runtime-d047019335ae77d2/out/src/helpers.o" "-c" "src/helpers.c"
    cargo:warning=src/helpers.c:1:10: fatal error: 'setjmp.h' file not found

    cargo:warning=#include <setjmp.h>

    cargo:warning=         ^~~~~~~~~~

    cargo:warning=1 error generated.

    exit status: 1

    --- stderr


    error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-DCFG_TARGET_OS_unknown" "-DCFG_TARGET_ARCH_wasm32" "-o" "/home/mao/WorkSpace/Substrate-HotStuff/target/debug/wbuild/node-template-runtime/target/wasm32-unknown-unknown/release/build/wasmtime-runtime-d047019335ae77d2/out/src/helpers.o" "-c" "src/helpers.c" with args "clang" did not execute successfully (status code exit status: 1).


  warning: build failed, waiting for other jobs to finish...
  error[E0583]: file not found for module `sys`
    --> /home/mao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/errno-0.3.2/src/lib.rs:26:1
     |
  26 | mod sys;
     | ^^^^^^^^
     |
     = help: to create the module `sys`, create file "/home/mao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/errno-0.3.2/src/sys.rs" or "/home/mao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/errno-0.3.2/src/sys/mod.rs"

  error[E0425]: cannot find function `with_description` in module `sys`
    --> /home/mao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/errno-0.3.2/src/lib.rs:47:14
     |
  47 |         sys::with_description(*self, |desc| {
     |              ^^^^^^^^^^^^^^^^ not found in `sys`

  error[E0425]: cannot find function `with_description` in module `sys`
    --> /home/mao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/errno-0.3.2/src/lib.rs:58:14
     |
  58 |         sys::with_description(*self, |desc| match desc {
     |              ^^^^^^^^^^^^^^^^ not found in `sys`

  error[E0425]: cannot find value `STRERROR_NAME` in module `sys`
    --> /home/mao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/errno-0.3.2/src/lib.rs:64:22
     |
  64 |                 sys::STRERROR_NAME,
     |                      ^^^^^^^^^^^^^ not found in `sys`

  error[E0425]: cannot find function `errno` in module `sys`
    --> /home/mao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/errno-0.3.2/src/lib.rs:95:10
     |
  95 |     sys::errno()
     |          ^^^^^ not found in `sys`

  error[E0425]: cannot find function `set_errno` in module `sys`
     --> /home/mao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/errno-0.3.2/src/lib.rs:100:10
      |
  100 |     sys::set_errno(err)
      |          ^^^^^^^^^ not found in `sys`

  Some errors have detailed explanations: E0425, E0583.
  For more information about an error, try `rustc --explain E0425`.
  error: could not compile `errno` (lib) due to 6 previous errors

**Comment by istommao** [comment]
<img width="2798" alt="image" src="https://github.com/paritytech/substrate/assets/5070879/191ecc95-2057-42fa-b709-004ca68aac3d">

**Comment by bkchr** [comment]
As you see it is wasmtime-runtime that fails to compile.
