### ISSUE TITLE
Contracts migration v9 to v10 is failling

### ISSUE THREAD

**Issue by SailorSnoW** [paritytech/substrate#14791]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

We are trying to upgrade our chain from polkadot-v0.9.43 to polkadot-v1.0.0 and can't manage to pass the migrations for the contracts pallet.

The chain is working fine on the runtime using polkadot-v0.9.43 and use the v9 pallet contract storage.
We actually have only 3 contracts on-chain.

When doing a try-runtime against our living chain with the new runtime and the v10, v11, v12 migrations effective in the pallet_contracts Config trait, here what is failing on the v10 migration:

`ERROR main runtime: panicked at 'called `Result::unwrap()` on an `Err` value: Other("deposit mismatch")', /Users/snow/.cargo/git/checkouts/substrate-7e08433d4c370a21/948fbd2/frame/contracts/src/migration.rs:296:35 `

Seems like the migration is failing cause something happen during the deposit changes.
Here is the full logs with some debug datas that I have added about the what's going on with the deposits:
[logs.txt](https://github.com/paritytech/substrate/files/12384633/logs.txt)

(some deposits value are really big and abnormal, the unreserve part seems not working and the new contract have 0 as deposits value)

### Steps to reproduce

- clone our [chain repo](https://github.com/Allfeat/Allfeat/tree/tofix/migration)
- build the new runtime:
`cargo build --release --package symphonie-runtime --features try-runtime`
- start a local node of our live testnet chain:
`cargo run --release --features try-runtime -- --chain=symphonie --sync warp --tmp`
- execute the try-runtime on_chain_upgrade:
`RUST_LOG=executor=trace,runtime=trace cargo run --release --features try-runtime -- try-runtime --runtime ./target/release/wbuild/symphonie-runtime/symphonie_runtime.compact.compressed.wasm on-runtime-upgrade --checks live --uri ws://localhost:9944`

**Comment by ggwpez** [comment]
cc @pgherveou

**Comment by pgherveou** [comment]
Looking into it

**Comment by pgherveou** [comment]
@SailorSnoW was 0.9.43 the first version of the pallet or did you go through other migrations before?

**Comment by SailorSnoW** [comment]
Perfect that worked great, thanks :)
I wasn't aware of NoopMigration doing a dummy migration by just upgrading the pallet version so yeah that was what I needed.
