### ISSUE TITLE
Grandpa: Syncing up a chain that doesn't have grandpa from a node that does

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#1492]
Our testnet doesn't contain the GRANDPA runtime module, but locally we have integrated it. However, connecting to our testnet from scratch fails with the following error:
```
Error: Execution: Function: Module doesn't have export GrandpaApi_grandpa_authorities
```
Is it the case that the GRANDPA module is not backwards compatible given the configuration needed in a node? I'm confused why the node is even searching for grandpa authorities when the genesis runtime doesn't contain any links to such a module. The only other explanation is the required configuration needed for GRANDPA, which our new local node copy is looking for.

This leads me to a larger question, has substrate/Polkadot defined any documents for keeping new versions backwards compatible? Are there processes one can follow more closely or should we be resorting to using an older checkout of our node to connect to the testnet.

EDIT: Realising this, there is no way forward except spinning up a new testnet. It seems worthwhile however to make future options more backwards compatible so one not be limited in such a way.

**Comment by rphmeier** [comment]
This amounts to a change of consensus algorithm, which would be possible after #1304.
