### ISSUE TITLE
Support multiple pending authority set changes

### ISSUE THREAD

**Issue by andresilva** [paritytech/substrate#1497]
Currently `GrandpaBlockImport` only supports importing one pending authority set change, it will error when importing a second block that signals an authority set change if any previous one has not been finalized yet. This can be problematic if finality is temporarily stalled, as authorities will keep producing blocks but will stall after a second authority change is signaled (e.g. at the end of the session). 

`GrandpaBlockImport` should allow multiple non-overlapping changes on the same branch. In order to do it safely all change blocks must be justified and the justifications must be imported in-order (so that authority set changes are enacted accordingly).

**Comment by gterzian** [comment]
I'm interesting in looking into this one...

**Comment by andresilva** [comment]
Sorry I didn't notice you self-assigned. I've already implemented this (at least from the sync side) since we decided on a short-notice that we need this for the alexander testnet. It's dependent on #1619 (or should work in tandem with).

**Comment by gterzian** [comment]
@andresilva No problem, I'll take a look at how you've done it in https://github.com/paritytech/substrate/issues/1497 then :)
