### ISSUE TITLE
Document staking mechanism in substrate

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#1498]
The current staking mechanism spreads across multiple modules in the substrate.

- Seating
- Council 
- Staking

has dependencies for staking.

It will be nice to  have an overview of this

**Comment by gavofyork** [comment]
Fwiw, the only module that is used for staking is, as might be expected, `staking`. The others cover governance.

**Comment by Kalanamith** [comment]
@gavofyork Thanks, I sense there might be a weak dependency for Staking via the council ->  seats.rs  
```rust
fn present_winner
```
method. Please correct if wrong.

**Comment by gavofyork** [comment]
Will do this at same time as https://github.com/paritytech/substrate/issues/1709
