### ISSUE TITLE
srml-support macros doesn't seem to work with 2018 edition

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#1509]
When I try to omit explicit extern crate for `parity-codec` I get this error message coming from `decl_event`.

```
error[E0463]: can't find crate for `_parity_codec`
   --> srml/contract/src/lib.rs:263:1
    |
263 | / decl_event! {
264 | |     pub enum Event<T>
265 | |     where
266 | |         <T as balances::Trait>::Balance,
...   |
281 | |     }
282 | | }
    | |_^ can't find crate
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

when I omit the explicit extern crate for `srml_support` I get this error:

```
error[E0463]: can't find crate for `hidden_include`
   --> srml/contract/src/lib.rs:287:1
    |
287 | / decl_storage! {
288 | |     trait Store for Module<T: Trait> as Contract {
289 | |         /// The fee required to create a contract. At least as big as staking's ReclaimRebate.
290 | |         ContractFee get(contract_fee) config(): T::Balance = T::Balance::sa(21);
...   |
311 | |     }
312 | | }
    | |_^ can't find crate
```

There are some instances to fix:

https://github.com/paritytech/substrate/blob/03f1af279446d70b372ff1cb15641dbfb6b40ee5/srml/contract/src/lib.rs#L56

**Comment by thiolliere** [comment]
OK I got an idea on it:

The issue on hidden include is that we generate a module that import srml-support with "extern crate srml_support". But the 2018 way to rename crates while importing them is to write in Cargo.toml `runtime-support = { package = srml-support }`
Thus we can't do extern crate srml_support anymore.

But we need to access it in a way. A solution I imagine is to use the CARGO_MANIFEST_DIR and extract the rename from it at compile time so we can access with the right name. This seems doable.

**Comment by thiolliere** [comment]
This is now solved with https://github.com/paritytech/substrate/pull/1757
