### ISSUE TITLE
Estimate performance gains using compilation

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#1519]
We can use wasm2c to compile the runtime into C files, compile them into a library and use it form substrate. 

This should give us a good estimate what we can achieve by employing compilation for running the runtime. 

Extracted from https://github.com/paritytech/substrate/issues/1374

**Comment by pepyakin** [comment]
It is not yet known for sure, but I'd expect that integration with a single compiled file without any dependencies to be quickier than compiling a giant like v8. Also it has it's own quirks: it is too tied with JS and afaik requires host functions to be defined via JS routines. That also prevents us from using i64 in signatures so we need to find workaround.

Moreover, I'd expect behavior of a statically compiled file to be more similar to what we ultimately want, than the behvaior of v8 (e.g. v8 has at least two tiers of compilation).

All in all, I think `wasm2c` has a better potential for that kind of task.

**Comment by cmichi** [comment]
Closed because the investigation had happened in #1845.
