### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1525]
Node stuck at hight 128474
Grandpa authority set changes at 128475
Restart doesn't help. Wipe volume then restart sometimes can fix the issue, other time stuck again on a block before authority set changes.

node based on substrate: 9edfc2441116ef89b449de99522a27bb0c2051a5
runtime built ~2 weeks ago. I can pinpoint the exact version if needed

```
2019-01-23 04:08:32 ImportQueue DEBUG sync  Error importing block 128475: 0x926845638ab8f00b728708a93af05ff879d2b02e0dc74e4b3d025e5063e85b29: Error(ClientImport("Incorrect base hash"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

full log:
https://gist.github.com/xlc/fed0869364cef1ddec4bc56fe522f2fa

I think it is relates to grandpa finalization process that the justification somehow get lost on authority set changes. Then later when another authority set changes happen, it stops syncing because it can only handle one authority set changes at time.

**Comment by rphmeier** [comment]
Steps to reproduce and `afg=debug` logs would be helpful

**Comment by rphmeier** [comment]
Probably related to #1508

**Comment by xlc** [comment]
More logs with `afg` logger

https://gist.github.com/xlc/bf54dc55c9d02eaef771686bea8765bd

I don't have a good way to reproduce it from scratch, it is easy to reproduce with my internal testnet. For stuck node, restart won't help. For new node syncing up, there is a large chance (> 30%) that it stuck at some block.
I think the main thing is just make many authority changes (stack, unstake, stake and don't validate so it get unstaked by network) and eventually syncing nodes will have this issue.

**Comment by gavofyork** [comment]
Should be sorted now.
