### ISSUE TITLE
Sync imports same blocks repeatedly

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1540]
This is a violation of the interface of the sync service and generally indicates that something is going wrong. Sanity checks in other components make this non-critical but generally should be addressed as it is a waste of bandwidth.

**Comment by rphmeier** [comment]
(footprint label seems relevant; it's often downloading the same block hundreds of times -- that's a big waste of network bandwidth)

**Comment by gterzian** [comment]
I will take a look...

**Comment by gterzian** [comment]
@rphmeier Do you mean that sync sends a `GenericMessage::BlockRequest` for blocks it has already seen, or that is handles redundant incoming `BlockResponse`(or something else)?

**Comment by rphmeier** [comment]
@gterzian I'm not very familiar with the sync internals; All I know is that the GRANDPA block import worker often has the same blocks fed to it (often 10+ times in succession). The sync service should neither:
  - download the same block more than once (wasted effort)
  - feed the block to the import worker more than once

and I'm not sure which of these is happening here.

**Comment by gavofyork** [comment]
is this fixed yet @rphmeier @arkpar ?

**Comment by arkpar** [comment]
It should not be happening anymore, but it would be nice to verify that and add some additional checks  of block status before handing blocks to GRANDPA verification.

**Comment by gavofyork** [comment]
ok - maybe one for the chaos testnet then. @gterzian @rphmeier
