### ISSUE TITLE
Protocol/Network: move peer request timeout logic out of protocol

### ISSUE THREAD

**Issue by gterzian** [paritytech/substrate#1541]
Part of https://github.com/paritytech/substrate/issues/1517

Currently, there are two distinct peer timeout workflows 

When sending a block request to a peer:

1. When a message is sent to a Peer, the sending is [timestamped](https://github.com/paritytech/substrate/blob/f60815887667b38ff512f6f6294163c134e698f6/core/network/src/protocol.rs#L816).
2. When the blockresponse comes in, the timestamp is [set to `None`](https://github.com/paritytech/substrate/blob/f60815887667b38ff512f6f6294163c134e698f6/core/network/src/protocol.rs#L276).

When handshaking with a peer:

1. When the peers first connects, this is [timestamped](https://github.com/paritytech/substrate/blob/f60815887667b38ff512f6f6294163c134e698f6/core/network/src/protocol.rs#L328).
2. When the status message has been received, the peer is [removed from "handshaking peer"](https://github.com/paritytech/substrate/blob/f60815887667b38ff512f6f6294163c134e698f6/core/network/src/protocol.rs#L560), added to "peers". 
3. When a peers disconnects while handshaking, it is also r[emoved from "handshaking peers"](https://github.com/paritytech/substrate/blob/f60815887667b38ff512f6f6294163c134e698f6/core/network/src/protocol.rs#L343). 

Periodically, as part of [`tick`](https://github.com/paritytech/substrate/blob/f60815887667b38ff512f6f6294163c134e698f6/core/network/src/protocol.rs#L476), protocol will 

1, check the timestamp for each peer, if it is `Some(..)`, and [report a peer if a timeout has been reached](https://github.com/paritytech/substrate/blob/f60815887667b38ff512f6f6294163c134e698f6/core/network/src/protocol.rs#L490). 
2. Check the timestamp for each handshaking peers, and report it if it is above the timeout. 

This logic could be moved to the libp2p2 [`ServiceTask`](https://github.com/paritytech/substrate/blob/f60815887667b38ff512f6f6294163c134e698f6/core/network-libp2p/src/service_task.rs), which could keep track of handshaking peers as well as any block request/response cycle, and when reporting a peer for timeout, produce a [`ServiceEvent`](https://github.com/paritytech/substrate/blob/f60815887667b38ff512f6f6294163c134e698f6/core/network-libp2p/src/service_task.rs#L140) that protocol can handle to update it's internal state. 

How does that sound @tomaka ?

**Comment by tomaka** [comment]
That is the plan already with #1517

**Comment by gavofyork** [comment]
@tomaka I'm closing this; please reopen and place in appropriate milestone if needed.
