### ISSUE TITLE
Replace `error-chain`

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#1547]
With the latest nightlies, rust spits out a warning about using a deprecated method of the `Error` trait. See [here](https://github.com/rust-lang-nursery/error-chain/issues/254) for more information. 
As `error-chain` is in maintenance mode and its unlikely that there will be any real new stuff, we should watch out for what is the new way of error reporting in rust. (Failure probably already failed).

**Comment by tomaka** [comment]
> we should watch out for what is the new way of error reporting in rust.

Implementing the `Error` trait manually on an enum has always worked and has no risk of suffering from maintenance mode.
