### ISSUE TITLE
Staking reward could potentially overflow

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1572]
Look here:

https://github.com/paritytech/substrate/blob/bbe18168174cadaab8c693dd1f0812a883d150e4/srml/staking/src/lib.rs#L356-L359

https://github.com/paritytech/substrate/blob/bbe18168174cadaab8c693dd1f0812a883d150e4/srml/staking/src/lib.rs#L378-L380

**Comment by jaybutera** [comment]
This is tough because a fully defined solution includes casting to a u128 like 
```
let safe_mul_rational = |b| match b.check_mul(rem) {
    Some(x) => x / total,
    None => (b as u128 * rem as u128 / total as u128) as u64
};
```
but web assembly does not support u128, so there must be some form of undefined behavior. I think it's not ideal for the function to fail if the overflow occurs because that just means nominators with extraordinary funds can't get slashed. 

A good compromise might be to come as close to the real solution as is possible to compute without an embedded u128 library.
```
let safe_mul_rational = |b| match b.check_mul(rem) {
    Some(x) => x / total,
    None => (b as u128 / total as u128) as u64
};
```

**Comment by DemiMarie-parity** [comment]
@jaybutera We can emulate `u128` ourselves.  I am surprised that Rust does not do this when targeting wasm.

**Comment by pepyakin** [comment]
To my knowledge Rust supports u128 when targeting wasm, although a bit inefficient. @jaybutera can you expand on what exactly undefined behavior you are referring to? Is there any examples or particular points?

**Comment by DemiMarie-parity** [comment]
@jaybutera There is no need for undefined behavior:

* This is safe Rust.  Undefined behavior in safe rust is a compiler and/or library bug, by definition.
* This code is probably not performance critical, so we can use `u128`.  If performance is an issue, we can use a manual emulation.

**Comment by shaopengw** [comment]
`u128` seems still not big enough, I recently run into this overflow problem with 1 token balance as `10^18` units. In fact, as long as one balance value multiplies another, it tends to overflow because:
```
u128::max_value() / (10u128.pow(18) * 10u128.pow(18)) == 340
```

**Comment by xlc** [comment]
This is bricking our testnet. Any plan to fix this?

**Comment by thiolliere** [comment]
using some euclidian division we can guarantee no overflow for `exposure.total * exposure.others[n].value < N::maxvalue`

**Comment by thiolliere** [comment]
another solution is to reduce the precision of the fraction exposure.other[n].value/exposure.total when the multiplication exposure.total * exposure.others[n].value overflow

something like this: with fraction decreasing when precision is lost:
```rust
fn main()  {
	let mut b: u32 = 0xa000_0000;
	let mut c: u32 = 0xffff_ffff;

	while c.checked_mul(b).is_none() {
		b /= 2;
		let round_up = c % 2 == 1;
		c /= 2;
		if round_up {
			c += 1;
		}
	}
}
```

**Comment by thiolliere** [comment]
We should be able to provide some approximation but I havn't found proper solution yet.

Two other solution would be:
* compute validator ratio using a conversion to u64 similar to phragmen
* add an associated type in the trait which is DoubleSizeBalance.

**Comment by thiolliere** [comment]
this is fixed by PR now
