### ISSUE TITLE
Add `no_std` support to trie

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1574]
Our substrate modified Merkle Patricia tree should work in `no_std` as well

https://github.com/paritytech/substrate/blob/bbe18168174cadaab8c693dd1f0812a883d150e4/core/trie/src/lib.rs#L17-L22

**Comment by cheme** [comment]
this seems to be fine with 'alloc' feature, https://github.com/debris/elastic-array/pull/8 is required then will need trie update on https://github.com/cheme/trie/tree/no_std (I am waiting for crate version update which may not be super smooth) and at last the actual substrate trie crate update.
