### ISSUE TITLE
Harden and improve `Permil` and `Perbill`

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#1577]
We should have support for `impl Mul<Permill> for N where N: As<usize>` and really need to make sure, Permil and Perbill don't overflow....

https://github.com/paritytech/substrate/blob/bbe18168174cadaab8c693dd1f0812a883d150e4/core/sr-primitives/src/lib.rs#L129-L133

https://github.com/paritytech/substrate/blob/bbe18168174cadaab8c693dd1f0812a883d150e4/core/sr-primitives/src/lib.rs#L183-L187

**Comment by thiolliere** [comment]
Do we want to return a Result ? probably not

making sure don't overflow can be done with b.saturating_mut(self) / 1000...

**Comment by thiolliere** [comment]
I'm not used to parity codes yet, and whom have to close the issue.
Also we can note that saturating seem to be improvable as we can divide first if it would overflow.
