### ISSUE TITLE
Error when install: fills up /tmp directory on linux ubuntu

### ISSUE THREAD

**Issue by rfikki** [paritytech/substrate#1588]
Compiling rocksdb v0.11.0
   Compiling kvdb-rocksdb v0.1.4 (https://github.com/paritytech/parity-common?rev=b0317f649ab2c665b7987b8475878fc4d2e1f81d#b0317f64)
   Compiling substrate-client-db v0.1.0 (https://github.com/paritytech/substrate#b5bdacd4)
   Compiling srml-council v0.1.0 (https://github.com/paritytech/substrate#b5bdacd4)
   Compiling substrate-service v0.3.0 (https://github.com/paritytech/substrate#b5bdacd4)
   Compiling srml-aura v0.1.0 (https://github.com/paritytech/substrate#b5bdacd4)
   Compiling substrate-cli v0.3.0 (https://github.com/paritytech/substrate#b5bdacd4)
   Compiling substrate-finality-grandpa v0.1.0 (https://github.com/paritytech/substrate#b5bdacd4)
   Compiling substrate-consensus-aura v0.1.0 (https://github.com/paritytech/substrate#b5bdacd4)
   Compiling node-cli v0.1.0 (https://github.com/paritytech/substrate#b5bdacd4)
   Compiling node-runtime v0.1.0 (https://github.com/paritytech/substrate#b5bdacd4)
   Compiling node-executor v0.1.0 (https://github.com/paritytech/substrate#b5bdacd4)
LLVM ERROR: IO failure on output stream: No space left on device
error: failed to compile `substrate v0.10.0 (https://github.com/paritytech/substrate#b5bdacd4)`, intermediate artifacts can be found at `/tmp/cargo-install78VEZr`

Caused by:
  Could not compile `node-cli`.

To learn more, run the command again with --verbose.
mktemp: failed to create directory via template ‘/tmp/tmp.XXXXXXXXXX’: No space left on device
fatal: could not create work tree dir 'substrate-up': No space left on device
cp: cannot stat '/substrate-*': No such file or directory
Run source ~/.cargo/env now to update environment

**Comment by rphmeier** [comment]
How much space is available on the drive in the beginning?
Do you have a proposed fix? This is `cargo` using a lot of space for intermediate artifacts, apparently more than you have available on the drive. I am not sure what you expect us to do.

**Comment by rfikki** [comment]
Filesystem          1K-blocks      Used Available Use% Mounted on
udev                 16448036         0  16448036   0% /dev
tmpfs                 3293592    345772   2947820  11% /run
/dev/mapper/vg-root 443636896 298071104 123007280  71% /
tmpfs                16467956         0  16467956   0% /dev/shm
tmpfs                    5120         0      5120   0% /run/lock
tmpfs                16467956         0  16467956   0% /sys/fs/cgroup
/dev/sda5              983704    155188    778548  17% /boot
/dev/mapper/vg-tmp     967320      1244    899724   1% /tmp
tmpfs                 3293592         0   3293592   0% /run/user/1001

**Comment by rfikki** [comment]
I have no problem running any other software on this server. No problem if there is nothing you want to do about it. Just wanted you all to know about this, others might run into the same issue.

**Comment by bkchr** [comment]
Just clone the repository and build it from this folder. So, your tmp is not used.
