### ISSUE TITLE
Delegation voting

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1592]
Currently the democracy module requires all accounts to issue their own votes for all elections. It would (arguably) be helpful if accounts could "subscribe" to other accounts in order to pass control over their voting capacity to them.

Introduce storage:
- `Delegations: map AccountId => (AccountId, Period)`: Any delegations to a given account from some delegating account together with the maximum period multiplier that the delegator may command.
- `DelegatorCount: map AccountId => u32`: The number of accounts delegating to a given account.
- `SubscriptionVotes: map (AccountId, RefIndex) => VoteCount`: Any additional votes for an account in a referendum leant by delegators.

Introduce functions:
- `delegate(origin, who: AccountId, maximum_periods: Period)`
- `undelegate(origin)`
- `assertVotes(origin, VoteCount)`
- `challengeVotes(origin, VoteCount)`

Specific functionality to follow.

**Comment by drewstone** [comment]
Will you require the dispute mechanism we discussed? I guess with such a mechanism you don't need to maintain backlinks to tally, defaulting to rebuilding the tree off-chain. Would be interesting see where we can lend assistance and generalise for different implementations (ones with max delegation depth, finer-grained delegation, etc).

@jnaviask

**Comment by drewstone** [comment]
For tallying delegations, you need to also store backlinks from accounts that are delegated to
`DelegationBacklinks: map T::AccountId => Vec<T::AccountId>`

**Comment by marcio-diaz** [comment]
What is the meaning of  `assertVotes` and `challengeVotes`?

**Comment by gavofyork** [comment]
In this imagining (not necessarily what get implemented), `assertVotes` would allow a transactor to attest to final tally. `challengeVotes` would allow another transactor to dispute that.

In reality, the initial implementation of this will be simpler and just use validator "opinions". We can introduce a council fallback for challenging this.
