### ISSUE TITLE
Many warnings about static variable `__CacheGetByteStructXXX` should have an upper case name.

### ISSUE THREAD

**Issue by koushiro** [paritytech/substrate#1594]
https://github.com/paritytech/substrate/blob/01bff36cbb7a800720c8d867b63736ba233d22f3/srml/support/procedural/src/storage/transformation.rs#L659

https://github.com/paritytech/substrate/blob/01bff36cbb7a800720c8d867b63736ba233d22f3/srml/support/procedural/src/storage/transformation.rs#L677

Solution:

```rust
let cache_name = proc_macro2::Ident::new(&("__CACHE_GET_BYTE_STRUCT_".to_string() + &str_name.to_uppercase()), name.span()); 
```

**Comment by bkchr** [comment]
Will be fixed by: https://github.com/paritytech/substrate/pull/1428
