### ISSUE TITLE
Suggestion: Module level mocks created for tests should not be shared between crates 

### ISSUE THREAD

**Issue by Kalanamith** [paritytech/substrate#1631]
## Observation
Observed that certain mocks created for test purposes shared between tests in other  crates.
As for as example any changes made to mocks.rs file in balance module should not break any tests in staking module. 
 
### When it comes to tests (especially unit tests) 

- There should be global mocks which can be shared through out the project and the behaviour of those mocks are independent from each crates and global to all the crates.
- There should be Module level which scopes only to that crate.

### Outcome
This will ensure that we have a clean test implementation and it is easy to maintain the project in the long run .
Its a good practice to make unit tests independent (real unit tests)

_Influenced by PyTest framework_

**Comment by gavofyork** [comment]
"global" anything in a language so deeply modular as Rust is dumb :-P

That might for a monolithic project without pure-plugin-style inter-crate dependencies, but I think it's not such a good fit for SRML where individual crates have a peer relationship with dependencies. For example, there is shared logic for mocking between balances and all SRML crates that are dependent on balances. However other SRML crates know nothing of balances - they don't even link to balances. Therefore following modular principles, this logic cannot be present in crates which do not depend on balances as it would be were it lumped into a globally available, monolithic mockup. It therefore follows that you either mirror the dependency graph of the SRML modules with SRML test mockups or you duplicate logic everywhere.

We currently do the former, which I believe is a better approach to the copy'n'paste of the latter.
