### ISSUE TITLE
Cannot update the storage in tests

### ISSUE THREAD

**Issue by siman** [paritytech/substrate#1638]
I update a value in storage in tests, and then when I read it, the entry in storage is not changed.

```rust
let code: Vec<u8> = vec![1, 2, 3];
println!("> Storage before:\n{:?}", storage::unhashed::get_raw(well_known_keys::CODE));
println!("wasm code: {:?}", code);
storage::unhashed::put_raw(well_known_keys::CODE, &code);
println!("< Storage after:\n{:?}", storage::unhashed::get_raw(well_known_keys::CODE));
```

A full code to reproduce this issue:
https://gist.github.com/siman/a86efbdc91aae04fe736abe0ba2595e9

**Comment by bkchr** [comment]
Hey @siman, after looking into the issue it is not a bug.
Looking [here](https://github.com/paritytech/substrate/blob/0b655477cf9d9ef10d4c42685d61e3714d0ca4cc/core/state-machine/src/testing.rs#L113) you see that for the key `CODE` there is a special treatment in tests. You can test by replacing the key with `codesiman` or something like that and your test will work :)

**Comment by siman** [comment]
@bkchr I think I need `CODE` key because I'm trying to test a logic that updates runtime code in storage. Then what is the best way to test that code runtime code has been updated based after some condition met?

**Comment by bkchr** [comment]
@siman I will prepare a pr to make it possible to alter the `CODE`. I will mention you in the pr.
