### ISSUE TITLE
Instructions from readme appear outdated

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#1643]
Trying to follow the instructions at https://github.com/paritytech/substrate#51-on-mac-and-ubuntu

The install and build seems perfectly normal, then I run `substrate --chain=staging build-spec > ~/chainspec.json` and get a bad usage message

```
error: Found argument 'build-spec' which wasn't expected, or isn't valid in this context

USAGE:
    substrate --chain <CHAIN_SPEC>

For more information try --help
```

**Comment by bkchr** [comment]
Please put --chain behind build-spec.

**Comment by JoshOrndorff** [comment]
Thanks. That did it. Here's a PR. My first one, so let me know if I missed anything from contributing doc. I wasn't able to create my own branch in the paritytech repo. https://github.com/paritytech/substrate/pull/1644
