### ISSUE TITLE
Allow different ways of limitting the transactions in a block

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#1651]
Currently we limit the size of all extrinsics in the block (see https://github.com/paritytech/substrate/pull/1581) and have the limit hardcoded in the runtime.

However interaction with other modules (namely `srml-contract`) may require some other mechanism of limitting the number of transactions. For instance contracts use up gas and we can have a block gas limit alike Ethereum.

Would be perfect if the `weight` of the transaction was also given to the pool to allow better (more optimal) allocation of extrinsics to block to maximise both: fee and utilisation

It's a follow up issue on #1354 (see comment https://github.com/paritytech/substrate/issues/1354#issuecomment-453928936)

**Comment by rphmeier** [comment]
When we're building blocks we also want to be informed of when this limit has been hit and how close we are to it. If the proposer can get back an `Error::BlockFull(remaining_weight)` and finish proposing / push more transactions with`sum(new_txs.weight) <= remaining_weight` that would work really well.

**Comment by tomusdrw** [comment]
I guess that's resolved with #3157
