### ISSUE TITLE
Don't prune blocks until finalisation is past them

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1652]

**Comment by rphmeier** [comment]
I'm not convinced this is tractable. In general we shouldn't prune before finality but in the case of large network partitions full nodes will either have a choice to use a huge amount of disk space or to be unable to revert. A memory-based pruning heuristic like parity-ethereum has is the way to go.

The exception is nodes running GRANDPA or block authorship. They should be keeping all unfinalized states.

**Comment by DemiMarie-parity** [comment]
@rphmeier how much disk space are we talking about?

**Comment by rphmeier** [comment]
Depends how long the partitions are...but take a look at how big a geth or parity archive node DB is. I think if we had finality stalled for a week we could easily accrue 10GB or more of drive space.

**Comment by gavofyork** [comment]
10 GB is fine for validators.

**Comment by abebeos** [comment]
Still relevant?
