### ISSUE TITLE
Weird "possible fork" & stalled sync

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1664]
Internet connection dropped for a minute but syncing seemed to be stalling before then. https://gist.github.com/gavofyork/47a7a14d484fcd055af914840f11c5f8

**Comment by arkpar** [comment]
Is this on a flakey or mobile network by any chance?

**Comment by gavofyork** [comment]
network did indeed go down for a period.

**Comment by gavofyork** [comment]
will leave it for now.
