### ISSUE TITLE
Charred Cherry doesn't sync with master

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1672]

**Comment by bkchr** [comment]
Isn't one reason, that we break the api? And the recent node does not work with the "old" wasm runtime?

**Comment by arkpar** [comment]
Indeed, the reason is breaking changes in `check_inherents` and probably other functions. 
```
 Useless("Verification failed: Error(CallResultDecode(\"BlockBuilder_check_inherents\"),
```
I'm not sure how this can be fixed in master, unless these breaking changes are reverted.

**Comment by gavofyork** [comment]
ok - i guess we could upgrade to the new API?

**Comment by gavofyork** [comment]
in any case, not a bug so closing.
