### ISSUE TITLE
Add `onInitialize` handler to be called immediately after runtime upgrade

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1686]
When perform a runtime upgrade, it will be useful to be able to perform some work immediately after the upgrade.
This `onInitialize` handler can be used to do initialization work for the new runtime. e.g. migrate storage from old format to new format

It could be wasm code / smart contract style attached to the setCode method.
Or have `onInitialize` part of the wasm runtime interface, this does means have to store this one time used code in storage alone with rest of the runtime.

It should also call some the native client code handler to notify the runtime change to allow native client code to perform some other work. e.g. Reset metadata cache

**Comment by gavofyork** [comment]
Should be manageable by a standard block `OnInitialise` and a boolean storage item to check for whether upgrade has happened. Anything more complex (e.g. to be able to determine whether an upgrade has happened) is quite complex and not as flexible.
