### ISSUE TITLE
Allow configurable Grandpa finality head size

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1735]
For early production networks we will want to reserve the ability to revert in case of catastrophic runtime failure, governance attack, ...

Since reverting a finalised block is problematic, and since there won't be all that much need of fast-finality in the early says, we should allow for a long (e.g. 1 days) unfinalised head.

Critical systems that rely on non-reversion (e.g. exchanges) would be advised to mirror their confirmation protocol to match the finality delay.

**Comment by xlc** [comment]
It will be very helpful if this allows us to revert a bricked chain (due to broken runtime upgrade), 2 unfinalised head should be enough because there won't be more blocks when head is bricked.

**Comment by rphmeier** [comment]
The downside here is that GRANDPA changes require finality to take effect. This means our GRANDPA validators will be lagging behind considerably.

**Comment by andresilva** [comment]
This can already be done by specifying custom GRANDPA voting rules. By default, we lag by 2 blocks from best (https://github.com/paritytech/substrate/blob/master/client/finality-grandpa/src/voting_rule.rs#L241). The voting rules are part of the GRANDPA config so any end-user of substrate already needs to define them when instantiating the service (https://github.com/paritytech/substrate/blob/master/bin/node/cli/src/service.rs#L230).

**Comment by andresilva** [comment]
Fixed in #3673.
