### ISSUE TITLE
`initialize_block` is called more than once for a consensus import

### ISSUE THREAD

**Issue by sorpaas** [paritytech/substrate#1762]
I haven't yet figured out all details about this issue, but just open it first to keep track. It looks like in some situations for block import, we can call `initialize_block` more than once.

Note that this usually won't be noticed and isn't a problem for most srml chains -- we set some values based on headers, but never append values to list or inc a counter.

**Comment by bkchr** [comment]
Hey, I'm not sure if that is somehow related, but [this](https://github.com/paritytech/substrate/blob/6288a4774a5ca57832896f6c501ba04aa6ef398c/core/client/src/call_executor.rs#L210) can lead to `initialise_block` being called 2 times. `initialised_block` would need to be set, if the given method is `initialise_block`. However, this could should not be called when importing a block..

**Comment by rphmeier** [comment]
@sorpaas you have checked that `initialise_block` is called twice on the imported block and not on an `ApiRef`?
