### ISSUE TITLE
Convert British English to US English before 1.0 release

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#1768]
Lots of functions and APIs within substrate use British English rather than US English. For example `on_finalise` vs `on_finalize`.

Should probably migrate to use US English since it is [pretty standard for programming](https://stackoverflow.com/questions/157807/gb-english-or-us-english), and we should conform.

**Comment by gavofyork** [comment]
how is this going @shawntabrizi ?

**Comment by shawntabrizi** [comment]
@joepetrowski wanted to take a first stab and I will do a second pass to make sure nothing gets missed.

I will also create an item on the docs side to do a full scrub.

**Comment by gavofyork** [comment]
Is this docs? The APIs are the important things here.

**Comment by shawntabrizi** [comment]
@gavofyork this issue is for the Substrate codebase.

The [other issue](https://github.com/paritytech/substrate-developer-hub/issues/62) is for the docs.

**Comment by arkpar** [comment]
https://www.npmjs.com/package/american-british-english-translator
Could be somewhat useful
