### ISSUE TITLE
Optimal Approved Assignment using Phragmén

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#1772]
Update staking module to allow nominators to approve any number of validators, and then they should be optimally assigned off-chain using Phragmén.

This will require off-chain compute, so until that is done, the algorithm should do the assignment on-chain.

Basic implementation of Phragmén is here: https://github.com/w3f/consensus/blob/master/NPoS/simplePhragm%C3%A9n.py

**Comment by Kianenigma** [comment]
To be implemented here #1782.
