### ISSUE TITLE
Test Network should support adding network specialization

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1787]
The `network/tests/mod.rs` contains a very useful mock network that routes messages between peers.

Networks in Substrate have "Specializations" that are used to account for protocol-specific messages. The `TestNetwork` in that module should be extended to support arbitrary network specialization, so that network tests for higher-level protocols (e.g. the Polkadot protocol) can use this infrastructure.

**Comment by rphmeier** [comment]
@gterzian this is done, isn't it?

**Comment by gterzian** [comment]
Yes, it is done
