### ISSUE TITLE
Handle to rocksdb doesn't seem to be dropped/released

### ISSUE THREAD

**Issue by gterzian** [paritytech/substrate#1792]
In this commit: https://github.com/paritytech/substrate/pull/1775/commits/4f71f77eea68a0f122f2d363fea855e47e1c2da7

I'm trying to stop a running `let _ = cli::run(args_clone, exit, version).unwrap();` using `exit`, and then start a new cli. On the restarting, I get the below error, originating from the call to `Database::open` at https://github.com/paritytech/substrate/blob/67a8539f18fc2ec2ff2d5ac34c65e6c0d03206e4/core/client/db/src/utils.rs#L196

```
`Err` value: Error(Msg("Error(Client(Backend(\"IO error: While lock file: /tmp/alice/chains/local_testnet/db/LOCK: No locks available\"))
```

So it appears the DB isn't closed, unless you actually shut down the entire process(since it obviously work if you do a ctrl-c and then re-start the node). 

Any ideas?

**Comment by bkchr** [comment]
Please always provide labels and a milestone for issues.
@andresilva do you maybe have an idea?

**Comment by DemiMarie-parity** [comment]
First question: do we leak any memory on Valgrind?

**Comment by bkchr** [comment]
What should a memory leak have to do with this problem? The handle is probably not dropped, because some futures still holds it. If you end the process, the handle will be dropped and there is no memory leak.

**Comment by gnunicorn** [comment]
closing as this is outdated.
