### ISSUE TITLE
system_peers not getting latest remote data

### ISSUE THREAD

**Issue by kenhuang** [paritytech/substrate#1805]
system_peers rpc method did not return the real-time remote node data, data seems to refresh after restart local node.

```
 curl -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "method":"system_peers", "params":[], "id": 1 }' http://localhost:9933/ | jq '.'
```

**Comment by gavofyork** [comment]
@jacogr can you confirm this?

**Comment by jacogr** [comment]
I am not seeing the same on https://polkadot.js.org/apps/#/explorer/node (via the RPC node)

It does update and the nodes drop there - the connections seem relatively unstable there, so each 10s refresh shows a different number which aligns with what is on telemetry

**Comment by xlc** [comment]
(the node info UI doesn’t work on mobile as I can’t scroll horizontally)

The real issue is the height of peers is not accurate compare to value displayed in telemetry

**Comment by nyetwurk** [comment]
`curl -sS -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "method":"system_peers", "params":[], "id": 1 }' http://localhost:9933/
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
`
