### ISSUE TITLE
Better error response from RPC for failed transaction

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1806]
Currently if a transaction failed, all I can get is from polkadot.js is `error.message [-32603]: Unknown error occured`
It should be possible to give a more detailed error message.

This RPC response, which does indicate the error code 3, which is `CantPay`, but it is hard to get it out of the data string.

```
{
    "code": -32603,
    "message": "Unknown error occured",
    "data": "Error(Pool(InvalidTransaction(3)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
}
```

https://github.com/paritytech/substrate/blob/6a4b58068421f280ff2dfe564220c58147c35f4a/core/sr-primitives/src/lib.rs#L331

However the data field needs to be more parseable and the correct error code should be returned (maybe in a subcode field?)

cc @jacogr

**Comment by thiolliere** [comment]
-32603 is the correct error isn't it ?

should we return this ?
```rust
{
    "code": 3,
    "message": "Runtime check for the transaction failed, invalid transaction",
    "data": "Error(Pool(InvalidTransaction(3)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })"
}
```

otherwise adding a subcode seems ok

**Comment by xlc** [comment]
I don't know the meaning of `-32603` (any docs?) but it maybe useful.
It will be good if data is a JSON instead string. e.g.
```
{
    "code": -32603,
    "message": "Unknown error occured",
    "data": {
      "kind": "Pool",
      "error": "InvalidTransaction",
      "error_code": 3
    }
}
```

**Comment by bkchr** [comment]
@tomusdrw didn't you improved this in some pr recently?

**Comment by thiolliere** [comment]
note it seems easy to implement: we have access to the full type of the error. see https://github.com/paritytech/substrate/blob/master/core/rpc/src/author/error.rs#L66

**Comment by tomusdrw** [comment]
@bkchr nope, as @thiolliere it's just the matter of matching more error types.
We can either introduce new top-level error codes (i.e. others than `-32603`; I'd do that for common errors) or we can return structured results in `data`.

**Comment by paul-freeman** [comment]
-32603 is JSON RPC Internal Error: https://www.jsonrpc.org/specification#error_object

**Comment by paul-freeman** [comment]
Any chance of getting this issue bumped up the priority queue? We have a pretty large downstream project that needs the `CantPay` error elevated into the `code` field somehow. The polkadot client currently strips the `data` field, so this error gets completely hidden as "Unknown error occured".
