### ISSUE TITLE
Authority's key is forcibly replaced with Account key

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1829]
https://github.com/paritytech/substrate/blob/18bbe130180989d92b0bcea7952cdf1e58b0d6f4/srml/session/src/lib.rs#L144

Every era, authority's key is forcibly replaced with Account key. 
Account authority key only in current era can use.

**Comment by gguoss** [comment]
7f580f6

**Comment by gguoss** [comment]
https://github.com/paritytech/substrate/issues/1829

**Comment by gavofyork** [comment]
This should not be the case. Do you have a test to demonstrate it?

`session`'s `on_finalize` calls `check_rotate_session`. This calls `rotate_session` which then calls `on_session_change`; this is the hook that `staking` uses to change the validator set which calls the code you posted above. However, immediately after this, `rotate_session` patches this set with the `NextKeyFor` items: https://github.com/paritytech/substrate/blob/18bbe130180989d92b0bcea7952cdf1e58b0d6f4/srml/session/src/lib.rs#L188-L192

**Comment by gguoss** [comment]
yes , you are right.
