### ISSUE TITLE
Runtime: Signature and sender should be Optional

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#184]
Currently they rely on `Default` trait to be implemented which is annoying. Rather they should be `Option<Signature>` and `Option<AccountId>`.

**Comment by rphmeier** [comment]
addressed in https://github.com/paritytech/polkadot/pull/169 using a wrapper type that imposes the `Default` bound.

**Comment by gavofyork** [comment]
Not actually addressed; this needs sorting properly so that signature and sender are either both `Option` or not. In either case, they should work with an arbitrary lookup scheme and, probably, arbitrary crypto for the signing.

**Comment by rphmeier** [comment]
Using `Option` is fine but we can get away without the runtime overhead if we use a trait-based system. There should definitely be no overhead in runtimes where there is no such thing as an optional signature.
