### ISSUE TITLE
Run a grandpa validator node without become an aura validator node

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1841]
Please forgive me if I misunderstand how the consensus works.

Aura is used for block production and a offline aura validator means increased average block time until it is removed from the validator list.
Grandpa is used for block finalization and less than 1/3 of total validator offline should not affect the block finalization time.

This basically means Aura node have high availability requirement whereas Grandpa have a lower availability requirement compare to Aura node. It will be good to allow node to become Grandpa validator without become Aura validator. This allows home server to become grandpa validators to improve decentralization without hurting the block production in case anything unexpected happens.

**Comment by rphmeier** [comment]
This is already possible.
