### ISSUE TITLE
macro `construct_runtime!` build metadata for Module in first position only

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#1846]
construct runtime generates metadata for a module with Module parameter only if this parameter is in the first position: https://github.com/paritytech/substrate/blob/master/srml/support/src/runtime.rs#L720-L764

This is quite error prone and not explicit in the documentation. So either we should make it explicit and I would recommend to compile error when Module is found in another place or we can just make it agnostic regard the position.

actually it is probably an error and the latter was what we wanted.

**Comment by thiolliere** [comment]
my bad

**Comment by bkchr** [comment]
That is clearly a bug, metadata should be generated regardless of the position of `Module`.
