### ISSUE TITLE
Nominate error: Nominate any validator,will nominate 5Ef31o...wa8VHN

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/substrate#1848]
**Tested version:**  
```
polkadot v0.3.14-2a5e8fc1  
&&
polkadot v0.3.14-2a5e8fc1
&&
substrate v0.10.0-8ef14988
```
**NOTE:** tested Dev chain, and Alexander have same issue.
- use charlie nominate Alice
![_ _20190222112631](https://user-images.githubusercontent.com/34789555/53217901-d352f600-3694-11e9-8ef6-e6a6a87ebfe7.png)  
![_ _20190222112701](https://user-images.githubusercontent.com/34789555/53217922-ed8cd400-3694-11e9-8eec-394fe6ab2915.png)

- Then charlie will nominate this address : `5Ef31oEFfAj1XJqWTY7V9g1xSdPjEB1WYX7X38qSFbwa8VHN`
![_ _20190222112708](https://user-images.githubusercontent.com/34789555/53217938-05fcee80-3695-11e9-99e8-1dc00e9ccf7e.png)
- Then can't **Unnominate**

**Comment by jacogr** [comment]
This doesn't seem like a substrate issue, this seems like a UI issue. (Cannot move it there, but should rather be opened there. Will close here, reference there.)
