### ISSUE TITLE
PeerInfo hash and number not updated

### ISSUE THREAD

**Issue by gterzian** [paritytech/substrate#1859]
It appears that [`PeerInfo`](https://github.com/paritytech/substrate/blob/1ca4cc0a16a357782bb1028bb57376594ca232a0/core/network/src/protocol.rs#L100) is not updated as part of ongoing sync, only `Peer.known_blocks` is updated: https://github.com/paritytech/substrate/blob/1ca4cc0a16a357782bb1028bb57376594ca232a0/core/network/src/protocol.rs#L838

Compare this with [`PeerSync`](https://github.com/paritytech/substrate/blob/1ca4cc0a16a357782bb1028bb57376594ca232a0/core/network/src/sync.rs#L49), whose best hash and number are updated when the peer announces new blocks https://github.com/paritytech/substrate/blob/1ca4cc0a16a357782bb1028bb57376594ca232a0/core/network/src/sync.rs#L703

Note that `PeerInfo` is the data used by the `ProtocolContext` that is passed around to the network specialization. So in practice, if the specialization were to check the best number of a peer, it would see the best number at the time the peer was first connected, without any updates that might have occured since. 

The `PeerInfo` is also used by `SyncProvider.pees`, which is for example used by the rpc system. So again the rpc system will only see the best hash and number at the time the peer connected. 

It would be quite easy to pass `PeerSync` to the specialization and so on, since all of that is thread-local in the `Protocol` thread. Note that if we want to make up to date best hash/number available to other threads via `SyncProvider`, the state of a peer becomes a source of lock contention across the system(see https://github.com/paritytech/substrate/pull/1857 and https://github.com/paritytech/substrate/issues/1853). So it might be better to make updates available via a stream of some sort. 

Don't know if this is intended or a bug...

**Comment by xlc** [comment]
Related? https://github.com/paritytech/substrate/issues/1805

**Comment by gterzian** [comment]
@xlc absolutely 👍
