### ISSUE TITLE
Improve blockchain import/export

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate#1860]
* Improve the status output for the import. At the moment the status output for importing many blocks looks like this:
```
$ cargo run -- import-blocks --dev ./5k-blocks.bin                                                                                                            
    Finished dev [unoptimized + debuginfo] target(s) in 0.82s
     Running `target/debug/substrate import-blocks --dev ./5k-blocks.bin`
2019-02-25 11:19:53 Importing 5000 blocks
2019-02-25 11:19:53 #0
2019-02-25 11:19:53 #1000
2019-02-25 11:19:53 #2000
2019-02-25 11:19:53 #3000
2019-02-25 11:19:53 #4000
```
It seems as if nearly all blocks were immediately imported, but what actually happened is that they were merely added to the import queue and the program will then hang for a long time whilst processing them all and giving no new output. The output should make clear how many were imported and how many are still processed.
* Rate-limit loading from the import file based on backpressure from the import queue, so that the case above is handled better. This was escalated from https://github.com/paritytech/substrate/pull/1807, where @rphmeier mentioned that we do it this way in parity-ethereum. Maybe some inspiration can be taken from there.
* Make it clear in the `--export-blocks` flag documentation that JSON cannot be re-imported.

**Comment by rphmeier** [comment]
@cmichi we should see if it's possible to print output using the informant (maybe modifying it so it has an `Option<NetworkHandle>` or whatever. This uses import notifications internally so it will give the behavior that we want.

**Comment by tomaka** [comment]
The import block part of the issue is fixed.

Remains:

> Make it clear in the --export-blocks flag documentation that JSON cannot be re-imported.
