### ISSUE TITLE
Remove dependency on OpenSSL

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#1862]
It is only used by the `ws` and `websocket` crates, and can be quite annoying especially on Windows.

Depends on https://github.com/libp2p/rust-libp2p/issues/849

**Comment by tomaka** [comment]
Triage: libp2p no longer depends on OpenSSL, but `jsonrpc` does.

**Comment by burdges** [comment]
We're using rusttls almost everywhere now?

**Comment by tomaka** [comment]
Closing as fixed.
I don't know what has fixed it, but we only depend on `openssl-probe` now.
