### ISSUE TITLE
Add an RPC query for the state of the network

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#1870]
We're having issues right now figuring out why a node A is connected or not to a node B.
In order to solve that, let's add an RPC query that returns the state of the network.

Since the networking in general may change in the future, make it clear for now that this is only about debugging. In other words:
- The output is meant to be read by a human.
- The output may change.

In the future, we may add more strongly-defined RPC queries.

**Comment by xlc** [comment]
I always want this but lack of time/knowledge to build it myself. I think this can extends `system_peers` RPC from #1362

**Comment by gterzian** [comment]
@tomaka what are you thinking of in terms of "state of the network"? Currently we have [`SyncProvider.peers()`](https://github.com/paritytech/substrate/blob/a6ca090c3e2e44b24f34319648f66b64575369e0/core/network/src/service.rs#L50) returning all connected peers. What additional details would this new rpc endpoint(or an extended `system_peers` expose?

**Comment by tomaka** [comment]
I was thinking of the peers we're connected to with libp2p but not Substrate, the local state of the DHT, the latest ping time, the identity of the peers (ie. their version), and so on.

In other words, not a hack-two-things-together issue but something that requires adding some involved modifications.

**Comment by bkchr** [comment]
@tomaka I added this to the `as-and-when` milestone. If you want to make this for `1.0`, just modify it :)
