### ISSUE TITLE
Keep track of storage bytes used by a contract

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#1877]
To properly charge contracts for their storage usage we would need to keep track the exact count of bytes a contract uses.

For now we can go with a simple way to do it, something like this: 

1. we add to a contract an associated field called `used_storage_bytes`. This involves adding the associated routines to the [`AccountDb`](https://github.com/paritytech/substrate/blob/ebe4c972bab088a760ca43e7662bf750ccf1e919/srml/contract/src/account_db.rs#L46) since this value is subject to reversal.
2. on each call to [`set_storage`](https://github.com/paritytech/substrate/blob/ebe4c972bab088a760ca43e7662bf750ccf1e919/srml/contract/src/exec.rs#L561) we would compare the value being set to the old value. We add the difference between the old and new values to some counter local to [`CallContext`](https://github.com/paritytech/substrate/blob/ebe4c972bab088a760ca43e7662bf750ccf1e919/srml/contract/src/exec.rs#L548). This counter is initialized with value of `used_storage_bytes` upon creation of the `CallContext`.
3. after the execution of the call is finished, we flush the local counter to the associated `used_storage_bytes`.

Upon instantiation of a contract `used_storage_bytes` is initialized with the value of a global variable `used_bytes_offset`, that should also be introduced as part of this PR.

**Comment by cheme** [comment]
Using child trie for account, this could be calculated at trie level.
Question, currently there does not seem to be a size limit on store element (same thing for runtime in fact), current trie structure is not really fit for big value, would'nt it be simplier to use fix length storage and then evaluate to number of element of the child trie (it still needs the trie to be able to keep trace of it number of values)?
Still make me think that trie should be able to manage big value more efficiently.

**Comment by pepyakin** [comment]
Ah, I'm not really familiar with our trie implementation and whether it is possible to do that efficiently, but that would be cool if it is possible to do that. 
That said, I'm fine with starting with the naive approach presented in the description.

There is no limit on stored a size of a stored value presently, right. However, we would like to change it. For example, it is absurd to store a value which size is so big that it would take gas around the block limit. In practice, the limit should be way smaller, I'd say. On the other hand, I'd prefer not to set it as low as 32 bytes, as Ethereum does. As a ballpark estimate, I'd say that the value size should be somewhere between 1KB-8KB (Don't quote me on that). Even if it ends up with 1KB or even 512 bytes, we don't want to keep track of size of a contract in those rough discrete values. If a contract uses only 4 bytes, it IMO should be charged only for 4 bytes.

**Comment by thiolliere** [comment]
https://github.com/paritytech/substrate/pull/2154

**Comment by thiolliere** [comment]
I think the current implementation is ok it just have to query the previous value before committing each change to and then after committing all change it update the actual storage_size.

Though we can still reopen and change the title of the issue
