### ISSUE TITLE
Implementation of accounting and removal

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#1882]
This is the principal part of the state rent system and it includes:

1. implementation of deduction due to touching a contract,
2. implementation of the `claim_surcharge` dispatchable call, which essentially gives a way for touch a contract without involving code execution and also offers incentivisation for sending inherents and signed extrinsics (with the preference of the former one).
3. generating a tombstone hash (a hash value that is required for the restoration process).

There is one open question at the present, whether or not we want for removal to be a subject for rollback or not. I believe the rollback mechanism can be implemented as a separate issue.

**Comment by thiolliere** [comment]
by rollback you mean https://github.com/paritytech/substrate/issues/1883 isn't it ?

**Comment by pepyakin** [comment]
no, I actually mean rollback of `AccountDb`.

**Comment by xlc** [comment]
Are there any documentations about the state rent system? I want to evaluate if #2230 is a breaking change or not and the effect of it but without a high level documentation it is hard to figure out how it works exactly.
