### ISSUE TITLE
Restoration mechanism

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#1883]
In this part of the state rent mechanism a means for restoration of removed contract are implemented.

We would implement a function `ext_restore` that receives all the required parameters for the restoration of a contract. The storage is transfered from the calling contract and the calling contract is destroyed. This happens eagerly without delaying it to the finalization stage.

**Comment by thiolliere** [comment]
Do we want to allow to restore a contract that has been evicted from a just previous call (tombstone is not yet written to final storage, only pending in overlay) ?

**Comment by thiolliere** [comment]
design of https://github.com/paritytech/substrate/issues/1882 has strong consequences on this, so I think I should think on both at the same time.

**Comment by thiolliere** [comment]
restore should be an extrinsic also ?
