### ISSUE TITLE
Rewrite `construct_runtime!` as procedural macro

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#1897]
The declarative macro `construct_runtime!` should be rewritten as procedural macro. The current version of the macro can be found here: https://github.com/paritytech/substrate/blob/master/srml/support/src/runtime.rs#L78-L267
All the `__decl_*` helper macros in the same file should be converted as well.

Expected outcome:
- Much better error reporting
- Better readable code
- More tests 

Expected time frame, around week, depending on the rust/procedural macro knowledge.

**Comment by alleycat-at-git** [comment]
@bkchr I'm currently implementing this refactoring and one thing I struggle with is how to call `impl_outer_event` that is located in `srml-support` crate from the `srml-support-procedural` crate. Basically I'm rewriting the `__decl_outer_event` macro and it uses `crate::impl_outer_event` at the expansion. Obviously, when I do the same in `srml-support-procedural` crate I get an error. Is there a workaround of that except an obvious rewriting of `impl_outer_event`?

**Comment by bkchr** [comment]
Hey, first ty that you are doing this :)

Could you please take a look here:
https://github.com/paritytech/substrate/blob/66042f1cc737f4eb5ca8d05db9d981c3e4bd3693/srml/support/procedural/src/storage/transformation.rs#L85-L91

Basically, we will re-export the macro from the `srml-support` module. So, you will need to include this crate in a hidden module and then you can access everything `srml-support` exports.
I hope that is understandable, if not, just ask again :)

**Comment by alleycat-at-git** [comment]
@bkchr #3810 Ready for review
