### ISSUE TITLE
Genesis Config Storage Encoding Values Incorrectly

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#1899]
https://github.com/paritytech/substrate/blob/f429a0cb8983cebe380d1cbc7aaf753db0aeba55/srml/support/procedural/src/storage/transformation.rs#L240

@thiolliere and I spent some time debugging an issue I found when working on tests in the new staking module. We ended up finding that the encode/decode process around building genesis storage can result in bad values.

Here is an example of how we determine this line is the problem.

We introduce some print statements around the code:

```
println!("Before: {:?}", v);
let v = Encode::using_encoded(&v, |mut v| {println!("Meanwhile {:?}", v); let a = Decode::decode(&mut v); println!("After: {:?}", a); a})
    .expect(#error_message);
```

We build the genesis value as seen in this pull request branch:
https://github.com/paritytech/substrate/pull/1782

```
		/// The amount of balance actively at stake for each validator slot, currently.
		///
		/// This is used to derive rewards and punishments.
		pub SlotStake get(slot_stake) build(|config: &GenesisConfig<T>| {
			config.stakers.iter().map(|&(_, _, value)| value).min()
		}): BalanceOf<T>;
```

We expect the value `1000` to be stored, but when we print the value on block 1, we see `256001`. Here is the result of the print statements we added:

```
Before: Some(1000)
Meanwhile [1, 232, 3, 0, 0, 0, 0, 0, 0]
After: Some(256001)
```

In fact, the value which is actually stored is always 256*x +1 which makes it look like some sort of issue related to compact encoding.

This issue does NOT appear for most other types or situation, only with `BalanceOf`. Here are some of the other outputs from the same updated code:

```
Before: 0
Meanwhile [0, 0, 0, 0]
After: Some(0)
Before: 3
Meanwhile [3, 0, 0, 0, 0, 0, 0, 0]
After: Some(3)
Before: Perbill(1000000000)
Meanwhile [0, 202, 154, 59]
After: Some(Perbill(1000000000))
Before: Perbill(400000000)
Meanwhile [0, 132, 215, 23]
After: Some(Perbill(400000000))
```

**Comment by thiolliere** [comment]
it seems to be figured out :-) on decl_storage we accept whatever type. I'll fix it on decl_storage macro.

**Comment by shawntabrizi** [comment]
Fixed the bug in code here: https://github.com/paritytech/substrate/commit/93da8d8c0d8ab84175d834f7b5a52db25708b463

**Comment by bkchr** [comment]
CC @cheme

**Comment by thiolliere** [comment]
fixing on decl_storage part is more work that expected, let's move to https://github.com/paritytech/substrate/issues/1901
