### ISSUE TITLE
decl_storage build expression is error prone because type is not checked

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#1901]
We had hard time debugging it with @shawntabrizi  [there](https://github.com/paritytech/substrate/issues/1899)

indeed build is a closure that return whatever encodable type we encode it and decode it as the true put type:
https://github.com/paritytech/substrate/blob/master/srml/support/procedural/src/storage/transformation.rs#L240

in some of our code we actually return the correct type:
 `./srml/session/src/lib.rs:103:		pub CurrentIndex get(current_index) build(|_| T::BlockNumber::sa(0)): T::BlockNumber;`

in some other part we don't and can't as is (it would require some new bounds on abstract type) like for abstract type hash for example: 
`./srml/system/src/lib.rs:205:		RandomSeed get(random_seed) build(|_| [0u8; 32]): T::Hash;`

many ways to solve it:
* let as is
* requiring explicit type and make new bounds
* make a build argument that explicit type and unsafe_build that only requires encodable one

**Comment by bkchr** [comment]
CC @cheme again :D

**Comment by cheme** [comment]
Could returning directly the required type from the closure be an option?

**Comment by thiolliere** [comment]
I mean we can also make this closure return an enum like
```rust
struct ClosureReturn<T: Encode> {
  Explicit(Hash)
  UnsafeUnexplicit(T)
}
impl From<Hash> for ClosureReturn..
impl ClosureReturn {
  fn unwrap() {
    match {
// if unexplicit then encode decode as before
    }
  }
}

and making something like user return: 
Safe(...)
or Unsafe(...)
```
hmm not sure, I just try to bring ideas

**Comment by thiolliere** [comment]
looking at the code it seems we actually need the unsafe things is when storing abstract Hash type.

if I didn't miss things there is no other use of unsafe type in substrate at the moment

**Comment by rphmeier** [comment]
cc @shawntabrizi here's a pitfall :)
