### ISSUE TITLE
What prevents balances module `Balance` type to be signed integer?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1904]
I believed it is assumed everywhere that `Balance` have to be unsigned integer but I did not see any type bounds about this.

Is using signed integer allowed or there is a missing type bound?

I tried to change the type to `i128` and getting this compile error, which I believe is fixed in parity-codec 3.1?
```
--> node/runtime/src/lib.rs:102:6
    |
102 | impl balances::Trait for Runtime {
    |      ^^^^^^^^^^^^^^^
    |
    = help: consider adding a `#![recursion_limit="512"]` attribute to your crate
    = note: required because of the requirements on the impl of `_IMPL_DECODE_FOR_Event::_parity_codec::Decode` for `_IMPL_DECODE_FOR_Event::_parity_codec::Compact<_>`
    = note: required because of the requirements on the impl of `_IMPL_DECODE_FOR_Event::_parity_codec::Decode` for `_IMPL_DECODE_FOR_Event::_parity_codec::Compact<_>`
```

**Comment by bkchr** [comment]
The error message is weird, but I think the problem is that we don't implement `Compact` for signed types. Do you want to support negative balances?

**Comment by xlc** [comment]
I don’t want to support negative balance and I would like to enforce it via compiler instead of documentation.

**Comment by bkchr** [comment]
What do you want to enforce? Non-negative balances? Use a `u128` as this can not be negative.

**Comment by xlc** [comment]
I am developing a module using the Balance type from balances module. I need to ensure a value is positive. I can either `value > Zero::zero()` or `!value.is_zero()`. First one works for both signed or unsigned value, second one only works for unsigned value. But I cannot make the assumption that Balance type is always unsigned unless it is been enforced by balances module type bounds, which is not the case here.

**Comment by bkchr** [comment]
So, why not just use `value > Zero::zero()`? I assume that it should be as fast as `!value.zero()`.
Another solution could be to let your module trait derive from the `Balance` trait and add a trait bound `where <Self as balance::Trait>::Balance: Unsigned` and you the `Unsigned` trait from [here](https://docs.rs/num/0.2.0/num/trait.Unsigned.html).

**Comment by xlc** [comment]
That will work. My real question is: Is it intentional to not having Unsigned trait for the Balance type in the balances module?

**Comment by bkchr** [comment]
If the user wants, he still could get a signed type into the balance by using a new type wrapper and implementing the unsigned trait.
So, you can not really force the user to use unsigned data types.

**Comment by xlc** [comment]
Sounds like won’t fix for me, which is fine.
