### ISSUE TITLE
Move finality-tracker opinions on finalized block height out of chain state

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#1909]
#1458 might be an approach to this

Keeping all recently thought-to-be-finalized heights ("opinions") by block authors in chain storage is overkill.

Some kind of dedicated auxiliary storage would be far more efficient. This would only require that full nodes intending to follow the median would keep some recent blocks in their chain.

This would have some fallout in the GRANDPA offline-fallback implementation, as currently the chain is aware of signalled offline changes and can avoid dispatching regular change events that interleave with them. After this issue is complete, the chain won't be aware of signalled offline changes because they will originate from out-of-band logic.

**Comment by andresilva** [comment]
The finality tracker has been removed.
