### ISSUE TITLE
Different chain networks should not route each other's p2p node information to each other.

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1913]
2019-03-04 15:23:44.419 INFO Banned PeerId(QmdU82FC39tj6YUFsie2cC3LLjqWEqA6C7N5piWb8XTjWX) (#5, Dialer { address: "/ip4/47.96.97.52/tcp/31127" }, None).

There are some different p2p information in network/node.json.

**Comment by bkchr** [comment]
CC @tomaka

**Comment by tomaka** [comment]
Right now the network is differentiated based on the `protocol_id` in the chain spec: https://github.com/paritytech/substrate/blob/f429a0cb8983cebe380d1cbc7aaf753db0aeba55/core/service/src/chain_spec.rs#L92

Later I'd like to try switch to a different discovery mechanism that allows knowing which chain a node belongs to when discovering it.
cc https://github.com/libp2p/rust-libp2p/pull/942

**Comment by tomaka** [comment]
Progress report: #5045 is the first step towards fixing this.
We need a transition period during which nodes support both the old Kademlia and the one-DHT-per-chain. Then later we can finish this by removing the old Kademlia.

**Comment by tomaka** [comment]
#5993 removed the old Kademlia.
The last step is https://github.com/paritytech/substrate/issues/5825

**Comment by tomaka** [comment]
Fixed in https://github.com/paritytech/substrate/pull/6549
