### ISSUE TITLE
Grandpa consensus affects p2p links

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1922]
When the finalized of the nodes are inconsistent, the nodes that are finalized are more easily connected.

<img width="1275" alt="wechatc659c4bed4f255b3bc13c4f7fc655d47" src="https://user-images.githubusercontent.com/9285062/53776844-58aa9600-3f32-11e9-83ca-7e37aac10a2b.png">
There are 3 validators in **3992**height, however, only 1 validator in **3990** height. So in **3990** height's validator can't connect other node.
<img width="1251" alt="wechat81383614c7481b059439c57ef9f76a04" src="https://user-images.githubusercontent.com/9285062/53776866-7546ce00-3f32-11e9-8f57-3304fbb94401.png">

**Comment by rphmeier** [comment]
cc @arkpar , it may have something to do with block announcements?

Also, it might be a case that the poor connectivity causes the validator to be behind, not the other way around.

**Comment by gguoss** [comment]
![image](https://user-images.githubusercontent.com/9285062/53937847-4de63180-40e9-11e9-9f0a-3a277fe81621.png)

- problem 1: listen_addrs: ["/ip4/127.0.0.1/tcp/30333", "/ip4/192.168.1.236/tcp/30333", "/ip4/115.193.183.144/tcp/30333", "/ip4/0.0.0.0/tcp/30333"].
0.0.0.0 can't listen?

- problem 2: INFO sync  Dropping 1 because "Sent unknown consensus engine id" ,Dropping PeerId(QmSX5KnWLHo5nd3iK6Q99tQEF2v9StAoHQGEb3XY7g3QHk) on purpose (#1, Dialer { address: "/ip4/127.0.0.1/tcp/30333" }, None).  
this peer is god node, can't dropping because unknown consensus engine id？

- problem 3: INFO substrate  Idle (0 peers).
0 peers can't run gossip？

**Comment by gguoss** [comment]
![image](https://user-images.githubusercontent.com/9285062/53938543-8c7ceb80-40eb-11e9-97c6-923b0498da67.png)

can't connect 0.0.0.0:port, can reconnect 127.0.0.1:port

**Comment by gguoss** [comment]
<img width="2120" alt="wechat6d09608edf7cd63e948eabfbd7a1bfbc" src="https://user-images.githubusercontent.com/9285062/54003272-973b8d00-418c-11e9-869b-f3eb930dfcdf.png">

Validator (auth1, auth2, auth3, auth4)
problem1: In height 17400(Grandpa update authority, deposit log), affect p2p links.

problem2: auth 1~4, p2p connected correct, but height not consistent, (auth3 ,auth4) in 17700 ad spawn block.  (auth1 and auth2 ) in 17433 and spawn block.

**Comment by gguoss** [comment]
[auth1.log](https://github.com/paritytech/substrate/files/2944240/auth1.log)
17400 is finalized by grandpa. but auth1 continue rollback (< 17400).

**Comment by rphmeier** [comment]
Related to https://github.com/paritytech/substrate/pull/1944 perhaps

**Comment by rphmeier** [comment]
@gguoss how does latest master do?

**Comment by gguoss** [comment]
Before #1944 test. 
Now used latest master test , p2p looks good.

**Comment by gguoss** [comment]
4 validators (A,B,C,D )
A,B,C same finalized height(same round). then start D(D's round < (A or B or C)'s round).

In Mac OS, D can't connect any node, 
libp2p-2 INFO sync  Dropping 1 because "Sent unknown consensus engine id".

In Ubuntu OS, A, B, C, D 4 validators run ok.

**Comment by rphmeier** [comment]
@gguoss I'll keep this one open for now -- we are in the middle of some network overhaul to make this better.

**Comment by arkpar** [comment]
This is now resolved as far as I know
