### ISSUE TITLE
Telemetry reportedly not submitting data on windows.

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/substrate#1929]
Originally reported at https://github.com/paritytech/substrate-telemetry/issues/116

Error in action (in a VM):
![](https://maciej.codes/kosz/wserror.png)

This only happens when using `wss` connections, `ws` connections either to localhost or live telemetry over `ws` are going in through fine.

**WORKAROUND**: Windows clients can use `--telemetry-url ws://telemetry.polkadot.io:1024/`, the URL is deprecated but it works for now (I'll make sure it continues to work until this issue is resolved).

Sadly there is little context to the issue. I'll try doing some stuff in the VM to see if I can fix it.

**Comment by mnaamani** [comment]
Is the client missing some CA certs used by telemetry.polkadot.io ? or perhaps using incompatible key exchange/encryption scheme?

**Comment by maciejhirsz** [comment]
I don't know yet, the error is completely uninformative (`StringError("None")`), and it's coming from the underlying WS library. Missing certs is a possibility.

**Comment by maciejhirsz** [comment]
OpenSSL is not working for mysterious reasons. The `ws` crate can be switched to `native-tls`, but that one [panics on Windows](https://github.com/housleyjk/ws-rs/issues/226) instead.

**Comment by DemiMarie-parity** [comment]
Does ring-tls work?

**Comment by maciejhirsz** [comment]
It might, but we are constrained by whatever TLS support the `ws` crate has.

**Comment by tomaka** [comment]
In #2812, we switched the implementation from `ws` to `libp2p-websocket`.
This would need to be tested again.

**Comment by tomaka** [comment]
Triaging: let's close this. Please reopen if that issue arises again.
