### ISSUE TITLE
decl_storage! generation of a hidden module could be avoided in some situation

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#1936]
the hidden module doesn't harm that much but sometimes rustc then propose solutions to user that are not very encouraged.

Like if Currency is not in scope it may advise for 
```rust
use crate::demo::sr_api_hidden_includes_decl_storage::hidden_include::traits::Currency;
```
which user should not rely on.

This is OK as it is in the name but still it could be avoided: generate_crate_access and generate_hidden_include should return renamed crate name and no module to generate if outside of the crate itself.

**Comment by bkchr** [comment]
The module just needs to be tagged as `#[doc(hidden)]` and then the rust people finally need to ignore these stuff in the compiler.

**Comment by thiolliere** [comment]
I got those annoying path quite often actually I think as we can implement without module very easily, it worth not waiting for compiler improvments

**Comment by thiolliere** [comment]
well by the way if wanted I can PR https://github.com/paritytech/substrate/compare/gui-remove-missleading-hidden-import?expand=1

**Comment by bkchr** [comment]
Your solution only works for rust 2018 and I'm also not sure what happens when the user renames a crate in lib.rs in rust 2018.
This is a compiler bug, if you want it to be solved, please solve it in rustc.

**Comment by thiolliere** [comment]
indeed I forgot 2015
