### ISSUE TITLE
Potential grandpa performance issue

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1938]
3 validators setup. Due some libp2p issue the connections between nodes are very unstable.
As the result of the unstable connections, the chain stop finalizing. This is fine as I know people are investigating on the libp2p issue.

Now my chain have best block 36722 and finalized 18681.

I copied the db folder of a validator node (synced up to date) and started a new node. It start using 100% CPU on single core and stops responding (no syncing, no RPC, no Ctrl+C to kill).

I did some quick investigation and found out the only thread `ImportQueue` is busy (using 100% CPU) and all the work are inside this
https://github.com/paritytech/substrate/blob/82744fbb6f4d677f2edfe9d88737c237622c97a4/core/finality-grandpa/src/import.rs#L90

and most of time are in this loop
https://github.com/paritytech/substrate/blob/82744fbb6f4d677f2edfe9d88737c237622c97a4/core/client/src/client.rs#L1173

I am not familiar how to do performance analysis on rust but just few random pause shows most of time are accessing rocks db for block headers to traverse in the chain.

This probably causes libp2p timeout issue because it takes more than 5mins in my cause to finish `best_containing` call.

I am not familiar with this part of the code, it will be good if someone do #1444 and make sure `best_containing` can always be completed in a reasonable amount of time.

**Comment by andresilva** [comment]
I believe the issue is that the leaf set was not being pruned when leaves were finalized and therefore it just grew unbound. https://github.com/paritytech/substrate/pull/1871 fixed this.

**Comment by andresilva** [comment]
Can you check if the version you're using contains that PR?

**Comment by xlc** [comment]
Cool. I did not have that change. I will update substrate.
