### ISSUE TITLE
Grandpa polling round 1 ?

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1939]
![image](https://user-images.githubusercontent.com/9285062/53940209-06af6f00-40f0-11e9-9886-a24255255c0d.png)

finalized is 6654,  right round is 56. however this node is polling round 1.

**Comment by gguoss** [comment]
<img width="1879" alt="wechat00e90099e0aa668a6b17e9452c0f6b32" src="https://user-images.githubusercontent.com/9285062/53940422-a10fb280-40f0-11e9-8a5b-2c636c4326c7.png">
When the number of peers is 0, should the grandpa poll be stopped?

**Comment by rphmeier** [comment]
Did you erase the DB and restart? How many nodes are live voting?

**Comment by gguoss** [comment]
I can't be sure of the specific situation. After all, it has been a while.
 But I probably remember that it should
 erase the db and restart,  less than 2/3 nodes voting.

We have used the latest substrate and have not encountered similar problems in p2p, and grandpa.
