### ISSUE TITLE
The normal node in the p2p network cannot connect.

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1940]
Some p2p nodes can't connect to any node. You must delete the node.json that rejects your peer and restart the peer node before you can link yourself to the peer. Regularly deleting node.json and restarting p2p can solve this problem, but it is rather rude. The scoring system in p2p rejects the system, and from time to time it will isolate some good nodes and never connect.

**Comment by xlc** [comment]
I am seeing the same issue as well.

**Comment by tomaka** [comment]
This issue has been open a long time ago when the network was known to have lots of issues.
Since the networking looks stable now, and since this issues doesn't really provide much information, I'm going to close this.
