### ISSUE TITLE
How to implement an in memory store for extrinsic scope variable?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1949]
I need a place to store some values that are global accessible by multiple modules. The lifetime of this store does not need to exceeds the execution of extrinsic. i.e. it get cleared between each time an extrinsic is applied.

Basically I want to setup a `Map<Vec<u8>, Vec<u8>>` before this line and make it accessible during the extrinsic execution. May be some helper methods/macros to ensure type safety.
https://github.com/paritytech/substrate/blob/c4ca27f7121f37172ae0d2d92280a947ca77edd8/srml/executive/src/lib.rs#L186

I can't find a way to implement it without some kind of global variables. I am not sure if `lazy_static` is allowed in the runtime. The only other solution I can think of is add new method in [Externalities](https://github.com/paritytech/substrate/blob/c4ca27f7121f37172ae0d2d92280a947ca77edd8/core/state-machine/src/lib.rs#L89)

Related comments:
https://github.com/paritytech/substrate/pull/1924#discussion_r263031905
https://github.com/paritytech/substrate/pull/1815#issuecomment-465845939

**Comment by gavofyork** [comment]
Any data that needs to persist outside of `apply_extrinsic` (a single dispatchable `Call`), must be stored in a storage item.
