### ISSUE TITLE
Failed to write to trie: Database missing expected key

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [paritytech/substrate#1952]
> 2019-03-10 02:12:01 Substrate Node
> 2019-03-10 02:12:01   version 0.10.0-c4ca27f7-x86_64-linux-gnu
> 2019-03-10 02:12:01   by Parity Technologies, 2017-2019
> 2019-03-10 02:12:01 Chain specification: Dried Danta
> 2019-03-10 02:12:01 Node name: absorbing-death-5599
> 2019-03-10 02:12:01 Roles: FULL
> 2019-03-10 02:12:03 Best block: #244116
> 2019-03-10 02:12:03 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmQxEngmGUqKqyuCAMpXYzrShHDokUZYtb9cxV1457Mozx
> 2019-03-10 02:12:03 Kademlia random query has yielded empty results
> 2019-03-10 02:12:03 Listening for new connections on 127.0.0.1:9944.
> 2019-03-10 02:12:03 Network misbehaviour from PeerId(QmRn8yqn6LPTcM7fc2Wo76u9wgqw2WKU9Ysmegm9NCSrwU) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
> 2019-03-10 02:12:03 Network misbehaviour from PeerId(QmVGwAmgrS4HTi8Qka6aVAdG3uS7u7nEzcdE1qdbgSttiw) with protocol [115, 117, 112]: Upgrade(Select(NoProtocolFound))
> 2019-03-10 02:12:03 Failed to write to trie: Database missing expected key: 0x574a466dde88b6a5c6839615cf2e92e13ca21f654a80e370e411f40ca3e7d513
> Hash not equal
> 4d12b5464945cf6250a81c8cba4bc4c071642fd05687d899a34124f476adb8f2
> d6dfaeca7e72e503d4670ebc27edc8f7f3cba31cf53f9f8d54090b07cf3890b8
> /Users/a/src/substrate2/srml/executive/src/lib.rs
> 214
> 3`

**Comment by gguoss** [comment]
same as https://github.com/paritytech/substrate/issues/1733

**Comment by Matthias-Fauconneau** [comment]
purge-chain, --pruning=archive gets me to sync. 
But not finalize which might be why the node stays idle. 
Updates from time to time but does not participate.
I tried Polkadot Alexander as well, and that just doesn't even sync (idles at block 0).
I guess I should not worry about correct versioning since Cargo compiles all the libraries.
Maybe toolchain ?
Or simply broken backward compatibility somewhere syncing up new nodes, any CI ?
