### ISSUE TITLE
 Error(Client(Backend("GRANDPA DB is corrupted."))

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1955]
All 3 validators nodes cannot be started with this error.

```
2019-03-10 21:10:54.819 main INFO substrate::cli  Node name: ANDREA
2019-03-10 21:10:54.819 main INFO substrate::cli  Roles: AUTHORITY
Error: Error(Client(Backend("GRANDPA DB is corrupted.")), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

Let me know if you need to access the genesis json file and the db folder

**Comment by hammeWang** [comment]
I have fetched&merged the latest version today and still got `Error: Error(Client(Backend("GRANDPA DB is corrupted.")),`.

**Comment by sunqiLoveSnow** [comment]
got similar error log as 
"Error: Service(Client(Backend("GRANDPA DB is corrupted: Error decoding field VoterSetState :: Live.completed_rounds")))
"
