### ISSUE TITLE
Panic about telemetry.

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1957]
stack backtrace:
   0: substrate_panic_handler::panic_hook::h556a24646b64e387 (0x110769d1b)
             at /Users/gavin/.cargo/git/checkouts/substrate-cce119ab4fc6bea1/35b778a/core/panic-handler/src/lib.rs:82
   1: substrate_panic_handler::set::{{closure}}::h9be6d9fd5e6879d6 (0x110769926)
             at /Users/gavin/.cargo/git/checkouts/substrate-cce119ab4fc6bea1/35b778a/core/panic-handler/src/lib.rs:31
   2: std::panicking::rust_panic_with_hook::h89953ae7e5aa54e3 (0x110af0e20)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/panicking.rs:478
   3: std::panicking::begin_panic::h31c1589473c45536 (0x110a5d4e7)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/panicking.rs:408
   4: <slog_scope::NoGlobalLoggerSet as slog::Drain>::log::hb2d74c831cf6d165 (0x110620c9b)
             at /Users/gavin/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.1.1/lib.rs:123
   5: <alloc::sync::Arc<D> as slog::Drain>::log::h49f15b9847f1ac86 (0x10e825827)
             at /Users/gavin/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.4.1/src/lib.rs:1690
   6: <slog::Logger<D>>::log::hfe58f425777d63a4 (0x10e824492)
             at /Users/gavin/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-2.4.1/src/lib.rs:1204
   7: <substrate_consensus_aura::AuraVerifier<C, E> as substrate_consensus_common::import_queue::Verifier<B>>::verify::{{closure}}::h4c376916321b4599 (0x10dac273a)
             at /Users/gavin/work/rust/ChainX/<::slog::slog_log macros>:4
   8: slog_scope::with_logger::{{closure}}::h8cd17216f852109f (0x10d988917)
             at /Users/gavin/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.1.1/lib.rs:215
   9: <std::thread::local::LocalKey<T>>::try_with::h96ccb30b93b82ddd (0x10d69d775)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/thread/local.rs:296
  10: <std::thread::local::LocalKey<T>>::with::hc7825fe6ffcf190d (0x10d68beec)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/thread/local.rs:242
  11: slog_scope::with_logger::hd88565c26f2686db (0x10d9865f6)
             at /Users/gavin/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.1.1/lib.rs:211
  12: <substrate_consensus_aura::AuraVerifier<C, E> as substrate_consensus_common::import_queue::Verifier<B>>::verify::hc88e277671817473 (0x10dac0ebd)
             at /Users/gavin/work/rust/ChainX/<::substrate_telemetry::telemetry macros>:2
  13: substrate_consensus_common::import_queue::import_single_block::h742c55c784c7c83d (0x10ddbc33b)
             at /Users/gavin/.cargo/git/checkouts/substrate-cce119ab4fc6bea1/35b778a/core/consensus/common/src/import_queue.rs:552
  14: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::import_a_batch_of_blocks::h754b4fb139283a29 (0x10ddc4ad5)
             at /Users/gavin/.cargo/git/checkouts/substrate-cce119ab4fc6bea1/35b778a/core/consensus/common/src/import_queue.rs:431
  15: <substrate_consensus_common::import_queue::BlockImportWorker<B, V>>::new::{{closure}}::h3331c96d2221e560 (0x10ddc594e)
             at /Users/gavin/.cargo/git/checkouts/substrate-cce119ab4fc6bea1/35b778a/core/consensus/common/src/import_queue.rs:397
  16: std::sys_common::backtrace::__rust_begin_short_backtrace::h3cfa3ddd980bb74d (0x10e080c80)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/sys_common/backtrace.rs:136
  17: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hbc378d8c47024e1c (0x10dacee80)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/thread/mod.rs:469
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf03429e3de26c18b (0x10ded18a0)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/panic.rs:309
  19: std::panicking::try::do_call::h9bbc4ee6d9c9c099 (0x10e1bb590)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/panicking.rs:293
  20: ___rust_maybe_catch_panic (0x110afa25e)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libpanic_unwind/lib.rs:87
  21: std::panicking::try::hcfbca6cb32f8a0ca (0x10e1b9621)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/panicking.rs:272
  22: std::panic::catch_unwind::h41e24b57880e2062 (0x10ded1de0)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/panic.rs:388
  23: std::thread::Builder::spawn_unchecked::{{closure}}::hd220473d940c020a (0x10dace60c)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/thread/mod.rs:468
  24: <F as alloc::boxed::FnBox<A>>::call_box::haba31bc361f3fd44 (0x10dacf248)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/liballoc/boxed.rs:749
  25: std::sys::unix::thread::Thread::new::thread_start::h4d0c5d5fe5fab51e (0x110af96ab)
             at /rustc/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/libstd/sys_common/thread.rs:14
  26: __pthread_body (0x7fff7996d304)
  27: __pthread_start (0x7fff7997026e)

Thread 'ImportQueueWorker' panicked at 'slog-scope: No logger set. Use `slog_scope::set_global_logger` or `slog_scope::scope`.', /Users/gavin/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-scope-4.1.1/lib.rs:123

Use Ctrl + C command to  close process.

**Comment by gavofyork** [comment]
Under what conditions did this happen?

**Comment by gguoss** [comment]
https://github.com/paritytech/substrate/blob/6ac1f183e0852a387953592d31f01957ff3c76f8/node/cli/src/lib.rs#L127-L130, 
substrate node is Ok, only node-template is not add it.

ChainX is derived substrate node-template, so panic it.

**Comment by bkchr** [comment]
Should be fixed by #1958
