### ISSUE TITLE
staking genesis config `stakers` not working 

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#1967]
I started with `cargo run -- --dev` and from polkadot apps chain state `staking.slotStake` is still 0 and stakers give me 0 as well.

Something wrong in those lines

https://github.com/paritytech/substrate/blob/83edb41dea03ad3ffae0204c710058aab5ccce04/srml/staking/src/lib.rs#L269-L278

I need to call `staking.bound` from the Alice account and then on next era have a non-zero `staking.slotStake`

**Comment by Kianenigma** [comment]
I'm slightly uncertain of how exactly the specs are found and build; But at a first glance, it looks to be an issue from not the mentioned code but somewhere in `chain_spec`. Will have a closer look at it. Some validators __should__ have been selected.
