### ISSUE TITLE
Inherent transaction shouldn't deposit executive result event.

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#1985]
https://github.com/paritytech/substrate/blob/7af4c9c9cd6b689db5bcba5b76edc18bca80c781/srml/executive/src/lib.rs#L187

inherent transaction always success. shouldn't deposit executive result event.

**Comment by gavofyork** [comment]
this isn't strictly true: inherent extrinsics are just as fallible as any other extrinsic.

that said, it is something of a waste, so would be worth considering if it can be done cleanly.
