### ISSUE TITLE
[Tutorial] `subkey inspect Alice` returns nothing

### ISSUE THREAD

**Issue by fleupold** [paritytech/substrate#1989]
#1795 renamed the `subkey restore` subcommand to `subkey inspect`. However, the command `subkey inspect Alice` from the substrate [tutorial](https://docs.substrate.dev/docs/creating-a-custom-substrate-chain#section-step-2-add-alice-to-your-network) is no longer returning any output.

This makes it hard to recover the seed for the pre-funded account. Would it be possible to update the tutorial with a working command?

To temporarily workaround, the seed happens to be `0x416c696365202020202020202020202020202020202020202020202020202020`

**Comment by shawntabrizi** [comment]
The functionality of converting "Alice" into a 256bit hex was lost in the latest update, but I updated the tutorial to use the latest commands and made a note that "0x416c696365202020202020202020202020202020202020202020202020202020" is simply "Alice" in hex

**Comment by shawntabrizi** [comment]
## Step 2: Add Alice to your network

Alice is a hard-coded account in your blockchain's genesis block configuration. To make your life easier, this account is automatically pre-funded with currency and made a "super user" to your blockchain upgrade system. To access the "Alice" account, you must use her unique seed, which happens to be a 256 bit hex encoding of the string "Alice":
```
0x416c696365202020202020202020202020202020202020202020202020202020
```
Optionally, you can see the details generated by this seed by opening a new terminal, and using the installed substrate/subkey package:

```
subkey inspect 0x416c696365202020202020202020202020202020202020202020202020202020
    
> Secret Key URI `0x416c696365202020202020202020202020202020202020202020202020202020` is account:
>   Public key (hex): 0x787d6f7e9572e21656f61d3d897c343c80c81b774b1d76e5c8c72552b7ccbc25
>   Address (SS58): 5Engs9f8Gk6JqvVWz3kFyJ8Kqkgx7pLi8C1UTcr7EZ855wTQ
```

**Comment by shawntabrizi** [comment]
This is now further updated to support the latest crypto in Substrate and the Substrate UI.

Alice's URI is now: `//Alice` using sr25519, and can be directly put into the seed for the substrate UI

**Comment by gatsbyz** [comment]
`./target/release/subkey inspect //Alice`  works geat for me
