### ISSUE TITLE
Change `stake` from the balances module to `issuance`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#1990]
Balances module stills refers to "total balance across all accounts" as "total stake" when this is now "total issuance".

Changing all notions of "stake" to "issuance" can be important to prevent confusion with the staking module.

Specifically:
https://github.com/paritytech/substrate/blob/8930f297737db67257f3be1a8b286f8c50189066/srml/balances/src/lib.rs#L358-L369

Should have updated function names, and all downstream dependencies on these functions will need to be updated.

Additionally, any documentation which references this "stake" term in the context of the balances module should be updated.

**Comment by shawntabrizi** [comment]
Renaming all functions happening here: https://github.com/paritytech/substrate/pull/2025
Renaming all documentation happening here: https://github.com/paritytech/substrate/pull/1943

**Comment by gavofyork** [comment]
Closing then.
