### ISSUE TITLE
Remove `upgrade-key` module from SRML

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#1991]
The upgrade-key module is an historical artifact and should be removed from Substrate.

The sudo module does everything that this module would do

Need to make sure that no downstream dependencies need upgrade-key, like Substrate Node Template or any tutorials

**Comment by adamdossa** [comment]
FYI - https://docs.substrate.dev/docs/substrate-runtime-recipes still references the upgradeKey when talking about updating the runtime (in the screenshot)
