### ISSUE TITLE
Panic on sync process: database missing key

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#1994]
According to https://github.com/airalab/substrate-node-robonomics/issues/13.

Bug looks like something broken in pruning procedure because `--pruning archive` fix it.

**Reproducing:**

* substrate rev `4cbda5d31a52555f3f241a7ba8065e8b5cb887f1`

Just sync on clean db with enabled `staking`, `grandpa-finality` and `finality-tracker`.

**Comment by xlc** [comment]
Duplicates #1733
