### ISSUE TITLE
WASM build error with ZK libraries

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#2004]
I'm working to integrate some elliptic curve operations in a runtime module [here](https://github.com/hicommonwealth/edgeware-node/tree/drew.merkle/modules/edge-merkletree) and cannot build due to these odd errors. I've introduced the following libraries,
1. https://github.com/matter-labs/sapling-crypto/
2. https://github.com/matter-labs/bellman/

This should compile down to WASM as it works outside of substrate, however I'm unaware of what would restrict this from compiling.
```
error[E0152]: duplicate lang item found: `panic_impl`.
  --> /Users/drewstone/.cargo/git/checkouts/substrate-7e08433d4c370a21/b32b071/core/sr-io/src/../without_std.rs:30:1
   |
30 | / pub fn panic(info: &PanicInfo) -> ! {
31 | |     unsafe {
32 | |         #[cfg(feature = "wasm-nice-panic-message")]
33 | |         {
...  |
46 | |     }
47 | | }
   | |_^
   |
   = note: first defined in crate `std`.

error[E0152]: duplicate lang item found: `oom`.
  --> /Users/drewstone/.cargo/git/checkouts/substrate-7e08433d4c370a21/b32b071/core/sr-io/src/../without_std.rs:50:1
   |
50 | / pub extern fn oom(_: ::core::alloc::Layout) -> ! {
51 | |     static OOM_MSG: &str = "Runtime memory exhausted. Aborting";
52 | |
53 | |     unsafe {
...  |
56 | |     }
57 | | }
   | |_^
   |
   = note: first defined in crate `std`.

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0152`.
```

**Comment by bkchr** [comment]
Hey, both libraries do not support `no_std`, so this will not work. The error just tells you that some items are defined multiple times. If you see such an error while compiling for WASM, you can be 90% sure that something pulls in std, but nothing should pull in std while compiling for `no_std`.

**Comment by burdges** [comment]
See https://github.com/zkcrypto/bellman/pull/32

**Comment by bkchr** [comment]
Even with the linked pr, it will not work on WASM.

**Comment by arthurgreef** [comment]
I tried adding Dalek bulletproofs to substrate. The bulletproof library can be built with --no-default-features and --features alloc. I can also build the library with substrate. If, however, I reference the library from an srml model lib.rs file I get the error the errors in this post. I'm not sure how this happens when wasm is in the picture. Any ideas? Thanks.

**Comment by burdges** [comment]
We shall depend upon at least the verification code from these libraries, and stronger scalability will require proovers too, so actually fixing this sounds pretty important.  Ideally, all these libraries could become core+alloc but if not then we'll need some hacked std. 

In any case, these errors originate form sr-io which includes primitives which includes numerous crypto crates: https://github.com/paritytech/substrate/blob/master/core/primitives/Cargo.toml  It's plausible the error originate in some memory zeroing crate's attempt to trick the compiler via `#[no_mangle]` or similar.
