### ISSUE TITLE
Use serde for network messages

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#2011]
Instead of `parity-codec`, we should use for example CBOR.
However this is a networking breaking change.
cc #1518

**Comment by gavofyork** [comment]
could do with further explanation.

serdee should **NOT** be used for anything touching substrate-protocol-level elements such as transactions, headers and blocks.

**Comment by tomaka** [comment]
Sorry, I wrote that in a rush during the meeting.

The idea is to use `Serialize`/`Deserialize` on [this struct](https://github.com/paritytech/substrate/blob/91fa6594fe734ae41a2019cbc277cd175e7e91b9/core/network/src/message.rs#L175) instead of `Encode`/`Decode`, but not touch the traits of anything outside of the `message.rs` file.

**Comment by gavofyork** [comment]
that looks problematic since it includes high-level protocol elements by type (`Header`, `Extrinsic`, ...). they should not be encoded by serde.

**Comment by DemiMarie-parity** [comment]
> could do with further explanation.
> 
> serdee should **NOT** be used for anything touching substrate-protocol-level elements such as transactions, headers and blocks.

Is that because it lacks backwards-compatibility?

**Comment by tomaka** [comment]
> Is that because it lacks backwards-compatibility?

I think it's because we don't want to have extra conversions between the network and the runtime.
