### ISSUE TITLE
documentation: transaction lifetime sequence diagram

### ISSUE THREAD

**Issue by brenzi** [paritytech/substrate#2013]
I propose a documentation diagram to understand what happens with a transaction within substrate.

After a discussion below #1789 I'll be adding single diagrams per issue over here.

![tx-seq](https://github.com/brenzi/substrate-doc/raw/master/transaction-sequence-diagram.svg?sanitize=true)

please consider using this diagram for substrate docs.

**Comment by brenzi** [comment]
improves #578

**Comment by brenzi** [comment]
@shawntabrizi is this a good way to contribute images?
As draw.io now supports github, it's quite easy for me to do updates and the diagram in the OP will stay up to date

**Comment by shawntabrizi** [comment]
@brenzi as I mentioned in the PR, I actually think opening these kinds of issues/prs makes more sense here: https://github.com/paritytech/substrate-developer-hub/issues

I think the only documentation that would go through the main substrate repo would be things embedded directly in the code. However our external documentation effort around substrate will happen in the developer-hub repo

**Comment by brenzi** [comment]
oh, I missed that, sorry. opened an identical issue over there, will close this one
https://github.com/paritytech/substrate-developer-hub/issues/51
