### ISSUE TITLE
Any example about writing and deploying a substrate smart contract?

### ISSUE THREAD

**Issue by hliu4atomos** [paritytech/substrate#2036]
We tried a lot but failed to deploy our smart contract on substrate. I think any document or examples will be very helpful. 

Much appreciated!

**Comment by bkchr** [comment]
Please stop spamming the same issue. You got your answer in the last issue.

**Comment by hliu4atomos** [comment]
Did you really check that issue? You just duplicate my last issue to a issue which will be never fixed.
Is this your style you guys to resolve the issue?

**Comment by pepyakin** [comment]
I think Basti is right, duplication of the same issue is not helpful for us. I marked it as duplicate for the sake of linkness, so whenever we get documentation we could either post it in one place or crawl to every linked issue. I'm very sorry to hear that you think that that issue will never be fixed.

I'm gonna go ahead an at least lock this issue, and may be even delete this. However, you are welcome to ask further questions in the original issue.
