### ISSUE TITLE
libp2p expect panic

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#2049]
====================

stack backtrace:
0: substrate_panic_handler::set::{{closure}}::hd7e4a3830a237daf (0x55f636c03d6f)
1: rust_panic_with_hook (0x55f636ce0a38)
at src/libstd/panicking.rs:482
2: continue_panic_fmt (0x55f636ce04d1)
at src/libstd/panicking.rs:385
3: rust_begin_unwind (0x55f636ce03b5)
4: panic_fmt (0x55f636cfad4c)
at src/libcore/panicking.rs:85
5: expect_failed (0x55f636cfadb6)
at src/libcore/option.rs:1038
6: <substrate_network_libp2p::service_task::Service as futures::stream::Stream>::poll::hca519c8f96cb6cf1 (0x55f635f4ba9f)
7: <futures::stream::for_each::ForEach<S, F, U> as futures::future::Future>::poll::h1bae8aebb08d4357 (0x55f635eb891a)
8: <futures::future::select_all::SelectAll as futures::future::Future>::poll::hbcbc4178b5e6571a (0x55f635d88bee)
9: <futures::future::chain::Chain<A, B, C>>::poll::h8df7a57853571ee8 (0x55f6362cbaf6)
10: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::he9bbe2586c23617b (0x55f63600cd90)
11: <futures::future::select::Select<A, B> as futures::future::Future>::poll::h088120de04fa9136 (0x55f63627090d)
12: <futures::future::map::Map<A, F> as futures::future::Future>::poll::hbf121af41270b64c (0x55f6360f31e9)
13: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h7a9910e0c8c35dc0 (0x55f636009377)
14: <futures::future::chain::Chain<A, B, C>>::poll::h990174b916626818 (0x55f6362cccca)
15: futures::task_impl::std::set::h6e75e009651eef20 (0x55f636caa321)
16: <futures::task_impl::Spawn>::poll_future_notify::h88f1273db308d59f (0x55f636caaf45)
17: std::panicking::try::do_call::hb5fb0bc4f1f74968 (0x55f636caf380)
18: __rust_maybe_catch_panic (0x55f636ce6939)
at src/libpanic_unwind/lib.rs:87
19: tokio_threadpool::task::Task::run::hba1413f8b67bf85f (0x55f636cafb8f)
20: tokio_threadpool::worker::Worker::run_task::hcc66a6ad6d214ada (0x55f636ca6c04)
21: tokio_threadpool::worker::Worker::run::hcd9ffc80880fe5b1 (0x55f636ca60fd)
22: <std::thread::local::LocalKey>::with::h7b8226d6091e2b24 (0x55f636c8c10d)
23: <std::thread::local::LocalKey>::with::h380ddfc72c1aa269 (0x55f636c8bdce)
24: <std::thread::local::LocalKey>::with::h60dfd11923064a92 (0x55f636c8bf5a)
25: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h29d794483fe27199 (0x55f636c8cd5d)
26: <std::thread::local::LocalKey>::with::h1f73543daaa73608 (0x55f636cae322)
27: <std::thread::local::LocalKey>::with::h445d250d8dd061d5 (0x55f636cae849)
28: std::sys_common::backtrace::__rust_begin_short_backtrace::h1b8b18417ac1e0d1 (0x55f636cb0d10)
29: std::panicking::try::do_call::hbaddd16c4fd510db (0x55f636caf3cb)
30: __rust_maybe_catch_panic (0x55f636ce6939)
at src/libpanic_unwind/lib.rs:87
31: <F as alloc::boxed::FnBox>::call_box::hb2995b33847e44f3 (0x55f636ca8d1f)
32: call_once<(),()> (0x55f636ce5ccd)
at /rustc/633d75ac17fa1a1bdaf5923895e6d5b7f3040c92/src/liballoc/boxed.rs:749
start_thread
at src/libstd/sys_common/thread.rs:14
thread_start
at src/libstd/sys/unix/thread.rs:81
33: start_thread (0x7f3416c216b9)
34: clone (0x7f341674141c)
35: (0x0)

Thread 'libp2p-0' panicked at 'index_by_id is always kept in sync with the state of the behaviour', src/libcore/option.rs:1038

Whether the libp2p panic should allow the node to continue execution instead of shutting down the process？

**Comment by gguoss** [comment]
https://github.com/paritytech/substrate/blob/32f064e2b09d8bb4d9b56fb6c563a9b03f07730d/core/network-libp2p/src/service_task.rs#L408

use handle expect function replace expect.

**Comment by bkchr** [comment]
@tomaka ping.

**Comment by tomaka** [comment]
Well, this code just got reworked and doesn't exist anymore, so I guess I'll close this.
