### ISSUE TITLE
Make Aura consensus generic over key type

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#2058]
Right now it only supports ed25519, but sr25519 or other signature schemes should be supported as well.

`start_aura` is dependent on a `B: Block` type parameter, so extending it with a `Key` parameter where `Key: Pair<Public=AuthorityIdFor<B>>` should be possible.

**Comment by DemiMarie-parity** [comment]
Fixed by #

**Comment by DemiMarie-parity** [comment]
Fixed.

**Comment by rphmeier** [comment]
@DemiMarie-parity Note that you can write `Fixes #X` in a PR name or description and GitHub will automatically close it.
