### ISSUE TITLE
Pattern not covered in substrate-trie

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#2069]
While building with `rustc-1.32` get error:
```
   Compiling substrate-trie v0.4.0 (https://github.com/paritytech/substrate#d270ae4f)
   Compiling fork-tree v0.1.0 (https://github.com/paritytech/substrate#d270ae4f)
   Compiling finality-grandpa v0.6.0
error[E0004]: non-exhaustive patterns: `_` not covered
  --> /tmp/nix-build-substrate-node-robonomics-0.9.0.drv-0/substrate-node-robonomics-0.9.0-vendor/substrate-trie/src/node_header.rs:60:14
   |
60 |         Some(match input.read_byte()? {
   |                    ^^^^^^^^^^^^^^^^^^ pattern `_` not covered

error: aborting due to previous error
```

`rustc-1.32` isn't so fresh but used in many linux distrubutions, when it isn't so hard please fix it.

**Comment by rphmeier** [comment]
We're targeting stable Rust and, given that Substrate is itself under heavy development, it's unlikely that this will change in the near future.

**Comment by JoshOrndorff** [comment]
If you're new to rust (like me) checkout https://rustup.rs

Just had to run `rustup update` and this build error was solved.
