### ISSUE TITLE
DigestItem refactoring for swappable consensus

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#2083]
Related to #1365 

Right now, the `DigestItem::Seal` in `sr-primitives` is very Aura-specific. As part of [Swappable Consensus · Issue #1304 · paritytech/substrate · GitHub](https://github.com/paritytech/substrate/issues/1304) we are moving a lot of stuff to be based on `ConsensusEngineId`s. For BABE this would be the array `['b'B', b'A', b'B', b'E']`.

Currently `DigestItem::<SealSignature>::Seal(u64, SealSignature)`

We'd like it to be defined as `DigestItem::Seal(ConsensusEngineId, Vec<u8>)`. This will lead to the `Signature` parameter being removed from `DigestItem` and all containing structs (this is a win!). 

Unfortunately, that's not backwards compatible with the old Aura implementation and will break things.

To make it backwards compatible, we will originally add this as `DigestItem::Consensus(ConsensusEngineId, Vec<u8>)` and write a `fn start_aura2`.

**Comment by DemiMarie-parity** [comment]
@rphmeier does this still depend on #1365?

**Comment by rphmeier** [comment]
No, I don't think so. Removed that from the issue description.
