### ISSUE TITLE
What is `contract_fee`?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2112]
https://github.com/paritytech/substrate/blob/a30d6a1a898d06ec8a6ca955eefffa1d697f967e/node/cli/src/chain_spec.rs#L153

What is this `contract_fee` here?

Reading #2045 doesn't help much

```
//! * `contract_fee` - Gets the fee required to create a contract
//! 
//! * `call_base_fee` - Gets the fee required for a call into a contract.
//! 
//! * `create_base_fee` - Gets the fee required for a create of a contract. 
```

What is the difference between `contract_fee` and `create_base_fee`?

And what are the units of those fields? They are in `Balance` or `Gas`?

I think simply update documentation is not enough, the field names needs improving.

**Comment by pepyakin** [comment]
Good questions!

- `contract_fee` - is a fee charged when a new contract account is instantiated (e.g. by invoking an `ext_create` (or `ext_instantiate` in the future) function) and happens at the transfer time and transfer is a result of either of a `call` or `create/instantiate`. The fee is denominated in balance units, but charged in gas, so some lossy conversion takes place. This is an abstraction defined in the contracts module.
- there are two other related parameters `creation_fee` and `transfer_fee`. The former is charged when a simple account is created. And the latter one is charged when a simple transfer is happening. These two are not a part of the contracts module but are part of the balances module.
- `call_base_fee` and `create_base_fee` are basically a price which is denominated in gas units that is taken whenever `call` or `create/instantiate` function is invoked (including the first top-level call).

cc @nczhu

**Comment by xlc** [comment]
Am I right that when `call` or `create/instantiate` function is invoked, `call_base_fee` is always charged. `contract_fee` may also be charged if a new contract account is instantiated. 
Then in what case may result `call_base_fee` get charged but not `contract_fee`? When the contract account instantiation failed?

Why `contract_fee` is denominated in balance units instead of gas unit? The lossy conversion will complicate the gas fee estimation and gas fee breakdown.

Imaging someone is developing a fee estimation tool.
This tool should able to present something like this:

Base fee: 100
Gas price: 1
Contract creation fee: 50
Gas usage (user input or result of local estimation): 50
Total fee charged: 100 + 1 * 50 + 50 = 200

**Comment by nczhu** [comment]
I think reading through /exe.rs could help. My understanding of fees is: 

1. When you instantiate (create) a new smart-contract: 
    1.1. Pay a base fee `create_base_fee`. (then the contract dest address is determined)
    1.2. Pay a contract account instantiation fee `contract_fee` (the associated acct to your smart-contract)
    1.3. Pay any associated Balance transfer fees [see 2.2] (actual payment into the smart contract)

2. When you make a call (either to transfer funds, and/or a call into a smart-contract): 
    2.1. Pay a base call fee `call_base_fee`
    2.2 _If the recipient account doesn't exist yet_: pay a account `creation_fee` (this is just a standard account, not a smart-contract associated account)
    2.2 _If the recipient account does exist_: just pay a standard `transfer_fee`

_I may have omitted edge cases here._ 

Agree on the potential renaming, but as I understand, this module is still under development and the thinking around fees is in flux. I'm going to wait for major design pieces to be decided before making the module docs more detailed :)
