### ISSUE TITLE
GRANDPA: Equivocation slashing for the current set

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#2129]
As a first step towards #1112 

Add a call type to the `srml-grandpa` module where peers can provide two votes that are _equivocating_. This will check that both are of the same type, signed by the same validator , and are not equivalent. 

If so, it will not currently do anything. After #1699 we can slash for it.

the `prevote_equivocation` and `precommit_equivocation` functions on `Environment` should trigger this transaction to be sent. 

cc: @andresilva

**Comment by andresilva** [comment]
Fixed in #3868.
