### ISSUE TITLE
Each node clock is not aligned

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#2131]
<img width="1545" alt="WeChatbe81e9007d92c29b605ebfdf9d2aad91" src="https://user-images.githubusercontent.com/9285062/55127608-b1450b80-514b-11e9-9521-e70084a12ac2.png">

Reason: The computer local time is basically timed by its own hardware chip, and occasionally there is a big error with the NTP time. 
Of course, you can solve the time consistency by restarting the computer or manually setting NTP.
But is there a node time consistency alignment protocol for the p2p layer?

**Comment by bkchr** [comment]
A timeout does not use NTP at all, it just use a monotonically increasing clock. So, you can have set any time you want on your PC.
