### ISSUE TITLE
Check a size of a table and maybe account it at instantiation time.

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2173]
At present, we check for declared memories in a contract wasm module.

https://github.com/paritytech/substrate/blob/623de51806441558512d003732483a0209d78040/srml/contract/src/wasm/prepare.rs#L51-L57

This is important to check because otherwise wasm VM might happily allocate (or at least reserve) the specified amount memory at the instantiation time and we won't be able to prevent that in general (unless we have full control over VM and specify all the params for instantiation which we are not doing here).

However, we don't do that for tables at the moment where in theory a contract can request a very big table.

**Comment by jimpo** [comment]
This seems straightforward to implement. But we should decide whether to cap the table size or charge gas for it. Capping the size at 2^18 elements (1 MiB) seems easy and reasonable.

**Comment by pepyakin** [comment]
I am happy with capping although I think we can make a way lower limit. 64k should be enough for everyone.
