### ISSUE TITLE
Telemetry sometimes goes offline and doesn't come back

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#2189]
Not sure why, but one of my nodes (Linux) that's a local network (i.e. behind NAT) will disappear from telemetry and not come back until i restart it.

It doesn't happen with other nodes, so first thing should be introducing appropriate logging to ascertain what's going on with the machine that it is happening on.

**Comment by tomaka** [comment]
Would need to be tested again after #2812.
If that reproduces, the `telemetry` logs should be detailed enough to understand what is going on.

**Comment by tomaka** [comment]
Triaging: I'm going to close this, assuming it doesn't happen anymore (which is likely the case, as the code got rewritten from scratch).
