### ISSUE TITLE
Limit the size of a stored value in the storage

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2192]
A contract can store a value of arbitrary size in its KV storage. Theoretically, it is possible to store a value that won't be possible to load, assuming the possibility of decreasing the block gas limit.

We might want to introduce a limit for the size of a strorage value. For that, we can add a field that holds the size limit. On each call to `set_storage`, it will check the length of the storage value and if it exceeds the limit a trap will be generated.

**Comment by jimpo** [comment]
Should this be a module configuration parameter (like changeable through governance) or just a hard-coded constant?

**Comment by pepyakin** [comment]
That's a great question. I think after the recent migration to hard-coded constants the hard-coded constants are more preferrable now.
