### ISSUE TITLE
Fuzz the peerset manager to test coherency

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#2200]
Write a test for the `peerset` crate that uses the API in a random way, and verifies if the output is coherent (eg. if the peerset doesn't send "dropped" twice in a row for the same node).

cc @debris

**Comment by tomaka** [comment]
List of things to verify in the output:

- "Connect" must only be emitted for a node for which a "Drop" was emitted earlier, or if it is the first time we emit an event about this node. Two "Connect" about the same node in a row is invalid, and a "Connect" that follows an "Accept" for that same node is invalid.
- "Drop" must only be emitted for a node for which a "Connect" or "Accept" was previously emitted. Two "Drop" in a row about the same node is invalid.
- "Accept" or "Reject" must not be emitted about a node for which we emitted a "Connect" earlier.

Please note that the point of the test is not just to be a basic usage, but to try the weirdest situations imaginable.

**Comment by gterzian** [comment]
Ok I'll take this on...

**Comment by tomaka** [comment]
Triage: this is done.
