### ISSUE TITLE
Full and Light share database

### ISSUE THREAD

**Issue by niklasad1** [paritytech/substrate#2204]
The following doesn't work:

```bash 
$ cargo run --release \-- --name niklasad1
$ cargo run --release \-- --name niklasad1 --light
Error: Error(Client(Backend("Unexpected database type. Expected: light")), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

This makes it impossible to sync light and full on the same chain without removing the database or changing `base--path` ?!

**Comment by pepyakin** [comment]
cc @arkpar / @svyatonik

**Comment by tomaka** [comment]
Should we do it the same way as parity-ethereum and have two different databases?

**Comment by xlc** [comment]
We are having this issue while implementing our desktop node client. Our solution is use `--base-path` to make sure full mode and light mode are not having a same base path. But it will be better if Substrate can handle this logic.
