### ISSUE TITLE
_genesis_phantom_data required for unknown reason

### ISSUE THREAD

**Issue by mnaamani** [paritytech/substrate#2219]
using substrate v1.0.0rc1 I'm encountering an issue in one of my runtime modules, that is forcing me to have to provide a `_genesis_phantom_data` in the genesis config.

Chainspec:
https://github.com/Joystream/substrate-node-joystream/blob/2196301d63df55872f9efc446a13969fd915b4c3/src/chain_spec.rs#L264

Runtime module:
https://github.com/mnaamani/substrate-runtime-joystream/blob/80bd88b4ae3bd5624534d5b38cdc1a1ed7a6d917/src/roles/actors.rs#L100

```
missing field `_genesis_phantom_data` in initializer of `joystream_node_runtime::roles::actors::GenesisConfig<joystream_node_runtime::Runtime>`

missing `_genesis_phantom_data`rustc(E0063)
```
cc:
@bkchr

**Comment by bkchr** [comment]
After a first look, the generic parameter is used and so we should not add the phantom field.

**Comment by mnaamani** [comment]
Was this fixed perhaps in https://github.com/paritytech/substrate/commit/51e7b7761591143c0fd520fb9cc6849fd4b120c5

**Comment by bkchr** [comment]
No, this is for event and not storage. And it does something different ^^

**Comment by thiolliere** [comment]
We currently have GenesisConfig generic over T the trait. I'm not sure it is mandatory though.

But in your case GenesisConfig doesn't use T in its fields (which are u64 and bool) so we add a fields to make use of it through a PhantomData.

We may want to generate not generic GenericConfig here ?

**Comment by bkchr** [comment]
I already started working on this. We really need to eliminate this `PhantomData` and I have some ideas on how to do this. We should hopefully be able to work around this fully.
