### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [paritytech/substrate#2237]
Hello! I really like this project and I'd like to contribute to it by designing a logo. If you'd want that too, please let me know if there are any specific things you'd want this logo to represent or to have, and if you don't have any I'll just implement my own ideas. Looking forward to hearing from you :)

**Comment by shawntabrizi** [comment]
@newfinal100 Thanks for looking to contribute to Substrate, but at this moment we already have a logo we are pretty happy with :)

We can certainly keep you in mind if there are other such tasks where open source graphic designers can help!
