### ISSUE TITLE
broken build when running curl https://getsubstrate.io -sSf | bash 

### ISSUE THREAD

**Issue by bitsrules** [paritytech/substrate#2251]
I just ran ```curl https://getsubstrate.io -sSf | bash ```
on a fresh Ubuntu machine but got a build error:

```
   Compiling node-executor v1.0.0 (/tmp/tmp.OVsQx366QL/node/executor)
error: couldn't read node/executor/src/../../runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm: No such file or directory (os error 2)                                                                     
  --> node/executor/src/lib.rs:26:100
   |
26 | native_executor_instance!(pub Executor, node_runtime::api::dispatch, node_runtime::native_version, include_bytes!("../../runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm"));
   |                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          

error: aborting due to previous error

error: failed to compile `substrate v1.0.0 (/tmp/tmp.OVsQx366QL)`, intermediate artifacts can be found at `/tmp/tmp.OVsQx366QL/target`

Caused by:
  Could not compile `node-executor`.
```

**Comment by xlc** [comment]
you need to run `./scripts/build.sh` to build wasm files first

**Comment by bitsrules** [comment]
@xlc Is the best way to fix the script so it does that automatically?

**Comment by xlc** [comment]
I don't know what is the best way to fix this issue.
Better to wait someone from Parity to answer this.

**Comment by bkchr** [comment]
Cc @shawntabrizi shouldn't this be fixed?

**Comment by shawntabrizi** [comment]
@xlc @bitsrules the code should be there to solve this issue:

```
function install_substrate {
	g=`mktemp -d`
	git clone https://github.com/paritytech/substrate $g
	pushd $g
	./scripts/build.sh
	cargo install --force --path . substrate
	popd
}
```

Would be good to see if others can reproduce the error and provide the full output logs of the install

**Comment by shawntabrizi** [comment]
Talking to @bitsrules offline, the error happens here when trying to build the wasm:

```
*** Building wasm binaries in core/executor/wasm
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
```

This means rust nightly was not installed? We need to add some extra commands to make sure this happens?

**Comment by shawntabrizi** [comment]
Seems that I could run `init.sh` before running `build.sh`, will open a PR, but would like someone else to help me confirm that this will solve the issue.

**Comment by bitsrules** [comment]
This fixed the issue, the script succeeds without an build errors. 
To verify this I ran it on a new fresh Debian 18.04 vm on GCP.
Thank you @shawntabrizi !
