### ISSUE TITLE
RPC to query nonce value includes one in the tx pool

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2263]
It is possible to query the nonce value for an account but it does not consider the transactions in the transaction pool. This means the client side have to implement nonce method to take account of sent but unconfirmed transactions.

It will be better if there is a RPC method give highest nonce value including the one in the transaction queue.

Something similar to `web3.eth.getTransactionCount("0xf82e...", "pending");`

**Comment by tomusdrw** [comment]
`nonce` is specific to a particular runtime, transaction pool have no notion of `nonce` or `sender` whatsoever.

I think this will rather be a chain-specific RPC (which we currently don't support yet), I wouldn't expect anything like that in core substrate though.

**Comment by xlc** [comment]
I see. How can I add chain specific RPC? It will be good if there is some example in node-template project

**Comment by xlc** [comment]
I see. When can I expect to have chain specific RPC? If it is unlikely to happen in next quarter, I will need to find a solution myself for my chain.

**Comment by pepyakin** [comment]
Theoretically you can have chain-specific RPC right now (although there is no first-class support). You can use the existing `state_call` RPC method to call arbitrary functions on runtime. The only requirement is the functions have to have a signature of form: `(&[u8]) -> Vec<u8>` (modulo FFI specifics).

As soon as you have it, you can call the runtime. Theoretically, you could provide APIs for parsing extrinsics there.
