### ISSUE TITLE
Ability to create custom getters

### ISSUE THREAD

**Issue by adamdossa** [paritytech/substrate#2271]
In the `decl_storage!` block it is possible to specify a getter function, which is then exposed over the JSON RPC API.

The documentation says that functions in the modules public "call" list are either signed, root or inherents - but it seems like getters introduce another class (since they can be called externally without signing the transaction).

Is it possible to create these types of functions directly? This would be similar to a `view` function in Solidity - for example I may want to take two values from storage, sum them, and return the value (to an external caller).

**Comment by adamdossa** [comment]
Motivation for this is to have these functions exposed over the RPC API (similar to the way getters are, without needing to provide an origin).

**Comment by bkchr** [comment]
We don't expose any function defined in `decl_storage! ` directly over the Json Rpc Api. We expose a Rpc call to access the storage and the js app can build the key it requires out of Metadata.

We currently don't support extending the Rpc api in a simple way. You could create your own runtime api with `decl_runtime_apis!` and call this runtime api from your Rpc call.
