### ISSUE TITLE
Update node-template-release script to pin v1.0 instead of a commit

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2275]
It should pin to v1.0 tag when it is available.
Can we have it pin to 1.0 branch for now? Or what is the best way to update substrate version for generated project?

**Comment by bkchr** [comment]
@gabreal can we have the script run for the v1.0 branch and uploaded to a path just for v1.0?

**Comment by gabreal** [comment]
Every tagged release on the v1.0 branch will have its node template released according to the tag e.g. https://releases.parity.io/substrate/x86_64-ubuntu:xenial/v1.0.0rc1/substrate-node-template.tar.gz

**Comment by xlc** [comment]
No need substrate side change (other than make new tag when 1.0 is out) https://github.com/paritytech/substrate-up/issues/28

**Comment by xlc** [comment]
It seems like http://releases.parity.io/substrate/x86_64-ubuntu:xenial/latest/substrate-node-template.tar.gz is point to https://github.com/paritytech/substrate/releases/tag/v1.0.0rc1 which doesn't have https://github.com/paritytech/substrate/pull/2356 and causing issue with latest substrate-up script
Can someone make another v1.0 rc tag or make a v1.0 branch release for node template?

**Comment by gabreal** [comment]
This is caused by the fact that the docker os has changed in the master branch to debian:stretch (from ubuntu:xenial in v1.0). Therefore latest builds of the master branch are published here: http://releases.parity.io/substrate/x86_64-debian:stretch/latest/substrate-node-template.tar.gz

**Comment by xlc** [comment]
Closed by #2495
