### ISSUE TITLE
"network_state" value in telemetry is string, should be json

### ISSUE THREAD

**Issue by mattrutherford** [paritytech/substrate#2300]
`network_state` value in telemetry is string, it should be json, in `"msg":"system.interval"`

Need to check whether this applies to any other values in other messages.

eg: 

```json
"network_state":"{\"peerId\":\"QmaGMX8QCeeiq79YiHc7ndR2npwbk2HdcmFFkYWLBHmznu\",\"listenedAddresses\":[\"/ip4/0.0.0.0/tcp/30333\"],\"externalAddresses\":[\
...
```

**Comment by bkchr** [comment]
Yeah, we just need to drop the `serde_json::to_string`.
