### ISSUE TITLE
Parameterize Minimum 'Stakable' Balance.

### ISSUE THREAD

**Issue by Kianenigma** [paritytech/substrate#2301]
since balances in Polkadot (and _substrate node_) are a u128 value, in which only the middle 64 bit is an actual value (lower 32 bits = dust ---- higher 32 bits = reserved zeros) a shift by 32 was hardcoded into the staking module a while back to properly format the balances and use them as numeric values.

This (to some extent) problematic shift by 32 is configurable via a config type in `Staking::Trait` but pre-compiled, of course, as a part of the runtime. So the argument would be that anyone building a custom substrate chain is free to change it as they want.
 
But this slightly bad for a dev chain:
A normal dev chain in which the user might actually not be interested in any of this but rather to quickly run a chain and be happy with an account with just 10 units of balance (cc @cmichi).  We've had some reports that validators in the testnet/dev-chains are not earning rewards, all because they had a balance less than 2^32, which is equal to zero from the perspective of the staking module.

What I propose is:

- The fact that this particular 128 bit structure of the default balance is hidden is not good. If it is only relevant in Staking, then it is arguable. Otherwise, _it should be parameterized_ (either when the runtime is built or via genesis --e.g. users defining that any balance less than `N` bits is considered to be dust). 
  - Consequently, this assertion in this [draft PR](https://github.com/paritytech/substrate/pull/2302/files#diff-b5a024b4f4ae96b0bfc0681acae56709R521) can safely stay but the bound should be the __aforementioned configured value__, not hardcoded 32. 
  - Moreover, the `CurrencyToVote` (the object that actually shifts the balances) can work based on this config value by default. Of course, the user is still free to change it altogether, this is the one which is shipped in `substrate/node/runtime` by default. 

I am not sure, but if this actually should be a configurable value, isn't it related to `balances::existential_deposit`? The new config could, for instance, be called `staking::minimum_stakable_deposit`?

- If this goes through at least the polkadotjs/apps should show a gentle warning if any balance less than the aforementioned configured value is being staked. 

Unlike what I originally imaged, with such config we actually don't really have to move the shift-by-32 exclusively to the polkadot repo; it is still part of _substrate node_ and it will now no longer annoy the dev chain.

As mentioned in the title, whatever comes out of this issue should also be documented properly (if it is a valid point and gets implemented eventually).

People that might be interested and have valuable opinions: @gavofyork @bkchr @shawntabrizi
PR: https://github.com/paritytech/substrate/pull/2302

**Comment by xlc** [comment]
What is the reason that staking module cannot work with u128 balance value directly and it needs to reduce it down to u64?

**Comment by Kianenigma** [comment]
> What is the reason that staking module cannot work with u128 balance value directly and it needs to reduce it down to u64?

That would be slightly different in terms of 'why' but indeed related. 

I think it would be the combination of what I wrote above: 
1. how __literally__ only 64 bit of the designated u128 is a real value, rest is worthless
2. And: at the moment it also helps us computationally in the election but this will be subject to change in the near future most likely. If the balance is somehow reduced to u64 then computation in u128 is safe w.r.t. multiplication.

**Comment by xlc** [comment]
Make sense.

In that case I would like to propose make `CurrencyToVote` come from balances module, and balances can provides a genesis config to specify which 64 bits are relevant. In staging net, it will be the middle 64 bits, in dev net, it can be the low 64 bits.

It is really the balances module to determine the relevant bits range, not staking module.
