### ISSUE TITLE
A way to expose limited set of RPC methods

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2303]
Is it possible to only expose a limited set of RPC methods for diagnosis purpose only? Such like sync progress, block height, health, etc.

Those RPC should be very safe and readonly and cannot be (easily) abused so they can be open to public behind a general rate limiting API gateway.

RPC like submit transaction and query historical state have a larger attack surface so we would like to close them by default.

**Comment by bkchr** [comment]
CC @tomusdrw @ascjones

**Comment by tomusdrw** [comment]
I'd rather invest some time to make https://github.com/tomusdrw/jsonrpc-proxy more production ready than to build that into substrate. @xlc is that something that would work for you?

The permissioning configuration example can be found here:
https://github.com/tomusdrw/jsonrpc-proxy/blob/master/examples/permissions.json

Basically it's just the matter of running the proxy + pointing to the configuration file.

**Comment by xlc** [comment]
Yes an easy configurable json rpc proxy will work too.
