### ISSUE TITLE
Limit of number of transactions in a block

### ISSUE THREAD

**Issue by maxsam4** [paritytech/substrate#2308]
As per my tests, it seems like the default limit is only 257 transactions/limit. 
I tested it using the below script
```
// Required imports
// @ts-check
const { ApiPromise, WsProvider } = require('@polkadot/api');
const { Keyring } = require('@polkadot/keyring');
const BN = require('bn.js');

const BOB = '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty';

async function main () {
  const provider = new WsProvider('ws://127.0.0.1:9944');
  const api = await ApiPromise.create(provider);
  const keyring = new Keyring();
  const test5 = keyring.addFromMnemonic('enhance embody priority wise tree pig trash reform drum sure zebra canoe', {"name": "test4"}, "sr25519");
  let rawNonce = await api.query.system.accountNonce(keyring.getPairs()[0].address());
  let nonce = new BN(rawNonce.toString());
  for (let i = 0; i < 260; i++) {
    const transfer = api.tx.balances.transfer(BOB, 100000);
    transfer.signAndSend(test5, { nonce });
    nonce = nonce.add(new BN(1));
  }
  const transfer = api.tx.balances.transfer(BOB, 100000);
  await transfer.signAndSend(test5, { nonce });
  console.timeEnd('test');
 // 4 tx will fail bcz one block can only have 257 tx.
}

main().catch(console.error).then(() => process.exit());
```

This seems like a bug somewhere. 256 would have been a natural limit but 257 is just weird.
Error shown by the script is
```
RPC-CORE: submitExtrinsic (extrinsic: Extrinsic): Hash:: 1011: Unknown Transaction Validity (2)
ExtError: submitExtrinsic (extrinsic: Extrinsic): Hash:: 1011: Unknown Transaction Validity (2)
```
Error in node logs is
```
Extrinsic invalid: 0x1957c4f88ebd8b21ba0a95289062b390c6e8b2e199fad532530c25e7f110f417
```

**Comment by bkchr** [comment]
CC @tomusdrw

**Comment by tomusdrw** [comment]
It's not an artificial limit, it's a property of our runtime, so I'd say it's expected behavior
https://github.com/paritytech/substrate/blob/b51f8f2a9d420ad3b507d57f4f4a56e33b2d8ead/srml/executive/src/lib.rs#L318-L320

Note that custom runtimes are free to implement something else, we could also allow parameterisation of this.

Are there any valid uses cases for increasing this value? What' the reasonable limit in your opinion?

**Comment by maxsam4** [comment]
@tomusdrw That explains it, thanks.

I don't have any specific use case right now but I wouldn't want to put in limits that are not needed. Can you please tell me why this limit was put in place?

The only reason I can think of is to prevent spam but I don't think this limit helps. The attacker can just use multiple accounts as this limit seems to be account specific from the code.

**Comment by tomusdrw** [comment]
@maxsam4 I guess the limit was mostly introduced to prevent `requires` set from growing in an unbounded manner, that said `requires` shouldn't really be a vector at all - it's fine if we only require a transaction with `nonce-1` and the rest is required transitively. I'll try to prep a PR to remove the limit (or at least make it cusomisable) and fix the `requires` vector.
