### ISSUE TITLE
srml-contract: ext_set_code_hash

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2347]
We could introduce some mechanism that allows some form of upgradability, a-la "make a call to self but with the specified `code_hash`" and build upgrading mechanism on top of this or similar indirect mechanism.

However, it might be better to just provide a mechanism that would allow changing the `code_hash` of the calling contract directly, instead of providing second-class mechanism. It will be up to users to verify if the contract's code can change but in more direct manner.

This feature might be related to 🦄dynamic linking, since sometimes contracts would want to change libraries `code_hash`es.

Code hash querying (#2346) is also related

**Comment by pepyakin** [comment]
There is a subtle interaction with removal of a contract to take into account. 

`instantiation` derives the address of a creating account from `code_hash`, `origin` and provided input `data`. Then if there is the `ext_set_code_hash` function available then a contract after instantiation can change its code hash. If this contract gets removed either by deliberate self destruction or by state rent eviction the original instantiator could reinstantiate the removed contract with the code hash used at the instantiation time, that is the original one. This allows for tricky cases. 

For example: 

1. Alice instantiates a contract with code `C`. This code only allows to upgrade to other code hash, say `Cg`.
1. That code can be permission-less and owner less, i.e. it doesn't have a notion of owner, doesn't privilege certain kinds of users and it doesn't have `ext_set_code_hash`, so it can't change the logic of itself anymore. Let's suppose that the contract gets a lot of attention and trust, possibly accumulating a lot of funds.
1. Then the contract gets removed somehow: either selfdestruct or state rent eviction without leaving a tombstone.
3. Alice reinstantiates the contract on its place with code `C` (not `Cg`).
4. Since the only possible action to do with `C` is to upgrade code to some other code hash, Alice does exactly that, upgrading code to some `Cm`. The only possible thing `Cm` does is to send all funds to Alice.

**Comment by xlc** [comment]
What is the reason for the current derive contract address algorithm? Instead of something similar to ethereum?

**Comment by pepyakin** [comment]
In fact, the current derive algo is similar to Ethereum's CREATE2. The reasons pretty much the same.

**Comment by thiolliere** [comment]
maybe we can add a nonce in the generation of the contract address.
either a global nonce in a storage in contract.
or maybe just AccountNonce from system. no ?

**Comment by pepyakin** [comment]
Yeah, that would help to solve this particular issue at hand. However, this way we would also lose advantages of instantiation approach (see the differences between CREATE vs. CREATE2 in Ethereum).

On the first glance the problem we are having here seems to be caused by the interaction of the following features:

1. `set_code_hash`
1. clean removal of a contract, by
    1. deliberate self destruction
    1. clean removal by state rent mechanism (i.e. without leaving a tombstone)
1. our instantiation process (CREATE2 like)

It seems if we remove or change one feature the problem will be solved. `CREATE2` mechanism seems to be important and provides new functionality. I believe we also don't want to leave traces of removed contracts since this is a way to bloat blockchain. `set_code_hash` seems to be useful (see the description of this issue), however ultimately it might be seen as convenience functionality which could be achieved by other mechanisms like having a proxy contract which redirects calls to the current version of the contract. (However, we don't have a story for proxy contracts right now)

Regarding not being able to deploy the same contract two times:
I believe we've already discussed this issue with @Robbepop and we've already had an idea of mitigation of this issue although a bit clumsy: if a contract needs to instantiate another contract it needs change the input `data` somehow. 

That said, I'd propose to create another issue for this problem if required and reserve this issue for the discussion about the `set_code_hash`.

**Comment by pepyakin** [comment]
Abandoning `set_code_hash` looks like the way forward. This means we would have some other way (even if indirect) to run updated logic.
