### ISSUE TITLE
srml-contracts: storage trie doesn't use hashing

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2365]
A contract uses a child trie for implementing its storage after #2002. Before that it used a doublemap with twox and blake2 for hashing the keys and values. 

After that PR landed, all values are now stored in the storage under raw keys, without any hashing.

This might be problematic.

cc @thiolliere

**Comment by thiolliere** [comment]
so basically it seems we should use blake2_256 in all storage call put_raw get_raw

**Comment by pepyakin** [comment]
Yeah. This might be related to the refactoring mentioned in https://github.com/paritytech/substrate/issues/2325

**Comment by thiolliere** [comment]
solved
