### ISSUE TITLE
Systemd socket activation

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/substrate#2385]
It would be nice for Substrate to support systemd socket activation on Linux systems.

**Comment by bkchr** [comment]
Why?

**Comment by DemiMarie-parity** [comment]
It makes it easy for Substrate to operate as a daemon, and makes management easy.  It also makes it easy to run Substrate in a sandbox with low privilege.

**Comment by bkchr** [comment]
I still don't get it. If your node just starts, when someone tries to connect to it, it will probably never be started.

**Comment by gavofyork** [comment]
Indeed. Substrate is a node, not a wake-on-demand "server".
