### ISSUE TITLE
Aura authorship task terminated unexpectedly. Restarting

### ISSUE THREAD

**Issue by maxsam4** [paritytech/substrate#2390]
I am trying to use grandpa in a new chain but I am unable to seal blocks. When running a validator node, the following error is thrown again and again
```
Starting consensus session on top of parent 0xd49f1bbc63da294f927e90847722f5c4333bbd4bfff8b0d0761908a1d0d4404f
src/libcore/result.rs
999
5
Aura authorship task terminated unexpectedly. Restarting
```
Alice is the single validator in the dev chain, defined using 
`vec![get_authority_keys_from_seed("Alice"),]` 
and I have tried running the node with `--dev`, `--alice --dev`, `--key="//Alice" --validator --chain=dev` and a few other options but same result.

From the error, it seems like some unwrap is failing but I am unable to figure out which exactly.

**Comment by bkchr** [comment]
Latest master and you have just executed the following command?
```
cargo run -- --alice --dev
```

**Comment by maxsam4** [comment]
No, I created a node template and then tried to implement grandpa in it (The default template does not use grandpa).

Any help towards debugging this error will be appreciated. It would be great if you could tell me in which scenarios this is thrown.

**Comment by bkchr** [comment]
For me our `node` works with the given cli.

Could you enable the feature `wasm-nice-panic-message` for sr-io and rebuild the wasm blob? This will output the full error message.

**Comment by maxsam4** [comment]
afaict, the sr-io package is directly picked up from github by cargo. Is there a way to enable it other than cloning the repo. editing the file and pointing cargo towards it?

**Comment by bkchr** [comment]
You need to enable it in your `Cargo.toml` that includes `sr-io`.

See: https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section Especially look at "To use the package awesome:".

**Comment by maxsam4** [comment]
Thanks @bkchr . This is the full error message
```
Starting consensus session on top of parent 0xca5c60f430c7403de396ae819f167c24c69a2324e5cf8e0ba2b965efe3ff379f
panicked at 'Gets and decodes final number inherent data: "Finalized number inherent data not found"', src/libcore/result.rs:999:5
Aura authorship task terminated unexpectedly. Restarting
```

**Comment by bkchr** [comment]
It seems that you not have `run_grandpa_voter` called. Please look at `node/cli/src/service.rs` into `AuthoritySetup` on how to setup Grandpa.
 
As this is no bug, I close this issue. But feel free to ask more in this issue if you still have some problems.
