### ISSUE TITLE
allow modules to validate transaction

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#2391]
https://github.com/paritytech/substrate/pull/2342#issuecomment-486202390

also can relate to https://github.com/paritytech/substrate/issues/2262

**Comment by thiolliere** [comment]
design thoughts:
* modules can only validate transaction that call into himself.
* modules has a validate_transaction function (like on_finalize) that can validate a call.
* it is the responsability of validate_transaction to pay the transaction
  * (regular signed transaction are payed by signer)
  * we could restrain it by making validate_transaction returning a set of weighted account maybe. But seems better not to.

**Comment by thiolliere** [comment]
ok I'm mixed on implementation either I create a trait same as `Dispatchable` named `Validatable` that is implemented same as `Dispatchable` by construct_runtime.

Or I make use of of `IsSubType` trait: I move this trait to sr-primitives, and then both Dispatchable and Validatable can be implemented automatically with `AllModule` kind of similar way to OnFinalize stuff.

Hmm but `construct_runtime` allow not to use a Call of a module. So better to go former way.

**Comment by thiolliere** [comment]
also either we make a validate_transaction that takes Call enum or otherwise we could do an attribute on method which could be `#[validate_transaction_with(my_function)]` on the method itself

**Comment by gavofyork** [comment]
This should be an API similar to `ProvideInherent`: there should be an analogous trait `ValidateUnsigned` , with a function `fn validate_unsigned(call: &Self::Call) -> Result<TransactionValidity, Self::Error>`. It should be advertised in `construct_runtime` in a similar way and aggregated accordingly to implement the runtime-level `validate_transaction` API. The two tags do what you'd expect by looking at the validation logic for normal Signed Transactions in executive.

``
impl<T: Trait> ProvideInherent for Module<T> {
	type Call = Call<T>;
	fn validate_unsigned(call: &Self::Call) -> result::Result<TransactionValidity, Self::Error> {
		// TODO: Check to see whether this `call` is, in and of itself, valid. If so, state the attributes of validity for the transaction queue.
	}
}
```
