### ISSUE TITLE
Uncoupled node connections and grandpa finalize

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#2396]
When the node's finalize height cannot be up to date, the number of connects for that node will slowly decrease until it is 0.

**Comment by marcio-diaz** [comment]
I'm still debugging, not sure yet what is the cause. Something that you may try (as quick fix) if you have time is setting https://github.com/paritytech/substrate/blob/2899be9eef8821eb1b601812c038c69d7a177f93/core/finality-grandpa/src/communication/mod.rs#L68 `INVALID_VIEW_CHANGE` to a higher value, like `-100`.
