### ISSUE TITLE
Constify parameter value storage items

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#2400]
Storage items that function only as rarely changing parameters of the system should instead be "hard-coded" runtime items. They can then be changed with a runtime upgrade.

Should move the `type_parameter` and `Get` items from polkadot into substrate and roll them out across the modules, similarly to how they're used in `slots.rs`.

**Comment by thiolliere** [comment]
I think I can see why it is implemented that way.
But it seems equivalent of it being implemented using a regular trait function.
Or assoicated const value.

**Comment by bkchr** [comment]
It needs to be an associated const value. Otherwise, you would need to modify the module to modify the value.

**Comment by bkchr** [comment]
I'm not 100% convinced that we should use `type_parameter` + `Get` here. I would propose to use const associated types in the configuration trait. 
By using a const associated type we can support default values very easily.
