### ISSUE TITLE
Parliamentary governance needs to finally force grandpa finalize permissions?

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#2426]
When there is more than a certain number of validators in the grandpa consensus that are always dropped, which makes it impossible to finalize, is it necessary to force finalize through parliamentary governance voting?

**Comment by rphmeier** [comment]
@gguoss If finality drops, the governance has no mechanism to finalize blocks. It would require a hard-fork recovery or the use of the GRANDPA offline-fallback.
