### ISSUE TITLE
BABE randomness

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/substrate#2435]
This comes after #2084.

**Comment by rphmeier** [comment]
Can you do a brief writeup of how this will be accomplished? Either here or when you open a PR -- just to provide some background for reviewers.

**Comment by rphmeier** [comment]
Building on #2372 and #2656 : 

At a very high level, what we'll want is to make sure there's an inherent digest which contains the (checked) VRF proof. Then we'll have the BABE logic inspect the VRF proof somehow and fold it into the randomness beacon. But as a first step we'll just want to get the VRF into `srml-babe`.

**Comment by burdges** [comment]
We only produce the random beacon from the the VRF outputs at the end of the epoch, but you could accumulate the eventual random beacon with each block, so `new_vrf_output_sum = f(old_vrf_output_sum,current_vrf_output)`.   In this, `f` could be some hash function, but `f` could equally be Ristretto `+` on `RistrettoPoint`, or any `+` on `[u8; 32]` like xor, lexicographic, `wrapping_add`s, etc.

**Comment by DemiMarie-parity** [comment]
@burdges

> We only produce the random beacon from the the VRF outputs at the end of the epoch, but you could accumulate the eventual random beacon with each block, so `new_vrf_output_sum = f(old_vrf_output_sum,current_vrf_output)`. In this, `f` could be some hash function, but `f` could equally be Ristretto `+` on `RistrettoPoint`, or any `+` on `[u8; 32]` like xor, lexicographic, `wrapping_add`s, etc.

Would a low influence function be desirable here?

Also, it seems to me that the best way to avoid various attacks is to look at “What fraction of the VRF outputs satisfy predicate X?”, not “Does the beacon satisfy predicate X?”.  The main reason is that it requires more validators to collaborate if they want to maliciously control the outcome.

**Comment by burdges** [comment]
I do not think so..  These low influence functions normally increase colluding adversaries influence.  And worse for Ouroboros/BABE they can do so "out of sequence".  

As an example, you run bitwise majority vote then the malicious block producers can push specific bits in specific directions, so some later honest block producers have no influence over some bits.  If otoh you just do xor then everyone has equal influence and adversaries control exactly as many bits as they have tailing block producers, with the caveat that they cannot analyze so many really.

Ouroboros/BABE only really requires one honest block producer succeeding within the right time frame, although any honest block producer succeeding require more honest block producers.  I'd think the analysis must be altered for a low influence function, but maybe that's an interesting exercise @hndnklnc and we might learn something interesting if done carefully.

Anyways the "naively" conservative choice would be `f` being a hash function.  It's more likely using 256 bits over 128 makes some small difference though, in which case do not add elliptic curve points.

**Comment by hndnklnc** [comment]
There are two problems of using a low influence function for the randomness beacon

1. We cannot guarantee that the randomness is truly random. For example, if we use a median function then the malicious parties can easily make that the VRF output that they want is the median.

2. The malicious parties should not know the randomness beacon until the end of the epoch for security. However, with the low influence function, we may not guarantee this because it is not truly random. If they knew the randomness beacon before the end of the epoch, they would update the validator set (or key update) for 2 epoch's later so that the malicious validator's selected more than honest ones.
