### ISSUE TITLE
Document storage key generating algorithm

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2443]
Is there any documents of how storage key is been generated?

I spent a lot of time debugging a double map breaking change caused by #2268.
I simply change the hasher for prefix + key 1 from twox128 to blake2 256 and it doesn't work.

I had a hard time to debug macro generated code trying to figure out why simply change the hasher is not enough and then finally found out an extra `using_encoded` is performed so I have to add length prefix. I don't know if this is intended because I cannot find any documents and spec about this.

The old algorithm for double map with twox128 for key 2 hasher:
`twox128(encode(prefix) + encode(key1)) + twox128(key2)`

The new algorithm for double map with twox128 for key 2 hasher:
`blake2_256(encode(encode(prefix) + encode(key1))) + twox128(key2) `

The extra encode seems redundant to me.

I also cannot find any tests for double map storage key generation. There should be some to ensure the generated key won't change unexpectedly.

**Comment by rphmeier** [comment]
cc @thiolliere

**Comment by thiolliere** [comment]
there is no security issue just the encoding is not optimized

**Comment by thiolliere** [comment]
so I implemented this way but otherwise we can also just update the doc to specify the current behavior as it doesn't harm that much. ?

**Comment by xlc** [comment]
Can someone make a decision on this so we know if there is going to be another breaking change in 1.0 branch or not.

**Comment by thiolliere** [comment]
I

**Comment by thiolliere** [comment]
I don't know about the decision to make in v1.0, but if it is not too late I vote for putting that in.

The PR is #2480

**Comment by thiolliere** [comment]
> Can someone make a decision on this so we know if there is going to be another breaking change in 1.0 branch or not.

this is now merged on 1.0 branch with breaking change and documentation.
