### ISSUE TITLE
srml-contract: set rent_allowance to more sensible default

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2448]
By default `rent_allowance` is set to 0. If a contract doesn't make any adjustments in its `deploy` function then it would be evicted on the next call to that contract.

It looks like that the more sensible default would be to set `rent_allowance` to `max_value` by default.

**Comment by thiolliere** [comment]
it is just a matter of changing this default:
https://github.com/paritytech/substrate/blob/0c1802b5e405a8421485c0aeebaad5a235fc5211/srml/contract/src/account_db.rs#L126
