### ISSUE TITLE
Optimize Docker build

### ISSUE THREAD

**Issue by chevdor** [paritytech/substrate#2464]
Currently, .dockerignore does not exclude `.git`.
AFAIK, the `.git` folder is only required by `./scripts/build.sh` to figure out what is the root folder.

Finding another way to identify the root folder (currently PROJECT_ROOT=`git rev-parse --show-toplevel`) allows to exclude the .git folder and avoid what is currently the copy of around 800+MB to the first stage image.

**Comment by folsen** [comment]
@TriplEight sorry to add you to a bunch of things, but maybe you can take a look at this one too?

**Comment by TriplEight** [comment]
@chevdor could you specify which docker build do you mean: `parity/substrate` or `parity/rust-builder`?
First one just copies substrate's binary, second anyways `git fetch`es the whole repository every job.

**Comment by chevdor** [comment]
I was referring to https://github.com/paritytech/substrate/blob/master/Dockerfile
In the current version, the build.sh script needs the .git folder but only to find the root folder of the project magically. If we find a way to do it without needing the .git folder (which is not needed otherwise), we spare the copy (take time and space) of ~800MB and growing. The first stage image is already very fat so losing this weight would be very beneficial, especially for CI.

**Comment by TriplEight** [comment]
@chevdor 
The thing is our current CI (GitLab) makes use of this Dockerfile: https://github.com/paritytech/scripts/blob/master/docker-files-for-Gitlab-CI-rust/rust-builder/Dockerfile
This image is universal builder for Substrate based projects.

And this image https://github.com/paritytech/substrate/blob/master/scripts/docker/Dockerfile is used for publishing Substrate's binary.

I'm not aware if the Dockerfile you are talking about is being used anywhere, please tell me if it is.
