### ISSUE TITLE
Random Hash logic return 0x0000000000000000000000000000

### ISSUE THREAD

**Issue by Niklaskkkk** [paritytech/substrate#2465]
Hi, 
I try to follow this guide: https://shawntabrizi.github.io/substrate-collectables-workshop/#/2/generating-random-data

Once I updated my .rs file with the random_hash variable and create a new Kitty ,all values in the Kitty property has the value "kittyStorage.kitties: Kitty
{"id":"0x0000000000000000000000000000000000000000000000000000000000000000","dna":"0x0000000000000000000000000000000000000000000000000000000000000000","price":0}"

Appreciate any input on why this happens. I paste my code below: 

```
use support::{decl_storage, decl_module, StorageValue, StorageMap, dispatch::Result, ensure, decl_event};
use system::ensure_signed;
use runtime_primitives::traits::{As, Hash};
use parity_codec::{Encode, Decode};

#[derive(Encode, Decode, Default, Clone, PartialEq)]
#[cfg_attr(feature = "std", derive(Debug))]
pub struct Kitty<Hash, Balance> {
    unique_id: Hash,
    dna: Hash,
    price: Balance,
    gen: u64,
}

//pub trait Trait: system::Trait {}
pub trait Trait: balances::Trait {
    type Event: From<Event<Self>> + Into<<Self as system::Trait>::Event>;
}

decl_event!(
    pub enum Event<T>
    where
    <T as system::Trait>::AccountId,
    <T as system::Trait>::Hash {
        Created(AccountId, Hash),
    }
);

decl_storage! {
    trait Store for Module<T: Trait> as KittyStorage {
        OwnedKitty get(kitty_of_owner): map T::AccountId => T::Hash;
        Kitties get(kitty): map T::Hash => Kitty<T::Hash, T::Balance>;
        KittyOwner get(owner_of): map T::Hash => Option<T::AccountId>;

        Nonce: u64;
    }
}

decl_module! {
    pub struct Module<T: Trait> for enum Call where origin: T::Origin {

        fn deposit_event<T>() = default;

        fn create_kitty(origin) -> Result {
            let sender = ensure_signed(origin)?;
            let nonce = <Nonce<T>>::get();

            let random_hash = (<system::Module<T>>::random_seed(), &sender, nonce).using_encoded(<T as system::Trait>::Hashing::hash);

            ensure!(!<KittyOwner<T>>::exists(random_hash), "Kitty already exists");

            let new_kitty = Kitty {
                unique_id: random_hash,
                dna: random_hash,
                price: <T::Balance as As<u64>>::sa(0),
                gen: 0,
            };

            <Kitties<T>>::insert(random_hash, new_kitty);
            <KittyOwner<T>>::insert(random_hash, &sender);
            <OwnedKitty<T>>::insert(&sender, random_hash);

            <Nonce<T>>::mutate(|n| *n += 1);

            Self::deposit_event(RawEvent::Created(sender, random_hash));

            Ok(())
        }
    }
}
```

**Comment by shawntabrizi** [comment]
@Niklaskkkk A hash of all 0's when you query the storage value implies to me the default value is being returned. My best guess is that you are not querying a kitty which has been created.

For example, if you call `Kitties` with some `Hash` which does not actually map to a real kitty, it will return the default values, which is all 0 for all the different properties.

It would be good to double check that you have indeed created a cat in your system, and then queried for that particular cat to get the hash information.

One improvement you can make to your runtime is have the `Kitties` storage item store an `Option<Kitty<T::Hash, T::Balance>>`, thus it will explicitly return `None` rather than the default value for a kitty.

**Comment by shawntabrizi** [comment]
@Niklaskkkk I am going to close this since it might be a dead thread, but if you need assistance, please do reach out!

**Comment by Niklaskkkk** [comment]
Yes @shawntabrizi , it worked with your suggestion. Thanks!

**Comment by Niklaskkkk** [comment]
Hi @shawntabrizi , 
I continued the tutorial and am struggling with an issue in section 4 - create kitties. 
I try to do it through the browser console, and also with added button functionality (next section). However, both return the same error message: "Failed subscription" (see attached picture).

I am on Ubuntu 18.04
Node v8.10.0
@shawntabrizi 

![error message](https://user-images.githubusercontent.com/40757307/58413854-1a78ca80-807a-11e9-89d5-b8f833b57184.png)
![error2](https://user-images.githubusercontent.com/40757307/58413858-1d73bb00-807a-11e9-86ff-4a268010832d.png)

**Comment by shawntabrizi** [comment]
@Niklaskkkk Did you sanity check other things? For example checking that Alice has funds?

Does balance transfer work?

I suggest you join our Riot channel so that we can help you a bit more quickly: https://docs.substrate.dev/docs/feedback
