### ISSUE TITLE
Subkey docker hub image  

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2478]
There is https://hub.docker.com/r/parity/substrate but I don't think it includes subkey. 
Will be good if there is an prebuilt docker image for subkey or add subkey to substrate image

**Comment by TriplEight** [comment]
If `subkey` does not depend from `substrate`, I'm going to create a separate docker image for it.
@xlc are some specific flags required when building `subkey`?

**Comment by xlc** [comment]
I am not aware of any specific flags required to build `subkey`

**Comment by TriplEight** [comment]
then I'll build it with just `--release`

**Comment by xlc** [comment]
Fixed by #2752
