### ISSUE TITLE
improve RPC error message "Invalid Transaction"

### ISSUE THREAD

**Issue by brenzi** [paritytech/substrate#2485]
Currently, extrinsics either get finalized or they fail with "Invalid Transaction". 

I suggest that the developer can access more verbose error messages like 
* extrinsic decoding failed
* signature verification failed
* wrong nonce
* not enough funds to pay fees
* module-specific failures 
  * no such module
  * no such method

I could live with trace messages in the node log, but nicer would be to return these via RPC response

**Comment by xlc** [comment]
Related (maybe duplicated): https://github.com/paritytech/substrate/issues/2246

**Comment by brenzi** [comment]
defenately related, but my requirement is a bit more relaxed, as node log would be sufficient for me.

**Comment by tomusdrw** [comment]
Already addressed by #3433
