### ISSUE TITLE
Chain behavior with less than minimum validator candidates

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#2494]
When this happens `candidates.len() < <MinimumValidators<T>>`,

here should be an approach to make sure: 

 - The internal state of Staking + Session module is sensible. Example: exposures need to be probably removed as we don't really want to slash anyone anymore at this state. Or, we currently don't clean the session module's list of validator if this case happens. 
- The global behavior of the chain is properly changed (probably via some function calls or events). Quote: 

https://github.com/paritytech/substrate/blob/f481c7123cc3928c5a5c01f7395ab1f3be7c3de5/srml/staking/src/lib.rs#L1028-L1036

(not certain which milestone is this worth to be placed in)

**Comment by xlc** [comment]
Not sure if this is related.
I had an issue that with 4 minimum validators, 2 current validators (via misconfigured chain spec), I can't add new validators.
On election, it will have 2 + 1 = 3 new validators, which is less than minimum validators, and not updating validators because it is less than minimum and as a result there still only 2 validators.

**Comment by Kianenigma** [comment]
> On election, it will have 2 + 1 = 3 new validators, which is less than minimum validators, and not updating validators because it is less than minimum and as a result there still only 2 validators.

Based on this looks like it is related but it is the expected behavior. 3 candidates (assuming all have enough balance). 4 minimum. Nothing will happen. Correct?

**Comment by dvc94ch** [comment]
Should we allow invalid chain specs? Why don't we do this instead?

```diff
diff --git a/srml/staking/src/lib.rs b/srml/staking/src/lib.rs
index c1b42a8b..4a4b0ce0 100644
--- a/srml/staking/src/lib.rs
+++ b/srml/staking/src/lib.rs
@@ -275,8 +275,8 @@ use runtime_io::with_storage;
 use rstd::{prelude::*, result, collections::btree_map::BTreeMap};
 use parity_codec::{HasCompact, Encode, Decode};
 use srml_support::{
-       StorageValue, StorageMap, EnumerableStorageMap, decl_module, decl_event,
-       decl_storage, ensure, traits::{
+       StorageValue, StorageMap, EnumerableStorageMap, assert_eq_uvec, decl_module,
+       decl_event, decl_storage, ensure, traits::{
                Currency, OnFreeBalanceZero, OnDilution, LockIdentifier, LockableCurrency,
                WithdrawReasons, OnUnbalanced, Imbalance, Get
        }
@@ -585,9 +585,11 @@ decl_storage! {
                                        };
                                }
 
-                               if let (_, Some(validators)) = <Module<T>>::select_validators() {
-                                       <session::Validators<T>>::put(&validators);
-                               }
+                               // Make sure the genesis state of the session module is consistent
+                               // with the genesis state of the staking module.
+                               let validators = <Module<T>>::select_validators().1
+                                       .expect("Genesis state of the staking module is valid.");
+                               assert_eq_uvec!(validators, <session::Validators<T>>::get());
                        });
                });
        }
```

**Comment by burdges** [comment]
We could maybe degrade to some "staking and governance only" chain state.  It'd make moving staking and governance off the relay chain "interesting".  :(

**Comment by thiolliere** [comment]
as discussed offline it seems a good solution would be to not create a new era until there is a successful election of more than the minimum number of validator.

**Comment by burdges** [comment]
It makes election censorship more risky, but that's likely better than our alternatives.

**Comment by thiolliere** [comment]
The emergency phase is implemented, in the emergency phase the configured trusted origin (proportion of collective or root in kusama) can push the solution.
So I think we can close, or maybe we can reopen if we want to implement more functionality like:
> We could maybe degrade to some "staking and governance only" chain state

**Comment by kianenigma** [comment]
Yeah, this can be closed now.
