### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by gguoss** [paritytech/substrate#2496]
https://github.com/paritytech/substrate/blob/14bc1b40b66ee66beb53efa65cbb25c89e90fc31/core/client/src/call_executor.rs#L212

The initialization of this function takes a lot of performance when the node is just started. It may cause the node to build block took too long.
Any call_api_at call takes more than 0.1s to execute in the debug compiled executable node.

**Comment by bkchr** [comment]
Without a call trace, we can not do that much.

Is it calling into wasm?

**Comment by bkchr** [comment]
And after some time the function execution time decreases?

**Comment by vjoke** [comment]
I have tested TPS of latest code, only to get a low TPS, far below 1k TPS,  someone reported this issue previously #2344,  want to know when the performance will be improved

**Comment by gguoss** [comment]
> Without a call trace, we can not do that much.
> 
> Is it calling into wasm?

Debug build,  native call

**Comment by gguoss** [comment]
> And after some time the function execution time decreases?

A period of time (about 2 blocks of time) is decreases.
But the initialization of this environment should not be placed in the block time

**Comment by bkchr** [comment]
Everytime or just for the genesis block?
It could be the first pass time initialization of the wasm blob. Could you please provide some trace? You could use https://github.com/ferrous-systems/flamegraph to generate one.

**Comment by gguoss** [comment]
> Everytime or just for the genesis block?
> It could be the first pass time initialization of the wasm blob. Could you please provide some trace? You could use https://github.com/ferrous-systems/flamegraph to generate one.

Everytime,  
[my_flamegraph.svg.zip](https://github.com/paritytech/substrate/files/3156743/my_flamegraph.svg.zip)

**Comment by bkchr** [comment]
Is this still relevant?
