### ISSUE TITLE
Specify the maximum number of incoming connections

### ISSUE THREAD

**Issue by zhang-dong-dong** [paritytech/substrate#2507]
Hello, the startup parameter --in-peer value I set to 5, but there are still more than 15 P2P links. What's the reason?

> 2019-05-08 19:40:34.591 INFO [runtime|xrml_xsystem] height:9643, blockproducer: 6488ceea630000b48fed318d13248ea7c566c0f4d2b8b90d12a136ad6eb02323 (5ELXHYwf...)|name:genesis2
2019-05-08 19:40:34.593 INFO Imported #9643 (0xbc9f…b43a)
2019-05-08 19:40:34.593 INFO [redis] get_blocknumber in [put] is None
2019-05-08 19:40:35.527 INFO Idle (**15 peers**), best: #9643 (0xbc9f…b43a), finalized #9632 (0xa51f…e546), ⬇ 6.3kiB/s ⬆ 9.7kiB/s

**Comment by tomaka** [comment]
`--in-peers` specifies the maximum number of incoming connections. There's also `--out-peers` that specifies the maximum number of outgoing connections (25 by default).
The maximum number of connections is `in_peers + out_peers`.

**Comment by zhang-dong-dong** [comment]
I see. That's right. Thank you.
