### ISSUE TITLE
Chains spawning chains

### ISSUE THREAD

**Issue by void4** [paritytech/substrate#2509]
Since your smart contract language seems to be able to handle byte arrays, if the state of a chain can be fully serialized into and deserialized from contiguous bytes, one could imagine a chain (the state under consensus) signalling/instructing the underlying P2P-client to create a new chain from this or a newly constructed snapshot.

"Genesis/fork split on demand", so to speak.

Interesting patterns are possible, possibly useful when disagreements occur:

```
At block 1M:
    Create two new chains, each with half of the rights/data/public keys, corresponding to the disagreeing parties
    Kill this chain
```

**Comment by folsen** [comment]
In theory I do believe this could be possible yes!
