### ISSUE TITLE
WASM build.sh uses tput in a way that can break CI pipelines

### ISSUE THREAD

**Issue by Sushisource** [paritytech/substrate#2515]
The top-level build.sh script in the node template has calls to tput to bold-ify some text. 

This can result in errors like `tput: No value for $TERM and no -T specified` when hooked up to a pseudo-terminal, as is often the case in CI pipelines (like gitlab).

The call can specify -T, or the script can just not bother with the colors.

Thanks! Loving the platform.

**Comment by bkchr** [comment]
Just call `export TERM=xterm` before calling the script and you are fine.

**Comment by Sushisource** [comment]
@bkchr Yes, I understand how to fix the problem. What I'm saying is this is surprising for your users. There's no reason the build.sh script can't check for a TERM variable and use colors iff it's set. I can make an MR for this too.

**Comment by bkchr** [comment]
You can create a pr for that.
