### ISSUE TITLE
Pre-create finality proofs for authority set change blocks

### ISSUE THREAD

**Issue by svyatonik** [paritytech/substrate#2554]
from https://github.com/paritytech/substrate/pull/1669#pullrequestreview-227844812

Creating the finality proof seems to be a bit heavy and requires having state available (pruned nodes won't be able to help a light client sync from genesis). I think in a follow-up PR we should change it so that full nodes always generate a finality proof for authority set change blocks and persist it. This way we can use it when serving a finality proof that spans multiple authority set changes.

**Comment by EmmanuellNorbertTulbure** [comment]
Is this still relevant @svyatonik ? Asking to know if I should migrate it or not.

**Comment by svyatonik** [comment]
I think it isn't
