### ISSUE TITLE
Audit is failing.

### ISSUE THREAD

**Issue by TriplEight** [paritytech/substrate#2559]
I tried to add `cargo-audit` check to substrate's CI and stumbled upon the issue with `yaml-rust`.
As was mentioned in https://github.com/paritytech/substrate/issues/2233 is an optional feature we don't use. It does not affect the security.
```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 22 security advisories (from /ci-cache/substrate/cargo/cargo-audit/advisory-db)
    Scanning Cargo.lock for vulnerabilities (502 crate dependencies)
error: Vulnerable crates found!

ID:	 RUSTSEC-2018-0006
Crate:	 yaml-rust
Version: 0.3.5
Date:	 2018-09-17
URL:	 https://github.com/chyh1990/yaml-rust/pull/109
Title:	 Uncontrolled recursion leads to abort in deserialization
Solution: upgrade to: >= 0.4.1
```

But from the testing perspective it prevents running `cargo audit`. 

So please, fix it.

**Comment by thiolliere** [comment]
we use yaml feature there 
```
./subkey/Cargo.toml:13:clap = { version = "~2.32", features = ["yaml"] }
./test-utils/chain-spec-builder/Cargo.toml:8:clap = { version = "~2.32", features = ["yaml"] }
```

their is issue tracker is https://github.com/clap-rs/clap/issues/1387

**Comment by TriplEight** [comment]
I'm merging `cargo-audit` https://github.com/paritytech/substrate/pull/2752

**Comment by TriplEight** [comment]
Closing the issue.
Now there is `cargo-audit` CI job which is allowed to fail. But that doesn't mean it should be ignored. All troubles it indicates, **must** be eventually fixed.
