### ISSUE TITLE
Execution optimisation

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#257]
Execution stack is currently suboptimal. Each call involves querying code from storage, getting runtime version, initialising wasm module, etc. A bulk of work should only be done once per code change. There should be a module between state and executor that tracks code changes and caches reusable bits for each state. If the state does not have code changed since the last state it should reuse cached data for the new state. 

Related: #238

**Comment by pepyakin** [comment]
I think, that #238 could be subsumed by this.

**Comment by gnunicorn** [comment]
@arkpar anything else you wanted to have addressed, that not in #276 and #283 already?
