### ISSUE TITLE
Refactor TestExternalities

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#2572]
As I wanted to extend functionnalities of TestExternalities it seems I ended up just copying the Ext implementation with InMemory backend and thins.

I can't make use of Ext directly because TestExternalities would be a self referencing struct.

I think we could update the test to create TextExternalities in two call one for creating backend stuff and another one for creating the referencing Ext.

Also test could make use of with_storage. All in all it seems code is redundant between TestExternalities, BasicExternalities and Ext

**Comment by Kianenigma** [comment]
I am not much aware of everything that happens under the hood when you simply create an externalities (storage, backend etc.) so can't judge much, but already had in mind to propose: 

- We can make an approach like the `ExtBuilder` sort-of standard and refactor all modules to use it + isolate the struct in a generic way (if possible) as _the standard substrate test framewrok_.

- Not sure if it is possible but having some kind of a `before_each()` and `afte_each()` in my fantasies also sounded nice-to-have.

**Comment by thiolliere** [comment]
maybe we can do that:
```
impl<H: Hasher> TestExternalities<H> where H::Out: Ord {
       /// Return externalities
       pub fn ext(&mut self) -> Ext<H, InMemory<H>, ChangesTrieInMemoryStorage<H>, NeverOffchainExt> {
               Ext::new(&mut self.overlay, &self.backend, Some(&self.changes_trie_storage), None)
       }
}
```
and then in most test we have to add `.ext()` I have a wip branch there, note test of sr-api-macros fails for a reason still unknown to me. https://github.com/paritytech/substrate/tree/gui-refactor-test

**Comment by Kianenigma** [comment]
Okay, I see your changes but I see that we are sorta not on the same page and maybe they should be different issues. What I envisioned and wanted to add was a way to minimize the boilerplate needed to set up the test. I should talk to you in person about this.

**Comment by thiolliere** [comment]
My main concern was I wanted to use Ext and InMemoryBackend stuff as much as possible instead of a custom implementation of Externalities.
Yes sure

**Comment by thiolliere** [comment]
might be easier to solve with https://github.com/paritytech/substrate/pull/3793

**Comment by thiolliere** [comment]
Test externalities is refactored, maybe we can improve test tools in general but this is another issue.
