### ISSUE TITLE
OnDilution should update total issuance

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#2580]
[`on_dilution`](https://github.com/paritytech/substrate/blob/d9c36a02d02adf9b35619b127293e7ae43b7c9a9/srml/treasury/src/lib.rs#L291) mints new funds for the Treasury pot, but does not increase `total_issuance`.

This only gets called from [Staking](https://github.com/paritytech/substrate/blob/d9c36a02d02adf9b35619b127293e7ae43b7c9a9/srml/staking/src/lib.rs#L895) in `new_era`. `reward_validators` correctly updates the `total_issuance` each time it rewards a validator, but `on_dilution` does not.

**Comment by joepetrowski** [comment]
Looking at this a bit further, the pot's funds are added to `total_issuance` when they get spent. So, they do not count as part of total issuance when they are in the pot.

What was the motivation behind this? Maybe I am missing something, but IMO, those funds are in the system and should be counted in issuance when they are added to the pot, not when they are spent.

```
	fn spend_funds() {
		let mut budget_remaining = Self::pot();
		Self::deposit_event(RawEvent::Spending(budget_remaining));

		let mut missed_any = false;
		let mut imbalance = <PositiveImbalanceOf<T>>::zero();
		<Approvals<T>>::mutate(|v| {
			v.retain(|&index| {
				// Should always be true, but shouldn't panic if false or we're screwed.
				if let Some(p) = Self::proposals(index) {
					if p.value <= budget_remaining {
						budget_remaining -= p.value;
						<Proposals<T>>::remove(index);

						// return their deposit.
						let _ = T::Currency::unreserve(&p.proposer, p.bond);

						// provide the allocation.
						imbalance.subsume(T::Currency::deposit_creating(&p.beneficiary, p.value));

						Self::deposit_event(RawEvent::Awarded(index, p.value, p.beneficiary));
						false
					} else {
						missed_any = true;
						true
					}
				} else {
					false
				}
			});
		});

		T::MintedForSpending::on_unbalanced(imbalance);

		if !missed_any {
			// burn some proportion of the remaining budget if we run a surplus.
			let burn = (Self::burn() * budget_remaining).min(budget_remaining);
			budget_remaining -= burn;
			Self::deposit_event(RawEvent::Burnt(burn))
		}

		Self::deposit_event(RawEvent::Rollover(budget_remaining));

		<Pot<T>>::put(budget_remaining);
	}
```

**Comment by thiolliere** [comment]
it seems the currency traits doesn't provide a straightforward way to create some unattributed positive imbalance.
It can be done by deposit_creating a random account and and call make_free_balance_be to its fund back.
This way you would have a positive imbalance you can store in your pot.
I think we should add `fn creating(amount) -> PositiveImabalance` ?

**Comment by joepetrowski** [comment]
> I think we should add fn creating(amount) -> PositiveImabalance ?

Yeah, would be nice for other modules that may introduce imbalances, but I think one of the goals of the Currency trait is to protect issuance handling. This function is definitely useful, but maybe with a big warning in the doc.

**Comment by thiolliere** [comment]
it doesn't need a big warning to me, the imbalance created will increase total_issuance when created, and decrase when dropped, it is quite safe, it is just not-account-attributed balance, like the pot here.

**Comment by joepetrowski** [comment]
I don't think imbalances increase or decrease total_issuance when they are created. I think they just accumulate in the {Positive, Negative}Imbalance type and then adjust total_issuance when they are dropped. No?

**Comment by thiolliere** [comment]
oh yes it seems true, total_issuance is only updated on drop of imbalance, which makes sense, it is all in all an Imbalance.

then maybe we should could create another structure PositiveBalance: `fn creating(amount) -> PositiveBalance` with PositiveBalance representing a balance not assigned to an account. it would be an opaque structure that could unwrap into an Imbalance. I'm not sure of the API.

**Comment by Kianenigma** [comment]
is this still valid @joepetrowski ?

**Comment by joepetrowski** [comment]
> is this still valid @joepetrowski ?

Looking at the code now, it looks like it's handled properly, but I have not followed code changes here super closely. If you think it's OK now then we can close it.

**Comment by thiolliere** [comment]
we do agree that this diff is correct isn't it ?
```diff
@@ -506,10 +513,13 @@ mod tests {
        #[test]
        fn unused_pot_should_diminish() {
                with_externalities(&mut new_test_ext(), || {
+                       let init_total_issuance = Balances::total_issuance();
                        Treasury::on_dilution(100, 100);
+                       assert_eq!(Balances::total_issuance(), init_total_issuance + 100);
 
                        <Treasury as OnFinalize<u64>>::on_finalize(2);
                        assert_eq!(Treasury::pot(), 50);
+                       assert_eq!(Balances::total_issuance(), init_total_issuance + 100);
                });
        }
```

the amount burnt by treasury is kept in total_issuance

**Comment by joepetrowski** [comment]
> the amount burnt by treasury is kept in total_issuance

I wouldn't call funds in the Treasury "burned," so yes, they should be part of `total_issuance`.

**Comment by thiolliere** [comment]
This is not me taht call this "burned" this is the name of the Event: https://github.com/paritytech/substrate/blob/04e5c332ed101dc6af65291eceb18ffbb160b25a/srml/treasury/src/lib.rs#L316

**Comment by thiolliere** [comment]
hmm I was confused why this test was passing, it is wrong to me 50 are burn an should not be into total issuance anymore. But this is actually an issue in srml-balances: https://github.com/paritytech/substrate/pull/3443

Apart from that I think it is fine now.

**Comment by thiolliere** [comment]
> Looking at this a bit further, the pot's funds are added to total_issuance when they get spent. So, they do not count as part of total issuance when they are in the pot.

> What was the motivation behind this? Maybe I am missing something, but IMO, those funds are in the system and should be counted in issuance when they are added to the pot, not when they are spent.

Now the pot amount is count as part as total issuance.

And total issuance issue on burn is fixed so we can close it
