### ISSUE TITLE
Is it possible to tell if a contract execution error is caused by out of gas?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2584]
All I can see now from node terminal is `Runtime: during execution` and nothing much on sdk side.

What does this `during execution` actually mean? Additional println give me `Err(Trap(Trap { kind: Host(DummyHostError) }))`, which is still not very helpful.

Does `DummyHostError` / `during execution` already mean out of gas or there are other conditions to trigger this?

@pepyakin

**Comment by satyamakgec** [comment]
I did face that issue one or two times there may be many causes of that error. I am sharing my findings with you it may solve your problem as well. I was not able to find the right cause but some are listed below.

- **Contract storage gets pruned if you are not executing your local in the archived state.**
    To solve this run your chain using this command - `substrate --pruning archive`
- **Using the incompatible version of ink with respect to the substrate.**  
    I am assuming you are using the substrate v1.0 which is compatible with this git commit `efe69028cc5bd9ec86bfc15f52162b39c560c194` of the ink modules. 

Apart from that, there may be other causes as well, Like the gas issue as well to get rid of this try to pass gas in kilos unit.

**Comment by pepyakin** [comment]
`during execution` say that there were a trap during the execution of a smart-contract. This can be either:

1. OOB access by a contract (unlikely in Rust + ink)
2. Rust-level panics or aborts (including OOM)
3. Trap by the smart-contract host (i.e. substrate runtime), this includes the out-of-gas condition.

Until we have additional debugging capabilities `ext_println` is your best friend...
