### ISSUE TITLE
`pub fn on_finalize()` is not expected operation. 

### ISSUE THREAD

**Issue by satellitex** [paritytech/substrate#2590]
I wrote below code. but runtime doesn't output "finalize!" when each block finalize.
```
pub fn on_finalize(n: T::BlockNumber) {
  runtime_io::print("finalize!");
}
```

But, 
```
fn on_finalize(n: T::BlockNumber) {
  runtime_io::print("finalize!");
}
```
is expected operation.

**Comment by bkchr** [comment]
The macro should detect `on_finalize`, even with the leading `pub`.

**Comment by thiolliere** [comment]
related to https://github.com/paritytech/substrate/issues/2423
reservation is made on exact signature otherwise it is understood as a regular method.
adding a new param or a result will make it understood as a standard call. which is confusing

**Comment by xlc** [comment]
Does it make sense to move those reserved methods into different macro?
At least I feel it doesn't make sense to have `on_finalize` public.

**Comment by thiolliere** [comment]
> Does it make sense to move those reserved methods into different macro?

well this macro would be required because we need to implement a default one otherwise, and it will need some information about module name I think so prefered to put in decl_module.

>  At least I feel it doesn't make sense to have on_finalize public.

I would go to make all reserved keyword completely reserved and if the signature is wrong then it compile-error with a useful message telling the right signature

**Comment by bkchr** [comment]
The function is public anyway, this just implements a trait. These are all just shortcuts for implementing the traits OnFinalize OnInitialize etc.

**Comment by Kianenigma** [comment]
I assume #2609 will close this and won't need further work, right?

**Comment by thiolliere** [comment]
yes reserved function name are not confusing anymore
