### ISSUE TITLE
RPC to ask a node ban a bad transaction

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2604]
Currently it is easy to craft a bad transaction to cause validators unable to produce new blocks (e.g. bad sudo).
I want a way to have a RPC to tell all the nodes that I have control of, to ban a known bad transaction by hash, to 1) not relay it to other nodes, 2) not trying to include it in a block.

This won't stop others to include such transaction but useful in a controlled testnet.
Currently the only way to have the network to "forget" a transaction is restart all the nodes. Which is still possible for a controlled testnet, but much harder than just have validators ban them via RPC.

It may need to be protected somehow (#2303) or disabled by default to avoid people abuse this.

**Comment by tomusdrw** [comment]
Should be fairly easy, since hash-based banning mechanism is already in place, just requires exposing over RPC.

However, I don't get how a bad transaction can prevent blocks from being produced, can you elaborate?
If it panics it should be marked as invalid and removed from the pool and the block should be restarted without it, is that not what happens?

Is this related: https://github.com/paritytech/substrate/pull/2594 ?

**Comment by xlc** [comment]
For example, a bad runtime upgrade. 
In my case, there are overflowing issues on staking module (#1572) and it happens on on_finalize, so I think it have no way to recover because the transaction itself is valid. A nominate transaction can change the state of the chain and triggers this bug on next era end.

**Comment by xlc** [comment]
Not sure if it is related but one thing I observed is that often you can see pending transactions in other nodes but no pending transactions in validator nodes.
I guess one possible reason is that validators are unable to process those transactions and ban them. But this ban is not propagated so bad transactions stays in other nodes' tx pool.
With this RPC I can at least prune the tx pools of my nodes, and for private testnet it means I can do cleanup for all the nodes which makes testing easier. Because otherwise a bad tx could stay in tx pool for a very long time and making the account signed that tx not usable due to nonce issue.
