### ISSUE TITLE
RPC to enable / disable grandpa on validator nodes

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2608]
This will allow developers temporary to turn off finalization of a testnet before submitting any dangerous transactions (e.g. runtime upgrade). If things goes bad, one can revert back and ban the bad transaction (via #2604) and continues. If everything works as expected, use the same RPC to re-enable finalization.

It need to be protected somehow (#2303) or disabled by default to avoid people abuse this.

Related: #2369

**Comment by xlc** [comment]
Just found out there is already `--no-grandpa` flag to turn off grandpa so while RPC will be easier to use, I can already achieve the flow I want.

**Comment by andresilva** [comment]
We're also planning on having a runtime module to allow disabling GRANDPA in a decentralized manner (the `--no-grandpa` flag only works if you control a majority of the authorities).

**Comment by tomusdrw** [comment]
I'd say it falls under general authorship RPC set here: #2369, closing as duplicate to keep the tracker tidy.
