### ISSUE TITLE
Can't build custom runtime module that depends on serde in no_std

### ISSUE THREAD

**Issue by attente** [paritytech/substrate#2614]
Sorry if this is the wrong repo to report this in. I can't seem to do a no_std build of a custom runtime module when serde is added as a dependency.

I've isolated the problem in this repo here: https://github.com/attente/substrate-serde. It's just a new repo created via `substrate-node-new`, and modified to build serde in `no_std` mode as well.

This is the error message when trying to build it:

```
[nix-shell:~/substrate-serde]$ scripts/build.sh 
Building webassembly binary in runtime/wasm...
   Compiling substrate-serde-runtime v1.0.0 (/home/william/substrate-serde/runtime)
warning: unused doc comment
  --> /home/william/substrate-serde/runtime/src/template.rs:23:1
   |
23 |   /// This module's storage items.
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
24 | / decl_storage! {
25 | |     trait Store for Module<T: Trait> as TemplateModule {
26 | |         // Just a dummy storage item. 
27 | |         // Here we are declaring a StorageValue, `Something` as a Option<u32>
...  |
30 | |     }
31 | | }
   | |_- rustdoc does not generate documentation for macro expansions
   |
   = note: #[warn(unused_doc_comments)] on by default
   = help: to document an item produced by a macro, the macro must produce the documentation as part of its expansion

warning: unused import: `serde`
  --> /home/william/substrate-serde/runtime/src/template.rs:11:5
   |
11 | use serde;
   |     ^^^^^
   |
   = note: #[warn(unused_imports)] on by default

error: duplicate lang item in crate `std`: `panic_impl`.
  |
  = note: first defined in crate `sr_io`.

error: duplicate lang item in crate `std`: `oom`.
  |
  = note: first defined in crate `sr_io`.

error: aborting due to 2 previous errors

error: Could not compile `substrate-serde-runtime`.

To learn more, run the command again with --verbose.
```

It should be possible to do this AFAICT because Serde does support no_std builds: https://serde.rs/no-std.html

**Comment by bkchr** [comment]
Did you disabled the default features, as written in the serde documentation?

**Comment by attente** [comment]
Yes, I did it here: https://github.com/attente/substrate-serde/commit/9c010b91d412cf9d79809f07d8aafbac68bf51f8#diff-a3fea9165475a45ebf09566e2842a9dbR119

**Comment by bkchr** [comment]
So, somehow the `default` and `std` features are still enabled. I think that this is a problem of the cargo feature resolution. You would need to make sure that these features are disabled for all of your dependencies.

This is the line that tells you that the feature is enabled:
```
Running `rustc --crate-name serde /home/bastian/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=3c29ed886629a68a -C extra-filename=-3c29ed886629a68a --out-dir /home/bastian/projects/parity/substrate-serde/runtime/wasm/target/release/deps -L dependency=/home/bastian/projects/parity/substrate-serde/runtime/wasm/target/release/deps --cap-lints allow --cfg ops_bound --cfg core_reverse --cfg de_boxed_c_str --cfg de_rc_dst --cfg core_duration --cfg integer128 --cfg range_inclusive --cfg num_nonzero`
```

Why do you need serde in wasm?

**Comment by attente** [comment]
Is there a way to track down which dependency is causing it? FWIW, that example repo is just simply the bare template node with no-std serde (`default-features = false`) included as a new dependency, so I have to assume that the problem lies somewhere in the template node's dependency tree.

As for why I'd like to use serde in the runtime module, it already provides a bunch of serialization implementations for several primitive data types, as well as the derive macro that automatically allows serialization and deserialization of custom types too, making them easier to work with rather than directly with byte strings.

**Comment by bkchr** [comment]
Are you aware of parity-codec?

You could look into srml-support, as we use serde for the GenesisConfig. Maybe that needs some tweaking. But serde is just enabled on std.

**Comment by attente** [comment]
Ok, I'll have to take a deeper look into it. Thanks!
