### ISSUE TITLE
Generalize chunked_map (or chunked_list?)

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#2619]
Already manually implemented and used in Council and Indices.

Essentially equal to splitting a giant `Vec<T>` into fixed size smaller vectors each fetched via an index. Needs a bit of work to keep track of _where to insert next_ + _cleanup (option--probably should let the user call an expensive `clean()` if they want it)_. 

Using it is:

- bit more expensive to do a global iteration.
- otherwise more efficient to read and write (smaller chunks, not sure but maybe it also helps key hashing?).

Also, good in the sense that it can encourage new substrate users NOT to naively store bulks of `Vec<T>`.

**Comment by kianenigma** [comment]
A very good example + inspiration of how this can be done is implemented by @apopiak here: https://github.com/apopiak/stablecoin/blob/master/storage-adapters/src/priority_queue.rs

**Comment by apopiak** [comment]
@kianenigma Was wondering whether to take a shot at implementing this, but cannot find the Council and Indices implementations. :sweat_smile: 
Any pointers?

**Comment by apopiak** [comment]
ok, I think I found it, do you mean the voters in elections [here](https://github.com/paritytech/substrate/blob/028a71594f93edc1c105c85f425760943a362f8e/frame/elections/src/lib.rs#L248)?

**Comment by marcio-diaz** [comment]
> ok, I think I found it, do you mean the voters in elections [here](https://github.com/paritytech/substrate/blob/028a71594f93edc1c105c85f425760943a362f8e/frame/elections/src/lib.rs#L248)?

I think so, I  was just going to paste a link there.

**Comment by kianenigma** [comment]
This issue is quite old, but I think it is still interesting to keep around. It can be implemented now easier with the new storage types.
