### ISSUE TITLE
Handle child trie key in change trie

### ISSUE THREAD

**Issue by cheme** [paritytech/substrate#2622]
Change tries as described in  #628 store extrinsic index for a key change.
In the case of a child trie child key change, the root parent trie key will be include in change trie but not the key in the  child trie, making the information a bit less relevant.

I wonder if child trie key could benefit from the same mechanism. I see two options:
- put all in change_trie (change trie will replace key by (option<parent_key>, key).
- create a change_trie per child trie and manage multiple change trie

the second option looks the most promising to me but I am not very familiar with change trie, @svyatonik maybe you have a good idea.

 Also it seems  to me that this should be optional per child trie (iirc the change trie is optional).

There is also the question of the proof for child change trie.

**Comment by svyatonik** [comment]
To support multiple changes tries we need to include root of every CT into block' digest then. Probably not the best idea? I'm not sure- how many child tries could be there.

**Comment by cheme** [comment]
Should putting child change trie root in parent change trie solve this root in digest issue (you still have to pack multiple change trie content but you got a single root in block digest)?
How many child tries depends on usage from runtime so I think we can also assume many (a lot). And that will be the case if contracts are use in runtime (one per contract with one kv changed in block).

**Comment by svyatonik** [comment]
I don't see how it could help. IMO option (1) is more viable than the second one.
