### ISSUE TITLE
Undesired behavior using same libp2p Node-Key on many nodes

### ISSUE THREAD

**Issue by riusricardo** [paritytech/substrate#2624]
Running identical nodes could have an impact or destabilize the network.
It should not be allowed to run several nodes using the exact same identity parameters. Connected nodes are using unnecessary resources and opening/closing connections constantly. Even if the full multi-address is different, the connections keep switching.

These nodes don't need to be validators, so it could happen on a considerable scale without any way of being slashed or punished.

Is this an expected behavior?, or there should be a way to penalize a libp2p ID for being connected twice.

```
substrate --name Test-1 \
--node-key bf9f922a3faa37cabba98ba7a96d74e64435097f328eaf808acf355bc522832c \
--node-key-type Ed25519
```
```
substrate --name Test-2 \
--node-key bf9f922a3faa37cabba98ba7a96d74e64435097f328eaf808acf355bc522832c \
--node-key-type Ed25519
```

**Comment by tomaka** [comment]
We don't support using the same network key from multiple different nodes.

The network key **is** the node. If we receive a connection from a node whose identity is A while we're already connected to a node whose identity is A, we assume it's the same node and close one of the two.

> It should not be allowed to run several nodes using the exact same identity parameters.

I don't see how we could detect that.

> These nodes don't need to be validators, so it could happen on a considerable scale without any way of being slashed or punished.

We locally decrease the reputation value of a node every time it disconnects. Over time it will get less and less priority.

**Comment by riusricardo** [comment]
> We don't support using the same network key from multiple different nodes.

This makes total sense. My concern is related to some tests that I did on Polkadot where I forced two nodes to have the same network key, and they stayed connected to many peers. I can also say that my test was for just one day so I don't know how fast decreasing the reputation can help.

> The network key is the node. If we receive a connection from a node whose identity is A while we're already connected to a node whose identity is A, we assume it's the same node and close one of the two.
> We locally decrease the reputation value of a node every time it disconnects. Over time it will get less and less priority.

This is something I was thinking about, but this reputation goes down with time. Changing the key will create a "new" node identity. It remains as a possibility to use the same key as a way to attack and then rotate keys every few hours. There will be no way to decrease reputation at the needed speed to prevent the attack.

> I don't see how we could detect that. We know that we're talking to one node and not two based on the nodes' identity.

Neither do I. It looks to be a complex issue. Does the IP or the full multi-address could help?

**Comment by tomaka** [comment]
> This makes total sense. My concern is related to some tests that I did on Polkadot where I forced two nodes to have the same network key, and they stayed connected to many peers. I can also say that my test was for just one day, so I don't know how fast reputation should decrease to mitigate this.

This reputation system is pretty recent and not really fully implemented yet.

> This is something I was thinking about, but this reputation goes down with time. Changing the key will create a "new" node identity. It remains as a possibility to use the same key as a way to attack and then rotate keys every few hours. There will be no way to decrease reputation at the needed speed to prevent the attack.

On the other hands, the reputation is regular nodes will increase over time. If you create a new identity, you start below existing nodes.

Of course you could act benevolent for a while, until you build up reputation, then start being dishonest, but that means attacks don't last very long.

> Neither do I. It looks to be a complex issue. Does the IP or the full multi-address could help?

Some nodes could legitimately have multiple different ways to be reached.
Each node has generally at least both an IPv4 and an IPv6, and in the future maybe some connectivity through a proxy.
This would also raise the question of how long do you cache the IP address of a node. If my ISP decides to change my IP, I don't want nodes to refuse me because they think I'm now a different node.
Identifying a node based on its IP address or multiaddress is in my opinion a step in the wrong direction.

**Comment by riusricardo** [comment]
> This reputation system is pretty recent and not really fully implemented yet. From a technical point of view it's very easy to make it behave the way we want, but we're not sure exactly what "the way we want" is.

Great to hear that there is a work in progress solution :)

> On the other hands, the reputation of regular nodes will increase over time. If you create a new identity, you start below existing nodes.

Does starting from below creates a time restriction for connection retires or restricts number of nodes? 
When you launch a new node it will connect to many nodes, it could be part of this reputation to limit the initial connections and over time gain access to more nodes. By doing this the attack vector could be smaller.

> Of course you could act benevolent for a while, until you build up reputation, then start being dishonest, but that means attacks don't last very long.

Sound like the way to go. Working to increase your reputation is the best approach. 

> Some nodes could legitimately have multiple different ways to be reached.
Each node has generally at least both an IPv4 and an IPv6, and in the future maybe some connectivity through a proxy.
This would also raise the question of how long do you cache the IP address of a node. If my ISP decides to change my IP, I don't want nodes to refuse me because they think I'm now a different node.
Identifying a node based on its IP address or multiaddress is in my opinion a step in the wrong direction.

Agree, this is not the best approach, many ISPs change the IP very regularly. It can also expose the node to more attacks.



By the way, it seems that most of these concerns have already been analyzed. Thanks for replying :)
I just wanted to expose possible issues. If all this has been taken into account, do not hesitate to close the issue.

**Comment by tomaka** [comment]
> Does starting from below creates a time restriction for connection retires or restricts number of nodes?

Nodes would randomly periodically disconnect well-behaving nodes in order to leave room for newcomers.

We don't want to have, say, 25 nodes all connected together and the 26th cannot join because everybody is full.

**Comment by tomaka** [comment]
I'm going to close this unless you have further questions.
