### ISSUE TITLE
About verify first, write last

### ISSUE THREAD

**Issue by entropytech** [paritytech/substrate#2625]
I have read the tutorial at https://shawntabrizi.com/substrate-collectables-workshop/#/3/buying-a-kitty, which says "verify first, write last', 
I totally agree with that, however, I want to confirm the following: 

If something wrong happened when invoking function of runtime module, will the previous modification to the state be reverted to its original state?
If the answer is no, what's the purpose of commit_prospective and discard_prospective in module overlayed_changes.rs?

**Comment by bkchr** [comment]
You are not writing to the state directly, instead you first write into `OverlayedChanges`. If the transaction fails, it will not modify the state at all. But it all depends on your implementation.
