### ISSUE TITLE
Safe: Custom node Name should be deprecated or a new solution.

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/substrate#2626]
I think future the telemetry's custom node Name should be deprecated. Because, someone can set name: "polkadot-official"/ "authority"/ "coinbase" / "bitcoin.com" / "Binance"/ ... , Pretend to be the official node, there will be unfair ways to attract nominators. If it's large, it's a security risk.  
https://github.com/paritytech/substrate-telemetry/issues/147

**Comment by jiangfuyao** [comment]
https://github.com/paritytech/substrate-telemetry/issues/147

**Comment by bkchr** [comment]
I don't see any security problem because of node naming. Trusting a node because of its name sounds like a security error on your side. Nominating is not done by name and if you want to nominate `Binance`, then you should probably get the correct key to nominate from `Binance`.

**Comment by chevdor** [comment]
As I mentioned in https://github.com/paritytech/substrate-telemetry/issues/147, as of today, there are already a few checks in place to avoid polluting too much.
Names that are tool long, or url/email looking will not be accepted. I agree anyway with @bkchr, relying on the name in telemetry to pick a validator is probably the worst idea a user can have.
