### ISSUE TITLE
ext_now (ab)uses As<u64>

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2629]
`ext_now` uses the scratch buffer to return the timestamp value. However, it unnecessary truncates it to `u64` before encoding. 

It also tries to cache the value optimistically. I am not sure if that's a good way because in that case the origin pays for fetching the timestamp on every context creation instead of only when it is needed.

**Comment by Kianenigma** [comment]
Does this relate in any way to the `Remove-As` PR and refactor?

**Comment by pepyakin** [comment]
Yes. I can see that it is addressed in #2602 and thus it should close this issue.
