### ISSUE TITLE
ext_call/ext_create take the gas value by u64

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2630]
In `ext_call` and `ext_create` there is ability to specify how much gas we should devote for the nested execution context. Although the type of gas units can be changed and can potentially be `u128`, `ext_call` and `ext_create` take `u64`.

This one is not that simple because ideally we avoid specifying the exact value at all since it can be abused hardcoding the gas values.

**Comment by jimpo** [comment]
Hmm, one solution would be to change the signature of `ext_call` and `ext_create` to take a `gas_ptr` and `gas_len` and decode into a `Gas`.

I don't understand what you mean by "it can be abused hardcoding the gas values." Like the contract hardcodes the gas values? What is wrong with that?

**Comment by pepyakin** [comment]
> Hmm, one solution would be to change the signature of `ext_call` and `ext_create` to take a `gas_ptr` and `gas_len` and decode into a `Gas`.

Right, I'd like to avoid this since it involves two additional memory accesses performed from the runtime. Although that shouldn't be a big issue, since I don't think that `call` is a hot spot.

> I don't understand what you mean by "it can be abused hardcoding the gas values." Like the contract hardcodes the gas values? What is wrong with that?

Let's suppose that there is one contract A that wants to call a contract B. B's code is immutable and the developer of A can precalculate the gas prices that would be charged for execution of B. Let's suppose that the developer of A did exactly that and supplies a hardcoded value as an argument to the call. The value the exact same that is required.

Later, the gas price of one of the operations that performed on the course of execution increases by 1 (e.g. due to discovered issue with underpricing). Now, `A` is broken. Raising of gas prices is completely natural, since the network evolves and it might want to perform different decisions which might increase or decrease the gas prices.

One might argue that this is a documentation issue, and it could be communicated in docs that the gas values are not to be hardcoded and that error is completely A's developer fault. However, I am not sure if I agree since we have a counter-example in Ethereum where it seems that they announced this in their documentation, but at some point it was discovered that there is quite some contracts that depend on this.

**Comment by jimpo** [comment]
After offline discussion, @pepyakin and I agree that changing to `gas_ptr` + `gas_len` is a good improvement for now.

**Comment by jimpo** [comment]
Another option here would be to fix gas units as u64 in Substrate. This likely seems required to implement internal gas metering, where metering instructions do not require a call into the external environment each time.

**Comment by jimpo** [comment]
Fixed by #2944.
