### ISSUE TITLE
CLI flag to force all native execution mode

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2636]
If will be good if there is a flag to do something similar to `--block-construction-execution=native --importing-execution=native --other-execution=native --syncing-execution=native` but also force always native mode regardless the runtime version.

This is intent for debugging runtime. Breakpoints are not getting hit due to many reasons and one of them is the wasm executor is been used instead of the native executor.

I don't care if the native version is compatible or not (maybe print some warning if not compatible), I just want to debug it.

It is already hard enough to set breakpoints on external crate due to potentially mismatched git version (IDE present me one version and cargo use another one and hence breakpoint not working). It will be good if I can disable wasm executor to make debugging easier.

I now know how to do it properly, but I cannot teach everyone the all the approaches required to diagnostic why breakpoint is not working.

**Comment by fzzr-** [comment]
I'm interested this feature too.
