### ISSUE TITLE
Don't use `saturated_into` in informant

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#2652]
We should require the `BlockNumber` to implement `Display + Serialize` for the informant as a local where bound.

https://github.com/paritytech/substrate/pull/2602_

**Comment by tomaka** [comment]
The issue here is that the informant shows for example "4.2 blocks per second".
It's not really possible to have decimal values, unless we hack together something by printing `{}.{}` and assuming that the block is displayed as a number.

**Comment by tomaka** [comment]
A solution could be to use `TryInto<u128>`. If it succeeds, show decimals. If it fails, show a rounded integer.
