### ISSUE TITLE
Make `BlockNumber` in CLI generic as well

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#2653]
For some use cases in the CLI we require the `BlockNumber`, currently we assume the block number fits into `u32`. This is not correct and thus, we should make the CLI generic over the `BlockNumber` as well.

https://github.com/paritytech/substrate/pull/2602

**Comment by niklasad1** [comment]
@bkchr 

Do you mean that for example [these](https://github.com/paritytech/substrate/blob/master/client/cli/src/params.rs#L738-#L762) should take a type parameter instead in `u32`?

It doesn't seem possible to do with `structopt`, see https://github.com/TeXitoi/structopt/issues/128

**Comment by bkchr** [comment]
Yeah we should remove the `u32`. We could create your own type `struct BlockNumber(String)` that we use as parameter to structopt. `Parse` or whatever structopt uses would make sure that the given parameter is really a number and not a string. In Substrate itself we just put a bound on the "real" `BlockNumber` type that it needs to implement `From<String>` or something similar. I think that should work.
