### ISSUE TITLE
sr-primitives in v1.0 branch can fail compile as a transitive dep b/c of serde double-import

### ISSUE THREAD

**Issue by Sushisource** [paritytech/substrate#2663]
In any package which depends on a package than then in turn depends on sr-primitives (ex: I have a rust client which depends on my runtime, which depends on sr-primitives), if that package also uses serde (or even has any other transitive dependencies which do) and uses the `derive` feature rather than depending directly on `serde-derive`, sr-primitives fails to compile with:

```
error[E0252]: the name `Serialize` is defined multiple times
  --> /home/spencer/.cargo/git/checkouts/substrate-7e08433d4c370a21/779a28a/core/sr-primitives/src/testing.rs:20:5
   |
19 | use serde::{Serialize, Serializer, Deserialize, de::Error as DeError, Deserializer};
   |             --------- previous import of the macro `Serialize` here
20 | use serde_derive::Serialize;
   | ----^^^^^^^^^^^^^^^^^^^^^^^-
   | |   |
   | |   `Serialize` reimported here
   | help: remove unnecessary import
   |
   = note: `Serialize` must be defined only once in the macro namespace of this module

error[E0252]: the name `Deserialize` is defined multiple times
  --> /home/spencer/.cargo/git/checkouts/substrate-7e08433d4c370a21/779a28a/core/sr-primitives/src/testing.rs:22:5
   |
19 | use serde::{Serialize, Serializer, Deserialize, de::Error as DeError, Deserializer};
   |                                    -------------
   |                                    |
   |                                    previous import of the macro `Deserialize` here
   |                                    help: remove unnecessary import
...
22 | use serde_derive::Deserialize;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ `Deserialize` reimported here
   |
   = note: `Deserialize` must be defined only once in the macro namespace of this module
```

This is already fixed by 
https://github.com/paritytech/substrate/commit/0e6a407a13fbc5a5ad200645aed72bb8a8e528d7
or 
https://github.com/paritytech/substrate/commit/d45de4b37d0ff139056af2aa1e67e25b72b32369

As far as I can tell, and just needs to be backported to 1.0.  I can try to put together a PR if that would be accepted. Thanks!

**Comment by thiolliere** [comment]
Was it one of your issue @shawntabrizi ?

**Comment by shawntabrizi** [comment]
Yeah I ran into this issue when mixing up code between master and v1.0 branch.

I am not sure if this is consider a "breaking" change, but if not, then we should backport it :)

**Comment by thiolliere** [comment]
This should be fixed no ? open otherwise
