### ISSUE TITLE
Light-client Authority Set Handoffs

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#269]

**Comment by rphmeier** [comment]
This is desired for light-client-friendly tracking of authority set changes.

When the authority set changes from `A` to `A'` at a block `B`, The header of B will contain an `NewAuthorities(A')` event in the digest.

When an authority imports such a block and believes the change to be the result of a valid block execution, he generates a signature on a `HandoffAttestation(Hash(B), NewAuthorities(A'))` message and circulates it to other authorities. Upon witnessing such signatures from a majority of authorities, he accumulates them into a full `Justification(B, NewAuthorities(A'))` message.

When a full or light node imports a block with this kind of digest event, it waits to fetch a justification for the change before continuing to sync on top of that chain. Full nodes will save the justification permanently in the database.

Optimization: automatically provide the justification with any relevant blocks.

This can also be used for a fast warp sync with the caveat that it is vulnerable to long range attacks.

**Comment by gavofyork** [comment]
Done in #687

**Comment by svyatonik** [comment]
Not actually - we only have a `DigestItem` trait now - everything else is not ready yet.

**Comment by svyatonik** [comment]
Current state:
#687 : `DigestItem::AuthoritiesChange`
#726 : `DigestItem::AuthoritiesChange` is emitted when authorities set changes
https://github.com/paritytech/substrate/commit/1d0f52f967ae6c5c7ac4c3b0e584eb2684d1ea4e : (probably we don't need this at all) 'pausable' synchronization
TODO : generate && broadcast justification by authorities

**Comment by gavofyork** [comment]
@rphmeier @svyatonik is there still anything to do here for a functional & secure MVP of AfG/GRANDPA/SHAFT?

**Comment by rphmeier** [comment]
I'm not convinced we can get a light-client running for beta but perhaps for 1.0.
