### ISSUE TITLE
Panick when discarding state when there are active references to this state

### ISSUE THREAD

**Issue by svyatonik** [paritytech/substrate#2693]
Right now "competing" noncanonical states are physically removed from DB during canonicalization of the block ([here](https://github.com/paritytech/substrate/blob/master/core/state-db/src/noncanonical.rs#L289)). When someone holds the reference to the discarded state (that could be for example Aura preparing import of side block - i.e. it is not yet **importing** (which is protected by `import_lock`) but is calling for example [`check_inherents`](https://github.com/paritytech/substrate/blob/master/core/consensus/aura/src/lib.rs#L552)), this could lead to situation when state is discarded when someone still holds its reference. This leads to  panics like this:
```
thread 'ImportQueueWorkerthread '' panicked at 'ImportQueueWorker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0xd63aea6d77baf4f0b8e1eff1b898a5ca490c9a01566d1e3fba54fcfbb45fb8d9"Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0xd63aea6d77baf4f0b8e1eff1b898a5ca490c9a01566d1e3fba54fcfbb45fb8d9"', src/libcore/result.rs:', 997:5
```

One possible fix of the issue (initially proposed by @rphmeier ) is not to discard any state that someone holds reference to. @arkpar has agreed to help with this issue (big thanks!).

**Comment by svyatonik** [comment]
relevant traces:
https://gist.github.com/svyatonik/d3aeaa6866db033d1b1ff9ac27e3a285
https://gist.github.com/svyatonik/f4b2df26f9c13c060301c7f7dea7e06a
https://gist.github.com/svyatonik/3642e5168475184495bfbda4473d6b4d
https://gist.github.com/svyatonik/e2272174adb09dac6f788ac9a05c03cb

**Comment by JKingdom** [comment]
maybe related to our issue? #2637
