### ISSUE TITLE
"Warp" synch

### ISSUE THREAD

**Issue by bedeho** [paritytech/substrate#2698]
Is there any spec, documentation or implementation of "warp" sync, as mentioned here by Gav?

https://youtu.be/iUMZyL5kTwc?t=1294

**Comment by andresilva** [comment]
This isn't something that's part of our short-term roadmap so I don't think there's any spec or official documentation on it. The tricky part is proving GRANDPA authority set changes from genesis up until the snapshot block. To do that I expect we'll be able to reuse the existing finality proofs that we have for the light client (https://github.com/paritytech/substrate/blob/master/core/finality-grandpa/src/finality_proof.rs#L17).
We'll also want to generalize the warp sync to work with arbitrary consensus engines, so I guess we'll just have a way for consensus engines to plug in their own snapshot logic.

**Comment by andresilva** [comment]
Ref: #1208

**Comment by bedeho** [comment]
Thank you for your prompt reply.

Tendermint/Cosmos also advertises something equivalent to warp synch, but they never provide a robust explanation of how it exactly is supposed to work, and what the security model is.

I am not totally sure what you mean by snapshot, but perhaps I can quickly state what I was expecting Warp synch to allow. A light client can go offline from some block height H, where it knows the validator set V(H) in some way, and then come back _at any block height_ H+k (k>0), and be able to authenticate whether the claimed validator set for H+k is, in fact, genuine _without_ downloading O(k) block headers. This all happens with the same security model as normal light client protocol where one does, in fact, download all headers, but does not validate any extrinsic processing.

Is this what you mean?

**Comment by rphmeier** [comment]
Yup, the linked issue describes a way to do it for GRANDPA.

**Comment by NukeManDan** [comment]
Might be getting close?
https://github.com/paritytech/substrate/pull/9227

**Comment by bkchr** [comment]
Yeah it is done.
