### ISSUE TITLE
Contract ext_dispatch_call refactor

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#2705]
Restoration mechanism has been implemented as an extrinsic call that contract can call using `ext_dispatch_call`. Even though that this extrinsic is technically available to be called by any user, it can only be meaningfully called by a contract (i.e. it bails out if called by an account without code).

We could refactor into the following architecture:

```
enum Delayed {
    DispatchCall(call)
    SendEvent(event)
    RestoreTo(...)
}
```

and merge events and calls fields of ExecutionContext into a delayed field.

CC @pepyakin

**Comment by pepyakin** [comment]
This is also related to suicide/selfdestruct.
