### ISSUE TITLE
Please upgrade `node-template` for substrate 1.0

### ISSUE THREAD

**Issue by RyanKung** [paritytech/substrate#2722]
node-template is not work on v1.0 rc.

I tried to upgrade my project, but here are too many changes without detailed Document and example.

**Comment by bkchr** [comment]
Cc @shawntabrizi

**Comment by shawntabrizi** [comment]
@RyanKung I will take a look right away, but in the meantime please take a look at https://github.com/shawntabrizi/substrate-package

**Comment by RyanKung** [comment]
@shawntabrizi Cool, I will check it, Thank you
