### ISSUE TITLE
why create a new user within the dockerfile?

### ISSUE THREAD

**Issue by zscole** [paritytech/substrate#2728]
what's the logic behind this decision? it increases build time and adds unnecessary overhead. is there any particular reason the `substrate` user is added? by default, docker has root access.

**Comment by bkchr** [comment]
About which `Dockerfile` do you speak?

And I also don't understand why adding a user adds overhead?

**Comment by zscole** [comment]
https://github.com/paritytech/substrate/blob/master/Dockerfile

> And I also don't understand why adding a user adds overhead?
For our purposes, we have to be able to essentially SSH into containers in order to perform particular actions which could be made more complicated by adding a username. 

I rewrote the [Dockerfile](https://github.com/Whiteblock/dockerfiles/blob/master/substrate/Dockerfile) for our purposes though.

**Comment by bkchr** [comment]
I still don't understand your problem.
