### ISSUE TITLE
Avoid allocating 0-len vectors when crossing WASM boundary

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#2730]
See comment: https://github.com/paritytech/substrate/pull/2615#discussion_r287416956

This code needs changing:
https://github.com/paritytech/substrate/blob/11f7b6ab49779a469cb2edffc5bad2cb63a3e2c9/core/sr-io/without_std.rs#L1065-L1074

Along with all `this.heap.allocate(0)` calls in the `wasm_executor.rs`

**Comment by tomusdrw** [comment]
Changing the label since it seems that actually we might be leaking memory if our allocator does allocate something even if `0` len is given (which I believe it does).

That's because `RawVec` (created via `from_raw_parts`) does not deallocate given pointer if capacity is `0`:
https://github.com/rust-lang/rust/blob/master/src/liballoc/raw_vec.rs#L710

**Comment by expenses** [comment]
I'm a little confused here. If `len` is 0, can't we just return `Some(Vec::new())`? Or are you concerned that the capacity would be higher?

**Comment by bkchr** [comment]
Closing in favor of https://github.com/paritytech/substrate/issues/3561
