### ISSUE TITLE
error: Could not compile `srml-staking`

### ISSUE THREAD

**Issue by Tore19** [paritytech/substrate#2742]
macos

curl https://sh.rustup.rs -sSf | sh
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
rustup update stable
cargo install --git https://github.com/alexcrichton/wasm-gc
brew install cmake pkg-config openssl git llvm

Then
cargo install --force --git https://github.com/paritytech/substrate subkey

It showed that

error[E0277]: the trait bound `usize: _IMPL_DECODE_FOR_RewardDestination::_parity_codec::Encode` is not satisfied
  --> /Users/zhangtong/.cargo/git/checkouts/substrate-7e08433d4c370a21/c93ca93/srml/staking/src/phragmen.rs:75:2
   |
75 |     /// Index of the candidate stored in the 'candidates' vector.
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `_IMPL_DECODE_FOR_RewardDestination::_parity_codec::Encode` is not implemented for `usize`

error[E0277]: the trait bound `usize: _IMPL_DECODE_FOR_RewardDestination::_parity_codec::Decode` is not satisfied
  --> /Users/zhangtong/.cargo/git/checkouts/substrate-7e08433d4c370a21/c93ca93/srml/staking/src/phragmen.rs:75:2
   |
75 |     /// Index of the candidate stored in the 'candidates' vector.
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `_IMPL_DECODE_FOR_RewardDestination::_parity_codec::Decode` is not implemented for `usize`
   |
   = note: required by `_IMPL_DECODE_FOR_RewardDestination::_parity_codec::Decode::decode`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `srml-staking`.

**Comment by Tore19** [comment]
Linux. The same error too.

**Comment by gautamdhameja** [comment]
PR https://github.com/paritytech/substrate/pull/2743 should fix this.

**Comment by Tore19** [comment]
Hi, it showed this error just now.

error[E0277]: the trait bound `usize: _IMPL_DECODE_FOR_Call::_parity_codec::Encode` is not satisfied
   --> /Users/zhangtong/.cargo/git/checkouts/substrate-7e08433d4c370a21/4a14361/srml/aura/src/lib.rs:170:2
    |
170 |     start_slot: usize,
    |     ^^^^^^^^^^ the trait `_IMPL_DECODE_FOR_Call::_parity_codec::Encode` is not implemented for `usize`

error[E0277]: the trait bound `usize: _IMPL_DECODE_FOR_Call::_parity_codec::Encode` is not satisfied
   --> /Users/zhangtong/.cargo/git/checkouts/substrate-7e08433d4c370a21/4a14361/srml/aura/src/lib.rs:172:2
    |
172 |     skipped: usize,
    |     ^^^^^^^ the trait `_IMPL_DECODE_FOR_Call::_parity_codec::Encode` is not implemented for `usize`

error[E0277]: the trait bound `usize: _IMPL_DECODE_FOR_Call::_parity_codec::Decode` is not satisfied
   --> /Users/zhangtong/.cargo/git/checkouts/substrate-7e08433d4c370a21/4a14361/srml/aura/src/lib.rs:170:2
    |
170 |     start_slot: usize,
    |     ^^^^^^^^^^ the trait `_IMPL_DECODE_FOR_Call::_parity_codec::Decode` is not implemented for `usize`
    |
    = note: required by `_IMPL_DECODE_FOR_Call::_parity_codec::Decode::decode`

error[E0277]: the trait bound `usize: _IMPL_DECODE_FOR_Call::_parity_codec::Decode` is not satisfied
   --> /Users/zhangtong/.cargo/git/checkouts/substrate-7e08433d4c370a21/4a14361/srml/aura/src/lib.rs:172:2
    |
172 |     skipped: usize,
    |     ^^^^^^^ the trait `_IMPL_DECODE_FOR_Call::_parity_codec::Decode` is not implemented for `usize`
    |
    = note: required by `_IMPL_DECODE_FOR_Call::_parity_codec::Decode::decode`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `srml-aura`.

**Comment by Tore19** [comment]
should remove unneeded derive(encode/decode) in file https://github.com/paritytech/substrate/blob/master/srml/aura/src/lib.rs, just like #2743, right?

**Comment by Kianenigma** [comment]
@rphmeier @DemiMarie-parity ^^

**Comment by bkchr** [comment]
This was a result of releasing a version of `parity-codec` that  did not follow semver versioning. We purged the version and this should now be fixed.

**Comment by Tore19** [comment]
It works now. Thank you guys.
