### ISSUE TITLE
Add "pub" attribute to who/value of "IndividualExposure" in srml/staking.

### ISSUE THREAD

**Issue by hexinlee** [paritytech/substrate#2746]
Hi, I queried srml/staking->stakers to obtain the nominator vote details, and the struct "Exposure" was decoded successfully. However, when I translated "IndividualExposure->who(AccountId)" to human readable ss58address, founding "who" & "value" fields are private.
Could you please change the attributes to "pub" for internal fields of "IndividualExposure"?

Below is the code:
// the result is the response of Staking->Stakers storage api from node using ws.
let result = "0x9ee898fe80efae19f2e50d202b2437d0d45a38acccffac50f471319363fed9580f00e853acb584230f00a8d99bc22923040b00407a10f35a4944";

// hex to Vec<u8>
let mut result_vec = hexstr_to_vec(result);	

// here I can obtain stakers: Option<Exposure<AccountId, Balance>>
let stakers = Decode::decode(&mut result_vec.as_slice());

// here I can obtain the first element of others field in struct IndividualExposure<AccountId, Balance: HasCompact>:
let stakers_others_first = stakers.unwrap().others[0];

// problem coming!!! The who is private!!! Below code can't work!
let who = stakers_others_first.who;

Thank you guys.

**Comment by Kianenigma** [comment]
We talked in riot as well. I am not 100% if your issue is caused by the field being private (don't really know the metadata and how clients/UIs fetch + decode info), but as I speculated it seems like for instance, the PolkadotJS apps can easily read these values so the problem must be somewhere else. For example, I got this log from running a script to fetch staking info on Alexander:
```
[true] Fetched info for {
 "stash":"5F6UVPBSgtmm9arX1aWPrkB1QuHEHDvQYmBeEG1uTzvNSq8W",
 "ctrl":"5HCAVxJAidmCT8JUma8zTtosnfggsvHZ6rjEvz6pHD7wto7n",
"ledger":null,"
elected":true,
"stakers":{"total":1100057128894858,"own":400059064025482,"others":[
{"who":"5G1FCJQaEpminnUQr5K4H2GMQBkEphbnhFa5JKyDtYWfzusf","value":699998064869376}]}}
```

This is a working account, so you should be able to verify. CC @jacogr

**Comment by jacogr** [comment]
On the Polkadot-JS side -

- the data we get back from the node is SCALE encoded
- we have implementations for each of the substrate types 
- when decoding the data, we map (via the metadata types) in the correct type

So any pub/non-pub on the Rust side does not affect JS. Basically if the data is in the encoded binary blob, we will decode it and provide access to it via the re-implemented structs.

**Comment by hexinlee** [comment]
I checked JS code, it uses "readable" attribute for the private fields in Rust version. That's the reason in JS the "private" field can be access. I tried creating another similar struct in my own project, adding "pub" attribute, it can be also decoded successfully. So the problem solved.  Anyway, thank you guys. @Kianenigma @jacogr
