### ISSUE TITLE
question: why substrate need to occupy so large storage?

### ISSUE THREAD

**Issue by AtenJin** [paritytech/substrate#2756]
Hi, we are ChainX
Our mainnet is running for a week, we notice substrate need a large storage.

our nodes are just running for a weak, and the storage has already occupied for more than 4GB! It's obviously that the real data could not occupy so large space just in a weak.

and when look up the files in `db` (`<rootpath>/chains/<xxxx>/db`)
the `*.sst` files occupy 3.9GB
```bash
-># ls -alF *.sst | awk '{sum+=($5/1024/1024)} END {print "Sum = ", sum}'
Sum =  3904.85  # this is MB
```
the `*.log` files occupy 290M
```bash
-># ls -alF *.log | awk '{sum+=($5/1024/1024)} END {print "Sum = ", sum}'
Sum =  290.101  # this is MB
```
and all files occupy 4.2GB:
```bash
-># du * -sh
4.2G	db
8.0K	keystore
8.0K	network
```

and the archive mode  node(`--purning=archive`) is more than 4.9GB now.
we don't know why substrate node need so large space.

we start the node with default parameters, is there any other parameters could reduce the space occupation?
(our block is 2 second one block, and at now, there is just 2~5 extrinsics in a block(include inner extrinsic))

**Comment by gguoss** [comment]
@bkchr ping

The amount of data stored on the substrate is increasing too fast. Is there a solution?

**Comment by arkpar** [comment]
@JKingdom Could you run with `-l state-db=trace` for a few minutes and post the output here?

**Comment by maticko** [comment]
I'm experiencing the same issue, running network for ~26 days, with 6s blocks, so around ~387,000 blocks and nodes consume between 4-8GB disk space. But they all run in the same mode. The only difference is for how long they run.

**Comment by bkchr** [comment]
@maticko is your network finalizing?

**Comment by maticko** [comment]
@bkchr it did for some time, but now it's not and even nodes don't agree what is the last finalised block. For example, some nodes are saying block ~188k is last finalised, others are saying ~242k is last finalised.
