### ISSUE TITLE
Support tuples for `OnNewAccount` hook in Balances module

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#2763]
Runtime developers may want to trigger multiple functions when a new account is created, however this is not currently supported for `OnNewAccount` like it is for other hooks.

We should also look through the other modules and make sure that their hooks also support tuples.

**Comment by xlc** [comment]
[EventHandler](https://docs.microsoft.com/en-us/dotnet/api/system.eventhandler-1?view=netframework-4.8) pattern is commonly used in C#. Does it make sense to have something similar here to make those callback / event handler easier to use?

Something like
```
trait EventHandler<T> {
    fn onEvent(args: T);
}

struct SomeEvent {
   foo: u32
}

trait Trait {
    type OnSomeEvent: EventHandler<SomeEvent>;
}

impl<T> EventHandler<T> for () 
impl<T, A: EventHandler<T>, B: EventHandler<T>> EventHandler<T> for (A, B) 
....

impl my_module::Trait for Runtime {
   OnSomeEvent: (ModuleA, ModuleB)
}
```

The goal is avoid update each individual trigger to make them support multiple handlers.

Also, is there a proper name for this pattern? Trigger? Callback? I will want to call it event but there is already another event in Substrate.
