### ISSUE TITLE
BlockNumber is still converted to u32/u64 in substrate-client-db and substrate-state-db

### ISSUE THREAD

**Issue by svyatonik** [paritytech/substrate#2766]
originally noted in: https://github.com/paritytech/substrate/pull/2666#issuecomment-498247402

example conversions:
https://github.com/paritytech/substrate/blob/e45524e52925557d182bb8bbe9d8fa4a2182beb5/core/client/db/src/utils.rs#L86
https://github.com/paritytech/substrate/blob/e45524e52925557d182bb8bbe9d8fa4a2182beb5/core/state-db/src/lib.rs#L192

**Comment by EmmanuellNorbertTulbure** [comment]
Is this still relevant @svyatonik ? Asking to know if I should migrate it or not.

**Comment by svyatonik** [comment]
Don't know for sure, but let's assume it isn't
