### ISSUE TITLE
Transaction Fees: 80% to treasury, 20% to block producer

### ISSUE THREAD

**Issue by nczhu** [paritytech/substrate#2769]
*Wanted to put up an issue for this as it’s important for K, please CRUD this issue as needed.*

[Detailed research here](http://research.web3.foundation/en/latest/polkadot/Token%20Economics/#relay-chain-transaction-fees)

### How a transaction fee is constituted and split
There will be several types of transactions, with different fee levels. This fee differentiation is used to reflect the different costs in resources incurred by transactions, and to encourage/discourage certain types of transactions. Thus, we need to analyze the resource usage of each type of transaction, to adjust the fees (to be done).

Part of the transaction fee needs to go as a reward to the block producer for transaction inclusion, as otherwise they would have an incentive not to include transactions since smaller blocks are faster to produce, distribute and incorporate in chain. However, the block producer should not be rewarded the full amount of the fee, so they are discouraged from stuffing blocks. 

**How much of the tx fee goes to the block producer is an adjustable parameter via governance; we originally suggest 20%, and suggest that the other 80% go to treasury (instead of burning) to keep better control of inflation/deflation).**

This percentage might depend on the transaction type, to encourage the block producer to include certain tx types without necessarily increasing the fee.

@0x7CFE @Kianenigma

**Comment by gavofyork** [comment]
spreadsheet has this as @0x7CFE . now it's @Kianenigma ? would be good to keep the issue and spreadsheet aligned with each other and reality.

**Comment by Kianenigma** [comment]
My mistake. I am not directly assigned to this.

**Comment by Kianenigma** [comment]
Ain this done by now? https://github.com/paritytech/substrate/pull/2912
