### ISSUE TITLE
`decl_module!` allow procedural macro to work on calls function

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#2782]
Currently we only provide doc attribute for dispatchable call.

But some module maker could want to add more logic make use of procedural macros.

Would it be interesting to allow this users to make use of regular attribute ?

Pros:
* User can make use of procedural macros to add logic on calls in a very efficient way.

Cons:
* This expose our implementation into some kind of APIs, the way we implemented this distpatchable function would now be constrained because some user have macros that expect previous result.
* This is quite touchy in regards to what we auto-generate like `Ok(())` for instance.

Finally I feel not in favor of it considering the potential complexity it brings in regards to backward compatibility and APIs.

@gautamdhameja 
@bkchr ?

**Comment by bkchr** [comment]
Do you have any procedural macro in your mind that would be helpful?

**Comment by gautamdhameja** [comment]
I was thinking of custom attribute macros which can check a condition before a function executes. For example - access control, logging, etc.

**Comment by thiolliere** [comment]
This will be fixed by https://github.com/paritytech/substrate/pull/6877

Basically the macro does it take information from the dispatchables implement block but doesn't touch other attribute macro. Thus other macro can expand and modify the inner content of the dispatchables after the pallet macro attribute has read its information and expanded its stuff (elsewhere, it doesn't touch the implement block).

For instance transactional annotation is supported without any change in the pallet attribute macro.

Though what is not expanded is a macro which would modify the signature of the dispatchable.
E.g. if a macro add an argument to a dispatchable, then, as pallet macro is executed first, pallet macro doesn't have the added argument information and the pallet macro expansion will be invalid.

**Comment by thiolliere** [comment]
So if someone need to execute a macro prior to `pallet` macro then he currently cannot do easily.

Maybe we provide a macro helper to execute some macro defined inside a macro:

```rust
execute_foo! {
#[pallet]
mod pallet {

....
foo!{ ... }
}
```

So execute_foo would search for keyword `foo!` and then take its input and then execute it and replace `foo! {.. }` with the result.

If ppl have strong need for it then I can try to come up with something.
