### ISSUE TITLE
Build binary releases for OSX

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#2787]
Pre-built binary packages [like this](https://releases.parity.io/substrate/x86_64-debian:stretch/latest-v1.0/substrate) are useful for quickly exploring and learning about the substrate node. Create packages for targeting OSX as well.

Homebrew is probably a good package manager to target.

This is a focused spinoff of #2534 .

cc @amaurymartiny @TriplEight

**Comment by amaurymartiny** [comment]
Before targeting homebrew/dmg/pkg (maybe leave that to the community to manage?), just a simple binary would be enough imo.
