### ISSUE TITLE
Build binary releases for windows

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#2788]
Pre-built binary packages [like this](https://releases.parity.io/substrate/x86_64-debian:stretch/latest-v1.0/substrate) are useful for quickly exploring and learning about the substrate node. Create packages targeting Windows as well.

An exe or msi installer would probably be a reasonable way to distribute the software.

This is a focused spinoff of #2534 .

cc @amaurymartiny @TriplEight

**Comment by amaurymartiny** [comment]
Before an exe or msi installer, just a simple binary would be enough imo.

**Comment by bkchr** [comment]
Could you please move all your 3 issues into one issue and just make a bullet list. We don't need so many redundant issues.

**Comment by JoshOrndorff** [comment]
I created three separate issues based on I've opened this issue https://github.com/paritytech/substrate/issues/2818

I hope there will be a best practice for fast-forwarding the blockchain during testing.
`System::set_block_number(System::block_number() + 1);` is not sufficient if any of your runtime uses `on_initialize` or `on_finalize`.

I'm fine with either approach.

**Comment by JoshOrndorff** [comment]
I created three separate issues based on https://github.com/paritytech/substrate/issues/2534#issuecomment-498822374

I'm fine with either approach.

**Comment by bkchr** [comment]
I know that you created 3 separate issues, but we don't want to spam the issue tracker.
