### ISSUE TITLE
Package linux binaries as rpm

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#2789]
Pre-built binary packages [like this](https://releases.parity.io/substrate/x86_64-debian:stretch/latest-v1.0/substrate) are useful for quickly exploring and learning about the substrate node. Package these builds as RPMs as well as debs.

This is a focused spinoff of #2534 .

cc @amaurymartiny @TriplEight

**Comment by DemiMarie-parity** [comment]
We also need to ensure that the packages are signed by a key that Parity controls.  Will @kirushik be in charge of managing that key?

**Comment by kirushik** [comment]
We are actually a little bit stuck in designing a "clean room" build system for building the final releases and signing them.
The plans certainly include rpm and deb repositories; we're not 100% sure if those will be distro-agnostic, or if we will have to depend on certain distro-specific ABIs and make those packages distro-specific.

I cannot give any ETA on when it will happen; also we will probably look into publishing parity-ethereum there first, using that project as a test ground.
