### ISSUE TITLE
Use storage append when possible.

### ISSUE THREAD

**Issue by mattrutherford** [paritytech/substrate#2794]
When making multiple RPC calls to `democracy::propose()` the execution appears to slow down exponentially.

eg:

```javascript
api.tx.democracy
    .propose(api.tx.balances.setBalance(random_address, 5000, 123),500)
    .signAndSend(sender, { nonce });
```

By the time we have sent approximately ~4k tx, transaction processing is stalling, maybe 2-4tps.

**Comment by Kianenigma** [comment]
(assigning myself as in I will investigate. No clue what might come out of it)

**Comment by mattrutherford** [comment]
Additional info: around 3000 tx we get occasional messages ~:

`Discarding proposal for slot 390066160; block production took too long`

Isolating the time spent in the `propose` function (native execution) - is ~300ms per call by the time we reach this level of active proposals (~3k). In contrast, the first calls to `propose` when there are few pending proposals take around 50μs, in this case a 6000x performance degradation. 

There are similar but not quite as severe degradations in `council::motions::propose` and `vote`, each degrading exponentially with number of pending proposals.

The number of tx included per block seem to fluctuate a lot at this level and it might be interesting to log block production time.

**Comment by mattrutherford** [comment]
It's `Self::public_props()` that gets slower :

https://github.com/paritytech/substrate/blob/698e5af4a56b229773082e0a256acecaf7727c3e/srml/democracy/src/lib.rs#L339

**Comment by Kianenigma** [comment]
So this is the getter function for the storage value:

https://github.com/paritytech/substrate/blob/698e5af4a56b229773082e0a256acecaf7727c3e/srml/democracy/src/lib.rs#L247-L248

And the only _write_ to storage items is in the same function that you are benchmarking:

https://github.com/paritytech/substrate/blob/698e5af4a56b229773082e0a256acecaf7727c3e/srml/democracy/src/lib.rs#L343-L345

My initial perspective:

- Using `Vec<T>` as a sotrage item is _not ideal_ but with 4k elements, it shouldn't become exponentially slow to read. Are you 100% positive that the read from storage is the bottleneck?
- Any idea how big each `proposal` is? if it is very large, then it can explain the situation.

**Comment by mattrutherford** [comment]
Here's some timings for those lines in question, along with overall time for the propose function:

`let mut props = Self::public_props();` = 120545μs, 
`props.push((index, (*proposal).clone(), who));` = 47μs, 
`<PublicProps<T>>::put(props);` = 141μs
total fn time = 120762μs

The proposal is just a balances::set_balance, so my assumption is that it's relatively small.

**Comment by bkchr** [comment]
> And the only _write_ to storage items is in the same function that you are benchmarking:
> 
> https://github.com/paritytech/substrate/blob/698e5af4a56b229773082e0a256acecaf7727c3e/srml/democracy/src/lib.rs#L343-L345
> 

This should clearly use `<PublicProps<T>>::append((index, (*proposal).clone(), who)); ` as this is much much faster for bigger vectors.

**Comment by Kianenigma** [comment]
Right-- I never noticed this for `StorageValue` and strangely I think it is not really used _anywhere_ in substrate where we are storing a `Vec<T>` as raw value (except for events).

**Comment by bkchr** [comment]
I implemented this end of April, to overcome performance problems with `Events`. So, this is probably the reason it is not used that much :D

**Comment by mattrutherford** [comment]
I just tried the same test using `append` and can confirm this basically fixes the problem, as expected, with performance improvement everywhere. Initially fn time is now ~20μs and after 3300 tx only increasing to around ~60μs.

**Comment by bkchr** [comment]
@mattrutherford Can you let it run for a while and see if the time still increases? Factor 3 is already a lot.

**Comment by Kianenigma** [comment]
Noting that this is in-progress but needs some updates to parity-scale-codec first. 
https://github.com/paritytech/parity-scale-codec/pull/101
