### ISSUE TITLE
state_queryStorage is too verbose

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2826]
The `state_queryStorage` RPC method enumerates storage entries that were changed between the given blocks. However, the resulting list size is proportional to the number of blocks not the number of changes. It would be great if we could omit the storage entries that were unchanged.

cc @svyatonik

**Comment by tomusdrw** [comment]
@pepyakin Wouldn't it be better to introduce a different RPC method for that then? like `state_diffStorage(blockA, blockB)`?
AFAIR the point of `queryStorage` was to be able to trace all changes that happened since given block.

**Comment by pepyakin** [comment]
> AFAIR the point of queryStorage was to be able to trace all changes that happened since given block.

What I was trying to convey is that it encodes no changes as an empty array whereas it could just omitted.

**Comment by tomusdrw** [comment]
Oh, is it? Then yeah, we could simplify that. I think we don't do that if changes trie is disabled, so probably the behaviour differs there.
