### ISSUE TITLE
srml-contract: Ditch the input buffer

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2829]
At the present srml-contract has notion of an input buffer. When a contract is invoked the data passed as input is stored in this buffer and stays available until the execution context for that contract is disposed.

It looks like we can remove this buffer and reuse the scratch buffer instead of it. This should work because at present the scratch buffer for a newly created execution context is empty, as well as when `call`/`instantiate` returns the buffer either is wiped (in case of a trap) or filled with the output data (in case of `call`) or the address of a contract (in case of `instantiate`). The latter can be changed to the output data of an instantiate though.

**Comment by Robbepop** [comment]
I like unifying the input and scratch buffer. How is the exact design for this?
I think for the purpose of clear usage we want to do the following:

Remove
```rust
fn ext_input_len
fn ext_input
```
And replace it with
```rust
fn ext_input_buffer() -> u32
```
Which simply returns the length of the input buffer and copies the input buffer contents into the scratch buffer so that the next call to copy from scratch buffer returns the input buffer data.

**Comment by pepyakin** [comment]
My thinking was that the input data would be stored in the scratch buffer at the beginning of the call. Then the contract would copy this data to its linear memory before calling other functions that clobber the scratch buffer (such as `ext_get_storage`).

This approach, compared to the status quo and yours, will allow us to not store the input buffer throughout the whole lifespan of the execution context thus lowering peak memory usage in some cases. That said, this is not the primary benefit that I am interested in, the primary benefit is small simplification of the srml-contract.

**Comment by Robbepop** [comment]
It is a good point that we can drop the input buffer after it has been received once.
However, my only fear is that this introduces some kind of implicit state in the mechanism of copying from the scratch buffer.
I am fine with your proposed approach thought and I currently do not see any major pitfalls besides this implied state that is never really beautiful to have.

**Comment by pepyakin** [comment]
Yeah, although we already have this, since the scratch buffer already has this implicit stateful behavior: the data is retained until the next call.
