### ISSUE TITLE
srml-contract: Return data from `instantiate`

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2830]
For now, when a contract is being isntantiated by another contract, there is no way to return data from the instantiatee to the instantiator.

The scratch buffer is filled with the address of the created contract. If the instantiated contract returns data it is discarded similiarly to the output of the top-level executions.

There are a few ways to solve this problem, e.g.:

- Encode with SCALE a tuple of `(AccountId, Vec<u8>)` and return that,
- #2831

**Comment by Robbepop** [comment]
Do we have concrete use cases for this? Returning the address of the newly created contract seems to be useful, but what about the other data? Also in ink! we want to encode this into a contract definition.

**Comment by pepyakin** [comment]
I think it should be useful though not required to return this additional data from a constructor. This limitation seems to be artificial.

**Comment by jimpo** [comment]
A SCALE encoding of `(AccountId, Vec<u8>)` seems inconvenient as presumably the contract that wants to decode needs to have SCALE library code, which is non-trivial. Since `AccountId` is `Sized`, is it OK to just concatenate the contract address and return data directly?

**Comment by pepyakin** [comment]
Actually, we already depend on SCALE to some degree. Basically, every call that saves some value in the scratch buffer does it with `.encode` which encodes it with SCALE.

OTOH, I believe that so far practically only trivial types are encoded (i.e. no vec, thus no compact encodings etc), so adding a vector would be quite a stretch...

I am not sure what `Sized` has to do here. You don't want to take the raw representation of it and just dump it in the scratch buffer, right?

**Comment by jimpo** [comment]
Well, if it's `Sized` then it should have a constant-sized encoding (not just raw representation). Or is that not true in general? Regardless, account IDs specifically should have a fixed size encoding, depending on their type definition, no?

**Comment by pepyakin** [comment]
Yeah, I think this is not true in general. If `x: Box<dyn Encode>` is `Sized`, however, you cannot tell `x.encode().len()` or its upper bound.

Regarding `AccountId`, this might be true for the node-runtime, but I am not sure about it in general. 

This problem is similar to what we had in #2831. It is not clear if we can assume the upper bound or if it is feasible to do so.

**Comment by jimpo** [comment]
Discussed offline. An option for encoding that shouldn't carry much decoding complexity is to write the account ID into the scratch buffer, encoded with SCALE, then any data remaining in the scratch buffer after the account ID is return data. If account IDs can be encoded with fixed size (which should often be the case), then there is no need to encode any lengths.

**Comment by jimpo** [comment]
We still haven't come up with an ideal proposal, but the two leading options seem to be:

1) On successful instantiation, fill the scratch buffer with the concatenation of SCALE-encoded AccountId with the return data. To decode, first decode the AccountId and whatever remains in the scratch buffer is return data. On a failed instantiation with a failing exit status, the scratch buffer just contains the return data. The downside is just that it's a little weird for the scratch buffer to have an AccountId just on successful contract instantiation and be different for `ext_call` and failing instantiations.

2) Add a separate `ext_instantiated_address`, which fills the scratch buffer with the AccountId of the last successfully instantiated contract in a call context. This adds more state to the call context, but allows us to leave the scratch buffer with return data in all calls to `ext_call` and `ext_create`.

**Comment by athei** [comment]
Is now part of https://github.com/paritytech/substrate/issues/6355
