### ISSUE TITLE
srml-contract: return chain-specific types bypassing the scratch buffer

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2831]
We decided to settle on the scratch buffer in contrast to capped outputs with manual reservation of memory in a contract's linear memory and other considered approaches. 

However, one idea that might be still applicable and benificial is returning data of chain-specific types (i.e. data types that are specified via configuration traits, like `T::Balance`) bypassing the  scratch buffer. 

For example, now we have `ext_gas_left()` function which returns via the scratch buffer the amount of gas left at the moment of calling this function. In order to get the value of gas left the user will have to call

```
ext_scratch_copy(
  ptr,  // The pointer to pre-allocated area of length `len`.
  0,    // The offset from the start of the scratch buffer from where to start copying
  len,  // The expected length of the buffer or the output of `ext_scratch_size`.
);
```

and then deserialize the value from `T::Gas`.

If the value were returned directly bypassing it would be more efficient. One obvious drawback is that it won't be longer possible to preallocate a vector for the size of contents of the scratch buffer, the client code has to **know the sizes up-front**. 

However:

1. It is clear that serialized sizes of these configuration types should have some upper bound (otherwise, they won't be usable even in the scratch buffer model where there are memory limits in place). More likely the sizes would be a constant (i.e. lower = upper bound) and even yet liker they would be small. (Consider `T::Gas`, `T::Balance`, `T::Hash`, `T::AccountId`)
2. Contracts will be instantiated for the target chain anyway, so they will have to know what types the srml-contract is instantiated with. So they can hardcode the upper bounds of the sizes of SCALE serialized versions of these types.

At first it seems that this solution cements serialized sizes upper bounds (i.e. increase will lead to breakage of already deployed contracts). But on a closer inspection, that situation can only happen if we have an enum and we add another variant to it which the serialized size is greater than the previous upper bound of the type and adding another variant to an enum is a a problem for the already deployed contracts by itself.

This should solve #2830.

**Comment by Robbepop** [comment]
From the perspective of ink! the only problem I see is that determination of encoding length is sometimes harder than one might suspect and generally cannot be derived automatically.
So even though we look at a simple thin-wrapper around `i32` (e.g. `struct Foo(i32)`) its encoding might be very different from that of a `i32`.

So types that want to bypass the scratch buffer need to explicitely communicate their encoding lengths which in general has to be kept in sync manually by the respective developer of that particular code. This might become painful.

Besides that I think we should definitely benchmark this if possible so that we do not introduce a lot of performance for near to no gains.

**Comment by pepyakin** [comment]
> So types that want to bypass the scratch buffer need to explicitely communicate their encoding lengths which in general has to be kept in sync manually by the respective developer of that particular code. This might become painful.

Yes I agree, and in fact, this whole issue is built around the assumption that the sizes of these types won't be changing, since I as I wrote I think it will break the contracts anyway. However, I am not 100% sure about this, and it might need further investigation and planning.

> Besides that I think we should definitely benchmark this if possible so that we do not introduce a lot of performance for near to no gains.

Yes, it is hard to disagree. However, for the moment it we have a problem: it is not yet clear if it will tell us something useful since our environment doesn't yet correspond to what we would want to have in the future. For one, compilation can make a difference here. But more importantly, we assume that communication between a contract and the runtime via the substrate wasm sandboxing capability has noticeable overhead but there are already some changes we have in mind:

1. I have some ideas how to make sandboxing more efficient, which might just invalidate its slowness assumption.
2. Process sandboxing of sandboxed wasm instances (put is intended), which is desired for compilation, might add considerable amount of overhead.

**Comment by Robbepop** [comment]
> 
    I have some ideas how to make sandboxing more efficient, which might just invalidate its slowness assumption.
    Process sandboxing of sandboxed wasm instances (put is intended), which is desired for compilation, might add considerable amount of overhead.

Are there some issues with further information somewhere?

**Comment by pepyakin** [comment]
Not yet.

**Comment by pepyakin** [comment]
> We decided to settle on the scratch buffer in contrast to capped outputs with manual reservation of memory in a contract's linear memory and other considered approaches.

Ultimately, we have decided to go with the capped approach. Therefore closing.

Related https://github.com/paritytech/substrate/issues/6355
