### ISSUE TITLE
seal: dedicated function for deliberate revert

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#2852]
At the moment, if wasm code of a contract traps during execution the execution context, and consequently all changes, is reverted returning all unused gas.

This mechanism is suitable for using it for checking preconditions of contracts:

```rust
/// A useless contract that returns the result of division.
/// Panics, if `b` is 0.
pub(external) fn div(&self, a: usize, b: usize) -> usize {
  // Not necessary since `a / b` will panic anyway if `b == 0`, but just for 
  // the clarity sake.
  // 
  if b == 0 {
    panic!("b == 0");
  }
  a / b
}
```

However, if we wanted to facilitate static analysis, it might be not ideal because for this use-case it is beneficial for differentiating these two categories of faults:

1. general faults. i.e. mechanical ones, such as OOB memory accesses, division by zero and well as ones that are more high-level such as violation of application-specific invariants e.g. ERC20's `self.total_issuance() > 0`.
2. premature and deliberate termination due to violation of some precondition. E.g. permission check belongs here: ```precondition!(self.owner == self.caller)```.

From the static analysis perspective, a precondition check is OK and expected to fail thus should not trigger a red flag. Furthermore, it auguments the analysis with additional constraint that further improves the quality of analysis, e.g. by lowering the false positive rate of triggering a red flag for particular code.

```rust
pub(external) fn div(&self, a: usize, b: usize) -> usize {
  // In this case this is necessary:
  if b == 0 {
    precondition_fail!("b == 0");
  }
  a / b
}
```

in this case the analyzer will not trigger on the panic that can be possible on precondition fail and hopefully it will be smart enough to not trigger on the panic that can be possible on `a / b` if `b` is 0.

For this to implement we could add a `ext_preconditional_fail` function dedicated for exactly this. Then if the static analyser sees such a call then treats it as precondition failure hence ignoring it. 

This function could take a parameter with data which is specific to this case. This data can be actually passed to the caller. One can imagine making use of this data for the callee to return description of an actionable error thus allowing wider range of possible interactions between contracts.

Additionally, although much less importantly, because there is no practical and clean way to trap in WebAssembly from Rust on stable we could add another function (or repurpose `ext_preconditional_fail`) tailored for this use case. 

Not so much useful by itself (Ink! for example is based on nightly atm), we could also augument this function with a data buffer parameter which would be passed as output to the caller in case of executing this function. On the on-chain execution path this function could just discard the passed data and trap.

For the purposes of static analysis reaching this function by control flow still be considered as invariant failure.

**Comment by DemiMarie-parity** [comment]
I very much like this idea.

While I do not have experience with Ink!, I do have experience with Solidity.  Solidity has `require` to express a precondition failure, and `assert` to express an internal error.  This distinction is extremely useful in practice: `require` is used to indicate things like “Operation not permitted” or “Insufficient funds”, while `assert` is used like Rust’s `assert!`.  Static analysis tools consisider a failing `require` to be deliberate, but flag an `assert` that can fail as erroneous.  Furthermore, these have different gas behavior: while both revert the transaction, a failing `require` returns all unused gas, while a failing `assert` consumes all possible gas.

**Comment by Robbepop** [comment]
Hmm, ... isn't this `ext_precondition_fail` more or less what in Rust is normally expressed as returning the `Err` variant of a `Result`? Since we want to stay language agnostic here I can see why we would want to introduce this `ext_*` call but I wonder how we would implement this into ink! that tries to provide a Rust-like experience in writing smart contracts.

**Comment by pepyakin** [comment]
You are right, and this can be incorporated in ink! as Result and this function called in the pre-main code of ink if `Err` is returned. However, this will inhibit static analysis since in this case the analyzer should reason not only about control flow but also should track this return value to the return value of the called `pub(external)` function, which seems to give results of lower quality. So i'd go for the macro/call approach.

Although this concerns only the static analysis of wasm binary, I believe the same problems are related to the source-level static analysis, so macro/call approach would be more suitable as well.

While I agree that the `Result` type is more idiomatic, I think it is not particulary important compared to better chances of having good quality of static analysis.

@DemiMarie-parity Yeah good point on debuggability. I think we could actually expose these messages as part of something like #2082.

**Comment by jimpo** [comment]
Hmm, functionally you could get many of the same benefits by having the entry point functions (`call` and `deploy`) return an exit code (0 is success, 1+ maps to types in some error enum) and leave output data/error message in the scratch buffer (or a dedicated output buffer). The contract language (ink!) would be responsible for ensuring that the state of the scratch buffer and exit code are correct on return. Basically, this pushes the complexity into the higher-level contract language while keeping the VM as simple as possible.

The downside, as @pepyakin describes, is lesser ability to perform static analysis on the Wasm binary. But I wonder how important that is as static analysis on the source code will always be more powerful for appropriate high-level languages like Rust.

**Comment by athei** [comment]
This makes total sense to me. It is also useful in order to have another module error `PreconditionalFailed` that is different form the dreaded `ContractTrapped`. By this precondition errors can be more easily distinguished from bugs.

**Comment by Robbepop** [comment]
I agree this would be a nice-to-have feature for better errors. The API could look like the following:
```rust
fn seal_revert(status: u32) -> !;
```
Where `status` is a status code defined by the contract and communicated via the contract's metadata since we should not store panic/error strings in the Wasm itself but a `u32` code should suffice the needs in most cases. The only problem is that with a simple `u32` status code we cannot properly communicate associated error information but it is good enough and definitely much better than what we currently employ.

**Comment by athei** [comment]
My favoured signature is

```rust
seal_precondition_fail(status: u32, data_ptr: u32, data_len: u32) -> !;
```

The data would be left empty by a highly optimized contract I wager. However, I want to give contracts the possibility to emit messages if they want to. The messages would only be read when the contract is executed as RPC but never on-chain. See: https://github.com/paritytech/substrate/issues/5239#issuecomment-804017217

**Comment by athei** [comment]
@Robbepop Is this feature still useful for ink with the existence of he revert flag in `seal_return`?

**Comment by Robbepop** [comment]
I currently no longer see a need for this feature with the aforementioned extension to `seal_return`. Therefore this can be closed. If we ever find a usecase for this we can simply reopen this issue.
