### ISSUE TITLE
How to upgrade the earlier substrate version to new version ?

### ISSUE THREAD

**Issue by satyamakgec** [paritytech/substrate#2861]
I am running my chain on the `node-template v1.0.0`. It is working fine with my requirements but `@polkadot/api` somewhere giving me errors when I use an old version (Like this - https://github.com/polkadot-js/api/issues/970). So I am thinking to upgrade my substrate version to latest or you can say `node-template v2.0.0` to fix those errors I am getting. What is the best way to do so? I have 7 - 8 SRML modules in my existing chain so I don't want any discrepancies on my code.

**Comment by bkchr** [comment]
`2.0.0` is just master, so this will break frequently.

@shawntabrizi should be able to help you, as he knows which js version works on 1.0

**Comment by satyamakgec** [comment]
@bkchr that issue get solved by @jacogr. It makes sense the master will break frequently. But In general, how will the upgrade procedure be performed on the native code side or upgrade the substrate version.

**Comment by bkchr** [comment]
You mean later? When you have a running network? When you update the native side, you will need to redistribute it, like for any other software.

**Comment by satyamakgec** [comment]
I understand, But How do I upgrade Ex - if there is a new substrate version gets released and I want to upgrade my chain with the new substrate version then what will be steps. Like in Ethereum fork we will use the patches provided by the parity and geth but how do we do it in the substrate?

**Comment by bkchr** [comment]
What is the `Ex`? 

And as we are currently still in development, there is currently no predefined way to help users upgrade their stuff. Sorry! When we come to the point of stable releases, we will probably also provide changelogs and upgrade help!

I will close this issue for now, when there is more stuff to be asked, just keep posting.
