### ISSUE TITLE
Make state generic over Hash

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#292]
Get rid of `TrieH256` type.

**Comment by snd** [comment]
this roughly means replacing all uses of `TrieH256` by a type param, correct?

**Comment by arkpar** [comment]
Yep, already taken care of in #297

**Comment by snd** [comment]
this can be closed since https://github.com/paritytech/polkadot/pull/297 is merged, right?

**Comment by dvdplm** [comment]
Re-opened this since #297 was reverted.

**Comment by dvdplm** [comment]
I think this can be closed.
