### ISSUE TITLE
failed to select a version for the requirement `zeroize = "^0.8"`

### ISSUE THREAD

**Issue by AlexanderMazaletskiy** [paritytech/substrate#2940]
Hi, guys! Can you help me?
cargo install --force --path ./ akropolis
  Installing akropolis v0.8.2 (/root/akropolis/node)
    Updating git repository `https://github.com/paritytech/substrate.git`
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/substrate.git`
    Updating git repository `https://github.com/paritytech/substrate-bip39`
    Updating git repository `https://github.com/paritytech/parity-common`
error: failed to compile `akropolis v0.8.2 (/root/akropolis/node)`, intermediate artifacts can be found at `/root/akropolis/node/target`

Caused by:
  failed to select a version for the requirement `zeroize = "^0.8"`
  candidate versions found which didn't match: 0.9.1, 0.9.0, 0.7.0, ...
  location searched: crates.io index
required by package `libp2p-noise v0.7.0`
    ... which is depended on by `libp2p v0.9.1`
    ... which is depended on by `substrate-network v2.0.0 (https://github.com/paritytech/substrate.git#96e17dc5)`
    ... which is depended on by `akropolis v0.8.2 (/root/akropolis/node)`

zeroize 0.8 yanked from crate index.

How to resolve it?

**Comment by bkchr** [comment]
CC @tomaka

**Comment by tomaka** [comment]
Fixed in #2945
