### ISSUE TITLE
Convert error string to enum

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#2953]
Convert hardcoded error string and `&'static str` error type to use Error enum

- [ ] srml-executive
 https://github.com/paritytech/substrate/blob/51ec6283ff1fb3a1fd9e1844d83229e40e387a63/srml/executive/src/lib.rs#L341-L342

- [ ] srml-system
https://github.com/paritytech/substrate/blob/51ec6283ff1fb3a1fd9e1844d83229e40e387a63/srml/system/src/lib.rs#L181-L182

- [ ] node-runtime
https://github.com/paritytech/substrate/blob/51ec6283ff1fb3a1fd9e1844d83229e40e387a63/node/runtime/src/lib.rs#L190-L194
https://github.com/paritytech/substrate/blob/51ec6283ff1fb3a1fd9e1844d83229e40e387a63/node/runtime/src/lib.rs#L215-L216

Related: #2880

**Comment by niklasad1** [comment]
I'm not sure I understand this issue w.r.t. to `Error enum`

I thought the intention was replace the hardcoded `&'static str` with an associated type `Error?

**Comment by xlc** [comment]
@niklasad1 Yes. In some case we need to introduce new Error enum or new variant on existing Error enum, and in some case just replace it with the associated type `T::Error`

**Comment by xlc** [comment]
@bkchr is this still relevant?

**Comment by bkchr** [comment]
No. Thanks for asking @xlc  :)
