### ISSUE TITLE
Actually construct the `Authorship::set_uncles` inherent

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#2956]
#2941 creates logic for a `set_uncles` inherent to set some uncles. But we'll want to actually create a piece of logic that can call `client.uncles()` and ignore any duplicates (i.e. those which have already been included). We can model off the code for the `FinalityTracker` inherent, which makes use of the client as well.

**Comment by kianenigma** [comment]
@andresilva isn't this same or similar to https://github.com/paritytech/substrate/pull/3293 ?

**Comment by andresilva** [comment]
No it's different. Currently the authoring logic for BABE (and Aura but not relevant there) doesn't collect and include any uncle data. Like @rphmeier said this needs to be done by calling `client.uncles()` and calling `set_uncles` with it when we are proposing a new block.
