### ISSUE TITLE
How to add a custom service/component?

### ISSUE THREAD

**Issue by kigawas** [paritytech/substrate#2964]
Like PR #1942, it requires lots of codes to add an internal service inside the substrate node. 

![](https://substrate.dev/docs/assets/off-chain-workers.png)

What my questions are:

1. Are there some ways to customize the substrate node and add a service here without too many code changes?

```rust
pub trait ServiceTrait<C: Components>:
	Deref<Target = Service<C>>
	+ Send
	+ Sync
	+ 'static
	+ StartRPC<C>
	+ MaintainTransactionPool<C>
	+ OffchainWorker<C>
        + CustomService<C>
{}
impl<C: Components, T> ServiceTrait<C> for T where
	T: Deref<Target = Service<C>>
	+ Send
	+ Sync
	+ 'static
	+ StartRPC<C>
	+ MaintainTransactionPool<C>
	+ OffchainWorker<C>
        + CustomService<C> // <- add my service, and do other stuff somewhere else
{}
```

2. If there is no way to do so, is there any plan to support this just like how we are using `decl_module!`?

3. If this is not a best practice or it's anti-pattern, is there any recommended way to implement similar features or behaviors?

**Comment by rphmeier** [comment]
IMO it's not that difficult. Take a look at how e.g. the GRANDPA and aura workers are started. If you write your code as a long-running `Future<Item=(),Error=()>`` that selects on an `Exit` parameter, you can easily dispatch it.
