### ISSUE TITLE
How to play with `decl_runtime_apis` & `impl_runtime_apis`

### ISSUE THREAD

**Issue by YaaMe** [paritytech/substrate#2965]
I create primitives and decl apis like
```
decl_runtime_apis! {
    pub trait MyApi {
        fn touch();
    }
}
```
and then impl apis in node/runtime like
```
impl_runtime_apis! {
   ...
   impl my_primitives::MyApi<Block> for Runtime {
       fn touch() {}
   }
   ...
}
```
and try to invoke it like
```
  service.client().runtime_api().touch(&BlockId::Number(0)).unwrap();
```

and got `Err(Execution(Wasmi(Function("Module doesn\'t have export MyApi_touch"))))`
what really confuse me.
So

+ 1: Could I or Should I define my own runtime_api?
+ 1.1: If yes, Did i miss anything? I read a part of macros and search the code about `OffchainWorkerApi`&`AuraApi` usage and failed to get a clue about it..
Thanks

**Comment by bkchr** [comment]
Did you recompile the WASM files?

**Comment by YaaMe** [comment]
If you mean `./script/build.sh && cargo build` then yes.....
~~but..yeah,i still think it's maybe another weired & silly problem..~~

**Comment by bkchr** [comment]
So, problem solved?

**Comment by YaaMe** [comment]
No

**Comment by YaaMe** [comment]
Ok I see, even though I just update `wasm` & `runtime` part.I also need to `purge-chain`.
Thanks for the clue.
