### ISSUE TITLE
Migrate Aura authorship-detection to Pre-runtime digests

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#2986]
The inherent-based approach used before is now obsolete. See #2929 as an example of how to use `PreRuntime` digests in the runtime to compute authorship info.

This should be accompanied with a `FindAuthor<u32>` implementation.

**Comment by DemiMarie-parity** [comment]
Are inherents obsolete at this point?

**Comment by rphmeier** [comment]
@DemiMarie-parity for this use-case. Not for others.

**Comment by thiolliere** [comment]
This is needed for staking to reward its validator, shouldn't it be Milestone 2.0-K ?
