### ISSUE TITLE
Networking Primitives to get ready for Sentry Nodes

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#2999]
Sentry nodes are special nodes set up by a validator operator that are intended to be the points-of-contact for the validator node, which is shielded from public connections.

Typically, sentry nodes will function as normal nodes. But for consensus networking in particular, they will have to behave as though they _are_ the validator node. That means that it needs to become aware of what knowledge the validator node has. 

This will typically be handled on the level of particular networking protocols (knowing how to proxy certain requests to the underlying validator).

---

### Basics

What needs to be made available to the networking protocol:
  - Whether the local node _has_ sentry nodes and what their `PeerId`s are.
  - Whether the local node _is_ a sentry node and what its `PeerId` is.

This information needs to be made available to the core-level networking, any `NetworkSpecialization` and any `consensus_gossip::GossipValidator`

Then we'll also need CLI parameters for configuring and setting up sentry nodes.

**Comment by rphmeier** [comment]
cc @twittner : do you have some input on how best to integrate into the substrate networking to attach info onto `PeerId`s when connecting?

**Comment by twittner** [comment]
> - Whether the local node *is* a sentry node and what its `PeerId` is.

What the `PeerId` of its validator node is?

> do you have some input on how best to integrate into the substrate networking to attach info onto `PeerId`s when connecting?

I am not sure what you mean. I think information about `PeerId`s would go into `network::config::NetworkConfiguration`.

**Comment by rphmeier** [comment]
> What the PeerId of its validator node is?

yes, sorry.

**Comment by tomaka** [comment]
Done as part of https://github.com/paritytech/substrate/pull/5520 https://github.com/paritytech/substrate/pull/5665
