### ISSUE TITLE
For Polkadot: WASM-based smart-contract parachain

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#30]
Can link in relevant code from https://github.com/paritytech/parity 

BlockData:
  - 256 recent headers
  - parachain transactions
  - state trie proof

Validation function:
  - check header validity (mostly just timestamp)
  - apply ingress prior to transactions
  - apply transactions

Collator:
  - create valid header
  - apply ingress
  - push transactions from queue until out of gas or transactions.
  - best choice of gas amount?

**Comment by gavofyork** [comment]
Not relevant here.
