### ISSUE TITLE
For Polkadot: Validators should evaluate as many parachain candidates as possible

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#301]
Currently they select the winning candidate parachain block blindly by pre-selecting its collator as "primary". this is bad since it eradicates the "golden-ticket" scheme to incentivise collator rotation. rather, they should evaluate as many candidates as possible prior to the latest point that they need to put forward a preferred candidate, ordering them in terms of parachain preference (parachains should be able to provide a metric for wellness of block) and/or the collator "golden-ticket" winner.

**Comment by jiangfuyao** [comment]
![](http://p37d7w3w4.bkt.clouddn.com/jianyi.png)

**Comment by gavofyork** [comment]
Not relevant here.
