### ISSUE TITLE
Ubuntu 16.04 compilation error: failed to run custom build command for `librocksdb-sys v5.18.3`

### ISSUE THREAD

**Issue by pepoospina** [paritytech/substrate#3014]
In Ubuntu 16.04 gcc was not up to date. 

I ran

```
sudo apt-get install clang-3.9
```

and it worked.

**Comment by bkchr** [comment]
You write about `gcc`, but installed `clang`. We list in our dependencies that you need to have `clang` installed. So, I will close this. Ty.
