### ISSUE TITLE
Cannot add custom rpc without hacking substrate-servife crate

### ISSUE THREAD

**Issue by guoxbin** [paritytech/substrate#3033]
1. cannot replace FullComponents with a custom one because ServiceFactory traits hold a FullService type bounded with ServiceTrait<FullComponents<Self>>

2. cannot add extra handler because rpc::rpc_handler receive 4 handlers(state, chain, author, system) which are not unextendible

**Comment by bkchr** [comment]
Yeah, this is currently not supported.
@tomusdrw is that anything that will come in the near future?

**Comment by tomusdrw** [comment]
I'll have a look today, cause it's long overdue. Same issues were raised in #2263, so let's continue there.
