### ISSUE TITLE
Split out substrate

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#304]
Substrate is increasingly an independent project. Moreover, it will be licensed under some more permissive license, perhaps Apache2, perhaps MPL or possibly BSD+Patent (tbd by legal/enterprise strategy team). We'll want to repot it into a separate repo.

**Comment by chevdor** [comment]
Any work started on this?

**Comment by chevdor** [comment]
FYI: I started playing with https://github.com/chevdor/substrate to have a base for a PR for this issue.
