### ISSUE TITLE
GRANDPA assumes that light clients only need to know authorities list and slot number

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/substrate#3053]
GRANDPA assumes that light clients only need to know authorities list and slot number.  This blocks BABE epochs from working on light clients.

**Comment by rphmeier** [comment]
Why should GRANDPA consensus influence anything about BABE?

As long as light clients know the next authorities 1 epoch ahead, it should be fine under a synchrony assumption (which BABE has).
