### ISSUE TITLE
no ./scripts/build.sh anymore

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/substrate#3066]
this https://substrate.dev/docs/en/getting-started/installing-substrate#manual-build (in version "Substrate Developer Hub 1.0.0") says 

```
# Build the wasm runtime
./scripts/build.sh
```
but that [does not exist](https://github.com/paritytech/substrate/tree/master/scripts).

**Comment by drandreaskrueger** [comment]
I could continue now, after a

    git checkout v0.9.2

**Comment by drandreaskrueger** [comment]
That [release v0.9.2](https://github.com/paritytech/substrate/releases) is half a year old. 

When will be a new new release?

Should I work with that v0.9.2, or rather risk a newer/st version? Which one do you recommend?

**Comment by andresilva** [comment]
In master the process is simplified, you only have to do `cargo build` and it will take care of building the runtime as well. Yeah, I guess that documentation you linked needs to be updated to instruct how to check out the v1.0 branch. You should do `git checkout -b v1.0 origin/v1.0`. cc @shawntabrizi 

Feel free to close the issue if this is solved for you.

**Comment by drandreaskrueger** [comment]
> that documentation you linked needs to be updated 

Yes. That the  `./scripts/build.sh` step is obsolete. That part was misleading. Even though the heading of the page said "v1.0.0".

I know it is difficult to keep many separate manuals uptodate. That was actually one of the worst aspects of learning Ethereum: half of the manuals were faulty, because not updated. Uncountable dead ends I ran into because of that, raised dozens of issues, etc.. Lost so much time.

I don't know how you can prevent that. By better planning or tooling. Ideas?


> to instruct how to check out the v1.0 branch

Or better, I should be able to just checkout the head of the master branch, no?   
Or yes, if not that, then include some "checkout lastrelease" thingy into the instructions.


So you recommend against 0.9.2, and instead recommend v1.0 ?

Then I am trying this now:

```
git checkout -b v1.0 origin/v1.0
./scripts/init.sh
cargo clean
RUSTFLAGS=-Awarnings cargo build
```
right?

**Comment by drandreaskrueger** [comment]
nope:

```
RUSTFLAGS=-Awarnings cargo build

[...]

   Compiling node-executor v1.0.0 (~/paritytech_substrate/node/executor)
error: couldn't read node/executor/src/../../runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm: No such file or directory (os error 2)
  --> node/executor/src/lib.rs:26:100
   |
26 | native_executor_instance!(pub Executor, node_runtime::api::dispatch, node_runtime::native_version, include_bytes!("../../runtime/wasm/target/wasm32-unknown-unknown/release/node_runtime.compact.wasm"));
   |                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `node-executor`.

To learn more, run the command again with --verbose.
```

**Comment by andresilva** [comment]
The master branch tracks what will eventually become Substrate 2.0, therefore there are some breaking changes compared to 1.0 and there are no stability guarantees. On v1.0 we guarantee some API stability. I also think documentation will be more up-to-date regarding v1.0 (since it's more stable).

Besides `init.sh` you need to run `build.sh`. I think the following should work:

```
git checkout -b v1.0 origin/v1.0
./scripts/init.sh
./scripts/build.sh
cargo build
cargo build -p subkey
```

Substrate is still early in development and changing rapidly so I think it's a bit understandable that documentation might be a bit lacking. I'm not working on learning resources myself but either way I see that these are getting improved and more documentation is available.

**Comment by drandreaskrueger** [comment]
Ah, now `./scripts/build.sh` is back again? Thanks.

So it is really only missing in master branch? What about then still having a simple `./scripts/build.sh` in master with `echo obsolete` - then I might have already been successful there now.


On the other hand, perhaps it is good that this obstacle was in the way, because:

> On v1.0 we guarantee some API stability.

Perfect, that is what I want. Thanks.

**Comment by andresilva** [comment]
Maybe my explanation earlier wasn't clear:
- on master
```
cargo build
```

- on v1.0
```
./scripts/build.sh
cargo build
```

You only need to run `./scripts/init.sh` once (in either branch) in order to install the required rust compiler. You can run it again in the future in order to keep updating it but there's no need to do it every time you want to build.

**Comment by andresilva** [comment]
Yes, `cargo build --release` should give you a significantly faster binary (but the build will be slower).

**Comment by drandreaskrueger** [comment]
Yes, I had understood that by now. Thanks again. Just add it to your manuals  ...

---

Hooray, it finally worked:

```
target/debug/subkey --version; target/debug/substrate --version
subkey 1.0.0
substrate 1.0.0-2f1b89f4-x86_64-linux-gnu

target/release/subkey --version; target/release/substrate --version
subkey 1.0.0
substrate 1.0.0-2f1b89f4-x86_64-linux-gnu
```

```
ls target/{debug,release}/{subkey,substrate} -lh | awk '{print $5, $9}'

109M target/debug/subkey
500M target/debug/substrate
6.1M target/release/subkey
38M target/release/substrate
```
---

Thanks a lot for your help.

CanClose

**Comment by drandreaskrueger** [comment]
Hello @andresilva, 

IF I understand correctly [what I was told over there](https://github.com/paritytech/substrate/issues/3107#issuecomment-510618402), then [you might have pointed me](https://github.com/paritytech/substrate/issues/3066#issuecomment-509388062) to a "dead" version, i.e. which has reached its EOL? 

Of course, I don't want to invest myself into a dead version. Please reopen this (or the other) issue, and

* you discuss with @bkchr what's the best policy on this, and
* advise me what to do then.

Thanks a lot.

**Comment by andresilva** [comment]
If you want to experiment with building your own time runtime you are probably interested in API stability and in that case v1.0 is better, master is changing everyday.

@bkchr mentioned that those kinds of bugs are not being looked into on v1.0, it's a minor thing (pruning is delayed) and not breaking. If you can replicate the same issue in master (probably it's there too but a lot of code has changed) open an issue and we will look into it.

My recommendation is that you read the existing documentation, figure out what you want to do (create a runtime, just run a node and connect to an existing network, create your private network, etc.). And based on that decide if master or v1.0 is more appropriate for your what you want to do.

**Comment by drandreaskrueger** [comment]
Yes, thanks. I am just worried to to work with an unsupported version. I had that before, and it can be super depressing, putting lots of time into the wrong thing. Perhaps I better don't touch ANY version of substrate, and just further delay my work here until 2.0 is stable?

Additional info from @shawntabrizi in the chat:

> Stability of 2.0 should be coming soon, so you are a bit in limbo for the time being. If you are doing runtime module development, I would build against 1.0, and do a one time migration (should be relatively low pain) once we announce 2.0 stability.

> If you want to test performance, networking, other other aspects of Substrate, run a 2.0 node. Let me know if this helps.

**Comment by shawntabrizi** [comment]
If you build a runtime with 1.0, it should be relatively easy to change to 2.0. in many cases you will need to make no changes at all.

I would recommend you build on 1.0 as mostly everything is the same. There should be documentation and plenty of support to migrate things after the fact.

**Comment by drandreaskrueger** [comment]
Thanks @shawntabrizi and @andresilva - so I'd be using this tag, right? 

--> https://github.com/paritytech/substrate/releases/tag/v1.0.0 

It's 4 months old now. Will there a be a newer one soon?

**Comment by shawntabrizi** [comment]
@drandreaskrueger That tutorial does use master.

We are in the midst of changing. If you want docs for master you can find them under `next`:

https://substrate.dev/docs/en/next/

Note many pages still in development. Tutorials will come too, you can follow this:

https://substrate.dev/docs/en/next/tutorials/creating-your-first-substrate-chain/

**Comment by drandreaskrueger** [comment]
Great, thank you very much. That looks helpful indeed.

[Here](https://substrate.dev/docs/en/next/tutorials/start-a-private-network-with-substrate#compiling-the-tools):

    # Switch to the proper commit
    git checkout 7d7e74fb

Exactly, that's what I meant. I'd tag that version. Even though that's "24 Sep", so perhaps some selected newer commit would be more appropriate? There haven't been [any tags](https://github.com/paritytech/substrate/tags) for ~4 months?

**Comment by drandreaskrueger** [comment]
Not sure: Is https://github.com/substrate-developer-hub/substrate-node-template obsolete now perhaps? 

Because https://substrate.dev/docs/en/next/tutorials/start-a-private-network-with-substrate#compiling-the-tools is using https://github.com/paritytech/substrate and it says:

>  The second is a more minimal runtime that lives in the **node-template directory**.  
> We'll be using the node template in this tutorial because ...

that sounds as if.

**Comment by shawntabrizi** [comment]
@drandreaskrueger there are two choices when writing docs on bleeding edge software:

* Write content that constantly breaks, and the user suffers.
* Write content that is **fixed** to a point in time that works.

What are you trying to learn here? The content on the page or something very specific about the last 1 month of commits?

Until Substrate 2.0 is actually released, we can only provide so much support and time constantly updating the docs. I can say in general that the content in these tutorials should not be so out of date they are unusable.

If you wish to work on the bleeding edge of master, you probably can figure it out using these docs and some critical thinking, but we wont have stuff that will hand hold you through the process.

**Comment by drandreaskrueger** [comment]
Thanks for the explanations. I understand that it's not easy to accommodate very different needs.

My focus:

* as stable as possible
* while not working with something that is outdated soon

Sorry for my too many questions, but I have made the experience of working into dead ends too many times now - so I rather ask before. And already it was good, because you pointed me to that amazing collection of instructions. Thanks a lot. 

So I guess I stick to the `7d7e74fb` then? It's tested and definitely works with your tutorial, and will very probably suit my needs. Sorry, you are right, Sep 25 is really not long ago. True.

Why then not ask the paritytech/substrate maintainer to tag this version `7d7e74fb`? 

Tags and releases are really helpful for us endusers of your code - to sort out all those questions you mentioned ... by ourselves.

---

And what about the `substrate-developer-hub/substrate-node-template` vs `/paritytech/substrate/node-template` question? Obsolete? Which one do you suggest to use?

Thanks.

**Comment by shawntabrizi** [comment]
@drandreaskrueger `substrate-developer-hub/substrate-node-template` is our version of "tagging" for tutorials and docs.

We take a snapshot of the `paritytech/substrate/node-template` and keep in the dev hub to be referenced by all of our docs.

As it updates, we will update all versions of our docs that depend on it if there is a breaking change.

**Comment by drandreaskrueger** [comment]
>   is our version of "tagging" for tutorials and docs.

Ah great. That makes a lot of sense.  
Nice. Good to know.

> snapshot of the  ... to be referenced by all of our docs.

I understand. Now.  
The question is whether "outsiders" will understand that.  
(me, I would always search for a stable-but-most-recent tag in the main repo, i.e. paritytech/substrate)

Idea: Put your ^ sentence at the top of the [README](https://github.com/substrate-developer-hub/substrate-node-template/blob/master/README.md) perhaps?  (Perhaps additionally a link back to your repo from /paritytech/substrate.)

Thanks for all the infos. A lot. Much appreciated.

I have been successful, by the way. My new scripts are now starting "a swarm of" nodes, bootnode-interconnected, each with their own (babe,gran)-keys, entered into the chainspec, etc. Was a bit difficult in the middle - but also very rewarding. Good that I have that now. Will make it available.

Some suggestions for your tutorial: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/327
