### ISSUE TITLE
node-template  build error 

### ISSUE THREAD

**Issue by beykery** [paritytech/substrate#3069]
start my project  from node-template , i add the `srml-example={path="../example"}` in runtime/Cargo.toml as a runtime module , then `cargo build` in node-template dir , i got error bellow ：

error: failed to run custom build command for `node-template-runtime v2.0.0 (/Users/yangchaoqun/work/study/cross/node-template/runtime)`

Caused by:
  process didn't exit successfully: `/Users/yangchaoqun/work/study/cross/node-template/target/debug/build/node-template-runtime-0106ae5040f62031/build-script-build` (exit code: 1)
--- stdout
Executing build command: "rustup" "run" "nightly" "cargo" "build" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/yangchaoqun/work/study/cross/node-template/target/debug/wbuild/node-template-runtime/Cargo.toml"

--- stderr
    Updating crates.io index
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling libc v0.2.59
   Compiling cc v1.0.37
   Compiling spin v0.5.0
   Compiling syn v0.15.39
   Compiling autocfg v0.1.4
   Compiling ryu v1.0.0
   Compiling ppv-lite86 v0.2.5
   Compiling failure_derive v0.1.5
   Compiling serde v1.0.94
   Compiling cfg-if v0.1.9
   Compiling rustc-demangle v0.1.15
   Compiling itoa v0.4.4
   Compiling semver-parser v0.7.0
   Compiling remove_dir_all v0.5.2
   Compiling same-file v1.0.4
   Compiling backtrace-sys v0.1.30
   Compiling lazy_static v1.3.0
   Compiling rand_chacha v0.2.0
   Compiling semver v0.6.0
   Compiling walkdir v2.2.8
   Compiling c2-chacha v0.2.2
   Compiling build-helper v0.1.1
   Compiling quote v0.6.12
   Compiling getrandom v0.1.6
   Compiling fs2 v0.4.3
   Compiling serde_json v1.0.40
   Compiling semver v0.9.0
   Compiling toml v0.5.1
   Compiling rand_core v0.5.0
   Compiling backtrace v0.3.32
   Compiling rand v0.7.0
   Compiling synstructure v0.10.2
   Compiling serde_derive v1.0.94
   Compiling tempfile v3.1.0
   Compiling failure v0.1.5
   Compiling cargo_metadata v0.8.0
   Compiling substrate-wasm-builder v1.0.4
   Compiling wasm-build-runner-impl v1.0.0 (/Users/yangchaoqun/work/study/cross/node-template/target/debug/build/node-template-runtime-06ea42e6118dbb8f/out/wasm_build_runner)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 51s
     Running `/Users/yangchaoqun/work/study/cross/node-template/target/debug/build/node-template-runtime-06ea42e6118dbb8f/out/wasm_build_runner/target/debug/wasm-build-runner-impl`
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling typenum v1.10.0
   Compiling syn v0.15.39
   Compiling cc v1.0.37
   Compiling byteorder v1.3.2
   Compiling autocfg v0.1.4
   Compiling serde v1.0.94
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.59
   Compiling rand_core v0.4.0
   Compiling subtle v2.1.0
   Compiling byte-tools v0.3.1
   Compiling failure_derive v0.1.5
   Compiling rustc-demangle v0.1.15
   Compiling arrayvec v0.4.10
   Compiling cfg-if v0.1.9
   Compiling smallvec v0.6.10
   Compiling opaque-debug v0.2.2
   Compiling crunchy v0.2.2
   Compiling fake-simd v0.1.2
   Compiling memchr v2.2.1
   Compiling nodrop v0.1.13
   Compiling scopeguard v0.3.3
   Compiling heapsize v0.4.2
   Compiling keccak v0.1.0
   Compiling bitvec v0.11.3
   Compiling subtle v1.0.0
   Compiling ucd-util v0.1.3
   Compiling static_assertions v0.2.5
   Compiling lazy_static v1.3.0
   Compiling regex v1.1.9
   Compiling rustc-hex v2.0.1
   Compiling utf8-ranges v1.0.3
   Compiling memory_units v0.3.0
   Compiling constant_time_eq v0.1.3
   Compiling hash-db v0.14.0
   Compiling hashmap_core v0.1.10
   Compiling byte-tools v0.2.0
   Compiling hex v0.3.2
   Compiling base58 v0.1.0
   Compiling scopeguard v1.0.0
   Compiling arrayref v0.3.5
   Compiling rand v0.4.6
   Compiling environmental v1.0.1
   Compiling integer-sqrt v0.1.2
   Compiling bitmask v0.5.0
   Compiling unicode-segmentation v1.3.0
   Compiling strum v0.14.0
   Compiling substrate-wasm-builder-runner v1.0.2
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling num-traits v0.2.8
   Compiling block-padding v0.1.4
   Compiling semver v0.9.0
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling rand_os v0.1.3
   Compiling log v0.4.6
   Compiling lock_api v0.1.5
   Compiling thread_local v0.3.6
   Compiling regex-syntax v0.6.8
   Compiling trie-root v0.14.0
   Compiling lock_api v0.2.0
   Compiling node-template-runtime v2.0.0 (/Users/yangchaoqun/work/study/cross/node-template/runtime)
   Compiling heck v0.3.1
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand v0.5.6
   Compiling clear_on_drop v0.2.3
   Compiling backtrace-sys v0.1.30
   Compiling rustc_version v0.2.3
   Compiling parity-wasm v0.31.3
   Compiling hashbrown v0.1.8
   Compiling uint v0.8.0
   Compiling hash256-std-hasher v0.14.0
   Compiling tiny-keccak v1.5.0
   Compiling aho-corasick v0.7.4
error: failed to run custom build command for `clear_on_drop v0.2.3`

Caused by:
  process didn't exit successfully: `/Users/yangchaoqun/work/study/cross/node-template/target/debug/wbuild/target/debug/build/clear_on_drop-c79a4d28f3e484ab/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("wasm32-unknown-unknown")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-apple-darwin")
CC_wasm32-unknown-unknown = None
CC_wasm32_unknown_unknown = None
TARGET_CC = None
CC = None
CFLAGS_wasm32-unknown-unknown = None
CFLAGS_wasm32_unknown_unknown = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-o" "/Users/yangchaoqun/work/study/cross/node-template/target/debug/wbuild/target/wasm32-unknown-unknown/debug/build/clear_on_drop-3fa6ea98ed443494/out/src/hide.o" "-c" "src/hide.c"
cargo:warning=error: unable to create target: 'No available targets are compatible with this triple.'
cargo:warning=1 error generated.
exit code: 1

--- stderr

error occurred: Command "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-o" "/Users/yangchaoqun/work/study/cross/node-template/target/debug/wbuild/target/wasm32-unknown-unknown/debug/build/clear_on_drop-3fa6ea98ed443494/out/src/hide.o" "-c" "src/hide.c" with args "clang" did not execute successfully (status code exit code: 1).

warning: build failed, waiting for other jobs to finish...
error: build failed

warning: build failed, waiting for other jobs to finish...
error: build failed

how can i fix it please ?

**Comment by bkchr** [comment]
How old is your `node-template`? You need to find out what includes `clear_on_drop`, by looking into your `Cargo.toml`.

**Comment by beykery** [comment]
i use latest master branch .

**Comment by bkchr** [comment]
From today?

**Comment by beykery** [comment]
yes

**Comment by bkchr** [comment]
[test.tar.gz](https://github.com/paritytech/substrate/files/3372121/test.tar.gz)
Can you please test this one?

**Comment by beykery** [comment]
thank you, i tested it ,but fail as before . 
here is the repo : https://github.com/beykery/substrate-test
i just add a example module into runtime , but can not build it .
please check it .

**Comment by bkchr** [comment]
Can you please try the following patch:
```
diff --git a/runtime/Cargo.toml b/runtime/Cargo.toml
index 460b9ea..d616651 100644
--- a/runtime/Cargo.toml
+++ b/runtime/Cargo.toml
@@ -30,6 +30,7 @@ std = [
     'safe-mix/std',
     'consensus-aura/std',
     'offchain-primitives/std',
+    'srml-example/std',
 ]
 [dependencies.aura]
 default_features = false
@@ -143,4 +144,5 @@ rev = 'd5dc301e613859f6b156fa23641a5d6c8285780b'
 
 # example moudle
 [dependencies.srml-example]
-path = '../example'
\ No newline at end of file
+default_features = false
+path = '../example'
```

**Comment by beykery** [comment]
yeah it work，thank you !

**Comment by beykery** [comment]
@bkchr sorry when i add a extern crate bitcoin to example moudle' Cargo.toml , and run `cargo build` , it fail as bellow :

error: failed to run custom build command for `node-template-runtime v2.0.0 (/Users/yangchaoqun/work/study/cross/substrate-node-template-new/runtime)`

Caused by:
  process didn't exit successfully: `/Users/yangchaoqun/work/study/cross/substrate-node-template-new/target/debug/build/node-template-runtime-ed9cfd1381025576/build-script-build` (exit code: 1)
--- stdout
Executing build command: "rustup" "run" "nightly" "cargo" "build" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/yangchaoqun/work/study/cross/substrate-node-template-new/target/debug/wbuild/node-template-runtime/Cargo.toml"

--- stderr
   Compiling wasm-build-runner-impl v1.0.0 (/Users/yangchaoqun/work/study/cross/substrate-node-template-new/target/debug/build/node-template-runtime-73b69e5f634f517c/out/wasm_build_runner)
    Finished dev [unoptimized + debuginfo] target(s) in 1.61s
     Running `/Users/yangchaoqun/work/study/cross/substrate-node-template-new/target/debug/build/node-template-runtime-73b69e5f634f517c/out/wasm_build_runner/target/debug/wasm-build-runner-impl`
   Compiling sr-io v2.0.0 (https://github.com/paritytech/substrate.git?rev=d5dc301e613859f6b156fa23641a5d6c8285780b#d5dc301e)
error[E0152]: duplicate lang item found: `panic_impl`.
  --> /Users/yangchaoqun/.cargo/git/checkouts/substrate-7e08433d4c370a21/d5dc301/core/sr-io/src/../without_std.rs:28:1
   |
28 | / pub fn panic(info: &PanicInfo) -> ! {
29 | |     unsafe {
30 | |         #[cfg(feature = "wasm-nice-panic-message")]
31 | |         {
...  |
44 | |     }
45 | | }
   | |_^
   |
   = note: first defined in crate `std`.

error[E0152]: duplicate lang item found: `oom`.
  --> /Users/yangchaoqun/.cargo/git/checkouts/substrate-7e08433d4c370a21/d5dc301/core/sr-io/src/../without_std.rs:49:1
   |
49 | / pub extern fn oom(_: ::core::alloc::Layout) -> ! {
50 | |     static OOM_MSG: &str = "Runtime memory exhausted. Aborting";
51 | |
52 | |     unsafe {
...  |
55 | |     }
56 | | }
   | |_^
   |
   = note: first defined in crate `std`.

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0152`.
error: Could not compile `sr-io`.


please check it ： 
https://github.com/beykery/substrate-test/commit/764e00b4a62c794b60d147c2b0faaf64d6a5b845

**Comment by bkchr** [comment]
Did you read https://substrate.dev/docs/en/tutorials/creating-a-runtime-module?

The problem is that the crate `bitcoin` does not compile for `no_std`. There is not that much you can do (besides making the crate compilable on `no_std`).
