### ISSUE TITLE
Slashing should reduce registered amount that is bonded

### ISSUE THREAD

**Issue by Tbaut** [paritytech/substrate#3088]
The account `5F7BJL6Z4m8RLtK7nXEqqpEqhBbd535Z3CZeYF6ccvaQAY6N` has more DOTs bonded than available in `free_balance`. Also it has no vesting and no reserved balance.

staking.ledger from its controller:
```json
{
    "stash": "5F7BJL6Z4m8RLtK7nXEqqpEqhBbd535Z3CZeYF6ccvaQAY6N",
    "total": "0x00000000000000000023829049fb9940",
    "active": "0x00000000000000000023829049fb9940",
    "unlocking": []
}
```

which is ~9,9951×10¹⁵

balances.freeBalance: ~9,9946x10¹⁵

**Comment by Kianenigma** [comment]
@Tbaut any other strange behavior regarding this? Now, reading the discussion again, I think the original offset was simply because of paying fees.

**Comment by Tbaut** [comment]
It's not about the fee, it's about the registered amount (this [this comment](https://github.com/paritytech/substrate/issues/3088#issuecomment-498171789)) and the new title of this issue.

**Comment by kianenigma** [comment]
This is fixed already, as we do call update-ledger now with the new amount bonded after the slash. 

https://github.com/paritytech/substrate/blob/9467f562ddb9c85ff78fca69d08137950b948019/frame/staking/src/slashing.rs#L599-L606
