### ISSUE TITLE
no pruning ?

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/substrate#3107]
## summary

pruning is off by default?

## explanations

Asked in the chat already:

> Syncing substrate:     
> Only the first THIRD of the chain already **takes up 14 GB**!     
> My disk is small, so I quit syncing, with Ctrl-C.    
>  
> Then noticed after CTRL-C and restart, that the size taken by `~/.local/share/substrate`  
> **suddenly became 4.2G only**. 
> 
> How to trigger that compression DURING syncing?

answer was:

> After restart you see pruning.   
> I currently don't know why that is not being executed while syncing.

So, it's probably better that I tell you this, so you can look into it.

---

## Version:
[1.0 as suggested here](https://github.com/paritytech/substrate/issues/3066#issuecomment-509388062)
```
git checkout -b v1.0 origin/v1.0
[...]
substrate --version
substrate 1.0.0-2f1b89f4-x86_64-linux-gnu
```
Oh - compiled with target `--release`!  
Perhaps you show {d,r,...} in the `--version` number too, somehow.

**Comment by drandreaskrueger** [comment]
Found two CLI options that seem to be related:

```
--db-cache <MiB><br />
Limit the memory the database cache can use

--pruning <PRUNING_MODE>
Specify the pruning mode, a number of blocks to keep or 'archive'. Default is 256.
```
What is your recommendation to force pruning, on small disks?

---

Synced. Size _@1,425,183_ is 15145699540÷(2^30) = _14.11 Gb_  (**after** Ctrl-C, and restart).

**Comment by bkchr** [comment]
For 1.0 we don't provide anymore support for bugs like this. Sorry.

**Comment by drandreaskrueger** [comment]
Thanks!  In the chat you said 

> Please try latest master

Sorry, (judging by many bad experiences of much lost time when using someone's latest master) that's _probably_ not a good option for me. Please instead point me to a reasonably stable release version with (at least moderate) LTS instead. Thanks.

I had been told to use v1.0 - see that comment https://github.com/paritytech/substrate/issues/3066#issuecomment-510668084 . Perhaps you two together come up with a new advise for me?

Thanks, much appreciated.
