### ISSUE TITLE
Offchain API

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate#3139]
Follow-up from https://github.com/paritytech/substrate/pull/3079/.

Change the Offchain API for `authority_pubkey(kind: offchain::CryptoKind)` to `crypto_pubkey(&self, key: Option<CryptoKeyId>, kind: CryptoKind)`. 

And possibly change the API of `verify(…)` as well to take the public key instead of `CryptoKeyId`.

**Comment by dvc94ch** [comment]
I think that we need to include a block number. `authority_pubkey(kind: offchain::CryptoKind, valid_at_blocknumber: BlockNumber)`
