### ISSUE TITLE
Enable Offchain API to handle local storage race conditions better

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate#3143]
Follow-up from https://github.com/paritytech/substrate/pull/3079/.

This is how the race condition can appear:

Worker A finds no value in storage (`local_storage_get(…)` returns `None`). It can not issue `local_storage_compare_and_set(…)` with `old_value == None`, since that function requires a `&Vec<u8>` for `old_value`. Thus it must use a `local_storage_set(…)`.

Concurrently another worker does the same thing, resulting in a race condition.

- [ ] Change `local_storage_compare_and_set(…)` to take `Option<&Vec<u8>>`.
- [ ] Adapt the way `srml/im-online` sets local storage to use this new `local_storage_compare_and_set(…)` API then.

**Comment by gterzian** [comment]
You could also consider running offchain worker sequentially, as in "one after the other".  

You could add `compare_and_set` in a few places, and that means users having to use an atomic-like API, which is notoriously hard. 

Or you run workers sequentially, meaning anyone can get/set as much as they want in any order, without potential for race-condition. 

cc @tomusdrw

**Comment by tomusdrw** [comment]
@gterzian Offchain workers can be a long-running processes that await some heavy computations to be finished or some external requests.
We currently run them after every block import and we allow the workers to decide when they want to do something or not. By running them sequentially we could end up with a situation where you are multiple blocks behind and that's definitely not feasible.

The need for synchronisation between workers should be rare though, so I'd expect CAS to be used sparingly.

**Comment by gterzian** [comment]
> By running them sequentially we could end up with a situation where you are multiple blocks behind and that's definitely not feasible.

Couldn't that also happen de-facto if each block adds an off-chain worker that lives for "a long time" and they end-up contending for resources? 

So let's say we're at a new block 100, and they're are 99 offchain workers that have been spawned and doing all sorts of stuff, then that 100th spawned worker might well only be scheduled when we're at block 200?

**Comment by tomusdrw** [comment]
> Couldn't that also happen de-facto if each block adds an off-chain worker that lives for "a long time" and they end-up contending for resources?

Sure, but it's up to the users to define a logic. They can have a long running workers every 10k blocks (That runs for say 5k blocks) and in the meantime spawn a bunch of smaller tasks that complete faster.

It's a similar argument to: "What if user creates a runtime that causes blocks to be processed for longer than the block time.". Well, sure it's possible, but we trust they know what they are doing, and with good docs we can educate them what can and cannot be done.

**Comment by gterzian** [comment]
Ok, I see what you mean.

**Comment by tomusdrw** [comment]
> I'll take a look at adding the Option then, unless somehow is already working on this.

No, I don't think anyone is looking into it currently.

Also I consider the `local_storage` ext APIs to be low-level, I really hope we will be able to employ some macro magic and make the read/atomic_mutate operations really seamless for the users.

**Comment by gterzian** [comment]
Looks like this was done already, right?

https://github.com/paritytech/substrate/blob/0671a41b31b596686a41be6d338108a62de4e0af/core/client/db/src/offchain.rs#L82

**Comment by tomusdrw** [comment]
Only on the db layer, it should also be exposed like that to wasm:
https://github.com/paritytech/substrate/blob/fcb1277555a5e83d5c8469410a94e013c84b1b14/core/sr-io/src/lib.rs#L309
