### ISSUE TITLE
Connection refused for external ip address

### ISSUE THREAD

**Issue by alanpoon** [paritytech/substrate#3145]
curl -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "method":"chain_getRuntimeVersion", "params":[], "id": 1 }' http://192.168.1.37:9933
Connection refused but 
curl -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "method":"chain_getRuntimeVersion", "params":[], "id": 1 }' http://127.0.01:9933 works.
I cannot run client server in one machine and connect to node server in another machine. What are the steps to make my dev substrate project to production?
Os: ubuntu 18.04
command ran: cargo run -- --dev

**Comment by bkchr** [comment]
Do you have any firewall?

Otherwise cc @tomusdrw

**Comment by alanpoon** [comment]
no firewall. sudo ufw status verbose => inactive @tom

**Comment by alanpoon** [comment]
@tomusdrw I ran with --rpc-external, it works. Thanks.
