### ISSUE TITLE
Refactor offchain api again

### ISSUE THREAD

**Issue by dvc94ch** [paritytech/substrate#3156]
The AuthorityKeyProvider trait should be split. Aura/Baba/Grandpa should implement that trait individually.

Open questions:
How to register authority key providers
How to dispatch to an authority key providers through the offchain worker api

**Comment by folsen** [comment]
Should be fixed with #3213 once that's closed.

**Comment by gavofyork** [comment]
Yup - we don't want any kinds of "authority key providers". They should look after their own business and not be seeking to fulfil any normative PoS API.
