### ISSUE TITLE
srml-staking `DoSlash` impl: payout rewards to the misbehavior reporters

### ISSUE THREAD

**Issue by niklasad1** [paritytech/substrate#3166]
Currently, we are only slashing in `srml_staking::StakingSlasher` which in the future needs to give rewards to the misbehavior reporters.

The suggestion currently is to have to a type `Reporter: IntoIter<(AccountId, Perbill)>` where Perbill is the priority for a reporter.

All priorities must sum to at most `1.00`

**Comment by rphmeier** [comment]
This could be useful a bit further on to smooth out fisherman variance a bit with a commit-reveal style reporting. Rewarding only the first to the punch means that you are often at risk of front-running.

Instead we could have fishermen put forward the hash of the report payload and then it will be revealed later. Anybody who submitted the correct hash will be rewarded (with more going to the earlier reporters). To discourage front-running without knowledge of the misbehavior, we could allow nodes to put forward a hash of a "bait" string + a signature by the baiter. Anyone who submits the same hash but is not the signer of the bait string gets their money taken when the report was revealed to be bait.

**Comment by burdges** [comment]
We should not require that bait mechanism.  It suffices for fishermen to hash some secret local randomness and their own public key into their commit.  

As an aside, you could save fishermen from even tracking this secret local randomness by placing the VRF output point, or some bytes output, into the commitment, but providing the input and proof only in the reveal, not in the commitment.  We cannot make fishermen stateless anyways though, and almost all transactions include some randomness, so this serves no real purpose, and the hashing solution is vaster for verifiers.
