### ISSUE TITLE
Why do we use Incrementalnput in srml_support for storage

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#3168]
get function in srml_support is implemented as such:

https://github.com/paritytech/substrate/blob/a534483d546ac2554160e095772fc6fb3b47da87/srml/support/src/storage/unhashed/mod.rs#L24-L33

it make use of incremental input which is implemented there:

https://github.com/paritytech/substrate/blob/a534483d546ac2554160e095772fc6fb3b47da87/srml/support/src/storage/mod.rs#L30-L42

When implementing Decoding we usually make a lot of call to read, mostly with few bytes, I can't find the reason for those reads to be split, I think we should just do a read_storage and and decode from `&[]`.

Do I miss something ? if no then this can be done for child::get as well.

**Comment by bkchr** [comment]
I once stumbled over this as well and after some thinking found a reason for it, but I don't remember it anymore xD 
In general this looks like some try to optimize the storage access, but you are right and that this probably generates to much read accesses. I think you can remove it.

**Comment by thiolliere** [comment]
actually implementing it the correct make the CI failing:

apply this diff on master for instance:

```diff
diff --git a/srml/support/src/storage/unhashed/mod.rs b/srml/support/src/storage/unhashed/mod.rs
index 77e6c2b37..573cf33ce 100644
--- a/srml/support/src/storage/unhashed/mod.rs
+++ b/srml/support/src/storage/unhashed/mod.rs
@@ -23,12 +23,12 @@ pub mod generator;
 
 /// Return the value of the item in storage under `key`, or `None` if there is no explicit entry.
 pub fn get<T: Decode + Sized>(key: &[u8]) -> Option<T> {
-       runtime_io::read_storage(key, &mut [0; 0][..], 0).map(|_| {
-               let mut input = IncrementalInput {
-                       key,
-                       pos: 0,
-               };
-               Decode::decode(&mut input).expect("storage is not null, therefore must be a valid type")
+       runtime_io::read_storage(key, &mut [0; 0][..], 0).map(|len| {
+               // TODO TODO: the +1024 works but this a bug no?
+               // let mut buffer = sr_std::vec![0; len+1024];
+               let mut buffer = sr_std::vec![0; len];
+               runtime_io::read_storage(key, &mut buffer, 0).expect("storage is not null");
+               Decode::decode(&mut &buffer[..]).expect("storage is not null, therefore must be a valid type")
        })
 }
 
```

**Comment by thiolliere** [comment]
it is on the key `:extrinsic_index`
