### ISSUE TITLE
no block produced in staging mode

### ISSUE THREAD

**Issue by hexinlee** [paritytech/substrate#3172]
Hi, I used below command to start my own chain based on Substrate, but **the best blocknum and finalized blocknum were always 0.**

./target/release/mychain --chain=staging --validator -d ./tmp/node1 --key 0x03d082749cc7e1e6562dd4f8d9051898b2e5fa8ad028b3e33a3545ace8dc5e08 --name node1  --rpc-cors all --rpc-external --ws-external &

./target/release/mychain --chain=staging --validator -d ./tmp/node2 --key 0xad09085a5894744ce3ccf5dd979eb7f83a2d37402eb7d49a156821aecd92c54d --name node2 --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmTk3WbKzScQjXe5SdXoPMkBNzwSom1GPr8Yw6i3scUxfJ --port 30334 --rpc-cors all --ws-external --rpc-external &

./target/release/mychain --chain=staging --validator -d ./tmp/node3 --key 0x79a1edba7b6e3c04e38802c185223b17f76905bf3969441ff7145e9017955127 --name node3 --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmTk3WbKzScQjXe5SdXoPMkBNzwSom1GPr8Yw6i3scUxfJ --port 30335 --rpc-cors all --ws-external --rpc-external &

./target/release/mychain --chain=staging --validator -d ./tmp/node4 --key 0xe629f234fb4049ca02befadf860e517caa51c7ff172513657dd964578a139e13 --name node4 --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmTk3WbKzScQjXe5SdXoPMkBNzwSom1GPr8Yw6i3scUxfJ --port 30336 --rpc-cors all --ws-external --rpc-external &

**Please note:
1.this phenomenon only happened for staging mode, it's Ok for local/dev mode.
2.now my chain is based on the commitId "5fd945581b862e7e215d2a49d301c78bea70db6f" of Substrate. When I reverted the based commitId to "f923ae2ac056da19feed7084eccdf84d9c545ab4", everything becomes OK.

Please help check what's happening about p2p connection after commit f923ae2ac056da19feed7084eccdf84d9c545ab4.

Thank you

**Comment by bkchr** [comment]
Can you please try latest Master?

**Comment by hexinlee** [comment]
> Can you please try latest Master?
I tried latest commit 0671a41b31b596686a41be6d338108a62de4e0af. 
The bset blocknum and finalized blocknum are still always 0 in staging mode in Macos. ..

**Comment by hexinlee** [comment]
@bkchr hi, please see the above comment. It still doesn't work.

**Comment by Kianenigma** [comment]
I think at this point your commands + chain_spec, if you used a custom one, would also help to debug this.

**Comment by hexinlee** [comment]
@Kianenigma 

[chain_spec.txt](https://github.com/paritytech/substrate/files/3429346/chain_spec.txt)
Hi, this is the chain_spec. 

The commands were as below:
./target/release/mychain --chain=staging --validator -d ./tmp/node1 --key 0x03d082749cc7e1e6562dd4f8d9051898b2e5fa8ad028b3e33a3545ace8dc5e08 --name node1 --rpc-cors all --rpc-external --ws-external &

./target/release/mychain --chain=staging --validator -d ./tmp/node2 --key 0xad09085a5894744ce3ccf5dd979eb7f83a2d37402eb7d49a156821aecd92c54d --name node2 --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmTk3WbKzScQjXe5SdXoPMkBNzwSom1GPr8Yw6i3scUxfJ --port 30334 --rpc-cors all --ws-external --rpc-external &

./target/release/mychain --chain=staging --validator -d ./tmp/node3 --key 0x79a1edba7b6e3c04e38802c185223b17f76905bf3969441ff7145e9017955127 --name node3 --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmTk3WbKzScQjXe5SdXoPMkBNzwSom1GPr8Yw6i3scUxfJ --port 30335 --rpc-cors all --ws-external --rpc-external &

./target/release/mychain --chain=staging --validator -d ./tmp/node4 --key 0xe629f234fb4049ca02befadf860e517caa51c7ff172513657dd964578a139e13 --name node4 --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmTk3WbKzScQjXe5SdXoPMkBNzwSom1GPr8Yw6i3scUxfJ --port 30336 --rpc-cors all --ws-external --rpc-external &

But I guess it's not related with Chain_spec, since everything is OK when using old commit of Substrate. As my own experience, after "f923ae2ac056da19feed7084eccdf84d9c545ab4", the block producing becomes bad, always 0.
