### ISSUE TITLE
Aggregate + Clean runtime fixed point arithmetic types

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#3189]
### Currently we have: 

- Perbill
- Permill
- PerU128
- Fixed64

###  Need to add: 

- [ ] [`RationalU32 `](https://github.com/paritytech/substrate/pull/2882#discussion_r306745580)
- [ ] Clean up PerU128
- [ ] Make the Api and exposed functions of _all_ of them consistent. All should expose `normal`, `checked`, `saturating` etc.

### Maybe

- [ ] Move to a new sr-arithmetic crate or arithmetic.rs in `sr-primitives`.
- [ ] Extensive and unified tests for all of them.
- [ ] Should probably close ~https://github.com/paritytech/substrate/issues/2558~ https://github.com/paritytech/substrate/issues/2908 along the way.
- [ ] There are some usages of multiplication and power of 2 in https://github.com/paritytech/substrate/pull/3322

CC @thiolliere

**Comment by thiolliere** [comment]
instead of `RationalU32` I would name it `FractionalU32` because it can't exceed 1, or maybe we can make that it can exceed one.

**Comment by thiolliere** [comment]
PerU128 doesn't implement multiplication which is to distinguish with Perbill and Permill

**Comment by xlc** [comment]
Those types will be very useful to ink as well. Does it make sense to move them into a standalone fixed point rust crate?
