### ISSUE TITLE
Telemetry websocket connection does not respond to PING

### ISSUE THREAD

**Issue by mattrutherford** [paritytech/substrate#3190]
Previously when using the `ws` library, the telemetry connection would respond to ping ( https://tools.ietf.org/html/rfc6455#section-5.5.2 ). Would be great if we can reinstate this functionality.

**Comment by tomaka** [comment]
cc @twittner

**Comment by twittner** [comment]
The web-socket implementation used for telemetry responds to pings if the connection is polled. I think that telemetry is only writing to the connection, but never reading from it, hence `<soketto::connection::Connection as Stream>::poll` is never called.
