### ISSUE TITLE
ledger nano s support

### ISSUE THREAD

**Issue by dvc94ch** [paritytech/substrate#3198]
Wondering if anyone has looked into this yet. Yubikey support ed25519, but the main advantage of a hardware wallet is displaying the transaction on the display so that you know what you are actually signing.  It looks like one would have to write a substrate app for bolos (the ledger os), which interprets the extrinsics for display.

**Comment by Kianenigma** [comment]
Just recalling that was discussed a few times in public chats in Riot as well. Maybe @folsen can recall what was the conclusion?

**Comment by jacogr** [comment]
It is part of the W3F grant program, https://github.com/w3f/Web3-collaboration/issues/14

**Comment by folsen** [comment]
Definitely something we want, but yes we'd have to write an app for it. If there's a grantee that can do it that'd be great, but lets keep an eye on this and try to make sure it looks like we'll have something in place for launch.

**Comment by dvc94ch** [comment]
The main difficulty with the app is that runtime upgrades might break it. It looks like an interesting weekend project to get yubikey/nano s to sign transactions, without using the display. We need this for https://github.com/paritytech/ink/issues/134.

For this one needs to construct an apdu packet, and then send it to yubikey with pcsc-rust and the ledger using ledger-rs.

**Comment by folsen** [comment]
> The main difficulty with the app is that runtime upgrades might break it.

That's why I'd wait as long as possible with it so we're reasonably sure that whatever we built it against is stable enough.

**Comment by bkchr** [comment]
Should be done
