### ISSUE TITLE
MaybeDisplay no longer necessary

### ISSUE THREAD

**Issue by bddap** [paritytech/substrate#3212]
The `Display` trait, has been moved from `std::fmt` to `core::fmt` and should now be compatible with no_std crates.

[MaybeDisplay](https://github.com/paritytech/substrate/blob/f9e5a3742cfecb7f8f89c7c961ae900cca645b65/core/sr-primitives/src/traits.rs#L581-L591) can now be removed for simplicity.

**Comment by xlc** [comment]
We still want to avoid having types implement `Display` trait in wasm to avoid size bloat.

**Comment by bddap** [comment]
Consider whether that optimization is worth the extra complexity. Remember, this is part of the substrate public interface and therefore user-facing.

It's usually a good idea to test optimizations. Tests may show that MaybeDisplay doesn't make a difference on wasm size.

**Comment by bkchr** [comment]
I don't see the complexity of `MaybeDisplay` and as highlighted by @xlc `Display` introduces a lot of code bloat.
Given this, I close this issue.
