### ISSUE TITLE
Allow transaction pooling for the smart contract transaction when current block gas limit is full 

### ISSUE THREAD

**Issue by satyamakgec** [paritytech/substrate#3231]
I was going through the implementation of the `srml-contract` module and it has this comment https://github.com/paritytech/substrate/blob/855ad098501e560600a76b81fa3251dab2af228b/srml/contracts/src/gas.rs#L203
Which doesn't makes sense to me, It will make lot of transaction fail if current block doesn't has the limit to execute. Don't we have some kind of pooling of the transaction ?

**Comment by tomusdrw** [comment]
`BLOCK_FULL` error returned down the line should be handled by the authorship module and such transaction should be retried in the next block. Is that not what you experience?

**Comment by satyamakgec** [comment]
@tomusdrw if it works as you describe then I think it is not an issue, I did not test the behavior yet I was only exploring the code and this comment makes me confuse. I think it is better to mention this behavior in the module as a comment. If you want I can raise a PR for this.

**Comment by tomusdrw** [comment]
Well, that's pretty much precisely what a comment 3 lines below says:
https://github.com/paritytech/substrate/blob/855ad098501e560600a76b81fa3251dab2af228b/srml/contracts/src/gas.rs#L207

Feel free to open a PR and improve the comments, I'm closing this since I don't think it's an issue.
