### ISSUE TITLE
Upgrade schnorrkel

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/substrate#3243]
It is currently several major versions old.

**Comment by burdges** [comment]
There was a reason for skipping those version in that they were breaking wire format.  We're now done with the audit, and anything else I thought up, so the current wire format is final in 0.7.0.  

An update would break any testnets running, unless someone writes a shim for the verify routines that accepts both.

**Comment by kianenigma** [comment]
related to https://github.com/paritytech/substrate/issues/3245
