### ISSUE TITLE
Replace `slog` with `log` once `log` supports structured logging

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#3260]
The entirety of Substrate uses the `log` crate, except for the telemetry which uses `slog` because of structured logging.

The `log` is currently getting support for structured logging:
https://github.com/rust-lang-nursery/log/issues/149
https://github.com/rust-lang-nursery/log/issues/328

Once this is done, we can switch out from `slog`.

**Comment by yoshuawuyts** [comment]
https://github.com/yoshuawuyts/kv-log-macro now works, which coupled with the `kv_unstable` macro should probably cover most of what you might want from a logging solution (:

**Comment by gnunicorn** [comment]
> We're using `slog` just to have a global logger and to serialize json, we could replace it with `serde_json` and `lazy_static`

**Comment by tomaka** [comment]
If someone tackles this issue, please add me as a reviewer.

**Comment by bkchr** [comment]
Telemetry isn't using `slog` anymore.
