### ISSUE TITLE
Telemetry worker doesn't detect if server isn't responsive

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#3276]
If the telemetry server closes the connection (ie. sends a FIN) then Substrate will try to reconnect as it should.

However if the connection simply isn't responsive (no ACK is sent back) then Substrate doesn't care.

**Comment by gterzian** [comment]
I'll look into this.

**Comment by tomaka** [comment]
This should be fixed by adding a timeout when writing data.
This is in the category of issues that would be trivial to solve if async/await were stable.
