### ISSUE TITLE
Support multi-range changes tries pruning

### ISSUE THREAD

**Issue by svyatonik** [paritytech/substrate#3282]
In post #3201 world, there'll be a way to update changes trie configuration on a living blockchain. Current pruning algorithm should be updated to support pruning tries from different config ranges. The algorithm should be as follow:
1) track (in DB) range `[RBEGIN; REND]` covered last non-pruned top-level digest trie. It could be a trie built using current (active) configuration or one of previous;
2) when block `B` is finalized, check if `B - REND > max_blocks_to_keep`:
2.1) if true: prune that trie (and all lower-level digests) + start tracking next trie (that is probably created using next configuration);
2.2) if false: do nothing

**Comment by abebeos** [comment]
Remove https://github.com/paritytech/substrate/labels/U1-asap
