### ISSUE TITLE
Light client fails to sync flaming fir

### ISSUE THREAD

**Issue by svyatonik** [paritytech/substrate#3289]
For BABE chains light client should have an access to the `Epoch` data to validate blocks. Given that genesis block is available on light client, we know the epoch#0 data => client verifies epoch#0 blocks successfully. Next epoch#1 (on current Flaming Fir) starts from block#55 => block#54 contains a digest that has a data for epoch#2 (that's the main diff with Aura, where we had a digests that were applied starting from the next block). But apparently we're missing data for epoch#1 here.

I've chatted with @andresilva (thanks for your help) && looks like there's no way to build epoch#1 data using genesis block (which is available locally on light) => the only way is to fetch it from remote node. Like we do with finality proofs. This, however, differs from finality proofs because there we're still able to import block && here import will fail. So the solution is: (1) either pause sync process until response is received or (2) allow import of block even though it can be invalid.

**Comment by tomaka** [comment]
We could tweak the sync code so that nodes automatically send us everything that's needed for syncing?

**Comment by andresilva** [comment]
The light client will need to handle this case explicitly by making a remote call request so that a full node can give it the data it needs from runtime execution. This is only needed for Epoch #1, because BABE always emits digest data for epoch N+1, so when Epoch #0 ends, the light client will get data for future Epoch #2 from header digest and cache it. From then on, it won't need to do anymore remote call requests to be able to verify header, it will always have the data at hand extracted from digests in it's local cache.

**Comment by tomaka** [comment]
Since this only concerns epoch #1, what about we accept potentially invalid blocks just for epoch #1?

**Comment by svyatonik** [comment]
> Edit: actually the remote call request may not be the best option as it relies on good availability on the network of really old states (most nodes will have these pruned after a while). So maybe the full nodes will actually need to persist this Epoch data?

Good point, similar to #2554 . So probably instead of general remote-call, it should be a consensus-specific message (similar to finality proof) + the proof of `::epoch()` call should be saved on full nodes. Let's fix this issue without pre-creating the proof and fix it withing #2554 . I wanted to introduce elimination of the ":code" from remote-call-proof before fixing that issue.

> This only concerns epoch #1, right? So we could accept potentially invalid blocks just for epoch #1?
Is that somehow attackable?

Right. The only attack I can think about is spamming light database+import queue with invalid blocks. But eventually we'll connect right peer + get correct blocks, which will be finalized. So I'd vote yes for accepting invalid blocks but only for epoch#1. I have already tried to implement 'pausable sync' about a year ago && it was a painful process. Now, of course, it'll be even more painful.

Another issue iirc is currently we're using `LongestChain` as a best chain selection strategy on light nodes => until we'll see finalized block, we'll treat those invalid blocks as the 'best' => will use these by default in RPCs, informant and so on.

**Comment by tomaka** [comment]
> Another issue iirc is currently we're using LongestChain as a best chain selection strategy on light nodes => until we'll see finalized block, we'll treat those invalid blocks as the 'best' => will use these by default in RPCs, informant and so on.

We can create another `SelectChain` named `Finalized` that selects the finalized block, right?

**Comment by svyatonik** [comment]
I believe so, but this strategy may have its opponents. Anyway, if we'll go the import-invalid-block way, then `FinalizedChain` must be introduced before. I'll try to open PR for that today.
