### ISSUE TITLE
Outdated references to `MakePayment`

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#3299]
`MakePayment` trait is been removed but it still exists in a few comments.

https://github.com/paritytech/substrate/blob/89a56adaf8512ab55aabe4f1d9725e3a1baaba11/srml/contracts/src/lib.rs#L428

https://github.com/paritytech/substrate/blob/1fcd1286d87dc7acb8c2b0ee3ff6fe2199536ea0/srml/balances/src/lib.rs#L75

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by kianenigma** [comment]
yeah, must be gone. 

We need a new doc explaining the replacement approach, signed extensions. I wanted to write this asap.
