### ISSUE TITLE
Implement decode_len on storages by decl_storage

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#3302]
parity-scale-codec does provide the feature of decoding only the length an element (the lenght of a vec for instance). storage with such element should provide this feature on its element.

This is a placement issue for reference from the code.

**Comment by kianenigma** [comment]
I am more or less doing the same here: #3071 but the PR has taken a bit too long. I suppose if either of us can add Basti's recommendation on having a `noDefault`  marker trait, then it should be good to go.

**Comment by thiolliere** [comment]
yes maybe but at some point I wanted them to be implemented same as append in StorageValue just after a where condition.

Actually I think we can implement them for both map and linkedmap so it is fine behind where condition.

**Comment by thiolliere** [comment]
actually done in https://github.com/paritytech/substrate/pull/3344
