### ISSUE TITLE
Client hangs syncing Flaming Fir

### ISSUE THREAD

**Issue by sjeohp** [paritytech/substrate#3308]
Around 1/3 of the time syncing from scratch (using [d013bd900](https://github.com/paritytech/substrate/commit/d013bd900face690506312771d22e46a7590e5a9)) the client hangs indefinitely and won't respond to signals.  Trace indicates a minute or so of all peers being busy, then "too many blocks in the queue" forever.

**Comment by tomaka** [comment]
We've noticed a similar issue on the bootnodes. The issue seems to be that when syncing we receive blocks that are not part of the finalized chain.

**Comment by arkpar** [comment]
@tomaka What makes you think so? Debugging shows it is an endless loop in `TelemetryWorker::poll`

**Comment by tomaka** [comment]
The issue isn't about master, so I was trying to blindly guess that it could be the issue that we saw earlier today. If it's the telemetry, then we can close as fixed.
