### ISSUE TITLE
The signature signed by subkey could not be verified on polkadot.js.org

### ISSUE THREAD

**Issue by en** [paritytech/substrate#3383]
Does the signature algorithm not match now?
subkey commit 6fbca29c341254433c8d56db8473ae1f7004f6a3
```
$ subkey inspect //Alice
Secret Key URI `//Alice` is account:
  Public key (hex): 0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d
  Address (SS58): 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY

$ echo -n abc | subkey sign //Alice
0a8957f6e37a6025baa67395dcb86d7a5a543b65f880d8d3c73c77d4a7e08f718e068233c3d05b1e60467a21446a1d8be319e41f71ddb1c572ff4c3b76913d84

$ echo -n abc | subkey  verify 0a8957f6e37a6025baa67395dcb86d7a5a543b65f880d8d3c73c77d4a7e08f718e068233c3d05b1e60467a21446a1d8be319e41f71ddb1c572ff4c3b76913d84 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
Signature verifies correctly.
```
![image](https://user-images.githubusercontent.com/14307069/62941073-c3c49680-be07-11e9-9d64-d284be791ca6.png)

**Comment by kianenigma** [comment]
as far as I had a look subkey is doing everything right, double-checking that the latest check for genesis hash is also there. Probably will be resolved as someone from the js team takes a look. 

@jacogr @Tbaut maybe the recent schnorrkel update is related?

**Comment by jacogr** [comment]
echo adds an `\n` - that is not in the string as entered on the UI.

**Comment by bkchr** [comment]
I think this now can be closed? 
If not, please reopen.
