### ISSUE TITLE
Unpin the version of futures-preview

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#3386]
As a quick fix for broken master, we pinned `futures-preview` to version 0.3.0-alpha.17. Version alpha-18 is released but we get errors while switching to it.

**Comment by YaaMe** [comment]
[runtime 0.3.0-alpha.7](https://crates.io/crates/runtime/0.3.0-alpha.7) updated
Problem seems to be solved.

**Comment by tomaka** [comment]
Can be closed. We're not using `futures-preview` anymore.
