### ISSUE TITLE
Expected epoch change to happen by this block

### ISSUE THREAD

**Issue by Tore19** [paritytech/substrate#3415]
Change MILLISECS_PER_BLOCK from 6000 to 2000.

Run ./target/release/substrate --dev.

After running sometimes, it shows error: ClientImport("Expected epoch change to happen by this block")

**Comment by Tore19** [comment]
The epoch slots seems to be something wrong with it
![image](https://user-images.githubusercontent.com/10955745/63154388-13db6d00-c043-11e9-992c-c06026b42e85.png)

And then it stucked.
![image](https://user-images.githubusercontent.com/10955745/63156009-5a7e9680-c046-11e9-9033-6c0ab792abf5.png)

**Comment by bkchr** [comment]
I think this was fixed in master. 
@andresilva am I correct?

**Comment by Tore19** [comment]
Yeah. It was fixed. Thanks for your attention.

**Comment by Tore19** [comment]
It was fixed in master

**Comment by bkchr** [comment]
Thanks for reporting back and closing the issue 👍
