### ISSUE TITLE
Expose SignedExtra details in metadata

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#3427]
This is required for JS SDK to know the extrinsic format. Otherwise JS SDK have to hardcode the extrinsic format for a given known chain.

Right now the SignedExtra for note-template is not in sync with substrate node
https://github.com/paritytech/substrate/blob/7854edb46403accd95cfdd5ba83b89ef2495c2c6/node-template/runtime/src/lib.rs#L240

And this cause all polkadot.js transaction fail with a bad signature error (error code 0). It is hard/impossible to diagnosis this kind of issue for a new substrate developer.

**Comment by kianenigma** [comment]
- node-template should become happy again via https://github.com/paritytech/substrate/pull/3422

Not sure if the metadata thingy is a good idea or not.

**Comment by xlc** [comment]
Fixed by #4774
