### ISSUE TITLE
Nit: make `subscribeFinalizedHeads` and `subscribeNewHead` consistant

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#3431]
https://github.com/paritytech/substrate/blob/fa253b92979177c3ebac8a718be1dbc8a2c0e116/core/rpc/src/chain/mod.rs#L70

https://github.com/paritytech/substrate/blob/fa253b92979177c3ebac8a718be1dbc8a2c0e116/core/rpc/src/chain/mod.rs#L88

Please close if this is not an issue, but it seems weird that we have inconsistent plurality with `subscribeFinalizedHeads` and `subscribeNewHead`.

Seems like both should either be plural or singular `Head`.

**Comment by jacogr** [comment]
If it does get changed either way, please just remember to add an alias for the old version as to not create absolute chaos on the APIs. (Since it has no way to detect what is available prior to making a call)
