### ISSUE TITLE
Include ./build.sh into the build process if nightly is detected

### ISSUE THREAD

**Issue by chevdor** [paritytech/substrate#346]
From a discussion on #polkadot-watercooler:matrix.org

chevdor:
> Is there currently a reason why the ./build.sh script needs to be ran manually vs being integrated to the build process ? Would that make sense to make a PR for that?

> <...>

Gav:
> That said, if you could detect that the nightly compiler was available and then conditionally build it, that would be good, I think.

**Comment by gavofyork** [comment]
Closing this for now, since it's not clear it would be a step forward
