### ISSUE TITLE
Proposition: Linked map: put linkage upfront with fixed size.

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#3466]
This proposition is to implements swap method on linked_map efficiently: https://github.com/paritytech/substrate/issues/3341

Currently linked_map is implemented as such:
* head of the linked map is stored at a specific key: it contains the key (not hashed, just the encoded key).
* every elements are append with a linkage structure which contains previous and next key (still not hashed just encoded key) wrapped in option.

I propose to change this a such:
* head contains hashed key of the first elemnt
* every element contains a linkage with fixed size and preprend to the value inserted.
```rust
struct Linkage {
next_hashed_key: [u8; hash_size],
next_hashed_key_exists: bool,
previous_hashed_key: [u8; hash_size],
previous_hashed_key_exists: bool
}
```

Then:
* get method instead of just reading the value will have to read the value in storage after the linkage size. Just calling sr_io::read_storage with corresponding offset is fine.

Pros:
* we can implement swap method without decoding value: just swapping the raw bytes after linkage is fine
* for keys bigger than their hash the linkage is smaller.

Cons:
* This is a breaking change
* we can also just implement an unefficient swap for linked_map (by decoding values).
* for keys smaller than their hash the linkage is bigger now.

**Comment by tomusdrw** [comment]
AFAIR I was considering something like this, but the goal was to also be able to iterate over keys. With this approach it's either not possible, or the unhashed key would need to be included in the linkage as well, no?

**Comment by thiolliere** [comment]
oh yes with this design it is not possible to iterate over keys. we can't really include key into linkage as key size is not bounded.

Another solution would be to prepend the size of the value in the current design:
value_size++value++linkage.

Thus we could implement swap without decoding value.
I'm not sure it worth it anymore though

**Comment by thiolliere** [comment]
also maybe too late for this, I will just fix the swap by making an inefficient implementation, it is ok.
