### ISSUE TITLE
I can nominate with 0 bonded unit

### ISSUE THREAD

**Issue by Tbaut** [paritytech/substrate#3521]
How to reproduce:

- bond X nits (with X > ED) from Bob_stash linked to Bob
- unbond everything so that bonded = 0
- nominate Alice
- the extrinsic succeeds

![image](https://user-images.githubusercontent.com/33178835/64036863-79a41a80-cb54-11e9-9152-69ee7f3122a8.png)

**Comment by kianenigma** [comment]
I think: we are forgetting the fact the once you call unbond you are technically still locked and bonded; you are _scheduled to unbond_ after x blocks. In your scenario, after X block your account should be removed and hence no longer a staker/nominator.

I am on phone and can't dig deeper until late next week but if what I said makes sense to you then this is invalid.

**Comment by DemiMarie-parity** [comment]
@Tbaut @kianenigma does the UI make this clear?

**Comment by Tbaut** [comment]
> I think: we are forgetting the fact the once you call unbond you are technically still locked and bonded; you are scheduled to unbond after x blocks. In your scenario, after X block your account should be removed and hence no longer a staker/nominator.

Checking this now.

> does the UI make this clear?

Not entirely. This is why the issue was originally opened in the UI repo. We're now in the process of verifying where the culprit really is.

**Comment by joepetrowski** [comment]
> I think: we are forgetting the fact the once you call unbond you are technically still locked and bonded; you are scheduled to unbond after x blocks. In your scenario, after X block your account should be removed and hence no longer a staker/nominator.

So can you still validate/nominate with funds that are unbonding? So you can wait until the last day, commit some misbehavior, and then escape slashing as long as you aren't discovered right away. And the whole point of unbonding is to prevent that.

**Comment by rphmeier** [comment]
Indeed - you shouldn't be able to nominate or stake with funds that are unlocking.

**Comment by kianenigma** [comment]
what you have stored in an unlocking chunk (scheduled to unlock soon) is still recorded and bonded (not sure if the term is correct here)(solid example: you are rewarded based on that + you vote with that stake) but you are also slashable by that amount. 

For the purpose of preventing what Joe explained: that's indeed true but I thought this is exactly why something with a name like historical session data was added where we store old validators and their exposures. or am I missing sth @rphmeier ? afair you either added this yourself or you were in the loop.

**Comment by rphmeier** [comment]
> but you are also slashable by that amount.

@kianenigma 
Is it for as long as it's meant to be? If I have 1 hour/minute/second left before my funds unlocked, I'll only be slashed if my misbehavior is detected and slashed before my funds unlock. The point of the unbonding period is that we have a minimum amount of time to detect when somebody has misbehaved.

It's wrong to say that someone is slashable for that amount if that's not the case.

**Comment by kianenigma** [comment]
> It's wrong to say that someone is slashable for that amount if that's not the case.

Correct, my explanation is wrong. And I was actually totally wrong: 

the code that I linked to (using `.total`) seem to be a dead code and this is the correct one which uses only `.active`, meaning that unstaking portion is never used for nomination etc. 

https://github.com/paritytech/substrate/blob/d2e7d660f8dbbb8f9753dfd231cef1c9b502c41c/srml/staking/src/lib.rs#L1234-L1236

PR: https://github.com/paritytech/substrate/pull/3284

Then we're fine regarding that. 

Back to the core of the issue, how the UI renders this

> Checking this now.

what up @Tbaut?

**Comment by gavofyork** [comment]
The UI should not enable those buttons if the active bonded amount is zero. This is, in any case, a UI issue and should be moved there.

**Comment by rphmeier** [comment]
It seems rather to be an `srml-staking` issue, if confirmed. It's not secure to nominate with withdrawing funds (as it undermines the purpose of the withdrawal period)

**Comment by kianenigma** [comment]
> It seems rather to be an srml-staking issue, if confirmed. It's not as secure to nominate with withdrawing funds (as it undermines the purpose of the withdrawal period)

Perhaps you missed my last comment that:

> the code that I linked to (using `.total`) seem to be a dead code and this is the correct one which uses only `.active`, __meaning that unstaking/unbonding portion is never used for nomination, votes__ etc.

**Comment by rphmeier** [comment]
Right, I did indeed miss that.

**Comment by Tbaut** [comment]
From my tests: 
An extrinsic with such an account (with `active:0`) succeeds: `{"stash":"JKspFU6ohf1Grg3Phdzj2pSgWvsYWzSfKghhfzMbdhNBWs5","total":"0x0000000000000000018a59e972118000","active":0,"unlocking":[{"value":"0x0000000000000000018a59e972118000","era":672}]}`

the `staking.nominators (Vec<AccountId>, Linkage<AccountId>)` gets populated subsequently. 
`[["5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY"],{"previous":null,"next":null}]`

Now as soon as you call `withdrawUnbonded` the `staking.nominators` is cleared.

Looks good, should be handled on the UI side then.
