### ISSUE TITLE
Why drop a reference?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/substrate#3535]
After `cargo expand` I got something like this:

```rust
#[allow(non_upper_case_globals, unused_attributes, unused_qualifications)]
const _IMPL_ENCODE_FOR___InherentHiddenInstance: () = {
    #[allow(unknown_lints)]
    #[allow(rust_2018_idioms)]
    extern crate parity_codec as _parity_codec;
    impl _parity_codec::Encode for __InherentHiddenInstance {
        fn encode_to<EncOut: _parity_codec::Output>(&self, dest: &mut EncOut) {
            drop(dest);
        }
    }
};
```

Why drop a reference? 

I found [https://github.com/paritytech/substrate/issues/634](https://github.com/paritytech/substrate/issues/634). Just to ignore the `unsued` warning?

**Comment by bkchr** [comment]
Yes, why do you open a new issue for this?
The old issue already explained it.

**Comment by AurevoirXavier** [comment]
Sry, but he use **seemingly**. So I got confused.

**Comment by bkchr** [comment]
Okay. Yes we do this to prevent the unused warning. But we could probably improve this in the parity codec crate.
