### ISSUE TITLE
substrate.readme.io - project doesn't exist

### ISSUE THREAD

**Issue by edanilov** [paritytech/substrate#3537]
The page - https://www.parity.io/substrate-has-arrived/

> We’re hard at work making Substrate the most developer-friendly blockchain framework. We have started a developer hub where you can:
> 
> Get an overview.
> Learn how to install Substrate.
> Learn how to create a custom Substrate chain.

https://substrate.readme.io - Project doesnt exist... yet!

**Comment by shawntabrizi** [comment]
The correct link is now https://substrate.dev/

We will update the blog post. Closing this since it isn't related to the Substrate project directly.
