### ISSUE TITLE
`Maybe*` trait names are a bit misleading

### ISSUE THREAD

**Issue by c410-f3r** [paritytech/substrate#3551]
Currently, the conditional compilation of the `Maybe*` marker traits depend solely of the `std` feature. Having said that, a more precise naming like `StdSerializable` could enhance consistency and avoid potential misleads.

**Comment by kianenigma** [comment]
I am not against what you say, but reading your comment, I actually see one reason why `Maybe-xxx` is better: currently it is dependent on `std` or `no_std`, but in general this is just one case and in practice it could be any targeted/conditional compilation flags that determine if these Maybe traits are compiled or not. Hence, the word `Maybe` is more general

**Comment by bkchr** [comment]
Yeah, it is just a type that maybe implements a trait. I'm relative sure to have seen this pattern in other rust projects as well, but could not find an example with a quick search.

Given that and @kianenigma comment, I will close this. Nevertheless, thank you for your input :)
