### ISSUE TITLE
Can add #[derive(Debug, Serialize, Deserialize)] to function of struct UncheckedExtrinsic?

### ISSUE THREAD

**Issue by okayabc** [paritytech/substrate#3554]
pub struct UncheckedExtrinsic<Address, Call, Signature, Extra>
where
Extra: SignedExtension
{
/// The signature, address, number of extrinsics have come before from
/// the same signer and an era describing the longevity of this transaction,
/// if this is a signed extrinsic.
pub signature: Option<(Address, Signature, Extra)>,
/// The function that should be called.
pub function: Call,
} ,we know the function type is enum, because it doesn't derive Serialize, so can't change it to json format.

**Comment by bkchr** [comment]
Why do you need `Serialize`, `Deserialize`?

**Comment by okayabc** [comment]
Because i write a rust client to decode the extrinsic of every block. After decoded function field of UncheckedExtrinsic, i get a concrete enum value. Now i want to use serde_json::to_string to convert the enum value to the json format string, so i can get every argument's value.

**Comment by bkchr** [comment]
If you have the enum, why not match on it?

**Comment by okayabc** [comment]
Because the enum count equal all modules's function count, if i use match method, then i should match all modules's function. furthermore, parameter type and count of every function is not same. If adding a new function in node, i should also add corresponding match statement in my client, so using match is not a best method.  

If the enum can change to json format string, then we can decode the json string. 

All module's name , all function name of every module and all argement name and type of a function, all of these i can get using get_metadata call. 

Using the metadata, i can get the enum value directly, it will be more efficient and smart than using match statement.

**Comment by gavofyork** [comment]
this might have quite a lot of footprint, since we'd need to ensure that all `SignedExtensions` and their associated types also fulfilled those traits.

if you submit a PR, i'd take a look.

**Comment by okayabc** [comment]
Thank you very much!

**Comment by ltfschoen** [comment]
i'd like to be able to debug in a runtime module function using serde, i.e.
```
let stringified = serde_json::to_string(&my_json).unwrap();
debug::info!("Stringified json{:#?}", stringified);
```

otherwise we have to debug each individual field. i supposed we could just loop through all the fields... 
```
debug::info!("Field of json {:#?}", my_json.my_json_field);
```

@tomusdrw suggested we'd have to:
1) short-term: add serde support to the sr_io module
2) long-term: export lightweight serialize and deserialize json in runtime

**Comment by bkchr** [comment]
Why not use Debug for debugging?

**Comment by tomusdrw** [comment]
My suggestions were in the context of offchain workers, I don't think that if such external APIs are introduced (short-term solution) it would ever be exposed for regular runtime operations. I agree with @bkchr now that we have `Debug/RuntimeDebug`, it's actually better to just use this.
