### ISSUE TITLE
How to compute T::Balance by T::Moment

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/substrate#3560]
I dont know to how to convert T::Moment Type to T::Balance type for computing a fee which depend on time?
Is there any example?

**Comment by xlc** [comment]
You can convert Moment `.into()` to u32/u64 with and then again `.into()` Balance and then to multiply

Example https://github.com/kusamakitties/kusama-kitties/blob/3041538f8715728b50cfa07357bbb5ad7ef2c923/kkrml/kitties/src/lib.rs#L158-L160

**Comment by bkchr** [comment]
@yjhmelody problem solved?

**Comment by yjhmelody** [comment]
yes，thanks.
