### ISSUE TITLE
Prevent daisy-chained stash/controller accounts

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#3566]
When `staking::bond` is called, it only checks that the stash is not already a stash and the controller is not already a controller. This allows you to make the controller a stash account with another downstream controller.

Account roles should be exclusionary.

**Comment by burdges** [comment]
We should discourage making them the same, but it could be done correctly, so not sure if we're better off forbidding it or fixing any surrounding issue, but I'd default to fix anything this breaks, and then maybe forbid it if we think that improves usability or something.

**Comment by kianenigma** [comment]
Given the typical situation that a chain launches but has no balance transfers enabled yet, then a singular account as both stash and controller is basically the only way. 

All in all and given this, I am in for closing this as it is fine. A UI can prevent you from locking yourself out (bonding everything and thus your controller cannot pay for fees) and show you warnings.

**Comment by burdges** [comment]
Cool.  A stash selecting itself as controller is different form a daisy chain of course, so good UX might be giving that a special exception, but I've no strong opinions.
