### ISSUE TITLE
Exponentially growing validator rewards

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#3575]
I'm having issues with respect to the title. What runtime parameters should be changed to curb this?

Here's a link to the runtime and the chainspec:
- https://github.com/hicommonwealth/edgeware-node/blob/develop/node/runtime/src/lib.rs
- https://github.com/hicommonwealth/edgeware-node/blob/develop/node/service/src/chain_spec.rs

**Comment by drewstone** [comment]
My observations since they may help, I was running a local chain with alice, bob, charlie, dave, eve, and ferdie as validators. We have a per block treasury reward being issued.

- At first treasury earns roughly 4 tokens each block
- After some point (60 blocks I believe) the staking rewards skyrocket and treasury begins earning 89 Tera token units
- Validator balances also jump from 10 tokens to around 260,000, and after 120 blocks or so they grow to giga values.

Eventually, the node crashes in an attempt to multiple into an overflow since these values become so large. The nodes stall at block 179 since 180 would issue new rewards.

**Comment by thiolliere** [comment]
I take a look,

for information inflation model is written here https://github.com/paritytech/substrate/blob/9b08e7ff938a45dbec7fcdb854063202e2b0cb48/srml/staking/src/inflation.rs#L17-L54
for the spec https://research.web3.foundation/en/latest/polkadot/Token%20Economics/#inflation-model

**Comment by drewstone** [comment]
@thiolliere does this have issues when one changes the number of decimals in the token units? We use 18 but most chains I see being deployed on your end are 15. Could this have adverse effects?

**Comment by drewstone** [comment]
I may have found an issue (or I'm using something wrong) with respect to the OnRewardMinted hook of the staking module and the corresponding on_dilution of the Treasury module.
This call here: https://github.com/hicommonwealth/substrate/blob/develop/srml/staking/src/lib.rs#L1196
Combined with: https://github.com/hicommonwealth/edgeware-node/blob/develop/node/runtime/src/lib.rs#L260
Makes for an extremely large dilution issuance
I added an event in our copy of substrate and after the first era, am getting over 50 trillion new tokens minted to the Treasury
I added an event here: https://github.com/hicommonwealth/substrate/blob/develop/srml/treasury/src/lib.rs#L350
You can also replicate it by running with the following two validators on develop branch of edgeware-node

**Comment by drewstone** [comment]
I can confirm, removing the Treasury from the `OnRewardMinted` fixes these problems. @thiolliere
