### ISSUE TITLE
BABE epochs should change based on time-slot, not block number

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#3586]
[The BABE Spec](https://research.web3.foundation/en/latest/polkadot/BABE/1-cycle/)

Time is divided into discrete `slot`s. In the spec, with each epoch consisting of _exactly_ `epoch_len` slots. In the current implementation, epochs consist of _at minimum_ `epoch_len` slots.

However, the current implementation changes the epoch at the first block `>= epoch_len` slots after the start slot of the epoch. This is bad for two reasons:
  - it's not to-spec
  - block authors can temporarily delay the time for the new epoch to start, which forces the old randomness to be used

It also complicates equivocation slashing, since different blocks on small forks may have the same slot number, but be on different epochs (i.e. sessions). If the same validator has 2 different session keys on 2 chains, he can equivocate without being punished.

-------

Required Changes:
 
**Account for Time-Slot when Authoring/Verifying**
(core)

When determining which authority-set/randomness to verify under, we should account for time-slot.

We will change the `fn epoch` in BABE to follow this procedure:
  1. find the epoch information of the parent block
  2. compare that epoch's end-slot to the current slot number
    2a. if less, return that epoch
    2b. if greater than or equal to the end, return the successor epoch

**Account for chains that did not start with these changes**
(core)

unsure. there are a couple different options

1. hard-fork, which introduces special-cased validation logic for such chains (as part of chain spec or BABE config)
2. remove support for such chains

**Compute Randomness without the VRF Output of the Current Block**
(SRML)

After making the above core changes, the epoch can be considered to have changed just _before_ the epoch-changing block, as opposed to during/after. This means that the responsibility of authoring the epoch-changing block moves from the prior set to the new set. Thus the next-epoch randomness, as computed during the epoch change logic, should not include the VRF output from the pre-runtime digest of the block.

**Comment by rphmeier** [comment]
Assuming that the epoch start-times haven't actually drifted in such chains, there is an intermediary solution (in this case, the only differing point is that the epoch-change blocks are authored by the prior set/randomness as opposed to the new set/randomness).

1. The situation is equivalent to using a `>` condition as opposed to `>=` for checking blocks, and we absolutely trust the randomness given by the runtime. This is fine as long as we don't attempt to re-compute the randomness off-chain (light clients, verification queues w/ lookahead)
2. First, introduce a configurable transition (default: 0) for the slot number where we change to a `>=` condition
3. Next, introduce a runtime upgrade which performs the correct randomness calculation from that point onwards

**Comment by DemiMarie-parity** [comment]
@rphmeier will it necessarily? Light clients will need a snapshot anyway, and it makes sense to me that it should include the randomness.
