### ISSUE TITLE
Optimize tree_route and related, avoid read_header

### ISSUE THREAD

**Issue by marcio-diaz** [paritytech/substrate#3592]
When syncing it seems that we waste a lot of time in `read_header`, function that reads a header from db, when actually we only need the hash of the parent header. Functions that should be optimized:

- `is_descendent_of`, this function is quite un-optimized but heavily used in `import_block`.
- `ancestry`.
- `tree_route`

Using a hash map from `(hash -> parent_hash)` I could apparently reduce syncing Kusama from 2:20 hours to 20 minutes on my laptop.

**Comment by andresilva** [comment]
As discussed elsewhere, adding a LRU cache to use for these ancestry checks is probably a good idea.
