### ISSUE TITLE
Client should not require Block hash to be H256 for everything useful

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#3624]
This pollutes _everything_.

When we need to use hashes as keys on disk, I think it would be fine to truncate hashes to 256 bits silently and internally (as that is more than enough entropy), but not to require it as a type parameter everywhere.

**Comment by rphmeier** [comment]
@andresilva pointed out that somewhere `we need a bound proving that Backend::Hasher::Out == Block::Hash`.

We should aim to make this more flexible with some kind of conversion parameter or drop the requirement entirely.

**Comment by burdges** [comment]
I'm confused.. Isn't H256 exactly what avoid the type parameter everywhere?

**Comment by bkchr** [comment]
@burdges This line https://github.com/paritytech/substrate/blob/203e2c23b51bf23f778b3afee16465e6dca04cf2/core/client/src/client.rs#L301 is the one that should be dropped.

**Comment by rphmeier** [comment]
Well, I suppose in some sense it's avoiding a concrete specification of the hash algorithm, but Substrate in some places says "we're generic over the hash output length" and in most (important places) it says "the hash length must be 256 bits".

**Comment by burdges** [comment]
I see..  We need 256 bit hashes for 128 bits of security anyplace where birthday attacks pose a threat, like in Merkle trees.  We can safely neglect that we technically loose some security bits from the Merkle tree itself, so we do not afaik require more than 256 bits anyplace.  

If we identify places that only require fewer bits of security, like MACs, then we could make them use some `MacTag128` or `H192` types, but yeah I agree being generic over hash size everywhere is either harmful or useless.

**Comment by rphmeier** [comment]
Well, it should either be fully-generic or fully-non-generic, not some weird halfway-house.

**Comment by burdges** [comment]
I'm saying non-generic is fine.  If we find a place where a smaller size it appropriate, then we can make that non-generic at the smaller size.

**Comment by rphmeier** [comment]
Right - and just to clarify, any cryptographic non-safety caused by too-small hashes is not something that would arise as part of the implementation of this issue. That would happen in the chain configuration, where somebody might choose a hash size which is too small.

**Comment by DemiMarie-parity** [comment]
IMO, a better option would be to have a `type SubstrateHash = H256` and then use `SubstrateHash` everywhere.  That way, we can still change the type if we need to.

**Comment by bkchr** [comment]
DOne
