### ISSUE TITLE
Split BABE verification and authorship code into own modules

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#3642]
#3620 extracts the `SharedEpochChanges` to its own module, but there is still more to do.

some non-exhaustive suggestions:
The block verification logic that make up the bodies of the `BabeBlockImport` and `BabeVerifier` should be split out into free functions in a `verification` sub-module, which can be more easily tested.

`BabeVerifier` should do little more than call out to a `verify_block_unordered(header, parent_header, slot_now)` function.

the portion of `BabeBlockImport` that checks whether a block is first-in-epoch and if so, whether it has a new epoch digest, should be extracted as well.

Other code, like the slot worker definition, claiming slots, etc. should also be refactored out into separate modules, perhaps as `pub(crate)` items.

**Comment by DemiMarie-parity** [comment]
Doing the refactoring, it appears to me that `verify_block_unordered` needs a _little_ bit more information ― but not much more.
