### ISSUE TITLE
Possible child trie key collision when pruning

### ISSUE THREAD

**Issue by cheme** [paritytech/substrate#3648]
Currently two different child tries will store the encoded value of their trie node in rocksdb without any distinction of origin.

Therefore if two child tries got similar contents, part of their underlying trie node can be identical and the same rocksdb entry will be shared.

Since we do not use reference counting (for good reason) on our stored trie encoded node, it results in problematic key collisions, and makes child trie unusable if pruning is activated.

Tackling this can be done by using reference counting for our child trie rocksdb entries (this is not the prefered approach) or by isolating every child trie datas (prefixing rocksdb key values with a unique child trie id was the chosen approach in #2209).

Note that in the current code there is no distinction between rocksdb entries coming from the top level trie storage and the child trie storages, so prefix approach will need to either apply prefix to top level key or change the api to allow some trie (top) to store in a dedicated rocksdb column.

A previous PR #2209 did implement this, but a caveat was that the unique child trie technical identifier where stored on chain see https://github.com/paritytech/substrate/pull/2209#issuecomment-528811294 .

Note that usage of keyspace for keys under a child trie allows some efficient deletion. When a child trie get fully removed, the fact that next written entries for the same child trie key are using a new keyspace makes a prunning only on keyspace possible (no need to register every keys and possibility to make the actual pruning at rocksdb level).

**Comment by abebeos** [comment]
Could someone please add sections like this to this issue, and clarify if this is still an unsolved issue?

## Current Status

## Expected

## Possible Solution(s)

**Comment by cheme** [comment]
Sorry, this was fixed in https://github.com/paritytech/substrate/pull/4162 (long ago).
