### ISSUE TITLE
`decl_storage!` should forbid default value for `Option` types

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#3671]
```
decl_storage! {
	trait Store for Module<T: Trait> as SomeModule {
		pub Value : Option<bool> = None;
	}
}
```

This should compile to an error saying that `= None` is not supported. Having a default value for optional types makes no sense, so we should just forbid it. The default value, if not set at genesis, should always be `None`.

Estimated time frame to complete: 3-5hours.

**Comment by kianenigma** [comment]
If October goes by and no one takes this, I can :p

**Comment by expenses** [comment]
Not very elegant, but inserting something like
```rust
if name.to_string().starts_with("Option<") && default_value.inner.is_some() {
    panic!("{}: Default values for Options not allowed", name);
}
```
at https://github.com/paritytech/substrate/blob/master/srml/support/procedural/src/storage/transformation.rs#L762 would do the trick, right?

**Comment by kianenigma** [comment]
there is a `type_infos.is_option` that should make it even easier.

I don't think ^^ would work. I can do `type Kian<T> = Option<T>` and then... ? 🤷🏻‍♂️

**Comment by bkchr** [comment]
> Not very elegant, but inserting something like
> 
> ```rust
> if name.to_string().starts_with("Option<") && default_value.inner.is_some() {
>     panic!("{}: Default values for Options not allowed", name);
> }
> ```
> 
> at https://github.com/paritytech/substrate/blob/master/srml/support/procedural/src/storage/transformation.rs#L762 would do the trick, right?

Never panic in proc macros! Never! Return a `syn::Result` and convert the error to a compile error: https://docs.rs/syn/1.0.5/syn/struct.Error.html#method.to_compile_error

Use `is_option` as highlighted by @kianenigma. You could still add an option, if you rename it, but then you don't get the effects that you normally get in the macro.
