### ISSUE TITLE
`decl_storage!` should import the storage traits automatically

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#3672]
`decl_storage!` should include the traits for `StorageLinkedMap`, `StorageValue`, etc defined here: https://github.com/paritytech/substrate/blob/master/srml/support/src/storage/mod.rs

The traits should be included by `use StorageLinkedMap as _` to not clash with any other trait includes.

Expected time frame: 2 hours.

**Comment by expenses** [comment]
This can be closed now :^)
