### ISSUE TITLE
ProvideRuntimeApi is not implemented for AbstractService::client()

### ISSUE THREAD

**Issue by alleycat-at-git** [paritytech/substrate#3684]
**Reproducing issue:**

Add these lines to node/cli/src/lib.rs, `fn run` (https://github.com/paritytech/substrate/blob/master/node/cli/src/lib.rs#L172)

```
use sr_primitives::traits::ProvideRuntimeApi;

let svc = service::new_full(config).map_err(|e| format!("{:?}", e))?;
let runtime_api = svc.client().runtime_api();
```

This errors with 
```
174 |             let rutime_api = svc.client().runtime_api();
    |                                           ^^^^^^^^^^^
    |
    = note: the method `runtime_api` exists but the following trait bounds were not satisfied:
            `substrate_client::client::Client<<impl substrate_service::AbstractService as substrate_service::AbstractService>::Backend, <impl substrate_service::AbstractService as substrate_service::AbstractService>::CallExecutor, <impl substrate_service::AbstractService as substrate_service::AbstractService>::Block, <impl substrate_service::AbstractService as substrate_service::AbstractService>::RuntimeApi> : sr_primitives::traits::ProvideRuntimeApi`
```

This makes it impossible to interact with the service's `runtime_api` and it looks like it should be implemented for a client https://github.com/paritytech/substrate/blob/master/core/client/src/client.rs#L1393

**Comment by bkchr** [comment]
What do you want to achieve? Why do you need the runtime api at this point?

If we add some trait bounds, `runtime_api` works, but you would not be able to call any method in the runtime as there is some more Rust trait magic required.

**Comment by alleycat-at-git** [comment]
> What do you want to achieve? Why do you need the runtime api at this point?
> 
> If we add some trait bounds, `runtime_api` works, but you would not be able to call any method in the runtime as there is some more Rust trait magic required.

So basically I want to instantiate a Substrate service and be able to query Runtime data like Balances or other modules using that instance. 

The concrete use case for me is I need to make a notification stream of imported blocks (I do that with `import_notification_stream`) and add to each block some data from the blockchain storage. I did that by creating `decl_runtime_api` and `impl_runtime_api` which worked fine but now the problem is I cannot access this API from the Substrate service instance at all.

**Comment by alleycat-at-git** [comment]
@bkchr So I tried to do the same thing using the `new_full!` macro and it worked fine. To me it looks somewhat inconsistent that `runtime_api` is available with `new_full!` but is not available for `new_full` function.

**Comment by bkchr** [comment]
Ty @alleycat-at-git 

Fixed by: https://github.com/paritytech/substrate/pull/3709
