### ISSUE TITLE
Additional custom metadata for module

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#3686]
It will be useful to have `decl_module` takes an additional `ModuleMetadata` `Encode`able and have it stored and passed via metadata rpc call.

This can be useful for various purposes, such as a workaround of #3187 (manually encode the child storage field info, and then JS SDK can decode it and extract the child storage details).

This is like a more generalised version of the `constants` field in the metadata, that it is not used in runtime, but significantly improves SDK developer's life quality.

**Comment by shawntabrizi** [comment]
Should ideally be supported with some expansion of: https://github.com/paritytech/substrate/issues/5678

**Comment by apopiak** [comment]
related to #917

**Comment by thiolliere** [comment]
with pallet macro there is extra constants: https://substrate.dev/rustdocs/v3.0.0/frame_support/attr.pallet.html#extra-constants-palletextra_constants-optional

it can add any values to the metadata under any names, would that be enough ?
what more would be needed.

**Comment by xlc** [comment]
Never aware of this feature but I think it solves my issue

**Comment by shawntabrizi** [comment]
I don't get it. How will this be used?

**Comment by xlc** [comment]
with `extra_constants`, I should be able to define arbitrary constants that is accessible via metadata, so it can expose things like non-runtime defined parameters, child storage key prefix or any other metadata that could be used by SDK. If I want, I should be able to have it return a JSON string represents custom types and partially address #917.
