### ISSUE TITLE
Basic, persistent reputation system

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#370]
- assign a number to every node address
- bootnodes get 100
- nodes that are discovered otherwise get 10
- keep them all in order
- connect to the nodes at the top of the list, but ensure there's a jittered exponential reconnect time to avoid hammering nodes at the top that go offline for a while and let nodes at the bottom get tried
- if a node doesn't work when trying to connect, reduce the number by 1. if it does successfully connect then for every 10 minutes of successful connection, increase by 1.
- nodes don't go above 100. 
- once a node gets to 0, remove from the local table

**Comment by tomaka** [comment]
If a node gets to 0 then gets rediscovered by Kademlia later, should it be added again with a score of 10?

Since we don't dial nodes that are down the list often, I assume that it would take quite a lot of time to go down to 0 anyway, so I'd say yes. Otherwise we would have to store on disk every single address that has ever been reported by Kademlia.

**Comment by chevdor** [comment]
I think nodes with a better block should also get a boost.
That would help prevent a node connecting to many 'still syncing' node and stall until it find a node that can provide newer blocks.

**Comment by tomaka** [comment]
I've made a few adjustments after prototyping with this.

An addr with a score of 0 is not removed from the list but is considered invalid and is never tried. Addresses with a score of 0 are also cached on the disk.

Addresses which we are not connected to have a time-to-live, after which they are removed from the network topology.
Therefore even addresses with a score of 0 can be rediscovered once they expire.

If we successfully connect to an address and obtain the corresponding peer ID, the address' score is set to 0 for any node other than the valid peer ID. This means that if multiple peers get reported the same address, once we connect to one of them the others get slashed. This quickly removes any entry that contains `127.0.0.1`.
