### ISSUE TITLE
Error compiling libp2p-core when running  curl https://getsubstrate.io -sSf | bash

### ISSUE THREAD

**Issue by tabbre-blockchain** [paritytech/substrate#3725]
On Ubuntu 19.04 
running 

~$ curl https://getsubstrate.io -sSf | bash
Ubuntu/Debian Linux detected.
.....
.....
Compiling libp2p-core v0.12.0
error[E0433]: failed to resolve: could not find `types` in `protobuf`
   --> /home/charles/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.12.0/src/keys_proto.rs:188:98
[getsubstrate io  compile error.log](https://github.com/paritytech/substrate/files/3671749/getsubstrate.io.compile.error.log)
.....

full log of console attached

**Comment by bkchr** [comment]
Already fixed in master.
