### ISSUE TITLE
Node Template Fails to Change Epoch

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#3727]
When running a node template on Substrate, it fails to produce blocks after 100 due to "Expected Epoch Change":

```
2019-09-30 19:35:42 Idle (0 peers), best: #100 (0xb075…c064), finalized #100 (0xb075…c064), ⬇ 0 ⬆ 0
2019-09-30 19:35:47 Idle (0 peers), best: #100 (0xb075…c064), finalized #100 (0xb075…c064), ⬇ 0 ⬆ 0
2019-09-30 19:35:48 Starting consensus session on top of parent 0xb075eeb491f2531a81323bc2e8b9c4aa1da8f6e1d8a66bec66bd1721bbe8c064
2019-09-30 19:35:48 Prepared block for proposing at 101 [hash: 0x5e2dae479d06712d50c84baf71895bf2558ef07a189f44f9965f6ff01b2a959d; parent_hash: 0xb075…c064; extrinsics: [0xd801…18b8]]
2019-09-30 19:35:48 Pre-sealed block for proposal at 101. Hash now 0x02018d7198c46b28b3370f07ee6fbc14dfdd57f6fe7bf21aa2827a8b5326285e, previously 0x5e2dae479d06712d50c84baf71895bf2558ef07a189f44f9965f6ff01b2a959d.
2019-09-30 19:35:48 Error with block built on 0xb075eeb491f2531a81323bc2e8b9c4aa1da8f6e1d8a66bec66bd1721bbe8c064: ClientImport("Expected epoch change to happen at 0x02018d7198c46b28b3370f07ee6fbc14dfdd57f6fe7bf21aa2827a8b5326285e, s261644158")
```

Tested on Substrate commit `e0d486d617cbe24f0c91cd6aa0dfcfb6c4e4dcc2` and `7d7e74fb77b6bee2ce9d6ebafcae09caff2d0e50`

The regular Substrate node works.

@rphmeier

**Comment by shawntabrizi** [comment]
Works in `3ba0f2a2dbd37c31851a0ff1c1c0c47aa940de90` before BABE changes

**Comment by rphmeier** [comment]
Somehow node and Polkadot both work with the babe commits, while `node-template` fails to bootstrap.

**Comment by rphmeier** [comment]
Oh, it's because `node-template` isn't using `session` - the epoch change logic in `srml-babe` isn't triggered because of that.

**Comment by kianenigma** [comment]
seems like it is non-sensical at the first place for node-template to exist without session module and just needs s fix for that?

**Comment by kianenigma** [comment]
But this does bring up a question: 
If Babe is not functional properly without session, it should be _strictly_ dependent on it, no? it is quite strange that I see babe's cargo file requires session, while a runtime is allowing babe to be included without session. Ideally, I imagine each module statically naming a few module ID's as _strong dependency_ or something, and perhaps `construct_runtime!` checking it?

**Comment by bkchr** [comment]
You don't want to have a strong link to session. Just yesterday you recommended a pr that removed such a strong dependency and now you want to add one for yourself :D 
I think the only solution is to improve the documentation in the srml-babe module, telling you that you need something that handles sessions. Besides that, we could also improve the error message and giving a hint that probably no session change occurred.

**Comment by shawntabrizi** [comment]
@bkchr is there a way to have the trait be such that anything can implement "sessions" but it _has_ to be implemented?

I see that as also a solution here if rust/magic allows it?

**Comment by bkchr** [comment]
Normally you could just declare the other modules trait as super trait:
```
trait Trait: other_module::Trait {}
```

But that enforces you to directly use the other module in your runtime.


We could add some dummy associated type to the Babe `Trait` that requires that a trait `Session` is implemented. Currently this `Session` trait could only be some sort of marker trait, so just an empty trait. We would implement this marker trait for our sessions module and the user would be forced to provide something that implements this session trait. 
We could add some dummy associated type, that requires that a dummy `Session` trait is implemented and impl

**Comment by kianenigma** [comment]
> You don't want to have a strong link to session. Just yesterday you recommended a pr that removed such a strong dependency and now you want to add one for yourself :D

Shawn also pointed out the same. But frankly, I see this differently. If Babe is dysfunctional without session, or let's say _something that can provide some session handler implementation etc.,_ then I see a strong dependency more suitable. It is better to ship a less generic srml that _works_, rather than a dynamic fancy generic one that does not :P 

But as you mentioned, that would be supertrait, which is not nice. That bounds _srml-babe_ to always use _srml-session_, not some custom session implemented by anyone else. Ideally, would be great if we could: 

> We could add some dummy associated type, that requires that a dummy Session trait is implemented and impl

👍

**Comment by rphmeier** [comment]
> We could add some dummy associated type, that requires that a dummy Session trait is implemented and impl

I'll do something like this, but cleaner

**Comment by zikunfan** [comment]
Hey buddy, I am a green bird to substrate. same problem when I import `babe` into runtime.
I aware you guys already decouple seesion from babe. My question is how to import session into runtime?😂

**Comment by shawntabrizi** [comment]
@zikunfan we have a tutorial here: https://substrate.dev/docs/en/next/tutorials/adding-a-module-to-your-runtime

But depending on what you are trying to do, it may be easier to start with the Substrate node which is already set up with a PoS consensus system with Babe + Session + everything else:

https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs
