### ISSUE TITLE
Nodes connect to themselves

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#373]
It appears that node connect to themselves when they perform Kademlia queries.
Fortunately they don't connect to themselves when it comes to the actual dot protocol.

**Comment by gavofyork** [comment]
Is this still an issue?

**Comment by tomaka** [comment]
Yes: https://github.com/libp2p/rust-libp2p/issues/341

**Comment by tomaka** [comment]
Fixed by https://github.com/libp2p/rust-libp2p/pull/1097.
The fix is not in Substrate yet, though.
Once a new version of libp2p is published, we can update Substrate to use it, and close this.
