### ISSUE TITLE
Build-time panic if Cargo.toml becomes invalid during build

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/substrate#3747]
This can happen if it was manually edited, for example.

**Comment by bkchr** [comment]
Could you please explain? I don't understand what you want to tell us with this issue.

**Comment by DemiMarie-parity** [comment]
If, while a build is in progress, I edit one of the `Cargo.toml` files (which was initially valid) such that it contains a syntax error, the build scripts panic.  I forget which file triggers the bug.

**Comment by bkchr** [comment]
Yeah, if a `Cargo.toml` file is invalid I don't see why we should not panic.

We can not build when something is invalid, given that, I close this issue.
