### ISSUE TITLE
Issue installing subkey with substrate

### ISSUE THREAD

**Issue by jpbrusso** [paritytech/substrate#3770]
Hi,
 I'm on Ubuntu 16 running as root. I run the following commands to install subkey

$ curl https://getsubstrate.io -sSf | bash -s -- --fast
$ cargo install --force --git https://github.com/paritytech/substrate subkey
$ source ~/.cargo/env

everything runs okay until I hit the following error, can anyone help?

error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-0.10.1/src/lib.rs:201:1
    |
201 | extern crate alloc;
    | ^^^^^^^^^^^^^^^^^^^

   Compiling pkg-config v0.3.16
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `zeroize`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `subkey v2.0.0 (https://github.com/paritytech/substrate#aba25769)`, intermediate artifacts can be found at `/tmp/cargo-installzfKb7s`

Caused by:
  build failed

**Comment by bkchr** [comment]
Which version of rust are you using?

**Comment by jpbrusso** [comment]
rustc 1.35.0. I ran the commands as is to install per the installation guidance. Do I need to update my repositories or something else?

**Comment by bkchr** [comment]
Your rustc is too old, please use latest stable.

**Comment by jpbrusso** [comment]
ok I updated rust and went through the installation, now when I run:
$ cargo build -p subkey
from the root directory

I get:
error: could not find `Cargo.toml` in `/root/.cargo` or any parent directory

**Comment by thiolliere** [comment]
by root directory you mean the root directory of substrate repo isn't it ?

is it possible that you run this command as root user and thus rust can't find .cargo because you installed rust as your personal user ?

**Comment by thiolliere** [comment]
if you want to build the project you have to run the project from within the substrate workspace. so you have to go into the repo and run from it.

Otherwise if you want to install directly from git you have to use `cargo install --force --git=https://github.com/paritytech/substrate subkey`

**Comment by thiolliere** [comment]
and then `source ~/.cargo/env` it seems

**Comment by thiolliere** [comment]
I think you should be fine feel free to open it if one error come again
