### ISSUE TITLE
no timestamp parameter in the chainspec.json

### ISSUE THREAD

**Issue by edanilov** [paritytech/substrate#3789]
> Now, edit ~/chainspec.json in your editor. There are a lot of individual fields for each module, and one very large one which contains the WebAssembly code blob for this chain. The easiest field to edit is the block period. Change it to 10 (seconds):
> 
>      "timestamp": {
>         "minimumPeriod": 10
>       },

no timestamp parameter in the chainspec.json

**Comment by tomaka** [comment]
For context, the quote is in the README.

**Comment by tomusdrw** [comment]
I think this stuff has been moved to `parameter_types` in https://github.com/paritytech/substrate/pull/3093
