### ISSUE TITLE
Improve test suite for runtime modules. should be tested with non null ExistentialDeposit

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#3798]
I found an issue in treasury due to the test suite having ExistentialDeposit to 0 https://github.com/paritytech/substrate/pull/3797

if you grep to other modules there is:
```
./srml/utility/src/lib.rs:111:		pub const ExistentialDeposit: u64 = 0;
./srml/democracy/src/lib.rs:1027:		pub const ExistentialDeposit: u64 = 0;
./srml/elections/src/mock.rs:59:	pub const ExistentialDeposit: u64 = 0;
./srml/scored-pool/src/mock.rs:52:	pub const ExistentialDeposit: u64 = 0;
./srml/example/src/lib.rs:679:		pub const ExistentialDeposit: u64 = 0;
./srml/executive/src/lib.rs:357:		pub const ExistentialDeposit: u64 = 0;
./srml/council/src/lib.rs:127:		pub const ExistentialDeposit: u64 = 0;
```

I think test suite should take into account existential deposit in general this is more relevant and probably catch more bug.

Actually I think all parameter types in
```rust
	parameter_types! {
		pub const ExistentialDeposit: u64 = 0;
		pub const TransferFee: u64 = 0;
		pub const CreationFee: u64 = 0;
		pub const TransactionBaseFee: u64 = 0;
		pub const TransactionByteFee: u64 = 0;
	}
```

should be set to a value different from 0 in general (except in some precise test obviously)

**Comment by kianenigma** [comment]
related: https://github.com/paritytech/substrate/pull/1966

**Comment by kianenigma** [comment]
As I also stated here [here](https://github.com/paritytech/substrate/pull/3797#issuecomment-541635501), it seems like the general situation is that the current balances module is really based on having a positive ed. There are some notes here:

- the semantics of ed is defined in a way that ed = 0 doesn't make much sense. One simple approach is to ban ed = 0 and just call it a day.
- allow ed to be shut-down aka. ed = 0 but it looks like some modules (namely Indices and treasury) need further investigation regarding how they interact with this feature.
