### ISSUE TITLE
contracts: implement `ext_runtime_get_storage`

### ISSUE THREAD

**Issue by ascjones** [paritytech/substrate#3803]
In order to allow smart contracts to query runtime storage, a new `ext_` function is required:
```
fn ext_runtime_get_storage(key_ptr: u32, key_len: u32) -> u32
```
I've implemented a quick prototype: https://github.com/paritytech/substrate/compare/aj-contracts-get-storage.

However this is [hard coded](https://github.com/paritytech/substrate/compare/aj-contracts-get-storage#diff-96eada255f897b2fc434cb93b380661fR706) to hash the key `twox_128(key)`

Assuming we don't expect the contract itself to perform the key hashing, the remaining problem to solve is the API for correct hashing of keys for different storage types:

- Value `twox_128(key)`
- Map `blake2_256(prefix + key)`
- Map2 `twox_128(prefix + key)`
- LinkedMap `blake2_256(prefix + key)`
- LinkedMap2 `twox_128(prefix + key)`
- DoubleMap `blake2_256(prefix + key) + blake2_256(key2)`
- DoubleMap2 `twox_128(prefix + key) + twox_128(key2)`

Rel: https://github.com/paritytech/ink/pull/204

**Comment by xlc** [comment]
Related previous discussion: #2214

**Comment by xlc** [comment]
Access the storage directly will make it very hard / impossible to upgrade runtime module storage format because it means all the contracts have to upgrade as well.
