### ISSUE TITLE
Where's the `start` function in sr-sandbox ?

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/substrate#3815]
confused about https://github.com/paritytech/substrate/blob/master/core/sr-sandbox/src/lib.rs#L177
```
If execution of `start` function generated a trap, then `Err(Error::Execution)` be returned.
```

I see the sandbox's Instance code and tests. I dont know where the `start` function is,
Like https://github.com/paritytech/substrate/blob/master/core/sr-sandbox/with_std.rs#L313

Also, what's the state param mean in Instance::new()?

And any different in sr-sandbox and executor/sandbox?

**Comment by bkchr** [comment]
CC @pepyakin

**Comment by pepyakin** [comment]
start function is a term that is coming from wasm spec. It is a function that may be defined by a wasm module to be executed at instantiation time. Note that rustc by default doesn’t emit it.

state parameter is needed for passing around additional parameter. Use case is to pass around some user defined context in the host functions. For instance, in sr-sandbox uses it to pass around the context of type associated with the instance and it has a type of T

**Comment by yjhmelody** [comment]
@pepyakin 
So that  a wasm code which not include `start`, won't be run if don't use `invoke` function ?

**Comment by NikVolf** [comment]
@yjhmelody if you have no start function, this start step is just no-op, so no need to disable anything

**Comment by pepyakin** [comment]
what @NikVolf said. Ignoring the start function if it is present in the module would make such execution environment non-spec compilant since executing the `start` function as the last step of instantiation is mandated by the spec.
