### ISSUE TITLE
parity-common: outdated revision

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#3824]
**Problem** 

This issue connected to https://github.com/paritytech/polkadot/issues/451, duplicated sources raised by outdated version of `parity-common` that used in https://github.com/paritytech/substrate/blob/master/core/client/db/Cargo.toml#L11.

@bkchr could you explain please, is upgrade possible now?

**Comment by bkchr** [comment]
Hey, yeah, I put this on my list.

**Comment by bkchr** [comment]
Fixed in master.
