### ISSUE TITLE
Invalid transaction send over RPC results “Stream terminated” error

### ISSUE THREAD

**Issue by geigerzaehler** [paritytech/substrate#3849]
I’m using [`substrate_rpc_api::author::AuthorClient::watch_extrinsic`](https://crates.parity.io/substrate_rpc_api/author/struct.AuthorClient.html#method.watch_extrinsic) to submit and extrinsic to a node. If I send an invalid intrinsic (say the account does not exist) the future returned by `watch_extrinsic` errors with `RpcError::Other("Stream terminated")` instead of providing me with a validation error.

One way to provide information about validation errors would be for the subscription stream returned by `watch_extrinsic` to emit [`Status::Invalid()`](https://crates.parity.io/substrate_transaction_graph/watcher/enum.Status.html#variant.Invalid). However, this currently does not allow us to encode information about the failure that can be decoded by the client.

Another option would be to have the future to error with `RpcError`. In fact, over the wire the node sends a JSON RPC error response to the `watch_extrinsic` request. The response includes the message "Invalid transaction" and the data "Payment". A bug in the `jsonrpc` library prevents this error from being properly propagated.

Related:
* #2485 Encoding more information about invalid transactions

**Comment by tomusdrw** [comment]
I think this was recently fixed in #3817 Can you check against latest master to see if it's still the case?

**Comment by geigerzaehler** [comment]
@tomusdrw I using the latest master which includes #3871. Before, I never received a response at all and the `watch_extrinsic` call would stall. I believe the issue is that the `subscriber.reject(err.into())` call you added is improperly handled by `jsonrpc` and thus results in “Stream terminated”.

If we go the route with encoding this in the `Status` we would replace `subscriber.reject(...)` with `subscriber.send(Status::Invalid())`. (I don’t know the subscriber API so `send` is just a placeholder)

**Comment by tomusdrw** [comment]
@geigerzaehler we can't really send a notification, cause the subscription is not created at all in that case (it doesn't really make sense, cause the transaction is not in the pool). I suppose it might be an error in the client part of the `jsonrpc` indeed, most likely we don't handle subscription rejections correctly.

**Comment by tomusdrw** [comment]
Do you see this log line being printed in your client code (perhaps you need to enable `env_logger` in your app):
https://github.com/paritytech/jsonrpc/blob/d1993a80176afdcbae6949bbf73ebbaf5625e644/core-client/transports/src/transports/duplex.rs#L217-L222

**Comment by tomusdrw** [comment]
I believe it's more a `jsonrpc` client issue than substrate issue, let's move the discussion there:
https://github.com/paritytech/jsonrpc/issues/508

**Comment by geigerzaehler** [comment]
> Do you see this log line being printed in your client code (perhaps you need to enable `env_logger` in your app):
> https://github.com/paritytech/jsonrpc/blob/d1993a80176afdcbae6949bbf73ebbaf5625e644/core-client/transports/src/transports/duplex.rs#L217-L222

Yes, that is what I can see in the logs.

> I believe it's more a `jsonrpc` client issue than substrate issue, let's move the discussion there:
> [paritytech/jsonrpc#508](https://github.com/paritytech/jsonrpc/issues/508)

If we fix this on the `jsonrpc` side then `watch_extrinsic` will result in an `RpcError`. While this is better it does not allow us to properly encode information about the validation error. We would need to extract this information from the `message` and `data` fields of `RpcError`. Just something to consider.

**Comment by tomusdrw** [comment]
Well, since we are calling JSON-RPC endpoint the rpc-compliant error format is the best we can get. We could however encode more structured info in `data` field, but it seems we actually encode the entire `InvalidTransaction` enum there:
https://github.com/paritytech/substrate/blob/dbdebca9b35670cbf4efcfc210a318abd2f7879e/core/rpc/api/src/author/error.rs#L110

So I don't know what more we could give. Basically you need to match on the error code and then parse `data: Option<serde::Value>` to the enum type.
