### ISSUE TITLE
Add 'println!' to sr-primitives

### ISSUE THREAD

**Issue by geigerzaehler** [paritytech/substrate#3865]
To allow for a debugging experience that is closer to `std` Rust it would be great if `println!` were provided. This can easily be implemented by combining `sr_primitives::print` and `sr_std::fmt::format`.

**Comment by tomusdrw** [comment]
See #3821

**Comment by geigerzaehler** [comment]
> See #3821

:clap:

**Comment by bkchr** [comment]
So, I think this can be closed :)
