### ISSUE TITLE
Pass arguments to off-chain worker

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#3912]
How to pass arguments to off-chain worker? AFAIK it is possible to configure session key for offchain worker to consume. But can this session key be arbitrary string?

For example, I would like to pass API key to off-chain worker so it can fetch data from exchanges. The offchain code can check if it has API key configured to do actual work.

In the end, I would like to build an oracle module that allow people to stake to become an operator. Then they can configure a session key and one or more external services API keys to start submit data using offchain worker. This makes a permisionless decentralised oracle network possible.

**Comment by thiolliere** [comment]
it seems arguments to off-chain worker can benefit from the architecture of the chain spec. with availability to changes keys at specific block numbers and extend it.

**Comment by thiolliere** [comment]
hmm did I actually understood correctly ?

pass argument to off-chain worker from where ? from the runtime ? or from the cli ?

if it is from the runtime this can be done indeed

**Comment by thiolliere** [comment]
> In the end, I would like to build an oracle module that allow people to stake to become an operator. Then they can configure a session key and one or more external services API keys to start submit data using offchain worker. This makes a permisionless decentralised oracle network possible.

I don't understand how this make use of arguments ? this key is just in the trie ?

**Comment by tomusdrw** [comment]
> For example, I would like to pass API key to off-chain worker so it can fetch data from exchanges. The offchain code can check if it has API key configured to do actual work.

This should be just inserted to the local offchain worker database under some known key. You can set it up during service or CLI initialisation.

**Comment by xlc** [comment]
Yes like @tomusdrw said. Pass arguments from runtime is easy as offchain worker can just read storage. I would like to pass arguments from CLI or API. Preferably from API so it can be rotated without reboot the node.

**Comment by xlc** [comment]
Fixed by #4694
