### ISSUE TITLE
Transaction Weight mechanism not considering proposals

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#3921]
Disaptchable calls can be dispatched indirectly (and many of them are designed to be dispatched indirectly, such as `system::set_code`). The transaction weight for those indirects calls are not considered at all right now.

e.g. `collective::vote` is `FixedOperational(200_000)` and may dispatch an arbitrary proposal, such as `membership::add_member` which is `FixedNormal(50_000)`. The final weight for such transaction should be 250_000 instead of ignoring the weight of `membership::add_member`.

Related: #3730 can make dynamically increase weight possible when the proposal is dispatched.

**Comment by kianenigma** [comment]
related to https://github.com/paritytech/substrate/issues/3730

also @sorpaas I think you will need the same thing for EVM, right?

**Comment by sorpaas** [comment]
Yeah I think it's related to EVM module as well.

**Comment by xlc** [comment]
I think this is fixed already.
