### ISSUE TITLE
Transaction pool might panic if tags are pruned but no hashes provided on prune

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#3923]
Maybe it is unavoidable, but it is still might be an attack vector for some usage scenarios

```
Every time transaction is imported its hash is placed in `ready` map and tags in `provided_tags`;
Every time transaction is removed from the queue we remove the hash from `ready` map and from `provided_tags`;
Hence every hash retrieved from `provided_tags` is always present in `ready`;
qed
```

**Comment by tomusdrw** [comment]
Can you elaborate on the case that you have in mind? This proof is internal to the "ready" part of the pool, the invariant is that we never put a hash to `provided_tags` (tags to hash mapping) without putting the same hash to `ready` (hash to transaction mapping). I don't see how it could ever break.

We really don't need to provided `hashes` of transactions when pruning, this is only done to temporarily ban the hashes and prevent them from being re-imported to the pool in some scenarios. We get the hashes from the aforementioned mapping given `provided_tags`.

**Comment by NikVolf** [comment]
Well I triggered this error during benchmarks using just public api, I'll post a failing test

**Comment by NikVolf** [comment]
See https://github.com/paritytech/substrate/compare/nv-txpool-panic-2?expand=1

`cargo test -p substrate-transaction-graph`
 
if hash is also passed in prune_tags, then no panic
