### ISSUE TITLE
libp2p/polkadot protocol handshake should include `--name` param

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#398]
Nodes have a public name provided by `--name` parameter on the CLI. This should be (optionally) provided to  any remote nodes during handshake to facilitate debugging in network logs.

**Comment by tomaka** [comment]
Libp2p has no way to do this right now, but the good thing with it is that we can invent our own protocol.

**Comment by gavofyork** [comment]
over-dependent on the upstream protocol so will close for now.
