### ISSUE TITLE
`StorageLinkedMap` trait does not provide `hashed_key_for` equivalent

### ISSUE THREAD

**Issue by Sushisource** [paritytech/substrate#3987]
I've been migrating from 1.0 to 2.0 and one of the pain points I've had is there used to be a `key_for` method available on *all* map types. Somehow now they don't all share some common trait (which seems like a slip backward in usability of the api).

I would expect the linked map and double map to both provide a `hashed_key_for` method - ideally through some common trait that all maps share.

But, as it stands, although https://substrate.dev/rustdocs/master/srml_support/storage/generator/trait.StorageLinkedMap.html#method.storage_linked_map_final_key exists, it is inaccessible (seemingly due to some macro weirdness generating traits behind `hidden_include` modules).

The functions on https://substrate.dev/rustdocs/master/srml_support/storage/trait.StorageLinkedMap.html *are* accessible, but provide no way for me to even get the storage prefix, and hence I'm forced to manually re-implement `storage_linked_map_final_key` in a way that I can access.

Overall pleased with a lot of the improvements in 2 but this one felt like a bit of a regression

**Comment by bkchr** [comment]
Why do you need these methods?

**Comment by thiolliere** [comment]
I wanted to remove this method for all storage map actually. I would be interesting by your usecase as well.
Also the generator should be accessible at https://crates.parity.io/srml_support/storage/generator/trait.StorageLinkedMap.html

**Comment by Sushisource** [comment]
The use-case here is constructing the right hash I need to pass to the `getStorage` JSON RPC call. I found I wasn't able to call anything on the generator trait, even after trying to bring it into scope a bunch of different ways.

If there's a much simpler way to get the data I want from RPC in 2.0 now, I'm all ears :smile:

**Comment by bkchr** [comment]
```
diff --git a/srml/staking/src/lib.rs b/srml/staking/src/lib.rs
index 23f0d7715..960c5f2d8 100644
--- a/srml/staking/src/lib.rs
+++ b/srml/staking/src/lib.rs
@@ -1037,6 +1037,8 @@ impl<T: Trait> Module<T> {
                controller: &T::AccountId,
                ledger: &StakingLedger<T::AccountId, BalanceOf<T>>
        ) {
+               use support::storage::generator::StorageLinkedMap;
+               Validators::<T>::storage_linked_map_final_key(&T::AccountId::default());
                T::Currency::set_lock(
                        STAKING_ID,
                        &ledger.stash,
```

I don't see the problem?

**Comment by Sushisource** [comment]
@bkchr Weird. I wasn't able to get that to compile before, kept complaining about some generated hidden namespaces inside the macro, but now it's working fine. I might've had two things going on at once conflicting with each other.

I think it'd still be nice if there was a common trait for getting the storage keys, unless there is/will be an improved mechanism for looking up stored values via rpc.

Thanks!

**Comment by bkchr** [comment]
There can not be a common trait, as a `StorageValue` does not hashes the key for example.

Your problem was that you did not import the corresponding trait and so, rustc recommended to import the trait from our hidden imports.

**Comment by Sushisource** [comment]
@bkchr 
There easily could still be a common trait. You could have a `key_for() -> StorageKey`. The key would either be hashed or not, as appropriate for the type. If you need to know if it was, it could return an enum with `Hashed` and `Unhashed` variants.

So, definitely possible, and the kind of thing that I think improves usability for people getting started with the platform.

**Comment by bkchr** [comment]
1. This is all internal api that can change in any moment, just how the key is build is fixed.
2. For a `StorageValue` a single `key_for()` works, but for a map this doesn't work. `key_for` for a map requires the key as input to generate you the final storage key. A double map even requires 2 keys to generate the final key. You see, there is no real common interface.

People starting with Substrate should use the provided tools, if you come to the point where you want to reimplement some internals, fine, but then you need to use either unstable internal apis or generate the keys on your own.

Given your description, I assume that you build a rpc client? Why do you not use the metadata? The metadata already contains the required data for you. If you not use the metadata, your rpc client will only work for one specific runtime.

**Comment by bkchr** [comment]
Maybe if you describe your use case better and what you want to do, we can help you better.

**Comment by Sushisource** [comment]
Sorry for the late reply.

Sure, I see how the interface isn't precisely common across all storage types, but there could at least be one for maps, and someone added exactly what I was getting at in any case, which is all I really wanted: https://github.com/paritytech/substrate/pull/4120

Yes, I am building an rpc client (though it only needs to be specific to my runtime). I'd like to use the metadata, unfortunately I can't find much in the way of documentation on how to actually do that. I'm not trying to re-implement internals, in fact I would love to avoid that - that's exactly why I opened this item. I can find this: https://substrate.dev/docs/en/next/runtime/runtime-metadata

Which helps me get the metadata, but it doesn't help much in terms of telling me how to actually use it. It doesn't particularly help with this situation, for example. Metadata for a linked map looks something like:
```
 { 
                  "name":"PendingMints",
                  "modifier":1,
                  "type":{ 
                     "Map":{ 
                        "hasher":"Blake2_256",
                        "key":"FiatReqNonce",
                        "value":"PendingMint",
                        "linked":true
                     }
                  },
                  "fallback":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                  "documentation":[ 

                  ]
               }
```

This data helps me with knowing which hasher to use, but I still would need to know how exactly to construct the storage hashes to get items in the map over RPC, and that process is difficult to figure out from documentation. I've just had to read source like https://substrate.dev/rustdocs/master/src/srml_support/storage/generator/linked_map.rs.html#43-76

I think the bigger story here is that I'm asking these questions that might seem wrong because it's hard to figure out what the right path is purely from docs.

Thanks!

**Comment by bkchr** [comment]
You don't need these interfaces, as they are only usable from within the runtime. When you have the metadata, you can do the following. [Here](https://github.com/paritytech/substrate/blob/master/paint/support/procedural/src/lib.rs#L84-L87) is documented on how to calculate the keys for the storage. So, for example to access the head key:
`blake2_256("head of " ++ "NAME_OF_YOUR_MODULE" ++ "  " ++ "MyMap")`

To access a value:
`blake2_256("NAME_OF_YOUR_MODULE" ++ " " ++ "MyMap" ++ KeyYouWantToAccess)`

`NAME_OF_YOUR_MODULE` is also available in the metadata.
