### ISSUE TITLE
Make `runtime_io::chain_id` configurable

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#3990]
I think it currently returns hardcoded `42`. It should be configurable in chain spec.

https://github.com/paritytech/substrate/blob/7dd7067991655310ed7d115e1f541b5709fc4596/core/state-machine/src/basic.rs#L171

But there is also another `id` in chain spec, which is a string.

https://github.com/paritytech/substrate/blob/7dd7067991655310ed7d115e1f541b5709fc4596/core/chain-spec/src/chain_spec.rs#L111

**Comment by ayushmishra2005** [comment]
@xlc I checked the latest codebase. I couldn't find `core` directory. Can you please guide me? I want to pick this task.

**Comment by xlc** [comment]
It is now here

https://github.com/paritytech/substrate/blob/184527825c0f9c2037df99406fec029d3cfbba12/primitives/state-machine/src/basic.rs#L264

**Comment by ayushmishra2005** [comment]
@xlc I debugged a bit. I found that this file is related to `Types and traits related to chain specifications`

https://github.com/paritytech/substrate/blob/c60f00840034017d4b7e6d20bd4fcf9a3f5b529a/primitives/chain-spec/src/lib.rs#L18


Should I defined `chain_id` as Constant here ?
https://github.com/paritytech/substrate/blob/c60f00840034017d4b7e6d20bd4fcf9a3f5b529a/primitives/core/src/crypto.rs#L56

**Comment by xlc** [comment]
Make it a constant is definitely not the intent of this issue because that won't make it configurable by any means.

However I don't actually know how should we make it configurable and if even we need this field or not.

If you just want to contribute something simple, I highly recommend to pick something else. We need someone to actually define how should we improve this first before any coding.

**Comment by thiolliere** [comment]
as a note BasicExternalities is only used:

to build genesis storage in https://github.com/paritytech/substrate/blob/c60f00840034017d4b7e6d20bd4fcf9a3f5b529a/frame/support/procedural/src/storage/genesis_config/mod.rs#L157

and to get runtime version:
https://github.com/paritytech/substrate/blob/c60f00840034017d4b7e6d20bd4fcf9a3f5b529a/primitives/io/src/lib.rs#L397

but indeed it should either be unavailable or return the correct value I think

**Comment by athei** [comment]
Closed by #7810. One should use the following as chain id:
https://github.com/paritytech/substrate/blob/0fc832988bef7ab27f6cf2f3040fcb2d3c9b6568/frame/system/src/lib.rs#L261-L266
