### ISSUE TITLE
Build failed when adds libsodium-sys dependency in runtime

### ISSUE THREAD

**Issue by Tore19** [paritytech/substrate#4009]
1, Pull the latest mater of substrate

2, Add libsodium-sys = "0.2.4" to the [dependencies] section in the Cargo.toml of runtime

3, cargo build --release

It shows error as follows.

error: failed to run custom build command for `libsodium-sys v0.2.5`

Caused by:
  process didn't exit successfully: `/Users/zhangtong/work/project/rust/substrate/target/release/wbuild/target/release/build/libsodium-sys-76f237e160de93a8/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=SODIUM_LIB_DIR
cargo:rerun-if-env-changed=SODIUM_SHARED
cargo:rerun-if-env-changed=SODIUM_USE_PKG_CONFIG
cargo:rerun-if-env-changed=SODIUM_DISABLE_PIE
OPT_LEVEL = Some("3")
TARGET = Some("wasm32-unknown-unknown")
HOST = Some("x86_64-apple-darwin")
CC_wasm32-unknown-unknown = None
CC_wasm32_unknown_unknown = None
TARGET_CC = None
CC = None
CFLAGS_wasm32-unknown-unknown = None
CFLAGS_wasm32_unknown_unknown = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")

--- stderr
thread 'main' panicked at '
"/Users/zhangtong/work/project/rust/substrate/target/release/wbuild/target/wasm32-unknown-unknown/release/build/libsodium-sys-b7537dd6750cfc83/out/source/libsodium-1.0.18/configure" "--prefix=/Users/zhangtong/work/project/rust/substrate/target/release/wbuild/target/wasm32-unknown-unknown/release/build/libsodium-sys-b7537dd6750cfc83/out/installed" "--host=wasm32-unknown-unknown" "--enable-shared=no"
CFLAGS= -O2
CC=clang
checking build system type... x86_64-apple-darwin17.7.0
checking host system type...
Invalid configuration `wasm32-unknown-unknown': system `unknown' not recognized
configure: error: /bin/sh build-aux/config.sub wasm32-unknown-unknown failed

***********************************************************
Possible missing dependencies.
See https://github.com/sodiumoxide/sodiumoxide#cross-compiling
***********************************************************

', /Users/zhangtong/.cargo/registry/src/github.com-1ecc6299db9ec823/libsodium-sys-0.2.5/build.rs:270:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by bkchr** [comment]
Why do you need the library in the runtime?

Nevertheless, the library does not compiles for wasm: https://github.com/sodiumoxide/sodiumoxide/issues/347

(And this is not the issue tracker for other crates)

**Comment by Tore19** [comment]
@bkchr  We implement a key pair algorithm and signature algorithm using libsodium-sys. And in our module, we want to verify the user's signature in our own way. So we use the library. Maybe there's something wrong with our implementation logic? Any suggestions?

**Comment by bkchr** [comment]
No there is nothing wrong on your side, `libsodium` just do not compiles for wasm. Are you aware that every module needs to be compilable to wasm in Substrate?

**Comment by Tore19** [comment]
@bkchr  I see. I will find another way to implement our functions. Thanks for your answer. You Guys Are Doing a Great Job!

**Comment by bkchr** [comment]
You could look how we implement the hashing functions for wasm (they call into native) and use the same scheme. (This will currently require some internal changes to Substrate, but that will change in the future).

Nevertheless, if you want to develop a parachain for Polkadot, it will be required that your crypto works in wasm.

**Comment by Tore19** [comment]
Got it.
