### ISSUE TITLE
Implement Send and Sync for TestExternalitities

### ISSUE THREAD

**Issue by geigerzaehler** [paritytech/substrate#4013]
It would be helpful if `substrate_state_machine::TestExternalities` implemented `Send` and `Sync` so it can be used in more elaborate tests.

In my particular use case I’m creating a client test double that simulates the node runtime with `TestExternalities`. I would like to use the client across different threads which requires the `Send` for `TestExternalities`.

**Comment by bkchr** [comment]
Hmmm. We could probably make it `Send`, but probably not `Sync`.

Why don't you just add a function that creates the externalities and you call this function from your threads? Then you don't need it to have `Send` implemented.

**Comment by geigerzaehler** [comment]
> Why don't you just add a function that creates the externalities and you call this function from your threads? Then you don't need it to have `Send` implemented.

Unfortunately this does not allow me to share the externalities between threads. In my example I’m running a webserver where I want to provide the test double as a “request context”. The webserver requires the context to implement `Send` because it spawns multiple threads. So I’m limited by the API the server gives me.

One way to work around this would obviously be to call the text externalities only in a single fixed thread and implement an adapter that uses message passing to call the externalities from a different thread. Implementing this adapter is not easy though. It would be a lot easier if TestExternalities implemented `Send`.

**Comment by bkchr** [comment]
Do you modify the externalities somewhere in your server or what are you doing with them?

**Comment by geigerzaehler** [comment]
> Do you modify the externalities somewhere in your server or what are you doing with them?

Yes. This is roughly the setup we have
```rust
pub struct Client {
    test_ext: TestExternalities,
}

impl Client {
    fn transfer(&mut self) {
        self.test_ext.execute_with(|| {
            // runtime code
        })
    }
}

fn main() {
    let test_ext = TestExternalities::new();
    let client = Arc::new(Mutex::new(Client { test_ext }));
    let service = warp::any().map(move || {
        client.clone().lock().unwrap().transfer();
        warp::reply()
    });
    warp::serve(service).run(([127, 0, 0, 1], 8080))
}
```
This fails to compile. The closure passed to `map` may be run in another trait to `client` needs to implement `Send`. But this is only the case if `TestExternalities` implements `Send` too.
