### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/substrate#4018]
when i use the command: 'WASM_BUILD_TYPE=release cargo run -- -- dev ', the error for example:

thread 'rustc' panicked at 'Tried to access field 0 of union with 0 fields', src/librustc_target/abi/mod.rs:742:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (2477e2493 2019-11-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `substrate`.

To learn more, run the command again with --verbose.

**Comment by bkchr** [comment]
Could you please stop to opening the same issue over and over again? As written in the last issue, this is a rustc bug.
