### ISSUE TITLE
Support rust-std in WebAssembly runtime

### ISSUE THREAD

**Issue by sorpaas** [paritytech/substrate#4043]
The target we compile wasm runtime to, `wasm32-unknown-unknown`, actually [has builtin `std` support](https://forge.rust-lang.org/release/platform-support.html). Adding support for `std` would help to solve many of our current user complaints.

Some details of the std support on the wasm target:

* Filesystem is implemented as [shim](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/wasm/fs.rs) that cannot be constructed.
* Single thread is assumed, which is used to implement constructs like [`Mutex`](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/wasm/mutex.rs) and [`RwLock`](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/wasm/rwlock.rs).
* You can find more about the std implementation at [this folder](https://github.com/rust-lang/rust/tree/master/src/libstd/sys/wasm).
* I think the only issue we need to deal with is the allocator. Currently the std library assumes [dlmalloc](https://github.com/alexcrichton/dlmalloc-rs), but it should be possible to switch it to our external allocator.

**Comment by sorpaas** [comment]
After some discussions with @gavofyork I think we'll not be adding `std` support in runtime. Closing the issue.

**Comment by h4x3rotab** [comment]
Why? I think any background here about the cancellation would be helpful for the developers.

**Comment by sorpaas** [comment]
@h4x3rotab I think the general consensus yesterday was that:

* If developers try to do stuff which are not allowed in runtime, `std` opens up some caveats of panics, potential DoS attacks, among others. This is something we don't want to see.
* While it was not the intention, we wrote many code with the assumption that `std` is native, `no_std` is wasm.
* It makes things clear that runtime must be deterministic. It may not be a "perfect model", and I do think there're other models that may work better (for example, post-build check of unexpected imports), but still, this is a model that works.
* It's considered by many that `wasm32-unknown-unknown`'s `std` implementation is just unstable and not for production, while wasm itself is.
