### ISSUE TITLE
Method to get BABE block authorship information

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#4102]
For chains that use BABE, the client should have an endpoint to return

- its VRF output for each slot in an epoch,
- its secondary slot leadership, and
- the epoch's threshold. 

This is so that validator operators can monitor their nodes for any missed slots.

CC @andresilva

**Comment by andresilva** [comment]
Here's the overall idea of what needs to be done:

- Compute start and end slots for the current session (https://github.com/paritytech/substrate/blob/master/frame/babe/src/lib.rs#L363);
- For each slot, try to claim it as a primary and as a secondary using any validator keys available (https://github.com/paritytech/substrate/blob/master/client/consensus/babe/src/authorship.rs#L173 & https://github.com/paritytech/substrate/blob/master/client/consensus/babe/src/authorship.rs#L102);
- Register all successful claims (i.e. `claim.is_some()`);
- Expose this information through an RPC API endpoint.

**Comment by andresilva** [comment]
Closed by mistake.

**Comment by burdges** [comment]
Just fyi, I suppose one could argue the chain's security might be improved if session key existed only in a secure enclave and validator operators were not permitted to know their upcoming slots.  We're never plan to require trusted hardware like that because trusted hardware has a rather poor threat model, so no real concern here.  It's not impossible however that some future operators might similarly want to disable themselves this information using trusted hardware, which I suppose means running relative time inside the trusted hardware too.  It's no concern right now though.

**Comment by seunlanlege** [comment]
>  It's not impossible however that some future operators might similarly want to disable themselves this information using trusted hardware.

isn't this behaviour slashable?

**Comment by burdges** [comment]
Apologies for the derail, but no..  

The node would still make blocks normally.  And an operator could still order it to shut down at the end of an epoch.  It'd just hide its secret session keys and this information about when from even its own operator.  

As I said, trusted hardware has a shitty threat model, so we do not envision pursuing this direction, but some folks are really into trusted hardware, so maybe someone would want this one day.

**Comment by burdges** [comment]
Anyways the point is: All early block authorship information, and presumably almost everything presented by this API is secret.  So please do require authentication for accessing this API.  Options include unix domain sockets, non-networked RPCs, local loopback network device, or if going over real networks then require the TLS connection be authenticated with the controller key or something certified by it.  In the TLS case, you should be wary of replay attacks if you do not bind the authentication to the TLS session.

**Comment by andresilva** [comment]
@burdges I agree that the information exposed by this API is sensitive and appropriate security measures should be considered when exposing it. Currently we already expose other sensitive APIs (e.g. `author_hasKeys`, `author_hasSessionKeys`) so I wouldn't want to block this issue on that. Our current security model assumes that RPC is not exposed if you are a validator.

In parity-ethereum we had a way for the node to specify which APIs it would like to expose (we might want to implement similar functionality in Substrate). There's also an idea to move all that logic to a JSON RPC proxy (https://github.com/tomusdrw/jsonrpc-proxy).
