### ISSUE TITLE
Significantly slower compilation times after #3969

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#4116]
I've noticed an increased compilation time recently and bisected the commit that caused it.
The issue is not super severe on a powerful server (8 x i9), the compilation time goes from `6m18s` to `8m52s`, but on a decent laptop it goes from `17m13s` to `25m17s`. It seems consistently increased by ~30%.

It's not very obvious for me what change exactly in #3969 causes this, it would be good to investigate.

**Comment by gnunicorn** [comment]
Confirming. Seeing the same issue here from ~13min -> ~16:50min ...

```
cargo clean && time cargo build:

@ 1fa9b541a409228cde567d6118afa4f517b3078f:

    Finished dev [unoptimized + debuginfo] target(s) in 12m 56s
cargo build  3809,30s user 169,40s system 512% cpu 12:57,04 total


----

@ fc563644f2d36af9cdd26b0f8125cb5da2a6180e:

    Finished dev [unoptimized + debuginfo] target(s) in 16m 49s
cargo build  5060,85s user 227,63s system 521% cpu 16:54,45 total

----

```

**Comment by bkchr** [comment]
I have looked at the build [graph](https://internals.rust-lang.org/t/exploring-crate-graph-build-times-with-cargo-build-ztimings/10975) before and after the change.

Before this commit we had the following targets when running `cargo build`:
substrate 2.0.0 (bin "substrate")

After the commit, we have the following targets:
srml-contracts 2.0.0 (lib)
node-cli 2.0.0 (bin "substrate", lib)
substrate-cli 2.0.0 (lib)
transaction-factory 0.0.1 (lib)
substrate-primitives 2.0.0 (lib)
srml-support 2.0.0 (lib)
node-rpc-client 2.0.0 (bin "node-rpc-client")
srml-session 2.0.0 (lib)
substrate-session 2.0.0 (lib)
node-executor 2.0.0 (lib)
substrate-test-runtime-client 2.0.0 (lib)
substrate-network 2.0.0 (lib)
srml-authority-discovery 0.1.0 (lib)
substrate-service 2.0.0 (lib)
srml-staking 2.0.0 (lib)
substrate-rpc-primitives 2.0.0 (lib)
node-rpc 2.0.0 (lib)
substrate-test-client 2.0.0 (lib)
substrate-offchain 2.0.0 (lib)
substrate-offchain-primitives 2.0.0 (lib)
substrate-consensus-common 2.0.0 (lib)
srml-support-test 2.0.0 (lib)
srml-grandpa 2.0.0 (lib)
substrate-consensus-aura 2.0.0 (lib)
sr-primitives 2.0.0 (lib)
srml-offences 1.0.0 (lib)
srml-democracy 2.0.0 (lib)
srml-utility 2.0.0 (lib)
substrate-consensus-babe 2.0.0 (lib)
substrate-consensus-rhd 2.0.0 (lib)
srml-transaction-payment-rpc-runtime-api 2.0.0 (lib)
sr-std 2.0.0 (lib)
substrate-inherents 2.0.0 (lib)
substrate-authority-discovery-primitives 2.0.0 (lib)
... (probably every crate in the workspace)

It seems that we just need to run `cargo build -p node-runtime`, when we really want to find the commit that blow up the compilations times :D

**Comment by tomaka** [comment]
As mentioned, `cargo build` didn't compile for instance `node-template` before. Now it does.

**Comment by eddyb** [comment]
Looking at the previous comments and the `Cargo.toml` changes in #3969, it seems like `cargo build` before is equivalent to `cargo build -p node-cli` after the change.

Would `cargo build -p node-cli` be considered a viable replacement?

If not, `default-members = ["node/cli"]` could be added to `[workspace]` (see [relevant documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#package-selection)) to restore the original behavior for `cargo build`, `cargo run`, etc.

**Comment by bkchr** [comment]
Yeah, I think its time to close this issue. The reported slowdown was a false positive.
