### ISSUE TITLE
substrate RPC rejects Python?

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/substrate#4131]
Please see this, I think there is a flaw in the RPC server:

https://github.com/substrate-developer-hub/substrate-node-template/issues/11

**Comment by JoshOrndorff** [comment]
The issue is single vs double quotes in the request, not python. I can reproduce your results using `curl`.

```bash
$ curl -H 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"author_rotateKeys", "id":1 }' https://dev-node.substrate.dev:9933

{"jsonrpc":"2.0","result":"0xb2e193c900159b6cf86b2dedea550030c9c912a160e1996decbd09159527d92f882739012a3bb9803e7ee4ffd72a290436735dbdd20a463db2736365c112597b9a2eca667dedde4a32180b2c6bbecb033cc7640f0683da37f3b070c3f72abb2a","id":1}


$ curl -H 'Content-Type: application/json' --data "{ 'jsonrpc':'2.0', 'method':'author_rotateKeys', 'id':1 }" https://dev-node.substrate.dev:9933

{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}
```

Is the Substrate RPC supposed to accept single quotes?

**Comment by drandreaskrueger** [comment]
It became a problem because the default way for Python to stringify its dictionaries seems to be singlequotes: '

**Comment by JoshOrndorff** [comment]
This is not an issue with Substrate RPC, but how you're making the request. I've made a suggestion in the original issue you linked. Please follow up there if you need more help.

**Comment by drandreaskrueger** [comment]
Oh great, thanks. If you want to, see this explanation how it happened: https://github.com/substrate-developer-hub/substrate-node-template/issues/11#issuecomment-555205652
