### ISSUE TITLE
Make weights compatible with u64

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#4141]
Currently `type Weight = u32`. 

It is likely that we will not want to change this, but it should be easily possible, and the code should always respect and use this type, rather than hardcoding u32. This issue is a simple refactor of tests and codes that use the u32. At most, some overflow errors might happen that need to be dealt with, with either saturating or checked arithmetic. 

cc @pepyakin

**Comment by bkchr** [comment]
Isn't that already done in one of your prs?

**Comment by pepyakin** [comment]
I guess this #4124

**Comment by kianenigma** [comment]
Nope, I don't know where you two found it from, but I had the intention to do so in that PR but actually decided to do it separately :D 👀

**Comment by bkchr** [comment]
Why do we need to add different overflow checks when we use a different type?
