### ISSUE TITLE
RPC parsing error

### ISSUE THREAD

**Issue by IPSE-TEAM** [paritytech/substrate#4168]
the substrate master code compiled,but the error come out:

{jsonrpc: "2.0", error: {code: -32700, message: "Parse error"}, id: null}
error: {code: -32700, message: "Parse error"}
code: -32700
message: "Parse error"
id: null
jsonrpc: "2.0"

**Comment by jacogr** [comment]
Fix here https://github.com/paritytech/substrate/pull/4166

**Comment by bkchr** [comment]
Fixed by: https://github.com/paritytech/substrate/pull/4166
