### ISSUE TITLE
Module doesn't have export AuraApi_slot_duration

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#4172]
Even though this is configured in the runtime, it complains when I run the node.
```
Error: Service(Client(Execution(Wasmi(Function("Module doesn\'t have export AuraApi_slot_duration")))))
```

The repo/runtime this is on can be found here: https://github.com/hicommonwealth/edgy/blob/master/node/runtime/src/lib.rs

**Comment by bkchr** [comment]
Did you purge your db?

**Comment by zkpzoyoe** [comment]
Has this been solved? It seems that I got this problem as well.

**Comment by bkchr** [comment]
@zkpzoyoe You need to purge your db.
