### ISSUE TITLE
Prefixed double_map

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4178]
I would like to iterate every elements inside a double map. This will be used by offchain worker so I am not too worried about performance issue.

Use cases: Iterate every positions in a finial service chain, check if they are safe, and submit transaction to liquidate unsafe positions. This can happen like every 10 mins (maybe configurable via #3912) and with some economic incentive, we can have reasonable confidence that there will be enough people running offchain worker to close unsafe positions.

Related: #3992

**Comment by xlc** [comment]
Partially duplicates #3675?

**Comment by thiolliere** [comment]
Done in https://github.com/paritytech/substrate/pull/4185
