### ISSUE TITLE
error: failed to run custom build command for `clear_on_drop v0.2.3`

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4179]
On current master 990acfe4d67c70b44005350a2e2122e810809849

`cargo check -p pallet-balances --no-default-features --target=wasm32-unknown-unknown` gives following error

```
   Compiling backtrace-sys v0.1.32
   Compiling num-traits v0.2.9
error: failed to run custom build command for `clear_on_drop v0.2.3`

Caused by:
  process didn't exit successfully: `/Users/xiliangchen/projects/substrate/target/debug/build/clear_on_drop-9ed103d1e303c0cb/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("wasm32-unknown-unknown")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-apple-darwin")
CC_wasm32-unknown-unknown = None
CC_wasm32_unknown_unknown = None
TARGET_CC = None
CC = None
CFLAGS_wasm32-unknown-unknown = None
CFLAGS_wasm32_unknown_unknown = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
running: "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-o" "/Users/xiliangchen/projects/substrate/target/wasm32-unknown-unknown/debug/build/clear_on_drop-f532bdc078fbeff4/out/src/hide.o" "-c" "src/hide.c"
cargo:warning=error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-unknown"'
cargo:warning=1 error generated.
exit code: 1

--- stderr


error occurred: Command "clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-unknown-unknown" "-Wall" "-Wextra" "-o" "/Users/xiliangchen/projects/substrate/target/wasm32-unknown-unknown/debug/build/clear_on_drop-f532bdc078fbeff4/out/src/hide.o" "-c" "src/hide.c" with args "clang" did not execute successfully (status code exit code: 1).



warning: build failed, waiting for other jobs to finish...
error: build failed
```

I don't understand why runtimes builds fine in Substrate.

**Comment by xlc** [comment]
Reduced example: https://github.com/laminar-protocol/substrate/tree/wasm-error and `cargo check --manifest-path palette/balances/Cargo.toml  --no-default-features --target=wasm32-unknown-unknown`

Looks like `primitives/std` in `[dev-dependencies]` is polluting `primitives` in `[dependencies]`. Sounds like Cargo bug?

**Comment by xlc** [comment]
I see. This workarounds the issue in Substrate
https://github.com/paritytech/substrate/blob/990acfe4d67c70b44005350a2e2122e810809849/bin/node/cli/Cargo.toml#L90

**Comment by xlc** [comment]
Reopen this because something still isn't right. The workaround should at least have a TODO associated with this issue.

**Comment by kianenigma** [comment]
You mean the `optional = true `? 

Generally, I think we don't really want to put some content which is regarding _how to hack around cargo's bugs_ here. You can safely close this IMO.

**Comment by xlc** [comment]
`clear_on_drop` is not directly used by Substrate. It should be removed once this Cargo bug is fixed.

**Comment by bkchr** [comment]
@xlc see https://github.com/paritytech/substrate/pull/4180

We can not do more at the moment. You also need to go into the directory of the crate and call `cargo check ...`. You can not do this with `cargo check -p ..` in the top directory.

**Comment by bkchr** [comment]
Okay, yeah. If you really want to have `cargo check` runs on your dependencies. We probably need a tool that strips the `dev-dependencies` or someone fixes cargo.

**Comment by xlc** [comment]
@bkchr Thanks. I kind of got it working. 

https://github.com/laminar-protocol/open-runtime-module-library/blob/master/Makefile#L2

**Comment by bkchr** [comment]
Yeah, I saw your commit, but this is also just a hack^^
