### ISSUE TITLE
Wasmtime fails to compile on ARM architectures.

### ISSUE THREAD

**Issue by riusricardo** [paritytech/substrate#4188]
OS: Ubuntu
Arch: AArch64

There is a known wasmtime issue: https://github.com/bytecodealliance/wasmtime/issues/339
I'm building it after installing the required dependecies using this [script](https://github.com/paritytech/scripts/blob/master/wasm-utils/install-rust-lld-ARM.sh)

Error:
```
  = note: /home/ubuntu/polkadot/target/release/deps/libwasmtime_jit-7ebb7eb626f556ca.rlib(wasmtime_jit-7ebb7eb626f556ca.wasmtime_jit.cf56work-cgu.4.rcgu.o): In function `wasmtime_jit::link::link_module':
          wasmtime_jit.cf56work-cgu.4:(.text._ZN12wasmtime_jit4link11link_module17h7df126b02cc2c10fE+0xd38): undefined reference to `__rust_probestack'
          wasmtime_jit.cf56work-cgu.4:(.text._ZN12wasmtime_jit4link11link_module17h7df126b02cc2c10fE+0xd3c): undefined reference to `__rust_probestack'
          collect2: error: ld returned 1 exit status
          
error: aborting due to previous error
error: could not compile `polkadot`.
```
Building a Substrate based chain works well unless wasmtime is enabled.

cc: @jimpo

**Comment by jimpo** [comment]
@pepyakin The problem is that wasmtime is a default feature right now on polkadot. Ideally, wasmtime would only be a default feature on certain architectures. Is there a way to do that with Cargo?

**Comment by niklasad1** [comment]
@jimpo https://github.com/rust-lang/cargo/issues/2524

**Comment by bjornwgnr** [comment]
Can this be resolved? Looks like target-specific features for dependencies has been implemented and is available in nightly as of recently: rust-lang/cargo/issues/7914

**Comment by pepyakin** [comment]
Good to know!

Although I am not sure if we can make use of that until it stabilizes?

**Comment by niklasad1** [comment]
> Although I am not sure if we can make use of that until it stabilizes?

What do you mean by that i.e. are you referring to that substrate can't rely on unstable features?

Otherwise, it could be nightly only and you can enable it by `cargo +nightly build -Z features=itarget`? 

If `-Z features=itarget` is not enabled it would probably end up in a compile error with the union of all features for the specific crate but I'm not sure...

**Comment by pepyakin** [comment]
I mean that we have one Cargo.toml that has to work both on nightly and stable and we would write there

```toml
[dependencies.`cfg(target_arch="x86_64")`.wasmtime]
```

how would that work when a regular user compiles substrate with stable?

**Comment by niklasad1** [comment]
Ok, I see

> how would that work when a regular user compiles substrate with stable?

Yeah, you are right that would bring those additional `wasmtime` features into the stable build.
