### ISSUE TITLE
Substrate: Alternative consensus engines

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#420]
Substrate currently uses only Rhododendron. The consensus algorithm should instead be stored in the `:consensus` key of the database (defaulting to `rho` if it doesn't exist) and substrate should use that algorithm to determine what consensus protocol to use for the given block. Since some consensus algorithms are non-final or require multiple blocks to reach finality, then any block whose state-transition function alters the `:consensus` key to anything other than `rho` will use `rho` to finalise that block as a handoff procedure.

The consensus algorithm is free to require arbitrary other storage keys for its operation.

In principle, in the future, there may be a handoff to `dot`.

**Comment by DemiMarie-parity** [comment]
It seems that this has already been fixed.  We already use AuRa and GRANDPA, and BABE is being worked on.

**Comment by DemiMarie-parity** [comment]
@gavofyork can this be closed?

**Comment by tomaka** [comment]
Triage. This looks like a duplicate of #1304, which contains more details.
