### ISSUE TITLE
I just hung up the node

### ISSUE THREAD

**Issue by puti94** [paritytech/substrate#4206]
`const wsProvider = new WsProvider('wss://kusama-rpc.polkadot.io/');
    const api = await ApiPromise.create({provider: wsProvider});
    await api.isReady;
    let transfer = api.tx.balances.transfer(
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      '120000000000000000000000000000000000000',
    );
    const data = await api.rpc.payment.queryInfo(transfer.toHex());`
I didn't mean to

**Comment by bkchr** [comment]
That is a known bug currently, but we are working on it.

Nevertheless, ty.
