### ISSUE TITLE
Scaffold and harness to turn a Substrate Runtime into a Polkadot Parachain

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#421]
In `substrate/runtime` there are several modules that can be composed (e.g. `polkadot/runtime`) to create a single (wasm-targetable) runtime. Combined with Substrate's networking, database and consensus, a whole blockchain can be created.

A substrate runtime provides little more than four callable endpoints: `initialise_block`, `apply_extrinsic`, `finalise_block` and `execute_block` (which just does all three). It is provided with two real extrinsic endpoints to call (`get_storage` and `set_storage`) together with several additional "optimisation" endpoints for doing common crypto, Merkle-tree stuff and wasm sandboxing.

A parachain execution environment is somewhat different since the only Wasm code endpoint is one which must validate a block based upon the previously validated block's output:

- `validate_block(block: Vec<u8>, previous_output: Vec<u8>) -> Result<Vec<u8>, Error>`

No database is provided; in the case of a parachain which uses a substrate-like KV database for storage, then it must be simulated through a set of witness data being passed in through the `block` data. Scaffold would be needed to ensure this is API-compatible with the `get_storage` and `set_storage` of Substrate, and to make a `block` format which includes both a compatible `header`, the `extrinsics` and the `witness` data. It is likely that a different `Executive` module would be needed here.

For block production and synchronisation a generic collator node implementation is needed. Much like the generic parts of Substrate, this would take a Substrate-like runtime and provide a specialised node which is able to light-sync to Polkadot, full-sync to the parachain chain and produce blocks through the `initialise_block`, `apply_extrinsic` and `finalise_block` endpoints.

Notably, these blocks would need to correspond to the runtime harness's expectations, including the appropriate header and witness data. Furthermore, the specialised node would, like Substrate, need to maintain a peer network of other collators, fishermen and full nodes on the same parachain together with a constantly rotating set of Relay-chain peers for submitting blocks.

**Comment by bkchr** [comment]
Also done.
