### ISSUE TITLE
`ValidatorPrefs` Updates Should Apply at Next Era

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#4220]
If a current validator issues `staking::validate()` with new `ValidatorPrefs`, the effects are felt immediately. That is, the validator can change their commission mid-era and take the rewards from their nominators.

Related: https://github.com/paritytech/substrate/issues/4121

**Comment by thiolliere** [comment]
if we fix this and allow the validator to change the preference only for future era is that enough ?
I can imagine a validator changing the preference just before a new era is planned, thus no nominators will have the time to change their nomination.

**Comment by joepetrowski** [comment]
Validators will probably be more advanced and diligent than nominators, so they definitely could pull this off. That said, hopefully their nominators would only suffer one era of lost rewards and would then choose a different validator. Perhaps something for the research team to chime in on whether changes should apply in era `n + 1` or `n + 2`.

CC @burdges @AlistairStewart

**Comment by burdges** [comment]
As you like, another option is era n+1 but only if the transaction appears before the final epoch of era n, after that it's n+2.

**Comment by thiolliere** [comment]
Due to https://github.com/paritytech/substrate/pull/4474 ValidatorPrefs indeed apply at next era. though there is no delay for nominators to know this preference ahead of time (a validator can change its preference just before the new era)
