### ISSUE TITLE
How to Disable `Grandpa` in `service` with Latest Substrate Version?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/substrate#4224]
The block stuck at 1000 and I got this https://github.com/paritytech/substrate/issues/2834 too.

So I'm trying to disable the `Grandpa`. 

I remove all the `Grandpa` in `runtime` and `chain_spec`.

Everything is ok, it can be compiled.

When I run `cargo run --release -- --dev`, it shows:

```
2019-11-27 20:34:59 Roles: "FULL"
2019-11-27 20:34:59 Loading GRANDPA authority set from genesis on what appears to be first startup.
Error starting the node: Execution: Function: Module doesn't have export GrandpaApi_grandpa_authorities
```

This lead me to modify the `service`. But in the latest substrate
version. `construct_service_factory` was removed and switch `aura` to `babe`. I don't know how to do this.

**Comment by rphmeier** [comment]
`node/service` will still have references to GRANDPA you'll want to get rid of.

**Comment by AurevoirXavier** [comment]
Hi, @rphmeier 

The block stuck at 1000 now.
How can I fix this error if I don't disable the `Grandpa`?
