### ISSUE TITLE
imOnline functionality reporting wrong counts for authoredBlocks [Polkadot]?

### ISSUE THREAD

**Issue by Mitchell-Grimes** [paritytech/substrate#4228]
Original issue for a different project based off substrate: 

- https://github.com/polkadot-js/apps/issues/1954

I'm curious on why imOnline would think that a validator is offline for an entire session, even though it authored the first and last block for that said session.  Specifically the `imOnline.authoredBlocks` module

If the imOnline module is not able to access the proper `authored blocks` of a chainstate, could this report '0' for the total?

**Comment by chrisli30** [comment]
@Mitchell-Grimes We have exactly the same question. Following up here to see if you have got to the bottom of this?

Thanks!

**Comment by bkchr** [comment]
This question is 2 years old, aka very likely to be already fixed. 

@chrisli30 if you have such problems. Please proof with the respective links in a new issue. This means, showing that your validator produced blocks in a particular session, but im-online reported that it was offline.
