### ISSUE TITLE
Multi node

### ISSUE THREAD

**Issue by damianoazzolini** [paritytech/substrate#4229]
I'm tryng to connect multiple nodes together. I've tried to adapt the instructions from polkadot (https://github.com/paritytech/polkadot#32-local-two-node-testnet) in this way: in one terminal
`$> substrate --dev --alice` 
and in the other
`$> substrate --dev --bob --port 30334 --bootnodes ip4/127.0.0.1/tcp/30333/NODE_ID`
but the two nodes does not communicate... It is possible to do it? Is there any guide?

**Comment by damianoazzolini** [comment]
I've made some progress. In the first terminal i start Alice with 
```
$> substrate --dev --base-path /tmp/alice --alice --port 30333 --validator
```
and everithing works fine. In the second terminal i start Bob
```
$> substrate --base-path /tmp/bob --dev --bob --port 30334 --validator --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/ALICE_ID
```
Now, the output of Bob terminal is ok `2019-11-29 11:29:24 Idle (1 peers), best: #40 (0xdf84…9d9a), finalized #38 (0x6322…27aa)` but Alice seems to stop working 
```
2019-11-29 11:29:27 Next epoch starts at slot 525007790
2019-11-29 11:29:27 New epoch 0 launching at block 0x4429…87d5 (block slot 525007590 >= start slot 525007590).
2019-11-29 11:29:27 Next epoch starts at slot 525007790
2019-11-29 11:29:27 New epoch 0 launching at block 0x4429…87d5 (block slot 525007590 >= start slot 525007590)
... and print the same data over and over
```
I've tried to purge the chain using `substrate purge-chain --dev` and `rm -rf /tmp/alice` and `rm -rf /tmp/bob` but the issue is still present

**Comment by marcio-diaz** [comment]
I think you should use `--chain=local`. Try:

`./target/debug/substrate --chain=local --alice` in a terminal and 
`./target/debug/substrate --chain=local --bob -d /tmp/bob` in another one.
