### ISSUE TITLE
"print_utf8" and "print_num", the result can't show on console. 

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/substrate#4238]
use runtime_io::misc::{print_num, print_utf8};
 in "decl_module!", i use 'print_utf8("------------------------------------".as_bytes());'   
and  'print_num(64 as u64);' 
in the time compile, have no error. but when i do something in ui, the console have no showing'-------------------------' or  '64'.

**Comment by bkchr** [comment]
Add the following parameter when running your node `-lruntime=debug`, that will show you the output.
