### ISSUE TITLE
`frame-balances` called `pallet-balances` in Cargo.toml

### ISSUE THREAD

**Issue by rockbmb** [paritytech/substrate#4252]
See [this](https://github.com/paritytech/substrate/blob/master/frame/balances/Cargo.toml#L2), and also [this](https://github.com/paritytech/substrate/blob/master/frame/aura/Cargo.toml#L2).

Given the [recent renaming of Pallet to FRAME](https://github.com/paritytech/substrate/pull/4182), shouldn't the above two occurrences of `pallet`, and whichever others may exist, be replaced with `frame` as well?

**Comment by joshua-mir** [comment]
modules in `frame` are called pallets - things that are prefixed `frame` are a part of the `frame` api itself (support, system, etc.).
