### ISSUE TITLE
Submit the Substrate logo to simpleicons.org

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/substrate#4258]
Some projects based on Substrate want add the Substrate Badge to README, likes this:  

[![Substrate version](https://img.shields.io/badge/Substrate-2.0.0-brightgreen?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAMAAAAMCGV4AAACnVBMVEUAAADx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/Lx8/L///8xTYz2AAAA3nRSTlMAAAAAAAMLDgwDAAAAAAAAAAEIDRATFRYNAgAAAAAABgwPEhQYGh4gHQwCAAURDhEUFyIfICImKSsfCgc+Mh0XUHkpKTwtLjIyDQdATj4sYJdmdmMyNDc3Dwc8SEQ/QH+wolI1OTs8EAc5Qj84fpRDepU7PkFBEgY1PDo1RJC1mFA/Q0dEEwUwODQxV3tol4xGR01JFAUsNC4sOS0tb3dMTVFPFQMYKCkmIh8uT05PU1hQEQAABxceHxotTlNWWDQHAAAAAAAIEhQtVFlCDwAAAAAAAAABBzBZHwAAAAC7ixRpAAAAHUlEQVQI12NkYEQGnxn5UPiMLPxDm8/IcBGZpwwAu3gDrD4z5cUAAAAASUVORK5CYII=)](https://substrate.dev/) 

Demo: <https://github.com/jiangfuyao/Acala/blob/master/README.md> . 

So, If have time, submit the Substrate logo to the <https://simpleicons.org/>, It's not only used for the badge. 

Submit link: <https://github.com/simple-icons/simple-icons/issues/new?template=icon_request.md>

**Comment by goldsteinsveta** [comment]
There are two versions for the logo now. I will submit as soon (Q4 2019 :)) as there's a graphic decision which one to use for this case

**Comment by goldsteinsveta** [comment]
FYI https://github.com/simple-icons/simple-icons/pull/2324

**Comment by jiangfuyao** [comment]
It's very Cool!  
```
[![Substrate version](https://img.shields.io/badge/Substrate-2.0.0-brightgreen?logo=Parity%20Substrate)](https://substrate.dev/)
```
[![Substrate version](https://img.shields.io/badge/Substrate-2.0.0-brightgreen?logo=Parity%20Substrate)](https://substrate.dev/)

----
![屏幕快照 2020-02-27 下午9 34 25](https://user-images.githubusercontent.com/34789555/75449976-f3ed1480-59a8-11ea-820d-0a153345b861.png)
