### ISSUE TITLE
invalid command code when use rename-crates-for-2.0.sh on mac 10.14

### ISSUE THREAD

**Issue by jingleizhang** [paritytech/substrate#4269]
substrate version 'f094a7ea281ddfbb37c7e713979734a21fd51dba'
mac 10.14

use: **sh .maintain/rename-crates-for-2.0.sh**

Renaming substrate-application-crypto to sc-application-crypto
sed: 1: "./Cargo.toml": invalid command code .
sed: 1: "./.maintain/node-templa ...": invalid command code .
sed: 1: "./test/utils/Cargo.toml": invalid command code .
sed: 1: "./test/utils/chain-spec ...": invalid command code .
sed: 1: "./test/utils/runtime/Ca ...": invalid command code .
sed: 1: "./test/utils/runtime/cl ...": invalid command code .
sed: 1: "./test/utils/transactio ...": invalid command code .
sed: 1: "./test/utils/primitives ...": invalid command code .
sed: 1: "./test/utils/client/Car ...": invalid command code .
sed: 1: "./bin/node-template/Car ...": invalid command code .

...and so on

**Comment by bkchr** [comment]
You probably need to use `bash`.

CC @gnunicorn
