### ISSUE TITLE
1014: Priority is too low

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/substrate#4282]
in the latest version, when i run the code on ui, for exaple:
```
#[weight = SimpleDispatchInfo::FixedNormal(500_000)]
pub fn do_something(origin, something: u32) -> Result {
	// TODO: You only need this if you want to check it was signed.
	let who = ensure_signed(origin)?;

	// TODO: Code to execute when something calls this.
	// For example: the following line stores the passed in u32 in the storage
	Something::put(something);

	// here we are raising the Something event
	Self::deposit_event(RawEvent::SomethingStored(something, who));
	Ok(())
}
```
then have the error:
1014: Priority is too low
 the i do some thing else in  ui, all have the same error.

**Comment by bkchr** [comment]
@tomusdrw any idea?

**Comment by tomusdrw** [comment]
@wjy19990622 your local pool already contains a transaction with the same nonce. Can you post some logs with `-ltxpool=trace`?

Also restarting a node should fix this (as well as adding `system_accountNextNonce` custom RPC extension to your node initialisation).

**Comment by tomusdrw** [comment]
@wjy19990622 please re-open when you are able to provide more details on that issue.
