### ISSUE TITLE
How to interact with substrate node using web3.js?

### ISSUE THREAD

**Issue by sbhm2** [paritytech/substrate#4283]
I want to do two things with my local --dev substrate node:-
1. Interact with it using web3.js instead of polkadot-js/api.
2. Want my chain connection over http instead of ws or wss.
Are these things possible to do with parity substrate chain?

**Comment by bkchr** [comment]
@jacogr have you any input for this?

**Comment by jacogr** [comment]
The RPCs are not Ethereum-compatible, rather it is expanded and determined by the on-chain metadata. You put a RPC proxy in front that translates the calls.

**Comment by bkchr** [comment]
I think that explains it, ty @jacogr
