### ISSUE TITLE
Moment type can't show on ui

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/substrate#4287]
pub struct MyStruct<T::Moment> {
mytime: T::Moment,
}

in ui "setting", the code for example:
{"MyStruct":
{
"mytime":"Moment"
}
}

but the result is unknown.

**Comment by wjy19990622** [comment]
pub struct MyStruct<T:  timestamp::Trait> {
mytime: T::Moment,
}

**Comment by bkchr** [comment]
CC @jacogr

**Comment by jacogr** [comment]
You need to open it in https://github.com/polkadot-js/apps - I am assuming that is the UI you are referring to here.

**Comment by wjy19990622** [comment]
yes， i open it in  https://github.com/polkadot-js/apps ， but i can't  show on the UI when i use the moment type in struct。

**Comment by jacogr** [comment]
Sorry, I meant that it needs to be logged as an apps-related issues in the apps repo, this has got nothing to do with Substrate. The types are defined in the UI, the result is queried from the UI.

https://github.com/polkadot-js/apps/issues
