### ISSUE TITLE
`decl_event!` should generate only one struct/type

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#4288]
Currently `decl_event!` creates `enum RawEvent` and `type Event =` when you have a generic event, but for none-generic events it just generates `enum Event`.
This needs to be unified, aka just generate `enum Event`.

As rust automatic trait derives are somewhat broken, the macro will need to implement`Clone`, `PartialEq`, `Eq` and `RuntimeDebug` on it's own. It is required that trait bound will not be put onto the generic parameter itself and instead it needs to be put onto the associated types, so something like this:
```
enum Event<T> {
    SomeEvent(T::Data),
}
```

has the following `PartialEq` bounds:
```
impl<T: Trait> PartialEq for Event<T> where T::Data: PartialEq
```

and not:

```
impl<T: Trait> PartialEq for Event<T> where T: PartialEq
```

`parity-scale-codec` does this already automatic and so `derive(Encode, Decode)` should work without any problems.

The code of the macro can be found [here](https://github.com/paritytech/substrate/blob/master/frame/support/src/event.rs)

**Comment by herou** [comment]
@bkchr Can I work on this ticket?

**Comment by herou** [comment]
@bkchr any other issue which you offer mentorship?

**Comment by bkchr** [comment]
@herou what is your background? What kind of tasks are you searching for?

**Comment by herou** [comment]
@bkchr I am a mobile developer (Java), recently (6 months) learning rust, substrate, and blockchain to get my feet into.

**Comment by bkchr** [comment]
Maybe this one: https://github.com/paritytech/substrate/issues/3059 ?

**Comment by thiolliere** [comment]
Fixed by https://github.com/paritytech/substrate/pull/6877
