### ISSUE TITLE
Verification failed from peer: Execution: Could not convert parameter `block` between node and runtime: Error decoding field Block.extrinsics

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4295]
My testnet node failed to sync new blocks with this error

```
2019-12-05 21:28:42.713 import-queue-worker-0 TRACE sync  Starting import of 128 blocks  (23485..23612)
2019-12-05 21:28:42.714 import-queue-worker-0 TRACE sync  Header 0x3997…5ab6 has 2 logs
2019-12-05 21:28:42.904 import-queue-worker-0 TRACE sync  Verifying 23485(0x3997…5ab6) from QmfZFm6bGGpaJ8J2TJb14ubtm86hdNeAwqvxDoVw5FDWUC failed: Execution: Could not convert parameter `block` between node and runtime: Error decoding field Block.extrinsics
2019-12-05 21:28:42.905 tokio-runtime-worker-8 TRACE sync  Imported 0 of 128
2019-12-05 21:28:42.905 tokio-runtime-worker-8 INFO sc_network::protocol::sync  Verification failed from peer: Execution: Could not convert parameter `block` between node and runtime: Error decoding field Block.extrinsics
2019-12-05 21:28:42.905 tokio-runtime-worker-8 DEBUG sync  Restarted with 23484 (0x6d1c…ad48)
2019-12-05 21:28:42.905 tokio-runtime-worker-8 DEBUG sync  New peer with known best hash 0x6d1c…ad48 (23484).
```

All we did was submitted a sudo call at block 23485.

https://acalanetwork.github.io/apps/#/explorer/query/23485

The code: https://github.com/AcalaNetwork/Acala

To reproduce

`docker run --rm acala/acala-node`

**Comment by bkchr** [comment]
Did you had any runtime upgrades before?

**Comment by xlc** [comment]
No.

**Comment by bkchr** [comment]
But your validators still continue building new blocks?

**Comment by xlc** [comment]
Yes. 
Telemetry: https://telemetry.polkadot.io/#list/Acala
Explorer: https://acalanetwork.github.io/apps/

**Comment by bkchr** [comment]
There is no sudo call at the other linked block?

**Comment by xlc** [comment]
I have regenerate the genesis and reset the network and it seems find now. Will reopen if happens again. 

I guess it may be relates to some cache issue of the wasm file when building spec so I cargo clean it first.

**Comment by ToufeeqP** [comment]
Hi, I am getting the same error when I tried to start the new archive node from the Boot node. The new node's binary is different though since it has some updates, should I be using the same binary which is used in the boot node?

**Comment by ToufeeqP** [comment]
This is the exact error I am getting on archive node:
`Apr 07 10:16:58.469  INFO ⚙️  Syncing, target=#1624862 (1 peers), best: #256 (0x1411…960d), finalized #0 (0x04f5…578a), ⬇ 16.7kiB/s ⬆ 0.7kiB/s    
Apr 07 10:16:58.747  WARN 💔 Verification failed for block 0x465884fc0ef67611a192629819b869e57f25a507ba90a31d9bcc6a34392619c4 received from peer: 12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2, "Execution: Could not convert parameter `block` between node and runtime: Error decoding field Block.extrinsics"    
Apr 07 10:17:03.337  WARN 💔 Verification failed for block 0x465884fc0ef67611a192629819b869e57f25a507ba90a31d9bcc6a34392619c4 received from peer: 12D3KooWBmAwcd4PJNJvfV89HwE48nwkRmAgo8Vy3uQEyNNHBox2, "Execution: Could not convert parameter `block` between node and runtime: Error decoding field Block.extrinsics"    
Apr 07 10:17:03.472  INFO 💤 Idle (0 peers), best: #324 (0x9ed0…a12b), finalized #0 (0x04f5…578a), ⬇ 8.4kiB/s ⬆ 0.6kiB/s `

**Comment by bkchr** [comment]
@ToufeeqP this means you probably did not bump your `spec_version` properly.

**Comment by ToufeeqP** [comment]
Thanks for replying, I will try bumping the `spec_version`  to match the current spec_version of the boot node.

**Comment by ToufeeqP** [comment]
I just realised that I have never updated the boot node, so its `spec_version` is 1 which is the same as the current spec-version from which I am trying to start a new node. However, when I used the same binary as the one which is used in the boot node, a new node started normally & syncing the old blocks.

**Comment by bkchr** [comment]
You should not use the same spec_version. Based on the spec_version it is decided which runtime to call. And you native runtime is probably not compatible anymore.

**Comment by bkchr** [comment]
https://substrate.dev/docs/en/knowledgebase/runtime/upgrades#runtime-versioning

**Comment by ToufeeqP** [comment]
Any idea, how to make the native runtime compatible with the current running node?

**Comment by bkchr** [comment]
No, you should be self aware on what you changed in your runtime to make it incompatible.
