### ISSUE TITLE
the doublemap value allways  return 0 or null in UI.

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/substrate#4299]
there are my doublemap in substrate:
TokenInfo: double_map T::AccountId, blake2_256(Vec<u8>) => u32;

i update the doublemap's  key and value successful. but in https://polkadot.js.org/apps/#/chainstate,  my doublemap values can't show correctly, allway 0x00. then i change the value type to u32,  it allway return 0.
but on the console, return correct  Vec<u8> or u32.

tell me what can i do?  thanks.

**Comment by bkchr** [comment]
Please open an issue at https://github.com/polkadot-js/apps

This is the appropriate repository for these kind of bugs.
