### ISSUE TITLE
Question: how to convert core:std:str to <T as frame_system::Trait>::AccountId with no_std?

### ISSUE THREAD

**Issue by jingleizhang** [paritytech/substrate#4310]
Trying to convert core:std:str to \<T as frame_system::Trait\>::AccountId 
in offchain-worker runtime with no_std, as:

```
hex = { version = "0.4.0", default-features = false }
use hex::FromHex;
use primitives::crypto::UncheckedInto;

let r_accnt: T::AccountId = <[u8; 32]>::from_hex("Cx5qYMJDA7fuH8MAeRf5o4Xya4Zz9zAqqvSz1joXKoectda").unwrap().into();

```

and I just find errors like

```
the trait `core::convert::From<[u8; 32]>` is not implemented for `<T as frame_system::Trait>::AccountId`

```
I have read the codes in subkey. 

But question still is how to convert core:std:str should  to  \<T as frame_system::Trait\>::AccountId in offchain-worker runtime

thanks very much!

**Comment by bkchr** [comment]
Try `<T::AccountId as Decode>::decode(&mut &hex::from_hex())`.

But why do you need a hardcoded account id?

**Comment by jingleizhang** [comment]
Thanks a lot, that decode works:)

In this case the account id is fetched from http+json by offchain worker, then it has to be decoded to T::AccountId .
