### ISSUE TITLE
Extend naming system

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4311]
Naming system could become more sophisticated:

Introduce ability for council to verify names. Deposit `FEE+BOND`; council verifies your information (by checking your website on which the account ID should be published, and querying you on riot); if good, `BOND` is returned, `FEE` goes to treasury. If bad, `BOND+FEE` goes to treasury.

In the future, more identification fields can be added.

```
#[derive(Encode, Decode)]
pub enum Field {
  Web,
  Riot,
}
/// Information that has been verified by the `VerifierOrigin` (which will initially be configured
/// to be the council, but could be a community-led oracle, too).
Verified: map T::AccountId => Vec<(Field, Vec<u8>)>;
```

Secondly, introduce basic vouching system, so that outfits who control a lot of public accounts (e.g. Cryptium) are able to vouch for each individually without bothering the council for each one.

```
/// Ordered account IDs of accounts that have been vouched for by the key. The balance
/// is how much has been deposited so far for registration. Except for fee changes, It should
/// be proportional to the number of entries. The size of the `Vec` should be capped at
/// something sensible (e.g. 100). If additional entries are needed, then multiple levels of
/// indirection can be used.
Vouched: map T::AccountId => (T::Balance, Vec<T::AccountId>);
```

**Comment by bneiluj** [comment]
It's very good idea.
