### ISSUE TITLE
Figure out why Phragmen is taking so long for staking

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4313]
At the end of every era, the chain stalls for some substantial period of time. This is likely due to Phragmen taking too long to execute, coupled with a timeout during block authoring that discards blocks if they take too long to evaluate when executed using wasmi (the slow interpreter).

We need to profile the wasmi execution of this using real data from the chain to confirm that it is taking longer than a few seconds to execute and see what of the algorithm is most problematic (trie i/o, general CPU, memory allocations, crypto), and whether there's a hidden O(N**2) complexity that we didn't see before.

**Comment by gavofyork** [comment]
@kianenigma one to look into once you're back online.

**Comment by burdges** [comment]
cc @AlfonsoCev

**Comment by kianenigma** [comment]
alleviated via #4517. 

As for a wasmi benchmark, the current benchmark force has already included this as well.

**Comment by kianenigma** [comment]
Okay I confidently see this is closed as we have now different mechanisms in place.
