### ISSUE TITLE
Figure out the latest memory leak/CPU hog

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4316]
Related: #4249

Memory spiked with no obvious runtime activity at ~2330 CEST on 2019/12/05. There was highly periodic CPU usage at the same time:

![image](https://user-images.githubusercontent.com/138296/70325159-a772bc80-1831-11ea-90ee-a47a18587e16.png)

Figure out what this is and fix it.

**Comment by gnunicorn** [comment]
outdated.
