### ISSUE TITLE
Compile errors in multiple Substrate modules when building on Substrate

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#4334]
Following up on #4333

```
error[E0046]: not all trait items implemented, missing: `generate_with_phrase`, `from_phrase`
  --> /home/joshy/.cargo/git/checkouts/substrate-7e08433d4c370a21/fa8b36b/primitives/finality-grandpa/src/lib.rs:33:2
   |
33 |     app_crypto!(ed25519, GRANDPA);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `generate_with_phrase`, `from_phrase` in implementation
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
   = help: implement the missing item: `fn generate_with_phrase(_: core::option::Option<&str>) -> (Self, alloc::string::String, <Self as sp_core::crypto::Pair>::Seed) { unimplemented!() }`
   = help: implement the missing item: `fn from_phrase(_: &str, _: core::option::Option<&str>) -> core::result::Result<(Self, <Self as sp_core::crypto::Pair>::Seed), sp_core::crypto::SecretStringError> { unimplemented!() }`
```

I first encountered this error when working on this [Substrate Recipes PR](https://github.com/substrate-developer-hub/recipes/pull/107). This is all runtime code, no outer-node stuff. That will come next.

Steps to reproduce the error
```
git clone -b newer-upstream https://github.com/substrate-developer-hub/recipes.git
cargo check -p weight-fee-runtime
```

cc @tomusdrw since we discussed this previously

**Comment by JoshOrndorff** [comment]
I've also encountered this error in a Substrate crate while updating to recent builds of master.
```
error[E0432]: unresolved imports `txpool_api::error`, `txpool_api::PoolStatus`
  --> /home/joshy/.cargo/git/checkouts/substrate-7e08433d4c370a21/fa8b36b/client/transaction-pool/graph/src/pool.rs:37:18
   |
37 | use txpool_api::{error, PoolStatus};
   |                  ^^^^^  ^^^^^^^^^^ no `PoolStatus` in the root
   |                  |
   |                  no `error` in the root
```

Please advise whether these should be opened in separate issues.

**Comment by tomusdrw** [comment]
`weight-fee-runtime` compiles successfully here:
https://github.com/substrate-developer-hub/recipes/pull/110

Most of the errors was because of imports of incorrect crates - i.e. you can't import any `sc-*` crate to the runtime. `sp-*` crates usually need `default-features=false` and then `std` feature enable conditionally.
I think none of the issues mentioned here is in fact substrate issue, so closing. @JoshOrndorff feel free to open new issues in case you run into any more problems.

**Comment by JoshOrndorff** [comment]
Thank you very much @tomusdrw !

**Comment by tarunjais2** [comment]
> `weight-fee-runtime` compiles successfully here: [substrate-developer-hub/recipes#110](https://github.com/substrate-developer-hub/recipes/pull/110)
> 
> Most of the errors was because of imports of incorrect crates - i.e. you can't import any `sc-*` crate to the runtime. `sp-*` crates usually need `default-features=false` and then `std` feature enable conditionally. I think none of the issues mentioned here is in fact substrate issue, so closing. @JoshOrndorff feel free to open new issues in case you run into any more problems.

hi, @tomusdrw and @JoshOrndorff, I have been using sc-* and sp-* crates but don't know the difference between them can you guys help me to find the difference?

**Comment by WB-Expert5007** [comment]
Hi, Everyone. How are you? I am converting the consensus engine from poa to pos on substrate node template project. For it, I am referencing this github, https://github.com/ltfschoen/substrate-node-template/pull/4/files. But there is one problem. Reference project's version is 3.0.0 but my current substrate-node-template project's version is 4.0.0-dev. So I have modified some code and tried to build it. And I am getting this error when I build the substrate project.

error[E0432]: unresolved imports node_template_runtime::AuthorityDiscoveryConfig, node_template_runtime::SessionKeys --> node/src/chain_spec.rs:5:2 | 5 | AuthorityDiscoveryConfig, | ^^^^^^^^^^^^^^^^^^^^^^^^ no AuthorityDiscoveryConfig in the root

How can I solve this problem? Please help me. Best Regards.
