### ISSUE TITLE
Tip division should be configurable

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#4363]
Block producers should get 100% of the tip, but [currently](https://github.com/paritytech/substrate/blob/09917a50941922c3eb226acf93461b1ac5bb9fc9/frame/transaction-payment/src/lib.rs#L175) the tip gets included with the other pre-dispatch fees (base fee, byte fee, weight fee).

> The transaction fee is considered a base price. There will be a different field in the transaction called tip, and a user is free to put any amount of tokens in it or leave it at zero. Block producers receive 100% of the tip on top of the standard 20% of the fee, so they have an incentive to include transactions with large tips.

Source: https://research.web3.foundation/en/latest/polkadot/Token%20Economics.html#-2.-slow-adjusting-mechanism

**Note:** The W3F Research page may be out of date. Verify with research team that they still want this behavior.

Ideally, the tip division is configurable in the runtime. For example, one could decide that for normal fees, 20% go to the author and 80% to the Treasury, while for tips the split is 50/50.

CC @thiolliere

**Comment by thiolliere** [comment]
if somebody wants to do it before the freeze I don't have enough time to get it, one can take a look at my PR, or do another way. I'll unassigned for now.

(note that it might look that I unassigned too late but the PR was there for a long time and I learned about the freeze just a few days ago back from days off).
