### ISSUE TITLE
Update Frame Pallets to use `decl_error!`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#4365]
Since https://github.com/paritytech/substrate/pull/3433 has been merged in, we have had the ability to create really nice error experiences for users using Substrate Pallets.

We just need to migrate existing errors into this new format.

I expect, since this will change a bunch of modules, we will do this in a few steps. This issue will track the progress:

- [x] assets
- [x] aura
- [x] authority-discovery
- [x] authorship
- [x] babe
- [x] balances
- [x] collective
- [x] contracts
- [x] democracy
- [x] elections
- [x] elections-phragmen
- [x] evm
- [x] example
- [x] executive
- [x] finality-tracker
- [x] generic-asset
- [x] grandpa
- [x] identity
- [x] im-online
- [x] indices
- [x] membership
- [x] metadata
- [x] nicks
- [x] offences
- [x] randomness-collective-flip
- [x] scored-pool
- [x] session
- [x] society
- [x] staking
- [x] sudo
- [x] support
- [x] system
- [x] timestamp
- [x] transaction-payment
- [x] treasury
- [x] utility

**Comment by shawntabrizi** [comment]
Sudo: https://github.com/paritytech/substrate/pull/4369

**Comment by DarkEld3r** [comment]
Treasury: #4370.

As far as I can see, there are no custom errors in `utility`.

**Comment by DarkEld3r** [comment]
Stacking: #4387.

**Comment by shawntabrizi** [comment]
Balances: https://github.com/paritytech/substrate/pull/4405
