### ISSUE TITLE
Use secure websockets (wss://)

### ISSUE THREAD

**Issue by expenses** [paritytech/substrate#4380]
Light clients in the browser need to connect to other nodes via websockets. Unfortunately, [you can't use an insecure websocket on a secure (https://) page](https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox). To fix this, we should use secure websocket connections, and supply a security certificate. This default cert should be overridable. This will mostly require changes to jsonrpc/jsonrpsee.

**Comment by tomaka** [comment]
The certificate needs to be good enough for a browser to accept connecting to it. Which means that every single full node would need to register a domain name and asks a certificate from a registrar.
That doesn't look very realistic to me.

**Comment by tomusdrw** [comment]
Yeah, we were considering that in the past as well, but to be honest it's much easier (and safer) to just document how to set up a reverse proxy that terminates ssl in front of the node than to implement it with all needed details.

**Comment by expenses** [comment]
Closing because this probably isn't achievable.
