### ISSUE TITLE
Additional event-attribute balances.ReapedAccount

### ISSUE THREAD

**Issue by emielvanderhoek** [paritytech/substrate#4382]
This is a request to add an additional attribute to the `balances`.`ReapedAccount`-event.
Currently only the account identifier is included as (first) event attribute (example: https://polkascan.io/pre/kusama-cc3/event/9618-9).

I'd like to have an additional (second) attribute with a `Balance` type that explicitly shows the amount that is burnt on reaping the account.

The context of this change is Polkascan's accounting project which allows us (and others) to have a complete accounting of the native token economy without querying account balances. In this particular case there is no way to identify the exact amount that is lost. It is a value greater than 0 and less than the existential deposit. The second event-attribute solves this.

**Comment by emielvanderhoek** [comment]
For the example event above the value of the second attribute should be: 900000000

**Comment by shawntabrizi** [comment]
@emielvanderhoek Adding `dust` amount to the event is very simple, however it will not solve the problem I think you want to solve.

The `ReapedAccount` event will only fire when both the `free_balance` and the `reserve_balance` of an account is zero.

These two balances hit zero whenever they fall below the existential deposit. However, one of the balances can be "dropped to zero" while the other balance is still above the existential deposit. This means there would be a burn of account funds, but no event emitted which you can use to track.

The solution here would be to introduce another event whenever funds are burned in general, which could be done, but this has some non-zero overhead. Would want @gavofyork to chime in to say if this is a feature we should support.

**Comment by gavofyork** [comment]
Easier is simply to move funds from free <-> reserved if one is above ED and the other below.

**Comment by shawntabrizi** [comment]
@emielvanderhoek another follow up I need to do here is emit an event when the `sudo` calls `set_balance`.

**Comment by emielvanderhoek** [comment]
`set_balance` (sudo) example related to this (https://github.com/paritytech/polkadot/issues/692) issue perhaps. Looks like it mints out of thin air. In this case it is the treasury account:

**Comment by emielvanderhoek** [comment]
I'll follow-up on your questions after the weekend.

**Comment by emielvanderhoek** [comment]
@shawntabrizi thank you this helps immensely. I expect to be able to deal with the other examples you mention in https://github.com/paritytech/substrate/pull/4389
