### ISSUE TITLE
Improved Pallet Error Tracing

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#4385]
This is a rough outline of a proposed improvement to overall error tracing available for FRAME Pallets.

## Issue

There are limitations of the current Pallet error system in Substrate. We assume that runtime errors can only be a single error from a single module. Furthermore, we do not support passing of errors from one module to another in a clean and accurate way. See #4384 

However, interactions between modules can be complex, and ideally a good error system would be able to accurately represent complex interactions between these modules and output verbose information to external user interfaces.

## Goal

The goal of this proposal is to have the following:
* A simple, backwards compatible runtime development API for errors.
* Verbose and accurate multi-module errors and tracing.
* Opt-in complexity, default simplicity.

## Proposed Solution

Imagine a user triggers the following:

* They call a custom module
* This calls the staking module to increase stake
* This calls the balance module to reserve more balance.

The user does not have enough free balance to ultimately do the reserve, and as a result the whole stack of calls will fail.

Let's first assume that our ideal error could contain information about an error which propagates through multiple modules, each with their own optional custom messaging.

An error trace might look like this:

```
Errors:
* Balance Module returns error `NotEnoughFreeBalance`
* Staking Module returns error `CouldNotIncreaseStake`
* Custom Module returns error `CouldNotCompleteTask`
```

In this case, we are able to see the full suite of errors starting from the Balances module where the call initial failed, but also custom error messages for each module about what happened.

In terms of Rust, a Vec is able to contain this information:

```
// First item is a Module unique identifier
// Second item is the error unique identifier in the Enum
type Error = (u8, u8);
type Result = Result<(), Err(Vec<Error>)>;
```

So the overall error would look like:

```
Err[(Error(BalanceId, ErrorId), Error(StakingId, ErrorId), Error(CustomId, ErrorId))]
```

### Runtime Development

When writing code for Pallets, the `Vec<Error>` can grow using a helper function.

Starting at the balances module:

```rust
//balances/lib.rs
ensure!(free_balance >= amount_to_reserve, Error::NotEnoughFreeBalance);
```

From the perspective of the staking module:

```rust
// staking/lib.rs
<balances::Module<T>>::reserve_balance(user, amount).add_error(Error::CouldNotIncreaseStake)?;
```

And from the custom module:

```rust
// custom/lib.rs
<staking::Module<T>>::increase_stake(user, amount).add_error(Error::CouldNotCompleteTask)?;
```

You can see that each module can choose to add an additional error onto the vec of errors, ultimately creating this verbose error object.

A module could also choose not to `add_error`, and just propagate the error up. For example, if the staking module did not want to add any error, they could simply write:

```rust
// staking/lib.rs
<balances::Module<T>>::reserve_balance(user, amount)?;
```

And if the rest of the code is the same, the final object would look like:

```rust
Err[(Error(BalanceId, ErrorId), Error(CustomId, ErrorId))]
```

Ideally this would enable full backwards compatibility with how we write runtime modules today.

## Implementation Details

I really have no idea about implementation details, but would love feedback to understand if this is possible and wanted.

**Comment by xlc** [comment]
While I agree this is very useful for development purpose, I am not sure if the overhead worth it. On the other hand, it can be part of #2082 and it shouldn't be hard to add / modify some macros to auto generate some stack trace for diagnostic build.

**Comment by shawntabrizi** [comment]
@xlc to me this is not really a "debugging/diagnostics" thing. This is all about being able to simply plug runtime module into one another and use them fluidly.

For example, we can assume many people will build off of the `pallet_balances` module, and will do a bunch of unique things using our balance system. No matter what functionality they write, we have a set of standards around `pallet_balances` like the errors it emits, and what it means to the outside world.

In the world we live in now, 100% of the time, if you use `pallet_balances` and it returns an error, you will need to "wrap" or "change" or "stringify" that error, and ultimately lose all of the metadata about what that error ultimately provides.

What I hope this would bring is the fact that you can write whatever encompassing logic you want around other modules, and still be able to propagate useful, module specific, error messages out to your front-end experiences, ultimately informing the user what the correct problem is, and allowing UIs to reuse standards when presenting errors to the user.

**Comment by bkchr** [comment]
So, I'm 100% for improving the error handling. However I'm not really for stacking errors, from user perspective that would be really cool, but we should not forget that the error is stored in the state of the block.

**Comment by shawntabrizi** [comment]
@bkchr Part of my goals is that it would be optional and opt in.

> this could maybe lead to some sort of foot gun.

Is that still an issue in this case?

Also we are talking about a Vec of (u8, u8). Seems... relatively small even in extreme cases right?

**Comment by xlc** [comment]
I can total see in extreme cases it can generate some huge data.
This is basically a stack trace on exception / error and on recursive code, the stack can be very deep and most of the stacks are not useful.

```
fn foo(val: u32) -> Result {
    if val > 10000 { return Ok(()) }
    return foo(val + 1).add_error(Error:SomeError);
}
```

**Comment by xlc** [comment]
Eventually we will want to have complete error trace but I don't think it is required to be part of the runtime / onchain state.
The error code stored onchain can be just few bytes with limited information. To get more information just need to replay the block with some diagnostic flag (using #2082).

Then polkascan or alike services can run with this diagnostic mode by default to index more details whereas other full node / validators can just run the standard runtime without the overhead of additional error details.

**Comment by shawntabrizi** [comment]
@xlc I agree with you. I guess all you really need in terms of UI is to know exactly where the error came from (original module, original error), and the rest of the trace is something to be investigated off-chain.

So this issue is too much, but there is some change needed to even bring this minimum functionality to our error system.
