### ISSUE TITLE
Failed to submit extrinsic: Extrinsic verification error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: GenericAsset.0"))

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/substrate#4386]
when i use the module "generic-asset", the function that  i create it can run successfully, but other functions can't run and show "Failed to submit extrinsic: Extrinsic verification error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: GenericAsset.0"))". why?
![没有升级？](https://user-images.githubusercontent.com/45120344/70719975-ec18bf00-1d2d-11ea-842d-2badd91b725f.png)

**Comment by wjy19990622** [comment]
there are my code:

in lib.rs :1234: 
 
`impl generic_asset::Trait for Runtime {
	type Event = Event;
	type Balance = Balance;
	type AssetId = u32;
}`
`GenericAsset: generic_asset::{Module, Call, Storage, Event<T>, Config<T>},`


in chain-spec.json:
`let assetid: Vec<u32> = vec![1,2,3,4,5].into();`

`generic_asset: Some(GenericAssetConfig{
			endowed_accounts: endowed_accounts.iter().cloned().collect::<Vec<_>>(),
			initial_balance: 1000*100000*MILLICENTS,
			assets: assetid,  // 已经解决
			next_asset_id: 6u32,
			spending_asset_id:1u32,
			staking_asset_id: 4u32,

		}),`

**Comment by shawntabrizi** [comment]
@wjy19990622 what version of the Substrate node are you using here?

**Comment by wjy19990622** [comment]
> @wjy19990622 what version of the Substrate node are you using here?
> 
> `substrate --version` or equivalent.

substrate 2.0.0-8cb06da98-x86_64-linux-gnu

**Comment by wjy19990622** [comment]
> > @wjy19990622 what version of the Substrate node are you using here?
> > `substrate --version` or equivalent.
> 
> substrate 2.0.0-8cb06da98-x86_64-linux-gnu

command:
 ./target/debug/substrate  --version

**Comment by wjy19990622** [comment]
> > > @wjy19990622 what version of the Substrate node are you using here?
> > > `substrate --version` or equivalent.
> > 
> > 
> > substrate 2.0.0-8cb06da98-x86_64-linux-gnu
> 
> command:
> ./target/debug/substrate --version



> > > @wjy19990622 what version of the Substrate node are you using here?
> > > `substrate --version` or equivalent.
> > 
> > 
> > substrate 2.0.0-8cb06da98-x86_64-linux-gnu
> 
> command:
> ./target/debug/substrate --version

i use the command: cargo build , WASM_BUILD_TYPE=release cargo run  purge-chain  --dev -y, WASM_BUILD_TYPE=release cargo run -- --dev.

and change the Version for example 'authoring_version: 11'，'spec_version: 200', 'impl_version: 200'.

but it didn't work.

**Comment by bkchr** [comment]
Did you purged your db?

**Comment by wjy19990622** [comment]
> Did you purged your db?

yes， when i run the code, i use the command "WASM_BUILD_TYPE=release cargo run purge-chain --dev -y" allways.

**Comment by bkchr** [comment]
You still having the problem? Do you have a link to your project to try it locally?

**Comment by kuronyago** [comment]
I have the same problem

node-template 2.0.0-8b6fe66-x86_64-macos

https://github.com/kuronyago/substrate-assets

**Comment by kianenigma** [comment]
cc @xlc

**Comment by xlc** [comment]
A quick look it seems like mismatch codec issue

https://github.com/paritytech/substrate/blob/bd540a67464ccfd24e0fec9081171dab7857183e/frame/generic-asset/src/lib.rs#L211

https://github.com/polkadot-js/api/blob/fc4cbb608ce4076e9a2c51f3c060448045035951/packages/types/src/interfaces/genericAsset/definitions.ts#L8

**Comment by xlc** [comment]
Add this to polkadot apps Settings -> Developers temporary workaround the issue.
```
{
  "AssetOptions": {
    "initalIssuance": "Compact<Balance>",
    "permissions": "PermissionLatest"
  }
}
```
