### ISSUE TITLE
Sync stopped

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4398]
I've been running polkadot with just a single peer connection, in part to uncover these bugs.

Full trace (`-l sync=trace`) attached.

[synctrace-dead-1.txt](https://github.com/paritytech/substrate/files/3966060/synctrace-dead-1.txt)

Related #4367

**Comment by gavofyork** [comment]
@arkpar one to look into.

**Comment by arkpar** [comment]
Here it looks like GRANDPA service issues a lot of explicit fork sync requests that interfere with normal sync. The fix would be to prioritize normal sync over downloading old forks.
