### ISSUE TITLE
`ReapedAcccount` event is spammed when multiple transactions are placed in the same block

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#4402]
Take a look at Kusama CC-3 Block here:
https://polkadot.js.org/apps/#/explorer/query/0x3cf167740da9aac3559a95247cb015d2324fd259e9a12da570a8b782bca04909

In this block, a user submits multiple transactions which transfers their full balance. All but the first transaction failed (good).

However, you can see that the `ReapedAccount` event was emitted multiple times, when it should only really be emitted once here.

We should improve this.

**Comment by dud1337** [comment]
After discussion with @laboon, this issue appears to be related to a negative "Active Accounts" integer on https://polkascan.io/pre/kusama-cc3

![undead_active](https://user-images.githubusercontent.com/5631021/72347470-95115b80-36d8-11ea-8163-e85fa704d7ce.png)

**Comment by shawntabrizi** [comment]
@dud1337 indeed, that along with the fact that Kusama had zero fees for a while, so any account with zero nonce and zero value could submit a transaction and that would also trigger the `ReapedAccount` event.

Not sure if there is a good solution to this for situations where there are no fees.
