### ISSUE TITLE
Introduce general BadOrigin runtime error

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4409]
Right now module use various ways for reporting bad origins, even though the origin recognition APIs are all reusable library code. Some report a `&str` (of various content), others report a local `BadOrigin`-like error type.

Instead, there should be a single `BadOrigin` error (e.g. defined in `frame_system`) that all `ensure_origin`/`try_origin`/`ensure_root`/`ensure_nobody`/`ensure_signed` functions and their ilk use. If modules want to customise the error to something local, then they can with `map_err`, but a simple `ensure_root(origin)?` should Just Work.

**Comment by gavofyork** [comment]
@DarkEld3r maybe one for you?

**Comment by shawntabrizi** [comment]
Related: https://github.com/paritytech/substrate/issues/4365
