### ISSUE TITLE
Fix inflation calculation to account for total stake

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#4411]
Currently ([source](https://github.com/paritytech/substrate/blob/40b1e530870cd5c1803fdd39b6386dcaa6a770fb/frame/staking/src/lib.rs#L1341L1350)), the staking rewards calculation calculates the total amount at stake by multiplying the `SlotStake` - the stake of the minimally staked validator - by the number of validators.

The actual amount at stake - if we consider any funds liable to be slashed as "at stake" - then the number of tokens at stake is higher since most validators will have more than the slot stake.

The calculation should find the sum of the amount at stake (sum of `exposure.total` from [`Stakers`](https://github.com/paritytech/substrate/blob/40b1e530870cd5c1803fdd39b6386dcaa6a770fb/frame/staking/src/lib.rs#L672)) and pass that to the payout function.

Related: https://github.com/paritytech/substrate/issues/4407

```
let validator_len: BalanceOf<T> = (validators.len() as u32).into();
let total_rewarded_stake = Self::slot_stake() * validator_len;

let (total_payout, max_payout) = inflation::compute_total_payout(
	&T::RewardCurve::get(),
	total_rewarded_stake.clone(),
	T::Currency::total_issuance(),
	// Duration of era; more than u64::MAX is rewarded as u64::MAX.
	era_duration.saturated_into::<u64>(),
);
```

**Comment by joepetrowski** [comment]
After talking with @rphmeier, we may just want to use the median amount at stake instead of the sum. Either way, we should not use the minimum as it may be highly variable era-to-era.

**Comment by rphmeier** [comment]
The research.web3.foundation site should describe this, if it doesn't already. Least-staked is OK, but bottom-tercile is probably the ideal metric

**Comment by thiolliere** [comment]
This was fixed in lazy payouts PR
