### ISSUE TITLE
Merge subkey functionality into general cli

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#4416]
Subkey is a secondary binary we ship that allows to generate keys and create transactions for substrate-node. It's main purpose at the time of creation was to provide a small binary for substrate-node. Unfortunately, because of the way it is designed, it can only be reused for non-substrate-node-chains within constraints of using the same primitives (namely keys). This is unfortunate.

Instead, it would be better to generalise the code base and merge the main features into `sc-cli` for general reuse. A secondary cli-template could be provided in the node-template to have it create a dedicated $WHATEVER-subkey binary still, but also to have all the commands directly available in the main cli. 

This mostly requires rust experience. I am happy to mentor on this task.

**Comment by bkchr** [comment]
So, I like the `secondary` cli-template approach :+1: But I don't understand why we should have all the subkey subcommands be part of the main cli. This makes the CLI really weird. Why do you need "vanity address generation" or "signature verification" be part of the main cli?

**Comment by NikVolf** [comment]
fwiw I'd like `substrate key generate ...` (instead of `substrate generate-key` or even worse, `substrate generate`)

**Comment by seunlanlege** [comment]
> What I don't like, having all these sub commands that are not really related to running a node.

moving the discussion here, the cli provides other utilities like exporting blocks, etc. and so  "vanity address generation" or "signature verification" IMO fall under the same idea of "utilities"

**Comment by bkchr** [comment]
I also would go with @NikVolf proposal to have a sub-subcommand.

While these are also utility commands, they are not really related to a node. Stuff like inserting the key unsing the rpc is also not that useful when being integrated directly with the node.

**Comment by bkchr** [comment]
Maybe we should not blow up the cli that much and just provide the template.

**Comment by seunlanlege** [comment]
> fwiw I'd like substrate key generate ... (instead of substrate generate-key or even worse, substrate generate)

with this in mind, any suggestions for the `generate-node-key` command?

**Comment by seunlanlege** [comment]
ping @NikVolf

**Comment by NikVolf** [comment]
@seunlanlege why not `substrate key generate-node-id` ?

**Comment by gnunicorn** [comment]
closed via #4954
