### ISSUE TITLE
Allow OffchainWorker Local Storage (DB) set/get over RPC.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#4420]
The RPC API should pretty much directly reassemble the `sp_io` local storage API.

This will allow setting up some secrets via RPC or even enabling/disabling some workers (requires the worker code to support that obviously).

Also allows investigating the state of the worker on running node.

**Comment by xlc** [comment]
This will also solves #3912

**Comment by xlc** [comment]
Without #2303, this could be a DOS vector as anyone have access to this RPC will be able to insert data to fill the disk of the node.

**Comment by tomusdrw** [comment]
Implemented in #4694
