### ISSUE TITLE
what does system.ExtrinsicFailed mean?

### ISSUE THREAD

**Issue by chaosmw** [paritytech/substrate#4432]
I write a custom module, when I test sending tx with javascript, it always reports the following error, 

{"ApplyExtrinsic":1} :system.ExtrinsicFailed [{"module":8,"error":0},{"weight":10000,"class":0,"paysFee":true}]

No other error info attached,  what does this message mean?  
However, simple transfer extrinsic of module balance works without problem.
Any suggestion would be appreciated.

**Comment by shawntabrizi** [comment]
It means your module function returned `Err` rather than `Ok`. Can you share the code of the function you are calling?

Take a look at your terminal where you are running the node. You may see a more clear error message there.

**Comment by shawntabrizi** [comment]
Please feel free to reopen if there are follow up questions or join our Substrate Technical channel here: https://riot.im/app/#/room/!HzySYSaIhtyWrwiwEV:matrix.org
