### ISSUE TITLE
Document ordering of sp_transaction_pool::TransactionStatus

### ISSUE THREAD

**Issue by geigerzaehler** [paritytech/substrate#4434]
I’m using the `watch_extrinsic` RPC method and would like to know what transaction status changes to expect. For example, is the first item in the stream always either `Ready` or `Invalid`? Does the stream terminate after receiving `Invalid` or `Usurped`?

It would be great if this was documented in the `TransactionStatus` enum and referenced in the `watch_extrinsic` documentation.

**Comment by bkchr** [comment]
CC @tomusdrw
