### ISSUE TITLE
Improve proving code (follow up on #3860)

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#4437]
1. Add typedefs for storage types, to avoid `Vec` :nauseated_face: 
https://github.com/paritytech/substrate/pull/3860#discussion_r356051854

2. Check if we can avoid clones of both keys and values when calculating delta:
https://github.com/paritytech/substrate/pull/3860#discussion_r356052757

**Comment by DarkEld3r** [comment]
I have tried to deal with the second part of this issue several times, but now I'm thinking it isn't worth it. At least not until we are sure that we have a bottleneck there.
