### ISSUE TITLE
Transaction Status should differentiate between InBlock and Finalized.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#4438]
Currently the RPC stream returns `Finalized` event, whenever the transaction is included in block, which obviously is not technically correct.

We should rename current `Finalized` event to `InBlock` and introduce a new event that is triggered by actual finality.

Requested by @jacogr some time ago, but I didn't have time to look at this yet, happy to mentor though and help with the issue.

**Comment by rphmeier** [comment]
> We should rename current Finalized event to InBlock and introduce a new event that is triggered by actual finality.

The chain state doesn't know that well about what's actually finalized

**Comment by tomusdrw** [comment]
Yes I know, but I imagine that it will require another stream of events coming from the consensus protocol about finalised hashes, that can in turn be used by the transaction pool watcher to trigger these events.
It's not going to be trivial, for sure.

**Comment by rphmeier** [comment]
I see, or the API code could correlate this a bit higher-up in the stack, by watching for finality notifications.

**Comment by Sushisource** [comment]
Huge +1 to this. This was deeply confusing to discover that `Finalized` here did not mean what you might reasonably intuitively expect it to mean.

**Comment by tomusdrw** [comment]
CC @jacogr 
We now have events for:
`inBlock`, `retracted` and later for `finalized` or `finalityTimeout`
note that only the latter two will terminate the stream.
