### ISSUE TITLE
Split methods in sc_network::NetworkService into organized traits 

### ISSUE THREAD

**Issue by kigawas** [paritytech/substrate#4450]
Now we are implementing some redundant traits for `NetworkService` to organize logic or simplify unit tests, but I didn't see a criterion for this and everyone implements yet another network trait in their own way.

I suggest we should break the methods in `impl NetworkService` into separate decoupled traits and compose them when necessary.

There are already some prs on this

#4436 
#4439

**Comment by tomaka** [comment]
I'm quite opposed to the general idea of splitting `NetworkService` just for the sake of it. It just makes everything more complicated.
As far as I know, modules that define their own `Network` trait do so precisely because they don't want to be too depend on `sc_network`.

**Comment by altonen** [comment]
I'll close this as complete as the `NetworkService` has been split into organized traits
