### ISSUE TITLE
substrate-client meta-crate

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#4453]
once #4452 is tackled, we can finally look at and discuss how to expose a stable and neat external API for the substrate client.

The generic idea is to have a `substrate-client`-meta-crate (a crate that only re-exports dependents and maybe contains further docs, but no further code). Similarly as libp2p or tokio, feature-switches allow to enable- and disable specific dependent crates and features, some of them specifically marked as unstable. For any version released of the crate, the dependent versions have been shown to work together successfully.

The goal would be to have the `substrate-node-template` dependencies to build the outer client be reduced to the new meta-crate `substrate-client`. It  shouldn't be necessary to depend on any `sc-*` or `sp-*` for a default client any more.  This might differ, if you want to replace any component (database, executor, consensus, etc) or use highly unstable features. This crate would be the one curated, stable exposed API we recommend to use for any runtime development.

**Comment by JoshOrndorff** [comment]
> This might differ, if you want to replace any component (database, executor, consensus, etc) or use highly unstable features.

That being the case, I would like to put considerable thought into what the default is. Or recommend releasing a few such meta-crates. If we release just one then we are making a statement like Aura/Grandpa is the default. I've been wrestling with this in the recipes and recently came to the conclusion that the most generic simple "default" setup is consensus that does _not_ interface with the runtime. https://github.com/substrate-developer-hub/recipes/pull/235

**Comment by shamb0** [comment]
Hello @gnunicorn, If its open, I am interested to pick-it up. 
Can I have some overview to kick off the task.
