### ISSUE TITLE
Change genesis.code encoding in chainspec to bytes.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#4454]
Currently `genesis.code` inside chain spec JSON is encoded as raw `Vec<u8>` which results in a JSON array containing shitload of numbers, which by default when pretty-printed results in one number per line.

Instead we should encode `code` as hex (see `Bytes` wrapper) as it's way more compact, but to maintain backward compatibility we should support both formats when deserializing the chain spec.

CC @JoshOrndorff, I saw that on your seminar and thought that we could fix it :)

**Comment by bkchr** [comment]
Wasn't this fixed by this: https://github.com/paritytech/substrate/pull/4025 ?

**Comment by tomusdrw** [comment]
@bkchr Good point, it's quite possible as that's what the title suggests. Let me confirm that and close that issue if that's the case.

**Comment by tomusdrw** [comment]
Confirming it's already fixed in #4025.
