### ISSUE TITLE
Wasm executor should provide stubs for unknown externs

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#4456]
The wasm executor currently returns an error when it finds an extern for that we don't provide an implementation on the host. Instead of returning an error, the executor should be configurable to provide stubs for functions it does not know. Each stub should return an error when being called, which instructs the executor to stop the execution of the runtime.

- Make the executor configurable on what to do for unknown externs.
- If stub usage is enabled, we should provide the stub and print some `trace!` info about this.

Wasmi integration should be rather trivial. We have the resolver here: https://github.com/paritytech/substrate/blob/master/client/executor/wasmi/src/lib.rs#L280
If stub generation is enabled we should return a fixed index that corresponds to our stub.

Wasmtime maybe requires some more work, but that needs to be tested. Currently we register all the host functions we get here: https://github.com/paritytech/substrate/blob/master/client/executor/wasmtime/src/runtime.rs#L218
As the required extern functions are present in the wasm blob, it should be rather trivial to extract them and provide a stub for each unknown.

I can mentor/help on this.

**Comment by bkchr** [comment]
Already implemented :)

**Comment by cecton** [comment]
@bkchr also for wasmtime??

**Comment by bkchr** [comment]
Yes
