### ISSUE TITLE
Request: New event for block author fees (received)

### ISSUE THREAD

**Issue by emielvanderhoek** [paritytech/substrate#4458]
On Kusama-CC3 some balance changes cannot be accounted for.
On block 12618 a total of 4 `treasury`.`Deposit`-events are triggered with a value of 171969744.
This implies that a total of 687878976 accrues to the treasury.
https://host-01.polkascan.io/pre/kusama-cc3/block/12618#events

It appears that the exact same amount of one of the `treasury`.`Deposit`-events (171969744) goes to the blockAuthor (FQ4cZ1o9Bfq5FTViZM27NRPimh6JfJbYA4dsMS4Lhquj9XK).
I believe this to be the code that explains this behavior: https://github.com/paritytech/substrate/blob/5a8851c4636fdc7a3279c8e870fc54b83b2b1623/bin/node/runtime/src/lib.rs#L97

I propose an additional & new event to be triggered that explicitly states the amount that goes to the blockAuthor. Ideally with two attributes (`author` [AccountId] & `fees` [Balance]).

**Comment by gavofyork** [comment]
No sooner said... https://github.com/paritytech/polkadot/pull/702
