### ISSUE TITLE
Decrease Dht log level from warning to info or debug

### ISSUE THREAD

**Issue by philipstanislaus** [paritytech/substrate#4478]
Every 5 minutes (our session/epoch time), our validators logged warnings like this: 

```WARN sub-authority-discovery Value for hash 'Key(b"\x12 \xde2\x91\x8aVZv\xa7b\x80\xd1ye\x11z)\xbf2\x1aC&*\x83eK\xf0uC\xa5\x03K\xcc")' not found on Dht.```

It seems that these log statements do not have any signifcance – can we decrease the log level for them?

Here's a screenshot from our datadog (last 24 hours, validator was started about 14 hours ago):

<img width="1440" alt="Bildschirmfoto 2019-12-22 um 11 04 03" src="https://user-images.githubusercontent.com/6912756/71320750-201f7d00-24b0-11ea-8406-87b02b34b388.png">

**Comment by bkchr** [comment]
They use Substrate `c6fc2e6240edeb31233b07748c6bf968c7c15553`.

CC @mxinden

**Comment by mxinden** [comment]
> It seems that these log statements do not have any signifcance – can we decrease the log level for them?

They report that the given authority is not putting their addresses on the Kademlia DHT, or that we have data availability issues within the DHT. The former sounds more realistic, given that this feature is still behind a feature flag.

Both `debug` as well as `warn` level sound good to me. Once we have more authorities use the *authority discovery* feature we can probably go back to `warn` level.
