### ISSUE TITLE
Merge cli informant and telemetry

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#4496]
We just do `telemetry!` and it posts both on telemetry endpoints (if any activated) and cherry-picks some data for the cli informant at the same time.

**Comment by bkchr** [comment]
Hmm, why?

**Comment by NikVolf** [comment]
@bkchr just an idea
In the view of
#4209, #830 

and existing cli notifications

As I see it, there will be same data with the same purpose, prepared and posted for two destinations. This can be generalised, maybe not worth the effort though.

**Comment by bkchr** [comment]
In general sounds good, but I think it should be the other way around. We send the telemetry data when we print the informant. 

Filtering the telemetry data sounds false to me. The telemetry is not any structured data. This would require us to parse the data again and print only the stuff we want. I don't see the benefit. Just makes stuff more complicated.

**Comment by NikVolf** [comment]
The benefit is to make informant a sort of poor man telemetry client right in the cli, when you don't have anything else

Then also later you can enrich the informant output in a configurable way, it will just start to catch and show more of the telemetry events.

But I understand that it maybe little benefit, so I will keep this issue to myself and think about it while implementing those mentioned metrics

**Comment by tomaka** [comment]
One important thing to note is that the informant is specific to the CLI. Substrate itself is a library and doesn't necessarily have a CLI. The telemetry, however, is always present. I don't really see why they should be coupled.
