### ISSUE TITLE
Session error about ShouldEndSession

### ISSUE THREAD

**Issue by LusWar** [paritytech/substrate#4500]
I want to add `staking` module in node-template and try not to introduce other modules. When I add the `session` module with reference to node's code, I got the following error. There is no related code for `ShouldEndSession` in AuRa.  I wonder if there is a solution.
```
   Checking sp-session v2.0.0 (https://github.com/paritytech/substrate.git#584d3752)
    Checking sp-finality-grandpa v2.0.0 (https://github.com/paritytech/substrate.git#584d3752)
    Checking pallet-transaction-payment-rpc-runtime-api v2.0.0 (https://github.com/paritytech/substrate.git#584d3752)
    Checking pallet-authorship v2.0.0 (https://github.com/paritytech/substrate.git#584d3752)
    Checking pallet-balances v2.0.0 (https://github.com/paritytech/substrate.git#584d3752)
    Checking pallet-finality-tracker v2.0.0 (https://github.com/paritytech/substrate.git#584d3752)
error: failed to run custom build command for `staking-node-runtime v0.0.1 (/Users/luswar/Projects/substrate-staking/staking-node/runtime)`

Caused by:
  process didn't exit successfully: `/Users/luswar/Projects/substrate-staking/staking-node/target/debug/build/staking-node-runtime-b28e907ba9ff4cb9/build-script-build` (exit code: 1)
--- stdout
Executing build command: "rustup" "run" "nightly" "cargo" "build" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/luswar/Projects/substrate-staking/staking-node/target/debug/wbuild/staking-node-runtime/Cargo.toml"

--- stderr
   Compiling wasm-build-runner-impl v1.0.0 (/Users/luswar/Projects/substrate-staking/staking-node/target/debug/wbuild-runner/staking-node-runtime)
    Finished dev [unoptimized + debuginfo] target(s) in 2.55s
     Running `/Users/luswar/Projects/substrate-staking/staking-node/target/debug/wbuild-runner/staking-node-runtime/target/debug/wasm-build-runner-impl`
   Compiling staking-node-runtime v0.0.1 (/Users/luswar/Projects/substrate-staking/staking-node/runtime)
error[E0277]: the trait bound `pallet_aura::Module<Runtime>: pallet_session::ShouldEndSession<u32>` is not satisfied
   --> /Users/luswar/Projects/substrate-staking/staking-node/runtime/src/lib.rs:190:2
    |
187 | impl pallet_session::Trait for Runtime {
    | -------------------------------------- in this `impl` item
...
190 |     type ShouldEndSession = Aura;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `pallet_session::ShouldEndSession<u32>` is not implemented for `pallet_aura::Module<Runtime>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `staking-node-runtime`.

To learn more, run the command again with --verbose.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by bkchr** [comment]
You can use `frame-staking::PeriodicSession` as type for `ShouldEndSession`.

**Comment by LusWar** [comment]
Thank u，I found `frame-session::PeriodicSessions<Period, Offset>` as type for `ShouldEndSession`. I think it is still difficult for beginners to build a node using the current substrate framework. I want to make a graphical tool to build a usable node for junior developers, just like Ganache for Ethereum. It may also generate the corresponding node code. Do you think this idea can be supported by the foundation?

**Comment by LusWar** [comment]
> You can use `frame-staking::PeriodicSession` as type for `ShouldEndSession`.

Thank u，I found frame-session::PeriodicSessions<Period, Offset> as type for ShouldEndSession. I think it is still difficult for beginners to build a node using the current substrate framework. I want to make a graphical tool to build a usable node for junior developers, just like Ganache for Ethereum. It may also generate the corresponding node code. Do you think this idea can be supported by the foundation?

**Comment by LusWar** [comment]
> You can use `frame-staking::PeriodicSession` as type for `ShouldEndSession`.
Thank u，I found `frame-session::PeriodicSessions<Period, Offset>` as type for `ShouldEndSession`. I think it is still difficult for beginners to build a node using the current substrate framework. I want to make a graphical tool to build a usable node for junior developers, just like Ganache for Ethereum. It may also generate the corresponding node code. Do you think this idea can be supported by the foundation?

**Comment by LusWar** [comment]
> You can use `frame-staking::PeriodicSession` as type for `ShouldEndSession`.

Thank u，I found` frame-session::PeriodicSessions<Period, Offset>` as type for `ShouldEndSession`. I think it is still difficult for beginners to build a node using the current substrate framework. I want to make a graphical tool to build a usable node for junior developers, just like Ganache for Ethereum. It may also generate the corresponding node code. Do you think this idea can be supported by the foundation?

**Comment by LusWar** [comment]
> You can use `frame-staking::PeriodicSession` as type for `ShouldEndSession`.

Thank u，I found `frame-session::PeriodicSessions<Period, Offset>` as type for `ShouldEndSession`. I think it is still difficult for beginners to build a node using the current substrate framework. I want to make a graphical tool to build a usable node for junior developers, just like Ganache.  It may also generate the corresponding node code. Do you think this idea can be supported by the foundation?

**Comment by bkchr** [comment]
I'm the wrong person for these kind of questions. Sorry! I think this is the correct repo to ask questions: https://github.com/w3f/Web3-collaboration

However, we are still working hard on the documentation to make the start easier, but ty for the feedback.
