### ISSUE TITLE
Sandbox api calls not matching io interface

### ISSUE THREAD

**Issue by jaybutera** [paritytech/substrate#4506]
The [Sandbox trait](https://github.com/paritytech/substrate/blob/master/primitives/io/src/lib.rs#L758) in the io crate recently changed from static functions to methods that take a self argument.

The sandbox module which uses the the io Sandbox interface is still calling with static functions [sandbox/without_std.rs#L253](https://github.com/paritytech/substrate/blob/master/primitives/sandbox/without_std.rs#L253).

I'm not that confident this is a problem - I don't fully understand how these pieces fit together. But when I add the `contracts` module as a dependency to a [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template), `sp-sandbox` fails to compile because of a mismatch of the interface mentioned above.

![Screenshot from 2019-12-28 12-17-42](https://user-images.githubusercontent.com/2101658/71539280-4e97cf00-296c-11ea-9799-7068fe17cf5b.png)

**Comment by bkchr** [comment]
Hey, the Sandbox trait is annotated with the attribute #[runtime_interface]. This is a macro and very simplified it generates a static function per method declared in the trait.(the self parameter ja stripped out) 
Could you please give a link to a git repo that contains your code?

**Comment by jaybutera** [comment]
Ok that makes sense, turns out this is just caused by not first running `./scripts/init.sh`.
