### ISSUE TITLE
Network test randomly fails (light_peer_imports_header_from_announce)

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#4507]
Might be only in release mode, see https://gitlab.parity.io/parity/substrate/-/jobs/340546#L1997

**Comment by bkchr** [comment]
Cc @arkpar

**Comment by NikVolf** [comment]
Tried it for some time both in release & debug mode, with no fails.

Seems suspicious!

**Comment by arkpar** [comment]
cc @svyatonik
