### ISSUE TITLE
kvdb-rocksdb overlay cache is not effective

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#4508]
Seems that cache in kvdb itself (memorizing raw key-value pairs on write), despite showing effectiveness in synthetic benchmarks, offers no performance advantage for sync speed, sometimes even negative (anybody can try run polkadot it with `parity-common` replaced from this branch https://github.com/paritytech/parity-common/tree/no-overlay). Not counting increased memory footprint.

This is probably due to:
- There are a higher-level cache-s with good hit ratio.
- RocksDb has its own raw key-value cache, and quite configurable.

Given that, and also the fact that this cache prevents other possible optimisations (such as zero(little)-copy database transactions), we might want to remove it.

There are probably considerations other than sync speed, which would be great to hear about.

**Comment by NikVolf** [comment]
In fact, it is not used at all probably

So I might draft a version of kvdb with no overlay cache + significantly reduced copy of transaction data (now any key and any value _must_ be put into dedicated `Vec<u8>`, and this totally can be avoided)

**Comment by ordian** [comment]
This resolved in https://github.com/paritytech/parity-common/pull/313 I believe.
