### ISSUE TITLE
when use the type Vec\<u8\>  as the map key, it can't remove.

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/substrate#4524]
code:
<OwnerMineRecord<T>>::remove(tx);

OwnerMineRecord is my map, the tx type is Vec\<u8\>. and the error  for example:
'the trait `_::_parity_scale_codec::EncodeLike<REWARD_CURVE::_sp_runtime::sc_application_crypto::Vec<u8>>` is not implemented for `&u8`'

**Comment by wjy19990622** [comment]
> code:
> <OwnerMineRecord>::remove(tx);
> 
> OwnerMineRecord is my map, the tx type is Vec<u8>. and the error for example:
> 'the trait `_::_parity_scale_codec::EncodeLike<REWARD_CURVE::_sp_runtime::sc_application_crypto::Vec<u8>>` is not implemented for `&u8`'

sorry, this is my wrong.  the tx just type 'u8'.

**Comment by bkchr** [comment]
As this seems to be solved, I close the issue?
