### ISSUE TITLE
Pairing engines with native invokes

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#4529]
From the discussion with @burdges, this is very much desired for Polkadot.

Also desired for general substrate audience, as there are already some protocols based on generic pairing engines.

The idea is to support our pairing engine, which offloads heavy operations to the native invokes. Heavy operations would be miller loop, final exponentiation and some curve elementary operations like point adding and multiplication, including those on squared fields.

**Comment by bkchr** [comment]
Hmm, I don't see any difference to the native interface we already provide for runtimes? What would be the difference?

**Comment by NikVolf** [comment]
We will definitely want to use dedicated runtime interface for this, yes.

Basically, what we need is to implement a pairing engine (https://docs.rs/pairing/0.15.0/pairing/trait.Engine.html or similar), which will work through this new runtime interface.

**Comment by burdges** [comment]
It appears SNARK verification only requires exposing [`bellman::groth16::verify_proof`](https://docs.rs/bellman/0.2.0/bellman/groth16/fn.verify_proof.html) and the batched version @swasilyev worked on.  

In practice, you need other curve arithmetic before calling `verify_proof`, but often that occurs on `JubJubEngine` Edwards curve, not a `pairing::Engine` curve.  It'll be faster if this runs native, but maybe not so bad if it runs in WASM.  At least some zcash code around uses `std::io::{Read,Write}` excessively, which presents problems with no_std, btw.

As an example, our ring VRF verifier calls `verify_proof` in https://github.com/w3f/ring-vrf/blob/master/src/verifier.rs and the JubJub [`Point::to_xy`](https://docs.rs/zcash_primitives/0.1.0/zcash_primitives/jubjub/edwards/struct.Point.html#method.to_xy), although I'll change it simplify the circuit by doing more JubJub arithmetic in the verifier for cofactor, etc.

Anything like [ZEXE](https://github.com/scipr-lab/zexe) needs actual pairing arithmetic before calling their `verify_proof`.  I'll note that G2 scalar multiplications cost as much as MIller loops, so at least they should probably be run native.

**Comment by NikVolf** [comment]
Yep need to figure api

1. Polkadot requirements (only groth16 verification?). This might be implemented only in polkadot/cumulus, if not overlapped with (2)

2. What would be best default choice regarding ZNARKs for general audience? I would say ZEXE, but I might be wrong!

**Comment by folsen** [comment]
A few comments.

Unsure of this feature as a whole and whether it's the right direction or not. To bkchr's point, we have a native interface, what are we trying to do that can't be done with the native interface? What API are we trying to add, we all know where we end up if we need to do client changes every time we want to use some specific crypto. If native functions are needed they should be access through a generic API.

That said, benchmarks seem to indicate that if we compile wasm to native for execution (something we have to do for the runtime regardless), the slowdown might not be significant enough to warrant having a bunch of special host functions, especially not for verification which is already reasonably fast.

As for best default choice for SNARKs for a general audience? ZEXE brings a lot of baggage with it and is more than just a proof system, it's a whole way to do private smart contracts, a way that isn't proven in any way and is questionable how one would even program those smart contracts, it's a very different way of thinking about things. The most useful thing would probably be one of the newer constructions that are both recursive and transparent, but those aren't battle-tested. 

Bellman is the only battle-tested and vetted library but it also requires a trusted setup and brings its own challenges with it, and also doesn't have any of the new fancy properties like recursiveness or post-quantum security.

**Comment by burdges** [comment]
I'm not talking about ZEXE specifically but any two layer recursive Groth16 SNARK.  We might need arithmetic on G2 for the inner layer, which gets slow.  Ignore my ZEXE comments for now.

We could expose [`bellman::groth16::verify_proof`](https://docs.rs/bellman/0.2.0/bellman/groth16/fn.verify_proof.html) as is.  We could alternatively expose a general multi-scalar multiplication like https://docs.rs/bellman/0.2.0/src/bellman/groth16/verifier.rs.html#34-36 and a miller loop plus final exponentiation like https://docs.rs/bellman/0.2.0/src/bellman/groth16/verifier.rs.html#46

**Comment by NikVolf** [comment]
> Unsure of this feature as a whole and whether it's the right direction or not. To bkchr's point, we have a native interface, what are we trying to do that can't be done with the native interface? What API are we trying to add, we all know where we end up if we need to do client changes every time we want to use some specific crypto. If native functions are needed they should be access through a generic API.

Yeah sorry for the noise, I didn't mean that we should do it or I'm starting doing it. Just discussed with @burdges and open it to see if there is any interest in generalisation of the problem. ZEXE I believe have some advantages that you can just store records on chain and also wrap user functions (acting on records) in Calls to get private generic module which users can run in whatever fashion they want. I think it is designed very general (I've only read the paper though), but as you say, not battle-tested, so it maybe too early to think about it.

So closing for now, I'll reopen if I have actual idea & there will be some users interested

@burdges We can implement it in cumulus/polkadot separately, ping me if/when you need help with that.
