### ISSUE TITLE
Provide warnings when runtime is built with std dependencies

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#4537]
It is rather hard to figure out is what dependency brought std features to the runtime (and made it fail to compile).

Simple analyzer tool (paring Cargo.toml files and dependency tree?) built in the node template binaries might improve the situation.

**Comment by bkchr** [comment]
Yeah, that is something I have in my mind for quite some time. However, I'm not sure this is Substrate related. IMHO this is more a general rust problem. I will close this issue to keep the issue tracker clean. If you want to work on it, I'm open to speak about it. :)
