### ISSUE TITLE
 export blocks data appears error

### ISSUE THREAD

**Issue by jeremymj** [paritytech/substrate#4538]
use lastest version `6e0a4877afbe2309e106b84333bb70200531b604` code and compile with `cargo build --release` command.Do the following:
``` 
./substrate purge-chain --dev

./substrate --dev （./substrate --dev --pruning archive）

./substrate export-blocks --dev
```
An error message appears:
```
2020-01-06 19:58:58 DB path: /home/jeremy/.local/share/substrate/chains/dev/db
Error: Service(Client(Msg("State database error: Expected pruning mode: archive")))
```

**Comment by bkchr** [comment]
Hey, thank you for the bug report.

Whoever wants to work on this, I can mentor. This will basically just require to support the `--pruning` flag for `export-blocks`. We probably also need to support `--pruning` for `import-blocks` as well.

**Comment by jeremymj** [comment]
OK, when I finish the urgent task at hand, if it hasn't been solved, I can try it.

**Comment by ashutoshvarma** [comment]
> This will basically just require to support the --pruning flag for export-blocks. We probably also need to support --pruning for import-blocks as well.

@bkchr As you suggested, I was trying to add the pruning flag (`PruningParams`) in `export-blocks` (`ExportBlocksCmd`) but looks like it is already supported.
https://github.com/paritytech/substrate/blob/3c1c49e8317abfedaede198ef4aed8173eb23ef0/client/cli/src/commands/export_blocks_cmd.rs#L63-L65

```
./target/release/substrate export-blocks --dev --pruning archive
```
the command runs without any errors

Has the codebase changed since then? Am I missing something?

**Comment by bkchr** [comment]
Maybe it was already supported back then. I probably not checked the code before posting.

**Comment by ashutoshvarma** [comment]
I tried looking around in `src/cli` but couldn't find anything meaningful (maybe I miss something). I am not yet familiar with the codebase, @bkchr If it's not much trouble could you point me where should I start looking for this.
Thanks 

Also, building/rebuilding codebase (especially node-* crates) took almost all the RAM around 15GB in my 16GB machine. Is it normal?
Rust toolchain: latest nightly

**Comment by bkchr** [comment]
You already said it works? So, nothing needs to be changed?

**Comment by ashutoshvarma** [comment]
Looks like I didn't make myself clear.

```
​./target/release/substrate export-blocks --dev --pruning archive
````
This works, but
```
​./target/release/substrate export-blocks --dev
```
This still fails with same error in issue description.

I don't think adding '--pruning archive' always is intended (?). Even if it is then error message should be more explanatory.

**Comment by bkchr** [comment]
This is completely fine. Pruning is required when running a validator node and thus you need to specify this for the export command. As there is nothing that needs to be done here. I will close this issue.
