### ISSUE TITLE
pallet_aura docs still refer to frame_consensus

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#4574]
The module documentation for `pallet_aura` ([rendered here](https://substrate.dev/rustdocs/master/pallet_aura/index.html)) links to `frame_consensus` which I believe has been removed for quite a while.

Perhaps the line should just be removed, or maybe the link should be pointed at `pallet_babe` instead.

**Comment by bkchr** [comment]
There are other occurrences of `frame_consensus` in the other pallets. These need to be removed as well.
