### ISSUE TITLE
The identity module use "Sudo" prefix incorrectly

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#4591]
the prefix used by identity is "Sudo"

https://github.com/paritytech/substrate/blob/ae9c6eac90606c7e612df52d37e89ff1e6d9203b/frame/identity/src/lib.rs#L379

this is probably not intented and might leads to collision with sudo module, however fixing it require migrating Kusama identity module.

**Comment by kianenigma** [comment]
Yeah; I saw this while scraping some data a while back and I hoped it was intentional in some way? I forgot to ask but I could see the author actually wanting to place them under the same tree path for some optimisation reasons?

**Comment by bkchr** [comment]
We can not use `ModuleToIndex` for this, as it would break in the moment you insert a module in between. However, we probably could support this in construct runtime (by just taking the name that the user chooses), but this is a really huge change and requires a storage upgrade. So, nothing that will come in the near future.
