### ISSUE TITLE
Document, clean and stabilise phragmen's behavior with dupe candiadtes and voters.

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#4593]
Both staking and elections _should_ not allow duplicate candidates, but still, it happened https://github.com/paritytech/substrate/pull/4592. A simple fix should make sure that phragmen is internally also dealing with this, in the proper way. Currently, out of luck, the dupes are being ignored, but it should be done in a more mature manner.

**Comment by shawntabrizi** [comment]
@kianenigma lets do this together this week

**Comment by kianenigma** [comment]
More precisely: 

- dupe candidate
- dupe voter
- dupe target

**Comment by kianenigma** [comment]
I have found a bug related to this: using offline-phragmen, I realized that this assertion in the reduce code is failing, only in polkadot at the moment: 

https://github.com/paritytech/substrate/blob/252b146b43e3877aefae6afd5c9a9e6093c5d7a9/primitives/npos-elections/src/reduce.rs#L172

Which means: 

Someone submitted a duplicate vote, and it somehow made its way into the reduce code. After tweaking the error message, I find this dude: 

![Screenshot 2020-07-20 at 17 35 27](https://user-images.githubusercontent.com/5588131/87956789-ba2fbe00-caaf-11ea-9121-29dc83220de0.png)


Surprising is that it seems like seq-phragmen elected both of the duplicate edges. This should have not happened, and needs investigating. 

![Screenshot 2020-07-20 at 17 38 32](https://user-images.githubusercontent.com/5588131/87956877-d6cbf600-caaf-11ea-9f73-fd3e7e7e3495.png)

**Comment by kianenigma** [comment]
More evidence: 

```
#17 --> NO_IDENT [8889bb12ffc22c93e6190aeac259184d7181bed3f0cc9938d27315f8e61c8c4a (1462Rm6Z...)] [total backing = 16934,734DOT (16,934,734,626,230,101) (4 voters)] [own backing = 0,010DOT (10,000,000,000)]
  Voters:
    #1 [amount = 6720,128DOT (6,720,128,027,299,203)] 75d7a967cb385d6f867d150f0727d9cba858c65d192530b44298a06c9bfdea9c (13fWfiEQ...)
    #2 [amount = 0,000DOT (42,560,803)] 75d7a967cb385d6f867d150f0727d9cba858c65d192530b44298a06c9bfdea9c (13fWfiEQ...)
    #3 [amount = 10214,596DOT (10,214,596,556,370,095)] aa6908fa06b85012d44fc8966d9760fb0b0fd9282be9f239927a0089e29e94c8 (14rSLrbz...)
    *#4 [amount = 0,010DOT (10,000,000,000)] 8889bb12ffc22c93e6190aeac259184d7181bed3f0cc9938d27315f8e61c8c4a (1462Rm6Z...)

```

**Comment by kianenigma** [comment]
Albeit, on chain this seems to be fine: 

![Screenshot 2020-07-20 at 17 41 06](https://user-images.githubusercontent.com/5588131/87957162-388c6000-cab0-11ea-95da-62860ab23576.png)

**Comment by kianenigma** [comment]
As an additional part of this, Both staking and elections-phragmen should ensure that the votes submitted by the voter are all unique, rather than relying on the underlying election crate to filter it out for them.

**Comment by coriolinus** [comment]
One random note unrelated to this PR per se: this pallet had quite a bad rap for not having a well defined behaviour with duplicate votes and candidates and targets etc. Now, finally, everything that goes through `setup_input` (called prior to `seq_phragmen` and `phragmms`) gets sanitized. Would be good to ensure these functions have the same standard.

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/pull/8236#discussion_r594335953_
