### ISSUE TITLE
wasmtime implementation violates aliasing requirements

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#4599]
When wasmtime handles a call to host functions it uses a mutable pointer to the contents of `FunctionExecutorState` and linear memory. The problem arises when using the sandbox wasmtime reenters into the host handling routines and obtains the mutable reference to the same items again.

**Comment by DemiMarie-parity** [comment]
1. This is a wasmtime bug, unless we have `unsafe` somewhere.
2. Until we have suitable OS-level sandboxing, we should stick with wasmi for the sandbox for security reasons.

**Comment by pepyakin** [comment]
1. Yeah, there is a lot of unsafe used. Not always with a good reason, IMO. This is (as well as this issue) should be addressed with #4686.
2. I think this is not relevant: The issue is still present even though we that wasmi is being used for sandbox. It just the implementation of the wasmtime executor backend spawns this issue.
