### ISSUE TITLE
Default keys to something enumerable

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4610]
Right now, we default to using Blake2-256 for maps and double-maps. This guarantees security but comes at a cost of being unable to enumerate the keys (we can enumerate the values but only the hashes of the keys).

We should replace this default with Blake2-128-Concat. This provides 128-bits of security against trie-unbalancing attacks which should be just as secure as Blake2-256 since we were never going to be worrying about all 256 bits being equal, while at the same time, is secure against birthday attacks as it concatenates the preimage and also (for the same reason) includes the key.

First PR (pre-2.0):
- Alter the pallets that are relying on defaults to explicitly specify Blake2-256 hasher.
- Change the default to Blake2-128-Concat

Second PR (post-2.0)
- Prepare migration code to allow Blake2-256-based maps to be translated to Blake-128-Concat. This will be a multi-phase migration where initially the key preimages of the origin Blake2-256 map are injected, then later (in an initialize_block, along with an upgrade) they are moved wholesale into the Blake2-128-Concat map and the original map destroyed.

**Comment by bkchr** [comment]
Why not provide some new parameter to a decl storage line that stores the key with the value in a tuple? For the user it would make no difference, up to the point where he wants to iterate the keys. We could implement an extra trait, if the new attribute is set.

**Comment by gavofyork** [comment]
that's another way, yeah. in both cases there should be no significant change for the user. this way is slightly more space efficient (fewer bytes stored as it's `16 + len(key) + len(value)` rather than `32 + len(key) + len(value)` and it may be slightly faster since we're only computing a hash of half the size.

**Comment by thiolliere** [comment]
I think it should be better make the transition be removing default hasher and reintroducing later.
Otherwise once this PR is merged, some ppl could merge master without seeing this change no ?

**Comment by thiolliere** [comment]
adding the new default can be done whenever people think it is ready, the change is very similar to the code before the PR that removed the default, you just have to change 2 lines in the parsing in decl_storage

**Comment by bkchr** [comment]
I think we should just stick to no default hasher as it is done now. Being explicit for this is probably better anyway.
