### ISSUE TITLE
Refactor and optimise balances pallet

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#4613]
Balances pallet should be reorganised to optimise typical use-cases:
- Vesting should be split into its own pallet and utilise the locking subsystem. Claiming vested funds should be an explicit call which just reduces the `vesting` lock. This reduces the computation and storage access needed for making withdraw checks.
- Time-limits on locks should be removed as a feature. This allows a `locked_balance` field to be maintained (which is just the max of all the locks). This alone can be consulted when attempting a withdraw avoiding the need to iterate through the locks in for withdraw operations.
- Reserved balance, free balance and locks should be coalesced into a single storage item. Furthermore, there should be an additional member of the item whose type is configured by the config trait. This can be constructed in a similar manner to session keys, allowing other modules to deposit data into the same item. Since use-cases generally require reading various attributes of a single account, amalgamating data concerning an account from many different modules into the same storage item should increase the cache hits and improve performance, provided the size of the storage item's value doesn't get too large. (Ethereum makes this optimisation by combining balance, nonce, storage root and code hash into a single storage item.)

**Comment by xlc** [comment]
We have started working on the vesting module. We are happy to contribute it to FRAME if it is desired.

https://github.com/laminar-protocol/open-runtime-module-library/issues/73
