### ISSUE TITLE
Bonded fund cannot be used for transaction payment but comments said otherwise

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4616]
Previously, bonded fund can be used for transaction payment so it is OK to bond all the funds and still be able to make transaction to unbond them. This is no longer possible after #3606 but the comments still says `The lock will lock the entire funds except paying for further transactions. `

https://github.com/paritytech/substrate/blob/70f1d8d968f374f09b395420901c0926a2d874f7/frame/staking/src/lib.rs#L1272-L1286

With `WithdrawReason::Tip`, it should be safe to allow `TransactionPayment` reason and https://github.com/paritytech/substrate/pull/3364#discussion_r313806640 no longer applies.

**Comment by bkchr** [comment]
CC @kianenigma
