### ISSUE TITLE
(some) node subcommands are broken

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#4623]
...and they fail with `keystore` not being configured. Namely `import-blocks` and `factory` at least.

Also it would be nice to actually write some tests for the sub-commands so that we don't run into that issue in the future.

**Comment by bkchr** [comment]
Part 1 is done and the CLI commands are fixed, now we need some tests.

**Comment by NikVolf** [comment]
Yes @bkchr

**Comment by NikVolf** [comment]
I'll wait until @cecton finishes some refactoring there though
Test would be as silly as fix with current api 🤷‍♀️

**Comment by tomusdrw** [comment]
@NikVolf maybe we could have tests that actually start a CLI? Then it's not really related to the API at all and we would test the CLI parsing in one go.

**Comment by cecton** [comment]
Definitely agree! I made the PR already, I will add some tests tomorrow. #4692

**Comment by cecton** [comment]
Fixing it in #4842

**Comment by gnunicorn** [comment]
is this after the merge of #4842 still open?
