### ISSUE TITLE
two transactions do not fit in one block

### ISSUE THREAD

**Issue by alex-cloudwalk** [paritytech/substrate#4627]
We started our own network from node-template without any changes in the code. Repository commit c6fc2e6. json-file was changed and attached below:
[bn1spec_bal_raw.txt](https://github.com/paritytech/substrate/files/4063811/bn1spec_bal_raw.txt)
At the moment the network can be seen at https://telemetry.polkadot.io/#list/cw_test
When we try to send two transaction simiusly they are not included in the same block, but are added one at a time to each sequential block. We tried to send our transactions from different computers, from different accounts and to different accounts, but still, transactions are included in a different blocks.
We tried it for a quite few times and right now it looks like that only one transaction can be included in the block.
screens:
![photo_2020-01-15_05-43-08](https://user-images.githubusercontent.com/53624542/72418661-047b5f80-375a-11ea-996d-5445d6645b1e.jpg)
![photo_2020-01-15_05-43-02](https://user-images.githubusercontent.com/53624542/72418682-10ffb800-375a-11ea-9fed-f2e7a8bbe63d.jpg)
![photo_2020-01-15_05-43-05](https://user-images.githubusercontent.com/53624542/72418688-13faa880-375a-11ea-9ce0-eef69ba8e31c.jpg)

**Comment by tomusdrw** [comment]
Could you run the validator node with `-lbasic_authorship=trace,txpool=trace` and post the logs here?

**Comment by kianenigma** [comment]
- what are the transactions exactly? 
- Have you changed `MaximumBlockWeight` and `MaximumBlockLen`? Increase them (to maybe the max_value even) and if it is solved it means the weight is preventing it. Though the logs from the pool validation should also tell us what is happening.

**Comment by gitigs** [comment]
- Transactions are simple transfers from one account to another account, nothing special.
- We didn't touch those values, they must be default. But correct me if I'm wrong please, to change .. and .. we should modify it from Rust code?

**Comment by gitigs** [comment]
> * Transactions are simple transfers from one account to another account, nothing special.
> * We didn't touch those values, they must be default. But correct me if I'm wrong please, to change `MaximumBlockWeight` and `MaximumBlockLen` we should modify it from Rust code?

**Comment by gitigs** [comment]
1. Transactions are simple transfers from one account to another account, nothing special.
2. We didn't touch those values, they must be default. But correct me if I'm wrong please, to change `MaximumBlockWeight` and `MaximumBlockLen` we should modify it from Rust code?

**Comment by kianenigma** [comment]
Yup from the rust code in the runtime top file /runtime/src/lib.rs

**Comment by alex-cloudwalk** [comment]
We again sent transactions today with logs turned on. Both transactions were sent on block 204330, one went to block 204331, the second went to 204332.
Logs from the Alice node: https://gist.github.com/alex-cloudwalk/7f77b330f4de8d208972d12be8211957
Logs from the Bob node: https://gist.github.com/alex-cloudwalk/780f051d1534b9708b7026ad2bc2b74e

**Comment by tomusdrw** [comment]
@alex-cloudwalk thanks for the logs, unfortunately due to a mistake on my side the logs do not contain a full info that would be needed, could you please re run with:
`-ltxpool=trace,sc_basic_authority=trace`?
The pool accepts both transactions and they are present in the pool at the same time, so I suspect it's most likely a block weight limit issues as @kianenigma mentioned. The logs would confirm our suspicions.

**Comment by alex-cloudwalk** [comment]
@tomusdrw thanks for the quick response. Here are the logs with `-ltxpool=trace,sc_basic_authority=trace`:
Logs from the Alice node: https://gist.github.com/alex-cloudwalk/52107daae6335f740a4f3be266003a28
Logs from the Bob node: https://gist.github.com/alex-cloudwalk/928bc42e3f4f3c934d3943e67aecd37d

**Comment by tomusdrw** [comment]
Take a look at this line: https://gist.github.com/alex-cloudwalk/928bc42e3f4f3c934d3943e67aecd37d#file-log__bob_validator_029_034-txt-L26
 the block is full already, so it's definitely a weight issue as @kianenigma mentioned.

**Comment by alex-cloudwalk** [comment]
thanks for your help, @tomusdrw and @kianenigma
