### ISSUE TITLE
RPC to fetch all changed storages for a given block

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4638]
I would like to have a RPC to fetch all the changed storages (keys and maybe new values) for a given block. This would allow me easily to index the state changes without subscribe to all the known keys.

**Comment by tomusdrw** [comment]
I thought it should already be possible via `state_queryStorage`, but it seems that it requires a key list:
https://github.com/paritytech/substrate/blob/9cd3a020b62c12b34a40f118efdd7f6eb2ed0e6e/client/rpc-api/src/state/mod.rs#L110-L113

`state_subscribeStorage` allows you to pass `None`, but it doesn't support historical values.

So it seems to be just a limitation of current API and it should be possible to implement. (I suspect that fixing `queryStorage` could require re-executing the block).

**Comment by shaopengw** [comment]
I tried to implement this RPC via change trie, which should be able to provide a list of changed keys for a given block. After setting up change trie config, I can get the change trie root for each block. But when iterating the change trie storage at its root by `TrieBackendEssence` https://github.com/paritytech/substrate/blob/c82a0f7b58c8c3f204cb10d4a03cd4855b236c29/primitives/state-machine/src/trie_backend_essence.rs#L261-L265

strangely there is always no key value pairs. Not sure if this is the proper way to iterate on a change trie storage of a given block.

**Comment by xlc** [comment]
@tomusdrw Is it possible to prioritize this issue or otherwise will you mind to shine some lights on how to implement this?

**Comment by jacogr** [comment]
Couple to this (similar) is a `getKeysPaged` & `queryStorageAt` subscriptable combo. So a big issue with using those two on lists is that it is once-off, so you never known -

- when new keys have been added (per prefix)
- when the values for a key has changed

So rough approx. may be (and this could certainly be done API-side aka non-node side as well, just not as effective) -

- subscribe to all changes
- compare prefix supplied against changes
- return the keys/values for those results

**Comment by xlc** [comment]
@jacogr This is almost what I was experimenting here: https://github.com/open-web3-stack/open-web3.js/pull/90/files#diff-b31c8ce8be287ba13e6f24f59d966fc8R27

I am using `subscribeStorage` to query state changes for new blocks, but it cannot handle disconnection (missed subscriptions), fork (only subscribe for finalized blocks) etc.

The use cases I have for this API are:
- when detect missed blocks, query the state change for missed block.
- subscribe to finalized head, and only query state change for finalized block
-when fork is detected, revert changes for forked block, and re-apply the block in canonical chain

**Comment by xlc** [comment]
bumping...

**Comment by kianenigma** [comment]
+1

**Comment by emielvanderhoek** [comment]
+2

**Comment by bkchr** [comment]
Using `subscribe_storage` with `keys = None` will always give you all the storage changes per block. For the historical use case, we should extend `state_traceBlock` to also be able to return storage changes. Returning keys should probably be enough?

**Comment by xlc** [comment]
Yes with changed keys it is trivial to query new and old values.

**Comment by xlc** [comment]
Closed by https://github.com/paritytech/substrate/pull/9642
