### ISSUE TITLE
trait bound `rand::rngs::thread::ThreadRng: rand_core::CryptoRng` is not satisfied

### ISSUE THREAD

**Issue by stanieltron** [paritytech/substrate#4650]
Hello all, 
C:\rust\substrate-xyk> rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\s\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.42.0-nightly (3291ae339 2020-01-15)

error[E0277]: the trait bound `rand::rngs::thread::ThreadRng: rand_core::CryptoRng` is not satisfied
   --> C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\libp2p-core-0.7.1\src\identity\ed25519.rs:34:44
    |
34  |         Keypair(ed25519::Keypair::generate(&mut rand::thread_rng()))
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::CryptoRng` is not implemented for `rand::rngs::thread::ThreadRng`
    | 
   ::: C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\ed25519-dalek-1.0.0-pre.3\src\ed25519.rs:130:12
    |
130 |         R: CryptoRng + RngCore,
    |            --------- required by this bound in `ed25519_dalek::ed25519::Keypair::generate`
    |
help: trait impl with same name found
   --> C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\rand_core-0.4.2\src\lib.rs:430:1
    |
430 | impl<'a, R: CryptoRng + ?Sized> CryptoRng for &'a mut R {}
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: Perhaps two different versions of crate `rand_core` are being used?

error[E0277]: the trait bound `rand::rngs::thread::ThreadRng: rand_core::RngCore` is not satisfied
   --> C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\libp2p-core-0.7.1\src\identity\ed25519.rs:34:44
    |
34  |         Keypair(ed25519::Keypair::generate(&mut rand::thread_rng()))
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::RngCore` is not implemented for `rand::rngs::thread::ThreadRng`
    | 
   ::: C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\ed25519-dalek-1.0.0-pre.3\src\ed25519.rs:130:24
    |
130 |         R: CryptoRng + RngCore,
    |                        ------- required by this bound in `ed25519_dalek::ed25519::Keypair::generate`
    |
help: trait impl with same name found
   --> C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\rand_core-0.4.2\src\lib.rs:373:1
    |
373 | / impl<'a, R: RngCore + ?Sized> RngCore for &'a mut R {
374 | |     #[inline(always)]
375 | |     fn next_u32(&mut self) -> u32 {
376 | |         (**self).next_u32()
...   |
392 | |     }
393 | | }
    | |_^
    = note: Perhaps two different versions of crate `rand_core` are being used?

error[E0277]: the trait bound `rand::rngs::thread::ThreadRng: rand_core::CryptoRng` is not satisfied
   --> C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\libp2p-core-0.7.1\src\identity\ed25519.rs:141:48
    |
141 |         SecretKey(ed25519::SecretKey::generate(&mut rand::thread_rng()))
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::CryptoRng` is not implemented for `rand::rngs::thread::ThreadRng`
    | 
   ::: C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\ed25519-dalek-1.0.0-pre.3\src\secret.rs:172:12
    |
172 |         T: CryptoRng + RngCore,
    |            --------- required by this bound in `ed25519_dalek::secret::SecretKey::generate`
    |
help: trait impl with same name found
   --> C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\rand_core-0.4.2\src\lib.rs:430:1
    |
430 | impl<'a, R: CryptoRng + ?Sized> CryptoRng for &'a mut R {}
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: Perhaps two different versions of crate `rand_core` are being used?

error[E0277]: the trait bound `rand::rngs::thread::ThreadRng: rand_core::RngCore` is not satisfied
   --> C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\libp2p-core-0.7.1\src\identity\ed25519.rs:141:48
    |
141 |         SecretKey(ed25519::SecretKey::generate(&mut rand::thread_rng()))
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::RngCore` is not implemented for `rand::rngs::thread::ThreadRng`
    | 
   ::: C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\ed25519-dalek-1.0.0-pre.3\src\secret.rs:172:24
    |
172 |         T: CryptoRng + RngCore,
    |                        ------- required by this bound in `ed25519_dalek::secret::SecretKey::generate`
    |
help: trait impl with same name found
   --> C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\rand_core-0.4.2\src\lib.rs:373:1
    |
373 | / impl<'a, R: RngCore + ?Sized> RngCore for &'a mut R {
374 | |     #[inline(always)]
375 | |     fn next_u32(&mut self) -> u32 {
376 | |         (**self).next_u32()
...   |
392 | |     }
393 | | }
    | |_^
    = note: Perhaps two different versions of crate `rand_core` are being used?

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `libp2p-core`.

Any idea whre might be the problem or how to fix it? Thank you

**Comment by bkchr** [comment]
Do you try to compile 1.0 branch?

**Comment by stanieltron** [comment]
yes

**Comment by bkchr** [comment]
Yeah that is not supported anymore, if you want to play with Substrate, please use the master branch.
