### ISSUE TITLE
CLI's version uses static str which prevents formatting

### ISSUE THREAD

**Issue by cecton** [paritytech/substrate#4663]
Original comment about the source of the issue: https://github.com/paritytech/cumulus/pull/42#discussion_r367934842

In this particular case we want to add text in the description that shows how to use the command line to pass parameters to the relay chain and the para chain. To do that it would be best if we know the name of the executable.

Unfortunately Version takes static str so it is not possible to format at runtime.

cc @bkchr

**Comment by bkchr** [comment]
The problem I see is that everyone who implements a collator will need to replicate this piece of code. This should not be required.

**Comment by cecton** [comment]
We could/should use https://doc.rust-lang.org/std/env/fn.current_exe.html

But this is not possible because app_dirs requires &'static str.

I believe we can circumvent this issue by using lazy_static.

**Comment by pscott** [comment]
@cecton Has this issue been addressed? Trying to find the initial code, but github is giving me [this error](https://github.com/paritytech/cumulus/pull/42/files/7dfecb1634876a4c132af25a7da4c67d8e85e52e#diff-2485b6feddda62972bc63aed70f55e5f), and I can't find the code in the current repo... 

It looks like it has been solved here:

https://github.com/paritytech/cumulus/blob/05a83e8bdbcf4c216e8632431aa49dd996ce4c3f/test/parachain/src/command.rs#L46-L51

but I'm not sure at all ^^

**Comment by cecton** [comment]
@pscott the stuff that was blocking to make it work is fixed (app_dirs). So it is now possible to convert all those `&'static str` to String instead AND to use `current_exe` instead of having to specify one.

To summarize:
1. If we convert the `&'static str` to String we can customize the description more easily
2. Having to specify the `executable_name` is a constraint introduced by the `app_dirs` dependency and it is less flexible (and more boilerplate) compared to using the `current_exe()`

You can pick the task if you want. I believe it should go without surprise but you can ping me if you have any issue.
