### ISSUE TITLE
Wasmtime spends too much time growing memory

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#4682]
During the block execution/construction with ~500-600 transactions, about 50% of time is spent on growing memory inside wasmtime.

(this method https://github.com/bytecodealliance/wasmtime/blob/815576edc5ab00da8c6b67916bf7e9f8af1504d2/crates/runtime/src/instance.rs#L632)

**Comment by bkchr** [comment]
And wasmi behaves differently? I assume you test `remark`?

**Comment by NikVolf** [comment]
I am not sure about wasmi, it is much slower anyway.

I tested transfers, but only between several fixed accounts, so should be not much difference than just remark.

**Comment by bkchr** [comment]
By growing memory you mean allocating for something inside the runtime or really for some structures inside `wasmtime`?

**Comment by NikVolf** [comment]
Sorry, I probably gave too little context

https://github.com/bytecodealliance/wasmtime/blob/815576edc5ab00da8c6b67916bf7e9f8af1504d2/crates/runtime/src/instance.rs#L632

Exactly this method takes up to 50% time

**Comment by pepyakin** [comment]
Yeah, thanks for the filling the issue! It is on my radar already.

**Comment by pepyakin** [comment]
I think the issue should be fixed by now.
