### ISSUE TITLE
Remove the workaround that lowers fees for transfering via contracts module

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#4713]
If https://github.com/paritytech/substrate/pull/4147 is merged, then we will have a workaround that will make transfers via contracts module much more cheaper than through balances module.

See [this](https://github.com/paritytech/substrate/pull/4147/files#r368534673)

**Comment by athei** [comment]
What is to be done here after the merge of #5712? Do we need to adjust the `Schedule`?

**Comment by athei** [comment]
AFAIK that workaround never made it in because #4147 was never merged. Instead, #5446 was merged with does not contain such a work around.
