### ISSUE TITLE
Service's Configuration has optional fields that shouldn't be optional

### ISSUE THREAD

**Issue by cecton** [paritytech/substrate#4776]
Following the discussion on: https://github.com/paritytech/substrate/pull/4692/files/bea809d4c14a2ede953227ac885e3b3f9771c548#r372049016

There are 2 conflicting things we would like to have:
 * Running a node requires a Configuration and some of the fields are not optional but they are defined as Option
 * We should be able to define defaults to the Configuration before the command line get parsed. Therefore some of the fields need to be Option

> The idea is to be able to make a Configuration before it being modified by the commandline arguments. For that I need defaults and chain_spec, like some other fields, are Option even though they are required for running a node.

> It's not ideal. I think it would be best to have some kind of intermediate object, one that has the Options that can be converted to one that doesn't have and it would be fail-able at that point.

**Comment by TimvanScherpenzeel** [comment]
I was going to make a new ticket but I think my issue is possible related to this ticket and known.

It is currently not possible to disable the `grafana data source server` by setting the `grafana_port` to `None` as suggested in:

https://github.com/paritytech/substrate/blob/26e37ff685819646633f5246419c03c02df81dff/client/service/src/config.rs#L75-L76

This appears to be because of:

https://github.com/paritytech/substrate/blob/26e37ff685819646633f5246419c03c02df81dff/client/cli/src/lib.rs#L637-L642

The `grafana data source server` should not be a strict requirement to run a node right?

Same goes for `rpc_http` and `rpc_ws` (where setting `None` doesn't actually disable them):

https://github.com/paritytech/substrate/blob/26e37ff685819646633f5246419c03c02df81dff/client/cli/src/lib.rs#L628-L635

**Comment by cecton** [comment]
Is it new? It doesn't look related to my change, the code was there before:

https://github.com/paritytech/substrate/blob/1ed1cc542110aaaee9cf0de87a7c256a1de407c6/client/cli/src/lib.rs#L1072-L1076

**Comment by TimvanScherpenzeel** [comment]
It is not directly related to your latest changes I believe but I thought it might relate to this ticket. If it does not I’ll gladly make a new ticket specifically for the issue that I’m facing.

**Comment by cecton** [comment]
No no I think you're right, it's definitely related to this ticket. I was just afraid I broke something.

The comment really is an indication that it was meant to be an option but clearly it's never None when running a node.

**Comment by cecton** [comment]
@TimvanScherpenzeel actually I'm an idiot. The main reason for this refactoring was to allow more flexibility so you can customize at different places how you run the node. So you CAN actually put those values to None if you want.

In the most common case, you would use the "run" function to run the node:

https://github.com/paritytech/substrate/blob/26e37ff685819646633f5246419c03c02df81dff/bin/node-template/src/command.rs#L32-L38

But what this function does is just initializing and running the node:

https://github.com/paritytech/substrate/blob/26e37ff685819646633f5246419c03c02df81dff/client/cli/src/lib.rs#L229-L249

So what you can do is actually initialized yourself, modify the configuration and then run the node:

```rust
	init(&mut config, spec_factory, &run_cmd.shared_params, version)?;

	config.grafana_port = None;

	run_cmd.run(config, new_light, new_full, version)
```

**Comment by cecton** [comment]
I got a brilliant idea on how to solve this ticket and the implementation is almost exactly like this crate: https://crates.io/crates/optional_struct but also kinda the opposite:
 * instead of derive it would be a proc macros: so we can have the optional struct in sc_cli and not in sc_service (because it doesn't make sense to have it on sc_service)
 * instead of `[struct].apply_options([optional_struct])` it would be a `[optional_struct].into() -> [struct]`
 * instead of defining all the default values of each field in one function, define all the default values of each field in a dedicated function (`fn default_[field]()`). If one function is not declared: fail to compile
 * the `From` (into) implementation would be generated automatically and will use `default_[field]()` for every field that is None

With this implementation we would have:
 * sc_service::Configuration not have Option on fields that are required
 * the compiler will enforce that every field added to sc_service::Configuration will have a default value defined in a function in sc_cli (so sc_cli would fail to compile if we add a field that is not optional and doesn't have a default value)
 * it would avoid mistakes like [here](https://github.com/paritytech/substrate/pull/4981/files#diff-ed4918dd0da951e344e205c78f972484R650) where the value in config is forced without checking if the option is already defined in the config

**Comment by cecton** [comment]
Though this whole thing doesn't make #4842 irrelevant: #4842 adds:
 * tests
 * better clarity (separated modules) 
 * the API is less error prone and prevents issues like [this one](https://github.com/paritytech/polkadot/pull/831/files#diff-aa9e17d15ba39424b200b856a3859a03R77) where the wrong structopt is used to populate the config

**Comment by cecton** [comment]
@bkchr can you check this private repo [here](https://github.com/paritytech/optional-struct-macro/blob/master/examples/basic.rs) and let me know what you think of it?

This is very similar to [optional_struct](https://crates.io/crates/optional_struct) but it does enforce defaults at compile time:

Example build output where a default field is missing its default function:

```
error[E0599]: no function or associated item named `default_field_2` found for type `Test` in the current scope
  --> examples/fail_to_compile.rs:6:1
   |
6  |   optional_struct!(struct Test {
   |   -                ----------- function or associated item `default_field_2` not found for this
   |  _|
   | |
7  | |     field_1: u32,
8  | |     field_2: usize,
9  | |     field_opt: Option<String>,
10 | | }
11 | | );
   | |  ^
   | |  |
   | |  function or associated item not found in `Test`
   | |__help: there is a method with a similar name: `default_field_1`
   |    in this macro invocation
```

**Comment by cecton** [comment]
Mentioning #5204 which shows that the API is still not good.

Note 1: probably enforcing the fields to be required would be prevent this situation where databse and config_dir are not set.

Note 2: optional_struct won't help for this case.
