### ISSUE TITLE
AccountDb is inefficient

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#480]
For collecting changes while executing smart-contracts we use an abstraction called [`AccountDb`](https://github.com/paritytech/polkadot/blob/master/substrate/runtime/contract/src/account_db.rs). 
It lets us collect some changes made to an account db (such as transfers, contract storage modifications, etc) and either commit these changes to the storage or discard them. Furthermore, it is possible to create nested account dbs which changes also can be commited to the parent db or discarded.

The problem with the current implementation of AccountDb is that it is rather inefficient. It uses cascade of hash maps. That is, nested account db is just a hash map with keys as account address and values as account data that collects all performed changes. If some value requested which isn't present in the hash map, a query to the parent account db is performed. It continues until value is found in some parent account db or if the last account db returned there is no such value. If the value is found then it is cached in the current overlay and returned.

With that construction, it is possible to make a very deep transaction that have a long chain of nested account dbs and try to query a large range of keys that lead to such cache misses and cost of which would be proportional to the depth of the transaction stack and not to how much is paid for the gas.

That's unfortunate and AccountDb should have runtime characteristics proportional to how much is paid for the gas.

**Comment by gavofyork** [comment]
Check the ethereum implementation, but I suspect that it's the same there. Fact of the matter is that (even dozens of) cache lookup is faster that a disk-DB lookup and that's what we charge gas price on.

**Comment by arkpar** [comment]
parity-ethereum implementation is more efficient:
https://github.com/paritytech/parity-ethereum/blob/master/ethcore/src/state/mod.rs#L298-L306

**Comment by pepyakin** [comment]
This is the only non linear part of the current smart-contract runtime, as far as I can tell.

**Comment by gavofyork** [comment]
Closed as invalid
