### ISSUE TITLE
author_insertKey always return error with Invalid params: prefix is missing

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4810]
```
$ curl -H 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"author_insertKey", "params":["babe", "0x1111111111111111111111111111111111111111111111111111111111111111", "5DtDLm5rQHShDqojQpsvcN8tRXHVFaecfDoRet1SU6BFD9Fi"],"id":1 }' localhost:9933
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: prefix is missing."},"id":1}
```

Tried different formats, keys, it just doesn't work. Similar command works in a few weeks old version.

`author_rotateKeys` works

**Comment by bkchr** [comment]
You are giving the arguments in the wrong order, first `suri` and than `public_key`.

(As you are giving the `suri` as second parameter, it expects a `0x` that is not present)

**Comment by xlc** [comment]
Sorry I don't get it. Can you provide a working example? Did this change recently?

**Comment by xlc** [comment]
I see, public key is in hex format, not ss58.

`curl -H 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"author_insertKey", "params":["babe", "1111111111111111111111111111111111111111111111111111111111111111", "0x50780547322a1ceba67ea8c552c9bc6c686f8698ac9a8cafab7cd15a1db19859"],"id":1 }' localhost:9933` works

**Comment by bkchr** [comment]
Yeah^^
