### ISSUE TITLE
Align StorageMap interface more with Rust's {Hash,BTree}Map

### ISSUE THREAD

**Issue by apopiak** [paritytech/substrate#4839]
The interface of `StorageMap` mostly keeps to the interface of Rust's `HashMap` and `BTreeMap` except that it renames [`contains_key`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.contains_key) to [`exists`](https://github.com/paritytech/substrate/blob/master/frame/support/src/storage/mod.rs#L129).

I think it would make sense to either rename the function to the Rust name (`contains_key`) or create an alias.

**Comment by bkchr** [comment]
Will you want to do this @apopiak? As discussed in Riot, this should be done in a timely manner. 
I don't think that anyone has any problems with this change.

**Comment by apopiak** [comment]
Yep, will take on.

**Comment by apopiak** [comment]
I'm sorry to do this now instead of earlier, but I noticed another discrepancy:
[`StorageMap::take`](https://substrate.dev/rustdocs/master/frame_support/storage/trait.StorageMap.html#tymethod.take) is called
[`HashMap::remove`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.remove) in the original, while [`StorageMap::remove`](https://substrate.dev/rustdocs/master/frame_support/storage/trait.StorageMap.html#tymethod.remove) doesn't really have an equivalent (you just `remove` and drop the value).
`HashMap::take` does not exist, but `HashMap::drain()::take()` does which could lead to confusion.

**Comment by apopiak** [comment]
Also it's not a huge deal, but you remove a `StorageValue` with `kill` and a `StorageMap` entry with `remove`.

**Comment by bkchr** [comment]
> I'm sorry to do this now instead of earlier, but I noticed another discrepancy:
> [`StorageMap::take`](https://substrate.dev/rustdocs/master/frame_support/storage/trait.StorageMap.html#tymethod.take) is called
> [`HashMap::remove`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.remove) in the original, while [`StorageMap::remove`](https://substrate.dev/rustdocs/master/frame_support/storage/trait.StorageMap.html#tymethod.remove) doesn't really have an equivalent (you just `remove` and drop the value).
> `HashMap::take` does not exist, but `HashMap::drain()::take()` does which could lead to confusion.

I think this is fine, that is just something where we diverge from a default hashmap. 

> Also it's not a huge deal, but you remove a `StorageValue` with `kill` and a `StorageMap` entry with `remove`.

I would expect that `StorageMap::kill` would remove the whole data structure (currently this function is called `remove_all`).

**Comment by apopiak** [comment]
> I think this is fine, that is just something where we diverge from a default hashmap.

ok

> I would expect that `StorageMap::kill` would remove the whole data structure (currently this function is called `remove_all`).

right, makes sense
