### ISSUE TITLE
Omitting `id` in JSON rpc request getting empty response

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4862]
Not sure if this is Substrate or jsonrpc upstream issue, but 

```
 $ curl -v -H 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"system_health" }' localhost:9933
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9933 (#0)
> POST / HTTP/1.1
> Host: localhost:9933
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 45
>
* upload completely sent off: 45 out of 45 bytes
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< content-length: 0
< date: Sun, 09 Feb 2020 07:31:41 GMT
<
* Connection #0 to host localhost left intact
* Closing connection 0
```

I don't think response 200 with empty response is the correct behavior. It should either tell me a required field `id` is missing, or give me a result.

Also it is give me empty response on invalid method

```
$ curl -v -H 'Content-Type: application/json' --data '{ "jsonrpc":"2.0", "method":"system_health1" }' localhost:9933
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9933 (#0)
> POST / HTTP/1.1
> Host: localhost:9933
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 46
>
* upload completely sent off: 46 out of 46 bytes
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< content-length: 0
< date: Sun, 09 Feb 2020 07:34:03 GMT
<
* Connection #0 to host localhost left intact
* Closing connection 0
```

This confused me a lot while figuring out what's wrong.

**Comment by bkchr** [comment]
Sounds like jsonrpc.

Cc @tomusdrw

**Comment by niklasad1** [comment]
If the request is missing ìd` it is then regarded as a JSON-RPC notification which doesn't return a response, https://www.jsonrpc.org/specification#request_object.

We have a similar issue in [parity-ethereum](https://github.com/paritytech/parity-ethereum/issues/11353).

I'm not super familiar with the implementation but seems correct to me, maybe you can clarify this @tomusdrw :)

**Comment by tomusdrw** [comment]
Yeah, it's the way it should work according to the spec:
https://www.jsonrpc.org/specification#notification

> A Notification is a Request object without an "id" member.  [...] The Server MUST NOT reply to a Notification, including those that are within a batch request.

We could possibly add a flag to HTTP server though to reject notifications (since we don't even have any). The thing is that with other transports without and `id` there is no way to correlate request and the response (http is unique, since it's inherently request-response protocol).

**Comment by bkchr** [comment]
Yeah okay, sounds like we follow the specification here. So, no bug on our side here. 

Probably better to use some cli tool that talks jsonrpc directly: https://github.com/dan-da/jsonrpc-cli
