### ISSUE TITLE
Test for process interruption generates untracked files

### ISSUE THREAD

**Issue by cecton** [paritytech/substrate#4888]
After running the tests purge_chain_works.rs and running_the_node_and_interrupt.rs a few directories are created: interrupt_test and purge_chain_test.

There is nothing wrong with that but they should be ignored in the Git repository and not marked as untracked files. If we don't do that, someone WILL commit them by mistake one day.

Maybe a good solution would be to prefix all those data generated and then add the prefix to the .gitignore. Or maybe put all the data generated in a directory that we put in the .gitignore. Or generate the data in /tmp instead of inside the repository.

**Comment by cecton** [comment]
We should also clean-up the data directories before running the tests.

**Comment by bkchr** [comment]
> We should also clean-up the data directories before running the tests.

We do this^^

**Comment by cecton** [comment]
oh

**Comment by pscott** [comment]
@cecton I just tried running those tests (multiple times) but I haven't managed to reproduce the issue.
It is my understanding that we're using [tempfile](https://docs.rs/tempfile/3.1.0/tempfile/index.html), so this should not be leaking any files.
There's probably something I'm missing here :)

**Comment by cecton** [comment]
hey @pscott yes it has been fixed in the meanwhile but it wasn't using tempfile in the beginning. In polkadot we still don't use tempfile though
