### ISSUE TITLE
Transaction payment API cannot handle fee that is too high

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4897]
https://github.com/paritytech/substrate/blob/00a400f82539e2f78e8ddbcd98aea512c87c5f3c/frame/transaction-payment/rpc/runtime-api/src/lib.rs#L54

This is causing issue for us.

On surface u64 supports value up to ~10^19, which is enough for most of the chains even if their token have 18 decimals (which we do).

But we are having issue that because the number is serialized as a number literal in JSON and `BN.js` will throw if the value is more than `Number.MAX_SAFE_INTEGER` which is `(2^53 -1)`. So the real save range that polkadot.js can handle is only up to ~10^16. That is a much more limited range.

We should instead serialize the `partial_fee` into a string, rather number. This will also allow it support u128 type or whatever the type `Balance` is.

**Comment by bkchr** [comment]
As commented in the PR. I don't think that it is a good idea to change the Rust implementation because of some flaws on the JS side which clearly should be solvable.

**Comment by jacogr** [comment]
Do you have an actual example of a breakage? The reason why I am asking is that this is not the only place this happens, ie. large numbers going into JSON. 

What I do recall (and I don’t have an example) is that the serialization (serde) actually does go into hex when the value is too large. (At least, that is what I recall seeing elsewhere - and it has been a while on these)

So here would really try to get a example of the failure described.

**Comment by xlc** [comment]
@jacogr https://console.acala.network/#/explorer

Attempting to submit transaction will cause this error (and bunch other unrelated errors)

```
VM337:37 2020-02-12 23:06:03        RPC-CORE: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: createType(RuntimeDispatchInfo):: Struct: failed on 'partialFee':: Assertion failed
window.console.error @ VM337:37
main.63aed445.js:65 Uncaught (in promise) Error: queryInfo(extrinsic: Bytes, at?: BlockHash): RuntimeDispatchInfo:: createType(RuntimeDispatchInfo):: Struct: failed on 'partialFee':: Assertion failed
    at e.selector (main.63aed445.js:65)
    at e.error (vendor.10c9733c.js:1)
    at e._next (vendor.10c9733c.js:8)
    at e.next (vendor.10c9733c.js:1)
    at e.notifyNext (vendor.10c9733c.js:1)
    at e._next (vendor.10c9733c.js:8)
    at e.next (vendor.10c9733c.js:1)
    at e.notifyNext (vendor.10c9733c.js:8)
    at e._next (vendor.10c9733c.js:8)
    at e.next (vendor.10c9733c.js:1)
```

**Comment by xlc** [comment]
@bkchr I disagree with you. I believe it is Substrate's issue that the transaction payment API cannot handle fees with more than `u64::max_value()`. The fact JS parser can only handle up to 2^53 is kind of unrelated. It is perfectly legit that a chain may want to have fee that is more than u64::max_value given that the Balance type is generic and is usually u128 and can be U256.

**Comment by bkchr** [comment]
Given your description I thought that you want to workaround some JS problems. 

But you are right that we currently use `u64` to workaround bugs in serde with `u128`. Not a huge fan to store the stuff in a `String`, but there is no better solution for now.
