### ISSUE TITLE
On-chain offline-validator voting

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#491]
Each validator, using the rhododendron [`on_advance_round`](https://docs.rs/rhododendron/0.2.1/rhododendron/trait.Context.html#tymethod.on_advance_round) hook maintains a list of validators `[Option<bool>]` he has seen online (heuristic: those for which proposals were received during their round). Periodically (once per session?), the validator can post a transaction containing this list.

If the runtime, at any point, sees that a validator is indicated offline by >1/2 and indicated online by <1/3, that validator is slashed. We can do a draconian slash for the moment and in the future make it exponentially increasing per offense.

NOTE: only rounds which fully completed should used to count a validator offline. Rounds which end with the `WAS_BEHIND` reason can be used to indicate a validator as online but not used to consider him offline.

**Comment by rphmeier** [comment]
cc @gnunicorn

**Comment by gavofyork** [comment]
done, more or less.
