### ISSUE TITLE
Couldn't Compile 'node-cli' error

### ISSUE THREAD

**Issue by KotaHemanthIITD** [paritytech/substrate#4914]
I'm manually building substrate for linux. After Cloning substrate git repository. I have manually executed following commands

- cargo install --force --path ./bin/node/cli #substrate
- cargo install --force --path ./bin/utils/subkey subkey

When executed 'cargo build' getting error attached below.

Compiling node-cli v2.0.0 ($HOME/substrate/bin/node/cli)
error: linking with `cc` failed: exit code: 1
 
 $HOME/substrate/target/debug/deps/liblibrocksdb_sys-f9c1c5eb20f81d8c.rlib(options_helper.o): In function `rocksdb::(anonymous namespace)::SerializeVectorCompressionType(std::vector<rocksdb::CompressionType, std::allocator<rocksdb::CompressionType> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
          $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-6.2.4/rocksdb/options/options_helper.cc:286: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
          $HOME/substrate/target/debug/deps/liblibrocksdb_sys-f9c1c5eb20f81d8c.rlib(threadpool_imp.o): In function `rocksdb::ThreadPoolImpl::Impl::StartBGThreads()':
          $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/librocksdb-sys-6.2.4/rocksdb/util/threadpool_imp.cc:346: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
          collect2: error: ld returned 1 exit status
  
It seems like a bash path triggered issue. Kindly help to resolve above build error.

**Comment by bkchr** [comment]
This is a linking error. Which operating system do you use?

**Comment by KotaHemanthIITD** [comment]
I'm using Centos 8

**Comment by bkchr** [comment]
Can you try to compile rust rocksdb directly please: https://github.com/rust-rocksdb/rust-rocksdb

**Comment by KotaHemanthIITD** [comment]
tried it but didn't work .. it builds fine in rocksdb but from substrate directory it's still giving same error. may i know required libraries to be included in $PATH environment variable for successful build?

**Comment by bkchr** [comment]
You have a linking error, it does not complain about missing libraries. 

Could you post a link to the full error output?

**Comment by KotaHemanthIITD** [comment]
Kindly find logs below
https://github.com/KotaHemanthIITD/bitcoin_logs/blob/master/substrate_error.log

**Comment by bkchr** [comment]
Maybe follow the installation instructions here: https://github.com/facebook/rocksdb/blob/master/INSTALL.md#supported-platforms for Centos

Otherwise it is just some linker error without any proper output from a dependency. I'm sorry for you, but we can not help with that as it is a dependency. 

If nothing works, I recommend to try a docker container with Ubuntu or whatever.

That said, I'm closing this issue.

**Comment by KotaHemanthIITD** [comment]
link you have shared helped .. substrate is building in centos 8 now. Thanks.

**Comment by bkchr** [comment]
Perfect!  :)
