### ISSUE TITLE
check-block with old block failed with `Could not fetch epoch at `

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4923]
```
$ ./target/debug/acala check-block --pruning=archive 130000
2020-02-14 11:32:52 Importing 1 blocks
2020-02-14 11:32:52 There was an error importing block with hash 0x756060db2b4ec9913ba37071dcaae8834fe8bbaf0d9fdbdbf42362400a84fd28: VerificationFailed(None, "Could not fetch epoch at 0x1d439b949dd15a0f3056b1aab6f460a0e68a283ab2b61bb088a11fa77eea35ed")
2020-02-14 11:32:52 Stopping after #0 blocks because of an error
Completed in 101 ms.
Segmentation fault: 11
```

Pruning mode is already archive. Anything I can do so I can replay old block to debug it?

**Comment by bkchr** [comment]
CC @arkpar

**Comment by arkpar** [comment]
Must be related to some additional pruning by grandpa/babe verifier. @andresilva Do we prune epoch changes regardless of `--pruning` setting? Ideally we should keep everything in archive mode, so that any old block could be re-checked.

**Comment by andresilva** [comment]
Currently epoch data for BABE and GRANDPA is pruned on finality, the idea is that you'd never need to import anything before the finalized block. With the current implementation there's no way to do this that doesn't lead to performance regressions if we never prune these data structures.

**Comment by xlc** [comment]
Is it possible to skip those digest verifications? I just want to debug why a tx in a block resulted an unexpected change.

**Comment by andresilva** [comment]
I guess you can just pass the client directly to the import queue to use as `BlockImport` (rather than running grandpa and babe block import logic). 

https://github.com/paritytech/substrate/blob/master/bin/node/cli/src/service.rs#L88

Here you'd replace this parameter with `client.clone()`.

**Comment by xlc** [comment]
@andresilva I think that's not enough. `BabeVefifier` that created by `import_queue` still causing the issue.

**Comment by xlc** [comment]
I am trying to temporary replace the consensus to manual-seal which seems like a no-verification consensus, but can't get it working #4926
