### ISSUE TITLE
How to use Manual Seal consensus engine?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4926]
Any docs of how to use it?

By reading the code, this doesn't make sense to me.
https://github.com/paritytech/substrate/blob/a6e7c051242433a02b7d524a349f3dba084fa549/client/consensus/manual-seal/src/lib.rs#L65

Does it mean it is not suppose to replace babe for local development purpose? Because I want to use it for e2e tests so that I don't need to figure out a perfect block time that is not too slow to run the tests but not too fast so I can't control what's included in a block.

 What is the purpose of manual seal consensus again? There are zero docs and zero examples that I can find.

**Comment by andresilva** [comment]
cc @seunlanlege

**Comment by seunlanlege** [comment]
hi @xlc could you explain what you're trying to acheive?

You use manual seal by passing the required args and spawning the returned future as an essential task

https://github.com/paritytech/substrate/blob/a6e7c051242433a02b7d524a349f3dba084fa549/client/consensus/manual-seal/src/lib.rs#L122-L131

See an example here, https://github.com/paritytech/substrate/blob/seun-instant-seal-service/bin/node-template/src/service.rs

**Comment by xlc** [comment]
I was trying to use the `import_queue` from manual-seal and it doesn't build.

https://github.com/paritytech/substrate/compare/master...laminar-protocol:try-manual-seal?expand=1

**Comment by JoshOrndorff** [comment]
@seunlanlege and I have written a recipe that demonstrates using both manual and instant seal. https://github.com/substrate-developer-hub/recipes/pull/202

Reviews there would be appreciated.
