### ISSUE TITLE
ss58 network prefix questions

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4927]
What is the strategy of picking ss58 network prefix? Does every production network require a unique one?

How do we assign a prefix ourself? I don't think PR to subkey should be the correct way.

We need a documentation explain the procedure to pick and assign a network prefix.

We should have a single source of truth file (in json / csv format) that contains all the assigned prefixes so Subkey & polkadot.js & other SDK can use it to correctly handle all ss58 address prefixes.

We should have an open registry and some documented procedure to allocate network prefixes.

> (0..48): Account/address identifiers on networks:

ss58 format only support up to 49 unique network identifier. This is a small number and we are going to run out of it.

(Not sure if this is the right place for this discussion, let me know if there is a better place)

**Comment by apopiak** [comment]
We have now run out of prefixes if we keep to the specified 49. What's the plan?
@gavofyork

**Comment by xlc** [comment]
Sort of closed by #8039
