### ISSUE TITLE
Run a spell checker + basic grammar tool over the entire repo

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#4933]
Before 2.0 release, lets do a pass over the whole repo with a basic spell checker and grammar tool.

We should prefer US english over UK english.

I would say if there are any questions whether to do A vs B, let's just follow the [Google Style Guidelines](https://developers.google.com/style).

**Comment by bkchr** [comment]
@shawntabrizi Will you do this?

**Comment by shawntabrizi** [comment]
I will if no one else will!

**Comment by bkchr** [comment]
If anyone wants to do this, please contact @shawntabrizi.

@shawntabrizi I just assigned you to make sure that it will be done ;)
