### ISSUE TITLE
Is it possible to tell what are changed state by a transaction?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#4939]
If possible, I would like a RPC that can tell me the state that been modified by a transaction.
Otherwise some additional loggings that print those information to stdout is also good. Maybe this is already logged and I just need to know which logger to enable?

**Comment by bkchr** [comment]
We don't log this and there is no functionality for this. You can listen for storage changes, but these are all changes done by a block.

**Comment by pepyakin** [comment]
This is another case that could be addressed by #2082

**Comment by xlc** [comment]
fixed by https://github.com/AcalaNetwork/chopsticks
