### ISSUE TITLE
links not found

### ISSUE THREAD

**Issue by mikedoan** [paritytech/substrate#4943]
All reference links in https://substrate.dev/docs/en/conceptual/core/executor are not found.

- https://substrate.dev/rustdocs/pre-v2.0-3e65111/substrate_service/config/struct.ExecutionStrategies.html
- https://substrate.dev/rustdocs/pre-v2.0-3e65111/substrate_client/enum.ExecutionStrategy.html
- https://substrate.dev/rustdocs/pre-v2.0-3e65111/substrate_executor/struct.RuntimeVersion.html

**Comment by bkchr** [comment]
Cc @JoshOrndorff

**Comment by bkchr** [comment]
Ty for the issue, but this is the wrong repo. Correct would be the this one https://github.com/substrate-developer-hub/substrate-developer-hub.github.io

I think it will be solved by @JoshOrndorff

**Comment by JoshOrndorff** [comment]
Thanks for reporting. The fix is in PR https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/456 and will be merged shortly.
