### ISSUE TITLE
Test "fork_aware_finalization" is flaky

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#4944]
`$ for i in {1..100}; do cargo test -p sc-transaction-pool fork_aware_finalization; done`

```
test testing::pool::fork_aware_finalization ... ok
```

...

```
---- testing::pool::fork_aware_finalization stdout ----
thread 'testing::pool::fork_aware_finalization' panicked at 'assertion failed: `(left == right)`
  left: `Some(InBlock(0x2e0b0dc7758b986a5968e92658a58396a2047e84a87bb419424bb26c943a2521))`,
 right: `Some(Ready)`', client/transaction-pool/src/testing/pool.rs:436:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

cc @seunlanlege

**Comment by seunlanlege** [comment]
hmm, looks like events may be skipped and lost forever, what do you think of switching to a bounded channel for backpressure @tomusdrw ?

**Comment by tomusdrw** [comment]
I don't think the events are being skipped or lost. Seems there is just a race condition between sending a notification from transaction pool and block production (the transaction is already in the pool, but the event was not yet sent). The test should just take it under the account.
