### ISSUE TITLE
Memory: mmap returned an error

### ISSUE THREAD

**Issue by maxsam4** [paritytech/substrate#4971]
My node stops producing block at around 9500 block number (~25th era, ~50th session). The first error is:
```
Encountered consensus error: ClientImport("Execution(Other(\"Memory: mmap returned an error\"))")
```
Which then causes the following error infinite times:
```
Encountered consensus error: ClientImport("Execution(Other(\"ApplySnapshotFailed\"))")
```
I tried restarting the chain from scratch 3 times and the error happened at block 9519 and 9558 and 9551.

The chain I'm using is available in the `develop` branch of https://github.com/PolymathNetwork/Polymesh

It is based on substrate commit `93569d0d1af7aa5eb67b9de8b58d7fffde63b421` but has a bunch of changes.

**Comment by pepyakin** [comment]
Can you reproduce consistently? Did it happen at those blocks each of those 3 times or you mean that the error happened once at 9519, once at 9558 and once at 9551?

What are the memory parameters of the machine you are running on? I assume it is 64 bit? How much free memory it had at failure times? Do you maybe run it inside of a docker container? Do you have any related logs to it?

Related #3780

**Comment by maxsam4** [comment]
I have reproduced it thrice consecutively. The error happened at those blocks on 3 different chains. I am running it on a single node in `--dev` mode so once the error happens, the chain is forever stuck and needs to be started from scratch.

64bit Ubuntu bionic. 16 gigs of ram. It had free ram available when the error happened initially (the system logs have no mention of oom). However, after a few hours of this error, the node eventually goes oom and the system kills it.

I am not using any docker containers. 

What kind of logs would you like?

**Comment by pepyakin** [comment]
For start, it would be helpful to see if there are anything that can be seen in the regular logs (ie those that are printed in stdout by default).

Besides that, I think it would help to know

1. what is the amount of RSS and VIRT memory the node consumes before, at the time of failure, and after the failure.
1. what is the number of mmaping the app requests. You can do it either with `pmap <pid>` (preferable) or `cat /proc/<pid>/maps`.
1. are there any limits set in place for that process? `ulimit -a`
1. what is `sysctl vm.max_map_count`?

Thanks that would be very helpful

**Comment by maxsam4** [comment]
I am currently running it on a fresh chain. The current ram usage is 13gb and increasing there's obviously a memory leak somewhere (could be due to one of our changes). I suppose at around 9500 block, there won't be enough ram left to process the block.

**Comment by maxsam4** [comment]
So the error happened again. At block 9453 with just 30mb available memory left. 15 gigs+ consumed by the node. Need to figure out the root cause of the memory leak now.

**Comment by bkchr** [comment]
Is that a dev chain that you are using?

**Comment by maxsam4** [comment]
Yes, it is.

**Comment by maxsam4** [comment]
FYI ran it with valgrind and there's confirmed memory leak within 20 blocks being mined. A snippet of the output: https://gist.github.com/maxsam4/aa8c72dfe40996bab6738d085bd14e49

FWIW the node is compiled in release mode. I am doing more tests now. Including testing it on the substrate's node template and Polkadot node.

**Comment by maxsam4** [comment]
There seem to be a memory leak in Polkadot as well: https://gist.github.com/maxsam4/809295d919f392f655f84af551e0d3e1

However, it's much lower than the leak in our node.

**Comment by maxsam4** [comment]
After a bit more poking around, it seems like polkadot has the same problem. Memory usage is growing without bounds on the latest polkadot node running in dev mode. I'm measuring heap usage with valgrind massif right now, will post the graph and massif file after collecting a bit more data.

Right now, the node has mined 120 blocks and it's using 600mb of ram (and growing).

**Comment by NikVolf** [comment]
600mb and growing is totally ok

If/when it grows total > 2-3 Gb, can you run it with `-lusage=trace` and post some logs?

**Comment by xlc** [comment]
in telemetry, you can order node by memory usage, and you can see many using > 5g, which is too much

**Comment by maxsam4** [comment]
Slightly unrelated, both my sentry nodes on Kusama got stuck maybe due to oom.

One has this error
```
Verification failed from peer: UnknownBlock: BlockId::Hash(0x8b2ae3c1441d9d8c34a4236b8ead3253d51eccdd610cdaf6de505afd978b3f8f)
Idle (4 peers), best: #1054646 (0x8d9d…0950), finalized #1054646 (0x8d9d…0950), ⬇ 14.0kiB/s ⬆ 20.3kiB/s
```
and the other has
```
Verification failed from peer: UnknownBlock: BlockId::Hash(0x7bf7e3f58d9f722fd72d8fde80b9cf45c1a6856092ad43539455cc2c2c0a9cb9)
Idle (4 peers), best: #1015366 (0xb9fd…b277), finalized #1015366 (0xb9fd…b277), ⬇ 14.0kiB/s ⬆ 1.0kiB/s
```
A lot of people in the riot validator chat have the same problem.

**Comment by maxsam4** [comment]
@NikVolf Polkadot's node is printing these with ltrace `2020-02-19 16:30:03.517 main-tokio- TRACE usage  Usage statistics: caches: (1153008 state, 8021310 db overlay), i/o: (7 tx, 13281 write, 132402 read, 1897 avg tx, 250/259 key cache reads/total)`

but my node is not. do you know why?

**Comment by NikVolf** [comment]
What is the version of your node?

**Comment by NikVolf** [comment]
@maxsam4 This was shipped after your commit
But can you show this output on polkadot when  it consumes close to all available memory?

**Comment by maxsam4** [comment]
@NikVolf Interestingly, polkadot's memory usage hasn't grown much after I enabled ltrace. It could be that valgrind was adding the overhead and not polkadot itself. I am running without valgrind this time.

**Comment by maxsam4** [comment]
Here's some heap details of my node when it was consuming 10 gigs of ram in total. 
https://drive.google.com/file/d/1TYGaC5sSNjdADWwLA6pKZ1ul-2k7lSfE/view?usp=sharing

Use massif-visualizer to view it properly.

among other things, it seems like polling future is causing high memory usage. Any ideas what's going wrong? We have not touched the babe/grandpa/futures modules.

**Comment by NikVolf** [comment]
> Here's some heap details of my node when it was consuming 10 gigs of ram in total.
> https://drive.google.com/file/d/1TYGaC5sSNjdADWwLA6pKZ1ul-2k7lSfE/view?usp=sharing
> 
> Use massif-visualizer to view it properly.
> 
> among other things, it seems like polling future is causing high memory usage. Any ideas what's going wrong? We have not touched the babe/grandpa/futures modules.

We indeed had troubles with memory leak in master after updating libp2p, but it is fixed now. I'd suggest you update to latest master.

**Comment by maxsam4** [comment]
> We indeed had troubles with memory leak in master after updating libp2p, but it is fixed now. I'd suggest you update to latest master.

Thanks, I was trying to delay that till next substrate release because that'll be another big refactor for us but I suppose we should just do it at this point.

**Comment by maxsam4** [comment]
I forgot to update this issue but upgrading to latest substrate indeed fixed this issue.
