### ISSUE TITLE
timestamp set in block doesn't match slot in seal

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/substrate#4984]
If I set 

```rust
pub const MILLISECS_PER_BLOCK: Moment = 1000;
```

I want to produce one block per second

**Comment by bkchr** [comment]
What are you using? Babe or Aura?

**Comment by AurevoirXavier** [comment]
> What are you using? Babe or Aura?

Babe

**Comment by bkchr** [comment]
Did you purge your chain after the change?

**Comment by AurevoirXavier** [comment]
> Did you purge your chain after the change?

Yes, It works on 1500, 2000, 3000... But not 1000.

**Comment by bkchr** [comment]
Release build? Maybe Babe is too heavy for 1 sec block time at the moment.

@andresilva any ideas?

**Comment by andresilva** [comment]
I guess it's possible that by the time the timestamp is collected to populate inherent data it is already from the next slot, I'd need to look into it. Either way, it is not a good idea to deploy a chain with 1s block time IMO.

**Comment by AurevoirXavier** [comment]
> I guess it's possible that by the time the timestamp is collected to populate inherent data it is already from the next slot, I'd need to look into it. Either way, it is not a good idea to deploy a chain with 1s block time IMO.

It's a dev chain not for production, So I want to set it to 1s.

I'm on pre-2.0 tag.
