### ISSUE TITLE
Authority keys are generated from equal seeds

### ISSUE THREAD

**Issue by user-4t34zA2wQ** [paritytech/substrate#4986]
In https://substrate.dev/rustdocs/master/src/node_cli/chain_spec.rs.html#183 the keys, GrandpaId, BabeId, ImOnlineId and AuthorityDiscoveryId are generated from the same seed in the same function and hence are equal.

Does this raise any security concerns?

In addition, what if (hypothetically) they are also equal to the second AccountId in the return type?

**Comment by bkchr** [comment]
This is only used for test nets. So, no security problem.

The public keys for a production net are not generated in there.

**Comment by user-4t34zA2wQ** [comment]
Yes. Does this imply that keys should be different in production situations? Is there a reference?
