### ISSUE TITLE
UnorderedSet data structure

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5039]
What is the best way to implement an UnorderedSet?
I noticed Substrate uses sorted Vec to implement UnorderedSet in few places and use binary search operation for insertion and deletion.
I am thinking to use `double_map hasher(twox64_concat) Key, hasher(twox64_concat) Item => ()`.

Any suggestions? It will be good if this is can be generalized in Substrate because there are many use cases for UnorderedSet such as store memberships.

**Comment by bkchr** [comment]
Hey, so for managing a membership there is the membership pallet.

I think there is no general solution for implementing a set. It really depends on the expected total size. If the size will not be that big, using a vec should be the goto solution. However if you expect millions of entries, using some sort of storage map could be more performant.

**Comment by xlc** [comment]
I am expecting up to few hundreds entries and each entry is a u32 id, which I guess I should be using sorted vec. In that case some data structure to encapsulate the logics will be helpful. i.e. `set.insert(value)` instead of `let location = set.binary_search(...); set.insert(location, value)`

**Comment by bkchr** [comment]
Why not use the membership pallet for it?

**Comment by xlc** [comment]
Because I am not storing memberships but ending auction ids 

https://github.com/laminar-protocol/open-runtime-module-library/blob/3ac2286c76b4db816104afbeca03416003d20619/auction/src/lib.rs#L42
