### ISSUE TITLE
Light client cache runtime code

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#5047]
Currently the runtime code is part of the `StorageProof` of the `execution_proof`. From a performance perspective, caching the runtime code on the light client would be a much better idea.

The rough idea would be the following:
1. Introduce a new digest `RuntimeCodeChanged`. This digest should be added to the header when the runtime code changes. 
2. Make light client listen for `RuntimeCodeChanged` digests.
3. Request runtime code in light client after `RuntimeCodeChanged` was detected and cache it locally.

CC @svyatonik

**Comment by cheme** [comment]
Naïve question, why not storing a hash of `:code` in the state instead?

**Comment by svyatonik** [comment]
> Naïve question, why not storing a hash of :code in the state instead?

Because light client has no local access to the state. It would need to fetch proof of read of that `:code_hash` at every block. Digest is available from headers => we'll know when we really need to fetch new `:code`. It is like polling vs subscription.

**Comment by cheme** [comment]
Feels like `:code` is not needed anymore in the state since we got it from the headers (at least when managing a cht). Yet keeping the hash of the code in the state is probably harmless. I guess having a separate storage for runtimes is another issue, but maybe the light client specific runtime management could be generalized to full client for possible future changes.

**Comment by svyatonik** [comment]
> Feels like :code is not needed anymore in the state since we got it from the headers (at least when managing a cht).

I may be missing something from your comment, but the idea was never to include the whole `:code` in the header. Just the signal that the code has been changed and we need to fetch the new version. I do not think that including the code itself is a good idea (given its size).

**Comment by cheme** [comment]
yes I was just saying that we can fetch runtime hash from the headers (given on genesis we include a initial change), so it is not strictly needed in state as long as client got the cht.

I was not proposing to put those big blobs in header :) , quite the opposite (removing them from the state could be good but then we need to store them somewhere and a way to share them: so if there is a dedicated storage used by light, it could probably be use by full client to, but it needs a specific rpc to query it afterward).

Ok, I misread the description, I was thinking the `RuntimeCodeChange` digest would include a hash of the new runtime, but it does not have to. My comment only make sense if it does.

**Comment by svyatonik** [comment]
OK, I got your idea now, thanks :) Yes - `hash(code)` should probably be a part of that digest. But what you're talking about is quite a significant change that, imo, deserves separate discussion/issue :)

**Comment by seunlanlege** [comment]
interested in light client mechanics if anyone's willing to mentor this issue :eyes:

**Comment by svyatonik** [comment]
@seunlanlege Great! Thanks for your interest :) Imo, it could be done roughly as follows (every point could be a separate PR, order matters):
1) introducing a 'DigestItem::RuntimeChanged' (or `RuntimeCodeChange`) digest item - it should have some unqiue code id. The most straightforward way is to include hash (code), so the item would be 'DigestItem::RuntimeChanged(Hash)';
2) emitting this item when code is changed - i.e. from `System::set_code()` function (you could take a look at the `System::set_changes_trie_config` for example);
3) whenever client imports header with 'DigestItem::RuntimeChanged', it inserts new entry into blockchain cache (`client/src/cache/*`). This entry means that starting from this header, runtime code has given hash. The code itself should be stored in some parallel storage (would it be extension to blockchain cache, or separate column - it is up to you);
4) whenever client has request for remote execution at some block, it:
4.1) reads `hash(runtime_code)` entry from the blockchain cache;
4.2) asks that 'parallel storage' if it already has code for that block. If yes - returns that code;
4.3) if no - asks remote nodes for `storage_proof(runtime_code, at_block)`, inserts that code into 'parallel storage' and returns that code;
5) so now we have locally available runtime code. The only thing we need are trie nodes that are touched during execution. So:
5.1) we're changing how `message::RemoteCallRequest` is processed - it should not include runtime code in the proof (that's the goal of this issue);
5.2) we're passing cached runtime code to the `execution_proof_check()`.

OK, while I was writing this, I've also noticed that the `RuntimeCode` requires `heap_pages`. I assume that it is consensus-critical => we need to have same value both on full and light nodes. So I also suggest to include `heap_pages` into 'DigestItem::RuntimeChanged(Hash, u64)'. This `u64` may be stored in the blockchain cache itself (not in that 'parallel storage'). And `System::set_heap_pages` should also emit 'DigestItem::RuntimeChanged`. So we may have the same code spanning through several blocks ranges, but different `heap_pages`.

If you have any further questions - please ask here, or DM me! Good luck :)

**Comment by tomaka** [comment]
Now that the light client is dead, we can probably revisit this issue and no longer include the runtime code in the proof?

**Comment by bkchr** [comment]
Sound good to me
