### ISSUE TITLE
'subkey inspect' generates different SS58 address from 'subkey --network kusama generate'

### ISSUE THREAD

**Issue by yyi-99plus** [paritytech/substrate#5091]
Command1:
========
subkey --network kusama generate

Output:1
========
Secret phrase `bid young steak uniform test throw plunge crumble neither curve punch arctic` is account:
  Secret seed:      0x15356de91f772c3a8ac6a7c9c8fb75d478fd64f3440152dcdc70889eaa0cd9d7
  Public key (hex): 0x709eab46927ef17f8be785171b696ca17602bbae340c5d383e7049f44b24615a
  Account ID:       0x709eab46927ef17f8be785171b696ca17602bbae340c5d383e7049f44b24615a
  SS58 Address:     F7z1r97PGAfTjh5ycv9YdzGCSy3oRMad3c6riTD6H1yLrZT

Command2:
========
subkey inspect 0x15356de91f772c3a8ac6a7c9c8fb75d478fd64f3440152dcdc70889eaa0cd9d7

Output2:
========
Secret Key URI `0x15356de91f772c3a8ac6a7c9c8fb75d478fd64f3440152dcdc70889eaa0cd9d7` is account:
  Secret seed:      0x15356de91f772c3a8ac6a7c9c8fb75d478fd64f3440152dcdc70889eaa0cd9d7
  Public key (hex): 0x709eab46927ef17f8be785171b696ca17602bbae340c5d383e7049f44b24615a
  Account ID:       0x709eab46927ef17f8be785171b696ca17602bbae340c5d383e7049f44b24615a
  SS58 Address:     5EcNMXoEku9ji5seCv76egdG3rgozkYQAfmMU4BFcUoUbkaN

Result:
========
The public keys are the same but the SS58 addresses are different.

**Comment by laboon** [comment]
It's just showing the Substrate version of the address of the public key, as opposed to the Kusama-style address, since you didn't specify which network format you wanted it in.  You just need to set the `--network kusama` as part of the `inspect` call:

```
(878) ~/web3/substrate $ subkey --network kusama inspect 0x15356de91f772c3a8ac6a7c9c8fb75d478fd64f3440152dcdc70889eaa0cd9d7
Secret Key URI `0x15356de91f772c3a8ac6a7c9c8fb75d478fd64f3440152dcdc70889eaa0cd9d7` is account:
  Secret seed:      0x15356de91f772c3a8ac6a7c9c8fb75d478fd64f3440152dcdc70889eaa0cd9d7
  Public key (hex): 0x709eab46927ef17f8be785171b696ca17602bbae340c5d383e7049f44b24615a
  Account ID:       0x709eab46927ef17f8be785171b696ca17602bbae340c5d383e7049f44b24615a
  SS58 Address:     F7z1r97PGAfTjh5ycv9YdzGCSy3oRMad3c6riTD6H1yLrZT
```

If you only have the public address, you can do something similar with polkadot.js by changing the settings of the address display, or you can use the W3F utility script `pubkeyToAddress` - https://github.com/w3f/utility-scripts

```
(875) ~/web3/substrate $ node ~/web3/utility-scripts/src/misc/pubkeyToAddress.js 0x709eab46927ef17f8be785171b696ca17602bbae340c5d383e7049f44b24615a
Substrate Address:
5EcNMXoEku9ji5seCv76egdG3rgozkYQAfmMU4BFcUoUbkaN
Kusama Address:
F7z1r97PGAfTjh5ycv9YdzGCSy3oRMad3c6riTD6H1yLrZT
Polkadot Address:
13YfVs4JcgRD9ctAAZA6nqTQuUgTh46YFAVqdMAcAZpznHs5
```
