### ISSUE TITLE
State rent and empty values

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#5107]
At the moment of writing the storage rent computes the effective rent based on the byte size of each storage entry the contract occupies.

However, https://github.com/paritytech/substrate/pull/5103 raised a question: how are zero sized storage values interact with storage rent? For now, they won't affect the final cost. That doesn't seem right because in reality even an empty mapping occupies some DB space.

@Robbepop proposed to just ban this sort of interactions for now and allow them when we deem they are actually useful. While this sounds tempting, I am not sure if we should go this way - this seems to be a bit more limiting, especially considering there is already one use-case discovered: sets that leverage KV storage.

<details>
Imagine a contract that has to maintain a set of, say, u32 values. The set of values is potentially unbounded. If we were to save such a set in a single storage entry, as a serialized vector without repeated values, then such a vector will have to be serialized, deserialized, and filled at least once per contract run. 

A solution would be to leverage the key to encode the value and then just check if the value under that key exist. If all values of the set are kept under prefix `0xFFFFFFFFFFFFFFFFFF` then a value `0x12345678` would have key `0xFFFFFFFFFFFFFFFFFF12345678`. If such a key exists then the value in the set. If empty values were banned we would have to have a one byte dummy value in each entry, which seems to be awkward.
</details>

**Comment by thiolliere** [comment]
somewhat related to https://github.com/paritytech/substrate/issues/5986
