### ISSUE TITLE
Implement saturated_mul for Fixed64

### ISSUE THREAD

**Issue by apopiak** [paritytech/substrate#5114]
`sp_arithmetic::Fixed64` implements [`saturated_multiply_accumulate`](https://github.com/paritytech/substrate/blob/6e0a4877afbe2309e106b84333bb70200531b604/primitives/arithmetic/src/fixed64.rs#L76) for unsigned types which does `uint + self * uint`. It would be great to also have (in pseudo-Rust) `saturated_multiply<U: unsigned>(n: U)` that does `self * uint`.

**Comment by kianenigma** [comment]
Yeah that makes sense. 

Fixed64 is pretty much a proxy for our one and only use case for it in substrate, so it is not super generic. 

Why do you need it?

**Comment by apopiak** [comment]
I want numbers in the range of 1 to (e.g.) 1'000 to refer to the amount of my [stablecoin](https://github.com/apopiak/pallet-stablecoin) that you are [bidding for bonds](https://github.com/apopiak/pallet-stablecoin/blob/19f8ee56a3d3ac129685391c7360472a3a75967a/src/lib.rs#L263) as well as calculating the amount of [expansion/contraction](https://github.com/apopiak/pallet-stablecoin/blob/19f8ee56a3d3ac129685391c7360472a3a75967a/src/lib.rs#L388) that needs to be done.

**Comment by apopiak** [comment]
We actually removed one usag, but the other remains.

**Comment by marcio-diaz** [comment]
Closed by #5877
