### ISSUE TITLE
Different between `&T::AccountId` and `impl Borrow<T::AccountId>`?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/substrate#5115]
I saw a lot of these usage in balances module.

Which way is better? Why?

**Comment by AurevoirXavier** [comment]
Which way is better? Why?

**Comment by bkchr** [comment]
Depends on the use case and what you want to achieve. However, this is more a general Rust programming question that is not related to Substrate.

One last tip, look [here](https://doc.rust-lang.org/std/borrow/trait.Borrow.html) for more information. 
Tip^2: You could have some `struct Whatever { accountid: T::AccountId, some_other_data: Vec<u8> }` that implements this trait.
