### ISSUE TITLE
Remove wasmtime fork

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#5140]
since #5109 we have a wasmtime fork which allows us to be more efficient in caching by implementing specific thread-safety features on it. However, we do not want to support the fork long-term, instead make sure a thread-safe original wasmtime is released and switch to that. This is a tracking issue for that progress.

Related https://github.com/bytecodealliance/wasmtime/pull/1227

**Comment by pepyakin** [comment]
This is sorted, I believe.
