### ISSUE TITLE
Flaky transaction pool test

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#5144]
```
 ---- testing::pool::should_push_watchers_during_maintaince stdout ----
thread 'testing::pool::should_push_watchers_during_maintaince' panicked at 'assertion failed: `(left == right)`
  left: `5`,
 right: `3`', client/transaction-pool/src/testing/pool.rs:331:2
```
Job: https://gitlab.parity.io/parity/substrate/-/jobs/407602

cc @tomusdrw @NikVolf

**Comment by bkchr** [comment]
Pr: https://github.com/paritytech/substrate/pull/5121

**Comment by kianenigma** [comment]
Sorry, but happens again :( 

https://gitlab.parity.io/parity/substrate/-/jobs/440163

cc @NikVolf

**Comment by kianenigma** [comment]
https://gitlab.parity.io/parity/substrate/-/jobs/441783 
https://giphy.com/gifs/Friends-episode-4-friends-tv-the-one-with-rachels-assistant-StoeNoDkYuum8cj8MV

(it is a different test case though)
