### ISSUE TITLE
`MODULE_ID` should be configurable

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#5149]
Some pallets introduce a `MODULE_ID` which is hard-coded into the runtime.

These are usually used as a seed for generating a unique account id for those pallets to hold funds (like a POT).

This pattern is not flexible, and immediately makes it so that these pallets could not be made instantiable.

It would be better to have these as configuration traits, and even better, to have them auto-populated based on the `ModuleToString`: https://github.com/paritytech/substrate/issues/5148

**Comment by emostov** [comment]
I was interested in working on this issue but noticed DarkEld3r self-assigned over a month ago. If there has been no progress on this issue, can I have it assigned to myself?

**Comment by shawntabrizi** [comment]
@emostov I think that should not be a problem. Ill assign you
