### ISSUE TITLE
Benchmarking CLI should use `--chain dev` if not provided.

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#5154]
Right now, if a user forgets to provide `--chain`, they get a nasty misleading error:

```
Error: Input("Error executing runtime benchmark: Wasmi(Function(\"Module doesn\\\'t have export Benchmark_dispatch_benchmark\"))")
```

Instead, we should choose <strike>a default chain just like if we were running the node</strike> the dev chain spec which contains the benchmarking apis.

**Comment by bkchr** [comment]
It actually selects a default chain, but not the `dev` chain that you need^^

**Comment by shawntabrizi** [comment]
Why does it need to be the dev chain?

I would prefer it be with whatever genesis will be used by default when running a node without flags.

**Comment by bkchr** [comment]
It does that and by default `Substrate` uses flaming flir and that wasm blob clearly doesn't contain the benchmarking functionality. You can choose whatever chain spec you want ^^

**Comment by shawntabrizi** [comment]
> that wasm blob clearly doesn't contain the benchmarking functionality

Ah, cause the wasm was baked into the chain spec, and that one is old

**Comment by bkchr** [comment]
> > that wasm blob clearly doesn't contain the benchmarking functionality
> 
> Ah, cause the wasm was baked into the chain spec, and that one is old

Yep exactly.
