### ISSUE TITLE
Is the `AccountData` compatible with `Instance`?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/substrate#5175]
The system module require an `AccountData` and the balances module require a `StoreMap`.

But if I've 2 balances, how to configure the runtime?

---

Now I make a ugly hack:

Decl 2 same modules.

```rust
struct AccountData<Balance> {
	balances_1_free: Balance, // unused in module 2's storage
	balances_2_free: Balance, // unused in module 1's storage
	...
}

// ---

impl pallet_system::Trait for Runtime {
	type AccountData = pallet_my_support::AccountData<Balance>;
	...
}

impl pallet_balances1::Trait for Runtime {
	type AccountStore = frame_system::Module<Runtime>;
	...
}

impl pallet_balances2::Trait for Runtime {
	type AccountStore = frame_system::Module<Runtime>;
	...
}
```

**Comment by AurevoirXavier** [comment]
Also the `DustLost` should trigger by both of the 2 balances' total < `ED`. Any elegant way to achive this?

**Comment by thiolliere** [comment]
First note that pallet_balance can also not make use of AccountData and use a dedicated storage map though performance won't be as good (see the file frame/balances/src/tests_local.rs )

For now I don't see how it is possible to use AccountData for multiple module easily,
you can still implement StoredMap trait for each balance by hand on a new type I think:
```rust
struct StoredMapAccoundDataForBalance1;
impl StoredMap<AccountId, AccountData<Balance1>> for StoredMapAccountDataForBalance1 {
// Implement functions by calling the frame_system stored map
}
```
But this is just a suggestion I'm not sure if it will works
