### ISSUE TITLE
Prometheus metrics: add build info label

### ISSUE THREAD

**Issue by gabreal** [paritytech/substrate#5181]
The new prometheus metics endpoint exposes metrics currently in the following format:
```
polkadot_block_height_number{endpoint="metrics",instance="XXX",job="job_name"",namespace="namespace",pod="pod_name",service="polkadot-metrics",status="best"}
```

These metrics give no information about which version/build these metrics are from. Therefore it would be very useful to have a default label added to all of those metrics e.g. like it is the case with the dotexporter:
```
dot_chain_block_number{block="head",build="0.7.22-dev-ab76ea7-x86_64-linux-gnu",chain="Kusama CC3",instance="XXX",job="jobb_name",name="parity-polkadot",namespace="namespace",pod="pod_name",service="polkadot-metrics",substrate_ref="a439a7a",version="0.7.22-dev"}
```

The relevant useful labels are:
- `version="0.7.22-dev"`
- `build="0.7.22-dev-ab76ea7-x86_64-linux-gnu"`
- `chain="Kusama CC3"`
also useful but not sure if so easy to get `substrate_ref="a439a7a"` which denotes the substrate build reference.

**Comment by mxinden** [comment]
I would suggest we introduce a static info metric that each node exposes with a `version`, `build` and `chain` label. This metric can then be [grouped](https://prometheus.io/docs/prometheus/latest/querying/operators/#many-to-one-and-one-to-many-vector-matches) onto any other metric of the same target resulting in the above requested extended metric.

**Comment by gabreal** [comment]
Sounds also good to me even though it will make queries more complex. What's the main argument against adding those labels to every metric?

**Comment by mxinden** [comment]
https://github.com/paritytech/substrate/pull/5192 would add the `node_info` metric as suggested in https://github.com/paritytech/substrate/issues/5181#issuecomment-596423977.

> What's the main argument against adding those labels to every metric?

From a  gut feeling this would be something that should happen during relabeling or through service discovery. In addition adding a label to each metric on the target side bloats the overall output. 

I need to put some more thoughts into this. @gabreal could you explain your use cases when you need this information joined with other metrics? Would you like to alert among other things based on the version of Substrate/Polkadot?

Implementation note: One could do this within the [registry](https://docs.rs/prometheus/0.8.0/prometheus/struct.Registry.html#method.new_custom).

**Comment by gabreal** [comment]
Well the primary use case is to identify different versions running. it's not clear at all which version is deployed where and also for the nightly testing when writing alerts it's necessary to identify the builds from the metrics. Otherwise one would have to log into the node/pod (assuming only one node is running there) and query the `polkadot --version`. For instance one could also have two different versions running at the same time and compare their behaviour. So every metric that I want to compare I do want to be able to associate with the build info.
I guess relabelling when scraping or using the join queries will work good enough.

**Comment by gabreal** [comment]
For instance with [this](http://prometheus.parity-mgmt.parity.io/graph?g0.range_input=1h&g0.expr=dot_chain_block_number%7Bversion%3D%220.7.21%22%7D&g0.tab=1) query I get easily which versions are deployed on which nodes and can compare their behaviour based on their build reference.

**Comment by gabreal** [comment]
![](file:///home/gabriel/screenshots/Screenshot_2020-03-10%20Prometheus%20Time%20Series%20Collection%20and%20Processing%20Server.png)

**Comment by gabreal** [comment]
so basically now queries have to be grouped like this:

![](https://cdn1.imggmi.com/uploads/2020/3/10/0c1fdb6144f4550a5bea2df65267060a-full.png)

in order to connect the labels to with the metrics. would it also be possible to add the chain name? and the commit id is the substrate ref, I assume, what will it be for polkadot builds?

**Comment by gabreal** [comment]
for completeness: this is exactly the way robustperception is recommending this https://www.robustperception.io/exposing-the-software-version-to-prometheus :+1:
