### ISSUE TITLE
wasm-build-runner-impl should ignore .cargo/config

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5190]
This is a very low priority issue, but if someone puts `target = "foo"` in `.cargo/config` file, it will be picked up by the WASM builder.
The `wasm-build-runner-impl` will then be compiled for the wrong platform and will fail to run.

**Comment by bkchr** [comment]
What does `target = "foo"` do? Or what is the expected outcome?

**Comment by tomaka** [comment]
> What does target = "foo" do? Or what is the expected outcome?

It sets the default target to compile to if you don't pass `--target`.
https://doc.rust-lang.org/cargo/reference/config.html#buildtarget

For example if someone wants to configure Substrate to configure to Android by default, they might set `target = "arm-something"`, which will cause the WASM building crate to also be built for Android.
