### ISSUE TITLE
txpool resubmission race condition on fast block authoring

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#5211]
when authoring blocks fast (sub-second with POW), it can happen that the pruning process for the extrinsic in a block hasn't actually removed the blocks from the pool before an attempt is made to author another block. because it has already been included, it is then marked as `Invalid` and removed and the RPC is informed – rather than given then information that it has been included in the previous block.

Leading to the odd case, that over RPC we are informed the block was invalid, on chain, however, we can see that it has been applied.

**Comment by bkchr** [comment]
@NikVolf is this solved now?

**Comment by NikVolf** [comment]
@bkchr Yes
