### ISSUE TITLE
Issues with Identity benchmarks

### ISSUE THREAD

**Issue by lamafab** [paritytech/substrate#5217]
When compiling with `cargo build --release --features=runtime-benchmarks`, running the functions `set_subs`, `clear_identity` and `kill_identity` fail:

```bash
./target/release/substrate benchmark --chain dev --execution=wasm --wasm-execution=compiled --pallet pallet-identity --extrinsic set_subs --steps 1 --repeat 1
Error: "NotFound"

./target/release/substrate benchmark --chain dev --execution=wasm --wasm-execution=compiled --pallet pallet-identity --extrinsic clear_identity --steps 1 --repeat 1
Error: "NotFound"

./target/release/substrate benchmark --chain dev --execution=wasm --wasm-execution=compiled --pallet pallet-identity --extrinsic kill_identity --steps 1 --repeat 1
Error: "NotFound"
```

The error is probably this one:
```rust
decl_error! {
	/// Error for the identity module.
	pub enum Error for Module<T: Trait> {
		/// ...
		/// Account isn't found.
		NotFound
		/// ...
```

I looked through the code in `frame/identity/src/benchmarking.rs` and `frame/identity/src/lib.rs`, but I'm not familiar enough with the Pallet internals to (quickly) figure out what the correct fix is for this.

For example, removing:

```rust
ensure!(<IdentityOf<T>>::contains_key(&sender), Error::<T>::NotFound);
```

... from `fn set_subs` makes the old error disappear and replaces it with `Error: "InsufficientBalance"`.

**Comment by marcio-diaz** [comment]
Thanks for the report @lamafab.
