### ISSUE TITLE
RPC: Query multiple storage keys at single block at once

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/substrate#5220]
Currently it's either possible to:
1. `state_queryStorage(Vec<Key>, BlockHash, Option<BlockHash>)`
2. `state_getStorageAt(Key, Option<BlockHash>)`

With (1) the node has to query a range of blocks (setting `from=to=latest` does not seem to work at all). Also if you specify the mandatory argument `from=latest_hash` you are risking a race condition between querying a single block or two blocks (if a new one is imported in the meantime).

With (2) you can only query one key at the time, and the latest block is optional.

The idea would be to provide another method that allows you to query a vector of keys, but also be sure that it will fetch only the latest block data. So something like:
`state_queryStorageAt(Vec<Key>, Option<BlockHash>)`

Potentially we could implement `state_queryStorageAt` as:
```
fn state_queryStorageAt(&self, keys: Vec<Key>, at: Option<Hash>) -> _ {
  let block = at.unwrap_or_else(get_latest);
  self.state_queryStorage(keys, block, Some(block))
}
```
if we fix `state_queryStorage` to work with a single block in range too.

CC @jacogr

**Comment by tomusdrw** [comment]
CC @seunlanlege perhaps you would be interested?

**Comment by seunlanlege** [comment]
Yeah definitely
