### ISSUE TITLE
Benchmarks should generate unit tests

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#5222]
A runtime benchmark is basically the same as a unit test:

* It sets up storage.
* Runs a bunch of functions which cannot fail, else it returns an error.
* Ultimately executes a final extrinsic which must return `Ok(())`.

The `benchmark!` macro should wrap the benchmark logic into simple unit tests which confirm that the benchmarks will not fail when actually being executed for benchmarking.

Ideally, it would run some similar loop over the components just like a real benchmark, maybe with a limited number of steps and no repeats to reduce the time it takes to execute.

This also means, as extrinsics change, or benchmarks are written, that these tests will execute as a part of the CI process for pull requests.

**Comment by shawntabrizi** [comment]
Additionally it would be nice to have a "verify" code block, which allows you to run some arbitrary runtime assertions which must pass, verifying that your benchmark is indeed doing what it wants, but without including that verification time in the benchmarks.

This would be useful for extrinsics which "fail silently", extrinsics which have multiple paths (ensuring you walk down the right path), and for the more general function benchmarks.

**Comment by kianenigma** [comment]
I am still curious to see how all of this is going to work with https://github.com/paritytech/substrate/pull/4947 😬

**Comment by shawntabrizi** [comment]
Here is an example what an autogenerated unit test would look like:

https://github.com/paritytech/substrate/blob/a92b533f1ee6383e1e4286369cf171506c6bcb52/frame/im-online/src/benchmarking.rs

Seems super simple given what we do with the benchmarks already.
