### ISSUE TITLE
When to inc_ref / dec_ref?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5255]
There is an introduction of `inc_ref` / `dec_ref` in frame_system recently. 

It is been called by some of the substrate pallets (e.g. democracy, recovery), but not some others (e.g. identity, society).

There isn't much documentations about when a custom pallet should use inc/dec the reference of an account.

Any quick guidance? and some extensive documentations followup?

(Is this kind of question belong to here or substrate-developer-hub?)

**Comment by bkchr** [comment]
CC @gavofyork
