### ISSUE TITLE
Expose hash functions

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#5258]
We can expose hash functions that are provided by the substrate host, such as: `keccak256`, `blake2`, `twox`. This shouldn't be that hard and I don't see any reason to not expose them.

**Comment by Robbepop** [comment]
With the upcoming refactoring of the currently broken `storage::HashMap` in ink! there is going to be a demand for having those `ext_*` hash functions available.

Not having those implies embedding them into the contract Wasm blobs which ...
- bloats the Wasm for every contract that embeds them
- contracts are more likely to use different or even broken crypto hash implementations
- gas costs are a lot higher with embedded crypto hashes than in natively running crypto hashes provided by `ext_*` interfaces. This is especially a problem since crypto hashes are probably going to be a very common operation.

**Comment by seanyoung** [comment]
The gas cost for these functions has to given some consideration. EVM has very low prices for keccak for example. 

Additionally these crypto functions are available in Solidity: https://solidity.readthedocs.io/en/v0.6.4/units-and-global-variables.html#mathematical-and-cryptographic-functions

**Comment by Robbepop** [comment]
> Additionally these crypto functions are available in Solidity: https://solidity.readthedocs.io/en/v0.6.4/units-and-global-variables.html#mathematical-and-cryptographic-functions

I think these should go into their own issue/PR since they potentially imply more background work on the Substrate side for the not yet implemented pieces.

**Comment by seanyoung** [comment]
Both interfaces look really good. From Solang perspective, keccak will be called often, and in many cases the interface without the scratch buffer can be used, which will make the code shorter.

Perfect!

**Comment by Robbepop** [comment]
> Both interfaces look really good. From Solang perspective, keccak will be called often, and in many cases the interface without the scratch buffer can be used, which will make the code shorter.

In which cases can the version with the `result_ptr` _NOT_ be used?

**Comment by seanyoung** [comment]
Given this Solidity:
```
contract c {
        function test() public {
                bytes memory data = hex"aabbccdd";
                bytes32 hash = keccak256(data);

                byte first_byte = data[0];
        }
}
```
- The input to keccak256() is shorter than 32 bytes
- The input to keccak256() is used *after* the call (copied to first_byte)

Now an implementation might just copy data and ensure the buffer is at least 32 bytes. However, what if the input is much larger; now the copy might become costly.

**Comment by bkchr** [comment]
> We should have a separate ext_ function per crypto hash imo, e.g.:
>
> fn ext_keccak256(data_ptr: u32, data_len: u32);
> fn ext_blake2(data_ptr: u32, data_len: u32);
> fn ext_twox(data_ptr: u32, data_len: u32);

Should already make them future proof, aka compatible to the real host function? So, that in the future a contract could directly call the host function.

**Comment by seanyoung** [comment]
> @seanyoung In which cases can the version with the `result_ptr` _NOT_ be used in Solang? In ink! the versions with the `result_ptr` can _always_ be used and actually should be preferred over the functions without `result_ptr` for efficiency. ink! simply has a static buffer that is large enough to hold any of these hashes always and can be re-used as `result` buffer.
> 
> I am asking because in the end we will only opt-in for having one of these proposed interfaces.

The version with result_ptr is sufficient in all cases.

Note that it would be useful if the result_ptr can overlap with the input, so Solang can avoid allocations and hash in-place.

**Comment by Stefie** [comment]
> Should already make them future proof, aka compatible to the real host function? So, that in the future a contract could directly call the host function.

I was about to write that. Or at least following the same naming scheme, which would be `ext_${trait}_${function_name}_version_1` 

So:
```
fn ext_hashing_keccak_256_version_1(data_ptr: u32, data_len: u32);
fn ext_hashing_blake2_256_version_1(data_ptr: u32, data_len: u32);
fn ext_hashing_twox_256_version_1(data_ptr: u32, data_len: u32);
```

**Comment by Stefie** [comment]
The specs changed last week, changes can be found here https://github.com/w3f/polkadot-spec/blob/master/runtime-environment-spec/polkadot_re_spec-diffed-updates.pdf

**Comment by bkchr** [comment]
It is not only the naming, it is especially about the format the data is passed.
For `keccak_256` the function actually looks like:
```
fn ext_hashing_keccak_256_version_1(input: u64, res: u32);
```

`input` encodes the pointer and the length of the pointer.
`res` encodes the pointer to the 32 byte long array.

**Comment by Robbepop** [comment]
> It is not only the naming, it is especially about the format the data is passed.
> For `keccak_256` the function actually looks like:
> 
> ```
> fn ext_hashing_keccak_256_version_1(input: u64, res: u32);
> ```
> 
> `input` encodes the pointer and the length of the pointer.
> `res` encodes the pointer to the 32 byte long array.

Why is `input` a merged `(u32, u32)` type instead of simply 2 `u32`?
All the other `ext_` functions don't do this kind of merging even if they could.
I think we should probably stay aligned if we go down this path.

**Comment by Stefie** [comment]
From the new specs:

> Definition E.2. The Runtime pointer-size type is an i64 integer, representing two consecutive i32 integers in which the least significant one indicates the pointer to the memory buffer. The most significant one provides the size of the buffer. This pointer is the primary way to exchange data of arbitrary sizes between the Runtime and the Runtime Environment.

**Comment by bkchr** [comment]
> Why is `input` a merged `(u32, u32)` type instead of simply 2 `u32`? Also is `ptr` in hi-bits or lo-bits?

[Macro & trait magic](https://media1.tenor.com/images/d820481ef14b1cd2a16ff4e7660deb5f/tenor.gif?itemid=9239559) 

A macro generates the `ext_*` functions automatically from given rust functions and I can not do such a split into two parameters with a associated type from a trait.

The rust documentation to the system can be found [here](https://crates.parity.io/sp_runtime_interface/index.html).

**Comment by Robbepop** [comment]
I do not care too much about the low-level interface since the only really important detail is that the interface remains stable.
However, a critique that I see is that merging two `u32` into a `u64` is rather ... unconventional for C interfaces. Not sure if this is actually a bad thing though.
Also I wonder if it would make sense to instead perform this mapping from two `u32` to a merged `u64` in SEAL instead of contract side.

**Comment by bkchr** [comment]
I once talked to @pepyakin about it. The idea is that you could call the host function directly from the contract without going through the Sandbox in the future. This should give some nice performance improvements. 
But if that is something that will never come, we don't need to keep them compatible.

**Comment by pepyakin** [comment]
To give some more clarity, the improvements that we were talking about are the following: if the supervisor (seal-contracts) gives ability to call some of the Substrate Runtime Interface functions, e.g. `ext_hashing_keccak_256_version_1`, then we could allow contract jit-compiled code to call directly into the Sustrate Runtime Interface avoiding the supervisor wasm code altogether and avoiding the need of additional thunks or adapters. This has to do with the vague idea of sandbox V2 (not sure if we have something written anywhere though)

**Comment by Robbepop** [comment]
How about adding experimental support for https://github.com/BLAKE3-team/BLAKE3 for contracts?

**Comment by Stefie** [comment]
It's not implemented in Substrate/ Polkadot yet, so it would be way more complicated to add support for it because the other algorithms are already available as host functions and exposed via `sp_io`

**Comment by Robbepop** [comment]
> It's not implemented in Substrate/ Polkadot yet, so it would be way more complicated to add support for it because the other algorithms are already available as host functions and exposed via `sp_io`

Good point so better do this as a follow-up if we decide that we actually want support for BLAKE3. However, we can still use this thread in order to decide exactly this. :)

**Comment by Robbepop** [comment]
Since ink! is in need of this I started work on this to integrate the main `blake2_256`, `keccak_256` and `twox_256` as `ext_` functions.

**Comment by Robbepop** [comment]
Implemented by https://github.com/paritytech/substrate/pull/5326. Closed.
