### ISSUE TITLE
OnNewAccount not shown on separate line

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate#5272]
I think some refactoring has accidentally caused `OnNewAccount` to be now shown on the same line as `MigrateAccount` throughout the Substrate codebase (e.g. https://github.com/paritytech/substrate/blob/master/bin/node-template/runtime/src/lib.rs#L165).

**Comment by shawntabrizi** [comment]
It will be cleaned up when we remove MigrateAccount very soon. It is noted in Gav's original PR.
