### ISSUE TITLE
unify usage of `hex` and `rustc_hex` dependencies

### ISSUE THREAD

**Issue by niklasad1** [paritytech/substrate#5296]
The dependency tree is already large, I detected that we use two different libraries (hex and rustc_hex) for encoding/decoding hexadecimal "strings".

I don't know the reason why both are used maybe somebody could clarify?!

AFAIK `hex` works for slices which `rustc_hex` doesn't.

**Comment by gavofyork** [comment]
We're using both because `hex` has an actually good API and `rustc_hex` is in use by other dependencies that we don't have control over.

Having seen the crap that is added to our code when switching to `rustc_hex`, I would prefer to stick to `hex`.
