### ISSUE TITLE
Windows build failed for substrate 2.0-alpha4

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#5307]
Unfortunately, the latest substrate release (2.0 alpha4) build fails for windows platform according to our CI: https://github.com/airalab/robonomics/runs/516740243?check_suite_focus=true#step:7:1801 

```
error[E0277]: `*mut winapi::um::wbemcli::IEnumWbemClassObject` cannot be sent between threads safely
##[error]    --> C:\Users\runneradmin\.cargo\git\checkouts\substrate-7e08433d4c370a21\6a38fdc\client\service\src\builder.rs:1106:16
     |
1106 |         spawn_handle.spawn(
     |                      ^^^^^ `*mut winapi::um::wbemcli::IEnumWbemClassObject` cannot be sent between threads safely
```

* **rust**: nightly-2020-02-02

**Comment by bkchr** [comment]
That is an upstream issue, I reported it: https://github.com/GuillaumeGomez/sysinfo/issues/282
