### ISSUE TITLE
Thread 'ImportQueue' panicked at 'Externalities not allowed to fail within runtime

### ISSUE THREAD

**Issue by xuqzab** [paritytech/substrate#531]
polkadot node crashed on startup.  Google compute engine small instance ubuntu 18.04 with 1.7 gb memory.

instance-1:~$ polkadot
2018-08-09 18:25:06 Parity ·:· Polkadot
2018-08-09 18:25:06   version 0.3.0-d5de4bc6-x86_64-linux-gnu
2018-08-09 18:25:06   by Parity Technologies, 2017, 2018
2018-08-09 18:25:06 Chain specification: Krumme Lanke
2018-08-09 18:25:06 Node name: remarkable-pickle-0066
2018-08-09 18:25:06 Roles: FULL
2018-08-09 18:25:06 Generated a new keypair: fda28acd95ac1e4633c2c9b89cb785a66081bb6b77eac9dc90c32a21489d630f (5H
oGFsAp...)
2018-08-09 18:25:06 Initialising Genesis block/state (state: 0x609a…3f5a, header-hash: 0x6c5a…71cc)
2018-08-09 18:25:06 Best block: #0
2018-08-09 18:25:06 Local node address is: /ip4/0.0.0.0/tcp/30333/p2p/QmckHjhmgiQHJ3HfR5exSZMSkrjHcT6ox9U6KEd98mf
yfj
2018-08-09 18:25:07 Idle (0 peers), best: #0 (0x6c5a…71cc)
2018-08-09 18:25:07 Reconnected to telemetry server: wss://telemetry.polkadot.io/submit/
2018-08-09 18:25:07 New external node address: /ip4/35.196.80.109/tcp/30333/p2p/QmckHjhmgiQHJ3HfR5exSZMSkrjHcT6ox
9U6KEd98mfyfj
====================
stack backtrace:
   0:     0x55c50b1057fc - backtrace::backtrace::trace::h82a1e8b54f992c25
   1:     0x55c50b1047b2 - <backtrace::capture::Backtrace as core::default::Default>::default::h5ac4471b128f6b3a
   2:     0x55c50b104828 - backtrace::capture::Backtrace::new::h62f7e7eda275b141
stack backtrace:
   0:     0x55c50b1057fc - backtrace::backtrace::trace::h82a1e8b54f992c25
   1:     0x55c50b1047b2 - <backtrace::capture::Backtrace as core::default::Default>::default::h5ac4471b128f6b3a
   2:     0x55c50b104828 - backtrace::capture::Backtrace::new::h62f7e7eda275b141
   3:     0x55c50a9b38e0 - substrate_cli::panic_hook::panic_hook::h06d4b26d57f90cba
   4:     0x55c50a9b35f8 - core::ops::function::Fn::call::ha65591062b938644
   5:     0x55c50b235503 - std::panicking::rust_panic_with_hook::he4c3a67f6258a8f9
                        at libstd/panicking.rs:515
   6:     0x55c50b235259 - std::panicking::continue_panic_fmt::h156c04b2aea348c7
                        at libstd/panicking.rs:426
   7:     0x55c50b234f75 - rust_begin_unwind
                        at libstd/panicking.rs:337
   8:     0x55c50b291aab - core::panicking::panic_fmt::h0e6d5c6fb2a34dd6
   9:     0x55c50a7a2918 - core::result::unwrap_failed::hdfaa1e0af6f89796
  10:     0x55c50a8a9141 - <substrate_state_machine::ext::Ext<'a, H, C, B> as substrate_state_machine::Externalities<H>>::storage::h95ce49634211b75f
  11:     0x55c50a776f27 - substrate_state_machine::execute_using_consensus_failure_handler::hd02c3a76c5ffcdb5
  12:     0x55c50a6f980b - <substrate_client::call_executor::LocalCallExecutor<B, E> as substrate_client::call_executor::CallExecutor<Block, substrate_primitives::h
asher::BlakeHasher, substrate_primitives::rlp_codec::RlpCodec<substrate_primitives::hasher::BlakeHasher>>>::call::h3faac5e47a1deabd
  13:     0x55c50a85d6f4 - <substrate_client::client::Client<B, E, Block>>::authorities_at::h0e0e2d2b4be4c427
  14:     0x55c50a83cd04 - <substrate_client::client::Client<B, E, Block> as substrate_network::chain::Client<Block>>::import::hb7b13cde2e71efe1
  15:     0x55c50a714150 - substrate_network::import_queue::import_thread::h3ecc353fa466d0ed
  16:     0x55c50a6fa4b4 - std::panicking::try::do_call::heaa35a0b60463b06
  17:     0x55c50b258959 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  18:     0x55c50a780093 - <F as alloc::boxed::FnBox<A>>::call_box::hca8d88504668124c
  19:     0x55c50b232ada - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output=R> + 'a> as core::ops::function::FnOnce<A>>::call_once::h75e539106a648d39
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread::h88a639c99862a9f5
                        at libstd/sys_common/thread.rs:24
  20:     0x55c50b236075 - std::sys::unix::thread::Thread::new::thread_start::h7d7a420a78cfa84d
                        at libstd/sys/unix/thread.rs:90
  21:     0x7f15bdfb86da - start_thread
  22:     0x7f15bdac988e - __clone
  23:                0x0 - <unknown>
Thread 'ImportQueue' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x609ac0341c7cdee38e4ec08bc12b64cd83881a
42929ede606fdb26cf16fd3f5a"', libcore/result.rs:945
This is a bug. Please report it at:
    https://github.com/paritytech/polkadot/issues/new

**Comment by xuqzab** [comment]
Just tried it again.  The node ran a bit longer but then failed following : 2018-08-09 18:50:33 New external node address: /ip4/172.17.0.1/tcp/30333/p2p/QmckHjhmgiQHJ3HfR5exSZMSkrjHcT6ox9U6
KEd98mfyfj  with the same error message as above.  This may be a known issue, I'm new to the community but I think I saw a comment on chat about external node addresses on cloud vps being a problem.

**Comment by gavofyork** [comment]
will close - please reopen if you can find a way to reproduce.
