### ISSUE TITLE
Further Democracy refactoring

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#5322]
Democracy pallet is currently huge and there are a number of subsystems that could be split out into their own pallets to increase modularity, code-reuse, maintainability, &c.

- [ ] Refactor public proposal queue into its own pallet.
  - Support arbitrary number of tabling origins, not just public and "external" (council).
- [ ] Refactor Preimages into its own pallet.
  - There should be a composable way to allow other pallets to express the hashes for which pre-images are allowed to be given and whether or not it needs a deposit.
- ~Refactor DispatchQueue into its own pallet.~ Completed with the Scheduler PR.
- [x] Refactor proxy into its own pallet.
  - A proxy pallet would be configured at the runtime-aggregation level with a determinator to tell whether a given dispatchable is valid for proxying. Typically this would preclude transfer but include governance stuff.
- [x] More generally, introduce a new pallet to handle weight-aware scheduling of dispatches on certain blocks. It would have an internal API trait:
```
pub trait Scheduler<Call, BlockNumber> {
  type PeriodicItem;
  /// Guarantee that `what` will be dispatched, no earlier than block `when`. Higher `priority` values will be scheduled earlier than lower values.
  fn schedule(when: BlockNumber, priority: u8, what: Call);
  /// Guarantee that `what` will be dispatched at an average of once every `period` blocks.
  fn schedule_periodic(period: BlockNumber, what: Call) -> PeriodicItem;
}
```
The pallet which implements it should be able to give a configurable amount of block weight over to dispatching these items. If the items to be scheduled on a particular block cannot all be dispatched due to weight, then they should be dispatched in the block(s) immediately following.

**Comment by bkchr** [comment]
> Refactor DispatchQueue into its own pallet.

@coriolinus maybe you could work on this? We could reuse this in Cumulus.
