### ISSUE TITLE
node should print warning if it's a validator but doesn't have secret to any of the chains validators keys

### ISSUE THREAD

**Issue by snd** [paritytech/substrate#533]
currently it just seems to silently not validate blocks. a helpful warning log message would help with troubleshooting

**Comment by snd** [comment]
i see. in my tests it didn't print it. though i'm using polkadot::service directly and not spawning a node. will try to figure out why. might just be log settings

**Comment by gavofyork** [comment]
would be good to have `--validator` on-by-default and have extra logging (perhaps part of the informant) when taking part in consensus.

**Comment by gavofyork** [comment]
Will close in favour of doing #543 properly.
