### ISSUE TITLE
Slash Event could't find on Kusama Chain currently.

### ISSUE THREAD

**Issue by q615115160** [paritytech/substrate#5344]
I could't find the slash event on Kusama Chain currently.
Is there a bug?Please help me.

**Comment by bkchr** [comment]
What do you mean? I don't understand the question.

**Comment by q615115160** [comment]
> What do you mean? I don't understand the question.

In kusama Chain, the validator (address: GCiTn1UJQT9TE5iamqoKweVoWGRZr9DF8uKXL4cG98fXczf) has been slashed in era 551 and 552.But i cound't find the staking.slashed event related to it.

**Comment by bkchr** [comment]
How do you know that is was slashed?

**Comment by q615115160** [comment]
via chainstate page(https://polkadot.js.org/apps/#/chainstate),  query staking.validatorSlashInEra(EraIndex, AccountId): Option<(Perbill,BalanceOf)>.  I found that GCiTn1UJQT9TE5iamqoKweVoWGRZr9DF8uKXL4cG98fXczf has been slashed in era 551.

**Comment by alexxuyang** [comment]
> via chainstate page(https://polkadot.js.org/apps/#/chainstate), query staking.validatorSlashInEra(EraIndex, AccountId): Option<(Perbill,BalanceOf)>. I found that GCiTn1UJQT9TE5iamqoKweVoWGRZr9DF8uKXL4cG98fXczf has been slashed in era 551.

This point is to save the unapplied slash data in storage, not conduct the actual *SLASH* and emit the slash event. Kusama would defer the actual slash 28 eras later.

**Comment by alexxuyang** [comment]
> How do you know that is was slashed?

I think the question is, he can found the data in chainstate -> validatorSlashInEra, but later there isn't any related slash event emitted, 28 eras later.

**Comment by jacogr** [comment]
The Kusama council cancelled the deferred slashes, via majority approval, for all validators for these eras. There would not have been any events.
