### ISSUE TITLE
Transaction are marked Invalid, but still execute completely.

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#5355]
To start, here is a <2min screencast demonstrating the issue. https://youtu.be/s1_ITcHzWcw

I'm working on a [PoW chain ](https://github.com/substrate-developer-hub/recipes/pull/173) based on substrate v2.0.0-alpha.3 It compiles, and produces blocks as expected.

When an extrinsic is submitted to the chain, its status comes back as `Invalid`. I spent a while trying to determine why it was invalid, only to later realize that the transaction actually does execute to completion. In the screencast you can see a balance transfer marked as invalid, but the sender and receiver balances are updated correctly, and the `TransferSucceeded` event is emitted.

**Comment by bkchr** [comment]
Please try with latest master.

**Comment by tomusdrw** [comment]
Most likely fixed in https://github.com/paritytech/substrate/pull/5227

**Comment by JoshOrndorff** [comment]
Indeed this is fixed on latest master. Thank you.
