### ISSUE TITLE
Question / Curiosity about node peering.

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#5356]
This scenario was originally described here: https://github.com/substrate-developer-hub/recipes/issues/185

# Summary

I've reproduced this peering behavior with the [Substrate node template](https://github.com/substrate-developer-hub/substrate-node-template) (aura/grandpa), the Recipes' [kitchen node](https://github.com/substrate-developer-hub/recipes/tree/master/nodes/kitchen-node) (babe/grandpa), and the Recipes' in-progress [basic-pow node](https://github.com/substrate-developer-hub/recipes/tree/joshy-pow/nodes/basic-pow) (pow).

# Steps to Reproduce

Start three nodes as follows on the same machine (with appropriate modifications for other nodes).
```
# 1st node
$ ./target/release/basic-pow --alice --base-path /tmp/basic-pow-01
# 2nd node
$ ./target/release/basic-pow --bob --base-path /tmp/basic-pow-02
# 3rd node
$ ./target/release/basic-pow --base-path /tmp/basic-pow-03
```

# Observed Bevahior

Alice peers with both of the other nodes. The non-alice nodes do not peer together. Thus when Alice's node is killed the two remaining nodes have no peers and do not discover each other.

# Expected Behavior

All three nodes peer together. When Alice's node is killed a single non-partitioned network survives.

**Comment by bkchr** [comment]
I assue `alice` is a bootnode in the chain spec?

It looks like MDNS doesn't work for the other nodes. Best would be to collect `libp2p` logs with `-llibp2p=trace`.

@tomaka any other idea?

**Comment by tomaka** [comment]
What I think happens is that all three nodes try to listen on the same port.

When you start Alice, it works, but when you try to start Bob and Romuald (I'm going to name the third node Romuald) the listener fails to start.

Bob and Romulad don't connect to each other because there's no way they can connect.

**Comment by bkchr** [comment]
But shouldn't they find each other using MDNS?

**Comment by tomaka** [comment]
mDNS is a way for nodes to report to each other their IP address and port. But if they don't listen on any TCP port, they still can't connect to each other after discovering each other with mDNS.

It would work if we automatically opened a random port as a fallback if the configured one is busy, but we're not doing that at the moment.

**Comment by bkchr** [comment]
Ahhh, we don't open a port when the default one is blocked? That sounds odd...

**Comment by tomaka** [comment]
> Ahhh, we don't open a port when the default one is blocked? That sounds odd...

The problem is that it's not as trivial as it sounds now that `TcpListener::bind` is an asynchronous method (which is the case in both tokio and async-std). In order to not block the initialization, we don't know immediately if opening the port has succeeded.

https://github.com/libp2p/rust-libp2p/pull/1515 should normally make it possible to ultimately fix a couple of small issues.

**Comment by JoshOrndorff** [comment]
Confirmed @tomaka 's hypothesis. The specifying non-conflicting ports as follows solves the problem.

```
./target/release/node-template --alice --base-path /tmp/ALICE --port 12345
./target/release/node-template --bob --base-path /tmp/BOB --port 12346
./target/release/node-template --base-path /tmp/ROMUALD --port 12347
```

I'm satisfied knowing the explanation, and don't consider this something that needs fixed. Feel free to re-open this if you would like a tracking issue to fix it in the future.

cc @jimmychu0807

**Comment by jimmychu0807** [comment]
Thank you all for the investigation.
