### ISSUE TITLE
remove hidden feature flags

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#5368]
In client we have a feature flags, that _aren't_ exposed through their respective `Cargo.toml`s, like in sc-client-db, we have the 'hidden' `kvdb-rocksdb`-feature that some (like sc-service) activate but isn't known otherwise. The reason for that seems to be that the name of the feature is the same as for a dependency, which cargo prevents you from having. 

But not exposing the feature means that ~~neither `crates.io` nor `docs.rs` know about it and~~ they are harder to discover and thus go more often unnoticed. This is not the common convention. Instead we should rename the features and make them explicit.

refs #5367

**Comment by bkchr** [comment]
What is a hidden feature?

What you are describing is a feature of cargo. Not sure why `crates` and `docs.rs` should not be aware of this feature?

**Comment by gnunicorn** [comment]
with hidden I mean not exposed in the `Cargo.toml`. I am aware that it is possible to reference features in `#[cfg[features=` that aren't in the `Cargo.toml`, however not that this was an intentional design decision - as a typo in there is often an easily overlooked bug. I suppose that one could argue that any optional dependency could be referenced as a `feature` as well and while then using `feature=` in the name of the cfg-attr is unfortunate, this was legitimate behavior.

I'd still very much prefer to expose actual explicit features in the `Cargo.toml` and have them activate the corresponding dependencies rather than defining it through the "optional dependency as feature" approach. It makes them easier to discover and use.
