### ISSUE TITLE
Improve checking for peer id mismatch

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#5369]
https://github.com/paritytech/substrate/pull/5365 introduced an error when we can not connect to a bootnode, because the requested peer id is different than the one returned by the remote node.

However, the implementation is based on string matching. This should be improved. A solution could be to provide a trait that is added to the boxed error in `libp2p`. The trait could look like this:
```
trait IsPeerIdMismatch {
    /// Returns `Some(_)` if `self` is a peer id mismatch error. The returned peer id is the one obtained from the remote node.
    fn is_peer_id_mismatch(&self) -> Option<PeerId>;
}
```

The trait would than be used to check the error, instead of using string matching.

cc @tomaka

**Comment by tomaka** [comment]
Better is instead to not produce a `Box<Error>` but an enum.
The actual type that we `Box` is [this](https://docs.rs/libp2p/0.16.2/libp2p/core/nodes/network/enum.NetworkReachError.html). Returning it should be as simple as removing the `Box::new` [here](https://github.com/libp2p/rust-libp2p/blob/48e14d3247ca4f8668d542939630672205e6d13b/swarm/src/lib.rs#L471).

**Comment by bkchr** [comment]
Yeah this is even better :) I just thought that boxing the error maybe had some reason.

**Comment by tomaka** [comment]
Done in #5278
