### ISSUE TITLE
Print a warning when a bootnode or reserved node has a chain root mismatch

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5391]
It sometimes happens during development that you're trying to connect to your bootnodes without realizing that there's a state root mismatch.

The connections will fail, but in order to figure out why one has to dig through the `sub-libp2p` or `sync` logs. Instead there should be a clearer indication (a warning) when that happens.

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/commit/e796df1898d5ef1dc4321e53cfdd238f16cb8b72 this?
