### ISSUE TITLE
How to call substrate api in rust directly?

### ISSUE THREAD

**Issue by clearloop** [paritytech/substrate#5444]
## Desc

I would like to implement a `substrate attach` just like `geth attach`~ I've tried to use `polkadot-js/api` with node `REPL` directly, but not satisfied with the result.

They're too many `promise` in `polkadot-js/api` and it's difficult for me to handle them in `REPL`, me as a bad javascript coder.

I would like to work with `rust / wasm` directly, is there any advice can help me to reach this?

**Comment by bkchr** [comment]
Which api do you want to call? Can you please give a better description of what you want to achieve.

**Comment by clearloop** [comment]
> Which api do you want to call? Can you please give a better description of what you want to achieve.

Every one of them actually, just like what [rust-web3][0] does.

## Preview

My current stage is like this:

```
 𝝺 sh substrate.sh
> api
Promise {
  ApiPromise {
    registry: TypeRegistry {},
    __phantom: <BN: 0>,
    _consts:
     { babe: [Object],
       timestamp: [Object],
       transactionPayment: [Object],
       finalityTracker: [Object],
       contracts: [Object],
       society: [Object],
       claims: [Object],
       elections: [Object],
       kton: [Object],
       balances: [Object],
       staking: [Object],
       treasury: [Object],
       vesting: [Object] },
    _derive:
     { accounts: [Object],
       balances: [Object],
       chain: [Object],
       contracts: [Object],
       council: [Object],
       elections: [Object],
       imOnline: [Object],
       session: [Object],
       society: [Object],
       staking: [Object],
       technicalCommittee: [Object],
       treasury: [Object] },
    _extrinsics:
     { [Function]
       system: [Object],
       utility: [Object],
       babe: {},
       timestamp: [Object],
       // ...
    }
}
```
Just like a `substrate attach` instead of `geth attach`, I can not handle the `Promise` well, and want to write a command line tool in pure rust.

[0]: https://github.com/tomusdrw/rust-web3

**Comment by bkchr** [comment]
So you just want a library to call the RPC methods?

**Comment by clearloop** [comment]
> So you just want a library to call the RPC methods?

Yep

**Comment by bkchr** [comment]
Do you have seen [this](https://github.com/paritytech/substrate/blob/master/bin/node/rpc-client/src/main.rs)?

However, I assume that you actually want this: https://github.com/paritytech/substrate-subxt

**Comment by clearloop** [comment]
Thanks!  the [substrate-subxt][0] is actually what I want, but it seems not complete yet?


[0]: https://github.com/paritytech/substrate-subxt

**Comment by bkchr** [comment]
Best is to open an issue in the associated repository. I will close this issue now.
