### ISSUE TITLE
Events should be chucked 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#5466]
All events are stored under a single key. retrieving this potentially huge blob of data for cases such as account creation in genesis, or other potentially blocks that are bloated with lots of events, is a rocksdb killer; events should be chucked into smaller maps of vectors. See the `elections` pallet for a reference of this.

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/pull/5463

I think this is the better solution.

**Comment by kianenigma** [comment]
I know about the PR but from the internal discussion I understood that we want the chunking as well anyhow. Maybe I misunderstood?

**Comment by kianenigma** [comment]
related https://github.com/paritytech/substrate/issues/2619

**Comment by bkchr** [comment]
I still don't see how this should improve the performance. This increases the amount of storage accesses and we will not see 100k events.

**Comment by kianenigma** [comment]
Yeah this issue is subject to doubt. Yet I think the implementation of the abstraction is good feature to provide anyhow.

**Comment by bkchr** [comment]
The abstraction is a completely different topic^^
