### ISSUE TITLE
Uncaught error. Something went wrong with the query and rendering of this component.

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/substrate#5482]
when i oprate the collective module in https://polkadot.js.org/apps/#/, the error appear for example:
![议会模块](https://user-images.githubusercontent.com/45120344/78125778-16f56300-7444-11ea-9446-9f1a36369e58.png)

**Comment by bkchr** [comment]
Please open in the appropriate repository: https://github.com/polkadot-js/apps
