### ISSUE TITLE
Duplicate rustc-hex source

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#549]
I have troubles with building `v0.2.3` release via cargo vendor:

```
Caused by:
  found duplicate version of package `rustc-hex v2.0.0` vendored from two sources:

        source 1: https://github.com/rphmeier/rustc-hex.git#ee2ec40b
        source 2: registry https://github.com/rust-lang/crates.io-index  
```

**Comment by jiangfuyao** [comment]
Before cargo install, try: rm -rf .cargo/git/*

**Comment by akru** [comment]
Thank you @jiangfuyao, but this is not about typical installation.

This issue very similar to 
https://github.com/paritytech/polkadot/issues/376

**Comment by dvdplm** [comment]
Hi @akru, can you try to update your package with `cargo update -p rustc-hex`? That dependency recently moved from `https://github.com/rphmeier/rustc-hex` to crates.io and the v.2 version was released.

**Comment by akru** [comment]
Thank you, @dvdplm, but imperative way as you propose doesn't work for me.

 Way to reproduce issue:
```bash
$ cargo vendor
    Updating registry `https://github.com/rust-lang/crates.io-index`                                                                   
    Updating git repository `https://github.com/paritytech/jsonrpc.git`                                                                
    Updating git repository `https://github.com/tomaka/libp2p-rs`
 Downloading tokio-dns-unofficial v0.3.1
 Downloading rustc-hex v2.0.0
 Downloading tokio-current-thread v0.1.0
 Downloading rhododendron v0.3.0
error: failed to sync

Caused by:
  found duplicate version of package `rustc-hex v2.0.0` vendored from two sources:                                                     

        source 1: https://github.com/rphmeier/rustc-hex.git#ee2ec40b                                                                   
        source 2: registry https://github.com/rust-lang/crates.io-index                                                                

```

Possible fix:
```patch
diff --git a/substrate/rpc/Cargo.toml b/substrate/rpc/Cargo.toml                                                                       
index 9f257364..ed85a3b4 100644
--- a/substrate/rpc/Cargo.toml
+++ b/substrate/rpc/Cargo.toml
@@ -22,4 +22,4 @@ tokio = "0.1.7"
 [dev-dependencies]
 assert_matches = "1.1"
 substrate-test-client = { path = "../test-client" }
-rustc-hex = "2.0"
+rustc-hex = { git = "https://github.com/rphmeier/rustc-hex.git", version = "2.0", default_features = false }
```

@General-Beck please review.

**Comment by dvdplm** [comment]
Sorry for not being helpful! Can you try `rustc-hex = { git = "https://github.com/debris/rustc-hex.git", version = "2.0", default_features = false }` or even better just `rustc-hex = "2.0"`?

**Comment by General-Beck** [comment]
it's probably better to ask @rphmeier

**Comment by akru** [comment]
@rphmeier Can you help me?

**Comment by debris** [comment]
I guess the issue is caused by the fact that `cargo vendor` ignores `Cargo.lock` or runs `cargo update`. If you want to build it, just fetch repo from git and build it using cargo build

```
git clone git@github.com:paritytech/polkadot.git
cd polkadot
cargo build --release
```

it should work fine.

Meanwhile we will update all dependencies to use the latest version of rustc-hex.

**Comment by akru** [comment]
@debris What is important, it's actual for `v0.2.3` branch.

**Comment by gavofyork** [comment]
this looks resolved now... please reopen if still a problem
