### ISSUE TITLE
Validator was slashes for dont run the last upgrade. 0.2.4 update that step.

### ISSUE THREAD

**Issue by iammelea** [paritytech/substrate#551]
for validating today need
polkadot 0.2.4-7f0ed3a9-x86_64-linux-gnu.
update here 

Proper version

At the time of writing the cutting edge latest version is not appropriate and should not be used by validators. Only versions 0.2.1 and 0.2.2 work

thanks

**Comment by gavofyork** [comment]
Could you explain this in terms of expected behaviour and observed behaviour?
