### ISSUE TITLE
Allow registering custom request-response protocols

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5536]
Just like one can register notifications protocols, one should be able to register targeted request-response protocols.

I'm opening this issue to keep track of that feature.

cc'ing @mxinden @rphmeier as we discussed this in a meeting a couple of weeks ago (when the world was not on lockdown)

**Comment by tomaka** [comment]
For what it's worth, this issue is low-priority to me, but if there's an urgent need I can probably open a properly-tested PR in a day or two.

**Comment by rphmeier** [comment]
We haven't had issues so far emulating request/response over notifications-based protocols, so I also don't view this as high-priority.

**Comment by tomaka** [comment]
Can now be done after #6559 
The major obstacle to this now is to design an API.

**Comment by tomaka** [comment]
I briefly wanted to highlight that request-response protocols would show up in Grafana similar to this:

![Screenshot from 2020-07-14 13-09-57](https://user-images.githubusercontent.com/1412254/87419241-73375980-c5d3-11ea-93fe-150120b4cda6.png)

(one section like that per protocol)

Which is going to be very useful to figure out if things are working as expected.

**Comment by tomaka** [comment]
In #6634, starting a request to a node we're not connected to immediately fails. However, after chatting with Rob, there is a need for a function that tries to dial the node if we happen to not be connected to it.

**Comment by tomaka** [comment]
Reopening to address this comment:

> In #6634, starting a request to a node we're not connected to immediately fails. However, after chatting with Rob, there is a need for a function that tries to dial the node if we happen to not be connected to it.

**Comment by tomaka** [comment]
Note-keeping: the reason for being able to perform requests to nodes we're not connected to is because we are not necessarily guaranteed a peer slot on the target node.

If, instead, there exists a system that guarantees a peer slot, then this isn't needed.

**Comment by tomaka** [comment]
Last comment addressed through https://github.com/paritytech/substrate/pull/8008
Closing
