### ISSUE TITLE
error: Invalid value for '--telemetry-url <URL VERBOSITY>...': Verbosity level missing

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/substrate#5552]
Dear Substrate,

When i follow the tutorial "Start your own private network" and start the network with:
```
./target/release/node-template   --base-path /tmp/alice   --chain local   --alice   --po
rt 30333   --ws-port 9944   --rpc-port 9933   --telemetry-url ws://telemetry.polkadot.io:1024   --validator
```
I get the following error
```
error: Invalid value for '--telemetry-url <URL VERBOSITY>...': Verbosity level missing
```

**Comment by bkchr** [comment]
Use `--telemetry-url 'ws://telemetry.polkadot.io:1024 0'`. 

(`--help` gives you help on the expected format, but I also opened an issue to update the tutorials).
