### ISSUE TITLE
Code that uses runtime interface should not be used outside runtime

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#5554]
For example, `Verify` trait implementations for signatures calls runtime interface through `sp_io::crypto::*`, so using it outside of runtime is suboptimal and in most cases not needed.

**Comment by bkchr** [comment]
`Verify` trait is not the problem ;) The trait lives in `sp-runtime` and these are primitives for the runtime.

**Comment by NikVolf** [comment]
But the usage of this outside of runtime is a problem

**Comment by bkchr** [comment]
Yeah, I thought you wanted to say that `Verify` should be implemented differently, but that was probably some miss-interpretation by me.

**Comment by NikVolf** [comment]
Updated to avoid mis-interpretations 👍
