### ISSUE TITLE
How Do I stop blocks from being produced?

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/substrate#5565]
Is there any way to stop blocks from being produced within the runtime?
Is there a trait to implement?

**Comment by bkchr** [comment]
No. Why do you want to stop producing blocks?

**Comment by noahsalvadordenjo** [comment]
I would like to build my own consensus similar to pow

**Comment by bkchr** [comment]
There is no way to stop producing blocks. If you stop producing blocks, the chain is dead.

**Comment by xlc** [comment]
There is Manual Seal consensus engine, and the docs is been working at https://github.com/substrate-developer-hub/recipes/pull/202
