### ISSUE TITLE
Spawning tasks on Service does not match intended behavior

### ISSUE THREAD

**Issue by geigerzaehler** [paritytech/substrate#5581]
From the documentation of `Service::spawn_task` and `Service::spawn_essential_task` I get the impression that the former does not kill the process while the later does. And the code seems to indicate that a panic in an essential task will shutdown the node and return from `run_service_until_exit`.

In reality, a panic in a task spawned with `spawn_task` and `spawn_essential_task` results in the same behavior: The process exits before any cleanup happens. The culprit seems to be the panic handler from `sp_panic_handler`.

The behavior is present in the latest master.

**Comment by bkchr** [comment]
What you want is https://docs.rs/futures/0.3.4/futures/future/trait.FutureExt.html#method.catch_unwind

Panics are abnormal and nothing that should be catched by default.

**Comment by geigerzaehler** [comment]
> What you want is https://docs.rs/futures/0.3.4/futures/future/trait.FutureExt.html#method.catch_unwind

This does not work either. The panic handler from `sp_panic_handler` that exits the process is called _before_ the stack unwinds. This means the program never reaches the unwinding stage.

> Panics are abnormal and nothing that should be catched by default.

You right. I’m not trying to abuse panics for try/catch. I just want to make sure that the process shuts down properly when an essential task fails and does not shut down when a non essential task fails. This is the behavior that seems to be described in the docs. But it’s not what is happening at the moment.

**Comment by bkchr** [comment]
The point is that a panic, even in a non essential task is still a panic. The process should not recover from panics (outside of the runtime).

Panics should only be used for stuff that, if it goes wrong, brings down the whole process (as something is really badly broken).
