### ISSUE TITLE
Document and Calculate Weights for Pallets

### ISSUE THREAD

**Issue by apopiak** [paritytech/substrate#5596]
Issue to track progress on documenting weight for dispatch calls.

In order of benchmarking importance from Gav:
| docs  | weights | PR    | owner | pallet |
| :---: | :---:   | :---: | --- | ---    |
| [x]   | [x]     |  #5680 | @apopiak | Identity | 
| [x]   | [x]    |    #5446   |   @shawntabrizi     | Balances |
| [x]   | [x]     | #5593 #5775 | @shawntabrizi  | Timestamp |
| [x]   | [x]     |    paritytech/polkadot#1036   |   @shawntabrizi     | Polkadot/Claims |
| [x]   | [x]     |   #5708    | @shawntabrizi | Vesting |
| [x]   | [x]     | https://github.com/paritytech/substrate/pull/5771      | @thiolliere | Im Online |
| [x]   | [x]     |   https://github.com/paritytech/substrate/pull/5964    | @shawntabrizi | Staking |
| [x]   | [x]     | #5738 | @thiolliere | Session |
| [x]   | [x]     |  https://github.com/paritytech/substrate/pull/5845     | @kianenigma | Elections Phragmen |
| [x]   | [x]     |  https://github.com/paritytech/substrate/pull/5828     |   @thiolliere     | Democracy |
| [x]   | [x]     | #5802 | @apopiak | Collective |
| [ ]   | [x]     |   #5888 #5851     |   @tomusdrw @shawntabrizi     | Offences |
| [ ]   | [x]     | #5723 | @thiolliere | Treasury |
| [ ]   | [x]     |    #5787   |   @shawntabrizi     | Utility |
| [x]   | low-prio   | #5593 | @apopiak | Assets |
| [x]   | [x]     | #5593 #5888 | @shawntabrizi | System |

**Comment by thiolliere** [comment]
Should we extend this issue with information about:

> Create sufficiently accurate weight formula, based solely on call data (not on state!), refactoring dispatches as necessary.
> Implement weights through all pallets (FunctionOf).

of https://github.com/paritytech/substrate/issues/4961

**Comment by kianenigma** [comment]
I'll grab one or two that I can manage.

**Comment by apopiak** [comment]
I'm noted down as owner for `system`, but likely won't be able to get to it in time. So please grab it.

**Comment by thiolliere** [comment]
I take democracy but pallet is huge so if someone want to join I push my draft and we can divide extrinsics.

**Comment by thiolliere** [comment]
Did we forget society in our benchmark/weight formula effort ?
