### ISSUE TITLE
`pallet_timestamp::UnixTime::now` is called at genesis, invalid value returned: 0

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/substrate#5605]
How to impove this function? Switch `Time` to `UnixTime` is good but this can not be used at genesis.

**Comment by bkchr** [comment]
What you mean by improve? You call this method at genesis and the time is not set at genesis. Why do you need the time at genesis?

**Comment by AurevoirXavier** [comment]
There is timestamp in my bonding event. At genesis, some bonding happened.
