### ISSUE TITLE
Too many TCP connections open when authority-discovery is enabled

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5612]
While we are not "leaking" TCP connections anymore, the number of connections doesn't go below 200/300 when the authority discovery is enabled.

This should be figured out.

**Comment by tomaka** [comment]
Here are some details.

The following metrics have been pulled from nodes running on a recent commit of the Polkadot master branch.

Every ten minutes, the number of libp2p tasks increases by around 3000:
(note that the graph uses a logarithmic scale)

![Screenshot from 2020-05-20 16-38-08](https://user-images.githubusercontent.com/1412254/82459548-60fbdc00-9ab8-11ea-9d06-192267da3f9a.png)

Unsurprisingly, the CPU consumption of the network worker task unsurprinsingly peaks every 10 minutes as well:

![Screenshot from 2020-05-20 16-39-09](https://user-images.githubusercontent.com/1412254/82459677-82f55e80-9ab8-11ea-9776-e65fb47275b3.png)

And the number of times calling `NetworkWorker::poll` takes more than one second also peaks every 10 minutes (network worker in blue):

![Screenshot from 2020-05-20 16-40-07](https://user-images.githubusercontent.com/1412254/82459808-a5877780-9ab8-11ea-8cd3-74ff9f0c691d.png)

While I don't have a formal proof that these come from the authority discovery, the only thing that "ticks" every ten minutes, as far as I know, is the authority discovery.

**Comment by arkpar** [comment]
@mxinden could you take a look?

**Comment by tomaka** [comment]
Additionally, here is the number of active TCP connections on an average node:

In red and green, the established connections. In bright red, the number of pending attempts. In yellow, the number of connections that have recently been closed.

![Screenshot from 2020-05-20 16-43-18](https://user-images.githubusercontent.com/1412254/82460168-22b2ec80-9ab9-11ea-9ad0-3fb8ebdd4162.png)

If you except the 150 slots used for gossiping (I think our nodes are configured with 150 slots, not totally sure of that number), all the other connections are used for Kademlia purposes.

I opened this issue because I believe that this number is a bit high, but maybe this is a normal number by design, or by a bug somewhere that leaves connections open.

Tackling this issue consists in figuring out whether this is normal, and if not, decrease the number.

**Comment by tomaka** [comment]
Might be fixed by https://github.com/libp2p/rust-libp2p/pull/1698

**Comment by tomaka** [comment]
I believe this is now fixed. See the description of https://github.com/paritytech/polkadot/pull/1807#issue-501584636 for details.
