### ISSUE TITLE
Prometheus metrics get error 

### ISSUE THREAD

**Issue by gmajor-encrypt** [paritytech/substrate#5615]
prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8

substrate version : https://github.com/paritytech/substrate/commit/dd97b1478b31a4715df7e88a5ebc6664425fb6c6

23|  | 2020-04-13 03:09 +00:00: level=warn ts=2020-04-13T03:09:52.144Z caller=scrape.go:987 component="scrape manager" scrape_pool=substrate_node target=http://127.0.0.1:9615/metrics msg="appending scrape report failed" err="write to WAL: log samples: create new segment file: open data/wal/00000052: no such file or directory"

**Comment by bkchr** [comment]
@mxinden any idea?

**Comment by mxinden** [comment]
> 23| | 2020-04-13 03:09 +00:00: level=warn ts=2020-04-13T03:09:52.144Z caller=scrape.go:987 component="scrape manager" scrape_pool=substrate_node target=http://127.0.0.1:9615/metrics msg="appending scrape report failed" err="write to WAL: log samples: create new segment file: open data/wal/00000052: no such file or directory"

@gmajor-encrypt do I understand correctly that this is a log line of a Prometheus server? Prometheus time series database is using a write-ahead-log (WAL) to persist scrape data for cases of failure before the actual flush to the long term storage is happening. It seems like Prometheus was not able to find the current WAL log file.

If this issue continues to occur I would suggest reaching out in https://groups.google.com/forum/#!forum/prometheus-users for help.

I am going to close this issue as I don't think it is related to Substrate. If you think differently, please reopen it. Either way, thank you for taking the time to report the issue.
