### ISSUE TITLE
Move the tasks in transaction pool and import queue to the service

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5621]
At the moment the import queue and transaction pool spawn tasks on their own threads:

- https://github.com/paritytech/substrate/blob/8991aab9d98da49e3a7e608cb0a0162b610e25c7/primitives/consensus/common/src/import_queue/basic_queue.rs#L108
- https://github.com/paritytech/substrate/blob/29fa243d279789373658a60ad226a7f32d5595e5/client/transaction-pool/src/api.rs#L91

As far as I know, this is the case for the import queue because it is a CPU-intensive non-asynchronous task, and it is the case for the transaction pool because the change wasn't super straight-forward for a reason I forgot.
But now that tokio/async-std have executors that move blocking tasks to a different threads pool, there is no reason to not put blocking tasks in there as well.

Apart from these two, all of the other components of Substrate and Polkadot spawn their task using the service: https://github.com/paritytech/substrate/blob/8991aab9d98da49e3a7e608cb0a0162b610e25c7/client/service/src/task_manager.rs#L155
It would be a good idea in my opinion to finish the change and move *everything* as tasks into the service.

The benefits is that it automatically plugs the `on_exit` thing, and that after https://github.com/paritytech/substrate/pull/5619 it would be possible to see stats about them in Prometheus.

cc @gnunicorn

**Comment by NikVolf** [comment]
Making transaction validation to compete for cpu resources with block import might be an attack vector on node, so we might want reconsider.

**Comment by tomaka** [comment]
I thought that tokio was automatically moving blocking tasks to a separate threads pool, but I might be mistaken here because the documentation doesn't mention this.

However the main point of the issue is that we should IMO spawn things through the service. Having them use the "main" tokio scheduler is not necessarily important. It might indeed be a good idea to explicitly split between "potentially blocking" and "not supposed to be blocking".

In other words, we could probably:

- Add another field `block_task_executor` [here](https://github.com/paritytech/substrate/blob/88248c040fd0a0ff004f448fc8c47fdf000b653e/client/service/src/config.rs#L41).
- Then pass it as parameter [here](https://github.com/paritytech/substrate/blob/5fcd53350d246d005950173accba6ba832ad7463/client/service/src/task_manager.rs#L93).
- Turn [this `Sender<Future>`] into a `Sender<(Future, bool)>` indicating whether the task is blocking.
- Add a `SpawnTaskHandle::spawn_blocking` method.

**Comment by NikVolf** [comment]
It is not necessary refers to the notion of "blocking". It can just so happen, that there are so many transactions that we can't even validate them all, and we shouldn't starve block import in this case. Now in this scenario we just load 2 cores. Using service for spawning validation tasks for transactions will load all cores?

**Comment by tomaka** [comment]
Oh right, this might be it:

> it is the case for the transaction pool because the change wasn't super straight-forward for a reason I forgot.

**Comment by tomaka** [comment]
It could still be doable in theory, by having futures wait for each other so that there are never more than 2 doing actual work at the same time (essentially reproducing what happens right now).
But that's a more involved change, and it's debatable whether it's worth it.

**Comment by tomaka** [comment]
So, we've got a design issue related to the CLI and the Service's "tasks manager":

When start a block import with the CLI (`./polkadot import-blocks ...`), the CLI code builds a prototype for a full client, a `ServiceBuilder`.

This `ServiceBuilder` initializes the "tasks manager", which includes a channel of tasks pending to be spawned. These tasks are then transmitted to the executor only in `TasksManager::process_receiver`.

But when doing the CLI block import, we actually never finish the `Service`, and the `TasksManager` is simply silently dropped with all its pending tasks still in it.

**Comment by arkpar** [comment]
Import queue must be prioritized above all other tasks. That's the main reason it uses dedicated threads currently.
