### ISSUE TITLE
Fixed128 improvements

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5622]
Followup of #5614

Put `Fixed128` behind a feature flag and make `primitive_types` optional dependency.
https://github.com/paritytech/substrate/pull/5614#discussion_r407921803

Implement unchecked ops (`ops::Add` etc) behind a feature flag.
https://github.com/paritytech/substrate/pull/5614#discussion_r407508240

**Comment by shawntabrizi** [comment]
I will introduce these changes into my pr https://github.com/paritytech/substrate/pull/5446
