### ISSUE TITLE
`FixedPointNumber` trait

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#5625]
Fixed128 and Fixed64 have an inconsistent API.

We need to define a shared trait for fixed point numbers in Substrate, and optimistically also introduce a macro which allows us to automatically create new fixed point types with different levels of accuracy.

- [ ] Create, Review, Merge `FixedPointNumber` trait

- [ ] Update Fixed64 and Fixed128 to use the new trait

- [ ] Create a macro which allows for customization of the inner type, oversized type, and the DIV constant.

**Comment by kianenigma** [comment]
@marcio-diaz what's the status here? if not being worked on, I can help. 

>  Create a macro which allows for customization of the inner type, oversized type, and the DIV constant.

and FWIW I am still against this :D

**Comment by marcio-diaz** [comment]
It's in progress, I'll push the code soon. The trait is implement for both, currently I'm adding tests and probably I'll do some benches.

**Comment by shawntabrizi** [comment]
@marcio-diaz what will you be benchmarking?
