### ISSUE TITLE
Listen on IPv6 by default

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5691]
cc #5687
We had to revert listening by default because of benign libp2p errors.

**Comment by tomaka** [comment]
To expand a little bit, there are two issues:

- My logs are spammed with warnings when listening on IPv6: https://github.com/libp2p/rust-libp2p/issues/1552

- Before #5687, we were trying to listen both on `/ip4/0.0.0.0/tcp/<port>` and `/ip6/::/tcp/<port>`. This would try to open two sockets, and one of them would fail to open because of the port conflict.
It should be enough, normally, to *only* listen on IPv6, right? The kernel would then also automatically accept IPv4 connections on that port, if I'm not mistaken.

**Comment by bkchr** [comment]
We probably need to set [this](https://docs.rs/net2/0.2.33/net2/struct.TcpBuilder.html#method.only_v6) this to `false`.

**Comment by twittner** [comment]
> We probably need to set [this](https://docs.rs/net2/0.2.33/net2/struct.TcpBuilder.html#method.only_v6) this to `false`.

By default `IPV6_V6ONLY` is `false` on Linux and `true` on Windows (according to https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ipv6-socket-options). It is probably a good idea to explicitly set this option to `false` to ensure consistent behaviour accross platforms.

**Comment by twittner** [comment]
I have opened https://github.com/libp2p/rust-libp2p/pull/1555. Instead of setting IPV6_V6ONLY to false I set it to true. It allows us to bind two sockets to the same port, avoids mixed comparisons and works on more operating systems (on those that do not (want to) support IPv4-mapped IPv6 addresses such as OpenBSD).
