### ISSUE TITLE
When syncing, add target block via RPC

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/substrate#5727]
When syncing a node, the logs show a nice
```
⚙️  Syncing, target=#199957 (2 peers), best: #512 (0x5895…614e), finalized #512 (0x5895…614e), ⬇ 33.3kiB/s ⬆ 2.4kiB/s
```

However, I cannot find this `target=#...` number via RPC. In [light-ui](https://github.com/paritytech/substrate-light-ui/), where syncing can take some time, I'd like to show the target block.

I'm not 100% sure where to put it, maybe in `system_health`?

```js
{
  peers: number,
  shouldHavePeers: boolean,
  isSyncing: boolean,
  // add this field:
  syncing: { startBlock: number, currentBlock: number, targetblock: number } | null
}
```

Note: I copied how eth did it, for inspiration: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_syncing

pinging maybe @tomusdrw @ascjones?

**Comment by tomaka** [comment]
That should rather be named something like `bestNetworkBlock`, so that it's more precisely defined, no?

**Comment by tomusdrw** [comment]
Yeah, I was thinking `system_syncState` - I don't think that `health` should need so many details.

**Comment by marcio-diaz** [comment]
Isn't it possible to use `chain_subscribeNewHeads` to ge the `number`?

**Comment by tomaka** [comment]
So Ethereum does this:

```// Request
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'

// Result
{
  "id":1,
  "jsonrpc": "2.0",
  "result": {
    startingBlock: '0x384',
    currentBlock: '0x386',
    highestBlock: '0x454'
  }
}
```

Any objection to doing exactly the same thing, except with regular JavaScript numbers and not hexadecimal?
