### ISSUE TITLE
Do not resolve DNS in Observable Address Response

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#5756]
We currently accept any MultiAddress as in the observable address response. Using DNS4/6 this might lead to leaking information about our DNS configuration, thus it is not common practice to use DNS in these cases. If we receive a DNS response, we should simply discard and not resolve it.

**Comment by mxinden** [comment]
Adding `P7-nicetohave` label. See original `w3f` issue for details.

**Comment by tomaka** [comment]
What's the "observable address response"?

**Comment by tomaka** [comment]
Note keeping: an "observable address response" is one of the addresses reported by the `identify` protocol.

**Comment by tomaka** [comment]
cc @twittner Since you already did https://github.com/paritytech/substrate/pull/5735, would you mind looking into this?

**Comment by tomaka** [comment]
Closing as "won't fix"
