### ISSUE TITLE
With new lazy_payout implementation `Staking::MaxNominatorRewardedPerValidator` could be increase or maybe removed

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#5765]
In staking `T::MaxNominatorRewardedPerValidator` was introduced with the first version of lazy_payout where each nominator would claim the reward for each of its nomination. Thus the exposure of the validator would be queried as much time as its nominations

Now that it is only queried one time inside staker_payout I think this constraint doesn't hold anymore. Thus we could remove this limit.

Though I'm not sure the limit had any other reason, in this case maybe it could be increased.

@shawntabrizi

**Comment by thiolliere** [comment]
ok it actually serve a purpose, in the new version validator may wants to have this limit if it doesn't want to pay the fee for rewarding too much small nominators.

**Comment by adamdossa** [comment]
Sorry to comment on a closed issue, but just wanted to check on some of the details here. AFAICT the `MaxNominatorRewardedPerValidator` is still relevant with lazy payouts as it bounds the cost of storage updates in `do_payout_stakers`. So if you have too many nominators, it may be the weight of this transaction exceeds the maximum block weight... (even if the validator is willing to pay the transaction fee).

**Comment by thiolliere** [comment]
> So if you have too many nominators, it may be the weight of this transaction exceeds the maximum block weight... (even if the validator is willing to pay the transaction fee).

Yes this is one purpose, the other purpose is that the validator might not be willing to pay huge transaction fees if it is to reward nominator with very small stake.
