### ISSUE TITLE
Add a utility that turns a node private key into a PeerId without starting the node

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5778]
It's a commonly requested feature. Taking a secret file, we should produce the `PeerId`.

The utility would be very simple to write, but considering that this is mostly a tool for external people, its existence would have to be properly documented and I have no idea where to put it in the source tree.

**Comment by tomaka** [comment]
After some Riot discussions, let's put that in `subkey`.
`subkey` already allows generating a network key, and that's a very similar functionality.

**Comment by wpank** [comment]
Something like:

`subkey inspect-node-key <key_file>` would be very helpful :smiley:
