### ISSUE TITLE
Fix randomness computation 

### ISSUE THREAD

**Issue by burdges** [paritytech/substrate#5785]
At https://github.com/paritytech/substrate/blob/master/frame/babe/src/lib.rs#L577 we use `RawVRFOutput` directly for randomness, which should never happen. 

You should call `schnorrkel::VRFInOut::make_bytes` similar to what [`sc_consensus_babe::authorship::check_primary_threshold`](https://github.com/paritytech/substrate/blob/master/client/consensus/babe/src/authorship.rs#L95) does.  In schnorrkel, we produce these `VRFInOut`s inside `vrf_sign*` and `vrf_verify*`, so you could call `make_bytes` once on block import, and save those bytes as non-serialized block metadata.

If you'd rather reproduce those bytes again elsewhere, then you recreate the VRFInOut by first creating the transcript with [`sc_consensus_babe::authorship::make_transcript`](https://github.com/paritytech/substrate/blob/master/client/consensus/babe/src/authorship.rs#L122) and calling [`schnorrkel::PublicKey::vrf_attach_hash`](https://github.com/w3f/schnorrkel/blob/master/src/vrf.rs#L196)/[`schnorrkel::VRFOutput::attach_input_hash`](https://github.com/w3f/schnorrkel/blob/master/src/vrf.rs#L249) with the signers public key and the `schnorrkel::VRFOutput` (the actual bytes being used here).

I should apologize for not making this aspect of schnorrkel as missuse resistant as possible, but exposing `VRFOutput` separate from `VRFProof`, and exposing these `VRFInOut`s simplified the interface dramatically.  I should rename `schnorrkel::VRFOutput` to `VRFPreOutput` really.

**Comment by burdges** [comment]
I've renamed the `VRFOutput` type to `VRFPreOut` in https://github.com/w3f/schnorrkel/commit/030e68612313e7e3d103e14a1437acdcc1efaa49 to reduce confusion in future, but I have not yet published an ew version and any update should be completely orthogonal to https://github.com/paritytech/substrate/pull/5788

**Comment by DemiMarie-parity** [comment]
Is this a security hazard @burdges?

**Comment by burdges** [comment]
We safe from any attacks I know because Ristretto [accepts](https://ristretto.group/formulas/index.html) only one point encoding.   It'd degrade the randomness by a factor of 8 if we'd used another VRF like VEd25519 instead:  https://github.com/w3f/ring-vrf/issues/15

We do need Wei's fix in #5788 because (a) the `make_bytes` methods give us the VRF's PRF-like assumptions in the security proof, and (b) validators could conceivably choose related keys.  We
forbid (b) but it becomes more likely if folks play games like https://github.com/w3f/General-Grants-Program/pull/273
