### ISSUE TITLE
Separate validation logic in its own process

### ISSUE THREAD

**Issue by hodl-dot-farm** [paritytech/substrate#5799]
When you want to turn your full node into a validator node, you must restart it.

Separating the validation logic into its own process (with shared access to the node storage) would enable activation of the validating logic without restarting the node.

That would be useful in a HA situation, where you have two full nodes, with an elected master that performs validation. When a second node becomes the master, it would be good to instantly start validating without having to restart the process and reestablish all the p2p connections, etc... Especially with a 6 sec block time you can not afford a full restart.

Tezos for example is architected this way.

If there is another way of achieving the same result (for example sending a signal to the process to start/stop validation) that would also work.

**Comment by xlc** [comment]
you can just run both nodes as validator. when you want to switch, use RPC to insert the correct session key and it should work.

**Comment by hodl-dot-farm** [comment]
Makes sense, thanks.
