### ISSUE TITLE
Unsound use of Vec::set_len()

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/substrate#5819]
[This code](https://github.com/paritytech/substrate/blob/9a4edfc29d510068aaaa52ad0ba4372703e1363f/primitives/state-machine/src/ext.rs#L623) creates a `Vec<u8>` and sets its length without initializing it.  This may be undefined behavior.

**Comment by bkchr** [comment]
No, that isn't undefined behavior. One line above we allocate the correct amount. Please read the code before opening such issues.

**Comment by DemiMarie-parity** [comment]
@bkchr The problem is that the `Vec` contains uninitialized memory.

**Comment by bkchr** [comment]
Why is that a problem? Everything is overridden below.

**Comment by DemiMarie-parity** [comment]
It still may technically be undefined behavior, although I am not sure.  if `u8` had invalid values it would definitely be undefined behavior.
