### ISSUE TITLE
can vote (second) unlimited time for my own proposal

### ISSUE THREAD

**Issue by illlefr4u** [paritytech/substrate#5820]
I can vote (second) an unlimited number of times for my own proposal (see screenshot).
Despite the fact that this does not directly contradict the wiki, it seems to me that this is not how the system was conceived (including the UI prohibits vote for your own proposal or voting for someone else’s proposal a second time).

If this is nevertheless allowed by the system architects, then it is better to explain this on the Polkadot wiki as well.

![prop18_3](https://user-images.githubusercontent.com/21253681/80316373-d2a37b80-87d3-11ea-8b1b-71892a82c0aa.png)

**Comment by Swader** [comment]
This does not apply only to own proposals, but to any proposal.

**Comment by kianenigma** [comment]
See the linked issue in the polkadot wiki; this is not a bug. If you own 10x amount of a proposal's bond, you have the right to second it 10 times. Even if the system would have enforced different accounts, you could easily split tokens into different accounts and do it from there.
