### ISSUE TITLE
Nodes should only be inserted in the DHT of their chain

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5825]
We currently maintain one "legacy" global DHT, and one DHT per chain we are interested in.
However, at the moment, whenever we connect to a node, we immediately insert it in all of our DHTs.

This is wrong, and we should only insert a node after we know that it belongs to the correct chain.

**Comment by tomaka** [comment]
Update: the "legacy" global DHT has been removed, but this issue is still more than relevant for the "per-chain" DHT.

**Comment by mxinden** [comment]
Further discussion of restricting peers in the Kademlia routing table happens in https://github.com/libp2p/rust-libp2p/issues/1560.

**Comment by tomaka** [comment]
cc https://github.com/libp2p/rust-libp2p/issues/1611

**Comment by tomaka** [comment]
Should be fixed by https://github.com/paritytech/substrate/pull/6549
