### ISSUE TITLE
Block requests sometimes take a lot of time

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#5831]
When syncing Kusama from scratch for example, one can see the sync speed go up and down a lot. The reason for that is that we spend a lot of time waiting for block responses.

This should be investigated.

**Comment by tomaka** [comment]
0.7.32 includes the metrics added by https://github.com/paritytech/substrate/pull/5811 and will be helpful to understand that

**Comment by tomaka** [comment]
I can now see on Grafana that [the `on_block_request` method](https://github.com/paritytech/substrate/blob/c0ccc24d02080ab4fbb2c65440327fc72acb6c42/client/network/src/block_requests.rs#L342-L449) usually takes less than 1ms, but occasionally takes up to 4-6 seconds for an unknown reason.

We've also deployed https://github.com/paritytech/substrate/pull/5854 on two nodes, and I can see that the networking overhead is at a constant 150-200ms. This is actually pretty high in the absolute, and should also be fixed. I suppose it's because the network worker is quite busy.

**Comment by arkpar** [comment]
This does not explain the 40 second timeouts that happen all the time when syncing. Would be good to have a sync log for a machine that has `on_block_request` taking more than 40 seconds.

**Comment by tomaka** [comment]
Update: from the serving side, the fix to the "network freezes" seems to have improved the situation.

I think the next step here would be to continue smoothing the network events-propagation/performances story, and see if it still happens afterwards.

Even if the network events-propagation/performance issue is not directly responsible, fixing it first would eliminate the noise.

**Comment by tomaka** [comment]
I feel like this was caused by the network worker being overloaded. https://github.com/paritytech/substrate/pull/6692 should considerably improve the situation. We'll see after it has been deployed.

**Comment by tomaka** [comment]
I think this is fixed. While it's hard to definitely claim that blocks requests time is correct, here's for example the 99% percentile of block requests time over 48 hours:

![image](https://user-images.githubusercontent.com/1412254/106127055-71dc1180-615e-11eb-8889-afc137437810.png)

The occasional peak is most likely just a timeout.

**Comment by tomaka** [comment]
Perhaps more important, the 99th percentile of the time between receiving a request and sending back an answer:

![image](https://user-images.githubusercontent.com/1412254/106127420-d6976c00-615e-11eb-9150-2b2113086579.png)

There is an occasional peak, which is a bit intriguing, but it's overall flat.
