### ISSUE TITLE
BTreeSet vs sorted Vec?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5835]
Sorted `Vec` are used in many pallets. 

e.g.
https://github.com/paritytech/substrate/blob/c82a0f7b58c8c3f204cb10d4a03cd4855b236c29/frame/collective/src/lib.rs#L119

What are the reasons of prefer sorted `Vec` over `BTreeSet`?

**Comment by burdges** [comment]
A sorted `Vec` would be faster if you make the data once and read it many times, while `BTreeSet` handles churn much better.

**Comment by bkchr** [comment]
De-serializing a `BTreeSet` can be slower than a `Vec`. (Really depends on the implementation of `BTreeSet`).

Accessing the `Vec` is also much faster, you can just access by index.

**Comment by xlc** [comment]
Thanks for the answers.

I guess it means https://github.com/open-web3-stack/open-runtime-module-library/issues/149 will be useful.
