### ISSUE TITLE
Test case not working as expected: `nominators_also_get_slashed`

### ISSUE THREAD

**Issue by maxsam4** [paritytech/substrate#5838]
The intent of https://github.com/paritytech/substrate/blob/268450a946d3d7346ac0052d211009cb82316f1c/frame/staking/src/tests.rs#L536

is to make sure that nominators also get slashed but in the test, `nominator_slash` is equal to 0 and the test is checking that a slash of 0 is applied which is equivalent of no slash at all.

In addition, the `others` vector in the validator's exposure is an empty array which suggests that no nominators are going to be slashed.

I'm not sure if it's just some misconfigured test case or a bug in the code but in any case, I don't think the test case is verifying what it was meant to verify.

**Comment by maxsam4** [comment]
Here are the changes that I mentioned above that make the test fail: https://github.com/maxsam4/substrate/commit/84b756c94f253ec553405a97b13e34e85649c7a0

With 105% slashing, the validator loses 100% of their stake, and the nominator loses 0% (test fails).
At 5% slashing, the validator loses 5% of their stake and the nominator loses 0% (test passes).

**Comment by bkchr** [comment]
CC @kianenigma

**Comment by kianenigma** [comment]
I haven't looked into it in detail but it could very well be the case. Many of the staking tests are 
1. old 
2. not correctly wired together
3. don't uphold ot their standard and similar to your example, even if their pre-condition is not met, the do not panic. 

I'll take a look soon, thanks for raising it. 

related: https://github.com/paritytech/substrate/issues/5244

---- 

> In addition, the others vector in the validator's exposure is an empty array which suggests that no nominators are going to be slashed.

Yeah in this case nominators don't even exist to be slashed. 

> I'm not sure if it's just some misconfigured test case or a bug in the code but in any case, I don't think the test case is verifying what it was meant to verify.

Most likely just a misconfiguration.

**Comment by maxsam4** [comment]
Hey @kianenigma, did you get a chance to look at it?

**Comment by kianenigma** [comment]
Done.
