### ISSUE TITLE
Name event parameters

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5913]
Currently event parameters are unnamed, so the only way to know the meaning of each value is by looking at the type and docs.

It will be good if there is a way annotate the parameter name in metadata so SDK can generate named accessor.

For now we are going to try to parse the doc comments to look something like `(from, to, value)` to get the name, but it does not always work.

https://github.com/paritytech/substrate/blob/7217ab64596e7f5a876546a46d2499915bf645b2/frame/balances/src/lib.rs#L226

**Comment by bkchr** [comment]
This can come with https://github.com/paritytech/substrate/issues/5678
