### ISSUE TITLE
Maintain transactions bloom filter for each peer

### ISSUE THREAD

**Issue by NikVolf** [paritytech/substrate#5921]
Then we won't need to store which peer got which transaction. We just check against bloom filter instantly to see if particular peer hasn't ever saw particular transaction.

This should save us 128kb per peer and also lift 4096 known transactions per peer limitation.

**Comment by arkpar** [comment]
Bloom filter will either get saturated quickly or grow beyond 128kb size eventually.

**Comment by NikVolf** [comment]
> Bloom filter will either get saturated quickly or grow beyond 128kb size eventually.

No, with acceptable probability, bloom filter capacity per size is much greater than storing all known hashes per peer in map.

**Comment by arkpar** [comment]
> > Bloom filter will either get saturated quickly or grow beyond 128kb size eventually.
> 
> No, with acceptable probability, bloom filter capacity per size is much greater than storing all known hashes per peer in map.

But we don't store all known hashes, do we?

https://hur.st/bloomfilter/?n=100000&p=1.0E-3&m=&k=
with these parameters 175kb bloom filter will saturate after 100000 transactions. Which is a realistic number for a long running node on a busy blockchain, such as ethereum.

**Comment by NikVolf** [comment]
> But we don't store all known hashes, do we?

We don't but we don't store enough. 4096 transactions is barely one full block and it takes 128kb already. 

> with these parameters 175kb bloom filter will saturate after 100000 transactions. Which is a realistic number for a long running node on a busy blockchain, such as ethereum.

Yes, and to store note those 100,000 transactions like note them now it will require 3.2 Mb/peer + hashmap overhead ~ 18x as much?

Saturation over node running time can be handled by using 2 filters rotation.

**Comment by arkpar** [comment]
> Yes, and to note those 100,000 transactions like we note them now it will require 3.2 Mb/peer + hashmap overhead ~ 18x as much?

Well, you could just store 40 hash bits instead of 256 bits and get the same collision chance as bloom filter false positive probability.  

Another problem with bloom filter is that with false positive you might end up not sending a transaction to a peer that needs it. And if everyone uses the same bloom filter hash function, that transaction will never be propagated.
Salting the hash does not resolve this completely, if transaction is **created** on a machine, that happens to have the same bloom hash output as some other previous transaction, it won't be sent out.

**Comment by arkpar** [comment]
I don't really see a problem with the current hard-coded limit. There's no sense in tracking more than transaction pool capacity anyway. If a previously invalidated transaction enters the transaction pool again it would be rejected and won't be attempted to be propagated anyway.

**Comment by NikVolf** [comment]
> And if everyone uses the same bloom filter hash function, that transaction will never be propagated.

This is not a problem, each peer has it's own salt, so it will be send to some peers anyway.

But otherwise yeah, good arguments.

**Comment by burdges** [comment]
https://github.com/w3f/research-internal/issues/141
