### ISSUE TITLE
Asyncify keystore

### ISSUE THREAD

**Issue by rakanalh** [paritytech/substrate#5931]
This is part of the work that has to be done in order to implement #4689. 

The goal of this issue is to:
1. convert the trait `BareCryptoStore` to define async functions.
2. Rename the current `Store` in sc_keystore to `LocalStore` and update the interface accordingly.

#4689 Would then introduce RemoteStore which implements `BareCryptoStore` and is able to relay key management to the remote signer.

I am separating both issues so that i can merge smaller, easier to merge PRs and to prevent the scope of the parent issue from getting bigger.

**Comment by burdges** [comment]
How is the keystore structured now?  It already does the signing itself?

**Comment by rakanalh** [comment]
The keystore currently lives in it's own crate here: https://github.com/paritytech/substrate/blob/master/client/keystore/

And through #4925, we made signing go through the keystore instead of using the pairs directly to enable being able to introduce a remote keystore.

**Comment by rakanalh** [comment]
This was done in #7000
