### ISSUE TITLE
Could not compile `honggfuzz` Windows 10

### ISSUE THREAD

**Issue by qalqi** [paritytech/substrate#5957]
Followed all steps
1) https://substrate.dev/docs/en/overview/getting-started/#getting-started-on-windows
2) https://substrate.dev/docs/en/overview/getting-started/#get-the-source

At `cargo build --release`

```
honggfuzz-rs does not currently support Windows but works well under WSL (Windows Subsystem for Linux)
 --> C:\Users\X2\.cargo\registry\src\github.com-1ecc6299db9ec823\honggfuzz-0.5.47\build.rs:7:1
  |
7 | compile_error!("honggfuzz-rs does not currently support Windows but works well under WSL (Windows Subsystem for Linux)");
  | 

```
As on April 2020, Windows has 76.52% market share. Please support Windows

![image](https://user-images.githubusercontent.com/1781048/81387767-dd93cf80-9134-11ea-9d6f-795df7572429.png)

**Comment by bkchr** [comment]
> honggfuzz-rs does not currently support Windows but works well under WSL (Windows Subsystem for Linux)

Please use WSL. Currently we don't have enough resources to support windows.

**Comment by qalqi** [comment]
> > honggfuzz-rs does not currently support Windows but works well under WSL (Windows Subsystem for Linux)
> 
> Please use WSL. Currently we don't support Windows officially.

Why do you have steps for **Substrate for windows** that don't work? https://www.substrate.io/kb/getting-started/windows-users

**Comment by bkchr** [comment]
You already reported it in the correct repo here: https://github.com/substrate-developer-hub/knowledgebase/issues/65

I propose that you request further changes to the docs there.

Hongfuzz is only required for fuzzing, so if you use Substrate as a library, you should not run into the problems you see.

**Comment by qalqi** [comment]
I need a **substrate.exe** to run the substrate chain in windows 10 as a chain or validator. Can you guide me on removing the fuzzing?

**Comment by bkchr** [comment]
You can also use the `node-template` as in all the tutorials.

**Comment by qalqi** [comment]
> You can also use the `node-template` as in all the tutorials.

I only know `cargo build --release` Can you please elaborate.

**Comment by everhusk** [comment]
Wouldn't it make more sense to change the fuzzing library and enable windows support? As @qalqi has mentioned, it was working before the honggfuzz library was added and Windows users makes up a pretty significant share of the market for substrate.

**Comment by qalqi** [comment]
@gavofyork Can you look into providing Windows 10 support?

**Comment by qalqi** [comment]
The same issue is open here https://github.com/paritytech/substrate/issues/5681

**Comment by bkchr** [comment]
@qalqi did you try to run `cargo build --release -p substrate` directly?

**Comment by qalqi** [comment]
> @qalqi did you try to run `cargo build --release -p substrate` directly?

Received 
`error: package ID specification `substrate` matched no packages
`

**Comment by bkchr** [comment]
Sorry, use `-p node-cli`

**Comment by qalqi** [comment]
Running `cargo build --release -p node-cli`

gave following error
```

  Compiling sp-debug-derive v2.0.0-dev
error[E0432]: unresolved import `proc_macro`
  --> primitives\debug-derive\src\lib.rs:37:5
   |
37 | use proc_macro::TokenStream;
   |     ^^^^^^^^^^ help: a similar path exists: `syn::proc_macro`

error[E0433]: failed to resolve: use of undeclared type or module `proc_macro`
  --> primitives\debug-derive\src\impls.rs:22:42
   |
22 | pub fn debug_derive(ast: DeriveInput) -> proc_macro::TokenStream {
   |                                          ^^^^^^^^^^ use of undeclared type or module `proc_macro`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `sp-debug-derive`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by bkchr** [comment]
Please update your rust

**Comment by qalqi** [comment]
At Substrate commit `0947c5b72cebee15e22870cd0087d58727f91aac`
Did
```
rustup default nightly
rustup update nightly
rustup update stable
rustup target add wasm32-unknown-unknown --toolchain nightly
cargo build --release -p node-cli
```
Got the following error
```
error[E0599]: no method named `signal_handler_mut` found for reference `&runtime::Store` in the current scope                                                         
  --> C:\ ..\github.com-1ecc6299db9ec823\substrate-wasmtime-0.16.0-threadsafe.3\src\windows.rs:29:15
   |
29 |         *self.signal_handler_mut() = Some(Box::new(handler));
   |               ^^^^^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `signal_handler`

error: aborting due to previous error                                                                                                                                 

For more information about this error, try `rustc --explain E0599`.
error: could not compile `substrate-wasmtime`.  
```

**Comment by bkchr** [comment]
Yeah, the problem of this is that we don't have any Windows CI.

@arkpar maybe something you want to fix?

**Comment by qalqi** [comment]
Able to generate substrate binary. Unable to run in dev mode.

`$ ./substrate.exe --dev`


```2020-05-25 01:47:07 Running in --dev mode, RPC CORS has been disabled.
2020-05-25 01:47:07 Substrate Node
2020-05-25 01:47:07 ✌️  version 2.0.0-dev-b8c493d0a-x86_64-windows-msvc
2020-05-25 01:47:07 ❤️  by Parity Technologies <admin@parity.io>, 2017-2020
2020-05-25 01:47:07 �📋 Chain specification: Development
2020-05-25 01:47:07 🏷  Node name: parsimonious-show-2584
2020-05-25 01:47:07 �👤 Role: AUTHORITY
2020-05-25 01:47:07 �💾 Database: RocksDb at C:\Users\X2\AppData\Local\**Parity Technologies ,60,admin,64,parity.io,62**,\substrate\chains\dev\db       
2020-05-25 01:47:07 ⛓  Native runtime: node-250 (substrate-node-2.tx1.au10)
Error: Service(Client(Backend("Unsupported database version: 0")))```

**Comment by qalqi** [comment]
working after `./substrate.exe purge-chain --dev`

thanks
