### ISSUE TITLE
Weight & benchmarking result may not be reusable by other runtimes

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5966]
Currently, the weights are determined based on benchmarking results, which I think is based on Substrate dev chain runtime configuration.

However, it is possible that the weights will be different in other runtime, due to trait configuration differences.

For example,

https://github.com/paritytech/substrate/blob/d44702528ed61744143881cb290f8ae07c6701c2/bin/node/runtime/src/lib.rs#L214-L220

The location of `AccountStore` and the `DustRemoval` handler implementation will effect the performance and therefore may not have same performance characteristics as Substrate / Polkadot.

Burning foreign asset (cross chain tokens) may cause accounting issues. So other chain may want to send dust to treasury instead. This means means transfer may have one additional db read writes, and hence different weights.

This means:

- We need to be able to run benchmarks in a different runtime (maybe this is already possible?)
- The weights needs to be overridable/configurable

**Comment by shawntabrizi** [comment]
@xlc yeah this is a known part of our current assumptions.

We will need to modify all of our traits to support passing weight information. For example, any other implementation for Currency or other system level traits will have a huge impact on the weights of everything.

**Comment by shawntabrizi** [comment]
In the short term, allowing overriding of the weights we set on the runtime does sound like something we should address in the short term. Happy to brainstorm idea about how to do that.

**Comment by xlc** [comment]
Some kind of middleware pattern similar to signed extension may work? By default, the value from Substrate will be used, but can add custom middleware to add some value for some methods?

**Comment by kianenigma** [comment]
Allowing weight override should be a good step toward the right direction 👍

**Comment by xlc** [comment]
Should be fixed.
