### ISSUE TITLE
Potential flakiness with () as map value type

### ISSUE THREAD

**Issue by holygits** [paritytech/substrate#5977]
Tried making a pseudo-hashset in the runtime with
```rust
map T::AccountId => ()
```

The basic usage was inserting a new account ID into the map and using `contains_key` to check membership. It passed unit tests ok and sending extrinsics worked well. Sometimes the membership check would just fail, even though it was correct in previous blocks, this would create forks and panics with `state must match that calculated` in the test network.

In the end I changed `map AccountId => bool` and it appears to work correctly now.

Maybe this is a well known or expected footgun. Could prevent `()` as map value if so, otherwise it seems like it might be a sneaky 🐛

**Comment by xlc** [comment]
Yeah it is not really supported https://github.com/paritytech/subport/issues/7

**Comment by holygits** [comment]
🙏 ok seems we can close this. Some macro lint may help here for future users
