### ISSUE TITLE
Panic on invalid unsigned phragmen solution 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#5980]
https://github.com/paritytech/substrate/blob/3fe26e6efa3a70eb6606292a45370cb3326f1794/frame/staking/src/lib.rs#L1909-L1920

**Comment by thiolliere** [comment]
I'm not sure this is very important in this PR https://github.com/paritytech/substrate/issues/6106 I see 0.33 weak submission per era.
Moreover weak submission will no longer take weight because it will be refund with https://github.com/paritytech/substrate/pull/6032

Thus I think it doesn't waste too much.

Also I don't see why there is a security flag here.

**Comment by kianenigma** [comment]
related: https://github.com/paritytech/substrate/pull/4517#issuecomment-602526376 

Yeah now with proper weight refund perhaps this is less of a security issue. But still, no change allows each block author to submit any potentially a garbage solution with no consequence. Even if we refund, this is taking everyone's time. Moreover, they can submit a garbage solution that will not be refunded, and will be rejected due to an issue at the very end (i.e. bogus score). This allows validators to mess with the chain with no consequence. 

Panic would disincentivize this because they lose their authoring block.

**Comment by bkchr** [comment]
> Panic would disincentivize this because they lose their entire authoring block.

Panic where? In the extrinsic?

**Comment by kianenigma** [comment]
[yeah](https://github.com/paritytech/substrate/pull/4517#issuecomment-602526376 ).

**Comment by bkchr** [comment]
We don't have a mechanism that invalidates a full block on panic of an extrinsic ^>

**Comment by kianenigma** [comment]
> We don't have a mechanism that invalidates a full block on panic of an extrinsic ^^

I think what Gav meant was during import: a transaction panics in block import, then this invalidates the whole block no?

**Comment by bkchr** [comment]
Ahh yes that is correct.

**Comment by kianenigma** [comment]
Once https://github.com/paritytech/substrate/pull/6173 is merged, if we no longer have invalid unsigned solutions, this will be patched thereafter.

**Comment by kianenigma** [comment]
I've been doing more analysis after #6137 and we seem to be doing well. I will soon fix this.
