### ISSUE TITLE
Is storage value of `Option<()>` supported?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#5986]
We have few storage value with `double map X, Y => Option<()>` type to simulate an unordered set.

However I found out the `.iter(key1)` is not able to iterate all the values for `key1`.
Using `getStorage` RPC is able to read that storage did exists. `getKeys` is not able to iterate as the key wasn't exists.

Seems like the trie db is not able to distinguish between a non-exist key and an exist key with no value in some cases?

Change the type to `Option<bool>` works around the issue for me.

Example code:

https://github.com/laminar-protocol/laminar-chain/blob/f53fb6044ffa431993e4467f320f93af1b042ce2/modules/margin-protocol/src/lib.rs#L79

https://github.com/laminar-protocol/laminar-chain/blob/f53fb6044ffa431993e4467f320f93af1b042ce2/modules/margin-protocol/src/lib.rs#L667

This is not able to iterate.

The interesting thing is it works in unit test so we wasn't able to catch this issue before. Maybe something to do with low level db? The in memory db is able to handle but the real rocks db is not?

**Comment by thiolliere** [comment]
What should be the current behavior ? If I insert an empty value and then query for its existence then it return that it exists. But if I iterate it returns nothing.
So I guess this exists should actually return false and it still gets some value from some cache no ?

**Comment by thiolliere** [comment]
in overlayed_changes inserting a value of len 0 and then getting it will return Some, thus inside a same block you can do: `ext.place_storage(key, Some(())` and then `ext.exists_storage(key)` will return true.

**Comment by gavofyork** [comment]
I’ll m not sure it really should be fixed.

**Comment by thiolliere** [comment]
then maybe we should
* make const assert in decl_storage to prevent using type of size 0.
* add in the documentation in sp-io that zero size are not handled:
  Because if somebody insert a zero size value and then get it it can have different result depending on some cache. (overlay changes consider a zero size value to be `Some(value)`), and some other cache also.
* change client so that setting an empty slice value actually removes it.
