### ISSUE TITLE
Account for post-dispatch weight correction

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/substrate#6022]
The weight that is currently emitted is only the pre-dispatch weight. Since some functions now return a weight correction, they should emit any post-dispatch info so that one can calculate the exact fee paid for a transaction.

Edit: Also need any info necessary to calculate transaction fees from the block data, e.g. a single per-block event with all the parameters to calculate a fee based off of a transaction's final weight.

**Comment by athei** [comment]
I am in the process of adding this. PR will follow soon. However, I will be just replacing the weight in the `DispatchInfo` with the actual weight. In this way we do not need to emit additional data.
