### ISSUE TITLE
How to open substrate rocksdb wal support

### ISSUE THREAD

**Issue by freehere107** [paritytech/substrate#6023]
I want to sync substate db storage, but could not find any wal file from my db storage path.

https://github.com/rust-rocksdb/rust-rocksdb/blob/334b4652b60514ab63106428456ffd4f400ebfeb/src/db_options.rs#L99
https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log

**Comment by bkchr** [comment]
CC @arkpar

**Comment by arkpar** [comment]
WAL support is enabled by default. If you look in the DB dir you'll find a bunch of *.log files when the node is running.
