### ISSUE TITLE
Disable the Kademlia discovery when --reserved-only is passed

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6031]
The idea behind sentry nodes is that their validators should be only ever be connected to them.

At the moment, validators still perform Kademlia requests, both for random discovery purposes and for the authority-discovery system.

cc @mxinden 

This is low priority. This issue exists in order to not forget to do that.

**Comment by tomaka** [comment]
Depends on https://github.com/paritytech/substrate/issues/6264

**Comment by tomaka** [comment]
This issue was originally opened because validator nodes should only ever be connected to sentry nodes, and not open third-party connections. Despite sentry nodes being deprecated, we should still do this change.

**Comment by subtly** [comment]
@tomaka Where in the codebase would I look into fixing this?
