### ISSUE TITLE
The test_sync integration test doesn't call on_block_imported

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6033]
The documentation of `NetworkWorker::on_block_imported` mentions that it is mandatory to call it after importing a block. However our `test_sync` integration test doesn't do that.

This test is extremely intricate and consists in a bunch of components glued together like spaghettis cooked for too long and without oil. I have no idea how to fix that problem, and I'd recommend rewriting the test from scratch.

At the time of opening this issue, I'm about to introduce a performance-degrading hack in the network crate to bypass this problem. Please search for this issue number in the source code after fixing it.
EDIT: https://github.com/paritytech/substrate/pull/5938

**Comment by arkpar** [comment]
It is supposed to be called here: https://github.com/paritytech/substrate/blob/a2512e837003db3d3267764283edf31cf95a206c/client/network/test/src/lib.rs#L813

**Comment by tomaka** [comment]
've tried running the test and print a message in on_block_imported to check whether it is called, and I can confirm that it isn't.

The code used in the integration test is this one:
https://github.com/paritytech/substrate/blob/master/client/service/test/src/lib.rs

It's very redundant with the one on sc_network/test
