### ISSUE TITLE
T::AccountId used over <T::Lookup as StaticLookup>::Source in dispatchable calls

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#6042]
Substrate still have many `T::AccountId` in dispatchable call parameters. I think they should all be replaced by `<T::Lookup as StaticLookup>::Source`

This is results from a quick regex `\(origin, (.*): T::AccountId`

<img width="532" alt="Screen Shot 2020-05-15 at 5 23 22 PM" src="https://user-images.githubusercontent.com/1201310/82014470-c9ba1180-96d0-11ea-925e-edad1427adb6.png">

**Comment by shawntabrizi** [comment]
We brought this up internally in the past. Yes it should be done, but it was not a high priority. This could be a great first issue for anyone to pick up :)

happy to mentor

**Comment by ltfschoen** [comment]
I've had a go at this and created this WIP PR, which includes some questions. https://github.com/paritytech/substrate/pull/6637

**Comment by herou** [comment]
Is this ticket still available?

**Comment by ksr30** [comment]
@shawntabrizi is this issue available?

**Comment by shawntabrizi** [comment]
@ksr30 you can do it

**Comment by ksr30** [comment]
Thanks @shawntabrizi

**Comment by shamb0** [comment]
Hello @shawntabrizi , if its open shall I pick it up

**Comment by Doordashcon** [comment]
Is this still a needed task to solve @shawntabrizi?

**Comment by bkchr** [comment]
Yes, looks like their is still stuff to do.
