### ISSUE TITLE
Finish transition to the new PeerIds format

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6044]
Internally, `PeerId`s are now both an identity-multihash of the public key *and* a SHA256-multihash of that public key.

For Kademlia purposes, we use the SHA256 version.
All `PeerId`s are also displayed to the user as the SHA256 version.

The end goal is to transition these two to the identity version.

As a first step, we should show `PeerId`s to the user through their identity versions, so that all the configurations can be updated.

**Comment by tomaka** [comment]
cc https://github.com/libp2p/rust-libp2p/pull/1576

There are two approaches:

- Change the `Display` implementation of `PeerId` to the new one in libp2p.
- In Substrate, change everywhere we print a `PeerId` to show the identity version by manually base58-encoding the multihash. The problem with that approach is that we might miss some locations.

**Comment by romanb** [comment]
When node(s) using libp2p-kad are eventually upgraded, there will inevitably be a period where nodes have two identities in the DHT, right (assuming you don't stop and upgrade all your nodes at once but do a rolling upgrade)?

**Comment by tomaka** [comment]
I think the final step towards this is to remove support for the old representation.

While this will create a mild incompatibility between nodes regarding Kademlia, I don't think it is problematic. The random discovery should continue to work (albeit in an awkward way), and the authority-discovery is "best effort" mechanism and is not critical for the network to function properly.

**Comment by tomaka** [comment]
> I think the final step towards this is to remove support for the old representation.

Of course we should wait for a couple month to do that.

**Comment by tomaka** [comment]
https://github.com/paritytech/substrate/pull/6064 is in Polkadot 0.8.0 but not in versions 0.7.x.

According to the telemetry, there are currently only 9 Kusama nodes left that are on versions 0.7.x and that are in sync. I think it is reasonable for users to expect that versions 0.7.x no longer work properly.

I believe that we could finish this now.

**Comment by kaichaosun** [comment]
No sure if it's related to this issue https://github.com/paritytech/substrate/issues/7082.

**Comment by romanb** [comment]
This should be complete with https://github.com/paritytech/substrate/pull/7077.
