### ISSUE TITLE
Rust reference documentation on substrate.dev is outdated

### ISSUE THREAD

**Issue by geigerzaehler** [paritytech/substrate#6045]
The Rust reference documentation for the master branch (`https://substrate.dev/rustdocs/master`) that is linked from `substrate.dev` is outdated.

**Comment by apopiak** [comment]
Can you elaborate from which page the link is pointing (from substrate.dev itself?) as well as what is outdated?
FYI: We've launched the a new website at substrate.io and are in the process of moving there.

**Comment by geigerzaehler** [comment]
At the bottom of https://substrate.dev/docs/en/ the text “Check out Rust reference documentation.” links to https://substrate.dev/rustdocs/master. I was also using it directly from my browser history. So maybe a redirect would help, too.

**Comment by bkchr** [comment]
Duplicate issue & wrong repo: https://github.com/substrate-developer-hub/knowledgebase/issues/41
