### ISSUE TITLE
Audit all uses of twox_128

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/substrate#6051]
twox_128 is insecure, so it can only be used when the set of inputs is known in advance.  Since it only produces a 128-bit hash value, even using it with cryptographic hashes is unsafe, due to birthday attacks.

Pinging @burdges and @kirushik.

**Comment by burdges** [comment]
There is definitely a fishy looking usage around trie leaves, but @LeonGB explored it, found it safe enough, and wrote up some notes.  We'll see people worry about that twox_128 usage basically forever, so Leon can you send @kirill:matrix.parity.io your notes so that he has them on hand?

**Comment by DemiMarie-parity** [comment]
@burdges how bad would just purging twox_128 from FRAME be?  @LeonGB can you send the notes to me as well?  I am `@demi:matrix.parity.io`.

At the very least, each use of an insecure hash function should be accompanied by a proof that it is harmless.

**Comment by bkchr** [comment]
@DemiMarie-parity maybe you should post the ones that you think that are insecure.

**Comment by LeonGB** [comment]
I sent my notes to Kiril and Demi, but I did not do an audit of all uses of twox. We can indeed further investigate the uses that look insecure.

**Comment by bkchr** [comment]
I don't see any usage of `twox_128` in our code base, besides the usage for static keys. @DemiMarie-parity if you can not bring up any other use case of `twox_128`, we can close this.

**Comment by burdges** [comment]
I've no idea if any one person looked into all usages, and avoiding twox_128 might've saved us more headache than whatever CPU it saves elsewhere, but..

We addressed this in https://github.com/paritytech/substrate/issues/1868 and the explanation there is pretty reasonable, so unless someone can identify any specific iffy usage..

**Comment by burdges** [comment]
`find . -name *.rs -print0 | xargs -0 grep twox_ | grep -v test | grep -v bench | grep -v map | sed -e 's/:.*//' | uniq` says 
```
./frame/society/src/lib.rs
./frame/support/procedural/src/lib.rs
./frame/support/procedural/src/storage/parse.rs
./frame/support/src/storage/mod.rs
./frame/support/src/hash.rs
./frame/utility/src/lib.rs
./primitives/core/src/lib.rs
./primitives/core/src/hashing.rs
./primitives/io/src/lib.rs
```
It's possible DoS vulnerabilities exist, but anything important there should all come under comments in  #1868

**Comment by DemiMarie-parity** [comment]
Are the vulnerabilities limited to DoS?  My understanding is that hash collisions could be used to overwrite data, which is far worse @burdges.

**Comment by bkchr** [comment]
@DemiMarie-parity where do you have found possible hash collisions?

**Comment by burdges** [comment]
I'll do this at least superficially myself with Kirill's help.  You can close this issue.

**Comment by burdges** [comment]
I'm afraid the https://github.com/paritytech/substrate/issues/1868 has fairly unreadable discussion actually, but..

We believe twox_128 (xxhash) only gets used for static names like in https://github.com/paritytech/substrate/blob/master/frame/support/src/storage/mod.rs#L451-L452  We should therefore close this issue under the caveat that twox_128 being used for user controlled data should be considered a vulnerability. 

We've many `map hasher(twox64concat)` that computes `twox(key) ++ key` which appears safe for usages as a storage key, but why do that?

**Comment by DemiMarie-parity** [comment]
Can we get rid of the `twox64concat` hasher?  It seems pointless.

**Comment by xlc** [comment]
We are using a lot of `twox64concat` hasher, so please advise if they should be replaced.
Most of the usages are for sequence id, or enum with < 20 variants or `AccountId` that have corresponding private key.

**Comment by burdges** [comment]
Afaik, there is nothing wrong with twox64concat based upon my reading of decl_storage stuff in frame-support, but I'm curious what purpose it serves over identity.

**Comment by DemiMarie-parity** [comment]
@burdges The main advantage I can think of is where the preimage is not completely random, but also cannot be chosen at will by an attacker.  Public keys for which a private key is known to exist come to mind.

**Comment by xlc** [comment]
For sequence id, the preimage won't be random at all, so I guess twox64 can help a bit?

We will really love a guide to explain when to use each hasher, I am actually unsure when to use identity over twox64concat.

**Comment by DemiMarie-parity** [comment]
Sequence IDs are almost as far as possible from random, but they are also short, so the identity hasher may actually be okay ― it depends entirely on how the trie is implemented internally.

**Comment by thiolliere** [comment]
For context this is the current usage documented by decl_storage:
```
    blake2_128_concat: The default, safe choice. Use if you are unsure or don't care. It is secure against user-tainted keys, fairly fast and memory-efficient and supports iteration over its keys and values. This must be used if the keys of your map can be selected en masse by untrusted users.
    twox_64_concat: This is an insecure hasher and can only be used safely if you know that the preimages cannot be chosen at will by untrusted users. It is memory-efficient, extremely performant and supports iteration over its keys and values. You can safely use this is the key is:
        A (slowly) incrementing index.
        Known to be the result of a cryptographic hash (though identity is a better choice here).
        Known to be the public key of a cryptographic key pair in existence.
    identity: This is not a hasher at all, and just uses the key material directly. Since it does no hashing or appending, it's the fastest possible hasher, however, it's also the least secure. It can be used only if you know that the key will be cryptographically/securely randomly distributed over the binary encoding space. In most cases this will not be true. One case where it is true, however, if where the key is itself the result of a cryptographic hash of some existent data.
```
https://substrate.dev/rustdocs/master/frame_support_procedural/macro.decl_storage.html

I think twox_64_concat here as an understandable usecase. though we can audit the fact that all our `hasher(twox_64_concat) T::AccountId` is indeed from a key pair in existence

**Comment by burdges** [comment]
It's fine.  We're only using it for DoS attacks against the trie, so really it exists only to reduce the minimum deposit before declaring something dust.  We can close this issue.
