### ISSUE TITLE
Aura nodes try to author on every slot

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#6052]
When creating a private network as described in https://www.substrate.io/tutorials/start-a-private-network/v2.0.0-alpha.7/alicebob, the nodes produce errors like

```
Encountered consensus error: CannotSign([88, 111, 68, 26, 64, 196, 73, 49, 116, 34, 235, 87, 110, 210, 180, 172, 173, 48, 31, 26, 239, 99, 33, 149, 142, 20, 160, 177, 129, 23, 83, 58], "An unknown keystore error occurred: No such file or directory (os error 2)")
```
The nodes are trying to author blocks on every slot (not just their own) and of course they fail to sign blocks on someone else's slot. This is likely caused by #6008 

cc @danforbes @rakanalh

**Comment by rakanalh** [comment]
I am able to reproduce this compiling latest substrate master and using the `node-template` binary. What is interesting about this error is the "No such file or directory" part. 

Will investigate.

**Comment by bkchr** [comment]
@rakanalh do you want me to say that you not tried your changes?

**Comment by andresilva** [comment]
Issue is here: https://github.com/paritytech/substrate/pull/6008/files#diff-bd7ad82935a181b1d3db08eeee60bac9R248 

We are indeed claiming every slot since we removed the code that is filtering by the keys that we have available locally, i.e. we're trying slots for which we don't have any keys.

**Comment by rakanalh** [comment]
> @rakanalh do you want me to say that you not tried your changes?

I have tried babe but not aura which is my bad.



> Issue is here: https://github.com/paritytech/substrate/pull/6008/files#diff-bd7ad82935a181b1d3db08eeee60bac9R248
> 
> We are indeed claiming every slot since we removed the code that is filtering by the keys that we have available locally, i.e. we're trying slots for which we don't have any keys.

I have arrived to the same conclusion when debugging. Initially i would have thought that code only "converts" public key to pair which i didn't need in my original PR. But the fact that it returns an `Option` made it clear to me that we're returning the public key every time which would invoke `sign_with` on a public key that we don't have the private key for.

I posted a PR for the fix and i apologize for my mistake.
