### ISSUE TITLE
Alpha 7 an alpha 8 are not fully released

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#6057]
https://docs.rs/crate/pallet-staking/2.0.0-alpha.8

Last successful build is alpha 6.

Please add a step to release pipeline to make sure the released version is actually compilable.

**Comment by xlc** [comment]
I am getting the same error as docs.rs and I can't identify what causes the error by looking at the code. There isn't any `_phragmen::sp_runtime`.

But I suspect this issue have something todo with the build pipeline modify Cargo.toml file during release. Pulling crates from tags in Github works perfectly fine.

**Comment by bkchr** [comment]
@xlc the `sp-phragmen-compact` problem will be fixed by yanking the `2.0.0-dev.1` version. This will be done shortly by us.

**Comment by bkchr** [comment]
The crate is yanked, please make sure that the specific version is removed from your `Cargo.lock`.

**Comment by xlc** [comment]
@bkchr `cargo update` seems fixes the build issue we have. 

I will leave this open as I think there needs to be some process to ensure docs.rs builds successfully on publish.

**Comment by bkchr** [comment]
Docs.rs could not build because of the same error. So, I going to close this. In the end it was an error that happened quite some time ago.
