### ISSUE TITLE
Check the signature type when insert_key

### ISSUE THREAD

**Issue by Kayryu** [paritytech/substrate#6060]
Execute the insert_key through rpc. 
If the keyType is ‘babe‘ type, it must be sr25519. The user created and entered ‘suri‘ and ‘publicKey’ with ed25519, which is obviously the wrong private key.
Even if the user sets the key, the node will not generate blocks normally.

**Comment by bkchr** [comment]
`KeyType` is not bound to a specific crypto, so the RPC will not do any checks if the supplied key is correct. It is expected that the user supplies the correct key.
