### ISSUE TITLE
when to system.suicide

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#6071]
Questions about `system.suicide`

https://github.com/paritytech/substrate/blob/5a7600912b7fd50091990899e8ad93ad618f40c4/frame/system/src/lib.rs#L727-L744

Am I right the only purpose of this call is to remove account (i.e. nonce)?

Why anyone will want to pay tx fee to call this method?

The condition is balance is zero. But when balance is zero, it won't be able to pay tx fee to call this method? I guess it is possible to make balance just above `ExistentialDeposit` so after deduct tx fee it will drop below `ExistentialDeposit` and set to zero. But this still does not making much sense to me.

Why this method have no DB write?

**Comment by xlc** [comment]
Read bit more code, seems like this is just a fallback method not meant to be use by Polkadot/Kusama? Because when account balances drops to zero it will automatically call `kill_account` to wipe the data.

So it is for other chains to use?

**Comment by shawntabrizi** [comment]
Yes, I think this only applies when balances in not part of the `AccountData`.

Remember that `AccountData` in FRAME System and the Balances pallet both support keeping the nonce and balance information separate. If it is separate, and for whatever reason there is no `kill_account` hook on the data that is stored in `AccountData`, this `suicide` function will allow a user to clean up their account.

I also agree it is not used in Polkadot/Kusama.
