### ISSUE TITLE
 Every dispatchable must have a #[weight] attribute

### ISSUE THREAD

**Issue by avalverdero** [paritytech/substrate#6079]
Hello,

@crossi704 and me recently tried to upgrade our custom module code from alpha.6 to alpha.8 and I found this error:

```
 Identities get(identity): map hasher(opaque_blake2_256) T::Hash => Identity<T::AccountId>;
    |                      ^^^^^^^^
 error: Missing weight for $ ident. Every dispatchable must have a #[weight] attribute.
```
What is this weight notation that is being required now?

Many thanks in advance.

**Comment by bkchr** [comment]
I think this was already fixed in Substrate technical.

**Comment by Mikerah** [comment]
@bkchr I am having the same issue. Can you expand on how to solve this? Where in the documentation points to this problem?

**Comment by shawntabrizi** [comment]
@Mikerah in general, if you are seeing this error, add:

```
#[weight = 0]
```

over your function like so:

```
		/// Make some on-chain remark.
		///
		/// # <weight>
		/// - `O(1)`
		/// - Base Weight: 0.665 µs, independent of remark length.
		/// - No DB operations.
		/// # </weight>
		#[weight = 700_000]
		fn remark(origin, _remark: Vec<u8>) {
			ensure_signed(origin)?;
		}
```

^ from frame/system
