### ISSUE TITLE
pallet balances with zero ExistentialDeposit

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#6083]
Does pallet balances support zero `ExistentialDeposit`? I remember there were some issues regards it but not sure if they still applies after various refactors.

Context: https://github.com/AcalaNetwork/Acala/issues/236

**Comment by xlc** [comment]
After reading bit more code, seems like `ExistentialDeposit = 1` should work?

`ExistentialDeposit = 0` means account can never be removed, but with `ExistentialDeposit = 1` account can be removed when balance reach to 0.

https://github.com/paritytech/substrate/blob/812d94d42c6d6d7fd28cf18a08d84f14c49d8544/frame/balances/src/lib.rs#L589-L597

Still will like a confirmation.

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by shawntabrizi** [comment]
Our balances pallet does not support zero existential deposit. We have parts of our logic which assume it is non-zero, and of course the entire account reaping logic would not work.

It is a design decision and if you need that support you probably want to create a new pallet for that purpose.
