### ISSUE TITLE
In sc_service/src/metrics.rs, detach the networking-related metrics from non-networking-related metrics

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6093]
At the moment, metrics such as the CPU usage, disk writing, and so on are updated only when the networking periodically reports its status.

Unfortunately, that means that if the networking has an issue and freezes, then CPU usage, disk writing, ... are never updated. This is a problem, because they might be useful to understand *why* the networking freezes.

**Comment by romanb** [comment]
Closed by #6986.
