### ISSUE TITLE
RPC call author_insertKey failed, Method not found 

### ISSUE THREAD

**Issue by Xib1uvXi** [paritytech/substrate#6100]
substrate version:

```bash
➜  substrate git:(7e9a2ae78) ./target/release/substrate --version 
substrate 2.0.0-alpha.8-7e9a2ae78-x86_64-macos
```

start substrate:

```bash
./target/release/substrate purge-chain --dev

./target/release/substrate --dev
```

call author_insertKey:

```bash
curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d \
               '{
        "jsonrpc":"2.0",
        "id":1,
        "method":"author_insertKey",
        "params":["aura","strategy barely old print movie april gossip interest velvet endorse clever office","0x0ed4b40d52c0fd128b01774817656570ef7fe9a4497bf2a05fbc830e11"]
    }'
```

i got error: 

```json
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
```

in apps ui also has this problem

**Comment by Xib1uvXi** [comment]
i found run cmd flag can fix this problem 

```bash
--rpc-methods=Unsafe
```

**Comment by bkchr** [comment]
Yeah there was a bug, that was fixed on master.

**Comment by asmitadhungana** [comment]
In my case, it's throwing this error when I pass my Polkadot account's mnemonic and address in the above author_insertKey method as below:

curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d \
               '{
        "jsonrpc":"2.0",
        "id":1,
        "method":"author_insertKey",
        "params":["aura","weird god heaven reopen may infant since behold fall census love curb","0x5DcEwS93cx8dfWbU5zB5pwgcjs7yFQbt3tEaqvHHE6xzEEUy"] 
    }'


{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid hex character: w, at 6."},"id":1}
