### ISSUE TITLE
Deprecate FunctionOf

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#6104]
Sadly, yes. We recently learned that the whole thing was useless since the scope in which the right hand side of `#[weight = { ... }]`was being evaluated in already had access to all the parameters. So this is useless, adds only noise. It should be deprecated. 

- [ ] Mark `FunctionOf` as `#[deprecated]`
- [ ] Remove all users in substrate and polkadot

A good candidate for something to be done #6040.

**Comment by athei** [comment]
Split of the Origin part to: https://github.com/paritytech/substrate/issues/6316

**Comment by kianenigma** [comment]
@athei I think this by itself would be mostly code removal and pretty trivial for substrate/polkadot.  But, I'd surely flag it as `clientnoteworthy`, and maybe even consider communicating it in public channels since it might break other projects.
