### ISSUE TITLE
Provide `can_set_code` via the RPC api

### ISSUE THREAD

**Issue by NunoAlexandre** [paritytech/substrate#6105]
Submitting a `set_code` sudo call is rather expensive, considering that it is only validated at the latest stage and thus attempting to set an invalid new code still includes the tx in a block.

It would very useful to provide a call to validate the new code client-side, using the RPC API.

**Comment by bkchr** [comment]
The point of these `can_set_code` checks is that you don't fuck up your chain. The checks that are done there, should be always done anyway (`spec_version` increases and `spec_name` stays the same). That is nothing that needs to be exposed via RPC.

**Comment by NunoAlexandre** [comment]
> The point of these `can_set_code` checks is that you don't fuck up your chain. The checks that are done there, should be always done anyway (`spec_version` increases and `spec_name` stays the same). That is nothing that needs to be exposed via RPC.

Note that I am not suggesting to _not_ do that check in `set_code` but to additionally provide that method to be executed via the RPC API to have an earlier, preemptive check client-side, instead of basically playing such an expensive trial and error.

**Comment by bkchr** [comment]
That is no trial and error. You just make sure that one value increases and the other stays the same.

**Comment by NunoAlexandre** [comment]
@bkchr until those properties can be type-safe, mistakes can and will happen: the update tx signed with the wrong key pair, the wasm file spec_version is not greater than the runtime being updated, the `spec_name` is not the same, etc.

The original motivation behind this issue was that [we](https://github.com/radicle-dev/radicle-registry) wanted to validate these properties of a given wasm file on the client-side, to avoid the expensive travel of submitting an invalid runtime update that gets included in a block. Sure, the check should still take place runtime-side anyways, but having this check client-side would not only avoid expensive mistakes but it would also provide better error information. We tried to copy `can_set_code` to run it on the client but the method checking the wasm runtime version, `sp_io::misc::runtime_version`, needs to run in the runtime environment (it panicked with some error related to externalities).

Proving a way of querying a runtime whether some wasm blob _would_ be a valid update would undoubtedly be useful and helpful. At the very worse, I believe that 1) this check should happen before including the tx in a block and that 2) the errors should be better propagated.
