### ISSUE TITLE
State mismatch in libp2p: Expected alive incoming. Got None.

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6112]
This error seems to be printed once per hour on average on our nodes:

> 2020-05-22 01:18:55.134 tokio-runtime-worker ERROR sub-libp2p  State mismatch in libp2p: Expected alive incoming. Got None.

This can either be caused by a bug in the peerset sending inconsistent messages or by a bug in the state machine that handles the peerset's messages.

**Comment by romanb** [comment]
For what it is worth, I don't see this error any more in the Kibana logs for the "logstash-kusama" index family since June 14th. Are there other places or log indices to check?

**Comment by tomaka** [comment]
Let's assumed that it is fixed. We can always reopen if the error is seen in the logs again.
