### ISSUE TITLE
Pallets docs links broken

### ISSUE THREAD

**Issue by qalqi** [paritytech/substrate#6164]
Links for pallet docs are broken at
https://substrate.dev/docs/en/conceptual/runtime/frame
https://www.substrate.io/kb/runtime/frame

e.g
https://substrate.dev/rustdocs/master/pallet_assets/index.html
https://substrate.dev/rustdocs/master/pallet_authority_discovery/index.html
https://substrate.dev/rustdocs/master/pallet_babe/index.html

**Comment by shawntabrizi** [comment]
cc @JoshOrndorff and @danforbes

**Comment by danforbes** [comment]
Closing in favor of substrate-developer-hub/knowledgebase#41, which I have assigned to myself and will prioritize. Closing this issue in favor of that one. Thanks for the heads up, Shawn :+1:

**Comment by danforbes** [comment]
@qalqi - the changes have been merged in...thank you!
