### ISSUE TITLE
frame-support build fails with latest rust nightly-2020-05-26

### ISSUE THREAD

**Issue by mnaamani** [paritytech/substrate#6167]
`cargo build --release`

Compiler error building WASM runtime with latest `nightly-2020-05-26`

```
error[E0424]: expected value, found module `self`
   --> /Users/mokhtar/joystream/substrate/frame/support/src/traits.rs:913:11
    |
911 | / bitmask! {
912 | |     /// Reasons for moving funds out of an account.
913 | |     #[derive(Encode, Decode)]
    | |              ^^^^^^ `self` value is a keyword only available in methods with a `self` parameter
914 | |     pub mask WithdrawReasons: i8 where
...   |
929 | |     }
930 | | }
    | |_- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0424`.
error: could not compile `frame-support`.
```

Reverting to earlier version of nightly from a few days prior does not show same error.

**Comment by duval1024** [comment]
stable version `1.43.1 (8d69840ab 2020-05-04)`  also show the same error :

```
   Compiling frame-support v2.0.0-rc2 (/Users/duval/workspace/blockchain/substrate/frame/support)
error[E0424]: expected value, found module `self`
   --> /Users/duval/workspace/blockchain/substrate/frame/support/src/traits.rs:913:11
    |
911 | / bitmask! {
912 | |     /// Reasons for moving funds out of an account.
913 | |     #[derive(Encode, Decode)]
    | |              ^^^^^^ `self` value is a keyword only available in methods with a `self` parameter
914 | |     pub mask WithdrawReasons: i8 where
...   |
929 | |     }
930 | | }
    | |_- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0424`.
error: could not compile `frame-support`.

```

```
~/workspace/blockchain/substrate   master  rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/duval/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin
1.12.0-x86_64-apple-darwin
1.43.1-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.43.1 (8d69840ab 2020-05-04)


```

**Comment by duval1024** [comment]
I reinstalled all installed toolchains , and then fix this problem.

**Comment by bkchr** [comment]
This is fixed by this pr: https://github.com/rust-lang/rust/pull/72724

Installing rust nightly rustc 1.45.0-nightly (74e804683 2020-05-30) fixes it.

We also merged a pr to fix the underlying bug, so, if the feature is re-added to the compiler we should not run into the same problems.

**Comment by danforbes** [comment]
For people following our tutorials, will this problems always be present in Substrate v2.0.0-rc2? If so I can update the instructions for that version of the tutorial to add an extra step to make sure you're on the correct nightly. I guess I'm unclear if this is an ephemeral upstream issue with Rust or if this is something that will always be the case on v2.0.0-rc.

**Comment by bkchr** [comment]
No, the compiler reverted the code that lead to this compilation error. Until the code is re-added, the tutorial should work without any problems.

**Comment by JoshOrndorff** [comment]
A tutorial user reported the same error in `sp-consensus-babe` when trying to build subkey. https://github.com/substrate-developer-hub/tutorials/issues/53

I know the compiler itself reverted so this is not an immediate problem anymore, but I wonder if the underlying issue in `sp-consensus-babe` was fixed as @bkchr described for the one in `frame-support`

> We also merged a pr to fix the underlying bug, so, if the feature is re-added to the compiler we should not run into the same problems.

**Comment by brenzi** [comment]
I'm struggling with this for rc5:

```
     Compiling frame-support v2.0.0-rc5
  error[E0424]: expected value, found module `self`
      --> /home/abrenzikofer/.cargo/registry/src/github.com-1ecc6299db9ec823/frame-support-2.0.0-rc5/src/traits.rs:1184:11
       |
  1182 | / bitmask! {
  1183 | |     /// Reasons for moving funds out of an account.
  1184 | |     #[derive(Encode, Decode)]
       | |              ^^^^^^ `self` value is a keyword only available in methods with a `self` parameter
  1185 | |     pub mask WithdrawReasons: i8 where
  ...    |
  1200 | |     }
  1201 | | }
       | |_- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
       |
       = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

```

I uninstalled all my toolchains and re-ran
```
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
```

my `rustup show`
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/<_>/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.46.0 (04488afe3 2020-08-24)

```

**Comment by danforbes** [comment]
@brenzi can you try using the nightly from July 24th? That was the date `rc5` was released. There are some example commands here https://substrate.dev/substrate-contracts-workshop/#/0/setup

**Comment by brenzi** [comment]
hm, that nightly won't install because of missing cargo fmt. but that one works:
```
rustup toolchain install nightly-2020-07-12
```
however, the wasm builder decides on its own what toolchain to use, right? so it is of no use to do 
```
cargo +nightly-2020-07-12 build --release
```
right?

**Comment by brenzi** [comment]
```
cargo +nightly-2020-07-12 build --release
```
works

@bkchr suggested 
```
cargo update -p parity-scale-codec-derive
```
which makes it work with stable too.

**Comment by peterwillcn** [comment]
cargo +nightly-2020-07-12 build --release fix it

**Comment by srinjoychakravarty** [comment]
Thanks guys... 
**Latest fix [more detailed]:**

1. Install the latest toolchain
`$ rustup toolchain install nightly-2020-07-12`

2. List your rust toolchains and see which one is active
`$ rustup show`

3. Make the latest nightly toolchain the active one
`$ rustup default nightly-2020-07-12-x86_64-unknown-linux-gnu`

4. Ensure web assembly compilation is bound to the latest toolchain [activated above]
`$ rustup target add wasm32-unknown-unknown --toolchain nightly-2020-07-12`

5. Make compilation with stable toolchain **[optional]**
`$ cargo update -p parity-scale-codec-derive`_

6. Compile the ink smart contract in verbose mode so you have better insights into the successful compilation
`$ cargo +nightly-2020-07-12 build --release --verbose`
