### ISSUE TITLE
"OR gate" for EnsureOrigin

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#6182]
Enable something like this

```
type AddOrigin = EnsureOneOf<
    EnsureProportionMoreThan<_1, _2, AccountId, CouncilCollective>,
    EnsureProportionMoreThan<_1, _1, AccountId, TechnicalCollective>,
    EnsureRoot<AccountId>,
>
```

This can also replace all those code

https://github.com/paritytech/substrate/blob/2e9697e0001805007d3366269134327a4176d636/frame/membership/src/lib.rs#L123-L125

Relates to: https://github.com/paritytech/substrate/issues/3059

**Comment by kianenigma** [comment]
Linked: https://github.com/paritytech/substrate/issues/3059
