### ISSUE TITLE
FixedU128

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#6183]
We have `Fixed128`, will be useful to have `FixedU128` as well.

I wonder if the `implement_fixed` macro already support it?

This can also replace our implementation which have different API than `Fixed128` https://github.com/open-web3-stack/open-runtime-module-library/blob/master/utilities/src/fixed_u128.rs

**Comment by marcio-diaz** [comment]
I think it should work without much (or none) changes. Let me prepare a PR.
