### ISSUE TITLE
Storage export not found

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#6192]
**Description**

After upgrade to `substrate 2.0.0-rc2` I got following error:
```
2020-05-29 17:21:19 Cannot create a runtime: Instantiation("Instantiation: Export ext_storage_child_storage_kill_version_1 not found")
Error: Service(Client(Execution(Other("Instantiation: Export ext_storage_child_storage_kill_version_1 not found"))))
```

* Launch arguments: `./target/release/plasm-node --chain dusty`
* Node source code: https://github.com/staketechnologies/Plasm/tree/add/dusty-release-1.1.0

Could you help to find the core of this problem, please

**Comment by shawntabrizi** [comment]
Did you purge chain?

```
./target/release/plasm-node purge-chain --chain dusty

**Comment by bkchr** [comment]
These functions got removed quite some time ago. Which version did you used before?

**Comment by akru** [comment]
@shawntabrizi sure, this error for clear db.

@bkchr previous version was 2.0.0-alpha.6, could you suggest any workaround?

**Comment by akru** [comment]
Fixed by implementing dedicated runtime interface, thank you!
