### ISSUE TITLE
Encountered consensus error when trying to launch my private network.

### ISSUE THREAD

**Issue by herou** [paritytech/substrate#6199]
Hello,

I am following this tutorial: https://www.substrate.io/tutorials/start-a-private-network/v2.0.0-rc2/customchain and I am facing this issue: 
![image](https://user-images.githubusercontent.com/13895430/83354863-ddfe3f80-a35b-11ea-8f5e-97914a39b683.png)

Can somebody let me know what I am doing wrong? I am using the pre-generated keys.

**Comment by danforbes** [comment]
Closing in favor of substrate-developer-hub/tutorials/#46. @herou in the future you can also use [the Subport support repository](https://github.com/paritytech/subport). Issues on this repository should not be used for Substrate-related support issues. Noting root issue for posterity: https://github.com/paritytech/substrate/issues/6052.

**Comment by bkchr** [comment]
@danforbes you can move issues to the subport repo by using "transfer issue" on the right.

**Comment by danforbes** [comment]
Oh nice, thank you. In this case, the OP had already opened a duplicate issue on the Tutorial repo, but I didn't know about the button to move an Issue so I may use that in the future :rocket:

**Comment by bkchr** [comment]
(Though this only works for issues in the same organization, so, you can not move them to the developer hub repo)
