### ISSUE TITLE
Submit tx error: Transaction is temporarily banned

### ISSUE THREAD

**Issue by Wangmmx** [paritytech/substrate#6203]
When I send the polkadot transaction test network--westend, there is no balance in the account. Using the API interface, the error shows that there is no balance, which is normal. 
```
        const wsProvider = new WsProvider('wss://westend-rpc.polkadot.io');
        const api = await ApiPromise.create({provider: wsProvider});

        let transfer = api.tx.balances.transfer(to, value);
        console.log(transfer.sign(pair).toHex())//0x21028488ccfe1c52268e4f5dfb6228e71b2cff7a24446fad25fcd2bc3481fad2c63ccf00a3b22b22a68e887772b1a590330a33c9dad01b1c7d186765829d6d598a845f4af28a3ad1ef2122ea01f492d30344b02afe545f0eb5f879113bb4ec6a689c2f0e0000000400c5b423eea8b3438b5d16f8d34c2a54f2b7a8b65194d5d88a5fda9966de8b286a04
        await transfer.signAndSend(pair);
      
```
the error is:
RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Payment

But when I took out the transaction hex of the previous step separately and broadcasted it, the following error occurred: temporarily banned, I want to ask why
```
   let hex = '0x21028488ccfe1c52268e4f5dfb6228e71b2cff7a24446fad25fcd2bc3481fad2c63ccf00a3b22b22a68e887772b1a590330a33c9dad01b1c7d186765829d6d598a845f4af28a3ad1ef2122ea01f492d30344b02afe545f0eb5f879113bb4ec6a689c2f0e0000000400c5b423eea8b3438b5d16f8d34c2a54f2b7a8b65194d5d88a5fda9966de8b286a04';
   return api.rpc.author.submitExtrinsic(hex);
```

and the error is:
RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1012: Transaction is temporarily banned

what does this means? Why the error is different

**Comment by NikVolf** [comment]
This mean that exactly this transaction has been seen validated as invalid (see first error) and it not be validated again for some time (see second error).

**Comment by Wangmmx** [comment]
Why is this error instead of directly indicating insufficient balance, only the first time the same transaction parameters will prompt insufficient balance?

**Comment by NikVolf** [comment]
Because deducing the fact that the source account does not have enough balance requires a call into the runtime. This is expensive and substrate does not do this when it is not required. In this case we know advance that the transaction is invalid.

**Comment by Wangmmx** [comment]
I got it, thank you very much！
