### ISSUE TITLE
suggest: offline private key signature capability

### ISSUE THREAD

**Issue by jiangfuyao** [paritytech/substrate#622]
Provide offline private key signature capability,
Avoid the uncertainty of hosting private keys in the cloud servers.

**Comment by jiangfuyao** [comment]
edwardt said: The intention is to have session signing keys on the validator, while the derivation of those session keys will be done elsewhere.
My preference would be for the session keys to be derived from child signing keys (which are online) rather than the parent signing key (which I think could be offline). I think that would work, at least.

**Comment by gavofyork** [comment]
Yeah - this is likely to be middleware and addressed at a later stage. For now, there is simply a facility to alter the keys once per session to something else by signing a transaction with the validator key.
