### ISSUE TITLE
Unify doc/comment line width.

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#6222]
Maintaining the line width in the code is sometimes hard, and we have a CI check for it so it never goes above 120. 

Yet, maintaining it for the documents in the code is trivial, and we don't have any rule for it. 

As far as I know our preferred line width is 100 for document/comments. Yet, I often see lines aligned to 60 or 80. 

Both aligning this comments, and enforcing it potentially in the CI should be easy to do, and a good small step toward making the have a higher standard.

**Comment by kianenigma** [comment]
Here's a good (random -- all due respect to whoever the author of the code is :D) example 

https://github.com/paritytech/substrate/blob/2743ed4b26b786efdcb5d1123a277f21da0c29c0/frame/staking/src/lib.rs#L867-L870

Comparing this with the adjacent lines is not easy on the eyes IMO.

**Comment by kianenigma** [comment]
@TriplEight could this ever be a CI job that rewraps all comment lines to exact 100?

**Comment by TriplEight** [comment]
@kianenigma you mean some script/bot that would fix and commit this automatically? Pretty sure there are tools for that, but we will have to research what's their i.e. licensing of the produced code.
