### ISSUE TITLE
can't create a custom chain spec .json in the start a private network

### ISSUE THREAD

**Issue by inovatecsuriname** [paritytech/substrate#6239]
@jason-inovatec:/home/jason/substrate-node-template# ./target/release/node-emplate build-spec --chain=customSpec.json --raw --disable-default-bootnode
Error: Input("Error opening spec file: No such file or directory (os error 2)")

**Comment by bkchr** [comment]
`./target/release/node-emplate build-spec --raw --disable-default-bootnode > customSpec.json`

This is probably the command you are searching for.
