### ISSUE TITLE
Benchmarks tests are not run in CI

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#6263]
tests contains in benchmark modules such as https://github.com/paritytech/substrate/blob/606b4faf2f52ec588235d3cdff6c7364a393a645/frame/balances/src/benchmarking.rs#L134
are not run on CI.

This only means that master can have broken benchmark test.
Maybe one cheap way (for CI) to solve this would be to use runtime test as proposed in https://github.com/paritytech/substrate/issues/5570 then the current CI-test https://github.com/paritytech/substrate/blob/606b4faf2f52ec588235d3cdff6c7364a393a645/.gitlab-ci.yml#L287
would cover them.

(This is confirmed by this successful PR https://github.com/paritytech/substrate/pull/6257)

**Comment by shawntabrizi** [comment]
This has been solved
