### ISSUE TITLE
client/db broken feature

### ISSUE THREAD

**Issue by pscott** [paritytech/substrate#6268]
While working on #6267 I came across a feature that would not compile properly when activated.

Seems like the `subdb` feature of `client/db` does not compile, or at least runnning:
```bash
cd client/db; cargo build --features subdb
```
fails to build.

Side note: would it be a good idea to have CI try and build each feature of every crate? Maybe something like https://github.com/frewsxcv/cargo-all-features ?

**Comment by pscott** [comment]
(subdb does not exist as a feature YET, #6267 needs to be merged before it appears as a feature)

**Comment by rphmeier** [comment]
@pscott please attach labels to issues
