### ISSUE TITLE
[question] How to increase the balance

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/substrate#6275]
How to increase the balance of a given account from your runtime using the balances trait?

**Comment by shawntabrizi** [comment]
Using the `Currency` trait, you should use:

* `deposit_into_existing`: https://crates.parity.io/frame_support/traits/trait.Currency.html#tymethod.deposit_into_existing
* `deposit_creating`: https://crates.parity.io/frame_support/traits/trait.Currency.html#tymethod.deposit_creating

To mint net new tokens into a user's free balance. This function is used for staking rewards for example, to pay users for nominating or validating.
