### ISSUE TITLE
no_std WASM build mixed with std

### ISSUE THREAD

**Issue by jasl** [paritytech/substrate#6278]
This may not a Substrate bug, someone told me this is a Cargo issue and has long time (but he didn't give me the exact issue link)...

I'm trying to implement an extrinsic call in my pallet, and I want do decode JSON in that function.

So I choose to use `serde_json` (I also tried `serde_json_core`), and set `default-features = false`

the pallet pass compiled with no error.

then I add the code for decoding json, it look like

`let parsed_report: serde_json_no_std::Value = serde_json_no_std::from_slice(&report).unwrap();`

then compile again, the compile will failed, output:

```
error: duplicate lang item in crate sp_io (which frame_support depends on): panic_impl.
  |
  = note: the lang item is first defined in crate std (which serde depends on)

error: duplicate lang item in crate sp_io (which frame_support depends on): oom.
  |
  = note: the lang item is first defined in crate std (which serde depends on)
```

I remember that Substrate's WASM disabled std feature, so I use `cargo rustc --target=wasm32-unknown-unknown --manifest-path=./Cargo.toml --verbose 2>&1 | tee build.log` in `target/debug/wbuild` to catch up detailed compiling process, then I've found many crate compiled with std feature flag.

Output a little big, I attached as attachment

[build.log](https://github.com/paritytech/substrate/files/4742729/build.log)

I search with `feature="std"` in the log, there has 23 results, and I also found some doesn't `no_std` crate e.g. `futures` including the compiling process.

Finally I realize the `std` feature is from a `proc_macro`.

The issue will be triggered when using some crates that proc_macro also used in Substrate macro that would compile into WASM.

**Comment by shawntabrizi** [comment]
From the serde docs:

> In particular, a dependency on serde_json always needs Serde built with std. If you need JSON support without a standard library, please use serde-json-core instead of serde_json.

https://serde.rs/no-std.html

Consider other no-std json libraries too: https://github.com/xlc/lite-json

**Comment by jasl** [comment]
> I am not sure why serde json core did not work for you... do you have specific errors in that situation?
> 
> > In particular, a dependency on serde_json always needs Serde built with std. If you need JSON support without a standard library, please use serde-json-core instead of serde_json.
> 
> https://serde.rs/no-std.html
> 
> Consider other no-std json libraries too: https://github.com/xlc/lite-json
> 
> This one was built with substrate in mind.

> In particular, a dependency on serde_json always needs Serde built with std. If you need JSON support without a standard library, please use serde-json-core instead of serde_json.

I'm not English native speaker, but does this section is talking about default case? to using `serde_json` in `no_std` context require declare `serde = { version = "1.0", default-features = false }` and I've do this.

Actually `serde_json_core` still has this problem, because of `serde` compiled with `std`.

the compile error are

```
error: duplicate lang item in crate sp_io (which frame_support depends on): panic_impl.
  |
  = note: the lang item is first defined in crate std (which serde depends on)

error: duplicate lang item in crate sp_io (which frame_support depends on): oom.
  |
  = note: the lang item is first defined in crate std (which serde depends on)
```

which not clear.

I've attached a compile log that showed many crate compiled with `std` feature but Substrate Runtime should be already disabled `std`, that's a little weired.

**Comment by bkchr** [comment]
Yeah the feature is enabled by a `proc-macro`.

This is the cargo issue you are searching for: https://github.com/rust-lang/cargo/issues/7915

**Comment by jasl** [comment]
> Yeah the feature is enabled by a `proc-macro`.
> 
> This is the cargo issue you are searching for: [rust-lang/cargo#7915](https://github.com/rust-lang/cargo/issues/7915)

Thank you, so it seems there's no good way for the problem now, I modified a special `serde` (removing all `std` relates codes) to workaround.

I just leave an issue to mention this

**Comment by bkchr** [comment]
So this can be closed?

**Comment by jasl** [comment]
> So this can be closed?

OK closed

**Comment by jiyilanzhou** [comment]
I meet this question, when i add `#![cfg_attr(not(feature = "std"), no_std)]`, It work well.

**Comment by jasl** [comment]
> I meet this question, when i add `#![cfg_attr(not(feature = "std"), no_std)]`, It work well.

I switch to nightly Cargo resolver2 then the problem solved

**Comment by NoCtrlZ** [comment]
The same error happened.
The both of solution didn't work for me...
```
#![cfg_attr(not(feature = "std"), no_std)]
```
```
[package]
resolver = "2"
```
Was this problem fixed?
