### ISSUE TITLE
RPC to dry run a transaction

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#6298]
A new RPC to allow user submit transaction and dry run it and return all events.

It should respect to weight limits so this cannot be used to DOS the node.

Should have an option to disable signature validation to make this more useful (able to detect transaction will not success before asking user to sign).

`state_call` with `BlockBuilder_apply_extrinsic` may be able to achieve something similar but it is way too hard to use and does not expose events.

This will need to be an unsafe RPC to avoid ddos nodes.

**Comment by bkchr** [comment]
And this is an unsafe RPC?

**Comment by xlc** [comment]
In terms of safeness, I think this is similar to submit extrinsic? or `state_call`?

Any places for me to check is `state_call` unsafe other than reading the code?

**Comment by bkchr** [comment]
I mean, if you open a RPC where everyone can send you transactions to dry run them. They can ddos your node. Especially if they can disable signature checking.
