### ISSUE TITLE
Couldn't install on Fedora Solution

### ISSUE THREAD

**Issue by Mikerah** [paritytech/substrate#6299]
As I was attempting to follow the install instructions for Substrate, none of the instructions work for my variant of Linux, Fedora 27. This line

```
sudo apt install -y cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev
```
didn't compile on my system. 

What I wrote to solve this issue is the following:

```
sudo dnf install -y cmake pkg-config openssl-devel git gcc @development-tools clang clang-devel
```

**Comment by bkchr** [comment]
Probably an issue for https://github.com/substrate-developer-hub/knowledgebase, so I will close this now.

But pinging @JoshOrndorff to get you some attention.
