### ISSUE TITLE
When I ran our substrate node and encountered this problem.

### ISSUE THREAD

**Issue by geniusun** [paritytech/substrate#6303]
I attached the bug report below.

   0: sp_panic_handler::set::{{closure}}

   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   2: rust_begin_unwind
             at src/libstd/panicking.rs:380
   3: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
   4: <sp_database::kvdb::DbAdapter<D> as sp_database::Database<H>>::commit
   5: sc_client_db::Backend<Block>::try_commit_operation
   6: <sc_client_db::Backend<Block> as sc_client_api::backend::Backend<Block>>::commit_operation
   7: <&sc_service::client::client::Client<B,E,Block,RA> as sp_consensus::block_import::BlockImport<Block>>::import
_block
   8: <sc_finality_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sp_consensus::block_import::BlockImpo
rt<Block>>::import_block
   9: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sp_consensus::block_import::BlockImport<Block>>::i
mport_block
  10: sp_consensus::import_queue::import_single_block
  11: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  12: <futures_util::future::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  13: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  14: futures_executor::thread_pool::PoolState::work
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
  20: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/boxed.rs:1015
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:80
  21: start_thread
  22: clone

Thread 'import-queue-worker-0' panicked at 'Critical database eror: Custom { kind: Other, error: Error { message: "
IO error: No space left on deviceWhile appending to file: ./node-data/chains/prochain_testnet/db/005333.log: No spa
ce left on device" } }', <::std::macros::panic macros>:5

This is a bug. Please report it at:

  https://github.com/paritytech/substrate/issues/new

pure virtual method called
terminate called without an active exception
Aborted

**Comment by arkpar** [comment]
`No space left on device` - ran out of disk space.
