### ISSUE TITLE
client/network-gossip: Receive message from unregistered peer

### ISSUE THREAD

**Issue by mxinden** [paritytech/substrate#6331]
Some Substrate based nodes repeatedly log ["Got message from unregistered peer"](https://github.com/paritytech/substrate/blob/master/client/network-gossip/src/state_machine.rs#L323) on stderr.

The log line implies that the node received a message from a remote peer that the node is not currently connected to. `NotificationStreamOpened`, `NotificationsReceived` and `NotificationStreamClosed` are send via a single ordered channel which contradicts the logged error.

**Comment by tomaka** [comment]
This is most likely a duplicate of #5592 but we should leave it open and close when we know it's fixed.

**Comment by tomaka** [comment]
"Got message from unregistered peer" doesn't seem to happen anymore. Closing.
