### ISSUE TITLE
Create Key Pair and sign message at runtime benchmarking setup

### ISSUE THREAD

**Issue by thashimoto1998** [paritytech/substrate#6345]
Is it possible to implement create Key Pair (public key can convert into AccountId) and sign message at runtime benchmarking setup?
If possible, could you tell me implementation examples that would be helpful?

**Comment by bkchr** [comment]
cc @shawntabrizi

**Comment by shawntabrizi** [comment]
@thashimoto1998 can you clarify your use case here?

For the runtime benchmarking stuff, the accounts are generated within the benchmarking code, and we dont take any external input like signed messages.

**Comment by thashimoto1998** [comment]
Yes I can.
I have been developing state channel runtime module library. In the state channel, both parties sign the message off-chain and validate the message on-chain. To sign a message off-chain, Implementation of create KeyPair and sign the message at runtime benchmark setup is necessary.

**Comment by shawntabrizi** [comment]
Can you provide hard-coded messages that you know will pass verification?

**Comment by thashimoto1998** [comment]
I am not sure how to implement hardcoded co-signed message.
May I take it that there is not feature to create key pair and sign message in runtime layer and feature in runtime layer only can execute at benchmark?

**Comment by shawntabrizi** [comment]
Yes, that is how it is currently

**Comment by thashimoto1998** [comment]
I understand. Thank you.
