### ISSUE TITLE
Disable change consensus

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/substrate#6350]
Is it possible to disable the change consensus function?

**Comment by bkchr** [comment]
What is the change consensus function?

**Comment by noahsalvadordenjo** [comment]
I thought we could update our consensus with a new one and let all the nodes know about this new one

**Comment by bkchr** [comment]
If you speak about swappable consensus, substrate currently not supports this.

**Comment by pepyakin** [comment]
If you mean the state transition function (what we refer as "runtime" includes STF) then there is no way to disable that either. 

However, you can write such a runtime that just doesn't include a way to submit a new version of the runtime. That effectively makes changing the chain's STF impossible without something like hard forking.
