### ISSUE TITLE
Allow #[cfg(test)] in decl_module 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#6353]
Perhaps not super critical, but there is one use case in system in which we are exposing a pretty darn bad transaction only for testing. 

https://github.com/paritytech/substrate/blob/740115371b096af4ca2c3b2c860d95ba801cffcb/frame/system/src/lib.rs#L566-L572

Ideally, we should allow such `#cfg[test]`s in the `decl_mdoule`, or the test that is using this code should be reformulated to achieve the same goal in another way.

**Comment by bkchr** [comment]
Use a different way. We can add a custom module with this function.

**Comment by kianenigma** [comment]
No need for this anymore. We still don't allow it in the new one either, but not important anyhow.
