### ISSUE TITLE
Dynamically set runtime code with runtime spec

### ISSUE THREAD

**Issue by geigerzaehler** [paritytech/substrate#6376]
We would like to run the node with different initial runtime wasm code for development and testing. To avoid recompiling the node (which takes a long time) we want to make the runtime code configurable at node runtime (say, via a command line option). Accomplishing this with [`GenericChainSpec`](https://releases.parity.io/substrate-rustdoc/sc_service/struct.GenericChainSpec.html) seems impossible. The simplest implementation would look something like the following.
~~~rust
function (runtime_code: &[u8]) -> GenericChainSpec<GenesisConfig> {
  let make_genesis_config = || {
     GenesisConfig {
        system: Some(SystemConfig {
          code: runtime_code.to_vec(),
          changes_trie_config: Default::default(),
        }),
     }
  };

  GenericChainSpec::from_genesis(
     ...
     make_genesis_config,
     ...
  )
}

This code does not compile however. `GenericChainSpec::from_genesis` requires a `static` lifetime bound for the `make_genesis_config` function. This implies `static` lifetime for `runtime_code` which of course defeats the goal of having the runtime code be dynamically defined.

Is it possible to lift the restriction for the genesis config constructor in `from_genesis`?

**Comment by bkchr** [comment]
Why can you not just create different chain specs?
