### ISSUE TITLE
Update `decl_module` to make `type Error` mandatory

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#6418]
There are some pallets (`pallet-scheduler`, and few our ones) are using `decl_error` but did not expose it via `type Error = Error<T>;` in `decl_module`. 

We should make `type Error = Error<T>;`  mandatory and for pallets are not using `decl_error` yet, they can specify `type Error = &'static str;` meanwhile.

The error message should indicate how to resolve the error. i.e. add `type Error = &'static str;` 

If we want to be graceful, make it print a warning for now and make it error on next semvar breaking change.

**Comment by xlc** [comment]
I think we can close this? @thiolliere We can't make this mistake with the new pallet macro right?

**Comment by thiolliere** [comment]
Indeed we can close

yes in the macro, if you forget to put pallet::error on top of the error enum then nothing is derive on it, thus it can't be converted to DispatchError, so any usage will fail at compile time.
