### ISSUE TITLE
Make benchmark macro accept where clause

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#6432]
`decl_module` accepts a where clause, but it is not possible to write benchmark for such module without the ability to add where clause to `benchmark!` macro.

I have no idea what should the syntax be, but I need to attach `where <T as system::Trait>::Origin: OriginTrait<PalletsOrigin = T::PalletsOrigin>` somewhere.

cc @shawntabrizi 

Blocks #6387

**Comment by shawntabrizi** [comment]
Is this true for all the benchmarks?

If so we can probably stick it directly in the macro for now

**Comment by xlc** [comment]
I think it is true? Also without this the where clause syntax for `decl_module` is practically unusable, but it is not really used anywhere previously so I am not sure...

**Comment by xlc** [comment]
This is no longer required by #6387. @shawntabrizi you can decide if you want to keep this open or just close it.

**Comment by thiolliere** [comment]
I would prefer to make benchmarking handling where_clause same as decl_module, I assign myself and see if it difficult to do
