### ISSUE TITLE
Remove impl Randomness for ()

### ISSUE THREAD

**Issue by burdges** [paritytech/substrate#6452]
We gained an `impl<Output: Decode + Default> Randomness<Output> for ()` in https://crates.parity.io/frame_support/traits/trait.Randomness.html#foreign-impls added by https://github.com/paritytech/substrate/commit/cdceee247f46e2270db06fc69b9fa8c6f7e490da#diff-0010d009b169768f89902f63e50e3c10R780 which looks dangerous.

It's only used in frame/society/src/mock.rs which lives behind `#[cfg(test)] mod mock;` so maybe it can be replaced by pallet-randomness-collective-flip which provides insecure randomness for tests elsewhere? 

If we want this, then it would require the test feature be propagated into frame-support, like
```
impl<Output: Decode + Default> Randomness<Output> for () {
        fn random(subject: &[u8]) -> Output {
                if cfg!(test) {
                        Output::decode(&mut TrailingZeroInput::new(subject)).unwrap_or_default()
                } else {
                        panic!("Used () as Randomness in production")
                }
        }
}
```
<s>If test already implies std then one might play games with `std::collections::hash_map::RandomState` but presumably that's more cargo pain than its worth.

**Comment by rphmeier** [comment]
Tagging this as `Security` because it exposes an unsafe API to our end-users of Substrate
