### ISSUE TITLE
runtime: Refactor staking reward curve to be cached & dynamic

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#6469]
Staking reward curve is currently a static `PiecewiseLinear`, calculated once and only once in the block.

Instead, it should be a static, lazily cached value, not built unless needed, and re-built
in the case that input parameters have changed. The `ideal_stake` should be determined by the amount of parachain slots being bid on: this should be around `(75 - 25.min(slots / 4))%`.

We should probably introduce a new `trait Curve`, which declares the `calculate_for_fraction_times_denominator` function. `PiecewiseLinear` can impl this and staking pallet can require `RewardCurve` to `impl` it. We might get away with a simple `RefCell` to manage the cache and ensure that it can be updated as needed. Either way, we must ensure that the pieces are not recalculated on repeated calls.

**Comment by kianenigma** [comment]
cc @thiolliere

**Comment by thiolliere** [comment]
> Staking reward curve is currently a static PiecewiseLinear, calculated once and only once in the block.

Currently the calculation of the points happens at compile time, result is:
```rust
const REWARD_CURVE: PiecewiseLinear<'static> =
    {
        extern crate sp_runtime as _sp_runtime;
        _sp_runtime::curve::PiecewiseLinear::<'static>{points:
                                                           &[(_sp_runtime::Perbill::from_parts(0u32),
                                                              _sp_runtime::Perbill::from_parts(25000000u32)),
                                                              .......
                                                             (_sp_runtime::Perbill::from_parts(1000000000u32),
                                                              _sp_runtime::Perbill::from_parts(25073000u32))],
                                                       maximum:
                                                           _sp_runtime::Perbill::from_parts(100000000u32),}
    };
```

(reason for piecewise approximation was to avoid having to compute `2^fraction` on chain. though it is possible but not straightforward).

> Instead, it should be a static, lazily cached value, not built unless needed, and re-built
in the case that input parameters have changed. The ideal_stake should be determined by the amount of parachain slots being bid on: this should be around (75 - 25.min(slots / 4))%.

how often would `the amount of parachain slots being bid on` change ?
* either we provide the new approximation on every change
* or we should compute the function on chain (for this I can try to find some algorithm for `2^((ideal_stake_rate - current_stake_rate)/falloff)`)
* (or maybe if only ideal_stake change we can put into static something use for computing `f(ideal_stake_rate, current_stake_rate)` )

**Comment by gavofyork** [comment]
This needs to be addressed. It's made more urgent by the introduction of gilts, which will also affect the ideal amount. Perhaps there's some way of precomputing the shape of the curve at compile time and doing a linear interpolation at runtime.

> either we provide the new approximation on every change

No - changes can happen often and we can't upgrade the runtime for each of them at exactly the same time.

> or we should compute the function on chain (for this I can try to find some algorithm for 2^((ideal_stake_rate - current_stake_rate)/falloff))

This is the easiest way forward for now. We can save the computed points somewhere in storage to make it a bit faster(?) in case the inputs haven't changed since the last computation.

> (or maybe if only ideal_stake change then we can put into static something used for computing f(ideal_stake_rate, current_stake_rate) )

This might be a sensible optimisation.

**Comment by thiolliere** [comment]
staking pallet is now generic on the reward curve and pallet-staking-reward-fn https://github.com/paritytech/substrate/pull/8332 allows to compute some inflation on-chain.
Thus this is done
