### ISSUE TITLE
seal: avoid hitting the trie when computing weight

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#6486]
For computing the weight cost of `put_code` we fetch the schedule from the storage. However, accessing the storage within the `validate_transaction` path is discouraged. That's why we should consider switching the `put_code_per_byte_cost` to be a const.

**Comment by athei** [comment]
This will be solved once the proper weights arrive. The prices for the extrinsics are then read directly from the `WeightInfo` Trait and not from the schedule.
