### ISSUE TITLE
Confirm Phragmen will always select a nominator who nominates only one validator

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#6490]
Test/fuzzing should confirm the behavior of Phragmen where a nominator is never left out of the stakers set for having only backed one validator.

**Comment by kianenigma** [comment]
Basically: `reduce()` will not remove a nominator with a single vote. 

Answer being: generally speaking **no** and it is easy to see why: reduce only works on cycles, you need cycles in the graph of nominators to validators and then you remove one edge from that cycle. I cannot see how you can be part of a cycle if you have casted one vote only. cc @AlfonsoCev
