### ISSUE TITLE
Add 'retractTip' to tips opened with 'tipNew'

### ISSUE THREAD

**Issue by rrtti** [paritytech/substrate#6504]
A finder can currently call `retractTip` for tips opened with `reportAwesome`, but not with `tipNew`. 

Only council members can call `tipNew`, however they cannot retract if there is an error on the tip. It is not possible for `tipNew` msg to be mapped back to origin (no finder), guessing this is the reason behind the inability to retract. Ideally, once a council member calls `tipNew`, the same address should be able to call `retractTip` if needed. Not any council member, but the one who opened the tip.

**Comment by shawntabrizi** [comment]
Closed with https://github.com/paritytech/substrate/pull/6511
