### ISSUE TITLE
rc4 The bootnode you want to connect to at `/ip4/192.168.136.196/tcp/30333` provided a different peer ID than the one you expect: `12D3KooWSVSi7jXwGcfBBB5Uq9Pj2UakNakiqVwrS1TPdUzReLE

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/substrate#6534]
while using the newest rc4 template following the start a private network tutorial , on start up it give's me the following error
```
The bootnode you want to connect to at `/ip4/192.168.136.196/tcp/30333` provided a different peer ID than the one you expect: `12D3KooWSVSi7jXwGcfBBB5Uq9Pj2UakNakiqVwrS1TPdUzReLE
````
while im using the correct peer id

**Comment by bkchr** [comment]
This means the node has a different peer id. Please take a look into the log to find the correct peer id.

**Comment by noahsalvadordenjo** [comment]
https://drive.google.com/drive/folders/1NvPMQisQBB5K_P0Z-CnAk5aHzTsDRRwC?usp=sharing

**Comment by bkchr** [comment]
Why does it want to connect to all these ips? Did you changed the chain spec and added them?

**Comment by noahsalvadordenjo** [comment]
No, only cloned the git repository

**Comment by bkchr** [comment]
It tries to connect via `10.75.0.1`. Not sure.

Which repo did you clone?

**Comment by noahsalvadordenjo** [comment]
```
 git clone -b v2.0.0-rc4 --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
````

**Comment by bkchr** [comment]
Works for me without problems. You also don't need to specify a bootnode, as MDNS should find your other node

**Comment by noahsalvadordenjo** [comment]
sorry

**Comment by bkchr** [comment]
Did you find your problem?

**Comment by noahsalvadordenjo** [comment]
Im cloning the repo again to see if it works, actually my real problem is in here
https://github.com/noahsalvadordenjo/dev
produces blocks in dev mode but not in production

**Comment by noahsalvadordenjo** [comment]
It works
