### ISSUE TITLE
client/network: Rename DebugInfoBehaviour to InfoBehaviour

### ISSUE THREAD

**Issue by mxinden** [paritytech/substrate#6541]
I would like to use the `protocol_version` reported via the [`DebugInfoBehaviour`](https://github.com/paritytech/substrate/blob/master/client/network/src/debug_info.rs#L81) to only add peers to the DHT that are of the same protocol (e.g. Kusama). See https://github.com/paritytech/substrate/issues/5825 for details.

https://github.com/paritytech/substrate/blob/ec2ab7978a54e7f20af2f9ac12bde7719bb744fb/client/network/src/debug_info.rs#L41-L43

This would elevate the `DebugInfoBehaviour` from previously only being used for debugging to now being used as a core building block. Thus **I would like to rename `DebugInfoBehaviour` to `InfoBehaviour`**.

Objections? Alternative naming suggestions?

//CC @romanb @tomaka

**Comment by dvdplm** [comment]
`PeerInfoBehaviour`?

**Comment by tomaka** [comment]
:+1: for the name change
