### ISSUE TITLE
add RetractVote to Council voting process

### ISSUE THREAD

**Issue by rrtti** [paritytech/substrate#6558]
To send a treasury proposal to the Council, members call `Propose` in the Council module - this sends the proposal to vote by the Council **and** records the vote of the sender. This causes an issue when the Prime Member sends a proposal, because by signalling their vote councillors complain about the Prime Member signalling a decision in the best case scenario and some rely on soft-voting to pass motions in the worst. 

I'd like to:
1. add `RetractVote` call for the Prime Member to use (and vote aye or nay later when needed), or
2. allow the Council member to send proposals to council for voting without adding their vote in the same call.

**Comment by emostov** [comment]
@shawntabrizi do you have any thoughts on the merit of option 1 vs option 2? 

I am leaning towards adding an extrinsic (e.g. `propose_no_vote`) or maybe just a flag param to the existing `propose` (e.g. `selfVote: bool`) that allow not recording a vote in the first place. With this approach we avoid having to modify the `Voting` storage item to remove the vote after the `propose` call.
