### ISSUE TITLE
State tracing in runtime

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#6572]
Especially for balance transfers exchanges are asking us to provide not only the wasm blob and the final state but what is called "state traces", effectively the specific low level functions that are being executed by a specific transaction and the state changes those finally lead to. In past implementations we just added logging facilities to the specific function calls and be done with it but with the separation of concerns in substrate between client and runtime this is a bit more tricky for us.

Following #6916, we need to add `event_debug!`-traces with the to-be-hashed-key and its value prior to any `unhashed`-call that changes state – maybe also add `event_trace!` to the inner of `unhashed` as well as to all non-mutating-unhashed-calls to allow for debugging. Combined with the `span`-tree we should be able to identify which extrinsic lead to which changes.

**Comment by bkchr** [comment]
Isn't this issue basically this: https://github.com/paritytech/substrate/pull/6401 + `state=tracing`?

**Comment by bkchr** [comment]
And how should non `decl_storage` storage accesses being traced?

**Comment by bkchr** [comment]
Maybe we could just support a node only changes trie?

**Comment by xlc** [comment]
Sounds like https://github.com/paritytech/substrate/issues/4939?

RPC state_queryStorage is already able to fetch all the changes of a particular storage key and all the blocks causing the changes.

**Comment by shawntabrizi** [comment]
@gnunicorn @dvdplm Can we close this?
