### ISSUE TITLE
seal: Storage rent for code

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#6596]
Currently, no rent is collected for code that is stored on-chain. Only the state of the individual contracts is subject to rent payments. This is because code is deployed independently of a contract and can then be used by any contract without further costs. There is also no way (apart from governance) to remove code stored on the chain.

This opens up the chain to DoS because anyone can clutter the storage with code with only a one time cost that covers the computation costs of uploading the code.

For that reason, we propose that contracts should pay for the code they use. To incentives code sharing the costs are also shared between all users of a code blob. We change the rent formula that is calculated on contract access or `claim_surcharge` to:

```
rent = storage_rent + (code_size / num_code_users)
```

The costs for code storage converge against zero with more users using it. Due to integer arithmetic is reaches zero once `num_code_users > code_size`.

One issue is that the rent is not collected every block but only when the contract is accessed or `claim_surcharge` is called. The `num_code_users` can change in between blocks making the calculation inaccurate. However, we argue despite the inaccuracy we cannot come up with an attack that turns this into a DoS vector.

Steps that are necessary for implementation:

- Count the number of users per code hash and delete the code hash once the counter reaches zero
- The `set_code` **dispatchable** is replaced with `instantiate_with_code` because every code_hash needs at least one user. The `seal_instantiate` contract callable function stays untouched. Contracts cannot deploy code.
- Change the rent formula of contracts to also account for the code size.

**Comment by Robbepop** [comment]
Naming proposal:

`seal_instantiate` -> `seal_instantiate_from`
`seal_put_code` -> `seal_instantiate`

**Comment by seanyoung** [comment]
At some point in the future, it would be great to have libraries stored on chain. For example, a wasm dynamic linked library could be available as code. Maybe we `seal_instantiate` doesn't make much sense in this context.

**Comment by athei** [comment]
> Naming proposal:
> 
> `seal_instantiate` -> `seal_instantiate_from`
> `seal_put_code` -> `seal_instantiate`

This rename would change the semantic of an existing name. I don't want to cause confusing and code churn by doing so. Keeping `seal_instantiate` the way it is, is my only condition. By doing so we do not have to touch host functions in any way right now because there is no host function that can deploy new code. We can add this later if it turns out that contracts want to generate new contract code but this is an entirely different topic.

I would just replace the `put_code` **dispatchable** with a new function. This name is still open for grabs. Ideas:

```
instantiate_with_code
instantiate_with_upload
instantiate_uploading
```

**Comment by Robbepop** [comment]
How about `instantiate_new`?

**Comment by athei** [comment]
I did not consider that because it is misleading: It is not guaranteed that the instantiated code is new. If you upload a code and the code hash already exists this existing code will be used.
