### ISSUE TITLE
sync: Propagate transactions only to the subset of peers

### ISSUE THREAD

**Issue by grbIzl** [paritytech/substrate#6603]
In the current implementation sync layer propagates incoming transactions to all available peers: https://github.com/paritytech/substrate/blob/master/client/network/src/protocol.rs#L1210

This may cause significant load of incoming transactions for the peers, for example, during heartbeats sending: http://grafana.parity-mgmt.parity.io/d/bmwoiGWMz/network-transactions-overview?orgId=1&refresh=5s&from=now-1h&to=now

In Parity Ethereum client in this place there is an optimization: https://github.com/openethereum/openethereum/blob/master/ethcore/sync/src/chain/propagator.rs#L311 That propagates transactions only to the subset of the connected peers (randomly chosen)

I suggest to implement the similar logic in Substrate as well. 

Please note: as far as I've understood, all transactions should be propagated to the peers with authority role anyway.

**Comment by grbIzl** [comment]
cc @arkpar @NikVolf

**Comment by grbIzl** [comment]
(Created in terms of investigation for https://github.com/paritytech/stakingops-issues/issues/28 )

**Comment by tomaka** [comment]
cc #6604

**Comment by NikVolf** [comment]
What is here is implemented in https://github.com/paritytech/substrate/pull/6601

but it is only part of the story

**Comment by grbIzl** [comment]
> What is here is implemented in #6601
> 
> but it is only part of the story

Ok. You did it without an issue, that's why I didn't find any and create one

**Comment by grbIzl** [comment]
Closing this as duplicate of #6604 (where more general approach described)
