### ISSUE TITLE
Breaking CLI changes in latest master

### ISSUE THREAD

**Issue by ddorgan** [paritytech/substrate#6607]
Seeing a new error when trying to use the latest master with the same CLI options that had been working..

```
Jul 08 18:30:41 hostname kusama[3658]: Error: FlexiLogger(Parse("ignoring invalid part in log spec \'sub-authority-discovery\' (contains a dash or whitespace)", LogSpecification { module_filters: [ModuleFilter { module_name: Some("sc_offchain"), level_filter: Trace }, ModuleFilter { module_name: Some("consensus"), level_filter: Trace }, ModuleFilter { module_name: Some("imonline"), level_filter: Trace }, ModuleFilter { module_name: Some("runtime"), level_filter: Trace }, ModuleFilter { module_name: Some("client"), level_filter: Trace }, ModuleFilter { module_name: Some("txpool"), level_filter: Debug }, ModuleFilter { module_name: Some("slots"), level_filter: Trace }, ModuleFilter { module_name: Some("forks"), level_filter: Trace }, ModuleFilter { module_name: Some("babe"), level_filter: Trace }, ModuleFilter { module_name: Some("sync"), level_filter: Trace }, ModuleFilter { module_name: Some("afg"), level_filter: Trace }], textfilter: None }))
```

Removing ```sub-authority-discovery``` from the logging options was required.

**Comment by ddorgan** [comment]
Also can we not exit for these types of errors and just print a warning. These are not fatal problems.

**Comment by pscott** [comment]
I legitimately thought that exiting instead of warning was better, because when one starts a node, there are a lot of logs that pop out, and one could easily "miss" those warnings, and then wonder why his debug statements are not being logged.

I can of course not error on this and simply print a warning (will be with `eprintln!`) if that's better :)

**Comment by abebeos** [comment]
@pscott  , @ddorgan , 2 linked PRs never made the merge. Is this still actual?

**Comment by bkchr** [comment]
Not actual anymore.
