### ISSUE TITLE
subkey verify fails

### ISSUE THREAD

**Issue by chevdor** [paritytech/substrate#6613]
I am using subkey from the current master.

Checking out the doc shows:
```
USAGE:
    subkey verify [FLAGS] <sig> <uri>
```

I already have a message (=CHALLENGE), a seed (SEED) and a signature (SIG). The following fails:
```
$ echo $CHALLENGE | ./target/release/subkey verify $SIG $SEED
Error: Signature invalid.
```

Here are the contents:
```
$ echo $SEED
0xe270c3a68e24acda8805d3b4929d0a46d53caacee2df87b265df5f476ada6b70
```

```
$ echo $CHALLENGE
challenge
```

```
$ echo $SIG
7878a09c3b52af461ef972337fa34993a5fe50ba3796c51276c68e05de3e0b3724c6807eabb9b21168131c81e444d98594e8fdd915c760c7ae9542add34eca8d
```

SIG was obtained running:
```
SIG=`echo $CHALLENGE | ./target/release/subkey sign $SEED`; echo 0x$SIG
```

**Comment by chevdor** [comment]
I realize that my commands are wrong due to echo adding some newlines.

Here is the correction:
```
SIG=`echo -n $CHALLENGE | ./target/release/subkey sign $SEED`; echo 0x$SIG
```

It fails the verification nonetheless:
```
echo -n $CHALLENGE | ./target/release/subkey verify $SIG $SEED
Error: Signature invalid.
```

**Comment by chevdor** [comment]
🤦  if we would need the `SEED` to verify a signature, that would be a real problem.

My confusion came from following the doc blindly:
```
subkey verify [FLAGS] <sig> <uri>
```

We probably should replace `<uri>` by `<addr>`.

Passing the address and not the seed works all fine.
I keep this issue open so the doc can be fixed.

**Comment by herou** [comment]
@kianenigma  Can I work on this ticket?

**Comment by kianenigma** [comment]
Yes of course @herou
