### ISSUE TITLE
Check that the authority-discovery module discovers all (or almost all) validators

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6615]
https://github.com/paritytech/substrate/pull/6614 adds a new metric that reports the number of validators known to the authority-discovery module.

This issue is a reminder that, after this PR has been merged and deployed on our nodes, we should check if it reports a correct value.

**Comment by tomaka** [comment]
The metric is now on 8 nodes, and they seem to be somewhere between 14 and 16 known validators.

![Screenshot from 2020-07-10 18-38-15](https://user-images.githubusercontent.com/1412254/87177839-949afb80-c2dc-11ea-9714-1790c17f5f25.png)

**Comment by mxinden** [comment]
As of today the authority-discovery module is still disabled by default on Polkadot: https://github.com/paritytech/polkadot/blob/master/cli/src/cli.rs#L62-L72. I would still expect a node to find more validators as at least Parity and web3 is enabling this feature.

**Comment by tomaka** [comment]
Everything seems to work fine on Kusama!

![Screenshot from 2020-07-22 13-06-19](https://user-images.githubusercontent.com/1412254/88169457-46f78a80-cc1c-11ea-90af-4423e518a84f.png)

**Comment by tomaka** [comment]
Closing this as done :tada:
