### ISSUE TITLE
Is it possible to use different tokens to pay gas fee for the different runtimes?

### ISSUE THREAD

**Issue by AlexZhenWang** [paritytech/substrate#6624]
I now have a runtime related to a web app, I want to pay the gas fee for my users. I am thinking to drop some gas fee to users, but I don't want the user to use that token to pay for other extrinsics. Is it possible to use the different tokens to pay the gas fee for the different runtimes or even for the different methods? 

I don't mean in the recent versions, just want to see in the future, technically, whether that is possible.

**Comment by pepyakin** [comment]
Hey! Yeah, technically I think that's possible, although there are some caveats.

Gas is actually the same as weight, therefore the issue boils down to a custom way of buying weight. Then, we used to have a mechanism called `ext_dispatch_call` that allowed a contract to use its gas as weight to call into the host runtime - it would have given a headache, but now we don't have it in favor of a more opt-in approach #6466 - chain extensions. So calling back into the runtime shouldn't be a problem as well.
