### ISSUE TITLE
Remove clear_on_drop dependency

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6677]
After https://github.com/paritytech/substrate/pull/6676, we no longer need the `clear_on_drop` dependency in the browser node.

**Comment by xlc** [comment]
So the root cause of https://github.com/paritytech/substrate/issues/4179 is fixed?

**Comment by tomaka** [comment]
Before #6676, `clear_on_drop` was a dependency of `ed25519-dalek`. The root cause of #4179 is that compiling the runtime isn't supposed to compile `ed25519-dalek` (and thus not `clear_on_drop` either).
