### ISSUE TITLE
Sweep runtime for panics

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#668]
The runtime should not be able to panic except under circumstances that are statically analysable.

Basically, this means once any necessary inherent extrinsics have been determined to be present and valid, and once the transaction extrinsics have been determined to be properly signed and coming from accounts with the correct nonce and that can afford to pay for them, then `execute_block` MUST NEVER PANIC.

**Comment by DemiMarie-parity** [comment]
Can we statically verify this?  It seems to me that by making `panic_fmt` refer to an undefined symbol, we will get a link failure if the compiler cannot prove that the panic code is unreachable.
