### ISSUE TITLE
Runtime cleanup: Single module list in runtime/lib.rs

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#669]
We should ensure all modules implement/export Events/Logs/Storage/Call/GenesisConfig. Then rather than having three macros (`impl_outer_event`, `impl_outer_log`, `impl_outer_dispatch`) plus any others for the JSON metadata stuff, each listing most modules, we have only one `fuse_modules!` macro which lists the macros once and does the job of fusing together each of the modules where required for Events/Logs/Storage/Call/GenesisConfig.

Target API:

```rust
construct_runtime! {
	System: system,	// defaults to below
	System: system::{module, trait, call, storage, event, origin, log, config},	// defaults to below
	System: system::{module as Module, trait as Trait, call as Call, storage as Storage, event as Event, origin as Origin, log as Log, config as GenesisConfig},
	Consensus: consensus,
	Balances: balances,
	Timestamp: timestamp,
	Session: session,
	Staking: staking,
	Democracy: democracy,
	Council: council,
	CouncilVoting: council_voting,
	CouncilMotions: council_motions,
	Treasury: treasury,
	Contract: contract,
}
```

**Comment by bkchr** [comment]
Do we want to close this issue?
Currently renaming of types is missing in the current implementation. Should I add this directly or do we want to postpone this?

**Comment by gavofyork** [comment]
no need to add directly, i think. will close and we can enhance later as needed.
