### ISSUE TITLE
Add a Prometheus alert when the number of file descriptors is leaking

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6707]
Crashes caused by reaching the `ulimit` have unfortunately been surprisingly common.
I think we should have a Prometheus alert that detects that, in order to catch regressions early on.

It's a bit unclear to me, however, *what* exactly we'd be measuring.

**Comment by mxinden** [comment]
Done in https://github.com/paritytech/substrate/pull/6946.
