### ISSUE TITLE
Thread 'main' panicked at 'Authorities are already initialized!'

### ISSUE THREAD

**Issue by nasa8x** [paritytech/substrate#6733]
When I create "Create a Custom Chain Spec"
`
./target/release/substrate build-spec --disable-default-bootnode --chain local > custom-spec.json
`
Then update 2 parameters:

`
"palletBabe": {
        "authorities": [
          [
            "5FL9P7BvRryC9UjcWsTTgnni4WqKzfPjTt2ca7q7Bg4b98GZ",
            1
          ]
        ]
      },
`
`
"palletGrandpa": {
        "authorities": [
          [
            "5GWy2CwG22W9Xne8aedrcTBpgH4dnHnUhn42tQBChmXH5Qgt",
            1
          ]
        ]
      },
`

Then create raw spec:
`
./target/release/substrate build-spec --disable-default-bootnode --raw --chain custom-spec.json > spec-raw.json
`

Error message:
`
Building chain spec
💸 new validator set of size 2 has been elected via ElectionCompute::OnChain for era 0

====================

Version: 2.0.0-rc5-bf0e1ec10-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: pallet_babe::Module<T>::initialize_authorities
   6: <(TupleElement0,TupleElement1,TupleElement2,TupleElement3) as pallet_session::SessionHandler<AId>>::on_genesis_session
   7: std::thread::local::LocalKey<T>::with
   8: sp_state_machine::basic::BasicExternalities::execute_with_storage
   9: <node_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
  10: sp_runtime::BuildStorage::build_storage
  11: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sc_chain_spec::ChainSpec>::as_json
  12: sc_service::chain_ops::import_blocks::build_spec
  13: sc_cli::commands::build_spec_cmd::BuildSpecCmd::run
  14: sc_cli::runner::Runner<C>::run_subcommand
  15: node_cli::command::run
  16: substrate::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal
  19: _main

Thread 'main' panicked at 'Authorities are already initialized!', /Users/nasa8x/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/macros.rs:13

This is a bug. Please report it at:

        https://github.com/paritytech/substrate/issues/new

`
How to fix it?

**Comment by bkchr** [comment]
Authorities come from `pallet_session`. You can not set other validators again using the `authorities` fields of `babe` and `grandpa`.
