### ISSUE TITLE
Why  cargo install --force subkey stop at 5.67%?

### ISSUE THREAD

**Issue by link202064** [paritytech/substrate#6736]
nter@MacBook-Air substrate % cargo install --force subkey --git https://github.com/paritytech/substrate --tag v2.0.0-rc4
    Updating git repository `https://github.com/paritytech/substrate`
       Fetch [==>                                                    ]   5.67%

mac:3c:22:fb:03:a2:83 
ip: 192.168.31.142

**Comment by bkchr** [comment]
Looks like some git error. Nothing that is related to Substrate.
