### ISSUE TITLE
Usage About `sort_unstable_by`, Could Cause `Storage root must match that calculated`?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/substrate#6752]
I got `Storage root must match that calculated` on my chain: https://github.com/darwinia-network/darwinia/issues/481
Some disscuss about `sort_unstable_by`: https://users.rust-lang.org/t/sort-unstable-in-native-and-wasm/46536

**Comment by bkchr** [comment]
https://doc.rust-lang.org/std/vec/struct.Vec.html#method.sort_unstable_by

> but may not preserve the order of equal elements.

So yes.

**Comment by AurevoirXavier** [comment]
So isn't this a bug in https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L2892? @bkchr

**Comment by bkchr** [comment]
Actually my comment was not correct. I looked again into the source code and as far as I can see, they don't use any randomness.
