### ISSUE TITLE
Authority-discovery should start publishing records one session in advance

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6772]
At the moment, the authority-discovery code publishes records of the local node if it is a validator in the current session.
The problem with that is that, when a validator enters the validator set, it will take a couple of minutes for it to be discoverable on the DHT.

The good news is that we already know, during each session, what the validators of the next session are going to be.

The authority-discovery module should be modified to start publishing records if our node is a validator of the next session as well.

cc @mxinden

**Comment by tomaka** [comment]
We also need to start querying the validators of the next session one session in advance.

**Comment by mxinden** [comment]
Both advanced publishing and querying is happening once https://github.com/paritytech/substrate/pull/6788 is merged.
