### ISSUE TITLE
Node Template Should Include accountNextIndex RPC Call

### ISSUE THREAD

**Issue by danforbes** [paritytech/substrate#6801]
From Shawn:

> There is an `rpc_extensions_builder` that you need to pass to the `PartialComponents`:
> https://github.com/paritytech/substrate/blob/master/bin/node/cli/src/service.rs#L101
> You should do as I have said, and replicate the `rpc_extensions_builder` and pass that to the `PartialComponents` under `other`
> I think there should be a `rpc.rs` file in `node-template/node/src`, and you just copy and paste the setup structure you see in main node, and only include this single RPC
> additional RPCs can then be added by simply modifying `rpc.rs` with `io.extend(new_rpc)` or however that syntax is
> Would also be good to include the transaction payment rpc too

**Comment by Meuko** [comment]
Want me to also add the transaction payment rpc?
