### ISSUE TITLE
Allow DB Whitelisting from Benchmarks

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#6802]
We should allow a developer writing runtime benchmarks to whitelist a DB key as a part of their benchmarking code.

This will most commonly be used to whitelist the `caller` of the benchmark extrinsic. This would mean we could use accounts other than `caller, 0, 0` as the caller of a function, and correctly ignore changes to that account.

This would involve adding/change the host functions exposed by the benchmarking DB. Right now we have `set_whitelist` which allows you to set a complete whitelist (or reset a whitelist by setting it to an empty vec). We should probably introduce an `add_to_whitelist` function which simply appends new keys to the existing whitelist.

**Comment by thiolliere** [comment]
ideally I would add get_whitelist, add_to_whitelist, remove_from_whitelist.

For instance on_initialize might want to remove caller account data from whitelist, this is handy but not necessary.

Though we currently put into all genesis storage keys. and some might need to be remove from it.

**Comment by thiolliere** [comment]
I think the ideal, without touching more Ext trait, would be to have in benchmarking macro a whitelist variable available somehow:
```rust
	propose_spend {
		let u in 0 .. 1000;
		// Here make a available mut whitelist: Vec<Vec<u8>>
		let (caller, value, beneficiary_lookup) = setup_proposal::<T>(u);
	}: _(RawOrigin::Signed(caller), value, beneficiary_lookup)
```
and in benchmarking expansion each benchmark will do set_whitelist with the modified set.

maybe the syntax: `	propose_spend(mut whitelist: Vec<Vec<u8>>) { ..} `
