### ISSUE TITLE
De-Alias Substrate Node Template

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#6834]
From my comment in https://github.com/paritytech/substrate/pull/6829

> We should try to remove aliasing from the pallets in general: https://github.com/paritytech/polkadot/pull/1530
> 
> So `balances` -> `pallet_balances`, `sudo` -> `pallet_sudo`, etc...
> 
> Looking at the cargo.toml file is an easy way to spot where aliasing is happening (wherever `package` is defined).

cc @danforbes @JoshOrndorff @riusricardo

**Comment by bkchr** [comment]
Done by: https://github.com/paritytech/substrate/pull/6836
