### ISSUE TITLE
Bind exclusively to specific IP:PORT

### ISSUE THREAD

**Issue by LukeWheeldon** [paritytech/substrate#6853]
As we are suddenly getting rather close to not having the protection of sentries anymore, anything that can help maximise the security of the validators is going to become even more important than before.

One of the aspects that could use some improvement is the current inability to bind / listen exclusively to a specific IP:PORT. Obviously the firewall can cover for this missing feature, but this is not optimal.

Also, given the recent discussion around profitability, having this feature would enable to neatly run more than one node on a single server. There as well, one can play with the ports, but this is not optimal either.

**Comment by tomaka** [comment]
If you pass for example `--listen-addr=/ip4/1.2.3.4/tcp/30333`, then the node will specifically listen on `1.2.3.4:30333`.

The listened addresses default to `/ip4/0.0.0.0/tcp/30333` and `/ip6/[::]/tcp/30333`, but if you explicitly pass `--listen-addr` then these defaults are overridden.

**Comment by LukeWheeldon** [comment]
That's actually working perfectly. Thank you @tomaka.
