### ISSUE TITLE
Do you guys check your email?

### ISSUE THREAD

**Issue by GildedHonour** [paritytech/substrate#6854]
Do you guys check your email?

**Comment by kaichaosun** [comment]
Can you go to [this channel](https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org?via=matrix.parity.io&via=matrix.org&via=web3.foundation) if you expect substrate related chat?

**Comment by GildedHonour** [comment]
What are other means to get into contact?

**Comment by kaichaosun** [comment]
Probably go to this page: https://www.parity.io/contact/
