### ISSUE TITLE
Make outer call/origin non breaking change when one pallet removes one call/origin

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#6855]
currently when one pallet removes it calls or its origin, or if a runtime removes a pallet, then all indices are changed.
This is annoying because calls are usually expected not to change and same for origin (which is stored on chain by scheduler).

(also maybe event should benefit from it as well.)

Instead in the codec implementation of event/calls/origin we should use (when decoding the variant index) a fixed index given to construct_runtime.

Ideally I was thinking first using ModuleToIndex and allow user to set the index of a module. But this is not perfect because currently some pallet have their call at index n and their origin at index p. Thus in order not to break those types anymore, construct_runtime should allow to configure them independently.

I have no idea of syntax yet.

**Comment by bkchr** [comment]
I thought about this as well already and I think we should just use the following syntax:
```
construct_runtime! {
    ...
    #[index(100)]
    SomeModule::some_module,
    ...
}
```
