### ISSUE TITLE
"Discovered external address" is printed too often

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6874]
The message "Discovered new external address for our node" happens every time an external address enters the list of known external addresses of our node.
The problem is that this list of known external addresses is heuristic. It can happen that an address enters the list, then leaves it, then re-enters it, and so on.

**Comment by tomaka** [comment]
The question in play in this issue is: is the current behaviour about addresses entering/leaving the local list considered normal?
I believe that yes, in which case the solution is to not print the message every time but less often.

**Comment by andresilva** [comment]
At least on my node I think the current behavior is expected and the heuristic is working fine. Most of the addresses that get re-discovered are either IPV6 (i.e. not used so often), or some private address which is very likely the result of some NAT translation in between. It makes sense that these unused addresses are evicted from the list (regardless of whether they're rediscovered afterwards).
