### ISSUE TITLE
Unified Pallet Storage Version

### ISSUE THREAD

**Issue by apopiak** [paritytech/substrate#6888]
We want to have a unified way of storing the storage version of a pallet so that it can be referenced (and adjusted) by migrations.

We will probably want to generate it from or tie it to the versioning of the pallet crate.

related to #6482

**Comment by thiolliere** [comment]
related to https://github.com/paritytech/substrate/issues/7210

I think this can be close now that all pallet write their version to storage.

as written there: https://github.com/paritytech/substrate/issues/7210#issuecomment-714526491

I think the migration strategy is in good shape now

**Comment by apopiak** [comment]
closed by #7208
