### ISSUE TITLE
Remove light-client specific GRANDPA block import

### ISSUE THREAD

**Issue by andresilva** [paritytech/substrate#6893]
Currently we have separate instances of `BlockImport` for dealing with GRANDPA logic for full and light nodes. Initially the full node used to call into the runtime when importing a block (to fetch authorities IIRC). This is no longer the case and the light client can just use the regular `GrandpaBlockImport` (I've tested and it works). Is there any reason why we need to have separate handling for the light client and use finality proofs (instead of just regular justifications as in the full node).

cc @svyatonik

**Comment by andresilva** [comment]
For example, in BABE we have no special handling for the light client and just use the same `BabeBlockImport`.

**Comment by ayushmishra2005** [comment]
@andresilva Could you please guide me from where I can start looking into the code?

**Comment by andresilva** [comment]
@ayushmishra2005 I already have these changes done in a branch, this issue was more for tracking discussion on this change.
