### ISSUE TITLE
Inconsistent Types Returned in `hashed_key()` and `hashed_key_for()`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#6901]
Ran into this inconsistency:

`hashed_key` for `StorageValue` returns a slice:
https://crates.parity.io/frame_support/storage/trait.StorageValue.html#tymethod.hashed_key

`hashed_key_for` for `StorageMap` returns a vec:
https://crates.parity.io/frame_support/storage/trait.StorageMap.html#tymethod.hashed_key_for

These probably should be consistent. Which one to use? Slice?

cc @thiolliere

**Comment by kianenigma** [comment]
Storage value hash is fixed length (given we always use one type of hasher, XXhas in this case), while map is not. I think this is the reason why this is the way it is.

**Comment by bkchr** [comment]
@kianenigma is right. Storage values will always use `twox_128`, while the hash of maps can be configured by the user.
