### ISSUE TITLE
Participating in Governance should be Free for First Time Voters

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#6904]
Our on-chain governance system could be enhanced to remove fees for first time voters.

Users are already pretty dis-incentivized to participate in governance (quite a bit of overhead required on the user to stay up to date and stuff). Knowing that they will have to pay some fees in order to simply vote is only additional burden that the chain may be able to compensate for.

Using https://github.com/paritytech/substrate/pull/6749 we are able to return all fees from within the extrinsic logic if we want.

I suggest that we could, in certain places, detect if the user has not already submitted a vote, and then when we detect this is the first vote, return the fee. Any additional change of the vote would still charge a fee.

Whether this would be allowable in public democracy votes is questionable. There is potential to be abused via sybil attacks, but certainly this should be allowable for the council. (fixed number of members, much more voting activity).

This means that being on council would not really cost you fees with no reward as it does today.

We could, if we really wanted to push this idea, actually give some dust balance to voters, to actually **incentivize** them to vote. Again, this would only be given on the first vote. This certainly would not work for public voting, but for council, again this could be a positive feature.

It would mean that every council member get some really insignificant amount of tokens for voting the first time on motions, but dust is still more than zero, so it is some incentive for council members to vote on every motion, tip, etc...

**Comment by g2udevelopment** [comment]
@shawntabrizi I am interested in this one to 'try' as an easy task to contribute to substrate. I see a mentor is available can you point me to this person?

**Comment by shawntabrizi** [comment]
Hi @g2udevelopment.

Yes this issue is marked as "easy", but would probably need someone who is relatively familiar with runtime development and the democracy pallet. How much experience do you have so far? Are you familiar with weights and fees in the runtime?

**Comment by shawntabrizi** [comment]
We found a new issue for @g2udevelopment to work on: https://github.com/paritytech/substrate/issues/6997

So this is still open for the right contributor!

**Comment by shamb0** [comment]
Hello @shawntabrizi 

I like to pick-up this, if it still open ?

**Comment by shawntabrizi** [comment]
@shamb0 yes, I think this would be a good next task for you :)

**Comment by shamb0** [comment]
Thanks @shawntabrizi , may be I align with you to capture more details on this requirement
