### ISSUE TITLE
off-chain worker code does not run after runtime upgrade

### ISSUE THREAD

**Issue by jimmychu0807** [paritytech/substrate#6908]
To reproduce, I started two nodes with substrate-node-template

```
./target/release/node-template --alice --port 30333 --base-path /tmp/alice
./target/release/node-template --bob --port 30444 --base-path /tmp/bob
```

Performed a runtime upgrade with `sudo:sudoUncheckedWeight(system:setCodeWithoutChecks)` after compiling the latest code wasm (here is my [before-update code](https://github.com/substrate-developer-hub/substrate-node-template/blob/jimmy/ocw-v1/pallets/template/src/lib.rs#L104-L106) and [after-update code](https://github.com/substrate-developer-hub/substrate-node-template/blob/jimmy/ocw-v2/pallets/template/src/lib.rs#L109-L111), here is [the diff](https://github.com/substrate-developer-hub/substrate-node-template/compare/jimmy/ocw-v1...jimmy/ocw-v2)).

I expected to see the `off-chain worker enter v2` message being spitted out regularly in the Substrate node log. But I don't.

**Comment by bkchr** [comment]
You are using `info!`. This does not work from wasm. That is the reason why you don't see any output. Use `sp_runtime::print` for example.

**Comment by amyliumaiyi** [comment]
had this same issue, thanks for pointer
