### ISSUE TITLE
authority-discovery: Keep the validator ID <-> PeerId mapping of past sessions

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#6910]
In addition to the mapping of the current and next session, the authority discovery needs to be able to provide the `PeerId`/`Multiaddr` of validator IDs of past sessions, in order for disputes to work.

It is unclear how many sessions in the past we want to keep.

**Comment by mxinden** [comment]
More details in https://github.com/paritytech/polkadot/issues/1461#issuecomment-675570746.

**Comment by rphmeier** [comment]
Can we implement this entire on the runtime API level (as @mxinden suggested elsewhere) just by returning the `AuthorityId`s of N past sessions from a particular runtime?

The only thing that we'd need to be sure of is that the authority-discovery service needs to publish a DHT record for _every_ key in that list as opposed to only the _first_. However, that may already be the implemented behavior.

**Comment by mxinden** [comment]
An implementation of this ticket should ensure that either (a) the resources required for a lookup of all authorities is negligible or (b) the lookup of all authorities is spread out over time, only requiring a negligible amount of resources at a given moment.

(Related discussion: https://github.com/paritytech/substrate/pull/6788#issuecomment-679135172)

**Comment by bkchr** [comment]
This was done by just returning the all relevant authorities from the runtime.
