### ISSUE TITLE
Maybe need "transfer_with_memo" in balances module, it's a very useful feature for a chain.

### ISSUE THREAD

**Issue by atenjin** [paritytech/substrate#6972]
`transfer` is the most important call for a chain. However Substrate/Polkadot balances module just provide `transfer`, which just relate to transactor/dest, but do not attach other information.

In Ethereum/ EOS or some other blockchain, transactor could add input_data(Ethereum) or add Memo(EOS) to attach some useful information, for example it could used in exchange for deposit, or some one need this memo to log message, or some one need a transfer with a proof and so on.

I suggest to add a new call in balances module,  which named `transfer_with_memo`. It's same as `transfer`，but just contains a more parameter "Memo"

e.g.:
```rust
/// Type for leaving a note when sending a transaction.
#[derive(PartialEq, Eq, Clone, sp_core::RuntimeDebug, Encode, Decode, Default)]
#[cfg_attr(feature = "std", derive(Serialize, Deserialize))]
pub struct Memo(Vec<u8>);

impl From<Vec<u8>> for Memo {
    fn from(raw: Vec<u8>) -> Self {
        Self(raw)
    }
}

impl From<&[u8]> for Memo {
    fn from(raw: &[u8]) -> Self {
        Self(raw.to_vec())
    }
}

impl AsRef<[u8]> for Memo {
    fn as_ref(&self) -> &[u8] {
        self.0.as_slice()
    }
}

#[cfg(feature = "std")]
impl std::fmt::Display for Memo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", String::from_utf8_lossy(&self.0))
    }
}

#[cfg(not(feature = "std"))]
impl core::fmt::Display for Memo {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{:?}", self.0)
    }
}

impl Memo {
    /// Returns true if the inner byte length is in the range of [0, 128] and passes the xss check.
    pub fn check_validity(&self) -> DispatchResult {
        if self.0.len() > MAXIMUM_MEMO_LEN as usize {
            Err(DispatchError::Other(
                "transaction memo too long, valid byte length range: [0, 128]",
            ))
        } else {
            xss_check(&self.0)
        }
    }
}

// in balances module:
decl_module! {
    pub struct Module<T: Trait<I>, I: Instance = DefaultInstance> for enum Call where origin: T::Origin {
        type Error = Error<T, I>;

// ....

        /// Same as the [`transfer`] call, but with a memo parameter
        #[weight = T::DbWeight::get().reads_writes(1, 1) + 70_000_000]
        pub fn transfer_with_memo(
            origin,
            dest: <T::Lookup as StaticLookup>::Source,
            #[compact] value: T::Balance,
            memo: Memo,
        ) {
            memo.check_validity()?;
            Self::transfer(origin, dest, value.into())?;
        }
   }
}
```
in this example, `Memo` just a parameter in a call, and do not participate calculation. Memo would be limited by length, and exclude some special characters.

So can guys tell me whether we could add this feature in balances module?

**Comment by thiolliere** [comment]
I don't see why we should do xss_check here, Memo should just be a is a vec of byte, application using it should be careful how they interpret it that's all.
I'm also not sure why limiting the length of it. user already pays for it. See frame_system::remark.

I don't mind having this if needed, but maybe user can already emulate it with pallet_utility::batch ?

**Comment by xlc** [comment]
I don't like the idea of (ab)use one feature to achieve something else. utility.batch is designed to make batch call, not glue two thing into one.
It will be super confusing to handle batches in batch, and trying to identify if a batch is actually a batch, or a transfer with memo.

**Comment by xlc** [comment]
Something like `utility.callWithMemo(call, memo)`?

**Comment by atenjin** [comment]
maybe I think just use `system.batch` for must of time.
