### ISSUE TITLE
could not compile `js-sys`

### ISSUE THREAD

**Issue by kaibbb** [paritytech/substrate#6974]
error: return value of constructor must be a bare path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4793:13
       |
  4793 | /             /// The
  4794 | |             #[doc = $ctor]
  4795 | |             /// constructor creates an array of unsigned 8-bit integers.
  4796 | |             ///
  ...    |
  4800 | |             #[wasm_bindgen(constructor)]
  4801 | |             pub fn new(constructor_arg: &JsValue) -> $name;
       | |___________________________________________________________^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: return value of constructor must be a bare path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4803:13
       |
  4803 | /             /// An
  4804 | |             #[doc = $ctor]
  4805 | |             /// which creates an array with an internal buffer large
  4806 | |             /// enough for `length` elements.
  ...    |
  4811 | |             #[wasm_bindgen(constructor)]
  4812 | |             pub fn new_with_length(length: u32) -> $name;
       | |_________________________________________________________^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: return value of constructor must be a bare path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4814:13
       |
  4814 | /             /// An
  4815 | |             #[doc = $ctor]
  4816 | |             /// which creates an array with the given buffer but is a
  4817 | |             /// view starting at `byte_offset`.
  ...    |
  4822 | |             #[wasm_bindgen(constructor)]
  4823 | |             pub fn new_with_byte_offset(buffer: &JsValue, byte_offset: u32) -> $name;
       | |_____________________________________________________________________________________^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: return value of constructor must be a bare path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4825:13
       |
  4825 | /             /// An
  4826 | |             #[doc = $ctor]
  4827 | |             /// which creates an array with the given buffer but is a
  4828 | |             /// view starting at `byte_offset` for `length` elements.
  ...    |
  4837 | |                 length: u32,
  4838 | |             ) -> $name;
       | |_______________________^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4845:32
       |
  4845 |               pub fn fill(this: &$name, value: $ty, start: u32, end: u32) -> $name;
       |                                  ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4850:34
       |
  4850 |               pub fn buffer(this: &$name) -> ArrayBuffer;
       |                                    ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4856:36
       |
  4856 |               pub fn subarray(this: &$name, begin: u32, end: u32) -> $name;
       |                                      ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4862:33
       |
  4862 |               pub fn slice(this: &$name, begin: u32, end: u32) -> $name;
       |                                   ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4869:36
       |
  4869 |               pub fn for_each(this: &$name, callback: &mut dyn FnMut($ty, u32, $name));
       |                                      ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4874:34
       |
  4874 |               pub fn length(this: &$name) -> u32;
       |                                    ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4879:39
       |
  4879 |               pub fn byte_length(this: &$name) -> u32;
       |                                         ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4884:39
       |
  4884 |               pub fn byte_offset(this: &$name) -> u32;
       |                                         ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4889:31
       |
  4889 |               pub fn set(this: &$name, src: &JsValue, offset: u32);
       |                                 ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4893:37
       |
  4893 |               pub fn get_index(this: &$name, idx: u32) -> $ty;
       |                                       ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: first argument of method must be a path
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:4897:37
       |
  4897 |               pub fn set_index(this: &$name, idx: u32, value: $ty);
       |                                       ^^^^^
  ...
  4997 | / arrays! {
  4998 | |     /// `Int8Array()`
  4999 | |     /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array
  5000 | |     Int8Array: i8,
  ...    |
  5032 | |     Float64Array: f64,
  5033 | | }
       | |_- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

     Compiling proc-macro-crate v0.1.4
     Compiling frame-support-procedural-tools v2.0.0-alpha.5
     Compiling parity-scale-codec-derive v1.2.0
     Compiling sp-runtime-interface-proc-macro v2.0.0-alpha.5
  error[E0433]: failed to resolve: use of undeclared type or module `Int8Array`
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5000:5
       |
  5000 |     Int8Array: i8,
       |     ^^^^^^^^^ use of undeclared type or module `Int8Array`

  error[E0433]: failed to resolve: use of undeclared type or module `Int16Array`
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5004:5
       |
  5004 |     Int16Array: i16,
       |     ^^^^^^^^^^ use of undeclared type or module `Int16Array`

  error[E0433]: failed to resolve: use of undeclared type or module `Int32Array`
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5008:5
       |
  5008 |     Int32Array: i32,
       |     ^^^^^^^^^^ use of undeclared type or module `Int32Array`

  error[E0433]: failed to resolve: use of undeclared type or module `Uint8Array`
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5012:5
       |
  5012 |     Uint8Array: u8,
       |     ^^^^^^^^^^ use of undeclared type or module `Uint8Array`

  error[E0433]: failed to resolve: use of undeclared type or module `Uint8ClampedArray`
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5016:5
       |
  5016 |     Uint8ClampedArray: u8,
       |     ^^^^^^^^^^^^^^^^^ use of undeclared type or module `Uint8ClampedArray`

  error[E0433]: failed to resolve: use of undeclared type or module `Uint16Array`
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5020:5
       |
  5020 |     Uint16Array: u16,
       |     ^^^^^^^^^^^ use of undeclared type or module `Uint16Array`

  error[E0433]: failed to resolve: use of undeclared type or module `Uint32Array`
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5024:5
       |
  5024 |     Uint32Array: u32,
       |     ^^^^^^^^^^^ use of undeclared type or module `Uint32Array`

  error[E0433]: failed to resolve: use of undeclared type or module `Float32Array`
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5028:5
       |
  5028 |     Float32Array: f32,
       |     ^^^^^^^^^^^^ use of undeclared type or module `Float32Array`

  error[E0433]: failed to resolve: use of undeclared type or module `Float64Array`
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5032:5
       |
  5032 |     Float64Array: f64,
       |     ^^^^^^^^^^^^ use of undeclared type or module `Float64Array`

  error[E0412]: cannot find type `Int32Array` in this scope
     --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:700:37
      |
  700 |         pub fn notify(typed_array: &Int32Array, index: u32) -> Result<u32, JsValue>;
      |                                     ^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Int32Array` in this scope
     --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:705:27
      |
  705 |             typed_array: &Int32Array,
      |                           ^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Int32Array` in this scope
     --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:744:35
      |
  744 |         pub fn wait(typed_array: &Int32Array, index: u32, value: i32) -> Result<JsString, JsValue>;
      |                                   ^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Int32Array` in this scope
     --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:751:27
      |
  751 |             typed_array: &Int32Array,
      |                           ^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Int8Array` in this scope
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5000:5
       |
  5000 |     Int8Array: i8,
       |     ^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Int16Array` in this scope
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5004:5
       |
  5004 |     Int16Array: i16,
       |     ^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Int32Array` in this scope
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5008:5
       |
  5008 |     Int32Array: i32,
       |     ^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Uint8Array` in this scope
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5012:5
       |
  5012 |     Uint8Array: u8,
       |     ^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Uint8ClampedArray` in this scope
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5016:5
       |
  5016 |     Uint8ClampedArray: u8,
       |     ^^^^^^^^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Uint16Array` in this scope
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5020:5
       |
  5020 |     Uint16Array: u16,
       |     ^^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Uint32Array` in this scope
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5024:5
       |
  5024 |     Uint32Array: u32,
       |     ^^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Float32Array` in this scope
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5028:5
       |
  5028 |     Float32Array: f32,
       |     ^^^^^^^^^^^^ not found in this scope

  error[E0412]: cannot find type `Float64Array` in this scope
      --> /Users/Viki/.cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.37/src/lib.rs:5032:5
       |
  5032 |     Float64Array: f64,
       |     ^^^^^^^^^^^^ not found in this scope

     Compiling sp-api-proc-macro v2.0.0-alpha.5
  error: aborting due to 37 previous errors

  Some errors have detailed explanations: E0412, E0433.
  For more information about an error, try `rustc --explain E0412`.
  error: could not compile `js-sys`.

  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed

**Comment by bkchr** [comment]
Try: `rm -rf ~/.cargo/registry`
