### ISSUE TITLE
Dependency on deprecated failure crate

### ISSUE THREAD

**Issue by DemiMarie** [paritytech/substrate#6980]
The `failure` crate is [deprecated](https://github.com/paritytech/ledgeracio/issues/27#issue-687628964).  However, `pallet-session` depends on `pallet-timestamp`, which depends on `frame-benchmarking`.  This in turn depends on `linregress` which depends on `failure`.

Having a dependency on `linregress` in a release build is rather silly, so we should remove it.

**Comment by bkchr** [comment]
No issue.
