### ISSUE TITLE
Do you have any issue to work on?

### ISSUE THREAD

**Issue by herou** [paritytech/substrate#6983]
Hello,

I have some months that I am learning substrate and I am looking for small tickets to work on? Do you have any suggestions?
In case I am working on an issue and I have a question, which is the most appropriate person to ask for?

**Comment by burdges** [comment]
Check out the [Z1-mentor](https://github.com/paritytech/substrate/labels/Z1-mentor) label or maybe low [Q*](https://github.com/paritytech/substrate/labels?page=2&sort=name-asc) labels
