### ISSUE TITLE
How do nominators ranking after MaxNominatorRewardedPerValidator receive their rewards？

### ISSUE THREAD

**Issue by cryptomancc** [paritytech/substrate#7002]
In the Lazy Payout(#4474 ) implemention, the reward is limited to the T::MaxNominatorRewardedPerValidator biggest nominators, where will the leftover rewards go? And how do nominators ranking after MaxNominatorRewardedPerValidator receive their rewards？

**Comment by cryptomancc** [comment]
And there is a similar question, while appling Staking::clear_era_information, if the rewards are not cliamed, where will they go？

**Comment by thiolliere** [comment]
> In the Lazy Payout(#4474 ) implemention, the reward is limited to the T::MaxNominatorRewardedPerValidator biggest nominators, where will the leftover rewards go? And how do nominators ranking after MaxNominatorRewardedPerValidator receive their rewards？

the staking doc says:

> Rewards must be claimed for each era before it gets too old by `$HISTORY_DEPTH` using the
`payout_stakers` call. Any account can call `payout_stakers`, which pays the reward to the
validator as well as its nominators. Only the [`Trait::MaxNominatorRewardedPerValidator`]
biggest stakers can claim their reward. This is to limit the i/o cost to mutate storage for each
nominator's account.

so nominators ranking after MaxNominatorRewardedPerValidator have no reward

**Comment by thiolliere** [comment]
> And there is a similar question, while appling Staking::clear_era_information, if the rewards are not cliamed, where will they go? As far as I know from the source code(v2.0.0-rc6), the unclaimed rewards will disappear， is that a feature?

I confirm unclaimed reward disappear. the current process of having stakers claiming their rewards is because claiming all of them in one block cost too much.
Still maybe we can think of some automation like: claim reward of one staker per block automatically. But I think the preferred direction is to have it claimed not by the chain, maybe some notification tool like mail service or push service could be made here for stakers.

**Comment by bkchr** [comment]
CC @shawntabrizi @kianenigma

**Comment by kianenigma** [comment]
FYI we are working on the process of increasing the limit  
https://github.com/paritytech/polkadot/pull/1668
https://github.com/paritytech/substrate/pull/7007

The rest are answered correctly as far as see by @thiolliere.

**Comment by thiolliere** [comment]
I think the issue is answered, if you want to request having unclaimed era into treasury or something configurable, feel free to open another issue
