### ISSUE TITLE
Decreasing Vote on Democracy Does Not Decrease Lock

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#7006]
Right now the logic in democracy votes is:

```
		// Extend the lock to `balance` (rather than setting it) since we don't know what other
		// votes are in place.
		T::Currency::extend_lock(
			DEMOCRACY_ID,
			who,
			vote.balance(),
			WithdrawReason::Transfer.into()
		);
```

This means if you initially vote 1000 tokens, and then reduce your vote to 500 tokens, you are still locked for the full 1000 tokens.

One possible problem here is related to the fact that external pallets cannot inspect locks. Some solutions were presented before, but found unsatisfactory. Need to investigate how to best relay lock information to other pallets.

Additionally, this pallet may choose to create unique lock identifiers for each vote, making it easier to track, remove, and replace such locks.

Alternatively, this pallet can track lock information more carefully and know exactly what kind of locks it should be placing on various users.

In general, we should make voting and participating in governance a more positive experience for users, and this is not that.

**Comment by shawntabrizi** [comment]
Or maybe we just need to call `fn update_lock` at the end

**Comment by crystalin** [comment]
@shawntabrizi I see this has never been solved. Should we consider the current state to be the intended behavior ? (cc @bkchr )


The current behavior is problematic as it makes the state impossible to validate without having the history of the block. Ex: 
It is not possible to do: 
```
expect "democrac" lock to equal the maximum votingOf balance
```
