### ISSUE TITLE
Persistant Node Peer ID: Error: Service(Network(Key decoding error: Ed25519 secret key))

### ISSUE THREAD

**Issue by mswezey23** [paritytech/substrate#7025]
When starting a node; passing in `--key-node-file <PATH/TO/FILE>`, the node fails to start. 

This is the error message:
`Error: Service(Network(Key decoding error: Ed25519 secret key))`

I would expect the output of generating a node key file to be ready to consume for the node. 
Documentation, that I've found so far, is vague on how to handle this.

**Comment by mswezey23** [comment]
Workaround:
`--node-key="$(< '$PEER_KEY')"`

Where `$PEER_KEY` == path to to file

**Comment by wilwade** [comment]
We had this issue and it turned out that it was that we had a line break at the end of the file.

- Wrong: `echo "key" > node_key_file`
- Correct: `echo -n "key" > node_key_file`

(Or just make sure you don't use an editor that is adding in the new line on save like I was...)
