### ISSUE TITLE
Weight trait and WeightInfo implementation should be compatible. 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#7028]
Currently, they are not if we have unused parameters. The trait definition will have the unused parameters while the impl will not. 

I don't have a preference, but they should be consistent. 

> I see that currently it is problematic because in the function generating the trait you don't do the analysis, so you donno if a component is used or not. I would just remove the --weight-trait flag and always write the trait and impl together.
> then we can actually have tests that ensure what they produce compiles.

Currently as @shawntabrizi said the trait definition is just a helper and it should be manually tweaked. I think it can and should be fully automatic.

**Comment by shawntabrizi** [comment]
I have a feeling that us automatically hiding unused parameters is not a good thing. I may have added this feature without really thinking about the fact that it may constantly change the trait, when in fact the trait function should be constant in terms of the variables it needs as defined by the benchmarks.... even if a variable ends up having negligible effect...

**Comment by shawntabrizi** [comment]
This was fixed in the PR that transitioned to use templates. https://github.com/paritytech/substrate/pull/7390
