### ISSUE TITLE
subkey vanity - pattern is always created for network id 42

### ISSUE THREAD

**Issue by SvenMeyer** [paritytech/substrate#7031]
subkey-vanity 2.0.0-rc6

I tried to create vanity addresses for various networks (polksdot, kusama, edgeware), but whatever network I try , the pattern only shows up in networks with id 42.

`$ subkey vanity --pattern KUSA --network kusama`

```
Generating key containing pattern 'KUSA'
100000 keys searched; best is 188/237 complete
200000 keys searched; best is 188/237 complete
300000 keys searched; best is 189/237 complete
400000 keys searched; best is 219/237 complete
500000 keys searched; best is 219/237 complete
600000 keys searched; best is 233/237 complete
700000 keys searched; best is 233/237 complete
800000 keys searched; best is 233/237 complete
900000 keys searched; best is 233/237 complete
1000000 keys searched; best is 233/237 complete
best: 237 == top: 237
Secret Key URI `0x5d7f6eb29ed3b011d2b9aeb9f3d6f99c10a601c36cf34422c4490dbb02ecc6fa` is account:
  Secret seed:      0x5d7f6eb29ed3b011d2b9aeb9f3d6f99c10a601c36cf34422c4490dbb02ecc6fa
  Public key (hex): 0xbc346e2825163c504a493db5c79f84a3468b25d8dd67c6b999674695456f9769
  Account ID:       0xbc346e2825163c504a493db5c79f84a3468b25d8dd67c6b999674695456f9769
  SS58 Address:     Gq66UNxi6oKHBLKqP8yGUcbBWqGvRz8FyDhwYFvwq3wwXh5
```
![subkey-vanity](https://user-images.githubusercontent.com/25609/92323769-caf7bb80-f07e-11ea-8a40-29fbbfdf485a.png)

**Comment by twzhq** [comment]
can confirm:

`subkey vanity --network polkadot --pattern **aaa** 
Generating key containing pattern 'aaa'
best: 189 == top: 189
Secret Key URI 0xc1e2d92d8c9f3fa31a89bdd2d9678de1ff5a2a39f94d4e1cd16807ef77ac0a78 is account:
  Secret seed:      0xc1e2d92d8c9f3fa31a89bdd2d9678de1ff5a2a39f94d4e1cd16807ef77ac0a78
  Public key (hex): 0x16c8dc4e6ab67c9966f6a6897cee8e1479ef2bafe71cd3689a0b0c6ce20ddb5d
  Account ID:       0x16c8dc4e6ab67c9966f6a6897cee8e1479ef2bafe71cd3689a0b0c6ce20ddb5d
  SS58 Address:     1WsirBYRNFUeH6DRocLvZypf1oxiMxHYdrkffvEAGzk1Tqt

subkey inspect-key 0xc1e2d92d8c9f3fa31a89bdd2d9678de1ff5a2a39f94d4e1cd16807ef77ac0a78
Secret Key URI 0xc1e2d92d8c9f3fa31a89bdd2d9678de1ff5a2a39f94d4e1cd16807ef77ac0a78 is account:
  Secret seed:      0xc1e2d92d8c9f3fa31a89bdd2d9678de1ff5a2a39f94d4e1cd16807ef77ac0a78
  Public key (hex): 0x16c8dc4e6ab67c9966f6a6897cee8e1479ef2bafe71cd3689a0b0c6ce20ddb5d
  Account ID:       0x16c8dc4e6ab67c9966f6a6897cee8e1479ef2bafe71cd3689a0b0c6ce20ddb5d
  SS58 Address:     5C**aaa**WvUZaz1Ck5hUAZLnR9foPpK24Q9U98GWNvscByDq71B`

**Comment by bkchr** [comment]
This is fixed on master.

Thank you anyway for the issue.
