### ISSUE TITLE
sp-runtime have leaked std feature

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7055]
For some reason our CI starts failing. There are no code changes in our side. Master was green, but the same code fails now.

https://github.com/open-web3-stack/open-runtime-module-library/pull/279/checks?check_run_id=1089370489

No idea way, but during the investigation, it seems like sp-runtime in rc6 release and master cannot be build with wasm

This will fail

```
cd primitives/runtime
cargo check --no-default-features --target=wasm32-unknown-unknown
```

```
    Checking crunchy v0.2.2
    Checking proc-macro-nested v0.1.6
    Checking sp-arithmetic v2.0.0-rc6 (/Users/xiliangchen/projects/substrate/primitives/arithmetic)
    Checking futures-util v0.3.5
    Checking uint v0.8.3
    Checking tiny-keccak v2.0.2
    Checking hash256-std-hasher v0.15.2
error: cannot find macro `vec` in this scope
  --> primitives/arithmetic/src/biguint.rs:88:18
   |
88 |         Self { digits: vec![0; size.max(1)] }
   |                        ^^^
```

**Comment by xlc** [comment]
The new release of `integer-sqrt` breaks it. https://github.com/derekdreery/integer-sqrt-rs/issues/12

**Comment by bkchr** [comment]
> No idea way, but during the investigation, it seems like sp-runtime in rc6 release and master cannot be build with wasm
> This will fail

This is currently "expected" as we include `state-machine` as dev dependency and that will leak features when only checking the individual crate.

However, you already found the upstream issue and it needs to be fixed there. So, I close this.
