### ISSUE TITLE
Allow council to slash treasury tip

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7057]
pallet-treasury should provide a slash_tip call, require RejectOrigin, remove and slash a tip request.

Combined with increase tip deposit, should help reduce number of low quality tips.

**Comment by shamb0** [comment]
Hello @shawntabrizi,

If its open can I pick-up this ?

**Comment by shawntabrizi** [comment]
@shamb0 its probably not a great idea to work on this until your other PR is merged.

If you really want to jump on top of it, you can make another branch working off your changes which refactors treasury, but probably easier just to wait.

**Comment by shamb0** [comment]
Fine Shawn, then better I wait for merge.

**Comment by chevdor** [comment]
I was looking for the PR mentioned by @shawntabrizi, that must be #7536

**Comment by shawntabrizi** [comment]
@shamb0 @xlc this can now be worked on.

**Comment by xlc** [comment]
@shamb0 do you still want to work on this? otherwise I will give it a go next week.

**Comment by shamb0** [comment]
Thanks @shawntabrizi , Hi @xlc I pick-up this ...

**Comment by shamb0** [comment]
Hello @shawntabrizi / @xlc, 

Plz find the PR, tried to implement the API "slash_tip()" based on the requirement

**pallet-treasury should provide a slash_tip call, require RejectOrigin, remove and slash a tip request.**

* [Allow council to slash treasury tip by shamb0 · Pull Request #7753 · paritytech/substrate](https://github.com/paritytech/substrate/pull/7753)

And regarding requirement,

**Combined with increase tip deposit, should help reduce number of low quality tips.**

For me it occurs, this requirement is already handled by below pallet config.

```
	/// The amount held on deposit for placing a tip report.
	type TipReportDepositBase: Get<BalanceOf<Self>>;
```

by increasing TipReportDepositBase, tip deposit can be increased, to reduce number of low quality tips.

Plz correct me if I am wrong.

**Comment by xlc** [comment]
Yep you do not need to do anything about increase tip deposit part. It is something should happen in the Polkadot / Kusama runtime.

**Comment by shamb0** [comment]
> Yep you do not need to do anything about increase tip deposit part. It is something should happen in the Polkadot / Kusama runtime.

Thanks @xlc, Yes I am not touching tip deposit part :-)
