### ISSUE TITLE
Sweep runtime for overflows

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#706]
Particularly from multiplication of balances. Will likely need a half-word multiplier coding for it.

Many have been noted: 

```
// TODO: avoid overflow
```

**Comment by thiolliere** [comment]
include this https://github.com/paritytech/substrate/issues/1572

**Comment by DemiMarie-parity** [comment]
There are no more TODOs regarding overflow, but auditing the runtime is still worthwhile.
