### ISSUE TITLE
Verson bump needed? 0.8.0-rc6 -> 2.0.0-rc6

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate#7066]
I noticed the use of `version = 0.8.0-rc6` in the [node template](https://github.com/substrate-developer-hub/substrate-node-template) in many places in `./node/Cargo.toml` 

I wondered if the release `2.0.0-rc6` simply needs to be bumped in the associated crates in this workspace - mainly in the `./client` directory in this repo. 

If this is the case, hope it is an easy fix to propagate 😁

**Comment by bkchr** [comment]
The crates with version `0.8.0` have this version by intention. This should communicate that these crates are not "stable".
