### ISSUE TITLE
List of available log targets

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7067]
It will be helpful to have a list of available log targets so to help people identify useful log targets.

Maybe this is already documented somewhere that I have missed?

**Comment by bkchr** [comment]
Why do you need this?

Essentially every crate that doesn't use any custom prefix, it will be the crate that is the target.

**Comment by xlc** [comment]
I want do debug RPC & evm related issue but unsure what log flag I should use. 

Just -ltrace way too verbose but it does give me an idea of what log targets are available. It will be helpful if those are summarized into a document.

**Comment by bkchr** [comment]
This is more a docs issue and no code issue. So please open this in the knowledgebase, while I'm not convinced.

If you want to know the proper targets, you can look up them up in the corresponding code.
