### ISSUE TITLE
Nodes report 0 peers/0 bandwidth on telemetry

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#7097]
Opening this issue to keep track of [this discussion](https://github.com/paritytech/substrate/pull/7077#issuecomment-691170004).
The problem has likely been introduced [here](https://github.com/paritytech/substrate/pull/6986/files#r487127101) and might be resolved by [this PR](https://github.com/paritytech/substrate-telemetry/pull/289).

cc @romanb

**Comment by romanb** [comment]
> [..] and might be resolved by this PR.

I've tested this locally, of course, and am quite confident that it indeed resolves the problem.

**Comment by romanb** [comment]
I think this is resolved, feel free to reopen otherwise.
