### ISSUE TITLE
Benchmark Automation Should Produce `MaxBlockWeight` Weight Output

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#7100]
Right now, extrinsics that are `MaxBlockWeight` are marked like this from within the pallet. Imagine some blockchain whose block time is 100 seconds or something... Our extrinsics may not be considered `MaxBlockWeight` for such a chain. As with all other extrinsics, this should be configured from the weight trait.

**Comment by bkchr** [comment]
The title sounds weird :P 

Maybe we should just cap all extrinsics to `MaxBlockWeight`? So if there is an extrinsic that takes more weight, it would take max block weight in polkadot but in the other chain with 100 seconds block time only the weight of 3 seconds?

**Comment by shawntabrizi** [comment]
@bkchr I think there is a problem that the weight limit cap is "fuzzy". i.e. there are times we want to use `T::MaxBlockWeight` on an operation that is more than 3 secods, but less than 6 seconds... or for operations where it would be too hard in our system to calculate what the final weight should be.

In general, the point of this issue is just to expose full control over all weights to the user through the `WeightInfo` config. Right now we don't do this for `MaxBlockWeight` things.

**Comment by shawntabrizi** [comment]
i think we have appropriate automation for max block weight now, and this issue reads weird in hindsight
