### ISSUE TITLE
How to change spec_name

### ISSUE THREAD

**Issue by Tore19** [paritytech/substrate#7140]
We want to change the spec_name, but it will report this error:

`can_author_with` returned: `spec_name` does not match `node` vs `stafi` Probably a node update is required!

And the node will not produce blocks any more.

I just checked the code:
![image](https://user-images.githubusercontent.com/10955745/93553632-12971500-f9a6-11ea-9e70-fc75828305a8.png)

The spec_name cannot be modified.

If we have 100 validators, we need all validators to upgrade at the same time, and the runtime upgrade(system.set_code_without_checks) takes effect at the same time, or the network will stuck.  But obviously this is almost impossible.

So is there any way to change spec_name?

**Comment by bkchr** [comment]
That is actually a good case :P 

You could release a new node and use [`AlwaysCanAuthor`](https://github.com/paritytech/substrate/blob/master/primitives/consensus/common/src/lib.rs#L244)

**Comment by Tore19** [comment]
Yeah, got it. Thanks!
