### ISSUE TITLE
Refactor Treasury Pallet into Smaller Components

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#7143]
The treasury pallet has gained a number of features beyond its initial "proposals" queue.

We should split up treasury into individual components which isolate the different functionalities it provides:

* Main treasury pallet w/ pot
* Tips
* Reoccurring Payments
* Bounties

**Comment by shawntabrizi** [comment]
Anyone who is familiar with creating a new runtime pallet, adding it to the runtime, and writing a bit of runtime code should be able to do this task!

**Comment by laurogripa** [comment]
Hey, @shawntabrizi. Just out of curiosity, what do you think the folder structure should look like?

Do we keep the components inside the `treasury` module and still use the same tests file? Something like this:

```
treasury
└───src
│   │   main.rs
│   │   tips.rs
│   │   reoccurring_payments.rs
│   │   bounties.rs
│   │   tests.rs
│   Cargo.toml
│   README.md
```

**Comment by shawntabrizi** [comment]
@laurogripa actually each of these would be their own pallet so something like:

```
frame
└─── treasury
└─── tips
└─── bounties
```

There aren't reoccurring payments yet so nothing new to add for that.

Each of the pallets should "depend" on the treasury account, and use it just like treasury does.

You will see that treasury does some logic to see "how much it can spend", basically looking at its current balance and spending as much as possible.

In this case, the other pallets would simply manage funds from the same account, and also try to spend funds from it as best as it can.

**Comment by shamb0** [comment]
Hi @shawntabrizi  & @laurogripa,  I am new to substrate runtime, exploring "Q2-easy and Z1-mentor"  level issues. I am interested to jump-in, can I join together for this issue ?

**Comment by shawntabrizi** [comment]
@shamb0 this is probably an issue that you need some relative familiarity with runtime development, otherwise, you can go ahead and try. Should basically be creating 3 pallets from 1.

**Comment by shamb0** [comment]
Thanks @shawntabrizi , from your description got high level requirement for this issue. Let me give my try ...
