### ISSUE TITLE
Cargo readme generates wrong links in Markdown

### ISSUE THREAD

**Issue by TriplEight** [paritytech/substrate#7146]
Doing https://github.com/paritytech/substrate/pull/7145 I've crossed @gnunicorn 's `cargo-unleash`, that uses `cargo-readme` which has a [bug](https://github.com/livioribeiro/cargo-readme/issues/18) with creating links. It also has a suggested [workaround](https://github.com/livioribeiro/cargo-readme/issues/18#issuecomment-524613569).

> Because of the docs might be outdated when the crate has changed, the idea was to have `cargo-unleash` run automatically for crates that changed when releasing. 

This will definitely conflict with a link checker CI job unless there will be a fix.

**Comment by stiiifff** [comment]
Should be fixed by https://github.com/paritytech/cargo-unleash/pull/17

**Comment by gnunicorn** [comment]
@stiiifff did you run it against substrate and could send a PR with the updated Readmes, too? Then we can consider this issues fixed, I guess.

**Comment by stiiifff** [comment]
@gnunicorn will do it now.
