### ISSUE TITLE
Inconsistency between balances that can be used for governance

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7153]
`electionsPhragmen.vote` uses total balance, free + reserved

https://github.com/paritytech/substrate/blob/16474ee9ed8f75ad578f4539ae4fc016ecf8b3d1/frame/elections-phragmen/src/lib.rs#L389

`democracy.vote` uses free balance only
https://github.com/paritytech/substrate/blob/16474ee9ed8f75ad578f4539ae4fc016ecf8b3d1/frame/democracy/src/lib.rs#L1255

This is not a real issue, just feel inconsistent and will love to learn if there are any reasons behind the choice.

**Comment by xlc** [comment]
I end up having more miscFrozen than my free balances. So this account can no longer sending transactions unless I top it up with value more than reserved amount. I think `electionsPhragmen.vote` should use `free_balance` over `total_balance`

**Comment by bkchr** [comment]
CC @shawntabrizi @kianenigma

**Comment by kianenigma** [comment]
Yeah this is not pretty but I don't think it is a real issue (though I might be wrong here). It could also need a simple migration, let's fix it after we have a new migration testing pipeline.

**Comment by kianenigma** [comment]
This has already been fixed. 

https://github.com/paritytech/substrate/blob/34a0621761c4a333cb2074ff720f7acbfb92dbb8/frame/elections-phragmen/src/lib.rs#L359-L360
