### ISSUE TITLE
Destroy all RocksDB objects before static destructors run

### ISSUE THREAD

**Issue by DemiMarie** [paritytech/substrate#7166]
Otherwise we will run into undefined behavior in RocksDB: https://github.com/facebook/rocksdb/issues/649

**Comment by bkchr** [comment]
Why is that a Substrate issue?

**Comment by DemiMarie** [comment]
It shows up as a crash on shutdown in certain scenarios, and I don’t think Facebook is interested in fixing the behavior of RocksDB.

**Comment by bkchr** [comment]
If you don't provide scenarios in which this happens, we can not fix this.

**Comment by DemiMarie** [comment]
It happens when running unit tests for current substrate-subxt git HEAD, although not reliably.
