### ISSUE TITLE
Refactor weight generation code to use a templating language 

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7169]
Refactor the weight file generation code to use a templating language and allow people to pass a custom template.

This will allow people to customize header, footer, spacing, format etc.

https://github.com/paritytech/substrate/blob/master/utils/frame/benchmarking-cli/src/writer.rs

[handlebars](https://docs.rs/handlebars/3.4.0/handlebars/) will be a good templating language to use.

**Comment by shawntabrizi** [comment]
completed with https://github.com/paritytech/substrate/pull/7390

Thanks again @zadmarbella
