### ISSUE TITLE
Phragmen should ignore "empty" voters

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#7172]
We build the voters as such: 

https://github.com/paritytech/substrate/blob/0c8329c71c241cce09feb0372ee5d5d4a161d11a/primitives/npos-elections/src/lib.rs#L385-L405

If by the end of the `map()`, `edges.len()` is empty, then this voter should not be even included. Essentially, we have to change the `map()` to `filter_map`. 

Ideally there should be a test added for this, else we need to make sure the change is reflected in #6685 as well. 

This (as far as I know) does not cause any issues. It is just extra iterations here and there that will make the execution a bit slower.

**Comment by ksr30** [comment]
Hey @kianenigma , is this issue still open? ... I see #6685 is alreday merged.

**Comment by kianenigma** [comment]
ahh yes, thanks.

**Comment by kianenigma** [comment]
Well.. actually it seems like the answer is actually no.

**Comment by ksr30** [comment]
Okay Thanks @kianenigma
