### ISSUE TITLE
client/network: Stop sending noise legacy handshake

### ISSUE THREAD

**Issue by mxinden** [paritytech/substrate#7175]
Polkadot `v0.8.19` incorporated libp2p `v0.22` and thus supports receiving non length-prefixed protobuf frames in handshake payloads. Judging by [telemetry](https://telemetry.polkadot.io/#/Polkadot) the majority of nodes is running Polkadot `>= v0.8.22`.

With the above in mind, any objections against removing `send_legacy_handshake` and thus not sending length-prefixed protobuf payloads inside a length-prefixed noise frame?

//CC @tomaka @romanb @twittner

**Comment by romanb** [comment]
No objection from my side, if there is enough confidence that nodes operating "in the wild" had sufficient time to upgrade.

**Comment by tomaka** [comment]
Right now there are indeed only 5 nodes that are `<= 0.8.18` and manage to stay in sync, and I think two of them (`polkadot-sync-ew4-0`) even belong to Parity.
