### ISSUE TITLE
can't generate polkadot vanity address by subkey

### ISSUE THREAD

**Issue by zhouziyan** [paritytech/substrate#7177]
The generated address doesn't include the pattern.

root@iZj6ccgq3cou33osflcqsdZ:~/substrate# subkey vanity  --network polkadot --pattern "dot"
Generating key containing pattern 'dot'
100000 keys searched; best is 187/189 complete
200000 keys searched; best is 188/189 complete
300000 keys searched; best is 188/189 complete
best: 189 == top: 189
Secret Key URI `0x59332010243c43edbb04ce653c9f10707e2b20307145ecf17791fbf934141066` is account:
  Secret seed:      0x59332010243c43edbb04ce653c9f10707e2b20307145ecf17791fbf934141066
  Public key (hex): 0xca3056dfee01e3397e084deb771af7bbf89a48cea493256ca39a07f3861abc50
  Account ID:       0xca3056dfee01e3397e084deb771af7bbf89a48cea493256ca39a07f3861abc50
  SS58 Address:     15a72tKkj1v9qMbKxZp95WDzusXc2dx9oryAfaHp1TPHZunJ

root@iZj6ccgq3cou33osflcqsdZ:~/substrate# subkey --version
subkey 2.0.0-rc6

**Comment by kianenigma** [comment]
Should do like: 

```
subkey --network polkadot vanity dot                                                                                                                                                                             
Generating key containing pattern 'dot'
100000 keys searched; best is 188/189 complete
200000 keys searched; best is 188/189 complete
best: 189 == top: 189
Secret Key URI `0x804a06f1ecc396799a3d41c6379be7735dc89cf300d37e6edade8b9420b0eab0` is account:
  Public key (hex): 0x748b2ac7b860565af441e70d7304ea3c1a0c62e54b4ca1a1b29b9df18256196d
  Address (SS58): 13dotxnQmgCZvHorVp9b3paYoMnnF3q97ePNyoVhovWR8XSF
```

**Comment by zhouziyan** [comment]
@kianenigma Which version do you use?

I got following error:

root@iZj6ccgq3cou33osflcqsdZ:~# subkey --network polkadot vanity dot
error: Found argument '--network' which wasn't expected, or isn't valid in this context
	Did you mean to put '--network' after the subcommand 'vanity'?

USAGE:
    subkey <SUBCOMMAND>

For more information try --help

**Comment by kianenigma** [comment]
Indeed mine was old. It was with 2.0. With rc-6, I have the same issue.

**Comment by kianenigma** [comment]
(and I get the exact same output as you do o__0)

**Comment by kianenigma** [comment]
@seunlanlege I think your PR #4954 was the last one to change subkey?

**Comment by bkchr** [comment]
This should be already fixed in master.

@kianenigma please always test on master and not on any release.

**Comment by bkchr** [comment]
Works for me on master:
```
cargo run -p subkey -- vanity --network polkadot --pattern a 
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/subkey vanity --network polkadot --pattern a`
Generating key containing pattern 'a'
best: 93 == top: 93
Secret Key URI `0x8e42ad120a25d68dcbb3678488c297c6d6d02b70222fb2077b66a4e90a8e2c67` is account:
  Secret seed:      0x8e42ad120a25d68dcbb3678488c297c6d6d02b70222fb2077b66a4e90a8e2c67
  Public key (hex): 0x1686d9c1eeecbe4235e43edc905314bc9f05b37db7680a62bdbd1f6c75f17440
  Account ID:       0x1686d9c1eeecbe4235e43edc905314bc9f05b37db7680a62bdbd1f6c75f17440
  SS58 Address:     1WY7XL2CHNqE2X4dNRn26E4f1tow4sNFdbdFwuhL5RowLQW
```

**Comment by laboon** [comment]
@bkchr Shouldn't the SS58 address include the pattern `a` in this case?

**Comment by kianenigma** [comment]
Yes this is still wrong.

**Comment by ChinmayPatel** [comment]
Just tried the changes. It works. 

Shouldn't it say `Polkadot Address` instead of `SS58 Address`? 

```
$ ./target/release/subkey vanity --pattern "dot" --network polkadot
Generating key containing pattern 'dot'
best: 189 == top: 189
Secret Key URI `0x2cb9a43e3349dd3f88bbbe0fa1ac25a787bca2f93c0804e9df054a8056d2ea88` is account:
  Secret seed:      0x2cb9a43e3349dd3f88bbbe0fa1ac25a787bca2f93c0804e9df054a8056d2ea88
  Public key (hex): 0x748b28e34330db7def1929bbe99cc40c67e2479574eecc24744020e26067d25d
  Account ID:       0x748b28e34330db7def1929bbe99cc40c67e2479574eecc24744020e26067d25d
  SS58 Address:     13dotqPxGgVJ6pVi6EJYCLAZzZhietauW6mxrzHdG4mtbpBk 
```

**Comment by bkchr** [comment]
No.

If you use `inspect 13dotqPxGgVJ6pVi6EJYCLAZzZhietauW6mxrzHdG4mtbpBk` it will show you that this is a polkadot address
