### ISSUE TITLE
Could not compile `node-testing`

### ISSUE THREAD

**Issue by Tore19** [paritytech/substrate#7178]
MacOs

rustc --version
rustc 1.47.0-nightly (30f0a0768 2020-08-18)

rustc +nightly --version
rustc 1.48.0-nightly (fb1dc34a8 2020-09-21)

cargo --version
cargo 1.47.0-nightly (ab32ee88d 2020-08-10)

cargo +nightly --version
cargo 1.48.0-nightly (8777a6b1e 2020-09-15)

Substrate commit:
647ad15565d7c35ecf00b73b12cccad9858780b9

![image](https://user-images.githubusercontent.com/10955745/93871341-122daf80-fd01-11ea-994f-887e3e28d350.png)

What may be the problem? Does this have anything to do with the rust version?

**Comment by bkchr** [comment]
For me `cargo 1.48.0-nightly (8777a6b1e 2020-09-15)` works.

Also not sure why you have 2 different nightlies installed.

**Comment by Tore19** [comment]
@bkchr Hi, I installed the environment again.

```
curl https://sh.rustup.rs -sSf | sh
rustup default stable
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
```

Now the rust version is:

```
rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)

rustc +nightly --version
rustc 1.48.0-nightly (0da580074 2020-09-22)

cargo --version
cargo 1.46.0 (149022b1d 2020-07-17)

cargo +nightly --version
cargo 1.48.0-nightly (8777a6b1e 2020-09-15)
```

But it doesn't work either.

I remembered that I deleted Cargo.lock and build it. Maybe this is the problem.

So I recovered Cargo.lock and rebuild it again. It works.

I think it may be a version issue of some dependencies.

**Comment by bkchr** [comment]
So this can be closed now?

**Comment by Tore19** [comment]
Sure.
