### ISSUE TITLE
Refactor Module -> Pallet

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#7194]
The term _module_, used a lot in FRAME is historically linked to SR**M**L. 

Not a big deal, and probably lots of people are used to the current naming, but it is technically wrong. Now the term module is replaced with pallet. Hence, 

1. `decl_module!` -> `decl_pallet!`.
2. `struct Module` -> `struct Pallet`.

I think both can be addressed by https://github.com/paritytech/substrate/issues/5678 cc @thiolliere

**Comment by bkchr** [comment]
I don't think that we should touch any of the old code.

You can bring in your ideas in the proc-macro conversion pr, but we should not break the old code. Let it stay and we will deprecate it anyway with the merge of the new proc-macro macros.

**Comment by kianenigma** [comment]
Yes I think the PR that closes https://github.com/paritytech/substrate/issues/5678 should also close this.

**Comment by bkchr** [comment]
Sounds like we can close this issue directly? There is no real reason to have 100  issues open for one pr. If you want something specific, I propose that you comment on the original issue or directly in the pr.
