### ISSUE TITLE
multisig return to balance too low issue

### ISSUE THREAD

**Issue by ww8912188** [paritytech/substrate#7202]
Hi guys,

I tried a tranfer from a multisig address to an ordinary addres using polkadot explorer, it always return to an error: 
"Balance too low to send value".

But the origin account has 8+ dot. 

Here is the tx:
https://polkadot.subscan.io/extrinsic/0xac1dc144329820529d85638d7a23cf097f718695b7f7f78edb5bf3ea89e3d082
https://polkadot.subscan.io/extrinsic/0x370c047ceb8a236a89e18b03198d94fb935332dd4dce26c6242c0ad1cdc1945c

Can someone shing some light on this issue. Thanks in advance.

Regards,
Nan

**Comment by Swader** [comment]
There are caveats to multi-sig balances, explained [here](https://wiki.polkadot.network/docs/en/learn-accounts#making-transactions-with-a-multi-signature-account)

**Comment by ww8912188** [comment]
@Swader thanks for the quick reply, really appreciate!

Do we have a valid mulsig tranaction in polkadot explorer just as I mentioned [above](https://polkadot.subscan.io/extrinsic/0xac1dc144329820529d85638d7a23cf097f718695b7f7f78edb5bf3ea89e3d082)? 

I'm still struggling to create a deposit inside of a the multisig tx.

**Comment by ww8912188** [comment]
@Swader I just find the new world [here](https://polkadot.subscan.io/event?module=multisig&event=all). I'll have a try the input parameters of them.

**Comment by bkchr** [comment]
@ww8912188 anything else you want to know or can we close the issue?

**Comment by ww8912188** [comment]
I've got everything settled, close this issue.
