### ISSUE TITLE
Facing issue while implementing RPC that the trait Deserialize and Serialize is not implemented for Structure.

### ISSUE THREAD

**Issue by ksr30** [paritytech/substrate#7220]
Getting error while implementing RPC that :- 
```
error[E0277]: the trait bound `pallet_template::LinkedPriceLevel<K>: sp_runtime::Deserialize<'_>` is not satisfied
  --> pallets/template/rpc/src/lib.rs:16:1
   |
16 | #[rpc]
   | ^^^^^^ the trait `sp_runtime::Deserialize<'_>` is not implemented for `pallet_template::LinkedPriceLevel<K>`
   |
   = note: required because of the requirements on the impl of `for<'de> sp_runtime::Deserialize<'de>` for `std::vec::Vec<pallet_template::LinkedPriceLevel<K>>`
   = note: required because of the requirements on the impl of `sp_runtime::DeserializeOwned` for `std::vec::Vec<pallet_template::LinkedPriceLevel<K>>`
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
For reference :-
**rpc file :-**
```
#[rpc]
pub trait DexStorageApi<BlockHash,K> where K:Trait {
 
    #[rpc(name = "get_price_level")]
    fn get_price_level(&self, at: Option<BlockHash>, trading_pair: H256) -> Result<Vec<LinkedPriceLevel<K>>>;
}

/// A struct that implements the `SumStorageApi`.
pub struct DexStorage<C, M> {
    // If you have more generics, no need to SumStorage<C, M, N, P, ...>
    // just use a tuple like SumStorage<C, (M, N, P, ...)>
    client: Arc<C>,
    _marker: std::marker::PhantomData<M>,
}

impl<C, M> DexStorage<C, M> {
    /// Create new `SumStorage` instance with the given reference to the client.
    pub fn new(client: Arc<C>) -> Self {
        Self {
            client,
            _marker: Default::default(),
        }
    }
}


impl<C, Block, K> DexStorageApi<<Block as BlockT>::Hash, K > for DexStorage<C, Block>
    where
        Block: BlockT,
        C: Send + Sync + 'static,
        C: ProvideRuntimeApi<Block>,
        C: HeaderBackend<Block>,
        K: Trait,
        C::Api: DexStorageRuntimeApi<Block, K>,
{


    fn get_price_level(&self, _at: Option<<Block as BlockT>::Hash>, trading_pair: H256) -> Result<Vec<LinkedPriceLevel<K>>> {
        let api = self.client.runtime_api();
        let at = BlockId::hash(
            // Always take the best block hash for this RPC
            self.client.info().best_hash);

        // let hash_trading_pair = H256::from(trading_pair);
        let runtime_api_result = api.get_price_level(&at, trading_pair);
        runtime_api_result.map_err(|e| RpcError {
            code: ErrorCode::ServerError(9876), // No real reason for this value
            message: "Something wrong".into(),
            data: Some(format!("{:?}", e).into()),
        })
    }

}
```
**Structure LinkedPriceLevel :-**
```
#[derive(Encode, Decode, Clone, PartialEq, Eq)]
pub struct LinkedPriceLevel<T> where T: Trait {
    next: Option<FixedU128>,
    prev: Option<FixedU128>,
    orders: VecDeque<Order<T>>,
}
```
**Function in pallet file:-**

```
 pub fn get_price_level(trading_pair: T::Hash) -> Vec<LinkedPriceLevel<T>> {
        let temp: Vec<LinkedPriceLevel<T>> = <PriceLevels<T>>::iter_prefix_values(&trading_pair).collect();
        temp
    }

```

**Comment by kianenigma** [comment]
Here you can find an example that returns a struct: https://github.com/paritytech/substrate/tree/master/frame/transaction-payment/rpc

**Comment by kianenigma** [comment]
Looking a bit more into your case, you are surely missing deriving `Serialize`, `Deserialize` for `LinkedPriceLevel `. For example, see: 

https://github.com/paritytech/substrate/blob/596f377d49fede088e0c32791fb72f1343003b0d/frame/transaction-payment/rpc/runtime-api/src/lib.rs#L30-L45

**Comment by ksr30** [comment]
Hey @kianenigma , compiler is not able to resolve serde,
```
 error[E0432]: unresolved import `serde`
    --> /home/ksr/Desktop/Rust/client-project/Polkadex/pallets/template/src/lib.rs:19:5
     |
  19 | use serde::{Serialize, Deserialize, Serializer, Deserializer};
     |     ^^^^^ use of undeclared type or module `serde`

  error: aborting due to previous error
```
though, I included right dependency :- 
serde = { version = "1.0.101",optional = true , features = ["derive"] }


[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-generic-asset/std',
    'sp-core/std',
]

**Comment by ksr30** [comment]
and this what, i now changed @kianenigma :- 
```
#[derive(Encode, Decode, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "std", derive(Debug, Serialize, Deserialize))]
pub struct LinkedPriceLevel<T> where T: Trait {
    next: Option<FixedU128>,
    prev: Option<FixedU128>,
    orders: VecDeque<Order<T>>,
}
```

**Comment by kianenigma** [comment]
You need to feature gate the import of serde as well. Like 

```
#[cfg(feature = "std")]
use serde::{Serialize, Deserialize, Serializer, Deserializer};
```

**Comment by WB-Expert5007** [comment]
Hello, Everyone.
I am getting this error.
Please help me.

error[E0277]: the trait bound `C: ProvideRuntimeApi<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, BlakeTwo256>, sp_runtime::generic::UncheckedExtrinsic<MultiAddress<AccountId32, ()>, node_template_runtime::Call, MultiSignature, (frame_system::extensions::check_non_zero_sender::CheckNonZeroSender<node_template_runtime::Runtime>, frame_system::extensions::check_spec_version::CheckSpecVersion<node_template_runtime::Runtime>, frame_system::extensions::check_tx_version::CheckTxVersion<node_template_runtime::Runtime>, frame_system::extensions::check_genesis::CheckGenesis<node_template_runtime::Runtime>, frame_system::extensions::check_mortality::CheckMortality<node_template_runtime::Runtime>, frame_system::extensions::check_nonce::CheckNonce<node_template_runtime::Runtime>, frame_system::extensions::check_weight::CheckWeight<node_template_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<node_template_runtime::Runtime>)>>>` is not satisfied
  --> node/src/rpc.rs:76:1
   |
76 | / pub fn create_full<C, P, SC, B>(
77 | |     deps: FullDeps<C, P, SC, B>,
78 | |     backend: Arc<B>,
79 | | ) -> Result<jsonrpc_core::IoHandler<sc_rpc_api::Metadata>, Box<dyn std::error::Error + Send + Sync>>
...  |
94 | |     C::Api: BlockBuilder<Block>,
95 | |     P: TransactionPool + 'static,
   | |_________________________________^ the trait `ProvideRuntimeApi<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, BlakeTwo256>, sp_runtime::generic::UncheckedExtrinsic<MultiAddress<AccountId32, ()>, node_template_runtime::Call, MultiSignature, (frame_system::extensions::check_non_zero_sender::CheckNonZeroSender<node_template_runtime::Runtime>, frame_system::extensions::check_spec_version::CheckSpecVersion<node_template_runtime::Runtime>, frame_system::extensions::check_tx_version::CheckTxVersion<node_template_runtime::Runtime>, frame_system::extensions::check_genesis::CheckGenesis<node_template_runtime::Runtime>, frame_system::extensions::check_mortality::CheckMortality<node_template_runtime::Runtime>, frame_system::extensions::check_nonce::CheckNonce<node_template_runtime::Runtime>, frame_system::extensions::check_weight::CheckWeight<node_template_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<node_template_runtime::Runtime>)>>>` is not implemented for `C`
   |
help: consider further restricting this bound
   |
88 |         + 'static + sp_api::ProvideRuntimeApi<sp_runtime::generic::Block<sp_runtime::generic::Header<u32, sp_runtime::traits::BlakeTwo256>, sp_runtime::generic::UncheckedExtrinsic<sp_runtime::MultiAddress<sp_runtime::AccountId32, ()>, node_template_runtime::Call, sp_runtime::MultiSignature, (frame_system::extensions::check_non_zero_sender::CheckNonZeroSender<node_template_runtime::Runtime>, frame_system::extensions::check_spec_version::CheckSpecVersion<node_template_runtime::Runtime>, frame_system::extensions::check_tx_version::CheckTxVersion<node_template_runtime::Runtime>, frame_system::extensions::check_genesis::CheckGenesis<node_template_runtime::Runtime>, frame_system::extensions::check_mortality::CheckMortality<node_template_runtime::Runtime>, frame_system::extensions::check_nonce::CheckNonce<node_template_runtime::Runtime>, frame_system::extensions::check_weight::CheckWeight<node_template_runtime::Runtime>, pallet_transaction_payment::ChargeTransactionPayment<node_template_runtime::Runtime>)>>>,
   |                   ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   
 How can I solve this error?
 Please help me.
