### ISSUE TITLE
Provide multiple metadata versions

### ISSUE THREAD

**Issue by DemiMarie** [paritytech/substrate#7244]
Substrate 2.0.0 uses a metadata format (v12) that is incompatible with that used by previous versions.  substrate-subxt was quickly updated to use metadata v12, but this broke compatibility with Polkadot and Kusama, which had not yet upgraded.

To avoid this problem, we should support multiple metadata versions.  This ensures that clients can continue working across node and runtime upgrades, at least for long enough to be themselves updated.

CC @bkchr.

**Comment by thiolliere** [comment]
ah I didn't see this issue, close in favor of duplicate https://github.com/paritytech/substrate/issues/8083
But likely to be never implemented actually.
