### ISSUE TITLE
Logging sub-libp2p doesn't work anymore

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#7251]
Doing `polkadot --log sub-libp2p` doesn't show any of the `sub-libp2p` logs anymore.

Tried with Substrate master (commit f6c305ad238b26cbcfc371584d1a250aa565834a)

cc @andresilva @sorpaas

**Comment by bkchr** [comment]
This is an upstream "bug": https://github.com/tokio-rs/tracing/pull/1012

**Comment by tomaka** [comment]
Considering that it's the second time that it breaks, I wonder if we should not admit defeat and rename the logging target to `sub_libp2p`.

**Comment by bkchr** [comment]
I think it is not the only logging target with a dash.

After upstream has released a new version, we should introduce a test to make sure we catch this stuff. 

And I also hope that we don't again switch the logging implementation again in the near future.
