### ISSUE TITLE
Change the name of the GrandPa notifications protocol

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#7252]
At the moment, the GrandPa protocol is called `/paritytech/grandpa/1`. It's not great for two reasons:

1) It shouldn't contain the word `paritytech`.
2) Since the messages exchanged are specific to a certain chain, its name should contain the protocol ID.

Reason 2) will be important in the future, when nodes can be connected to multiple chains at the same time.

**Comment by tomaka** [comment]
The fix will include a transition period where the protocol will have two names. As such, this depends on #6605.

**Comment by tomaka** [comment]
Issue still relevant and important.

**Comment by acatangiu** [comment]
> 1. It shouldn't contain the word paritytech.

Using a new static `/substrate/grandpa/1` protocol name is easy AFAICT:
just use new protocol name, and add old protocol name (`/paritytech/grandpa/1`) to `fallback_names` in `sc_finality_grandpa::grandpa_peers_set_config()`

> 2. Since the messages exchanged are specific to a certain chain, its name should contain the protocol ID

If we want to customize the grandpa protocol name to have chain-specific ID (e.g. `/polkadot/grandpa/1`), then we'd need the chain ID in places such as `client/finality-grandpa/src/lib.rs::run_grandpa_voter()`.

Where is the _chain ID_ specified, what can be used as a chain-specific ID?

**Comment by tomaka** [comment]
We have this thing called the `protocolId` in the chain specification. The sync and transaction protocols already use this `protocolId` in their name.

However we have a plan to use the genesis hash instead of the `protocolId`, and it probably makes more to transition Grandpa to use the genesis hash: https://github.com/paritytech/substrate/issues/7746

**Comment by tomaka** [comment]
> Using a new static /substrate/grandpa/1 protocol name is easy AFAICT:
just use new protocol name, and add old protocol name (/paritytech/grandpa/1) to fallback_names in sc_finality_grandpa::grandpa_peers_set_config()

Yes

**Comment by burdges** [comment]
Assuming this is not pressing, we might consider merging this transition with a switch to Rabin-Williams signatures or something else faster than ed25519.   https://github.com/RustCrypto/RSA/issues/118

This is based upon my understanding that grandpa spends a lot of CPU on signature verification.

**Comment by tomaka** [comment]
We can always transition from `/blablabla/grandpa/1` to `/blablabla/grandpa/2` in the future.
