### ISSUE TITLE
Build tries to call git

### ISSUE THREAD

**Issue by yurivict** [paritytech/substrate#7254]
```
       Fresh rand_core v0.5.1
warning: Git command failed with status: exit code: 128
warning: Could not find `.git/HEAD` searching from `/usr/ports/security/substrate/work/substrate-2.0.0/bin/node-template/node` upwards!
       Fresh const-random-macro v0.1.8
 ```

Two issues:
1. It can't find git thatis installed
2. It shouldn't call git during build because (a) there is no internet connection (b) tarballs weren't git-cloned.

**Comment by bkchr** [comment]
The build is not failing, so I don't see any problems.

We just try to find the current revision to include it into the executable, but as said above the build is not failing when it can not find it.
