### ISSUE TITLE
error: could not compile `sp-application-crypto

### ISSUE THREAD

**Issue by GowthamChowdary** [paritytech/substrate#7256]
had this problem while i trying to do "cargo install node-cli --git https://github.com/paritytech/substrate.git --tag v2.0.0-rc4 --force --locked" from the [tutorial](https://substrate.dev/substrate-contracts-workshop/#/0/setup). it throws a bunch of "unexpected token" errors and " error[E0277]" s at me. 
on windows 10, rustc 1.46.0 .

**Comment by bkchr** [comment]
Please post the errors or otherwise we can not help you.

**Comment by xwvvvvwx** [comment]
I have the same error when trying to compile the `startercode` branch of [the substrate utxo workshop](https://github.com/substrate-developer-hub/utxo-workshop/tree/c7d46bcf07b4bfc3f454511c548011eca3389a05). I am using `rustc 1.48.0-nightly (7f7a1cbfd 2020-09-27)` and `cargo 1.48.0-nightly (05c611ae3 2020-09-23)`.

The full error output in this [this gist](https://gist.github.com/xwvvvvwx/7f7c845ea975593f74fa25f986e25c43)

**Comment by GowthamChowdary** [comment]
yep, i've got the same errors.

**Comment by bkchr** [comment]
Do you get the same errors on Substrate master? I tried the mentioned rust version and it compiles for me.

**Comment by xwvvvvwx** [comment]
latest master compiles fine for me with the above mentioned versions, would seem to rather be an issue of outdated dependencies / underspecified compiler requirements in the workshop repo. Thanks!

**Comment by GowthamChowdary** [comment]
@xwvvvvwx what changes did you make?

**Comment by xwvvvvwx** [comment]
@GowthamChowdary I didn't make any changes, I just tried compiling the `master` branch of substrate. The `utxo-workshop` repo is using an older version of substrate that I assume is no longer compatible with latest nightly rust.

For future reference I was able to compile the `utxo-runtime` package in the `startercode` branch on the `utxo-workshop` repo using `rustc 1.47.0-nightly (8e21bd063 2020-08-14)`.

**Comment by bkchr** [comment]
@xwvvvvwx why are you not using the master branch of the UXTO workshop? That compiles for me.

**Comment by xwvvvvwx** [comment]
because the workshop instruction videos say to start with the `startercode` branch

**Comment by bkchr** [comment]
@nczhu @apopiak could someone of you please update the workshop accordingly. Thank you.

**Comment by willy20040711** [comment]
I got the same error.

**Comment by fiexer** [comment]
Any updates on this?
Error is still happening. Thanks

**Comment by bkchr** [comment]
Please see https://github.com/substrate-developer-hub/utxo-workshop/pull/79 and open issues in the appropriate repository.
