### ISSUE TITLE
error: could not compile " error[E0046]: not all trait items implemented, missing: `Pair`"

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/substrate#7270]
After receiving the substrate from git master, adding the just following pallet(substrate-validator-set) to the node-templete and while building the error is as follows. Can you see why?  
for the below error missing, i add type Pair = Type, but still same error after build.
In primitives/application-crypto/src/lib.rs for substrate master git, the part where there are no declarations actually seems to be the problem.

-Cargo.lock (substrate) : sp-application-crypto version = "2.0.0"
-> library confilct not found

-cargo version : cargo 1.46.0 (149022b1d 2020-07-17)
-rustc version : rustc 1.46.0 (04488afe3 2020-08-24)
-linux : centos 7
-https://github.com/gautamdhameja/substrate-validator-set (pallet)

-error
error[E0046]: not all trait items implemented, missing: Pair
--> /home/final/v1/primitives/application-crypto/src/lib.rs:240:3
|
240 | impl $crate::CryptoType for Public {}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing Pair in implementation
|
::: /home/final/v1/primitives/application-crypto/src/ed25519.rs:29:5
|
29 | crate::app_crypto!(super, ED25519);
| ----------------------------------- in this macro invocation
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
= help: implement the missing item: type Pair = Type;

error[E0046]: not all trait items implemented, missing: Pair
--> /home/final/v1/primitives/application-crypto/src/lib.rs:433:3
|
433 | impl $crate::CryptoType for Signature {}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing Pair in implementation
|
::: /home/final/v1/primitives/application-crypto/src/ed25519.rs:29:5
|
29 | crate::app_crypto!(super, ED25519);
| ----------------------------------- in this macro invocation
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
= help: implement the missing item: type Pair = Type;

error[E0046]: not all trait items implemented, missing: Pair
--> /home/final/v1/primitives/application-crypto/src/lib.rs:240:3
|
240 | impl $crate::CryptoType for Public {}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing Pair in implementation
|
::: /home/final/v1/primitives/application-crypto/src/sr25519.rs:29:5
|
29 | crate::app_crypto!(super, SR25519);
| ----------------------------------- in this macro invocation
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
= help: implement the missing item: type Pair = Type;

error[E0046]: not all trait items implemented, missing: Pair
--> /home/final/v1/primitives/application-crypto/src/lib.rs:433:3
|
433 | impl $crate::CryptoType for Signature {}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing Pair in implementation
|
::: /home/final/v1/primitives/application-crypto/src/sr25519.rs:29:5
|
29 | crate::app_crypto!(super, SR25519);
| ----------------------------------- in this macro invocation
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
= help: implement the missing item: type Pair = Type;

error[E0046]: not all trait items implemented, missing: Pair
--> /home/final/v1/primitives/application-crypto/src/lib.rs:240:3
|
240 | impl $crate::CryptoType for Public {}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing Pair in implementation
|
::: /home/final/v1/primitives/application-crypto/src/ecdsa.rs:28:5
|
28 | crate::app_crypto!(super, ECDSA);
| --------------------------------- in this macro invocation
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
= help: implement the missing item: type Pair = Type;

error[E0046]: not all trait items implemented, missing: Pair
--> /home/final/v1/primitives/application-crypto/src/lib.rs:433:3
|
433 | impl $crate::CryptoType for Signature {}
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing Pair in implementation
|
::: /home/final/v1/primitives/application-crypto/src/ecdsa.rs:28:5
|
28 | crate::app_crypto!(super, ECDSA);
| --------------------------------- in this macro invocation
|
= note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
= help: implement the missing item: type Pair = Type;

error: aborting due to 6 previous errors

For more information about this error, try rustc --explain E0046.
error: could not compile sp-application-crypto

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by bkchr** [comment]
Please stop opening the same issue twice. You closed the other one, so I will close this one as well.

**Comment by puffanddmx** [comment]
Sorry. I just changed the place to upload the issue because the old place is not substrate channel

**Comment by puffanddmx** [comment]
> Please stop opening the same issue twice. You closed the other one, so I will close this one as well.

Sorry. I just changed the place to upload the issue because the old place is not substrate channel (maybe named subp...)

**Comment by bkchr** [comment]
It was still Substrate and I moved it by reason.

**Comment by puffanddmx** [comment]
anyway thanks!
