### ISSUE TITLE
Add EVM precompiles with custom index / address

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7286]
AFAIK, precompiles will be the way for EVM contracts to interact with runtime so we will want to add custom precompiles.
In order to avoid conflicts with future precompiles, we should be able to choose a custom index / address.

The current implementation is just a tuple of precompiles and the tuple index is the contract address, which is hard to support custom index.

cc @sorpaas

**Comment by sorpaas** [comment]
@xlc Right now you can always do this by directly implementing `Precompiles` trait, bypassing `Precompile` tuple.

To support a simpler interface we need type-level maps. We can either do this via `Get<HashMap<H160, Precompile>>>` or pull in typenum.

**Comment by xlc** [comment]
pallet-evm is no longer part of Substrate so close this one.
