### ISSUE TITLE
Could not compile v2.0.0

### ISSUE THREAD

**Issue by aidenthefox** [paritytech/substrate#7300]
it gives an error

  error[E0658]: function pointers cannot appear in constant functions
    --> /home/enumivo/.cargo/registry/src/github.com-1ecc6299db9ec823/environmental-1.1.1/src/local_key.rs:30:19
     |
  30 |     pub const fn new(init: fn() -> T) -> LocalKey<T> {
     |                      ^^^^
     |
     = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
     = help: add `#![feature(const_fn_fn_ptr_basics)]` to the crate attributes to enable

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0658`.
  error: could not compile `environmental`

even using older nightly versions

**Comment by bkchr** [comment]
Run `cargo update -p environmental` to fix this.
