### ISSUE TITLE
elections should use ref_count as well

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#7305]
Elections-phragmen module is also storing some deposit+storage for an account, and need to ensure that the account cannot be killed before the storage is cleared, thus needs to use `inc_ref` and `dec_ref` from system.

**Comment by gavofyork** [comment]
If it's keeping a deposit and/or introducing a lock on the account's funds, then it's already fine and no additional ref counting is needed. `inc_consumer` is specifically for instances where items relating to an account are placed in storage and no deposit is taken (so they're effectively piggybacking on the account's ED).

**Comment by kianenigma** [comment]
Thanks for clarifying -- then this this is a wontfix.
