### ISSUE TITLE
Transaction would exhaust the block limits

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/substrate#7309]
hi 
i try to deploy a.wasm file on substrate using function system.setCode.
i got the limit error below.
code byte for a.wasm is just 91,594 bytes.
what do i modify for this successful? MaximumExtrinsicWeight -> percent up?

parameter_types! {

	pub const ExtrinsicBaseWeight: Weight = 0;
	pub const BlockHashCount: BlockNumber = 2400;
	/// We allow for 2 seconds of compute with a 6 second average block time.
	pub const MaximumBlockWeight: Weight = 2 * WEIGHT_PER_SECOND;
	pub const AvailableBlockRatio: Perbill = Perbill::from_percent(75);
	/// Assume 10% of weight for average on_initialize calls.
	pub MaximumExtrinsicWeight: Weight = AvailableBlockRatio::get()
		.saturating_sub(Perbill::from_percent(10)) * MaximumBlockWeight::get();
	pub const MaximumBlockLength: u32 = 20 * 1024 * 1024;
	pub const Version: RuntimeVersion = VERSION;

}

code: Bytes
a.wasm (91,594 bytes)

-error-
system.setCode
1010: Invalid Transaction: Transaction would exhaust the block limits

**Comment by bkchr** [comment]
You need to overwrite the weight of the transaction and that can be done from polkadot-js.

**Comment by puffanddmx** [comment]
can you explain it in details?
(if you share the link, it is ok)

**Comment by bkchr** [comment]
Please read the tutorial: https://substrate.dev/docs/en/tutorials/upgrade-a-chain/sudo-upgrade#upgrade-the-runtime
