### ISSUE TITLE
Implement `best_seen_block` loader for NetworkService 

### ISSUE THREAD

**Issue by tgmichel** [paritytech/substrate#7311]
To complement `is_major_syncing`, ideally there should be a way of loading the `best_seen_block` (Target sync block number) from the `NetworkService`.

**Comment by tomaka** [comment]
I believe this is a duplicate of https://github.com/paritytech/substrate/issues/5727

Please reopen if that's not the case.

**Comment by tgmichel** [comment]
I wouldn't call it duplicate, but related. If the shared `NetworkWorker::service` would have a `best_seen_block` loader, then it could be used to fix the RPC issue you mentioned, but is not RPC exclusive.

I leave it to you to decide if that is reason enough to have both issues open.

**Comment by dmitry-markin** [comment]
Now when https://github.com/paritytech/substrate/issues/5727 is implemented, do we still need this issue?

**Comment by altonen** [comment]
Closing as completed as best seen block is part of `NetworkStatus`: https://github.com/paritytech/substrate/blob/master/client/network/common/src/service.rs#L103
