### ISSUE TITLE
Enable off-chain workers to store API keys for http requests

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#7325]
Is it possible to configure an offchain-worker with an API key that might be necessary to execute its offchain-worker function?

In the same vein as having a keystore, if offchain-workers had an API keystore that they can depend upon but outside of the runtime, so that you don't have to store these values in the runtime for obvious reasons. Has this been thought of/discussed much?

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/issues/4420

This should what you ask for.
