### ISSUE TITLE
Embed version (or other metadata) into runtime wasm blob

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#7327]
Currently a wasm runtime blobs provides the exported function `Runtime_version` to report the version its version. So theoretically, in order to get the version of a given wasm blob one needs to spin up the whole Substrate Runtime execution environment and execute that function. And in order to run some code in wasm module, one needs to instantiate it and for instantiation one needs to satisfy all imports requested by that module (although those could be stubs).

The only thing that `Core_version` does is passing a struct through SCALE encoding. Or minimally it could have been just returning a prepared at compile-time encoded version buffer. Requiring executing code for that sounds a bit too much.

Instead we could embed this version information into the wasm binary.

Wasm module consist of header and multiple sections. Some of them are predefined and mandated by the spec, but there can be 0 or more custom sections. A custom section consists of a string with name of the section and arbitrary payload.

We could define a special custom section that would carry the runtime version. We can embed other useful stuff as well, like runtime metadata, or maybe some versioning for runtime interface, or something else.

Now, the effects are:

1. Reading the version becomes very easy. One needs to traverse all the sections and find the required one and deserialize the info. No need to execute anything.
1. Appending a section is a simple concatenation. Just slap the new section at the end of binary and it will work.
1. Build process might be a bit more complicated and would require some post processing. In the context of Substrate/FRAME I would image these responsibilities would be taken on by wasm-builder.

**Comment by tomaka** [comment]
What is the use case for this?
In my mind, `Core_version` is used mainly in order to verify the new runtime during a runtime upgrade, in which case verifying that the new runtime can actually instantiate properly is a very very good thing.

**Comment by pepyakin** [comment]
I agree testing instantiation is a good thing. But I am not sure if doing it on-chain is the best approach here because of its costs. Calling into a runtime is very expensive. Currently, it is extremely expensive since it will lead to compiling its wasm code. Our data shows it can take around 5 secs to compile a beefy runtime. This is just too much for PVF execution (which prompted interest in implementation). 

On the other hand, this test doesn't give much. It would run only a limited portion of code: specifically this `Core_version` entrypoint. It would also run without checking if all the imports are satisfied, which is enforced during a normal run. 

This makes this test a very shallow one and very heavy. A better approach in my opinion is to rely on off-chain testing for such scenarios.

**Comment by pepyakin** [comment]
#8688 introduced version embedding into the wasm binary. Introduction of the same thing for the metadata is tracked by https://github.com/paritytech/substrate/issues/8870

**Comment by nazar-pc** [comment]
I just hit this as an obstacle for Subspace.

We are doing a lot of unusual things in our protocol, one of which is separating consensus nodes from execution nodes. We model them as two closely related, but physically distinct "chains", which means we technically have two runtimes.

It is desirable to combine two runtimes into one WASM bundle in our case, which I did and got weird errors that ultimately led me to https://github.com/paritytech/substrate/pull/8688 and from there here.

Since legacy way of going through instantiation is still present I'll probably strip extra sections for now to unblock further development on our side, but I'm also wondering if this can be revisited/revised.

One approach I think might be viable is to avoid WASM compilation and use interpreter mode for the particular use case described here, this should have a lower cost/time from if I understand it correctly. Another, more hacky way would be to have a way to specify a prefix to emitted link sections, so even if they are global, they can be distinguished from each other.

**Comment by bkchr** [comment]
@nazar-pc even when you strip the version section, it will not work. The runtime api is exposing the functions as extern C functions. Meaning you will have something like `Core_version` two times, which is also not allowed. 

Without wanting to look into what you are doing there exactly, it just sounds wrong and will not be supported by us.

**Comment by nazar-pc** [comment]
Runtimes in their own submodules in Rust. As long as the same versions of dependencies are used (which is the case for me), both instances of `Core_version` are identical and only one copy is present in WASM bundle. Seems to work just fine. The only issue is those global `link_section`s right now.

I worked around that by removing `sp_version::runtime_version`, thus forcing legacy code path, but it relies on current implementation details of Substrate and would be great to find a way that doesn't require global 

Even outside of my use case, if interpreting WASM is a viable option, it will even reduce the size of the WASM bundle a bit (349 bytes in my case across both sections) and will allow to remove `sp_version::runtime_version` macro.

**Comment by bkchr** [comment]
@nazar-pc again, without having looked into what you are doing. I assume that by combining both runtimes into one wasm blob you try to only have one source of truth? If that is the case, you could just have the hash of the other runtime in the state of the other runtime.
