### ISSUE TITLE
Add RPC client for offchain_workers 

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate#7332]
## Feature Request
Currently there's HTTP support for offchain workers, from sp_io::offchain and depends on sp_core::offchain. It would also be interesting to have RPC support to be able to query other RPCs such as other blockchain clients. This would enable building a light-client directly as an offchain worker.

Is this something that makes sense to have? Are there any recommendations, goals for implementation? I've been reading the code and have a bit of a hard time following how it is all handled with the http utility.

At first glance it seems:
- Extend `OffchainExt` with starting and receiving RPC calls/responses
- Expose raw RPC calls to offchain worker such that it can be called like
```
let request = rpc::Call::fetch(
	"mainnet1.edgewa.re",
	id,
	jsonrpc_version,
	method,
	params,
);
```

Any help or insight would be appreciated. I'm guessing you can't just import jsonrpc libraries into the pallet this since that wouldn't be no_std compatible.

**Comment by drewstone** [comment]
Maybe this isn't necessary if I can just POST to an RPC? I might be overthinking this.

**Comment by bkchr** [comment]
You can just develop your own runtime interface functions that provide a rpc interface.

**Comment by bkchr** [comment]
As there is currently no need to have this in Substrate, you can just develop your own host interface that is doing rpc requests for you.
