### ISSUE TITLE
warning# Git command failed with status: exit code: 128

### ISSUE THREAD

**Issue by Tassz44** [paritytech/substrate#7333]
I am following the tutorial [importing contracts pallet], and [cargo +nightly-2020-10-06 build] - load successfully, although there are 2 warnings: Git command failed with status: exit code: 128 &  Could not find `.git/HEAD`. 
Is this a bug or is there code to remove warnings?

**Comment by bkchr** [comment]
This warnings comes when you don't execute the compilation in a git repo. However it is fine to ignore and nothing bad happens ;)

**Comment by Tassz44** [comment]
Many thanks bkchr!

**Comment by Tassz44** [comment]
Hi,

I am following tutorial [Implementing the Contract Trait in runtime].

Added code snip to parameter_types! and to imp trait runtime. When I run cargo check -p node-template-runtime receive error:

 - error[E0282]: type annotations needed

- error: could not compile sp-arithmetic

   note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

I am using windows not mac, and had this error previously and it was due to nightly?

*Strange - when I run cargo +nightly-2020-10-06 check instead of cargo check -p node-template-runtime I receive a different error: cannot multiply MILLICENTS to {integer} cannot multiply CENTS to {integer}..

Tassz
________________________________

**Comment by bkchr** [comment]
Yes, you need to downgrade the nightly to the release from the first of october for example.

**Comment by Tassz44** [comment]
Hi,

Thanks for your reply.

I am using nightly-2020-10-06.. Where do downgrade nightly release from 1st october?

Tassz
________________________________

**Comment by bkchr** [comment]
https://substrate.dev/docs/en/knowledgebase/getting-started/#downgrading-rust-nightly

**Comment by Tassz44** [comment]
Thanks!
________________________________

**Comment by Tassz44** [comment]
Hi,

I have downgraded to 'rustup install nightly-2020-01-08' and run 'cargo +nightly-2020-01-08 build'..

When I run [cargo check -p node-template-runtime] receive error:
error[E0658]: subslice patterns are unstable
help: ]
________________________________

**Comment by bkchr** [comment]
I said the first of october and not the first of august ;)

**Comment by Tassz44** [comment]
Hi,

I've run: rustup uninstall nightly
               rustup install nightly-2020-10-01

               # find your nightly toolchain
               rustup toolchain list

              rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-01

Then: cargo +nightly-2020-10-01 build...

Get errors error[E0277]: cannot multiply `MILLICENTS` to `{integer}`_cannot multiply `CENTS` to `{integer}`..

Is this due to me not correctly configuring runtime file [lib.rs]?

Appreciate your feedback 😊

Tassz



________________________________

**Comment by bkchr** [comment]
Looks like you may have some other error in your code.

**Comment by Tassz44** [comment]
Ok Thanks.. Will carefully check over code and tutorial... Last question - is nightly-2020-10-01 to must stable version?
________________________________

**Comment by bkchr** [comment]
>  Last question - is nightly-2020-10-01 to must stable version?

I don't understand this?

**Comment by Tassz44** [comment]
I was building cargo with nightly-2020-10-06.... and now using 2020-10-01...
which of the above is the most stable version?



________________________________

**Comment by bkchr** [comment]
These are nightlies, they are not stable.

**Comment by Tassz44** [comment]
Thanks!

Sent from my BlackBerry — the most secure mobile device

**Comment by Tassz44** [comment]
Is nightly-2020-10-06 the latest updated version?

________________________________
