### ISSUE TITLE
Restarting node won't sync anymore.

### ISSUE THREAD

**Issue by aidenthefox** [paritytech/substrate#7345]
I started a single validator chain, it's running fine producing blocks and finalizing. Then i started a new node connecting to the validator, it sync's and keeps on synching. If I restart this node, it won't sync anymore. Is this expected on a chain with a single validator? I have not yet tried making it with 2 or more validators, I just want to know if syncing won't happen in this case if the 2nd non validating node stops and starts again.

**Comment by bkchr** [comment]
Hey no that is not expected.

Please run the second node with `-lsync=trace` and post a log of it. Otherwise we can not help ;)

**Comment by aidenthefox** [comment]
[LOG.txt](https://github.com/paritytech/substrate/files/5398503/LOG.txt)

**Comment by aidenthefox** [comment]
[LOG.txt](https://github.com/paritytech/substrate/files/5398520/LOG.txt)

**Comment by bkchr** [comment]
This is not the output of running with `-lsync=trace`?

There isn't anything useful in these logs.

**Comment by aidenthefox** [comment]
[Uploading trace.log…]()

**Comment by aidenthefox** [comment]
[trace.log](https://github.com/paritytech/substrate/files/5400094/trace.log)

**Comment by bkchr** [comment]
@aidenthefox which version of Substrate are you using?

And could you please give a detailed (which command you have executed) write up on how to reproduce this?

**Comment by aidenthefox** [comment]
v2.0.0

./substrate --chain raw.json --base-path /tmp/node02 --port 30334 --ws-port 9945 --rpc-port 9934 --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --rpc-methods=Unsafe --name MyNode02 --bootnodes /ip4/45.79.90.146/tcp/30333/p2p/12D3KooWNQjZT9LNi5jnJUwageh89sQSm4xfzA3kmRxnzexRBAzW

**Comment by aidenthefox** [comment]
i simply booted up a chain with a custom spec (just 1 validator) and used a new instance of a non validating node to sync to it.

also, the chain spec i modified this:

      "palletStaking": {
        "historyDepth": 84,
        "validatorCount": 2,
        "minimumValidatorCount": 1,
        "invulnerables": [],
        "forceEra": "ForceNone",
        "slashRewardFraction": 100000000,
        "canceledPayout": 0,
        "stakers": [
          [
            "5HQGEpUoGGwiBQU6uSunL1HKFQyD4QFaq77EkSRW8dq6ohgr",
            "5GZ3Ty9kqzDnwbH1QaZvKKfCgJsfaY1k24yA1rWqhP7wh82p",
            1000000000000000000000,
            "Validator"
          ]
        ]
      },

i'm not sure if it's a factor but i changed forceEra and removed the invulnerables

**Comment by bkchr** [comment]
Can you please post the full chain spec, ty.

And could you also try to reproduce this on master?

**Comment by aidenthefox** [comment]
this is the chain spec:

[custom.json.txt](https://github.com/paritytech/substrate/files/5405181/custom.json.txt)

i'll try to reproduce this it on master later and give you feedback

**Comment by aidenthefox** [comment]
using the master branch for the main node (validator) makes the v2.0.0 nodes (non validators) sync, so it seems the problem is using v2.0.0 in the main node. @bkchr

**Comment by aidenthefox** [comment]
i tried upgrading to master branch the non validator node and it still won't sync. but when i upgraded the main node to master, the v2 node and the master node can now sync to the main node.

**Comment by bkchr** [comment]
So this is fixed?

**Comment by aidenthefox** [comment]
> So this is fixed?

yes it seems fixed in master

**Comment by bkchr** [comment]
Perfect, thank you for testing master. I will close this pr now.
