### ISSUE TITLE
may be a small error in `sp-tracing` macro? target field is not from macro parameter

### ISSUE THREAD

**Issue by atenjin** [paritytech/substrate#7348]
I'm not sure where this small tip is an error:

in `sp-tracing` crate, in `within_span` and `enter_span`, I find that the macro has parameter `$lvl:expr`, but it not used in macro implementation part, in impementation all is filled `TRACE` level, like:
```rust
	(
		$lvl:expr,
		$name:expr;
		$( $code:tt )*
	) => {
		{
			$crate::within_span!($crate::span!($crate::Level::TRACE, $name); $( $code )*)
		}
	};
```
may should be:
```rust
	(
		$lvl:expr,
		$name:expr;
		$( $code:tt )*
	) => {
		{
			$crate::within_span!($crate::span!($lvl, $name); $( $code )*)
		}
	};
```
I'm not sure, in my view, I think the `$lvl:expr` should be used...

https://github.com/paritytech/substrate/blob/900d034fc1ba0ccb30dd54b2dd7498ad5caa7fb5/primitives/tracing/src/lib.rs#L148-L165

https://github.com/paritytech/substrate/blob/900d034fc1ba0ccb30dd54b2dd7498ad5caa7fb5/primitives/tracing/src/lib.rs#L226-L236

if this target level just should be `TRACE`, so way? 
and if `TRACE` is be pointed, the parameter `$lvl:expr` in marco is useless, and should be removed.

**Comment by bkchr** [comment]
cc @mattrutherford

**Comment by mattrutherford** [comment]
Agreed, this doesn't look right - thanks for the detailed report @AtenJin

**Comment by mattrutherford** [comment]
@dvdplm - it was this one mentioned as good starter issue
