### ISSUE TITLE
failed to run custom build command for `node-template-runtime v2.0.

### ISSUE THREAD

**Issue by MarekPas** [paritytech/substrate#7349]
>cargo build --release

error: failed to run custom build command for `node-template-runtime v2.0.0 (E:\Polkadot\substrate-node-template\
runtime)`

Caused by:
  process didn't exit successfully: `E:\Polkadot\substrate-node-template\target\release\build\node-template-runti
me-662494c5ad0f9f9c\build-script-build` (exit code: 1)
  --- stdout
  Executing build command: "rustup" "run" "nightly" "cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=E
:\\Polkadot\\substrate-node-template\\target\\release\\wbuild\\node-template-runtime\\Cargo.toml" "--color=alway
s" "--release"

.
.
.

  error: process didn't exit successfully: `E:\Polkadot\substrate-node-template\target\release\wbuild-runner\node
-template-runtime3982002549176752393\target\x86_64-pc-windows-msvc\release\wasm-build-runner-impl.exe` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by bkchr** [comment]
Please post more output. This output doesn't help.

**Comment by MarekPas** [comment]
Ok, here is a full output:
`   Compiling node-template-runtime v2.0.0 (E:\Polkadot\substrate-node-template\runtime)
   Compiling alga v0.9.3
   Compiling zstd-safe v2.0.5+zstd.1.4.5
   Compiling polyval v0.4.0
   Compiling poly1305 v0.6.0
   Compiling aes-soft v0.4.0
   Compiling sha2 v0.9.1
   Compiling blake2 v0.9.0
   Compiling mio v0.6.22
   Compiling parking_lot_core v0.4.0
   Compiling zeroize_derive v1.0.0
   Compiling parity-util-mem-derive v0.1.0
   Compiling failure_derive v0.1.8
   Compiling wasm-bindgen-macro-support v0.2.65
   Compiling proc-macro-error-attr v1.0.3
   Compiling serde v1.0.114
   Compiling pin-project v0.4.23
   Compiling tracing v0.1.19
   Compiling ref-cast v1.0.2
   Compiling dyn-clonable v0.9.0
   Compiling prost v0.6.1
   Compiling thiserror v1.0.20
   Compiling asn1_der v0.6.3
   Compiling minicbor v0.5.1
   Compiling scroll v0.10.1
   Compiling strum v0.16.0
   Compiling futures-task v0.3.5
   Compiling blocking v0.4.7
   Compiling rayon-core v1.7.1
   Compiling tokio-threadpool v0.1.18
   Compiling file-per-thread-logger v0.1.3
   Compiling tempfile v3.1.0
   Compiling fixed-hash v0.6.1
   Compiling twox-hash v1.5.0
   Compiling hashbrown v0.6.3
   Compiling multihash v0.11.2
   Compiling hmac-drbg v0.2.0
   Compiling salsa20 v0.3.0
   Compiling webpki-roots v0.19.0
   Compiling webpki-roots v0.18.0
   Compiling rustls v0.18.0
   Compiling ct-logs v0.7.0
   Compiling bindgen v0.54.0
   Compiling num-rational v0.2.4
   Compiling parking_lot v0.9.0
   Compiling zstd v0.5.3+zstd.1.4.5
   Compiling ghash v0.3.0
   Compiling aes v0.4.0
   Compiling tokio v0.2.22
   Compiling mio-named-pipes v0.1.7
   Compiling mio-extras v2.0.6
   Compiling parking_lot v0.7.1
   Compiling zeroize v1.1.0
   Compiling wasm-bindgen-macro v0.2.65
   Compiling proc-macro-error v1.0.3
   Compiling indexmap v1.5.0
error: failed to run custom build command for `node-template-runtime v2.0.0 (E:\Polkadot\substrate-node-template\runtime
)`

Caused by:
  process didn't exit successfully: `E:\Polkadot\substrate-node-template\target\release\build\node-template-runtime-6624
94c5ad0f9f9c\build-script-build` (exit code: 1)
  --- stdout
  Executing build command: "rustup" "run" "nightly" "cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=E
:\\Polkadot\\substrate-node-template\\target\\release\\wbuild\\node-template-runtime\\Cargo.toml" "--color=always" "--re
lease"

  --- stderr
      Updating crates.io index
     Compiling winapi v0.3.9
     Compiling cfg-if v0.1.10
     Compiling getrandom v0.1.15
     Compiling serde v1.0.117
     Compiling proc-macro2 v1.0.24
     Compiling unicode-xid v0.2.1
     Compiling ryu v1.0.5
     Compiling byteorder v1.3.4
     Compiling semver-parser v0.7.0
     Compiling syn v1.0.45
     Compiling log v0.4.11
     Compiling ppv-lite86 v0.2.9
     Compiling serde_derive v1.0.117
     Compiling serde_json v1.0.59
     Compiling itoa v0.4.6
     Compiling either v1.6.1
     Compiling rustc-demangle v0.1.17
     Compiling semver v0.6.0
     Compiling itertools v0.8.2
     Compiling build-helper v0.1.1
     Compiling winapi-util v0.1.5
     Compiling remove_dir_all v0.5.3
     Compiling atty v0.2.14
     Compiling ansi_term v0.12.1
     Compiling fs2 v0.4.3
     Compiling rand_core v0.5.1
     Compiling semver v0.9.0
     Compiling toml v0.5.7
     Compiling quote v1.0.7
     Compiling parity-wasm v0.32.0
     Compiling same-file v1.0.6
     Compiling rand_chacha v0.2.2
     Compiling wasm-gc-api v0.1.11
     Compiling walkdir v2.3.1
     Compiling rand v0.7.3
     Compiling tempfile v3.1.0
     Compiling cargo_metadata v0.10.0
     Compiling substrate-wasm-builder v2.0.1
     Compiling wasm-build-runner-impl v1.0.0 (E:\Polkadot\substrate-node-template\target\release\wbuild-runner\node-temp
late-runtime11862385942918612855)
      Finished release [optimized] target(s) in 8m 19s
       Running `E:\Polkadot\substrate-node-template\target\release\wbuild-runner\node-template-runtime118623859429186128
55\target\x86_64-pc-windows-msvc\release\wasm-build-runner-impl.exe`
  ←[0m←[0m←[1m←[32m   Compiling←[0m node-template-runtime v2.0.0 (E:\Polkadot\substrate-node-template\runtime)
  ←[0m←[0m←[1m←[32m   Compiling←[0m sp-arithmetic v2.0.0
  ←[0m←[1m←[38;5;9merror[E0282]←[0m←[1m←[38;5;15m: type annotations needed←[0m
  ←[0m    ←[0m←[1m←[38;5;14m--> ←[0mC:\Users\Marek\.cargo\registry\src\github.com-1ecc6299db9ec823\sp-arithmetic-2.0.0\s
rc\fixed_point.rs:541:9←[0m
  ←[0m     ←[0m←[1m←[38;5;14m|←[0m
  ←[0m←[1m←[38;5;14m541←[0m  ←[0m←[1m←[38;5;14m| ←[0m  ←[0m                let accuracy = P::ACCURACY.saturated_into();←
[0m
  ←[0m     ←[0m←[1m←[38;5;14m| ←[0m                      ←[0m←[1m←[38;5;9m^^^^^^^^←[0m ←[0m←[1m←[38;5;9mconsider giving
`accuracy` a type←[0m
  ←[0m←[1m←[38;5;14m...←[0m
  ←[0m←[1m←[38;5;14m1595←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m/←[0m ←[0mimplement_fixed!(←[0m
  ←[0m←[1m←[38;5;14m1596←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    FixedI64,←[0m
  ←[0m←[1m←[38;5;14m1597←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    test_fixed_i64,←[0m
  ←[0m←[1m←[38;5;14m1598←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    i64,←[0m
  ←[0m←[1m←[38;5;14m...←[0m    ←[0m←[1m←[38;5;14m|←[0m
  ←[0m←[1m←[38;5;14m1601←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    "_Fixed Point 64 bits signed, range = [
-9223372036.854775808, 9223372036.854775807]_",←[0m
  ←[0m←[1m←[38;5;14m1602←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m);←[0m
  ←[0m     ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|__-←[0m ←[0m←[1m←[38;5;14min this macro invocation←[0m
  ←[0m     ←[0m←[1m←[38;5;14m|←[0m
  ←[0m     ←[0m←[1m←[38;5;14m= ←[0m←[1m←[38;5;15mnote←[0m: this error originates in a macro (in Nightly builds, run with
 -Z macro-backtrace for more info)←[0m

  ←[0m←[1m←[38;5;9merror[E0282]←[0m←[1m←[38;5;15m: type annotations needed←[0m
  ←[0m    ←[0m←[1m←[38;5;14m--> ←[0mC:\Users\Marek\.cargo\registry\src\github.com-1ecc6299db9ec823\sp-arithmetic-2.0.0\s
rc\fixed_point.rs:541:9←[0m
  ←[0m     ←[0m←[1m←[38;5;14m|←[0m
  ←[0m←[1m←[38;5;14m541←[0m  ←[0m←[1m←[38;5;14m| ←[0m  ←[0m                let accuracy = P::ACCURACY.saturated_into();←
[0m
  ←[0m     ←[0m←[1m←[38;5;14m| ←[0m                      ←[0m←[1m←[38;5;9m^^^^^^^^←[0m ←[0m←[1m←[38;5;9mconsider giving
`accuracy` a type←[0m
  ←[0m←[1m←[38;5;14m...←[0m
  ←[0m←[1m←[38;5;14m1604←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m/←[0m ←[0mimplement_fixed!(←[0m
  ←[0m←[1m←[38;5;14m1605←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    FixedI128,←[0m
  ←[0m←[1m←[38;5;14m1606←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    test_fixed_i128,←[0m
  ←[0m←[1m←[38;5;14m1607←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    i128,←[0m
  ←[0m←[1m←[38;5;14m...←[0m    ←[0m←[1m←[38;5;14m|←[0m
  ←[0m←[1m←[38;5;14m1611←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m        [-170141183460469231731.68730371588
4105728, 170141183460469231731.687303715884105727]_",←[0m
  ←[0m←[1m←[38;5;14m1612←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m);←[0m
  ←[0m     ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|__-←[0m ←[0m←[1m←[38;5;14min this macro invocation←[0m
  ←[0m     ←[0m←[1m←[38;5;14m|←[0m
  ←[0m     ←[0m←[1m←[38;5;14m= ←[0m←[1m←[38;5;15mnote←[0m: this error originates in a macro (in Nightly builds, run with
 -Z macro-backtrace for more info)←[0m

  ←[0m←[1m←[38;5;9merror[E0282]←[0m←[1m←[38;5;15m: type annotations needed←[0m
  ←[0m    ←[0m←[1m←[38;5;14m--> ←[0mC:\Users\Marek\.cargo\registry\src\github.com-1ecc6299db9ec823\sp-arithmetic-2.0.0\s
rc\fixed_point.rs:541:9←[0m
  ←[0m     ←[0m←[1m←[38;5;14m|←[0m
  ←[0m←[1m←[38;5;14m541←[0m  ←[0m←[1m←[38;5;14m| ←[0m  ←[0m                let accuracy = P::ACCURACY.saturated_into();←
[0m
  ←[0m     ←[0m←[1m←[38;5;14m| ←[0m                      ←[0m←[1m←[38;5;9m^^^^^^^^←[0m ←[0m←[1m←[38;5;9mconsider giving
`accuracy` a type←[0m
  ←[0m←[1m←[38;5;14m...←[0m
  ←[0m←[1m←[38;5;14m1614←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m/←[0m ←[0mimplement_fixed!(←[0m
  ←[0m←[1m←[38;5;14m1615←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    FixedU128,←[0m
  ←[0m←[1m←[38;5;14m1616←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    test_fixed_u128,←[0m
  ←[0m←[1m←[38;5;14m1617←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m    u128,←[0m
  ←[0m←[1m←[38;5;14m...←[0m    ←[0m←[1m←[38;5;14m|←[0m
  ←[0m←[1m←[38;5;14m1621←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m        [0.000000000000000000, 340282366920
938463463.374607431768211455]_",←[0m
  ←[0m←[1m←[38;5;14m1622←[0m ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|←[0m ←[0m);←[0m
  ←[0m     ←[0m←[1m←[38;5;14m| ←[0m←[1m←[38;5;14m|__-←[0m ←[0m←[1m←[38;5;14min this macro invocation←[0m
  ←[0m     ←[0m←[1m←[38;5;14m|←[0m
  ←[0m     ←[0m←[1m←[38;5;14m= ←[0m←[1m←[38;5;15mnote←[0m: this error originates in a macro (in Nightly builds, run with
 -Z macro-backtrace for more info)←[0m

  ←[0m←[1m←[38;5;9merror←[0m←[1m←[38;5;15m: aborting due to 3 previous errors←[0m

  ←[0m←[1m←[38;5;15mFor more information about this error, try `rustc --explain E0282`.←[0m
  ←[0m←[0m←[1m←[31merror←[0m←[1m:←[0m could not compile `sp-arithmetic`

  To learn more, run the command again with --verbose.
  error: process didn't exit successfully: `E:\Polkadot\substrate-node-template\target\release\wbuild-runner\node-templa
te-runtime11862385942918612855\target\x86_64-pc-windows-msvc\release\wasm-build-runner-impl.exe` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
`

**Comment by bkchr** [comment]
You need to downgrade your nightly: https://substrate.dev/docs/en/knowledgebase/getting-started/#downgrading-rust-nightly

Use 2020-10-01

**Comment by mastmaster** [comment]
That worked @bkchr for me
