### ISSUE TITLE
Do not make nodes lose network reputation if no connection is active

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#736]
If zero connections are active, we can assume that it's the local connectivity that is not working, and therefore nodes shouldn't lose reputation for being unreachable.

Alternatively, the more nodes we're connected to, the more reputation non-reachable nodes should lose.

**Comment by drewstone** [comment]
For the latter feature regarding varying reputation, this would require a change to how `Severity` responses are aggregated correct?  So far I'm having trouble finding out whether single bad actions that are flagged with this object are dealt with or if they are stored somewhere, aggregated, and acted upon at some later date.

**Comment by tomaka** [comment]
@drewstone You haven't picked the best timing to work on this, as I've opened #742 that completely revamps the code. The `v0.2` branch already contains the change and can be used to experiment.

The code that handles the reputation is in `topology.rs`, where it's referred as the score of an address. The topology is also aware of which addresses we're currently connected to, so that's where I would put that change.

**Comment by gavofyork** [comment]
@tomaka is this issue still relevant?

**Comment by tomaka** [comment]
Yes

**Comment by tomaka** [comment]
With the introduction of the peerset, I don't think this issue is relevant anymore.

In the previous system, nodes would gain reputation when we were connected to them, and therefore network outages were strongly tied to the reputation system.
The particularly problematic area was that nodes reputations could go below the ones of newly-discovered addresses.

Now, nodes will indeed still lose reputation in case of a network outage, but there's no problem with that anymore. Since nodes lose reputation the same way, the ordering of nodes doesn't change. Once the network goes up again, we will reconnect to the same nodes.
