### ISSUE TITLE
lightmode support ?

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/substrate#7364]
i run the substrate as a light mode. 
is it not support for the light mode ? (error below)
full mode is working well.

Error: Service(Client(NotAvailableOnLightClient))

**Comment by bkchr** [comment]
What are you calling?

**Comment by puffanddmx** [comment]
when i run daemon, i put the tag like below.

--light
 Experimental: Run in light client mode

**Comment by bkchr** [comment]
Why do you want to run a light client?

**Comment by puffanddmx** [comment]
just testing if it works or not because some of people want to use light mode not archive.

**Comment by bkchr** [comment]
You know that there exists normal full node that isn't an archive?

**Comment by puffanddmx** [comment]
i am going to check it out!
