### ISSUE TITLE
Runtime worker threads feature requests

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7366]
Followup of #7089 

Other than my comments here https://github.com/paritytech/substrate/pull/7089#issuecomment-713178510 I have some feature requests.

Currently the interface is `Vec<u8> -> Vec<u8>` which is enough to get thing done, but not a developer friendly one.
It shouldn't be hard to implement some automatic args marshaling to improve type-safety.

It will be useful to have some messaging passing between threads. This will allow reuse runtime threads. From my understanding, spawn a new thread is expensive.

With the ability to reuse runtime threads, we can just have a global thread pool with fixed number thread. Instead of spawn new threads in pallet, pallet code should just dispatch a task into the global thread pool. This will allow to us disable the ability to spawn a new thread and prevent the possible resource abuse issue. It will be just one runtime config on the thread pool size and pallets developer doesn't need to worry about it anymore.

Should I break up this into multiple issues?

**Comment by NikVolf** [comment]
Thanks @xlc!

I think I will make separate issues that can clearly be implemented or addressed myself.
