### ISSUE TITLE
wasm-builder stalls build

### ISSUE THREAD

**Issue by pepyakin** [paritytech/substrate#7375]
While working (mostly `cargo check`) on polkadot I've stumbled on a problem where the `kusama-runtime` (only it) build hangs. According to `cargo build -vv` kusama-runtime starts building in the very start and the waits for the lock on build directory.

Here is the excerpt

```
[kusama-runtime 0.8.25]     Blocking waiting for file lock on package cache
[rococo-v1-runtime 0.8.25]     Blocking waiting for file lock on package cache
[polkadot-test-runtime 0.8.25]     Blocking waiting for file lock on package cache
[polkadot-runtime 0.8.25]     Blocking waiting for file lock on package cache
[westend-runtime 0.8.25]     Blocking waiting for file lock on package cache
[kusama-runtime 0.8.25]     Blocking waiting for file lock on build directory
```

Apparently, it never actually releases this lock. Removing `wbuild` and `wbuild-runner` didn't help and has lead to inclusion failures. Removing locks across the target directory didn't help as well, but probably I missed the right one.

`cargo clean` saved the day, but it's really annoying to wait for the rebuild.

**Comment by bkchr** [comment]
Is this reproducible?

**Comment by pepyakin** [comment]
just got that the second time

here is my current workflow in detail: i do `cargo check --all --tests` a lot (doing many changes across codebase), and when I get the first error, I ^C the build. I suspect that it is related.

Meanwhile I tried to do 

```
find ./target -iname '.cargo-lock' -exec rm {} \;
```

to remove **all** the locks and it helps.
