### ISSUE TITLE
types reversed in name-service/src/lib.rs and name-service/src/mock.rs

### ISSUE THREAD

**Issue by spencerbh** [paritytech/substrate#7377]
https://github.com/paritytech/substrate/blob/af5eca240eec0ec33f6b6e17f9d7984c16369382/frame/name-service/src/mock.rs#L102
https://github.com/paritytech/substrate/blob/af5eca240eec0ec33f6b6e17f9d7984c16369382/frame/name-service/src/lib.rs#L81

Inconsistent order of types `<BlockNumber, Balance>` in ExtensionConfig, unsure if relevant in this context?

**Comment by thiolliere** [comment]
This is not in master, but only in this PR https://github.com/paritytech/substrate/pull/7197 isn't it ?

Thus I reported there
