### ISSUE TITLE
Add RPC to run constructors

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#7379]
Currently, the UI can use the `contract_call` in order to determine gas costs of a call. However, this is not possible when deploying because there is no RPC that allows running a constructor.

Add a rpc `contracts_construct(code_hash, input) -> (ExecResult, ConsumedGas)` to allow for gas estimation on deploy.

@jacogr

**Comment by ayushmishra2005** [comment]
@athei Is below abstraction right?

    #[rpc(name = "contracts_construct")]
	fn construct(
		&self,
		address: AccountId,
		at: Option<BlockHash>,
	) -> Result<Option<ConsumedGas>>;

Please guide me for the implementation part.

**Comment by athei** [comment]
I am not exactly sure how this will look like because this depends on the changes that will happen to instantiation due to [code rent](https://github.com/paritytech/substrate/issues/6596). Adding a new RPC before those are makes no sense.
