### ISSUE TITLE
decl_storage macro strips conditional configuration checks

### ISSUE THREAD

**Issue by gregdhill** [paritytech/substrate#7430]
I want to declare a new storage item available only when a specific feature is enabled but it would seem as though the `decl_storage!` macro strips `cfg` items.

```rust
decl_storage! {
        #[cfg(feature = "foo-bar")]
        FooBar get(fn foo_bar) config(): bool;
}
```

**Comment by thiolliere** [comment]
yes all attributes which are not doc are ignored https://github.com/paritytech/substrate/blob/510e68b8d06a3d407eda0d4c1c330bd484140b65/frame/support/procedural/src/storage/mod.rs#L300-L303

Handling them sounds complicated, though we can return an error instead of ignoring non-doc attribute

**Comment by thiolliere** [comment]
I don't think we will fix it for decl_storage macro, the issue for the pallet v2 is here https://github.com/paritytech/substrate/issues/8102
