### ISSUE TITLE
Limit the number of simultaneous inbound TCP connections

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#7432]
(I somehow misremember having done that in the past, but apparently not)

At the moment, if too many TCP connections arrive, we will reach the system's ulimit, which also has the consequence that we can't open outbound TCP connections anymore, and not open files anymore.

It seems preferable to limit the number of TCP connections manually rather than relying on the ulimit.

**Comment by burdges** [comment]
I forget which Noise handshakes protocol labs likes, but around whitelisting..

Anything with a K in the second position authenticates the receiver in the first packet, and then I in the first position authenticates the sender in the first, but only to the desired receiver.  So IK, IKpsk1, IKpsk2, etc. all permit some whitelisting by receivers.  At least this holds with UDP ala nQUIC but not sure about TCP.  

I think TLS 1.3 cannot do any whitelisting without its 0-RTT extension.  Appears https://github.com/rot256/ninn was last worked on two years ago, not sure if a more recent nQUIC fork exists.  I'll ask around about nQUIC being reviewed.

**Comment by burdges** [comment]
It appears the nQUIC authors wrote the ninn fork of quinn https://eprint.iacr.org/2019/028.pdf so maybe we should bring ninn up to date with quinn.

**Comment by burdges** [comment]
I'll also caution that IK permits a replay attacks on the first round, so adversaries might DoS you by pretending to be other validators.  There are handshakes like IKpsk1, and this hypothetical IKpsk0, that avoid this issue by ratcheting the psk with every successful connection. 

Is this one packet DoS mode really correct?  Or can an adversary DoS with much less?  Or do they want more?

**Comment by tomaka** [comment]
https://github.com/libp2p/rust-libp2p/issues/1839

**Comment by tomaka** [comment]
Was done in #7606
