### ISSUE TITLE
Improve RandomNumberGenerator

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7434]
Currently RandomNumberGenerator only provides `pick_u32`, `pick_usize` (which is still pick_u32) and `pick_item`.

It should provide a method to generate a random byte stream so this can be more useful, like generate random u128.

My use case is offchain worker random number generation and the seed will be from `sp_io::offchain::random_seed()`.

**Comment by burdges** [comment]
It appears `sp_io::offchain::random_seed()` works only in off-chain workers, so anything you like works, like https://docs.rs/rand_chacha/0.2.2/rand_chacha/ or  https://docs.rs/rust-crypto/0.2.36/crypto/chacha20/struct.ChaCha20.html or similar. 
```
use ::rand_core::SeedableRng;
let rng = ::rand_chacha::ChaChaRng::from_seed(sp_io::offchain::random_seed());
```

**Comment by xlc** [comment]
Thanks for the suggestion @burdges 

It appears rand_chacha should work in runtime so we don't really have a use case for `RandomNumberGenerator` anymore?

**Comment by burdges** [comment]
I'd assume, but avoid the floating point methods in rand obviously.  

I've forgotten what `RandomNumberGenerator` does, but you cannot obtain great randomness inside the runtime, well except kinda by using BABE ala https://github.com/paritytech/substrate/issues/7046#issuecomment-714563982 etc.

**Comment by xlc** [comment]
https://github.com/paritytech/substrate/blob/master/primitives/runtime/src/random_number_generator.rs
It basically generates pseudo-random u32 by using a hasher and seed. Not much additional offering compare to rand_chacha.

**Comment by burdges** [comment]
I think chacha runs faster than most options here, unless your runtime has `RandomNumberGenerator` invoke some hash implemented in native code somehow.

**Comment by xlc** [comment]
RandomNumberGenerator is gone https://github.com/paritytech/substrate/pull/9198
