### ISSUE TITLE
Add ss58 prefix for Totem Live Accounting network

### ISSUE THREAD

**Issue by chrisdcosta** [paritytech/substrate#7439]
We would like to add the Totem Live Accounting Network prefix to the config.

We would like to reserve place 14 for the second Totem Testnet (Totem Lego on current v2.0 of Substrate) which will go live shortly, and for the eventual Totem Live Accounting MainNet which is planned for next year.

A pull request will be attached to this issue.

**Comment by apopiak** [comment]
#7442 was merged
