### ISSUE TITLE
RandomNumberGenerator panicking on pick_u32(u32::max_value)

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7444]
https://github.com/paritytech/substrate/blob/ab36e527eedf15a1fd74d257f5efca72d33e923c/primitives/runtime/src/random_number_generator.rs#L66

Addition overflow, I think the multiplication will also overflow.

Maybe we should just remove it and prefer `rand_chacha ` per https://github.com/paritytech/substrate/issues/7434#issuecomment-717244831

**Comment by ayushmishra2005** [comment]
@xlc How can I reproduce this?

**Comment by burdges** [comment]
It's likely tied into deployed chains, but it could be marked deprecated with a pointer to rand_chacha

**Comment by xlc** [comment]
Just call `rng.pick_u32(u32::max_value())` and it will panic. But as @burdges suggested someone need to decide if we should just deprecated this.

**Comment by gilescope** [comment]
I've fixed the initial issue and put a pointer in the docs to rand_chacha.
Can we close this issue out or should we add a formal deprecation attribute @burdges?

**Comment by burdges** [comment]
I suppose deprecation attributes could be useful if we do some regenesis or whatever in a few years.

**Comment by bkchr** [comment]
This thing is not used anywhere. (At least not in Substrate/Polkadot)

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/pull/9198 here we go.
