### ISSUE TITLE
rpc module for pallet-evm?

### ISSUE THREAD

**Issue by pangwa** [paritytech/substrate#7455]
It looks like the rpc module for pallet-evm is missing. Any plan to add rpc support for pallet-evm? Otherwise it's not possible to query evm contract data stores.

**Comment by bkchr** [comment]
CC @sorpaas

**Comment by sbhm2** [comment]
@pangwa can you show, how you integrated evm pallet in runtime lib.rs.
Also please refer to rpc module, I'll also going to need it once I will be able to integrate evm pallet.

**Comment by pangwa** [comment]
> @pangwa can you show, how you integrated evm pallet in runtime lib.rs.
> Also please refer to rpc module, I'll also going to need it once I will be able to integrate evm pallet.
for evm integration, please refer to: [https://github.com/AcalaNetwork/Acala/blob/b52fd9bd0fce3e8fe63e98deb06dbd66eeda7b1d/runtime/acala/src/lib.rs#L1277](code).

**Comment by NoCtrlZ** [comment]
@pangwa 
I think we can use Etherum RPC by using [this pallet](https://github.com/paritytech/frontier/blob/master/frame/ethereum/Cargo.toml).

**Comment by pangwa** [comment]
Awesome, thanks!

> @pangwa
> I think we can use Etherum RPC by using [this pallet](https://github.com/paritytech/frontier/blob/master/frame/ethereum/Cargo.toml).
> More details are in [here](https://github.com/paritytech/frontier#frontier)

**Comment by bkchr** [comment]
It seems this can now be closed. If I missed something, please reopen!
