### ISSUE TITLE
Non-instant finality and consensus abstraction

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#746]
To deal with consensus algorithms correctly, we'll need to handle non-finalized blocks in the client. We shouldn't prune non-finalized states (unless forced -- but we'll leave such forcing to future work). Finality information may come from outside of the client, so we'll need a method for finalizing older blocks. Finality comes with some optional data (raw bytes) we'll call a justification. For optimizing instant-finality cases like rhododendron, we'll have an optional argument to the block import method which can be used to finalize the block instantly.

GRANDPA can finalize many blocks at once, so the interface should not require that blocks are subsequently finalized, but rather do that internally by finalizing ancestors.

Along with import notification streams, we'll want finality notification streams for handling finality events in code outside the client code.

**Comment by rphmeier** [comment]
A note about #740: It makes use of a "leaves" list in the database backend. These leaves need to be pruned on finality.

**Comment by rphmeier** [comment]
#760 needs to be followed up by a PR to produce finality notifications. This might be most easily done by removing implicit finality from the backends (i.e. that each block finalized must be a direct child of the last block finalized, rather than being an arbitrary descendent). 

The client would perform many internal calls to `backend.finalize_block` when finalizing many blocks at once, and would broadcast notifications for each of them in turn. This prevents having to re-load the block hashes.

**Comment by rphmeier** [comment]
Moved the `ImportQueue` thing to #784

**Comment by gavofyork** [comment]
@rphmeier / @snd assigned you since you seem to be actively working on this

**Comment by snd** [comment]
what's left to do here?

**Comment by rphmeier** [comment]
Nothing!
