### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by maxsam4** [paritytech/substrate#7460]
We are seeing a leak of ~500 file descriptors every hour on our nodes.

`lsof` shows thousands of these.

```
polymesh 2911 polymesh  968u     sock                0,9      0t0 3560574381 protocol: TCPv6
polymesh 2911 polymesh  969u     sock                0,9      0t0 3560574745 protocol: TCPv6
polymesh 2911 polymesh  970u     sock                0,9      0t0 3560574528 protocol: TCPv6
polymesh 2911 polymesh  971u     sock                0,9      0t0 3560574908 protocol: TCPv6
polymesh 2911 polymesh  972u     sock                0,9      0t0 3560575520 protocol: TCPv6
polymesh 2911 polymesh  973u     sock                0,9      0t0 3560574530 protocol: TCPv6
polymesh 2911 polymesh  974u     sock                0,9      0t0 3560574681 protocol: TCPv6
polymesh 2911 polymesh  975u     sock                0,9      0t0 3560574604 protocol: TCPv6
polymesh 2911 polymesh  976u     sock                0,9      0t0 3560574922 protocol: TCPv6
``` 

The node is based on rc-6 release of the substrate framework. I disabled the authority discovery but it didn't change anything.

ps The leak is happening on regular full nodes as well i.e. not just sentry/validator nodes.

Source code: https://github.com/PolymathNetwork/Polymesh/tree/alcyone

Release binaries are also available on GitHub.

**Comment by bkchr** [comment]
We solved file descriptor leaking at some point, probably after rc-6. Can you please try latest master?

**Comment by maxsam4** [comment]
Thanks, I can confirm that the issue is not present in the 2.0.0 release.
