### ISSUE TITLE
Errors during cargo build --release

### ISSUE THREAD

**Issue by sensahin** [paritytech/substrate#7473]
I am following exact same commands explained on https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup

I am having below errors during "cargo build --release".

**Error1:** 

error[E0282]: type annotations needed
/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
let accuracy = P::ACCURACY.saturated_into();
consider giving `accuracy` a type
1595 | / implement_fixed!(
  1596 | |     FixedI64,
  1597 | |     test_fixed_i64,
  1598 | |     i64,
  ...    |
  1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
  1602 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Error2:**

error[E0282]: type annotations needed
/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
let accuracy = P::ACCURACY.saturated_into();
consider giving `accuracy` a type
  ...    |
  1611 | |         [-170141183460469231731.687303715884105728, 170141183460469231731.687303715884105727]_",
  1612 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Error3:**
error[E0282]: type annotations needed
/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
let accuracy = P::ACCURACY.saturated_into();
consider giving `accuracy` a type

1614 | / implement_fixed!(
  1615 | |     FixedU128,
  1616 | |     test_fixed_u128,
  1617 | |     u128,
  ...    |
  1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
  1622 | | );
       | |__- in this macro invocation
       |
       = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0282`.
error: could not compile `sp-arithmetic`
error: build failed

**Comment by bkchr** [comment]
See: https://github.com/paritytech/substrate/issues/7466
