### ISSUE TITLE
Keystore `raw_public_keys` returns wrong number of keys

### ISSUE THREAD

**Issue by rakanalh** [paritytech/substrate#7490]
In a test where the following keys are generated:
```
let keystore = LocalKeystore::in_memory();
keystore.sr25519_generate_new(TEST_TK, Some("//Alice"))
	.await.expect("InMem Keystore doesn't fail");
keystore.ed25519_generate_new(TEST_TK, Some("//Bob"))
	.await.expect("InMem Keystore doesn't fail");
keystore.ecdsa_generate_new(TEST_TK, Some("//Charlie"))
 	.await.expect("InMem Keystore doesn't fail");
```

**Expected behaviour**:
Calling sr25519_public_keys should return 1 key that was generated from `sr25519_generate_new`.

**Actual Behaviour**:
1. The call to `sr25519_public_keys` fails because trying to create `sr25519::Public::from_slice` for the ECDSA key returned by `keystore.raw_public_keys` panics. The panic is caused by the fact that a 32 byte key is expected while ECDSA public keys have the length of 33.
2. Even if the above issue is resolved, the call to `sr25519_public_keys` would return 2 as the call was able to "restore" sr25519 and ed25519 slices as sr25519 public keys.
```
assert_eq!(SyncCryptoStore::sr25519_public_keys(&keystore, TEST_TK).len(), 1); // FAILS
```

**Comment by bkchr** [comment]
We don't support running a node that use different crypto for the same key type and we will never support this. So, this is not a bug, it is a misuse!

**Comment by gnunicorn** [comment]
We would support a (remote) keystore serving multiple nodes with different crypto though, no? And even if not, I'd expect the node to not panic just because I added a different crypto under the same KEY_TYPE_ID...

**Comment by bkchr** [comment]
If one remote keystore serves multiple nodes, it would mean one node may signs for multiple authorities? I don't think that this will work. Babe for example tries to use all keys that it can find. I see us running here into problems.

How does the node panics in normal operation when you use a wrong crypto? How can I reproduce this?

**Comment by gnunicorn** [comment]
> If one remote keystore serves multiple nodes, it would mean one node may signs for multiple authorities?

Ehm, no. One does not imply the other. The server could very well decide to have one sign with one and one with another... as it would only hand out pairs selectively, too... 

As this  isn't the full server implementation, the question is merely, whether we would want our keystore to support the scenario(s) or expect the user to figure out that they need separate keystores or have their system panic.

**Comment by bkchr** [comment]
If the server is already doing the distinction, why not let it serve a different keystore per node?

I also don't think that we should encourage people to only have one remote keystore as this means that if you have access to one, you can compromise all nodes. 

The system can not really panic, as the keystore isn't aware which keytypes use which crypto.
