### ISSUE TITLE
How to interpret balances Deposit events?

### ISSUE THREAD

**Issue by alecalve** [paritytech/substrate#7491]
I've noticed that for some blocks in the early Polkadot history, the presence of Deposit events from the balances pallet may or may not actually increase the balance of the targeted account. My assumption was that all Deposit events result in a balance change, but this is not the case according to empirical data.

(This is a similar issue to https://github.com/paritytech/polkadot/issues/1845).

#### Context

I am running a Polkadot full node version 0.8.25 with relevant args --chain polkadot and --pruning archive.
I am querying it using the Substrate API sidecar.

#### Example situation

For example, block 31640's author doesn't receive funds following a Deposit event:

```
$ curl http://localhost:9934/accounts/167f5SpFqXtEKEShxjKVWG2YbmrzLuLAL1DFNZcMGDxRgFhM/balance-info\?at\=31639
... "nonce":"0","free":"0","reserved":"0","miscFrozen":"0","feeFrozen":"0" ...
$ curl http://localhost:9934/accounts/167f5SpFqXtEKEShxjKVWG2YbmrzLuLAL1DFNZcMGDxRgFhM/balance-info\?at\=31640
... "nonce":"0","free":"0","reserved":"0","miscFrozen":"0","feeFrozen":"0" ...
```

but for an earlier block, 31484, its author does receive funds for a similar event:

```
$ curl http://localhost:9934/accounts/146YJHyD5cjFN77HrfKhxUFbU8WjApwk9ncGD6NbxE66vhMS/balance-info\?at\=31483
... "nonce":"0","free":"369110000000","reserved":"0","miscFrozen":"0","feeFrozen":"0" ...
$ curl http://localhost:9934/accounts/146YJHyD5cjFN77HrfKhxUFbU8WjApwk9ncGD6NbxE66vhMS/balance-info\?at\=31484
... "nonce":"0","free":"369222866390","reserved":"0","miscFrozen":"0","feeFrozen":"0" ...
```

I could not find any explicit explanation as to why this is occurring.

#### Potential leads

Could it linked with the existential deposit? The account that didn't receive funds also didn't have a balance, and the amount it was slated to receive was below the existential deposit. However, in that case, why would a Deposit event be fired?

Is there any rule that I am not aware of that would explain this behaviour? Could it be the issue lies with the API sidecar?

Thanks in advance.

**Comment by bkchr** [comment]
Did you send more than existential  deposit to these accounts?

**Comment by alecalve** [comment]
To be clear, I'm not the one doing the on-chain activity, I'm just trying to interpret mainnet Polkadot data.

**Comment by bkchr** [comment]
This doesn't answer my question.

**Comment by alecalve** [comment]
At height 31639, [167f5..FhM](https://polkascan.io/polkadot/account/167f5SpFqXtEKEShxjKVWG2YbmrzLuLAL1DFNZcMGDxRgFhM) has a balance of 0.

Block 31640 is authored by [167f5..FhM](https://polkascan.io/polkadot/account/167f5SpFqXtEKEShxjKVWG2YbmrzLuLAL1DFNZcMGDxRgFhM), a balances Deposit [event](https://polkascan.io/polkadot/event/31640-6) is visible that targets that account. It's the only event in that block that concerns that account.

However, the balance of the account stays at 0.

**Comment by bkchr** [comment]
The amount is below the existential deposit. This means the account can not be created.

**Comment by alecalve** [comment]
So am I correct to assume that any event that credits free balance to an account should be ignored if that account was not previously `Endowed`?

**Comment by bkchr** [comment]
If the deposit is more than existential deposit, the account would be created.

**Comment by joepetrowski** [comment]
These events are the transaction fees earned by the 6 PoA validators during that phase of launch. Indeed, they had no actual accounts as they were just the validators at genesis. Transaction fees, being small anyway and only 20% going to the block author, are almost exclusively below ED.

You will see at some point there was a runtime upgrade with a high fee due to the length of the new runtime that actually created an account for one of the validators.
