### ISSUE TITLE
Can the linked list data of RC and RefCell be stored?

### ISSUE THREAD

**Issue by qaibeibei** [paritytech/substrate#7498]
Can the linked list data of RC and RefCell be stored?
I want to store a tree relationship

**Comment by bkchr** [comment]
Please stop opening the same issue multiple times.

**Comment by qaibeibei** [comment]
> 请停止多次打开同一期杂志。


Sorry, because the previous same question was not found without a reply, so I continued to ask a question

**Comment by bkchr** [comment]
Here is your question: https://github.com/paritytech/subport/issues/46
