### ISSUE TITLE
Fixed(I|U)(64|128)::(from|to)_fraction are dangerous

### ISSUE THREAD

**Issue by c410-f3r** [paritytech/substrate#7505]
Due to the native behavior of binary based floating numbers, it isn't possible to reliably assert that, e.g., `FixedU128::from_fraction(230000000442.54)` is indeed stored as a fixed `230000000442.54` integer representation.

**Comment by bkchr** [comment]
CC @kianenigma

**Comment by xlc** [comment]
This is a std only feature and cannot be used in wasm runtime. I think it is only used for tests and building chain spec.

**Comment by kianenigma** [comment]
Correct and thus, needless to fix.

**Comment by kianenigma** [comment]
(fwiw) I am actually up for removing them in favour of less confusion regarding float <-> runtime.

**Comment by c410-f3r** [comment]
Documentation about this behavior would be useful for users

**Comment by bkchr** [comment]
What kind of documentation? That these methods are not available in wasm?

**Comment by c410-f3r** [comment]
???

Documentation about the nature of binary-based floating point numbers that will result in plain wrong conversations for a type that wraps integers and is meant to be deterministic. IMHO, the fact that these methods can only be used for tests or whatever is just a detail because the semantics and functionalities aren't right.
