### ISSUE TITLE
Addresses passed with `--public-addr` get purged after a while

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#7518]
The `--public-addr` CLI option gives the possibility for the user to pass to the node its external IP addresses.

The way it's implemented is that at startup we call `libp2p::Swarm::add_external_address`:

https://github.com/paritytech/substrate/blob/3654d1ac2aa075cca1faa9f00580e1b9e3556041/client/network/src/service.rs#L381-L383

This, in turn, adds the address [to the registry](https://github.com/libp2p/rust-libp2p/blob/68c36d87d3727df6c18c1b36e662f714a0996a92/swarm/src/registry.rs#L68).

However, nodes continue to discover their (probably invalid) external IP address from other nodes.
Because of the way [libp2p's Registry](https://github.com/libp2p/rust-libp2p/blob/68c36d87d3727df6c18c1b36e662f714a0996a92/swarm/src/registry.rs#L68) is implemented, the addresses passed with `--public-addr` will eventually get purged. This is obviously not supposed to happen.

The detection [is automatically done in `libp2p-identify`](https://github.com/libp2p/rust-libp2p/blob/dc56d44edb09e64cd0abaa10043897bdb4c91a44/protocols/identify/src/identify.rs#L144-L146), so Substrate can't disable it.

There seems to be lacking a way in libp2p to implement something like `--public-addr`.

cc @mxinden @romanb

**Comment by tomaka** [comment]
For some history: `--public-addr` was implemented a long time ago when addresses stayed in the libp2p `Registry` forever.
But we then changed its behaviour to purge old addresses, and didn't update Substrate.

**Comment by romanb** [comment]
I can look into this on the libp2p side.

**Comment by tomaka** [comment]
@ddorgan The problem with nodes behind nginx not receiving incoming connections should now be fixed.

**Comment by ddorgan** [comment]
Good news, thanks @tomaka
