### ISSUE TITLE
Logs show block numbers in weird format

### ISSUE THREAD

**Issue by staking4all** [paritytech/substrate#7521]
Hi

In v24 and prior the logs would show the block numbers 

![image](https://user-images.githubusercontent.com/61656547/98846104-4e56d400-2457-11eb-88f5-979e09e1f214.png)

however from 25, 26 the logs seem to have a weird annotation for the block numbers. Is this correct and a new format? Or is it a bug? The block number is now hidden inside a bunch of new additional blurb
![image](https://user-images.githubusercontent.com/61656547/98846270-83fbbd00-2457-11eb-9dec-87c9fbb104a8.png)

According to telemetry the nodes is all fine and in sync.
![image](https://user-images.githubusercontent.com/61656547/98846372-a4c41280-2457-11eb-9b04-36394d667b72.png)

This impacts the monitoring on my nodes as I get info from the logs to do active alerts.

Thanks

**Comment by bkchr** [comment]
This looks like the log lines are mixed. How do you run the node? Did you tried to just run it on the terminal?

**Comment by staking4all** [comment]
I'm running it as a service as it is a validator node. So I read this in /var/log/syslog

I just tested it now on the terminal. It does not do this in the terminal.

It has a consistent pattern and if using a regex syntax you can pull out the number consistently. For some reason when writing to the log it has this extra text. If i revert back to version 24 it works fine. This is only visible from 25 and 26 which indicates something has changed from 25 that causes this.

Hope this helps

**Comment by bkchr** [comment]
I suspect this commit: https://github.com/paritytech/substrate/commit/46faa92432e3b85fde64e7fa504839ab81a462d1

By running it as service you mean you run it as systemd service?

**Comment by tomaka** [comment]
I think the "blobs" are just [ANSI color codes](https://en.wikipedia.org/wiki/ANSI_escape_code).
We shouldn't be trying to print colors when not printing to the terminal.

**Comment by staking4all** [comment]
> By running it as service you mean you run it as systemd service?

yes, run as systemd service

**Comment by bkchr** [comment]
Will be fixed by this: https://github.com/paritytech/substrate/pull/7525

**Comment by staking4all** [comment]
noice
