### ISSUE TITLE
build failed with compiling librocksdb-sys v6.11.4 failed on macOS 10.15.7

### ISSUE THREAD

**Issue by yiyanwannian** [paritytech/substrate#7522]
Compiling librocksdb-sys v6.11.4
The following warnings were emitted during compilation

   Compiling librocksdb-sys v6.11.4
   Compiling frame-executive v2.0.0
   Compiling pallet-sudo v2.0.0
   Compiling pallet-template v2.0.0 (/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/pallets/template)
   Compiling pallet-timestamp v2.0.0
   Compiling pallet-transaction-payment v2.0.0
   Compiling pallet-balances v2.0.0
   Compiling sc-client-api v2.0.0
   Compiling sc-rpc-api v0.8.0
   Compiling sc-transaction-graph v2.0.0
   Compiling pallet-session v2.0.0
   Compiling sc-block-builder v0.8.0
   Compiling sc-state-db v0.8.0
   Compiling sc-transaction-pool v2.0.0
   Compiling sc-light v2.0.0
   Compiling sc-consensus-slots v0.8.0
   Compiling sc-consensus v0.8.0
   Compiling substrate-frame-rpc-system v2.0.0
   Compiling sc-network v0.8.0
   Compiling sc-rpc v2.0.0
   Compiling sc-basic-authorship v0.8.0
   Compiling sc-consensus-aura v0.8.0
The following warnings were emitted during compilation:
。。。。。。。
warning: In file included from 
warning: 13 errors generated.
warning: 13 errors generated.
warning: 13 errors generated.
warning: 177 warnings and 13 errors generated.
warning: 13 errors generated.
warning: 13 errors generated.
warning: 13 errors generated.

error: failed to run custom build command for `librocksdb-sys v6.11.4`

Caused by:
  process didn't exit successfully: `/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-958b8483ede74939/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=rocksdb/
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-apple-darwin")
  CXX_x86_64-apple-darwin = None
  CXX_x86_64_apple_darwin = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-apple-darwin = None
  CXXFLAGS_x86_64_apple_darwin = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CXX_x86_64-apple-darwin = None
  CXX_x86_64_apple_darwin = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-apple-darwin = None
  CXXFLAGS_x86_64_apple_darwin = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CXX_x86_64-apple-darwin = None
  CXX_x86_64_apple_darwin = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-apple-darwin = None
  CXXFLAGS_x86_64_apple_darwin = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CXX_x86_64-apple-darwin = None
  CXX_x86_64_apple_darwin = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-apple-darwin = None
  CXXFLAGS_x86_64_apple_darwin = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CXX_x86_64-apple-darwin = None
  CXX_x86_64_apple_darwin = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-apple-darwin = None
  CXXFLAGS_x86_64_apple_darwin = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/db/blob/blob_file_addition.o" "-c" "rocksdb/db/blob/blob_file_addition.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/db/blob/blob_log_writer.o" "-c" "rocksdb/db/blob/blob_log_writer.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/db/blob/blob_log_format.o" "-c" "rocksdb/db/blob/blob_log_format.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/db/blob/blob_file_garbage.o" "-c" "rocksdb/db/blob/blob_file_garbage.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/db/builder.o" "-c" "rocksdb/db/builder.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/cache/cache.o" "-c" "rocksdb/cache/cache.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/db/arena_wrapped_db_iter.o" "-c" "rocksdb/db/arena_wrapped_db_iter.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/db/blob/blob_log_reader.o" "-c" "rocksdb/db/blob/blob_log_reader.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/cache/lru_cache.o" "-c" "rocksdb/cache/lru_cache.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/db/blob/blob_file_meta.o" "-c" "rocksdb/db/blob/blob_file_meta.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/cache/sharded_cache.o" "-c" "rocksdb/cache/sharded_cache.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/cache/clock_cache.o" "-c" "rocksdb/cache/clock_cache.cc"
 。。。。。。

  cargo:warning=using ::isunordered;
  cargo:warning=      ~~^
  cargo:warning=13 errors generated.
  exit code: 1
  cargo:warning=13 errors generated.
  exit code: 1
  cargo:warning=13 errors generated.
  exit code: 1
  cargo:warning=177 warnings and 13 errors generated.
  exit code: 1
  cargo:warning=13 errors generated.
  exit code: 1
  cargo:warning=13 errors generated.
  exit code: 1
  cargo:warning=13 errors generated.
  exit code: 1

  --- stderr

  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/houfa.zhou/dev/src/github.com/substrate-developer-hub/substrate-node-template/target/release/build/librocksdb-sys-9a985f5ad15d9840/out/rocksdb/cache/cache.o" "-c" "rocksdb/cache/cache.cc" with args "c++" did not execute successfully (status code exit code: 1).

warning: build failed, waiting for other jobs to finish...
error: build failed

detail log:
[err.log](https://github.com/paritytech/substrate/files/5528423/err.log)

**Comment by bkchr** [comment]
This is a rocksdb compilation error, not related to Substrate. It is only an external dependency. The best would be that you check that all dependencies are installed and if yes, go to the rust rocksdb github.
