### ISSUE TITLE
Parachain nodes halt block production/import at random

### ISSUE THREAD

**Issue by modbrin** [paritytech/substrate#7524]
Observing running local testnet with 2 fullnodes, 2 collators and 2 relay nodes, on long stand sessions without transactions, some nodes, in particular one of fullnodes at some point will keep same parachain block as best for a period of ~1h==~600blocks. At the same time other fullnode and collators maintain normal operation. For halted node transactions won't pass, just hanging until it eventually continues starting with importing network's best block.

Not sure if it's related but also node periodically encounters UnknownParent errors. Apart of that there are no errors near period of halt in logs.

Code is based on parachain template, rococo-branch for imports and relay node.

**Comment by bkchr** [comment]
Please post these issues in the Cumulus repo and not Substrate.

The old branch does not receive any fixes, please try latest master as with the other issue.
