### ISSUE TITLE
DoubleStorageMap No access to keys in iter_prefix_values() 

### ISSUE THREAD

**Issue by ondratra** [paritytech/substrate#7530]
When using `iter_prefix_values()` of `DoubleStorageMap` trait, there seems to be no way to retrieve `k2`. That creates a problem when iterating over prefix and wanting to change values in the storage.

I want to be able to achieve this:
```
decl_storage! {
    ...
    trait Store for Module<T: Trait> as MyModule {
        pub MyDoubleMap get(fn my_double_map) config(): double_map hasher(blake2_128_concat) MyKey1, hasher(blake2_128_concat) MyKey2 => MyValue;
    }
}

fn some_function_using_storage<T: Trait>(prefix: MyKey1) {
    let items = MyDoubleMap::<T>::iter_prefix_values(prefix);

    // this is the desired effect - in the current implementation `.next()` returns only `my_value`
    while let Some((my_key2, my_value)) = items.next() {
        MyDoubleMap::<T>::mutate(prefix, my_key2, |value| { ... })
    }
}
```

Is this feature something that can be added, or is there any obstacle? Is there any other way how to achieve walkthrough prefix's items and modify them? The iterator has access to the key, but its type is `Vec<u8>`, so I'm not sure if it can be converted back to `MyKey2`. https://crates.parity.io/src/frame_support/storage/mod.rs.html#445

EDIT: source code improved

**Comment by bkchr** [comment]
You are searching for this here: https://docs.rs/frame-support/2.0.0/frame_support/storage/trait.IterableStorageDoubleMap.html#tymethod.iter_prefix

**Comment by ondratra** [comment]
Thx! Missed that one.
