### ISSUE TITLE
contracts: Expose rent calculation parameters to contracts

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#7533]
In order for contracts to be able to implement mechanisms to [cope with rent payments](https://github.com/paritytech/ink/issues/539) they need access to the rent parameters:
https://github.com/paritytech/substrate/blob/02771e146f126a9759a62948ec8a2edd6ad47ee9/frame/contracts/src/lib.rs#L348-L365

Please note that the rent mechanism is subject to change soon:
#7529
#6596

**Comment by cmichi** [comment]
@athei It would be great if you could also add a Getter for the amount of storage used by the contract. With upcoming code rent it might make sense to distinguish between amount used for code and amount used for storage.
