### ISSUE TITLE
Authority-discovery: the first round of queries should be shorter than the others

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#7537]
At the moment we query all validators over a period of 10 minutes.

If I'm not mistaken, that means that in the first 10 minutes after a node restarts, it won't be able to connect to some validators.
This can be a problem if the node is a parachain collator.

I think it makes sense to shorten the time of the first ever period to, say, 1 minute, in order to make the network more robust to unexpected node restarts.

cc @mxinden

**Comment by mxinden** [comment]
Summarizing a discussion in Riot, the following algorithm should solve the issue of failing queries at startup:

When **publishing ones address** start off with a low interval (e.g. 2 seconds). When publishing fails, double the interval. When publishing succeeds fast forward the interval to the default (12h).

When **querying addresses** start of with a low interval (e.g. 2 seconds). Reset / Refill the pending query buffer each interval tick and double the interval until it is at the default (10 minutes). At all times enforce the [concurrent request limit](https://github.com/paritytech/substrate/blob/1c0f76b168345d1a42bb6a106d74d22d10ae2310/client/authority-discovery/src/worker.rs#L69).

In case this makes some configuration options obsolete, remove them.

**Comment by bkchr** [comment]
> When **publishing ones address** start off with a low interval (e.g. 2 seconds). When publishing fails, double the interval. When publishing succeeds fast forward the interval to the default (12h).

By succeed do you mean we don't get the `QuorumFailed` error? Or is a succeed already when we were able to publish it to one other node? 

Because if we do this until there is no `QuorumFailed` error, it means that on a local network we will probably never have this situation. 

While doing this, we probably also should make the `QuorumFailed` a `debug` message? WDYT?

**Comment by mxinden** [comment]
> By succeed do you mean we don't get the QuorumFailed error?

Correct.

> Because if we do this until there is no QuorumFailed error, it means that on a local network we will probably never have this situation.

I don't see a problem with never having this situation. In case publishing ones address always returns `QuorumFailed` the publishing interval will converge towards 12h eventually. Am I missing an issue with this approach?

**Comment by bkchr** [comment]
No everything fine, I just wanted to point this out :) I was not sure how much this maybe would "spam" the nodes of the local network.
