### ISSUE TITLE
Add remove_proxies API for pallet-proxies

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7557]
Add a pub API to remove all the proxies so other pallets can call this.

https://github.com/paritytech/substrate/blob/69198d1e5735798c8baa1921c6e2091c93260752/frame/proxy/src/lib.rs#L306-L310

**Comment by Doordashcon** [comment]
Is this still needed to be worked on?

**Comment by vjgaur** [comment]
I want to take up this as my first substrate issue. Would you please mind explaining a little on this issue for me to get started ?

**Comment by xlc** [comment]
Verify similar to `remove_proxy`

https://github.com/paritytech/substrate/blob/69198d1e5735798c8baa1921c6e2091c93260752/frame/proxy/src/lib.rs#L286-L293

Add new method `pub remove_all_proxy_delegates`, move the logic there, call this method from `remove_proxies`.

**Comment by vjgaur** [comment]
Ok cool

**Comment by vjgaur** [comment]
Hi please find my PR. I am unable to add a reviewer
