### ISSUE TITLE
Transaction Status Future

### ISSUE THREAD

**Issue by Gauthamastro** [paritytech/substrate#7581]
I am trying to send a lot of transactions to a substrate node. I am using the following code.

```
const nonce = await api.rpc.system.accountNextIndex(sender);
for (let i = 0; i < 10; i++) {
  // send, just retrieving the hash, not waiting on status
  api.tx.balances.transfer(recipient, 123).signAndSend(sender, { nonce });
  nonce = nonce +1;
}
```

The transaction is valid. But after some time, the status returned by transactions is Future. Is there any way to include transactions even though slowly instead of returning Future?

What should I tweak to achieve this?

**Comment by shawntabrizi** [comment]
You should use this tool which was created by @NikVolf and has been used to benchmark Substrate in the past:

https://github.com/NikVolf/sub-flood
