### ISSUE TITLE
[CI] master pipeline is failing

### ISSUE THREAD

**Issue by s3krit** [paritytech/substrate#7584]
`cargo-deny` and `unleash-check` are failing in Substrate's CI. This has the knock-on effect of the rust docs not being generated and uploaded to crates.parity.io (since some prior jobs failed).

In order to resolve rust-docs not being built, we could make the `build-rust-doc` job require a previous job directly like we do for `build-linux-substrate` [here](https://github.com/paritytech/substrate/blob/master/.gitlab-ci.yml#L412), but we should also fix the two failing jobs.

For `cargo-deny` it appears it is related to a licensing issue. See the snippet from the job's log below. Probably just need to add that license explicitly to `.maintain/deny.toml` if it's compatible - maybe check with Kirill.

```
error[L001]: failed to satisfy license requirements
  ┌─ minicbor-derive 0.6.0 (registry+https://github.com/rust-lang/crates.io-index):4:12
  │
4 │ license = "BlueOak-1.0.0"
  │            ^^^^^^^^^^^^^
  │            │
  │            license expression retrieved via Cargo.toml `license`
  │            rejected: not explicitly allowed

```

For `unleash-check`, I'm not sure. Perhaps @gnunicorn might know. Failed job log [here](https://gitlab.parity.io/parity/substrate/-/jobs/722053), snippet below:

```
error[E0432]: unresolved imports `sp_core::traits::RuntimeSpawnExt`, `sp_core::traits::RuntimeSpawn`
  --> src/async_externalities.rs:24:55
   |
24 |     traits::{Externalities, SpawnNamed, TaskExecutorExt, RuntimeSpawnExt, RuntimeSpawn},
   |                                                          ^^^^^^^^^^^^^^^  ^^^^^^^^^^^^ no `RuntimeSpawn` in `traits`
   |                                                          |
   |                                                          no `RuntimeSpawnExt` in `traits`
```

**Comment by TriplEight** [comment]
> In order to resolve rust-docs not being built, we could make the `build-rust-doc` job require a previous job directly

yeah, it makes sense depend `build-rust-doc` from `test-linux-stable`. But for [`publish-s3-doc`](https://github.com/paritytech/substrate/blob/68a058cdc315217d87b381b539d38d3cf24e9896/.gitlab-ci.yml#L678) then it makes sense to add the dependency from the `build-linux-substrate` as well.
That will make a logical chain "if the test is OK and the binaries are built, we publish the docs". Regardless of the `cargo deny` or `unleash`. HDYT?

> but we should also fix the two failing jobs.

Talked w @kirushik , he suggests avoiding [this crate](https://crates.io/crates/minicbor-derive). So we can't allow this license. @romanb maybe you have a good idea on how to get rid of `minicbor`?

**Comment by TriplEight** [comment]
Done the first part in https://github.com/paritytech/substrate/pull/7591

**Comment by TriplEight** [comment]
cc https://github.com/paritytech/ci_cd/issues/102

**Comment by Xanewok** [comment]
`unleash-check` has been fixed (#9129) but `publish-s3-doc` still failed in https://gitlab.parity.io/parity/substrate/-/jobs/1009988.

It now depends on
- `build-rust-doc` and
- `build-linux-substrate`

both of which are were green in the pipeline containing the failed doc publish job (https://gitlab.parity.io/parity/substrate/-/pipelines/146797).

@s3krit @TriplEight Do you have any idea what might be causing this?

**Comment by TriplEight** [comment]
@Xanewok gitlab [says](https://gitlab.parity.io/parity/substrate/-/jobs/1013918#L26) `warning: Skipping file /builds/parity/substrate/crate-docs/.lock. File/Directory is not readable.` as a last line of the `script:` and runs `after_script:` right after, this means it's likely the thing that caused the error. (`after_script:` runs regardless)

**Comment by TriplEight** [comment]
Docs publishing fixed in https://github.com/paritytech/substrate/pull/9341
