### ISSUE TITLE
Blake2-256 or 512 ?

### ISSUE THREAD

**Issue by bruce1ee** [paritytech/substrate#7585]
I have a question about Address Encoding. Wiki shows that the checksum uses Blake2-256 algorithm, while polkadot-js is using Blake2-512. So, is the wiki wrong?

![image](https://user-images.githubusercontent.com/73994934/100040486-5a249c00-2e42-11eb-9772-bf983690e589.png)

![image](https://user-images.githubusercontent.com/73994934/100040479-56911500-2e42-11eb-8d58-d0902c127ca1.png)

https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58)#checksum-types

https://github.com/polkadot-js/common/blob/f07d66562b09e4ddb8ec31f51f354d1c07d44212/packages/util-crypto/src/address/sshash.ts

**Comment by jacogr** [comment]
64 byte output (512 bits), also see https://github.com/paritytech/substrate/blob/master/primitives/core/src/crypto.rs#L305

**Comment by bruce1ee** [comment]
@jacogr So is the document page required to be corrected?

**Comment by bkchr** [comment]
No, as @jacogr it is the length of the output!
