### ISSUE TITLE
Possible reentrancy issues with hooks in mutate closure

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#7605]
Substrate have some hooks invocation inside `mutate` calls, this means there will be pending changes in stack which are not accessible by hooks. When hook attempting to read or modify the same values, a lost update will happen.

This could trigger some security issue if the implementer of the hooks did not know this constraint.

One example is the `DustRemoval` hook on pallet-balances

https://github.com/paritytech/substrate/blob/cff25fbc37c9fc564f8816eefdcd8dce15e1606b/frame/balances/src/lib.rs#L207

It is called in `post_mutation`

https://github.com/paritytech/substrate/blob/cff25fbc37c9fc564f8816eefdcd8dce15e1606b/frame/balances/src/lib.rs#L604-L611

which is called in `try_mutate_exists`

https://github.com/paritytech/substrate/blob/cff25fbc37c9fc564f8816eefdcd8dce15e1606b/frame/balances/src/lib.rs#L645-L654

So the `DustRemoval` cannot do any modification to the `maybe_account` or lost update will happen.

**Comment by kianenigma** [comment]
I read a bit about the previous reentrancy issues in ETH but still can't figure out what you exactly mean by "lost update". Can you elaborate on the scenario above and point out what exactly can go wrong, under which conditions?

**Comment by xlc** [comment]
Here is a demo https://github.com/paritytech/substrate/blob/0fe33f078cd5242376e575136d0fd2d21d5627c9/frame/balances/src/tests_reentrancy.rs

All the dust should go to account `1`, which is a typical usage if `1` is a treasury account.

https://github.com/paritytech/substrate/blob/0fe33f078cd5242376e575136d0fd2d21d5627c9/frame/balances/src/tests_reentrancy.rs#L101-L105

This is a working normal case, 50 dust goes to `1`

https://github.com/paritytech/substrate/blob/0fe33f078cd5242376e575136d0fd2d21d5627c9/frame/balances/src/tests_reentrancy.rs#L159-L164

This is a lost update case

https://github.com/paritytech/substrate/blob/0fe33f078cd5242376e575136d0fd2d21d5627c9/frame/balances/src/tests_reentrancy.rs#L174-L178

The transfer send 450 to account `1` and dust removal send another 50 to `1`. But because the 450 write happen after the 50 write, so 50 disappears.

**Comment by shamb0** [comment]
Hello @xlc/@kianenigma/Shawn,

Tried first level of analysis,

Observed recursive call at "fn try_mutate_account()" in "fn transfer()" execution sequence.

Looks like local stack object "AccountData" is not in-sync with DB.

Below snapshot captures status of "AccountData" in "fn try_mutate_account()"

![](https://i.imgur.com/ECMu2Qw.png)

So recursive is comming into picture during Dust removal.

As part of initial analysis, tried to do "fn transfer()" without any recursive. to make test function "fn has_reentrancy_issue()" to work.

Plz find draft version in the link https://github.com/paritytech/substrate/pull/7783

Looking for some input on, howto make local object "AccountData" in-sync with DB, under recursive call context.
