### ISSUE TITLE
Error: Attempted to send notification on unknown protocol: "/paritytech/grandpa/1"

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#7629]
This line is being printed occasionally on our nodes.

https://github.com/paritytech/substrate/blob/8febf11a1ab7870c5284ae06951045c5d450cac2/client%2Fnetwork%2Fsrc%2Fservice.rs#L637

**Comment by xlc** [comment]
I am seeing this on my Polkadot node as well.

**Comment by tomaka** [comment]
Will most likely be fixed by #7374
