### ISSUE TITLE
Running test case fails by calling http_request_start of sp_io 2.0.0

### ISSUE THREAD

**Issue by h4n0** [paritytech/substrate#7645]
I implemented http request based feature in offchain worker with sp-io 2.0.0. I added test case for this function to check if the http response is as expected. However, the test case failed with the following error message:

`thread 'tests::test_fetch_balances' panicked at '`http_request_start_version_1` called outside of an Externalities-provided environment.', /home/han/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-io-2.0.0/src/lib.rs:877:5`

I checked the source and found that http_request_start function has an `.expect("http_request_start can be called only in the offchain worker context")`

I can understand that the offchian worker related function shall not be called directly outside, but if I just want to have some test cases running locally, how could I bypass this error?

**Comment by bkchr** [comment]
Run your inside:
```
sp_io::TestExternalities::default().execute_with(|| {});
``

**Comment by hanqo** [comment]
thanks for the quick reply. Just tried simply to make my function call wrapped by this syntax and it still failed. 
But it's a good hint and I will read the doc of sp_io::TestExternalities first.

**Comment by hanqo** [comment]
Hi @bkchr 
After digging into the sp io source code further and it seems that it's getting more and more complicated. With your solution it has still the same panic but slightly a bit more progress. The progress is that, it runs till 888 line of sp-io-2.0.0/src/lib.rs instead of 877 from last run. Any other suggestions?

**Comment by bkchr** [comment]
Ahh yeah sorry!

https://github.com/paritytech/substrate/blob/master/primitives/runtime/src/offchain/http.rs#L527-L563

Check here on how to use the offchain stuff in tests
