### ISSUE TITLE
Benchmark template should be given quality and confidence information

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#7648]
The benchmark analysis includes some quality and confidences value for the min square analysis.

I think, considering that weight generation is automated and nobody looks at curves anymore, it could be important to have more information on the curve and linear regression.

Giving the already computed quality and confidences value for the min square analysis would be an improvment, I would also be in favor of putting this value in comment in the template.hbs.

cc @shawntabrizi

**Comment by shawntabrizi** [comment]
no problem
