### ISSUE TITLE
Migrate elections-phragmen module storage to proper prefix

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#7657]
Currently, the module's data is stored under prefix `PhragmenElection`, while the version is stored under `ElectionsPhragmen`. This is also changing with #5678, and will be just additional confusion everywhere to maintain. Move all to a unified prefix.

**Comment by thiolliere** [comment]
This is currently the case with a lot of pallets.

storage version is stored using `PalletInfo::name<pallet::Module<..>>()` and storages are stored after a fixed prefix declared in decl_storage and instances.

All this will be solved by macro attribute as storages will use `PalletInfo::name<pallet::Module<..>>()` similarly to stored version.

**Comment by bkchr** [comment]
Yeah, I don't see the reason for this issue?

This is nothing that can be changed from the pallet itself.

**Comment by kianenigma** [comment]
Indeed, if we move the macro attribute then they will be unified and fixed. 

I am not sure if it is noted somewhere: This can cause some migrations to happen by migrating to to attribute macros, which should not be overlooked.

**Comment by thiolliere** [comment]
> This can cause some migrations to happen by migrating to to attribute macros, which should not be overlooked.

Yes I wrote it in the upgrade guidelines https://thiolliere.github.io/doc/frame_support/attr.pallet.html#checking-upgrade-guidelines
