### ISSUE TITLE
Maybe a code flaw to lose treasury tip reasons

### ISSUE THREAD

**Issue by wliyongfeng** [paritytech/substrate#7667]
Currently when we propose a tip, the reasons are stored under `Reasons` storage. Code is [here](https://github.com/paritytech/substrate/blob/master/frame/treasury/src/lib.rs#L356).

```rust
/// Simple preimage lookup from the reason's hash to the original data. Again, has an
/// insecure enumerable hash since the key is guaranteed to be the result of a secure hash.
pub Reasons get(fn reasons): map hasher(identity) T::Hash => Option<Vec<u8>>;
```

When we call `tip_new`, reasons are inserted while key is the hash and value is the `Vec<u8>` reasons. 
Then when we call `close_tip`, reasons are removed by the hash key.

The problems is what if there are 2 tips(A, B) with same reasons? When I close A, do I lose the reasons of B?
I know there is a low possibility that 2 tips exist at same time with same reasons. But if the code acts like my worry, I think it's a code flaw.

**Comment by thiolliere** [comment]
Yes but code checks for it:

in `tip_new` if the reason is used already, otherwise we fail with `AlreadyKnown`.
```
		fn tip_new(origin, reason: Vec<u8>, who: T::AccountId, #[compact] tip_value: BalanceOf<T, I>) {
			let tipper = ensure_signed(origin)?;
			ensure!(T::Tippers::contains(&tipper), BadOrigin);
			let reason_hash = T::Hashing::hash(&reason[..]);
			ensure!(!Reasons::<T, I>::contains_key(&reason_hash), Error::<T, I>::AlreadyKnown);
```
(and `T::Hashing` is secure hash).

Thus it shouldn't be possible to have ` 2 tips(A, B) with same reasons`.

**Comment by wliyongfeng** [comment]
Oh, cool, thanks.
