### ISSUE TITLE
Allow querying the fee details from transaction payment

### ISSUE THREAD

**Issue by liuchengxu** [paritytech/substrate#7691]
Currently, the `compute_fee()` of transaction payment only exposes the value of the final total fee, we can add a new API like `compute_fee_details()` that returns the details of the final fee. ChainX now uses a workaround [transaction-fee pallet](https://github.com/chainx-org/ChainX/blob/8b3dce1fac/xpallets/transaction-fee/src/lib.rs#L63) for this purpose but has to copy-and-paste partial transaction-payment code. If transaction-payment can have the built-in fee details support, we could avoid the copy-and-paste.

**Comment by shawntabrizi** [comment]
@liuchengxu do you plan to make a PR for this? Pretty sure we would happily accept one.

**Comment by liuchengxu** [comment]
Thanks @shawntabrizi , will surely send a PR.

**Comment by liuchengxu** [comment]
Hi @shawntabrizi can you have a look at this https://github.com/paritytech/substrate/pull/7692?
