### ISSUE TITLE
Support multiple keys in rpc.state_getStorage

### ISSUE THREAD

**Issue by ianhe8x** [paritytech/substrate#7705]
For some reason state_subscribeStorage supports it but state_getStorage not. And it cause an inconvenience that `@polkadot/api` has to use `state_subscribeStorage` then unsubscribe for a one shot multi-key query. 

It is also not friendly for http provider since subscribe like rpc calls are not supported over http.

**Comment by shawntabrizi** [comment]
@ianhe8x you should look at the other available RPCs.

This seems to do what you want: https://polkadot.js.org/docs/substrate/rpc/#querystorageatkeys-vecstoragekey-at-blockhash-vecstoragechangeset

**Comment by ianhe8x** [comment]
Thanks for pointing out the direction.
