### ISSUE TITLE
Panic when build raw chainspec json file

### ISSUE THREAD

**Issue by tolak** [paritytech/substrate#7713]
Hi, got following error when build raw chain spec from a original chainspec json file.

## Error
```sh
Thread 'main' panicked at 'Genesis member does not have enough balance to be a candidate: DispatchError::Module { index: 6, error: 1, message: Some("LiquidityRestrictions") }', /Users/wwf/workspace/RustProjects/tolak-chain/substrate/frame/elections-phragmen/src/lib.rs:237
```
## Steps i had done

```sh
./target/release/tolak-node build-spec --disable-default-bootnode --chain local > chainspec/calla.json
```

do some changes, then build raw chainsjpec

```sh
./target/release/tolak-node build-spec --chain=./chainspec/calla.json --raw --disable-default-bootnode > ./chainspec/calla-raw.json
```
Then error was comming, **but the balance of the memebers actually enough**.

## Dev environment

 - substrate2.0
 - nightly-2020-10-06-x86_64-apple-darwin (default)
 - rustc 1.49.0-nightly (a1dfd2490 2020-10-05)

## Others

At the end of the Output, i got

```sh
This is a bug. Please report it at:

        https://github.com/paritytech/substrate/issues/new
```
So i create this issue.

The chainspec i use also can be found [here](https://github.com/tolak/tolak-chain/blob/master/chainspec/calla.json)

**Comment by bkchr** [comment]
Can you reproduce this on substrate please?

However it looks like you just have misconfigured the genesis config.

**Comment by tolak** [comment]
May i ask how to reproduce this on substrate? Test code you mean?

**Comment by bkchr** [comment]
The point is this message:
`Genesis member does not have enough balance to be a candidate`.

Which means that your genesis configuration is wrong. Do you searched for this message in Substrate?

**Comment by tolak** [comment]
Yap, i did read that snip of code, and checked the balance of the account. It's enough i think.
pallet-balance config:

```sh
      "palletBalances": {
        "balances": [
          [
            "5Gmb57XQPTfshhCuQZUDUxS5iWXj8vjTYPL6EyYG7cjKM4GK",
            1000000000000000000000
          ],
```

pallet-electioon-phragmen config:

```sh
      "palletElectionsPhragmen": {
        "members": [
          [
            "5Gmb57XQPTfshhCuQZUDUxS5iWXj8vjTYPL6EyYG7cjKM4GK",
            10000000000000000
          ],
```

**Comment by bkchr** [comment]
Cc @kianenigma

**Comment by kianenigma** [comment]
What is the CandidacyBond of the chain? This is configured in the runtime. The error is because this value is failing to get reserved. Also, this behavior will change soon, see [this](https://github.com/paritytech/substrate/pull/7040#discussion_r532159519) discussion.

**Comment by tolak** [comment]
The parameter was set as follow in runtime:

```sh
	pub const CandidacyBond: Balance = 10 * DOLLARS;
```
I didn't change those parameters, they all copy from [here](https://github.com/paritytech/substrate/blob/533bbbd2315d55906a6dac5726a722e094656d52/bin/node/runtime/src/lib.rs#L578)

**Comment by kianenigma** [comment]
Yeah the issue is that the same accounts are used in staking as well, therefore they will have some balance locked in there as well. If you remove `stakers` (or just assign different accounts) then the chain spec will build. 

- @gnunicorn this is a good candidate to be patched and released to crates.io before the next release. Possible to do that? 

- @TriplEight would be nice to have have a CI job maybe that build the `local` and `development` chain's chain-spec with all the default parameters? This simple test could have detected this issue. Such inter-pallet relations are not visible within unit tests sadly.

**Comment by tolak** [comment]
I let the **stakers** empty, and YES, building passed. But i still have doubt that initial balance of the account is 1000000000000000000000, and locked balance for staking is 10000000000000000, looks like still have enough amount to be a candidate. Actually even i increase initial balance to 10 times, still failed with same error.

**Comment by bkchr** [comment]
> * @TriplEight would be nice to have have a CI job maybe that build the `local` and `development` chain's chain-spec with all the default parameters? This simple test could have detected this issue. Such inter-pallet relations are not visible within unit tests sadly.

@kianenigma what you mean by this? Just call build-spec? Why isn't that just added as a rust test that initializes the genesis config and checks that this does not panic?

**Comment by shawntabrizi** [comment]
@kianenigma this is why I think genesis members should not have their balances manipulated... these kinds of things can be confusing and can force users to do certain things they wouldnt want to, for example needing to give users extra balance than they want in genesis.

**Comment by kianenigma** [comment]
> I let the **stakers** empty, and YES, building passed. But i still have doubt that initial balance of the account is 1000000000000000000000, and locked balance for staking is 10000000000000000, looks like still have enough amount to be a candidate. Actually even i increase initial balance to 10 times, still failed with same error.

You also have duplicate keys in your balances keys. For example, `5Gmb57XQPTfshhCuQZUDUxS5iWXj8vjTYPL6EyYG7cjKM4GK` is defined twice and the second time it has way less balance and this value is less than something that can cover both the cost of being a council member and a staker.

**Comment by kianenigma** [comment]
> > * @TriplEight would be nice to have have a CI job maybe that build the `local` and `development` chain's chain-spec with all the default parameters? This simple test could have detected this issue. Such inter-pallet relations are not visible within unit tests sadly.
> 
> @kianenigma what you mean by this? Just call build-spec? Why isn't that just added as a rust test that initializes the genesis config and checks that this does not panic?

Ahh but we already have this. I thought this issue can happen with one of the default chain-specs, but it seems to be specific to the user.

**Comment by tolak** [comment]
> > I let the **stakers** empty, and YES, building passed. But i still have doubt that initial balance of the account is 1000000000000000000000, and locked balance for staking is 10000000000000000, looks like still have enough amount to be a candidate. Actually even i increase initial balance to 10 times, still failed with same error.
> 
> You also have duplicate keys in your balances keys. For example, `5Gmb57XQPTfshhCuQZUDUxS5iWXj8vjTYPL6EyYG7cjKM4GK` is defined twice and the second time it has way less balance and this value is less than something that can cover both the cost of being a council member and a staker.

Actually i had noticed this difference when the first time i got building failied, almost same error happed in session pallet config. One thing more important is that when i exported chainspec json from "local" chainspec(give **--local**), the pallet balance config already contains doubt balance initialization, then i doubt init the banalce in my custom chainspec json file, it solved that error. That's why i think double initiation is a **SHOULD BE**. But seems it's not.

I build spec with this:

```sh
./target/release/tolak-node build-spec --disable-default-bootnode --chain local > customSpec.json
```

And full banalce config in customSpec.json is:

```sh
      "palletBalances": {
        "balances": [
          [
            "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
            1000000000000000000000
          ],
          [
            "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
            1000000000000000000000
          ],
          [
            "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y",
            1000000000000000000000
          ],
          [
            "5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy",
            1000000000000000000000
          ],
          [
            "5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw",
            1000000000000000000000
          ],
          [
            "5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL",
            1000000000000000000000
          ],
          [
            "5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY",
            1000000000000000000000
          ],
          [
            "5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc",
            1000000000000000000000
          ],
          [
            "5Ck5SLSHYac6WFt5UZRSsdJjwmpSZq85fd5TRNAdZQVzEAPT",
            1000000000000000000000
          ],
          [
            "5HKPmK9GYtE1PSLsS1qiYU9xQ9Si1NcEhdeCq9sw5bqu4ns8",
            1000000000000000000000
          ],
          [
            "5FCfAonRZgTFrTd9HREEyeJjDpT397KMzizE6T3DvebLFE7n",
            1000000000000000000000
          ],
          [
            "5CRmqmsiNFExV6VbdmPJViVxrWmkaXXvBrSX8oqBT8R9vmWk",
            1000000000000000000000
          ],
          [
            "5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY",
            10000000000000000
          ],
          [
            "5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc",
            10000000000000000
          ]
        ]
    }
```

**Comment by kianenigma** [comment]
yeah this duplicate stuff is a bit annoying, will be an easy fix though.

**Comment by kianenigma** [comment]
Given #7725 and #7040, unless if you object @tolak, I think we can close.

**Comment by tolak** [comment]
Yeah, thanks for the help, pls close it.
