### ISSUE TITLE
macro decl_storage! not support list 

### ISSUE THREAD

**Issue by JKingdom** [paritytech/substrate#772]
Hi:
In `storage_items`(seem old version)
It support List like
```
storage_items! {
	Value: b"a" => u32;
	List: b"b:" => list [u64];
	Map: b"c:" => map [u32 => [u8; 32]];
}
```
but in `decl_storage!` it not support list yet!
```
#[macro_export]
#[doc(hidden)]
macro_rules! __decl_storage_items {
	// simple values
	($cratename:ident $traittype:ident $traitinstance:ident $(#[$doc:meta])* $name:ident : $ty:ty; $($t:tt)*) => {
		__decl_storage_item!(() ($traittype as $traitinstance) () (OPTION_TYPE Option<$ty>) (get) (take) $cratename $name: $ty);
		__decl_storage_items!($cratename $traittype $traitinstance $($t)*);
	};
        // ...
        // maps
	($cratename:ident $traittype:ident $traitinstance:ident $(#[$doc:meta])* $name:ident : map [$kty:ty => $ty:ty]; $($t:tt)*) => {
		__decl_storage_item!(() ($traittype as $traitinstance) () (OPTION_TYPE Option<$ty>) (get) (take) $cratename $name: map [$kty => $ty]);
		__decl_storage_items!($cratename $traittype $traitinstance $($t)*);
	};
	// ...
        // no list !
	// exit
	($cratename:ident $traittype:ident $traitinstance:ident) => ()
}
```
hope to support it!

**Comment by JKingdom** [comment]
It seems to use Vec directly

**Comment by JKingdom** [comment]
emmm 
yes I can use this Vec like:
```rust
decl_storage!{
pub List get(list): default Vec<Symbol>;
}
```
but when I use it
```rust
let mut list = <List<T>>::get();
list.push(xxx);
<List<T>>::set(list);
``` 
due to the MPT(would state), every modify would be stored, but under this type, it would store the whole list every time.

in the old version, the list is provided, So I hope to provide the list that do not store the all value just the modified part.
ps: the map could not instead of list, because the list could known the length to iterate but map couldn't.

**Comment by gavofyork** [comment]
You can easily use a `map [ u32 => Symbol ]` and a `u32` (count) in order to simulate a list. It was removed because huge lists that are expected to be enumerated are problematic in general anyway since iteration would incur huge numbers of database queries, which are much more costly than one large element and thus better served as `Vec<Symbol>`.

**Comment by JKingdom** [comment]
Ok, thank you very mush!
