### ISSUE TITLE
Idea: Replace protocolId with the genesis hash

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#7746]
At the moment, most networking protocols contain what is called the `protocolId`, defined in the chain specs.
For example, the syncing protocol of Polkadot is named `/dot/sync/2`, because Polkadot has `protocolId: "dot"` in its chain specs.

Instead of using a user-chosen `protocolId`, we could name the protocol using the hash of the genesis block.
The sync protocol could for example become `/91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3/sync/2`.

The advantage of doing so is that things become "automatic". No need to define your own `protocolId` anymore, and no need to verify whether the genesis hash is the same between two nodes during the blocks announce handshake.

The drawback is obviously that this is longer than just `dot`, so more bytes are transmitted on the network. The `multistream-select` protocol requires protocol names to be string.
To mitigate this, we could use an encoding other than hex encoding of the hash. Using a different encoding might however make things confusing.

This also depends on how we tackle #7458. After #7458, the definition of "genesis block" might become a bit blurry.

**Comment by tomaka** [comment]
Depends on https://github.com/paritytech/substrate/issues/6605

**Comment by tomaka** [comment]
Some remark: using just the genesis hash would make it impossible to do a hard fork.
We should use the combination of the genesis hash *and* some optional value found in the chain specs.

Adding an extra field also makes it flexible enough to not run into an issue if a chain transitions from standalone to parachain.

**Comment by tomaka** [comment]
Issue still relevant and important.

**Comment by acatangiu** [comment]
At the network level, when looking at scale wouldn't it be expensive to string match against such a long protocol id?

Would `protocolId` + `truncatedGenesisHash` like `/dot/91b171bb1/sync/2` also work?

**Comment by tomaka** [comment]
There's no need to truncate. We don't care about the performance of comparing strings of 50 bytes.

**Comment by acatangiu** [comment]
Done in https://github.com/paritytech/substrate/pull/10463

**Comment by tomaka** [comment]
This was done for Grandpa/Beefy, but not for the syncing and transactions protocols.

**Comment by tomaka** [comment]
One last thing to do is change the Kademlia protocol name: https://github.com/paritytech/substrate/blob/c76c40ac94c1e66c38af6fcf2dba18e401b125b9/client/network/src/discovery.rs#L202

Unfortunately, this is maybe more complicated, because libp2p doesn't allow setting backwards compatible names for this protocol.

**Comment by bkchr** [comment]
> One last thing to do is change the Kademlia protocol name: https://github.com/paritytech/substrate/blob/c76c40ac94c1e66c38af6fcf2dba18e401b125b9/client/network/src/discovery.rs#L202
> 
> Unfortunately, this is maybe more complicated, because libp2p doesn't allow setting backwards compatible names for this protocol.

@dmitry-markin could you check with upstream if adding support for backwards compatible names would be accepted? If yes, could you please do this.

**Comment by dmitry-markin** [comment]
> @dmitry-markin could you check with upstream if adding support for backwards compatible names would be accepted? If yes, could you please do this.

Done in https://github.com/libp2p/rust-libp2p/pull/2846.

**Comment by bkchr** [comment]
> > @dmitry-markin could you check with upstream if adding support for backwards compatible names would be accepted? If yes, could you please do this.
> 
> Done in [libp2p/rust-libp2p#2846](https://github.com/libp2p/rust-libp2p/pull/2846).

Nice! So we will be able to close this with the next libp2p update.

**Comment by mxinden** [comment]
> with the next libp2p update

For the protocol: https://github.com/libp2p/rust-libp2p/pull/2869

**Comment by bkchr** [comment]
@dmitry-markin please keep track on this and when it is released, please update libp2p. :)
