### ISSUE TITLE
Consider using types that ensure ordering in elections-phragmen

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#7748]
As per noted here, after a number of bugs that were caused because of broken assumptions about the ordering of runners-up, it is worthy to consider using types that ensure order (i.e. `SortedVec`), at the cost of a bit less performance, to ensure veracity.

See the discussion here for more. https://github.com/paritytech/substrate/pull/7384#issuecomment-745546319

**Comment by xlc** [comment]
There are many other places should also use `SortedVec` such as the balances lock

**Comment by shawntabrizi** [comment]
Could also use a type for vec of maximum length, for things like strings, or other weight limit related stuff.
