### ISSUE TITLE
payment_queryInfo for setCodeWithoutChecks makes WebSocket close

### ISSUE THREAD

**Issue by KalitaAlexey** [paritytech/substrate#7758]
I try Runtime Upgrade with sudo setCodeWithoutChecks and the moment I press "Submit Transaction" it opens a dialog with "Sign and Submit". My browser gets irresponsible for 3 seconds. I observe the network tab in developer tools and I see that the previous WebSocket connection is closed after sending payment_queryInfo whose size is 2.5Mb (while my binary is 1.3MB). I see another WebSocket is open and being used, but once I press "Sign and Submit" the page is reloaded because "there is no connection to node".
In logs I see Max fragments exceeded (#6712)
Also, it's worth to mention that it happens in one setup, but it's fine in the other (the difference is negligible).
EDIT: The problem happens on a globally available test net and doesn't happen if the same test net is started locally due to how sockets work.

It seems it fails after receiving 960KB.
My browser sends fragments of 4Kb and jsonrpc-ws-server is configured to accept at max 240 fragments. That was  the cause. I had to fork the repository and made a change. fragments_capacity = max(1, max_payload_bytes / 4096)

**Comment by kianenigma** [comment]
seems like the issue belongs primarily in `jsonrpc-ws-server `?

**Comment by KalitaAlexey** [comment]
Yes.s

**Comment by bkchr** [comment]
This reads exactly as the linked #6712. So, why do we need a new issue for this?

**Comment by KalitaAlexey** [comment]
The scenario is different. The error happens before setCode is executed.

**Comment by bkchr** [comment]
No, in the other issue `setCode` also wasn't executed. In your case here the same happens, we send data over RPC to the node and it does not accept the huge RPC request.

(To calculate the fees, it needs to send the full transaction)

**Comment by KalitaAlexey** [comment]
Okay. You may be right.

**Comment by KalitaAlexey** [comment]
Does Runtime Upgrade work for everyone else?

**Comment by bkchr** [comment]
We never had problems with runtime upgrades. I also have send transactions with more than 4MiB recently.
