### ISSUE TITLE
[Feature request] Delete last X blocks

### ISSUE THREAD

**Issue by Swader** [paritytech/substrate#7760]
A chain sync can sometimes be interrupted illegally, which tends to corrupt the database. This will make further syncing impossible and would require a backup restoration or full resync. It would be ideal to be able to discard the last X blocks and resume syncing from there with some kind of `prunelast [numblocks]` command.

**Comment by bkchr** [comment]
If the database is corrupt, it will very likely fail on opening. There isn't anything we can do.

And we already have the `revert` sub-command. 

I don't see anything else we can do for this issue. So, I will close it.

**Comment by Swader** [comment]
I forgot that `revert` was a thing, thanks!
