### ISSUE TITLE
Very slow compilation of substrate-browser-utils

### ISSUE THREAD

**Issue by TriplEight** [paritytech/substrate#7765]
I've noticed that Compiling substrate-browser-utils v0.8.0 takes ages on my machine and some not very powerful servers, it maybe even hangs somewhere in the process.

Compiling seems to hang forever.
The command is 
```
cargo +nightly build --manifest-path=bin/node/cli/Cargo.toml --no-default-features --features browser --target=wasm32-unknown-unknown -Z features=itarget
```

@bkchr 's guess that it's rust-lang/rust#75992 regression

I went through
```
production:
rustc 1.50.0-nightly (825637983 2020-11-18) # image docker.io/paritytech/ci-linux:production
rustc 1.50.0-nightly (eb4fc71dc 2020-12-17)
rustc 1.50.0-nightly (803c60218 2020-12-13)
rustc 1.50.0-nightly (d32c320d7 2020-12-10)
2020-12-01
2020-11-25 (24)
2020-11-25 (21)
2020-11-19
2020-11-18

docker.io/paritytech/ci-linux:d0f2b553-20201118
docker.io/paritytech/ci-linux:3ec7097e-20201117
docker.io/paritytech/ci-linux:3ec7097e-20201116
docker.io/paritytech/ci-linux:4cc65dc0-20201102
docker.io/paritytech/ci-linux:974ba3ac-20201001
```

It freezes on
```
   Compiling substrate-browser-utils v0.8.0 (/builds/utils/browser)
    Building [=======================> ] 647/652: node-runtime(build)
```

But beefy CI machines, however, run [this test](https://gitlab.parity.io/parity/substrate/-/jobs/752533) on production image quite fast.

_Originally posted by @TriplEight in https://github.com/paritytech/substrate/issues/7722_

**Comment by bkchr** [comment]
This crate was removed.
