### ISSUE TITLE
Performance gap between native and wasm

### ISSUE THREAD

**Issue by MyronFanQiu** [paritytech/substrate#7779]
I wrote a benchmark for our chain and the execution time and weight gap between native exectuion and wasm execution mod is huge. The execution time in wasm mode is 1000 times than that in native mode. Is it correct behavior? Is there any best practice to increase the execution time in wasm?

**Comment by shawntabrizi** [comment]
@MyronFanQiu which wasm execution mode were you using?

We do our benchmarking using `--wasm-execution=compiled` which uses wasm-time, and I think the results are not as extreme as you mention. If you are using wasmi instead, which is default, then yeah, I think about 1000x slowdown is expected.

**Comment by burdges** [comment]
As I understand it, browsers have techniques to pass pointers across the wasm boundary between JS and WASM, which requires some care but works, while we semi-serialize everything.  We'll gradually do more and more calls between WASM blobs and to native, so this will become more of an issue, although not sure it'll even be that problematic.

**Comment by MyronFanQiu** [comment]
@shawntabrizi You're correct! I'm not fully understand the difference between `compiled` and `interpreted` right now. I may need to dig into it deeply.

**Comment by MyronFanQiu** [comment]
close this issue right now.
