### ISSUE TITLE
What is the function check_equal in executive.final_checks?

### ISSUE THREAD

**Issue by honeywest** [paritytech/substrate#7782]
header.state_root().check_equal(&storage_root); 
Is it necessary?
why not header.extrinsics_root().check_equal(&new_header.extrinsics_root()); 
https://github.com/paritytech/substrate/blob/3c5bfc05f9299da6da50dd36b701679d5172bdbe/frame/executive/src/lib.rs#L402-L410

**Comment by bkchr** [comment]
Clearly you can do both.

Please read the docs if you want to know what a function is doing. No reason to open issues.
