### ISSUE TITLE
import-blocks does not work on an empty node when first imported block height is not 0

### ISSUE THREAD

**Issue by nicolasochem** [paritytech/substrate#7790]
Substrate chains have an `import-blocks` and `export-blocks` function. `export-blocks` has `--from` and `--to` arguments where the user can pass the index of the first and last desired blocks included in the output file.

Substrate has also a `--pruning` option where the user can elect to only keep state of the last i.e. 10k blocks.

It should be possible to import blocks from block N to block N + 10000 on a new unsyned node, then run the node in `--pruning 10000`.

However, `import-blocks` command fails with `unknown parent` error when attempting to do that. It appears that any blocks file generated this way cannot be imported, unless `--from 0` argument to export-blocks command is passed.

**Comment by bkchr** [comment]
How should we generate the state for X, where X is the first block in your backup, when we don't have X - 1? To generate the state for X you need the state from X - 1. This means we can not import blocks for that we don't have the parent.

Pruning means to delete the state of individual blocks that are too far from the tip and will not be required anymore.
