### ISSUE TITLE
Better to make tip hash unique

### ISSUE THREAD

**Issue by wliyongfeng** [paritytech/substrate#7796]
We can see the tip hash is decided by the reason and the beneficiary from the [code](https://github.com/paritytech/substrate/blob/master/frame/tips/src/lib.rs#L246).

```rust
let hash = T::Hashing::hash_of(&(&reason_hash, &who));
```
There's no problem for on-chain data since the on-chain tip reason is keep unique by the [following code](https://github.com/paritytech/substrate/blob/master/frame/tips/src/lib.rs#L247)

```rust
ensure!(!Tips::<T>::contains_key(&hash), Error::<T>::AlreadyKnown);
```

There maybe same hashes for historical different tips. We can see it happen on Kusama and please check following 2 events.

[5180308-2](https://polkascan.io/kusama/event/5180308-2)
[3987893-2](https://polkascan.io/kusama/event/3987893-2)

2 tips are closed, but either of their hash is `0x8660f695f225b2ad388e698541a45f53f55734e211fc10374a2997abc219d435`.

Again there's no problem for on-chain data, but it's not good for off chain data handling. Reasons:
- When we say hash, we usually think it will be unique
- For off chain apps, like explorer, it will take more work to handle this. Actually subscan has a bug for the tip I mentioned above, and check [this link](https://kusama.subscan.io/treasury_tip/0x8660f695f225b2ad388e698541a45f53f55734e211fc10374a2997abc219d435) to confirm it. They mixed the tips of 2 into 1.

Take the tipper and the tipper nonce to tip hash calculation maybe an option.

**Comment by bkchr** [comment]
Not sure this is required. There are other hashes that are also not guaranteed to be unique, like the transaction hash for example. It is completely legal to have multiple transactions with the same hash.

**Comment by wliyongfeng** [comment]
> Not sure this is something we want. There are other hashes that are also not guaranteed to be unique, like the transaction hash for example. It is completely legal to have multiple transactions with the same hash.

Understand, so I use 'better'. I have no problem if same hash is legal, but indeed it bring more burden to app developer.

**Comment by bkchr** [comment]
But the same applies to proposal and everything else. There are so many places you can have duplicated hashes, which mean that you already need to have implemented some mechanism to handle this.

**Comment by shawntabrizi** [comment]
Hash here is just a representation of text, so any two tips with the same text will have the same hash. You should not treat them as unique, just a representation of some very possibly duplicate text...

**Comment by wliyongfeng** [comment]
> But the same applies to proposal and everything else. There are so many places you can have duplicated hashes, which mean that you already need to have implemented some mechanism to handle this.

Yes, I'm not complaining about the historical data, but a better solution. It means other new developed para-chains with this pallet will handle this problem as well.

> Hash here is just a representation of text, so any two tips with the same text will have the same hash. You should not treat them as unique, just a representation of some very possibly duplicate text...

Not only the text, but also the beneficiary. I know the result, but I'm thinking why not introduce tipper and tipper nonce to keep it unique.
