### ISSUE TITLE
A little doubt about the use of enum types 

### ISSUE THREAD

**Issue by zhang6321615** [paritytech/substrate#7798]
Why doesn't the code here use Self::Full

https://github.com/paritytech/substrate/blob/6ba867a3b0ed3d19843c27fc3f90aaab5759f211/frame/system/src/lib.rs#L878

**Comment by bkchr** [comment]
There is no reason. This feature of using `Self` for enums came later to Rust, so maybe it was not yet stable. However, both syntaxes are equal.
