### ISSUE TITLE
should `base_extrinsic` weight fee be adjusted same as dispatchable weight fee

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#7812]
as written in https://wiki.polkadot.network/docs/en/learn-transaction-fees#fee-adjustment

> The per-weight fee can change up to 30% in a 24 hour period. 

Both base_extrinsic weight fee and dispatchable weight fee are per-weight fee, but pallet-transaction-payment only adjust the fee associated to the dispatchable:

https://github.com/paritytech/substrate/blob/0fc832988bef7ab27f6cf2f3040fcb2d3c9b6568/frame/transaction-payment/src/lib.rs#L336-L354

It doesn't make that much sense to me to put `base_extrinsic` weight apart from the total weight used by the extrinsic.

Instead I think formula should be:
```
 inclusion_fee = len_fee + [targeted_fee_adjustment * total_weight_fee];
 final_fee = inclusion_fee + tip;
```

WDYT cc @kianenigma

**Comment by kianenigma** [comment]
Given that it is very likely for `targeted_fee_adjustment ~= 0` in a live chain, I think it is much safer to exclude base_fee from adjustments. Also, note that the bape to which you linked is outdated (at least as far as we are concerned, because our implementation already diverges from what is stated there) and is reported here: https://github.com/w3f/research-internal/issues/446 (invite only)

**Comment by thiolliere** [comment]
`"base fee"` is currently:
https://github.com/paritytech/substrate/blob/2eaeb91bc6d20786aa4ad5f5538c0deac46e14cd/frame/transaction-payment/src/lib.rs#L410

So `"base fee"` is the weight of the `"base_extrinsic"` weight of the dispatchable class, converted into fee. This is what I mean by `"base_extrinsic weight fee"`.
So the `"base_fee"` is weight dependant. It directly depends on the weight of an empty dispatchable of a class. We compute the `"base_fee"` price only from a weight.

As I understand it: a dispatchable complete weight (i.e. the time associated for its dispatching on the benchmark machine) is divided into 2 parts: base_extrinsic weight and variable weight (returned by dispatch info). Only the variable weight price is adjusted with "targeted_fee_adjustment". the base_extrinsic weight price is not. This is what I don't really understand.

If we want to introduce a "base_fee" which doesn't depend on the weight I'm all ok for it, but I find its current definition (i.e. base_extrinsic weight converted to fee) a bit unexpected.

If we agree that the total weight of an extrinsic is `base_extrinsic` weight + variable weight part (returned by dispatch info) then the fee defintion should be:
```
 inclusion_fee = len_fee + [targeted_fee_adjustment * total_weight_fee] // and maybe + some_base_fee_unrelated_to_base_extrinsic_weight
 final_fee = inclusion_fee + tip
 ```
 instead of 
 ```
 inclusion_fee = len_fee + base_part_of_extrinsic_weight + [targeted_fee_adjustment * variable_part_of_extrinsic_weight]
 final_fee = inclusion_fee + tip
 ```

**Comment by thiolliere** [comment]
also as `"targeted_fee_adjusment"` is here to change the price of a weight in case block are full or empty I find it unfair that extrinsic with a very small variable part (i.e. dispatch info weight is small compated to `base_extrinsic` weight) gets less affected than extrinsic with a big variable part (i.e. dispatch info weight is big compared to `base_extrinsic` weight).

For example if we take 2 extrinsic A and B where A weight is 2 times base_extrinsic weight and A len is 2X and B weight is base_extrinsic + epsilon and B len is X. Then if targeted_fee_adjusment is less than 1. It is better to send A than 2 times B. Whereas when targeted_fee_adjusment is more than 1. It is better to send 2 times B than A.
Which is a bit counter intuitive to me.

So AFAICT the total weight of the extrinsic should be adjusted with `"targeted_fee_adjusment"`, not only the variable part.
and `"base_fee"` value should come from other consideration than base_extrinsic weight.

Maybe I just miss the reason for "base_fee" to be, what does "base_fee" cost should account for ?

**Comment by kianenigma** [comment]
Ahh my definitions were a bit outdated, thanks for clarifying it. 

> If we want to introduce a "base_fee" which doesn't depend on the weight I'm all ok for it, but I find its current definition (i.e. base_extrinsic weight converted to fee) a bit unexpected.

Yes I agree. I also expected the `base_fee` to be a constant expressed in `balance`, not `weight`. Although, I still argue that `base_extrinsic_weight_fee` is not dependent on the _weight of the extrinsic_, and this is what I meant by not being weight-dependent. Perhaps it would have been better to call it _static_, or _not dispatch-dependent_. But given a deterministic weight-to-fee (which should always be the case), base_fee _is_ already a balance, as it is always converted to fee and used without any adjustment. So the formula is, if you apply `weight_to_fee(base_weigh)` early on: 

```
inclusion_fee = len_fee + base_fee + [targeted_fee_adjustment * weight_fee]
 final_fee = inclusion_fee + tip
```

I think this goes back to early on when we did weights for polkadot. Back then, we had base_fee as a balance, and given that for benchmarks we wanted to have a base_weight as well, it made sense to merge them together, and you are proposing decoupling them again.

> If we agree that the total weight of an extrinsic is base_extrinsic weight + variable weight part (returned by dispatch info) then the fee definition should be:

>  inclusion_fee = len_fee + [targeted_fee_adjustment * total_weight_fee] // and maybe + some_base_fee_unrelated_to_base_extrinsic_weight
>  final_fee = inclusion_fee + tip

I would personally be fine with this as well, but I am worried that it is a bit too complicated to be educated to developers. The only important note is to never make the entire fee adjustable. Maybe we should actually revert back to having `base_fee` as a balance type, and then the amalgamator runtime that wants to set this value can set something like: 

```
parameter_types! { const BaseFee: Balance = WeightToFee(BASE_WEIGHT_FROM_BENCHMARKS).convert(); }
impl transaction_payment::Config for Runtime { type BaseFee = BaseFee }
```

> Maybe I just miss the reason for "base_fee" to be, what does "base_fee" cost should account for ?

I am not sure either, to me it is 
1. anti-DOS
2. the amount of weight for a noop, which means the cost of all the machinery in the runtime that the dispatchable is _not_ responsible for.

**Comment by thiolliere** [comment]
> Although, I still argue that base_extrinsic_weight_fee is not dependent on the weight of the extrinsic, and this is what I meant by not being weight-dependent. Perhaps it would have been better to call it static, or not dispatch-dependent.

Should you think the fee for `base_extrinsic_weight` shouldn't be adjusted with `targeted_adjusment_fee` ?

For me the `targeted_adjusment_fee` is there to adjust the price of the weight depending on the fullness of blocks in order to avoid too much full blocks. Thus the whole extrinsic weight should be adjusted, variable part and static part.
The idea is too make the price of weight bigger or smaller depending on the fullness of blocks. Both variable part and static part of the weight are making the block more or less full, I don't know why there should be a difference between them.
I feel like it result in weird incentivisation https://github.com/paritytech/substrate/issues/7812#issuecomment-753606516

> the amount of weight for a noop, which means the cost of all the machinery in the runtime that the dispatchable is not responsible for.

The dispatchable is responsible for all its weight, static and variable. Dispatching the extrinsic will increase the weight of the block by static weight + variable weight. And it will take the time (on benchmark machine): variable weight + static weight.

> anti-DOS

Yes I'm ok to have a base_weight, or maybe better having `targeted_adjusment_fee` a sensible minimum to avoid this DOS.


All in all what I don't understand is that `targeted_adjusment_fee` is there to adjust the price of weight. But it you have an extrinsic with a weight close to base_extrinsic_weight. Then its price is never adjusted, which feels unfair.

**Comment by kianenigma** [comment]
> Should you think the fee for base_extrinsic_weight shouldn't be adjusted with targeted_adjusment_fee ?

Given the current setup, no I think it shouldn't. If we add a separate, static base fee for anti-dos purposes, then I think it should. 

> For me the targeted_adjusment_fee is there to adjust the price of the weight depending on the fullness of blocks in order to avoid too much full blocks. Thus the whole extrinsic weight should be adjusted, variable part and static part.
The idea is to make the price of weight bigger or smaller depending on the fullness of blocks. Both variable part and static part of the weight are making the block more or less full, I don't know why there should be a difference between them.
I feel like it result in weird incentivisation #7812 (comment)

This has been discussed before within w3f and parity and I can give you the gist of if that most people were against it as it is likely to push the chain where all fees are zero except len_fee, which is a bit DOS-prone. (I am personally open t the discussion though, just telling your previous discussion outcomes.)

> All in all what I don't understand is that targeted_adjusment_fee is there to adjust the price of weight. But it you have an extrinsic with a weight close to base_extrinsic_weight. Then its price is never adjusted, which feels unfair.

Maybe you can see this minimum_base fee that we never go below it, similar to the minimum of the adjustment factor. It is just expressed in a different way.

---

All in all, I think the current system meets the requirements, but the terminology is confused. So the issue can stay, while the priority is probably low.

**Comment by thiolliere** [comment]
This has been discussed before within w3f and parity and I can give you the gist of if that most people were against it as it is likely to push the chain where all fees are zero except len_fee, which is a bit DOS-prone.

If the weight price is almost zero isn't DOS-prone already ? like there can be extrinsics which have a small len and very big weight. Then if the weight price is very low, this extrinsic cost same as a balance transfer, but take way more time to be computed, could this open DOS attack ?

Anyway I can't really understand but I think it is just me.
