### ISSUE TITLE
about ink pallet

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/substrate#7827]
I want to use the ink pallet built in the substrate.
After building a contract built with ink, I tried to initiate/putcode and use it, but after using it several times, I found out that it was not used due to the depletion of fees. So, I was able to use the contract call without fail by transferring the native coins to the contract address. If so, in order to solve the difficult problem above, where can I modify the ink pallet to build a fee-free thing?

**Comment by thiolliere** [comment]
There is:
```
	/// Price of a byte of storage per one block interval. Should be greater than 0.
	type RentByteFee: Get<BalanceOf<Self>>;
```
Maybe you can set it to 1 then the rent will be very very low

**Comment by puffanddmx** [comment]
are there any way that can be 0 byte not setting 1?

**Comment by thiolliere** [comment]
doc say you shouldn't, but maybe for development it is fine.

**Comment by puffanddmx** [comment]
if someone deploys new contract on the network, does he need to charge some coins into the contract address everytime to use this contract?
if the contract address has low money, is it impossible to do the service?

**Comment by puffanddmx** [comment]
thanks!
