### ISSUE TITLE
Pluggable Consensus: Import Queue

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#784]
As part of pluggable consensus, we need to abstract over verification of blocks. Consensus engines will check the validity of a block under a consensus engine based on two different types of data: internal and external justifications. Internal justifications are part of the header, while external justifications are a piece of auxiliary data. Usually, consensus engines will use one or the other.

The synchronization code doesn't care how the block is verified, and code that isn't knowledgeable about the consensus algorithm can't meaningfully optimize and parallelize verification code. So the sync service just gets an `ImportQueue` trait object for it to pump blocks into.

```rust
type Justification = Vec<u8>; /// Opaque, to be decoded by consensus engine.

/// Errors that can occur when queuing a block. Deeper verification errors are not encompassed by
/// this type.
pub enum Error {
    /// Bad external justification: there is still a chance the block can be good.
    BadExternalJustification(String), // for debug-printing
    /// Bad internal justification: no chance the block is still good
    BadInternalJustification(String),
}

/// A handle to the import queue.
trait ImportQueue<Block: BlockT> {
    /// Queue a single block. Returns an error and the block if unable to queue.
    fn queue(&self, header: Block::Header, block: Option<Block::Body>, justification: Justification) -> Result<(), (Error, Block::Header)>;
    /// Queue many blocks at once. Returns an error with the first bad block it finds.
    fn queue_many(&self, blocks: Vec<(Block::Header, Option<Block::Body>, Justification)>) -> Result<(), (Error, Block::Header)>;
}
```

The import queue in turn is expected to decode and check justification info against the block, and then call `Client::import_block`.
In the case of internal justification, this data will always go at the end of the header's Digest.

```rust
/// data required to import a block.
pub struct ImportBlock<Block: BlockT> {
    origin: BlockOrigin,
    header: Block::Header,
    external_justification: Justification,
    internal_justification: Vec<u8>, // Block::Digest::DigestItem?
    body: Option<Vec<Block::Extrinsic>>,
    finalized: bool, // true for instant finality
}

impl<Block: BlockT> Client<Block> {
    // ...
    fn import_block(&self, import_block: ImportBlock<Block>) -> Result<(), Error> { ... }
}
```

The `internal_justification` is an artifact of a current open question in the verification pipeline.

https://github.com/paritytech/substrate/blob/8568aa77e39a2288928f97597b13e60852e952da/srml/executive/src/lib.rs#L205-L210

Line 210 checks that the digest produced by the runtime is the same as the digest of the header we are executing the block for. If we want to retain this check (which is useful for ensuring that digest items coming _from the runtime_ like log events are consistent) then we have to alter the import pipeline:
  1. The import queue checks the internal justification, and chops it off the end of the digest
  2. The import queue passes the "scrubbed" header to `import_block` along with the `internal_justification`
  3. The client verifies the scrubbed block and then re-appends the `internal_justification` to the block.
  4. The client imports the full block to the database.

If we remove the assertion that the digest produced by the runtime is the same as the digest of the header passed to the `execute_block` function, then this pipeline alteration and the `internal_justification` field on `ImportBlock` is unnecessary.

**Comment by arkpar** [comment]
`queue` and `queue_many` should not perform any justification checks synchronously and therefore can't return justification errors. The only error condition that can be checked at this point is that the block or justification is already known to be bad, or that the block is part of the bad chain.

**Comment by arkpar** [comment]
I don't really understand the issue with the digest. Why wouldn't the check for digest just work without stripping anything from the header, like it does for state root?

> The import queue checks the internal justification, and chops it off the end of the digest

What exactly is internal justification check here and how can it be performed ahead of block execution?

**Comment by rphmeier** [comment]
> queue and queue_many should not perform any justification checks synchronously and therefore can't return justification errors

yeah. we can't check these things synchronously. errors have to be handled internally to the queue and asynchronously noted, same as in the parity-ethereum queue.

> I don't really understand the issue with the digest. Why wouldn't the check for digest just work without stripping anything from the header, like it does for state root?

The purpose of internal justifications is for consensus algorithms like Aura or PoW, where we need the seal on the block to affect its hash (think of `hash` vs. `bare_hash` in parity-ethereum). This is in contrast to consensus algorithms like rhododendron where there are many valid justifications for a single block.

If the digest item is added _after_ execution (i.e. after resolution of the storage root), then the check in the issue description will fail because this digest item was not added in runtime execution and thus doesn't match.

The reason the digest item is added after runtime execution is because we need to sign the contents of the block -- this can't be done in the runtime unless the runtime had all validators' private keys (this is a terrible idea).

So we need to either prune off the last digest item and compare that what the runtime generates is the same, or remove this check from runtimes entirely.

**Comment by gnunicorn** [comment]
How do we want to deal with `cli`s `import-block` command which currently internally does:

```

		match SignedBlock::decode(&mut input) {
			Some(block) => {
				// TODO: non-instant finality.
				let header = client.check_justification(block.block.header, block.justification.into())?;
				client.import_block(BlockOrigin::File, header, Some(block.block.extrinsics), true)?;
			},
			None => {
				warn!("Error reading block data.");
				break;
			}
		}
```

Which, if I understand this correct, reads blocks from a file, verfies and imports them using `client`. However, if `client` no longer directly provides facilities to check verifications (as they are provided by the consensus-engine used) and only provides means to import already trusted blocks, how is the `cli` supposed to be able to verify they aren't importing garbage?

**Comment by rphmeier** [comment]
The CLI or service needs to know how to instantiate the import queue for supported consensus algorithms regardless (from the spec or some hardcoded list). So rather than importing the blocks directly to the client, the CLI `import-block` command should be giving the blocks to the import queue, which manages verification.

**Comment by rphmeier** [comment]
#1014 does some more improvement here; after that the only thing left to do would be to move the import queue code to `consensus_common`.
