### ISSUE TITLE
Should the command line have in node-template?

### ISSUE THREAD

**Issue by honeywest** [paritytech/substrate#7860]
in bin/node-template 
Can we provide cli command?
For example:
getheight
getblock 
transfer etc.

**Comment by bkchr** [comment]
I don't understand what you want to say with this issue. Please use proper English and explain better what you want. Ty.

**Comment by honeywest** [comment]
Both bitcoin and Ethereum nodes have command lines
It will be much more convenient
For example, we want to query a block

**Comment by shawntabrizi** [comment]
@honeywest you can access a CLI like that here: https://github.com/polkadot-js/tools/tree/master/packages/api-cli
