### ISSUE TITLE
Eventual stop in block production upon changing Babe epoch duration on a runtime upgrade

### ISSUE THREAD

**Issue by alexsednz** [paritytech/substrate#7864]
This issue is not about how to restore the chain or hard spooning after a block production interrupt. This is rather about how the babe epoch parameter can be adjusted while keeping all or most of the blocks. Currently, the division of Babe related logic between the client and the runtime means that after a runtime upgrade if the new runtime has committed to a longer epoch duration, the client will throw the error `ClientImport("Expected epoch change to happen at ...` right after the time that some activity from Babe is expected according to the previous epoch duration. From an outer perspective, this could be avoidable if either the new runtime would respect the previous commitment for the first iteration or the client could notice a runtime parameter change.

**Comment by andresilva** [comment]
It's currently not possible to change the epoch duration. There is a comment to that effect here: https://github.com/paritytech/substrate/blob/master/frame/babe/src/lib.rs#L67-L69

Allowing such a change is an involved task that is currently not planned.
