### ISSUE TITLE
Missing some crates in release 2.0.1

### ISSUE THREAD

**Issue by zikunfan** [paritytech/substrate#7875]
1. `pallet-bounties`: https://crates.io/search?page=1&per_page=10&q=pallet-bounties
2. `pallets-tips`: https://crates.io/search?page=1&per_page=10&q=pallet-tips
3. `sp-keystore`: https://crates.io/search?page=1&per_page=10&q=sp-keystore

**Comment by bkchr** [comment]
CC @gnunicorn

**Comment by xlc** [comment]
Those pallets did not exist when v2.0.0 is released so it does not make sense to make v2.0.1 release for those because they won't be compatible with 2.0.0 release.

**Comment by thiolliere** [comment]
yes 2.0.1 is just 2.0.0 with some compilation fix, it doesn't include new crates, and those creates are a major breaking change AFAICT

**Comment by gnunicorn** [comment]
thanks, @zikunfan , for reporting,

as @thiolliere  already said, 2.0.1 is just a patch release to fix the compilation issues with nightly - as such it only includes the necessary backports for that. This should allow people using the 2.x release to switch to latest nightly again for some performance boosts. 

A full release, including new pallets, is in process of being prepared and should be happening within a couple of weeks.
