### ISSUE TITLE
Dynamic delay on proxy accounts

### ISSUE THREAD

**Issue by olanod** [paritytech/substrate#7893]
When adding a proxy account there's a delay parameter that specifies the number of blocks to wait before the transaction is submitted, it would be nice if it would be more granular or dynamic in some way so a user can create a proxy that can for example transfer only a maximum amount of tokens in a given time or if transferring a large amount of resources would have to wait a longer period of time giving the owner of the main account more time to cancel it if it's dangerously suspicious.

**Comment by bkchr** [comment]
Duplicate
