### ISSUE TITLE
Rust analyzer marks `decl_module!` as invalid

### ISSUE THREAD

**Issue by sander2** [paritytech/substrate#7896]
When using `decl_module!`, rust analyzer marks the complete content as invalid, giving the error "could not resolve macro `$crate::sp_tracing::trace_span`". I suspect this is because `$crate` usage is not allowed in Rust2018. While actual compilation still works, the IDE experience is greatly deteriorated.

**Comment by thiolliere** [comment]
note that you can usually remove the unwanted diagnostic from rust-analyzer, I personnally use:
```rust
{
	"rust-analyzer": {
		"diagnostics": {
			"disabled": [
				"macro-error",
				"unresolved-proc-macro",
				"inactive-code"
			]
		}
	}
}
```

**Comment by bkchr** [comment]
This is some error in rust-analyzer. 

>  I suspect this is because $crate usage is not allowed in Rust2018.

This is not true.

Closing as this is no Substrate issue.

**Comment by sander2** [comment]
> note that you can usually remove the unwanted diagnostic from rust-analyzer

Thanks! 

It turns out it was indeed an issue with rust-analyzer, and it's [fixed](https://github.com/rust-analyzer/rust-analyzer/pull/7205) in the newest version.
