### ISSUE TITLE
Implement Deserialize for RuntimeMetadataPrefixed

### ISSUE THREAD

**Issue by olanod** [paritytech/substrate#7937]
`RuntimeMetadataPrefixed` is the type returned by `Runtime::metadata()` which implements Serialize and I imagine is the way metadata can be serialized to JSON to be used in JS. Once I have metadata as JSON I think is reasonable to want to deserialize it back to `RuntimeMetadataPrefixed` which can be used by Rust tools that don't want a hard dependency on a  specific runtime code don't you think?

**Comment by ascjones** [comment]
See ongoing work in the new `frame-metadata` crate: https://github.com/paritytech/frame-metadata/pull/3

**Comment by olanod** [comment]
Awesome! even better to have it as a tiny crate :)
