### ISSUE TITLE
Bump node authorization to v2.0.1

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate#7944]
https://github.com/paritytech/substrate/blob/d5bdd81de1af28250f4bef32a06a6e2dfd80c800/frame/node-authorization/Cargo.toml#L3

This must have been missed in the 2.0.1 release? on crates.io // lib.rs it shows as 2.0.0 latest. 

This pallet is used in https://substrate.dev/docs/en/tutorials/build-permission-network/add-node-authorization-pallet

IMHO low priority, as the tutorial has not migrated to 2.0.1 and AFAIK substrate v3.0.0 is ... 🔜

**Comment by bkchr** [comment]
We only released crates as 2.0.1 which were required to make Substrate build with latest stable/nightly. This will come with 3.0.0
