### ISSUE TITLE
Next Release tracking issue

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate#7947]
We want to make a new full feature release, especially to get the new FRAME into the hands of people. As of now, the strategy is to release all crates with code changes since 2.0 under the correct SemVer-version, so some will be patches others minor some major upgrades.

Big picture changes (_why_ we are releasing):
- this brings FRAME 2.0 macros
- FRAME: Ref-Counting Provider #7343
- New Pallet: Participation Lottery Pallet #7221

Please link in this (with checklist here) any blocking issues or PRs, _that are being worked on and expected to be merged within the next 2 weeks latest_ , including a mention of the person responsible (as shown):

 - [x] cleaning up dependencies #7956 @gnunicorn 
 - [x] updating to SCALE 2.0 #7994 @thiolliere

**Comment by liuchengxu** [comment]
Please include #7127 in the next release.

**Comment by xlc** [comment]
I would like to have https://github.com/paritytech/substrate/pull/7778 if possible

**Comment by thiolliere** [comment]
we should also include incoming release of parity-scale-codec 2.0

**Comment by gnunicorn** [comment]
@thiolliere is this expected to happen within the next 10 days? Is there a tracking issue for it?

**Comment by thiolliere** [comment]
Yes it is expected to happen next week, there is only one PR left https://github.com/paritytech/parity-scale-codec/milestone/3

**Comment by apopiak** [comment]
I would like to get these 2 quality of life PRs in: #8017 and #8019

**Comment by thiolliere** [comment]
not sure it is required to next release, but https://github.com/paritytech/substrate/issues/7949 can be good to have

**Comment by bkchr** [comment]
Telemetry is broken: https://github.com/paritytech/substrate/issues/8093

**Comment by gnunicorn** [comment]
closed by https://github.com/paritytech/substrate/pull/8098

**Comment by liuchengxu** [comment]
Why no release for sc-finality-grandpa-wrap-sync? https://crates.io/search?page=1&per_page=10&q=sc-finality-grandpa-wrap-sync

**Comment by gnunicorn** [comment]
@liuchengxu it is marked as `publish = false` by its authors:

https://github.com/paritytech/substrate/blame/3957f43912e43fd28b624bb0736141ac24b51615/client/finality-grandpa-warp-sync/Cargo.toml#L8

I presume because it is far from ready yet, but would leave it to @expenses to elaborate on that.

**Comment by expenses** [comment]
> I presume because it is far from ready yet, but would leave it to @expenses to elaborate on that.

Personally, I think the crate is ready-enough at the moment. The core part of grandpa warp sync is in `sc-finality-grandpa` anyway; the request response handler is pretty simple. I think `publish = false` is just there because I copied it from somewhere else 😅

**Comment by liuchengxu** [comment]
@gnunicorn @expenses If the code is ready, is there any chance that we can still have it published in the Substrate 3.0 release? It just does not look perfect with only one git dep left in the Cargo.toml.
