### ISSUE TITLE
Default PalletInfo impl for `()` can cause storage collisions

### ISSUE THREAD

**Issue by ascjones** [paritytech/substrate#7949]
Discovered while working on https://github.com/paritytech/substrate/pull/7936.

Usually `construct_runtime!` generates a `PalletInfo` impl which returns the unique pallet name to use as the storage prefix.  However, manually configured test runtimes use `type PalletInfo = ()` in their `system::Config` implementation. The `PalletInfo` impl for `()` returns `"test"` from `name()`, which can cause storage collisions where two pallets have a storage item with the same name.

In my case it was because both System and Balances have an `Account` storage item - the temporary fix was applied here: https://github.com/paritytech/substrate/pull/7936/commits/c147734e3d8469aa1623a07b51d82cf48d95143b.

Chatted with @thiolliere, and we have agreed that we need to remove the footgun of the `PalletInfo` impl for `()`. Potential solutions:

- Make `construct_runtime!` macro work for test ruuntimes (@thiolliere already has some code in this direction)
- Create `impl_pallet_info!` for test runtimes to generate code similar to `construct_runtime`
- Make the default impl for `()` return some guaranteed unique and consistent pallet prefix, maybe using something in `std::any`.
- Allow standalone pallets to somehow provide an implementation of PalletInfo that is only used if the `System` does not provide one, though this might be tricky because of instantiable pallets (@thiolliere to elaborate)

### Update:

We are in the process of updating all test runtimes to use `construct_runtime!` directly. Here is a list, please put your name against any that you are working on to avoid duplicating work. It's just a raw list of all frame modules, so feel free to amend where necessary.

- [x] assets #7974
- [x] atomic-swap #7974
- [x] aura #7974
- [x] authority-discovery #7974
- [x] authorship #7974
- [x] babe #7975
- [x] balances #7975
- [x] benchmarking @thiolliere
- [x] bounties @ascjones #8051
- [x] collective
- [x] contracts @ascjones #8051
- [x] democracy @ascjones #8051
- [x] elections 
- [x] ~~elections-phragmen~~
- [x] example @thiolliere
- [x] example-offchain-worker @thiolliere
- [x] example-parallel @thiolliere
- [x] executive
- [x] grandpa @thiolliere
- [x] identity @thiolliere
- [x] im-online @thiolliere
- [x] indices #7975
- [x] lottery @thiolliere
- [x] membership @thiolliere
- [x] merkle-mountain-range @thiolliere
- [x] metadata @thiolliere
- [x] multisig @thiolliere
- [x] nicks @thiolliere
- [x] node-authorization @thiolliere
- [x] offences @thiolliere
- [x] proxy @thiolliere
- [x] randomness-collective-flip
- [x] recovery
- [x] scheduler
- [x] scored-pool
- [x] session
- [x] society
- [x] staking
- [x] sudo
- [x] support
- [x] system @thiolliere
- [x] timestamp
- [x] tips
- [x] transaction-payment
- [x] treasury
- [x] utility
- [x] vesting
- [x] test-utils

**Comment by thiolliere** [comment]
I think ppl should already use construct_runtime in their tests: staking, executive and few other do that.
We can also introduce some helper type in system IMO as done in https://github.com/paritytech/substrate/pull/7950

**Comment by xlc** [comment]
Maybe someone can fix https://github.com/paritytech/substrate/issues/3335 so we don't need to remember all the details to generate a test runtime?

**Comment by thiolliere** [comment]
maybe we can do a mix of them:
improving implementation of `()` for `PalletInfo` with `std::any` but at the same deprecate it with a clear message:
`The implementation () for PalletInfo use trait Any and can be inconsistent between tests use construct_runtime or impl_pallet_info instead`

**Comment by bkchr** [comment]
I think we should fix it properly directly.

As I have implemented it, we didn't use it, so there wasn't any problem with this common prefix :grin:

**Comment by thiolliere** [comment]
Does an implementation of `PalletInfo` for `()` using `std::any::type_name` or `Any as Debug` is a proper fix.
IMHO I'm not sure `std::any::type_name` is always consistent between testing environment.
And same for `Any as Debug`.

Thus the proper fix is deprecated or remove implementation of `PalletInfo` for `()`, while providing a macro to implement it easily and encourage ppl to make use of construct_runtime

**Comment by ascjones** [comment]
> while providing a macro to implement it easily and encourage ppl to make use of construct_runtime

Should we only encourage use of `construct_runtime` in the deprecation message, rather than another macro to remember  to add in addition to  `impl_outer_event` and `impl_outer_origin`

**Comment by bkchr** [comment]
I like the idea of encouraging people to use `construct_runtime` in tests as well.

**Comment by shawntabrizi** [comment]
I think we should remove the impl of `()` for `PalletInfo`

**Comment by ascjones** [comment]
We should, once all `PalletInfo = ()` occurrences are gone. There's still a few there if you do a search. I will remove more today.
