### ISSUE TITLE
Skip empty blocks and instant finality consensus

### ISSUE THREAD

**Issue by g2udevelopment** [paritytech/substrate#7952]
When building an enterprise (private / consortium) chain it can happen that the volume of transactions are rather low. The consequence is that there is a high ratio of empty blocks. 

The current implementations of the slot based consensus engines that are part of substrate need to produce blocks at a timed interval even if they are empty (bar the inherent from the timestamp module).

I think it would greatly help enterprise cases if one of the following changes where to happen.

1. Change Aura to skip empty blocks (I have to admit that I don't know if this is possible from an algorithmic and/or security standpoint).

2. Have an instant finality consensus engine like PBFT/Tendermint that has the possibility to skip empty blocks.

For your reference here is an issue (https://github.com/tendermint/tendermint/issues/246) and a PR (https://github.com/tendermint/tendermint/pull/584/files) with an implementation of the empty block skipping in Tendermint.

When looking for similar issues I found an old issue talking about returning a PBFT engine to substrate (https://github.com/paritytech/substrate/issues/1020)

@andresilva

**Comment by burdges** [comment]
We'll want parathreads eventually which produce blocks whenever they like, which implies roughly this.  We'd maybe focus upon parathreads however because they're far cheaper than parachains and thus permit wider usage of the network.  We have not yet designed parathread block production per se, but perhaps collators simply buy their slot oncew they've some worthwhile block.

**Comment by g2udevelopment** [comment]
> We'll want parathreads eventually which produce blocks whenever they like, which implies roughly this. We'd maybe focus upon parathreads however because they're far cheaper than parachains and thus permit wider usage of the network. We have not yet designed parathread block production per se, but perhaps collators simply buy their slot once they've some worthwhile block.

Yes the idea of parathreads for 'small' usage chains looks very promising. Because in most cases I have tough of the `small` chain eventual wants to pin it's state to a more secure chain, which is exactly what is happening when using the Relay chain as a parathread.

But do you think that it is possible to design the consensus in a pluggable way that it could even be used standalone without the use of parathreads? So that for instance a simple node-template setup can plug-in this consensus instead of Aura+Grandpa.

**Comment by burdges** [comment]
Yes, we'll build more consensus options for paracahins eventually.

**Comment by kaichaosun** [comment]
I'd like to pick this issue. Before making further changes, I have following questions:
* Does `skip empty blocks` feature required by both public blockchain and enterprise blockchain (aka, permissioned blockchain)
* Are there scenarios that an enterprise blockchain also want to use BABE?
* How is this feature sound from security aspect?

**Comment by andresilva** [comment]
FWIW I implemented the `skip empty blocks` functionality in the older Aura implementation of parity-ethereum (https://openethereum.github.io/Aura#empty-steps). I don't think we should implement that here, it just adds complexity to Aura and is not really well thought out. Ideally Substrate should have a consensus engine that provides instant finality (something like Tendermint) and skipping empty blocks should be a functionality in this new engine. Implementing a new consensus engine is a big task that needs to be properly planned though and this is not a priority right now.
