### ISSUE TITLE
impl Contains<T> for any Get<T>

### ISSUE THREAD

**Issue by nanocryk** [paritytech/substrate#7972]
`frame_support::traits::Contains<T>` should be implemented for any type implementing `frame_support::traits::Get<T>`.

It would for example allow to use `frame_system::EnsureSignedBy<Who, AccountId>` with `Who` being a type declared in a `
parameter_types!` call, avoiding the need to declare a type and manually implement `Contains` for only one authorized `AccountId`.

**Comment by nanocryk** [comment]
It seems to not be possible since some pallets implements `Contains` for their `Module`, leading to a conflicting implementation with an hypothetical implementation of `Get` in a downstream crate.

For the initial intent of using `EnsureSignedBy` with a `Get`, maybe add a similar type that accepts a `Get` instead of a `Contains` ?
I would have also expected the collective pallet's `Module` implemented `Contains`, but I suppose the custom `EnsureX` types replaces this need.

**Comment by bkchr** [comment]
You can just implement the `EnsureSignedBy' in your codebase. Not sure why you need to have some modifications for this on the Substrate side?

**Comment by nanocryk** [comment]
Indeed, just sounds a good feature to be able to use an `EnsureSignedBy` with a `Get` when implementing a runtime with simple permissions.

**Comment by bkchr** [comment]
Yeah while it is easy, it is also feature creep. This is such a small change that it just can be done on the level of a runtime

**Comment by kianenigma** [comment]
Shan't we close if it is agreed upon to implement such things in upstream runtimes and not substrate?
