### ISSUE TITLE
Query regarding benchmarking 

### ISSUE THREAD

**Issue by ksr30** [paritytech/substrate#7973]
Hi all,
I was going through a benchmark file of Identity Pallet. And I have a doubt when we are becnhmarking **add_registrar** function. 

```
add_registrar {
		let r in 1 .. T::MaxRegistrars::get() - 1 => add_registrars::<T>(r)?;
		ensure!(Registrars::<T>::get().len() as u32 == r, "Registrars not set up correctly.");
	}: _(RawOrigin::Root, account("registrar", r + 1, SEED))
```
Here in first line, when we are calling **add_registrars**, its probably doing some extra stuff which are not required by **add_registrar** like **set_fee** and **set_field**.
```
fn add_registrars<T: Config>(r: u32) -> Result<(), &'static str> {
	for i in 0..r {
		let registrar: T::AccountId = account("registrar", i, SEED);
		let _ = T::Currency::make_free_balance_be(&registrar, BalanceOf::<T>::max_value());
		Identity::<T>::add_registrar(RawOrigin::Root.into(), registrar.clone())?;
		**Identity::<T>::set_fee(RawOrigin::Signed(registrar.clone()).into(), i.into(), 10u32.into())?;**
		let fields = IdentityFields(
			IdentityField::Display | IdentityField::Legal | IdentityField::Web | IdentityField::Riot
			| IdentityField::Email | IdentityField::PgpFingerprint | IdentityField::Image | IdentityField::Twitter
		);
		I**dentity::<T>::set_fields**(RawOrigin::Signed(registrar.clone()).into(), i.into(), fields)?;
	}

	assert_eq!(Registrars::<T>::get().len(), r as usize);
	Ok(())
}
```
So my question is ... why we need to include that ... when we are benchmarking this particular extensic function?

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by kianenigma** [comment]
Looks a bit strange that there are multiple dispatchables in there, indeed.

**Comment by thiolliere** [comment]
it can be that `add_registrars` function is used in lots of other benchmark setup than `add_registrar`, e.g. `set_fee`, `kill_identity`, ...
I think that at least one of the other benchmarks requires that the registrar is setup like this.

`add_registrars` isn't only to setup `add_registrar` benchmark.

Feel free to reopen if that doesn't answer you

**Comment by kianenigma** [comment]
Ahh, right I though the function being benchmarked called 3 dispatchables, but it is the setup function. Yes this is okay then.

**Comment by ksr30** [comment]
hmm ... okay thanks @thiolliere @kianenigma
