### ISSUE TITLE
about contract frame

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/substrate#7987]
After doing the contract (erc 721)putcode/instantiated , we need to put the gas limit / endowment like below link.
how to calculate the gas limit/endowment to be successful extrinsic related with maxblockweight?
When instantiated, the contract address is created, but you have to put in money after endowment. If there are much endowments in the contract address, money(fee) does not be deducted every time the contract is executed. However, if the contract address contains less endowment when created, money(fee) is deducted each time the contract is executed. Actually i do not understand it happens. Shouldn't the fee be deducted from the contract address regardless of the amount of endowments? Can you give me some examples please?

-code
https://github.com/paritytech/substrate/blob/1c9a9e4798e10c3eba277eeef143cb4ca12e9bae/frame/contracts/src/lib.rs#L604

**Comment by bkchr** [comment]
CC @athei

**Comment by athei** [comment]
> Shouldn't the fee be deducted from the contract address regardless of the amount of endowments?

It depends on the endowment. The endowment acts as a deposit and offsets the rent payment. Given enough endowment the contract stops paying rent. Check pallet configuration:
https://github.com/paritytech/substrate/blob/46c510f4bde0eb4178d84adf45dc8568eb79c25d/frame/contracts/src/lib.rs#L291-L319

Please use our [ink! chatroom](https://matrix.to/#/!tYUCYdSvSYPMjWNDDD:matrix.parity.io?via=matrix.parity.io&via=matrix.org&via=corepaper.org) for further questions and support requests.
