### ISSUE TITLE
Dont finalized block

### ISSUE THREAD

**Issue by Daelon02** [paritytech/substrate#7998]
We have substrate node with babe + grandpa consensus. We tried to run it on different computers and create a network. Everything works if we use the pre-installed accounts of Alice and Bob. We are trying to create our own config with our own keys. using subkey, 2 pairs of 4 keys were generated. 2 in sr25519 format (account address and account stash address), then a key in ed25519 format (used for GrandpaId). We took a seed-phrase from him and created a sr25519 key (for Babe). That is, we have 2 validators. We launched the nodes and using rpc requests inserted keys for both validators (babe + gran)

Nodes see each other on the network, create blocks, but do not finalize blocks. With what it can be connected? The screenshots show the config that we use when starting the network
![photo_2021-01-28_11-26-21](https://user-images.githubusercontent.com/63471940/106118614-f88fef00-615c-11eb-8d03-1b97acdaacee.jpg)
![photo_2021-01-28_11-26-26](https://user-images.githubusercontent.com/63471940/106118617-f9c11c00-615c-11eb-8f58-bd4216109687.jpg)

**Comment by bkchr** [comment]
Did you restart the nodes after inserting the grandpa keys?

**Comment by Daelon02** [comment]
> 
> 
> Did you restart the nodes after inserting the grandpa keys?

No

**Comment by bkchr** [comment]
Please do this and it will fix your problem

**Comment by Daelon02** [comment]
> 
> 
> Please do this and it will fix your problem

Yes, thats fix problem, but, how it works?

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/issues/7268
