### ISSUE TITLE
Outdated reference in Example pallet to Frame System

### ISSUE THREAD

**Issue by al3mart** [paritytech/substrate#8000]
In pallet example we can find this https://github.com/paritytech/substrate/blob/a2ee0b414f29ce558155dac5cbf78b40723bcc73/frame/example/src/lib.rs#L580 referencing `CheckRuntime` in frame/system. But once in system `CheckRuntime` is not implemented anywhere.

Is documentation in pallet example talking about signed extensions in general or that reference is outdated ?

**Comment by thiolliere** [comment]
It is probably outdated and probably refered to one the of the extension in system like `CheckSpecVersion`

**Comment by kianenigma** [comment]
yeah, it is the check spec version. Can open a PR for that and close the issue @al3mart?

**Comment by al3mart** [comment]
Sure :) Jumping on it

**Comment by al3mart** [comment]
#8056 Closes this issue
