### ISSUE TITLE
cannot upgrade runtime on chain from 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by 2075** [paritytech/substrate#8016]
we are building zero, a videogame network, based on parity substrate and run a network since ~ august 2020 with around 4m blocks produced – until last week:

when upgrading a network through sudo / setCode, which previously worked like a charm many times, we end up with a broken chain when uploading a new runtime based on substrate 2.0.1 into a chain based on substrate 2.0.0. we are using all by default included pallets.

the first error we get after an upgrade is: ```FATAL: Unable to initialize the API: -32603: Unknown error occurred: Client, VersionInvalid, Other, \"Instantiation: Export ext_default_child_storage_storage_kill_version_2 not found\```

we already checked for additional code rendering the new build defect, but separately, both builds work flawless.

as the newer chainspec contains more details for the contracts pallet, and multiaddress format, it seems there are some changes, which the old runtime cannot chew, but coming from the error, we cannot identify, what the original problem is and could not find any documentation explaining eventually breaking changes included in the 2.0.1 patch version bump.

changing the genesis chainspec renders the following builds incompatible with the old runtime, therefore a chain cannot be upgraded if we change the chainspec.

using the old chainspec, results in the following error message after a successful build and starting the node:
```Error: Service(Client(Storage("Error parsing embedded file: missing field limits at line 200 column 5")))```

prior to the recent updates, the build never complained about missing data in the spec, therefore the question is, where is this introduced or how can we disable this or is it a breaking change we do not know about?

even though we cannot roll back to a previous state anymore, we would like to understand the problem and a correct migration path.

thanks in advance for any pointers, @NukeManDan
marco

**Comment by bkchr** [comment]
Did you update your nodes before trying the new wasm file with the new host function?

**Comment by 2075** [comment]
there aren't any new functions, we just wanted to bump the versions to prepare for our orml stuff. therefore we thought, uploading the new wasm would be sufficient. only the changed chainspec which seems to require a more verbose config of the contracts pallet caught our eye.

- run old node with old chainspec -> upload new wasm -> FATAL: Unable to initialize the API
- run new node with old chainspec -> Error parsing embedded file
- run new node with new chainspec -> node works, but breaks chainstate

isolated, both worked fine, to verify, i have built another vanilla node from substrate using the original chainspec which leads to above mentioned second error. therefore the confusion.

maybe i am missing something :) thanks!

**Comment by bkchr** [comment]
There are new host functions, that is the reason I mentioned this. You need to upgrade your old nodes before to provide this new host function.



>     * run new node with old chainspec -> Error parsing embedded file

This sounds like you don't use the raw chainspec? If you deploy any network, you need to use the raw chainspec! Otherwise it can break when you change your native runtime!

**Comment by 2075** [comment]
okay, understood. actually we somehow did not use the raw spec until now. therefore i double checked with a raw version of the original spec with our old chain and your mint 2.0.1 tagged version and it seems to work.

what would be the correct/recommended upgrade path, considering e.g. no added pallets or the same pallets with respective types/state exist in the old and the new version? is it possible at all to migrate between two different chainspecs like this, from the old 2.0.0 based, non raw spec to e.g. 2.0.1 with the raw spec?

as it is a testnet, it is meant to break, therefore i wouldnt mind to reboot the net once more, as the old state is lost anyway, but we need a feasible upgrade path for coming migrations.

thanks a lot for looking into this!

**Comment by bkchr** [comment]
You always keep the same genesis normally and just do runtime upgrades. If there are runtime upgrades that will use a new host function, you will need to update the nodes before applying the runtime upgrade on chain.

Migrating between chainspecs is not really possible, I'm also not 100% sure what you mean by this :D 

If this is solved, please close it.

**Comment by 2075** [comment]
Thanks, this is exactly how I understood it.

**Comment by AndreiNavoichyk** [comment]
Hey @bkchr 
We received the same error after applying the forkless upgrade with v3.0.0 to the network with v2.0.1.
Could you add more details about `you will need to update the nodes before applying the runtime upgrade on chain`? 
Thanks.
