### ISSUE TITLE
Panic after upgrading node-template from 2.0.1 to frontier 

### ISSUE THREAD

**Issue by lovesh** [paritytech/substrate#8028]
My node is forked off from [node-template directory](https://github.com/paritytech/substrate/tree/master/bin/node-template) of this repo. It (with chain spec `dev`) worked fine till version 2.0.1 but after upgrading to [frontier branch](https://github.com/paritytech/substrate/tree/frontier/bin/node-template), the dev node crashes on running with error

```
Thread 'main' panicked at 'assertion failed: frame_system::Module::<T>::inc_consumers(&account).is_ok()', .cargo/git/checkouts/substrate-7e08433d4c370a21/4888ac6/frame/session/src/lib.rs:447
```

Before the upgrade, in my runtime's `lib.rs` `construct_runtime` macro, I had `session` pallet declared before `balances` pallet like this

```
construct_runtime!(
    pub enum Runtime where
        Block = Block,
        NodeBlock = opaque::Block,
        UncheckedExtrinsic = UncheckedExtrinsic
    {
        System: system::{Module, Call, Config, Storage, Event<T>},
        RandomnessCollectiveFlip: randomness_collective_flip::{Module, Call, Storage},
        Timestamp: timestamp::{Module, Call, Storage, Inherent},
        Session: pallet_session::{Module, Call, Storage, Event, Config<T>},
        ......
        Balances: balances::{Module, Call, Storage, Config<T>, Event<T>},
```

But after moving `balances` pallet above `session` pallet, the panic doesn't occur. As per the docs of `construct_runtime`, the dependent pallet should follow the dependency but there is no dependency between `balances` and `session`. Are there other considerations when putting pallets in `construct_runtime!`? 
Here is my [code](https://github.com/docknetwork/dock-substrate/blob/new-substrate/runtime/src/lib.rs#L604), just in case.

**Comment by bkchr** [comment]
CC @shawntabrizi @thiolliere

**Comment by thiolliere** [comment]
>  but there is no dependency between balances and session.

The account in the keys in the genesis config of session must be existing accounts (i.e. it has an existential balance in balance module or whatever other provider of existence).
As your genesis config relies on pallet balances to make those account existing it is necessary for the session genesis config to be executed after balances genesis config.

(Maybe this can be improved by automatically give existential deposit to the session keys accounts, but I'm not sure of the real interest)

**Comment by lovesh** [comment]
Got it. Thanks

**Comment by thiolliere** [comment]
I guess we can close it, feel free to reopen if you have suggestion
