### ISSUE TITLE
ed25519-zebra

### ISSUE THREAD

**Issue by burdges** [paritytech/substrate#8055]
Are we using the [prehashed](https://docs.rs/ed25519-dalek/1.0.1/ed25519_dalek/index.html?search=prehash) variant of ed25519 anyplace?  If not, then we [should](https://hdevalence.ca/blog/2020-10-04-its-25519am) replace ed25519-dalek with [ed25519-zebra](https://github.com/ZcashFoundation/ed25519-zebra), which better supports batch verification. 

Ain't clear if ed25519-zebra ever wants features not required by zcash, so maybe we should do something else if we use the prehashed variant of ed25519 somewhere.  I once pointed @tomaka to its existence

**Comment by burdges** [comment]
Related lib https://github.com/hdevalence/ed25519consensus for the Go implementation

**Comment by burdges** [comment]
We never use the prehashed variant in substrate or polkadiot according to `grep -r --include "*.rs" _prehashed .` so..

We should go ahead and switch to ed25519-zebra whenever it's convenient.

**Comment by tomaka** [comment]
If I understand correctly, `ed25519-zebra` is a slightly-non-standard flavour of ed25519 that is more strict (and thus better)?

**Comment by burdges** [comment]
It's less strict and thus better.  :)

**Comment by burdges** [comment]
It's being worked on..

**Comment by gilescope** [comment]
Is this something the other polkadot implementations will also want to switch over to? (i.e. should there be some linked issues?)

**Comment by burdges** [comment]
Yes!  We definitely need all implementations to migrate to an equivalent ed25519.  It's straightforward to modify an ed25519 to be equivalent, just multiply by the cofactor when checking the verification equation.  Thanks for bringing this up.

**Comment by burdges** [comment]
We still need this, which requires updating https://github.com/paritytech/substrate/pull/8764.

We now need to understand the difference between ed25519-zebra and ed25519-consensus, which forked after 3 Dec 2020 --- commit https://github.com/ZcashFoundation/ed25519-zebra/commit/0e7a96a267a756e642e102a28a44dd79b9c7df69

https://github.com/penumbra-zone/ed25519-consensus/commits/main
https://github.com/ZcashFoundation/ed25519-zebra/commits/main

I'm personally inclined to stick with zebra because zcash is a more established player.  Also, we switched schnorrkel back off curve25519-dalek-ng recently, non-ng has many open issues & pulls https://github.com/dalek-cryptography/curve25519-dalek/issues but at least it has them so everyone knows the status of things.

**Comment by burdges** [comment]
We'll stick with ed25519-zebra so #8764 needs to be updated.
