### ISSUE TITLE
Unsigned transactions not respecting `longevity` value

### ISSUE THREAD

**Issue by nahuseyoum** [paritytech/substrate#8063]
Hello,
It seems like unsigned transactions are not respecting the `longevity` property and are always defaulting to immortal.

I have a pallet that is trying to send mortal unsigned_transactions like this:

```
ValidTransaction::with_tag_prefix("bla")
.priority(TransactionPriority::max_value())
.and_provides(vec![("Some data...").encode()])
.longevity(64_u64)
.propagate(true)
.build()
```
But polkadotjs is showing it as Immortal.

**Comment by bkchr** [comment]
`longevity` is only used for the tx-pool. What value have you set in your runtime `lib.rs` for `CheckEra`? 

In Substrate this is done here:
https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs#L775

Do you just copied this code? Or do you do something else?

**Comment by bkchr** [comment]
I just checked again with @jacogr. Actually the problem is that you are using an unsigned transaction that doesn't have any era information attached. So, the transaction will always be shown an immortal. It is the job of you as a runtime developer to return a proper value from the `unsigned_validate` function as you already do :) So, everything is fine.

**Comment by jacogr** [comment]
The UI is actually wrong/misleading - the transaction is unsigned, doesn't have an era so should not actually show the lifetime info for these.

**Comment by nahuseyoum** [comment]
Thanks, but as you can see from my code snippet, I am returning a proper value from `unsigned_validate` (64 blocks) instead of `TransactionLongevity::max_value()`. 

As far as i understand, passing `TransactionLongevity::max_value()` in `unsigned_validate` means the transaction is immortal, any other value means the transaction should be mortal. (https://github.com/paritytech/substrate/blob/9b08105b8c7106d723c4f470304ad9e2868569d9/primitives/runtime/src/transaction_validity.rs#L28). Unless unsigned_transactions do not have a concept of era and will disregard the `longevity` value passed in.

By the way I am using https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs#L775 without any modifications.

**Comment by bkchr** [comment]
> Thanks, but as you can see from my code snippet, I am returning a proper value from `unsigned_validate` (64 blocks) instead of `TransactionLongevity::max_value()`.

But the UI is not aware of this data. The UI uses the data that is attached to the transaction and in the case of an unsigned transaction there isn't any data attached. 

@jacogr already opened an issue to fix this visualization of unsigned transactions.

**Comment by nahuseyoum** [comment]
I see, so as far as the mem-pool is concerned, the value i passed will be respected. Thanks a lot for confirming.
