### ISSUE TITLE
SKIP_WASM_BUILD broken

### ISSUE THREAD

**Issue by brenzi** [paritytech/substrate#8067]
I'm trying to build our node with `SKIP_WASM_BUILD` for CI, but I get:

```
error: couldn't read /home/runner/work/encointer-node/encointer-node/target/release/build/encointer-node-notee-runtime-977d6aeb8c07b251/out/wasm_binary.rs: No such file or directory (os error 2)
 --> runtime/src/lib.rs:7:1
  |
7 | include!(concat!(env!("OUT_DIR"), "/wasm_binary.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `encointer-node-notee-runtime`
```

Shouldn't it be clear that no wasm is present with this flag? Or do I miss something?

**Comment by brenzi** [comment]
this regards commit a208da16

**Comment by bkchr** [comment]
@brenzi which version of the wasm-builder are you using?

**Comment by brenzi** [comment]
`		.with_wasm_builder_from_crates("2.0.0")`

**Comment by brenzi** [comment]
but I found
```
https://github.com/encointer/encointer-node/blob/e2e5c0a6f90f072c297c61879c28a41bb2c6e8c5/runtime/Cargo.toml#L49
```
as a remainder of the node-template I guess.

Our code:
https://github.com/encointer/encointer-node

**Comment by bkchr** [comment]
@brenzi could you please the latest `wasm-builder`. This also doesn't require anymore the `wasm-builder-runner`

**Comment by bkchr** [comment]
`SKIP_WASM_BUILD` should work there as you imagine it here in the issue ;)

**Comment by brenzi** [comment]
yes. upgrading wasm-builder fixed it. thank you!
