### ISSUE TITLE
Allow pallet to declare its default parts and make construct_runtime automatically use them by default

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#8084]
Instead of having to declare:
```rust
construct_runtime!(
...
Example: example::{Module, Storage, Call},
);
```
we could be able to do:
```rust
construct_runtime!(
...
Example: example all_parts_except::{Call},
// which would result in using `Module, Storage` in this example
);
```
(syntax must be improved)

a stale PR exist https://github.com/paritytech/substrate/pull/6494 but doesn't implement the `except_part` logic.

**Comment by KiChjang** [comment]
Are there any cases where a pallet part is included in a pallet, but the user doesn't want to declare it to be used? If not, then we could automatically declare the existence of a pallet part simply via the inclusion of its corresponding attribute, i.e. this pallet:

```rust
#[frame_support::pallet]
pub mod pallet {
    #[pallet::pallet]
    pub struct Pallet<T>(_);

    #[pallet::config]
    pub trait Config: frame_system::Config {}

    #[pallet::call]
    impl<T: Config> Pallet<T> {}
}
```

would automatically declare `Pallet`, `Call` and nothing else -- the `#[pallet::*]` attribute macros would automatically declare those parts. We can then remove the need for the user to explicitly declare pallet parts via the `decl_construct_runtime_args!` macro as implemented in #6494.

**Comment by thiolliere** [comment]
indeed I think `decl_construct_runtime_args!` of #6494 should be automatically generated by the pallet macro.

> Then if a user tries to use a non-existent pallet part during runtime construction, we could then generate a more helpful error message saying something like "Pallet does not contain #[pallet::genesis_config], declare one in order to include Config for the pallet in the runtime".

I also agree and on that, but that would be not possible to support in old decl_* macros, so as long as it is not deprecated I'm not sure how it can be implemented.

But in general yes I think pallet macro declares pallet items, those items are to be aggregated in construct_runtime.
I think forcing construct_runtime to read exclusively items declared by pallet macro, allows better error message and more consistent code.

Also I don't think we need to support declaration of parts for decl_* macros. no need to enhance decl_* macros, but we shouldn't break them IMHO

**Comment by thiolliere** [comment]
still relevant
