### ISSUE TITLE
Slashing: on-chain evaluation of misbehavior reports from the BFT and statement table subsystems

### ISSUE THREAD

**Issue by rphmeier** [paritytech/substrate#81]
...and automatically generate transactions with any witnessed misbehavior.

Should be simple enough:
  - Each misbehavior report must be accompanied by some security bond.
  - Each report contains a validator who misbehaved, the block hash they were building on when they misbehaved, and the proof of misbehavior
  - A report is valid iff the validator was a validator at the given block hash and the misbehavior given is true.

BFT misbehavior reports could be managed at the substrate level.
Parachain Statement Table misbehavior can only be managed in the polkadot runtime -- and will often require proofs of group membership at a block in recent history. We will need to make sure that all duty rosters within some range of history are computable.

**Comment by gavofyork** [comment]
@rphmeier i can help out on this regarding runtime logic and slashing, but will need help on logic for determining if "the misbehavior given is true"

**Comment by smisty** [comment]
What does that mean?
