### ISSUE TITLE
Remove Unsafe Pruning Flag

### ISSUE THREAD

**Issue by wpank** [paritytech/substrate#8103]
As of now, to run pruned nodes, you must use the flag `--unsafe-pruning`. Many people are running validators fine with pruning now. This should be removed.

**Comment by wi1dcard** [comment]
Hi @wpank , do you have any update on this issue? Is there an estimated time of removing the flag?

**Comment by mmyyrroonn** [comment]
Hi. @RGafiyatullin  I have a question here and hope you can shed some light on this. If all validators and watchers in the network are running in the pruned mode, for a new coming node(validator or watcher), is it able to sync the chain from scratch?

**Comment by bkchr** [comment]
Yes, pruning here is only about the state, not the blocks.

**Comment by mmyyrroonn** [comment]
> Yes, pruning here is only about the state, not the blocks.

oh. Thank you very much! Good to know

**Comment by RGafiyatullin** [comment]
The `--unsafe-pruning` emits an obsoletion-warning on the startup now.

This CLI-argument should be completely removed in some future release.

**Comment by RGafiyatullin** [comment]
[That](https://github.com/paritytech/substrate/issues/11380) will remove the CLI-argument completely.

For now it is left as an acceptable CLI-argument in order not to break the existing scripts that may launch the substrate.
