### ISSUE TITLE
Replace `let _ = ...` in the Runtime with `debug_assert!`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#8106]
Right now, many pallets in FRAME use `let _ = ...` for situations where we assume that a function cannot fail or where we can do nothing about a failure.

Some examples are:
* Trying to unreserve too much balance
* Over slashing
* Check then execute pattern on functions that return a result
* etc...

While it is possible that such states will appear in the actual runtime environment (for example a user is slashed, eating into reserved balance, and then unreserve would actually be more than available), within tests, this shouldn't really happen.

As such we should replace the following patterns in our codebase:

```
// It really should be reserved; there's not much we can do here on fail.
let _ = CurrencyOf::<T>::unreserve(&who, amount);
```

in favor of:

```
// It really should be reserved; there's not much we can do here on fail.
let err_amount = CurrencyOf::<T>::unreserve(&who, amount);
debug_assert!(err_amount.is_zero());
```

Or:

```
// Not much we can do if this fails...
let _ = T::Currency::transfer(&Self::account_id(), &winner, lottery_balance, KeepAlive);
```

for

```
// Not much we can do if this fails...
let res = T::Currency::transfer(&Self::account_id(), &winner, lottery_balance, KeepAlive);
debug_assert!(res.is_ok());
```

**Comment by Ethan-Pongon** [comment]
I'd like to take this task if I could have a mentor help me out as it's my first one.

**Comment by shawntabrizi** [comment]
@Ethan-Pongon I am happy to mentor you on this task.

You can message me on Riot or Discord under `@shawntabrizi`

**Comment by Ethan-Pongon** [comment]
@shawntabrizi Awesome, I'll get you added.

**Comment by shawntabrizi** [comment]
Shawn Tabrizi#2662

**Comment by hirschenberger** [comment]
This this still work in progress?

**Comment by shawntabrizi** [comment]
@hirschenberger I don't believe anyone is specifically doing this if you wanted to pick it up.

**Comment by hirschenberger** [comment]
Ok, I'm working on this. So the locations to change are in the `frame` directory but not within tests and benchmarks, right?

**Comment by shawntabrizi** [comment]
probably does need to change there too... if you have question about some specific case, let me know and I can confirm

**Comment by shawntabrizi** [comment]
#8398 solved some of these problems, but we need to fix other functions which were not directly listed.

Would be more of a "hunt the codebase" type actions.

**Comment by hirschenberger** [comment]
As I'm in, maybe I should just continue...

**Comment by shawntabrizi** [comment]
@hirschenberger totally up to you! What you did is correct, just need to hunt for all of them (to the best of your ability)

**Comment by hirschenberger** [comment]
@shawntabrizi  

I have some questions:

* It's only relevant to pallets in the frame directory?
* I can skip the benchmarks, bc. I don't want to either introduce overhead by using assert and they are never used in non-release code, so debug_assert would never be run?
* I can use assert instead if debug_assert in tests, as the runtime overhead does not matter?

**Comment by shawntabrizi** [comment]
* Yes only in the FRAME directory
* Benchmark tests run the same benchmark code, so debug assert should show up
* Yeah, in tests directly, assert should be used

**Comment by hirschenberger** [comment]
Hey @shawntabrizi 
I have a problem, I can't find a way to check a `SignedImbalance<u64, PositiveImbalance<mock::Test>>` like [here](https://github.com/paritytech/substrate/blob/fb8b68fbc54d6687008a6c9a080011f66edae5dd/frame/elections/src/tests.rs#L394)

How can I use the `peek` or `is_zero` functions on them?

**Comment by shawntabrizi** [comment]
@hirschenberger can you show me a specific piece of code you are trying to work on?

Looks like you want to do `.drop_zero().is_ok()` or similar.

Otherwise it may be that you simply need to add some peek functions to `SignedImbalance`.

**Comment by hirschenberger** [comment]
I left out the `let _ = Balances::make_free_balance_be` cases, as it's not always clear to me what the balance would be to test for.

**Comment by hirschenberger** [comment]
I think this can be closed as the PR is merged.
