### ISSUE TITLE
`check_inherent` implementation fails when validity depends on data in earlier inherent.

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#8108]
In some cases it makes sense that the validity of an inherent depends on data provided by an earlier inherent. The current implementation of `check_inherent` does not support this. Rather the inherents are checked in isolation. This means that the later inherent cannot be checked properly.

I have hit this case where one of my parachain inherents depends on data from the relay chain supplied by the parachain inherent. I expect this may be the case frequently for parachains.

**Comment by bkchr** [comment]
Can you please give more context?

Why depend the first inherent on the second one?

**Comment by JoshOrndorff** [comment]
I can offer two examples -- one minimal "toy" example, and one that we are currently using in Moonbeam. Both of them make sense in terms of being a cumulus parachain, and it is the parachain inherent that is depended upon.

## Block Mortality

I've sketched this https://github.com/purestake/cumulus/tree/joshy-inherent-question-example The inherent allows the parachan block author to include a maximum height for the relay parent. The inherent check compares the max height from the inherent to the actual relay parent height from the earlier parachain inehrent.

## Author Filtering

Parachain block authors insert their author identity via an inherent. Only some subset of staked authors are eligible at each height, so we perform some filtering logic and check whether the author from the inherent is indeed eligible at this height. It is desirable that filtering down the staked set to an eligible subset uses information from the relay parent (like the relay block height or the randomness beacon) because if it depends only on the parachain, then a colluding minority of authors could refuse to author and stall the parachain forever. Including "entropy" from the relay chain solves this because the eligible subset of authors will change at every block height.

This example is abstract over the filtering process. To make it concrete, assume we're using Aura. If it is Alice's turn to author, and she chooses not to, and the eligibility depends only on information from the parachain, then the parachain is stalled forever even though Alice is only one of many staked authors.

## Alternative ways to proceed

Having worked through creating both of these examples, I thought of a few viable alternative approaches. Maybe one of these is what I'm looking for.

* Do a simple preliminary check in `check_inherent` if possible, and delay the full check until block execution begins. This is what we're currently doing in Moonbeam and it seems realistic.
* Write a custom implementation for the `BlockBuilderApi`'s [`check_inherents` method](https://crates.parity.io/sp_block_builder/trait.BlockBuilder.html#method.check_inherents) that is not limited to checking them individually, but can inspect them arbitrarily

**Comment by JoshOrndorff** [comment]
Oh, that first toy example is stupid. The author already knows what relay parent his block is built on, so there is no need for an inherent to inject a maximum. I still think the second example and the general idea are valid.

**Comment by bkchr** [comment]
> Only some subset of staked authors are eligible at each height, so we perform some filtering logic and check whether the author from the inherent is indeed eligible at this height. It is desirable that filtering down the staked set to an eligible subset uses information from the relay parent (like the relay block height or the randomness beacon)

Why don't you have some callback mechanism as we have for timestamp for example? So whatever is set first, you check it in the callback and check the data.


Check inherents in general is also to check data like timestamp, but you don't need to check the author. Why isn't that done at importing the block?

**Comment by JoshOrndorff** [comment]
> callback mechanism as we have for timestamp for example? So whatever is set first, you check it in the callback and check the data.

That makes sense. I think that's what I meant in the first alternative I suggested .Thanks for the tip. I believe we're on the right track.

> Check inherents in general is also to check data like timestamp, but you don't need to check the author.

Okay, that makes sense. So for timestamp I want to check the timestamp that the author put in the block against my own local clock, and make sure they're reasonably close. But I wouldn't want to compare the author in the block to my own author id (especially since not all nodes will even be authoring). Is this what you mean?

Thanks for reading and helping me think through this.

**Comment by bkchr** [comment]
I mean you can check the author id when the block is imported :)

**Comment by JoshOrndorff** [comment]
Oh, now that I'm thinking about timestamp.

It seems reasonable to require that the timestamp of a parachain block is >= the timestamp of the relay parent block. Should this also happen at import time? Maybe I could do that by using the `OntImestampSet` callback?

**Comment by bkchr** [comment]
Timestamp will be based on the `slot` number of the relay chain. This means `slot * slot_duration` you get the timestamp.
