### ISSUE TITLE
Pallet contracts v3.0.0 isn't in crates

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#8146]
**Description**

Unfortunately, I've noticed that `pallet_contracts` wasn't uploaded into crates.io as others.

I guess the reason is wrong pallet version: 

https://github.com/paritytech/substrate/blob/master/frame/contracts/Cargo.toml#L3

**Comment by bkchr** [comment]
AFAIK this was done on purpose and it comes later.

CC @athei please correct me and close ;)

**Comment by athei** [comment]
This is correct and also stated in the release notes.

**Comment by akru** [comment]
I see, thank you for response @bkchr @athei ! Looking forward to contracts updates.
