### ISSUE TITLE
Add way to query back reserved nodes through JSON-RPC layer

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#8147]
Apparently some users want to be able to query back the reserved nodes that they passed through `--reserved-nodes` and added/removed through `addReservedPeer` and `removeReservedPeer`.

**Comment by h4x3rotab** [comment]
Indeed! Recently we are building a Substrate validator DevOps framework. We use `addReservedPeer` and `removeReservedPeer` to connect pair our nodes in the private network in a cluster, but there's no way to query the current reserved node list. It would be very useful.

Also chatted with @wpank about this idea. Quoted here:

> There's the `system_networkState` call, which dumps a lot of networking info about the state of the network from the nodes point of view, and then the `system_peers` rpc call, which shows the current peers the node is connected to. I imagine the reserved status can probably be added to the `system_peers` rpc call as a bool - something like reservedPeer: true or something like that. If this is a feature that would be really useful, best to add an issue to substrate

**Comment by tomaka** [comment]
`system_reservedPeers` :rocket:
