### ISSUE TITLE
Sparse parameter sets in benchmarking

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#8191]
When specifying complexity components and their ranges, the ranges are necessarily independent - you cannot make one range parameter depend on aonther. This fares badly in cases where there is a logical dependency and makes it difficult to benchmark in a sensible way.

Consider the function `foo`:

```
/// subcount should be less than count.
fn foo(count: u32, subcount: u32) {
  for i in 0..count {
    do_something();
    for j in 0..subcount.min(i) {
      do_something_else();
    }
  }
}
```

The ideal benchmarking code would be written:

```
{
  let c in 0 .. MAX_COUNT;
  let s in 0 .. c;
}: {
  foo(c, s)
}
```

But this is not currently possible.

The alternative:

```
{
  let c in 0 .. MAX_COUNT;
  let s in 0 .. MAX_COUNT;
}: {
  foo(c, s)
}
```

is problematic since there will be an accidental non-linearity for cases where `s > c` which won't work well with the linear regression analysis.

**Comment by shawntabrizi** [comment]
This should be doable now.
