### ISSUE TITLE
pallet-contracts-rpc 3.0 isn't uploaded into crates

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#8216]
**Description**

Thank you for the `pallet-contracts` updates. Unfortunately, https://crates.io/crates/pallet-contracts-rpc is still not updated. I'll be happy when it also will be uploaded.

**Comment by bkchr** [comment]
CC @athei @gnunicorn

**Comment by athei** [comment]
Oops. Yes this must have been an oversight. It should be released to crates.io.

**Comment by gnunicorn** [comment]
[Done](https://crates.io/crates/pallet-contracts-rpc).  Sorry about that.
