### ISSUE TITLE
duplicate lang item in crate `sp_io` 

### ISSUE THREAD

**Issue by transxask** [paritytech/substrate#8218]
i created my crate 'node constant', and compiled it  in this crate, it work. but when i use this crate in 'runtime', and the err occur.

there are my crate depency:
```
[package]
name = "node-constants"
version = "0.1.0"
authors = ["transxask <orwx71@163.com>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

node-primitives = {path = '../primitives', default-features = false, version = '2.0.0'}
[features]
default = ['std']
std = [
    "node-primitives/std",
]


```

and there are my runtine depency:
```
[dependencies]
node-primitives = {path = '../primitives', default-features = false, version = '2.0.0'}
node-constants = {path = '../constants', default-features = false, version = '=0.1.0'}
[features]
default = ['std']
std = [
   "node-constants/std",
    "node-primitives/std",
]
```
 error: duplicate lang item in crate `sp_io` (which `sp_application_crypto` depends on): `panic_impl`.
    |
    = note: the lang item is first defined in crate `std` (which `node_constants` depends on)
    = note: first definition in `std` loaded from /home/wjy/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libstd-4e755af785aa469c.rlib
    = note: second definition in `sp_io` loaded from /home/wjy/桌面/substrate-node-template/target/release/wbuild/node-template-runtime/target/wasm32-unknown-unknown/release/deps/libsp_io-f906c973f56d73ef.rmeta

  error: duplicate lang item in crate `sp_io` (which `sp_application_crypto` depends on): `oom`.
    |
    = note: the lang item is first defined in crate `std` (which `node_constants` depends on)
    = note: first definition in `std` loaded from /home/wjy/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libstd-4e755af785aa469c.rlib
    = note: second definition in `sp_io` loaded from /home/wjy/桌面/substrate-node-template/target/release/wbuild/node-template-runtime/target/wasm32-unknown-unknown/release/deps/libsp_io-f906c973f56d73ef.rmeta
```

**Comment by bkchr** [comment]
This means you are mixing dependency versions. You need to use the same git commit everywhere in your project.
