### ISSUE TITLE
Benchmarking CLI should have API to Return Available Benchmarks / Pallets for Automation

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#8225]
Benchmarking CLI should have some commands / API to tell the outside world what available pallets, benchmarks, and maybe even runtimes (strech goal for polkadot) are available to run.

This can be used inside of automated bots or tools to trigger all the benchmarks for a runtime automatically.

For example, when releasing a new version of Substrate, we should be able to do:

```
/benchmark runtime all
```

And it would know how to trigger all the benchmarks available in that runtime.

Something like:

```
cargo run --release --features=runtime-benchmarks -- benchmark --list
```

Returns:

```
pallet, benchmark
frame_system, remark
...
pallet_sudo, sudo
```

**Comment by stanly-johnson** [comment]
@shawntabrizi I can work on this. I think I should start by changing [this](https://github.com/paritytech/substrate/blob/master/utils/frame/benchmarking-cli/src/lib.rs) file?
