### ISSUE TITLE
Benchmarking CLI should allow `-` or `_` as delimiter

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#8226]
Right now, when running a benchmark, we string match the name of the pallet as configured in the `add_benchmarks!` macro.

This means to run a benchmark you need:

```
./target/debug/substrate benchmark --chain dev --execution wasm --wasm-execution compiled --pallet pallet_example --extrinsic '*' --steps 50 --repeat 20 --raw --output ./
```

Where `pallet_example` is used, not `pallet-example`.

Both could be easily supported, we just need to do some string manipulation somewhere in the pipeline to check for both forms of the name.

**Comment by hirschenberger** [comment]
Hi, I'd like to take this one to get my feet wet in substrate. Anything else to consider?

**Comment by hirschenberger** [comment]
If you don't want the whitespace changes, I can revert them. It was made by `rustfmt` when saving the file.
