### ISSUE TITLE
Publish substrate-test-runtime-client so we can write tests for custom RPC

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#8229]
Right now substrate-test-runtime-client is not published.
This means we can't use it write tests for custom RPC.

We should either publish test related crates or provide alternative solution for builders to write tests.

**Comment by bkchr** [comment]
This is a Substrate specific test runtime, that should not be published.

I don't understand why you not just write your own test runtime?

I think we could publish `substrate-test-client`, as this is some generic abstraction, but not more.

**Comment by xlc** [comment]
Maybe I am not asking for the right thing. My real request is be able to write tests for our custom RPC and by looking examples from Substrate, `substrate-test-runtime-client` is used and hence my request.

Maybe I should write my own test runtime and my own test client? It will be helpful if there are some examples.

**Comment by bkchr** [comment]
Can you not use your runtime?

At the beginning `substrate-test-runtime` was some very stripped down runtime. Nowadays it already contains a lot more code, probably too much.

Maybe a better question, why do you need a full runtime for your RPC? Can you not just pass some mock object into your RPC to test it?

**Comment by xlc** [comment]
It is probably me need to read more code to understand how it suppose to work... But some example will always be helpful.

This is the code I want to write test for https://github.com/AcalaNetwork/Acala/blob/master/modules/evm/rpc/src/lib.rs#L95-L101

We have defined our runtime API which is used by our RPC code.
Just wasn't sure the best way to create mocks that will get everything compile.

**Comment by bkchr** [comment]
There is https://docs.rs/sp-api/3.0.0/sp_api/macro.mock_impl_runtime_apis.html that will probably be helpful for you :)

**Comment by zjb0807** [comment]
I tried to implement RPC test like this:
https://github.com/paritytech/substrate/blob/a8c2bc66ea8667a1dcbafa13ce184b020bd6f84b/client/consensus/babe/rpc/src/lib.rs#L292-L301

The `TestClientBuilder` of `substrate-test-runtime-client` is required to generate the `client`, but the `client` does not implement `EVMApi`.

Is there any way to implement the RPC unit test?

**Comment by bkchr** [comment]
I don't know what your rpc takes as arguments etc.

And as I already said above, you should not use the substrate-test-runtime-client outside of substrate.
