### ISSUE TITLE
can't start substrate in dev mode

### ISSUE THREAD

**Issue by CremaFR** [paritytech/substrate#8268]
Hello,

I can't start a chain in dev after following the documentation on macOs
I tried to find issues on this but I'm clueless i only found #5858

version:
cmake 3.19.6
pkg-config 0.29.2_3 
openssl@1.1 1.1.1j
llvm 11.1.0
rustc 1.50.0
macOs v11.1

    substrate % cargo run --release -- --dev                  
        Finished release [optimized] target(s) in 1.33s
         Running `target/release/substrate --dev`
    2021-03-04 12:06:26  Running in --dev mode, RPC CORS has been disabled.    
    2021-03-04 12:06:26  Substrate Node    
    2021-03-04 12:06:26  ✌️  version 2.0.0-8fc92d1d7-x86_64-macos    
    2021-03-04 12:06:26  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021    
    2021-03-04 12:06:26  📋 Chain specification: Development    
    2021-03-04 12:06:26  🏷 Node name: workable-competition-9669    
    2021-03-04 12:06:26  👤 Role: AUTHORITY    
    2021-03-04 12:06:26  💾 Database: RocksDb at /Users/thomasbrillard/Library/Application Support/substrate/chains/dev/db    
    2021-03-04 12:06:26  ⛓  Native runtime: node-265 (substrate-node-0.tx2.au10)    
    Error: Service(Client(Backend("Unsupported database version: 0")))

Additionally there is a test that fails I don't know if it might be related to the database error I have

    test tests/derive_no_bound_ui/eq.rs ... mismatch
    
    EXPECTED:
    ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
    error[E0277]: can't compare `Foo<T>` with `Foo<T>`
       --> $DIR/eq.rs:6:8
        |
    6   | struct Foo<T: Config> {
        |        ^^^ no implementation for `Foo<T> == Foo<T>`
        |
        = help: the trait `PartialEq` is not implemented for `Foo<T>`
    ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
    
    ACTUAL OUTPUT:
    ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
    error[E0277]: can't compare `Foo<T>` with `Foo<T>`
       --> $DIR/eq.rs:6:8
        |
    6   | struct Foo<T: Config> {
        |        ^^^ no implementation for `Foo<T> == Foo<T>`
        |
       ::: $RUST/core/src/cmp.rs
        |
        | pub trait Eq: PartialEq<Self> {
        |               --------------- required by this bound in `Eq`
        |
        = help: the trait `PartialEq` is not implemented for `Foo<T>`
    ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
    note: If the actual output is the correct output you can bless it by rerunning
          your test with the environment variable TRYBUILD=overwrite
    
    test tests/derive_no_bound_ui/partial_eq.rs ... ok
    
    
    test derive_no_bound_ui ... FAILED
    
    failures:
    
    ---- derive_no_bound_ui stdout ----
    thread 'derive_no_bound_ui' panicked at '1 of 4 tests failed', /Users/thomasbrillard/.cargo/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.39/src/run.rs:57:13
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    
    
    failures:
        derive_no_bound_ui
    
    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 3.94s
    
    error: test failed, to rerun pass '-p frame-support-test --test derive_no_bound_ui'

**Comment by bkchr** [comment]
Run `cargo run --release -- purge-chain --dev` and try again. The test failures are not related.
