### ISSUE TITLE
Consistent `Pallet` and `Module` naming

### ISSUE THREAD

**Issue by shaunxw** [paritytech/substrate#8287]
In pallet attribute macro, `Module` struct is renamed to `Pallet`, but there are still some places using the name `Module`. For instance in `construct_runtime` macro: https://github.com/paritytech/substrate/blob/88014d553fc1c0f1b1f4c6da1c8d6d16b32ac7f0/bin/node/runtime/src/lib.rs#L1080

and `DispatchError::Module` etc: https://github.com/paritytech/substrate/blob/88014d553fc1c0f1b1f4c6da1c8d6d16b32ac7f0/primitives/runtime/src/lib.rs#L405

They should be renamed to `Pallet` to make it consistent and less confusing.

**Comment by thiolliere** [comment]
Currently pallet macro do write: `type Module<T> = Pallet<T>;` in order not to break construct_runtime.

Now we can update construct_runtime to use Pallet struct, make decl_module generate the type alias `type Pallet<T> = Module<T>`, and deprecated the type alias in pallet macro.

For other occurences of Module we need to renames types and fields.

**Comment by thiolliere** [comment]
there is still DispatchError module variant which could be replaced to Pallet, but at some point DispatchError is not part of FRAME, thus I'm not sure it makes sense to rename.

There is also metadata types which says: ModuleMetadata and ModuleConstantMetadata, etc.. but it is pretty minor IMO

**Comment by shaunxw** [comment]
IMHO if they refer to the same thing, ideally the same term/naming should be used. I totally agree they are minor and low priority.

**Comment by kianenigma** [comment]
Both Metadata and DispatchError are none-frame concepts, so I guess it is fine to keep them as they are now. 

Although for the metadata, it is reasonable to say that the Metadata of a frame based chain would internally use `Pallet` etc. But if `ModuleMetadata ` are terms that any runtime would have, they should use `Module`.

**Comment by shaunxw** [comment]
I see, so "pallet" is only for inside FRAME, and outside FRAME it still is "runtime modules".
