### ISSUE TITLE
Bump version 2 -> 3 for pallets?

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate#8293]
The devhub is [updating everything to v3.0.0](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues?q=is%3Aissue+is%3Aopen+label%3Av3-tutorial-update) and there are still some pallets that are v2.0.0 - what needs to be done to have them formally upgraded to 3.0.0? I see some pallets don't use FRAME v2 macros but are marked as v3 in substrate.

Specific examples that are still v2.0.0 :
- https://github.com/paritytech/substrate/blob/master/frame/node-authorization/Cargo.toml
  - (blocking [this docs update](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/888))
- https://github.com/paritytech/substrate/blob/master/frame/example/Cargo.toml
- https://github.com/paritytech/substrate/blob/master/frame/example-parallel/Cargo.toml
- https://github.com/paritytech/substrate/blob/master/frame/example-offchain-worker/Cargo.toml

I know that publishing to crates.io is required for others to set the correct version as well.

**Comment by xlc** [comment]
I think semvar is used so major version bump only happens if there is breaking change.

But I can see this is going to be messy because every pallets will have different version number and unrelated to FRAME version...

**Comment by NukeManDan** [comment]
IMHO every major release should bump _every_ dependency to the latest released version to keep the entire substrate library on the same base know-to-work version throughout the codebase. I was under the impression this was the strategy (breaking change or not). Otherwise you will have to manually upgrade each breaking change, instead of just bumping everything (and troubleshooting your breakages)

**Comment by bkchr** [comment]
The example pallets make no sense to bump. They are not published anyway.

`node-authorization` was missed 100% cc @gnunicorn

**Comment by NukeManDan** [comment]
examples are not published on crates.io - but for consistency in the whole of substrate, can we bump them to 3.0.0 to avoid confusion?

**Comment by kianenigma** [comment]
I am still waiting for the day in which pallets have their own individual release, version and changelog, and we use the crate version for migrations.

**Comment by bkchr** [comment]
Me as well :)

**Comment by kianenigma** [comment]
These crates have not changed, and thus will not be bumped.
