### ISSUE TITLE
Detailed memory usage report

### ISSUE THREAD

**Issue by arkpar** [paritytech/substrate#830]
Major memory consumers should track memory usage and that should be printed in the informant periodically and reported to telemetry. This includes

- [x] RocksDB cache size
- [x] state-db pruning and finalisation overlays
- [ ] libp2p buffers?
- [x] Block queue
- [x] Consensus and gossip message store
- [x] Transaction queue

**Comment by gavofyork** [comment]
This is also a candidate for #814

**Comment by guanqun** [comment]
use heapsize's heap_size_of_children?

**Comment by arkpar** [comment]
> use heapsize's heap_size_of_children?

Probably. Except for RocksDB that has its own API for reporting memory usage.
