### ISSUE TITLE
Traces for hooks not implemented

### ISSUE THREAD

**Issue by JesseAbram** [paritytech/substrate#8303]
Base on this [comment](https://github.com/paritytech/substrate/pull/8209#discussion_r590191692) 

The trace_span in hooks in dispatch.rs does not implement trace.

As well, a nice touch would be to have the module name in the traces as per this [comment](https://github.com/paritytech/substrate/pull/8209#discussion_r588815223)

**Comment by thiolliere** [comment]
to give more understanding the pallet attribute macro doesn't do traces contrary to decl_module.

cc @emostov

**Comment by dvdplm** [comment]
> The trace_span in hooks in dispatch.rs does not implement trace.

Do you mean the other way around? The old macros had the spans and the new ones do not?

> This happens for hooks: on_initialize, on_finalize, .... and also dispatchables.

This is a bit concerning, sounds like all the traces are missing atm? Is there a tracking ticket for this (or is this it?)?

**Comment by thiolliere** [comment]
I opened https://github.com/paritytech/substrate/pull/8305
I think @emostov  is working on dispatchables
