### ISSUE TITLE
Backing off claiming new slot for block authorship: finality is lagging.

### ISSUE THREAD

**Issue by Daelon02** [paritytech/substrate#8328]
Hi everyone, we have a problem
When we trying add new validator, we have this error 
`Backing off claiming new slot for block authorship: finality is lagging.`

**Comment by bkchr** [comment]
Can you please stop to open the same issue multiple times.TY

**Comment by Daelon02** [comment]
> 
> 
> Can you please stop to open the same issue multiple times.TY

Why throw this error?

**Comment by bkchr** [comment]
You have opened the same issue already today.

**Comment by Daelon02** [comment]
> 
> 
> You have opened the same issue already today.

I know, but she was removed

**Comment by bkchr** [comment]
No the issue was moved to a proper place for this kind of issue.

**Comment by Daelon02** [comment]
> 
> 
> No the issue was moved to a proper place for this kind of issue.

Please tell me where exactly?

**Comment by aramakam3505** [comment]
Hi , Where can i get solution for this issue??? I am facing the similar problem.

**Comment by Daelon02** [comment]
> Hi , Where can i get solution for this issue??? I am facing the similar problem.

You need more validators than you have

**Comment by aramakam3505** [comment]
@Daelon02 It was working fine with 1 validator and faced that error when there are 2 validators.....

**Comment by aramakam3505** [comment]
@Daelon02 It was working fine with 1 validator and faced that error when there are 2 validators.....

**Comment by Daelon02** [comment]
> @Daelon02 It was working fine with 1 validator and faced that error when there are 2 validators.....

You need more 2 validators, only dev can work with 1 validator

**Comment by 17akash** [comment]
> > @Daelon02 It was working fine with 1 validator and faced that error when there are 2 validators.....
> 
> You need more 2 validators, only dev can work with 1 validator

i have 2 more validators and i am also facing the same issue ,my block finalisation is stopped and new block generation time is increased , is there any way to resolve this issue without purging the blockchain

**Comment by maybeTomorrow** [comment]
same issuse，
