### ISSUE TITLE
Remove git dependency during build

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#8334]
Currently a proper build requires git to get commit hash. But I would like to exclude .git folder from our docker build while stilling having git commit in version. Should offer an environment variable to specify the git commit and fallback to use git rev-parse.

https://github.com/paritytech/substrate/blob/1e045f218db16027197dc11ac04220896321260f/utils/build-script-utils/src/version.rs#L23-L25

**Comment by bkchr** [comment]
Nothing of this is backed into substrate. We use this to generate the `SUBSTRATE_CLI_IMPL_VERSION` build env variable that itself is used by the node example implementation to expose this to the cli interface. You can just write your own build script that does whatever you want :)
