### ISSUE TITLE
Put the boostrap nodes behind a DNS

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#835]
Libp2p supports multiaddresses in the format `/dns/example.com/tcp/30333`, so we could put the bootstrap nodes behind a DNS.

**Comment by arkpar** [comment]
DNS is subjectible to hijacking and DDoS. Security implications should be considered first.

**Comment by tomaka** [comment]
> DNS is subjectible to hijacking 

We pass the peer id as part of the address, so that shouldn't be an issue.

**Comment by tomaka** [comment]
I suppose that this is more of a devops issue rather than a Substrate issue. Substrate itself supports DNS address.

Closing.
