### ISSUE TITLE
Update `FixedPointNumber` and other Arithmetic with Proper Names

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#8364]
https://github.com/paritytech/substrate/pull/8327 introduced a better naming for functions across `PerThing`.

The same naming should be applied to all the other helpers and utilities within Substrate Arithmetic.

cc @kianenigma

**Comment by kianenigma** [comment]
I checked the names now and this is mostly done, there is just one function name that needed fixing. I'll do this as a part of another PR.
