### ISSUE TITLE
Node become no peers over time and stops syncing

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#8366]
We have deployed an Acala testnet with 1 bootnode, 3 validators, 1 rpc node. Over past week we have experienced twice that the bootnodes & validators peer count drop to zero and stops the network.

After enabled more logging, I can only find this suspect

```
TRACE tokio-runtime-worker peerset: Report 12D3KooWKT28BbijF1Wjee6AHK3AbDVn4zhUdq9P6aM96SMkST6d: -4 to 12421. Reason: Duplicate gossip
```

Is this expected? Anything specific I should look for on diagnostic this issue?

cc @tomaka

**Comment by bkchr** [comment]
Do you have this https://github.com/paritytech/substrate/commit/97ecd629aff816c15cfff7e73d34dc8c9c5c6a9b commit in your node?

**Comment by xlc** [comment]
The commit is 4 days ago and our testnet launch a week ago so I don’t think we have it.

Will update & redeploy.

**Comment by bkchr** [comment]
If you used https://github.com/paritytech/substrate/commit/7e5c30709d0d6bae01e1eb9412d17cdf1620af7d in your test network, this would explain it and this would be fixed by this other commit mentioned above :D

**Comment by shaunxw** [comment]
It seems https://github.com/paritytech/substrate/commit/97ecd629aff816c15cfff7e73d34dc8c9c5c6a9b is not in Substrate `rococo-v1` branch. @bkchr Could you please help to merge master into it?

**Comment by bkchr** [comment]
I will do this, however the rococo branch also does not contains the problematic commit.

**Comment by xlc** [comment]
Right. We were using Substrate master but now switched to rococo-v1. So should be fine on our side now.

**Comment by shaunxw** [comment]
We're using the latest Substrate rococo-v1, but still have this message @xlc mentioned above:

> TRACE tokio-runtime-worker peerset: Report 12D3KooWKT28BbijF1Wjee6AHK3AbDVn4zhUdq9P6aM96SMkST6d: -4 to 12421. Reason: Duplicate gossip

As latest rococo-v1 doesn't include https://github.com/paritytech/substrate/commit/7e5c30709d0d6bae01e1eb9412d17cdf1620af7d , this issue might not be related to it.

It seems that the repeating duplicated gossip messages keep peer reputation going down until disconnection. https://github.com/paritytech/substrate/blob/211be1d5f477fa025f7813238b95a1524ad4212f/client/network-gossip/src/state_machine.rs#L340-L344

**Comment by bkchr** [comment]
Any idea which gossip is duplicated?

**Comment by tomaka** [comment]
> It seems that the repeating duplicated gossip messages keep peer reputation going down, and finally caused disconnection with all peers. 

The reputation decrease is so low that this can't realistically cause a disconnect, until we're being sent gigabytes per second.

**Comment by xlc** [comment]
The issue is not happening anymore and double check the logs I found out it was #8260 causing the trouble.

The duplicated gossip did not decrease the reputation to the level of disconnecting.

Will close for any and continuing monitor our testnet logs.
