### ISSUE TITLE
Provide inherent data is called for non-validators

### ISSUE THREAD

**Issue by jflatow** [paritytech/substrate#8377]
We have an inherent (https://github.com/compound-finance/gateway/blob/develop/pallets/cash/src/internal/miner.rs#L66-L85) which seems to be called whether the node is a validator or not - our understanding is that create inherent / provide inherent data should not be called unless the node is actually authoring a block, is there something wrong with out setup?

**Comment by bkchr** [comment]
This called when we call `check_inherents`. So, completely fine.
