### ISSUE TITLE
DispatchError changes after encoding and then decoding

### ISSUE THREAD

**Issue by shaunxw** [paritytech/substrate#8400]
If we have a `DispatchError::Module` variant like this:

```rust
DispatchError::Module { index: 1, error: 1, message: Some("foo") }
```

After encoding and then decoding, it will become different:

```rust
DispatchError::Module { index: 1, error: 1, message: None }
```

IMHO it needs be fixed as in general variables should be the same. It could cause troubles while doing equal assertion. Like in ORML unit tests, when a event contains `DispatchError`, comparing the built even in test function with `System::events()` results unexpected unequal, unless with a manual conversion like [here](https://github.com/open-web3-stack/open-runtime-module-library/blob/65cb2e986217cad9c89e974d9f09ba7bbfc4a2df/unknown-tokens/src/tests.rs#L36-L38).

**Comment by bkchr** [comment]
This is done by intention, because we don't want to store the `message` on chain.

I'm open to accept a pr that changes the `PartialEq` to ignore `message`.
