### ISSUE TITLE
pallet-timestamp: broken links to timestamp::Config, Call, and Pallet

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate#8426]
when i go to the v3.0.0 docs for pallet_timestamp, these links appear to be broken:

* timestamp::Config
* Call
* Pallet

https://substrate.dev/rustdocs/v3.0.0/pallet_timestamp/index.html

but for v2.0.0 those links work at https://substrate.dev/rustdocs/v2.0.0/pallet_timestamp/index.html

**Comment by thiolliere** [comment]
should be fixed by https://github.com/paritytech/substrate/pull/8437
