### ISSUE TITLE
Move `Schedule` from storage to the `Config` trait

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#8433]
The `Schedule` is a struct that sees a lot of changes to its fields. The main reason is that every new contract callable function needs a new field. For this reason we made its fields private in #8359. Otherwise we would be burning through major version numbers every time we **add** a new function. This is not enough, though. Because the `Schedule` is in storage and also a parameter to the `update_schedule` dispatchable it is still exposed as a public API.

In order to solve this issue we remove the `Schedule` from storage and instead make it configurable through the `Config` type. This will drop the functionality to update the `Schedule` without a runtime upgrade, though. I argue that this feature wouldn't be that useful because the weight prices are already automatically adjusted depending on chain utilization. Larger changes would need some code changes in most cases. Any objections @pepyakin ?

- [x] Remove the `CurrentSchedule` item from the pallet.
- [x] Add storage migration which removes it from storage.
- [x] Add the `Schedule: Get<Schedule>`  as an associated type to `Config`
- [x] Enable `debug_println` when called via RPC instead of relying on a genesis config as a toggle.
- [ ] Make `Schedule` fields public in order to allow customization.

Making the fields private does not help us with avoiding major version bumps because the public `WeightInfo` trait still needs to change. We just accept the fact that we will have new major version numbers and expect runtimes to bump the version number and re-run benchmarks. Most of the time that will be everything that is to it.

Partly fixed by #8359 and #8773

**Comment by pepyakin** [comment]
That makes sense.
