### ISSUE TITLE
Unresolved Import

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/substrate#8438]
I'm not sure how to resolve this issue. I'm getting an unresolved import message for the line below. Can anyone help me out? Thanks!

<img width="1054" alt="Screen Shot 2021-03-23 at 2 37 11 PM" src="https://user-images.githubusercontent.com/62865359/112200210-639df500-8be5-11eb-9002-2733f01e390b.png">

**Comment by J-Cook-jr** [comment]
I also tried removing the braces but then I got this:

<img width="1054" alt="Screen Shot 2021-03-23 at 2 37 11 PM" src="https://user-images.githubusercontent.com/62865359/112200593-c2fc0500-8be5-11eb-96ea-ea493b30b8de.png">

**Comment by J-Cook-jr** [comment]
Sorry about the last issue, but this is actually what happened when I deleted the braces:

<img width="1050" alt="Screen Shot 2021-03-23 at 2 40 21 PM" src="https://user-images.githubusercontent.com/62865359/112200678-d7400200-8be5-11eb-94df-c2b8de8e6b32.png">

**Comment by bkchr** [comment]
This is some rust-analyzer error message that are not always correct. Please don't open issues for such stuff.

**Comment by J-Cook-jr** [comment]
Ok, thanks for letting me know @bkchr
