### ISSUE TITLE
Rename `generate_solution_type!` such that it shows exactly the types

### ISSUE THREAD

**Issue by kianenigma** [paritytech/substrate#8444]
This is an example of a solution type generation: 

```
sp_npos_elections::generate_solution_type!(
	#[compact]
	pub struct NposSolution16::<u32, u16, sp_runtime::PerU16>(16)
	// -------------------- ^^ <NominatorIndex, ValidatorIndex, Accuracy>
);
```

The fact that I have to document it, and double check it is exactly showing the issue here. the syntax of the macro should be such that it clearly shows these. After all, the entire `::` and `<_>` is fake and I am manually parsing it. Maybe something like 

```
sp_npos_elections::generate_solution_type!(
	#[compact]
	pub struct NposSolution16::<Voter = u32, Target = u16, Accuracy = sp_runtime::PerU16>(16)
);
```

**Comment by kianenigma** [comment]
@coriolinus unassign if not suitable, I think it is a good way to get familiar with `generate_solution_type` a wee bit more.

**Comment by coriolinus** [comment]
Sure, it seems suitable. The proposed syntax seems good to me. 

It's worth noting that last week there was a separate discussion (which I'm having trouble finding now) in which similar keyword-style generic arguments were proposed, and some people felt pretty strongly that they were confusingly different from standard Rust syntax. I'm not convinced that that's a strong reason not to use this syntax, but the PR will need to ensure that the macro's documentation contains both a description of what's going on and an example.

**Comment by kianenigma** [comment]
The syntax here is pretty arbitrary and we can parse anything. Also, this will not be used extensivelty, so it need not be "valid rust". Important thing is to make sure while you are writing it, you won't mix `VoterIndex` and `TargetIndex`, which is a deadly flaw.
