### ISSUE TITLE
after network reset fresh nodes sync from idle node from old chainspec (again)

### ISSUE THREAD

**Issue by 2075** [paritytech/substrate#8469]
hey, it's me, chainbreaker, again

after like 1,350,000 blocks some users reported that after like around 850 blocks their nodes stop syncing with an error message like this:

```
zero-node    | 2021-03-26 07:25:27  :broken_heart: Verification failed for block 0xebb1bdbd83ef88a0e410dc0a9f5c563c6d29c48adac90654fd9915a3e4942cc4 received from peer: 12D3KooWL9grAK87VT7JmWzXaRNz5V3jpX3uffHUEGeaDET8m5NB, "Execution failed: ApiError("Could not convert parameter block between node and runtime: Could not decode Block::extrinsics:\n\tCould not decode Call::GameDAOCrowdfunding.0:\n\t\tCould not decode Call::create.7:\n\t\t\tNot enough data to fill buffer\n")"
```

it seems, when i reported last time issues on our chain regarding panics that after upgrading the nodes something went wrong unnoticed, as the node count did not really change for a while.

after testing this with a fresh node, we got the same result, so initiated a network reset, which did not quite work out due to some nodes not upgrading and resetting their nodes.

when starting the fresh nodes, everytime they sync the old state from one idle node, even a new generated chainspec did not change this behaviour, as well as setting a new name for the protocol in chainspec (just more like a guess).

last effort was to start with a spec with only one validator set, but even then when opening ports this one synced from the old chain.

what can we do here to avoid syncing with stall / idle / malicious nodes in such situation?

in total this is the third time already that happened to us. 

thanks much for input!

**Comment by bkchr** [comment]
This means you don't have done handled the `spec_version` properly. There is probably some mismatch between native and wasm.

Try running with `--execution wasm`, it should fix it.

**Comment by 2075** [comment]
hm, we *always* increase spec for major and impl for minor changes at the moment, like semver.
![image](https://user-images.githubusercontent.com/1140449/112733277-2fa53580-8f3f-11eb-8917-877fe774c62b.png)

the running chain was on 10.2, previously upgraded with the wasm blob and later on upgraded through updated docker nodes. therefore people running nodes always use a "latest" tag.

regarding `--execution wasm`:  does it signal to use the onchain runtime vs the one delivered in the image?

thx

**Comment by 2075** [comment]
to me it is just weird to see this when all nodes are down: 
![image](https://user-images.githubusercontent.com/1140449/112733418-3e401c80-8f40-11eb-8604-9a5e803d4f66.png)

and when we start fresh bootnodes and validators, they sync with the idle node shown above. so maybe i am discussing two issues it seems. :)

**Comment by bkchr** [comment]
> regarding `--execution wasm`: does it signal to use the onchain runtime vs the one delivered in the image?

We always use the on-chain wasm. However, it could also use the native runtime.

Please just try this.

**Comment by 2075** [comment]
thanks, this helped to let the fresh node sync without errors.

now it seems like we have something new on top:

```
subzero    | 2021-03-28 13:48:34  Detected prevote equivocation in the finality worker: Equivocation { round_number: 1074137, identity: Public(05c3d476933158a48810944ff5b746316b1ec652493777662ee7aaba8f889c94 (5CCGGdHu...)), first: (Prevote { target_hash: 0x5cfe8531a51363dd156e6053a777c3a3d238f6e19069a7b37a625083c3ab3f62, target_number: 1320354 }, Signature(6dfaee92aca3f1aba2ebfb6ac42bdf37a96a4c87f8fe007e4adcfd176fd8f5df984f21d85102912277d4a3859086095f9e70f0f3b4c90c9e96bbaacb21407309)), second: (Prevote { target_hash: 0x53e571016abde0c1edc24d4818d3bd6f98297252eba2f03270096e9862792830, target_number: 1320357 }, Signature(2b6e2bcae5a86a7ab0b65a06002b928cd0dc9c2defd2907b063c9f2505ec849d7fb61ce35561e3b373a39d2ece151f6d1cb73ae63994aae2c43cf6b57a24880c)) }
subzero    | 2021-03-28 13:48:35  🔍 Discovered new external address for our node: /ip4/159.100.246.86/tcp/30333/p2p/12D3KooWDiWDSEsfyq62tR43DU2ToaQ5tAh4C4BsQk5Dmf7F2aPf
subzero    | 2021-03-28 13:48:36  Detected prevote equivocation in the finality worker: Equivocation { round_number: 1074137, identity: Public(5671a38f0686dcf850909dac3a571cfd49db420f2b115faa14a48b1f9151c12a (5E23jUEV...)), first: (Prevote { target_hash: 0x571c3cd7f63db5e13c4726bade7163ef5ebf7e2fc38ac1fea7b475142a90a09a, target_number: 1320356 }, Signature(2f97a2d581833324bad5a230fb578709c90c0a856340163c79098b5021ca415e8d9a69208db27cedcc40bea081ee069a3ba83def13d95cfce4ac681b35a7d107)), second: (Prevote { target_hash: 0x53e571016abde0c1edc24d4818d3bd6f98297252eba2f03270096e9862792830, target_number: 1320357 }, Signature(806f20300dda4fc8aa596836d4462a5763d3e6de1e6a2cec5b5b3ffb49afe48f848f31240c27a5813801c8a38c52ba772408bdc0ca6ffbf3f19628cc04bf120a)) }
```

**Comment by bkchr** [comment]
This means you have two nodes running with the same keys.

**Comment by 2075** [comment]
hm, impossible :) the three nodes are completely separate, including their respective key sets. 
at the end it seems the chain was bricked, latest error was unexpected epoch change.
so we decided to not spend any more time figuring out repairs.
thanks again!

**Comment by 2075** [comment]
-> question remaining is: how to avoid new nodes syncing void state from old nodes.

**Comment by bkchr** [comment]
> how to avoid new nodes syncing void state from old nodes.

Not sure what you mean by this

**Comment by 2075** [comment]
...this was my initial question... *sigh*

already happened three times since last summer:

we tried to reset the network, one node was still running with the full blockheight. when starting new bootnodes and validators, all synced the state of that idle node. then we changed the chainspec and tried various things: different spec/impl - still synced, different chainspec still synced, different protocol id - still synced. this should not happen from my understanding.

**Comment by bkchr** [comment]
If you have a different genesis hash, they will not sync from the old node.

So, this means you did not generate a proper new genesis chain spec. Just purging and restarting the nodes, doesn't change the genesis hash.

**Comment by 2075** [comment]
works now as expected, thanks!

**Comment by JosephKnecht-lab** [comment]
I faced the same problem. I had two nodes running with the same keys. 

For someone who might encounter this problem in the future, this is the best way to reset your chain.

- Delete /target in substrate-node-template (this removes all the files from tmp/ so that you can start from a clean state)

- Build your chain with: cargo build --release

- Start your nodes again...
