### ISSUE TITLE
Solve the --no-private-ipv4 situation

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#8490]
The `--no-private-ipv4` option really should be enabled by default for live chains, but if we always enable it by default, then starting a chain locally wouldn't work anymore.

**Comment by coriolinus** [comment]
Would it be reasonable to enable `--no-private-ipv4` by default _unless_ `--dev` is present?

**Comment by bkchr** [comment]
No. `--dev` is single node anyway.

**Comment by tomaka** [comment]
Done in https://github.com/paritytech/substrate/pull/8642
