### ISSUE TITLE
Crash after 1 day

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#8499]
```
Thread 'tokio-runtime-worker' panicked at 'assertion failed: false', /home/jasl/.cargo/git/checkouts/substrate-7e08433d4c370a21/1404f2a/client/network/src/protocol/notifications/behaviour.rs:1720
```

https://github.com/AcalaNetwork/Acala/issues/851

Using commit https://github.com/paritytech/substrate/commit/1404f2af4cbe90d35b4c8a1405a9452feb789adc

**Comment by arkpar** [comment]
@tomaka

**Comment by tomaka** [comment]
Note that this is a `debug_assert!`. It won't happen if you compile with `--release`.

**Comment by tomaka** [comment]
I'm confident that I fixed this and forgot to link to this issue.
