### ISSUE TITLE
Missing Error declaration in some pallets

### ISSUE THREAD

**Issue by h4x3rotab** [paritytech/substrate#8501]
Now if we check `rpc.state.getMetadata`, there are a lot of pallets without error declarations populated in metadata it returns. We have checked Phala PoC3 and Polkadot (at the latest block, and block 1000). All of them have this problem.

For example, if you search "Indices" pallet, and find the `errors` field in its entry, it shows:

```json
          errors: [],
          index: 4
```

This will cause errors in polkadotjs and subxt whenever they decode a block with the errors from these bad pallets.

However, not all the pallets have this problem. We checked around the definition of the bad pallets and good pallets, and found all the bad pallets forgot to declare the error inside `decl_module!`. So we suspect this is the root cause. Now we cannot dedicate some time for further testing. So I just created this issue and leave it as a record.

Good example:

https://github.com/paritytech/substrate/blob/88243c11d67baeaa27057118db10135dad6e7df5/frame/recovery/src/lib.rs#L325-L327

Bad example:

https://github.com/paritytech/substrate/blob/88243c11d67baeaa27057118db10135dad6e7df5/frame/indices/src/lib.rs#L105-L111

A full list of the good pallets (by grep `type Error = Error<T>` in the frame directory):

```
substrate/frame/assets/src/lib.rs:
substrate/frame/atomic-swap/src/lib.rs:
substrate/frame/authorship/src/lib.rs:
substrate/frame/balances/src/lib.rs:
substrate/frame/collective/src/lib.rs:
substrate/frame/contracts/src/lib.rs:
substrate/frame/democracy/src/lib.rs:
substrate/frame/elections/src/lib.rs:
substrate/frame/elections-phragmen/src/lib.rs:
substrate/frame/evm/src/lib.rs:
substrate/frame/grandpa/src/lib.rs:
substrate/frame/identity/src/lib.rs:
substrate/frame/im-online/src/lib.rs:
substrate/frame/multisig/src/lib.rs:
substrate/frame/nicks/src/lib.rs:
substrate/frame/node-authorization/src/lib.rs:
substrate/frame/proxy/src/lib.rs:
substrate/frame/recovery/src/lib.rs:
substrate/frame/scheduler/src/lib.rs:
substrate/frame/scored-pool/src/lib.rs:
substrate/frame/session/src/lib.rs:
substrate/frame/society/src/lib.rs:
substrate/frame/staking/src/lib.rs:
substrate/frame/sudo/src/lib.rs:
substrate/frame/support/src/metadata.rs:
substrate/frame/system/src/lib.rs:
substrate/frame/treasury/src/lib.rs:
substrate/frame/vesting/src/lib.rs:
```

**Comment by xlc** [comment]
Related https://github.com/paritytech/substrate/issues/6418

**Comment by shawntabrizi** [comment]
This would be a good first issue for any people who want to hunt down all the missing errors.

**Comment by h4x3rotab** [comment]
Would appreciate if we can get a quick fix because all the miners on our network were halted :(

**Comment by shawntabrizi** [comment]
@h4x3rotab can you elaborate on how this has broke your miners?

You should be able to handle no error metadata, as it is clearly not required, and basically you should not expect it from all Substrate teams.

**Comment by jasl** [comment]
> @h4x3rotab can you elaborate on how this has broke your miners?
> 
> You should be able to handle no error metadata, as it is clearly not required, and basically you should not expect it from all Substrate teams.

It breaks SubXT, I attached a PR for them to workaround this

**Comment by KiChjang** [comment]
It seems like that there's quite a lot of pallets nowadays that don't use the `decl_module` macro to implement dispatch logic anymore, and instead uses the `#[pallet]` macro. Pallets using the new attribute macro don't seem to need the `type Error = Error<T>` line anymore; instead, #[pallet::error]` looks to be enough. Am I missing anything here?

**Comment by shawntabrizi** [comment]
@KiChjang yes, that is accurate. Thew new macros solve this issue. But old pallets could be patched up in the meantime.
