### ISSUE TITLE
Update `rocksdb` for Apple Silicon Support (M1 ARM chip) 

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate#8507]
Apple M1 builders need to use [cumbersome workarounds](https://vikiival.medium.com/run-substrate-on-apple-m1-a2699743fae8) to build substrate.

[A `rocksdb PR](https://github.com/rust-rocksdb/rust-rocksdb/pull/503) is now merged, and _should_ resolve the core issues 🤞🏼 , once it enters a release substrate can be updated to greatly improve M1 support.

**Comment by bkchr** [comment]
This is not yet released and we should no track any external dependencies here.
