### ISSUE TITLE
Potential Bug with Consumers Reference Counting 

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#8536]
https://github.com/paritytech/subport/issues/142#issuecomment-813783707

My investigation of this account implies to me that there should be no consumer reference counters on this account, but there seems to be and it is blocking account deletion.

Needs a deeper investigation as to how this state may have been reached and where there may be some issue with the management of reference counters.

**Comment by kianenigma** [comment]
Also might be related: 
![Uploading Screenshot 2021-03-11 at 19.02.04.png…]()

**Comment by shawntabrizi** [comment]
@kianenigma this is strange because in this case, the consumer is being left over, and your error implies it is being removed beyond zero.

It is like an error in both directions....
