### ISSUE TITLE
Event emit ordering causes a data corruption in the UI

### ISSUE THREAD

**Issue by shekohex** [paritytech/substrate#8537]
### The Issue

Currently, we have an issue where the UI (our dApp, Polkadot UI) fails to decode the events data.

in our [`mixer`](https://github.com/webb-tools/anon/blob/913b5a4547af0be9c54c2a0de957416f81733631/pallets/mixer/src/lib.rs) pallet for example we have this event:
```rust
pub enum Event<T: Config> {
    /// New deposit added to the specific mixer
    Deposit(
	/// Id of the tree
	T::TreeId,
	/// Account id of the sender
	T::AccountId,
        /// Deposit size
	BalanceOf<T>,
	/// Number of leaves before insertion
	u32,
	/// Leaf data
	Vec<ScalarData>, // A ScalarData is just [u8; 32]
    ),
    /// ...
}
```

when we call [`mixer.deposit`](https://github.com/webb-tools/anon/blob/913b5a4547af0be9c54c2a0de957416f81733631/pallets/mixer/src/lib.rs#L250) this event is get emitted, but it shows in the UI (Polkadot for example) as `undefined.undefined` (the first part is the section, next is the enum variant name) which should be `mixer.Deposit` event.

<details>
  <summary>Screenshot (Click here to expand)</summary>

![image](https://user-images.githubusercontent.com/14620076/113697843-0e2d1200-96d4-11eb-9d11-a105ed6d0caa.png)

</details>

### Attempts

1. I tried to call the [`mixer.deposit`](https://github.com/webb-tools/anon/blob/913b5a4547af0be9c54c2a0de957416f81733631/pallets/mixer/src/lib.rs#L250) with empty `data_points`(empty leaves) this result in the event gets emitted correctly! and it shows up in the UI (means correct decoding of the event)
but it shows only the following data (TreeId, AccountId, Balance, Number of Leaves (0)).
    <details>
      <summary>Screenshot (Click here to expand)</summary>

    ![image](https://user-images.githubusercontent.com/14620076/113698095-62d08d00-96d4-11eb-9291-bb40448920b0.png)

    </details>

    > Thoughts: I think it is an Issue with `Vec<ScalarData>` not get decoded correctly.
    
2. Next, I tried to Make it into two events:

    ```rust
    Deposit(T::TreeId, T::AccountId, BalanceOf<T>, u32),
    NewLeaves(Vec<ScalarData>),
    ```
    And then I emitted the `NewLeaves(data_points)` event first, before the `Deposit` one, and no luck! both events didn't show up correctly!

    > Thoughts: It sounds that it is not an issue with the `Vec<ScalarData>` but I need to make sure more of that.

3. Adding a dummy event:

    I tried to add a dummy event to see if is really an issue with `Vec<ScalarData>` not being decoded correctly, so I added this event:

    ```rust
    DepositTest(ScalarData)
    DepositTest2(Vec<ScalarData>)
    ```

    And at the far beginning of the `deposit` method, right before the [`T::Currency::transfer`](https://github.com/webb-tools/anon/blob/913b5a4547af0be9c54c2a0de957416f81733631/pallets/mixer/src/lib.rs#L271) call, I emitted this event `DepositTest(data_points[0])` and `DepositTest2(data_points)` then noticed that it shows in the UI!! wut?
    <details>
      <summary>Screenshot (Click here to expand)</summary>
      
      ![image](https://user-images.githubusercontent.com/14620076/113699260-9cee5e80-96d5-11eb-853b-e74bd49041a4.png)

    </details>

    > Thoughts: Ok, now I'm sure it is not an issue with our data types, and the UI can correctly decode the `Vec<ScalarData>` so where is the issue!

4. Moving things around:

    Currently, at the [`develop`](https://github.com/webb-tools/anon/blob/develop) branch, we emit this event at the end of the `deposit` method [here](https://github.com/webb-tools/anon/blob/913b5a4547af0be9c54c2a0de957416f81733631/pallets/mixer/src/lib.rs#L284), right before the return. which is good, and should be the correct way to do this!

    but now I'll try to emit it before the [`T::Currency::transfer`](https://github.com/webb-tools/anon/blob/913b5a4547af0be9c54c2a0de957416f81733631/pallets/mixer/src/lib.rs#L271) call, as I did with the Dummy events. and sure enough. It works! and correctly shows in the UI with all data correctly decoded.

    <details>
      <summary>Screenshot (Click here to expand)</summary>
      
      ![image](https://user-images.githubusercontent.com/14620076/113699914-767cf300-96d6-11eb-86b7-94513c5e6994.png)

    </details>

Now, I'm really sure there is something really odd happening here, is it possible that is an issue when we emit both the `mixer.Deposit` event and [`merkle.NewMember`](https://github.com/webb-tools/anon/blob/913b5a4547af0be9c54c2a0de957416f81733631/pallets/merkle/src/lib.rs#L200) which is get emitted [here](https://github.com/webb-tools/anon/blob/develop/pallets/merkle/src/lib.rs#L591) from this call [here](https://github.com/webb-tools/anon/blob/913b5a4547af0be9c54c2a0de957416f81733631/pallets/mixer/src/lib.rs#L276) could that make the data to be corrupted?

<details>
<summary>Polkadotjs UI Types: (Click here to expand)</summary>

```json
{
  "EvmAddress": "H160",
  "TokenSymbol": {
    "_enum": [
      "EDG"
    ]
  },
  "CurrencyId": {
    "_enum": {
      "Token": "TokenSymbol",
      "DEXShare": "(TokenSymbol, TokenSymbol)",
      "ERC20": "EvmAddress"
    }
  },
  "GroupId": "u32",
  "Amount": "i128",
  "AmountOf": "Amount",
  "BlockLength": "u64",
  "CurrencyIdOf": "CurrencyId",
  "ScalarData": "[u8; 32]",
  "Nullifier": "ScalarData",
  "Commitment": "ScalarData",
  "MixerInfo": {
    "minimum_deposit_length_for_reward": "BlockNumber",
    "fixed_deposit_size": "Balance",
    "leaves": "Vec<ScalarData>",
    "currency_id": "CurrencyIdOf"
  },
  "WithdrawProof": {
    "mixer_id": "GroupId",
    "cached_block": "BlockNumber",
    "cached_root": "ScalarData",
    "comms": "Vec<Commitment>",
    "nullifier_hash": "ScalarData",
    "proof_bytes": "Vec<u8>",
    "leaf_index_commitments": "Vec<Commitment>",
    "proof_commitments": "Vec<Commitment>",
    "recipient": "Option<AccountId>",
    "relayer": "Option<AccountId>"
  },
  "Manager": {
    "accountId": "AccountId",
    "required": "bool"
  },
  "GroupTree": {
    "leaf_count": "u32",
    "max_leaves": "u32",
    "depth": "u8",
    "root_hash": "ScalarData",
    "edge_nodes": "Vec<ScalarData>"
  },
  "Address": "AccountId",
  "LookupSource": "AccountId",
  "Keys": "SessionKeys2",
  "PalletsOrigin": {
    "_enum": {
      "System": "SystemOrigin",
      "Timestamp": "Null",
      "RandomnessCollectiveFlip": "Null",
      "Balances": "Null",
      "Utility": "Null",
      "Indices": "Null",
      "Authorship": "Null",
      "Aura": "Null",
      "Grandpa": "Null",
      "Staking": "Null",
      "Session": "Null",
      "Historical": "Null",
      "Sudo": "Null",
      "TransactionPayment": "Null",
      "Merkle": "Null",
      "Mixer": "Null"
    }
  }
}
``` 

</details>

**Comment by shawntabrizi** [comment]
@shekohex can you share the custom types you registered on the Polkadot JS side?

Could simply be an issue with decoding on the JS side.

**Comment by shekohex** [comment]
Sure, here are all the types

```json
{
  "EvmAddress": "H160",
  "TokenSymbol": {
    "_enum": [
      "EDG"
    ]
  },
  "CurrencyId": {
    "_enum": {
      "Token": "TokenSymbol",
      "DEXShare": "(TokenSymbol, TokenSymbol)",
      "ERC20": "EvmAddress"
    }
  },
  "GroupId": "u32",
  "Amount": "i128",
  "AmountOf": "Amount",
  "BlockLength": "u64",
  "CurrencyIdOf": "CurrencyId",
  "ScalarData": "[u8; 32]",
  "Nullifier": "ScalarData",
  "Commitment": "ScalarData",
  "MixerInfo": {
    "minimum_deposit_length_for_reward": "BlockNumber",
    "fixed_deposit_size": "Balance",
    "leaves": "Vec<ScalarData>",
    "currency_id": "CurrencyIdOf"
  },
  "WithdrawProof": {
    "mixer_id": "GroupId",
    "cached_block": "BlockNumber",
    "cached_root": "ScalarData",
    "comms": "Vec<Commitment>",
    "nullifier_hash": "ScalarData",
    "proof_bytes": "Vec<u8>",
    "leaf_index_commitments": "Vec<Commitment>",
    "proof_commitments": "Vec<Commitment>",
    "recipient": "Option<AccountId>",
    "relayer": "Option<AccountId>"
  },
  "Manager": {
    "accountId": "AccountId",
    "required": "bool"
  },
  "GroupTree": {
    "leaf_count": "u32",
    "max_leaves": "u32",
    "depth": "u8",
    "root_hash": "ScalarData",
    "edge_nodes": "Vec<ScalarData>"
  },
  "Address": "AccountId",
  "LookupSource": "AccountId",
  "Keys": "SessionKeys2",
  "PalletsOrigin": {
    "_enum": {
      "System": "SystemOrigin",
      "Timestamp": "Null",
      "RandomnessCollectiveFlip": "Null",
      "Balances": "Null",
      "Utility": "Null",
      "Indices": "Null",
      "Authorship": "Null",
      "Aura": "Null",
      "Grandpa": "Null",
      "Staking": "Null",
      "Session": "Null",
      "Historical": "Null",
      "Sudo": "Null",
      "TransactionPayment": "Null",
      "Merkle": "Null",
      "Mixer": "Null"
    }
  }
}
```

I also updated the issue with them.

**Comment by shekohex** [comment]
Ok, we found the issue, it was with our Types.

Closing.
