### ISSUE TITLE
Audit use of `.is_err()` in Runtime Tests

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#8545]
When testing extrinsics, it is important that we follow the "Check First, Write Last" approach so that an extrinsic which results in an error does NOT modify the runtime state.

There is a special macro which does this: `assert_noop!`.

This function specifically checks that a function results in error and that the state root of the blockchain before and after that error is the same.

There may be some places in runtime tests where `asssert!(function.is_err())` is used instead of `assert_noop!`. This can hide such problems about modifying the state, and all of these instances should be replaced with `assert_noop!` instead.

**Comment by hirschenberger** [comment]
I started working on this and realized that in the `GasMeter` module [here](https://github.com/paritytech/substrate/blob/master/frame/contracts/src/gas.rs#L120) test-specific code is injected which unconditionally modifies the state. So using `assert_noop` will fail in the tests below.
It seems a little unclean to modify program-logic for tests only.

**Comment by shawntabrizi** [comment]
@athei care to comment on intentions here?

**Comment by athei** [comment]
Despite the comment those are not written to storage. It is a in-memory only data structure.

**Comment by hirschenberger** [comment]
I sometimes see compiler warnings (mostly unused variables) and long lines from time to time, is it ok to fix that stuff en passant or should I make an extra PR for this?

**Comment by athei** [comment]
If you are not touching the said code I would defiantly prefer a separate PR. Having additional noise in a PR makes it harder to review.

I would prefer grouping those "warning fixes" in a single PR.
