### ISSUE TITLE
Getting error[E0658]: const generics are unstable while cargo build substrate

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/substrate#8590]
While going cargo build, I am getting 

```
error[E0658]: const generics are unstable
  --> /home/ayush/.cargo/registry/src/github.com-1ecc6299db9ec823/arrayvec-0.7.0/src/arrayvec.rs:42:30
   |
42 | pub struct ArrayVec<T, const CAP: usize> {
   |                              ^^^
   |
   = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information
   = help: add `#![feature(min_const_generics)]` to the crate attributes to enable
```

**Comment by liuchengxu** [comment]
Just run `rustup update` to use the latest stable Rust, see https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#const-generics-mvp.

**Comment by ayushmishra2005** [comment]
> Just run `rustup update` to use the latest stable Rust, see https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#const-generics-mvp.

Should I stop using `nightly`?

**Comment by liuchengxu** [comment]
Nope, you can still use `nightly` as long as it's newer enough. `rustup update` will update both the stable and nightly to the latest anyway, and that fixes this issue.

**Comment by bkchr** [comment]
Yeah, please use either latest stable or a nightly that isn't older than stable.

**Comment by PankajMUI** [comment]
rustup update
rustup toolchain install nightly
rustup default nightly
rustup override set nightly

rustup target add wasm32-unknown-unknown --toolchain nightly

**Comment by PankajMUI** [comment]
rustup update
rustup toolchain install nightly
rustup default nightly
rustup override set nightly

rustup target add wasm32-unknown-unknown --toolchain nightly

**Comment by PankajChaudhary5** [comment]
rustup update
rustup toolchain install nightly
rustup default nightly
rustup override set nightly

rustup target add wasm32-unknown-unknown --toolchain nightly
