### ISSUE TITLE
The crate package is contained in its own metadata; qed

### ISSUE THREAD

**Issue by transxask** [paritytech/substrate#8595]
hello, guys. I build  my project based on substrate, and then the err occur:
`thread 'main' panicked at 'The crate package is contained in its own metadata; qed', /home/wjy/.cargo/git/checkouts/substrate-f4423eebfa0046a3/3ec97a3/utils/wasm-builder/src/wasm_project.rs:542:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
 but sometimes,  i build it again, and  success. why?

**Comment by bkchr** [comment]
Do you modify the `Cargo.toml` files while building?

**Comment by transxask** [comment]
No

**Comment by transxask** [comment]
> Do you modify the `Cargo.toml` files while building?

No

**Comment by transxask** [comment]
> > Do you modify the `Cargo.toml` files while building?
> 
> No

`https://github.com/listenofficial/listen.git`. there is my project

> > Do you modify the `Cargo.toml` files while building?
> 
> No

Maybe there's something wrong with my computer. Could you please try to compile it. there is my project`https://github.com/listenofficial/listen.git`.

**Comment by transxask** [comment]
Soory, it is my wrong. it seem that  there is a package named 'node-runtime' in my project. it confict with substrate.
