### ISSUE TITLE
api.tx.sudo.sudo(api.tx.pallet.method) return 'badOrigin'

### ISSUE THREAD

**Issue by AmazingBeerBelly** [paritytech/substrate#8607]
I use the Polkadot.js's sudo module to call the pallet method, api.tx.sudo.sudo(api.tx.pallet.method(params)) In this way, I use Alice's account to signAndSend, and I get the reporting 'badOrigin'.

but it is success to call api.tx.sudo.sudo(api.tx.balances.setBalance(ADDR, 12345, 678).

Why? Thanks a lot!

**Comment by bkchr** [comment]
Only root functions can be called with root. Not every function needs to accept root.

**Comment by AmazingBeerBelly** [comment]
Excuse me, which functions are root functions? Or how to define the root function? Thanks a lot!

**Comment by bkchr** [comment]
Search for `ensure_root`

https://substrate.dev/docs/en/knowledgebase/runtime/origin

**Comment by icodezjb** [comment]
The same issue, try `api.tx.sudo(api.tx.pallet.method)
```rust
pub fn sudo(
	origin: OriginFor<T>,
	call: Box<<T as Config>::Call>,
) -> DispatchResultWithPostInfo {
	// This is a public call, so we ensure that the origin is some signed account.
	let sender = ensure_signed(origin)?;
	ensure!(sender == Self::key(), Error::<T>::RequireSudo);

	let res = call.dispatch_bypass_filter(frame_system::RawOrigin::Root.into());
	Self::deposit_event(Event::Sudid(res.map(|_| ()).map_err(|e| e.error)));
	// Sudo user does not pay a fee.
	Ok(Pays::No.into())
}
```
sudo is not require root, so sudo->sudo return BadOrigin by ensure_signed
