### ISSUE TITLE
Investigate increased contract instrumentation costs

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#8611]
The weight for contract instrumentation per byte [increased by a factor of 20x](https://github.com/paritytech/substrate/pull/8608#pullrequestreview-634420002). I am not sure why and when this happened.

This regression should be bisected and corrected.

**Comment by athei** [comment]
After some investigation I found out the following:

- The regression only exists in the wasm runtime but **not** in the native runtime.
- It was introduces by [this PR](https://github.com/paritytech/substrate/pull/8128).

**Comment by bkchr** [comment]
So reverting the commit fixes your problem?

**Comment by athei** [comment]
I did a bisect and this was the first commit that had the regression.

**Comment by athei** [comment]
I tracked down the culprit. The regression is gone when I remove the `trace!` statements in [this](https://github.com/paritytech/wasm-utils/blob/master/src/stack_height/max_height.rs) file. Those are tight loops and it makes total sense to see such a slowdown when those are not compiled out.

Specifying `disable-logging` does not help. This feature does not activate `log/release_max_level_off` which could explain the problem. However, even if I add this to `sp-io` the regression is still there. It seems that the tracing code is not properly removed. Maybe the log feature is not properly propagated (maybe something with the new resolver).

**Comment by athei** [comment]
The issue is being solved by deactivating logging when a runtime is being build for benchmarking (see linked PR).
