### ISSUE TITLE
sp_arithmetic: different fixed point accuracies

### ISSUE THREAD

**Issue by sander2** [paritytech/substrate#8612]
When using the `sp_arithmetic`, `FixedU128` has a scaling factor of `1_000_000_000_000_000_000`. In many applications this is massively overkill, and in one of our uses, it causes us to be at risk of of not being able to represent the entire range of possible numbers. Would it be possible to either provide multiple accuracies, or to make it it configurable? Currently the `DIV` is a constant, but it doesn't necessarily need to be

**Comment by marcio-diaz** [comment]
You can define your own using this [macro](https://github.com/paritytech/substrate/blob/e186f7cb6cc41023e3e0a2c84c17e58938b76296/primitives/arithmetic/src/fixed_point.rs#L1611).

**Comment by sander2** [comment]
Thanks, but the macro is not exported so we can't use it from our crate. I'm not very familiar with macro's - would it be sufficient to just add a `#[macro_export]`?

**Comment by bkchr** [comment]
Cc @kianenigma

**Comment by kianenigma** [comment]
It would be easy enough to export those macros and then you can create custtom types. 

But I am not a fan of that, given the combination of:

1. We haven't properly tested if that macro is capable of generating proper types for all boundaries afaik. Also we haven't audited that piece of the code yet. So making it public is a lot of maintenance burden for us. @marcio-diaz nught correct me though. 
2. How big of a deal is it to just use Fixed64? Also, note that we have more fine-grained `PerThings`. What is your scenario and why do you want this?

If you are really keen on getting the fresh types, I recommend you to fork our macro in to your repo and maintain it also there.

**Comment by sander2** [comment]
>     2. How big of a deal is it to just use Fixed64? Also, note that we have more fine-grained `PerThings`. What is your scenario and why do you want this?

We need to store a potentially very large number, which is basically `sum(stake_i * score_i)`. We are worried that this could overflow if there is a lot of collateral staked. I looked into PerThing, but the types with smaller precision also use a smaller internal representation type, which for this usecase kind of defeats the purpose.

> If you are really keen on getting the fresh types, I recommend you to fork our macro in to your repo and maintain it also there.

Ok, we will consider doing this. Thanks for the replies

**Comment by kianenigma** [comment]
This is already resolved, the issue was more of a question. Anyone can use the macros to generate their own custom fixed stuff. We only provide a handful in substrate.
