### ISSUE TITLE
[rococo-v1] Broken build with latest jsonrpsee

### ISSUE THREAD

**Issue by c410-f3r** [paritytech/substrate#8660]
When issuing `cargo update`, Cargo will update `jsonrpsee-utils` to `0.2.0-alpha.5` but `jsonrpsee-http-client` will still be at `0.2.0-alpha.3` causing building errors. Please, transpose https://github.com/paritytech/substrate/pull/8644 to `rococo-v1` .

**Comment by bkchr** [comment]
Never use `cargo update`.

Use `cargo update -p sp-io` when you want to update Substrate for example.

**Comment by c410-f3r** [comment]
Due to transient dependencies and specific version specifications like `~` or `=`, successful graph dependency resolution can not always be easily accomplished be individually updating a set of discrete crates.
