### ISSUE TITLE
system `on_runtime_upgrade` should be triggered after custom on runtime upgrade, similarly to other pallet

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#8683]
About this code:
https://github.com/paritytech/substrate/blob/acd17418855e56082abe202680dd437f169b2c49/frame/executive/src/lib.rs#L207-L216

I don't see why frame system pallet would take prioritised before the custom one whereas other pallet doesn't.

The custom on runtime upgrade should be able to do any kind of migration prior to pallet migration, allowing to bypass them.

cc @drewstone @al3mart

**Comment by al3mart** [comment]
I'm cc'ing @apopiak here :)

**Comment by drewstone** [comment]
@bkchr proposed removing all `on_runtime_upgrade` logic from the pallets and handling it directly at the runtime level, which seems like a good option imo. That way a team can check the references and order however they please.

**Comment by shawntabrizi** [comment]
Was there some bigger issue that was found which pointed to this?

**Comment by drewstone** [comment]
@shawntabrizi we're trying to run the next Edgeware upgrade and it seems the ref count migrations can't be updated on the fly (it migrates to triple count from double when we're still on single).

If there's no way to custom execute code before this, our only resolution is to fork substrate which I'd ideally try to avoid.
