### ISSUE TITLE
transfer_all() function in Balances Pallet

### ISSUE THREAD

**Issue by CurlyBracketEffect** [paritytech/substrate#8696]
It would be helpful to have a function that takes into account the transaction fee required to send the entire balance of an account without leaving any dust behind to be reaped. 

 amountToTransfer + partialFee + tip? = Total balance

**Comment by shawntabrizi** [comment]
I think by the time it gets to the extrinsic, all fees and tips are already deducted from the account, so it should be simple enough to query the free balance of the user account, and then use that amount for a transfer call.

**Comment by xlc** [comment]
but block weight fee multiplier changes every block so you can never guarantee the transfer success

**Comment by shawntabrizi** [comment]
@xlc I think you are reading my comment wrong.

I think a new extrinsic like this solves this:

```
fn transfer_all_free(origin, to: T::AccountId) {
    let who = ensure_signed(origin)?;
    let total_free = Self::free_balance(who);
    Self::transfer(who, to, total_free, AllowDeath)?;
}
```

This logic is built into the runtime and happens after all the fee stuff is deducted. So I think it will always succeed when the full transfer is possible.

**Comment by kianenigma** [comment]
> but block weight fee multiplier changes every block so you can never guarantee the transfer success

Yes but not during the block, so for the duration of a single block, it is constant. I think shawn's proposal works.

**Comment by mutobui** [comment]
> @xlc I think you are reading my comment wrong.
> 
> I think a new extrinsic like this solves this:
> 
> ```
> fn transfer_all_free(origin, to: T::AccountId) {
>     let who = ensure_signed(origin)?;
>     let total_free = Self::free_balance(who);
>     Self::transfer(who, to, total_free, AllowDeath)?;
> }
> ```
> 
> This logic is built into the runtime and happens after all the fee stuff is deducted. So I think it will always succeed when the full transfer is possible.

I try to implement transfer_all_free in runtime with KeepAlive then got the error
```
ModuleError {
            index: 1,
            error: 4,
            message: Some(
                "KeepAlive",
            ),
        },
```

**Comment by ggwpez** [comment]
> I try to implement transfer_all_free in runtime with KeepAlive then got the error

Why are you implementing it again? The function already exists now `Balances::transfer_all` @mutobui
