### ISSUE TITLE
Is it possible to get rpc_methods parameters and documentation?

### ISSUE THREAD

**Issue by kurotych** [paritytech/substrate#8702]
I want to make auto generation for API documentation. There is convenient way to do almost all what I need by parsing metadata `state_getMetadata` of my pallets. There are Extrinsics, storages, etc. with name, type and documentation.

Is there any way to take the same information about RPC calls(information about parameters and documentation)? 
I found only `rpc_methods` method that retrieves the list of RPC methods without additional information.

**Comment by bkchr** [comment]
No sorry there is not automated way for doing this.
