### ISSUE TITLE
keystore: Difference between KeyType and CryptoType?

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/substrate#8703]
Substrate's keystore traits as codified in `sp-keystore` distinguish between a `KeyType` and a `CryptoType`. For example see the `sign_with` method from https://github.com/paritytech/substrate/blob/master/primitives/keystore/src/lib.rs#L120-L132

```Rust
	/// Sign with key
	///
	/// Signs a message with the private key that matches
	/// the public key passed.
	///
	/// Returns the SCALE encoded signature if key is found and supported, `None` if the key doesn't
	/// exist or an error when something failed.
	async fn sign_with(
		&self,
		id: KeyTypeId,
		key: &CryptoTypePublicPair,
		msg: &[u8],
	) -> Result<Option<Vec<u8>>, Error>;
```

At first I thought I understood this. I thought crypto type would distinguish between {ed25519, sr25519, ecdsa} whereas key type would distinguish between use cases such as {aura, babe, im-online, collator key, offchain worker, ... }.

But then I remembered we also have the `sp-application-crypto` crate which, according to its own docs, contains "macros for constructing application specific strongly typed crypto wrappers".

If we have strongly-typed crypto wrappers such that each application has its own type, why can't that type keep track of the underlying cryptography. Why do we need to separately pass the cryptography type into the keystore when signing?

------------------

A more concrete way to approach my confusion is through this example that I expected to be simple. What CryptoTypeId do I need to supply? (Obviously `42` is wrong.) I thought I should be able to directly use the information I got back from the key generation process. Am I approaching this the wrong way?

```Rust
use sc_keystore::LocalKeystore;
use sp_application_crypto::{CryptoTypePublicPair, KeyTypeId};

// I know the docs say I should start with the async version, but I want to be
// sure I can copy code from Aura, so I'm starting with sync.
use sp_keystore::SyncCryptoStore;

/// A play key type id that represents general-purpose communication.
pub const COMMS: KeyTypeId = KeyTypeId(*b"comm");

fn main() {
    // Create a place to store my keys.
    let keystore = LocalKeystore::in_memory();

    // Generate a key. I'll use sr25519
    let my_public_key = keystore.sr25519_generate_new(COMMS, None).unwrap();

    println!("My public key is: {}", my_public_key);

    // Sign a message with my new key
    let message = "send the money to Alice".as_bytes();
    let signature = keystore
        .sign_with(
            COMMS,
            &CryptoTypePublicPair(42, my_public_key.0.to_vec()),
            message,
        )
        .unwrap();

    // TODO Verify that signature.
    // I guess the keystore will not be involved with verifying at all.
}
```

**Comment by JoshOrndorff** [comment]
Another related question. If I do use `app_crypto!` (as opposed to sr25519 in my above example) is the keystore still able to generate keys for me? Or I have to generate my own keys and insert them with insert_unknown?

**Comment by bkchr** [comment]
`CryptoTypeId` came way later than the initial `sp-application-crypto` crate. 

The idea is still that you use `sp-application-crypto` for all the stuff. The keystore is already prepared to be remote at some point in the future. As a `KeyType` doesn't tell you what kind of crypto this is and stuff like Aura for example supports sr25519/ed25519 you need to have some way to know what kind of crypto you want (on the remote keystore).
