### ISSUE TITLE
propose removing all `on_runtime_upgrade` logic from the pallets and handling it directly at the runtime level

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#8713]
@bkchr proposed removing all `on_runtime_upgrade` logic from the pallets and handling it directly at the runtime level, which seems like a good option imo. That way a team can check the references and order however they please.

_Originally posted by @drewstone in https://github.com/paritytech/substrate/issues/8683#issuecomment-828355253_

Some hint for implementers:
* remove the implementation of OnRuntimeUpgrade on the pallet in frame/support/procedural/src/pallet/expand.rs
* remove the method on_runtime_upgrade, pre_upgrade, post_upgrade in the Hook trait in frame/support/src/traits/hooks.rs
* modify the frame-executive:
  * do not require that AllPallets implement OnRuntimeUpgrade anymore
  * do not execute AllPallets::on_runtime_upgrade anymore.

That should be all I think.

**Comment by kianenigma** [comment]
I really agree with this. Handling migrations that are baked into the pallet is too opaque in my opinion.
