### ISSUE TITLE
Remove the need to specify `<T>` for parts in `construct_runtime!` (like `Event<T>`)

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#8743]
Instead of fetching the type from the macro we can fetch the type from the `Pallet` struct placeholder.

We introduce a trait `trait PalletEvent { type Event }`,
we implement it for the pallet placeholder.
and then we use `<Pallet<Runtime> as PalletEvent>::Event` when building the aggregated runtime event.

Thus there is no longer need for specify the generics of the `Event` type.

Same for `Origin` and `Config`.

This main advantage of it is in to not have these difficult compilation error when the generics are wrongly specified.

**Comment by thiolliere** [comment]
still relevant

**Comment by KiChjang** [comment]
What happens if there is data in an `Event` enum that requires access to `Config`? Currently with generics, we can access it via `T::AccountId` for example, but without `T`, we would not be able to specify any of the types in `Config`.

**Comment by thiolliere** [comment]
no this isn't what I meant, event type can still be generic, but the configuration of the part doesn't require to give this information.

This can be achieve by using trait implemented on the pallet struct:
```
trait PalletEvent {
type Event: ....;
}
impl<T: Config> PalletEvent for Pallet<T> {
type Event = TheEventDefinedInThePallet<T>;
}
```
(maybe the trait `PalletEvent` needs generics too like `PalletEvent<T, I=()>`, but I think it is no needed)

**Comment by KiChjang** [comment]
Solving this issue is actually a prerequisite to #8084, because an "import all declared pallet parts" syntax by definition does not include a generic for the pallet parts that require it.

**Comment by thiolliere** [comment]
actually when pallet declare their parts they can also declare their part with the correct generic. But I agree it can make code simpler.

**Comment by thiolliere** [comment]
This PR https://github.com/paritytech/substrate/pull/9681 doe the automatic declaration of pallet parts.
So user only declare some part to exclude, without giving any information about the generics.

Maybe this issue can be considered fixed then

**Comment by thiolliere** [comment]
personally I would close this issue, with the new syntax nobody should declare the part manually, instead they only whitelist or blacklist parts.
Maybe the syntax is not ideal, but this is not what this issue is about.

Feel free to re-open if you disagree

**Comment by KiChjang** [comment]
My [current PR](https://github.com/paritytech/substrate/pull/9658) can only support non-generic `Event` and `Config` -- I don't think there is a way to support non-generic `Origin` for FRAMEv1 macros, so until we get every FRAME macro to use v2, then I don't think it's worth pursuing yet.
