### ISSUE TITLE
Different PalletIDs produces the same AccountId

### ISSUE THREAD

**Issue by kurotych** [paritytech/substrate#8767]
Hello. During testing pallets, I faced with issue when AccountIDs had the same value, but PalletIDs were different.

It is reproduced on current master branch. Also the same behavior in 3.0.0 version.
To get different account ID should be unique first 4 bytes, others are ignored.

Code to reproduce: 
```
#[test]
fn pallet_id_not_unique() {
    let pallet_id1: u64 = PalletId(*b"py/laaaa").into_account();
    let pallet_id2: u64 = PalletId(*b"py/lbbbb").into_account();
    assert_ne!(pallet_id1, pallet_id2);
}
```
_Don't forget to add `use sp_runtime::traits::AccountIdConversion;` and `use frame_support::PalletId;`_

---- pallet_id_not_unique stdout ----
thread 'pallet_id_not_unique' panicked at 'assertion failed: `(left != right)`
  left: `7795583003763437421`,
 right: `7795583003763437421`', frame/support/test/tests/pallet.rs:507:5

**Comment by bkchr** [comment]
CC @shawntabrizi 

Sounds similar to https://github.com/paritytech/substrate/issues/8564

**Comment by shawntabrizi** [comment]
Yeah, the issue here is that you are mapping this to a u64 which does not have enough bytes.

If you want to properly test the account id generation you need to use the full `AccountId32` type
