### ISSUE TITLE
Provide solution for Empty block

### ISSUE THREAD

**Issue by nagarajmanjunath** [paritytech/substrate#8784]
Hi everyone,  ```Empty Block``` in Substrate. There should some config to enable or disable the empty block if there is no transaction. Empty block taking a lot of space without having any transaction in a block. Please do provide any suggestion or solution on this ```Empty Block``` creation.

**Comment by shawntabrizi** [comment]
Please take a look at the instant seal node: https://substrate.dev/recipes/kitchen-node.html
