### ISSUE TITLE
Timestamp is zero during offchain worker testing

### ISSUE THREAD

**Issue by kurotych** [paritytech/substrate#8821]
Hello. 

I want to cover test case when deadline for [StorageLock](https://github.com/paritytech/substrate/blob/c93ef27486e5f14696e5b6d36edafea7936edbc8/primitives/runtime/src/offchain/storage_lock.rs#L246) is expired.

I used example how to do it from [here](
https://github.com/paritytech/substrate/blob/3f110196163b5ec03bac5ee188d60bedf3ebd91d/frame/im-online/src/tests.rs#L203).

But deadline for lock isn't happening. 
After some investigation I found that `sp_io::offchain::timestamp()` always return 0.
The same function is used in [fn has_expired](https://github.com/paritytech/substrate/blob/c93ef27486e5f14696e5b6d36edafea7936edbc8/primitives/runtime/src/offchain/storage_lock.rs#L130)

_To make sure of it you can add `println!("Timestamp: {:?}", sp_io::offchain::timestamp())` to [offchain_worker](https://github.com/paritytech/substrate/blob/3f110196163b5ec03bac5ee188d60bedf3ebd91d/frame/im-online/src/lib.rs#L431) and run test:
`cargo test -- --nocapture should_generate_heartbeats`_

Is there any workaround?

**Comment by shawntabrizi** [comment]
You can call the test function `set_timestamp` which is exposed in the pallet: https://github.com/paritytech/substrate/blob/master/frame/timestamp/src/lib.rs#L259

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/blob/master/primitives/core/src/offchain/testing.rs#L234-L242

We don't use any real timestamp in the tests. As you see above, you could call `sleep_until` to set the timestamp. However, in general testing that something times out it a little bit tricky. Can you show your test?

**Comment by bkchr** [comment]
> You can call the test function `set_timestamp` which is exposed in the pallet: https://github.com/paritytech/substrate/blob/master/frame/timestamp/src/lib.rs#L259

Not related to the timestamp pallet

**Comment by kurotych** [comment]
> https://github.com/paritytech/substrate/blob/master/primitives/core/src/offchain/testing.rs#L234-L242
> 
> We don't use any real timestamp in the tests. As you see above, you could call `sleep_until` to set the timestamp. However, in general testing that something times out it a little bit tricky. Can you show your test?

[Here you are.](
https://github.com/minterest-finance/minterest-chain-node/commit/e8bbbafb75c76681ef99a0b8a1e65cae3d7c5c5d#diff-460029bf54abf74170adc7ee68cbac6da5b55d0bc23227096174e2048d41c8a2R17)

It is really a little bit tricky, but approach with `sleep_until` works. I create a new thread and wait half second when offchain worker will start and dramatically increase timestamp.  

So my issue is resolved. But it would be nice to have a `real` timestamp to test lock with deadline.

**Comment by kurotych** [comment]
We found nice solution. 
Create `OffChainExt` [wrapper](https://github.com/minterest-finance/minterest-chain-node/blob/master/test-helper/src/offchain_ext.rs#L11) after impl `Externalities` for it, and [return system timestamp](https://github.com/minterest-finance/minterest-chain-node/blob/master/test-helper/src/offchain_ext.rs#L44).
