### ISSUE TITLE
Pallet macro: `pallet::constant` should support custom type for metadata

### ISSUE THREAD

**Issue by shaunxw** [paritytech/substrate#8827]
Some native rust types cannot be used in metadata, like `&'static [u8]`, and currently it's represented by `&[u8]` in metadata like in [claims pallet](https://github.com/paritytech/polkadot/blob/ebbb354bc4521858c8bc56c9102e62955f41a333/runtime/common/src/claims.rs#L221).

`pallet::constant` should provide a way to configure custom types for metadata. An attribute macro like `pallet::constant_type("&[u8]")` might be a way to do it.

**Comment by thiolliere** [comment]
https://github.com/paritytech/substrate/pull/8615 should remove the need for specifying the type if I'm correct.

**Comment by thiolliere** [comment]
hopefully will be fixed by https://github.com/paritytech/substrate/pull/8615

**Comment by shawntabrizi** [comment]
i believe this should be fixed now
