### ISSUE TITLE
Incorrect ordering of fees and tips in Transaction Payment

### ISSUE THREAD

**Issue by xx-labs** [paritytech/substrate#8854]
It appears that the ordering of transaction fees and tips is incorrect when passing to the on_unbalanceds function:
https://github.com/paritytech/substrate/blob/965be9f4a37acd89433dfbb885ca431803a3148d/frame/transaction-payment/src/payment.rs#L122-L124

The split function returns the split amount first, and the remainder second
https://github.com/paritytech/substrate/blob/965be9f4a37acd89433dfbb885ca431803a3148d/frame/balances/src/lib.rs#L1183-L1189

This means that what is passed to on_unbalanceds is [tip, fees] instead of [fees, tip] as the comments specify.

This implementation of DealWithFees that splits fees between block producer and Treasury illustrates the issue, as the comments clearly specify that the first item is believed to be the fees.
https://github.com/paritytech/substrate/blob/965be9f4a37acd89433dfbb885ca431803a3148d/bin/node/runtime/src/lib.rs#L141-L155

This bug can be found in the Polkadot Mainnet.
Here is an example of a transfer without tips:
https://polkadot.js.org/apps/#/explorer/query/0x0218a64f98f808d654f9113cd1feeb70d66e1fb02742b2ee43df33d3b88922e7
The totality of the transaction fee is deposited in the block producer's account.

Here is an example of a transfer with a tip:
https://polkadot.js.org/apps/#/explorer/query/0xf0d74cc96794b6ef3ff3836ff115bff18fefb9132790ae033d5d5014a24cb102
The totality of the transaction fee + 20% of the tip is deposited in the block producer's account.
80% of the tip is deposited into the Treasury account.

**Comment by thiolliere** [comment]
yes your diagnostic is right. This PR should fix it https://github.com/paritytech/substrate/pull/8860
