### ISSUE TITLE
[pallet-contracts] Schedule is not public for developer to change the config

### ISSUE THREAD

**Issue by atenjin** [paritytech/substrate#8869]
after #8773 Schedule is moved from a storage to outside, but `Schedule` just provide a `Default::default()` implementation, but not provide the construct function to set any attribute!

https://github.com/paritytech/substrate/blob/master/frame/contracts/src/schedule.rs#L50-L59

it's attributes are all `(crate)`

and the `Limits` and other structs are not public.

For example If I wanna change the max_code_len, I cannot set from the runtime.

**Comment by atenjin** [comment]
related to #8433

**Comment by athei** [comment]
The rational for this change is explained in the issue you linked. That said, I fully intent to add back the ability to fully customize the the `Schedule` before the next version of this crate is released. But it cannot by making the fields public for the reason explained in the linked issue. I will probably write a proc macro that creates versioned constructors that let you set all fields.
