### ISSUE TITLE
Extrinsics in chain_getBlock (rpc) do not have compact length value

### ISSUE THREAD

**Issue by emielvanderhoek** [paritytech/substrate#889]
The extrinsics in chain_getBlock (rpc) do not have compact length value while documentation suggests it should (https://wiki.parity.io/Extrinsic).
I have checked for all extrinsics up to block 122000 on BBQ-Birch.
Gavin suggested (on Substrate Technical channel) this may be a bug in the RPC.

**Comment by emielvanderhoek** [comment]
The extrinsics all either start with 0x01 (unsigned) or 0x81 (signed).

**Comment by gavofyork** [comment]
To reproduce
- use JSONRPC to get an extrinsic from a block;
- it will begin with the version marker (0x01 or 0x81) instead of the compact `u32` length prefix.
