### ISSUE TITLE
'sp-version' breaks `no_std` builds that are not wasm

### ISSUE THREAD

**Issue by clangenb** [paritytech/substrate#8891]
The re-export of the `sp_version_proc_macro::runtime_version` in `sp-version` that was introduced here https://github.com/paritytech/substrate/pull/8688. Breaks `no_std` builds that are not wasm.

This is inconvenient for us, as in [SubstraTEE](https://github.com/scs/substraTEE), we want to include arbitrary substrate-pallets in an sgx-enclave, which is a no-std but not wasm environment. As `sp-version` is a dependant of `frame-system`, it is virtually impossible to use any pallets without patching sp-version.

Is it an option to remove this re-export?

**Comment by bkchr** [comment]
What kind of error you get?

**Comment by clangenb** [comment]
I get some duplicate lang items error. I could identify the problematic crate to be `sp-version`. In this crate I found the following section, where I concluded without much more investigation that this is the issue:

https://github.com/paritytech/substrate/blob/c2ec5bc8f12bb5a084b976f2dc1280796e9c1b23/primitives/version/src/lib.rs#L83-L95

**Comment by bkchr** [comment]
Do you use the macro? If not, it should not be responsible for what you are seeing.

**Comment by clangenb** [comment]
Ok, I could track it down. It was related to https://github.com/rust-lang/cargo/issues/7915.

Adding `resolver = 2` in our `no_std` crate prevented leakage of `std` from the `proc_macro`.

Thanks for your time! 👍
