### ISSUE TITLE
apple m1 cargo build failed: LLVM ERROR: Global variable '_ZN12node_runtime1_16SECTION_CONTENTS17h28c19e8d9889aa72E' has an invalid section specifier 'runtime_version': mach-o section specifier requires a segment and section separated by a comma.

### ISSUE THREAD

**Issue by zmrush** [paritytech/substrate#8914]
apple m1 cargo build failed:
LLVM ERROR: Global variable '_ZN12node_runtime1_16SECTION_CONTENTS17h28c19e8d9889aa72E' has an invalid section specifier 'runtime_version': mach-o section specifier requires a segment and section separated by a comma.

but when i use cargo build --release,it successed

**Comment by bkchr** [comment]
Do you use latest master?

**Comment by zmrush** [comment]
yes,i found it just now,thanks
