### ISSUE TITLE
Expose fork choice events

### ISSUE THREAD

**Issue by eskimor** [paritytech/substrate#8921]
For Polkadot listening to actual fork choice events instead of block import events would make the implementation simpler and more importantly would improve performance considerably, if this would result in less forks that need to be considered when building blocks. See [here](https://github.com/paritytech/polkadot/pull/3104) for a short discussion.

**Comment by bkchr** [comment]
What are fork choice events? Even reading the discussion is not revealing any more information.

**Comment by eskimor** [comment]
My understanding is, that we get notified an what fork we would build another block, by the rules applied. E.g. max number of primary blocks, no disputes, ... With just block imports, we don't know for example if another imported block should supersede some other - e.g. because a primary block just arrived, so we can drop the already present secondary one. I have not really looked at that code yet, but that's my understanding so far. Other than that block import events should be pretty much the fork choice, I guess - as why would we import a block we don't want to build on? Anyhow, maybe @rphmeier can shed some more light.

**Comment by bkchr** [comment]
I think https://github.com/paritytech/polkadot/pull/3104#issuecomment-849414148 this already covers what you want.

**Comment by eskimor** [comment]
We have [that](https://github.com/paritytech/substrate/blob/master/client/api/src/client.rs#L255) already.
