### ISSUE TITLE
failed to select a version for the requirement `zeroize = "^0.9.1"`

### ISSUE THREAD

**Issue by btravis182** [paritytech/substrate#8936]
Hi guys, 
I am trying to install parity and I am very new to this. While following the instructions from the book I am reading, I came up with the following issue. I tried to look it up on here but could not find anything. Anybody has been through that or would know how to fix it? Thanks a lot!!

> warning: Using `cargo install` to install the binaries for the package in current working directory is deprecated, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.
>   Installing parity-ethereum v2.7.2 (C:\Users\rugge\parity)
>     Updating crates.io index
>     Updating git repository `https://github.com/paritytech/rust-ctrlc.git`
>     Updating git repository `https://github.com/paritytech/app-dirs-rs`
> error: failed to compile `parity-ethereum v2.7.2 (C:\Users\rugge\parity)`, intermediate artifacts can be found at `C:\Users\rugge\parity\target`
> 
> Caused by:
>   failed to select a version for the requirement `zeroize = "^0.9.1"`
>   candidate versions found which didn't match: 1.3.0, 1.2.0, 1.1.1, ...
>   location searched: crates.io index
>   required by package `parity-crypto v0.4.2`
>       ... which is depended on by `parity-ethereum v2.7.2 (C:\Users\rugge\parity)`

**Comment by bkchr** [comment]
This is Substrate and parity-ethereum doesn't exist anymore. This is now openethereum.

**Comment by btravis182** [comment]
Thanks for replying. Will get into openethereum!
