### ISSUE TITLE
code panics when max argument of pick_u32 is u32::max_value()

### ISSUE THREAD

**Issue by bennetyee** [paritytech/substrate#8940]
https://github.com/paritytech/substrate/blob/6a63f282a5c0fb608569137ed464a23583d2d7de/primitives/runtime/src/random_number_generator.rs#L66

L77 is careful to handle the `u32::max_value()` case, but on L66 the computation of the largest acceptable value `top` to avoid biased output isn't.  The subexpression `((max + 1) as u64)` computes `(max + 1)` as u32 first before converting to u64, so will overflow if `max` is `u32::max_value()`.  In debug builds the computation will panic on the `(max + 1)` because overflows are detected; in optimized builds the overflow to zero is not detected, but the computation will panic on the division by zero.

This is fixed by replacing those subexpressions with `((max as u64) + 1)`.

**Comment by xlc** [comment]
Duplicates of https://github.com/paritytech/substrate/issues/7444
