### ISSUE TITLE
Have a super easy way to run different wasm runtimes on the same binary

### ISSUE THREAD

**Issue by expenses** [paritytech/substrate#8974]
A lot of chains only change the runtime and don't change the client code at all. Therefore it'd be great if there was an easy way to run a chain by just giving it a runtime wasm. This would ideally be done by a script of some kind.

Here's what should happen:

1. Substrate should be compiled ONCE.
2. You run a cli command with the path of a wasm blob as an argument.
3. The chain runs and starts producing blocks.

**Comment by xlc** [comment]
the chain spec already includes wasm as long as a valid chain spec is provided, there is no need to pass wasm blob.

we should just avoid build runtime natively and have a way to build dev chain spec and have it committed to repo so others can still run dev chain out of the box.

**Comment by arkpar** [comment]
`substrate --chain polkadot.json` should work. Although it has been a while since anyone tested it.

**Comment by NukeManDan** [comment]
I think the [playground](https://github.com/paritytech/substrate-playground) could benefit from this and contribute some ideas towards this effort. One that seems obvious is a containerized flow:
0. (one person) builds and publishes an image for "shell" node (with no runtime, or defaulting to a minimal one?)
1. (anyone) pulls image
2. builds rumtime wasm  if needed, or pull from published location
3. passes wasm blob to execute

In the parachain context, integration with https://github.com/paritytech/polkadot-launch would seem like a good fit

This also seems to be highly related to efforts in https://github.com/paritytech/smoldot , yes?

**Comment by gilescope** [comment]
For native pallet dev, would it be helpful to be able to run in a dev `shell` mode where there was no networking, no forks and no consensus so that there was little to compile - just an uncontended local chain? (I'm guessing that may pull in only half the crates..)

**Comment by gilescope** [comment]
In fact for projects like the bridge project that just need a shell node, we can avoid compiling substrate client at all and just compile the runtime.

**Comment by expenses** [comment]
I'm researching this now. First problem: `new_full_client` requires a `NativeExecutionDispatch`, which is created using the `native_executor_instance!` macro. As we're choosing whichever runtime we're using at runtime, we can only execute blocks using a non-native (wasm) executor.

**Comment by expenses** [comment]
Okay, I've gotten over that bump by using some hacks to use a `WasmExecutor` instead. The branch is up here: https://github.com/paritytech/substrate/compare/ashley-easy-builder.

Now I need to find a way to define `RuntimeApi`.

**Comment by expenses** [comment]
Okay, I've used `cargo expand` to expand out the generated runtime generation code, and have used that to make a basic impl of `RuntimeApi`. The next problem is trying to make a transaction pool.

`FullPool::new_full` requires `Client::Api: sp_transaction_pool::runtime_api::TaggedTransactionQueue<Block>`, and the implementation of that requires `validate_transaction`.

`validate_transaction` in the generated code is implemented using `Executor::validate_transaction`, where:

```rust
/// Executive: handles dispatch to the various modules.
pub type Executive = frame_executive::Executive<
	Runtime,
	Block,
	frame_system::ChainContext<Runtime>,
	Runtime,
	AllPallets,
	(),
>;

/// All pallets included in the runtime as a nested tuple of types.
/// Excludes the System pallet.
pub type AllPallets = ((TransactionStorage , (Uniques , (Gilt , (Lottery , (Mmr , (Assets , (Tips , (Bounties , (Multisig , (Proxy , (Scheduler , (Vesting , (Recovery , (Society , (Identity , (RandomnessCollectiveFlip , (Historical , (Offences , (AuthorityDiscovery , (ImOnline , (Sudo , (Contracts , (Treasury , (Grandpa , (TechnicalMembership , (Elections , (TechnicalCommittee , (Council , (Democracy , (Session , (Staking , (ElectionProviderMultiPhase , (TransactionPayment , (Balances , (Indices , (Authorship , (Timestamp , (Babe , (Utility ,)))))))))))))))))))))))))))))))))))))))) ;
```

I feel like copying this is the wrong move, as we're specifically trying to create a node that _doesn't need to think about runtime pallets_.
