### ISSUE TITLE
Have an enforced code style

### ISSUE THREAD

**Issue by expenses** [paritytech/substrate#8981]
At the moment, we don't have any setup for code formatters such as `cargo fmt`. This means that developers manually have to do things such as break off lines at the appropriate column wide. These things take up time needlessly and I think it'd be better to have an enforced, consistent style across the codebase.

My proposal for this would be to have a [rustfmt.toml](https://rust-lang.github.io/rustfmt/?version=v1.4.36) that conforms to the existing style of the codebase as much as possible. We could then run `cargo fmt` on CI, or request that PR authors run it.

**Comment by expenses** [comment]
This is also mentioned briefly here: https://hackmd.io/u_HZ86QHRm2Rp1gG1b2R1g?view

**Comment by gilescope** [comment]
Most of substrate's clients will expect cargo fmt. If rustc can do it then I can't see why we can't.

**Comment by thiolliere** [comment]
some historical discussion on this subject: https://forum.parity.io/t/simplify-reviews-whitespace-changes-vs-cargo-fmt/428/15

**Comment by gilescope** [comment]
Not unexpected. Perfection is impossible, but consistency is possible. We will not be able to rust fmt the codebase in a way that everyone is happy with, but perhaps we can do it such that no one person is too unhappy with the result. That would be a win.

**Comment by thiolliere** [comment]
I still find the issue relevant, we should conclude on the opened PR

**Comment by gilescope** [comment]
Totally agree. Spent a lot of time over the last day or two altering line
lengths and formatting. It should be a thing of the past.

**Comment by gilescope** [comment]
We can close this issue now or should we do the same for polkadot?

**Comment by bkchr** [comment]
Can be closed now.
