### ISSUE TITLE
Why logs by default goes to stderr instead of stdout? How do we change that?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#8994]
If will be helpful if we can make logs (at lease non WARN/ERROR level logs) goes to stdout instead of stderr.

Our hosted logging solution by default categorize all logs in stderr as ERROR level and doesn't play nice with the default behavior of Substrate.

If will be helpful if there is a way for us to change the default behavior.

**Comment by NukeManDan** [comment]
Before this has a setting in substrate (unless I am missing it) you could work round with [redirecting stderr to std](https://tldp.org/LDP/abs/html/io-redirection.html)
