### ISSUE TITLE
FRAME Storage `remove_all` API should have a key limit 

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#9002]
Similar to the `storage_kill` api in child tries, the `remove_all` api on any maps should also have an optional key limit to enforce weight restrictions.

https://github.com/paritytech/substrate/pull/8166

When calling `remove_all`, a user should also be able to include `Option<u32>`, which describes the maximum number of keys that can be removed at once.

At the end of the operation, you can return `AllRemoved(u32)` or `SomeReamining(u32)` with the number of items that were actually removed at the end of the operation.

Should reuse and rename `KillChildStorageResult`:

https://github.com/paritytech/substrate/blob/master/primitives/io/src/lib.rs#L89

**Comment by xlc** [comment]
https://github.com/paritytech/substrate/issues/8742

**Comment by shawntabrizi** [comment]
ah didnt see it. Yeah this is a bit more descriptive, and I will have someone work on it soon.
