### ISSUE TITLE
Kademlia is in fact unidirectional

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate#901]
There was a misunderstanding of the libp2p specs. Kademlia is in fact unidirectional, meaning that if nodes A and B want to query each other they each have to open their own substream.

cc https://github.com/libp2p/rust-libp2p/issues/557

The change can be done either in a backwards compatible way (ie. accept incorrect remotes but do it correctly) or in a breaking way.

**Comment by gavofyork** [comment]
@tomaka is this still relevant?

**Comment by tomaka** [comment]
This has been fixed in upstream libp2p. I've been working on updating Substrate for the latest version.
