### ISSUE TITLE
Add support to `&[&[u8]]` in `runtime_interface` Macro

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#9015]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/1860335/120730043-91899a80-c4ae-11eb-8d54-2e614679c6a5.png">

**Comment by bkchr** [comment]
This is not really easily doable.

1. We can send the data to the host in this format. Yeah.
2. However, we would decode it as `Vec<Vec<u8>>` and there is no easy way to convert this into `&[&[u8]]` in a generic way.

**Comment by burdges** [comment]
Anyone know if Servo handles structures like `&[&[u8]`?  I know it passes JS "Vec"s into some native type based upon SpiderMonkey's allocator, meaning zero copies. I've always assumed Servo WASM could handle `&[&[u8]` without reallocation or copies.

**Comment by bkchr** [comment]
Not sure if they can handle this, but is that soo important?
