### ISSUE TITLE
How to support gPRC or ptotobuf?

### ISSUE THREAD

**Issue by rise0chen** [paritytech/substrate#9031]

**Comment by bkchr** [comment]
Can you be more specific?

**Comment by rise0chen** [comment]
I want to use for IoT devices
, and replace json RPC with gRPC.

**Comment by bkchr** [comment]
Nothing holds your from creating gRPC bindings

**Comment by adoerr** [comment]
If our idea is to do some sort of sensor data fusion/aggregation, you might want to have a look at the [Off-chain Worker](https://substrate.dev/recipes/off-chain-workers/index.html).
