### ISSUE TITLE
How to use "full_crypto" feature from sp-core in pallet?

### ISSUE THREAD

**Issue by shelbyd** [paritytech/substrate#9032]
I have a simple pallet that needs to verify a signature outside of the standard Origin mechanism. I've been using the [Pair](https://docs.rs/sp-core/3.0.0/sp_core/crypto/trait.Pair.html) trait.

The `Pair` trait is locked behind the `full_crypto` feature of the `sp-core` crate. When I enable the `full_crypto` feature, for WASM builds I get the following error:

```
error[E0046]: not all trait items implemented, missing: `Pair`
   --> /home/shelbyd/.cargo/git/checkouts/substrate-7e08433d4c370a21/70ef0af/primitives/application-crypto/src/lib.rs:441:3
    |
441 |         impl $crate::CryptoType for Signature {}
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `Pair` in implementation
    |
   ::: /home/shelbyd/.cargo/git/checkouts/substrate-7e08433d4c370a21/70ef0af/primitives/application-crypto/src/ecdsa.rs:29:5
    |
29  |     crate::app_crypto!(super, ECDSA);
    |     --------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
    = help: implement the missing item: `type Pair = Type;`
```

This seems to originate from sp-application-crypto, since it doesn't have the full_crypto feature enabled without default features. I'm directly including the `frame-support` crate, which includes `sp-runtime`, which includes `sp-application-crypto`. I can resolve that issue by specifying `sp-application-crypto` as a dep of my pallet with the full_crypto feature specified.

Doing that, it now seems to require an allocator.

```
error: failed to run custom build command for `fractal-protocol-blockchain-runtime v0.0.1 (/home/shelbyd/workspace/fractal-protocol/blockchain/runtime)`

Caused by:
  process didn't exit successfully: `/home/shelbyd/workspace/fractal-protocol/blockchain/target/debug/build/fractal-protocol-blockchain-runtime-68771b059d76d3e5/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "/home/shelbyd/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/home/shelbyd/workspace/fractal-protocol/blockchain/target/debug/wbuild/fractal-protocol-blockchain-runtime/Cargo.toml" "--color=always" "--release"
  Using rustc version: rustc 1.53.0-nightly (42816d61e 2021-04-24)


  --- stderr
     Compiling fractal-protocol-blockchain-runtime-wasm v1.0.0 (/home/shelbyd/workspace/fractal-protocol/blockchain/target/debug/wbuild/fractal-protocol-blockchain-runtime)
  error: `#[alloc_error_handler]` function required, but not found.

  note: Use `#![feature(default_alloc_error_handler)]` for a default error handler.

  error: `#[panic_handler]` function required, but not found

  error: aborting due to 2 previous errors

  error: could not compile `fractal-protocol-blockchain-runtime-wasm`
```

Is there a standard way of verifying signatures in pallet code that I can reference?

Separately, I could redesign the feature I'm working on to use an extrinsic sent by the signer of this data. My problem with that is I'd still like the sender of this extrinsic to pay the transaction fee instead of the original signer, and I don't see a way to do that.

**Comment by bkchr** [comment]
`full-crypto` doesn't support WASM.

Check the `RuntimePublic` trait in `application-crypto/traits.rs` or the raw verify methods in `sp-io`

**Comment by shawntabrizi** [comment]
> Is there a standard way of verifying signatures in pallet code that I can reference?

Yes:

* https://github.com/paritytech/polkadot/blob/master/runtime/common/src/purchase.rs#L374
* https://github.com/paritytech/polkadot/blob/master/runtime/common/src/crowdloan.rs#L421
* https://github.com/paritytech/polkadot/blob/master/runtime/common/src/claims.rs#L587
