### ISSUE TITLE
Missing "staking(Bonded)" event associated to "staking(rebond)"

### ISSUE THREAD

**Issue by TheGoldenEye** [paritytech/substrate#9039]
After executing a "staking(rebond)" extrinsic I miss the associated "staking(Bonded)" event. 
Unfortunately it is not possible to track bonding/unbonding/rebonding this way.
I think "staking(Bonded)" should be triggered in response to "staking(rebond)", possibly a new event as well.

**Comment by shawntabrizi** [comment]
Thanks for the report! I opened a PR
