### ISSUE TITLE
[contracts] `seal_debug_message` not showing up in process output

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate#9051]
I'm running `canvas-node` with

```
cargo run --features contracts-unstable-interface -- --dev --tmp -lerror,runtime::contracts=debug
```
The feature is used by default in the `canvas-node`, I'm just putting it here for clarity.

I took the CLI flags from the [`contracts` readme](https://github.com/paritytech/substrate/tree/master/frame/contracts#debugging).

I modified our flipper examples `Cargo.toml` with
```
ink_env = { version = "3.0.0-rc3", path = "../../crates/env", default-features = false, features = [ "ink-debug" ] }
```
and added a couple `ink_env::debug_println!("---------");` in the contract.
None of those show up on the console when I deploy the contract and interact with it.

I added a couple `log::debug!` statements in the `contracts` pallet's `fn seal_debug_message(…)` and found that `fn append_debug_buffer(…)` always returns `false` [here](https://github.com/paritytech/substrate/blob/master/frame/contracts/src/exec.rs#L1292), which makes [this condition](https://github.com/paritytech/substrate/blob/master/frame/contracts/src/wasm/runtime.rs#L1680) omit appending the debug message. Setting an explicit `--execution native` doesn't change this.

**Comment by athei** [comment]
Works on substrate. The reason why it does not work on canvas is because you need to enable it in your runtime API implementation. You need to pass `true` as last parameter to `bare_call` and `bare_instantiate`:
https://github.com/paritytech/canvas-node/blob/c69023ad51ff0ed8974d0f651fa5ded5d9bf552e/runtime/src/lib.rs#L516-L536

**Comment by cmichi** [comment]
Great, thx!
