### ISSUE TITLE
js glue code for wasm-binary with wasm-builder

### ISSUE THREAD

**Issue by zababurinsv** [paritytech/substrate#9058]
Please tell me if it is possible to build [wasm](https://github.com/paritytech/substrate/tree/master/utils/wasm-builder#wasm-builder-is-a-utility-for-building-a-project-as-a-wasm-binary) with js glue code? If not. Is it possible to do this with wasm-pack ?

**Comment by bkchr** [comment]
Why would you like to do this?

**Comment by zababurinsv** [comment]
I dealt with the project. I was answered [here](https://github.com/paritytech/substrate-connect/issues/300)
