### ISSUE TITLE
Allow contracts to query whether an address is a contract

### ISSUE THREAD

**Issue by athei** [paritytech/substrate#9064]
The following APIs should be introduced for contracts to call:

```rust
fn is_contract(account_id: AccountId) -> bool;
fn caller_is_origin() -> bool;
```

Technically, `caller_is_origin` might not be required as `is_contract(self.caller())` could be used for that. However, `caller_is_origin` can be implemented without any storage lookup and therefore uses less gas. Sometimes it is useful to check whether a contract is called by another contract or the origin. `caller_is_origin` is a cheap way to do so.

Please note that when being called as RPC the origin can indeed be a contract just because the RPC allows the sender to be specified freely. This does not matter here because during on-chain execution the origin can never be a contract and therefore no interaction with dry-running can occur.

Does this API make sense to you @Robbepop @cmichi @ascjones  ?

The issue came up here: https://github.com/paritytech/ink/issues/804

**Comment by cmichi** [comment]
Yes, makes sense to me.

**Comment by athei** [comment]
Updated `is_contract` to be `bool` because tombstones no longer exist.
