### ISSUE TITLE
Rename `AllPallets` to `AllPalletsWithoutSystem` and `AllPalletsWithSystem` to `AllPallet`

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/substrate#9105]
Let's remove one more footgun.

Where is `AllPalletWithoutSystem` useful?

cc @thiolliere

**Comment by thiolliere** [comment]
yes, but we have to careful that people don't miss this change, and execute some system stuff 2 times.
Maybe for a better transition we should do: rename `AllPalletsWithSystem to AllPallet` in another release or find another name which doesn't conflict, like `AllPalletsTuple` or `PalletsTuple` while deprecating `AllPallets`

**Comment by KiChjang** [comment]
I like to be more pedantic and have `AllPalletsWithSystem` and `AllPalletsWithoutSystem`. That way there's no way people can mistake one for the other.

**Comment by TomaszWaszczyk** [comment]
The issue relies only on renaming  types `AllPallets` and `AllPalletsWithSystem` or also some changes in logic? What version of changes should be implemented, version of @shawntabrizi or @KiChjang ?

I look for practical experience in Rust and I am willing to implement simple tasks.

**Comment by thiolliere** [comment]
IMO we should do KiChjang suggestion, otherwise people will very likely miss the breaking change.
But having PalletsTuple wasn't

**Comment by thiolliere** [comment]
Or a new name with deprecated old type alias
```rust
type AllPalletsTuple = ..
type AllPalletsTypleWithoutSystem = ..
#[deprecated(..)]
type AllPallets = AllPalletsTupleWithoutSystem
#[deprecated(..)]
type AllPalletsWithSystem = AllPalletsTuple
```
