### ISSUE TITLE
`VotingDataOf<T>` is a complicated tuple which should be a struct

### ISSUE THREAD

**Issue by coriolinus** [paritytech/substrate#9152]
Lets avoid tuples, and use a struct instead.

_Originally posted by @shawntabrizi in https://github.com/paritytech/substrate/pull/9081#discussion_r655036353_

**Comment by kianenigma** [comment]
would be good if we close this soon to keep the backlog clear

**Comment by emostov** [comment]
@kianenigma can I take a stab at this next week?

**Comment by kianenigma** [comment]
not relevant anymore.
