### ISSUE TITLE
Fully self-descriptive metadata types

### ISSUE THREAD

**Issue by emielvanderhoek** [paritytech/substrate#917]
One thing I am missing has to do with the Types one can find in the Metadata. 

Some types are (Rust?!) base types such as ‘u32’, ‘bool’ or base structures such as ‘vec’. It is quite clear how to deal with these in an objective manner.

What I am missing has to do with the higher level objects such as T::Balance, ValidatorPrefs, Address, et cetera. The metadata is not self-descriptive enough to ‘know’ the composition of these higher level objects/structures. Hence an outside system (such as a 'generalized substrate explorer' [https://polkascan.io]) would need to ‘hard code’ the composition of such types or structures.

So I suppose what i am suggesting is to extend the metadata with a description of the composition of higher level objects and structures.

PS: discussion with Gavin on Riot hinted that this is  non-trivial change and will likely not be picked up before 2020. Hence this issue is for future reference.

**Comment by thiolliere** [comment]
Some update on it, this will be solved by using scale-info https://github.com/paritytech/scale-info so that full type description will be available in the metadata.

Some more advancment detail https://github.com/paritytech/substrate/issues/7971#issuecomment-766762778

**Comment by emielvanderhoek** [comment]
Almost 2.5 years in the making :)

This feature will (hopefully) lower the maintenance burden on the API-layer teams significantly.
The Polkascan team really looks forward to this feature.

**Comment by shawntabrizi** [comment]
@ascjones How close are we on this?

We have some ideas which may be temporary fix in the meantime if this will take 6-8 more months.

**Comment by ascjones** [comment]
Not that long for sure, on the home stretch now - maybe 1-2 months depending on how much time I can dedicate to it, and also what we decide to do about where the metadata itself will be stored (discussed in https://github.com/paritytech/substrate/discussions/8370)

What's your specific use case and what did you have in mind? One approach would be for me to manually generate the metadata for your runtime in the new format, which is possible before all my work gets merged into master.

Also see

**Comment by xlc** [comment]
Some patched version `Encode`/`Decode` derive that generates the type metadata and print them on with some special build flag will already be useful. At this will allow us easily to maintain the type definition that currently are manually created.

**Comment by shawntabrizi** [comment]
yes, that was my hack solution too. Create some kind of temporary RPC which will have the types needed for that node to work.

**Comment by apopiak** [comment]
Let's get that hacky thing going

**Comment by thiolliere** [comment]
WIP https://github.com/paritytech/substrate/pull/8615
