### ISSUE TITLE
RPC <-> chain spec

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#918]
The chain-spec should include a new top-level item: "properties". This should map to a JSON object. An extra RPC should be provided `system_properties` which returns that JSON object.

**Comment by emielvanderhoek** [comment]
This allows for Polkascan.io (Explorer) and the js-UI to strip hardcoded constants per Substrate-instance and be a generic as possible.

Suggestions for such properties:

1. 'ss58'-prefix (0x44 for BBQ Birch, 0x2a for Polkadot testnet)
2. network-name ("BBQ Birch")
3. unit denominations (dot, birch, bbq, et cetera)
