### ISSUE TITLE
decide whether to make election consts into storage items

### ISSUE THREAD

**Issue by coriolinus** [paritytech/substrate#9185]
> As you have also noticed recently, it is a big PITA to go through a full runtime upgrade cycle in order to make any changes. I am becoming more a fan of making as many of configs as possible, a storage item, and a a root controlled call to set them/each.
>
> Note that this should only be possible for configs that are transient. For example, if deposits are recorded on-chain, then we can change the deposit on the fly. But If it weren't, this would have not been valid. 
>
> I think `SignedMaxSubmissions`, `SignedRewardBase`, and the 3 deposits could be storage items. WDYT?

_Originally posted by @kianenigma in https://github.com/paritytech/substrate/pull/7910#discussion_r656151493_

> We have to be smart about when to use such things. There is a non-zero overhead to making things storage items, and this sees to me to be a configuration which will be very infrequently updated. But just something to consider, not saying one way or another.

_Originally posted by @shawntabrizi in https://github.com/paritytech/substrate/pull/7910#discussion_r656935247_

We need to choose whether or not to refactor these election consts into storage items.

**Comment by kianenigma** [comment]
would be good if we close this soon to keep the backlog clear

**Comment by kianenigma** [comment]
Decision is: no.
