### ISSUE TITLE
State already discarded for BlockId

### ISSUE THREAD

**Issue by xueyouzhang9527** [paritytech/substrate#9194]
when I ran a validator as a full node by `substrate --dev --tmp --unsafe-pruning --pruning 5`,  and called RPC `getBlock(hash)` but got an unknown error `Unknown error occurred: Client, UnknownBlock, State already discarded for BlockId::Hash`. It seems like that the full node also prunes block data. 

> A full node is pruned, meaning it discards all information older than 256 blocks, but keeps the extrinsics for all past blocks, and the genesis block. A node that is pruned this way requires much less space than an archive node..

from [Set up a Full Node](https://wiki.polkadot.network/docs/maintain-sync)

**Comment by bkchr** [comment]
If you use curl it works:
```
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "chain_getBlock", "params":["0xc4d8064e64a6f275ce0c5cc5355f95021b3c12fd3fb3341b720364c818c92bea"]}' http://localhost:9933
```

It is polkadot-js that tries to fetch the `RuntimeVersion` and fails. @jacogr maybe it could show a better error when it fails at some intermediate rpc.
