### ISSUE TITLE
Automatically impl deposit_event 

### ISSUE THREAD

**Issue by gavofyork** [paritytech/substrate#920]
The `decl_module` macro should automatically impl the `deposit_event` function. Right now it's manually implemented in each module which is boilerplatey.

**Comment by guanqun** [comment]
not all srml module implemented `deposit_event`, should we add a switch/flag in the `decl_module` to decide if we need to implement this function?

**Comment by gavofyork** [comment]
yup.

**Comment by gavofyork** [comment]
yes
