### ISSUE TITLE
Allow for childstate queries for multiple child keys

### ISSUE THREAD

**Issue by jacogr** [paritytech/substrate#9203]
Current we have childstate queries for single keys, 

```
getStorage(
  childKey: PrefixedStorageKey,
  key: StorageKey,
  at: Option<Hash>
): Option<StorageData>
``` 

This approach work quite well. However in places where we do use childstate (e.g. crowdloans) we actually want to get multiple entries. For instance, I have 4 accounts for contributed to a specific crowdloan and to retrieve the values need to do 4 individual requests. This is in the cases where I know that the specific accounts have contributed.

Now look at the case where I may want to check if some of my accounts contributed to a specific loan. To do this would need to make X indv. RPC calls (where X = number of available accounts). For an RPC-user perspective and from an Node overhead perspective, it would potentially be much more optimal to have a signature such as -

```
/// getStorages? getEntries? Not sure about the naming...
getEntries(
  childKey: PrefixedStorageKey,
  keys: Vec<StorageKey>,
  at: Option<Hash>
): Vec<Option<StorageData>>
```

Which would allow us to query a specific childtrie to retrieve the values for more than one key in a single request.

**Comment by hirschenberger** [comment]
On which level needs this to be implemented? Is it enough to just call the client's `child_storage` function for each key, collect the data and return it or is there also a new Trie-Backend function required which is probably more efficient by reducing database operations?
