### ISSUE TITLE
Consider moving client-only and frame-only primitives out of `primitives`

### ISSUE THREAD

**Issue by expenses** [paritytech/substrate#9214]
`primitives` is meant to contain shared components.

**Comment by expenses** [comment]
Pinging @seunlanlege @gilescope

**Comment by expenses** [comment]
- [ ] #9214

**Comment by gilescope** [comment]
Will take a crack at this as v similar to yesterday's.

**Comment by bkchr** [comment]
Duplicate of: https://github.com/paritytech/substrate/issues/5485
