### ISSUE TITLE
`submit` call in `election-provider-multi-phase` doesn't really need witness parameter

### ISSUE THREAD

**Issue by coriolinus** [paritytech/substrate#9229]
https://github.com/paritytech/substrate/blob/3f7d2b7658cb87de61b75e3a782d17abd8a915d1/frame/election-provider-multi-phase/src/lib.rs#L923-L928

The `submit` call currently requires `num_signed_submissions`, which is verified to be the current number of signed submissions queued. However, this has minimal effect on the actual weight of the function:

(From [here](https://github.com/paritytech/polkadot/blob/68074a7ffa57d51d5c028a330199d03bf92bf740/runtime/polkadot/src/weights/pallet_election_provider_multi_phase.rs#L105-L111)):

```rust
	fn submit(c: u32) -> Weight {
		(78_972_000 as Weight)
			// Standard Error: 16_000
			.saturating_add((308_000 as Weight).saturating_mul(c as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
```

`c` will always be between 0 and 16 (from [here](https://github.com/paritytech/polkadot/blob/68074a7ffa57d51d5c028a330199d03bf92bf740/runtime/polkadot/src/lib.rs#L337)); `308_000 * 16` is approximately equal to 5 milliseconds, or 1/5 of a database read. 

We can improve usability without substantially affecting performance by dropping the parameter.

**Comment by kianenigma** [comment]
needs the staking miner to also be updated.

**Comment by niklasad1** [comment]
Closed by https://github.com/paritytech/substrate/pull/10945
