### ISSUE TITLE
Explore adding an event for the staking pallet's `chill_other`

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate#9242]
The `chill_other` extrinsic does not emit any events. Adding an event may help improve the ergonomics of researching the staking apparatus. In particular it would make it easier to find instances of the call in explorers that support event based lookup. Many explorers do not support lookup of nested calls (i.e. those made within batch/proxy etc).

**Comment by shawntabrizi** [comment]
@emostov yeah just add one for all the chill events.
