### ISSUE TITLE
can we make the same return between "node-template   export-blocks" and  "rpc getBlock"

### ISSUE THREAD

**Issue by baidang201** [paritytech/substrate#9255]
can we make the same rt between "node-template   export-blocks" and  "rpc getBlock",than we can use rpc getBlock replace export-blocks to backup the block.

otherway, we can modify import-blocks Compatible with rpc  getBlock  format.

```
node-template-export-blocks 3.0.0
Export blocks

USAGE:
    node-template export-blocks [FLAGS] [OPTIONS] [--] [output]
//////////////////////////////////////////////
getBlock(hash?: BlockHash): SignedBlock#
    interface: api.rpc.chain.getBlock
    jsonrpc: chain_getBlock
    summary: Get header and body of a relay chain block
```

![unknown](https://user-images.githubusercontent.com/3405789/124209423-1999a900-db1c-11eb-9cb9-bbef83941d3c.png)

**Comment by bkchr** [comment]
Please try with substrate node itself.

**Comment by baidang201** [comment]
Thank you, i make a misstake. i find  "nodejs api.rpc.chain.getBlock" is different from ' {"jsonrpc":"2.0","method":"chain_getBlock","params":["0xc39190845a3ba955a5526aa2db7e2c63133fb498c46690599bedf2eeec27458a"],"id":1}  
or 
./node-template export-blocks --dev --from 1 --to 1 1.data --pruning=archive" '

it means we can use to chain_getBlock backup Finalized block replace ./node-template export-blocks?

**Comment by bkchr** [comment]
> it means we can use to chain_getBlock backup Finalized block replace ./node-template export-blocks?

I don't see why not.
