### ISSUE TITLE
Unsafe methods without unsafe flag should not appear in rpc_methods

### ISSUE THREAD

**Issue by jacogr** [paritytech/substrate#9297]
Currently unsafe methods still appear in the `rpc_methods` RPCs although they are not callable. So the flow is basically -

- get `rpc_methods`
- decorate the available methods on the middleware, e.g. APIs
- user of middleware can now call them

On the 3rd step the RPC does return a "method not allowed" when the node is run without the unsafe flags.

However since these really cannot be called, don't believe the `rpc_methods` should actually return them. If not doing this is too much pain, I guess we can continue living with the status-quo.

I have had a number of support queries on this behavior since they _seem_ like they can be called, not sure if not returning/decorating it will make things worse (since there is now no error anywhere). But I guess at least documenting them as unsafe and then not returning them in the list would help... somewhat. 

It almost feel like a damned-if-you do, damned-if-you-don't case...

**Comment by xlc** [comment]
duplicates to https://github.com/paritytech/substrate/issues/7024

**Comment by jacogr** [comment]
Sorry, missed that one completely...
