### ISSUE TITLE
Node potentially not validating parachains

### ISSUE THREAD

**Issue by memuG** [paritytech/substrate#9301]
Hi,
I observe that my 1kv Validator performs extremely poorly last month with very low Era Points:
https://thousand-validators.kusama.network/#/leaderboard/Cp2kxaQCVbPCfEc1T2tFxvMWvaUDuuKqSfhxnkDjuLk3bxy

Had a discussion on 1KV Element Channel and after finding the below errors in logs, the suggestion was to submit this issue here. 
Could you please help me analyze why is the node facing the Network issues and what can be done to prevent it and make the Node work as normal.

Log errors from the time, the node has been active last week:

ESC[2m2021-07-04 12:27:32ESC[0m Some network error occurred when fetching erasure chunk origin=Public(f8a0de679938a5a93d013742fa52b6c640a76f891c2c719b0cce4f18c793c972 (J
CKBTobg...)) err=Network(DialFailure)
ESC[2m2021-07-04 12:27:32ESC[0m Some network error occurred when fetching erasure chunk origin=Public(f8a0de679938a5a93d013742fa52b6c640a76f891c2c719b0cce4f18c793c972 (J
CKBTobg...)) err=Network(DialFailure)
ESC[2m2021-07-04 12:27:32ESC[0m Some network error occurred when fetching erasure chunk origin=Public(f8a0de679938a5a93d013742fa52b6c640a76f891c2c719b0cce4f18c793c972 (J
CKBTobg...)) err=Network(DialFailure)
ESC[2m2021-07-04 12:27:32ESC[0m Some network error occurred when fetching erasure chunk origin=Public(f8a0de679938a5a93d013742fa52b6c640a76f891c2c719b0cce4f18c793c972 (J
CKBTobg...)) err=Network(DialFailure)

Hardware info:
4 Core CPU and 8 GB RAM, 120GB SSD.
Firewall:
To Action From
30333 ALLOW Anywhere

current load:
top - 13:12:11 up 13 days, 17:36,  1 user,  load average: 1.33, 1.54, 1.54
Tasks: 124 total,   1 running, 123 sleeping,   0 stopped,   0 zombie

%Cpu(s): 31.4 us,  6.6 sy,  0.0 ni, 60.1 id,  0.0 wa,  0.0 hi,  1.9 si,  0.1 st

MiB Mem :   7771.6 total,    918.9 free,   1807.2 used,   5045.6 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   5726.8 avail Mem

**Comment by iisaint** [comment]
Hi, 
I got the same problem since updating to  Polkadot v0.9.8. 

The p2p port 30333 is open. 
Hardware info: 8 vCPUs, 16 GB ram, 320 GB ssd. 

```
2021-07-10 13:19:15 Some network error occurred when fetching erasure chunk origin=Public(141e375700ca6444b8e1f320dbd5dee1ab25c2bf3a6bb4162d4fe81beeef8e66 (D2hT9HuS...)) err=Network(DialFailure)
2021-07-10 13:19:15 Some network error occurred when fetching erasure chunk origin=Public(c6816200922708c0cee8891acb1498727487383e364d3cc7b3de28eaf1c14b4f (H4bS7AQt...)) err=Network(DialFailure)
2021-07-10 13:19:15 Some network error occurred when fetching erasure chunk origin=Public(dc73630c508f2f82203ee56691863f1c0b2f3c0529801a94179a69894fc8c03e (HZNL4fPU...)) err=Network(DialFailure)
2021-07-10 13:19:15 Some network error occurred when fetching erasure chunk origin=Public(76f387cbe37ec3ddaf57a4351c038adb8189c45d3739459a7426071eb5d68c69 (FGHWe58E...)) err=Network(DialFailure)
```

Had another error when my node is chosen by a parachain validator.
```
fetch_pov_job err=FetchPoV(NetworkError(Network(Timeout)))
fetch_pov_job err=FetchPoV(NetworkError(Network(Timeout)))
```

**Comment by bkchr** [comment]
This can happen from time to time. So, everything is fine.

**Comment by memuG** [comment]
The Validator is performing this way for over a month now, so this is not "from time to time" and nothing is fine!
Do you maybe have any other suggestions?
