### ISSUE TITLE
env:ext_storage_clear_prefix_version_2 error while executing: system_accountNextIndex 

### ISSUE THREAD

**Issue by avolkov-dev** [paritytech/substrate#9303]
Node version is  0.9.7
Chain: Westend
Node is running in archive mode and this query was runing fine for some time. Then (today) it start erroring without any configuration changes (node was completely untouched). What can cause the issue?
```
curl --location --request POST 'http://5.9.2.71:8028' \
--header 'Content-Type: application/json' \
--data-raw '{"id":2, "jsonrpc":"2.0", "method": "system_accountNextIndex", "params":["5GuoS6u6AiCbEMX3Qprz42YpunghWkFrguB5Z3S71z6RyY6X"]}'

```
responds
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": 1,
        "message": "Unable to query nonce.",
        "data": "Application(VersionInvalid(\"RuntimeConstruction(Other(\\\"host doesn't provide such function: env:ext_storage_clear_prefix_version_2\\\"))\"))"
    },
    "id": 2
}
```

**Comment by lukanus** [comment]
+1 I'm experiencing the same issues. At the same time mainnet nodes are running fine.

**Comment by shawntabrizi** [comment]
You need to update to 0.9.8 client

**Comment by POMbn** [comment]
Chain: Polkadot
Running version 0.9.12

I am getting the same error:
Error: Service(Other("Failed to get runtime version: RuntimeConstruction(Other("host doesn't provide such function: env:ext_crypto_secp256k1_ecdsa_recover_compressed_version_2"))"))

![Capture](https://user-images.githubusercontent.com/93606242/142774533-277ef2db-79f8-4e9f-b529-97899216f809.PNG)

**Comment by flipchan** [comment]
> You need to update to 0.9.8 client
did this solve the problem?

Cant this be solved with a runtime migration?
I'm having the same problem:
```
Error: Service(Application(Application(VersionInvalid("RuntimeConstruction(Other(\"host doesn\\\'t provide such function: env:ext_storage_clear_prefix_version_2\"))"))))
```

https://github.com/edgeware-network/edgeware-node/issues/20
