### ISSUE TITLE
How to migrate AccountData?

### ISSUE THREAD

**Issue by librelois** [paritytech/substrate#9326]
I need to be able to browse the `AccountData` of all the accounts, I was sure it would be possible, as it is at least necessary to migrate a change of `AccountData`, but it doesn't seem possible without fork `frame_system`.

I would like to be able to call `translate_values` on the` StorageMap` storing the accounts, but frame_system only exposes this map via the `StoredMap` trait, a trait that does not allow to browse all the values :/

Is there a way to modify the `AccountData` of all accounts without fork `frame_system` ?

**Comment by bkchr** [comment]
CC @shawntabrizi @thiolliere

**Comment by thiolliere** [comment]
if you want to modify the AccountData you need to migrate the storage map: Account: https://substrate.dev/rustdocs/latest/frame_system/pallet/type.Account.html
you can call translate_values on it: https://substrate.dev/rustdocs/latest/frame_support/storage/types/struct.StorageMap.html#method.translate_values

I think this should answer your question, feel free to reopen for further questions
