### ISSUE TITLE
Make benchmark take into account the cost of decoding the call

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#9349]
Currently benchmark for calls doesn't take into account the cost of decoding the call. Instead we should take it into account as some big calls can be a bit expensive to decode.

**Comment by thiolliere** [comment]
This PR fix it for the benchmarks which are not manual https://github.com/paritytech/substrate/pull/9343
Still need to be fixed for manual benchmarks

**Comment by shawntabrizi** [comment]
Can it be fixed for benchmarks which are manual?

I think probably not, so it should be out of scope here.

**Comment by thiolliere** [comment]
For manual benchmark, we should do the decoding of call inside the benchmark, it is doable.

It doesn't apply to manual benchmark which doesn't benchmark for a specific call though

**Comment by hirschenberger** [comment]
Is this the way?

https://github.com/hirschenberger/substrate/commit/90f8154ec4998fc4f7f9beb9eae1011043188960

**Comment by thiolliere** [comment]
Yes it is, note that for those 2 calls it seems we can rewrite them with the syntax `benchmark_name { init }: call_name(args)`
But your implementation is also good.

**Comment by hirschenberger** [comment]
I'd like to work on this. I convert all possible places to the specific call syntax.

Is it ok to panic in this case or do I have to use expect when decoding? Wouldn't it be possible to implement `From<parity_scale_codec::Error> for BenchmarkError` so that one can use `?`?

**Comment by thiolliere** [comment]
the expect seems legit to me, the decoding shouldn't fail considering it has been encoded just above. The only way it would fail it is because encoding/decoding is not correctly implemented.
But if returning the error is doable then it should also be fine.

**Comment by hirschenberger** [comment]
EDIT: I meant unwrap, not panic. So that I can save the explanation

**Comment by thiolliere** [comment]
some `expect` with very short explanation seems better to me (, or `?`), even if benchmark are not critical I think it is a good practice

**Comment by hirschenberger** [comment]
How can I format benchmark code? It seems as if `cargo +nightly fmt --all` does not touch it.

**Comment by thiolliere** [comment]
Yes, because it is code inside a non-attribute macro. It should be improved indeed, by creating a new way to declare benchmark with an attribute macro. I'll add this note in this tracking issue https://github.com/paritytech/substrate/issues/9513
