### ISSUE TITLE
Customized checks of signed extrinsics before entering the mempool

### ISSUE THREAD

**Issue by h4x3rotab** [paritytech/substrate#9363]
Extrinsics go to the mempool, get included in a block, and then they are executed, giving out the result if the execution. Validating the extrinsics in block is necessary to keep the consistency of the state. However, some extrinsics can be checked early, e.g. before entering the mempool, like Bitcoin. In this case we can further offload the burden of the blockchain to network nodes.

How to implement such check in Substrate? For **unsigned extrinsics**, which is already widely used, we have a hook for that:

```rust
#[pallet::validate_unsigned]
impl<T: Config> ValidateUnsigned for Pallet<T> {
    type Call = Call<T>;
    fn validate_unsigned(source: TransactionSource, call: &Self::Call) -> TransactionValidity {
        // ....
    }
}
```

We can get the call arguments, read the pallet storage, and return if it's valid or not. But for **signed extrinsics**, I have searched a bit, it looks like we only have this defined in a runtime to check the extrinsic:

```rust
impl sp_transaction_pool::runtime_api::TaggedTransactionQueue<Block> for Runtime {
    fn validate_transaction(
        source: TransactionSource,
        tx: <Block as BlockT>::Extrinsic,
        block_hash: <Block as BlockT>::Hash,
    ) -> TransactionValidity {
        Executive::validate_transaction(source, tx, block_hash)
    }
}
```

... and it's not sure if this function is within a block execution context where we can check the call arguments against some storage items.

> ### Background
> 
> We are implementing a message queue pallet. Oracles submit messages with a sequence id in strict increasing order. In case there are multiple oracles submitting the same message (with the same sequence id), we will only accept the first extrinsic, but want to ignore the rest. So we want to reject all the messages with either:
>
> - the message sequence id is less than the known id in the pallet storage, or
> - the message sequence id is redundant with another extrinsic in the mempool,
>
>  to enter the mempool.

**Comment by thiolliere** [comment]
for signed extrinsic, you can use the SignedExtension mechanism.

The signed extension allow to give some logic to be executed when validating a transaction: https://substrate.dev/rustdocs/latest/sp_runtime/traits/trait.SignedExtension.html#method.validate

you can look at frame_system check_weight signed extension for example: https://github.com/paritytech/substrate/blob/fe663ed0e982e9a767a15d548f663dc0df294ca7/frame/system/src/extensions/check_weight.rs#L187-L264

**Comment by bkchr** [comment]
Yeah `SignedExtension` is what you are searching for. Closing this issue, please reopen if you have further questions.

**Comment by h4x3rotab** [comment]
Thanks for the answer! It's really helpful.

I got a few questions thought:

1. `SignedExtension` can be used to attach some data to an extrinsic (e.g. nonce), and it means the client (e.g. polkadot.js) must be aware of it to sign transactions. In my case, no data needs to be attached. So do I need to change the upstream client if I add a check there?
2. The return value of `validate()` has two fields: `provides` and `requires`. Sounds like it can be used to build a dependency graph like bitcoin tx. Does it imply the block author will sort the transaction pool and apply the extrinsics in the topological order?

**Comment by h4x3rotab** [comment]
Done at https://github.com/Phala-Network/phala-blockchain/pull/372. Confirmed both polkadot.js and subxt works without any change.

> Note that in principle we should add the corresponding logic of a SignedExtension to all the Substrate clients (i.e. Polkadot.js, subxt). However since CheckMqSequence doesn't attach any data to a transaction, it can be treated as no-op safely. Polkadot.js and subxt noticed the extension, but fortunately they didn't refuse to work. It may not be the case in the future.

**Comment by bkchr** [comment]
> Thanks for the answer! It's really helpful.
> 
> I got a few questions thought:
> 
>     1. `SignedExtension` can be used to attach some data to an extrinsic (e.g. nonce), and it means the client (e.g. polkadot.js) must be aware of it to sign transactions. In my case, no data needs to be attached. So do I need to change the upstream client if I add a check there?

Yes that is right. Polkadot-js also supports custom signed extensions. You give the signed extension a name in your rust code and you can use this name in polkadot-js as well to register the extension there. For details you need to check the polkadot-js docs.

> 
>     2. The return value of `validate()` has two fields: `provides` and `requires`. Sounds like it can be used to build a dependency graph like bitcoin tx. Does it imply the block author will sort the transaction pool and apply the extrinsics in the topological order?

Yes that is right. This is for example used to order transactions based on the nonce.
