### ISSUE TITLE
pallet-balances may not be the only provider

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#9375]
https://github.com/paritytech/substrate/blob/0803f7d953938aa65de36993ed74cecb1f7b5407/frame/balances/src/lib.rs#L1416-L1419

It should be using `can_dec_provider` instead of `is_provider_required`.

Also need to have some tests to cover the case where pallet-balances is not the only provider. Or if there are multiple instances of it.

**Comment by shaunxw** [comment]
I think it could be closed now with #9411 merged.
