### ISSUE TITLE
Include the `rustfmt.toml` when generating the `node-template`

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate#9386]
With #8982 and #9381, the `node-template` now will be formatted with the same rustfmt settings, and we would like to propagate this file in the [the template generation tool](https://github.com/paritytech/substrate/blob/master/.maintain/node-template-release/src/main.rs) so that the [devhub node template](https://github.com/substrate-developer-hub/substrate-node-template) will always include the same `rustfmt.toml` file.

**Comment by ericjmiller** [comment]
Hi @NukeManDan.  I'm interested in contributing, so though I'd dip my toe in.  Thanks for the various mentor issues.  I think I'll start pecking away at those.
