### ISSUE TITLE
Make the allocator constraint available to the runtime

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate#9392]
The allocator has some limit: https://github.com/paritytech/substrate/blob/04f6f68397b05ca443cc1bba332b0833445a1508/client/allocator/src/freeing_bump.rs#L102

IMO this limit should be made available for the runtime. Otherwise it can be difficult to ensure it.

**Comment by bkchr** [comment]
IMO we should not have this limit at all :D

**Comment by thiolliere** [comment]
the total memory limit is still not available, though
