### ISSUE TITLE
`GetConst` trait for usage with `const` `parameter_types!`

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate#9407]
### Context

`frame_support::parameter_types` supports both `const` and `storage` "parameter type" creation. For `const` we require that the value is a constant and thus not mutable at runtime. On the other hand `storage` parameter types are mutable at runtime by changing the storage value.

### Problem

A pallet designer cannot guarantee that a parameter type is a constant and instead has to account for the fact that any `Config` parameter type may be mutable at runtime. In some cases this can make a pallets api unnecessarily brittle because the pallet designer either has to introduce logic to account for that parameter being mutable or just put a doc comment that the parameter type should be `const`.

### Solution

Introduce a `trait GetConst` which only `const` `parameter_types` implement. The trait could just require an impl for `fn get_const`. A pallet designer can then bound certain `Config` parameters with this trait if they desire immutability.

### Example use case

In the vesting pallet we are introducing a bounded vec to hold vesting schedules. The bound is dictated by the `Config` parameter `MaxVestingSchedules`. The potential benefits of a `GetConst` trait may be:
- If this bound is changed the weights for the pallets calls ideally should be recomputed. Both a `const` and weights can only be changed with a runtime upgrade, so if we assume weights are always done for a new runtime any change to this `const` should be accounted for.
- The runtime integrity test checking this value is at least 1 is only meaningful if we know it invariant at runtime.

**Comment by xlc** [comment]
We do have `#[pallet::constant]` annotation. I am wondering if we can reuse it? e.g. automatically add `GetConst` trait bound to it.

**Comment by shawntabrizi** [comment]
i dont think traits allow for the `getconst` we are looking for. We can instead literally put a const in the `Config` trait of the pallet. This should satisfy our requirements.
