### ISSUE TITLE
Why Doesn't nonfungibles::Mutate Specify a create_class Function?

### ISSUE THREAD

**Issue by danforbes** [paritytech/substrate#9419]
I'm having a little trouble understanding how to use the Uniques pallet, and it seems like one of the most straightforward ways to resolve my confusion would be to add a `create_class` function to the `nonfungibles::Mutate` trait. Otherwise, it seems entirely necessary for class IDs to be tracked off-chain, and that seems to be of limited utility. Why doesn't `nonfungibles::Mutate` specify a function to create an asset class? Alternatively/additionally, what is the intended use of the Uniques pallet with respect to making it easy for users to create asset classes with unique IDs?

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by danforbes** [comment]
Shawn shared the following thoughts with me via IM

> yeah seems like it is just an oversight or something
> dunno if it would make more sense to have the functionality in the Mutate trait, or just make a Create trait or something
> but either option is probably fine, and just needs a PR

I will look into making this enhancement 👍🏻
