### ISSUE TITLE
Avoid return DispatchResultWithPostInfo unless it is necessary 

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#9421]
https://github.com/paritytech/substrate/blob/5b55e01046cc78e0fd2dec962f73aabce676e8c4/frame/proxy/src/lib.rs#L639-L659

It doesn't make sense to have this return `DispatchResultWithPostInfo` as it doesn't refund weights.

It is misleading to user that it may refund weights, which doesn't make a lot of sense anyway. As a public method it cannot know how the itself is used and cannot return a reasonable value.

Most other `DispatchResultWithPostInfo` in pallet-proxy should also be changed to `DispatchResult`

**Comment by hirschenberger** [comment]
I have a PR. One question about formatting: Should the new rustfmt be applied to all changed files, the whole crate or not at all?

**Comment by bkchr** [comment]
To all files.

**Comment by hirschenberger** [comment]
> To all files.

You mean running `cargo +nightly fmt --all` in the basedir?

**Comment by bkchr** [comment]
Diffs to the already formatted code?

**Comment by hirschenberger** [comment]
Sorry, false alarm. I was missing the latest commits. There's two formatting changes in the current master:

```
client/network/src/request_responses.rs
frame/staking/src/lib.rs
```
PR follows...
