### ISSUE TITLE
Storage root mismatch

### ISSUE THREAD

**Issue by weichweich** [paritytech/substrate#9423]
We are seeing storage root mismatch errors on our test parachain. The issue is that the blocks are accepted by the relay chain, but only the block author can import the block. The other collators are failing with `panicked at 'Storage root must match that calculated.'`.

The problematic block doesn't contain any unusual extrinsic except our block reward payout which happens on every block.

We are running everything with version 0.9.8.

[Here are the logs.](https://github.com/paritytech/substrate/files/6867388/storage-error.zip) Collator 5 authored the block and collator 1 was unable to import it.

**Comment by bkchr** [comment]
I copied your report here: https://github.com/paritytech/cumulus/issues/532

I'm already looking into this other issue and I assume they are probably caused by the same bug
