### ISSUE TITLE
Publish test-runner

### ISSUE THREAD

**Issue by zjb0807** [paritytech/substrate#9505]
https://github.com/paritytech/substrate/blob/a2742a70d459dc60c79c7282205b1a987b64645a/test-utils/test-runner/Cargo.toml#L6

Please publish `test-runner` package. We can do some e2e tests with it.

**Comment by bkchr** [comment]
For what kind of e2e tests do you need this?

**Comment by zjb0807** [comment]
Test the RPC API.

And please set the fields `pub` in
https://github.com/paritytech/substrate/blob/a2742a70d459dc60c79c7282205b1a987b64645a/test-utils/test-runner/src/node.rs#L48-L73

**Comment by zjb0807** [comment]
https://github.com/paritytech/substrate/issues/8229

**Comment by bkchr** [comment]
1. The test runner stuff is far from being usable.
2. When you want to test RPC methods, you don't need the test runner.
3. Please check out our RPC tests.
