### ISSUE TITLE
Dependency circle in transaction pool

### ISSUE THREAD

**Issue by h4x3rotab** [paritytech/substrate#9509]
We can use SignedExtension's `provides` and `requires` outputs to build a tx dependency graph. Usually the graph is a DAG for a single extension (e.g. nonce). However, if two extensions give out different direction and form a dependency circle, what will happen? Will them be stuck at the transaction pool together until expiration?

**Comment by bkchr** [comment]
If you form a cycle, how should it break this up?

**Comment by h4x3rotab** [comment]
Only expire I think. Checked the docs of sc-transaction-pool and noticed it explicitly mentions to avoid circle.

Thanks!
