### ISSUE TITLE
Why does the POW authorship task prematurely terminate?

### ISSUE THREAD

**Issue by seunlanlege** [paritytech/substrate#9537]
https://github.com/paritytech/substrate/blob/777034d4d799fbb727d731d5b157e8a4ebaaf1d8/client/consensus/pow/src/lib.rs#L602-L604

If for some reason the metadata hasn't been updated with a new a block, the authorship task is prematurely terminated, without any error messages or documentation for this behaviour

cc @sorpaas

**Comment by bkchr** [comment]
> If for some reason the metadata hasn't been updated with a new a block

What is the reason you are talking about here?

**Comment by seunlanlege** [comment]
The authorship task itself sets the `MiningMetadata` on `MiningWorker ` here.

https://github.com/paritytech/substrate/blob/777034d4d799fbb727d731d5b157e8a4ebaaf1d8/client/consensus/pow/src/lib.rs#L697

at the same time, the authorship task uses this code to check if the worker is trying to build on the best block and prematurely terminates.

https://github.com/paritytech/substrate/blob/777034d4d799fbb727d731d5b157e8a4ebaaf1d8/client/consensus/pow/src/worker.rs#L76-L78

**Comment by seunlanlege** [comment]
now that i think about it, 

https://github.com/paritytech/substrate/blob/777034d4d799fbb727d731d5b157e8a4ebaaf1d8/client/consensus/pow/src/lib.rs#L575

this line too shouldn't terminate the authorship task

**Comment by bkchr** [comment]
Why? When you are syncing, it doesn't make any sense to build a block.

**Comment by bkchr** [comment]
> The authorship task itself sets the `MiningMetadata` on `MiningWorker ` here.
> 
> https://github.com/paritytech/substrate/blob/777034d4d799fbb727d731d5b157e8a4ebaaf1d8/client/consensus/pow/src/lib.rs#L697
> 
> at the same time, the authorship task uses this code to check if the worker is trying to build on the best block and prematurely terminates.
> 
> https://github.com/paritytech/substrate/blob/777034d4d799fbb727d731d5b157e8a4ebaaf1d8/client/consensus/pow/src/worker.rs#L76-L78

This is for making sure to not build on the same block twice.

**Comment by seunlanlege** [comment]
> This is for making sure to not build on the same block twice.

I understand this, what i don't understand is the `return` statement immediately after, shouldn't it be `continue` instead?

same goes for the line that checks for `major_syncing()`

**Comment by bkchr** [comment]
Yeah good point, that is a bug.
