### ISSUE TITLE
Use originally provided extrinsic payload to verify signature

### ISSUE THREAD

**Issue by shelbyd** [paritytech/substrate#9555]
I currently have an issue with a custom SCALE Encode/Decode implementation. I'm compiling the implementation to JS/WASM.

My transaction that uses the JS encoded representation is failing with `1010: Invalid transaction: Bad signature`. I believe it is because of the following psuedocode:

```
js_encoded = js_encode(obj);
rust_decoded = rust_decode(js_encoded);
rust_encoded = rust_encode(rust_decoded);

js_encoded != rust_encoded
```

Basically, this means that my implementation can parse the JS encoding, but the Rust encoding doesn't end up matching. I'm still investigating why.

Either way, the Substrate node is not accepting my transaction because, I assume, it is:

1. Decoding the original extrinsic payload (probably to check for validity)
2. Encoding the in-memory object
3. Checking the signature matches a newly generated payload using the Rust encoding

I know my implementation of Encode should work the same in Rust and JS, but Substrate should still use the original transaction payload to validate signatures.

**Comment by bkchr** [comment]
Even if we would do this it would fail later. The encoding needs to match, there is no way around this.
