### ISSUE TITLE
Debug instance for `Public` behaves weirdly on certain key

### ISSUE THREAD

**Issue by eskimor** [paritytech/substrate#9579]
I found this output in the logs of a validator: 

```
Public(0000000000000000000000000000000000000000000000000000000000000000 (CaKWz5om...)
```

The full address (from `SessionInfo`) seems to be: 

```
CaKWz5omakTK7ovp4m3koXrHyHb7NG3Nt7GENHbviByZpKp
```
The hex representation can hardly be all zeros.

It looks like the [`Debug instance`](https://github.com/paritytech/substrate/blob/4c3a55e7ca5c4c85c1eb53fd82ed71029d952510/primitives/core/src/sr25519.rs#L171) does something wrong for this key. Nothing obvious though.

**Comment by bkchr** [comment]
It can be zero. If the validator didn't set its key properly on chain, we use the default that is all zeros.
