### ISSUE TITLE
Add CheckedX for PerThing

### ISSUE THREAD

**Issue by KaiserKarel** [paritytech/substrate#9585]
We're using PerThings to keep track of pool allocations. Right now we're folding, deconstructing, summing and comparing with `PerThing::deconstruct` to ensure that the ratio is equal to 1 for the entire pool. Would be nice to have `CheckedAdd` implemented for this.

```
 let sum = config
    .items
    .iter()
    .fold(
        Some(config.reserved.deconstruct()),
        |sum, (_, allocation)| {
            sum.map(|sum| sum.checked_add(allocation.deconstruct()))
                .flatten()
        },
    )
    .ok_or(todo!())?;
ensure!(
    sum == Perquintill::one().deconstruct(),
    Error::<T>::AllocationMustSumToOne
);
```

**Comment by shawntabrizi** [comment]
@KaiserKarel do you want to make a PR for this?

**Comment by KaiserKarel** [comment]
Unless someone really wants this, but I have time this weekend to make a PR. :)

**Comment by kianenigma** [comment]
sounds like a good improvement to have! Looking forward @KaiserKarel
