### ISSUE TITLE
Effects and Interpretation of substrates `std`-feature flag

### ISSUE THREAD

**Issue by mustermeiszer** [paritytech/substrate#9597]
Hi, 

(when talking about `std` in the following I am referring to the substrate specific `std`-feature flag and not the standard runtime of rust)

I have a few questions regarding the `std`-feature flag and the consequences of it being activated or deactivated. 
Not sure, if this is the right place for this. Thanks in advance for your help.

* Does the feature flag indicated something like: "We are running in a no-wasm env"?
* Is it possible to activate `std` it in a wasm build without letting the build fail?
* Are there some (negative) consequences when using the `std` flag wrongly? (i.e. are there some assumptions made when this feature flag is active or not active)

Thanks again for your time!

**Comment by thiolliere** [comment]
> Does the feature flag indicated something like: "We are running in a no-wasm env"?

In substrate the wasm-runtime is built without std. Note that this is a choice, to keep the wasm-runtime as small as possible, but in general in rust it is possible to build a wasm binary with std enabled as far as I know.
I think in the codebase there is place where std is used to ensure it is not run in the wasm environment.

Also note that there was some thought given in the direction of removing the native runtime: https://github.com/paritytech/substrate/pull/8893

> Is it possible to activate std it in a wasm build without letting the build fail?

In general yes, but in substrate (and FRAME especially) I don't think it is possible to compile the wasm-runtime with std enabled.

**Comment by mustermeiszer** [comment]
Sorry, to re-assure here: Are you talking about std of rust, or the std-feature flag of substrate?

**Comment by thiolliere** [comment]
i don't see the difference between them. When we compile a crate without `std` feature, it is compiled without the rust standard library (or std of rust).
AFAIK we choose to compile the wasm-runtime without rust standard library to avoid having a big binary by using too much of it by mistake.

**Comment by mustermeiszer** [comment]
Mmh, okay. Then I have a few questions regarding some stuff that will not be available in wasm-env.But then for example the logic from [sp-state-machine](https://github.com/paritytech/substrate/blob/120793475f3fee4cee462ebd36196435a46e20ff/primitives/state-machine/src/lib.rs#L170-L985) will not be available. Especially the

**Comment by bkchr** [comment]
@mustermeiszer you can use this function here: https://github.com/paritytech/substrate/blob/master/primitives/trie/src/lib.rs#L304

This is available in `no_std`.

**Comment by mustermeiszer** [comment]
Thanks @bkchr.

**Comment by mustermeiszer** [comment]
For me this is reasonably explained and solved. Will close this here.
