### ISSUE TITLE
Contracts pallet - Add support for recovering public key from elliptic curve signatures (ECDSA)

### ISSUE THREAD

**Issue by PierreOssun** [paritytech/substrate#9609]
Can we add support for recovering public key from elliptic curve signatures (ECDSA) to !ink ?

We are trying to implement an ECDSA verifier in a contract. For this we are using recover function from the [libsecp256k1](https://github.com/paritytech/libsecp256k1) library developed by Parity and also used in Substrate.
The problem is that it uses a big list of constants that made cargo build fail due to its huge file size.
_As a note : We could compile the contract using rustflags to increase memory and the optimized WASM file size was 1.3 Mb_

In Ethereum, the [ecrecover](https://docs.soliditylang.org/en/v0.8.7/units-and-global-variables.html?highlight=ecrecover#mathematical-and-cryptographic-functions) function is implemented as a [precompiled contract](https://ethereum.stackexchange.com/questions/15479/list-of-pre-compiled-contracts) and can be called from any contract.
A suggested solution is to implement the EDCSA recover pub key logic in contracts-pallet level, so that it can be used by !ink contracts via ext calls (as it was implemented for hashes).
What do you think ?

**Comment by athei** [comment]
Makes sense to me. Contracts should not contain cryptographic code as it makes them way to big. 

> For this we are using recover function from the libsecp256k1 library developed by Parity and also used in Substrate.

A quick grep in substrate seems to suggest that it is in some `Cargo.toml` files but in no source file. Maybe an unused dependency. @gilescope  what do you think?

**Comment by PierreOssun** [comment]
Hello @athei 
It is used here:
https://github.com/paritytech/substrate/blob/16e17aeaa906ac12321286b5b6d5bdbefa030436/primitives/core/src/ecdsa.rs#L511

**Comment by bkchr** [comment]
@athei you probably want to use this here: https://github.com/paritytech/substrate/blob/b79e2b95c23adca8749fc38cba8e39aee1b32e1b/primitives/io/src/lib.rs#L784

And as @PierreOssun already pointed out, we use it in several places.

**Comment by athei** [comment]
Yeah I messed up my grep. This is great. We can use existing client functions for that.

**Comment by PierreOssun** [comment]
@athei 
If you agree to implement it, Supercolony can take care of it and do a Pull Request

**Comment by athei** [comment]
> @athei
> If you agree to implement it, Supercolony can take care of it and do a Pull Request

That would be great. But keep in mind that the biggest part of implementing this feature will be adding tests and benchmarks.

**Comment by atenjin** [comment]
related to https://github.com/paritytech/substrate/issues/8989, we think we not only need ecdsa recover, we also need more functions.

**Comment by xgreenx** [comment]
> related to #8989, we think we not only need ecdsa recover, we also need more functions.

Yea, but recovery is a feature only for ECDSA when verifying and signing must be implemented for all three supported key pairs.
