### ISSUE TITLE
Got this exception while running porta validator

### ISSUE THREAD

**Issue by grechman2** [paritytech/substrate#9613]
Hello guys!  Just saw this exception while running Porta validator. 

Aug 24 04:16:14 porta-n1 porta[82272]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /home/grechman/.cargo/git/checkouts/substrate-7e08433d4c370a21/70ef0af/frame/executive/src/lib.rs:462
Aug 24 04:16:14 porta-n1 porta[82272]: This is a bug. Please report it at:
Aug 24 04:16:14 porta-n1 porta[82272]:         https://github.com/paritytech/substrate/issues/new
Aug 24 04:16:15 porta-n1 porta[82272]: Hash: given=0dfebc48fbd9ed2c9aa787f2e9d6792c3c66d3d93f22fe72364213ee5b502285, expected=25b44a101af96f1ab18bc79e10101ed63d3f9ba90dd70d8708812697e51730fa
Aug 24 04:16:15 porta-n1 porta[82272]: ====================
Aug 24 04:16:15 porta-n1 porta[82272]: Version: 2.0.0-417b63b-x86_64-linux-gnu
Aug 24 04:16:15 porta-n1 porta[82272]:    0: sp_panic_handler::set::{{closure}}
Aug 24 04:16:15 porta-n1 porta[82272]:    1: std::panicking::rust_panic_with_hook
Aug 24 04:16:15 porta-n1 porta[82272]:              at rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:626:17
Aug 24 04:16:15 porta-n1 porta[82272]:    2: std::panicking::begin_panic::{{closure}}
Aug 24 04:16:15 porta-n1 porta[82272]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Aug 24 04:16:15 porta-n1 porta[82272]:    4: std::panicking::begin_panic
Aug 24 04:16:15 porta-n1 porta[82272]:    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
Aug 24 04:16:15 porta-n1 porta[82272]:    6: tracing::span::Span::in_scope
Aug 24 04:16:15 porta-n1 porta[82272]:    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
Aug 24 04:16:15 porta-n1 porta[82272]:    8: <porta_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,u32>,porta_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<porta_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<porta_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<porta_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<porta_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<porta_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<porta_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<porta_runtime::Runtime>)>>>>::execute_block
Aug 24 04:16:15 porta-n1 porta[82272]:    9: std::panic::catch_unwind
Aug 24 04:16:15 porta-n1 porta[82272]:   10: environmental::using
Aug 24 04:16:15 porta-n1 porta[82272]:   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Aug 24 04:16:15 porta-n1 porta[82272]:   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
Aug 24 04:16:15 porta-n1 porta[82272]:   13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Aug 24 04:16:15 porta-n1 porta[82272]:   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Aug 24 04:16:15 porta-n1 porta[82272]:   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Aug 24 04:16:15 porta-n1 porta[82272]:   16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Aug 24 04:16:15 porta-n1 porta[82272]:   17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Aug 24 04:16:15 porta-n1 porta[82272]:   18: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Aug 24 04:16:15 porta-n1 porta[82272]:   19: sp_api::Core::execute_block_with_context
Aug 24 04:16:15 porta-n1 porta[82272]:   20: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
Aug 24 04:16:15 porta-n1 porta[82272]:   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   28: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   29: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   31: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   32: std::thread::local::LocalKey<T>::with
Aug 24 04:16:15 porta-n1 porta[82272]:   33: futures_executor::local_pool::block_on
Aug 24 04:16:15 porta-n1 porta[82272]:   34: tokio::runtime::task::core::Core<T,S>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   35: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
Aug 24 04:16:15 porta-n1 porta[82272]:   36: tokio::runtime::task::harness::Harness<T,S>::poll
Aug 24 04:16:15 porta-n1 porta[82272]:   37: tokio::runtime::blocking::pool::Inner::run
Aug 24 04:16:15 porta-n1 porta[82272]:   38: tokio::runtime::context::enter
Aug 24 04:16:15 porta-n1 porta[82272]:   39: std::sys_common::backtrace::__rust_begin_short_backtrace
Aug 24 04:16:15 porta-n1 porta[82272]:   40: core::ops::function::FnOnce::call_once{{vtable.shim}}
Aug 24 04:16:15 porta-n1 porta[82272]:   41: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 24 04:16:15 porta-n1 porta[82272]:              at rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
Aug 24 04:16:15 porta-n1 porta[82272]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 24 04:16:15 porta-n1 porta[82272]:              at rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575:9
Aug 24 04:16:15 porta-n1 porta[82272]:       std::sys::unix::thread::Thread::new::thread_start
Aug 24 04:16:15 porta-n1 porta[82272]:              at rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys/unix/thread.rs:71:17
Aug 24 04:16:15 porta-n1 porta[82272]:   42: start_thread
Aug 24 04:16:15 porta-n1 porta[82272]:   43: clone

**Comment by bkchr** [comment]
What is porta?

This error indicates that a block was invalid. You should report this to the team building the chain you are using.
