### ISSUE TITLE
Contracts can no longer be uploaded

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate#9624]
Our `ink-waterfall` tests currently fail when trying to upload a contract which uses chain extensions. The upload fails in both Canvas UI, as well as polkadot-js. The error is `system.ExtrinsicFailed: Other`, hence I assume it's a Substrate issue.

It can be reproduced like this:
```
git clone --depth 1 https://github.com/paritytech/canvas-node.git

curl -s https://raw.githubusercontent.com/paritytech/ink/master/examples/rand-extension/runtime/chain-extension-example.rs >> canvas-node/runtime/src/lib.rs

sed -i 's/type ChainExtension = ();/type ChainExtension = FetchRandomExtension;/g' canvas-node/runtime/src/lib.rs

cargo run -- --tmp --dev -lerror,runtime::contracts=debug
```

And then deploy ink!'s [`rand-extension`](https://github.com/paritytech/ink/blob/master/examples/rand-extension/lib.rs) example with a UI of your choice. I've upload the compiled contract here: [rand_extension.contract.zip](https://github.com/paritytech/substrate/files/7046131/rand_extension.contract.zip).

It has been built with the latest `cargo-contract` and `cargo +nightly contract build`. It does not make a difference if I build it with `--release`.

cc @athei

**Comment by athei** [comment]
This is a regression introduced after merging https://github.com/paritytech/canvas-node/pull/71?

**Comment by cmichi** [comment]
Yes, it's a regression introduced with https://github.com/paritytech/canvas-node/pull/71. Everything works fine with the `Cargo.lock` before that.

**Comment by forgetso** [comment]
Is there a version of **canvas node** in which this is fixed or is it only on master? I've been hitting this error when deploying contracts with canvas release `v0.1.10` and when I build master I get a different issue related to `rococo-local`:

> (base) ➜  canvas-node git:(master) canvas --dev --tmp --unsafe-ws-external --rpc-cors all --ws-port=9944
> 2021-09-11 07:54:09 Canvas    
> 2021-09-11 07:54:09 ✌️  version 0.1.0-6f9b72b-x86_64-linux-gnu    
> 2021-09-11 07:54:09 ❤️  by Parity Technologies <admin@parity.io>, 2020-2021    
> 2021-09-11 07:54:09 📋 Chain specification: Development    
> 2021-09-11 07:54:09 🏷 Node name: acceptable-muscle-1176    
> 2021-09-11 07:54:09 👤 Role: AUTHORITY    
> 2021-09-11 07:54:09 💾 Database: RocksDb at /tmp/substrateC79vOY/chains/dev/db    
> 2021-09-11 07:54:09 ⛓  Native runtime: canvas-1 (canvas-0.tx1.au1)    
> Error: Input("Relay chain argument error: Invalid input: `rococo-local` only supported with `rococo-native` feature enabled.")

My build command was `cargo build --release --locked --features contracts-unstable-interface`


```
rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/chris/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2020-08-23-x86_64-unknown-linux-gnu
nightly-2021-06-28-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.55.0 (c8dfcfe04 2021-09-06)
```

**Comment by forgetso** [comment]
Thanks @athei the contracts node is working for me!
