### ISSUE TITLE
Tests are failing on `1.54.0` stable toolchain

### ISSUE THREAD

**Issue by rcny** [paritytech/substrate#9627]
Hi!

`ci-linux:production` image, which is used in Substrate and related projects pipelines, is stuck with `rustc 1.53.0 (53cb7b09b 2021-06-17)` due to failing tests on the recent stable. [Here is failing test job example](https://gitlab.parity.io/parity/substrate/-/jobs/1080766) with staging image bundled with `rustc 1.54.0 (a178d0322 2021-07-26)`.

I'm unable to gracefully promote current staging images into production images. Doing so forcefully will break stuff as in the example above.

**Comment by rcny** [comment]
Fails on the fresh `master` too:
[`test-linux-stable`](https://gitlab.parity.io/parity/substrate/-/jobs/1082083)
[`test-wasmer-sandbox`](https://gitlab.parity.io/parity/substrate/-/jobs/1082088)

**Comment by ordian** [comment]
FYI: rust 1.55 is out: https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html, can we go straight to 1.55?

**Comment by bkchr** [comment]
Yeah, probably a good idea :D
