### ISSUE TITLE
 `snow` which could resolve this conflict

### ISSUE THREAD

**Issue by abortrao** [paritytech/substrate#9680]
error: failed to select a version for `snow`.
    ... required by package `libp2p-noise v0.30.0`
    ... which is depended on by `libp2p v0.37.1`
    ... which is depended on by `sc-cli v0.10.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-08#4d28ebeb)`
    ... which is depended on by `frame-benchmarking-cli v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-08#4d28ebeb)`
    ... which is depended on by `node-template v3.0.0-monthly-2021-08 (/home/abel/subworkspace/substrate-node-template/node)`
versions that meet the requirements `^0.7.1` are: 0.7.2, 0.7.1

all possible versions conflict with previously selected packages.

  previously selected package `snow v0.7.1`
    ... which is depended on by `libp2p-noise v0.30.0`
    ... which is depended on by `libp2p v0.37.1`
    ... which is depended on by `sc-cli v0.10.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-08#4d28ebeb)`
    ... which is depended on by `frame-benchmarking-cli v4.0.0-dev (https://github.com/paritytech/substrate.git?tag=monthly-2021-08#4d28ebeb)`
    ... which is depended on by `node-template v3.0.0-monthly-2021-08 (/home/abel/subworkspace/substrate-node-template/node)`

**Comment by apopiak** [comment]
https://github.com/paritytech/substrate/pull/9391 bumps the libp2p version which will also bump snow, might be worth a try to cherry-pick.

**Comment by gilescope** [comment]
Hmm I can see that if I try and build Bit.Country master for example that this gets hit by this issue. I presume others will also hit this.

The prost 0.8 patch should probably be backported also as that seems to hit a fair few projects.

**Comment by bkchr** [comment]
> build Bit.Country master

Build what?

These monthly releases are absolutely random anyway and don't follow any real versioning.

**Comment by frisitano** [comment]
`sc-cli` will not build anymore.  I believe this is due to the one of the nested dependencies `aes-soft ^0.5.0` being yanked.  See below to recreate.

```
❯ cargo new hello_world --bin
     Created binary (application) `hello_world` package
❯ cd hello_world
❯ echo "sc-cli = { version = \"0.9.0\" }" >> Cargo.toml
❯ cat Cargo.toml
[package]
name = "hello_world"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sc-cli = { version = "0.9.0" }
❯ cargo build
    Updating crates.io index
error: failed to select a version for `snow`.
    ... required by package `libp2p-noise v0.29.0`
    ... which is depended on by `libp2p v0.34.0`
    ... which is depended on by `sc-cli v0.9.0`
    ... which is depended on by `hello_world v0.1.0 (PycharmProjects/reef/hello_world)`
versions that meet the requirements `^0.7.1` are: 0.7.2, 0.7.1

all possible versions conflict with previously selected packages.

  previously selected package `snow v0.7.1`
    ... which is depended on by `libp2p-noise v0.29.0`
    ... which is depended on by `libp2p v0.34.0`
    ... which is depended on by `sc-cli v0.9.0`
    ... which is depended on by `hello_world v0.1.0 (PycharmProjects/reef/hello_world)`

failed to select a version for `snow` which could resolve this conflict
```
