### ISSUE TITLE
Found this bug in the logs when the node was syncing

### ISSUE THREAD

**Issue by pro100programmer** [paritytech/substrate#9689]
![image](https://user-images.githubusercontent.com/87698760/132064788-ecb1c780-c483-45cf-a9c6-91338e98f267.png)

**Comment by pro100programmer** [comment]
I stopped the node. What I should do next?

**Comment by rphmeier** [comment]
cc @arkpar @bkchr State cache?

**Comment by bkchr** [comment]
@pro100programmer which project?

**Comment by mykolaGsystems** [comment]
The Porta
