### ISSUE TITLE
Move ss58-registry into its own crate

### ISSUE THREAD

**Issue by bkchr** [paritytech/substrate#9696]
The ss58-registry currently exists as the following json file: https://github.com/paritytech/substrate/blob/master/ss58-registry.json and once in code here: https://github.com/paritytech/substrate/blob/master/primitives/core/src/crypto.rs#L486

As it is generally a bad idea that we have two places for the same information, we should merge them. This was the idea from the beginning of the json file. So the following needs to be done:

1. Create a new crate in a separate repo (the name of the repo and crate needs to be decided on).
2. The repo contains the json file and this crate.
3. The crate parses at compile time the json file and generates the proper `Ss58AddressFormat` enum.
4. Release and integrate this crate into substrate.

**Comment by gilescope** [comment]
Great idea.
