### ISSUE TITLE
node gets stuck when importing blocks during startup

### ISSUE THREAD

**Issue by KalitaAlexey** [paritytech/substrate#9720]
It repeats "Scheduling 128 blocks for import".
Only once "Starting import of 128 blocks" and "Header 0x2e8a…ab76 has 2 logs".
And never "Block imported successfully".

I assume it gets stuck somewhere in client/service/src/client/client.rs Client::block_status.
Maybe at `self.importing_block.read()`

**Comment by bkchr** [comment]
Can you please share the cli commands you used and maybe the file with the blocks?
