### ISSUE TITLE
Why we need to reserve double balance if use `as_multi`?

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/substrate#9735]
If we use `as_multi_approve` code goes here
https://sourcegraph.com/github.com/paritytech/substrate/-/blob/frame/multisig/src/lib.rs?L590

Which pass `Zero` to `store_call_and_reserve`

```
T::DepositBase::get() = 1 * 20 * 10_000_000_000 + 88 * 100 * 100_000 = 200880000000
	+ T::DepositFactor::get() = 0 * 20 * 10_000_000_000 + 32 * 100 * 100_000 = 320000000
	* BalanceOf::<T>::from(((data.len() + 31) / 32) as u32)
```

---

If we use `as_multi` then here
https://sourcegraph.com/github.com/paritytech/substrate/-/blob/frame/multisig/src/lib.rs?L628

Which pass `deposit` to `store_call_and_reserve`

```
(
	T::DepositBase::get() = 1 * 20 * 10_000_000_000 + 88 * 100 * 100_000 = 200880000000
		+ T::DepositFactor::get() = 0 * 20 * 10_000_000_000 + 32 * 100 * 100_000 = 320000000
		* threshold.into() = 2
)
	+ T::DepositBase::get() = 1 * 20 * 10_000_000_000 + 88 * 100 * 100_000 = 200880000000
	+ T::DepositFactor::get() = 0 * 20 * 10_000_000_000 + 32 * 100 * 100_000 = 320000000
	* BalanceOf::<T>::from(((data.len() + 31) / 32) as u32)
```

**Comment by bkchr** [comment]
CC @shawntabrizi @thiolliere

**Comment by IkerAlus** [comment]
@AurevoirXavier I assume it is because with `as_multi` the whole call to be executed from the multisig account is stored whereas with `as_multi_approve` only the hash of the call is stored.
