### ISSUE TITLE
I've found a bug  D:

### ISSUE THREAD

**Issue by Solitud1nem** [paritytech/substrate#9745]
-- Logs begin at Tue 2021-09-07 11:22:37 UTC. --
Sep 10 07:39:33 Porta-1 porta[61173]: 2021-09-10 07:39:33  ⚙️  Syncing 305.5 bps, target=#845661 (14 peers), best: #13412 (0xf9ec…2cdc), finalized #13361 (0x1607…605f), ⬇ 160.2kiB/s ⬆ 5.3kiB/s
Sep 10 07:39:35 Porta-1 porta[61173]: 2021-09-10 07:39:35  [#14261] 🗳  Starting signed phase round  14.
Sep 10 07:39:35 Porta-1 porta[61173]: 2021-09-10 07:39:35  [#14311] 🗳  Starting unsigned phase(true ).
Sep 10 07:39:35 Porta-1 porta[61173]: 2021-09-10 07:39:35  [#14361] 🗳  Finalized election round wit h compute ElectionCompute::OnChain.
Sep 10 07:39:35 Porta-1 porta[61173]: 2021-09-10 07:39:35  [14361] 💸 new validator set of size 3 has been processed for era 13
Sep 10 07:39:38 Porta-1 porta[61173]: 2021-09-10 07:39:38  [#15461] 🗳  Starting signed phase round  15.
Sep 10 07:39:38 Porta-1 porta[61173]: 2021-09-10 07:39:38  [#15511] 🗳  Starting unsigned phase(true ).
Sep 10 07:39:38 Porta-1 porta[61173]: 2021-09-10 07:39:38  [#15561] 🗳  Finalized election round wit h compute ElectionCompute::OnChain.
Sep 10 07:39:38 Porta-1 porta[61173]: 2021-09-10 07:39:38  [15561] 💸 new validator set of size 3 has been processed for era 14
Sep 10 07:39:38 Porta-1 porta[61173]: 2021-09-10 07:39:38  ⚙️  Syncing 439.0 bps, target=#845662 (14 peers), best: #15607 (0x91c0…265f), finalized #15360 (0xf30a…2fe7), ⬇ 93.0kiB/s ⬆ 1.9kiB/s
Sep 10 07:39:40 Porta-1 porta[61173]: 2021-09-10 07:39:40  [#16661] 🗳  Starting signed phase round  16.
Sep 10 07:39:40 Porta-1 porta[61173]: 2021-09-10 07:39:40  [#16711] 🗳  Starting unsigned phase(true ).
Sep 10 07:39:40 Porta-1 porta[61173]: 2021-09-10 07:39:40  [#16761] 🗳  Finalized election round wit h compute ElectionCompute::OnChain.
Sep 10 07:39:40 Porta-1 porta[61173]: 2021-09-10 07:39:40  [16761] 💸 new validator set of size 3 has been processed for era 15

Sep 10 08:21:58 Porta-1 porta[61173]:   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 10 08:21:58 Porta-1 porta[61173]:   27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Sep 10 08:21:58 Porta-1 porta[61173]:   28: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::pollSep 10 08:21:58 Porta-1 porta[61173]:   29: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Sep 10 08:21:58 Porta-1 porta[61173]:   30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 10 08:21:58 Porta-1 porta[61173]:   31: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Sep 10 08:21:58 Porta-1 porta[61173]:   32: std::thread::local::LocalKey<T>::with
Sep 10 08:21:58 Porta-1 porta[61173]:   33: futures_executor::local_pool::block_on
Sep 10 08:21:58 Porta-1 porta[61173]:   34: tokio::runtime::task::core::Core<T,S>::poll
Sep 10 08:21:58 Porta-1 porta[61173]:   35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Sep 10 08:21:58 Porta-1 porta[61173]:   36: tokio::runtime::task::harness::Harness<T,S>::poll
Sep 10 08:21:58 Porta-1 porta[61173]:   37: tokio::runtime::blocking::pool::Inner::run
Sep 10 08:21:58 Porta-1 porta[61173]:   38: tokio::runtime::context::enter
Sep 10 08:21:58 Porta-1 porta[61173]:   39: std::sys_common::backtrace::__rust_begin_short_backtrace
Sep 10 08:21:58 Porta-1 porta[61173]:   40: core::ops::function::FnOnce::call_once{{vtable.shim}}
Sep 10 08:21:58 Porta-1 porta[61173]:   41: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Sep 10 08:21:58 Porta-1 porta[61173]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
Sep 10 08:21:58 Porta-1 porta[61173]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Sep 10 08:21:58 Porta-1 porta[61173]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
Sep 10 08:21:58 Porta-1 porta[61173]:       std::sys::unix::thread::Thread::new::thread_start
Sep 10 08:21:58 Porta-1 porta[61173]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
Sep 10 08:21:58 Porta-1 porta[61173]:   42: start_thread
Sep 10 08:21:58 Porta-1 porta[61173]:   43: clone
Sep 10 08:21:58 Porta-1 porta[61173]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/70ef0af/frame/executive/src/lib.rs:462
Sep 10 08:21:58 Porta-1 porta[61173]: This is a bug. Please report it at:
Sep 10 08:21:58 Porta-1 porta[61173]:         https://github.com/paritytech/substrate/issues/new
Sep 10 08:22:01 Porta-1 porta[61173]: 2021-09-10 08:22:01  [#416713] 🗳  Starting signed phase round 351.
Sep 10 08:22:02 Porta-1 porta[61173]: 2021-09-10 08:22:02  [#416754] 🗳  Starting unsigned phase(true).
![1](https://user-images.githubusercontent.com/76743883/132824008-0e7d7fe9-08a5-493c-9317-9f8cdfae89de.png)

**Comment by bkchr** [comment]
Which chain is that?

**Comment by bkchr** [comment]
You should post this issue to the repo of the chain you are running there.
