### ISSUE TITLE
Basic authorship pending txs limiter

### ISSUE THREAD

**Issue by akru** [paritytech/substrate#9758]
**Motivation**

According to this hack https://github.com/PureStake/substrate/commit/fdedb87add4f0215f9c0fd6c75ac817669dc486b

https://github.com/PureStake/substrate/blob/fdedb87add4f0215f9c0fd6c75ac817669dc486b/client/basic-authorship/src/basic_authorship.rs#L358-L366

Do you mind that block producer requires some limiter in pending transaction queue?

**Comment by crystalin** [comment]
I'm giving a bit more context.

What we observed was that some collators didn't include many tx in the block even having a full pool. The timing of the block production was under the 333ms allocated, and the weight was always < 30%.

We did some logging and observed that even if the pool ready queue contained 1000 items, only few were pushed to the block.
On top of that we discovered that the re-validation was triggered always during the block production (even if we changed the 200ms loop delay to 20s).

I suspected that somehow the revalidation impacted the pending tx iterator. So getting all the txs quickly before processing them would allow more tx in the block (and we confirmed that after doing that, we had stable and faster txs/block)

**Comment by bkchr** [comment]
> So getting all the txs quickly before processing them would allow more tx in the block (and we confirmed that after doing that, we had stable and faster txs/block)

I already had some testing branch to make the iterator more independent and not being influenced by a potential revalidation. However, I first need a proper benchmark to ensure that this really improves the situation.

**Comment by crystalin** [comment]
@bkchr So far, my only benchmark is to send 1000tx in the pool and see how many get into the block, with the bug, you will see inconsistent result: a block at 250, another one at 20, and ....
With the fix I did on our branch, it stays consistent (250, 243, 265...)

Here is my script (slightly modified):
```
// This script is expected to run against a parachain network (using launch.ts script)

import { Keyring } from "@polkadot/api";
import { SubmittableExtrinsic } from "@polkadot/api/promise/types";

import yargs from "yargs";

const argv = yargs(process.argv.slice(2))
  .usage("Usage: $0")
  .version("1.0.0")
  .options({
    url: {
      type: "string",
      description: "Websocket url",
      conflicts: ["network"],
      string: true,
    },
    from: {
      type: "string",
      description: "Private key to transfer from",
      demandOption: true,
    },
    count: {
      type: "number",
      default: 1000,
      description: "Number of transactions",
      demandOption: true,
    },
  }).argv;

const sendAllAndWaitLast = async (extrinsics: SubmittableExtrinsic[]) => {
    return new Promise(async (resolve, reject) => {
      console.log(`Preparing to send ${extrinsics.length} extrinsics`);
      for (let i = 0; i < extrinsics.length; i++) {
        if (i == extrinsics.length - 1) {
          const unsub = await extrinsics[i].send((result) => {
            if (result.isError) {
              reject(result.toHuman());
            }
            if (result.isInBlock) {
              console.log(`Last extrinsic submitted`);
              unsub();
              resolve(null);
            }
          });
        } else {
          await extrinsics[i].send();
        }
        if (i % 100 == 0) {
          console.log(`Sending extrinsic: ${i}...`);
        }
      }
      console.log(`Waiting for last extrinsic...`);
    });
  };

const main = async () => {
  const wsProvider = new WsProvider("wss://wss.moonriver.moonbeam.network");
  const polkadotApi = await ApiPromise.create({
    provider: wsProvider,
    typesBundle: typesBundle as any,
  });

  const keyring = new Keyring({ type: "ethereum" });
  const fromAccount = await keyring.addFromUri(argv.from);
  console.log(`Using funds from ${fromAccount.address}`);

  let fromNonce = (await polkadotApi.rpc.system.accountNextIndex(fromAccount.address)).toNumber();

  console.log(`Creating ${argv.count} balance tranfers of ${argv.count} Tokens...`);
  const transferTxs = await Promise.all(
    new Array(argv.count).fill(0).map((_, index) => {
      return polkadotApi.tx.system
        .remark("ok")
        .signAsync(fromAccount, { nonce: fromNonce + index });
    })
  );

  // Send the transfer transactions and wait for the last one to finish
  await sendAllAndWaitLast(transferTxs);

  await polkadotApi.disconnect();
  console.log(`Finished`);
};

main();
```

**Comment by bkchr** [comment]
Should be solved now.
