### ISSUE TITLE
Update ` .maintain/Dockerfile`

### ISSUE THREAD

**Issue by TriplEight** [paritytech/substrate#9765]
A follow-up from https://github.com/paritytech/substrate/pull/9753

> is it still used?

Yes, and it is critical to keep it.

> if yes, it should follow our containers policy and use ubuntu:20.04 as base

I see no issue with that. Do you want to include that in the PR? If not, please open an issue and I will take care of it.

> and have some metadata as the other images do

100%

_Originally posted by @chevdor in https://github.com/paritytech/substrate/issues/9753#issuecomment-917974659_

**Comment by chevdor** [comment]
- [ ] add metadata
- [x] use ubuntu:20.04 as base (was already done)
- [ ] add label `io.parity.image.type="builder"`
- [ ] remove labels not relevant to images not built via CI
- [ ] align the entrypoint with the `injected` image
- [ ] align the volumes with the `injected` image
- [ ] fix exposed ports

**Comment by chevdor** [comment]
See also https://github.com/paritytech/polkadot/pull/3884
