### ISSUE TITLE
Build of `v3.0.0` fails with `parity-db v0.2.2`

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate#9775]
Using this tag: https://github.com/paritytech/substrate/tree/v3.0.0
from a `cargo clean` build:
`cargo build --release` or `cargo build --release --locked` fails with:
```
error: failed to download `parity-db v0.2.2`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-db-0.2.2/Cargo.toml`

Caused by:
  failed to parse the version requirement `0.11	` for dependency `parking_lot`

Caused by:
  expected comma after minor version number, found '\t'
```
This is the last major release version, is a backport fix required to update dependencies for those that depend on this tag? Or any action needed at all?

**Comment by bkchr** [comment]
`cargo update -p parity-db` should do it.

**Comment by NukeManDan** [comment]
got ya - I figured that was the fix, should the release but updated minimally to get it building? I presume by closing this no, people may find this issue to solve themselves?

**Comment by bkchr** [comment]
Github search also works for closed issues.
