### ISSUE TITLE
feature request: Storage query of uniques classes by account

### ISSUE THREAD

**Issue by Yuripetusko** [paritytech/substrate#9777]
We are working on UI for minting uniques assets and noticed that there's no way to query Classes by account, only assets.  I can query all asset keys first by account, then query all classes from there and filter by those where issuer === accountId, but this won't work for Classes that have no assets (empty classes)

So I am wondering if it possible to add such storage query to substrate.

The reason why it's a problem. Imagine a UI/UX where you first create a collection (class) and then mint NFTs (assets) into this collection.

Imagine if user refreshes a page between signing class create tx and asset mint tx, so now there's no way to display all his previously created empty classes to select the one where to mint first asset into

**Comment by gavofyork** [comment]
Is it not possible to enumerate all `Classes` and filter those created by the user?

**Comment by Yuripetusko** [comment]
> Is it not possible to enumerate all `Classes` and filter those created by the user?

I am worried that query will be too heavy / slow once people start minting uniques actively
