### ISSUE TITLE
ws disconnected without error under heavy load (for the connection not overall)

### ISSUE THREAD

**Issue by ianhe8x** [paritytech/substrate#9811]
Versions: kusama v0.9.9-1

It is replicable on all public kusama endpoints listed in polkadot-apps. When running a subql indexing project, the ws connection was disconnected for every 1-2 mins. There're no errors in the node console only a new connection accepted (because jsapi reconnect attempts).

I launched a dedicated kusama node in onfinality to debug this issue, and it happened as well.

I exported jsonrpc logs. (DEBUG=api-ws), it showed in 1min since my app started, it sent 1034 jsonrpc requests.

```
grep -o "calling [^ ]*" ws.log| sort | uniq -c | sort -r

255 calling chain_getHeader
 252 calling chain_getBlockHash
 247 calling chain_getBlock
 244 calling state_getStorage
  10 calling state_getRuntimeVersion
   9 calling chain_getFinalizedHead
   4 calling system_health
   2 calling state_getMetadata
   1 calling system_properties
   1 calling system_chain
   1 calling state_unsubscribeStorage
   1 calling state_subscribeStorage
   1 calling state_subscribeRuntimeVersion
   1 calling state_queryStorageAt
   1 calling rpc_methods
```
[ws.log.tar.gz](https://github.com/paritytech/substrate/files/7189805/ws.log.tar.gz)

**Comment by bkchr** [comment]
Cc @dvdplm @niklasad1

**Comment by niklasad1** [comment]
It's really hard to debug this without logs from `jsonrpc server` but my hunch is that `max_payload_size` was exceeded and the `jsonrpc server` terminated the connection.

@ianhe8x is it possible to get the logs from the node that you connect somehow?

**Comment by ianhe8x** [comment]
Sure thing, @niklasad1 Can you advice the `-l` args to enable these logs?

**Comment by niklasad1** [comment]
> Sure thing, @niklasad1 Can you advice the -l args to enable these logs?

-l ="rpc=debug" should be sufficient

**Comment by ianhe8x** [comment]
Nothing useful, no error messages. After I excluded logs with `event.loop0 rpc: Response:` there wasn't much left.

**Comment by ianhe8x** [comment]
To reproduce the issue. 
```
git clone https://github.com/subquery/subql-starter
cd subql-starter
yarn
yarn codegen
yarn build
docker-compose pull
docker-compose up
```

Change project.yaml to use different endpoints.

**Comment by ianhe8x** [comment]
![image](https://user-images.githubusercontent.com/39037239/134116364-aa42c771-af10-4a65-b38a-eb27418155ce.png)

**Comment by niklasad1** [comment]
@ianhe8x 

Thanks, for the re-produce instructions why does the log above indicates that you connected `wss://rpc.polkadot.io`?

**Comment by ianhe8x** [comment]
I just demonstrate it's not related to a specific endpoint.

**Comment by alanchang124** [comment]
This problem occurs frequently in recent days. Especially when downloading a certain block containing a plenty of extrinsic.

**Comment by jamesbayly** [comment]
@niklasad1 we're still experiencing this issue. Is there any additional information that we can provide?

**Comment by niklasad1** [comment]
Sorry, the plan is to replace the current `jsonrpc servers` with `jsonrpsee` so I haven't really investigated this further and I suspect it has something with the recycling of buffers in the underlying websocket library `ws-rs`

Thus, I don't want to waste investigating/fixing this bug when we will stop using it in a month or two.

**Comment by niklasad1** [comment]
Meanwhile, we have a branch for [polkadot v0.9.16](https://github.com/paritytech/polkadot/tree/jsonrpsee-v0.9.16) that you can try if you want.

**Comment by niklasad1** [comment]
@ianhe8x 

The JSON-RPC servers has been replaced, can you please to re-run this again to see whether it's occurs?

**Comment by ianhe8x** [comment]
It's fixed. thanks.
