### ISSUE TITLE
Error: Service(Client(Backend("Invalid argument: Column families not opened: col11, col10, col9, col8, col7, col6, col5, col4, col3, col2, col1, col0")))

### ISSUE THREAD

**Issue by jasl** [paritytech/substrate#9836]
One of our (Khala Network) user report me a problem,
he gave a a snippet of log https://8n1.org/19610/1893

It shows, after a restart, the node shows

```
Error: Service(Client(Backend("Invalid argument: Column families not opened: col11, col10, col9, col8, col7, col6, col5, col4, col3, col2, col1, col0")))
```

then exit without panic.

**Comment by bkchr** [comment]
Maybe the db got corrupted?

**Comment by jasl** [comment]
> Maybe the db got corrupted?

Most probably, he said he restored db with backup then it work again

**Comment by bkchr** [comment]
Perfect.

**Comment by hauni97** [comment]
> 

I am getting the exact same error. After deleting and resyncing it solves the problem. However the same issue occurs a couple days later again. 

[miners_log.txt](https://github.com/paritytech/substrate/files/8694452/miners_log.txt)

What causes the db to get corrupted again?

**Comment by bkchr** [comment]
@hauni97 not sure that is really a Substrate issue. The issue from last year was also from Khala, so maybe the db isn't closed properly? 
How did you close the node? Was it killed?

**Comment by hauni97** [comment]
I found the error, the ssd drive is full, then the db gets corrupted.
