### ISSUE TITLE
Wrong value in Staking.Bonded event after Staking.Rebond extrinsic

### ISSUE THREAD

**Issue by TheGoldenEye** [paritytech/substrate#9840]
If Staking.Rebond extrinsic was executed with a value greater than the current / available balance, the resulting Staking.Bonded event should contain only the actual bonded value (currently it does not).
I see 2 solutions:
- the transaction fails due to insufficient balance
- the value ist interpreted as max_additional like in Staking.BondExtra extrinsic (here the Staking.Bonded event provides the actual bonded value)

Example 1 (Westend):
Stash 5D9x7E3f7VT2RqdpA54V8MJSh5xBr7pUV6bCDmGbpjZ9mi75 with balance of 178 WND
Staking.Rebond with 200 WND: https://westend.subscan.io/extrinsic/7435449-2

Example 2 (Kusama):
Stash DcAgRyM7BCEToY43W3WesEtPKWDBJ5RDDc5FEE38pbP25AD with balance of 2768 KSM 
Staking.Rebond with 27 million! KSM: https://kusama.subscan.io/extrinsic/9008712-3

**Comment by bkchr** [comment]
CC @kianenigma

**Comment by TheGoldenEye** [comment]
In which runtime it will be active?

**Comment by TheGoldenEye** [comment]
hmm, seams not
tested in westend with runtime 9111, old behavior
