### ISSUE TITLE
ERROR main parity_ws: Unable to listen on 127.0.0.1:9944 when another node is running

### ISSUE THREAD

**Issue by claudiociardelli** [paritytech/substrate#9868]
I starte a 2nd node on my  development machine where another node is already running and forgot to change she ws_port.
The 2nd instance refused to start (as it cannot use the port) and emitted the message.
ERROR main parity_ws: Unable to listen on 127.0.0.1:9944

That is good. But then did not exit gracefully but instead exited with a panick message as follows:

I was running the latest substrate-node template with the nightly rust build
==========================================================

2021-09-26 18:51:10.557 ERROR main parity_ws: Unable to listen on 127.0.0.1:9944

====================

Version: 3.0.0-monthly-2021-09+1-2e93d33-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: tokio::runtime::blocking::shutdown::Receiver::wait
   6: tokio::runtime::blocking::pool::BlockingPool::shutdown
   7: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
   8: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
   9: jsonrpc_ws_server::server::Server::start
  10: sc_rpc_server::inner::start_ws
  11: sc_service::start_rpc_servers::{{closure}}
  12: sc_service::start_rpc_servers
  13: sc_service::builder::spawn_tasks
  14: node_template::service::new_full
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: std::thread::local::LocalKey<T>::with
  17: tokio::park::thread::CachedParkThread::block_on
  18: tokio::runtime::thread_pool::ThreadPool::block_on
  19: tokio::runtime::Runtime::block_on
  20: sc_cli::runner::Runner<C>::run_node_until_exit
  21: node_template::command::run
  22: node_template::main
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: std::rt::lang_start::{{closure}}
  25: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/std/src/panicking.rs:403:40
      std::panicking::try
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/std/src/rt.rs:46:48
      std::panicking::try::do_call
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/std/src/panicking.rs:403:40
      std::panicking::try
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal
             at /rustc/addb4da686a97da46159f0123cb6cdc2ce3d7fdb/library/std/src/rt.rs:46:20
  26: main
  27: __libc_start_main
  28: _start

Thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/toto/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/shutdown.rs:51

**Comment by bkchr** [comment]
This is fixed in master. Wait for the next monthly release.
