### ISSUE TITLE
How to remove preimage from democracy pallet?

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#9880]
Anyone can pay a deposit to submit preimage of a proposal and never propose it. There is no way for the submitter to remove the preimage (and get deposit back) if it contains a mistake and therefore should not propose it.

**Comment by bkchr** [comment]
CC @shawntabrizi

**Comment by jacogr** [comment]
`reap_preimage`? https://github.com/paritytech/substrate/blob/master/frame/democracy/src/lib.rs#L1064-L1084

**Comment by xlc** [comment]
Tried and failed. https://karura.subscan.io/extrinsic/639704-2

> Remove an expired proposal preimage and collect the deposit.

**Comment by jacogr** [comment]
It says `TooEarly`, so it may just not yet be `VotingPeriod` blocks after the image was submitted.

**Comment by xlc** [comment]
Right. My bad. Should read the docs bit more closely.
