### ISSUE TITLE
sc_cli `key insert` gives wrong name to _gran_ key file created in local keystorage (BREAKS blocks finalization)

### ISSUE THREAD

**Issue by agryaznov** [paritytech/substrate#9888]
*(found while passing this [Tutorial](https://substrate.dev/docs/en/tutorials/start-a-private-network/))*

##  Summary
`key insert` gives a wrong name to file containing _gran_ (ed25519) key, which effectively leads to broken GRANDPA finalization in node

## Details
Performing the [`key insert` command](https://substrate.dev/docs/en/tutorials/start-a-private-network/customchain#option-3-use-the-key-command) operation with pre-generated Alice' key

```shell
# insert Alice's sr25519 aura key into storage
$ ./target/release/node-template key insert --base-path /tmp/node01 --chain local --key-type aura --suri "clip organ olive upper oak void inject side suit toilet stick narrow"

# insert Alice's ed25519 gran key into storage
$ ./target/release/node-template key insert --base-path /tmp/node01 --chain local --key-type gran --suri "clip organ olive upper oak void inject side suit toilet stick narrow"
```

leads to creating these two files :

```shell
$ find /tmp/node01/chains/local_testnet/keystore -type f -printf "%f\n"
617572619effc1668ca381c242885516ec9fa2b19c67b6684c02a8a3237b6862e5c8cd7e
6772616e9effc1668ca381c242885516ec9fa2b19c67b6684c02a8a3237b6862e5c8cd7e
```

one of which is possibly wrong-named, as in their names: 
 
+ `61757261` encodes _aura_ key type
+ `6772616e` encodes _gran_ key type

and the other `9effc1668ca381c242885516ec9fa2b19c67b6684c02a8a3237b6862e5c8cd7e` part derives from public key, which should be different for _aura_ (sr25519) and _gran_ (ed25519), but it turns out to be just the same for both

## how it (supposedly) should work 
if we just insert the same keys using JSON RPC (e.g. [with this script](https://github.com/paritytech/substrate-node-template/tree/tutorials/solutions/private-chain-v3/key-insert)), we get the _gran_ key file named properly (and nodes finalizing blocks successfully)

```shell
$ find /tmp/node01/chains/local_testnet/keystore -type f -printf "%f\n"
617572619effc1668ca381c242885516ec9fa2b19c67b6684c02a8a3237b6862e5c8cd7e
6772616eb48004c6e1625282313b07d1c9950935e86894a2e4f21fb1ffee9854d180c781
```

**Comment by agryaznov** [comment]
found in version:
```
[dependencies.sc-cli]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
tag = 'monthly-2021-09+1'
version = '0.10.0-dev'
```

**Comment by agryaznov** [comment]
Figured out that:

[InsertKeyCmd run()](https://github.com/paritytech/substrate/blob/master/client/cli/src/commands/insert_key.rs#L72) function just assumes the default `Sr25519` crypto scheme when no `--scheme` parameter set to `node-template key insert` command, **no matter which** `--key-type` was set.

But shouldn't it implicitly derive the `Ed25519` crypto scheme in case when `--key-type=gran` ?

**Comment by NukeManDan** [comment]
Thanks for the docs correction to specify scheme. I think this is OK to close, but possibly there should be a fix in the CLI's behavior to try and reason about if your key is correct or not. I will let the core team comment on that idea :pray:

**Comment by bkchr** [comment]
> But shouldn't it implicitly derive the `Ed25519` crypto scheme in case when `--key-type=gran` ?

It doesn't know this. 

However, with this: https://github.com/paritytech/substrate/pull/9909 the scheme will be required to be passed and not assumed anymore.
