### ISSUE TITLE
SRML: Seems to be impossible to add extra fields to a header

### ISSUE THREAD

**Issue by Vurich** [paritytech/substrate#991]
This was brought up with me by an attendee at Web3 Summit, but it doesn't seem to be possible to have a header with custom data at all. You can, of course, have a wrapper type that has the inbuilt header as a field and then whatever extra fields we want to add, but the issue is in `Header::new` in the `Header` trait. My suggestion would be to add a type parameter that represents "custom data", which for most headers can just be `()`. The usecase for the guy that I was talking to was sharding.

**Comment by ilblackdragon** [comment]
Yeah, I wanted to add few fields related to which shard this header belongs too and then manager that in the create block / acceptblock logic.

**Comment by gavofyork** [comment]
Currently that's done through specialising the `Log` datatype.
