### ISSUE TITLE
Implement core::fmt::Debug for BoundedVec

### ISSUE THREAD

**Issue by JayPavlina** [paritytech/substrate#9911]
`BoundedVec` does not currently implement `core::fmt::Debug`. It only implements `std::fmt::Debug`, as seen [here](https://github.com/paritytech/substrate/blob/c60ccc0719ea2036d3878b94bd9257c9332f5606/frame/support/src/storage/bounded_vec.rs#L204). This makes it difficult to use as a [Parameter](https://github.com/paritytech/substrate/blob/c60ccc0719ea2036d3878b94bd9257c9332f5606/frame/support/src/dispatch.rs#L66) for a pallet, because `core::fmt::Debug` is required.

**Comment by shawntabrizi** [comment]
@JayPavlina do you want to take this one?

**Comment by JayPavlina** [comment]
> @JayPavlina do you want to take this one?

Sure
