### ISSUE TITLE
Disable transaction ban for dev

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate#9921]
Currently bad transactions (e.g. when sender account does not have any balance to pay for fees) will get banned for 5 mins. This is necessary for production network but getting annoying for development network.

Should have a CLI flag to disable it or just disable it for dev mode by default.

**Comment by shunjizhan** [comment]
it's potentially useful to disable banning pools completely for dev. Not only bad transactions, but also recently mined tx gets blocked. This behavior blocks implementation of any state revert for dev.

For example, this common testing flow will fail
```
- tx1: deployDexContract()
- tx2: addLiquidity(10 dot)

- revert state to before tx1

- tx3: deployDexContract()            // error: tx temporarily banned (since it's the same as tx1)
- tx4: addLiquidity(20 ksm)
```
