### ISSUE TITLE
Duplicate code in core/test-runtime

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate#996]
The "wasm" subdirectory in https://github.com/paritytech/substrate/tree/master/core/test-runtime/wasm appears to contain duplicates of the files that are contained in the outer directory https://github.com/paritytech/substrate/tree/master/core/test-runtime

**Comment by bkchr** [comment]
We need a separate `Cargo.toml`, because `profile` is not configurable per target.
The `src` directory is already a symlink to the outer `src` directory.
As we can not change that much at the moment, I close this issue.
