### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AndreiAniukou** [paritytech/substrate#9991]
Oct 10 08:12:51 porta-node porta[49416]: This is a bug. Please report it at:
Oct 10 08:12:51 porta-node porta[49416]:         https://github.com/paritytech/substrate/issues/new
Oct 10 08:12:56 porta-node porta[49416]: 2021-10-10 08:12:56  [#1638970] 🗳  Starting signed phase round 1449.
Oct 10 08:12:57 porta-node porta[49416]: 2021-10-10 08:12:57  [#1639006] 🗳  Starting unsigned phase(true).
Oct 10 08:12:57 porta-node porta[49416]: 2021-10-10 08:12:57  [#1639007] 🗳  queued unsigned solution with score [44642857142857, 68587539439223683, 78808935020943708591566331251363]
Oct 10 08:12:57 porta-node porta[49416]: 2021-10-10 08:12:57  [#1639054] 🗳  Finalized election round with compute ElectionCompute::Unsigned.
Oct 10 08:12:57 porta-node porta[49416]: 2021-10-10 08:12:57  [1639054] 💸 new validator set of size 400 has been processed for era 1448
Oct 10 08:13:03 porta-node porta[49416]: Hash: given=4d946dafbd7ce0e5b8d2f3d345f68e316ad522fa19da113afe14415e49cb4938, expected=e18aee1ddb372e67197801c15eaf7c25febd090b80ed3a37961b28b452f68abe
Oct 10 08:13:03 porta-node porta[49416]: ====================
Oct 10 08:13:03 porta-node porta[49416]: Version: 2.0.0-417b63b-x86_64-linux-gnu
Oct 10 08:13:03 porta-node porta[49416]:    0: sp_panic_handler::set::{{closure}}
Oct 10 08:13:03 porta-node porta[49416]:    1: std::panicking::rust_panic_with_hook
Oct 10 08:13:03 porta-node porta[49416]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
Oct 10 08:13:03 porta-node porta[49416]:    2: std::panicking::begin_panic::{{closure}}
Oct 10 08:13:03 porta-node porta[49416]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Oct 10 08:13:03 porta-node porta[49416]:    4: std::panicking::begin_panic
Oct 10 08:13:03 porta-node porta[49416]:    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
Oct 10 08:13:03 porta-node porta[49416]:    6: tracing::span::Span::in_scope
Oct 10 08:13:03 porta-node porta[49416]:    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
Oct 10 08:13:03 porta-node porta[49416]:    8: <porta_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,u32>,porta_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<porta_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<porta_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<porta_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<porta_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<porta_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<porta_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<porta_runtime::Runtime>)>>>>::execute_block
Oct 10 08:13:03 porta-node porta[49416]:    9: std::panicking::try
Oct 10 08:13:03 porta-node porta[49416]:   10: sp_externalities::scope_limited::set_and_run_with_externalities
Oct 10 08:13:03 porta-node porta[49416]:   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Oct 10 08:13:03 porta-node porta[49416]:   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
Oct 10 08:13:03 porta-node porta[49416]:   13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Oct 10 08:13:03 porta-node porta[49416]:   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Oct 10 08:13:03 porta-node porta[49416]:   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Oct 10 08:13:03 porta-node porta[49416]:   16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Oct 10 08:13:03 porta-node porta[49416]:   17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Oct 10 08:13:03 porta-node porta[49416]:   18: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Oct 10 08:13:03 porta-node porta[49416]:   19: sp_api::Core::execute_block_with_context
Oct 10 08:13:03 porta-node porta[49416]:   20: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
Oct 10 08:13:03 porta-node porta[49416]:   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   28: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   29: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   31: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Oct 10 08:13:03 porta-node porta[49416]:   32: std::thread::local::LocalKey<T>::with
Oct 10 08:13:03 porta-node porta[49416]:   33: futures_executor::local_pool::block_on
Oct 10 08:13:03 porta-node porta[49416]:   34: tokio::runtime::task::core::Core<T,S>::poll
Oct 10 08:13:03 porta-node porta[49416]:   35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Oct 10 08:13:03 porta-node porta[49416]:   36: tokio::runtime::task::harness::Harness<T,S>::poll
Oct 10 08:13:03 porta-node porta[49416]:   37: tokio::runtime::blocking::pool::Inner::run
Oct 10 08:13:03 porta-node porta[49416]:   38: tokio::runtime::context::enter
Oct 10 08:13:03 porta-node porta[49416]:   39: std::sys_common::backtrace::__rust_begin_short_backtrace
Oct 10 08:13:03 porta-node porta[49416]:   40: core::ops::function::FnOnce::call_once{{vtable.shim}}
Oct 10 08:13:03 porta-node porta[49416]:   41: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Oct 10 08:13:03 porta-node porta[49416]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
Oct 10 08:13:03 porta-node porta[49416]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Oct 10 08:13:03 porta-node porta[49416]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
Oct 10 08:13:03 porta-node porta[49416]:       std::sys::unix::thread::Thread::new::thread_start
Oct 10 08:13:03 porta-node porta[49416]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
Oct 10 08:13:03 porta-node porta[49416]:   42: start_thread
Oct 10 08:13:03 porta-node porta[49416]:   43: clone
Oct 10 08:13:03 porta-node porta[49416]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/70ef0af/frame/executive/src/lib.rs:462
Oct 10 08:13:03 porta-node porta[49416]: This is a bug. Please report it at:
Oct 10 08:13:03 porta-node porta[49416]:         https://github.com/paritytech/substrate/issues/new
Oct 10 08:13:09 porta-node porta[49416]: Hash: given=22835888a307f4b0008c3c600749c58d1ff1421c85ac06f086be9e4a8eec02a9, expected=46d5969579c87cc960bc393befac952021f3f3a53470fe1dbd4277d4f7f4a8e5
Oct 10 08:13:09 porta-node porta[49416]: ====================
Oct 10 08:13:09 porta-node porta[49416]: Version: 2.0.0-417b63b-x86_64-linux-gnu
Oct 10 08:13:09 porta-node porta[49416]:    0: sp_panic_handler::set::{{closure}}
Oct 10 08:13:09 porta-node porta[49416]:    1: std::panicking::rust_panic_with_hook
Oct 10 08:13:09 porta-node porta[49416]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
Oct 10 08:13:09 porta-node porta[49416]:    2: std::panicking::begin_panic::{{closure}}
Oct 10 08:13:09 porta-node porta[49416]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Oct 10 08:13:09 porta-node porta[49416]:    4: std::panicking::begin_panic
Oct 10 08:13:09 porta-node porta[49416]:    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
Oct 10 08:13:09 porta-node porta[49416]:    6: tracing::span::Span::in_scope
Oct 10 08:13:09 porta-node porta[49416]:    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
Oct 10 08:13:09 porta-node porta[49416]:    8: <porta_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,u32>,porta_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<porta_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<porta_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<porta_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<porta_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<porta_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<porta_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<porta_runtime::Runtime>)>>>>::execute_block
Oct 10 08:13:09 porta-node porta[49416]:    9: std::panicking::try
Oct 10 08:13:09 porta-node porta[49416]:   10: sp_externalities::scope_limited::set_and_run_with_externalities
Oct 10 08:13:09 porta-node porta[49416]:   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
Oct 10 08:13:09 porta-node porta[49416]:   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
Oct 10 08:13:09 porta-node porta[49416]:   13: <sc_executor::native_executor::NativeExecutor<D> as sp_core::traits::CodeExecutor>::call
Oct 10 08:13:09 porta-node porta[49416]:   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
Oct 10 08:13:09 porta-node porta[49416]:   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
Oct 10 08:13:09 porta-node porta[49416]:   16: <sc_service::client::call_executor::LocalCallExecutor<B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
Oct 10 08:13:09 porta-node porta[49416]:   17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Oct 10 08:13:09 porta-node porta[49416]:   18: sp_api::runtime_decl_for_Core::execute_block_call_api_at
Oct 10 08:13:09 porta-node porta[49416]:   19: sp_api::Core::execute_block_with_context
Oct 10 08:13:09 porta-node porta[49416]:   20: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
Oct 10 08:13:09 porta-node porta[49416]:   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   27: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   28: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   29: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   31: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Oct 10 08:13:09 porta-node porta[49416]:   32: std::thread::local::LocalKey<T>::with
Oct 10 08:13:09 porta-node porta[49416]:   33: futures_executor::local_pool::block_on
Oct 10 08:13:09 porta-node porta[49416]:   34: tokio::runtime::task::core::Core<T,S>::poll
Oct 10 08:13:09 porta-node porta[49416]:   35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Oct 10 08:13:09 porta-node porta[49416]:   36: tokio::runtime::task::harness::Harness<T,S>::poll
Oct 10 08:13:09 porta-node porta[49416]:   37: tokio::runtime::blocking::pool::Inner::run
Oct 10 08:13:09 porta-node porta[49416]:   38: tokio::runtime::context::enter
Oct 10 08:13:09 porta-node porta[49416]:   39: std::sys_common::backtrace::__rust_begin_short_backtrace
Oct 10 08:13:09 porta-node porta[49416]:   40: core::ops::function::FnOnce::call_once{{vtable.shim}}
Oct 10 08:13:09 porta-node porta[49416]:   41: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Oct 10 08:13:09 porta-node porta[49416]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
Oct 10 08:13:09 porta-node porta[49416]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Oct 10 08:13:09 porta-node porta[49416]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1572:9
Oct 10 08:13:09 porta-node porta[49416]:       std::sys::unix::thread::Thread::new::thread_start
Oct 10 08:13:09 porta-node porta[49416]:              at rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys/unix/thread.rs:74:17
Oct 10 08:13:09 porta-node porta[49416]:   42: start_thread
Oct 10 08:13:09 porta-node porta[49416]:   43: clone
Oct 10 08:13:09 porta-node porta[49416]: Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/70ef0af/frame/executive/src/lib.rs:462
Oct 10 08:13:09 porta-node porta[49416]: This is a bug. Please report it at:
Oct 10 08:13:09 porta-node porta[49416]:         https://github.com/paritytech/substrate/issues/new

**Comment by bkchr** [comment]
You need to report this to the creator of this runtime/node.
